### ISSUE TITLE
How to re-write setting?

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#1002]
I notice when using `HSetting::Set($key, $module, $value)` it creates duplicate values, how do I get around this?

**Comment by luke-** [comment]
Can give an example?

This shouldn't happen...

**Comment by WASasquatch** [comment]
Uhh, well I deleted them but there was 20+ 'devMode' settings in the DB for the module 'devmode'.

Maybe it was a fluke as there is only 1 result now so far and I turned the feature on and off several times.
