### ISSUE TITLE
I can not loging with active directory

### ISSUE THREAD

**Issue by orelvis** [humhub/humhub#1011]
I have a problem.
humhub configure LDAP and users found me Status: Correct! (10 users), but can not start with any section of Directori active users.
I need help please.
thanks in advance

**Comment by orelvis** [comment]
which is the DN should I use for LDAP users synchronization with the group.
DN that were used in the authentication.
CN = "Administrator" CN = "Users" DC = "gnet" DC = "cu"

**Comment by luke-** [comment]
You can find example LDAP Settings here: https://community.humhub.com/u/luke/home

**Comment by jpcasas** [comment]
same here

**Comment by jpcasas** [comment]
ok it worked you just have to fill the field user filter. if you're using AD put (sAMAccountName=%s) and for other uid it will work
