### ISSUE TITLE
Installation Php Warning

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#1012]
![e29cd706-f24c-11e4-8fe4-c2d647a4f125](https://cloud.githubusercontent.com/assets/7725575/7454851/5f55658c-f280-11e4-9167-028cf1ae0ebd.PNG)

![0c8b9110-f24d-11e4-87db-f7677d547ef3](https://cloud.githubusercontent.com/assets/7725575/7454853/640a8d00-f280-11e4-969b-210869f2b267.PNG)

HumHub: 0.11.2

[04-May-2015 13:44:45 UTC] CDbException: CDbConnection.connectionString cannot be empty. (/home/xxxx/public_html/protected/vendors/yii/db/CDbConnection.php:370)
#0 /home/xxxx/public_html/protected/vendors/yii/db/CDbConnection.php(330): CDbConnection->open()
#1 /home/xxxx/public_html/protected/vendors/yii/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /home/xxxx/public_html/protected/vendors/yii/base/CModule.php(387): CDbConnection->init()
#3 /home/xxxx/public_html/protected/vendors/yii/logging/CDbLogRoute.php(109): CModule->getComponent('db')
#4 /home/xxxx/public_html/protected/vendors/yii/logging/CDbLogRoute.php(128): CDbLogRoute->getDbConnection()
#5 /home/xxxx/public_html/protected/vendors/yii/logging/CLogRoute.php(104): CDbLogRoute->processLogs(Array)
#6 /home/xxxx/public_html/protected/vendors/yii/logging/CLogRouter.php(123): CLogRoute->collectLogs(Object(CLogger), true)
#7 /home/xxxx/public_html/protected/vendors/yii/base/CComponent.php(561): CLogRouter->processLogs(Object(CEvent))
#8 /home/xxxx/public_html/protected/vendors/yii/base/CApplication.php(219): CComponent->raiseEvent('onEndRequest', Object(CEvent))
#9 /home/xxxx/public_html/protected/vendors/yii/base/CApplication.php(196): CApplication->onEndRequest(Object(CEvent))
#10 /home/xxxx/public_html/protected/vendors/yii/base/CApplication.php(828): CApplication->end(1)
#11 /home/xxxx/public_html/protected/vendors/yii/YiiBase.php(403): CApplication->handleError(2, 'include(/home/s...', '/home/xxxx/...', 403, Array)
#12 /home/xxxx/public_html/protected/vendors/yii/YiiBase.php(403): YiiBase::autoload()
#13 /home/xxxx/public_html/protected/vendors/yii/YiiBase.php(302): YiiBase::autoload('"CAssetManager"')
#14 /home/xxxx/public_html/protected/vendors/yii/YiiBase.php(196): YiiBase::import('"CAssetManager"', 'true')
#15 /home/xxxx/public_html/protected/vendors/yii/base/CModule.php(386): YiiBase::createComponent('array("class" =...')
#16 /home/xxxx/public_html/protected/vendors/yii/web/CWebApplication.php(193): CModule->getComponent('"assetManager"')
#17 /home/xxxx/public_html/protected/modules_core/installer/InstallerModule.php(36): CWebApplication->getAssetManager()
#18 /home/xxxx/public_html/protected/vendors/yii/base/CComponent.php(111): InstallerModule->getAssetsUrl()
#19 /home/xxxx/public_html/protected/vendors/yii/base/CModule.php(105): CComponent->__get('"assetsUrl"')
#20 /home/xxxx/public_html/protected/modules_core/installer/views/_layout.php(24): CModule->__get('"assetsUrl"')
#21 /home/xxxx/public_html/protected/vendors/yii/web/CBaseController.php(126): require('/home/xxxx/...')
#22 /home/xxxx/public_html/protected/vendors/yii/web/CBaseController.php(95): CBaseController->renderInternal('"/home/xxxx...', 'array("content"...', 'true')
#23 /home/xxxx/public_html/protected/vendors/yii/web/CController.php(784): CBaseController->renderFile('"/home/xxxx...', 'array("content"...', 'true')
#24 /home/xxxx/public_html/protected/modules_core/installer/controllers/IndexController.php(40): CController->render('"index"', 'array()')
#25 /home/xxxx/public_html/protected/vendors/yii/web/actions/CInlineAction.php(49): IndexController->actionIndex()
#26 /home/xxxx/public_html/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams('array("r" => "i...')
#27 /home/xxxx/public_html/protected/vendors/yii/web/CController.php(286): CController->runAction(Object(CInlineAction))
#28 /home/xxxx/public_html/protected/vendors/yii/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), 'array()')
#29 /home/xxxx/public_html/protected/vendors/yii/web/CWebApplication.php(282): CController->run('""')
#30 /home/xxxx/public_html/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('"installer/inde...')
#31 /home/xxxx/public_html/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest()
#32 /home/xxxx/public_html/index.php(42): CApplication->run()
#33 {main}
Previous error:
include(/home/xxxx/public_html/protected/vendors/yii/web/CAssetManager.php): failed to open stream: No such file or directory (/home/xxxx/public_html/protected/vendors/yii/YiiBase.php:403)
Stack trace:

**Comment by WASasquatch** [comment]
Sounds like your DB connection string is empty, for one.
