### ISSUE TITLE
Installation 0.11.2 Timeout

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#1013]
When installing the DB I keep getting a timeout 500 error

``` txt
2015/05/04 16:19:37 [error] 2576#0: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: ************, server: herbsy.cf, request: "GET /humhub/index.php?r=installer/setup/init HTTP/1.1", upstream: "http://63.141.253.146:8080/humhub/index.php?r=installer/setup/init", host: "herbsy.cf", referrer: "http://herbsy.cf/humhub/index.php?r=installer/setup/database"
```

The database did install correctly (from what I can see) after I went back to index and it restarted installer. I was able to start back from where it left off at site name.

**Comment by luke-** [comment]
Hmm, this seems related to the max execution time of your php scripts.
The installation takes a while until the whole database structure is created.
