### ISSUE TITLE
Error while trying to change some User Profile fields

### ISSUE THREAD

**Issue by g0dkar** [humhub/humhub#1017]
Hi!

I just learned about HumHub, installed it and it is AMAZING! Truly wonderful! The only problem I've had so far is that I can't change any of the default User Profile fields. I get this error whenever I try to change some info on the default User Profile fields.

I'm trying to hide some of them, and change the name of a few.

```
[From the "Admin -> Logging" page, formatted by me]
Trying to get property of non-object (/home/ubuntu/humhub-master/protected/modules_core/admin/controllers/UserprofileController.php:169)
Stack trace:
#0 /home/ubuntu/humhub-master/protected/vendors/yii/web/filters/CFilterChain.php(133): UserProfileController->runAction()
#1 /home/ubuntu/humhub-master/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run()
#2 /home/ubuntu/humhub-master/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter()
#3 /home/ubuntu/humhub-master/protected/vendors/yii/web/filters/CInlineFilter.php(58): UserProfileController->filterAccessControl()
#4 /home/ubuntu/humhub-master/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#5 /home/ubuntu/humhub-master/protected/vendors/yii/web/CController.php(291): CFilterChain->run()
#6 /home/ubuntu/humhub-master/protected/vendors/yii/web/CController.php(265): UserProfileController->runActionWithFilters()
#7 /home/ubuntu/humhub-master/protected/vendors/yii/web/CWebApplication.php(282): UserProfileController->run()
#8 /home/ubuntu/humhub-master/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController()
#9 /home/ubuntu/humhub-master/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest()
#10 /home/ubuntu/humhub-master/index.php(39): WebApplication->run()

REQUEST_URI=/admin/userprofile/editField/id/4 in /home/ubuntu/humhub-master/protected/modules_core/admin/controllers/UserprofileController.php (169) in /home/ubuntu/humhub-master/index.php (39)
```

I wish I could help more, but since I just started using it (and I'm really rusty on PHP) I'm afraid I can't =/

**Comment by barkatwhat** [comment]
What's the current status of this bug being fixed?

**Comment by WASasquatch** [comment]
The pull request should be reverted by HumHub developers since it appears the pull author has abandoned it. 

@luke-
@andystrobel

**Comment by esemve** [comment]
Hotfix (but i'm not a HumHub developer):


*** UserProfileController (line ~171): ***

        if ($form->submitted('save') && $form->validate()) {

            $this->forcePostRequest();

            // Use ProfileField Instance from Form with new Values
            $field = $form['ProfileField']->model;
            $fieldType = $form[$field->field_type_class]->model;
            $fieldType->setProfileField($field);

            $field->save();
            $fieldType->save();

            $this->redirect(Yii::app()->createUrl('//admin/userprofile'));
        }


*** ProfileFieldType.php ****


    /**
     * Returns an array of instances of all available field types.
     *
     * @return Array
     */
    public function getTypeInstances($profileField = null) {

        $types = array();
        foreach ($this->getFieldTypes() as $className => $title) {

            if (Helpers::CheckClassType($className, 'ProfileFieldType')) {
                $instance = new $className;
                if ($profileField != null) {
                    $instance->profileField = $profileField;


                    // Seems current type, so try load data
                    if ($profileField->field_type_class == $className) {
                        $instance->load();
                    }
                }
                $types[] = $instance;
            }
        }
        return $types;
    }

**Comment by rbraband** [comment]
Thank you esemve for the Fix!

**Comment by acubaniti** [comment]
Worked, great work!
