### ISSUE TITLE
The system is unable to find the requested action "GetFrontEndInfo"

### ISSUE THREAD

**Issue by Vatarus** [humhub/humhub#1019]
Hi!

Tell me, what is the problem and how to fix it?

![issue2](https://cloud.githubusercontent.com/assets/3394915/7465255/e41d02c0-f307-11e4-99dc-f7e9c216469b.png)

**Comment by luke-** [comment]
We removed this action from 0.11.2

Please check if you themed on of these views:
https://github.com/humhub/humhub/commit/55117843424105e495115d616a7da8f449b7445a
https://github.com/humhub/humhub/commit/49f998e1482e37a59800f48cb7239f968c911b6a

**Comment by Vatarus** [comment]
Thanks!
