### ISSUE TITLE
Hourly Cronjob fails

### ISSUE THREAD

**Issue by peterling** [humhub/humhub#1021]
Apparently since update to Version 0.11.2 my hourly Cronjob isn't working anymore.
It ran fine before the update. The daily Cronjob still runs fine.
It's running on Windows Server 2012 R2, the call is:
"C:\[PATH TO PHP]\php.exe C:\[PATH TO HUMHUB]\protected\yiic.php cron hourly"
The console output:
```
                     HumHub Console Interface - Version 1

--------------------------------------------------------------------------------

Cron Interface
--------------------------------------------------------------------------------



- Optimizing Search Index
- Updating LDAP Users

Fatal error: Call to a member function search() on a non-object in C:\[PATH TO HUMHUB]\protected\libs\HLdap.php on line 116

```

Any suggestions what I could try ?

Best Regards
Peter

**Comment by luke-** [comment]
Can you check your LDAP Settings at Administration -> LDAP?

**Comment by peterling** [comment]
Thanks for your reply,

indeed, it seems to be related to LDAP, not the update.
When I deactivate LDAP support, the Cron Job runs fine.
LDAP user support is also working so I don't know where something is wrong. I will try different settings.

Best Regards
Peter
