### ISSUE TITLE
Different Menus (Top Level Navigation) for Different User Groups

### ISSUE THREAD

**Issue by g0dkar** [humhub/humhub#1023]
Is there a way to show different menus to different user groups? I'm trying to show/hide some custom navigation items I've created so I can show the most useful items for each group. Like if you're in the "Frontend" group we'd show some Design resources in the top level navigation (Smashing Magazine, for example) but if you're from "Development" we'd hide those links and show you some dev stuff (StackOverflow, for example).

I've been trying to find how to do that but it doesn't seem possible right now.

**Comment by WASasquatch** [comment]
Take a look at https://github.com/humhub/humhub/blob/master/protected/widgets/TopMenuWidget.php

You can provide logic in the init() function to check for group, and then render a new view

**Comment by g0dkar** [comment]
Hmm! Nice! Thanks =D

I'll hit the docs later today to get started and learn how to get the user group and all that :)
