### ISSUE TITLE
Notifications Mail sends Deutsch Mail randomly

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#1024]
At random points, the Mail system will decide to use Deutsch language for sending emails on HumHub Community

<img src="http://i.imgur.com/CL44MUU.png" />

**Comment by Ardnived** [comment]
I'm having the same issue, but I think I know what the cause it. It seems to send the email in whatever the language preference of the sender is, regardless of the receiver's language preference.

Notifications that I get from an Italian (who has set his language preference to Italian) are in Italian.
![screen shot 2016-02-13 at 9 08 39 am](https://cloud.githubusercontent.com/assets/1362167/13028903/c8b41c80-d231-11e5-9738-aa27ea5f5fc8.png)

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-mail/issues/79
