### ISSUE TITLE
Notifications Module

### ISSUE THREAD

**Issue by sdaghfous** [humhub/humhub#1026]
Hi, 

I have a problem 
when I click to view notifications, it takes a long time to load without doing anything !!

![error satecbook](https://cloud.githubusercontent.com/assets/11873548/7511681/b03245d6-f49e-11e4-905e-234587f465e0.png)

thank you for your help

**Comment by luke-** [comment]
Can you please check your Server Error Log for more error details?

**Comment by sdaghfous** [comment]
thanks for your reply.

There is no details in the Server Log.
FYI : i use apache Server.

**Comment by ToonSoft** [comment]
Well, I have the same problem,and this is the error log.

json_encode(): Invalid UTF-8 sequence in argument (/var/www/protected/vendors/yii/web/helpers/CJSON.php:116) Stack trace: #0 unknown(0): nameValue() #1 /var/www/protected/vendors/yii/web/helpers/CJSON.php(246): array_map() #2 /var/www/protected/modules_core/notification/controllers/ListController.php(79): encode() #3 /var/www/protected/vendors/yii/web/actions/CInlineAction.php(49): ListController->actionIndex() #4 /var/www/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #5 /var/www/protected/vendors/yii/web/filters/CFilterChain.php(133): ListController->runAction() #6 /var/www/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #7 /var/www/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #8 /var/www/protected/vendors/yii/web/filters/CInlineFilter.php(58): ListController->filterAccessControl() #9 /var/www/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #10 /var/www/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #11 /var/www/protected/vendors/yii/web/CController.php(265): ListController->runActionWithFilters() #12 /var/www/protected/vendors/yii/web/CWebApplication.php(282): ListController->run() #13 /var/www/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #14 /var/www/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #15 /var/www/index.php(39): WebApplication->run() REQUEST_URI=/index.php?r=notification/list/index&from=0&ajax=1&CSRF_TOKEN=ab396d43cbe26c495562ea16509896e2cd62fe09&_=1432465056660 in /var/www/protected/modules_core/notification/controllers/ListController.php (79) in /var/www/index.php (39)

**Comment by sdaghfous** [comment]
Hello, 

I removed the admin user and i created another, no longer problemes appears !
