### ISSUE TITLE
Allowed file extensions issue

### ISSUE THREAD

**Issue by Vatarus** [humhub/humhub#1029]
__You can not add more than one file extension.__

![file_settings_ext](https://cloud.githubusercontent.com/assets/3394915/7532713/1c972640-f5a5-11e4-8720-fc2ae5493029.png)

**Comment by jonathandey** [comment]
You need to remove the space between the comma and second extension.

Example:
`jpg,doc`

**Comment by Vatarus** [comment]
Thanks. it works.
