### ISSUE TITLE
Relational Profile field drop-down type

### ISSUE THREAD

**Issue by hubrajesh** [humhub/humhub#1030]
Is there any proper way to use relational data to fill drop-down field type in current profile structure ? 
Like filling *country* profile field with a database table instead of using string input by user. 
I needed few profile fields like that so stopped using default get HForm model with definition and created my own custom form view. There was no need to allow admin to manage profile fields in my case so I decided to just create my custom form.
Just wanted to know if there is a way to keep using default instead of creating custom form.

**Comment by WASasquatch** [comment]
You can add this functionality easy enough. I'll provide some *simple* directions when I'm home.

**Comment by luke-** [comment]
Since 0.11.2 it's possible to create own profile field types by module

https://community.humhub.com/s/a620fd6b-425b-4591-b0d4-47d22f2f8edd/wiki/page/view/title/Custom+Profile+Field+Types

**Comment by hubrajesh** [comment]
Thanks 
I am using older version so I think custom form is only option for me.
Will update related files manually and try this trick.

**Comment by WASasquatch** [comment]
Seems incomplete. What about column types, comparatives, and the like?
