### ISSUE TITLE
failed to open stream: Too many open files in /[...]/humhub-master/protected/vendors/yii/YiiBase.php on line 403

### ISSUE THREAD

**Issue by mac-e-mac** [humhub/humhub#1033]
Hello,

after a couple of logins, which worked well, login in today led to a white screen.
URL stayed at http://mydomain.net/index.php?r=user/auth/login

This happened first while I was creating Spaces. Is there any cache that has to be deleted somewhere?

Thanks.

**Comment by mac-e-mac** [comment]
Found the Error Log:

11.05.2015 23:29:09 mydomain.net [client 93.231.63.0] PHP Warning:  include(/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/vendors/yii/base/CErrorEvent.php): failed to open stream: Too many open files in /mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/vendors/yii/YiiBase.php on line 403, referer: http://mydomain.net/index.php?r=user/auth/login
11.05.2015 23:29:09 mydomain.net [client 93.231.63.0] , referer: http://mydomain.net/index.php?r=user/auth/login
11.05.2015 23:29:09 mydomain.net [client 93.231.63.0] PHP Warning:  include(): Failed opening '/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/vendors/yii/base/CErrorEvent.php' for inclusion (include_path='.:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/vendors:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/modules_core/wall/notifications:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/modules_core/wall/widgets:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/modules_core/wall/models:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/modules_core/wall:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/modules_core/user:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/modules_core/user/forms:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/modules_core/user/notifications:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/modules_core/user/widgets:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/modules_core/user/models:/mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/modules_core/user/componen in /mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/vendors/yii/YiiBase.php on line 403, referer: http://mydomain.net/index.php?r=user/auth/login
11.05.2015 23:29:09 mydomain.net [client 93.231.63.0] 2 messages repeated, referer: http://mydomain.net/index.php?r=user/auth/login
11.05.2015 23:29:09 mydomain.net [client 93.231.63.0] PHP Fatal error:  Class 'CErrorEvent' not found in /mnt/webr/c0/29/54594829/htdocs/humhub-master/protected/vendors/yii/base/CApplication.php on line 810, referer: http://mydomain.net/index.php?r=user/auth/login

**Comment by mac-e-mac** [comment]
Hoster (Strato) answered that 
"Too many open files"
is the problem and that they can't solve it :(
Files where "opened by" Humhub but they are not really sure, what happened.

Anything I can do?

**Comment by WASasquatch** [comment]
This is a limitation of your host. HumHub is a framework with hundreds of fetched files included into one system.
