### ISSUE TITLE
Updating from 0.10.1 to 0.11.0-1: Error/Warning

### ISSUE THREAD

**Issue by kazuuu** [humhub/humhub#1034]
Hello!

I hope some one could help me.

I was running humhub version 0.10.0-rc.1 and i decided to update to the most recent version.

I did it from 0.10.0rc.1 to 0.10.0, then to 0.10.1... Everything without any issue.

But while updating from 0.10.1 to 0.11.0-1 i got lot of warnings (maybe its errors, i don't know). Those warnings happens when i execute:  $ php protected/yiic update

If i try to execute 'php protected/yiic update' again it execute ok...

Is there any problem if i just ignore it? and keep updateint til 11.2?

Thx!
Marcello M

********* First time running: php protected/yiic update **********

                     HumHub Console Interface - Version 1

--------------------------------------------------------------------------------
Updater
--------------------------------------------------------------------------------

*** Begin Migrations ***

Flushing Caches....
Autodetecting Modules....

Yii Migration Tool v1.0 (based on Yii v1.1.15)

extended with EMigrateCommand by cebe <mail@cebe.cc>

Active database component (connectionString):
    mysql:host=localhost;dbname=social

Total 5 new migrations to be applied:
    notification: m150204_103433_html5_notified
    user: m150210_190006_user_invite_lang
    user: m150302_114347_add_visibility
    wall: m150322_194403_remove_type_field
    file: m150322_195619_allowedExt2Text

Apply the above migrations? (yes|no) [no]:yes
*** applying m150204_103433_html5_notified
    > insert into setting ... done (time: 0.002s)
    > add column desktop_notified tinyint(1) DEFAULT 0 to table notification ... done (time: 0.010s)
    > update notification ... done (time: 0.002s)
*** applied m150204_103433_html5_notified (time: 0.017s)

*** applying m150210_190006_user_invite_lang
    > add column language varchar(10) DEFAULT NULL to table user_invite ... done (time: 0.005s)
*** applied m150210_190006_user_invite_lang (time: 0.007s)

*** applying m150302_114347_add_visibility
    > add column visibility INT(1) DEFAULT 1 to table user ... done (time: 0.060s)
*** applied m150302_114347_add_visibility (time: 0.063s)

*** applying m150322_194403_remove_type_field
    > drop column type from table wall ... done (time: 0.017s)
*** applied m150322_194403_remove_type_field (time: 0.019s)

*** applying m150322_195619_allowedExt2Text
PHP Error[2]: call_user_func() expects parameter 1 to be a valid callback, class 'ActivityModule' does not have a method 'onActiveRecordDelete'
    in file /var/www/public/protected/vendors/yii/base/CComponent.php at line 559
#0 /var/www/public/protected/vendors/yii/base/CComponent.php(559): call_user_func()
#1 /var/www/public/protected/vendors/yii/db/ar/CActiveRecord.php(859): HSetting->raiseEvent()
#2 /var/www/public/protected/vendors/yii/db/ar/CActiveRecord.php(973): HSetting->onBeforeDelete()
#3 /var/www/public/protected/vendors/yii/db/ar/CActiveRecord.php(1220): HSetting->beforeDelete()
#4 /var/www/public/protected/models/HSetting.php(186): HSetting->delete()
#5 /var/www/public/protected/modules_core/file/migrations/m150322_195619_allowedExt2Text.php(10): Set()
#6 /var/www/public/protected/vendors/yii/cli/commands/MigrateCommand.php(385): m150322_195619_allowedExt2Text->up()
#7 /var/www/public/protected/extensions/migrate-command/EMigrateCommand.php(467): ZMigrateCommand->migrateUp()
#8 /var/www/public/protected/vendors/yii/cli/commands/MigrateCommand.php(109): ZMigrateCommand->migrateUp()
#9 /var/www/public/protected/extensions/migrate-command/EMigrateCommand.php(266): ZMigrateCommand->actionUp()
#10 unknown(0): ZMigrateCommand->actionUp()
#11 /var/www/public/protected/vendors/yii/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs()
#12 /var/www/public/protected/commands/shell/ZMigrateCommand.php(127): ZMigrateCommand->run()
#13 /var/www/public/protected/vendors/yii/console/CConsoleCommandRunner.php(71): ZMigrateCommand->run()
#14 /var/www/public/protected/commands/shell/HUpdateCommand.php(92): CConsoleCommandRunner->run()
#15 /var/www/public/protected/commands/shell/HUpdateCommand.php(59): HUpdateCommand->runMigrations()
#16 unknown(0): HUpdateCommand->actionIndex()
#17 /var/www/public/protected/vendors/yii/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs()
#18 /var/www/public/protected/vendors/yii/console/CConsoleCommandRunner.php(71): HUpdateCommand->run()
#19 /var/www/public/protected/vendors/yii/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#20 /var/www/public/protected/vendors/yii/base/CApplication.php(180): HConsoleApplication->processRequest()
#21 /var/www/public/protected/yiic.php(26): HConsoleApplication->run()
#22 /var/www/public/protected/yiic(5): require_once()

************** Second time: php protected/yiic update *************

   HumHub Console Interface - Version 1

--------------------------------------------------------------------------------
Updater
--------------------------------------------------------------------------------

*** Begin Migrations ***

Flushing Caches....
Autodetecting Modules....

Yii Migration Tool v1.0 (based on Yii v1.1.15)

extended with EMigrateCommand by cebe <mail@cebe.cc>

Active database component (connectionString):
    mysql:host=localhost;dbname=7comm_social

Total 1 new migration to be applied:
    file: m150322_195619_allowedExt2Text

Apply the above migration? (yes|no) [no]:yes
*** applying m150322_195619_allowedExt2Text
*** applied m150322_195619_allowedExt2Text (time: 0.157s)

Migrated up successfully.

--------------------------------------------------------------------------------

*** Checking Modules ***

--------------------------------------------------------------------------------
Finished succesfully without errors!
--------------------------------------------------------------------------------

Screenshot while trying to update through Humhub Updater Beta Module:
![humhub-update-error](https://cloud.githubusercontent.com/assets/1808828/7556161/012d88c0-f73c-11e4-84c5-7ad95d9b70dd.jpg)

**Comment by druckpiloten** [comment]
Same here :( unfortunately, when new users wants to registrate to humhub, they got also a php warning and can not login afterwards.

**Comment by druckpiloten** [comment]
![bildschirmfoto 2015-05-12 um 17 59 35](https://cloud.githubusercontent.com/assets/12370165/7591899/b04cdffa-f8d0-11e4-87b4-5d70b2f32867.png)
