### ISSUE TITLE
Still 500's Across Board

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#1035]
So, I till get 500 Server Errors when enabling/disabling, downloading, or using HumHub update, or using the About Humhub page? What are these about. They are random, sometimes it works, sometimes it fails. Currently i cannot access the Update Humhub module at all. System doesn't produce any errors at all like the error kills the server that bad.

I think you need to figure out a alternative method for updating. Like Socks/Ftp instead of secure connections which are never used for updating in systems. Look at linux/windows. Open connections to deb/update, no SSL.

<img src="http://i.imgur.com/ndqt4Yc.png" /> 
<img src="http://i.imgur.com/DKsCN38.png" />

**Comment by mrluisiko99** [comment]
I have the same error. I am using Debian and SSL. All is up-to-date.
