### ISSUE TITLE
Caching with No Caching

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#1039]
So what is up with HumHub? It is the most frustrating software to develop for that I have ever worked on.

I can simply erase files and HumHub will still render the information like the file was never altered.

Target links don't work in my module.

I cannot edit my widgets right now because the system is somehow caching code without caching being enabled or any cache files available!!!! Why do I have to install a new HumHub installation just to work on a widget so things don't get cached randomly **_(until I develop for awhile and have to install ANOTHER HumHub installation)**_

<img src="http://i.imgur.com/sieUZ8w.jpg" />

and cache settings

<img src="http://i.imgur.com/NtLR4ZX.png" />

And the code

``` php
<?php
/**
* CustomStackSidebarWidget
*
*/
class CustomStackWidget extends HWidget {

    public $id;
    public $title;
    public $content;
    public $icon;
    public $visibility;
    public $notemplate;
    public $targets;

    public function __construct() {
        if (!isset($this->id)) {
            $this->id = '';
        }
        if (!isset($this->icon)) {
            $this->icon = '';
        }
        if (!isset($this->targets)) {
            $this->targets = false;
        }
        if (!isset($this->notemplate)) {
            $this->notemplate = 0;
        }
        if (isset(Yii::app()->request->getParam('sguid'))) {
            die('Hello ' . Yii::app()->request->getParam('sguid'));
        }
        return parent::__construct();
    }

    public function run() {

        if(Yii::app()->user->isGuest && $this->visibility == CustomPage::VISIBILITY_MEMBER) {
            continue;
        }

        // RENDER NOTHING!!!!!!!!!!!

    }   

}

?>
```

What the hell, guys?

**Comment by luke-** [comment]
There is definitively no other caching. Maybe you're using some additional caching extensions for PHP?
