### ISSUE TITLE
New users not found in mentioning auto-completion

### ISSUE THREAD

**Issue by hugochinchilla** [humhub/humhub#1042]
I recently installed HumHub and doing some tests with it I noticed some users will not appear on the completion box used to mention people.

I have noticed too that it will start working from the moment I enter as admin and open the edit form for that user and then save it without modifying it, then it works and the user can be auto-completed.

**Comment by luke-** [comment]
Couldn't reproduce that. Can you please provide more infos like
- HumHub Version
- Configuration e.g. LDAP / User Approval / ...
