### ISSUE TITLE
migrate to single page app to increase performance by a factor of at least 1000%

### ISSUE THREAD

**Issue by robertleeplummerjr** [humhub/humhub#1043]
I am a performance specialist.  If there isn't any immediate interest in this, I may do this myself.  The project this will marry along side is: https://github.com/Enpowi/Enpowi , which does use single page and vue.js for template and crossroads.js for routing.  It is wicked fast, it would be awesome to see it implemented in humhub.  Could we by chance meet and create a strategy moving forward?

**Comment by jus61** [comment]
Excuse me but what causes this script exactly

**Comment by robertleeplummerjr** [comment]
A single page app reduces the amount of data sent from server to client, which makes the overall app faster.  Facebook and Google have been using these for some time.  I built Enpowi because I had not yet seen a CMS that took advantage of these concepts.  It would be nice if HumHub took advantage of these api's as it would mean a faster overall social experience.

**Comment by jus61** [comment]
how can I implement this on my page Humhub

**Comment by WASasquatch** [comment]
AJAX is a tool, and never to be used as the overall carrier of a whole system. This is not a standard and would create incompatibilities. Facebook uses AJAX to load feeds, the same as HumHub. And standard pages for the rest, you can even see the name of the files such as "story.php" and "attachment.php" etc. 

It's standard, that you use AJAX as a tool, and never depend on it. Same for JS inherently. While most websites have moved out of the realm of fallback static pages, they still follow the standard that AJAX and JS are a tool, and not a means of building a website.

**Comment by robertleeplummerjr** [comment]
Quite honestly, it would probably mean using Enpowi as the api rather than
Yii.  Yii does seem mature, and is a fabulous platform, but the single page
app method changes the whole paradigm of the programming model.  With
Enpowi we use extremely simple html pages that use vue.js as a template
engine rather than using smarty, for example.  Too, because it is a single
page app, you are not constantly loading new css and javascript every time
a page loads, so it cuts down on the need to minify the javascript and
css.  There are no inter-mixing php + html throughout a page, you simply
deliver json to the client, and have the client sort out how to display
it.  A sample of this type of architecture can be found here:
https://github.com/Enpowi/Enpowi/blob/master/modules/blog/edit.php

This is a blog edit page.  Notice it is 44 lines of readable html/php.  I
guess in short it would be very interesting to see HumHub use some type of
single page architecure, as it increases performance through the entire
site as a whole.  Also, notice too we use crossroads.js, which takes
advantage of the hash on the client.

On Fri, May 22, 2015 at 10:03 AM, jus61 <notifications@github.com> wrote:

> how can I implement this on my page Humhub
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/1043#issuecomment-104667965>.
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
Jordan, Gmail + Google disagrees.

On Fri, May 22, 2015 at 1:55 PM, Jordan Thompson <notifications@github.com>
wrote:

> AJAX is a tool, and never to be used as the overall carrier of a whole
> system. This is not a standard and would create incompatibilities. Facebook
> uses AJAX to load feeds, the same as HumHub. And standard pages for the
> rest, you can even see the name of the files such as "story.php" and
> "attachment.php" etc.
>
> It's standard, that you use AJAX as a tool, and never depend on it. Same
> for JS inherently. While most websites have moved out of the realm of
> fallback static pages, they still follow the standard that AJAX and JS are
> a tool, and not a means of building a website.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/1043#issuecomment-104728830>.
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
Jordan: http://en.wikipedia.org/wiki/Single-page_application
Quote: "The most prominent technique currently being used is Ajax
<http://en.wikipedia.org/wiki/Ajax_%28programming%29>.[1]
<http://en.wikipedia.org/wiki/Single-page_application#cite_note-Flanagan2006-1>
Predominantly using the XMLHttpRequest
<http://en.wikipedia.org/wiki/XMLHttpRequest> object from JavaScript, other
AJAX approaches include using IFRAME or script HTML elements. Popular
libraries like jQuery <http://en.wikipedia.org/wiki/JQuery>, that normalize
AJAX behavior across browsers from different manufacturers, have further
popularized the AJAX technique."

On Fri, May 22, 2015 at 1:56 PM, Robert Plummer <
robertleeplummerjr@gmail.com> wrote:

> Jordan, Gmail + Google disagrees.
>
> On Fri, May 22, 2015 at 1:55 PM, Jordan Thompson <notifications@github.com
> > wrote:
>
>> AJAX is a tool, and never to be used as the overall carrier of a whole
>> system. This is not a standard and would create incompatibilities. Facebook
>> uses AJAX to load feeds, the same as HumHub. And standard pages for the
>> rest, you can even see the name of the files such as "story.php" and
>> "attachment.php" etc.
>>
>> It's standard, that you use AJAX as a tool, and never depend on it. Same
>> for JS inherently. While most websites have moved out of the realm of
>> fallback static pages, they still follow the standard that AJAX and JS are
>> a tool, and not a means of building a website.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/humhub/humhub/issues/1043#issuecomment-104728830>.
>>
>
>
>
> --
> Robert Plummer
>



-- 
Robert Plummer

**Comment by WASasquatch** [comment]
Google does not follow standards, at all, hens the collective waste-land of failed applications and projects. A lot of stuff gets too bashed by standard developers and they remove it. Like Google Code, followed no standards in cooperative/collaborative development, and people might as well download a git script for their own server.

**Comment by WASasquatch** [comment]
Gmail also has it's static backside, because they are aware of standards.

**Comment by robertleeplummerjr** [comment]
Lets try and keep this thread productive.  There is little to gain by bringing up a platform that has been antiquated since September 30, 2013.  The primary reason for bringing this up is SPAs are more performant.

Breakthrough: What I ended up doing to bring HumHub into Enpowi as a single page app is simply turn off majority of items handled directly by HumHub in it's landing page including much of the javascript and css, which are loaded from Enpowi.  Those items like notices I'll simply have running on Enpowi.

**Comment by WASasquatch** [comment]
The anecdotal is very relevant to the point you are missing. 

Your system has no fall-back system like Facebook, and other pages that "utilize" one-page technology. Again that "utilize" as it's a tool. Not a method of building a site. 

You have a create idea going on but currently it is just new tech with nothing to fall back on for multiple platforms. 

Facebook has a static system, as well as every other one-page system. Try their mobile/limited view version for web tv. There is no AJAX.

**Comment by rondonjon** [comment]
@robertleeplummerjr IMO you're prematurely narrowing down the discussion of whether or not to use single-page apps to a selection of frameworks for single-page apps. Although they could certainly serve as examples in the general discussion, a (possible) choice should be made later.

**Comment by rondonjon** [comment]
@WASasquatch 

> You have a great idea going on but currently *it is just new tech with nothing to fall back on* for multiple platforms.

I would like to contradict in two points:

1. AJAX (or the XMLHttpRequest, which I'm so free as to consider synonymous here) is a technology of the late **1990**'s. It was introduced in IE5 (for those that still remember it). I am not even questioning browsers that still doesn't support it or users that don't want it, may they live happily ever after. But I  would very sharply advise against letting such technology denial put a burden on the other (more or less) 99%.
1. Applications have minimum requirements. They always had. That's one reason why people keep upgrading their systems. And if something is considered as minimum, that means that there is no fallback solution for your system, and that's OK and widely accepted.

**Comment by rondonjon** [comment]
@robertleeplummerjr 

> A single page app reduces the amount of data sent from server to client, which makes the overall app faster.

Actually / IMO, the primary benefit is not *less* data transfer, but *less obtrusive* data transfer.

I believe that traffic may even increase in many apps once they're converted to SPA because they become more responsive and more asynchronous, but many of these features require more data than a static page (think of search suggestions, progressive image loading with multiple sizes etc. etc.)

But I support your idea 100%.

I have been evaluating HumHub for a few hours now, and, given that it is still a very new platform, I am a bit disappointed that the developers have apparently chosen the architecture of *yesterday's* web applications for a platform that wants to host *tomorrow's* social networks.

Having migrated a few websites from MPA to SPA myself, I doubt that this change (even in the early stage of this project) is a small thing, as it affects the architectural foundation of the whole project. 

Remember that newer SPAs are often JS-heavy (sometimes even using JS server-side), often distribute tasks differently between clients and servers, and use more traditional languages like PHP for not much more than APIs or support tasks. The build chain is different, the skillset of the developers is different ... I'm not sure if the core developers are willing / ready to walk down this road, since, if they did it right, they would have to drop large parts of their codebase and spend days and days on re-implementing these features instead of building new ones.
