### ISSUE TITLE
Validation in admin: user edit

### ISSUE THREAD

**Issue by hubrajesh** [humhub/humhub#1044]
![humhub 2015-05-16 13-59-39](https://cloud.githubusercontent.com/assets/11752885/7665441/e493c214-fbd3-11e4-9e70-9761bd5b87e0.png)

No validation when editing user in admin section.
Admin not supposed to do mistakes like this but still validation should be there and also in database level.
Tested in humhub ver. 0.11.2.

I have added following rules in my User model -
``` PHP
public function rules()
    {
     ...
     $rules[] = array('username, group_id, email', 'required');
     ...
     return $rules;
    }
```

**Comment by rbraband** [comment]
+1
