### ISSUE TITLE
Directory empty

### ISSUE THREAD

**Issue by max2020** [humhub/humhub#1045]
Hello ! 

I ve reinstalled my humhub on my server but i can't see the list of the users when i clic on the link directory. 

Thanks for your help
![capture d ecran 2015-05-16 a 14 31 02](https://cloud.githubusercontent.com/assets/4758732/7666459/7a089b46-fbe6-11e4-94bc-ffdde6e2de31.png)

**Comment by WASasquatch** [comment]
https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/updating.md#from-0101-to-0110

Last bit on page about rebuilding search.

**Comment by max2020** [comment]
Hello i use a mutualise server so i only have ftp access. Could tell me how to run these 2 commands with a url ?

Run php /path/to/humhub/protected/yiic search_rebuild
Run php /path/to/humhub/protected/yiic search_optimize

**Comment by luke-** [comment]
Sorry, thats not possible yet.

**Comment by max2020** [comment]
Ho no, and with FTP ?

**Comment by dakur** [comment]
I guess it's not possible either as it is "file transfer protocol" - used for transfering files, not running scripts..
