### ISSUE TITLE
Overwriting a view

### ISSUE THREAD

**Issue by SirbitoX** [humhub/humhub#1048]
Hi,
I want to overwrite a widget view (`/protected/modules_core/comment/widgets/views/form.php`) to my own theme. I created `form.php` file in `/mythem/views/comment/widgets` directory. but It didn't work. 
I'm doing any where wrong??
What about overwriting `/humhub/protected/modules_core/comment/views/comment/edit.php`? What should I do to overwrite it??
Thanks.

**Comment by SirbitoX** [comment]
@WASasquatch could you help me??

**Comment by WASasquatch** [comment]
From what I see you are overwritting correctly. HumHub has issues and simply ignores some overwrites I have come to discover. Several modules had to be scrapped because of view limitations and the system.

**Comment by SirbitoX** [comment]
Do you mean that several views of modules could not be overwritten??
What about my second question? 
Overwriting ```/humhub/protected/modules_core/comment/views/comment/edit.php```? What should I do to overwrite it??

**Comment by deMENSEN-JVD** [comment]
I was able to overwrite `/protected/modules_core/comment/widgets/views/form.php` by placing the overwrite in `/themes/theme-name/views/comment/widgets/form.php`.
Do other changes work, like CSS? Make sure the HumHub cache is disabled and cleared.

To overwrite `/protected/modules_core/comment/views/comment/edit.php` you would create `/themes/theme-name/views/comment/comment/edit.php`.

**Comment by SirbitoX** [comment]
@deMENSEN-JVD
I exactly overwrite the file as you have said, but it didn't work. I'm sure that the HumHub cache is disabled. Any other suggestion do you have??

**Comment by pvigorito-dgm** [comment]
same here...

**Comment by Felli** [comment]
Please move this to the [community site](https://community.humhub.com) if you have questions on customizations and theming of HumHub. :smile:
