### ISSUE TITLE
Unable To Delete User

### ISSUE THREAD

**Issue by nicksniffer** [humhub/humhub#1049]
![er](https://cloud.githubusercontent.com/assets/4383991/7671623/e60bebbc-fcf5-11e4-834c-90ce267f18e7.png)

**Comment by eduardonunesp** [comment]
I have a problem once when tried to delete an user that had created a space, then i delete and the user without a problem.

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-mail/commit/fe96d0fce00d95fd177b5a47b429831a25ec4a47 Fixed here
