### ISSUE TITLE
Request for Photo Gallery for Profile and Spaces

### ISSUE THREAD

**Issue by alexjose** [humhub/humhub#1050]
Photos bring life to all community. HumHub lacks a super photo gallery module with awesome UI/UX as the rest of the application.

Please do consider this request.

**Comment by jacmgr** [comment]
I completely agree. HumHub has everything I need for an interesting and useful small group site, except for a photo gallery.  It could be gallery per space would be enough for me; or multiple gallery per space.  I am not smart enough to do it, but would relly like it!

**Comment by WASasquatch** [comment]
They just need to write the view and simple functionality to draw posted images to the users profiles, and spaces it's posted too. I have a attachment system in works but I don't have much time currently working 50+ hour weeks.

**Comment by 001101** [comment]
In module 'files' you can also upload pictures and they will be shown in javascript popup, better than nothing.

**Comment by buddha87** [comment]
The new gallery module should be out soon.

**Comment by PapsOu** [comment]
Hi buddha87,

Do you have any fresh information's about this new gallery module ?

My customer want's a photo gallery in his humhub network and I would like to know if I should code it or wait for this release.

Thank's for your reply.

Regards.

**Comment by buddha87** [comment]
Its alsmost finished, the only thing missing before the release is a wall support for sharing the gallery. I hope this will be finished with the release of v1.2.

**Comment by gmwestrup** [comment]
Update please. I also would need this feature. Only thing missing for me.

**Comment by buddh4** [comment]
This will be released with v1.2 which is currently in beta.

**Comment by flegfleg** [comment]
Hi, i have 1.2.0-beta.2 installed… can´t find the gallery.

**Comment by Felli** [comment]
@flegfleg we're still in beta. You can still upload multiple images which will create a gallery within one post, this at the moment is the closest to a gallery we've got right now.
