### ISSUE TITLE
Vedio link post Fail on edit

### ISSUE THREAD

**Issue by hubrajesh** [humhub/humhub#1051]
Test on huhhub ver 0.11.2
When we try to edit a post with only video in message it will fail.
![test - humhub 2015-05-18 15-06-30](https://cloud.githubusercontent.com/assets/11752885/7678179/b3cc8b28-fd6f-11e4-8854-0aa912986b81.png)
![welcome space - humhub 2015-05-18 15-07-47](https://cloud.githubusercontent.com/assets/11752885/7678185/bb1d6366-fd6f-11e4-8889-75c8090caa71.png)

**Comment by hubrajesh** [comment]
This issue still exists even in version 1.0.0-beta.3.

**Comment by luke-** [comment]
Should be fixed in beta.4

https://github.com/humhub/humhub/commit/8b94d199d025d9465bea293f266b95dbe4905af6
