### ISSUE TITLE
HumHub emails coming in "Quoted"

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#1052]
Gmail is now assuming HumHub emails are a forward/quote of another message as well as flagging it's body content as spam/harmful. 

<img src="http://i.imgur.com/n8OqcZm.png" />

**Comment by rifaideen** [comment]
yes you are right. this is happening always.

**Comment by eduardonunesp** [comment]
Same here, i don't have any idea why that happens.

**Comment by luke-** [comment]
Should be fix in 0.20+
