### ISSUE TITLE
Weird page, after submitting markdown with the message module

### ISSUE THREAD

**Issue by vikrantc16** [humhub/humhub#1054]
I was testing markdown in messages on humhub and as I submitted the message, a weird page was there.
![thunasdfgr9](https://cloud.githubusercontent.com/assets/6683856/7722424/af69509a-fefd-11e4-9779-03f017f5f810.jpg)

I don't know how it happened, I was just sending a message. But please check it. Might be something big happening.

**Comment by andystrobel** [comment]
This works well for me. Can you please provide your release version and which markdown code you submitted, exactly?

**Comment by vikrantc16** [comment]
Well problem is solved now. It was theme to be blamed. We changed the theme and it worked. :+1:
