### ISSUE TITLE
Fatal error: Call to a member function isModuleEnabled() on a non-object in .../humhub/protected/modules/wiki/WikiModuleEvents.php on line 32

### ISSUE THREAD

**Issue by tgyou** [humhub/humhub#1056]
if activated "Report Content Module" and "Wiki module"  an error occurs as follows in "Reported Posts" menu. but, if "Wiki module" are disabled an error will not be displayed.

Fatal error: Call to a member function isModuleEnabled() on a non-object in .../humhub/protected/modules/wiki/WikiModuleEvents.php on line 32

WikiModuleEvents.php:32
```        if ($event->sender->space->isModuleEnabled('wiki') && $event->sender->space->isMember()) {```

nginx/1.8.0 TLS/Spdy
php 5.5.17
CentOS release 6.6
mariaDB 5.5.43

**Comment by WASasquatch** [comment]
```php
if ($event->sender->space != null && $event->sender->space->isModuleEnabled('wiki') && $event->sender->space->isMember()) {
```
May help ya in the meantime.

**Comment by tgyou** [comment]
@WASasquatch Thank you!

**Comment by luke-** [comment]
@WASasquatch Thanks for the fix

https://github.com/humhub/humhub-modules-wiki/commit/b2fd2690d0add527c73cbdece2316c7f8257e03f
