### ISSUE TITLE
Undo doesn't work on links | Still no paste in mobile

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#1057]
If you paste links in a post it will break the undo feature leaving the link intact and only removing previously typed words, and not pasted material. 

Still can't paste on mobile, which is a big bug. Half of HumHub's use is on mobile sharing content.

**Comment by ToonSoft** [comment]
Well,it is really a big bug.I can not paste ANYTHING on Android,Windows Phone,or iOS.My guys keep asking me why...
