### ISSUE TITLE
Custom pages and FFA

### ISSUE THREAD

**Issue by rbraband** [humhub/humhub#1058]
Hello, I have found that if I use a custom page open to guests that this site is accessible via the direct call - that's as far as we intended.
But in the top menu the menu item, however, is not displayed. For custom pages that are not visible to guests the menu entry is displayed.
The bug is that the permission to the page display works, the authorization for the menu does not.

I use custom_pages_extended

Sample: http://hub.cotg.ovh/custom_pages/8

**Comment by luke-** [comment]
could you please open this issue on the custom pages or custom pages extended github repo?

**Comment by WASasquatch** [comment]
I do notice you do not have guest mode enabled, and are then using guest mode features.

**Comment by rbraband** [comment]
@WASasquatch, I dont use any guest mode Feature, the System do using Thing that not transparent to me... where and what I have to enable and what are the consequences?

@luke, nice to see that manage error has found its way here - fix bugs , those were the good days...

**Comment by WASasquatch** [comment]
@rbraband  Guest Mode is required to set custom pages to guest mode. So I'd imagine the bug is there.

Administration -> Authentication -> First Option

<img src="http://i.imgur.com/8QAfZzN.png" />
