### ISSUE TITLE
displaying code to public

### ISSUE THREAD

**Issue by krishnatejaperannagari** [humhub/humhub#1060]
I got the following error when google was trying to index my site 

http://ngocommunity.org/index.php?r=search/index&mode=quick&keyword=-searchKeyword

Most of the code and functions are exposed for this error. Is it possible to hide all these details and show a simple error saying "It's not allowed to mix boolean and signs styles in the same subquery."

I am using latest version of humhub 0.11.2 on godaddy

**Comment by WASasquatch** [comment]
Turn off error reporting on HumHub. It is not to be used for public but
development.

**Comment by krishnatejaperannagari** [comment]
there is no option to turn off error report. I can flush them manually but they appear again

![1](https://cloud.githubusercontent.com/assets/6380932/7805265/d5608898-038c-11e5-92e3-7effbf285dc5.png)
![2](https://cloud.githubusercontent.com/assets/6380932/7805264/d55fee74-038c-11e5-8732-dece1b8da43e.png)
