### ISSUE TITLE
Module is not available error on creating migrations...

### ISSUE THREAD

**Issue by GQAdonis** [humhub/humhub#1061]
I have an issue where I am unable to create a migration using "yiic create [module] [name]".  I get an error saying "Module is not available".

I remember that the solution was to edit the main.php file under "config" directory, but in the latest updates, that section seems to be gone and I cannot figure out where to put the reference to my module, so I can make a migration.

Has something changed?

**Comment by WASasquatch** [comment]
Should you be using the migrate options? `yiic migrate create ...`

**Comment by luke-** [comment]
You need to enable the module to create migrations.
