### ISSUE TITLE
The search bar below avatar is not working

### ISSUE THREAD

**Issue by DearTanker** [humhub/humhub#1064]
can't search out anything

**Comment by dakur** [comment]
It works for me (clean installation of HumHub, using Firefox 38.0 on Ubuntu 14.04 LTS). Any details? What does inspector say? Are there any AJAX requests and responses?
Didn't you make update to 0.11 recently? (https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/updating.md#from-0101-to-0110)

**Comment by DearTanker** [comment]
Sorry, I mean, can't search for posts

**Comment by dakur** [comment]
Come on. It is not for searching in posts. It's written there: "Search for users and spaces"

**Comment by DearTanker** [comment]
your are right, i am sorry for this issue‘s title

**Comment by dakur** [comment]
@luke- : close request
