### ISSUE TITLE
oembed youtube video ie11

### ISSUE THREAD

**Issue by Guardian1983** [humhub/humhub#1067]
The youtube video is on top on the menu on everything, ignoring z-index, not possible to delete det post and the menu in top left is also under the youtube video.
no problem in chrome and firefox etc...

**Comment by WASasquatch** [comment]
Are you using compatibility mode?

**Comment by Guardian1983** [comment]
No i am not, everything in IE11 is standard. and the z-index is still being ignored by oembed, i can't possibly be the only one having this issue..

**Comment by Guardian1983** [comment]
I've tried comp. mode just now, everything looked crazy... :-D

**Comment by WASasquatch** [comment]
You might just be. You must have edited your theme and messed something up. My theme doesn't change any base structure:

<img src="http://i.imgur.com/xhFAxOt.jpg" />

**Comment by Guardian1983** [comment]
What happends if you push the menu down that makes you delete and edit the post? That's whete the error is ;-)

**Comment by Guardian1983** [comment]
My theme file is default... So that cant be... I'll try some things today...

**Comment by Guardian1983** [comment]
My problem here, the menu is not in front as it should be, i've tried on many other pc's now and it's the same problem, only in IE11!
So it's not in my theme or modifications done here.

![unavngivet](https://cloud.githubusercontent.com/assets/12225536/7959406/2da962a0-09f9-11e5-9ff8-26af17fe0061.jpg)

**Comment by Guardian1983** [comment]
My problem here, the menu is not in front as it should be, i've tried on many other pc's now and it's the same problem, only in IE11!
 So it's not in my theme or modifications done here.

![unavngivet2](https://cloud.githubusercontent.com/assets/12225536/7959466/953317c2-09f9-11e5-94a3-5b59c457cbd9.jpg)

**Comment by Guardian1983** [comment]
Just tested it on humhub's translate forum, the same error with the menu's there... 
So the error is'nt just with my installation of humhub ;-)

**Comment by WASasquatch** [comment]
Same story. Works fine. 

<img src="http://i.imgur.com/behzkkD.jpg" />

**Comment by Guardian1983** [comment]
Makes no sense at all, did'nt modify anything, and the error is on several computers, even in humhub translate forum, how is that possible? :-/

**Comment by WASasquatch** [comment]
Internet Explorer = Bad Renderer which has "Compensating" algorithms to compensate for bad markup, or unfamiliar markup. It causes random bugs from platform to platform and why it's not a standard browser in the web development field.

**Comment by Guardian1983** [comment]
Windows 7 here to... On all machine's, even tried it on a Windows 2008 server R2 ... Same problem, standard IE11 on all.... Makes no sense...

**Comment by Guardian1983** [comment]
Funny thing, just got it working here.. BUT, in a funny way, went into programs in IE, deactivated "Shockwave Flash Object", now it's working perfectly... VERY weird.. :-/

**Comment by WASasquatch** [comment]
Ah. You don't have just Flash, so Shockwave is taking over flash objects.

**Comment by Guardian1983** [comment]
i have Adobe flash installed, but yes... 
Have no idead if it is fixable, but maybe.. ;-)
But now you know where the problem is, maybe it's a bug, maybe not, and i also found out :-P
Thanks ;-)

**Comment by WASasquatch** [comment]
> just Flash

Most I know is IE has z-index issues. Most especially with `0` so it's best to always start at `1` or -`1` or some integer.  Shockwave taking over Flash elements may be resetting this index.

**Comment by Guardian1983** [comment]
I know IE is a major bug in website dev. hehe... But never seen this problem with z-index before, woth the shockwave thing... Have no idea what it does at all, all i know is that we got it working :-D
