### ISSUE TITLE
installation last step

### ISSUE THREAD

**Issue by roaphen** [humhub/humhub#1068]
I get the same error as the two issues below... Tried to activate URL rewrite...

https://github.com/humhub/humhub/issues/346
https://github.com/humhub/humhub/issues/799

Setup goes through without an issue. All requirements are met. on the last step to sign in (congratulations page): index.php?r=installer/config/finished
it redirects to the 1st step: index.php?r=installer/index

no errors in the errorlog/logging table... it is a shared hosting server: FreeBSD 9.3

does that mean it doesnt work on this server?

**Comment by mkuerbis** [comment]
the same over here
