### ISSUE TITLE
Username to short LDAP

### ISSUE THREAD

**Issue by timjcraig** [humhub/humhub#1069]
Is it possible to change username requirement from 4 to 3 characters?  Error message below. 

Could not create or update ldap user! (Array ( [username] => Array ( [0] => Username is too short (minimum is 4 characters). ) ) )

**Comment by hubrajesh** [comment]
change validation rule in file: /protected/modules_core/user/models/User.php

```php
 /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {

        if ($this->scenario == 'register') {
            // Only return all fields required for registration.
            // All other fields should be unsafe.
            return array(
               ...
                array('username', 'length', 'max' => 50, 'min' => 3), // change 'min' to 4 or any other number you want
            );
        }

```
or 
``` php 
$rules[] = array('username', 'length', 'max' => 50, 'min' => 4);

```

if this file gets updated by huhhub's updates then you have to do this again though.

**Comment by timjcraig** [comment]
@hubrajesh thank you for quick reply changing user.php resolved issue.

**Comment by a1co** [comment]
Why apply rules on LDAP users?

**Comment by TI-Admin** [comment]
There should be no enforced length validation with LDAP. I also do need length of 3 for our university ldap.
