### ISSUE TITLE
how to use urlManagerRules? 

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#1075]
https://github.com/humhub/humhub/blob/master/protected/components/ModuleManager.php#L190
````php
        // Append URL Rules
        if (isset($definition['urlManagerRules'])) {
            Yii::app()->urlManager->addRules($definition['urlManagerRules'], false);
        }
```

@luke- may I ask your help? How do I properly use this? I can never seem to get it to work.     

Also, must event callbacks be a array or can they be the callback function in question?

**Comment by luke-** [comment]
I've created a small Wiki entry about this feature.

https://community.humhub.com/s/a620fd6b-425b-4591-b0d4-47d22f2f8edd/wiki/page/view/title/Custom+URL+Manager+Rules

Hope this helps.

**Comment by WASasquatch** [comment]
Thank you!

**Comment by funkycram** [comment]
Updated link: https://community.humhub.com/content/perma?id=27089
