### ISSUE TITLE
Meny on mobile to far left

### ISSUE THREAD

**Issue by necken** [humhub/humhub#1078]
I have an issue with the meny on mobile platforms.
The dropdown is to far left, outside the screen.
Any idea how to fix this? Same on iphone, android
![Image of menu](http://kodnamn.se/stuff/mobilemenuhumhub.png)

**Comment by WASasquatch** [comment]
Same issues, as well as My Spaces menu is pretty broken. Mobile was working great prior to new 0.11.x.
