### ISSUE TITLE
http.php Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by jfranc0** [humhub/humhub#1079]
Hello,

don't know if this is supposed to be filed under bug or question, but here goes.

Having an issue accessing the module's and the about page under the administration panel.

I get the following when I try to access /admin/module/list

PHP Warning
include_once(Zend/Uri/Http.php): failed to open stream: No such file or directory
/var/www/html/protected/vendors/Zend/Loader.php(134)

along with a bunch of other Zend_Loader::loadFile() errors

any recommendations or advice would be extremely helpful. Thanks in advance.

Here is what shows up under "logging" in the Administration menu

include_once(Zend/Uri/Http.php): failed to open stream: No such file or directory (/var/www/html/protected/vendors/Zend/Loader.php:134) Stack trace: #0 /var/www/html/protected/vendors/Zend/Uri.php(137): loadClass() #1 /var/www/html/protected/vendors/Zend/Http/Client.php(306): factory() #2 /var/www/html/protected/vendors/Zend/Http/Client.php(284): Zend_Http_Client->setUri() #3 /var/www/html/protected/modules_core/admin/libs/OnlineModuleManager.php(152): Zend_Http_Client->__construct() #4 /var/www/html/protected/modules_core/admin/libs/OnlineModuleManager.php(170): OnlineModuleManager->getModules() #5 /var/www/html/protected/modules_core/admin/views/module/_header.php(7): OnlineModuleManager->getModuleUpdates() #6 /var/www/html/protected/vendors/yii/web/CBaseController.php(126): require() #7 /var/www/html/protected/vendors/yii/web/CBaseController.php(95): ModuleController->renderInternal() #8 /var/www/html/protected/vendors/yii/web/CController.php(869): ModuleController->renderFile() #9 /var/www/html/protected/components/Controller.php(191): ModuleController->renderPartial() #10 /var/www/html/protected/modules_core/admin/views/module/list.php(6): ModuleController->renderPartial() #11 /var/www/html/protected/vendors/yii/web/CBaseController.php(126): require() #12 /var/www/html/protected/vendors/yii/web/CBaseController.php(95): ModuleController->renderInternal() #13 /var/www/html/protected/vendors/yii/web/CController.php(869): ModuleController->renderFile() #14 /var/www/html/protected/components/Controller.php(191): ModuleController->renderPartial() #15 /var/www/html/protected/vendors/yii/web/CController.php(782): ModuleController->renderPartial() #16 /var/www/html/protected/modules_core/admin/controllers/ModuleController.php(75): ModuleController->render() #17 /var/www/html/protected/vendors/yii/web/actions/CInlineAction.php(49): ModuleController->actionList() #18 /var/www/html/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #19 /var/www/html/protected/vendors/yii/web/filters/CFilterChain.php(133): ModuleController->runAction() #20 /var/www/html/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #21 /var/www/html/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #22 /var/www/html/protected/vendors/yii/web/filters/CInlineFilter.php(58): ModuleController->filterAccessControl() #23 /var/www/html/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #24 /var/www/html/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #25 /var/www/html/protected/vendors/yii/web/CController.php(265): ModuleController->runActionWithFilters() #26 /var/www/html/protected/vendors/yii/web/CWebApplication.php(282): ModuleController->run() #27 /var/www/html/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #28 /var/www/html/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #29 /var/www/html/index.php(40): WebApplication->run() REQUEST_URI=/admin/module/list in /var/www/html/protected/vendors/Zend/Loader.php (134) in /var/www/html/protected/vendors/Zend/Loader.php (134) in /var/www/html/protected/vendors/Zend/Loader.php (82) in /var/www/html/protected/vendors/Zend/Uri.php (137) in /var/www/html/protected/vendors/Zend/Http/Client.php (306)

![php warning - google chrome_006](https://cloud.githubusercontent.com/assets/12788134/8026317/0180b856-0d3f-11e5-9926-7f1b409d5077.png)

**Comment by WASasquatch** [comment]
Common issue we've been having with 500 errors for modules and about page. Something to do with either remote server not being reachable most the time due to high volume, or settings on the server side that need to be adjusted.
