### ISSUE TITLE
Messages can't send

### ISSUE THREAD

**Issue by bbfdesign** [humhub/humhub#1083]
When I'm writing a Message to another User the Send Button is not working. I can click on it - but nothing happens ... I tested it with Chrome and Firefox.

**Comment by dakur** [comment]
I've installed clean installation, created user, enable Message module and tested it between admin and user and it worked fine (Ubuntu 14.04 LTS, Firefox 38.0). So I guess it is not a bug.

Do you have any details? What does Inspector say? What does it mean "nothing happens" - does the window close or something? is this behaviour in new message pop-up or in reply page/form? (Do you have Javascript enabled?)

**Comment by programguy** [comment]
The mail module has become extremely slow. Have you waited 20 seconds after clicking the button to see if it will send?

**Comment by hubrajesh** [comment]
Almost same issue here , After clicking send button browser freeze for few seconds. 
Looks like redirect action takes long time to process.
