### ISSUE TITLE
if enanle LDAP any user can access (not only the specified group)

### ISSUE THREAD

**Issue by viva-chegevara** [humhub/humhub#1087]
in HumHub setup LDAP authorization, filter:
(&(objectClass=user)(memberOf=cn=hub_access,cn=Users,DC=domain,DC=local))

the search says "Ok, found 20 members"
If enabled - the system can enter ANY user domain (not only a member of group "hub_access")
if disabled - the system can enter only the user who Importing

How can I restrict users?

**Comment by npeter88** [comment]
I have the same problem. I can't restrict login for users of a special group.
(&(objectClass=person)(!(memberOf=CN=Non-Intranet,CN=Users,DC=DOMAIN,DC=LOCAL)))

**Comment by aliel** [comment]
same problem

**Comment by snoopyf** [comment]
Any news about this issue? Noticed the same behaviour today.
My LDAP User Filter:
(&(objectClass=posixAccount)(memberOf=cn=www_humhub,cn=groups,dc=xxxxx,dc=xxxxx))

![humhub_ldap1](https://cloud.githubusercontent.com/assets/1266248/16111926/34719238-33b5-11e6-9613-1c9d9556f411.png)

After clicking the "save" Button, the Admin Interface correctly sais: "Status: OK! (1 User)", which is correct, as actually for testing only 1 user is "memberOf" the group.
Testing the filter on the linux console with ldapsearch leads to the same result:

```
# extended LDIF
#
# LDAPv3
# base <dc=xxxx,dc=xxxx> (default) with scope subtree
# filter: (&(objectClass=posixAccount)(memberOf=cn=www_humhub,cn=groups,dc=xxxx,dc=xxxx))
# requesting: dn 
#

# snoopy, users, xxxx
dn: uid=snoopy,cn=users,dc=xxxx,dc=xxxx

# search result
search: 3
result: 0 Success

# numResponses: 2
# numEntries: 1
```

BUT:
When entering any valid credentials of any other user in the baseDN, the login succeeds and the User is created in HumHub:

Login:
![humhub_ldap2](https://cloud.githubusercontent.com/assets/1266248/16112195/8d2ade38-33b6-11e6-8642-236ec1c87147.png)

Login Succeeds:
![humhub_ldap3](https://cloud.githubusercontent.com/assets/1266248/16112206/99521c80-33b6-11e6-8f5c-99d50ab5047b.png)

User created:
![humhub_ldap4](https://cloud.githubusercontent.com/assets/1266248/16112211/a4cc765a-33b6-11e6-8cdf-c7f096f2a8dd.png)

So IMHO the LDAP User Filter is completely useless atm.....

**Comment by luke-** [comment]
Please also set the login filter:

![image](https://cloud.githubusercontent.com/assets/4736168/16114029/6d25e21e-33bf-11e6-8371-59033ced8b21.png)

**Comment by snoopyf** [comment]
Setting the Login Filter to "(uid=%s)" doesn't change the behaviour, the Non-Group User is still able to login. I deleted the formerly created user before the login, of course.

OT: I didn't understand the difference between / the behaviour of "Login Filter", "User Filter" and "User Attribute" at all and in the docs there is nothing to read about it.
The (in the screenshot german) help text for "User Filter" sais: "Limit access to users meeting this criteria.". In other words (for me): "Just allow users to login at all, who can be found in LDAP with this filter, deny any other". And the example for "User Filter" is exactly what I would expect it is for: "Just allow users of "CN=Workers,CN=Users..." to login..."

So what is the "Login Filter" for additionally? And why do I have to set the "User Attribute" to "uid", too?
BTW: The Help Text for "Login Filter" sais: "...%uid replaces the username..." but the example is: '...or "(uid=%s)" ', the first mentions "%uid" as var, the second "%s" as var.
Tested with "(uid=%uid)" => No LDAP User could login any more
Tested with "(uid=%s)" => Login is possible as mentioned above.


I digged a little into the code and came across this:
In: "<humhubDir>/protected/humhub/modules/user/libs/Ldap.php":

- The only method respecting the "userFilter" - Setting at all was "refreshUsers"
- The method "authenticate" seems just to check the password with a ldap bind, regardless any filter
- The method "handleLdapUser" doesn't seem to use "userFilter", too. It just creates the user, when not found.

Then I did a "grep -ir userfilter" in the whole <humhub> dir, and the only founds where the settings dialog (and regarding) objects and the above mentioned.

So it seems to me that the userfilter setting is completely ignored during the login process..

**Comment by snoopyf** [comment]
After setting the "Login Filter" to exactly the same as the "User Filter" the behaviour is as expected... But now I am completely confused about the differences of "User Filter" and "Login Filter" (and their use cases...) Isn't that redundant?

**Comment by snoopyf** [comment]
Next issue:
When setting the "Login Filter" to exactly the same, as the "User Filter" login is only possible, when the group contains just one and only user... when it contains more than one, no LDAP User can log in, HumHubs Log sais:

"LDAP Error: 0x1: Unexpected result count (2) for: (&(objectClass=posixAccount)(memberOf=cn=www_humhub,cn=groups,dc=xxxx,dc=xxx)) "

So it is important, that the "Login Filter" results in just one find. Should be mentioned somewhere IMHO.
Now I set it to :" (&(uid=%s)(memberOf=cn=www_humhub,cn=groups,dc=xxx,dc=xxxx)) " and this seems to be the only working solution.

**Comment by tjmidnight** [comment]
This is not fixed and should not be closed. I'm having exactly the same issue as snoopyf, except that his login filter fix, adjusted for my site & LDAP server, does not allow my LDAP user to log in.

**Comment by buddh4** [comment]
If not already done and it's a different issue, please open a new issue.

**Comment by caumons** [comment]
I had to use same values for login filter and user filter in order to get it to work:

> (&(uid=%s,objectClass=inetOrgPerson)(memberOf=cn=humhub,cn=groups,dc=xxxx,dc=xxx))

**Comment by luke-** [comment]
The "Login filter" is used on login to check if the user is allowed to log in and the "User filter" is only used by the hourly cron job to automatically create/update/disable users.

Both filters should be basically the same - here an example which checks that the user is within a specific LDAP group and also the AD account is active.

Login Filter:
`(&(objectCategory=Person)(sAMAccountName=%s)(memberOf=CN=HumHub_User,OU=HumHub,DC=example,DC=com)(!(UserAccountControl:1.2.840.113556.1.4.803:=2)))`

User Filter:
`(&(objectCategory=Person)(sAMAccountName=*)(memberOf=CN=HumHub_User,OU=HumHub,DC=example,DC=com)(!(UserAccountControl:1.2.840.113556.1.4.803:=2)))
`
