### ISSUE TITLE
Can't setup a 2 tiers architecture

### ISSUE THREAD

**Issue by Daimanu06** [humhub/humhub#1088]
Hello.

I try to set up a 2 tiers architecture (web server + database server) and the mysql part is ok (the web server is connected to the db).

However, I can't tell humhub to use the second server as database. I have an error before the page asking the db address appears ( *CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'humhub_dbuser'@'localhost' (using password: YES)* ).

I searched a 'localhost' or '127.0.0.1' sequence in php files and tried to modify them without success.
Sounds weird that humhub tries to connect to a local database before anything else.

**Comment by hubrajesh** [comment]
humhub tries to connect local database because you installed humhub in your local system ? 
Just edit  */protected/config/local/_settings.php*  file for database configuration or create new config file and manage configuration in that file.

**Comment by Daimanu06** [comment]
Indeed, that's the right file to modify.
Thank you, now the websites connects correctly to the database.
Now I have another issue, the db has no table. I'm going to export an existing db to this one.
Thanks!
