### ISSUE TITLE
Joining/Revoking a community CSRF Vulnerability

### ISSUE THREAD

**Issue by SymbianSyMoh** [humhub/humhub#1099]
Hi,
I would like to report a Security Vulnerability in the HumHub Script with the following details:

Vulnerability:
Cross Site Request Forgery - (CSRF)

Info:
http://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

Affected URL(s)/Forms Code:
An example:
Join:
https://symbiansymoh.humhub.com/s/1f0cff4b-6a25-4f1f-b8fa-2cc6332be0f1/space/space/requestMembership

Revoke:
https://symbiansymoh.humhub.com/s/1f0cff4b-6a25-4f1f-b8fa-2cc6332be0f1/space/space/revokeMembership

More Details/Impact:
Joining or leaving a community behalf of the logged in humhub user.

Waiting for your reply
Thanks

**Comment by SymbianSyMoh** [comment]
!!

**Comment by MidooDj** [comment]
!!

**Comment by luke-** [comment]
Please do not open security related issues here.

Contact us directly at info@humhub.com.

https://github.com/humhub/humhub/blob/master/CONTRIBUTING.md
