### ISSUE TITLE
LDAP auth logs clear-text passwords

### ISSUE THREAD

**Issue by morxa** [humhub/humhub#1100]
### Summary
If an error occurs during LDAP authentication, an `Zend_Ldap_Exception` is written to the logfile, which contains the clear-text password of the user trying to authenticate. The log file contains an entry similar to the following entry:

```
exception 'Zend_Ldap_Exception' with message '0x20: No object found for: (&(objectclass=Person)(uid=0id))' in /var/www/humhub/protected/vendors/Zend/Ldap.php:692 
Stack trace: 
#0 /var/www/humhub/protected/vendors/Zend/Ldap.php(538): Zend_Ldap->_getAccount('morxa', Array) 
#1 /var/www/humhub/protected/vendors/Zend/Ldap.php(605): Zend_Ldap->_getAccountDn('morxa') 
#2 /var/www/humhub/protected/libs/HLdap.php(89): Zend_Ldap->getCanonicalAccountName('morxa', 1) 
#3 /var/www/humhub/protected/modules_core/user/components/UserIdentity.php(119): HLdap->authenticate('morxa', '<my_cleartext_password>') 
#4 /var/www/humhub/protected/modules_core/user/components/UserIdentity.php(45): UserIdentity->validatePassword(Object(User)) #5 /var/www/humhub/protected/modules_core/user/forms/AccountLoginForm.php(56): UserIdentity->authenticate() 
#6 /var/www/humhub/protected/vendors/yii/validators/CInlineValidator.php(42): AccountLoginForm->authenticate('password', Array) #7 /var/www/humhub/protected/vendors/yii/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(AccountLoginForm), 'password') 
#8 /var/www/humhub/protected/vendors/yii/base/CModel.php(159): CValidator->validate(Object(AccountLoginForm), NULL) 
#9 /var/www/humhub/protected/modules_core/user/controllers/AuthController.php(76): CModel->validate() 
#10 /var/www/humhub/protected/vendors/yii/web/actions/CInlineAction.php(49): AuthController->actionLogin()
#11 /var/www/humhub/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams(Array) 
#12 /var/www/humhub/protected/vendors/yii/web/CController.php(286): CController->runAction(Object(CInlineAction)) 
#13 /var/www/humhub/protected/vendors/yii/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array) 
#14 /var/www/humhub/protected/vendors/yii/web/CWebApplication.php(282): CController->run('login') 
#15 /var/www/humhub/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('user/auth/login') 
#16 /var/www/humhub/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() 
#17 /var/www/humhub/index.php(39): CApplication->run()
#18 {main} REQUEST_URI=/humhub/index.php?r=user/auth/login HTTP_REFERER=https://<base_url>/humhub/index.php?r=user/auth/login --- 
```
### How to reproduce
1. configure LDAP authentication
2. cause the LDAP authentication to throw an exception, e.g. by defining a faulty login filter
3. try to log in

### Expected behavior
The error should be shown to the user and logged to the log file, but the password should be omitted.

### Actual behavior
The clear-text password is both shown to the user in the browser and written to the log file.

### System Information
- OS: Debian Wheezy
- PHP 5.4.36
- apache 2.2.22
- mysql 5.5.40
- humhub v.0.11.2
- browser: any

**Comment by luke-** [comment]
Did you enabled production mode?

https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/installation.md#securityproduction-mode

**Comment by morxa** [comment]
No, because I'm still testing. But even in a testing phase, it is very inconvenient to print passwords as clear-text to the log. I'm debugging the LDAP connection, so I cannot simply use a fake user, and I cannot easily change my password to a temporal password, as the same credentials are used in several places. Moreover, I cannot ask other users to test if their credentials work, because if an error occurs, I will immediately get to know their passwords. So in my opinion, clear-text passwords should not be logged, even in non-production mode.

**Comment by ychoucha** [comment]
where is the log files, please
