### ISSUE TITLE
Please assist with theming

### ISSUE THREAD

**Issue by tayzee** [humhub/humhub#1109]
Hi, 

I am creating my own theme for humhub and I have created the new folder etc as instructed in the readme.

The problem I am having is that I have added some new user profile categories and fields and some of the information that will be in those categories are only going to be visible to admins and the user whose profile that information is captured in. 

So I have copied my modified version of the about.php file from /protected/modules_core/user/views/profile to
/Library/WebServer/Documents/humhub/themes/Thirst/views/modules_core/user/views/profile
however, this doesnt seem to be working out for me. Im not quite sure where to go from here..

Please can someone tell me where I should put my edited version of about.php and how to make sure that that version gets called.

Any assistance would be much appreciated.

Thanks

**Comment by WASasquatch** [comment]
Please pay close attention to the [Theming Guide](https://github.com/humhub/humhub/blob/master/protected/docs/guide/theming/index.md)

The path should look like /themes/Thirst/views/user/profile/ I believe.
