### ISSUE TITLE
boa noite eu gostaria de reportar um erro

### ISSUE THREAD

**Issue by lerivaldo** [humhub/humhub#1111]
ao envia os arquivos para a hospedagem na Hostgator  e quando vamos instalar gera o seguinte erro 

Parse error: syntax error, unexpected T_FUNCTION in /home/ e nome do Usuário aqui /public_html/   nome da pasta de hospedar os aquivos /protected/libs/HHtml.php on line 199

agradeço se alguém mim responder

**Comment by pekman1** [comment]
Cheque a versão do PHP oferecida pela sua Hospedagem e a versão que é requerida pelo Humhub. Avalie se são compatíveis.

**Comment by leotostes** [comment]
Lerivaldo, atualize o seu php para o 5.4+, tive o mesmo erro e foi resolvido assim.

**Comment by lerivaldo** [comment]
obrigado a todos pois ao atualizar o php deu tudo certo

**Comment by pekman1** [comment]
Que bom que resolveu.
