### ISSUE TITLE
Sending mail

### ISSUE THREAD

**Issue by dinguedelle** [humhub/humhub#1112]
The signup mail is not send! 
How to resolve this issu

**Comment by F4T4LITY** [comment]
got same problem 
we have to configure the script that send to the user the link for continue the registration

**Comment by luke-** [comment]
https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/installation.md#e-mail-configuration

**Comment by dalosgit** [comment]
Page not found Luke!

**Comment by luke-** [comment]
Meanwhile: https://www.humhub.org/docs/guide-admin-installation.html#e-mail-configuration

**Comment by dalosgit** [comment]
Hi Lucas,
thank you very much - i'm trying to fix the problem right now, but without any success.
The list did I worked one hour before.
Thank you!
Kr Phillip
