### ISSUE TITLE
Is there a way to see all spaces as a non admin user?

### ISSUE THREAD

**Issue by haimich** [humhub/humhub#1113]
I set up a test instance of Humhub and I'm absolutely excited about it so far, good work! There's only one thing I couldn't find out: when someone creates a public space, is there a way for other users to discover it or do you always have to invite all users manually? What I mean is like an "All Spaces" button as an addition to "My Spaces". Maybe it could also be integrated with the existing button, for example with a filter that by default only shows my spaces. I don't expect our Humhub installation to have more than 10 walls, but for bigger communites I think an extra page would be better. Another solution could be to display the creation of a space as an event on everyone's dashboard.

Btw: I read the [guidelines for contributing](https://github.com/humhub/humhub/blob/master/CONTRIBUTING.md) prior to opening this issue and it said I should ask the [community](http://community.humhub.org/) if I have a general question about Humhub. Unfortunately the link didn't work, all it showed was "Nothing to see here!" :smiley:

**Comment by hubrajesh** [comment]
community link: https://community.humhub.com

User can use directory link in top menu to see all users and public spaces. 
BTW creating space as event and sending notification to all connected/following user is good idea.

**Comment by haimich** [comment]
Thanks for the information, for some reason I thought "Directory" would only be a list of all users so I didn't look there. The community link you sent me also worked!
