### ISSUE TITLE
https://github.com/WASasquatch/humhub-modules-custom-pages-extended

### ISSUE THREAD

**Issue by RudolfFussek** [humhub/humhub#1114]
I have install this module, but I have a error:

Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /homepages/12/d576585625/htdocs/protected/modules/custom_pages/models/CustomPage.php on line 193

Can anyone help me?

Thanks!

**Comment by WASasquatch** [comment]
For reference: https://github.com/WASasquatch/humhub-modules-custom-pages-extended/blob/master/models/CustomPage.php
