### ISSUE TITLE
Cannot delete user

### ISSUE THREAD

**Issue by TeigneuX** [humhub/humhub#1117]
Hi,

I raise this error by deleting an user 
UserMessage and its behaviors do not have a method or closure named "leave".

This user was very active :-)

**Comment by programguy** [comment]
I've been meaning to report that problem for a while. It took me a long time to clean up the database from the mess it left. The problem has existed for a few months and the trouble actually lies in the mail module, so this issue belongs there.

**Comment by programguy** [comment]
Issue was fixed by @luke- in commit https://github.com/humhub/humhub-modules-mail/commit/fe96d0fce00d95fd177b5a47b429831a25ec4a47 and is part of version 0.6.3 of the mail module.
