### ISSUE TITLE
add options for user rules

### ISSUE THREAD

**Issue by My1** [humhub/humhub#1119]
well I saw that the user rules seem to be upon a request (issue #363) but it's plain annyoing for me with my Main username (My1) to get into such places especially if I am the admin.
I already changed the protected/modules_core/user/models/User.php but when I wanna change my name later in the UCP they want 5 letters, according to the message and not 4 as "usual" in humhub, this was not what I said in the php and when humhub updates it gets changed back again...

so please give us administrators an option for those rules.

**Comment by TME97** [comment]
Amen.
