### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by simon-roderus** [humhub/humhub#1120]
Please release a new Version 0.11.3 with the 35 commits since the last release so that can I update my humhub-installation.

**Comment by luke-** [comment]
@simon-roderus We try to release next week the 0.11.3

FYI: At the moment we're working on 0.20.0   based on Yii2

**Comment by simon-roderus** [comment]
Thank you for your fast response, luke. Sounds good!
I am looking formward to 0.11.3 and even more to 0.20.0!

**Comment by simon-roderus** [comment]
I reopen this issue, because I am still hoping for the 0.11.3 release soon :+1:

**Comment by simon-roderus** [comment]
Any plans to release 0.11.3 soon? Or should I switch to "master" branch and use the latest unreleased changes from there?

**Comment by luke-** [comment]
The master is a good choice if you want to be always up2date.

Current timeframe is to release the beta of 0.20 and also the 0.11.3 in about 1-2 weeks.

**Comment by simon-roderus** [comment]
Sounds good!
