### ISSUE TITLE
Test Thai Language Display is Show ?????  

### ISSUE THREAD

**Issue by chatgen** [humhub/humhub#1121]
TEST Thai Language Display that show.
 
" ? ? ? ? ? ? ? ? ? ? ? ? ? ?? ? ? ? ? ? ? ? ? ? ? ? ? ?? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ?"
![hum1](https://cloud.githubusercontent.com/assets/135108/8717357/ea982b3e-2bc4-11e5-8fe0-43b01682a8d0.png)

**Comment by luke-** [comment]
Make sure your database is installed with UTF8

https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/installation.md

**Comment by chatgen** [comment]
I have installed by UTF8 and is working, the case to have been resolved.

thank you ^^
