### ISSUE TITLE
Can't Upload File more than 8MB

### ISSUE THREAD

**Issue by parmindersingh1** [humhub/humhub#1123]
hello,
i am not able to upload file more than 8mb, in administration panel, it says maximum 8mb

**Comment by WASasquatch** [comment]
Have you checked your Apache settings for post limit and upload limit?

On Sat, Jul 18, 2015 at 1:43 AM, Parminder Singh <notifications@github.com>
wrote:

> hello,
> i am not able to upload file more than 8mb, in administration panel, it
> says maximum 8mb
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/1123>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*

**Comment by blackandcold** [comment]
It's actual the PHP settings not the Apache.
Usually you can find the php.ini in /etc/php/apache2/php.ini
and set following lines to the M (Megabyte) you want:

upload_max_filesize = 20M
post_max_size = 20M

**Comment by WASasquatch** [comment]
Those are actually, still, Apache settings. Lol Same with NGINX and other
server environments. Apache is handling the requests, not PHP.

On Sun, Jul 26, 2015 at 1:29 AM, Johannes Kurz <notifications@github.com>
wrote:

> It's actual the PHP settings not the Apache.
> Usually you can find the php.ini in /etc/php/apache2/php.ini
> and set following lines to the M (Megabyte) you want:
>
> upload_max_filesize = 20M
> post_max_size = 20M
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/1123#issuecomment-124957612>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*
