### ISSUE TITLE
Is there a difference between the mailing by the cronjobs and inside the app?

### ISSUE THREAD

**Issue by wikibit** [humhub/humhub#1129]
Hi,

is there a difference between the mailing by the cronjobs (hourly & daily) and from inside the app (like the sending of the activation mails etc...)

because I do receive the mails from the cronjobs (like the latest news and activities)
but e.g. mails from the user registration process are not send (or maybe they are send, but the do not arrive)

the app uses PHP mail, does the cronjob use the same?
if so, are there any differences in parameters?

I couldn't find it immediately when trying to dig in the code

Thanks

**Comment by luke-** [comment]
There should be no difference, maybe in your PHP configuration? (cli vs. web)
