### ISSUE TITLE
User followers & following user translation flipped in German

### ISSUE THREAD

**Issue by maxfrigge** [humhub/humhub#1130]
The German translation for `User followers` and `Following user` is flipped.

https://github.com/humhub/humhub/blob/master/protected/modules_core/user/messages/de/widgets_views_userFollower.php

It should be the other way around.

    <?php
    return array (
      '<strong>Following</strong> user' => 'Der <strong>Nutzer</strong> folgt',
      '<strong>User</strong> followers' => 'Dem Nutzer <strong>folgen</strong>',
    );

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/d73c6a26221ddaf6edb33a31203ad4d4b5fa0c2d
