### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by candidosales** [humhub/humhub#1131]
https://github.com/humhub/humhub/blob/master/protected/docs/guide/developer/core_changes.md

Don't work

**Comment by phparkle** [comment]
ditto

**Comment by luke-** [comment]
Here you can find an overview of latest changes:

https://github.com/humhub/humhub/releases
https://github.com/humhub/humhub/commits/master
https://github.com/humhub/humhub/wiki/Roadmap
