### ISSUE TITLE
Cometchat cookie integration issue

### ISSUE THREAD

**Issue by Spirantz** [humhub/humhub#1134]
I'm trying to integrate Cometchat into HumHub and have it set up almost 100%. Cometchat is pulling and displaying the users and usernames from my DB, however I am unable to get cometchat to log-in the users via the cookie. I noticed the cookie named 'sin' is what keeps people logged in on humhub, so I'm assuming thats the cookie cometchat needs to pull. However when I set: 

function getUserID() {
  $userid = 0; // Return 0 if user is not logged in

  if (!empty($_SESSION['sin'])) {
      $userid = $_SESSION['sin'];
  } 
  $userid = intval($userid);
  return $userid;
}

nothing happens and cometchat shows my user as logged out, even though they're logged into humhub. Is it possible to have a new cookie created upon logging in that's only valid for the session?

**Comment by WASasquatch** [comment]
Cookies and Sessions are not one in the same. You cannot call a cookie by use of the session function. You also should be sure to use Yii based code to not interfere with headers which will crash the script. 

http://www.yiiframework.com/wiki/152/cookie-management-in-yii/
http://www.larryullman.com/2011/05/03/using-sessions-with-the-yii-framework/

**Comment by Spirantz** [comment]
Thanks!

**Comment by Spirantz** [comment]
For anyone who may come across this issue in the future, I figured out how to make it work:

```
function get_user_id() 
	{
		global $db;
		
		$userid = NULL;

		if (!empty($_COOKIE['sin'])) 
		{
			$result = $db->execute("
				SELECT user_id 
				FROM " . TABLE_PREFIX . "user_http_session
				WHERE id = '" . $db->escape_string($_COOKIE['sin']) . "'
			");

			if ($row = $db->fetch_array($result))
			{
				if (!empty($row['user_id']))
				{
					$userid = $row['user_id'];
				}
			}
		}

		return $userid;
	}

```

**Comment by WASasquatch** [comment]
Again, I'd use Yii standards. HumHub is a framework with standards to
follow.

**Comment by gigabytedevelopers** [comment]
Please @Sprirantz, could you guide me through 9n how you successfully integrated cometchat to humhub?
