### ISSUE TITLE
Problems with mentions?

### ISSUE THREAD

**Issue by CKGrafico** [humhub/humhub#1135]
I don't know what's happening with mentions, any idea?
![humhubmention](http://i.imgur.com/vJG1Tao.gif)
Not JavaScript error on console

**Comment by dakur** [comment]
Check the AJAX requests in your browser inspector - are there any? What are the results?

**Comment by CKGrafico** [comment]
Yes more info:
domain.com/index.php?r=search/mentioning&CSRF_TOKEN=75555cb6c3b3a1d6dace3f1a6d0283202841f504&keyword=Paula&_=1438455380450

Return '[ ]'

![bugmention](http://i.imgur.com/uPYeLwD.gif)

**Comment by dakur** [comment]
And which version of HumHub do you use? What is the last commit you have (if you downloaded through git clone)?

**Comment by CKGrafico** [comment]
Las commit at master https://github.com/humhub/humhub/commit/538e4653e66a025067f94fb7975733afc4c43de3

**Comment by dakur** [comment]
Ok, I made clean installation with admin account called 'admin' and user account called 'user'. When I logged in as 'user' and try to mention 'admin' on my profile or in space, it works. Also mentioning 'user' by 'admin' works.
Isn't it possible, that 'Paula' user in your case is not activated yet or something like that? It must be some problem on your side.

**Comment by dakur** [comment]
If you make clean installation, does it work? How many users does your HumHub instance work with? How old is the installation? Have you updated? If so, did you read updating.md? https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/updating.md

**Comment by CKGrafico** [comment]
Thanks!
Was that
Run php /path/to/humhub/protected/yiic search_rebuild
Run php /path/to/humhub/protected/yiic search_optimize
Now works, not faster but works :)

**Comment by dakur** [comment]
Great!
@luke- : Close request.
