### ISSUE TITLE
Question; Private message

### ISSUE THREAD

**Issue by Spirantz** [humhub/humhub#1136]
Is it possible to disable the private message email that is sent each time you receive a PM?

**Comment by programguy** [comment]
Only through code at this point. It would be a great feature though.

**Comment by blackandcold** [comment]
And how through code?
Because "chatting" with messages leads to spam-like mail flood.

**Comment by blackandcold** [comment]
ok https://github.com/humhub/humhub-modules-mail/blob/master/models/Message.php
line 182-184

**Comment by hubrajesh** [comment]
@blackandcold 
Comment all lines **inside** notify function if you want to stop all mail notification. But if you just wants to stop notification for each message entry then comment function calls(**notify()** ) from controller file.
https://github.com/humhub/humhub-modules-mail/blob/master/controllers/MailController.php.

just keep it inside function : actionAddUser()

If you uncomment lines 182-184 then you have to make changes in database and code. I don't think setting "receive_email_messaging"  is available in humhub's default installation.

**Comment by unspecified23** [comment]
Hi guys, can you be more specific. I am trying to stop e-mail notifications for messages, I tried deleting the last row of
master/models/Message.php

but that hasn't changed anything.

Could you please tell me what do I have to do?

Thank you.
