### ISSUE TITLE
Documentation on how to develop custom modules lacks details

### ISSUE THREAD

**Issue by haimich** [humhub/humhub#1140]
I'm trying to figure out how to write my own module and integrate it in my Humhub instance. I read through all available wiki pages and searched for a solution in the Github issues but I couldn't find any information on how to install a module other than via the marketplace. I cloned an existing Github repository (task module) into `protected/modules`. Afterwards I noticed that it was marked as *installed* on the "Search online" page, but it didn't show up on the modules page of my spaces. 

Can you please give me a hint on how I can achieve this?

I'm running the newest Humhub version.

**Comment by luke-** [comment]
Sorry, we try to improve our documentation at the moment, but it still lacks on details & examples.

https://www.humhub.org/docs/
