### ISSUE TITLE
Erro syntax error, unexpected T_FUNCTION

### ISSUE THREAD

**Issue by feyth** [humhub/humhub#1151]
Estou enfrentando este erro

Parse error: syntax error, unexpected T_FUNCTION in /home/lovesegcom/public_html/protected/libs/HHtml.php on line 199

Como resolver?

Imagem anexo

Ps. segue login e senha do cpanel 

-------------------------------------------------
loveseg.com.br/cpanel
login.: lovesegcom
senha.:R3cruta=12x
------------------------------------------------ 
![erro_instalao](https://cloud.githubusercontent.com/assets/13915441/9426205/ef9dc14c-4907-11e5-8262-d52e4226598f.png)

**Comment by WASasquatch** [comment]
You should not provide cPanel access publicly. Wait for help from the developers, they can help you further via email if it is necessary.

**Comment by luke-** [comment]
Make sure you're PHP Version is PHP 5.4+

**Comment by efrj** [comment]
To run Humhub developed with Yii2, the minimum version of PHP to be used is the **5.6.19 version**.
