### ISSUE TITLE
Ohh, something went wrong! CDbConnection is unable to find PDO class "PDO". Make sure PDO is installed correctly.

### ISSUE THREAD

**Issue by arnelirobles** [humhub/humhub#1153]
Hello, I have downloaded the software. When installing on my local server (EasyPHP) everything went smooth. But when i installed in godaddy shared hosting i received an error

Ohh, something went wrong!
CDbConnection is unable to find PDO class "PDO". Make sure PDO is installed correctly.

![capture](https://cloud.githubusercontent.com/assets/3198856/9442681/b74178ee-4aaf-11e5-8846-d258635cd0ad.PNG)

Please help

**Comment by luke-** [comment]
Make sure PDO is installed correctly?
