### ISSUE TITLE
Multiple problems with the upload function

### ISSUE THREAD

**Issue by shenn1801** [humhub/humhub#1154]
I do have multiple problems with the upload function. On the one hand, some files are uploaded without any problems, they can be downloaded regularly and everything works fine. On the other hand, I have files of the same type (e.g. pdf) and of comparable (small) size and/or file name (only lower cases) which can be up- and downloaded but generate an error when opening them after the completion of the download (even though they were not corrupted before upload). The server permissions are ok; I am working with AFS, and all files have been uploaded to the upload-directory (this is the reason, of course, why I can download them - however, only a few of them open correctly). In general, the problem occurs for most xls, xlsx and pdf-files. Only the minority of pdfs can be opened, and - so far - no xls/xlsx at all. When changing the download method ("use x-sendfile...") things got even worse: the upload button and anything else just vanished, and 
![uploadbutton](https://cloud.githubusercontent.com/assets/13894913/9480735/08dfa25e-4b85-11e5-9218-ef8996841a17.jpg)
I had to cancel the upload process (see picture). To me, it seems that there is a kind of encryption taking place when up-/downloading the files that causes the problems. 

A second, albeit minor, problem is that in the case of picture uploads, two symbols will show up (see also attached image). While the first one always creates an error when clicked, the second one works fine. How can the error message be avoided? 
![upload problems](https://cloud.githubusercontent.com/assets/13894913/9480693/cb4dc5e2-4b84-11e5-8663-eaa6c2273b9a.jpg).

Here are my latest Humhub error logs: 

a) system.db.CDbCommand
CDbCommand::execute() fehlgeschlagen: SQLSTATE[23000]: Integrity constraint violation: 19 column id is not unique. Der SQL-Ausdruck war: INSERT INTO YiiCache (id,expire,value) VALUES ('26538d4c151c6aa7ccf973a5e71f53c1',1440540524,:value). in /.../protected/components/ModuleManager.php (68) in /.../protected/components/WebApplication.php (42) in /.../index.php (32)

b) php
Undefined variable: gdImage (/.../protected/modules_core/file/libs/ImageConverter.php:294) Stack trace: #0 /.../protected/vendors/yii/db/ar/CActiveRecord.php(1097): File->afterSave() #1 /.../protected/vendors/yii/db/ar/CActiveRecord.php(806): File->insert() #2 /.../protected/modules_core/file/controllers/FileController.php(106): File->save() #3 /.../protected/modules_core/file/controllers/FileController.php(65): FileController->handleFileUpload() #4 /.../protected/vendors/yii/web/actions/CInlineAction.php(49): FileController->actionUpload() #5 /.../protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #6 /.../protected/vendors/yii/web/filters/CFilterChain.php(133): FileController->runAction() #7 /.../protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #8 /.../protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #9 /.../protected/vendors/yii/web/filters/CInlineFilter.php(58): FileController->filterAccessControl() #10 /.../protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #11 /.../protected/vendors/yii/web/CController.php(291): CFilterChain->run() #12 /.../protected/vendors/yii/web/CController.php(265): FileController->runActionWithFilters() #13 /.../protected/vendors/yii/web/CWebApplication.php(282): FileController->run() #14 /.../protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #15 /.../protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #16 /.../index.php(39): WebApplication->run() REQUEST_URI=/intranet/index.php?r=file/file/upload&objectModel=&objectId= in /.../protected/modules_core/file/libs/ImageConverter.php (294) in /.../protected/modules_core/file/libs/ImageConverter.php (45) in /.../protected/modules_core/file/models/File.php (153) in /.../protected/modules_core/file/controllers/FileController.php (106) in /.../protected/modules_core/file/controllers/FileController.php (65)

**Comment by foxkrak** [comment]
I am not a programmer, most know what the problem alexorlov1 , leave unchecked the X- Sendfile option, Administration / file

sorry my inglish!

**Comment by foxkrak** [comment]
![imagem](https://cloud.githubusercontent.com/assets/16868080/12538562/c4d75e9c-c2c3-11e5-9e7f-10d080747758.JPG)
![imagem2](https://cloud.githubusercontent.com/assets/16868080/12538563/cabf1200-c2c3-11e5-97ce-b9272d026cba.JPG)
