### ISSUE TITLE
How to implement oauth?

### ISSUE THREAD

**Issue by candidosales** [humhub/humhub#1155]
Does anyone have any examples to implement OAuth authentication in Humhub?

Thanks

**Comment by davidjeddy** [comment]
Doing that exact thing right now...

**Comment by candidosales** [comment]
Thanks =D

**Comment by davidjeddy** [comment]
Got basic OAuth2 working via the Yii2 authClient; will be trying to wrap it in a humhub module for distribution via the market place tomorrow.

**Comment by candidosales** [comment]
waiting anxiously! :smile:

**Comment by niedakh** [comment]
we're planning to do something similar, can you push the code somewhere and maybe me & @riomus can help

**Comment by kalints** [comment]
+1 on that - hope to see it soon :)

**Comment by frey1esm** [comment]
Any update on this ?

**Comment by luke-** [comment]
I'm working on this at the moment...

**Comment by candidosales** [comment]
How is the progress?

**Comment by luke-** [comment]
It's finished and will be available in 1.1
https://github.com/humhub/humhub/commit/8191d4ef86e4490da1b0fa4d27f256de106f0f28
