### ISSUE TITLE
Problem in the Arabic language

### ISSUE THREAD

**Issue by mohmtr** [humhub/humhub#1156]
I have a problem in the Arabic languageWhen I write something in the Arabic language puts me question marks instead of words ! 

Can you help solve this problem

![untitled](https://cloud.githubusercontent.com/assets/9054708/9563469/5066ba08-4e8d-11e5-8a37-533db223c3ce.png)

**Comment by luke-** [comment]
Make sure your database is using utf-8

CREATE DATABASE `humhub` CHARACTER SET utf8 COLLATE utf8_general_ci;
