### ISSUE TITLE
Yii version?

### ISSUE THREAD

**Issue by VasileGabriel** [humhub/humhub#1159]
Hey everyone.
Reading around the web I found out that HumHub 0.11 is based on Yii 1.1. However in the documentation it is stated that HumHub modules are identical to Yii 2 modules and from what I know Yii 1.1 is not compatible with Yii 2.
The more I read through Humhub docs, the more I get confused. Some of the pages point to Yii 1.1 docs,  some to Yii 2.
Can someone please explain me what's the relation between HumHUb and Yii and which version of Yii should I learn for HumHub.

**Comment by andystrobel** [comment]
Sorry for this confusion. We currently change everything (website, docs, modules etc.), because we're currently launching the new HumHub 0.20 Release (based on Yii2). So please be patient until tomorrow and definitely learn Yii2 ;-)

**Comment by krai500** [comment]
Hi , I am glad to see humhub with Yii2.
Keep doing the good work.

**Comment by bmsrox** [comment]
When do you launch with yii2??

**Comment by andystrobel** [comment]
Hopefully tonight... but feel free to checkout the current master branch. (It is already the new Yii2 version)

**Comment by bmsrox** [comment]
Is it possible to update from 1 to 2

**Comment by andystrobel** [comment]
Yes :-)

**Comment by samdark** [comment]
Congrats with update.
