### ISSUE TITLE
HumHub 0.20 Isseue about datetime calendar with another language

### ISSUE THREAD

**Issue by krai500** [humhub/humhub#1161]
1. Issue about format datetime calendar problem when save to database.Such as Thai language.
![Image of Yaktocat](http://s9.postimg.org/3sny72tv3/3_9_2558_10_31_48.png)
![Image of Yaktocat](http://s9.postimg.org/o8yypb44v/3_9_2558_10_33_19.png)

**Comment by luke-** [comment]
Thanks, can you please open one issue per bug?

**Comment by krai500** [comment]
My Temporary Solution is setting "dateFormat" at Datepicker widget 
```
<?= $form->field($model, 'date_start')->widget(DatePicker::className(),[
	'dateFormat' => 'yyyy-MM-dd',
	'options' => [
	         'class' => 'form-control',
	          'id' => 'date_start',					
	]
]);?>
```

**Comment by elpardal** [comment]
@krai500 please tell me how to apply this their temporary solution.

**Comment by luke-** [comment]
Community Discussion: http://community.humhub.com/content/perma?id=36626

**Comment by acidjames** [comment]
Hi, This issue is still present in 1.0.0-beta1 with French language

**Comment by luke-** [comment]
Will be fixed in beta.3
