### ISSUE TITLE
User profile posts on the dashboard

### ISSUE THREAD

**Issue by leopaula** [humhub/humhub#1162]
http://community.humhub.com/content/perma?id=34244

**Comment by ValeSauer** [comment]
+1

**Comment by luke-** [comment]
This is not planned, only followed user posts appears on dashboard...

You can reach all user posts, also from unfollowed users via directory -> user posts.
https://community.humhub.com/directory/directory/user-posts

**Comment by leopaula** [comment]
Sorry, My title is a little confuse! I refer to select post destination in "optional user profle post" on the dashboard. There are other users requering this feature: 

http://community.humhub.com/content/perma?id=35761

![humhub_select_post_destination](https://cloud.githubusercontent.com/assets/13361238/9831282/b42f6e4a-5982-11e5-838f-3115e77bb3ff.jpg)
