### ISSUE TITLE
humhub-0.20.0-beta.1 autoload.php ?

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#1165]
Warning: require(C:\wamp\www\humhub/protected/vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp\www\humhub\index.php on line 13

![ekran alintisi](https://cloud.githubusercontent.com/assets/7725575/9656170/0f8ea6d4-523f-11e5-99de-093be56c6e6a.PNG)

Php - Mysql İnfo: http://codepen.io/anon/pen/jbEqzy

@luke-

**Comment by Havok75** [comment]
i have the same problem

**Comment by Kakiho** [comment]
You install according to instructions?
Link to docsumentation: https://www.humhub.org/docs/guide-admin-installation.html
