### ISSUE TITLE
Deletion of any space results in error (0.20 Beta 1)

### ISSUE THREAD

**Issue by demux79** [humhub/humhub#1166]
Deleting a space in the admin panel results in this error:

Oooops... It looks like you may have taken the wrong turn.
Page not found.

**Comment by luke-** [comment]
Can you please provide more details (error message, steps to reproduce)?

**Comment by demux79** [comment]
Sure. I have a demo instance on your server and a stand-alone instance. Both running 0.20 Beta 1 and both have the same error when deleting an existing space.

Login as administrator
Administration
Spaces
Red box with white x for deletion of an existing space
Error message: Oooops... It looks like you may have taken the wrong turn.
Page not found.

URL for the delete action:
http://****/index.php?r=admin%2Fspace%2Fdelete&id=3
