### ISSUE TITLE
Creation of note with etherpad-lite module breaks the stream. Note is not accessible (0.20 Beta 1)

### ISSUE THREAD

**Issue by demux79** [humhub/humhub#1167]
After a new note was created the stream does not load anymore
![image](https://cloud.githubusercontent.com/assets/14108031/9666630/8bcc9624-5277-11e5-9b8c-a8e16d75424e.png)

The same is true if you click on "notes" afterwards
![image](https://cloud.githubusercontent.com/assets/14108031/9666706/f26d4022-5277-11e5-9914-12725dc0c85b.png)

The link:
http://***/index.php?r=space%2Fspace%2Fstream&1=%2Fspace%2Fspace%2Fstream&limit=4&filters=&sort=c&from=&mode=normal&sguid=d9d45135-bb94-4bff-8903-b8465cb1f48b

results in this error:
{"name":"PHP Fatal Error","message":"Class 'humhub\\modules\notes\\widgets\\WallEntry' not found","code":1,"type":"yii\\base\\ErrorException","file":"/var/www/html/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php","line":124,"stack-trace":["#0 [internal function]: yii\\base\\ErrorHandler->handleFatalError()","#1 {main}"]}

Browser console displays this error:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Additionally, the note is not visible in the space. Etherpad-lite standalone is working fine.

**Comment by demux79** [comment]
Link http://****/s/7d14f1e2-bbf9-438a-8cbc-5e490bffbde5/notes/note/create results in this error:

{"name":"Exception","message":"Invalid container type!","code":0,"type":"yii\\base\\Exception","file":"/var/www/html/humhub/protected/humhub/modules/content/models/Content.php","line":609,"stack-trace":["#0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(169): humhub\\modules\\content\\models\\Content->setContainer(NULL)","#1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(267): yii\\base\\Component->__set('container', NULL)","#2 /var/www/html/humhub/protected/humhub/modules/content/widgets/WallCreateContentForm.php(117): yii\\db\\BaseActiveRecord->__set('container', NULL)","#3 /var/www/html/humhub/protected/modules/notes/controllers/NoteController.php(42): humhub\\modules\\content\\widgets\\WallCreateContentForm::create(Object(humhub\\modules\\notes\\models\\Note))","#4 [internal function]: humhub\\modules\\notes\\controllers\\NoteController->actionCreate()","#5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)","#6 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\\base\\InlineAction->runWithParams(Array)","#7 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\\base\\Controller->runAction('create', Array)","#8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\\base\\Module->runAction('notes/note/crea...', Array)","#9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))","#10 /var/www/html/humhub/index.php(25): yii\\base\\Application->run()","#11 {main}"]}

**Comment by luke-** [comment]
Fixed: https://github.com/humhub/humhub-modules-notes/commit/7b37880a769347177c3b1f9b01e2f7eb065de041

**Comment by demux79** [comment]
Thanks, it worked well on one instance. Unfortunately, two other instances fail. Etherpad works fine standalone there as well. Difference on the latter instances is that they run on apache2 port 8080 because nginx is listening on port 80 already. Maybe you can help or tell me if it is a configuration error on my side.

Creating a new note in a space fails
![image](https://cloud.githubusercontent.com/assets/14108031/9713272/a7e27122-5550-11e5-80f6-4de4237243ea.png)

Console output
jquery.js:8630
POST http://***:8080/index.php?r=notes%2Fnote%2Fcreate&sguid=b9b69ab8-e026-43c7-819a-ef338a0310d4 500 (Internal Server Error)

Output of the link
{"name":"Exception","message":"Invalid container type!","code":0,"type":"yii\\base\\Exception","file":"/var/www/html/humhub/protected/humhub/modules/content/models/Content.php","line":606,"stack-trace":["#0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(169): humhub\\modules\\content\\models\\Content->setContainer(NULL)","#1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(267): yii\\base\\Component->__set('container', NULL)","#2 /var/www/html/humhub/protected/humhub/modules/content/widgets/WallCreateContentForm.php(117): yii\\db\\BaseActiveRecord->__set('container', NULL)","#3 /var/www/html/humhub/protected/modules/notes/controllers/NoteController.php(48): humhub\\modules\\content\\widgets\\WallCreateContentForm::create(Object(humhub\\modules\\notes\\models\\Note))","#4 [internal function]: humhub\\modules\\notes\\controllers\\NoteController->actionCreate()","#5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)","#6 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\\base\\InlineAction->runWithParams(Array)","#7 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\\base\\Controller->runAction('create', Array)","#8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\\base\\Module->runAction('notes/note/crea...', Array)","#9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))","#10 /var/www/html/humhub/index.php(25): yii\\base\\Application->run()","#11 {main}"]}

**Comment by demux79** [comment]
Humhub debugging shows this error

exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1364 Field 'updated_by' doesn't have a default value' in /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Command.php:781 Stack trace: #0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Command.php(781): PDOStatement->execute() #1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Schema.php(448): yii\db\Command->execute() #2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(454): yii\db\Schema->insert('note', Array) #3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(424): yii\db\ActiveRecord->insertInternal(NULL) #4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(593): yii\db\ActiveRecord->insert(true, NULL) #5 /var/www/html/humhub/protected/humhub/modules/content/widgets/WallCreateContentForm.php(133): yii\db\BaseActiveRecord->save() #6 /var/www/html/humhub/protected/modules/notes/controllers/NoteController.php(48): humhub\modules\content\widgets\WallCreateContentForm::create(Object(humhub\modules\notes\models\Note)) #7 [internal function]: humhub\modules\notes\controllers\NoteController->actionCreate() #8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array) #10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('create', Array) #11 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('notes/note/crea...', Array) #12 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /var/www/html/humhub/index.php(25): yii\base\Application->run() #14 {main} Next exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1364 Field 'updated_by' doesn't have a default value The SQL being executed was: INSERT INTO `note` (`title`, `created_at`, `created_by`, `updated_at`) VALUES ('Test', NOW(), 1, NOW())' in /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:628 Stack trace: #0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Command.php(791): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `no...') #1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Schema.php(448): yii\db\Command->execute() #2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(454): yii\db\Schema->insert('note', Array) #3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(424): yii\db\ActiveRecord->insertInternal(NULL) #4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(593): yii\db\ActiveRecord->insert(true, NULL) #5 /var/www/html/humhub/protected/humhub/modules/content/widgets/WallCreateContentForm.php(133): yii\db\BaseActiveRecord->save() #6 /var/www/html/humhub/protected/modules/notes/controllers/NoteController.php(48): humhub\modules\content\widgets\WallCreateContentForm::create(Object(humhub\modules\notes\models\Note)) #7 [internal function]: humhub\modules\notes\controllers\NoteController->actionCreate() #8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array) #10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('create', Array) #11 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('notes/note/crea...', Array) #12 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /var/www/html/humhub/index.php(25): yii\base\Application->run() #14 {main} Additional Information: Array ( [0] => HY000 [1] => 1364 [2] => Field 'updated_by' doesn't have a default value )
