### ISSUE TITLE
Provide option to login with social networks / OAuth

### ISSUE THREAD

**Issue by Kovah** [humhub/humhub#117]
It would be really awesome if the user could sign up using his social networks like Facebook, Twitter, G+ or e.g. Github (what I could need).
Are there any plans implementing this (as a module)?

**Comment by Lokke** [comment]
+1

**Comment by dieffrei** [comment]
+1

**Comment by luckycat831** [comment]
+1

**Comment by gamebenchjake** [comment]
+1

**Comment by secondtruth** [comment]
+1

**Comment by WASasquatch** [comment]
+1

**Comment by altendorfme** [comment]
+1

**Comment by kkayacan** [comment]
+1

**Comment by serieznyi** [comment]
+1 vk

**Comment by inluxc** [comment]
+1

**Comment by JeXawoW** [comment]
+1

**Comment by rguedes** [comment]
+1

**Comment by inluxc** [comment]
We can use this generic connector.
http://www.yiiframework.com/extension/loid/

**Comment by eduardonunesp** [comment]
:+1:

**Comment by abedalzain** [comment]
+1

**Comment by kovou** [comment]
+1

**Comment by tgyou** [comment]
+1

**Comment by hubrajesh** [comment]
+1

**Comment by evan70** [comment]
i need connector too :)

**Comment by rafaelabreu** [comment]
+1 
Linkedin!

**Comment by baoc75** [comment]
It's been for a year :(( 
+1 for this project

**Comment by davidjeddy** [comment]
+1

**Comment by paulending** [comment]
+1

**Comment by scrobbleme** [comment]
+1

**Comment by creabrain** [comment]
+1

**Comment by icep87** [comment]
+1

**Comment by jahd2602** [comment]
+1 any guidance on how could this be implemented?

**Comment by luke-** [comment]
@jahd2602 https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/README.md

**Comment by maxlinux2000** [comment]
+2  :)

**Comment by luke-** [comment]
Will be available in 1.1

**Comment by ViraLata** [comment]
I was figthing this days to make this, rigth now I´m working on it, just thought that maybe someone will find this helpful :

First you have to install the library yiisoft/yii2-authclient , is really easy, you just have to edit the file composer.json, you´ll find it on the root folder, find the next piece of code and add the las line, here is mine :

    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.4",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "raoul2000/yii2-jcrop-widget": "*",
        "cebe/markdown": "1.0.2",
        "yiisoft/yii2-jui": "^2.0",
        "zendframework/zend-http": "*",
        "nqxcode/zendsearch": "^2.0",
        "xj/yii2-jplayer-widget": "*",
        "zendframework/zend-ldap": "^2.5",
        "yiisoft/yii2-authclient": "*"
    },

Then you execute this command :

composer update

Next find this file :

humhub/protected/humhub/config/web.php

And add this piece of code :

$config = [
    'id' => 'humhub',
    'bootstrap' => ['humhub\components\bootstrap\LanguageSelector'],
    'defaultRoute' => '/dashboard/dashboard',
    'layoutPath' => '@humhub/views/layouts',
    'components' => [
        'request' => [
            'class' => 'humhub\components\Request',
        ],
        'authClientCollection' => [
          'class' => 'yii\authclient\Collection',
          'clients' => [
            'facebook' => [
              'class' => 'yii\authclient\clients\Facebook',
              'authUrl' => 'https://www.facebook.com/dialog/oauth?display=popup',
              'clientId' => 'yourclientid',
              'clientSecret' => 'yourclientsecret',
            ],
          ],
        ],

Now here is the funny part, we have to change the way the user log in, the usual way is for the user to give his email and we send a "token" in a link to his inbox, the user enter the link we send him and then he can create the account, all of this is manage in the model "invite", but with yii2-authclient is diferent, in the site he chose he want to create an account with his facebook account, he is redirected to facebook and to continue he must give permission, then is redirected to our site to finish the account, so we have to change the email ecenario to the facebook ecenario, the good part is we can do this with our old model "invite" :D, to start this we have to add the facebook icon in the page "new account", for this we have to edit this file:

humhub/protected/humhub/modules/user/views/auth/login_modal.php

In this file find where humhub ask the user to create an email, and add this piece of code :

<?= yii\authclient\widgets\AuthChoice::widget(['baseAuthUrl' => ['/user/auth/auth'], 'popupMode' => false,]) ?>

For me it ended something like this :

 <?php if ($canRegister) : ?>
        <div class="tab-pane <?php echo (isset($_POST['AccountRegister'])) ? "active" : ""; ?>"
             id="register">
             <p>
             <?= yii\authclient\widgets\AuthChoice::widget(['baseAuthUrl' => ['/user/auth/auth'], 'popupMode' => false,]) ?>
			 </p>
            <p><?php echo Yii::t('UserModule.views_auth_login', "Don't have an account? Join the network by entering your e-mail address."); ?></p>
            <?php $form = ActiveForm::begin(); ?>

            <?php echo $form->field($registerModel, 'email')->textInput(['id' => 'register-email', 'placeholder' => Yii::t('UserModule.views_auth_login', 'email')]); ?>
            <hr>

Then we have to open this file :

humhub/protected/humhub/modules/user/controllers/AuthController.php

Find the function actions() and edit it like this :

    public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
            ],
            'auth' => [
            'class' => 'yii\authclient\AuthAction',
            'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

Now in the same file we have to create this function :

    public function onAuthSuccess($client)
    {
        //save the info from the account of facebook in the var $userAttributes
        $userAttributes = $client->getUserAttributes();
        //we look in the table if we already have a token for this user, if not we create one
        $invite = Invite::findOne(['email' => $userAttributes['email']]);
        if ($invite === null) {
            $invite = new \humhub\modules\user\models\Invite();
        }
        //save the info of the user to the model
        $invite->email = $userAttributes['email'];
        $invite->source = $client->getId();
        $invite->token = $userAttributes['id'];
        $invite->language = Yii::$app->language;
        //we save it in the table
        $invite->save();
        //redirect to the action actionCreateAccount() and we send the token
        return $this->redirect(Url::to(['/user/auth/create-account', 'token' => $invite->token]));
        //return Yii::$app->runAction('actionCreateAccount');
        //return $this->redirect('actionCreateAccount');
    }

Now should work :D, remember this is not a full tutorial, is only a small help, is only to create an account, is missing the login, but is an step, I´m still working in mine but I want it to share it.

**Comment by luke-** [comment]
Checkout Branch v1.1-dev https://github.com/humhub/humhub/tree/v1.1-dev it also contains yii2-authclient

**Comment by ViraLata** [comment]
I just checked, is perfect, thanks Luke :)

**Comment by luke-** [comment]
Here is also a little piece of docu :-)

https://github.com/humhub/humhub/blob/v1.1-dev/protected/humhub/docs/guide/admin-adv-auth.md

**Comment by Tobi005** [comment]
when I activate the Facebook-login, it works.
But the common authentification does not work anymore.

Is this known or is it a configuration problem?

(if it is a configuration problem, I did not find a way to activate the default authentification in  the protected\config\common.php file. I just added the code shown in admin-adv-auth.md)

**Comment by Censtudios** [comment]
@ViraLata I'm trying your solution, but I'm unfamiliar with using SSH so I'm not entirely sure how to use your step "composer update". I do have PuTTY. Can you explain in more detail how to do this step? Because when I try to insert 
`<?= yii\authclient\widgets\AuthChoice::widget(['baseAuthUrl' => ['/user/auth/auth'], 'popupMode' => false,]) ?>`
without updating, the signin/signup modal doesn't show up anymore (my guess is because my humhub can't find yii2-authclient.

**Comment by davidjeddy** [comment]
@Censtudios composer is a CLI tool manages package dependency in PHP. Now that you have  updated your configuration file you now need to tell the project to add the new libraries, vis a vis composer. Before jumping in head first with a project as big as HumHub I would recommend some reference reading on DCVS, MVC architecture, dependency management, and composer. Yes, it is a long list but you will thank yourself for it later.

**Comment by davidjeddy** [comment]
@Tobi005 with OAuth if a user makes an account on HH with a OAuth provider, the user then has to use that OAuth provider as the authoritative authentication provider. At the moment I have not seen a way of associating multiple authentication providers to one user account.

**Comment by Censtudios** [comment]
@davidjeddy What if I change the files in this commit manually? https://github.com/humhub/humhub/commit/8191d4ef86e4490da1b0fa4d27f256de106f0f28
It's a lot of work, but if it will make this feature work I'm willing to do it.

**Comment by davidjeddy** [comment]
@Censtudios  That could work, but every time you try to update HumHub you have to manually check the changes. I would recommend extend or override the existing logic as a theme/ module / component class.

**Comment by Censtudios** [comment]
I feel so proud I managed to install composer.phar lol. I went to the public_html directory and did "composer update" so it's doing that now. I'll try to follow those steps again see if it works now. Fingers crossed I don't break my site now..

**Comment by Tobi005** [comment]
@davidjeddy but my already created account (default authentification) can't login anymore.

**Comment by wmfleming** [comment]
Are there any further instructions on getting FB Auth to work with v1.2-dev?  I pulled that branch and trying to get oAuth for FB to work.  I used the following reference: https://github.com/humhub/humhub/blob/v1.2-dev/protected/humhub/docs/guide/admin-adv-auth.md

The problem is that as soon as I add that into the common.php file, the site breaks.  Get a page that says it is not working and unable to handle the request.  Are there other settings or configs that need to be implemented in order to utilize FB auth?

**Comment by buddha87** [comment]
@wmflemming the v1.2-dev branch is an rather unstable developer branch and should not be uses unless you want to contribute to this version. If you want to test consider using the v1.1-dev which should be more stable (but not yet beta)

**Comment by wmfleming** [comment]
@buddha87 I tried using the v1.1-dev branch and when I went to log in after the initial setup, I got a DB error after logging in and trying to load the site.  Gave me a user_id error in contents table.  I couldn't find a column for user_id.  This is why I switched to 1.2-dev.  I will try again and see what happens with v1.1-dev.

**Comment by buddha87** [comment]
ok, if you have trouble installing the v1,1 please open a new ticket.

**Comment by wondersoftheworld** [comment]
social logins seem like a no-brainer feature. why doesn't humhub ship with it? smh..

**Comment by petrk94** [comment]
Any update here?
I thought HuAuth looked good due its provide a lot social networks for use.
Is here still any development?

**Comment by danielkesselberg** [comment]
http://docs.humhub.org/admin-authentication.html
