### ISSUE TITLE
User ranking and permission 

### ISSUE THREAD

**Issue by baoc75** [humhub/humhub#1170]
Hello,
I am looking to add more ranks to my site. Example "Normal Users", "VIP Users", "Community Advisor" just like the "System Administrator" and set permission for every ranks. How to do this?

**Comment by andystrobel** [comment]
On which kind of permission you're thinking for the different user ranks, exactly?

**Comment by baoc75** [comment]
Yes, is this available on Humhub?

**Comment by andystrobel** [comment]
There is no deep role concept at the moment... which kind of permission do you need for the different ranks?

**Comment by baoc75** [comment]
For example: Community Advisor can access to Reported Post and decide which post will be deleted, User approval, Can delete other users post But can't access to Administration page.
