### ISSUE TITLE
Commenting in arabic/hebrew doesn't work

### ISSUE THREAD

**Issue by Palbear** [humhub/humhub#1172]
Hello,

when i comment in arabic/hebrew it doesn't work,it keeps running the three dots. 
English works. 
on humhub demo it did work.

PHP 5.5.27
Zend Engine v2.5.0
MySQL Server version: 5.6.21

Any solution soon?

![screen shot 2015-09-05 at 12 20 54](https://cloud.githubusercontent.com/assets/1853312/9698858/c2b18250-53c9-11e5-84ff-7824baec6924.png)

**Comment by dakur** [comment]
@Palbear : try to open Inspector and watch outgoing traffic. Any errors?

**Comment by Palbear** [comment]
Thanks for your reply. Here is what i get in the console:
<img width="1264" alt="screen shot 2015-09-23 at 19 43 15" src="https://cloud.githubusercontent.com/assets/1853312/10053345/c391cbba-622b-11e5-9c71-0d5c75a837e5.png">

**Comment by luke-** [comment]
Can you provide the 500 error message?

**Comment by Palbear** [comment]
you mean this:

Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD9\x85\xD8\xB1\xD8\xAD...' for column 'message' at row 1
The SQL being executed was: INSERT INTO `comment` (`message`, `object_model`, `object_id`, `created_at`, `created_by`, `updated_at`) VALUES ('مرحبا', 'humhub\\modules\\post\\models\\Post', 1, NOW(), 1, NOW())' 

in /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:628

Stack trace:
#0 /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/db/Command.php(791): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `co...')
#1 /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/db/Schema.php(448): yii\db\Command->execute()
#2 /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(454): yii\db\Schema->insert('comment', Array)
#3 /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(424): yii\db\ActiveRecord->insertInternal(NULL)
#4 /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(593): yii\db\ActiveRecord->insert(true, NULL)
#5 /Users/YJ/Sites/humhub/protected/humhub/modules/comment/controllers/CommentController.php(84): yii\db\BaseActiveRecord->save()
#6 [internal function]: humhub\modules\comment\controllers\CommentController->actionPost()
#7 /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#9 /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('post', Array)
#10 /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('comment/comment...', Array)
#11 /Users/YJ/Sites/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request))
#12 /Users/YJ/Sites/humhub/index.php(25): yii\base\Application->run()
#13 {main}

**Comment by cebe** [comment]
commenting with the string "مرحبا" does work for me on the v1.1-dev branch.
