### ISSUE TITLE
Etherpad module: no value for updated_by gets transferred to MySQL (version 0.20.0 beta1)

### ISSUE THREAD

**Issue by demux79** [humhub/humhub#1174]
Creating a new etherpad-lite note in a space results in a MySQL error for two of my three humhub installations.

No value gets inserted into column "updated_by" in both tables note and note_usercolors. MySQL returns an error because these columns have no default value and may not be null.

See #1167

**Comment by demux79** [comment]
This seems true for a lot of modules (all?). Polls, calendar, notes...

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/88687ea899af7bdbaa1694985cd41bc08cb7d659
