### ISSUE TITLE
Update not Working the two method 0.11 to 0.2

### ISSUE THREAD

**Issue by ychoucha** [humhub/humhub#1175]
Hello, 

i have tried to methode to update, but the methode failed : 

First with git pull :  

Hello i m tryng to update my installation but when i try to git pull i have the abording message : http://pastebin.com/wB3TYfWt

And the second with downloading archive : 

I have tried the second methode update and i have the error :

sudo php yii migrate/upPHP

Fatal error: Class 'CMap' not found in /var/www/html/humhub/protected/config/console.php on line 10

of course i follow the official guide here ---> https://www.humhub.org/docs/guide-admin-updating.html

can we help please ?

**Comment by tobciu** [comment]
did you just pull the master to your HumHub 0.11.2 installation, or did you update it with this guide? https://www.humhub.org/docs/guide-admin-updating-020.html (this guide is for updating humhub 0.11.2 and below)

**Comment by andystrobel** [comment]
Do you trying to upgrade from HumHub 0.11.x to 0.20 ?

**Comment by ychoucha** [comment]
of course im make like the guide says :

first methode : 
 i go on my files server and make a git pull and i have the abording error.

second method  : 

i get the last humhub 0.2 files and copy it on my server, and i copy files like says the guide : 

and still error  : 


"NetworkError: 500 Internal Server Error - http://192.168.17.241/humhub/index.php?r=dashboard%2Fdashboard%2Fstream&limit=4&filters=&sort=c&from=&mode=normal"



{"name":"Exception","message":"Could not get contents underlying object!","code":0,"type":"yii\\base\\Exception","file":"/var/www/html/humhub/protected/humhub/modules/content/components/actions/Stream.php","line":249,"stack-trace":["#0 [internal function]: humhub\\modules\\content\\components\\actions\\Stream->run()","#1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)","#2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\\base\\Action->runWithParams(Array)","#3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\\base\\Controller->runAction('stream', Array)","#4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\\base\\Module->runAction('dashboard/dashb...', Array)","#5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application->handleRequest(Object(humhub\\compo

**Comment by luke-** [comment]
Which method causes the error?

Did you executed:
php yii migrate/up
?

**Comment by ychoucha** [comment]
ok so i start from my humhub working 0.11.2

i m using how to here -----> https://www.humhub.org/docs/guide-admin-updating.html

- First i m tring the update with : >>Git/Composer based installations <<
Show gitPull.txt for details of execution and to resume :
>>>>>
user01 [/var/www/html/humhub] > git pull
...
protected/docs/guide/developer/sett
error: The following untracked working tree files would be overwritten by merge: uploads/file/index.html
....
Please move or remove them before you can merge.
Aborting <<<<<<<<

So i remove the uploads directory :
>>>>>>>>
user01 [/var/www/html/humhub] > sudo rm -R uploads/
user01 [/var/www/html/humhub] > git pull
Mise à jour 67b24d5..c0baab7
error: Your local changes to the following files would be overwritten by merge:
.gitignore
.htaccess.dist
.travis.yml
README.md
....
protected/docs/guide/developer/search.md
protected/docs/guide/developer/sett
Aborting
<<<<<<<<

===========================================
===========================================
===========================================


OK so now i try the second method >>Download Package installations<<

I remove all my humub, and i create a new humhub folder with files found here : https://www.humhub.org/downloads/humhub-0.20.0-beta.1.tar.gz


<<<<<<<<<<
user01 [/var/www/html] > sudo rm -R humhub/
user01 [/var/www/html] > sudo mkdir humhub/
user01 [/var/www/html] > cd humhub/
user01 [/var/www/html] > sudo wget https://www.humhub.org/downloads/humhub-0.20.0-beta.1.tar.gz
user01 [/var/www/html] > sudo tar -xvf humhub-0.20.0-beta.1.tar.gz
user01 [/var/www/html] > cd ..
user01 [/var/www/html] > sudo chown user01:www-data humhub/ -R
>>>>>>>>
Copie my /uploads/*,/protected/runtime,/protected/config/* folders of my old backup to this new humhub 0.2 installation (using filezilla)
<<<<<<
<<<<<<
user01 [/var/www/html] > cd humhub/protected
user01 [/var/www/html] > php yii migrate/up
PHP Fatal error: Class 'CMap' not found in /var/www/html/humhub/protected/config/console.php on line 10
>>>>>>>


Ok so now i give you all step i do, now what i can do to update my humhub please ?
So i musing the two metho to try to update my humhub, but the two method not wokrs.


![humhub_updade_version](https://cloud.githubusercontent.com/assets/301074/9812256/5636ac60-587c-11e5-82bc-f6a54164ee26.jpg)

**Comment by ychoucha** [comment]
U need more details ?
What do u need please ?

**Comment by andystrobel** [comment]
Do you read the first sentence at the the update guide from your link above? That means, that you have to use this guide: https://www.humhub.org/docs/guide-admin-updating-020.html to update from 0.11.2 to 0.20!
