### ISSUE TITLE
Configuring link links in account settings results in unknown method exeption (version 0.20 beta 1)

### ISSUE THREAD

**Issue by demux79** [humhub/humhub#1177]
My profile
Edit account
Modules
Link List - configure

results in:
Unknown Method – yii\base\UnknownMethodException
Calling unknown method: humhub\components\View::beginWidget()

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-linklist/commit/c2b10e4aa47dbb3215ee3310b3df7be95034b4c9
