### ISSUE TITLE
Editing user in admin interface results in NotSupportedException (version 0.20 beta 1)

### ISSUE THREAD

**Issue by demux79** [humhub/humhub#1178]
Adminstrator login
Administration
Users
Chose a user and click on edit button

Results in this error (installing php5-intl makes no difference):
PHP User Error – yii\base\ErrorException

exception 'yii\base\ErrorException' with message 'Exception (Not Supported) 'yii\base\NotSupportedException' with message 'Message format 'number' is only supported for integer values. You have to install PHP intl extension to use this feature.' in /var/www/html/humhub/protected/vendor/yiisoft/yii2/i18n/MessageFormatter.php:347 Stack trace: #0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/i18n/MessageFormatter.php(260): yii\i18n\MessageFormatter->parseToken(Array, Array, 'en-US') #1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/i18n/MessageFormatter.php(93): yii\i18n\MessageFormatter->fallbackFormat('{attribute} sho...', Array, 'en-US') #2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/i18n/I18N.php(114): yii\i18n\MessageFormatter->format('{attribute} sho...', Array, 'en-US') #3 /var/www/html/humhub/protected/humhub/components/i18n/I18N.php(92): yii\i18n\I18N->format('{attribute} sho...', Array, 'en-US') #4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/validators/StringValidator.php(176): humhub\components\i18n\I18N->format('{attribute} sho...', Array, 'en-US') #5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/widgets/ActiveField.php(699): yii\validators\StringValidator->clientValidateAttribute(Object(humhub\modules\user\models\Profile), 'company', Object(humhub\components\View)) #6 /var/www/html/humhub/protected/vendor/yiisoft/yii2/widgets/ActiveField.php(210): yii\widgets\ActiveField->getClientOptions() #7 /var/www/html/humhub/protected/vendor/yiisoft/yii2/widgets/ActiveField.php(200): yii\widgets\ActiveField->begin() #8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/widgets/ActiveField.php(156): yii\widgets\ActiveField->render() #9 /var/www/html/humhub/protected/humhub/compat/HForm.php(169): yii\widgets\ActiveField->__toString() #10 /var/www/html/humhub/protected/humhub/compat/HForm.php(105): humhub\compat\HForm->renderField('company', Array, Array) #11 /var/www/html/humhub/protected/humhub/compat/HForm.php(101): humhub\compat\HForm->renderElements(Array, Array) #12 /var/www/html/humhub/protected/humhub/compat/HForm.php(101): humhub\compat\HForm->renderElements(Array, Array) #13 /var/www/html/humhub/protected/humhub/compat/HForm.php(87): humhub\compat\HForm->renderElements(Array) #14 /var/www/html/humhub/protected/humhub/modules/admin/views/user/edit.php(14): humhub\compat\HForm->render(Object(yii\widgets\ActiveForm)) #15 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/html/h...') #16 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/html/h...', Array) #17 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/var/www/html/h...', Array, Object(humhub\modules\admin\controllers\UserController)) #18 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(371): yii\base\View->render('edit', Array, Object(humhub\modules\admin\controllers\UserController)) #19 /var/www/html/humhub/protected/humhub/modules/admin/controllers/UserController.php(147): yii\base\Controller->render('edit', Array) #20 [internal function]: humhub\modules\admin\controllers\UserController->actionEdit() #21 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #22 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array) #23 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('edit', Array) #24 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('admin/user/edit', Array) #25 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #26 /var/www/html/humhub/index.php(25): yii\base\Application->run() #27 {main}' in /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/ErrorHandler.php:299 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError('<span class="nu...', '<span class="st...', '<span class="st...', '<span class="nu...', '...') #1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(299): trigger_error('<span class="st...', '<span class="nu...') #2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/widgets/ActiveField.php(158): yii\base\ErrorHandler::convertExceptionToError(Object(yii\base\NotSupportedException)) #3 /var/www/html/humhub/protected/humhub/compat/HForm.php(169): yii\widgets\ActiveField->__toString() #4 /var/www/html/humhub/protected/humhub/compat/HForm.php(105): humhub\compat\HForm->renderField('<span class="st...', '[<span class="s...', '[<span class="s...') #5 /var/www/html/humhub/protected/humhub/compat/HForm.php(101): humhub\compat\HForm->renderElements('[<span class="s...', '[<span class="s...') #6 /var/www/html/humhub/protected/humhub/compat/HForm.php(101): humhub\compat\HForm->renderElements('[<span class="s...', '[<span class="s...') #7 /var/www/html/humhub/protected/humhub/compat/HForm.php(87): humhub\compat\HForm->renderElements('[<span class="s...') #8 /var/www/html/humhub/protected/humhub/modules/admin/views/user/edit.php(14): humhub\compat\HForm->render(Object(yii\widgets\ActiveForm)) #9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/html/h...') #10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('<span class="st...', '[<span class="s...') #11 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('<span class="st...', '[<span class="s...', Object(humhub\modules\admin\controllers\UserController)) #12 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(371): yii\base\View->render('<span class="st...', '[<span class="s...', Object(humhub\modules\admin\controllers\UserController)) #13 /var/www/html/humhub/protected/humhub/modules/admin/controllers/UserController.php(147): yii\base\Controller->render('<span class="st...', '[<span class="s...') #14 [internal function]: humhub\modules\admin\controllers\UserController->actionEdit() #15 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array('[<span class="t...', '[]') #16 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams('[<span class="s...') #17 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('<span class="st...', '[<span class="s...') #18 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('<span class="st...', '[<span class="s...') #19 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #20 /var/www/html/humhub/index.php(25): yii\base\Application->run() #21 {main}

**Comment by demux79** [comment]
The same error appears with "add new user" as administrator

**Comment by xaro1** [comment]
Also have this.

**Comment by luke-** [comment]
This was caused by a missing requirement of php-intl.

https://github.com/humhub/humhub/commit/975d7e99077b121f7424652f029c898ad3841858
