### ISSUE TITLE
Add, Translate, Replace Emoji

### ISSUE THREAD

**Issue by baoc75** [humhub/humhub#1179]
Hello, I just check in the file HHtml and go to this line
$emojis = array('Ambivalent', 'Angry', 'Confused', 'Cool', 'Frown', 'Gasp', 'Grin', 'Heart', 'Hearteyes', 'Laughing', 'Naughty', 'Slant', 'Smile', 'Wink', 'Yuck', 'Sleepy'); 

I trying to add more or translate them but not working. The only one I can do is replace Emoji by replace the png files.
So where to translate it? Thanks!

**Comment by buddh4** [comment]
You can overwrite the twemoji path in 1.4 https://github.com/humhub/humhub/blob/develop/protected/humhub/config/common.php#L253
