### ISSUE TITLE
The CSRF token could not be verified.

### ISSUE THREAD

**Issue by arielzg** [humhub/humhub#1182]
After install App and create administrator user, error display "The CSRF token could not be verified"

 Review in log:
2015/09/09 17:08:45 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'El token CSRF no puede ser verificado.' in /var/www/humhub/protected/vendors/yii/web/CHttpRequest.php:1247
Stack trace:
#0 /var/www/humhub/protected/vendors/yii/base/CComponent.php(561): CHttpRequest->validateCsrfToken(Object(CEvent))
#1 /var/www/humhub/protected/vendors/yii/base/CApplication.php(207): CComponent->raiseEvent('onBeginRequest', Object(CEvent))
#2 /var/www/humhub/protected/vendors/yii/base/CApplication.php(178): CApplication->onBeginRequest(Object(CEvent))
#3 /var/www/humhub/index.php(39): CApplication->run()
#4 {main}
REQUEST_URI=/index.php?r=user/auth/login
HTTP_REFERER=http://humhub.rd.local/index.php?r=user/auth/login

Thanks,

**Comment by arielzg** [comment]
Hi,

I have server with detail:
Red Hat Enterprise Linux Server release 6.5
Mysql version: 5.1.71 
PHP 5.4.38 (cli) 
last humhub release 

I have server with detail:
The error show when login and not permit do nothing. The database was created correctly,  the authentication  intendos are save in database.

http://myservidorl/index.php?r=user/auth/login

Thanks,
Ariel

**Comment by luke-** [comment]
Did you enabled cookies?
