### ISSUE TITLE
Theme: can't overwrite anything

### ISSUE THREAD

**Issue by hakido** [humhub/humhub#1183]
Hello there, i got  a issue with theming:
 i took the file from root/protected/humhub/modules/notification/widgets/views/overview.php
and in theme i have this path: root/themes/mytheme/views/notification/widgets/overview.php
this kind of path won't work for anything , and i can't find out why .. only root/themes/mytheme/views/layout/head.php is working cause i link-ed to my css file

**Comment by luke-** [comment]
FYI: I'm currently working on this issue

**Comment by luke-** [comment]
It seems you have another problem, your case works for me:

Copy:
protected/humhub/modules/notification/widgets/views/overview.php
to:
themes/myTheme/views/notification/widgets/overview.php

Modify themed file
![image](https://cloud.githubusercontent.com/assets/4736168/9814155/0e960120-588c-11e5-9c4e-75878a7bd681.png)


![image](https://cloud.githubusercontent.com/assets/4736168/9814161/1bd6123a-588c-11e5-8c1b-5ddd0b492fb0.png)

**Comment by allocenx** [comment]
Oke, i do not know about you, but i have the same problem, as other 3 of my friends, i even downloaded with composer and still wont work... so i guess there is really a problem...

**Comment by allocenx** [comment]
For example, on error view it works, but when it comes about modules, it doesn't work at all, and to be sure, i even asked 3 of my friends to check this out running different sytem operating... so maybe you have a new version or i do not know, its just that it doesnt work as you say, and yes i did 101% according to the documentation for theming,,,, i'll wait for your reply

**Comment by hakido** [comment]
anyone know how to solve this ??? i can't overwrite modules, layouts works just fine

**Comment by luke-** [comment]
@hakido Can you please give an example? I cannot reproduce this problem

**Comment by allocenx** [comment]
He is saying about the version 2 of humhub, 0.20 beta

**Comment by allocenx** [comment]
on version 1 of humhub, it does work perfectly, on version 2 of humhub, is this problem

**Comment by luke-** [comment]
Yes, I've tested in on the current git master  (0.20+)

**Comment by allocenx** [comment]
Hmm, oke, it seems that with the latest git master 0.20+ it works for me now...

**Comment by luke-** [comment]
Ok, perfect - we'll release the 0.20.0-beta.2 soon
