### ISSUE TITLE
Ability of adding markdown in posts and comments

### ISSUE THREAD

**Issue by leopaula** [humhub/humhub#1186]
http://community.humhub.com/content/perma?id=33882

https://guides.github.com/features/mastering-markdown/

Maybe, as an optional in order to show equations like this:

![equation](http://www.forkosh.com/mimetex.cgi?c=sqrt{a^2+b^2})

**Comment by otdftr** [comment]
I second that, at least for character formating (bold and italics...) and maybe headings.  Kind of a poor man's markdown like that would help.

**Comment by pirobase-pfuchs** [comment]
We would also love to see that, e.g. to add code snippets in monospaced fonts etc.
