### ISSUE TITLE
linebreak in start of post (0.20.0-beta.1)

### ISSUE THREAD

**Issue by Guardian1983** [humhub/humhub#1187]
Very weird linebreak in top/start of posts on wall, if you make a linebreak somewhere in the post.
Example, if i write "I'M TESTING" .. All is ok..
But if i write 
"I'M 
TESTING"..
Then the post on the wall has a linebreak in the very start of the post.
So i have to edit the sql and remove the linebreak to make it look correct.
It only happens if i make a linebreak somewhere in the post with enter..
very annoying!
![wrong2](https://cloud.githubusercontent.com/assets/12225536/9841885/82c54d50-5aa6-11e5-980a-f663d2251efe.png)

**Comment by andystrobel** [comment]
It works for me... please checkout the 0.20.0-beta.2 later (we will release today) and test it again.
