### ISSUE TITLE
wrong language about timeinfo (0.20.0-beta.1)

### ISSUE THREAD

**Issue by Guardian1983** [humhub/humhub#1188]
![missing](https://cloud.githubusercontent.com/assets/12225536/9841852/e5640cd6-5aa5-11e5-90c7-b300e9ea7eee.png)
My language setting is set on Danish.
But it still writes "about 3 hours ago", "about 10 hours ago".

**Comment by axeleszu** [comment]
It's an issue with jquerty.timeago.js refer to https://github.com/rmm5t/jquery-timeago/tree/master/locales
