### ISSUE TITLE
space info on dashboard not there? (0.20.0-beta.1)

### ISSUE THREAD

**Issue by Guardian1983** [humhub/humhub#1189]
When on the dashboard, there is no info about what space the posts are.
![missing](https://cloud.githubusercontent.com/assets/12225536/9841819/42cd0a0e-5aa5-11e5-8334-7aa58fab9ccb.png)

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/af76f5a68bfcbbd7fb1d9c7342c346a32d733f65#diff-0edc0fea32fdbd781f384434ed304c3cL5

**Comment by luke-** [comment]
Fixed here: https://github.com/humhub/humhub/issues/1219
