### ISSUE TITLE
wrong language about create Account (0.20.0-beta.1)

### ISSUE THREAD

**Issue by stefanroesler** [humhub/humhub#1191]
Hello,

if i want to create a new account, the labels will be not translated. I think it's a bug in the sourcecode?
 
![bildschirmfoto_2015-09-14_14-08-31](https://cloud.githubusercontent.com/assets/14264016/9849408/24702afa-5aeb-11e5-912f-3e7b614ff852.png)

![bildschirmfoto_2015-09-14_14-12-29](https://cloud.githubusercontent.com/assets/14264016/9849409/247525be-5aeb-11e5-958b-4bc1669729ee.png)

Is there a workaround?

Thx

**Comment by luke-** [comment]
Fixed: https://github.com/humhub/humhub/commit/131d7b0c44bc571165507fd9c41bd3037f7eea6c
