### ISSUE TITLE
Unknown Method – yii\base\UnknownMethodException

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#1195]
![humhub](https://cloud.githubusercontent.com/assets/7725575/9901197/811b3888-5c55-11e5-8b3f-89c36974b708.png)

http://codepen.io/anon/pen/NGxVwE

**Comment by Felli** [comment]
Have you deleted any folder/files, or changed anything within the platform?

**Comment by luke-** [comment]
@JeXawoW Seems that this error happens on our http://translate.humhub.org site - can you please describe the steps to reproduce this error?

**Comment by JeXawoW** [comment]
@luke-  Link List Module *(Configure)*
Broken link: http://translate.humhub.org/index.php?r=linklist%2Flinklist%2Fconfig&sguid=1d601225-6793-4e4f-9a6b-5e4bda0d4f97

![23](https://cloud.githubusercontent.com/assets/7725575/9935837/89a33f7a-5d48-11e5-8151-6534b72b95da.png)

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-linklist/commit/c2b10e4aa47dbb3215ee3310b3df7be95034b4c9
