### ISSUE TITLE
Feed doesn't load when using Cloudflare flexible SSL

### ISSUE THREAD

**Issue by 3ruce** [humhub/humhub#1196]
Running a fresh install of 0.11.2 and using Cloudflare flexible SSL, users can't see any entries in the stream/feed. Turning off Cloudflare flexible SSL and ensuring the site loads with http and not https solved the problem.

I don't think this is similar to https://github.com/humhub/humhub/issues/648 but reading that issue got me thinking about possible causes.

Interestingly, turning on 'Firefox Compatibility Mode' in the Pale Moon browser was one work-around that allowed https to work but it's not the most practical!

**Comment by Censtudios** [comment]
This issue still persists. My members asked me to activate SSL so I did using Cloudflare, but now using the https:// URL for profiles it won't show the stream at all, it's basically just blank where the stream should be. If I visit the same pages with just http then it shows fine.

**Comment by Censtudios** [comment]
For me, when I activated RocketLoad in cloudflare it seemed to work again. According to cloudflare RocketLoad should improve loading time on javascript and make it load more effecient or something, but in my opinion the pages load sliiiightly slower. But worth it to have the feed back lol
