### ISSUE TITLE
Unavble to change Default user group for new users

### ISSUE THREAD

**Issue by petersmithca** [humhub/humhub#1199]
I may be missing something, but everything says I need to set a defaultUserGroup - have been unable to find how to do that, no option on the group edit screen.

I dont want the GroupID dropdown on the registration page.  

I tried setting a default group on the setting table with sql, but still not seeming to do anything.

Thanks for any help!

Note: beta 0.20.9beta.1

**Comment by luke-** [comment]
Thats a bug in beta-1 which is already fixed.
https://github.com/humhub/humhub/commit/1c8dafa219d1edfb4d94da4056e48f7122f039c0
