### ISSUE TITLE
"Add directory" button broken

### ISSUE THREAD

**Issue by serverdonne** [humhub/humhub#1200]
Hi,
in the Files module the "add directory" button seems to do anything.
Actually if I open it in another tab, the form appears correctly and it works.
Debugging with Firebug I think I understood it should show a div-modal but nothing is happening.

I tried with:
 * Iceweasel 38.2.1
 * Chromium 45.0.2454.85

Thanks.

**Comment by luke-** [comment]
This module https://github.com/humhub/humhub-modules-cfiles ?
It's still under development...
