### ISSUE TITLE
Class 'HHtml' not found :: Admin :: Space

### ISSUE THREAD

**Issue by stefanroesler** [humhub/humhub#1201]
Then a admin show the members in a space, there the admin is not a member: "Class 'HHtml' not found"
![bildschirmfoto_2015-09-20_19-07-46](https://cloud.githubusercontent.com/assets/14264016/9981920/1920e6e6-5fcb-11e5-8c9f-db35fa100501.png)

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-linklist/commit/c2b10e4aa47dbb3215ee3310b3df7be95034b4c9
