### ISSUE TITLE
Since update to 0.20.0-beta.1 Latest activity no more works.

### ISSUE THREAD

**Issue by gfriloux** [humhub/humhub#1203]
Hi everyone.

I updated to 0.20.0-beta.1 following https://www.humhub.org/docs/guide-admin-updating-020.html
Since then, the "lastest activity" window no more loads.

My browser tells me : 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://social.friloux.me/index.php?r=dashboard%2Fdashboard%2Fstream&limit=10&from=&mode=activity

From admin logs : 
ERROR  Mon, 21 Sep 2015 22:01:24 +0200  yii\base\Exception
exception 'yii\base\Exception' with message 'Le contenu du add-on ne peut être trouvé' in /home/www/social.friloux.me/protected/humhub/modules/content/components/ContentAddonActiveRecord.php:70 Stack trace: #0 /home/www/social.friloux.me/protected/vendor/yiisoft/yii2/base/Component.php(130): humhub\modules\content\components\ContentAddonActiveRecord->getContent() #1 /home/www/social.friloux.me/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(247): yii\base\Component->__get('content') #2 /home/www/social.friloux.me/protected/humhub/modules/activity/components/BaseActivity.php(160): yii\db\BaseActiveRecord->__get('content') #3 /home/www/social.friloux.me/protected/humhub/modules/activity/components/BaseActivity.php(117): humhub\modules\activity\components\BaseActivity->getUrl() #4 /home/www/social.friloux.me/protected/humhub/modules/activity/models/Activity.php(96): humhub\modules\activity\components\BaseActivity->render() #5 /home/www/social.friloux.me/protected/humhub/modules/content/components/actions/Stream.php(259): humhub\modules\activity\models\Activity->getWallOut() #6 [internal function]: humhub\modules\content\components\actions\Stream->run() #7 /home/www/social.friloux.me/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #8 /home/www/social.friloux.me/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\Action->runWithParams(Array) #9 /home/www/social.friloux.me/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('stream', Array) #10 /home/www/social.friloux.me/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('dashboard/dashb...', Array) #11 /home/www/social.friloux.me/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 /home/www/social.friloux.me/index.php(25): yii\base\Application->run() #13 {main}

I am not a php/web developper, so i cant code anything, or do really technical  stuff in that matter, but i would gladly provide you anything you need to spot the problem.

**Comment by luke-** [comment]
Did you reinstalled all previously enabled modules?

**Comment by gfriloux** [comment]
No, i disabled everything, but once the installation over, i reenabled a few of them using admin panel (not copying old ones manually, and did not enabled thoses marked as uncompatible).

Now, enabling and disabling them all doesnt fix latest activity.

**Comment by luke-** [comment]
You can try to use the integrity checker to validate content/activity entries:
```
cd protected
php yii integrity/run
```

**Comment by gfriloux** [comment]
I had a lot of errors like : 
Deleting content id 36 of type CalendarEntry without valid content object! (yes|no) [no]:yes
Deleting content id 41 of type CalendarEntry without valid content object! (yes|no) [no]:yes
Deleting content id 44 of type CalendarEntry without valid content object! (yes|no) [no]:yes
Deleting file id 19 without existing target! (yes|no) [no]:yes
Deleting file id 20 without existing target! (yes|no) [no]:yes
Deleting file id 21 without existing target! (yes|no) [no]:yes

And then : 
root@jetdail:/home/www/social.friloux.me/protected# php yii integrity/run

*** Performing database integrity checks

Validating: Activity Module (237 entries)
Validating: Comment Module (98 entries)
Validating: Content Module - Wall Entries 323 entries)
Validating: Content Objects (323 entries)
Validating: File Module (360 entries)
Validating: Like (31 entries)
Validating: Notification Module (1 entries)
Validating: Space Module - Spaces (6 entries)
Validating: Space Module - Module (0 entries)
Validating: Space Module - Memberships (31 entries)
Validating: User Module - Users (12 entries)
Validating: User Module - GroupAdmin (0 entries)
Validating: User Module - Password (12 entries)
Validating: User Module - Profile (12 entries)
Validating: User Module - Mentioning (0 entries)
Validating: User Module - Follow (180 entries)
PHP Fatal error:  Class 'CalendarEntry' not found in /home/www/social.friloux.me/protected/humhub/modules/user/models/Follow.php on line 106
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'CalendarEntry' not found'

in /home/www/social.friloux.me/protected/humhub/modules/user/models/Follow.php:106

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
root@jetdail:/home/www/social.friloux.me/protected#

**Comment by luke-** [comment]
Did you really reinstalled the calendar module after 0.20 migration?
If yes, how?

**Comment by gfriloux** [comment]
Yes i installed it after by going to the admin panel, modules page, and clicking install.

**Comment by gfriloux** [comment]
I am back home, and even if i still have this error, latest activity is now working! i guess it got fixed by deletion content IDs.

**Comment by niklasenB** [comment]
I am having the same issue with my activity widget and ran the integrity checks.
To speed it up I removed all PollAnswered entries in activity table - so far so good.
But continuing with the integrity checks, it's throwing an exception on trying to remove other entries:

```
*** Performing database integrity checks

Validating: Polls Module - Answers (49 entries)
Validating: Polls Module - Answers User (323 entries)
Validating: Activity Module (1753 entries)
Validating: Comment Module (241 entries)
Deleting comment id 21 without existing target! (yes|no) [no]:y
Exception 'yii\base\Exception' with message 'Der Inhalt des Addons konnte nicht gefunden werden!'

in /var/www/html/intranet/humhub/protected/humhub/modules/content/components/ContentAddonActiveRecord.php:70

Stack trace:
#0 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/base/Component.php(130): humhub\modules\content\components\ContentAddonActiveRecord->getContent()
#1 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(247): yii\base\Component->__get('content')
#2 /var/www/html/intranet/humhub/protected/humhub/modules/comment/models/Comment.php(120): yii\db\BaseActiveRecord->__get('content')
#3 /var/www/html/intranet/humhub/protected/humhub/modules/comment/models/Comment.php(71): humhub\modules\comment\models\Comment->updateContentSearch()
#4 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(612): humhub\modules\comment\models\Comment->afterDelete()
#5 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->deleteInternal()
#6 /var/www/html/intranet/humhub/protected/humhub/modules/comment/Events.php(64): yii\db\ActiveRecord->delete()
#7 [internal function]: humhub\modules\comment\Events::onIntegrityCheck(Object(yii\base\Event))
#8 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/base/Event.php(188): call_user_func(Array, Object(yii\base\Event))
#9 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/base/Component.php(549): yii\base\Event::trigger(Object(humhub\commands\IntegrityController), 'run', NULL)
#10 /var/www/html/intranet/humhub/protected/humhub/commands/IntegrityController.php(39): yii\base\Component->trigger('run')
#11 [internal function]: humhub\commands\IntegrityController->actionRun()
#12 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#13 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('run', Array)
#15 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('run', Array)
#16 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('integrity/run', Array)
#17 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('integrity/run', Array)
#18 /var/www/html/intranet/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 /var/www/html/intranet/humhub/protected/yii(29): yii\base\Application->run()
#20 {main}
```

**Comment by niklasenB** [comment]
Hello,
I got it working.
After running the migrate/up script once again and clearing the caches I ran:
```
yes | php yii integrity/run
```
on cli which solved all the errors and deleted orphan entries.
