### ISSUE TITLE
Notifications don't dismiss

### ISSUE THREAD

**Issue by axeleszu** [humhub/humhub#1204]
Notifications stay on all user accounts in humhub 2

**Comment by luke-** [comment]
Already fixed in master

**Comment by dalosgit** [comment]
Hi luke, i also have the lastest humhub version and i just receive mails, if i invite a user. But i also want that every user gets a mail after a post automatically. The notification for standard ans user are set corret. Would be very nice from you if you can help me. Kr dalos
