### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by axeleszu** [humhub/humhub#1210]
protected/humhub/modules/content/messages/es/activities_views_created.php should include

return [
    '{displayName} created a new {contentTitle}.' => '{displayName} creó una nueva {contentTitle}.',
];

I assume the translation is missing for other languages too.

Which gives me the doubt, where beside a "new Post" this translation is used? Because in spanish "nueva" applies for female words like "entrada" post, but no for "correo" mail that should say "nuevo"

**Comment by luke-** [comment]
You can add missing translations at http://translate.humhub.org
