### ISSUE TITLE
Installation Error v 0.20 Beta

### ISSUE THREAD

**Issue by ferenczAndras** [humhub/humhub#1211]
Hello, I am getting the following error at installation : 

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
The SQL being executed was: CREATE TABLE `url_oembed` (
`url` varchar(255) NOT NULL,
`preview` text NOT NULL,
PRIMARY KEY (`url`)
)
Error Info: Array
(
    [0] => 42000
    [1] => 1071
    [2] => Specified key was too long; max key length is 767 bytes
)
↵
Caused by: PDOException

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

in C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\db\Command.php at line 781

**Comment by luke-** [comment]
Seems you posted an URL which is longer than 255 chars.

Maybe we should store a hash instead the full url.

**Comment by ferenczAndras** [comment]
I just made a folder : humhub in htdocs folder in xampp  and I tridet to run the site, and after puting the database, user and etc. I got this error.

**Comment by luke-** [comment]
https://www.humhub.org/docs/guide-admin-installation.html Did you followed these steps? Incl. Database creation?

**Comment by WASasquatch** [comment]
Why is the key a string?
