### ISSUE TITLE
Suggestion: Provide Beta Releases with dependencies

### ISSUE THREAD

**Issue by cboulanger** [humhub/humhub#1212]
Hi, I am interested in trying out the betas and providing feedback, but getting all the dependencies with composer doesn't work out for me (at least with the latest beta) - there are version conflicts which cannot be resolved. Can you provide ZIPs with all the needed libraries includes (just as with the 0.11.X version)? That would allow more people to contribute an squash bugs. Thank you.

**Comment by luke-** [comment]
You can find prebuild packages on our website: http://www.humhub.org/downloads
