### ISSUE TITLE
"The format of Birthday is invalid."

### ISSUE THREAD

**Issue by ManseeDK** [humhub/humhub#1214]
I always get the above error message when trying to add birthday to any profile.

I'm using HumHub 0.20.0-beta.2

**Comment by luke-** [comment]
Which language and PHP Version?

**Comment by ManseeDK** [comment]
My web hosting provider writes PHP 5.6.x
I have tried Danish and English (UK & US)

**Comment by luke-** [comment]
Hmm, can you reproduce this error also on our community? (community.humhub.com)

I can't reproduce this..

**Comment by ManseeDK** [comment]
Negative, can't reproduce it on your community. Re-installed the beta.2, same problem. I am now running 11.2 without any problems. If you can't identify the issue, you can close this issue. Thanks for trying
