### ISSUE TITLE
Search error when requesting a non-Latin characters (0.20.0-beta.2)

### ISSUE THREAD

**Issue by Vatarus** [humhub/humhub#1215]
An error occurs when the search query is not in Latin characters.

![search_error](https://cloud.githubusercontent.com/assets/3394915/10152703/ff074842-668f-11e5-986c-06c558fe5d52.png)

**Comment by daglex** [comment]
Same problem

**Comment by jacobmjelde** [comment]
Getting the exact same error when searching for "æøå", using 0.20 beta2 on both Windows Server and Ubuntu Server.
![search_error](https://cloud.githubusercontent.com/assets/6237590/10215086/eef9de16-681e-11e5-97de-8c33fea52531.PNG)

**Comment by luke-** [comment]
Which PHP Version? Cannot reproduce this with "æøå"

**Comment by daglex** [comment]
PHP - Version - 5.4.45-0+deb7u1: Ok!
PHP - GD Extension: Ok!
PHP - INTL Extension: Ok!
PHP - EXIF Extension: Ok!
PHP - Multibyte String Functions: Ok!
PHP - Curl Extension: Ok!
PHP - ZIP Extension: Ok!
LDAP Support: Ok!
PHP - APC Support: Ok!
PHP - SQLite3 Support: Ok!
Permissions - Runtime: Ok!
Permissions - Assets: Ok!
Permissions - Uploads: Ok!
Permissions - Module Directory: Ok!
Permissions - Dynamic Config: Ok!

**Comment by jacobmjelde** [comment]
PHP - Version - 5.5.9-1ubuntu4.13: Ok! 
•PHP - GD Extension: Ok! 
•PHP - INTL Extension: Ok! 
•PHP - EXIF Extension: Ok! 
•PHP - Multibyte String Functions: Ok! 
•PHP - Curl Extension: Ok! 
•PHP - ZIP Extension: Ok! 
•LDAP Support: Warning! (Hint: Optional - Install PHP LDAP Extension and Zend LDAP Composer Package) 
•PHP - APC Support: Ok! 
•PHP - SQLite3 Support: Ok! 
•Permissions - Runtime: Ok! 
•Permissions - Assets: Ok! 
•Permissions - Uploads: Ok! 
•Permissions - Module Directory: Ok! 
•Permissions - Dynamic Config: Ok!

**Comment by daglex** [comment]
Excellent running search.
