### ISSUE TITLE
Welcome to %aapName%

### ISSUE THREAD

**Issue by AlphabetoPT** [humhub/humhub#1217]
Hello, 
First of all THANK YOU!
I just love humhub.

However there's a little bug i would like to fix but i simply cant find where it is located due to giant number of files.

When people register it's showing this message:
http://prntscr.com/8m0s1d
Translated: "Welcome to %aapName%"

How can i fix it? I bet it's just a typo on the .php file.
Perhaps %appName%?

If you want to check by yourself -> http://www.zionportugal.com

Thank you guys!
Keep up the good work

**Comment by JeXawoW** [comment]
![screenshot from 2015-09-30 05 29 04](https://cloud.githubusercontent.com/assets/7725575/10185129/30e1f4a8-6734-11e5-97da-ab50a9e71273.png)

**Comment by AlphabetoPT** [comment]
Did you fixed?
Or you just can't see what i see?
Thanks

**Comment by WASasquatch** [comment]
`%appName%` is a placeholder, replaced by PHP with your applications name from the database settings. It's meant to say that. That's why it says your applications name in the email for @JeXawoW

**Comment by AlphabetoPT** [comment]
Then why is it showing up as %aapName% instead the actual name of the network?
i am using thunderbird.
My members are also complaining about this.

**Comment by luke-** [comment]
Was a problem in the PT translation, which is fixed now:

https://github.com/humhub/humhub/commit/af76f5a68bfcbbd7fb1d9c7342c346a32d733f65#diff-0edc0fea32fdbd781f384434ed304c3cL5

**Comment by AlphabetoPT** [comment]
Hello. how do i fix it?
i am n00b in this area.

**Comment by WASasquatch** [comment]
Upgrade or replace the files indicated in the link.

On Mon, Oct 5, 2015 at 3:18 AM, AlphabetoPT <notifications@github.com>
wrote:

> Hello. how do i fix it?
> i am n00b in this area.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/1217#issuecomment-145488288>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*
