### ISSUE TITLE
no modules in table notification after upgrade

### ISSUE THREAD

**Issue by tobciu** [humhub/humhub#1218]
hey,
after migration from 0.11.2 to 0.20.0-beta1 some users having problems with the notifications. when users perfom a click on the notifications icon, there getting an error: {name: "Internal Server Error", message: "There was an error at the server.", code: 0, status: 500}

after research i found, there getting this because in the table notification, there are entries with no module
![notifications_nomodule](https://cloud.githubusercontent.com/assets/3367991/10187321/fc2cd056-6757-11e5-9fa5-8f2cd4d399be.png)

when i update an entry, the error is gone

**Comment by luke-** [comment]
@tobciu entries (e.g. Space Invite) without module id doesn't produce an error on my installation. Can you provide the full 500 error message?

**Comment by luke-** [comment]
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/notification/migrations/m150714_100355_cleanup.php

For example this migration should set some module fields e.g. for Space Invites during Migration
