### ISSUE TITLE
multiple groups to one user

### ISSUE THREAD

**Issue by marvink** [humhub/humhub#122]
To get a more powerfull right system it would be nice to add multiple groups to one user.

**Comment by ziegenberg** [comment]
+1

**Comment by programguy** [comment]
+1 I really need this.

**Comment by sgregori** [comment]
+1 - I need it also... ;)

**Comment by ManseeDK** [comment]
+1 that would be great

**Comment by JeXawoW** [comment]
+1

**Comment by buddha87** [comment]
This will be part of Version 1.1.

**Comment by MatthiasHertel** [comment]
+1
