### ISSUE TITLE
Anheften in Beta 0.2 funktioniert nicht

### ISSUE THREAD

**Issue by robertfels** [humhub/humhub#1221]
Ich habe gerade das neuste Beta Update installiert. Wenn ich auf einen Beitrag klicke und diesen anheften möchte, dann springt die Seite lediglich nach ganz oben, allerdings wird der Beitrag nicht sticky.

Es scheint als sei keine Funktion hinter der Auswahl.

**Comment by luke-** [comment]
Hmm, ich kann das Problem leider mit der 0.20.0-beta.2 nicht nachvollziehen.

Gibt es evtl. einen Javascript Fehler?
