### ISSUE TITLE
No autoload.php | Installation not possible

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#1222]
``` txt
Warning: require(***/public_shtml/protected/vendor/autoload.php): failed to open stream: No such file or directory in ***/public_shtml/index.php on line 13

Fatal error: require(): Failed opening required '***/public_shtml/protected/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in ***/public_shtml/index.php on line 13
```

**Comment by allocenx** [comment]
Because if you would read documentation, which you did not, you would have seen that humhub requires some dependencies and you need to install them with composer, please go and read the documentation ;).

**Comment by WASasquatch** [comment]
Yeah, I did. It's only two commands ran. Lol I read the documentation fine.
Composer installed fine. Composer downloaded prerequisites, and then
updated.

On Thu, Oct 1, 2015 at 1:25 AM, allocenx <notifications@github.com> wrote:

> Because if you would read documentation, which you did not, you would have
> seen that humhub requires some dependencies and you need to install them
> with composer, please go and read the documentation ;).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/1222#issuecomment-144653935>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*

**Comment by allocenx** [comment]
I don't know about you, but for me worked pretty fine downloading the dependencies.

**Comment by WASasquatch** [comment]
It didn't mention any errors or anything. There were some "Yellow"
dependencies installing as apposed to green texted ones. Not sure what that
means.

On Sat, Oct 3, 2015 at 12:38 AM, allocenx <notifications@github.com> wrote:

> I don't know about you, but for me worked pretty fine downloading the
> dependencies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/1222#issuecomment-145211976>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*

**Comment by luke-** [comment]
@WASasquatch You can also use prebuild packages which doesn't require composer https://www.humhub.org/en/download/

**Comment by 001101** [comment]
Reproduced successfull!

git checkout stable - was not possible (no .git files in dir)

composer was running, also composer update

I think the Install Guide needs a refresh!!

**Comment by WASasquatch** [comment]
> *edit: Think the cp -R command on debian don't copy "dot dirs", so there was not .git at webroot

That actually sounds very much like the issue. Thanks for pointing that out.
