### ISSUE TITLE
Custom page Module: Bug when deleting from Space (0.20 beta2)

### ISSUE THREAD

**Issue by jacobmjelde** [humhub/humhub#1223]
When creating a custom page from administration eg. "PageA", and creating a page for a space eg. "PageB", a conseqent deletion of "PageB" will result in "PageA" being deleted instead of "PageB".
There seems to be no way to delete "PageB", apart from uninstalling the module.

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-custom-pages/commit/44b08049e13431645c077a9b685d981104f8275a 

Fixed in custom pages module
