### ISSUE TITLE
Buggy spaces?: 0.20beta2

### ISSUE THREAD

**Issue by jacobmjelde** [humhub/humhub#1224]
I have 2 users, who are in the same group (grouping shouldn't matter in this case).

Space availability:
UserA creates a space with the settings "Everyone can join" and "Public". I would expect this space to available for UserB in Directory -> Spaces....but it's not. Although UserB can see the space in the "New spaces"-widget on this page. When UserB clicks the space in the widget he can see the space page, but anything UserA has posted in it is gone...."This space is still empty"...i would expect a non-member of a public space to be able to read, but not post.

Space following:
From the space-page UserB can "Follow" the space. I would expect anything posted in UserA's space, that UserB follows, would be listed on UserB's dashboard. Only if UserB becomes a member of UserA's space, the posted content from the space is available on UserB's dashboard.....which in turn makes "Following" pointless....im sure this ain't how it's supposed to work :-)

I have cache disabled, and have tried rebuilding the search-index....with no luck :-(

**Comment by luke-** [comment]
@jacobmjelde About space following, only "Public" flagged content is available for Space followers. - We're going to ease this in the next release (0.21).
