### ISSUE TITLE
Ampersands in URL's in Wiki broken (and perhaps elsewhere)

### ISSUE THREAD

**Issue by petersmithca** [humhub/humhub#1226]
Per Lucas Bartholemy 10 days ago (from community)
@Peter Smith Thank you for the description, seems that this commit causes the problem: https://github.com/humhub/humhub/commit/7e081d4363ae5305a82c735cc3fa444288e72e97

**Comment by luke-** [comment]
@petersmithca Thank you for creating an issue for this!

**Comment by petersmithca** [comment]
No problem, wasn't sure if there was a protocol I should follow, but wanted to get it noted as it really affects me.  If there is a better procedure I should follow, please let me know. Really like this project, and while I'm really stretched for time, maybe in future I can help contribute further.
