### ISSUE TITLE
DEV - Database Exception – yii\db\Exception

### ISSUE THREAD

**Issue by RHansmann** [humhub/humhub#1228]
v0.21-dev: Administration -> Settings - Self test & Updates

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'contentcontainer' already exists
 The SQL being executed was: CREATE TABLE `contentcontainer` (
 `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `guid` varchar(255),
 `class` varchar(255),
 `pk` int(11),
 `owner_user_id` int(11),
 `wall_id` int(11)
 ) 
Error Info: Array
(
    [0] => 42S01
    [1] => 1050
    [2] => Table 'contentcontainer' already exists
)

↵ 
Caused by: PDOException 

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'contentcontainer' already exists

in D:\Apache\htdocs\humhub\protected\vendor\yiisoft\yii2\db\Command.php at line 781

$_GET = [
    'r' => 'admin/setting/self-test',
];

$_SERVER = [
    'HTTP_ACCEPT' => 'text/html, application/xhtml+xml, image/jxr, */*',
    'HTTP_REFERER' => 'http://localhost/humhub/index.php?r=admin%2Fsetting%2Foembed',
    'HTTP_ACCEPT_LANGUAGE' => 'de-DE,de;q=0.5',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
    'HTTP_HOST' => 'localhost',
    'HTTP_CONNECTION' => 'Keep-Alive',
    'HTTP_COOKIE' => 'pm_getting-started-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_space-members-panel=expanded; language=06aad97f29803e48cc05463333fb92ade86a6a78839a34add49a5ef0bdda0ed0a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22de%22%3B%7D; PHPSESSID=ilvna3l78ta0tv4sph1fgeugn7; Elgg=pd71i0ljcl36dineikqgutl7m3; 527e9064605f5c354d9fa907d44f829e=h74omahs45r80p09mkd6tttjq2; _csrf=14e8d1b13aefb00ec85aeb222470a45ad7da57d799afe898ead69f2b9cea4618a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22XFoJKu_R6tgF38pUVxR7hDFSH4PQz0rD%22%3B%7D; _identity=07656d1da6d75a6ab946637ca18536932be8ff79529b4ab65ea1dc3cfff18b19a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22ca443bdf-c19a-4a5a-95a1-dd0dd239b0d7%22%2C2592000%5D%22%3B%7D',
    'PATH' => 'C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Perl\\site\\bin;C:\\Program Files (x86)\\Perl\\bin;C:\\Program Files\\Perl64\\site\\bin;C:\\Program Files\\Perl64\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\OpenCL SDK\\2.0\\bin\\x86;C:\\Program Files (x86)\\Intel\\OpenCL SDK\\2.0\\bin\\x64;C:\\Program Files\\MySQL\\MySQL Server 5.1\\bin;C:\\Program Files (x86)\\WinMerge;C:\\Program Files\\php5;C:\\Program Files\\nodejs\\;C:\\ProgramData\\ComposerSetup\\bin;C:\\Program Files (x86)\\Skype\\Phone\\;',
    'SystemRoot' => 'C:\\WINDOWS',
    'COMSPEC' => 'C:\\WINDOWS\\system32\\cmd.exe',
    'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
    'WINDIR' => 'C:\\WINDOWS',
    'SERVER_SIGNATURE' => '',
    'SERVER_SOFTWARE' => 'Apache/2.4.16 (Win64) PHP/5.6.12',
    'SERVER_NAME' => 'localhost',
    'SERVER_ADDR' => '::1',
    'SERVER_PORT' => '80',
    'REMOTE_ADDR' => '::1',
    'DOCUMENT_ROOT' => 'D:/Apache/htdocs',
    'REQUEST_SCHEME' => 'http',
    'CONTEXT_PREFIX' => '',
    'CONTEXT_DOCUMENT_ROOT' => 'D:/Apache/htdocs',
    'SERVER_ADMIN' => 'admin@syconics.de',
    'SCRIPT_FILENAME' => 'D:/Apache/htdocs/humhub/index.php',
    'REMOTE_PORT' => '61277',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => 'r=admin%2Fsetting%2Fself-test',
    'REQUEST_URI' => '/humhub/index.php?r=admin%2Fsetting%2Fself-test',
    'SCRIPT_NAME' => '/humhub/index.php',
    'PHP_SELF' => '/humhub/index.php',
    'REQUEST_TIME_FLOAT' => 1444084212.358,
    'REQUEST_TIME' => 1444084212,
];

$_COOKIE = [
    'pm_getting-started-panel' => 'expanded',
    'pm_new-people-panel' => 'expanded',
    'pm_user-statistics-panel' => 'expanded',
    'pm_space-members-panel' => 'expanded',
    'language' => '06aad97f29803e48cc05463333fb92ade86a6a78839a34add49a5ef0bdda0ed0a:2:{i:0;s:8:"language";i:1;s:2:"de";}',
    'PHPSESSID' => 'ilvna3l78ta0tv4sph1fgeugn7',
    'Elgg' => 'pd71i0ljcl36dineikqgutl7m3',
    '527e9064605f5c354d9fa907d44f829e' => 'h74omahs45r80p09mkd6tttjq2',
    '_csrf' => '14e8d1b13aefb00ec85aeb222470a45ad7da57d799afe898ead69f2b9cea4618a:2:{i:0;s:5:"_csrf";i:1;s:32:"XFoJKu_R6tgF38pUVxR7hDFSH4PQz0rD";}',
    '_identity' => '07656d1da6d75a6ab946637ca18536932be8ff79529b4ab65ea1dc3cfff18b19a:2:{i:0;s:9:"_identity";i:1;s:50:"[1,"ca443bdf-c19a-4a5a-95a1-dd0dd239b0d7",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/',
    '__id' => 1,
];
 

2015-10-06, 00:30:13

Apache/2.4.16 (Win64) PHP/5.6.12

Yii Framework/2.0.6

**Comment by luke-** [comment]
Can you please retry it?
