### ISSUE TITLE
Error when you click on the Users tab in the admin

### ISSUE THREAD

**Issue by daglex** [humhub/humhub#1229]
After the update when linking http://site.ru/admin/user get an error

ERROR  Wed, 07 Oct 2015 20:53:02 +0300 

yii\base\ErrorException:64
exception 'yii\base\ErrorException' with message 'Can't use method return value in write context' in /var/www/nesterenko/data/www/humunity.ru/protected/humhub/modules/admin/models/UserSearch.php:91 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}

**Comment by luke-** [comment]
@daglex Can you please check the fix? Thanks!

**Comment by daglex** [comment]
Now, great! Thank you too.
