### ISSUE TITLE
Translate website

### ISSUE THREAD

**Issue by FelixINX** [humhub/humhub#1234]
Hi,

It is possible to publish the website files / or the translate files, for multilanguage version?

Thanks!

**Comment by dakur** [comment]
Use this page: http://translate.humhub.org/
There is also translation tool.

**Comment by luke-** [comment]
Our website http://humhub.org?

**Comment by FelixINX** [comment]
@luke-  Yes exactly. Haven't found a way yet, and not with the link of @dakur
