### ISSUE TITLE
CRM Module?

### ISSUE THREAD

**Issue by joshterrill** [humhub/humhub#1235]
In the screenshot on the home page, there's a link under the modules section that says CRM. I can't find one in the marketplace... does this mean that it will eventually be available? Or is it just for show?

**Comment by WASasquatch** [comment]
It's just for show. As far as I know they planned on releasing a Dropbox plugin and other stuff, but instead never did. Other plugins shown are private for clients, which I find is highly irresponsible to then show in a public open source release image.

**Comment by joshterrill** [comment]
Thanks for the information.

**Comment by zeleski** [comment]
eles não vão liberar o modulo CRM ?
