### ISSUE TITLE
Install Humhub without php intl

### ISSUE THREAD

**Issue by waynejuckts** [humhub/humhub#1236]
Would it be possible? Because my provider is not able to activate it? All the other requirements are not an issue. Thanks!

**Comment by krisak** [comment]
Same here!

**Comment by davidjeddy** [comment]
Would not recommend trying it. php-intl extension is used to help make applications i17n capable, which Yii2 by design. I'd find a new host as it does not sound like the one you have is up to speed.

**Comment by waynejuckts** [comment]
That`s not helpful...

**Comment by krisak** [comment]
Seems reasonable to me. Thanks, for clarification.

**Comment by EXC0DE** [comment]
it's posible to install without INTL , the Requirements is not so important for developing the the site or creating themes , if you remove the intl in the registration  the only affected is the Date and Location , here's the link of the script to bypass the intl requirements https://github.com/EXC0DE/bypass-humhub-intl/issues/1

**Comment by EXC0DE** [comment]
also after you have done to install , you can back the script into original :)

**Comment by cebe** [comment]
> php-intl extension is used to help make applications i18n capable, which Yii2 is by design

FYI: Yii has some fallback mechanisms that work fine with english-only environment. If you need other locale or language you should enable intl.

**Comment by EXC0DE** [comment]
Yup , intl is important , Once you need to online your site ,
