### ISSUE TITLE
Unarchive an archived post in space

### ISSUE THREAD

**Issue by zaidysf** [humhub/humhub#1237]
Hi, how to unarchive an archived post in space? thanks.

**Comment by zaidysf** [comment]
where i can find that "Unarchive" button on app?

**Comment by Aleks-2019** [comment]
Good time of day, how did you find this **button**? I can't find her either ...

**Comment by rsimai** [comment]
I think that's a misunderstanding. That button archives the whole space, not a single post.

But I have the same question: how do I (access and) unarchive a post? They seem to be gone to Nirvana when archived ...

**Comment by buddh4** [comment]
You inclue archived posts in the stream filter, but we probably should rather implement a "Only archived content" filter.

**Comment by rsimai** [comment]
You're right, thanks! Archived posts appear in the search but for convenience there should be a filter. It however won't solve the actual question. Funny enough I can still move archived posts to other spaces but: how to "unarchive" a post?

**Comment by buddh4** [comment]
![grafik](https://user-images.githubusercontent.com/9800854/78351414-05789c00-75a7-11ea-8be7-9f5cc8686ead.png)

I've opened a feature request, thanks for the feedback https://github.com/humhub/humhub/issues/3968
