### ISSUE TITLE
Bug: Some spaces are not showing up

### ISSUE THREAD

**Issue by zaidysf** [humhub/humhub#1238]
![issue](https://cloud.githubusercontent.com/assets/5093672/10450319/c65a0824-71c3-11e5-94b0-698a00a8ce93.png)
note : i've checked the record of those spaces on database.
sorry for my english.
thanks.

**Comment by andystrobel** [comment]
Can it be, that these 2 missing spaces are private spaces? Because private spaces will not showing up at the directory.

**Comment by zaidysf** [comment]
i think that image describes it. 
total spaces = 13
private spaces = 5
public spaces = 8
amount of spaces in page directory = 6 (it should be 8)

**Comment by luke-** [comment]
Maybe related to https://github.com/humhub/humhub/issues/1224 ?

**Comment by zaidysf** [comment]
it's different i think.
the first 2 spaces in New Pages tab are unsearchable eventhough i search it via search feature on topmenu.
suggestion : why spaces dir doesn't use same query as new spaces and add some conditional?

**Comment by luke-** [comment]
Which version do you use?

Did you tried to rebuild the search index?

The snippet shows the spaces directly from the database while the page itself shows the spaces from search index.

**Comment by zaidysf** [comment]
i'm using version 0.11.2.
no, i didn't.
one thing that makes me confused, why the query that is used in the "protected->modules_core->directory->controllers->DirectoryControllers->actionSpaces()" query different from those used in "protected->modules_core->directory->widgets->NewSpacesWidget" ?
thanks anyway.
