### ISSUE TITLE
LDAP Filter - max character

### ISSUE THREAD

**Issue by npeter88** [humhub/humhub#1244]
The userFilter in the ldap setting allow only 100 characters. But for long and more the one or two rules we need more than 100 characters. Please remove this limit.

Workaround:
Change the userFilter in phpmyadmin under "settings - userFilter". Then remove the cache under "humhub\protected\runtime\cache". Reload the ldap settings site and the new status is shown up.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/1368
