### ISSUE TITLE
New Idea One user login for humbub and wordpress

### ISSUE THREAD

**Issue by danielrodd** [humhub/humhub#1247]
I'm trying to merge and integrate my wordpress login to my humhub login directly from phpmyadmin and the user modules_core components.
What I have in mind is to
First,
include all wordpress tables into the same humbhub database since they have different names and don't generate conflict.
Secondly,
I would like the main core user module to update and read from wp_users database table upon user registration and read from it whenever it logs in to humhub.
Kind of like a double resgister and log in. This way, humhub users only register once and can inmediately use wordpress from within humhub by using custom links and iframes.

I would also like it to leave humhub user_password untouched but create an extra record with wordpress encryption and salt used to update user_pass in the wp_users table as well.

Finally I would like it to update user_email and the remaining columns in the wp_users table which aren't as many as the ones in humhub.

This would allow users to enjoy a fast private messaging system through a social network feel like environment, but also have access to a powerful multisite wordpress, all with one superuser alone, handled mainly by humhub.

Is it easy for c components to udpate and read those extra columns in a hidden duplicated way upon registry?

I'm stuck and don't know where to start, any ideas?

What this would mean is that upon new user registration, instead of creating just one username, it would copy the user inputs information into a hidden field that would then go to the wordpress table (wp_users), and instead of encrypting just one password, it's actually going to encrypt two using the same user password input information, one public with normal functionality for humhub and one hidden for wordpress integration directly on database.
I'm willing to pay for this, please help!

**Comment by tobciu** [comment]
hey, you can create a module with all the models connected to a 'second database' -> http://www.yiiframework.com/forum/index.php/topic/58498-using-more-than-one-database-in-the-application/
this module can also provide a additional login mechanism which can use both login routines (humhub and wordpress)
you can override the configuration ( https://github.com/humhub/humhub/blob/master/protected/humhub/config/web.php#L12-L16 ) so you can use your own User-Model and Login-Controller

**Comment by danielrodd** [comment]
I appreciate your suggestion tobciu, I still haven't tried this, I'm researching from heaven to hell for a way to do this smoothly. I asked on stackoverflow and got this answer, what do you think?

http://stackoverflow.com/questions/33303105/how-can-i-use-a-different-login-signup-mechanism-for-wordpress/33303887#33303887

I've spread my research to filter down a few suggestions online that have been there for a few years and are probably no longer compatible with yii 2.0, after reading for almost a week non stop I've found what could perhaps be the most accurate information:

(Maybe create a plugin in wordpress http://cornernote.github.io/yii-embed-wordpress/
and then follow this: 
http://stackoverflow.com/questions/33303105/how-can-i-use-a-different-login-signup-mechanism-for-wordpress/33303887#33303887)
(maybe change the table names in migration files to match those of wordpress and use just one database with all the tables in it for both applications?

http://stackoverflow.com/questions/471416/how-do-you-write-a-migration-to-rename-an-activerecord-model-and-its-table-in-ra#comment19407463_471416
)

This is the most popular thread out there but after reading all the comments, even the ones that link to other related forum topics, it seems to be an outdated, complicated, and incomplete approach for a simple login and sign up authentication.
http://www.yiiframework.com/wiki/322/integrating-wordpress-and-yii-still-another-approach-using-yii-as-the-router-controller/

I'm willing to pay for this, I'm creating a beautiful LMS that will run MOOCs, a Job dashboard that connects public company listings with teachers profiles, a questions answers point based knowledge center and a booking center with a google hangouts api conference classroom. All of these run on multise wordpress. What I'm basically doing is using humhub's beautiful user and social interface to replace buddypress's which is robust and slow to say the least. I'm disabling wordpress login altogether to manage users from yii's humhub :)

The project is here my.rodd.co, thank you in advance for all your help.

**Comment by davidjeddy** [comment]
@danielrodd Are you familiar with OAuth2 authentication? It may be easier to add OAuth to your Wordpress and Humhub applications; use a single authority to validate user identity. We wrote a bridge for Yii2 Authenticator as a Humhub module and has been working splendidly. Just an idea to float your direction.

**Comment by devcline** [comment]
some new about this feature? thanks

**Comment by jamoralesr** [comment]
@danielrodd 
You can use this:

1.- http://code.tutsplus.com/tutorials/wp-rest-api-setting-up-and-using-basic-authentication--cms-24762
2.- http://code.tutsplus.com/tutorials/wp-rest-api-setting-up-and-using-oauth-10a-authentication--cms-24797

**Comment by djcf** [comment]
I don't know how far you got in this project. We are doing something very similar with drupal and LDAP. I feel a post-mortem or retrospective on your project would be extremely useful for the community.

**Comment by cebe** [comment]
since Humhub 1.1, it is possible to use OAuth or other authentication providers.
