### ISSUE TITLE
no emails sent: Zend_Search_Lucene_Exception

### ISSUE THREAD

**Issue by sdsBG** [humhub/humhub#1248]
- cronjob is working
- no email was sent
- PHP 5.4.42
- get every hour this error message:

may somebody can help!

exception 'Zend_Search_Lucene_Exception' in /protected/vendors/Zend/Search/Lucene/Storage/File/Filesystem.php:67 

Stack trace: 
#0 /protected/vendors/Zend/Search/Lucene/Storage/Directory/Filesystem.php(184): Zend_Search_Lucene_Storage_File_Filesystem->__construct('/www/htdocs/w01...', 'w+b')
 
#1 /protected/vendors/Zend/Search/Lucene/Index/Writer.php(411): Zend_Search_Lucene_Storage_Directory_Filesystem->createFile('segments_24r', false) 

#2 /protected/vendors/Zend/Search/Lucene/Index/Writer.php(805): Zend_Search_Lucene_Index_Writer->_updateSegments() 

#3 /protected/vendors/Zend/Search/Lucene.php(1456): Zend_Search_Lucene_Index_Writer->optimize() 

#4 /protected/vendors/Zend/Search/Lucene/Proxy.php(518): Zend_Search_Lucene->optimize() 

#5 /protected/libs/HSearch.php(151): Zend_Search_Lucene_Proxy->optimize() 

#6 /protected/commands/shell/ZCron/ZCronRunner.php(77): HSearch->Optimize() 

#7 /protected/vendors/yii/console/CConsoleCommandRunner.php(71): ZCronRunner->run(Array) 

#8 /protected/vendors/yii/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array) 

#9 /protected/vendors/yii/base/CApplication.php(180): CConsoleApplication->processRequest() 

#10 /protected/yiic.php(26): CApplication->run() 

#11 /protected/yiic(5): require_once('/www/htdocs/w01...') 

#12 {main} ---

**Comment by luke-** [comment]
Can you try to rebuild the search index?

```
cd protected
php yiic search rebuild

**Comment by sdsBG** [comment]
Great!
It’s working!!

Thank you!


Von: Lucas Bartholemy [mailto:notifications@github.com]
Gesendet: Dienstag, 20. Oktober 2015 14:39
An: humhub/humhub
Cc: Groetzner, Benjamin - Solar-Log
Betreff: Re: [humhub] no emails sent: Zend_Search_Lucene_Exception (#1248)


Can you try to rebuild the search index?

cd protected

php yiic search rebuild
