### ISSUE TITLE
Create user

### ISSUE THREAD

**Issue by PiCTaTe** [humhub/humhub#1249]
Hi,

I'm implementing humhub in my enterprise.

We have another applications, with users on database.

I want migrate users from another bd (with username and password(md5), but on humhub database, i'm viewing one table "salt".

It is possible disable this column.

If no, how i can migrate the users?

**Comment by 3cst4sy** [comment]
leave it empty...should work

**Comment by davidjeddy** [comment]
You could also change the Yii2 user authentication / identity to use the database/table of your currently existing system.
