### ISSUE TITLE
preg_match(): Compilation failed: invalid UTF-8 string at offset 8

### ISSUE THREAD

**Issue by PiCTaTe** [humhub/humhub#1250]
Hi,

When i try to search an user in directory (with special characters), i have this error:

1. in /home/www/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Wildcard.php at line 179
170171172173174175176177178179180181182183184185186187188                        }
                    }
 
                    $index->nextTerm();
                }
            } else {
                $index->skipTo(new Index\Term('', $field));
 
                while ($index->currentTerm() !== null  &&  $index->currentTerm()->field == $field) {
                    if (preg_match($matchExpression, $index->currentTerm()->text) === 1) {
                        $this->_matches[] = $index->currentTerm();
 
                        if ($maxTerms != 0  &&  count($this->_matches) > $maxTerms) {
                            throw new OutOfBoundsException('Terms per query limit is reached.');
                        }
                    }
 
                    $index->nextTerm()

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/0442bdbb8f0ec4da7812bfcb851cb038cecb53ae

should be fixed in current master
