### ISSUE TITLE
SiteController redirect to user profile on login instead of dashboard

### ISSUE THREAD

**Issue by danielrodd** [humhub/humhub#1251]
Hi! thank you for this amazing project! so I'm sharing all my collaborations as soon as they work, what I'm hoping to achieve is to be able to redirect users to their profile instead of to the dashboard, I've been trying with Url::to within the public actionindex function but no luck, suppose I have this:
<?php echo Yii::app()->createUrl('//user/profile', array('uguid' => Yii::app()->user->guid)); ?>

how do I integrate it properly in this:

class SiteController extends Controller {
    public function actionIndex() {
	$this->redirect('index.php?r=user/profile&uguid=');
    }
}

Any help would be great!!
Cheers

**Comment by danielrodd** [comment]
OMG!!! I did it!!
Check it out:

class SiteController extends Controller {

    public function actionIndex() {
        
		if(Yii::app()->user->isGuest) {

      		$this->redirect(array('user/auth/login'));
		} else {

			$this->redirect(array('user/profile', 'uguid' => Yii::app()->user->guid));
		}
	}

}

**Comment by luke-** [comment]
Better is to create an own module for that, so you can better update HumHub later on

**Comment by alexraynes** [comment]
Hi guys On my humhub site all my users are directed to the Dashboard, how can I direct them to user/auth/login when the access the site example www.example.com
