### ISSUE TITLE
New Idea - Add user status "locked"

### ISSUE THREAD

**Issue by gallandp** [humhub/humhub#1252]
Maybe for later releases, it's an option to think about a new user status named "locked". The status means, that the user cannot login anymore, but the posts and comments of this user are still visible in the timelines. A the moment, posts or comments aren't visible anymore if the user status is "inactive".

**Comment by pelennart** [comment]
This would be something very handy for us as a company with leaving employees.

**Comment by pelennart** [comment]
You can bypass this by changing email-adress and password at once. You could even change the members title to something like "deactivated" so it would show to everyone that member is not part of the community anymore.
