### ISSUE TITLE
Directory, only Spaces (Pages) where i am a member will showing up

### ISSUE THREAD

**Issue by Waldschat** [humhub/humhub#1253]
In the Directory, only Spaces (Pages) where i am a member will showing up. But i can't see all spaces, only under "New Spaces" i can see some of the spaces. 
There a no privat spaces.
I use the Version 0.20.0.
Is this a bug?

**Comment by luke-** [comment]
This was a bug in beta-2, do you really using the latest version 0.20.0?

Can you try to rebuild the search index or edit/save the certain space?

**Comment by Waldschat** [comment]
Yes i am a admin and can see the Version Number: Aktuell installierte Version: 0.20.0

>>Can you try to rebuild the search index or edit/save the certain space?
I dont know how i can do this.

I can search for member, but if I search for spaces I can only find spaces where I a member.

**Comment by Waldschat** [comment]
>>Can you try to rebuild the search index or edit/save the certain space?

Can you explain this closer what I have to do?  Maybe in German?

**Comment by davideagostini** [comment]
If you need to rebuild the search index (e.g. after updating) you need to run following command:

```php
cd /path/to/humhub/protected
php yii search/rebuild
```

**Comment by Waldschat** [comment]
Thank you! I will give this the person who installed the software.

**Comment by Waldschat** [comment]
Problem was solved

**Comment by tinashechipawe** [comment]
Can you please explain how the problem was solved?  I have the same issue.

**Comment by Waldschat** [comment]
No sorry, I forgot it... :(

**Comment by tinashechipawe** [comment]
No worries Thanks
