### ISSUE TITLE
Not displayed counter notification modules-mail in the new version 0.20.0

### ISSUE THREAD

**Issue by daglex** [humhub/humhub#1255]
Not displayed counter notification humhub-modules-mail in the new version 0.20.0
Messages received, but the counter is not working.

**Comment by Anopetia** [comment]
Hi,

We have fix that here : https://github.com/Anopetia/humhub-modules-mail/commit/8e08ed0121bb5e9b7c958b336ec52cd5fbb7e770

**Comment by daglex** [comment]
I need an official fix

**Comment by Anopetia** [comment]
Official or not it's working +1:
