### ISSUE TITLE
daily cron job fails

### ISSUE THREAD

**Issue by 1resu** [humhub/humhub#1256]
Hi,

thanks for the new 0.20 Humhub release. Unfortunately the daily cron job fails with the following error message:

`
PHP Warning:  require_once(/humhub-0.20.0/protected/vendor/yiisoft/yii2/base/ErrorException.php): failed to open stream: Too many open files in /humhub-0.20.0/protected/vendor/yiisoft/yii2/base/ErrorHandler.php on line 194`
`
PHP Fatal error:  require_once(): Failed opening required '/humhub-0.20.0/protected/vendor/yiisoft/yii2/base/ErrorException.php' (include_path='.:/usr/share/php:/usr/share/pear') in /humhub-0.20.0/protected/vendor/yiisoft/yii2/base/ErrorHandler.php on line 194`

`PHP Warning:  require_once(/humhub-0.20.0/protected/vendor/yiisoft/yii2/base/ErrorException.php): failed to open stream: Too many open files in /humhub-0.20.0/protected/vendor/yiisoft/yii2/base/ErrorHandler.php on line 226`

`PHP Fatal error:  require_once(): Failed opening required '/humhub-0.20.0/protected/vendor/yiisoft/yii2/base/ErrorException.php' (include_path='.:/usr/share/php:/usr/share/pear') in /humhub-0.20.0/protected/vendor/yiisoft/yii2/base/ErrorHandler.php on line 226
`

Give me a hint if you need more information about my setup.

**Comment by luke-** [comment]
This is a server configuration problem/limit.

http://stackoverflow.com/questions/14748499/fatal-error-too-many-open-files
