### ISSUE TITLE
Editing profile image does not dismiss after editing

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1258]
Steps to reproduce:
1) Add profile image to a user
2) Visit {@app_path}/u/{username}/
3) Click the 'edit' option for the users profile image
4) change the cropping
5) observe modal does not dismiss.

Error received: 

"NetworkError: 500 Internal Server Error .../user/account/crop-profile-image"
<pre>Exception &#039;yii\base\UnknownMethodException&#039; with message &#039;Calling unknown method
: humhub\modules\user\components\User::getModel()&#039; 

in {@app_path}/protected/vendor/yiisoft/yii2/base/Component.php:285

**Comment by CodyTheFurry** [comment]
Same problem here!
