### ISSUE TITLE
Can not delete profile image

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1259]
Reproduce:
1) Visit {@app_domain}/u/{@username}
2) Add profile image
3) Click the 'X' to remove profile image

Error:
POST {@app_domain}/user/account/delete-profile-image?type=profile

jquery.js (line 8630)
ReferenceError: resetProfileImage is not defined
	
...":function(jsonResp) { resetProfileImage(jsonResp); },"url":"/user/account/delet...

**Comment by Censtudios** [comment]
Works fine for me and my members. After deleting the profile image it stays until the page is refreshed though.

**Comment by davidjeddy** [comment]
User is still required to reload the page in order for the delete action to complete. If a user clicks the "x" button to delete their profile image, then clicks "delete" when asked if they're sure they want to delete, the profile image isn't actually deleted until the page is reloaded.
