### ISSUE TITLE
How to add new page to user profile

### ISSUE THREAD

**Issue by Censtudios** [humhub/humhub#1261]
Hey. I am trying to add a new page to each user profile. I did the following:

1) Created a new "history.php" with the text "test" (will be replaced with a script I already made that works by itself) in the directory protected/humhub/modules/user/views/profile

2) Went to protected/humhub/modules/user/widgets/ProfileMenu.php and copy/pasted the code for the "About" page and renamed "about" to "history"

But when I go to domain.com/u/username/user/profile/history it says Page Not Found

domain.com/u/username/user/profile/about works obviously, and I basically tried to copy the about page and link to replaced the code with a new one. The link in the menu does show up and does link to the URL I am trying to reach, but the page itself does not show up.

Am I missing something? Do I have to edit another file somewhere to make the site know that "history" is also a valid page to visit?

**Comment by WASasquatch** [comment]
You need a controller for the view.

**Comment by Censtudios** [comment]
Oooh got it. I kinda thought before I should go to controllers and copy some stuff there too but I think I made a typo or missed to rename actionAbout() to actionHistory(), it didn't work before but now it does xD thanks. I'm starting to understand Yii more little by little.
