### ISSUE TITLE
Normal user can't invite new users

### ISSUE THREAD

**Issue by Waldschat** [humhub/humhub#1262]
Normal user can't invite new users because there is no button to invite, only a button to  quit the membership. In the authentication menu is "users can invite new users per e-mail" enabled.

Version 0.20.0.

**Comment by Waldschat** [comment]
solved

**Comment by Darren66** [comment]
I have just install v 0.20.1 and I still have the issue of normal users not being able to invite new users. I can turn this on my marking it on each user, but I would like to have this on by default for spaces.. is there anyway to do this?
