### ISSUE TITLE
Invalid URL in the signup email when Mail Transport Type is file

### ISSUE THREAD

**Issue by lez** [humhub/humhub#1264]
The URL I got had extra '3D' strings in it: (which is extra difficult to notice in the token)

http://www.humhub.local/index.php?r=3Duser%2Fauth%2Fcreate-account&token=3D562b8cf15a50c1434813681

**Comment by luke-** [comment]
http://stackoverflow.com/questions/4016067/whats-a-3d-doing-in-this-html
