### ISSUE TITLE
Minimum font-size up to 13px

### ISSUE THREAD

**Issue by 3cst4sy** [humhub/humhub#1268]
Hi,

in the default theme i had to change the fontsize from 12px to 13px, because the little "i" was displayed as "l" sometimes. 

Maybe commit in next version?

**Comment by andystrobel** [comment]
Hm... I think no. I know that 12px is small, but it's necessary at some points to stand out from the other text. And you will find 12px font everywhere on the web. I also couldn't reproduce it. Can you provide a screenshot?

**Comment by 3cst4sy** [comment]
![snapshot](https://cloud.githubusercontent.com/assets/15309464/10764401/40b03e3a-7cce-11e5-9461-69bb26c53c5d.PNG)
Browser: Chromium 48.0.2528.0 
Display: 1280x1024

**Comment by andystrobel** [comment]
Ok thanks. But for me it works fine. Can you check at your browser console which font will be used? It should be Open Sans.

**Comment by 3cst4sy** [comment]
browser console says: 
![snapshot](https://cloud.githubusercontent.com/assets/15309464/10765291/563454c2-7cd2-11e5-96c1-1097d45f9b05.PNG)

**Comment by Censtudios** [comment]
Wouldn't 13px be too big though? 12px is better for content in my opinion.
