### ISSUE TITLE
Spaces didn't work, "An internal server error occurred."

### ISSUE THREAD

**Issue by Waldschat** [humhub/humhub#1269]
In the last some days, two spaces are crashed. If we want open it a message appears "An internal server error occurred."

The different to other spaces, tags and links was added.
Version 0.20.0.

**Comment by dsteven11** [comment]
The same problem...

**Comment by luke-** [comment]
Can you try to update the LinkList Module?

**Comment by Waldschat** [comment]
Hi, I installed today a update for the LinkList Module, if you mean this.

**Comment by luke-** [comment]
Whats the exact error message?

Administration -> Logging

**Comment by Waldschat** [comment]
Now it works! Maybe the update in today fix the problem?!
Sorry, but I see the logging file only over the website and so I can see only 10 entries/page and there are about 8000 entries... And no possibility to search. Maybe I can let me send the log file tomorrow.
Where can I found the log file in the humhub directory?

**Comment by mojobsb** [comment]
I got the same problem with this error in logging:
exception 'yii\web\HttpException' with message 'Could not determine content container!' in ... protected/humhub/modules/content/components/ContentContainerController.php:89

I can't add spaces and the stream of the welcome-space isn't loading.
Any suggestions? Thanks!

**Comment by luke-** [comment]
Which modules are you using?

**Comment by mojobsb** [comment]
You mean modules like in "Administration > Modules"?
I was using "Poll", but the error occured before installing poll and after removing it.

**Comment by luke-** [comment]
Hm, can you try using the integritychecker and post the output?

cd protected
php yii integrity/run

**Comment by mojobsb** [comment]
ah, sorry I got no shell access, it's shared hosting.
Is that a problem?

**Comment by 3cst4sy** [comment]
try http://sourceforge.net/projects/phpshell/

**Comment by mojobsb** [comment]
I used phpshell and got this:

$ cd protected
$ php yii integrity/run

Parse error: syntax error, unexpected '[' in ... /protected/yii on line 23
Unable to create lock file:  Permission denied
Failed to start up concurrent users module!
