### ISSUE TITLE
Where can I change the text of welcome mail for new users?

### ISSUE THREAD

**Issue by Waldschat** [humhub/humhub#1270]
Where can I change the text of welcome mail for new users?
It's in english and I want it translate to german. I know I can edit it before send the mail at each time, but I want change the source.

**Comment by Censtudios** [comment]
If you mean the email that is sent out where you need to click on a link so users can't insert their username, pass, etc for their new accounts. I found it for you here:

protected/humhub/modules/user/views/mails/UserInviteSelf.php

**Comment by Waldschat** [comment]
Thanks a lot!  ;)
