### ISSUE TITLE
Directory problems

### ISSUE THREAD

**Issue by PiCTaTe** [humhub/humhub#1271]
Hi all,

I have one problem with directory.

I have 200 users on my humhub, but directory module show me only 16.

Best Regards.

**Comment by Censtudios** [comment]
I have the same. I imported users from another system and I thought it had something to do with that. However, if I edit each users info in the admin section or if they login by themselves, they are added to the directory.

**Comment by luke-** [comment]
You need to rebuild the search index:

https://www.humhub.org/docs/guide-admin-adv-search.html
