### ISSUE TITLE
remove break-word for content of comments

### ISSUE THREAD

**Issue by 3cst4sy** [humhub/humhub#1273]
Hi,

in long replies the default theme breaks words rather then just take care of justify the content. 
example for 2 words "tempor invidunt"
Left side: default theme - Right side: modified
![snapshot](https://cloud.githubusercontent.com/assets/15309464/10770117/dd38d8b4-7ce9-11e5-90e7-1aa4917fc95c.PNG)

**Comment by Censtudios** [comment]
This would be a nice thing to fix.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/c94a87e2f7179128aca97c428f24cbf9680a73cf
Should be fixed..
