### ISSUE TITLE
Update from 0.11.2 to 0.20.0 Database Exception – yii\db\Exception after calender module installation

### ISSUE THREAD

**Issue by Freekkel** [humhub/humhub#1274]
Hi,

I tried to update from 0.11.2 to 0.20.0 as shown in
https://www.humhub.org/docs/guide-admin-updating-020.html
that worked quiet fine, but as soon as I added the calendar module, my local testsite crashed and i got following Exception 

Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'start_datetime' in 'where clause'
The SQL being executed was: SELECT `calendar_entry`.* FROM `calendar_entry` LEFT JOIN `content` ON `calendar_entry`.`id` = `content`.`object_id` LEFT JOIN `user` ON `content`.`user_id` = `user`.`id` LEFT JOIN `space` ON `content`.`space_id` = `space`.`id` WHERE (((`start_datetime` >= '2015-10-28 11:44:35') AND (`end_datetime` <= '2015-11-04 11:44:35')) AND (`content`.`space_id`=13)) AND (`content`.`object_model`='humhub\\modules\\calendar\\models\\CalendarEntry') ORDER BY `start_datetime` LIMIT 3

Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'start_datetime' in 'where clause'
)

↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'start_datetime' in 'where clause'

.....

for full Error see http://test.berater-mainz.de/error.pdf 

What can I do? what am I missing?

thanks in advance. 

Freekkel

**Comment by luke-** [comment]
Did you executed all migrations?

Run database migration tool:
cd protected
php yii migrate/up --includeModuleMigrations=1

**Comment by Freekkel** [comment]
I get the following output 
```
Yii Migration Tool (based on Yii v2.0.6)

No new migration found. Your system is up-to-date.
```

so this seems to work. But the error stays.

**Comment by pelennart** [comment]
Probably the same route, but worth a try as it helped me with that problem:
1) Open self-test & updates from administration menu in another window or tab.
2) Install the module that leads to errors in modules menu
3) Switch back to self-test & updates and restart testing

**Comment by Freekkel** [comment]
@pelennart this workaround worked for the calendar module 

```
                Yii Migration Tool (based on Yii v2.0.6)

Total 2 new migrations to be applied:
	m150706_193118_renamefield
	m150707_134615_update

*** applying m150706_193118_renamefield
    > rename column start_time in table calendar_entry to start_datetime ... done (time: 0.027s)
    > rename column end_time in table calendar_entry to end_datetime ... done (time: 0.027s)
*** applied m150706_193118_renamefield (time: 0.057s)

*** applying m150707_134615_update
    > update activity ... done (time: 0.002s)
    > update activity ... done (time: 0.002s)
    > update activity ... done (time: 0.002s)
    > update activity ... done (time: 0.002s)
*** applied m150707_134615_update (time: 0.036s)


Migrated up successfully.
            
``` 

It also worked for other modules. Thanks a lot.

**Comment by Spiritdude** [comment]
@luke: please include the post "Did you executed all migrations?" into https://www.humhub.org/docs/guide-admin-updating-020.html has it's not mentioned there, e.g. add:
------
Install all the previous modules and once activated via the web-interface run in the command line following:
% cd protected
% php yii migrate/up --includeModuleMigrations=1

and then go back to the web-interface under Administration and run the Self-Test, if there are no errors the migration should be complete.
-------
I migrated from 0.11.2 to 0.20.1 when the dashboard did not work anymore, that manual 'php yii' did the job.
