### ISSUE TITLE
Update from 0.11.2 to 0.20.0  PHP Fatal error:  require(): Failed ope ning required ...

### ISSUE THREAD

**Issue by scrobbleme** [humhub/humhub#1278]
I just tried to update using the latest package and following this guide: https://www.humhub.org/docs/guide-admin-updating-020.html

But getting the following, when starting the web installer:

```
mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/XYZ/hub/protected/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in XYZ/hub/index.php on line 13
```

No problem with HumHub 0.11.2 so far.

**Comment by 3cst4sy** [comment]
check your /XYZ/hub/protected/vendor/.. any files in?

**Comment by scrobbleme** [comment]
Thank you, that was the hint I needed.

I downloaded the package from Github releases overview (because I could use wget there). Which is named the same, but isn't the same as from the official download page. Not quite obviously. 

It is working now ;)
