### ISSUE TITLE
[Bug] Polling Module - wrong people list who answered the poll question

### ISSUE THREAD

**Issue by pdanysz** [humhub/humhub#1280]
On Poll if you click the number of people who leave the vote you will see all users from Area instead of people who actually answered that particular question.

![image](https://cloud.githubusercontent.com/assets/385259/10826162/acb9bf7a-7e68-11e5-9e9a-b7fc11511c32.png)

**Comment by pdanysz** [comment]
Wrong part of app :)

**Comment by tobciu** [comment]
https://github.com/humhub/humhub-modules-polls/pull/20
