### ISSUE TITLE
theme.less

### ISSUE THREAD

**Issue by AlphabetoPT** [humhub/humhub#1281]
Hello i am trying to work on my theme but i just can edit the login page.
I can't change top bar color or anything actually on theme.less.
Is there anything more i need to do so humhub accepts my new css config?
Thanks

**Comment by andystrobel** [comment]
Normally you only have to edit the theme.less file, especially for the topbar. But you convert the theme.less file to css, right?

**Comment by AlphabetoPT** [comment]
No sir i did not. I did not needed to do that for editing login page.
Can you guide me through ?
Thanks

**Comment by andystrobel** [comment]
That are two different things. The one thing is to edit view files like the login page to change or modify DOM elements, the other thing is to modify the theme.less. file to change the whole layout with css. 

Read more about HumHub Theming here: https://www.humhub.org/docs/guide-theming-index.html
To getting started with LESS you will find a lot of tutorials with google. (For example: http://webdesign.tutsplus.com/articles/get-into-less-the-programmable-stylesheet-language--webdesign-5216)

**Comment by AlphabetoPT** [comment]
So the main point is i was editing the wrong file, right?

**Comment by andystrobel** [comment]
Normally not. You have to modify the theme.less file and compile it to theme.css. Of course, you could also edit just the theme.css file. But this is not the recommended way...

**Comment by AlphabetoPT** [comment]
sorry about my ignorance but what do you mean to compile the theme.lss to theme.css what's the fastest way to do that?
Also. i would like to understand why this compile process was not needed to edit background image on login page 

Thank you

**Comment by AlphabetoPT** [comment]
Sorry. I managed to edit all i wanted. However there are two things that after a full night i still cant find where to edit.
#1 What are the line number to edit the Links color?
#2 Is there a way to change the logo size on the login page? (only in login page)
Thank you
