### ISSUE TITLE
NetworkError: 500 Internal Server Error 

### ISSUE THREAD

**Issue by tejashp77** [humhub/humhub#1282]
working on localhost.

when I put live there are so many bugs.

one main thing is it shows NetworkError: 500 Internal Server Error  in every request.

for example if I am want to post something it will post but due to above error it will not display.

as well I can't retrieve data from database

**Comment by tejashp77** [comment]
any solution for my issue?

**Comment by tomtomsen** [comment]
a 500 internal server occurse if an exception occured.
have you checked your protected/runtime/app.log?

You wrote, that you cant connect to db. probably thats the problem. have you set your connection settings correctly?

**Comment by tejashp77** [comment]
thanx for replay.

the app.log file doesn't generated it means there is no error.

now,i have setup db as per wizard instructions. any other requirements are needed??

**Comment by aerth** [comment]
No doubt, **it is a permissions issue**. Happens to me all the time depending on php config. Did you fix it yet? Sounds like the error be in your /var/log/nginx/error.log or /var/log/apache2/error.log

**Comment by tejashp77** [comment]
@aerth still i don't get any solution for my issue

**Comment by tejashp77** [comment]
also i didn't found any error in /var/log/apache2/error.log

**Comment by tejashp77** [comment]
can you please suggest me which folders need permissions?

**Comment by tomtomsen** [comment]
maybe. if you rename the dynamic.php you should be able to resart the installer, just to check if all your directories are writeable.

**Comment by tejashp77** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8726751/10997672/e59d00ca-84b4-11e5-90ee-a49808bf2d3d.png)

there is no error of permissison in fresh installation.

i have attached screenshot. can you please check?

**Comment by aerth** [comment]
Hey @tejashp77 by visiting your URL it seems like you resolved the issue. How did you fix it?

**Comment by tejashp77** [comment]
@aerth its not solved.

please login with below credentials you can got the exact issue. 
test25@gmail.com /test25

**Comment by tejashp77** [comment]
Thank all for your contribution.

i have changed the server and now the issue solved.

Thank you

**Comment by badis** [comment]
Hi @tejashp77 ,

I have the same issue here , would please tell me what do you mean by changing the server ?

Do you mean go to another server  or changing something on the same server .

Thank you.

**Comment by aerth** [comment]
Either: 1. Correct the permissions on each php file or 2. PHP upgrade, or replace with different PHP. Best of luck
