### ISSUE TITLE
Error message after login

### ISSUE THREAD

**Issue by ychoucha** [humhub/humhub#1283]
Hello, on a frech insall of humhub 0.20 

i m on ubuntu server 14.04 lts, apache 

i added my ldap configuraiton, after that i evry time i log i have this error message : 

 PHP Core Warning – yii\base\ErrorException
Module 'ldap' already loaded

    2. yii\base\ErrorHandler::handleFatalError()

$_SERVER = [

what do u think please ?
![humhuberror](https://cloud.githubusercontent.com/assets/301074/10876109/e77be74a-8139-11e5-99c1-55b3d52e7973.jpg)

**Comment by luke-** [comment]
Maybe a PHP misconfiguration?

http://stackoverflow.com/questions/254279/php-warning-module-ldap-mysql-already-loaded-when-running-php-at-command
