### ISSUE TITLE
Error logging in on fresh install

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1286]
Steps taken:
`git clone https://github.com/humhub/humhub.git ./`
copy .
`composer global require "fxp/composer-asset-plugin:~1.0.0" && composer update --prefer-dist --profile --no-dev -o -v`

Visit URL
Complete install steps successfully.
copy .htacces.dist to .htaccess

Added
```
<?php

return [
    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ]
];
```

to /protected/config/common.php

visit {domain}/user/auth/login
Input username and password; press `log in` button
Receive error this error:

```
Call to a member function validatePassword() on null
1. in /var/www_vagrant/humhub.dev/protected/humhub/modules/user/models/forms/AccountLogin.php at line 51
42434445464748495051525354555657585960     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();
            if ($user !== null) {
                if ($user->auth_mode === User::AUTH_MODE_LOCAL && $user->currentPassword->validatePassword($this->password)) {
                    return;
                } elseif ($user->auth_mode === User::AUTH_MODE_LDAP && Ldap::isAvailable() && Ldap::getInstance()->authenticate($user->username, $this->password)) {
                    return;
                }
            }
            $this->addError($attribute, 'Incorrect username or password.');
        }
    }
 
```

Current hash: 0d5e6e31e7e165113822b9f34ded2c49c589db5e

**Comment by luke-** [comment]
Can you check the database? Is there an user & password entry created?

**Comment by davidjeddy** [comment]
That would be it, somehow the user_password table was cleared.
Suggestion: validate data exists before calling validatePassword()l, looks like \humhub\modules\user\models\forms\AccountLogin->validatePassword().
Closing
