### ISSUE TITLE
HumHub Crashed after PHP upgrade from 5.3.3 to 5.4.45

### ISSUE THREAD

**Issue by frey1esm** [humhub/humhub#1298]
Once I attempted to log in to Humhub after the upgrade, I receive this error:

<code>Invalid class type! |humhubmodulesusermodelsfieldtypeSelect|</code>

in /protected/vendors/yii/db/ar/CActiveRecord.php(145)

<code>145:  return parent::__get($name);</code>

**Comment by luke-** [comment]
This shouldn't be related to the PHP Update.

Which Humhub version?

**Comment by frey1esm** [comment]
0.11

The PHP update was the only thing changed prior to the error appearing immediately after login attempt.
