### ISSUE TITLE
Marketplace API SSL Problem

### ISSUE THREAD

**Issue by Themaster07** [humhub/humhub#1299]
Error in cURL request: SSL: no alternative certificate subject name matches target host name 'www.humhub.org')

**Comment by luke-** [comment]
Which OS & Version do you using?

**Comment by Themaster07** [comment]
0.20.0  version

**Comment by Themaster07** [comment]
![error](https://cloud.githubusercontent.com/assets/12178620/11109951/6de61cf6-88c4-11e5-9902-dba49731a55d.png) error please help me

**Comment by DanneG** [comment]
I have the same problem
HumHub v0.20.0

**Comment by luke-** [comment]
Seems your CURL Libary doesn't support SNI.

You can add following to your local configuration (protected/config/common.php):

```php
<?php

return [
    'modules' => [
        'admin' => [
            'marketplaceApiUrl' => 'https://api.humhub.com/v1/modules/',
        ]
    ]
];
´´´

**Comment by DanneG** [comment]
The same error occurs

**Comment by evolun** [comment]
I have a slightly different error but the same problem, after migration (perhaps in 0.20 beta still works, i don't remember well), if i try to upgrade or install a module:

`exception 'Zend\Http\Client\Adapter\Exception\RuntimeException' with message 'Error in cURL request: SSL peer certificate or SSH remote key was not OK' in /home3/humhub/protected/vendor/zendframework/zend-http/src/Client/Adapter/Curl.php:425`

I have imported the certificates from humhub.org and api.humhub.com in ca-bundle.crt but the problem persist.

**Comment by luke-** [comment]
Hmm you can also try to disable SSL Validation

´´´php
<?php

return [
    'modules' => [
        'admin' => [
            'marketplaceApiValidateSsl' => false
        ]
    ]
];
´´´

Which Operation System or CUrl Libary Versions do you use?

**Comment by evolun** [comment]
Ok, disabling SSL validation works for me.

I'm on CentOS 5.3 x86_64 with libcurl 7.21.7

**Comment by DanneG** [comment]
Yes, working for me too

CentOS 5.11
libcurl/7.40.0

**Comment by Themaster07** [comment]
thank you :+1:

**Comment by DanneG** [comment]
Same problem in: 1.0.0-beta.2

**Comment by rammyres** [comment]
Same issue with 1.0.0-beta.4

**Comment by luke-** [comment]
@rammyres Can you please post the error message?

**Comment by dreua** [comment]
@ fellow CentOS 8 admins: see #4458 for a workaround on the curl error / empty marketplace problem.
