### ISSUE TITLE
Date and time format in global config (feature request)

### ISSUE THREAD

**Issue by koteek85** [humhub/humhub#1304]
![hamhub-birthday](https://cloud.githubusercontent.com/assets/9195737/11309796/f7c1d992-8fd6-11e5-8042-07b67f40179a.jpg)
Kindly ask You to add date and time format global configuration (for humhub itself and modules) to resolve problems with formatter in future. 

https://github.com/humhub/humhub/issues/1214
https://github.com/humhub/humhub-modules-calendar/issues/24

P.S. @luke-, @andystrobel, thank You for your work, HumHub is awesome!

**Comment by luke-** [comment]
Date Handling should be improved now.
Anyway we're using the date format of user defined locale.
https://github.com/humhub/humhub/commit/6c1e4b61b3919f0d9d860cb53d92846f13492b09
