### ISSUE TITLE
URL Rewrite doesn't rewrite the link from the "Like" button on posts

### ISSUE THREAD

**Issue by radu-stanescu** [humhub/humhub#1311]

**Comment by luke-** [comment]
Works for me

![image](https://cloud.githubusercontent.com/assets/4736168/11266315/0659f4f0-8ea4-11e5-8838-6f17cc27a117.png)

**Comment by radu-stanescu** [comment]
I see also in your POST the URL link is not rewritten, only on the GET which comes after liking the post the URL is rewritten

**Comment by luke-** [comment]
It's intended that parameters are not rewritten.
