### ISSUE TITLE
Notification by mail after post

### ISSUE THREAD

**Issue by dalosgit** [humhub/humhub#1313]
Hi, i have the lastest humhub version and i just receive mails, if i invite a user. But i also want that every user gets a mail after a post automatically. The notification for standard user are set correct. Would be very nice if someone can help me. Kr dalos

**Comment by dalosgit** [comment]
Btw. Theres no log entry in the database or an error in json call. The method i use is php (function works for invite a user)

**Comment by dalosgit** [comment]
Hi Lucas,
thank you very much - i'm trying to fix the problem right now, but without any success.
The list did I worked one hour before.

**Comment by luke-** [comment]
- Is the Cron Job Running?
- Mail Settings Administration -> Mailling   correct?

**Comment by dalosgit** [comment]
Hi Luke, thanks for your response.
Do you know how i can create this cronjob? The cronjob is current not running, i dont know what file should be called to generate the mail. The written path in the setting does not work.

Kr phillip

**Comment by luke-** [comment]
https://www.humhub.org/docs/guide-admin-installation.html#enable-cron-jobs

**Comment by dalosgit** [comment]
Hi luke if i call the url ...social/protected/yiic manual to "start" the cronjob the following happens: 
#!/usr/bin/env php
<?php


require_once(dirname(__FILE__).'/yiic.php');

**Comment by pelennart** [comment]
You are probably running an older version of HumHub, not the latest or  you are using the old cron command.
With the new Yii2.0 there is no yiic anymore but yii.
