### ISSUE TITLE
migration.

### ISSUE THREAD

**Issue by AlphabetoPT** [humhub/humhub#1315]
Hello, i am using humhub, the latest build that updater finds and i changed hosts recently.
i copied all in /var/www/html and the .sql too.
I am now able to use it on ''almost normally'' on my new host but i cant acces modules page on admin panl or either send messages with the inbox module.

Help please.

Logs.
http://pastebin.com/pjaTwvdK

Thank you.

**Comment by luke-** [comment]
#1289

**Comment by AlphabetoPT** [comment]
I am sorry, how do i fix this?
I understand it had something to do with cURL hosts but i have no idea how to fix this.
Thanks

**Comment by AlphabetoPT** [comment]
well. luke i guess patiente is not his father.
Because it was not anything to do with cURL but with the mail configs because my new machine was not mail configured yet.

Still awesome platform humhub is and Thank you!
Bye.

Problem solved
