### ISSUE TITLE
Public/private toggle for posts don't work as expected

### ISSUE THREAD

**Issue by evolun** [humhub/humhub#1318]
If I mark a post as public, then private, something go wrong on the toggle and the post can't be public anymore, unless I reload the page.

If I make a post as public and try to make a subsequent post (without navigation/reload), it can't be public anymore and the toggle label show the action inconsistent to the presence of the tag label "public".

**Comment by numidark** [comment]
Similiar problem on Humhum 1.0.0 beta 3
