### ISSUE TITLE
Who voted bug

### ISSUE THREAD

**Issue by Dinevv** [humhub/humhub#1319]
When some of the administrators vote,the second one automatically is there when i open the voting tab.
example: https://scontent-ams3-1.xx.fbcdn.net/hphotos-xap1/v/t35.0-12/12279450_776080295848791_773108600_o.jpg?oh=9333cac380475e30a15e29c9cc451cc8&oe=565295BB

**Comment by luke-** [comment]
Please open this bug in https://github.com/humhub/humhub-modules-polls with more informations..
