### ISSUE TITLE
Unable to adjust modules when unable to reach humhub.com ...

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1320]
... even to see a list of installed modules is impossible if the cURL call to Humhub fails.

Suggestion: cURL call to humhub should fail gracefully in humhub\modules\admin\libs\OnlineModuleManager->getModuleUpdate() and related calls.

**Comment by luke-** [comment]
Should be already fixed in 0.21/1.0
https://github.com/humhub/humhub/tree/v0.21-dev

**Comment by davidjeddy** [comment]
That was fast.

And awesome. Now to wait for the patch to enter the stable release.

**Comment by luke-** [comment]
We're going to beta release it on monday.
