### ISSUE TITLE
how can create a page like pages in facebook or other social networks?

### ISSUE THREAD

**Issue by gharach** [humhub/humhub#1321]
has humhub a module for create a page ? our team wanna use humhub for creating a custom social network we love yii2 so we choose humhum. everything seams good in humhub ,space is good but it is more like "group" in common social networks so how about "page" , is it possible for us as developers to create a page module for hubhum, what is your advice? thank u

**Comment by Censtudios** [comment]
Was kinda hard to understand what you mean exactly, but I think you mean this:

https://github.com/humhub/humhub-modules-custom-pages

**Comment by gharach** [comment]
sorry for my bad english,i wanna a module for humhub to create pages (like pages in facebook)  i think thishttps://github.com/humhub/humhub-modules-custom-pages is just for create a html page

**Comment by Censtudios** [comment]
There used to be an extended module for custom pages that allowed for PHP as well, but its outdated and doesn't work anymore.

**Comment by gharach** [comment]
yes , i think "page" is more like user profile in humhub , i think we can re create user profile and create for create page module
