### ISSUE TITLE
Saving User Details subtracts one day from saved Birthday!

### ISSUE THREAD

**Issue by ibrowz** [humhub/humhub#1322]
Hello humhub,

I am experiencing a scenario that when saving User Details it subtracts one day from the saved Birthday.  Additionally when you selects a date it saves the date one day behind.  Also the "Hide year in profile." doesn't display the age correctly it just displays "0".  I am running version number 0.20.1.

Thank you for any response in this great open source resource.
Regards,
ibrowz

**Comment by luke-** [comment]
Which language do you using?
Does this problem also occur on our community site (community.humhub.com)?

**Comment by ibrowz** [comment]
Hello Lucas,

Thank you for looking into my experiences with HumHub.
First of all I'm using English (US) as the language.
Second, no this problem doesn't exist (subtraction of days when saving the
Birthday) on the community site.
Except that the "Hide year in profile." doesn't display the age correctly
in the community site,it just displays "0" as well.
The "Self Test" returns "OK" for all the software prerequisites.
I am running OPCache but have disabled it just to be sure, but still the
same result.
I expect there's something in my configuration (PHP 5.6.15) that's causing
the conflict.
Additionally, I'm running a Windows based environment with Apache 2.4.17.
I'm going to continue tweaking the PHP configuration and will let you know
if I find the conflict.

Really like the work you're doing with this project, keep it up!

Best,
David

**Comment by armouredking** [comment]
I can confirm the issue of days being subtracted from the birth date entry every profile save. I do not have the year issue though as noted by OP, appearance below:

Birthday
30. July

Using the latest beta version 1.0.0-beta.1 as well as 0.20.1.

Environment is as follows:
OS: Debian 8
WS: NGINX 1.6.2
PHP: 5.6.14

Using file based caching at the moment. Tested with English US and English UK.
