### ISSUE TITLE
Calendar entry in foreign language

### ISSUE THREAD

**Issue by facubesrl** [humhub/humhub#1323]
exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (28/nov/2015) at position 0 (2): Unexpected character' in /var/www/clients/client1/web18/web/protected/modules/calendar/models/CalendarEntry.php:141 Stack trace: #0 /var/www/clients/client1/web18/web/protected/modules/calendar/models/CalendarEntry.php(141): DateTime->__construct('28/nov/2015') #1 [internal function]: humhub\modules\calendar\models\CalendarEntry->validateEndTime('end_datetime', NULL) #2 /var/www/clients/client1/web18/web/protected/vendor/yiisoft/yii2/validators/InlineValidator.php(69): call_user_func(Array, 'end_datetime', NULL) #3 /var/www/clients/client1/web18/web/protected/vendor/yiisoft/yii2/validators/Validator.php(240): yii\validators\InlineValidator->validateAttribute(Object(humhub\modules\calendar\models\CalendarEntry), 'end_datetime') #4 /var/www/clients/client1/web18/web/protected/vendor/yiisoft/yii2/base/Model.php(352): yii\validators\Validator->validateAttributes(Object(humhub\modules\calendar\models\CalendarEntry), Array) #5 /var/www/clients/client1/web18/web/protected/modules/calendar/controllers/EntryController.php(82): yii\base\Model->validate() #6 [internal function]: humhub\modules\calendar\controllers\EntryController->actionEdit() #7 /var/www/clients/client1/web18/web/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #8 /var/www/clients/client1/web18/web/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array) #9 /var/www/clients/client1/web18/web/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('edit', Array) #10 /var/www/clients/client1/web18/web/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('calendar/entry/...', Array) #11 /var/www/clients/client1/web18/web/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 /var/www/clients/client1/web18/web/index.php(25): yii\base\Application->run() #13 {main}

**Comment by facubesrl** [comment]
how can I fix ?
thank you

**Comment by pelennart** [comment]
Try running the yii migration tool, e.g. surf to: http:// *your-humhub-domain* /index.php?r=admin%2Fsetting%2Fself-test

**Comment by luke-** [comment]
Duplicate: https://github.com/humhub/humhub/issues/1161
