### ISSUE TITLE
Enhancement: Provide docker image

### ISSUE THREAD

**Issue by cboulanger** [humhub/humhub#1325]
I have written the [recipe for a Humhub docker image](https://github.com/cboulanger/humhub-docker), which works well for me. However, I am not an expert either for Docker, Humhub, or secure server setup, and will not be able to maintain that image reliably. It would be good if the Humhub team created and maintained a Docker image themselves. It will certainly broaden the user base, since it takes the pain out of installation & setup and allows people to have their own test installation in seconds.

**Comment by acidjames** [comment]
Tried this docker image and worked perfectly on ubuntu, just wanted to say thanks

**Comment by cboulanger** [comment]
Great to hear that. I have just today committed a bug fix - you might want to make sure to check this issue in case you used an earlier image: the earlier recipe/image installs a cron job for the root user that only works if the www-data user has a shell (try `su www-data`). Otherwise, delete the root crontab and create one for the www-data user instead.

**Comment by acidjames** [comment]
Thanks, it's cool because the other humhub docker image has no mysql account pre-configured, as i have a very limited knowledge about docker, i chose yours

i like when it's real kickstarting testing apps !

cheers

**Comment by bkmeneguello** [comment]
If the humhub guys decide to adopt a docker image, I suggest https://github.com/mriedmann/humhub-docker, it's very lightweight.

**Comment by luke-** [comment]
Thanks for your help, there is finally a repository for Docker container.

https://github.com/humhub/docker

@mriedmann Special thanks for your support on this topic!
