### ISSUE TITLE
How can i check test mail whether the mail() function is working or not ?

### ISSUE THREAD

**Issue by gsivaprabu** [humhub/humhub#1328]
Hi,

Possible to check test mail() in humhub ?

 am using Mail Transport Type => PHP

how can i check test mail ?
![mail](https://cloud.githubusercontent.com/assets/2444608/11385191/51184568-933c-11e5-90d5-a404996d6c64.png)

**Comment by luke-** [comment]
e.g. try to recover password

**Comment by gsivaprabu** [comment]
Ok Luke, Thank you...
