### ISSUE TITLE
Failed opening required protected/vendor/autoload.php 1.0.0-beta.1

### ISSUE THREAD

**Issue by Philippe-M** [humhub/humhub#1332]
When install the 1.0.0-beta.1 version i've this error 

```
[Thu Nov 26 09:08:45 2015] [error] [client xxx] PHP Fatal error:  require(): Failed opening required '/xxx/protected/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /xxx/index.php on line 13
```

**Comment by luke-** [comment]
https://www.humhub.org/docs/guide-admin-installation.html

**Comment by Philippe-M** [comment]
ok but even using the installation procedure to the relationship I have still the same error. And the file is actually missing from the directory.
