### ISSUE TITLE
Error 'Trying to get property of non-object' in /var/www/humhub/protected/humhub/modules/space/notifications/views/inviteDeclined.php:6

### ISSUE THREAD

**Issue by cboulanger** [humhub/humhub#1333]
Cannot get notifications from server (500 Internal Server Error) 
Humhub v0.20.1

Request: GET /notification/list/index?from=0&ajax=1 HTTP/1.1
Response: {"name":"Internal Server Error","message":"There was an error at the server.","code":0,"status":500}

Server Log:

Error  Thu, 26 Nov 2015 09:36:10 +0100  yii\base\ErrorException:8
exception 'yii\base\ErrorException' with message 'Trying to get property of non-object' in /var/www/humhub/protected/humhub/modules/space/notifications/views/inviteDeclined.php:6 Stack trace: #0 /var/www/humhub/protected/humhub/modules/space/notifications/views/inviteDeclined.php(6): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/humhub...', 6, Array) #1 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/humhub...') #2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/humhub...', Array) #3 /var/www/humhub/protected/humhub/modules/notification/components/BaseNotification.php(120): yii\base\View->renderFile('/var/www/humhub...', Array, Object(humhub\modules\space\notifications\InviteDeclined)) #4 /var/www/humhub/protected/humhub/modules/notification/controllers/ListController.php(60): humhub\modules\notification\components\BaseNotification->render() #5 [internal function]: humhub\modules\notification\controllers\ListController->actionIndex() #6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array) #8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('index', Array) #9 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('notification/li...', Array) #10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 /var/www/humhub/index.php(25): yii\base\Application->run() #12 {main}

Request Log: 
Info  Thu, 26 Nov 2015 09:36:10 +0100  application
$_GET = [ 'from' => '0' 'ajax' => '1' ] $_COOKIE = [ 'language' => '(removed):2:{i:0;s:8:\"language\";i:1;s:2:\"de\";}' 'MMTOKEN' => '(removed)' 'PHPSESSID' => '(removed)' '_csrf' => '(removed):2:{i:0;s:5:\"_csrf\";i:1;s:32:\"9GYuRPMFJGGLPGJtJ408tnWtA145grEh\";}' '_identity' => '(removed):2:{i:0;s:9:\"_identity\";i:1;s:50:\"[2,\"c2a92f89-f250-40e3-bc48-589084da0c1f\",2592000]\";}' ] $_SESSION = [ '__flash' => [] '__returnUrl' => '/index.php?r=dashboard/dashboard' '__id' => 2 ] $_SERVER = [ 'REDIRECT_no-gzip' => '1' 'REDIRECT_HTTPS' => 'on' 'REDIRECT_SSL_TLS_SNI' => 'hub.trafo-berlin.de' 'REDIRECT_STATUS' => '200' 'no-gzip' => '1' 'HTTPS' => 'on' 'SSL_TLS_SNI' => 'hub.trafo-berlin.de' 'SSL_SERVER_S_DN_C' => 'DE' 'SSL_SERVER_S_DN_ST' => 'Berlin' 'SSL_SERVER_S_DN_L' => 'Berlin' 'SSL_SERVER_S_DN_O' => '(removed).' 'SSL_SERVER_S_DN_CN' => '(removed)' 'SSL_SERVER_I_DN_C' => 'DE' 'SSL_SERVER_I_DN_O' => 'DFN-Verein' 'SSL_SERVER_I_DN_OU' => 'DFN-PKI' 'SSL_SERVER_I_DN_CN' => 'DFN-CA Global' 'SSL_VERSION_INTERFACE' => 'mod_ssl/2.4.10' 'SSL_VERSION_LIBRARY' => 'OpenSSL/1.0.1k' 'SSL_PROTOCOL' => 'TLSv1.2' 'SSL_SECURE_RENEG' => 'true' 'SSL_COMPRESS_METHOD' => 'NULL' 'SSL_CIPHER' => '(removed)' 'SSL_CIPHER_EXPORT' => 'false' 'SSL_CIPHER_USEKEYSIZE' => '128' 'SSL_CIPHER_ALGKEYSIZE' => '128' 'SSL_CLIENT_VERIFY' => 'NONE' 'SSL_SERVER_M_VERSION' => '3' 'SSL_SERVER_M_SERIAL' => '19F14F80855CB5' 'SSL_SERVER_V_START' => 'Aug 17 12:22:09 2015 GMT' 'SSL_SERVER_V_END' => 'Nov 13 12:22:09 2018 GMT' 'SSL_SERVER_S_DN' => '(removed)' 'SSL_SERVER_I_DN' => '(removed)' 'SSL_SERVER_A_KEY' => 'rsaEncryption' 'SSL_SERVER_A_SIG' => 'sha256WithRSAEncryption' 'SSL_SESSION_ID' => '(removed)' 'SSL_SESSION_RESUMED' => 'Resumed' 'HTTP_HOST' => '(removed)' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; rv:42.0) Gecko/20100101 Firefox/42.0' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_ACCEPT_LANGUAGE' => 'de,en-US;q=0.7,en;q=0.3' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate' 'HTTP_DNT' => '1' 'HTTP_X_CSRF_TOKEN' => '(removed)==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_REFERER' => '(removed)/index.php?r=dashboard/dashboard' 'HTTP_COOKIE' => 'language=(removed)%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22de%22%3B%7D; MMTOKEN=(removed); PHPSESSID=(removed); _csrf=(removed); _identity=(removed)' 
'HTTP_CONNECTION' => 'keep-alive' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SERVER_NAME' => 'hub.trafo-berlin.de' 'SERVER_ADDR' => '172.17.0.1' 'SERVER_PORT' => '5010' 'REMOTE_ADDR' => '172.17.42.1' 'DOCUMENT_ROOT' => '/var/www/humhub' 'REQUEST_SCHEME' => 'https' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/humhub' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/var/www/humhub/index.php' 'REMOTE_PORT' => '41444' 'REDIRECT_QUERY_STRING' => 'from=0&ajax=1' 'REDIRECT_URL' => '/notification/list/index' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'from=0&ajax=1' 'REQUEST_URI' => '/notification/list/index?from=0&ajax=1' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1448526970.199 'REQUEST_TIME' => 1448526970 ]

**Comment by cboulanger** [comment]
Editing line 6 of https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/notifications/views/inviteDeclined.php like so fixes the error: 
```
 '{userName}' => '<strong>' . Html::encode(is_object($originator)?$originator->displayName:"") . '</strong>',
```
However, that's a hack/workaround, not a solution

**Comment by luke-** [comment]
Multiple: https://github.com/humhub/humhub/issues/1373
