### ISSUE TITLE
Birthday in Profile

### ISSUE THREAD

**Issue by agouws** [humhub/humhub#1338]
I keep on getting the following error when trying to complete the "Howdy user, thank you for using Humhub. You are the first user here..." screen. It complains that "The format of Birthday is invalid". This happens even when I select the date using the Calendar or when I try and manually filling it in using the specified format.
![error](https://cloud.githubusercontent.com/assets/15890631/11450561/6980dd86-95df-11e5-9460-01949cd690a2.gif)

**Comment by csrui** [comment]
I'm having the same issue. I'm using Portuguese as the default language.

**Comment by koteek85** [comment]
The same issue for Russian language.

**Comment by ibrowz** [comment]
Sorry to report but I too am experiencing this.
Regards,
ibrowz

**Comment by VasileGabriel** [comment]
same here on /admin/user/add and admin/user/edit.
