### ISSUE TITLE
Mail plugin frontend bug

### ISSUE THREAD

**Issue by Dinevv** [humhub/humhub#1339]
After the update of mailing plugin, we found a issue - when you click on the mail icon on the navigation bar, the window is broken: http://imgur.com/EFA7JWk

**Comment by andystrobel** [comment]
Which HumHub and Mail Module version you're using? Maybe you just empty the cache!?!

**Comment by Censtudios** [comment]
Humhub 1.0 beta1 and the latest Mail update 0.7.6. It happened to me too right after I updated the mail plugin

**Comment by Dinevv** [comment]
I am using the newest version of mail - 0.7.6 and humhub version 0.20.1(i am waiting for the next stable version).

**Comment by Censtudios** [comment]
So it has to do with the recent changes to the CSS of the plugin. Any way to downgrade back to the older version of the plugin?
