### ISSUE TITLE
error install 1.0.0-beta.1

### ISSUE THREAD

**Issue by Themaster07** [humhub/humhub#1341]
Database Exception – yii\db\Exception

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'facedogs_new.group_permission' doesn't exist
The SQL being executed was: SELECT \* FROM `group_permission` WHERE (`group_id`=1) AND (`module_id`='space') AND (`permission_id`='create_public_space')
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'facedogs_new.group_permission' doesn't exist
)
↵
Caused by: PDOException

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'facedogs_new.group_permission' doesn't exist

in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/db/Command.php at line 837
1. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/db/Schema.php at line 628
619620621622623624625626627628629630631632633634635636637 
        $exceptionClass = '\yii\db\Exception';
        foreach ($this->exceptionMap as $error => $class) {
            if (strpos($e->getMessage(), $error) !== false) {
                $exceptionClass = $class;
            }
        }
        $message = $e->getMessage()  . "\nThe SQL being executed was: $rawSql";
        $errorInfo = $e instanceof \PDOException ? $e->errorInfo : null;
        return new $exceptionClass($message, $errorInfo, (int) $e->getCode(), $e);
    }

**Comment by Dinevv** [comment]
+1

**Comment by pelennart** [comment]
Try calling https://your-humhub-domain/index.php?r=admin%2Fsetting%2Fself-test

**Comment by Themaster07** [comment]
http://facedogs.net/index.php?r=admin%2Fsetting%2Fself-test


Unknown Property – yii\base\UnknownPropertyException

Setting unknown property: humhub\modules\admin\Module::marketplaceApiValidateSsl
1. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/base/Component.php at line 197
188189190191192193194195196197198199200201202203204205206                    $behavior->$name = $value;
 
                    return;
                }
            }
        }
        if (method_exists($this, 'get' . $name)) {
            throw new InvalidCallException('Setting read-only property: ' . get_class($this) . '::' . $name);
        } else {
            throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);
        }
    }
 
    /**
     * Checks if a property is set, i.e. defined and not null.
     * This method will check in the following order and act accordingly:
     *
     *  - a property defined by a setter: return whether the property is set
     *  - a property of a behavior: return whether the property is set
2. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/BaseYii.php at line 518 – yii\base\Component::__set('marketplaceApiValidateSsl', false)
3. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/base/Object.php at line 105 – yii\BaseYii::configure(humhub\modules\admin\Module, ['modules' => [], 'marketplaceApiValidateSsl' => false])
4. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/base/Module.php at line 138 – yii\base\Object::__construct(['modules' => [], 'marketplaceApiValidateSsl' => false])
5. yii\base\Module::__construct('admin', humhub\components\Application, ['modules' => [], 'marketplaceApiValidateSsl' => false])
6. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/di/Container.php at line 372 – ReflectionClass::newInstanceArgs(['admin', humhub\components\Application, ['modules' => [], 'marketplaceApiValidateSsl' => false]])
7. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/di/Container.php at line 151 – yii\di\Container::build('humhub\modules\admin\Module', ['admin', humhub\components\Application], ['modules' => [], 'marketplaceApiValidateSsl' => false])
8. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/BaseYii.php at line 344 – yii\di\Container::get('humhub\modules\admin\Module', ['admin', humhub\components\Application], ['modules' => [], 'marketplaceApiValidateSsl' => false])
9. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/base/Module.php at line 354 – yii\BaseYii::createObject(['class' => 'humhub\modules\admin\Module', 'modules' => [], 'marketplaceApiValidateSsl' => false], ['admin', humhub\components\Application])
10. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/base/Module.php at line 511 – yii\base\Module::getModule('admin')
11. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/base/Module.php at line 449 – yii\base\Module::createController('admin/setting/self-test')
12. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('admin/setting/self-test', ['r' => 'admin/setting/self-test'])
13. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
14. in /home/facedogs/public_html/index.php at line 25 – yii\base\Application::run()

**Comment by Themaster07** [comment]
please help me ??? :(

**Comment by chandruxp** [comment]
+1

**Comment by luke-** [comment]
Please provide more informations.

e.g. steps to reproduce...

**Comment by chandruxp** [comment]
For me this happened when using humhub updated beta module.

I update from .20.0 to .20.1 with updated module without any problem. And immediately tried to update again to 1.0.0 beta with same module. Then instantly saw this same error message.

I reverted with a backup and didn't get a chance to try again manually.

**Comment by luke-** [comment]
Make sure you always using the latest available updater version.
This may cause the problem.

**Comment by frey1esm** [comment]
Version: 0.3.2 of the updater module was definitely required in order to update to 1.0.0-beta.1. I'm very surprised that the updater module does not validate versions first. My update crashed before I updated that module.
