### ISSUE TITLE
Like link not working on v1.0.0-beta.1

### ISSUE THREAD

**Issue by boutch** [humhub/humhub#1342]
Hello,

I've just updated my Humhub installation to v1.0.0-beta.1. Since then, the like link on the posts has stopped working. The Ajax call is made but an error is returned.

error: true, message: "Unable to verify your data submission."}
error: true
message: "Unable to verify your data submission."

Ajax call url is:
 index.php?r=like%2Flike%2Flike&contentModel=humhub%5Cmodules%5Cpost%5Cmodels%5CPost&contentId=111

Kind regards,

Jean-Luc

**Comment by luke-** [comment]
Maybe a problem with Cookies?

**Comment by boutch** [comment]
The issue has disappeared after I have upgraded to 1.0.0-beta.2.
