### ISSUE TITLE
Question: humhub version and 'Browse online' modules.

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1343]
...the way I see it working is that the application looks for the tag to determine if an install is valid to install a module. How would someone install a module if an application extends the humhub core but does not inherit the tags? Propose the module logic look for the tag in the git history for the tags commit hash, not just if the application is on that specific commit.

**Comment by luke-** [comment]
You can rather manually rise your modified version number or install the modules manually via github.

**Comment by davidjeddy** [comment]
github install sounds reasonable. Dont want to move your tags around.
