### ISSUE TITLE
Database Exception (since 0.21-dev)

### ISSUE THREAD

**Issue by jrschreiber** [humhub/humhub#1345]
**This occurrs after updating to 1.0.0-beta, as well as it did with the past 0.21-dev branch.**

```
Database Exception – yii\db\Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'user_humhub.group_permission' doesn't exist
The SQL being executed was: SELECT * FROM `group_permission` WHERE (`group_id`=1) AND (`module_id`='space') AND (`permission_id`='create_public_space')

Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'user_humhub.group_permission' doesn't exist
)

↵
Caused by: PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'user_humhub.group_permission' doesn't exist

in /var/.../humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 837
```

![unbenannt](https://cloud.githubusercontent.com/assets/14123747/11503076/e288f004-983e-11e5-844a-fc1c1d810943.jpg)

**Comment by Freekkel** [comment]
The following Instruction helped me with such Problems

1) Open self-test & updates from administration menu in another window or tab.
2) Install the module that leads to errors in modules menu
3) Switch back to self-test & updates and restart testing

**Comment by jrschreiber** [comment]
Thanks, but I can't access any of the administration tab (as seen un the 
I turned

**Comment by luke-** [comment]
Did you ran 'yii migrate/up --includeModuleMigrations=1' according to the docs?
https://www.humhub.org/docs/guide-admin-updating.html

**Comment by jrschreiber** [comment]
Now I did... completely missed that. Thanks!

You can close this.
