### ISSUE TITLE
Suggestion: Hashtags and Share

### ISSUE THREAD

**Issue by Censtudios** [humhub/humhub#1347]
**Hashtags** would be cool to quickly find similar posts (you just click on them). Even if the first draft of this would be just aesthetic (link markup, but no actual function behind it when you click on it) it would be nice. It gives the feeling of an actual social network, since hashtags are pretty much a must in today's social networks. Could be an extention of the @ tagging function maybe? Like tagging an expression, rather than another user. Every time a new hashtag is made, it's stored in the database and similar to the tagging, whenever someone else starts typing that same hashtag it shows up in a list.

**Share** Similar to twitter, where you can share other people's posts on your own timeline. Maybe at a later stage it could be developed in a method of finding trending topics or something a lot of members seem interested about going "viral" within your own social network.

I don't know how to make these and I can tell this project is very much community driven, which is something I really like about it, so I thought of writing this post. Maybe it will help :)

**Comment by gharach** [comment]
i agree

**Comment by feldrim** [comment]
Thinking of a hashtag is just a specific search command, it wouldn't be too hard. I suppose, adding a few lines to get  the #... as a hashtag, format and link would be enough.

**Comment by Censtudios** [comment]
Yeah exactly. Making a hashtagged word formatted as a link, as a quick way to use the search feature would probably suffice.

**Comment by Censtudios** [comment]
Any news regarding this feature?

**Comment by feldrim** [comment]
Thinking that catching emojis after ":" sign and usernames after "@" sign are included in humhub/protected/humhub/widgets/RichText.php , I believe catching words after a "#" sign ad turn it to a link like "https://community.humhub.com/search/search/index?keyword=wordwithhashtag" would be enough. I wish I had enough knowledge to code this little stuff but unfortunately I can only tell how it can be done.

**Comment by Censtudios** [comment]
Yeah my coding is not advanced enough to tackle this problem, but I could give it a try, see how far I get. If I do somehow managed to get it to work someone would have to go over the code to make sure it's correct.

**Comment by Censtudios** [comment]
Ok I got it to work lol. That was easier than I thought. Though in the future it would be nice to have a similar list to when you do mentions (@) with tags that were used before. But for now this will suffice.

Follow the simple instructions
https://jsfiddle.net/k8dtcrdx/1/

**Comment by feldrim** [comment]
Can you submit?

**Comment by feldrim** [comment]
@Censtudios Can you make a pull request?

**Comment by feldrim** [comment]
It's been ages. Has anyone ever tried to make a pull request?

**Comment by Censtudios** [comment]
To be honest I'm not sure how that works. I'm fairly new to github. Humhub is the first project I've been involved in. And the system I created is fairly basic.

**Comment by feldrim** [comment]
@luke- Would you do something about that?

**Comment by luke-** [comment]
We plan something like space topics in probably HumHub 1.2
This will also use hashtags.

**Comment by Censtudios** [comment]
Does that also allow to use it on normal profile posts? (not in spaces)

**Comment by luke-** [comment]
Not sure yet.

Topics on user profiles, is maybe not so useful.

**Comment by Censtudios** [comment]
But the purpose for hashtags is to follow trends and topic members talk about. So having these on user profiles is probably beneficial too. If you know what I mean.

**Comment by runonce86** [comment]
Any update on this? What's the current status?

**Comment by gseilheimer** [comment]
Further Idea: Is there an option to get the information of additional fields from the registration field automatically as an hashtag in the profile?

**Comment by saikishorekate** [comment]
Please Give me feedback about this #hash tag feature

**Comment by buddh4** [comment]
@saikishorekate planned is a topic feature for marking/categorizing content and to filter content in streams. Topics will be a part of the core so other modules can easily use topics for thair own purpose it. But this is just a concept yet.

**Comment by TezzahhH** [comment]
That sounds AWESOME!

**Comment by Ace2213** [comment]
There is a [share module](https://github.com/humhub-contrib/sharebetween) but it's basically abandoned.

I was able to get it partially working, the ability to share to your own profile, but it doesn't respect privacy settings of the post/content container where the post came from.

**Comment by nsturtz2** [comment]
I found the code it is at protected/vendor/npm-asset/at.js and there is a hashtags file protected/vendor/npm-asset/at.js/examples/hashtags.html how do I enable it to use in Humhub?

**Comment by buddh4** [comment]
Unfortunately its not that simple. At.js is just a library which was used for the mentioning feature and is not active anymore as far as I know. Implementing the Hashtag feature requires a richtext integration and a content -> hashtag relation.

**Comment by ArchBlood** [comment]
@luke- I believe this can be closed when it comes to sharing, otherwise #3936 should be used for Hashtags.
