### ISSUE TITLE
Can't change layout login page with my theme.

### ISSUE THREAD

**Issue by krai500** [humhub/humhub#1349]
![image](https://cloud.githubusercontent.com/assets/1871329/11537660/a1ecf0f0-9950-11e5-9c21-cbad346b088d.png)

I have put and modified "main.php" according to the above picture.. But Nothing change.

**Comment by andystrobel** [comment]
Do you have choosen "MyTheme" at the admin page? Or maybe a cache issue!?!

**Comment by krai500** [comment]
Yes I have chosen. I think this issue is about humhub\components\Theme Class.
Because pattern is".../views/moduleId/controllerId/viewName.php" .
"layouts" is not a controller id.
So, Theme Class can't find any match layout views.
