### ISSUE TITLE
Add FileInfo to Selftest

### ISSUE THREAD

**Issue by neighlyd** [humhub/humhub#1350]
Whenever I or my users attempt to upload profile images (either in profiles or spaces) the loading bar fills up and stays at full, but it will not upload the image. The Crop-Image dialogue does not come up either. 

I have attempted to upload photos ranging from 1024x1024 to 104x104 to see if it was a size issue. This does not make any difference.

I installed humhub .20.1 and upgraded to version 1.0.0-Beta, if that makes a difference.

![screen shot 2015-12-02 at 11 58 31 am](https://cloud.githubusercontent.com/assets/9094023/11542576/ddeef6de-98ec-11e5-9898-7e36cdff678c.png)

**Comment by neighlyd** [comment]
It appears that the extension fileinfo was not running.

I added the following line to my php.ini and it resolved the issue.

extension=fileinfo.so

**Comment by luke-** [comment]
We should add this to the selftest...
