### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by 1resu** [humhub/humhub#1353]
Hi,

the documentation files under /humhub/protected/humhub/docs/guide/ are slightly outdated. I want to enhance the update instructions but the version in the repository doens't fit with the [online documentation](https://www.humhub.org/docs/guide-admin-updating.html).

Could you please update the files? Anyway: thanks for this great peace of software!

**Comment by luke-** [comment]
Sure?

The online documentation should be daily created from /humhub/protected/humhub/docs/guide/.
Can you give me an example please?

**Comment by 1resu** [comment]
Now I'm not sure - it can't see the difference that I found when I created this issue...
Everything seems fine now.
