### ISSUE TITLE
Push notifications rewrite?

### ISSUE THREAD

**Issue by aqqadk** [humhub/humhub#1354]
Communications is key for a social platform, however, I have noticed that push notifications do not work even after allowing multiple times. I'm not sure how to recreate the issue since its flat out not working. Email is great, but when was the last time you checked your email for a Facebook notification?

**Comment by illmer** [comment]
In our case Push is only working, while I'm on the website. Maybe, that helps. But I totally agree with @aqqadk. Maybe an integration of onesignal.com would be a good idea?

**Comment by Felli** [comment]
Push Notifications isn't fully integrated just yet this is why this issue is still open. :smile:

**Comment by githubjeka** [comment]
onesignal for free Internet, HumHub used often for private intranet

**Comment by githubjeka** [comment]
Just one thing that I want updated that it's the time to show push desktop notification. Now they fast hide. My request is Please add time param for this to config that I can set it on local.
