### ISSUE TITLE
1.0 Beta 1: line breaks in comments occur within words  

### ISSUE THREAD

**Issue by otdftr** [humhub/humhub#1356]
...rather than at whitespace only. See lines 2ff in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/1713611/11613244/7523719e-9c1a-11e5-873a-4c066ef37ac5.jpeg)

**Comment by luke-** [comment]
Should be fixed in beta-2
https://github.com/humhub/humhub/commit/c94a87e2f7179128aca97c428f24cbf9680a73cf
