### ISSUE TITLE
Suggestion: Advanced Search Options

### ISSUE THREAD

**Issue by feldrim** [humhub/humhub#1358]
1. **Search in Profiles:** We can search all the content or search in spaces. Why can't we search in profiles?
2. **Search in Posts/Comments:** To make it specific it would be nice to have some radio buttons like:
   - Search in posts
   - Search in comments
   - Search in posts&comments
3. **Search in Messages:** It seems obvious I think.

**Comment by feldrim** [comment]
Maybe some more additions:
4. **Search in Date: ** Searching posts **from** and **to** a date to make it specific.

5. **Save Search:** Saving a search to use it later.

**Comment by funkycram** [comment]
Yes, search engine could be much better.
We need :
- syntax to be able :
    - to search a complete sentence ; e.g. `"car park"` (today, it finds posts containing only `car`)
    - to use `ADD`
- ordering : show newer posts first

**Comment by Abatjour3407** [comment]
I was just thinking about this... Also, I see in the profile fields one has the awesome option to make a profile field searchable. Maybe one should also include an advanced search filter for these fields to search ONLY in one or more of these fields?

**Comment by luke-** [comment]
@Abatjour3407 A good point. We are planning to tackle the search topic in the upcoming 1.9 version - unfortunately I can't be more specific about the scope of the features/changes yet.

**Comment by feldrim** [comment]
5 years, later, I'm surprised this issue is still in discussion. I opened this issue after the closing of Friendfeed, while a group of the community popped up an instance of Humhub for backup. We were missing the capabilities of Friendfeed, so I decided to work on it. We left the Humhub instance, but the issue still remains. Advanced Search is still a must-have for any kind of social medium. I hope Humhub can somehow manage to have a complete set of advanced search capability.

Sorry for the long comment that does not add anything to the discussion.

**Comment by ArchBlood** [comment]
I like the ideas proposed by this issue, and while it is pretty old, I'd like to say that HumHub has indeed worked a little bit on this when it comes to the mail module, currently there is a search option in it
![Screenshot_1](https://user-images.githubusercontent.com/35392110/109433295-abae6b00-79dd-11eb-956e-b4fc7f0d7841.png)

Currently the issue is that there are no ways implemented to search the index with the `UserPickerField`, and instead you can only search for exact users by name but it shouldn't be that hard to implement :thinking:

My idea would be to implement this field
```php
<?=  Yii::t('SearchModule.base', 'Search only in certain users:') ?>
<?= UserPickerField::widget([
    'id' => 'user_filter',
    'model' => $model,
     'attribute' => 'limitUserGuids',
     'selection' => $limitUsers,
     'placeholder' => Yii::t('SearchModule.base', 'Specify user')
]) ?>
```

**Comment by atdqm** [comment]
Hello,
We use Humhub for 3 months and we think also that the search engine should be ameliorate.
For instance searching a phrase "all the words" or avoid seaching little words like "the" that are found everywhere
Today, we are using Humhub 1.13

**Comment by luke-** [comment]
@atdqm The content search is one of the big points we want to improve soon.
