### ISSUE TITLE
Suggestion: Bring back LDAP for groups

### ISSUE THREAD

**Issue by vutran0424** [humhub/humhub#1360]
I'm not sure why tying a group to LDAP DN was removed. I found it to be very useful and a simple method to fill the landing page for the Directory. Another option would be to have the default Directory page be a list of Members. However once you connect this to LDAP and with no automatic member to group assignment, it leave the landing page of the Directory really bland.

**Comment by luke-** [comment]
Unfortunately since 1.0 we removed this and added it to the Enterprise Edition. https://www.humhub.org/en/enterprise

Basic LDAP Support and Profile Field Synchronisation is still available.

Sorry about that!
