### ISSUE TITLE
Uploading & Viewing Videos

### ISSUE THREAD

**Issue by shnmy** [humhub/humhub#1369]
Hello,
I want to know if humhub currently supports the uploading and viewing of videos.
Thank you very much in advance

**Comment by Havok75** [comment]
+

**Comment by shnmy** [comment]
please  if someone has already faced this problem to answer me !!!!!!!

**Comment by cagatayldzz** [comment]
+1

**Comment by davidfindlay** [comment]
I'm working on a module for this currently that will allow upload of HTML5 video compatible videos.

**Comment by vappleyard** [comment]
Hi,
Any update about this issue?

Thank you!

**Comment by davidfindlay** [comment]
I'm still working on my module, but it's not finished yet. I should have another stab at it.

**Comment by barrelmonkey** [comment]
Was this module ever completed? I am trying to find a way to include videos in posts but can't find a way yet.

**Comment by davidfindlay** [comment]
I'm intending to have another go at finishing my module this weekend. Will advise.
