### ISSUE TITLE
Create new Space

### ISSUE THREAD

**Issue by sdsBG** [humhub/humhub#1372]
Cannot create a new space since i've updated to version 1.0-beta

**Comment by sdsBG** [comment]
![humhub02](https://cloud.githubusercontent.com/assets/13250850/11950474/d7b0e2fe-a888-11e5-90a5-d17c492598cc.PNG)
![humhub01](https://cloud.githubusercontent.com/assets/13250850/11950473/d7b07490-a888-11e5-91b0-c48011da2d39.png)

In earlier version I could create new spaces like I highlighted with green lines.
I have the admin user and 12 spaces, but cannot create a 13th.

In administration menu (groups) I could create new groups for example.
![humhub03](https://cloud.githubusercontent.com/assets/13250850/11950496/13a9eaa8-a889-11e5-95ff-78cc0411b55e.PNG)

**Comment by luke-** [comment]
Make sure you have the permission to create spaces.
You can manage this permission in group administration. Administration -> Groups -> Select/Edit Group

**Comment by ledyspa** [comment]
Same problem here... impossible to create new spaces with SuperAdmin user.

![as_de_led_ _-_intranet](https://cloud.githubusercontent.com/assets/18555049/14642810/2f1802ae-064c-11e6-8840-ed2b136ff9bf.jpg)
![as_de_led_ _-_intranet1](https://cloud.githubusercontent.com/assets/18555049/14642813/31ccffea-064c-11e6-856b-7f1e0bd339b0.jpg)

**Comment by buddha87** [comment]
Please check the permission of the group you are in:
Check your group:
Administration -> Users -> Edit user (your account) -> check Group ID

Check group permission:
 Administration -> Groups -> Select the Group ID  -> check "Create public/private space" permission.

If its not allowed perhaps create a new group with the permission and join the group.

**Comment by ledyspa** [comment]
Solved! Thanks for support!
