### ISSUE TITLE
Space InviteDeclined Notification fatal - (After manual Update 1.0.0Beta1->Beta2)

### ISSUE THREAD

**Issue by otdftr** [humhub/humhub#1373]
...page will only load static content and show the blinking "loading" dots.

I kept the browsers open and just continued my open 1.0.0Beta1 sessions by page reload.
Trying to log off resulted in a "not found" error.

Previous "database upgrade" (console "php yii migrate/up --includeModuleMigrations=1") completed without errors and "nothing to do - everything up to date" or so.

Trying to run a cron/hourly gives the following error (see below), so I successfully :-) rolled back to 1.0.0beta1.

| 261 |     1 | yii\base\ErrorException:8       |  1450211023.019 | [-][1][-]                                        | exception 'yii\base\ErrorException' with message 'Trying to get property of non-object' in /srv/www/intern/HumHub/protected/humhub/modules/space/notifications/views/inviteDeclined.php:6
Stack trace:
#0 /srv/www/intern/HumHub/protected/humhub/modules/space/notifications/views/inviteDeclined.php(6): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/srv/www/intern...', 6, Array)
#1 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/View.php(325): require('/srv/www/intern...')
#2 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/srv/www/intern...', Array)
#3 /srv/www/intern/HumHub/protected/humhub/modules/notification/components/BaseNotification.php(120): yii\base\View->renderFile('/srv/www/intern...', Array, Object(humhub\modules\space\notifications\InviteDeclined))
#4 /srv/www/intern/HumHub/protected/humhub/modules/notification/Module.php(54): humhub\modules\notification\components\BaseNotification->render('mail')
#5 /srv/www/intern/HumHub/protected/humhub/modules/content/Events.php(159): humhub\modules\notification\Module->getMailUpdate(Object(humhub\modules\user\models\User), 'hourly')
#6 [internal function]: humhub\modules\content\Events::onCronRun(Object(yii\base\Event))
#7 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Event.php(188): call_user_func(Array, Object(yii\base\Event))
#8 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Component.php(549): yii\base\Event::trigger(Object(humhub\commands\CronController), 'hourly', NULL)
#9 /srv/www/intern/HumHub/protected/humhub/commands/CronController.php(41): yii\base\Component->trigger('hourly')
#10 [internal function]: humhub\commands\CronController->actionHourly()
#11 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#12 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#13 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('hourly', Array)
#14 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('hourly', Array)
#15 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('cron/hourly', Array)
#16 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('cron/hourly', Array)
#17 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#18 /srv/www/intern/HumHub/protected/yii(29): yii\base\Application->run()
#19 {main} |
| 262 |     4 | application                     | 1450211022.8943 | [-][1][-]                                        | $_SERVER = [
    'TERM' => 'xterm'
    'SHELL' => '/bin/bash'
    'SSH_CLIENT' => '88.79.133.163 62181 33711'
    'SSH_TTY' => '/dev/pts/1'
    'USER' => 'root'
    'MAIL' => '/var/mail/root'
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'PWD' => '/srv/www/intern/HumHub/protected'
    'LANG' => 'de_DE.UTF-8'
    'PS1' => '\\h:\\w\\$ '
    'SHLVL' => '1'
    'HOME' => '/root'
    'LOGNAME' => 'root'
    'SSH_CONNECTION' => '88.79.133.163 62181 94.199.241.163 33711'
    '_' => '/usr/bin/php'
    'OLDPWD' => '/srv/www/intern/HumHub'
    'PHP_SELF' => 'yii'
    'SCRIPT_NAME' => 'yii'
    'SCRIPT_FILENAME' => 'yii'
    'PATH_TRANSLATED' => 'yii'
    'DOCUMENT_ROOT' => ''
    'REQUEST_TIME_FLOAT' => 1450211022.89
    'REQUEST_TIME' => 1450211022
    'argv' => [
        0 => 'yii'
        1 => 'cron/hourly'
    ]
    'argc' => 2
]                                                                                                                                                           |

**Comment by luke-** [comment]
You can try to delete 'inviteDeclined' entries from Notification table manually.

I also had something similar on one installation - we'll investigate...

**Comment by otdftr** [comment]
there was only one. did a 
     mysql> delete from notification where class like '%InviteDeclined';
     Query OK, 1 row affected (0.01 sec)

but that did not help:

| 271 |     1 | yii\web\HttpException:404       | 1450213048.7767 | [82.83.43.242][5][gkrdappq3qdsf0spu6fpfh1u53]    | exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "ico/alert.ico".' in /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Module.php:461
Stack trace:
#0 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('ico/alert.ico', Array)
#1 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request))
#2 /srv/www/intern/HumHub/index.php(25): yii\base\Application->run()
#3 {main}

Next exception 'yii\web\NotFoundHttpException' with message 'Seite nicht gefunden.' in /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/web/Application.php:96
Stack trace:
#0 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request))
#1 /srv/www/intern/HumHub/index.php(25): yii\base\Application->run()
#2 {main}                                                           |
| 272 |     4 | application                     | 1450213048.6545 | [82.83.43.242][5][gkrdappq3qdsf0spu6fpfh1u53]    | $_GET = [
    'uguid' => 'd4b120b9-0b7e-4475-a918-f03054f4273c'
]

$_COOKIE = [
    'pm_user-spaces-panel' => 'expanded'
    'pm_profile-follower-panel' => 'expanded'
    'pm_profile-following-panel' => 'expanded'
...

| 273 |     1 | yii\web\HttpException:404       | 1450213048.8019 | [82.83.43.242][5][gkrdappq3qdsf0spu6fpfh1u53]    | exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "ico/alert.ico".' in /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Module.php:461
Stack trace:
#0 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('ico/alert.ico', Array)
#1 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request))
#2 /srv/www/intern/HumHub/index.php(25): yii\base\Application->run()
#3 {main}

Next exception 'yii\web\NotFoundHttpException' with message 'Seite nicht gefunden.' in /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/web/Application.php:96
Stack trace:
#0 /srv/www/intern/HumHub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request))
#1 /srv/www/intern/HumHub/index.php(25): yii\base\Application->run()
#2 {main}                                                           |
| 274 |     4 | application                     |  1450213048.671 | [82.83.43.242][5][gkrdappq3qdsf0spu6fpfh1u53]    | $_GET = [
    'sguid' => '718719e9-a7c9-4ed0-a14a-db67f989555a'
]

$_COOKIE = [
    'pm_space-members-panel' => 'expanded'
    'pm_getting-started-panel' => 'expanded'
...

**Comment by luke-** [comment]
Now the error changed to a 404, ico/alert.ico

Is there something else wrong?
