### ISSUE TITLE
LDAP: user cannot login if email is empty

### ISSUE THREAD

**Issue by michaelscheurer** [humhub/humhub#1374]
If the email field on ldap of a certain user is empty, it is not possible to login on humhub.

For example the user ludwig-beethoven has no email yet on ldap. Then the following errors occour:

--------------------------------------------------------------------------
ERROR  Wed, 16 Dec 2015 01:17:01 +0100  application
Could not create or update ldap user! (Array ( [email] => Array ( [0] => Email darf nicht leer sein. ) ) )

------------------------------------------------------------------------

Windows 10, Chrome. Humhub-version: 1.0.0-beta.2

**Comment by luke-** [comment]
At the moment an e-mail address is required for users.
https://github.com/humhub/humhub/issues/1381
