### ISSUE TITLE
Too many bugs and issues: Is it worth updating to the new humhub version

### ISSUE THREAD

**Issue by danielrodd** [humhub/humhub#1375]
I have a previous version of humhub that is perhaps outdated, with a few beautiful customazations and plugins that are no longer supported I'm wondering if it's worth updating to the latest stable release, I downloaded it, tried it out, but I didn't like some of the things it has to offer, like for instance the search is no longer suggestive, it actually takes you to a new page, another aspect is that it seems a hell lot slower than the one I'm currently using. Even the design is not as nice anymore, is it my impression or did the change in internal structure ruin humhub? Please help me, I'm trying to measure the pros and cons and see if it's really worth updating or stay put. It seems the issues section suddenly skyrocketed this year.

**Comment by WASasquatch** [comment]
In all honestly, I am not very particular about HumHub as well. They have seemed to ruin astray in their goals. Doing what they want, while forgetting promised features. While that is their prerogative, it is not good look for a open-source development heavily based on user input and satisfaction. 

They have also now relied so heavily on 3rd party frameworks, that HumHub itself is a more a plugin then a framework. 

I can't even install the latest version of HumHub on two paid server do to limitations, and am not going to constitute bad development planning as a reason to change hosts.
