### ISSUE TITLE
under userprofiles setting 

### ISSUE THREAD

**Issue by saurabhchris1** [humhub/humhub#1378]
Under user profile setting if we change some field to recquired at regestration then .....for new users it do not show on profile and also when regestring new user it do not show then last name and first name

**Comment by luke-** [comment]
Make sure the field is also set to "visible"

**Comment by saurabhchris1** [comment]
i tried it but still same problem
and one one more thing i want to ask is how seo for this there is one meta tag title .....

**Comment by saurabhchris1** [comment]
Under administrator setting in user profiles .......when we set birthday to visible and show at registration
......it show at registration page but when we register only username ,password and email is seen ....remaining information is not seen in profiles .......please check this out luke it is a big issue I think.....

**Comment by saurabhchris1** [comment]
i m using 0.20.1 stable version ......also one more issue is humhub loads little slow .....i think it should load faster
