### ISSUE TITLE
Can not update to v1.0.0-beta.1 

### ISSUE THREAD

**Issue by tonsk1** [humhub/humhub#1383]
If i try to update to v1.0.0-beta.1 via Update-Module there is a DB-issue with the following error message: 

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
The SQL being executed was: ALTER TABLE `contentcontainer_permission` ADD CONSTRAINT `contentcontainer_permission_pk` PRIMARY KEY (`permission_id`, `group_id`, `module_id`, `contentcontainer_id` )

**Comment by luke-** [comment]
This problem is fixed in beta.2.

At the moment you can only manually upgrade to beta.2
We try to find a solution...

**Comment by tonsk1** [comment]
How to upgrade manually from v20.1 to v1.0.0-beta.2 ?

I copied all files from beta2 to my server an restored the following files from v20.1:

    /uploads/*
    /protected/runtime
    /protected/config/*
    /protected/modules/* (if any)
    /themes (if any)

if i tried to migrate the DB by command, some files in /protected/vendor was missing. This folder was empty in beta2. So i restored this files from my v20.1.

After that the migration works, but when i visit my humhub now, i get an DB-exception:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zg_humhub2.group_permission' doesn't exist
The SQL being executed was: SELECT * FROM `group_permission` WHERE (`group_id`=1) AND (`module_id`='space') AND (`permission_id`='create_public_space')

What did i wrong?

**Comment by luke-** [comment]
Make sure you follow these steps (Option 2 - manual update):
https://www.humhub.org/docs/guide-admin-updating.html#option-2-manual-update

If you're vendor directory is empty - you didn't downloaded the packages from humhub.org

**Comment by tonsk1** [comment]
Ok, i downloaded it from github. thx!
