### ISSUE TITLE
Bug with: Show user profile post form on dashboard in Admin panel / Basique

### ISSUE THREAD

**Issue by wanes656** [humhub/humhub#1384]
Hi,

I have a problem with the displaying Widget in the dashBoard:
if ($showProfilePostForm) {} 

The TextBox is selected but the widget isn't diplay in the Dashboard.
In the Sql Database, the field: showProfilePostForm the value is 1    but i can't See the user post form in my dashBoard.

Contact me if you want more details: wanes.jean@gmail.com

Jean
French

**Comment by wanes656** [comment]
![image](https://cloud.githubusercontent.com/assets/15703195/11991946/5e02b722-aa20-11e5-905e-d32b8483ecac.png)

**Comment by luke-** [comment]
Why you don't enable it via Admin -> Basic -> Show user profile post form on dashboard

![image](https://cloud.githubusercontent.com/assets/4736168/11995512/2551bd74-aa52-11e5-91e4-a43e65965cd7.png)

**Comment by wanes656** [comment]
Yes, i Dit it. But the widget is still hidden.
![image](https://cloud.githubusercontent.com/assets/15703195/11995586/850e9484-aa53-11e5-8b08-12bdb3bff548.png)


![image](https://cloud.githubusercontent.com/assets/15703195/11995598/b46e0b24-aa53-11e5-8dc9-900028113185.png)

**Comment by luke-** [comment]
The checkbox is not clicked on your screenshot?
Which HumHub version do you use?

**Comment by wanes656** [comment]
![image](https://cloud.githubusercontent.com/assets/15703195/11995644/799cb634-aa54-11e5-87d3-cd637cb3ed2e.png)

![image](https://cloud.githubusercontent.com/assets/15703195/11995653/9d84980a-aa54-11e5-88c0-b70c3c94a964.png)


version Latest Stable Version
0.20.1

**Comment by luke-** [comment]
There is a form above your posts in last screenshot?
