### ISSUE TITLE
Item right side

### ISSUE THREAD

**Issue by arakis2015** [humhub/humhub#1386]
Hi!
Great system... one question :-)
How can I insert a personal item on the right side of the theme (like a wordpress HTML widget)
I want to insert google adsense or some html code......
please take a look at the attached file.

THX for help and merry christmas
vid
![hummi](https://cloud.githubusercontent.com/assets/16439032/12004244/80fc40f2-ab49-11e5-8be1-4843596582ad.jpg)

**Comment by arakis2015** [comment]
No idea?
regards
arakis

**Comment by buddh4** [comment]
this is possible with the latest custom_pages module
