### ISSUE TITLE
Send email to all users

### ISSUE THREAD

**Issue by Eldarya** [humhub/humhub#1387]
Hi, I have a question.
I would like to send an email to mail to all my users, unfortunately, I am too many to make the email manually, and then I wanted to know if there was a way to send an email to mail in other ways.
I already know of the existence of the form "Breaking News," but I do not need much, I need something that will get even users that have not connected for a long time.
Thank you.

**Comment by Censtudios** [comment]
Was already posted here 
https://github.com/humhub/humhub/issues/1275

**Comment by Eldarya** [comment]
Oh thx! :+1:
