### ISSUE TITLE
Error: Call to a member function validatePassword() on a non-object

### ISSUE THREAD

**Issue by Polyhistor** [humhub/humhub#1389]
This is the error displayed while trying to login to the system after the installation, I've tried changing ''$user = $this->getUser();'' to ''$user = new User();'' in ''protected/humhub/modules/user/models/forms/AccountLogin.php'', and the error were gone, but then my login credentials were not properly validated and now I getting the error: "wrong username or email" on the login form, What is the possible solution? any material to study in order to fix this? I'm quite new to this framework, and internet weren't much of a help regarding my issue, any consideration is highly appreciated...

**Comment by krai500** [comment]
"User" model have relation with "Password" model.
So if you create new User. You will don't get Password.
