### ISSUE TITLE
Admin Theming

### ISSUE THREAD

**Issue by marietaGonzales** [humhub/humhub#1390]
i'm trying to theme the admin side so I think that i have to do this to my theme

mytheme\views\admin\ _layout.php

for theming this 

protected\humhub\modules\admin\views\ _layout.php

I think that i'm right or i'm wrong?

**Comment by krai500** [comment]
Did you forget '\' ?

mytheme\views\admin\_layout.php

for theming this

protected\humhub\modules\admin\views\_layout.php

**Comment by marietaGonzales** [comment]
but that dosent work :(  i can't see anychange

**Comment by 0berst** [comment]
same problem here, tried to theme the dashboard but I'm not able to get the changes to show up

copied the layout.php from /protected/humhub/modules/dashboard/views/dashboard/ and put it at mytheme/views/dashboard/layout.php, changed some things, but nothing happend

is this a bug or is the files position wrong?

**Comment by krai500** [comment]
I used to have this problem too.Please tell me more environment info. Such as type of OS that your are development.

**Comment by 0berst** [comment]
my current environment: Debian 8 Jessie, Apache 2.4, PHP 5.6, HumHub 1.0.0-beta.3

**Comment by krai500** [comment]
https://github.com/humhub/humhub/tree/v1.0.0-beta.3/protected/humhub/modules/dashboard/views/dashboard

I have checked. This folder don't have "layout.php" file. 
So you can't change theme with that file.

**Comment by 0berst** [comment]
I misstyped, I meant "index.php", I copied the file and changed it, it didn't work
