### ISSUE TITLE
Cannot set default user profile visibility

### ISSUE THREAD

**Issue by TigerHix** [humhub/humhub#1391]
Whenever I am trying to set "Default user profile visibility" under "Authentication", the option "Visible for members+guests" could not be saved. The error reads "Default user profile visibility must be either "1" or "0"."

I have already enabled "Allow limited access for non-authenticated users (guests)" option above.

**Comment by amrit5003** [comment]
Were you able to find solution for this problem?
I am getting an exact error
'Default user profile visibility must be either "1" or "0" '
