### ISSUE TITLE
search engine optimization humhub

### ISSUE THREAD

**Issue by saurabhchris1** [humhub/humhub#1394]
how to make humhub search engine friendly

**Comment by feldrim** [comment]
I have another question about that. What if we don't want search engines peek through our network? An SEO development must allow administrators choose if the network could be searched and indexed by search engines or could be kept hidden.

**Comment by cebe** [comment]
@feldrim you can not forbit search engines to read your content but normally they respect a robots.txt entry so you can create such a file in your webroot: http://www.robotstxt.org/
