### ISSUE TITLE
Small UI issue in Administration -> User Profiles

### ISSUE THREAD

**Issue by makhnovskiy** [humhub/humhub#1396]
When visiting "User Profiles", looking in the sub-menu, the menu item is not active. Should be a quick easy fix.

<img width="523" alt="screen shot 2016-01-02 at 3 16 16 pm" src="https://cloud.githubusercontent.com/assets/3479205/12076539/d9d16444-b163-11e5-8861-1c2c25c5ef06.png">

<img width="594" alt="screen shot 2016-01-02 at 3 16 24 pm" src="https://cloud.githubusercontent.com/assets/3479205/12076540/deb4df54-b163-11e5-9ba8-29e2ce508088.png">

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/79afbc2892c04c9025ae5ee472385b7c5f2a15f4
