### ISSUE TITLE
Installation Issue : mb_internal_encoding('UTF-8');

### ISSUE THREAD

**Issue by maddox22** [humhub/humhub#1397]
hello sir 
my name is maddy and i was trying to use your script for making social network and when i m going to install your script in my server then i will face 
php fatal error for below code -

mb_internal_encoding('UTF-8');

so plz help me 

my server is godaddy's vps server 
with CentOS 6 + cPanel plz help me 

and i m using your latest script humhub-1.0.0-beta.3

and also tell me how can i create server setting for your script i mean  Apache settings

**Comment by luke-** [comment]
You'll require php multibyte extension
https://www.humhub.org/docs/guide-admin-requirements.html#general-requirements
