### ISSUE TITLE
Viewing files is not working --> Failed to load image:

### ISSUE THREAD

**Issue by testversuch** [humhub/humhub#1400]
Hello,
we've installed Humhub and it is a great network with an amazing design.
The problem is that files, which are uploaded to any stream are not visible. 
The path or anything else ist wrong. 
so when clicking on the file, the picture, video or document isn't visible. 

At a test of humhub 2 month ago, everything works fine. The server options didn't change.
We also tested a diffrent server and and the latest beta version of humhub.

It would be great, if anybody has an idea to fix this problem.

Thank You 

![test-image](https://cloud.githubusercontent.com/assets/12462305/12119167/5f4c7f42-b3ca-11e5-9d93-4ebdd7ac2011.png)
![test-image2](https://cloud.githubusercontent.com/assets/12462305/12119168/5f508146-b3ca-11e5-9e8c-c4da37657303.png)

**Comment by hanninger** [comment]
did someone solve this problem - it's the same with me...! Thanks

**Comment by dakur** [comment]
Try to make a change in web browser inspector - remove the # symbol from the image address so it will be http://.....-9c535761c877.jpeg
Does it now work? If yes, then there's an error in the path construction.

**Comment by milizeus** [comment]
deactivating <Use X-Sendfile for File Downloads> fixed it for me.

**Comment by rauldipeas** [comment]
I'm getting the same error.

**Comment by boily-qubeos** [comment]
I'm getting the same error. the directory file is created: 
uploads/file/98a636cc-835b-4d70-a8a7-8b38e96a9141/
but the directory is empty. 
I've tried with a 777 permission on the uploads directory, disabled the "Use X-Sendfile for File Downloads" option but with no success.
Does anyone has a trick to make it working?
Thanks to all.

**Comment by boily-qubeos** [comment]
The problem in my situation was that the **upload_max_filesize** configuration in php /etc/php/apache2/php.ini was too low. Just set it to a higher value (30M should be OK) and restart apache2.

**Comment by weshpoupou2** [comment]
I have the same problem... 
When connecting with IP address, the pictures appear ; with the domain name, images are broken...
I have disabled the "Use X-Sendfile for File Downloads" option.
![erreur HUMHUB](https://user-images.githubusercontent.com/97392624/148692304-211d23cf-0466-4ffb-b23f-7cfc9e93a2d8.png)
