### ISSUE TITLE
Private/public space inversion bug at creation

### ISSUE THREAD

**Issue by happyfredo** [humhub/humhub#1403]
Hi team !!

We notice a bug when we create space.
We choose public -> And in admin it's private.
When we change later in space option it's ok, it's only in creation.
If we force a group to create only public space, we have only private radio button and can't validate space creation.
![01](https://cloud.githubusercontent.com/assets/292381/12155186/257b156c-b4c4-11e5-8eee-ad05c7fa9365.png)
![2](https://cloud.githubusercontent.com/assets/292381/12155189/28a32aa4-b4c4-11e5-8f89-b51039245a3f.png)

I think there is an inversion of option.

**Comment by happyfredo** [comment]
same bug on your cloud service

**Comment by luke-** [comment]
Fixed: https://github.com/humhub/humhub/commit/b44699b3644bf67d500ac51cd44619764a336deb
