### ISSUE TITLE
User Profile > Modification > Checkbox hide year of birthdate

### ISSUE THREAD

**Issue by ygrosyeux** [humhub/humhub#1407]
Hello Team,

We notice a bug on user's profile when we modify the checkbox "Hide year in the birthdate".
>> When we save profile, this information isn't saved

Does anyone else have this problem ?

Thanks

Yann

**Comment by ygrosyeux** [comment]
We encounter this problem on the beta 3

**Comment by ygrosyeux** [comment]
![image](https://cloud.githubusercontent.com/assets/16611866/12201584/741ca0ac-b625-11e5-97bf-563d091c129e.png)

**Comment by happyfredo** [comment]
Hi @ygrosyeux  

It work here (beta 3 french version too)
