### ISSUE TITLE
Language selection forgotten when finished first setup

### ISSUE THREAD

**Issue by dakur** [humhub/humhub#1409]
Just now I was installing new HumHub (current clone, last commit 0105c5 from master), I chose Czech language in first setup and it went well. But when the setup was finished and I clicked Finish, it jumped to login screen and the language was back to default (English US). It's low prio, but it should not be difficult to fix it, I guess.

**Comment by githubjeka** [comment]
[This code](https://github.com/humhub/humhub/blob/master/protected/humhub/components/i18n/I18N.php#L68) responsible for it
```php
 public function setGuestLocale()
    {
        //...
        $languageChooser = new ChooseLanguage();
        if ($languageChooser->load(Yii::$app->request->post()) && $languageChooser->save()) {
            Yii::$app->language = $languageChooser->language;
        } else {
            $language = $languageChooser->getSavedLanguage();
            if ($language === null) {
                // Use browser preferred language
                $language = Yii::$app->request->getPreferredLanguage(array_keys($this->getAllowedLanguages()));
            }
            Yii::$app->language = $language;
        }

        $this->fixLocaleCodes();
    }
```

cookie guest

```
'expire' => time() + 86400 * 365, // 1 year
```

At the moment, this issue fixed.
