### ISSUE TITLE
mention @ on samsung android duplicate character

### ISSUE THREAD

**Issue by happyfredo** [humhub/humhub#1411]
Hi !

When we mention a name on samsung s5 (chrome and native browser) the mention add the char

exemple 
@seb -> Sebasien XXXX **seb**

Best regards

Fred

**Comment by happyfredo** [comment]
Hello,

Some precisions, it's only when the predictive keyboard is on. On a natural keyboard it's ok.

**Comment by buddha87** [comment]
Is this still an issue? Could not reproduce this, could you provide a screenshot or anything?
