### ISSUE TITLE
Video link/preview disappears after editing existing post

### ISSUE THREAD

**Issue by efelon** [humhub/humhub#1416]
Humhub 1.0.0-beta.3
Firefox 40.0.2
Windows 7

Reproduce:

* Create a post with content:
```
Video1:
https://www.youtube.com/watch?v=ia6OvV9aBzg
```
* Save Post
 * Post with video preview is visible.
* Edit Post and add another video link in the first line:
```
Video2:
https://www.youtube.com/watch?v=fciQpDDsAjw
Video1:
[...]
```
* Save
 * Video link/preview of videolink1 is gone.

**Comment by kevmax** [comment]
Can confirm the same / similar: type some text and paste in video link.
Both display fine. Then edit the post , and ONLY change the text and click save - only the text remains - the video 'disappears'
