### ISSUE TITLE
Android notification ?

### ISSUE THREAD

**Issue by happyfredo** [humhub/humhub#1418]
Android notification for chrome (v47) seem don't work actually.
Bug or enhancement ?

Best regards to the team

**Comment by happyfredo** [comment]
Apparently code work only for desktop notification.
Perhaps use this methos will be useful

http://deanhume.com/home/blogpost/push-notifications-on-the-web---google-chrome/10128

Best regards

**Comment by zelectron** [comment]
Notification in not working in Android app.
Is there any fix/patch ?

**Comment by buddha87** [comment]
There is no mobile app yet, we'll provide a mobile app with push notifications as soon as possible.

**Comment by CBRSHDW** [comment]
Any chance the push notifications are close to finialized?

**Comment by buddh4** [comment]
Duplicate of https://github.com/humhub/humhub/issues/1354 this is planned soon (for android and desktops).
