### ISSUE TITLE
Referential integrity.

### ISSUE THREAD

**Issue by VasileGabriel** [humhub/humhub#1421]
I noticed Humhub database tables have no foreign keys between them and all the referential integrity is done through the code itself and sometimes by running integrity/run command.
I think adding relations to the tables would make for a good change and it would remove the need for this 
[User.php](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/User.php#L109), as it queries the database for each user's profile.

Also in file [SpaceModelMembership.php](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/behaviors/SpaceModelMembership.php#L156)
 on my humhub install caching the result of this method gives 15 less queries on space pages.
Let me know if these are good changes and I'll prepare a PR.

**Comment by luke-** [comment]
Yes, we should use foreign keys when possible!

Would be awesome if you want to create a PR. Please use branch dev-1.1
https://github.com/humhub/humhub/tree/v1.1-dev
