### ISSUE TITLE
Do not use reserved SQL keywords as table names

### ISSUE THREAD

**Issue by stupiddog1979** [humhub/humhub#1424]
In the same way as a Java developer would never, ever use names like "double", "catch" or "if" as variable names, it is an extremely dangerous practice to use "GROUP" and "LIKE" as table names in HumHub, even where a RDBMS allows that.

Although not strictly a reserved keyword in ANSI-SQL, "COMMENT" (Reserved keyword at least in Oracle RDBMS and possibly in other RDBMS as well) should also be avoided.

**Comment by fdesanto** [comment]
Suggestion for team: this is very important issue, the best way is to use table prefix, docs at http://www.yiiframework.com/doc-2.0/yii-db-connection.html#$tablePrefix-detail

**Comment by stupiddog1979** [comment]
The tablePrefix proposal looks good, but please beware that this problem can apply to database identifiers in general, i.e. it can also affect schema names, column names, names of functions defined inside the database schema (if HumHub uses such functionality) etc.

**Comment by thewhiterabbit** [comment]
I'm trying to implement table prefixes in my HumHub installation. I have edited protected/vendor/yiisoft/yii2-gii/generators/model/Generator.php (prior to running the install) to look like this...
![screen shot 2016-06-02 at 9 44 22 am](https://cloud.githubusercontent.com/assets/5334222/15753200/b0202828-28a6-11e6-85d8-a150cba4115c.png)
...but it's not adding a tablePrefix "yii2" as assigned.

What am I doing wrong? I would like to implement this feature correctly and submit a pull request...

**Comment by fdesanto** [comment]
Hi @thewhiterabbit 
this is normal, this is proposal for Humhub developers.

To works this they need to change tables name in model file like docs at http://www.yiiframework.com/doc-2.0/yii-db-connection.html#$tablePrefix-detail

**Comment by thewhiterabbit** [comment]
@fdesanto I have looked at the yii2 documentation, but the way they (HumHub dev team) are using yii2 does not seem to correspond with the documentation.

I am unable to locate the common\config\main-local.php file in the HumHub directory structure, not even under the vendors/yiisoft directory, nor in any other paths, as described here http://stackoverflow.com/questions/28998385/yii2-gii-table-prefix

**Comment by thewhiterabbit** [comment]
Well, I have changed table prefix to 'yii2_' here...
![screen shot 2016-06-02 at 11 21 21 am](https://cloud.githubusercontent.com/assets/5334222/15756046/556e3b3c-28b4-11e6-81cf-9436e9245db2.png)
...in protected/vendor/yiisoft/yii2/db/Connection.php

Also set $useTablePrefix = true; in the MigrateController.php...
![screen shot 2016-06-02 at 11 26 44 am](https://cloud.githubusercontent.com/assets/5334222/15756181/f4acaa08-28b4-11e6-8d72-85107718f5fd.png)
...in protected/vendor/yiisoft/yii2/console/controllers/MigrateController.php

AND set $useTablePrefix = true; in model generator...
![screen shot 2016-06-02 at 11 29 58 am](https://cloud.githubusercontent.com/assets/5334222/15756327/98439744-28b5-11e6-92fd-1b5b78074714.png)
...in protected/vendor/yiisoft/yii2-gii/generators/model/Generator.php

HumHub still fails to create tables with the prefix set in $tablePrefix parameter. As far as I can tell by doing a find in the installed HumHub root folder - 21 items found in 7 documents and only 3 lines that seem to be relevant for setting the tablePrefix value and enabling the use of it.

Can someone from the HumHub team please address this so I can fix it for you? I would love to contribute, but at this point I have hit a dead end.

**Comment by fdesanto** [comment]
all these things will not works because humhub do not use tables name like {{%test}}, it use static names, so it not possible to generate tables prefix.

my proposal was to change all table names with format like '{{%test}}' instead simple 'test'. now humhub have a big limit

**Comment by thewhiterabbit** [comment]
OK, I understand now. Maybe I can change the code in all model class files...

public static function tableName()
    {
        return 'table_name';
    }

...to...

public static function tableName()
    {
        return $tablePrefix.'table_name';
    }

I'll do that and then test it.

**Comment by thewhiterabbit** [comment]
Actually my instincts tell me this will be better...

```
public static function tableName()
    {
		if (isset($tablePrefix && !empty($tablePrefix)))
		{
			return $tablePrefix.'table_name';
		}
		
		return 'table_name';
    }
```

**Comment by thewhiterabbit** [comment]
Also changing the tableName "like" to "likes" for obvious reasons. Almost done. Testing soon.

**Comment by thewhiterabbit** [comment]
I noticed just now while dropping the tables to reinstall - the 'log' and 'migration' tables were renamed with the prefix I added 'yii2_log' and 'yii2_migration'.

I'm testing the install again but I think now it will rename those tables 'yii2_yii2_log' and 'yii2_yii2_migration'. If that happens I will figure out a workaround. I don't quite understand how to use the '{{%test}}' naming method yet.

**Comment by thewhiterabbit** [comment]
Almost done testing. Looking good so far. Had to make many many changes!

**Comment by thewhiterabbit** [comment]
I give up... Not enough documentation and not enough understanding on my part... 
![screen shot 2016-06-02 at 9 44 28 pm](https://cloud.githubusercontent.com/assets/5334222/15769002/64c45f6a-290b-11e6-8496-2d9158a274d2.png)

**Comment by buddha87** [comment]
I haven't tried it by myself but don't you have to set the table prefix in the configuration as here: http://stackoverflow.com/questions/10646597/how-do-i-set-table-prefix-in-yii. The problem is that HumHub creates the db config dynamicly in /protected/config/dynamic.php. I think you'll have to add the settings in the Settingcontroller: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/installer/controllers/SetupController.php#L77 before installation. If this is working for you let us know and we could include something like this in v1.2.

**Comment by thewhiterabbit** [comment]
@buddha87, Ok I forked and edited these following files accordingly...

https://github.com/thewhiterabbit/humhub/blob/master/protected/humhub/modules/installer/views/setup/database.php#L49

https://github.com/thewhiterabbit/humhub/blob/master/protected/humhub/modules/installer/forms/DatabaseForm.php#L44

https://github.com/thewhiterabbit/humhub/blob/master/protected/humhub/modules/installer/controllers/SetupController.php#L77

Anything else required to make this work?

I noticed that the "vendor" folder is empty. Do I need to add it from the zip I downloaded from HumHub website in order to make it work or will it install/run without it?

**Comment by buddha87** [comment]
I think you have to return something like this {{%TableName}} in your tableName functions of models which fail to create in your case

**Comment by thewhiterabbit** [comment]
@buddha87, thanks for the fast reply. Could you please link me to a file and line number I need to change? Then I will make all the required changes to get this feature working. :)

**Comment by thewhiterabbit** [comment]
Is this correct?
```
/**
 * This is the model class for table "user_auth".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $source
 * @property string $source_id
 *
 * @property User $user
 */
class Auth extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user_auth}}';
    }
```

**Comment by thewhiterabbit** [comment]
I've replaced all table names with {{%TableName}} as shown above. The install doesn't even get past the first "next" button. It's an unrelated issue. If it's not already on here I'll create a new issue.

**Comment by thewhiterabbit** [comment]
@buddha87, @luke-  My fault, I included the wrong vendor folder in my upload. Fixed that, but...

So far I was able to get the fields to show up in the install setup database screen, but when I submit the information by clicking "next" the following is the error I get:
```
 PHP Notice – yii\base\ErrorException
Undefined variable: useTablePrefix

    1. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/humhub/modules/installer/controllers/SetupController.php at line 83
    74757677787980818283848586878889909192

                    $password = $config['components']['db']['password'];
     
                // Create Test DB Connection
                $dbConfig = [
                    'class' => 'yii\db\Connection',
                    'dsn' => $connectionString,
                    'username' => $model->username,
                    'password' => $password,
                    'charset' => 'utf8',
                    'useTablePrefix' => $useTablePrefix,
                    'tablePrefix' => $tablePrefix,
                ];
     
     
                Yii::$app->set('db', $dbConfig);
     
                try {
                    // Check DB Connection
                    Yii::$app->db->open();

    2. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array:{/home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/InlineAction.php:55}()
    3. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams()
    4. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction()
    5. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction()
    6. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest()
    7. in /home/m1chaelkent/public_html/cannacle.com/streams/index.php at line 25 – yii\base\Application::run()
    19202122232425

        require(__DIR__ . '/protected/humhub/config/web.php'),
        (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
        require(__DIR__ . '/protected/config/common.php'),
        require(__DIR__ . '/protected/config/web.php')
    );
     
    (new humhub\components\Application($config))->run();

$_GET = [
    'r' => 'installer/setup/database',
];

$_POST = [
    '_csrf' => 'YmUtQmZOYmswHGIUCBQbHAk9WgY5NjgsICEaBzN2DCINE3sHDRkwJQ==',
    'DatabaseForm' => [
        'hostname' => 'localhost',
        'username' => 'datauser',
        'password' => 'password',
        'database' => 'dataname',
        'useTablePrefix' => '1',
        'tablePrefix' => 'hum_',
    ],
];
```
So, how do I pass those new parameters on from the form to the $dbConfig array?
Shouldn't the framework set those fields into variables of the same name?

**Comment by thewhiterabbit** [comment]
I eliminated that error and now it's saying that useTablePrefix is an unknown property...
![screen shot 2016-06-03 at 6 58 09 pm](https://cloud.githubusercontent.com/assets/5334222/15796928/2f5710ea-29bd-11e6-8fe4-0c6322de3e2c.png)

I traced back to where the error is generated, but I don't know enough about Yii2 to go any further...
![screen shot 2016-06-03 at 7 16 17 pm](https://cloud.githubusercontent.com/assets/5334222/15797036/b8da9f92-29bf-11e6-8864-5d793ba73d34.png)

**Comment by luke-** [comment]
There is no 'useTablePrefix' attribute in DB connection - try to just set 'tablePrefix'.
http://www.yiiframework.com/doc-2.0/yii-db-connection.html#$tablePrefix-detail

Anyway I think a better solution for reserved SQL keywords will be to just rename the tables, e.g. we can find some syntax like "moduleId_modelId" so the 'like' table will be renamed to 'like_like' or the 'group' table to 'user_group'.
