### ISSUE TITLE
How to install non-Official plugins?

### ISSUE THREAD

**Issue by Ardnived** [humhub/humhub#1429]
I'm trying to test a few plugins with my personal HumHub installation. I downloaded the plugin, unzipped it, and placed it in the /protected/modules folder, as instructed. But the new modules don't appear in the Modules directory (/admin/module/list).

Anyone know what I'm supposed to do?

**Comment by tobciu** [comment]
which version of humhub do you use?
can you name us the humhub-module /can you provide us a link?  or can you make a screenshot from the /protected/modules/<your_module> directory?

**Comment by Ardnived** [comment]
HumHub v1.0.0-beta.3

Here are the plugins that I added to try out
https://github.com/ychoucha/HUMHUB-module-chat
https://github.com/WASasquatch/humhub-modules-onlineusers
https://github.com/Basster/humhub-modules-recent-spaces
https://github.com/WASasquatch/humhub-modules-random-space

I'll note that all the installed official plugins are still available in the Modules panel.

Here's a screenshot of my /protected/modules directory
![FileZilla Screenshot](https://cloud.githubusercontent.com/assets/1362167/12337088/cc51abb4-babc-11e5-84b1-6f6503ee049b.png)

**Comment by Felli** [comment]
The simplest answer to your question is that these modules aren't updated to work on the yii2 framework (Humhub 0.20 and newer.)

**Comment by Ardnived** [comment]
Ah that's a shame. Thanks for your time @tobciu and @Felli

**Comment by Felli** [comment]
@Ardnived just to note there is another method of "chat" which can be found [here](https://github.com/petersmithca/humhub-basic-chat).
