### ISSUE TITLE
Verified User Accounts

### ISSUE THREAD

**Issue by andipalmer** [humhub/humhub#1431]
Hey there! I have just started my new community and I love the software. I have been wondering if there is a module or extension that would allow me to "verify" other user accounts or maybe spaces to show that they are the original authentic profile or space on the website and also to help prevent fake-accounts.

I have searched the internet but could sadly not find anything like this. It would be awesome if someone could help create a module like this where you could give out the badge from the admin panel to users and spaces, as I have seen some other posts on here like this.

Here's a screenshot attached of a quick example I made how this could look like.

<img width="1150" alt="screen shot 2016-01-17 at 05 33 01" src="https://cloud.githubusercontent.com/assets/16740257/12375972/d67d5432-bcdb-11e5-934e-ea0c70167684.png">

Thanks!

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/920

**Comment by RamonGuilherme** [comment]
+1

**Comment by Zenternal** [comment]
This should be reopened, @luke- 
Its a good idea.

**Comment by darien12** [comment]
Please do this!

**Comment by Felli** [comment]
Please refer to issue #920 as this is a duplicate request. :wink:
