### ISSUE TITLE
User Registration: PHP Notice – yii\base\ErrorException : Undefined offset: 1 

### ISSUE THREAD

**Issue by malovern** [humhub/humhub#1435]
When a user enters their email address to register from the main sign up box and clicks Register we get the following message:

![capture](https://cloud.githubusercontent.com/assets/9249158/12421961/7ad5d608-bebc-11e5-96e9-19344b67dc7f.PNG)

**Comment by luke-** [comment]
Hmm, seems to be a problem with your E-Mail Configuration...
