### ISSUE TITLE
PHP Fatal Error yii/base/errorexception 

### ISSUE THREAD

**Issue by designtyler** [humhub/humhub#1436]
![screenshot 25](https://cloud.githubusercontent.com/assets/14317245/12438759/6434b58a-beef-11e5-9da8-4c2858658942.png)
![screenshot 26](https://cloud.githubusercontent.com/assets/14317245/12438760/6436c898-beef-11e5-96b9-f6ed50089df2.png)

Not gonna lie ya'll... Im new to the game and still learning A LOT. I just set up my first VPS because i was maxing out my hosting. take it easy on me :)

**Comment by luke-** [comment]
You need to install http://php.net/manual/de/mbstring.setup.php

**Comment by designtyler** [comment]
Fixed the issue! Thanks, you're awesome!

-----Original Message-----
