### ISSUE TITLE
Users Profile Editing Problem || Data is not Saving || Please Solve this Problem  

### ISSUE THREAD

**Issue by maddox22** [humhub/humhub#1437]
in my website user cant update there profile they can edit there profile but cant save changes plz need to solve this issue and also i cant use some admin option like i cant use that become user option when i click on that option nothing happen

**Comment by maddox22** [comment]
when user go and edit their profile data is not saving all fields user see blank and when i go from administrator account and i click on become users button that button dont working nothing happen

**Comment by maddox22** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11087996/12591841/ca8cdb78-c48f-11e5-8cd1-961e93841f8d.png)

**Comment by maddox22** [comment]
after saving 
![untitled](https://cloud.githubusercontent.com/assets/11087996/12591898/fbafeb00-c48f-11e5-9ce1-96b99ac5ca59.png)

**Comment by saurabhchris1** [comment]
have you used birthday as visible and show at registration page in settings under user profiles?

coz this is issue on humhub

**Comment by enemykilowatt** [comment]
I'm having this issue as well.  

I've filled out the entire profile, clicked "Save Profile", and been returned to the profile form with all the fields I just entered blanked out again. Only _First name,_ _Last name_, _Title _and _Gender _values are being saved.  I have hidden the Birthday field, but have not changed any other fields from the installed defaults.

**Comment by enemykilowatt** [comment]
Might be related... I just created a new profile field as a test and now I cannot delete that field.

**Comment by joseph-kuruvilla** [comment]
We are facing same issue.  User Profile fields are not saved. Any update or solution for this. thanks.

**Comment by thomasical** [comment]
On my HumHub site, users can not update their profiles. 

- Users can press "Edit Account" button.
- Users then see the "edit profile" page.
- Users can then enter changes in their profile fields.
- But when users press "Save Profile" save button changes are not saved, and user remains on the "Edit Account" page.

Please advise.

**Comment by buddha87** [comment]
does this still occure on v1.1?

**Comment by joseph-kuruvilla** [comment]
Issue fixed.
