### ISSUE TITLE
login page and language

### ISSUE THREAD

**Issue by Guardian1983** [humhub/humhub#1438]
protected/humhub/modules/user/messages/da/forms_AccountLoginForm.php
is not working on login page? Still is English language.. 
Everything else is in Danish, and working fine ;-)
![unavngivet](https://cloud.githubusercontent.com/assets/12225536/12515461/c3e012c8-c128-11e5-8341-0a9bd32f7923.png)

**Comment by luke-** [comment]
You mean "Incorrect username or password." is missing?

**Comment by Guardian1983** [comment]
It's not missing, as you can see in the post/picture... "Incorrect username or password." is the wrong language ;-)

**Comment by Guardian1983** [comment]
No feedback on this? ;-)

**Comment by Mouflin-Guillaume** [comment]
@luke- I have the same problem with version 1.5.3. I can't change the translation of "User or password incorrect". In model form login, this error is not a translation 
`$this->addError('password', 'User or Password incorrect.');`
It should be ` $this->addError('password', Yii::t('UserModule.auth', 'User or Password incorrect.');`
