### ISSUE TITLE
Uploaded modules not showing in admin panel, cannot activate them

### ISSUE THREAD

**Issue by Censtudios** [humhub/humhub#1440]
So I uploaded some modules into protected/modules but none of them show up on the modules page on the admin panel. This means I can't install any of these modules. Am I missing something or is this a bug?

The modules are up to date and I'm using HH 1.0 beta2

**Comment by luke-** [comment]
Are you sure these modules are compatible with 1.0?

**Comment by davidfindlay** [comment]
I'm having the same issue, although I'm developing one for a site currently running on 0.20 release. I've uploaded to protected/modules but can't see my module. Will much work be needed to upgrade for 1.0?

**Comment by Felli** [comment]
To be exact which modules are you using? Are they custom modules that you've created, or found here on GitHub?

**Comment by davidfindlay** [comment]
In case you're having the same trouble I was having with a custom module I'm creating, here's what I found. I had based mine of the example module, but it didn't have a config.php. I copied and modified the config.php used in the Dropbox module and then managed to make it work.

**Comment by Censtudios** [comment]
One of the modules was apparently not for 1.0, but the others are. I'll try the config.php thing @davidfindlay mentioned

**Comment by dzomb** [comment]
sms module not showing up for me...

**Comment by buddh4** [comment]
In case this still occures, I'll reopen this issue.
