### ISSUE TITLE
File upload character problem

### ISSUE THREAD

**Issue by OzkanOner** [humhub/humhub#1443]
I have a problem with file names on post uploads.

So, I tried to upload file named örnek.doc, the file can be uploaded. But I can't download this file. This error is showing up:

"Oooops... It looks like you may have taken the wrong turn. 
Could not find requested file!"

If the file name has Turkish characters like ÇÖİŞÜĞ etc. file cannot be downloaded. My humhub version is 1.0.0 beta-3

**Comment by luke-** [comment]
Should be fixed in upcoming beta-4.

https://github.com/humhub/humhub/commit/40d2d7c118e11cef5b59b0acc3fc5d01304a7953
