### ISSUE TITLE
error install 1.0.0-beta 3

### ISSUE THREAD

**Issue by Themaster07** [humhub/humhub#1444]
my site www.facedogs.net 

Invalid Parameter – yii\base\InvalidParamException

The file or directory to be published does not exist: /home/facedogs/public_html/protected/vendor/bower/jquery-nicescroll
1. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/web/AssetManager.php at line 452
443444445446447448449450451452453454455456457458459460461    public function publish($path, $options = [])
    {
        $path = Yii::getAlias($path);

```
    if (isset($this->_published[$path])) {
        return $this->_published[$path];
    }

    if (!is_string($path) || ($src = realpath($path)) === false) {
        throw new InvalidParamException("The file or directory to be published does not exist: $path");
    }

    if (is_file($src)) {
        return $this->_published[$path] = $this->publishFile($src);
    } else {
        return $this->_published[$path] = $this->publishDirectory($src, $options);
    }
}
```
1. in /home/facedogs/public_html/protected/vendor/yiisoft/yii2/web/AssetBundle.php at line 163 – yii\web\AssetManager::publish('/home/facedogs/public_html/prote...', [])

**Comment by luke-** [comment]
Did you updated as described here: https://www.humhub.org/docs/guide-admin-updating.html#gitcomposer-based-installations and ran **composer update** ?

**Comment by cndlhvn** [comment]
I got same issue.
But, this problem reasen is to use old composer version.
My old composer version is 
`Composer version 1.0-dev (1c525b76f81123af180743d31c208c29351cf931) 2015-12-09 15:47:26`

So you have to update composer version.
`$ composer self-update`

This is latest version of composer 
`Composer version 1.0-dev (1dce6442ed2518855d096d1123f04472d9b6f764) 2016-03-11 10:30:26`
after update composer, you run again.

`$ composer update`

Composer update will be succeed.
