### ISSUE TITLE
Disable Following

### ISSUE THREAD

**Issue by Ardnived** [humhub/humhub#1447]
A feature suggestion. The ability to disable "Following." We'd like our network to be more focused around Spaces and found that individual walls / following are a bit of a distraction.

For the moment I've simply created a theme which hides all follow buttons and following info, but if implemented as a feature it could also do something about the profile "Stream" either displaying all public posts (from spaces) or disabling it all together.

This is the kind of the complimentary feature to #264

**Comment by buddh4** [comment]
Can be disabled by user module setting.

**Comment by Blavkm** [comment]
> Can be disabled by user module configuration.

Can you point me how can I do this, or what module I have to mod for hide follow button and if is possible to hide followers and following list from user profiles?.
 Thanks in advice.

**Comment by buddh4** [comment]
In your `/protected/config/common.php`:

```php
return [
    'modules' => [
        'user' => [
            'disableFollow' => true
        ],
	'space' => [
            'disableFollow' => true
        ]
    ]
]
```
