### ISSUE TITLE
Check INTL/ICU Version 

### ISSUE THREAD

**Issue by badis** [humhub/humhub#1448]
When i have migrated a humhub installation from My first hosting provider  to Hostgator i get the following message  for every instance of gridview : 

Showing {begin, number}-{end, number} of {totalCount, number} {totalCount, plural, one{item} other{items}}

Is this related to a php extension ?

**Comment by luke-** [comment]
Hmm, very strange - does this problem only appears on GridViews?

**Comment by badis** [comment]
Well , i think @samdark has right on this : https://github.com/yiisoft/yii2/issues/10706 . PHP Intl extension version in my new server is 3.6 . where as in previous server is 4.2.1. i have asked the support team of the hosting provider to upgrade it. if that doesn't fix the issue i will further investigate and provide more infos . Thanks !
