### ISSUE TITLE
Add event sender parameter on widget EVENT_CREATE event.

### ISSUE THREAD

**Issue by rifaideen** [humhub/humhub#1449]
Hi, Add the sender parameter on widget EVENT_CREATE event so that the modules can interact directly with the event sender.

**typical use cases:**
i.e In Dashboard we have post form. We can override the `submitUrl` or we even we can change the view template.

**Comment by luke-** [comment]
EVENT_CREATE is used before before the widget is instanciated - for use cases like replace the widget class or parameters.

Maybe we should add another event EVENT_BEFORE_RUN?

**Comment by rifaideen** [comment]
Yes we can. Also one more suggestion If we added the same then we should introduce a variable maybe we can name it as `$view` to hold the widget view name and then alter the existing widgets to follow this. so that we can change the widget views too.

**Comment by luke-** [comment]
Hmm, not sure about this. To change the entire view of a widget you can do this already by following ways:

- Using the EVENT_CREATE, replace the entire widget by own widget (class could inherits the original) and overwrite 'run' method there. 
- Theming

If we introduce a 'viewFile' attribute, we need to modifiy all existing core widgets. 

Do you want to add the EVENT_BEFORE_RUN?

**Comment by rifaideen** [comment]
Can you explain me a bit about how to change entire widget by own widget on
EVENT_CREATE event. I don't wanna do it by theme the these changes are
module specific.

**Comment by luke-** [comment]
Example how to replace the Widget Class by EVENT_CREATE.

```php
    public static function onWidgetCreate($event)
    {
        // Change Class
        $event->config['class'] = widgets\MyWidget::className();
    }
```

**Comment by rifaideen** [comment]
wow. but anyways we need EVENT_BEFORE_RUN with sender parameter.
 Also I have seen that few of our widgets are not extend from
humhub\components\Widget on those widgets can't have EVENT_CREATE and
EVENT_AFTER_RUN events so extend them from humhub\components\Widget


Thanks & Regards
*- Rifaudeen*

**Comment by rifaideen** [comment]
wow. but anyways we need EVENT_BEFORE_RUN with sender parameter.
 Also I have seen that few of our widgets are not extend from
**humhub\components\Widget** on those widgets can't have **EVENT_CREATE** and
**EVENT_AFTER_RUN** events so extend them from **humhub\components\Widget**

**Comment by luke-** [comment]
Ok, we should also extend all widgets from **humhub\components\Widget**

Do you want to contribute this?

**Comment by rifaideen** [comment]
Yes. what about adding before run event?
