### ISSUE TITLE
Use LDAP attribute jpegPhoto for profile photo

### ISSUE THREAD

**Issue by bjoernh** [humhub/humhub#145]
Is it possible to fetch the profile Photo from the LDAP Directory?
For example OwnCloud do it this way.
Greetings

**Comment by Basster** [comment]
Check my (pretty simple) module https://github.com/Basster/humhub-ldap-thumbnail-module, which pulls "thumbnailphoto" from LDAP as profile photo.
Feel free to contribute!

**Comment by luke-** [comment]
Cool! Can we add this to the marketplace?

**Comment by Basster** [comment]
Sure,you can.I've just added an admin interface and refactored a bit.

**Comment by robcarey** [comment]
Is there any instructions on how to use or install this module?  Fumbling in the dark a bit here :)

**Comment by luke-** [comment]
This is also available on the Enterprise Edition module: http://docs.humhub.org/ee-ldap.html#profile-images
