### ISSUE TITLE
Using Japanese Characters in Name

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#1455]
This is the end resalt of using Japanese in the first & last name fields. So I'm guessing that this will also happen when using other languages such as Chinese as well.
![](http://i.imgur.com/EGEGCRZ.png)

**Comment by luke-** [comment]
Make sure your database & tables are created using UTF8.

https://www.humhub.org/docs/guide-admin-installation.html#1-preparation

**Comment by Felli** [comment]
This would be by default on my server, but when dealing with Humhub's installation it changes the fields to latin1_swedish_ci for some reason... I'll have to check more into this when I can.
![screenshot_6](https://cloud.githubusercontent.com/assets/2011633/12739706/f8113478-c920-11e5-879a-d8e5d06a78ed.png)

**Comment by dakur** [comment]
#677 is about this and still not fixed. :-\

**Comment by luke-** [comment]
If the database is initially created as UTF-8 there should be no problem.
(as described here: https://www.humhub.org/docs/guide-admin-installation.html#1-preparation)

Afterwards you need to manually change all tables or fields to UTF-8 - if db was not created using UTF-8.

@dakur not sure what to fix?

**Comment by dakur** [comment]
@luke- In my opinion HumHub should check correct collation before starting installation and abort it or at least show a warning.

**Comment by Felli** [comment]
@luke-  Hmm manually changing the tables does fix this, but the problem is that for some weird reason Humhub is setting the Collations to ```latin1_swedish_ci``` by default... Even if I have the default set to ```utf8_general_ci```, any idea on what is causing this problem?
## TO NOTE:
Using the follow in MySQL>your_database>SQL (Replace tbl_name with the database table name)
```ALTER TABLE tbl_name CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;```
Using this will change the database default Collation.
```ALTER DATABASE your_database CHARACTER SET utf8 COLLATE utf8_general_ci;```

**Comment by luke-** [comment]
@Felli you also need to change the Collation on field level.

HumHub should use the collation of the database when creating table or fields.
