### ISSUE TITLE
Birthday Date is saved off by one.

### ISSUE THREAD

**Issue by Ardnived** [humhub/humhub#1458]
Whenever I or any other use on our site saves their birthday, the date gets reduces by 1 day.

For example:
7/4/92 becomes 7/3/92
7/1/92 becomes 6/30/92

We are using Humhub 1.0.0-beta.3

**Comment by luke-** [comment]
Can you please check timezone settings at:

Administration -> Basic -> Timezone

**Comment by Ardnived** [comment]
Our timezone is set to 
> UTC+01:00 - Europe/Malta

This error has been reported by people in UTC+0, and verified by myself at UTC-8

This is to correspond to our server location, because with other timezones everyone was seeing the dates all over the site as wrong.

Surely though the birthday date should be set independent of timezone.

**Comment by luke-** [comment]
So anything works with correct timezone?

I know, we need to switch the database field to date only.

**Comment by Ardnived** [comment]
Other dates are all fine, but the issue with the birthday remains.

**Comment by luke-** [comment]
Can you reproduce that on our hosting or community with same timezone & locale/language?

**Comment by Ardnived** [comment]
Yes, the error occurs on your hosting.

The key settings for me that produced it seem to be having the server timezone at UTC+1 and my account timezone at UTC-8.

Appears to be a timezone issue, in which case this error might only occur when it is a different current date in those two timezones (meaning after 3pm UTC-8)
