### ISSUE TITLE
SQLSTATE[08004] [1040] Too many connections

### ISSUE THREAD

**Issue by gsivaprabu** [humhub/humhub#1462]
In my website i have this error in loading time, kindly note the screen shoot

# **Database Exception – yii\db\Exception**

**SQLSTATE[08004] [1040] Too many connections**

![podexception](https://cloud.githubusercontent.com/assets/2444608/12839002/5b860700-cbfa-11e5-9e03-ed45b5fae81c.png)

**Comment by makhnovskiy** [comment]
Check out this document: http://dev.mysql.com/doc/refman/5.7/en/too-many-connections.html 

THere may be a way to increase the connection amount, or look and see what PHP is doing that is keeping the connections open. Or some rogue/active app is utilizing all connections.

**Comment by gsivaprabu** [comment]
Oh ! ok thanks, @makhnovskiy
