### ISSUE TITLE
issue when we uninstall humhub updater the website shows internal server error please check this out

### ISSUE THREAD

**Issue by saurabhchris1** [humhub/humhub#1463]

**Comment by saurabhchris1** [comment]
to see this issue in humhub 0.20.1 
install humhub updater then enable then disable then uninstall ......then it shows " opps ......"
and then whole website shows internal server error

**Comment by Felli** [comment]
Here's a quick fix for this, go into your database and then go to module_enabled and removed "updater" from your database, this should fix this till you've updated your Humhub to a new version.

**Comment by saurabhchris1** [comment]
this is not working ......still it shows the same

**Comment by luke-** [comment]
Can you provide an error message regarding the internal server error?

**Comment by Penguinexpert1** [comment]
Are you with Hostgator by any chance? This seems to be a problem I had - Hostgator being as they are with these things... useless, don't help much - But the latest BETA version has fixed this :)
