### ISSUE TITLE
add module album?

### ISSUE THREAD

**Issue by Themaster07** [humhub/humhub#1469]
be perfect with this unit , we have for the future this module

**Comment by Felli** [comment]
There is already a albums module it's just not updated to yii2 FYI. :wink:

**Comment by rifaideen** [comment]
It's updated as new repository.  github.com/rifaideen/album

**Comment by Felli** [comment]
@rifaideen Sadly it's still in development and doesn't work, all it does is throw off internal server errors. Tho I do hope to see this module in working order soon. :+1:

**Comment by rifaideen** [comment]
Can you try another branch.


Thanks & Regards
*- Rifaudeen*

**Comment by Felli** [comment]
I tried both available branches, both give the same internal server errors.

**Comment by Censtudios** [comment]
Status: Under Development

So obviously it won't work yet, unfortunately.
