### ISSUE TITLE
how to use database migration tool?

### ISSUE THREAD

**Issue by saurabhchris1** [humhub/humhub#1470]
cd protected
php yii migrate/up --includeModuleMigrations=1 

how to use this?

**Comment by dakur** [comment]
What do you mean? Just run it on command line.

**Comment by mkreska** [comment]
I have the same problem. How can I run this command when I‘m on an shared webserver without command line access?

**Comment by Felli** [comment]
You require SSH access to use command lines at this time, the module that I've been working on isn't ready for production use as of yet.

**Comment by mkreska** [comment]
Ahh ok, thanks. At the moment I can‘t update automatically from 1.2.2 to 1.2.3 because the process is running in a timeout 😞. What’s your recommendation how to update when there is no command line access and auto updates fail?

**Comment by Felli** [comment]
You should be able to update by uploading the new files and starting the installer as long as you use the same database, although you should then also have to use the command lines which would, of course, be highly recommended. :thinking:

**Comment by mkreska** [comment]
Hmm, maybe it would work when I install a backup on my local machine with xamp, update local and upload HumHub to my production site.

**Comment by buddh4** [comment]
Migrations are also executed when entering "Administration -> Information -> Database"
