### ISSUE TITLE
space_id column in comment table ?

### ISSUE THREAD

**Issue by ali-abdalla** [humhub/humhub#1471]
I don't know why the column `space_id` in **comment** table is always null in database ? even when the comment created on post that exists on space.
![screen shot 2016-02-09 at 1 48 25 pm](https://cloud.githubusercontent.com/assets/14368377/12915439/eca87ff6-cf33-11e5-9ab5-c59da403a239.png)

**Comment by luke-** [comment]
Hmm, need to investigate - but it seems to be a deprecated column

**Comment by buddha87** [comment]
https://github.com/humhub/humhub/commit/42d8b99379e9f7effe8d2d3aca518c5eece07f4f
