### ISSUE TITLE
"File not Found Exception" - 0 Byte Image

### ISSUE THREAD

**Issue by wOOx92** [humhub/humhub#1475]
Hello,

while the most users of my HumHub instance can upload images without any problems, some are having big trouble upload images. The uploaded images are showing up as "0 Byte" (?) and no thumbnail is created. Im running HumHub Version: 1.0.0-beta.3.

Heres what the Admin-Log says:
`exception 'yii\web\HttpException' with message 'Konnte Datei nicht finden!' in /var/www/html/protected/humhub/modules/file/controllers/FileController.php:154 Stack trace: #0 [internal function]: humhub\modules\file\controllers\FileController->actionDownload() #1 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #2 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array) #3 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('download', Array) #4 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('file/file/downl...', Array) #5 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /var/www/html/index.php(25): yii\base\Application->run() #7 {main} `

So far, I found out, that it's not a problem of the specific useraccount. When I log into the account having trouble uploading images, I can upload images without any problems.

The issue occours with several devices/browsers, e.g. Android/Chrome, iPhone 6/Safari. At this point, Does anyone have a clue, what the problem is? :(
Thank you!

**Comment by wOOx92** [comment]
Sorry, issue can be closed, it's the same as https://github.com/humhub/humhub/issues/975

**Comment by luke-** [comment]
Thanks!
