### ISSUE TITLE
My Cron Jobs have stopped working after upgrade to v.20

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub#1476]
$_GET = [ 'r' => 'notification/list/index' 'from' => '0' 'ajax' => '1' ] $_COOKIE = [ 'CSRF_TOKEN' => '9eae1b622a1f09a8adee87826b6888683d980b62' 'pm_space-info-panel' => 'expanded' 'pm_space-members-panel' => 'expanded' 'pm_mostactiveusers-panel' => 'expanded' 'sin' => '0497d69f233a3e72c7244b46d8aa1c67' '_csrf' => '057c3035c5aaabed280ac29c058adb1311838aad1b0abce56875db3407e5ec08a:2:{i:0;s:5:\"_csrf\";i:1;s:32:\"opPAobomb_GTBylbOh9nYk4r3YQTiy1w\";}' 'pm_new-people-panel' => 'expanded' 'pm_user-statistics-panel' => 'expanded' '__utma' => '31464765.390842493.1452513482.1453678912.1453941319.4' '__utmc' => '31464765' '__utmz' => '31464765.1452513482.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' 'pm_user-spaces-panel' => 'expanded' 'pm_profile-follower-panel' => 'expanded' 'pm_profile-following-panel' => 'expanded' 'pm_getting-started-panel' => 'expanded' 'PHPSESSID' => 'hloorq67hqe6tvgob46ib317b6' '_identity' => '8793958abe5ec2fe3e71142485e82f204ae40e1cc402575cf5240a2617bddf1ca:2:{i:0;s:9:\"_identity\";i:1;s:50:\"[1,\"b36a4c12-e903-4631-8c79-55426b162162\",2592000]\";}' ] $_SESSION = [ '__flash' => [] '__returnUrl' => '/index.php' '__id' => 1 ] $_SERVER = [ 'PATH' => '/sbin:/usr/sbin:/bin:/usr/bin' 'PWD' => '/usr/local/cpanel/cgi-sys' 'SHLVL' => '0' 'PHP_FCGI_MAX_REQUESTS' => '5000' 'SCRIPT_NAME' => '/index.php' 'REQUEST_URI' => '/index.php?r=notification%2Flist%2Findex&from=0&ajax=1' 'QUERY_STRING' => 'r=notification%2Flist%2Findex&from=0&ajax=1' 'REQUEST_METHOD' => 'GET' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'REMOTE_PORT' => '64613' 'SCRIPT_FILENAME' => '/home/bvke2bbg/public_html/projects/index.php' 'SERVER_ADMIN' => 'webmaster@projects.rapidpage.ca' 'CONTEXT_DOCUMENT_ROOT' => '/home/bvke2bbg/public_html/projects' 'CONTEXT_PREFIX' => '' 'REQUEST_SCHEME' => 'http' 'DOCUMENT_ROOT' => '/home/bvke2bbg/public_html/projects' 'REMOTE_ADDR' => '216.240.7.170' 'SERVER_PORT' => '80' 'SERVER_ADDR' => '166.62.70.161' 'SERVER_NAME' => 'projects.rapidpage.ca' 'SERVER_SOFTWARE' => 'Apache/2.4.12' 'SERVER_SIGNATURE' => '' 'LD_LIBRARY_PATH' => '/usr/local/apache/lib' 'HTTP_COOKIE' => 'CSRF_TOKEN=9eae1b622a1f09a8adee87826b6888683d980b62; pm_space-info-panel=expanded; pm_space-members-panel=expanded; pm_mostactiveusers-panel=expanded; sin=0497d69f233a3e72c7244b46d8aa1c67; _csrf=057c3035c5aaabed280ac29c058adb1311838aad1b0abce56875db3407e5ec08a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22opPAobomb_GTBylbOh9nYk4r3YQTiy1w%22%3B%7D; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; __utma=31464765.390842493.1452513482.1453678912.1453941319.4; __utmc=31464765; __utmz=31464765.1452513482.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); pm_user-spaces-panel=expanded; pm_profile-follower-panel=expanded; pm_profile-following-panel=expanded; pm_getting-started-panel=expanded; PHPSESSID=hloorq67hqe6tvgob46ib317b6; _identity=8793958abe5ec2fe3e71142485e82f204ae40e1cc402575cf5240a2617bddf1ca%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22b36a4c12-e903-4631-8c79-55426b162162%22%2C2592000%5D%22%3B%7D' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_REFERER' => 'http://projects.rapidpage.ca/index.php?r=admin%2Fsetting%2Fcronjob' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_X_CSRF_TOKEN' => 'WV8weldRclk2L2A7ODMdNDsAdy4VKB47FjcJFA46RitqBmEuPihDLg==' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_CONNECTION' => 'close' 'HTTP_HOST' => 'projects.rapidpage.ca' 'UNIQUE_ID' => 'VsChEjI@sUcAAGZ3ZckAAAJT' 'FCGI_ROLE' => 'RESPONDER' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1455464722.1041 'REQUEST_TIME' => 1455464722 ]

**Comment by rapidpage** [comment]
Here is the error after i setup the new cron:
exception 'yii\base\InvalidConfigException' with message 'Unable to determine the entry script file path.' in /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/base/Request.php:62 Stack trace: #0 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/base/Component.php(130): yii\base\Request->getScriptFile() #1 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(421): yii\base\Component->__get('scriptFile') #2 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(241): yii\console\controllers\HelpController->getScriptName() #3 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp() #4 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL) #5 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #6 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array) #7 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array) #8 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array) #9 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('', Array) #10 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('', Array) #11 /home/bvke2bbg/public_html/projects/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request)) #12 /home/bvke2bbg/public_html/projects/protected/yii(28): yii\base\Application->run() #13 {main}

**Comment by luke-** [comment]
Which command do you using?

**Comment by rapidpage** [comment]
I am using 
30 * * * * /home/bvke2bbg/public_html/projects/protected/yii cron/hourly >/dev/null 2>&1
00 18 * * * /home/bvke2bbg/public_html/projects/protected/yii cron/daily >/dev/null 2>&1

**Comment by rapidpage** [comment]
Currently installed version: 1.0.0-beta.3

**Comment by Felli** [comment]
When it came to the Cron Jobs I had to set it up like this, as this is how my server is setup to take cron jobs.
Linux
```30	 * * * * /usr/local/bin/php /home/USER/public_html/district/protected/yii cron/hourly >/dev/null 2>&1```
```00	18 * * * /usr/local/bin/php /home/USER/public_html/district/protected/yii cron/daily >/dev/null 2>&1```
You should ask your server provider how they've setup their system.

**Comment by rapidpage** [comment]
thanks will try tonight, thanks for the help

**Comment by rapidpage** [comment]
I have put in your code, will provide feedback, and thanks!

**Comment by Felli** [comment]
@rapidpage No problem, I hope it works, if not you should check with your provider, as every server is different in it's own way. :smile:

**Comment by rapidpage** [comment]
cool, and i do appreciate your help!

**Comment by rapidpage** [comment]
I have setup a new site, testing your version of the cron and will let you know, thanks again

**Comment by rapidpage** [comment]
The cron jobs are working perfectly on new install, new server using:
/usr/local/bin/php infront of script
Thanks for everyone's help, i greatly appreciate it!
