### ISSUE TITLE
Chosen space visibility is ignored when creating new space

### ISSUE THREAD

**Issue by dakur** [humhub/humhub#1478]
When I create new space and I choose "visibility" in advanced settings, the space visibility is always set to private after submit. The "join policy" works fine.
Current version, branches master & v1.1-dev

**Comment by luke-** [comment]
Hmm, cannot reproduce that on current master....

**Comment by dakur** [comment]
You're right, I was checking my fork insteadof humhub/humhub, grr. Sorry.
