### ISSUE TITLE
Notifications at top have stopped working 

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub#1480]
Hi, i recently upgraded to the latest version and the notifications at the top have stopped working...

**Comment by luke-** [comment]
From which version?

To beta.3 or git master?

**Comment by rapidpage** [comment]
Currently installed version: 1.0.0-beta.3

**Comment by makhnovskiy** [comment]
Seems to be working fine for me in beta.3. Might be your install/update @rapidpage. Try setting a new install on another instance to see if it any modifications, settings may be the case.

**Comment by rapidpage** [comment]
I will setup a test server and see what happens, thanks for the input!  I will get back to you ASAP

**Comment by rapidpage** [comment]
i did setup a completely new install and the notifications are back, now i have the problem with how to fix the original installation / upgrade

**Comment by makhnovskiy** [comment]
Did you have any custom code on the original install? I would check there first.

There is also a logging functionality in "Administration" -> "Logging", that might give you some clues. 

Perhaps this may assist: https://github.com/humhub/humhub/issues/1326

**Comment by rapidpage** [comment]
No custom code, i did try your #1326 and the command did fix a lot of errors, but no change on the notifications, however, if i do a complete new install the notifications do properly display.  Is there anyway to do a new install and port over all of the conversations/users/spaces?

**Comment by Felli** [comment]
@rapidpage Use the same database that you were using before hand. :smile:

**Comment by rapidpage** [comment]
Hi, i tried that and notifications stop working...

**Comment by Felli** [comment]
Have you tried migrating your database tables from the new one to the old one?

**Comment by rapidpage** [comment]
No, that is very interesting, how would i do that and not loose the data?  I have about 18 months of history in the old (not working site) and do not want to loose that, but if i have to i definitely am ok with that

**Comment by makhnovskiy** [comment]
Create a dump of the db as backup. I dont think you will have to lose your data.

**Comment by rapidpage** [comment]
I think that when i updated from .10 i messed it up, i think that it is best that i start again, its sad to loose history, but the time spent to fix this is just too much, i so much appreciate your help though!

**Comment by makhnovskiy** [comment]
Don't do it. 18 months is too much!

**Comment by rapidpage** [comment]
thanks, did it anyways, new version is so much better, now getting silly errors after last update (oh boy)
