### ISSUE TITLE
Bulk Send SMS - not an issue

### ISSUE THREAD

**Issue by makhnovskiy** [humhub/humhub#1481]
I have hired someone to write a bulk sms utility in the admin panel to send out bulk emails to user groups. It is working perfectly utilizing the sms plugin, but has additional page. I can send the code over and you can add to a build or package as part of the sms plugin. Either way let me know, and I could assist. 

<img width="1169" alt="screen shot 2016-02-16 at 10 44 47 pm" src="https://cloud.githubusercontent.com/assets/3479205/13101925/23b7b144-d4ff-11e5-846a-ef224b05a9a9.png">
<img width="619" alt="screen shot 2016-02-16 at 10 44 55 pm" src="https://cloud.githubusercontent.com/assets/3479205/13101924/23b5c910-d4ff-11e5-97c3-f74c261495ca.png">

**Comment by luke-** [comment]
Awesome, can you create a PR to the SMS Module Repository?

https://github.com/humhub/humhub-modules-sms

**Comment by luke-** [comment]
You can also send us the code to info@humhub.com if you want to contribute.
