### ISSUE TITLE
Which port does Humhub run on?

### ISSUE THREAD

**Issue by thinhduckhoi** [humhub/humhub#1482]
So i followd the tutorial installing Humhub and run it with Docker.
`https://hub.docker.com/r/cboulanger/humhub-docker/`
I created dockerfile and build it as following the above-mention tutorial.
The point is i don't know which port is Humhub running on, when accessing the IP of server, the apache success page appeared and that's it.
How should i do now?

**Comment by luke-** [comment]
Depends on your webserver, usually port 80 or 443
