### ISSUE TITLE
How to use imagick ?

### ISSUE THREAD

**Issue by KaiserCoder** [humhub/humhub#1484]
Hi !
I would like to use Imagick on my server instead of GD. Is it possible ? If yes, how ?
Thanks !

**Comment by luke-** [comment]
Administration -> Files

**Comment by KaiserCoder** [comment]
Yeah but, what do I put in the command line field ? I dont even know the filenames :/

**Comment by Felli** [comment]
You can find command lines [here](http://www.imagemagick.org/script/command-line-processing.php).

**Comment by WebCrew** [comment]
Note at some hosting providers You need exec() to run imagemagic and thats a huge security risk so think twice about to using it at a social network script. GD is saver and ok to use with HumHub.

**Comment by victorpdiez** [comment]
on libux you put /usr/bin/convert (or the path to Imagik)
on windos C:\Program Files (x86)\Imagik-***-*-*\convert.exe
