### ISSUE TITLE
XSS vuln

### ISSUE THREAD

**Issue by KaiserCoder** [humhub/humhub#1487]
Hello,
I found an XSS vuln in the directory module.
www.yourhumhub.com/directory/members?keyword=1%27%3CScRiPt%20%3Ealert%28document.cookie%29%3C/ScRiPt%3E&page=3&per-page=10
Just use HtmlPurifier and change first line of actionMembers method of the DirectoryController:
$keyword = HtmlPurifier::process(Yii::$app->request->get('keyword', ""));

**Comment by luke-** [comment]
Please contact us directly via info@humhub.com
