### ISSUE TITLE
How to deploy? Parse error: syntax error, unexpected '[' in /..../index.php on line 20

### ISSUE THREAD

**Issue by DanDvoracek** [humhub/humhub#1488]
I tried to find some informations about how to deploy this great tool, but I can't find anything. 

After downloading the zip, I have no problem to run in locally, however once I upload my files to the server (shared hosting), I get the following error, and I'm pretty unsure about what it means, what to do with it.. Any tip? 

Parse error: syntax error, unexpected '[' in /... /index.php on line 20

I tried to look if some config needs to be set up, but don't find much about it on the web. Also I was expecting the installer to show up really..so dunno what I am doing wrong here. Would that be a dependency problem?

Many thanks

**Comment by luke-** [comment]
Your server seems to run PHP 5.3 or lower.

https://www.humhub.org/docs/guide-admin-requirements.html
