### ISSUE TITLE
Installation error, InvalidParamException: Syntax error

### ISSUE THREAD

**Issue by Lysande** [humhub/humhub#1493]
Attempting to install humhub locally. I'm running:

PHP 7.0.2
Apache 2.4.16
MySQL 5.7.10

via EasyPHP DevServer 16.1

On Windows 10 64, easydev installed as 32-bit. 

I've gotten past the databse setup. When asked to enter a name for my social network and proceed, I run into an exception: Invalid Parameter – yii\base\InvalidParamException Syntax error.

Stack trace submitted as an attached file, with my server variables at the bottom. First two traces as an image, as well. 

Any help is appreciated. 
[stacktrace.txt](https://github.com/humhub/humhub/files/143099/stacktrace.txt)

![capture](https://cloud.githubusercontent.com/assets/3249676/13261046/9600ccf4-da5e-11e5-923a-aaec3bf6c584.JPG)

**Comment by luke-** [comment]
Which HumHub version do you use?

**Comment by Lysande** [comment]
Right, sorry, forgot that. My downloaded file says 0.20.1. Latest version as of three weeks today when I downloaded it.

**Comment by Lysande** [comment]
I switched environments from EasyPHP, installed in C:\Program Files (x86)\ to wamp64 installed in C:\., which resolved the errors and let me install things smoothly. 

Not sure whether it was a problem with the environment or with the file location. 

All relevant files, as per the installation instructions, were set as readable, writable and modifyable by every process available.
