### ISSUE TITLE
[suggestion] Login with Facebook/Twitter/etc

### ISSUE THREAD

**Issue by Censtudios** [humhub/humhub#1507]
It would be nice for a lot of communities I think to be able to create accounts and login using an existing social account. By connecting their facebook account to humhub at signup future members don't have to go through the whole signup process and can easily create an account.

I don't know how easy/difficult it would be to make something like this for Humhub

**Comment by luke-** [comment]
Will come with 1.1

https://github.com/humhub/humhub/blob/v1.1-dev/protected/humhub/docs/guide/admin-adv-auth.md
