### ISSUE TITLE
make editor like bbcode editor

### ISSUE THREAD

**Issue by blackwin10** [humhub/humhub#1511]
hi
how can i make editor support images like bbcode

`example: [img]http://example.com/images.jpg[/img]`

i don't want to be bbcode, i just want to support images

**Comment by Felli** [comment]
The editor that's being used is markdown so you'll need to use ```![](image link here)```

**Comment by blackwin10** [comment]
can you explain more ?

**Comment by Felli** [comment]
@blackwin10 @Humhub uses Markdown in it's editors (In posts Humhub uses an upload option) this is how you uses Markdown. It's just like here on GitHub. Tho I prefer [John Gruber's Markdown Syntax](https://daringfireball.net/projects/markdown/syntax) documentaion over GitHub's.
### Code Example
The image must end with an image file type then follow by using --> ```![](Place the link to the image here)```

**Comment by blackwin10** [comment]
where can i add that code ?

**Comment by blackwin10** [comment]
@Felli

**Comment by Felli** [comment]
You upload it to the post, next to the submit button is an upload option.

**Comment by blackwin10** [comment]
you really didn't get me
![i want it like this](http://i.imgur.com/zIz9kox.png)

i want the users add images from external hosts, they just need to put the image

**Comment by blackwin10** [comment]
@Felli 
could you just teach me with short tip the php file that can i edit it

**Comment by Felli** [comment]
You'd have to wait, if I'm not mistaken @Humhub was planning on adding some kinda Markdown into the status update at some point in time, tho I might look into creating a temporary module for this maybe.

**Comment by blackwin10** [comment]
i will be thankful

**Comment by WebCrew** [comment]
You can use this one so far: 
https://community.humhub.com/content/perma?id=52867
