### ISSUE TITLE
Post creator (not humhub admin) don't have permission to delete a comment

### ISSUE THREAD

**Issue by aliabdallahawad** [humhub/humhub#1512]
Here's the steps to produce the issue:
1. Logged in with humhub non-admin account.
2. Create a new post on his profile.
3. Another User created a new comment on this post **(spam comment)**.
4. The post creator don't have permission to delete the comment although he is the post creator.

**Comment by Felli** [comment]
This I don't actually feel needs to be implemented into the core to be honest... Of course the report content could be extended (If not already extended) to make it possible to report & hide the reported comment till it is reviewed by a staff member.

**Comment by ali-abdalla** [comment]
@Felli Report/hide comments happen with this case:
1- User_1 creates new post
2- User_2 create a comment in User_1 post
3- User_3 see that User_2's comment is abuse, then he may has the option to hide and report it if he want.

---

but in my case, the post creator should have the right or access to delete on of his post's comments. check [Facebook](www.facebook.com) security in this case for an example.

**Comment by luke-** [comment]
Maybe we can add this optionally?

Add an attribute (contentOwnerCanDeleteComment) to the comment module (e.g. like that https://github.com/humhub/humhub/blob/master/protected/humhub/modules/comment/Module.php#L19)

These attributes can be changed by configuration.

Default should be false.
