### ISSUE TITLE
Error when going into 'Administration': IntlException Constructor failed'

### ISSUE THREAD

**Issue by Disreality** [humhub/humhub#1514]
Hey buds.
I just installed the 1.0.0-beta4 version on my website (brand new), and so far everything seems to be working. Apart from going into the admin settings.
When I press the button, it just says 'IntlException Constructor failed" and some code.

Since there were too many things to copy-and-paste, I've saved the page as a .webarchive.
http://syphonshared.weebly.com/uploads/5/9/1/9/59194125/intlexception.webarchive

Any help?
Thank you!
~ Syphon

UPDATE: Seems like the same error shows when pressing the search icon, too.
2nd UPDATE: I have used the tutorial to get to the admin settings. It seems like I can go anywhere but in the Basic area.

**Comment by Felli** [comment]
Hmm... Few questions, as I'm not having problems with installing nor updating Humhub.
What PHP version are you using?
Can you provide a way of reproducing these error?
Are you using any/have any modules/themes that aren't updated to yii2/latest version of Humhub?
Are you using any custom themes/modules that could be causing problems? :smiley:

**Comment by DevSyphon** [comment]
1. I'm not actually sure; I'm using Hostinger and it won't allow me to view it unless I pay; and I don't want to do that because it's still a prototype. I'm pretty sure, however, that I do not have composer installed.
2. A way to reproduce? Well, I can say this:
I login into my account.
I press my icon.
I press administration.
Error.

OR

I login into my account.
I press the search icon.
Error.

3. No, it's fresh, brand new. 1.0.0-beta4.
4. Again, nope :p

**Comment by Felli** [comment]
@DevSyphon as far as composer goes, I don't know if there are any free hosting sites that allow composer to be installed, all I can do is tell you that you should download and install manually

Download: [here](https://www.humhub.org/en/download/)
And follow the instructions from: [here](https://www.humhub.org/docs/)

Composer isn't 100% a necessary installer for HumHub.
As for Hostinger from what I remember (I myself use to use their services) they use PHP 5.3, 5.4, 5.5, 5.6, & 7.0 as for checking which version you're using, on their dashboard there should be an icon called "PHP Configuration" normally by default they have 5.4 set, this is one of the supported versions of PHP that HumHub uses, for a more detailed look in PHP Info under the advanced option will show everything that comes with your PHP version. :smiley:
For hosting itself I use x10Hosting which is pretty good in of itself.

**Comment by DevSyphon** [comment]
Maybe there was an error while installing or there's something wrong with Hostinger. I'll try to put HumHub on x10Hosting too, and I'll let you know if it works.

**Comment by WebCrew** [comment]
No its not a error I have the same problems cant enter Admin area, search does not work and image upload also. Its because HumHub 1.0.0.4 needs PHP INTL ICU version 4.8.1 minimum and at hostinger (hosting provider) and also my hostere Alfahosting the ICU vbersion is only 4.4.1 so far. Now we cant use our HumHub anymore and have to downgrade. I`m realy frustrated :(

**Comment by DevSyphon** [comment]
@WebCrew thanks for the reply. It seems really fucking shitty that we have to downgrade just because our hosts do not support newer versions of PHP INTL ICU. Hopefully they will start working on it and stop fucking around with the cPanel colors.

**Comment by Felli** [comment]
You should really try out x10Hosting if this is the case, as from what I can tell they fully support everything needed to run a Humhub website. :+1:

**Comment by WebCrew** [comment]
I`m at Alfahosting (the best known Hoster in Germany and its payd hosting) and all was fine until the latest HumHub update. My problem is, that my hoster update such scripts like PHP INTL only every quartal (all three month), now I have to wait and this sucks lol

**Comment by MaximStone** [comment]
I just wonder How to install PHP INTL ICU version 4.8.1 or higher? Is there anybody who installed it successfully and fix this bug? 

CentOS
php70w-intl.x86_64

Thank you

**Comment by MaximStone** [comment]
Ok, we've installed last centOS, and all extensions. All requirements are checked. And i have the same issue. Who knows what's wrong?

**Comment by MaximStone** [comment]
Ok i got it. It's because of localization. If i have russian language interface it's falling. If I will switch to eng then Ok.

**Comment by samdark** [comment]
@MaximStone any details on how to reproduce it?

**Comment by F3nom** [comment]
Hi, i have iis 8, php 7.04     HumHub 1.0.0 -  i get error when i trying to access admin panel with Russian language, if i switch to English or any other all going ok.
