### ISSUE TITLE
LDAP login issues

### ISSUE THREAD

**Issue by chaoticreality** [humhub/humhub#1516]
As with ticket #1427, I am having issues logging in via LDAP to a git/composer based HumHub install, updated today to the latest revision of master branch.

This is a different issue to the one rectified in commit [11aa2de](https://github.com/humhub/humhub/commit/11aa2de44b0fef08e7ada2e2f78b1b78c9065b84).

Splitting the if statement on line 53 of /protected/humhub/modules/user/models/forms/AccountLogin.php into individual statements and putting an error message on each shows that the code is failing on the Ldap::getInstance()->authenticate($user->username, $this->password) clause despite passing in the correct username and password.

This points to a problem in the Zend LDAP module and that's where I start to get totally out of my depth. Are there any more debug tests I can run?

**Comment by chaoticreality** [comment]
Could it be something to do with the fact that I'm using sha512 for password storage in my LDAP server? I am using OpenLDAP's slapd version 2.4.40

**Comment by luke-** [comment]
Hmm - in Beta.3 login worked?
Password Storage on LDAP server should be no problem.

**Comment by chaoticreality** [comment]
No, it didn't work in beta3 and searching for a resolution, I found the other ticket and so upgraded to beta4, assuming I was having the same issue as the one that had been resolved.

**Comment by luke-** [comment]
We have successfully some OpenLDAP (slapd) installations running on Beta.3/4

**Comment by chaoticreality** [comment]
The other interactions with slapd are working fine, when I try and login, the user is pulled from LDAP and appears in the users page on the site administration panel, and any updates in LDAP (change of name etc) to those users come across ok, so HumHub is obviously able to communicate back and forth alright with slapd. 

The issue is when trying to login for an LDAP based user it is just returning "invalid user/pass" although the credentials work fine when trying to authenticate via OpenLDAP CLI tools.

I'm assuming that there's an exception occuring in the [LDAP library authentication routine](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/libs/Ldap.php#L98) but with this just being caught and returning false to the [calling routine](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/forms/AccountLogin.php#L46), the invalid user/pass message is triggered even though this is probably not the issue.

I will try breaking down the LDAP library's authentication routine and adding some debug messages in there to see if I can work out what is going on.

**Comment by luke-** [comment]
I'm not so familiar with LDAP, maybe you'll require some DOMAIN\Username syntax?

Do you using any other software which uses ldap auth to this server?

**Comment by chaoticreality** [comment]
I don't think the DOMAIN\Username syntax is needed because the Ldap library [gets the canonicalised name](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/libs/Ldap.php#L101) before trying to authenticate and this same functionality is clearly working ok when initially trying to [find the user account to import](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/forms/AccountLogin.php#L106) in the model/form.

I am not currently using any other software that authenticates against the same LDAP server but will be doing so in the future (the reason for wanting to use LDAP with HumHub) but I have tested the credentials via command-line LDAP client and they are working ok.

I will do some debugging of the ldap library and see if I can track down the cause of the problem.

**Comment by evolun** [comment]
I don't know if this can be useful but I got this problem when I started to utilize HumHub on version 0.10, the trouble for me was in `getNode `from `getCanonicalAccountName` by Zend Ldap class in `authenticate` method.
All was well loading all users in db, and the way in which the nodes are handled is different in `refreshUsers` method, I'm not so expert in Zend LDAP and Yii framework, so initially I worked around copying this way, making a LDAP search (of the single logging user) in `authenticate` method and handling the item returned from the search.

Then I solved definitively paying attention to the case sensitivity of the DN, that is, I checked with a LDAP explorer the exact DN returned from LDAP and I noticed that was the same that I configured in HumHub admin panel except the uppercase/lowercase difference of some letters, the only difference was this, I copied and pasted the DN and all goes right.

**Comment by chaoticreality** [comment]
Welp, got it working by changing from sha512 to ssha for password storage. Can't work out why it would work from CLI but not from HumHub given the password is passed as plain text to slapd and all encryption/comparison happens server-side but either way, it's now working so happily closing this ticket.
