### ISSUE TITLE
LinkList > Error 500 if user isn't Administrator for the space

### ISSUE THREAD

**Issue by ygrosyeux** [humhub/humhub#1523]
I've a problem with module LinkList.

For a space, users must be Administrators. If not, there is an error 500.

If found this in log file : 
exception 'yii\base\ErrorException' with message 'Call to undefined method Yii::app()' in D:\ProgramData\Apache24Data\htdocs\rse\protected\modules\linklist\views\linklist\index.php:81 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}

Have you encountered this error ? I'm in beta 4

**Comment by buddha87** [comment]
It seems this was overlooked when porting from yii1 to yii2, will be fixed soon.

**Comment by buddha87** [comment]
Should work now with the latest version.
