### ISSUE TITLE
Private Spaces Issues

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#1525]
Just run into this one, it would seem that private spaces aren't so private after you've followed someone within the space itself, of course images don't show, but if you're not in the space, and someone posts in the space, for some weird reason their post shows up in your feed, I don't think this should be happening?

The private options are set to invite only, and private.
### Example

![](http://i.imgur.com/M5eRGaM.png)

**Comment by Felli** [comment]
Would seem that this only happens with one user, and is at random, no known reason behind this tho.

**Comment by Felli** [comment]
Alright so not only is it showing posts from said space, but vice versa as well!

**Comment by xensor** [comment]
mine is private but won't allow me to change it to visible or public. its stuck on private.

**Comment by buddha87** [comment]
Can't reproduce this, what do you mean with "after you've followed someone within the space itself".
Is this still a issue, if yes please explain it a bit more detailed as:

User A member of private space XY
User B not member of spax XY follows A
...

**Comment by buddh4** [comment]
@Felli Can this be closed? Don't know exactly how to reproduce this.

**Comment by Felli** [comment]
The issue can be closed now, as I wasn't able to reproduce this after 1.2beta-1 so I'm guessing this has been fixed without it being known.
