### ISSUE TITLE
Feature Request: Paste an image / a document from the clipboard

### ISSUE THREAD

**Issue by ygrosyeux** [humhub/humhub#1532]
Hi guys,

Is it planned - as what exists in github (when I created this ticket , for example) - you can paste the contents of the clipboard in a post, comment, or the wiki, and if the contents of the stuffing paper is an image or a document, it is uploaded to the server and a link to be added ?

This feature would be great practice !

**Comment by hubrajesh** [comment]
:+1:

**Comment by ygrosyeux** [comment]
Hi,

have you planned this enhancement please ?

Thanks
