### ISSUE TITLE
yii\web\HttpException:404

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub#1535]
Here is the error code:
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "ico/alert.ico".' in /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/base/Module.php:460 Stack trace: #0 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('ico/alert.ico', Array) #1 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #2 /home/hhrpadmin/public_html/index.php(25): yii\base\Application->run() #3 {main} Next exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/web/Application.php:96 Stack trace: #0 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #1 /home/hhrpadmin/public_html/index.php(25): yii\base\Application->run() #2 {main}

**Comment by rapidpage** [comment]
this error that i get it not consistent and have not been able to reduplicate

**Comment by rapidpage** [comment]
I mean not been able to cause it to happen, it mostly seems to happen when other users come on-board

**Comment by buddha87** [comment]
Hi, which humhub version are you using ? Found another ticket with the same error: https://github.com/humhub/humhub/issues/1373 (second comment)

**Comment by rapidpage** [comment]
1.0.0-beta.4

**Comment by rapidpage** [comment]
I just deleted the cache too

**Comment by rapidpage** [comment]
still getting tons of errors related to this issue, any ideas?

**Comment by rapidpage** [comment]
Here is the latest, i have updated to v1.0 and getting the following:
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "ico/alert.ico".' in /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/base/Module.php:460 Stack trace: #0 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('ico/alert.ico', Array) #1 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #2 /home/hhrpadmin/public_html/index.php(25): yii\base\Application->run() #3 {main} Next exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/web/Application.php:96 Stack trace: #0 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #1 /home/hhrpadmin/public_html/index.php(25): yii\base\Application->run() #2 {main}

**Comment by rapidpage** [comment]
closed,

**Comment by velykanov** [comment]
Have you really solved this issue or just ignore it?

**Comment by rapidpage** [comment]
Just ignoring

**Comment by velykanov** [comment]
Thanks
