### ISSUE TITLE
Auto-link URLs without http

### ISSUE THREAD

**Issue by joeworkman** [humhub/humhub#1538]
It would be nice if URLs would be auto linked to even if http:// was not added

**Comment by buddha87** [comment]
Most browsers add http:// automatically I think. Or what do you mean ?

**Comment by joeworkman** [comment]
If I type in apple.com into a comment or post, it could be nice if a link was generated for that.

**Comment by buddha87** [comment]
ah ok, you are right, should be added to the richtext editor.

**Comment by buddh4** [comment]
I think auto recognition for such urls are too error prone since, but the new richtext allows adding this by means of the link menu item.
