### ISSUE TITLE
Consolidate Notifications by thread

### ISSUE THREAD

**Issue by joeworkman** [humhub/humhub#1539]
So I officially launched my community and so far the only complaint was around the notifications. Humhub has a single notification for everything action. Every like and every comment for a thread gets its own notification. These really need to be consolidated on a per thread basis. This is true for both the notifications view on the web and the email summary that gets sent out. 

reference: https://community.humhub.com/s/96d933cd-e5a9-4314-8f8f-564f2dd81cf6/?wallEntryId=52896

**Comment by joeworkman** [comment]
It would also be great to have a setting where like notifications could be turned off.

**Comment by ygrosyeux** [comment]
:+1:

**Comment by programguy** [comment]
Same as #649 (though this is more detailed).

**Comment by buddha87** [comment]
Hi, the revision of the notification system is already planned for future releases and has a high priority for us, just for you info. Thanks for the advice !
