### ISSUE TITLE
Broken images in some email

### ISSUE THREAD

**Issue by joeworkman** [humhub/humhub#1540]
I have noticed broken images inside email for Messages. I looked at the source code for the email and its missing the domain. The img source only contains the path to the image. Thought that I would report this...

![screen shot 2016-03-01 at 9 17 22 pm](https://cloud.githubusercontent.com/assets/225628/13612355/f254853c-e51b-11e5-946a-4600156f3369.jpg)

reference: https://community.humhub.com/content/perma?id=52878

**Comment by luke-** [comment]
This only affects the mail module?

**Comment by nminelle** [comment]
Yes (for me). Precisely it concerns the private messages. Daily digest mails are ok.

**Comment by nminelle** [comment]
Found out.

In the file /protected/modules/mail/views/emails/NewMessageEntry.php, replace line 101:
`src="<?php echo $sender->getProfileImage()->getUrl(); ?>"`
by 
`src="<?php echo $sender->getProfileImage()->getUrl("", true); ?>"`

Same thing in the file /protected/modules/mail/views/emails/NewMessage.php, at line 102. 

Can I commit somewhere?

**Comment by buddha87** [comment]
Just make a pull request to master. Thanks.

**Comment by nminelle** [comment]
Commited, and now merged and deployed in the mail module (#84). Ticket may be closed @luke-
