### ISSUE TITLE
Unable to generate a random key

### ISSUE THREAD

**Issue by designgurudotorg** [humhub/humhub#1544]
I just installed the latest (beta4) version of humhub and keep getting this message every few screens - any idea why?

**Comment by buddha87** [comment]
Could be a Yii2 issue with your environment. Perhaps this will help: https://github.com/yiisoft/yii2/issues/10519

**Comment by designgurudotorg** [comment]
Thanks!  Looks like installing the PHP mcrypt extension did it - was using a Centos install on Digital Ocean.

**Comment by Scowen** [comment]
I resolved this by upgrading PHP to >= 7.1
