### ISSUE TITLE
No visible content to guests.

### ISSUE THREAD

**Issue by Eldarya** [humhub/humhub#1550]
Hi, I would like that the guests could see the contents that are posted on my community as I do?
Screen:
https://i.gyazo.com/c80624680e1340993e11da0de21070d7.png
https://i.gyazo.com/b3fe13ef6e6dc04e8bccd4b70e67acc7.png

Or if you do want to appear only after a determined space how can I do?

**Comment by buddha87** [comment]
Hi, here are the two steps to change the visibility:
1. Administration -> Authentication -> Allow limited access for non-authenticated users (guests)
2. Administration -> Spaces -> Settings -> Set 'Default Visibility' and 'Default Content Visibility' to 'Public'

**Comment by Eldarya** [comment]
Already tried but nothing says: No public viewing content found!

**Comment by buddha87** [comment]
Hmm, perhaps you have to set the posts you make to public by clicking the small gear icon on the bottom right of your post form. There should be an option "Make Public", but this should be set automaticly if you have the "Default Visibility" to public.
