### ISSUE TITLE
BUG: Unable to follow user as of commit 7aee8ab

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1554]
![screen shot 2016-03-11 at 20 21 05](https://cloud.githubusercontent.com/assets/6232455/13719610/47b96f04-e7c6-11e5-9abf-562e31a38db8.png)

Functionality does work at beta4 commit, does not work at 7aee8ab commit.

**Comment by luke-** [comment]
Are you using a custom theme?

**Comment by davidjeddy** [comment]
Issue is now invalid. Was an error in our database data set.
