### ISSUE TITLE
Impossible to set any space as "Default Space Guid"

### ISSUE THREAD

**Issue by sobietev** [humhub/humhub#1555]
Hi,

When I'm trying to set my welcome space as "Default Space Guid", I have a line appearing (see screenshot)
![image](https://cloud.githubusercontent.com/assets/17799118/13725874/b5e57efc-e8af-11e5-8386-164aa74c0f90.png)
It is impossible to select it.

Please help !
Thanks in advance

**Comment by buddha87** [comment]
Hi, could you check what the server is returning in this case (with the developer tools of your browser) ? Which humhub version are you using ?

**Comment by sobietev** [comment]
Sorry, I should have precised : 1.0.0-beta.4
Here is a screenshot of the error returned
![image](https://cloud.githubusercontent.com/assets/17799118/13726072/2e6ef964-e8b7-11e5-8e5a-217d46973851.png)
First line appeared when It detect a space when I type into "Espace par défaut".
second is when I click on the space.
Thanks for your quick answer !

**Comment by buddha87** [comment]
Hmm, could you trace the network XHR calls there should be a call like the following after typing 3 characters:
![spacechooser](https://cloud.githubusercontent.com/assets/9800854/13726170/49afb0ce-e8bc-11e5-916d-dedd7c6e6868.jpg)
