### ISSUE TITLE
Error in "Like"

### ISSUE THREAD

**Issue by torstenpetersen** [humhub/humhub#1561]
Hello, when i click on the "Like" Button, it will not change. I became this Error:

ERROR  Wed, 16 Mar 2016 12:56:27 +0100  yii\web\HttpException:500
exception 'yii\web\HttpException' with message 'Model & ID parameter required!' in /is/htdocs/wp1134194_OAPD7Y75IN/humhum/prod/protected/humhub/modules/content/components/ContentAddonController.php:84 Stack trace: #0 /is/htdocs/wp1134194_OAPD7Y75IN/humhum/prod/protected/vendor/yiisoft/yii2/base/Controller.php(152): humhub\modules\content\components\ContentAddonController->beforeAction(Object(yii\base\InlineAction)) #1 /is/htdocs/wp1134194_OAPD7Y75IN/humhum/prod/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('like', Array) #2 /is/htdocs/wp1134194_OAPD7Y75IN/humhum/prod/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('like/like/like', Array) #3 /is/htdocs/wp1134194_OAPD7Y75IN/humhum/prod/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #4 /is/htdocs/wp1134194_OAPD7Y75IN/humhum/prod/index.php(25): yii\base\Application->run() #5 {main}

**Comment by buddha87** [comment]
Hi, which HumHub version are you using ?

**Comment by torstenpetersen** [comment]
Actualy i use 1.0.0-beta.4 but i have the same problem on 0.20.1

**Comment by buddha87** [comment]
It seems, that the server call is missing some values in your case. Can you check which address is beeing called when pressing like, this can be done through the developer tools of your browser. The address should look like the following:

http://localhost/humhub/index.php?r=like%2Flike%2Flike&contentModel=humhub%5Cmodules%5Cpost%5Cmodels%5CPost&contentId=1

Furthermore which browser and backend environment do you use ?

**Comment by torstenpetersen** [comment]
I use Google Chrome Browser. 

The Link for like is: http://wirinduesseldorf.de/prod/index.php?r=like%2Flike%2Flike&contentModel=humhub%5Cmodules%5Ccomment%5Cmodels%5CComment&amp;contentId=7

**Comment by buddha87** [comment]
Hmm the '&amp' before contentId should not be encoded, it should be an '&' instead. I don't know why this happens in your case, but I found a similar issue: https://github.com/yiisoft/yii2/issues/9816#issuecomment-148725384

The solution in this case was:

> The problem was in config option arg-separator.output that was set for some reasons to non-default value &amp; by server admin.
> 
> If you didn't set it to default value Yii will encode the URL double.
> 
> While testing we set it with php_ini:
> ini_set('arg_separator.output', '&');

More information about this php setting: http://php.net/manual/en/ini.core.php#ini.arg-separator.output

**Comment by torstenpetersen** [comment]
Now i've added to .htaccess the line

php_value arg_separator.output &

and it works. Thank you!
