### ISSUE TITLE
Custom links on user edit profile page for admins

### ISSUE THREAD

**Issue by hfortune** [humhub/humhub#1563]
I run a nonprofit organization and we are building a community using HumHub for our members. I've been pleased thus far with how many of our needed features were already included in HumHub or its related modules. It is really a great fit for our organization.

I do have one very custom thing that we do and I'm hoping someone can point me in the right direction as to how to accomplish this:

We do several checks on our members prior to approving them for membership. In our other registration review screens, we've been able to insert custom links so that our administrators can easily look up this information prior to making an approval.

Ideally, I'd like these links to only be visible to admins and a particular group, but even if they must be visible to everyone within the edit screen, I think that would be sufficient.

Can anyone help me to figure out how I can insert these custom links so that our administrators can easily access them to review our pending members?

Thanks,
Heather

**Comment by buddha87** [comment]
Hi, with the upcoming release you are able to use permissions to enable/disable features for specific groups. You'll have to create a custom permission (a php class), assign this permission to your group and check this permission before inserting you links. I hope we can provide you with a more detailed documentation of how to use the permission system soon.

**Comment by hfortune** [comment]
How can I build the link using user profile fields?

For example:

```
<div>
	<h3>Family Watchdog Search</h3>
<div style="display:block; position:relative;">
	<div style="float:left; margin: 5px; display:inline;">
		<form method="post" action="http://www.familywatchdog.us/ShowMap_Status.asp" target="_blank">
  			<input type="submit" name="Submit" value="Search by address">
  			<input name="txtStreet1" type="hidden" id="txtStreet1" value="[field_streetaddress]">
  			<input name="txtCity" type="hidden" id="txtCity" value="[field_city]">
  			<input name="txtState" type="hidden" id="txtState" value="[field_state]">
  			<input name="txtZipCode" type="hidden" id="txtZipCode" value="[field_zip]">
		</form>
	</div><div style="float:left; margin: 5px; display:inline;">
		<form name="form2" method="post" action="http://www.familywatchdog.us/ShowNameList.asp" target="_blank">
  			<input type="submit" name="Submit3" value="Seach last name + state">
  			<input name="txtLastName" type="hidden" id="txtLastName" value="[field_lastname]">
  			<input name="txtState" type="hidden" id="txtState" value="[field_state]">
		</form>
	</div><div style="float:left; margin: 5px; display:inline;">
		<form name="form1" method="post" action="http://www.familywatchdog.us/ShowNameList.asp" target="_blank">
  			<input type="submit" name="Submit2" value="Search first name + last name + state">
 	 		<input name="txtFirstName" type="hidden" id="txtFirstName" value="[field_firstname]">
  			<input name="txtLastName" type="hidden" id="txtLastName" value="[field_lastname]">
  			<input name="txtState" type="hidden" id="txtState" value="[field_state]">
		</form>
	</div>
</div>
<div style="clear: both;" />
```

This is the code we are currently using on our Drupal websites. As you can see, we are building a link using tokens of user profile fields and with each user, it is pulling that user profile information into the link, so that it is a customized link for each user.

How can I go about creating a link like that (whether it is visible to just admin or anyone who can edit the user) on the user edit page.

Thanks in advance for any help
Heather
