### ISSUE TITLE
yii space/assign-all-members always shows Space not found! Check guid!

### ISSUE THREAD

**Issue by Twilek-de** [humhub/humhub#1568]
I am trying to use yii space/assign-all-members. But whatever guid I enter it always says "Space not found". I get the guids from the URLs of the spaces. I am using 1.0.0 beta4.

**Comment by buddha87** [comment]
Hi, this command needs the actual database id of the space not the guid. You can check the space id under Administration->Spaces.

**Comment by Twilek-de** [comment]
Yes perfect, that did it. Thank you...
