### ISSUE TITLE
integrating new features

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#1570]
Hello all.
I am trying to make some updates on a new column inside users table.
It seems that i cant find where the unique identifier is stored in the code.
Please help me complete this mysqli_query.:

`mysqli_query($conn, "UPDATE user SET newColumn='newValue' WHERE guid='".$WHATIPUTHERE."'");`

On the code above i am assuming the guid is the main unique id for each user. My approach may not be the best and cleanest but should work if i find what is the variable to insert there.
Please help me complete the query or if you can, guide me into achieving the same purpose.
Thanks

**Comment by VasileGabriel** [comment]
The guid is one of the unique identifiers for each user and is stored in the database for each user. You won't find this piece of info in code.
To update a user you better user the User model like this

`
$user = \humhub\modules\user\models\User::findOne(['guid' => $WHATIPUTHERE]);
$user->newColumn = 'newValue';
$user->save();

`
This is assuming you have that column in the database and the model passes the validation.

**Comment by AlphabetoPT** [comment]
sorry but im afraid i am not following.
how do i use the same session that is already created by humhub to detect wich GUID is being used or the current loged in user?
Thanks

**Comment by VasileGabriel** [comment]
```
Yii::$app->user->identity
```
is the model of the logged in user.

```
$user = Yii::$app->user->identity;
$user->newColumn = 'new value';
$user->save()
```
is the same code as in my first comment, with the difference that it executes for the logged in user.

**Comment by AlphabetoPT** [comment]
Hello, thanks.
I tried to insert that code on "/protected/modules_core/dashboard/widgets/DashboardSidebarWidget.php because thats the element i am changing. but the whole page returns an error let me show you:
Code inserted-> http://prnt.sc/aifcng
Page output -> http://prnt.sc/aifcts [this is my dashboard after the code]

**Comment by Felli** [comment]
@AlphabetaPT try using
```
$user = Yii::$app()->user->identity;
$user->newColumn = 'new value';
$user->save()
```
Then again I don't think even that will help within Yii2... Either way it's worth a try. :laughing:

**Comment by AlphabetoPT** [comment]
thanks @Felli i got this error now:

PHP notice

Undefined variable: app

/var/www/html/protected/modules_core/dashboard/widgets/DashboardSidebarWidget.php(2)

01 <?php
02 $user = Yii::$app()->user->identity;
03 $user->teste = 'new value';
04 $user->save();
05 // RUDIMENTAR MEU CARO xD
06 $ligacao =  mysqli_connect("localhost", "root", "!!21188kanuko!!", "humhub");
07 // SIGA PRA BINGO - > CHECK QUAIS STREAMS TAO ONLINE
08     // PEDRADA
09     $chnA = "pedradaftw";
10     function is_channelA_live( $channelA ) {
11     $twitchRequest = json_decode( @file_get_contents( 'https://api.twitch.tv/kraken/streams/' . $channelA ) );
12     return ( ! is_null( $twitchRequest->stream ) ) ? TRUE : FALSE;
13     }
14 // ---
Stack Trace
#0	
+  /var/www/html/protected/vendors/yii/YiiBase.php(320): require("/var/www/html/protected/modules_core/dashboard/widgets/Dashboard...")
#1	
+  /var/www/html/protected/vendors/yii/web/CWidgetFactory.php(146): YiiBase::import("application.modules_core.dashboard.widgets.DashboardSidebarWidge...", true)
#2	
+  /var/www/html/protected/vendors/yii/web/CBaseController.php(146): CWidgetFactory->createWidget(DashboardController, "application.modules_core.dashboard.widgets.DashboardSidebarWidge...", array("widgets" => array(array("application.modules_core.activity.widgets.ActivityStreamWidget", array("streamAction" => "//dashboard/dashboard/stream"), array("sortOrder" => 10)))))
#3	
+  /var/www/html/protected/vendors/yii/web/CBaseController.php(172): CBaseController->createWidget("application.modules_core.dashboard.widgets.DashboardSidebarWidge...", array("widgets" => array(array("application.modules_core.activity.widgets.ActivityStreamWidget", array("streamAction" => "//dashboard/dashboard/stream"), array("sortOrder" => 10)))))
#4	
–  /var/www/html/protected/modules_core/dashboard/views/dashboard/index.php(29): CBaseController->widget("application.modules_core.dashboard.widgets.DashboardSidebarWidge...", array("widgets" => array(array("application.modules_core.activity.widgets.ActivityStreamWidget", array("streamAction" => "//dashboard/dashboard/stream"), array("sortOrder" => 10)))))
24             <?php
25             $this->widget('application.modules_core.dashboard.widgets.DashboardSidebarWidget', array(
26                 'widgets' => array(
27                     array('application.modules_core.activity.widgets.ActivityStreamWidget', array('streamAction' => '//dashboard/dashboard/stream'), array('sortOrder' => 10)),
28                 )
29             ));
30             ?>
31         </div>
32     </div>
33 </div>
#5	
+  /var/www/html/protected/vendors/yii/web/CBaseController.php(126): require("/var/www/html/protected/modules_core/dashboard/views/dashboard/i...")
#6	
+  /var/www/html/protected/vendors/yii/web/CBaseController.php(95): CBaseController->renderInternal("/var/www/html/protected/modules_core/dashboard/views/dashboard/i...", array("showProfilePostForm" => "1"), true)
#7	
+  /var/www/html/protected/vendors/yii/web/CController.php(869): CBaseController->renderFile("/var/www/html/protected/modules_core/dashboard/views/dashboard/i...", array("showProfilePostForm" => "1"), true)
#8	
–  /var/www/html/protected/components/Controller.php(191): CController->renderPartial("index", array("showProfilePostForm" => "1"), true, false)
186              * @param4 String view path
187              */
188             Yii::app()->clientScript->registerScript("autoAjaxEventFire", "$('body').trigger('ajaxLoaded', ['" . $this->id . "', '" . $moduleID . "', '" . $this->action->id . "', '" . $view . "']);", CClientScript::POS_END);
189         }
190 
191         return parent::renderPartial($view, $data, $return, $processOutput);
192     }
193 
194     /**
195      * @return string the page title. Defaults to the controller name and the action name.
196      */
#9	
+  /var/www/html/protected/vendors/yii/web/CController.php(782): Controller->renderPartial("index", array("showProfilePostForm" => "1"), true)
#10	
–  /var/www/html/protected/modules_core/dashboard/controllers/DashboardController.php(82): CController->render("index", array("showProfilePostForm" => "1"))
77         if (Yii::app()->user->isGuest) {
78             $this->render('index_guest', array());
79         } else {
80             $this->render('index', array(
81                 'showProfilePostForm' => HSetting::Get('showProfilePostForm', 'dashboard')
82             ));
83         }
84     }
85 
86 }
#11	
+  /var/www/html/protected/vendors/yii/web/actions/CInlineAction.php(49): DashboardController->actionIndex()
#12	
+  /var/www/html/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams(array("r" => "dashboard/dashboard"))
#13	
+  /var/www/html/protected/vendors/yii/web/filters/CFilterChain.php(133): CController->runAction(CInlineAction)
#14	
+  /var/www/html/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run()
#15	
+  /var/www/html/protected/vendors/yii/web/CController.php(1145): CFilter->filter(CFilterChain)
#16	
+  /var/www/html/protected/vendors/yii/web/filters/CInlineFilter.php(58): CController->filterAccessControl(CFilterChain)
#17	
+  /var/www/html/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter(CFilterChain)
#18	
+  /var/www/html/protected/vendors/yii/web/CController.php(291): CFilterChain->run()
#19	
+  /var/www/html/protected/vendors/yii/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array("accessControl"))
#20	
+  /var/www/html/protected/vendors/yii/web/CWebApplication.php(282): CController->run("")
#21	
+  /var/www/html/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController("dashboard/dashboard")
#22	
+  /var/www/html/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest()
#23	
+  /var/www/html/index.php(39): CApplication->run()
2016-03-22 07:20:08 Apache/2.4.7 (Ubuntu) Yii Framework/1.1.15

**Comment by buddha87** [comment]
Hi, to retrieve the current user model use:

`Yii::$app->user->getIdentity()`

When you want to add a new column to the user table, you should do this by using a migration:
https://www.humhub.org/docs/guide-dev-module-db.html

If you just want to test, you also can add the column by yourself e.g. through phpmyadmin, Yii won't add the column for you ;)

In older versions the call was Yii::app() but this changed in Yii 2.

**Comment by AlphabetoPT** [comment]
@buddha87 thanks for helping but as soon as i place that line on the refered file it breaks the page.~
please i need this :) if someone is sure that can do it please add me on Skype -> mcaleatorio.
thanks

**Comment by AlphabetoPT** [comment]
Please all i need is a simple line that assign the current logged in user to a variable! Help me :)

**Comment by buddha87** [comment]
Where do you want to call this ? Within a view or a controller ? 
As I said: 

Yii::$app->user->getIdentity() should work, as in the following code:

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/controllers/AccountController.php#L48

perhaps you forgot to include Yii with:

`use Yii;`

If you want to use this in a view you have to enclose it like this

```
<?php $user =  Yii::$app->user->getIdentity(); ?>
<?= $user->id; ?>
```

But I really suggest reading some PHP tutorials and check the Yii documentation. I doubt that you'll get a full crash course here on github ;)

**Comment by AlphabetoPT** [comment]
Yeah i know thanks i just need to figure out this node and i will be able to complete my intention.
This is my current /protected/modules_core/dashboard/widgets/DashboardSidebarWidget.php.

http://pastebin.com/7Dn26rxw

As soon as i save a version with your updates my website crashes with error.
Can you please implement it on the current pastebin in order to make an example to me?
I would be really glad. Thank you very much for your patience

**Comment by buddha87** [comment]
Since I don't know if you are using the widget correct (which I doubt when i see the code ;) I cannot promise this is working for you, but here just the few lines at the beginning.

http://pastebin.com/csFw9qBe

Here is the part of the Yii doc for implementing widgets:

http://www.yiiframework.com/doc-2.0/guide-structure-widgets.html

You should really follow the guidelines of the framework you are using, otherwise its really hard to get proper support.

**Comment by AlphabetoPT** [comment]
I pasted the 3 lines as you said and this was the result on dashboard: http://prnt.sc/aihrd6
How can it be so dificult to get the logged in user?
I just used that widget to place a Stream on my model let me show -> http://prntscr.com/aihsqd
Once again Thanks for your patience... Any other clues?
Thanks

**Comment by AlphabetoPT** [comment]
Anyone? Please?

**Comment by VasileGabriel** [comment]
The code you were provided should work, but one of the problems is you shouldn't place that code in a widget. Those lines belong to a controller action.

**Comment by AlphabetoPT** [comment]
Now i get it! Thanks for the straightforward answer.
I am placing the changes in the wrong file!
Can you please send me the file location where i should be editing to get the same results as provided here?
http://prntscr.com/aihsqd

thanks

**Comment by VasileGabriel** [comment]
skype: gabriel.vasile93

**Comment by AlphabetoPT** [comment]
i will add and call in a few moments i am going home. thank you sir

**Comment by AlphabetoPT** [comment]
Im home now i added you. Whisper me when you can. Thanks
