### ISSUE TITLE
Cannot scroll Spaces list in Ios Safari

### ISSUE THREAD

**Issue by Twilek-de** [humhub/humhub#1573]
If I have more spaces than can be displayed I cannot scroll the spaces in the dropdown menu in safari on my iPhone (I use Humhub 1.0.0 beta 4)

![img_1962](https://cloud.githubusercontent.com/assets/8283684/14031181/e2d0878a-f20b-11e5-997f-808779cbec38.JPG)

**Comment by buddha87** [comment]
This bug was introduced by a new version of the nicescroll jquery plugin, we downgraded the plugin version and its working again. This will be part of the upcomming 1.0 release which will be releases within the next days.

**Comment by programguy** [comment]
This also applies to other browsers, such as Chrome on Android, just in case anybody was wondering.
