### ISSUE TITLE
`Powered by Yii Framework` in ./humhub/modules/admin/view/about

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1575]
![screen shot 2016-03-25 at 09 39 23](https://cloud.githubusercontent.com/assets/6232455/14045038/ef812136-f26c-11e5-9fe2-3994fd22651a.png)

**Comment by luke-** [comment]
Whats the problem?

**Comment by davidjeddy** [comment]
The verbiage 'Powered by Yii Framework' is visible in the lower right corner. Not sure if that is intended or not.

**Comment by luke-** [comment]
Yes,this is intended.
