### ISSUE TITLE
WIKI issue / vers. 1.1.0 / Delete a page

### ISSUE THREAD

**Issue by ygrosyeux** [humhub/humhub#1576]
Hi,

when I try to delete a page in a wiki, i've got an error : 

exception 'yii\web\HttpException' with message 'Access denied!' in D:\ProgramData\Apache24Data\htdocs\myvario\protected\modules\wiki\controllers\PageController.php:190 Stack trace: #0 [internal function]: humhub\modules\wiki\controllers\PageController->actionDelete() #1 D:\ProgramData\Apache24Data\htdocs\myvario\protected\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array) #2 D:\ProgramData\Apache24Data\htdocs\myvario\protected\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array) #3 D:\ProgramData\Apache24Data\htdocs\myvario\protected\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction('delete', Array) #4 D:\ProgramData\Apache24Data\htdocs\myvario\protected\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('wiki/page/delet...', Array) #5 D:\ProgramData\Apache24Data\htdocs\myvario\protected\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 D:\ProgramData\Apache24Data\htdocs\myvario\index.php(25): yii\base\Application->run() #7 {main}

I'm logged in super admin, administrator of the wiki's space.

**Comment by ygrosyeux** [comment]
Is anyone have this problem ?

**Comment by buddha87** [comment]
Hi, go to 'Space Settings -> Members -> Permissions' and check your permission settings for the given user group. It seems the user is not allowed to delete a wiki.

**Comment by ygrosyeux** [comment]
Hi,
i've checked, and the group is allowed to manage page. The problem persists. 
![wikiissue](https://cloud.githubusercontent.com/assets/16611866/14307468/7eb4fa10-fbcf-11e5-9952-0c696fe72ed9.png) ==> 
![image](https://cloud.githubusercontent.com/assets/16611866/14307472/884168de-fbcf-11e5-8061-f1ab67df0b09.png)

**Comment by buddha87** [comment]
Note: the the administrator in this context is the space administrator not the system administrator.

**Comment by alex8486** [comment]
I'm getting the same error. The space admin is me and i also tried making another user Administrator for the wiki or / and setting delete permissions to "members" but nothing worked for me or the user.

 Error  Thu, 07 Apr 2016 23:16:42 +0200  yii\web\HttpException:400
exception 'yii\web\HttpException' with message 'Access denied!' in /var/www/humhub/protected/modules/wiki/controllers/PageController.php:190 Stack trace: #0 [internal function]: humhub\modules\wiki\controllers\PageController->actionDelete() #1 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #3 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('delete', Array) #4 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('wiki/page/delet...', Array) #5 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /var/www/humhub/index.php(25): yii\base\Application->run() #7 {main}

**Comment by 3cst4sy** [comment]
It's a bug in protected/modules/wiki/controllers/PageController.php:189
change `if ($this->canAdminister()) {` to `if (!$this->canAdminister()) {`

**Comment by alex8486** [comment]
this fix works for me,  thanks for fast reply

**Comment by ygrosyeux** [comment]
this fix works for me too, thanks for fast reply :+1:
