### ISSUE TITLE
Trying to override views using theme pathMap...

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1582]
Trying to override some default views using Yii2 theming mechanism. I have check that the file paths exist but the view are not using the theme's overrides.

Application config:
```
...
        'view' => [
            'theme' => [
                'pathMap' => [
                    '@app/{app_name}/modules/oAuthUser/views/auth'=> '@app/../themes/{theme_name}/modules/oAuthUser/views/auth',
                ],
            ],
        ],
    ],
    'modules'  
```

Both the theme and Application have the same name.

See the following image for applicaton setup:
![screen shot 2016-03-28 at 12 39 45](https://cloud.githubusercontent.com/assets/6232455/14083147/1297fd62-f4e2-11e5-9924-a60bacc43eed.png)

With this setup, no matter what I try the applications oAuthUser/views/auth views are never overwritten with the theme version.

**Comment by buddha87** [comment]
the follwing pattern is used in [humhub/components/theme.php](https://github.com/humhub/humhub/blob/master/protected/humhub/components/Theme.php#L102) : 

 .../<moduleId>/views/<controllerId>/viewName.php
 to:
 .../views/<moduleId>/<controllerId>/viewName.php
 
or

 .../<moduleId>/[widgets|activities|notifications]/views/viewName.php
 to:
 .../views/<moduleId>/[widgets|activities|notifications]/viewName.php

**Comment by davidjeddy** [comment]
Ok, that does work, and very nicely (no configuration override needed). However, specifying overrides should also work. correct?

**Comment by davidjeddy** [comment]
Got it figured out:
![screen shot 2016-04-13 at 15 59 03](https://cloud.githubusercontent.com/assets/6232455/14507489/ca4ce37c-0190-11e6-8a99-2fc54f340831.png)
