### ISSUE TITLE
BUG: Acceptance testing does not load theme view overrides.

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1583]
Automatic view over rides work when using the application. However during acceptance testing I change the theme (confirmed successful) and then load the view that should be over written, the tests fail and the _output/\* provided shows that the view is NOT being overwritten.

**Comment by davidjeddy** [comment]
Sorted this out:

Solution:
./index-test.php has a $config array. This array needs to include the ./config/dynamic.php configuration if it is present. Exp to follow:

```
$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/protected/humhub/tests/codeception/config/acceptance.php'),
    require(__DIR__ . '/protected/tradesfactor/tests/codeception/config/acceptance.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : []
);
```

PR has been submitted https://github.com/humhub/humhub/pull/1586

**Comment by luke-** [comment]
We should use an own dynamic for testing:
https://github.com/humhub/humhub/issues/1231
