### ISSUE TITLE
Member directory shows duplicate users

### ISSUE THREAD

**Issue by caspre24** [humhub/humhub#1584]
In the member directory listing some users are listed multiple times (ranges from 2 up to 5 or 6 times).
I confirmed that in the database, these users exist only once (user table lists correct users).
I tracked down the problem to
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/directory/controllers/DirectoryController.php#L96 where the `$searchResultSet` already contains duplicate entries, but I'm a total Yii noob, so I don't know where to go from here on.

Interestingly, saving a user "deduplicates" him, but not permanently. What I mean is the following:
Lets assume we have a user Bob and he is listed multiple times.
Either through Administration->Users->Edit Bob or, if logged in as Bob, through Account Settings, bring up the edit user dialog.
It's irrelevant if any value is changed, but if I click "save"/"save profile", Bob is now listed only once in the directory.
I did this with all my users two days ago, but now, there are again 3 users showing up 3 or 4 times. And they haven't even logged in since then.

My specs:
Debian 8 Kernel 3.16.0-4-amd64 x86_64
nginx 1.8.1
PHP 5.6.17-0+deb8u1
MySQL  Ver 14.14 Distrib 5.5.47
HumHub 1.0.0

**Comment by luke-** [comment]
Hmm, the results (users) in directory are stored in lucence search index (protected/runtime/searchdb).

When a user is saved, all old records will be deleted and a new record in search index will be created.Which explains your "deduplicating" way, you can also rebuild the complete search index via console 

```
cd protected
php yii search/rebuild
```

We had a similar issue on a cron/ldap combination which caused a race condition.
Can you disable your cronjobs and check if the problem still appears?

**Comment by caspre24** [comment]
I'll try that, thanks for your quick reply ^^

**Comment by caspre24** [comment]
It seems the problem solved itself. Even with cron jobs running, no users were duplicated since my last "deduplication".
