### ISSUE TITLE
Composer: ext-ldap is required, but should be optional

### ISSUE THREAD

**Issue by dakur** [humhub/humhub#1588]
`composer update` returns:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - zendframework/zend-ldap 2.6.0 requires ext-ldap \* -> the requested PHP extension ldap is missing from your system.
>     - zendframework/zend-ldap 2.5.2 requires ext-ldap \* -> the requested PHP extension ldap is missing from your system.
>     - zendframework/zend-ldap 2.5.1 requires ext-ldap \* -> the requested PHP extension ldap is missing from your system.
>     - zendframework/zend-ldap 2.5.0 requires ext-ldap \* -> the requested PHP extension ldap is missing from your system.
>     - Installation request for zendframework/zend-ldap ^2.5 -> satisfiable by zendframework/zend-ldap[2.5.0, 2.5.1, 2.5.2, 2.6.0].

while HumHub requirements say: php5-ldap (optional)
So I am not able to install HumHub at all.

Clonned from master, last commit: c949ca2

**Comment by tobciu** [comment]
please read the error message ;-) http://lmgtfy.com/?q=php+ldap+install

**Comment by dakur** [comment]
Please read the issue title and maybe HumHub requirements too. ;-)

**Comment by tobciu** [comment]
sorry, i've working over a year with humhub and i've seen many of these error messages... so i didnt read all of your entry :-\

**Comment by luke-** [comment]
Since the manual installation via Git & Composer is for developers only - there might some extra dependencies.

Alternatively you can download prebuild packages or remove this requirement.
