### ISSUE TITLE
errors!

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1599]
![hum1](https://cloud.githubusercontent.com/assets/7725575/14226530/a1cbb708-f8d4-11e5-8bc9-c9e60ed032cf.png)

![hum2](https://cloud.githubusercontent.com/assets/7725575/14226531/a1f2b5ce-f8d4-11e5-9a87-7e456ce6f148.png)

![hum3](https://cloud.githubusercontent.com/assets/7725575/14226532/a207da08-f8d4-11e5-8efa-d9aef3e3004d.png)

Host:
![hummm](https://cloud.githubusercontent.com/assets/7725575/14226544/f508d54a-f8d4-11e5-8b3b-79919741c05b.png)
HumHub: 1.0.0
Php: https://jsfiddle.net/wny3vzp7/

**Comment by buddha87** [comment]
Do you know when this error occures, for which action?

**Comment by cagatayldzz** [comment]
@buddha87 
When I went to the user profile without logging in it gives me this error.
My English is bad :(
![screenshot_20160402-203225 01](https://cloud.githubusercontent.com/assets/7725575/14228041/267a776c-f913-11e5-97dd-6c725fa4a10e.png)

**Comment by buddha87** [comment]
The user of the profile has to allow guests to view his profile under 'Account-Settings -> Profile visibility' 
but there seems to be another issue with this: https://github.com/humhub/humhub/issues/1602
