### ISSUE TITLE
File-Uploads dont work

### ISSUE THREAD

**Issue by mitees** [humhub/humhub#160]
hi,

first of all: Really nice Social Network ! Love the design !

now my issue: no matter where i try to upload (.jpg) i cant upload the file. The progressbar goes till 100% but then nothing happens. also i i want to upload a file in the spaces, i can choose a file but then it doesnt upload. 

any suggestions?

edit: I didnt want to open a new issue for some improvement suggestions:
1. it would be great if you could see (like in facebook with the world icon or lock icon) if you post public or private instead of clicking the gear-icon....

2.it would be even greater if there would be infinite scrolling in the spaces instead of XX posts per site.

greetings

**Comment by foxkrak** [comment]
I am not a programmer, most know what the problem alexorlov1 , leave unchecked the X- Sendfile option, Administration / file

sorry my inglish. i don't speak inglish, i'm using the google translator!

**Comment by saqibamin** [comment]
I also encountered this issue once, but my issue was that I had the file_info extension disabled in php.ini. I just enabled it back and it was working fine afterwards.

**Comment by luke-** [comment]
@saqibamin Thanks for the hint, we've also added FileInfo extension to the requirements checker. (Was missing before)
