### ISSUE TITLE
Unable to invite people to spaces

### ISSUE THREAD

**Issue by Censtudios** [humhub/humhub#1601]
For a while now I've been having this issue, hoping it would get fixed in updates, but so far it hasn't.

When I try to invite a member of my site to a space and click SEND, the modal immediatly changes to the "invite by email" tab and says "email addresses is not valid!". When I try to invite them by inserting their email it says they are already a member of the SITE (not the space, but the site).

Screenshots:
http://riftside.net/aaa_error_1.png
http://riftside.net/aaa_error_2.png

**Comment by buddha87** [comment]
Which browser are you using, it seems that your browser somehow takes your placeholder text as value of the textarea when sending the form.

**Comment by Censtudios** [comment]
This happens in both chrome and firefox. And yes that's been happening for a few updates now. Since one of the earlier 1.0 beta's I think beta1 or beta2

**Comment by buddha87** [comment]
You mean every form submits the placeholder attribute of input fields as form value if you do not overwrite it ?

**Comment by Censtudios** [comment]
All forms show the placeholder as a form value except for the wall posts (that placeholder actually gets removed when you click the input field), although a few updates back it did post "What's on your mind" if you didn't write your own text. If you don't overwrite it (let's say in a PM or a comment) it will post the placeholder text instead.

But in the space invite, even if you do remove the placeholder text and only have the member name in there, it will give that weird error saying invalid email.

**Comment by Censtudios** [comment]
Found out it's indeed because of the placeholder problem. I replaced the placeholder texts of both the "pick users" and "invite by email" tabs literally to "", (so nothing) instead of //Yii::t('SpaceModule.views_space_invite', 'Email addresses') and when I invite a member it does work now.

So the problem really is the placeholder turning into actual form text

**Comment by buddha87** [comment]
Hmm, cannot reproduce this which HumHub version do you use ?

**Comment by Censtudios** [comment]
the latest (version 1.0.0 stable)

**Comment by buddha87** [comment]
How did you install your humhub ? By git/composer or did you download the full package under https://www.humhub.org/de/download ? If its a git/composer install you may have to update your composer dependencies.

**Comment by Censtudios** [comment]
I installed the full package 0.20 through FTP a few months ago and have been updating it using the Updater module ever since. I have no experience with git/composer

**Comment by buddha87** [comment]
Are you using a custom theme, if yes does this also happen if you change to the default theme ?

**Comment by buddha87** [comment]
Furthermore are there any errors in your developer console ?

**Comment by Censtudios** [comment]
I use a custom theme but it also happens on the default theme. When it happens no errors show up in admin/logging (though there's always random errors that show when bots or visitors visit pages that don't or no longer exist, 404 errors should not show up in logging :smile: )

I've been using the custom theme only for a week now, and like I said It's been happening for a few updates now. I think 1.0 beta 2 or 3

I've also been trying to figure out why it could be happening, but I couldn't. You're more knowledgable about this that's why I decided to post it after such a long time. (i was also hoping it would get magically fixed in the last few updates)

**Comment by buddha87** [comment]
Yeah, we plan to remove such errors in the future. Can you check which Jquery.Placholder version you are using. In my 1.0.0 its this:  HTML5 Placeholder jQuery Plugin - v2.3.1 . Here is a similar issue of the placeholder plugin https://github.com/mathiasbynens/jquery-placeholder/issues/244 perhaps you find some similar issues in theire github

**Comment by Censtudios** [comment]
Yes it says 2.3.1 for me as well. I'll take a look at that github thanks

**Comment by Censtudios** [comment]
Nope. I tried but it's still an issue.

It's weird, because some placeholders work fine, but others don't. For an example, when I use the Polls module, the "Ask something" placeholder works fine, but "Add answer" doesn't. What's on your mind" on the stream works fine too, but with mail module, "Add recipients" doesn't (although that one DOESN'T submit to the server). So some of them submit to the servers, others don't, others remove the placeholder fine, then others don't. It's really mixed.

**Comment by buddha87** [comment]
Does this change anything if you type $('#idoftheinputfield').placeholder() in your developerconsole, of course replace the id of the input field if it has an id ?

**Comment by Censtudios** [comment]
Well the Answers input fields in polls have no ID, but I do see that in the devconsole (I assume you mean the one in Chrome/Firefox when you click Inspect Element) changes from 

`<input type="text" name="newAnswers[]" class="form-control poll_answer_new_input contentForm placeholder" placeholder="Add answer..." title="">`

to

`<input type="text" name="newAnswers[]" class="form-control poll_answer_new_input contentForm" placeholder="Add answer..." title="">`

then back to the first one (where "placeholder" is also one of it's classes). This happens to all of the input fields with this issue. Maybe I can screencap/record some footage as an example for you to make it more clear? Maybe that helps.
