### ISSUE TITLE
BUG: Stream / Message content consistency.

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1605]
**Action Performed:**
0. Log in a User
1. Click on Messages
2. Click to send new message
3. Type username of User 2 and select from dropdown
4. Enter subject and message and click send
5. Click on edit icon next to message to edit it
6. Edit message or delete
7. Log out and log in as second user
8. View new messages

**Expected Result:**
User 2 sees message recieved, if message has been modified User 2 may receive an update message or be able to view the edit history, messages deleted in User 1's stream after sending message still appear in User 2's stream.

**Actual Result:**
Recipient stream displays edited version of message with no edit history. This is confusing to the user and is inconsistent with the emails received when the message is sent. 
Messages deleted are not displayed in the recipients stream, although they will receive an email re. the new message.

**Comment by buddha87** [comment]
Wouldn't call it a bug, but you are right the message should be marked with a last edit date information, and perhaps fire a new update notification for all participants. I think a history for edited messages would be a bit too much.

**Comment by davidjeddy** [comment]
What about doing a diff of the message content and store the original in a repository table as TEXT table?
