### ISSUE TITLE
Fatal Error when uninstalling module

### ISSUE THREAD

**Issue by RichWeber** [humhub/humhub#1608]
I get the next error when try to uninstall my module

```
PHP Fatal Error – yii\base\ErrorException

Class 'humhub\modules\admin\controllers\HttpException' not found
```

<img width="1146" alt="screen" src="https://cloud.githubusercontent.com/assets/1702252/14296783/6904b1a6-fb84-11e5-9679-860e30143e2a.png">

**Comment by buddha87** [comment]
thanks
