### ISSUE TITLE
yii\web\HttpExcep

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1623]
exception 'yii\web\HttpException' with message 'You need to login to view this user profile!' in /home/abcde/public_html/protected/humhub/modules/user/behaviors/ProfileController.php:64 Stack trace: #0 [internal function]: humhub\modules\user\behaviors\ProfileController->checkAccess() #1 /home/abcde/public_html/protected/vendor/yiisoft/yii2/base/Component.php(282): call_user_func_array(Array, Array) #2 /home/abcde/public_html/protected/humhub/modules/content/components/ContentContainerController.php(123): yii\base\Component->__call('checkAccess', Array) #3 /home/abcde/public_html/protected/humhub/modules/content/components/ContentContainerController.php(123): humhub\modules\user\controllers\ProfileController->checkAccess() #4 /home/abcde/public_html/protected/humhub/modules/content/components/ContentContainerController.php(102): humhub\modules\content\components\ContentContainerController->checkContainerAccess() #5 /home/abcde/public_html/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\modules\content\components\ContentContainerController->init() #6 /home/abcde/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(84): yii\base\Object->__construct(Array) #7 [internal function]: yii\base\Controller->__construct('profile', Object(humhub\modules\user\Module), Array) #8 /home/abcde/public_html/protected/vendor/yiisoft/yii2/di/Container.php(368): ReflectionClass->newInstanceArgs(Array) #9 /home/abcde/public_html/protected/vendor/yiisoft/yii2/di/Container.php(153): yii\di\Container->build('humhub\\modules\\...', Array, Array) #10 /home/abcde/public_html/protected/vendor/yiisoft/yii2/BaseYii.php(340): yii\di\Container->get('humhub\\modules\\...', Array) #11 /home/abcde/public_html/protected/vendor/yiisoft/yii2/base/Module.php(567): yii\BaseYii::createObject('humhub\\modules\\...', Array) #12 /home/abcde/public_html/protected/vendor/yiisoft/yii2/base/Module.php(520): yii\base\Module->createControllerByID('profile') #13 /home/abcde/public_html/protected/vendor/yiisoft/yii2/base/Module.php(512): yii\base\Module->createController('profile') #14 /home/abcde/public_html/protected/vendor/yiisoft/yii2/base/Module.php(448): yii\base\Module->createController('user/profile') #15 /home/abcde/public_html/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('user/profile', Array) #16 /home/abcde/public_html/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #17 /home/abcde/public_html/index.php(25): yii\base\Application->run() #18 {main}

**Comment by cagatayldzz** [comment]
![ekran alintisi](https://cloud.githubusercontent.com/assets/7725575/14379580/52c1f79a-fd83-11e5-96b9-ba8464b7c98b.PNG)
v.1.0.0

**Comment by buddha87** [comment]
Yeah you are trying to access a page as a guest, if its a user profile the user has to allow guests to access his profile under account settings.
