### ISSUE TITLE
userCount in UserPicker not working

### ISSUE THREAD

**Issue by atiyehk** [humhub/humhub#1629]
It seems that 'maxUsers' => <value>, is not working when creating a UserPicker in a form. 
I think userCount should be incremented in addUserTag (in userpicker.js) for this function to work properly.

if ($('#user_' + guid + ' a').attr('data-taken') != "true") {

```
    userCount++;
```

**Comment by buddha87** [comment]
The count of users is also determined by the backend action, which differs from userpicker to userpicker. This is not configurable at the moment. But perhaps we should declare a config setting for this.
