### ISSUE TITLE
Photo upload issues

### ISSUE THREAD

**Issue by aallen172** [humhub/humhub#1631]
I've been trying to upload photos to humhub however i continue to receive the included errors in the log file.  The self-test only shows a warning for the APC Support.  I'm running on Ubuntu 15.10 with 8 gigs of ram.  The error indicator states memory is exhausted but I'm not quite sure how that is possible considering my resources are not cumbersome on my server.  The memory in my php.ini is also at 256.

`$_GET = [ 'r' => 'file/file/upload' 'objectModel' => '' 'objectId' => '' ] $_POST = [ '_csrf' => 'Vkt4cUhpcVoFBBkfHVk9AgQnEy46DEceeyE3CSQ4Nz8vejQyGl8hEQ==' 'message' => '' 'notifyUserInput' => '' 'containerGuid' => '8fbe1d2d-0d72-402f-82fd-d523b2399773' 'containerClass' => 'humhub\\modules\\space\\models\\Space' 'fileList' => '' ] $_FILES = [ 'files' => [ 'name' => [ 0 => '20160405_171102.jpg' ] 'type' => [ 0 => 'image/jpeg' ] 'tmp_name' => [ 0 => '/opt/lampp/temp/phpcNFiqx' ] 'error' => [ 0 => 0 ] 'size' => [ 0 => 4549087 ] ] ] $_COOKIE = [ 'pm_space-members-panel' => 'expanded' 'player-6161726f6e' => '11' 'PHPSESSID' => 'tvq88hhmbbadiblogqgtuft602' '_csrf' => 'd59476b3bf7719fd08a3c3a59ef789699e9067776d5e580fc893bed508c6e9cea:2:{i:0;s:5:\"_csrf\";i:1;s:32:\"SOanU0LXRlk_re6D-jOxlQFey1LCR6PK\";}' '_identity' => '9c27f410a51052a671a294306929a4eadf6b875c3294c96d9a9f8a8160fc4caea:2:{i:0;s:9:\"_identity\";i:1;s:50:\"[1,\"e063d355-4ee4-41b8-805c-2dd5e38a675e\",2592000]\";}' ] $_SESSION = [ '__flash' => [] '__id' => 1 ] $_SERVER = [ 'UNIQUE_ID' => 'VwRLR38AAQEAAFj1ksIAAAAB' 'HTTP_HOST' => '192.168.1.102' 'HTTP_CONNECTION' => 'keep-alive' 'CONTENT_LENGTH' => '4549992' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_ORIGIN' => 'http://192.168.1.102' 'HTTP_X_CSRF_TOKEN' => 'Vkt4cUhpcVoFBBkfHVk9AgQnEy46DEceeyE3CSQ4Nz8vejQyGl8hEQ==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36' 'CONTENT_TYPE' => 'multipart/form-data; boundary=----WebKitFormBoundaryD3719t5b5tLJ4XVM' 'HTTP_REFERER' => 'http://192.168.1.102/social/index.php?r=space%2Fspace&sguid=8fbe1d2d-0d72-402f-82fd-d523b2399773' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8' 'HTTP_COOKIE' => 'pm_space-members-panel=expanded; player-6161726f6e=11; PHPSESSID=tvq88hhmbbadiblogqgtuft602; _csrf=d59476b3bf7719fd08a3c3a59ef789699e9067776d5e580fc893bed508c6e9cea%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22SOanU0LXRlk_re6D-jOxlQFey1LCR6PK%22%3B%7D; _identity=9c27f410a51052a671a294306929a4eadf6b875c3294c96d9a9f8a8160fc4caea%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22e063d355-4ee4-41b8-805c-2dd5e38a675e%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'LD_LIBRARY_PATH' => '/opt/lampp/lib:/opt/lampp/lib' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache/2.4.17 (Unix) OpenSSL/1.0.1q PHP/5.6.15 mod_perl/2.0.8-dev Perl/v5.16.3' 'SERVER_NAME' => '192.168.1.102' 'SERVER_ADDR' => '192.168.1.102' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '192.168.1.198' 'DOCUMENT_ROOT' => '/opt/lampp/htdocs' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/opt/lampp/htdocs' 'SERVER_ADMIN' => 'you@example.com' 'SCRIPT_FILENAME' => '/opt/lampp/htdocs/social/index.php' 'REMOTE_PORT' => '52751' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'POST' 'QUERY_STRING' => 'r=file%2Ffile%2Fupload&objectModel=&objectId=' 'REQUEST_URI' => '/social/index.php?r=file%2Ffile%2Fupload&objectModel=&objectId=' 'SCRIPT_NAME' => '/social/index.php' 'PHP_SELF' => '/social/index.php' 'REQUEST_TIME_FLOAT' => 1459899207.679 'REQUEST_TIME' => 1459899207 ]`

along with:

`exception 'yii\base\ErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 2988 bytes)' in /opt/lampp/htdocs/social/protected/humhub/modules/file/libs/ImageConverter.php:313 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}`

**Comment by buddha87** [comment]
Hi, the allowed size does not seem to be very high, perhaps the following issue will help, seems to be more an yii or server issue: http://www.yiiframework.com/forum/index.php/topic/22964-php-fatal-error-allowed-memory-size-exhausted/

**Comment by aallen172** [comment]
I apologize for not responding sooner.  I decided to start from scratch and backup all my databases and web media for a complete re-installation.  I kept my original humhub installation and created a new one and they both produce the same issue.

Am I supposed to be installing something else other than humhub in my lampp htdocs so it will work? I had presumed this was an all-in-one package which needed no outside dependencies however I can't find anything else which is needed to make it work.

Any help would be appreciated.  I am currently updating humhub, with the newest version released 5-2-16, and if it works I'll make sure I add it here.  The link you sent me did not help with my issue but I appreciate your time.

**Comment by aallen172** [comment]
Just updated and got a new error when attempting to upload a photo:

`WARNING  Tue, 03 May 2016 08:53:25 -0500  yii\log\Dispatcher::dispatch
Unable to send log via yii\log\FileTarget: Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Unable to append to log file: /opt/lampp/htdocs/social-old/protected/runtime/logs/app.log' in /opt/lampp/htdocs/social-old/protected/vendor/yiisoft/yii2/log/FileTarget.php:108 Stack trace: #0 /opt/lampp/htdocs/social-old/protected/vendor/yiisoft/yii2/log/Target.php(111): yii\log\FileTarget->export() #1 /opt/lampp/htdocs/social-old/protected/vendor/yiisoft/yii2/log/Dispatcher.php(188): yii\log\Target->collect(Array, true) #2 /opt/lampp/htdocs/social-old/protected/vendor/yiisoft/yii2/log/Logger.php(173): yii\log\Dispatcher->dispatch(Array, true) #3 /opt/lampp/htdocs/social-old/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(247): yii\log\Logger->flush(true) #4 [internal function]: yii\base\ErrorHandler->handleFatalError() #5 {main}`

**Comment by buddha87** [comment]
Did you set the right permissions on your server: https://www.humhub.org/docs/guide-admin-installation.html#file-modes-permissions

**Comment by buddha87** [comment]
Here are the requirements for your server environment: https://www.humhub.org/docs/guide-admin-requirements.html you can check if these packages are installed either in the installer or under Administration -> Selftest and Update. These are environment requirements and cannot be provided in the humhub package.

**Comment by aallen172** [comment]
All of the permissions have been set correctly and the following is my self test information:

`PHP - Version - 5.6.20: Ok!
PHP - GD Extension: Ok!
PHP - INTL Extension: Ok!
PHP - INTL Extension - ICU Version (4.8.1.1): Ok!
PHP - INTL Extension - ICU Data Version (4.8.1): Ok!
PHP - EXIF Extension: Ok!
PHP - FileInfo Extension: Ok!
PHP - Multibyte String Functions: Ok!
PHP - Curl Extension: Ok!
PHP - ZIP Extension: Ok!
LDAP Support: Ok!
PHP - APC Support: Warning! (Hint: Optional - Install APC Extension for APC Caching)
PHP - SQLite3 Support: Ok!
Permissions - Runtime: Ok!
Permissions - Assets: Ok!
Permissions - Uploads: Ok!
Permissions - Module Directory: Ok!
Permissions - Dynamic Config: Ok!

                Yii Migration Tool (based on Yii v2.0.8)

No new migrations found. Your system is up-to-date.
            `

**Comment by aallen172** [comment]
I disabled all extra modules and attempted to upload a photo and it gave me the following error after a brand new install:

ERROR  Tue, 03 May 2016 10:24:21 -0500  yii\base\ErrorException:1
exception 'yii\base\ErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 11952 bytes)' in /opt/lampp/htdocs/social-old/protected/humhub/modules/file/libs/ImageConverter.php:317 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}

**Comment by buddha87** [comment]
Is the file bigger than 134217728 bytes (~134MB) ?

**Comment by aallen172** [comment]
Oh wow no.  It's 5.14 mb which had been taken from a samsung gs6.

**Comment by aallen172** [comment]
So I started testing different photos, of different sizes, and apparently I can upload as long as they're variably under 2 mb.  That being said, my php.ini upload_max_filesize is 128m

**Comment by buddha87** [comment]
Hmm seem like the ImageConverter is pretty memory intensive.

**Comment by buddha87** [comment]
You could configure an ImageMagick command for converting images under Administration->Files, but you would have to install imagemagick first.

**Comment by aallen172** [comment]
I see that I have that function installed however I admit I have no knowledge of using it.  I check around on google to see what commands I should use.

**Comment by buddha87** [comment]
think you don't have to specify much arguments, here is line of code which which sets up the command https://github.com/humhub/humhub/blob/master/protected/humhub/libs/ImageConverter.php#L262 the width and height density... is set by default
