### ISSUE TITLE
Dashboard/Profile Private Posting

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#1632]
Is it possible to enable this feature, and if so how and why isn't it enabled by default? If there isn't an option for this I'd really like to suggest it being implemented for privacy concerns that can be had.

### Example
User01 follows User02 and is able to view all of User02's posts, but sometimes User02 wants a little more privacy to their posts, so they make it private, or only viewable by a select few users. I suggest that this be available in HumHub if not already. :smiley:

**Comment by buddha87** [comment]
You can create private posts on your profile -> Gear Icon -> Make private. In v1.1 these posts will only be visible for Friends.

**Comment by Felli** [comment]
That would be my problem, I'm not seeing this option, the only place that I can see this option is in Spaces. As for the options that I do see, Notify Members is the only one there. Where and which file do I have to edit to enable this feature if any. :smile:

### Screenshot
![screenshot_4](https://cloud.githubusercontent.com/assets/2011633/14413309/23967ad2-ff44-11e5-8a29-e7001880acd2.png)

HumHub v1.0.0

**Comment by buddha87** [comment]
This will be introduced with v1.1 with the enhanced permission system. Since there is no friendship system yet a private post on your profile would not be visible for anyone but yourself. :)
