### ISSUE TITLE
TypeError  search

### ISSUE THREAD

**Issue by asemasran** [humhub/humhub#1633]
TypeError
LimitIterator::__construct() expects parameter 3 to be integer, string given

    1. in /home/mtmrdnga/public_html/protected/humhub/modules/search/engine/ZendLuceneSearch.php at line 119
    110111112113114115116117118119120121122123124125126127128

            } else {
                $hits = new \ArrayObject($index->find($this->buildQuery($keyword, $options), $options['sortField']));
            }
     
            $resultSet = new SearchResultSet();
            $resultSet->total = count($hits);
            $resultSet->pageSize = $options['pageSize'];
            $resultSet->page = $options['page'];
     
            $hits = new \LimitIterator($hits->getIterator(), ($options['page'] - 1) * $options['pageSize'], $options['pageSize']);
            foreach ($hits as $hit) {
                $document = $hit->getDocument();
     
                $result = new SearchResult();
                $result->model = $document->getField('model')->getUtf8Value();
                $result->pk = $document->getField('pk')->getUtf8Value();
                $result->type = $document->getField('type')->getUtf8Value();
     
                $resultSet->results[] = $result;

    2. in /home/mtmrdnga/public_html/protected/humhub/modules/search/engine/ZendLuceneSearch.php at line 119 – LimitIterator::__construct(ArrayIterator, 0, '')
    113114115116117118119120121122123124125

     
            $resultSet = new SearchResultSet();
            $resultSet->total = count($hits);
            $resultSet->pageSize = $options['pageSize'];
            $resultSet->page = $options['page'];
     
            $hits = new \LimitIterator($hits->getIterator(), ($options['page'] - 1) * $options['pageSize'], $options['pageSize']);
            foreach ($hits as $hit) {
                $document = $hit->getDocument();
     
                $result = new SearchResult();
                $result->model = $document->getField('model')->getUtf8Value();
                $result->pk = $document->getField('pk')->getUtf8Value();

    3. in /home/mtmrdnga/public_html/protected/humhub/modules/search/controllers/SearchController.php at line 81 – humhub\modules\search\engine\ZendLuceneSearch::find('', ['page' => 1, 'sort' => 'title', 'pageSize' => '', 'limitSpaces' => [], ...])
    75767778798081828384858687

            } elseif ($scope == self::SCOPE_USER) {
                $options['model'] = User::className();
            } else {
                $scope = self::SCOPE_ALL;
            }
     
            $searchResultSet = Yii::$app->search->find($keyword, $options);
     
            $pagination = new \yii\data\Pagination;
            $pagination->totalCount = $searchResultSet->total;
            $pagination->pageSize = $searchResultSet->pageSize;
     
            return $this->render('index', array(

    4. humhub\modules\search\controllers\SearchController::actionIndex()
    5. in /home/mtmrdnga/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\search\controllers\SearchController, 'actionIndex'], [])
    6. in /home/mtmrdnga/public_html/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'search/search/index'])
    7. in /home/mtmrdnga/public_html/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('index', ['r' => 'search/search/index'])
    8. in /home/mtmrdnga/public_html/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('search/search/index', ['r' => 'search/search/index'])
    9. in /home/mtmrdnga/public_html/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
    10. in /home/mtmrdnga/public_html/index.php at line 25 – yii\base\Application::run()
    19202122232425

        require(__DIR__ . '/protected/humhub/config/web.php'),
        (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
        require(__DIR__ . '/protected/config/common.php'),
        require(__DIR__ . '/protected/config/web.php')
    );
     
    (new humhub\components\Application($config))->run();

$_GET = [
    'r' => 'search/search/index',
];

$_COOKIE = [
    'PHPSESSID' => 'arus49jlmnavugi0nskohefp12',
    '_csrf' => 'ac50db3dcd734f236edde269da39fbec54d8acd8f505989fb7c98733c38e0a97a:2:{i:0;s:5:"_csrf";i:1;s:32:"PZ7pucbYtgtWT6FJANCkOXsc8TqmEfIv";}',
    'pm_getting-started-panel' => 'expanded',
    'pm_user-tags-panel' => 'expanded',
    'pm_groups-statistics-panel' => 'expanded',
    'language' => 'ce7d690ab1965d4d6f100044870eac3ba81c120d4cf9b8ca3a7dc2bd6e8c5300a:2:{i:0;s:8:"language";i:1;s:2:"en";}',
    '_identity' => '47e148a0973c330f3d33228823f78b9a1581818bdf406a72db682d992b9e8ed2a:2:{i:0;s:9:"_identity";i:1;s:50:"[1,"da3c2c6b-fee9-452a-a85f-65ac1a85f7a3",2592000]";}',
    'pm_profile-follower-panel' => 'expanded',
    'pm_profile-following-panel' => 'expanded',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/index.php',
    '__id' => 1,
];

Yii Framework

2016-04-11, 16:31:11

Apache

Yii Framework/2.0.7

**Comment by buddha87** [comment]
Which HumHub version are you using and where did this occure ? On the main search ?

**Comment by asemasran** [comment]
v1.0.0
yes on the main search

**Comment by asemasran** [comment]
i deleted
this line
        $hits = new \LimitIterator($hits->getIterator(), ($options['page'] - 1) * $options['pageSize'], $options['pageSize']);

now workin but no main search
icon send me to link search page

**Comment by buddha87** [comment]
Ok, can you go under Administration -> Desing and check if the pagination Size is empty. I can reproduce this error if i set an empty pagination size, if its empty set it to 10 or something
