### ISSUE TITLE
Error: Message file for category 'yii' does not exist

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#1636]
I'm getting the following error in my logs, any idea how to fix this?
```The message file for category 'yii' does not exist: /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/messages/zh_cn/yii.php Fallback file does not exist as well: /home/USER/public_html/beta/protected/vendor/yiisoft/yii2/messages/zh/yii.php```

**Comment by luke-** [comment]
We're using slightly other language codes than yii. I've comitted a hotfix...
