### ISSUE TITLE
HUGE: Suddenly half my site stopped working

### ISSUE THREAD

**Issue by Censtudios** [humhub/humhub#1645]
I didn't change any files or the database, but when I woke up yesterday, I noticed that:

- members can't post (comments work however)
- members can't login
- going to directory/members gives an error (some other pages too)
- can't delete members
- basically almost anything that involves a submit button doesn't work

I've been trying for more than a day to figure out what is wrong, but I'm not sure. I thought at first it was because one of the members posted something that had an illegal string or something, but now I'm clueless. 

I also rebooted the server, restored a database backup and restored file backups of the directories mentioned in the error log. 

The error in the errorlog is always the same:

`exception 'yii\base\ErrorException' with message 'Uninitialized string offset: 0' in /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/File/AbstractFile.php:79 Stack trace: #0 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/File/AbstractFile.php(79): yii\base\ErrorHandler->handleError(8, 'Uninitialized s...', '/home/riftside/...', 79, Array) #1 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php(269): ZendSearch\Lucene\Storage\File\AbstractFile->readInt() #2 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php(420): ZendSearch\Lucene\Index->_readSegmentsFile() #3 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Lucene.php(67): ZendSearch\Lucene\Index->__construct('/home/riftside/...', false) #4 /home/riftside/domains/hub.riftside.net/public_html/protected/humhub/modules/search/engine/ZendLuceneSearch.php(263): ZendSearch\Lucene\Lucene::open('/home/riftside/...') #5 /home/riftside/domains/hub.riftside.net/public_html/protected/humhub/modules/search/engine/ZendLuceneSearch.php(75): humhub\modules\search\engine\ZendLuceneSearch->getIndex() #6 /home/riftside/domains/hub.riftside.net/public_html/protected/humhub/modules/search/engine/ZendLuceneSearch.php(69): humhub\modules\search\engine\ZendLuceneSearch->delete(Object(humhub\modules\user\models\User)) #7 /home/riftside/domains/hub.riftside.net/public_html/protected/humhub/modules/user/models/User.php(319): humhub\modules\search\engine\ZendLuceneSearch->update(Object(humhub\modules\user\models\User)) #8 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(739): humhub\modules\user\models\User->afterSave(false, Array) #9 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(533): yii\db\BaseActiveRecord->updateInternal(NULL) #10 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(595): yii\db\ActiveRecord->update(true, NULL) #11 /home/riftside/domains/hub.riftside.net/public_html/protected/humhub/modules/user/models/forms/AccountLogin.php(84): yii\db\BaseActiveRecord->save() #12 /home/riftside/domains/hub.riftside.net/public_html/protected/humhub/modules/user/controllers/AuthController.php(59): humhub\modules\user\models\forms\AccountLogin->login() #13 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin() #14 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #15 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #16 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('login', Array) #17 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('user/auth/login', Array) #18 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #19 /home/riftside/domains/hub.riftside.net/public_html/index.php(25): yii\base\Application->run() #20 {main}`

After checking the Apache logs as well I thought it might also have been caused because of this error I saw (maybe someone posted something during the unlucky timing this was happening on the server?)

`Database Exception: SQLSTATE[HY000]: General error: 1030 Got error 28 from storage engine` But that error hasn't shown up since and the database worked fine after that.

But that wouldn't explain why making new posts doesn't work, does it?

**Comment by luke-** [comment]
Error 28 from MySQL means - disc space full

This may also crashed the humhub search index:
You can rebuild it via:

cd protected
./yii search/rebuild

**Comment by Censtudios** [comment]
Is it possible to do that without ssh? I have very limited knowledge with SSH and I don't want to make things worse. And it seems like the commands you gave are very broad and I would have to use more than that to make it work xD

Maybe through FTP? (though I also already did re-upload the modules/search directory)

**Comment by Censtudios** [comment]
I managed to install yii on my server (I think) and tried it again but now it says 

-bash: ./yii: No such file or directory

I could really use some help here...

**Comment by buddha87** [comment]
yii is a php script which resides in the protected directory of your project you don't have to install it. just execute `./yii search/rebould` in your protected directory, first you have to change to your projects /protected directory

**Comment by Censtudios** [comment]
Oh I didn't realize that I have to CHMOD the yii and yii.bat files in protected! When I used the ./yii search/rebuild command before it said no permission, now it's doing something (putting a lot of periods, as if it's processing)

OK IT WORKS. Thanks a lot! I feel stupid now, but I'm glad I learned something new
