### ISSUE TITLE
Installing Modules Error

### ISSUE THREAD

**Issue by mitees** [humhub/humhub#165]
hi, i tried to install some modules, but no data can be received... can i install modules manually?

here is the error log:

ERROR  Fri, 12 Sep 2014 17:27:25 +0200  exception.CHttpException.500
exception 'CHttpException' with message 'Ungültige Anfrage' in /home/mfranz/htdocs/humhub/protected/components/Controller.php:152 Stack trace: #0 /home/mfranz/htdocs/humhub/protected/modules_core/admin/controllers/ModuleController.php(128): Controller->forcePostRequest() #1 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/actions/CInlineAction.php(49): ModuleController->actionInstall() #2 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams(Array) #3 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction)) #4 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #5 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/CController.php(1145): CFilter->filter(Object(CFilterChain)) #6 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain)) #7 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain)) #8 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #9 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array) #10 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/CWebApplication.php(284): CController->run('install') #11 /home/mfranz/htdocs/humhub/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('admin/module/in...') #12 /home/mfranz/htdocs/humhub/protected/vendors/yii/base/CApplication.php(169): CWebApplication->processRequest() #13 /home/mfranz/htdocs/humhub/index.php(39): CApplication->run() #14 {main} REQUEST_URI=/index.php?r=admin/module/install&moduleId=polls ---

**Comment by WASasquatch** [comment]
I have this same issue now. I get 500 internal server error. No logs. Another vhost on my server can install modules fine, so I'm not sure. vhost configuration is identical as well as the provided PHP modules. 

After numerous attempts, including a manual install of "custompages" I now only get a blank page that states `Modules directory` and nothing else when I click the "Modules" tab in the Administration Center. No errors are being logged.

**Comment by WASasquatch** [comment]
I was able to scrape this from my server after trying to install a module:

```txt

< Date: Mon, 30 Mar 2015 21:20:35 GMT
< Content-Type: text/plain; charset=us-ascii
< Transfer-Encoding: chunked
< Connection: keep-alive
<
{ [data not shown]
100    21    0    21    0     0    183      0 --:--:-- --:--:-- --:--:--   350
* Connection #0 to host data.leafly.com left intact
* Closing connection #0
zend_mm_heap corrupted
```

Notice `zend_mm_heap corrupted`

**Comment by WASasquatch** [comment]
I was able to scrape these calls if they help. Still not other error besides the 500 which persists for a minute or so when refreshing admin/module/list until it finally loads. 

```txt
67.170.40.87 - - [31/Mar/2015:00:09:19 +0000] "GET /development/index.php?r=dashboard/dashboard/GetFrontEndInfo&CSRF_TOKEN=df367c3cf26cd4d823a2603265030c854fafe26e&_=1427760556089 HTTP/1.0" 200 507 "http://herbsy.cf/development/index.php?r=admin/module/list" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0"
67.170.40.87 - - [31/Mar/2015:00:09:22 +0000] "POST /development/index.php?r=admin/module/enable&moduleId=breakingnews HTTP/1.0" 302 452 "http://herbsy.cf/development/index.php?r=admin/module/list" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0"
```

**Comment by megzinha** [comment]
I'm unable to install humhub when access localhost/humhub this error occurs:

Not Found

The requested URL /humhub was not found on this server.

Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80

I would like that someone help me solve this problem. Thanks. Sincerily, Meg.
