### ISSUE TITLE
max-width on images in the feed

### ISSUE THREAD

**Issue by devcline** [humhub/humhub#1650]
its it possible to add this option?

.post-files img {
    vertical-align: top;
    margin-bottom: 3px;
    max-width: 100%;
    width: 100%;
}

and i changed the sizes in thumbs generator.

**Comment by buddha87** [comment]
Hi, I think the images do look to clumsy, especially if you have multiple images in one post perhaps a slider gallery for images would be nice instead

**Comment by devcline** [comment]
some people prefer to see the whole image in the feed like and some prefer to click on it to see a full screen:)

**Comment by Ferdari** [comment]
+1 for this, also can you tell us how to change the thumbs generator?

> and i changed the sizes in thumbs generator.
