### ISSUE TITLE
Delete permission

### ISSUE THREAD

**Issue by thehiddennepali** [humhub/humhub#1651]
Hi I had created another moudles say demomoudle and I had displayed that in space and profile menu section for other user than admin.

the user can create/update/delete data on space section 
but on profile section user only can create/update content but I also need to delete the content,

while trying to delete I got "You are not allowed to perform this action."

so i think i need to create delete permission for user, but I didn't figure out how to create delete permission as I can't see any example and refrence regarding this

so plz any one could suggest me how I give user permission to delete the data

**Comment by luke-** [comment]
Indeed, unfortunately in 1.0 only user profile owner can delete content.
We changed this behavior in 1.1.

As workaround you need to create an own delete action.
