### ISSUE TITLE
Searching email in Manage Users returns PHP error.

### ISSUE THREAD

**Issue by cmoore-mayesh** [humhub/humhub#1652]
![image](https://cloud.githubusercontent.com/assets/18537993/14615885/dd76f918-0575-11e6-9209-4beb5ad3fe2b.png)

If I search for 'sue' in the email search box under Manage Users, I get this page full of PHP error.

![image](https://cloud.githubusercontent.com/assets/18537993/14615894/eb8068aa-0575-11e6-939d-d90ff372132d.png)

**Comment by cmoore-mayesh** [comment]
Using HumHub-1.0.0-beta.4 -- sorry forgot to add that to original post.

**Comment by buddha87** [comment]
Hi, does your profile table contain an email column ?

**Comment by cmoore-mayesh** [comment]
Confirmed with phpmyadmin -- email is column 33 under the profile table.
Also -- we're using LDAP to pull in username/password/email/etc. and for authentication.

**Comment by buddha87** [comment]
k this seems to be the problem, the email is also part of the user table, if both tables have this column, the query fails. We'll have to use the full path in the query to fix this. This will be part of the upcoming v1.0.1 release.

**Comment by cmoore-mayesh** [comment]
Ok -- anything I can do to fix it in the meantime?

**Comment by buddha87** [comment]
You'd have to checkout/replace the file of my pull request.

**Comment by cmoore-mayesh** [comment]
I got it :) Thanks much for the help!

**Comment by buddha87** [comment]
You are welcome, please note that it's possible that the same problem occures on others search querys as well, just inform us if you find other issues.
