### ISSUE TITLE
[Question] Roadmap

### ISSUE THREAD

**Issue by ygrosyeux** [humhub/humhub#1653]
Hello,

Is there a roadmap of upcoming features ?

The document in the Wiki seems no more updated since August 2015 .

Thank you !

**Comment by buddha87** [comment]
Hi,

we posted a roadmap in our community yesterday (space Contribution & Core Developement) https://community.humhub.com/s/96d933cd-e5a9-4314-8f8f-564f2dd81cf6/ .

**Comment by ygrosyeux** [comment]
Thx !
