### ISSUE TITLE
yii\base\ErrorException

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1659]
![screenshot_20160420-205458](https://cloud.githubusercontent.com/assets/7725575/14684807/60a80cb2-073a-11e6-8c1e-ac124b0d61d3.png)

**Comment by iBotPeaches** [comment]
This commit in the mail module seems to have gone crazy - https://github.com/humhub/humhub-modules-mail/commit/e6daeeb074bfd48de699a222b8848f21f991bc0a which introduced that problem.

**Comment by cagatayldzz** [comment]
@luke-

**Comment by luke-** [comment]
@cagatayldzz Oh, there is a git conflict on the message files at our translation server - I'm going to fix this tomorrow

**Comment by luke-** [comment]
Should be fixed now!
