### ISSUE TITLE
Use of undefined constant INTL_ICU_VERSION - assumed 'INTL_ICU_VERSION'

### ISSUE THREAD

**Issue by AskYous** [humhub/humhub#1661]
Hello,

**Error**
I installed HumHub locally to test it out. But after I see the first screen, I see this error:
![image](https://cloud.githubusercontent.com/assets/791996/14690546/6d691574-0701-11e6-8cfe-fa180d250b35.png)

**How I Produced It**

1. Download HumHub.
2. Run it on a server.
3. Click "next" on the welcome screen.
4. Receive this error.

**Technologies I used**

I've tried this in:
- WebMatrix
 - Using PHP version 5.4 and 5.5
- WAMP
 - Using PHP 5.5.12

And yes, I had the PHP Internationalization extension enabled:
![image](https://cloud.githubusercontent.com/assets/791996/14690755/8a51e2dc-0702-11e6-8e93-7485f1caf4fe.png)

**Comment by buddha87** [comment]
Hi, your INTL version is probably to low see this issue: https://github.com/humhub/humhub/issues/1514

HumHub 1.0.0.0 needs PHP INTL ICU version 4.8.1 minimum
