### ISSUE TITLE
Failed auto-registration for oAuth user

### ISSUE THREAD

**Issue by cebe** [humhub/humhub#1672]
I am using the 1.1-dev branch.

When a new user registers via oauth he always gets the registration form because the registration model does not have the default group set, resulting in a `null` user to be returned here:

https://github.com/humhub/humhub/blob/23d16549ec101500c6ad62a56683f54dc8e7957b/protected/humhub/modules/user/controllers/AuthController.php#L137

The registration form should not only have a hidden field that sends the value but also be pre-populated so that the registration works without the form.

I'm going to send a PR to fix it.

**Comment by cebe** [comment]
This is the validation that fails:

```
humhub\modules\user\models\Userhumhub\modules\user\models\Profilehumhub\modules\user\models\GroupUserArray
(
    [group_id] => Array
        (
            [0] => Group ID darf nicht leer sein.
        )

)
```

**Comment by luke-** [comment]
Thank you - just had this problem :-)
