### ISSUE TITLE
Error INTL, EXIF, FILEINFO WITH PHP 5.6

### ISSUE THREAD

**Issue by hederzapatero** [humhub/humhub#1676]
![phpx](https://cloud.githubusercontent.com/assets/10874945/14873017/3d93847a-0cc8-11e6-9509-2004909d5c36.jpg)

**Comment by buddha87** [comment]
Have you installed/enabled these packages ?

**Comment by hederzapatero** [comment]
Yes I have enabled, and the service assured me that are enabled. I have only these tools to do something in cpanel, is there any possibility to install around here?
![yes](https://cloud.githubusercontent.com/assets/10874945/14933000/82607fe6-0e57-11e6-8daa-86947bfe66ea.jpg)
