### ISSUE TITLE
500 Server Error on Notifications when originating_user_id is a deleted user

### ISSUE THREAD

**Issue by LMCv3** [humhub/humhub#1677]
When a notification from a deleted user is present, the notifications dropdown doesn't load any notifications, and the AJAX call throws a 500 internal server error.

Steps to reproduce:
1. Create 2 users (for this purpose, we'll call them Users A and B)
2. User A - invite user B to space
3. User B - accept invite to space
4. Delete user B
5. User A - click notifications bell, observe 500 error in console

If you delete the row in the notifications table that refers to the (now deleted) User B, notifications will begin to work for User A again. 

A suggested solution would be to delete all notifications that match originating_user_id of the user to be deleted upon deleting a user.

Currently Installed HumHub version: 1.0.0
PHP 5.6.20-0+deb8u1
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64)

**Comment by buddha87** [comment]
Please check under Administration->Logging if there is a more detailed error stack.

**Comment by LMCv3** [comment]
Here's the exception:
exception 'yii\base\ErrorException' with message 'Trying to get property of non-object' in /var/www/protected/humhub/modules/space/notifications/views/inviteDeclined.php:6 Stack trace: #0 /var/www/protected/humhub/modules/space/notifications/views/inviteDeclined.php(6): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/protec...', 6, Array) #1 /var/www/protected/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/protec...') #2 /var/www/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/protec...', Array) #3 /var/www/protected/humhub/modules/notification/components/BaseNotification.php(128): yii\base\View->renderFile('/var/www/protec...', Array, Object(humhub\modules\space\notifications\InviteDeclined)) #4 /var/www/protected/humhub/modules/notification/controllers/ListController.php(60): humhub\modules\notification\components\BaseNotification->render() #5 [internal function]: humhub\modules\notification\controllers\ListController->actionIndex() #6 /var/www/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #7 /var/www/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #8 /var/www/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('index', Array) #9 /var/www/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('notification/li...', Array) #10 /var/www/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 /var/www/index.php(25): yii\base\Application->run() #12 {main}

**Comment by luke-** [comment]
Hmm, can't reproduce this...

How do you delete the user?

Here is the code which (should) removes old notifications:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/notification/Events.php#L32-L34

**Comment by buddha87** [comment]
Same error was mentioned in the community, seems not to be a single case.

**Comment by LMCv3** [comment]
We deleted the user from the Admin -> Users screen by hitting the "X" button.

This happened a few times in a row, while setting up and deleting test users for a site.
