### ISSUE TITLE
Database Exception Error on New Install (v1.1-dev)

### ISSUE THREAD

**Issue by wmfleming** [humhub/humhub#1679]
Currently working on getting oAuth setup on v1.1-dev.  After downloading the branch, running composer update, I am able to go through the new install setup.  After setup completion, I log in for the first time using the admin account and get the following DB error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.user_id' in 'where clause'
The SQL being executed was: SELECT *, (SELECT count(*) FROM `like` WHERE like.created_by=user.id) as count_likes, (SELECT count(*) FROM `comment` WHERE comment.created_by=user.id) as count_comments, (SELECT count(*) FROM `content` WHERE content.user_id=user.id AND content.object_model='humhub\\modules\\post\\models\\Post') as count_posts FROM `user` ORDER BY (SELECT count(*) FROM `like` WHERE like.created_by=user.id)+(SELECT count(*) FROM `comment` WHERE comment.created_by=user.id)+(SELECT count(*) FROM `content` WHERE content.user_id=user.id AND content.object_model='humhub\\modules\\post\\models\\Post') DESC LIMIT 5
Error Info: Array
```
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'content.user_id' in 'where clause'
)
```
↵
Caused by: PDOException

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.user_id' in 'where clause'

in /var/www/socialicious/public_html/protected/vendor/yiisoft/yii2/db/Command.php at line 900

I have tried this on two different webservers and databases.  If I switch to the v1.2-dev branch the problem goes away however there are other issues when trying to use oAuth.

**Comment by buddha87** [comment]
Hmm could not recreate this issue. Does the error occure right after the login ? Did you select the create dummy data option of the installer ?

**Comment by cebe** [comment]
@wmfleming have you run database migrations?
