### ISSUE TITLE
No error message when PHP max. upload size reached

### ISSUE THREAD

**Issue by gfriloux** [humhub/humhub#168]
When trying to change avatar from the "my profile" page, using an android phone (using chrome web browser), we can select a new image to upload, we can see the upload to progress, but once over, the image doesnt change.

Works well under linux and chromium.

EDIT : Nothing to do with that, my sister told me her avatar is over 2MB while my php.ini is set to 2MB. An error message or something should be shown.

**Comment by luke-** [comment]
Seems that CSRF validation fails before we can check this.
Not sure how to handle this atm.

**Comment by jahd2602** [comment]
I solved increasing the "Maximum HTTP POST size" configuration inside php.ini (from 8 m to 50 m). It seems that if the file is bigger, it will get cut by PHP and the CSRF validation will fail.

There should be a way to overcome that situation. If humhub have a 4 mb limit, and php have a 8 mb limit, uploading a 6 mb limit will produce a nice humhub error message, but uploading a 10 mb will break Yii's CSRF and humhub will start to misbehave.
