### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1680]
http://translate.humhub.org/index.php?r=notes%2Fnote%2Fopen&id=2&sguid=1d601225-6793-4e4f-9a6b-5e4bda0d4f97
![screenshot_20160501-171022](https://cloud.githubusercontent.com/assets/7725575/14942254/bda142b6-0fbf-11e6-8c96-dd9819ca2f01.png)

**Comment by luke-** [comment]
Please reopen this ticket at: github.com/humhub/humhub-modules-notes
