### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1681]
The translation file is missing  (TR) 
-> Add space
![screenshot_20160501-171519 01](https://cloud.githubusercontent.com/assets/7725575/14942284/ca8a2ef6-0fc0-11e6-874a-8b65a90ed328.png)

**Comment by luke-** [comment]
You can translate it here:
http://translate.humhub.org/index.php?r=translation%2Ftranslate&moduleId=space&language=tr&file=picker
