### ISSUE TITLE
Edit User Profiles from User Approval Page

### ISSUE THREAD

**Issue by hfortune** [humhub/humhub#1683]
I'd like to be able to update a user's group and review their account prior to approving them (or as I am approving them). 

I notice that you can directly edit a user profile from the "User List" in Admin, but cannot do this from the User Approval list -- is there a reason for that? Can an edit profile button be added on the User Approval index?

Being able to easily review and edit a user as an administrator would be fantastic. Being able to automatically update the group a user is in as they are approved would be phenomenal!

Thanks,
Heather

**Comment by buddha87** [comment]
Hi the problem here is, that not only system admins are allowed to approve users and group managers (who are able to approve users) are not allowed to edit user profiles. But you are right this could be added to the admin view at least.

**Comment by hfortune** [comment]
I think being able to easily edit the user from the user approval list would allow administrators to change anything (like their group for example) that may need changing.

Right now, there isn't a profile for a non-approved user, so other than the first and last name, the administrator doesn't really have much to go on to "approve" the member. Allowing admins to see the user profile prior to approval, or edit the profile from the user approval screen (which allows them to see all of the profile information on one page), gives them more information to make an informed decision on whether to allow the applicant access or not.

Thank you for considering this enhancement!
