### ISSUE TITLE
Incorrect time of post or comment (Posted just now , but it says 11 hours ago)

### ISSUE THREAD

**Issue by abutuffah** [humhub/humhub#1686]
I have changed all the timezone and date.timezone either in the code and in my server. but still the time is wrong, any idea why?

It miss one hour, the post time is 2 May 2016 - 13.04, in fact it should be 2 May 2016 - 12.04.

I've checked my servers time zone and it's correct, really stuck on this :(

**Comment by andreevicctor** [comment]
how did you fix it?
