### ISSUE TITLE
Modules > Birthday

### ISSUE THREAD

**Issue by ygrosyeux** [humhub/humhub#1688]
Hello, there is a bug with the birthday module for bisextiles years ( like this year , for example). 

Until the anniversary day, no problem, it is displayed in the widget. But the day of the anniversary (and therefore when it is interesting to like it :-) ), the profile no longer appears. 

It seems to be related to the number of days of February that causes a shift .

Yann

**Comment by buddha87** [comment]
Hi, thanks for noticing could you please open a ticket in the module repository https://github.com/humhub/humhub-modules-birthday

**Comment by ygrosyeux** [comment]
Done ☺

Cordialement,

Yann

[SignatureYGR-VP]
[cid:image006.jpg@01D1AB9F.E58FC790]<http://www.divalto.com/event/divaltotour2016/?utm_source=EMATDFPart>


De : buddha87 [mailto:notifications@github.com]
Envoyé : mardi 17 mai 2016 16:39
À : humhub/humhub <humhub@noreply.github.com>
Cc : Yann GROSYEUX <ygrosyeux@variopositif.fr>; Author <author@noreply.github.com>
Objet : Re: [humhub/humhub] Modules > Birthday (#1688)


Hi, thanks for noticing could you please open a ticket in the module repository https://github.com/humhub/humhub-modules-birthday
