### ISSUE TITLE
missing method

### ISSUE THREAD

**Issue by atiyehk** [humhub/humhub#1689]
go to Directory->User profile posts, click in the "what's on your mind" box and hit submit, you get the following error ->

"Calling unknown method: humhub\modules\content\models\Content::getFirstWallEntryId()"

**Comment by buddha87** [comment]
Hi, which version are you using, I could not reproduce this in v1.0 and v1.1 ?

**Comment by atiyehk** [comment]
My Apologies. I am actively pulling and monitoring v1.2-dev and the issue was in that branch.

**Comment by buddha87** [comment]
No, problem we have to test these branches too, thanks for noticing :)
