### ISSUE TITLE
Allow custom slug for groups

### ISSUE THREAD

**Issue by TheZoker** [humhub/humhub#1692]
Hi there,

Humhub is awesome, but I don't like the urls of the spaces.

For the users it's great `/u/[username]`

Why don't you let space creators set a custom slug for their space, so the url will be like `/s/[spacename]`?

Because a url like `4eef98f5-ef47-41ea-b96c-cee48ac08dab` is neither comfortable to remember, nor beautiful.

**Comment by buddha87** [comment]
Will be part von v1.1
