### ISSUE TITLE
Error when updating 1.0 to 1.0.1

### ISSUE THREAD

**Issue by Censtudios** [humhub/humhub#1705]
This never happened to me before. I have been updating humhub through the updater since 0.2

I can retrieve the installation file, it then shows the changelog, but when I click proceed installation I see an error page. In the log I see this

`exception 'yii\base\ErrorException' with message 'Call to undefined method Yii::log()' in /home/riftside/domains/mydomain/public_html/protected/modules/updater/libs/UpdatePackage.php:273 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}`

Line 272-274:
`        if (@copy($source, $target) == false) {  `
`            Yii::log("InstallFile - Could not copy to: " . $target, CLogger::LEVEL_ERROR);  `
`            return false;`

**Comment by buddha87** [comment]
The exception is a bit misleading. The real problem seems to be a filesystem permission issue. Please check the write permission of the folders mentioned in the installation guide:

https://www.humhub.org/docs/guide-admin-installation.html#file-modes-permissions

**Comment by Censtudios** [comment]
All the files and folders listed there are CHMOD 755

**Comment by Censtudios** [comment]
The files/folders listed there were CHMOD 755, but even after changing it to 777 the error occurs.

**Comment by Censtudios** [comment]
Any update on this matter?

**Comment by luke-** [comment]
I've fixed the bug in the updater module - now errors should be logged correctly.
https://github.com/humhub/humhub-modules-updater/commit/c25ab430d5cb722ff619a0b57068f37c61fb3145

Can you plase try it again?
If there are now any errors in log - can you pleae create a new ticket for that?
