### ISSUE TITLE
[bug] Cant delete wiki page

### ISSUE THREAD

**Issue by devcline** [humhub/humhub#1709]
ERROR  Wed, 11 May 2016 16:04:31 +0200  yii\web\HttpException:400

`exception 'yii\web\HttpException' with message 'Access denied!' in /home/user/public_html/user/lab/protected/modules/wiki/controllers/PageController.php:194 Stack trace: #0 [internal function]: humhub\modules\wiki\controllers\PageController->actionDelete() #1 /home/user/public_html/user/lab/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #2 /home/user/public_html/user/lab/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #3 /home/user/public_html/user/lab/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('delete', Array) #4 /home/user/public_html/user/lab/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('wiki/page/delet...', Array) #5 /home/user/public_html/user/lab/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /home/user/public_html/user/lab/index.php(25): yii\base\Application->run() #7 {main}
`

Latest version , after update

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-wiki/issues/43
