### ISSUE TITLE
"internal error" (Spaces > Settings > Members)

### ISSUE THREAD

**Issue by ursina** [humhub/humhub#1715]
I can't access the menu item "members" in the spaces I have created myself. When I click (in a space I have created) on "Settings" and then "members" an error page appeares ("internal error").

**Comment by buddha87** [comment]
Please check the logs under "Administration->Logging"

**Comment by vladanPro** [comment]
I can't see settings for spaces members, i just see what is on picture, hot to access and remove from space?
![screen shot 2016-05-23 at 2 23 46 pm](https://cloud.githubusercontent.com/assets/1330505/15470646/06f3173a-20f2-11e6-8e0b-e0ceda43a3b5.png)

**Comment by buddha87** [comment]
The space menu is accessible here:

![spacemember](https://cloud.githubusercontent.com/assets/9800854/15479961/2fdd3c44-2123-11e6-85a0-7920c737eb02.jpg)

**Comment by vladanPro** [comment]
Ok tnx, is this also in 0.20.1 bcs we remove header in our site.
