### ISSUE TITLE
composer install

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1716]
How to install composer performed , respectively. 
Can you help me

**Comment by dakur** [comment]
Just read through this: https://getcomposer.org/doc/00-intro.md

**Comment by cagatayldzz** [comment]
ide.c9.io it gives error.
![111](https://cloud.githubusercontent.com/assets/7725575/15282570/e1efa5de-1b4c-11e6-98d3-3b55fddf9a2b.PNG)

**Comment by cagatayldzz** [comment]
I got it.

- sudo apt-get update
- sudo apt-get install curl libcurl3 libcurl3-dev php5-curl php5-ldap php5-cli php5-intl
- sudo service apache2 restart
- sudo service php5-fpm restart

installation and you need to make updates.
