### ISSUE TITLE
Include Mailing-email-adress field on installation and test-email function

### ISSUE THREAD

**Issue by programmieraffe** [humhub/humhub#1719]
Hey,

quick enhancement:

I just setup a new humhub installation. Users couldn't sign it at first, because the email-adress for outgoing mails in mailing administration was set to a default one. So my hosting provider blocked those emails.

Maybe other users will struggle as well with this. 

Also a quick "send test email" with the provided settings would be really helpful.

Best regards and thanks for the good work,
Matthias

**Comment by buddh4** [comment]
Test mail will be part of v1.5 the mail configuration is mentioned in [setup guide](https://docs.humhub.org/docs/admin/installation#e-mails).
