### ISSUE TITLE
Make profiles, spaces, and posts accessible to not logged in users

### ISSUE THREAD

**Issue by andystrobel** [humhub/humhub#172]

**Comment by globeFrEak** [comment]
+1

**Comment by programguy** [comment]
+1
This is great, as long as it can be turned off.

**Comment by kkayacan** [comment]
+1

**Comment by secondtruth** [comment]
+1

**Comment by simon-roderus** [comment]
+1 but should be optional

**Comment by andystrobel** [comment]
Hi Simon... it is already optional!

**Comment by mrluisiko99** [comment]
It should be an option to make user profiles and their posts accesible by non-logged users but keeping the rest of the network private (without access to home, pages...); and only a button to login or register.  If you are not logged, you view the login page (as now when is private) without posts, etc.
