### ISSUE TITLE
Multiple errors: Can't find content container 

### ISSUE THREAD

**Issue by programmieraffe** [humhub/humhub#1720]
I just did a fresh installation on an hosteurope webserver webspace (PHP 5.6., HTTPS, subdirectory of a domain https://<DOMAIN>.de/hub/) and I get a lot of the following errors when I try to navigate to spaces:

`exception 'yii\web\HttpException' with message 'Kann Content Container nicht finden.' in /is/htdocs/secret-path-to-hub-replaced/hub/protected/humhub/modules/content/components/ContentContainerController.php:89 Stack trace: #0 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\modules\content\components\ContentContainerController->init() #1 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/base/Controller.php(84): yii\base\Object->__construct(Array) #2 [internal function]: yii\base\Controller->__construct('module', Object(humhub\modules\space\modules\manage\Module), Array) #3 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/di/Container.php(368): ReflectionClass->newInstanceArgs(Array) #4 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/di/Container.php(153): yii\di\Container->build('humhub\\modules\\...', Array, Array) #5 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/BaseYii.php(340): yii\di\Container->get('humhub\\modules\\...', Array) #6 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/base/Module.php(567): yii\BaseYii::createObject('humhub\\modules\\...', Array) #7 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/base/Module.php(520): yii\base\Module->createControllerByID('module') #8 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/base/Module.php(512): yii\base\Module->createController('module/enable') #9 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/base/Module.php(512): yii\base\Module->createController('manage/module/e...') #10 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/base/Module.php(448): yii\base\Module->createController('space/manage/mo...') #11 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('space/manage/mo...', Array) #12 /is/htdocs/secret-path-to-hub-replaced/hub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /is/htdocs/secret-path-to-hub-replaced/hub/index.php(25): yii\base\Application->run() #14 {main} `

How can I debug this?

Best regards,
Matthias

**Comment by luke-** [comment]
Does this problem always exists when you try to access a space?

**Comment by Lugat** [comment]
Got the same error. Check the requested URL in firebug for example. Maybe you can see that the args seperator &amp; causes the error. If this happens, just do the following in your index.php:

`ini_set('arg_separator.output', '&');`

or the php.ini

arg_separator.output = "&"

**Comment by programmieraffe** [comment]
Thanks @Lugat, that solved the problem!

In the request url were indeed wrong encoded separators: Request URL:<mypage>/index.php?r=space%2Fspace%2Fstream&limit=10&amp;from=&amp;mode=activity&amp;sguid=6e00b654-a77c-456b-824e-6277a5ad2447

ini_get returns "&amp;" for default value of arg_separator.output 

(@luke- yes, always.)
