### ISSUE TITLE
IntlException: Constructor failed [HumHub 1.0.1]

### ISSUE THREAD

**Issue by KitsuneSolar** [humhub/humhub#1725]
1. User profile > Language > select "Russian" > Save
2. Go to AdminCP, error:

![screenshot-2016-05-18-01-04-45](https://cloud.githubusercontent.com/assets/12877339/15340916/9d1471ee-1c94-11e6-9b3d-524cffa95811.png)

1. User profile > Language > select "English" > Save
2. Go to AdminCP... NO error! :)

**Comment by KitsuneSolar** [comment]
1. User profile > Language > select "Russian" > Save
2. Go to Search page, error:

![screenshot-2016-05-18-03-02-23](https://cloud.githubusercontent.com/assets/12877339/15343404/05e57d66-1ca5-11e6-923e-d2ad4212b10e.png)

1. User profile > Language > select "English" > Save
2. Go to Search page... NO error! :)

**Comment by KitsuneSolar** [comment]
Fix:

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/messages/ru/picker.php#L3

Find:

```
'Add {n,plural,=1{space} other{spaces}}' => 'Добавить {n,plural,=1{space} другие{spaces}}',
```

Change to:

```
'Add {n,plural,=1{space} other{spaces}}' => 'Добавить {n,plural,=1{space} other{spaces}}',
```

This is the correct behavior?

**Comment by cebe** [comment]
what is your php version?

**Comment by cebe** [comment]
may be related to https://github.com/yiisoft/yii2/issues/11528 if it is PHP 7

**Comment by KitsuneSolar** [comment]
> what is your php version?

PHP 7

> may be related to yiisoft/yii2#11528 if it is PHP 7

is very similar!

**Comment by cebe** [comment]
a fix will be shipped with Yii 2.0.9, which will be released soon, so this can be closed.  yiisoft/yii2#11528

**Comment by wartur** [comment]
I see this problem too.
thanks for fix!

**Comment by cebe** [comment]
[yii 2.0.9 is released](http://www.yiiframework.com/news/102/yii-2-0-9-is-released/), so a simple `composer update yiisoft/yii2` should fix it.
