### ISSUE TITLE
Invalid method!

### ISSUE THREAD

**Issue by KitsuneSolar** [humhub/humhub#1731]
Follow user, example:
https://community.humhub.com/u/andreas+strobel/user/profile/follow

Blank page with:

> Invalid method!

**Comment by luke-** [comment]
You cannot use this link directly.

Is there also a problem when you click the follow link on the profile?

**Comment by KitsuneSolar** [comment]
> Is there also a problem when you click the follow link on the profile?
Yes. Links do not work. On my test site and community site.

**Comment by luke-** [comment]
Maybe you have cookies disabled?

**Comment by KitsuneSolar** [comment]
> Maybe you have cookies disabled?

Nop...
I found error! uBlock in Chrome & Firefox.
But unBlock used by many users!

![screenshot from 2016-05-18 17-28-26](https://cloud.githubusercontent.com/assets/12877339/15362563/43f6e5c6-1d1e-11e6-80be-07ad5540a92b.png)

**Comment by buddha87** [comment]
Hi could you try to check why its logged https://github.com/gorhill/uBlock/wiki/The-logger . It's does not block anything on my firefox.

**Comment by KitsuneSolar** [comment]
![screenshot from 2016-05-18 20-47-33](https://cloud.githubusercontent.com/assets/12877339/15369123/eb6ae47c-1d39-11e6-8508-e161674edeab.png)

**Comment by buddha87** [comment]
I think this dependency will be removed in v1.2 anyways
