### ISSUE TITLE
Internal server error after update to 1.0.1

### ISSUE THREAD

**Issue by manoyanx** [humhub/humhub#1734]
After the update, i got an internal server error.

And here is the log if it helps :

`exception 'yii\base\Exception' with message 'Could not get contents underlying object!' in C:\wamp\www\jinisys\protected\humhub\modules\content\components\actions\Stream.php:249 Stack trace: #0 [internal function]: humhub\modules\content\components\actions\Stream->run() #1 C:\wamp\www\jinisys\protected\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array) #2 C:\wamp\www\jinisys\protected\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\Action->runWithParams(Array) #3 C:\wamp\www\jinisys\protected\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction('stream', Array) #4 C:\wamp\www\jinisys\protected\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('dashboard/dashb...', Array) #5 C:\wamp\www\jinisys\protected\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 C:\wamp\www\jinisys\index.php(25): yii\base\Application->run() #7 {main}`

**Comment by luke-** [comment]
Which additional modules are you using?
Did you upgraded via Updater Module?

From which version did you upgrade?

**Comment by neighlyd** [comment]
Hello,

I am receiving the same "internal server error" message.

I was using the poll, mail, dropbox, and files modules. I also had freichat running overtop of that.

I used the Updater Module to update.

I was upgrading from version 1.0.0.

**Comment by frey1esm** [comment]
I just received this error when upgrading to 1.2 beta

`Could not get contents underlying object!`

**Comment by eddiepiazza** [comment]
I have same error, please may you explain me how you identified the orphaned content to delete it also?

Thanks

**Comment by frey1esm** [comment]
In the database I saw entries in the `content` table where `object_model` = 'Activity' and there was no matching record in the `activity` table (`content.object_id` => `activity.id`) so I just deleted them.
