### ISSUE TITLE
Search for < 3 characters keyword finds everything

### ISSUE THREAD

**Issue by cebe** [humhub/humhub#1737]
if you want to prevent searching on small terms it should at least match nothing and show a message to the user.
Current behavior is to match everything, which is confusing as regardless for what I am searching, the result is the same. Also this behavior is problematic when searching for users, e.g. names like "Xin Li".

A search for Xin Lee will find only the one user, a search for Xin Li will find both. This is inconsistent.

I suggest to change it in the following way:

Allow 2 or more characters here, instead of >2:
https://github.com/humhub/humhub/blob/dd388cb3365633b8b4cdb493a2e9af42d457e24c/protected/humhub/modules/search/engine/ZendLuceneSearch.php#L145-L146

Return an empty result on search for a single character, i.e. empty query condition.

**Comment by luke-** [comment]
What about this solution?

**Comment by cebe** [comment]
wow, you are fast :) I just implemented it like this (buildQuery only):

```diff
diff --git a/protected/humhub/modules/search/engine/ZendLuceneSearch.php b/protected/humhub/modules/search/engine/ZendLuceneSearch.php
index 6792664..21a96f1 100644
--- a/protected/humhub/modules/search/engine/ZendLuceneSearch.php
+++ b/protected/humhub/modules/search/engine/ZendLuceneSearch.php
@@ -141,14 +141,21 @@ class ZendLuceneSearch extends Search
         \ZendSearch\Lucene\Search\Query\Wildcard::setMinPrefixLength(0);
 
         $query = new \ZendSearch\Lucene\Search\Query\Boolean();
+        $emptyQuery = true;
         foreach (explode(" ", $keyword) as $k) {
-            // Require at least 3 non-wildcard characters
-            if (strlen($k) > 2) {
+            // Require at least 2 non-wildcard characters
+            if (mb_strlen($k, Yii::$app->charset) >= 2) {
                 $term = new \ZendSearch\Lucene\Index\Term("*" . $k . "*");
                 $query->addSubquery(new \ZendSearch\Lucene\Search\Query\Wildcard($term), true);
+                $emptyQuery = false;
             }
         }
 
+        // if no keywords or only too short keywords are given, the result is empty.
+        if ($emptyQuery) {
+            return new \ZendSearch\Lucene\Search\Query\EmptyResult();
+        }
+
         // Add model filter
         if (isset($options['model']) && $options['model'] != "") {
             if (is_array($options['model'])) {
```

**Comment by cebe** [comment]
I'll send a pull request for this.

**Comment by luke-** [comment]
Oh, I've overseen the EmptyResult class, but anyway I'm a little bit sure about this.

We're using the Zend Lucence Query Builder also to generate search queries for Solr.
The EmptyResult to string method, seems to generating an invalid lucence query.

```php
    public function __toString()
    {
        return '<EmptyQuery>';
    }
```

**Comment by cebe** [comment]
I've sent a PR fixing the things I mentioned but keeping the return null approach for empty result.

**Comment by luke-** [comment]
Ok prefect! Thank you!

**Comment by cebe** [comment]
Thank you for the fast response :)
