### ISSUE TITLE
yii\i18n\PhpMessageSource::loadMessages - (1.1.0-dev)

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1744]
The message file for category 'iso3166Codes' does not exist: /home/ubuntu/workspace/humhub-dev/protected/humhub/messages/tr/iso3166Codes.php

**Comment by cebe** [comment]
same happens for 'de' locale: 	"The message file for category 'iso3166Codes' does not exist: /home/cebe/dev/metadesign/social-metabms/humhub/protected/humhub/messages/de/iso3166Codes.php" on `/user/account/edit` page.

**Comment by cebe** [comment]
there should be no need for this data to be shipped in a class. all country names and translations are provided by the PHP `intl` extension.
