### ISSUE TITLE
How to create a custom module from scratch in HumHub

### ISSUE THREAD

**Issue by nadilhassan** [humhub/humhub#1749]
I was start to work with hum hub and i would like to create a new module , So how can i do this ?
Is there any other documentations or examples other than www.humhub.org/docs/guide-dev-module.html

**Comment by benmag** [comment]
I would love to see some improvement made to this. Creating my first few modules required a fair bit of trial and error just to get it showing up in the modules page. 

All the information required to make a module is there it's just it can take awhile on your first try. 

What if we built a module generator? So we could  start up a new module with a yiic command?

**Comment by buddha87** [comment]
A Gii module generator would be great, can't predict when we'll have the resources to implement this but hopefully soon.

**Comment by petersmithca** [comment]
I've started a tutorial here. tho haven't gotten very far, nor can I claim to understand everything.  http://showcase.thepetersmith.com/custom_pages/view?id=2  - note this is on my own little VPS, so not sure how much traffic it will support.  I have more written, just not added yet, will try to do that soon.

**Comment by benmag** [comment]
Just opened a pull request which implements a Humhub module generator via the Gii module generator. 

When you run it, it will spit out an automatically generated humhub module with your ID and namespaces correctly set so you don't have to spend time doing that yourself. 

The module itself is very basic. It just adds an admin only page + menu item and a public page + top menu  item. 

In the future it could be expanded it to have a template for a basic content container module to help demonstrate how that can be implemented.

**Comment by nadilaccura** [comment]
@benmag  Do you mean that attache the Gii Module to humhub application and then start generating modules from that Gii generator ? 
If that so can you please provide me the steps..

**Comment by benmag** [comment]
@nadilaccura I updated the [dev-module docs](https://github.com/benmag/humhub/blob/16f7ab625c5b678d9c0e880c82b44fce7f6056fc/protected/humhub/docs/guide/dev-module.md) as part of my PR, not sure if you saw that or not.

**Comment by nadilaccura** [comment]
@benmag When i was try to integrate yiigii module in humhub application it gives an Error

PHP Fatal Error – yii\base\ErrorException

Class 'HWebModule' not found

**Comment by benmag** [comment]
@nadilaccura I don't think the `HWebModule` class is in the current version of HumHub? What version are you on? I've tested this on v1.0.0 and v1.0.1

**Comment by nadilaccura** [comment]
@benmag  i am sorry the Error i get is 
ReflectionException

Class humhub\generators\module\Generator does not exist

I am using version: 1.0.1

**Comment by benmag** [comment]
@nadilaccura I've tested it on v1.0.1 and it works

- Do you have `"yiisoft/yii2-gii": "*",` in `require-dev` in your `composer.json`? 
- Have you run `composer update`?

**Comment by nadilaccura** [comment]
@benmag There is no composer.json file in my humhub project? How do i find it? composer.json files in Yii2 project but i could not find in humhub project

**Comment by benmag** [comment]
@nadilaccura I am assuming you've installed it via the Download Manager. If you're going to be doing any development stuff, I'd recommend following the steps to [install via Git/Composer](https://www.humhub.org/docs/guide-admin-installation.html#via-gitcomposer)

**Comment by nadilaccura** [comment]
@benmag  yes i did like you said.. let me install it via git and check Thank You1

**Comment by cuilster** [comment]
hi benmag, i get the same error. I've installed humhub via git/composer and updated it.
http://localhost/humhub/index.php?r=gii
anyone could help me please?

@nadilnadeem i think you already get this done, cause i sucsessfully installed your "News" module :-) Do you have a clue?

greetings c

**Comment by nadilnadeem** [comment]
Follow this, It should work
https://www.humhub.org/docs/guide-dev-index.html#enable-gii

Whats the error you getting

**Comment by cuilster** [comment]
same as you did. i already found the problem^^
the tutorial (with web.php code) from banmag refers to the customized humhub\generator
the original tutorial finally gets the gii generator to work...

still confusing cause i also installed the humhub\generator too...

thanks nadilnadeem

**Comment by primantok** [comment]
A few days ago I wrote a suggestion in HumHub community about module "boilerplate / template" especially for integration with 3rd party software. For advanced module, learning yii framework is a must because HumHub build with yii framework.

Here is part of my suggestion:
Create a module "boilerplate" with detailed help / instruction would help you to boost HumHub popularity & community contribution.
Etherpad Notes & Dropbox module is good starting point to create module for everyone that interested to make third party integration. Just clone those module, replace unnecessary code with "placeholder" & place inline help / docummentation line-by-line.
For detail please read here https://community.humhub.com/content/perma?id=69865.

If you the author of Etherpad Notes & Dropbox module, if posible, please make those module as template / boilerplate for everyone that interested in creating HumHub module but dont have yii experience like me.

Cheers

**Comment by benmag** [comment]
@primantok that was the point of my HumHub Module Generator PR #1751. It also has some extra documentation around how to use it.

@luke- is there any update on this?

**Comment by cuilster** [comment]
gii is useless for humhub. since there is no working humhub module generator you have to build modules the slow way.

**Comment by gustavolira** [comment]
Hi any news about this problem?
I'm still receiving `Class humhub\generators\module\Generator does not exist`

**Comment by buddh4** [comment]
We are working on the [devtools](https://github.com/humhub/humhub-modules-devtools), but I currently don't find the time to enhance it. This module has a very rudimentary GII module generator (this was not implemented by us). But we have to update this to v1.2 and add some further options. Any contribution is welcome.
