### ISSUE TITLE
Enh: Override Yii2's default \yii\web\User::loginRequired() to prevent 'Login Required' Exception...

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1750]
...as this is a common exception that is thrown when attempting to access a part of the site when a user is not logged in I am suggesting it redirects to a view that states as much, instead of the current default behavior of throwing an exception.

**Comment by Censtudios** [comment]
I have something very similar, if not the same. In the last 2 hours I have already 2000 entries in my error log being

`exception 'yii\web\ForbiddenHttpException' with message 'Login Required' in /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/web/User.php:446 Stack trace: #0 /home/riftside/domains/hub.riftside.net/public_html/protected/humhub/components/behaviors/AccessControl.php(62): yii\web\User->loginRequired() #1 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/base/ActionFilter.php(71): humhub\components\behaviors\AccessControl->beforeAction(Object(yii\base\InlineAction)) #2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent)) #3 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/base/Component.php(541): call_user_func(Array, Object(yii\base\ActionEvent)) #4 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(269): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent)) #5 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/web/Controller.php(108): yii\base\Controller->beforeAction(Object(yii\base\InlineAction)) #6 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(152): yii\web\Controller->beforeAction(Object(yii\base\InlineAction)) #7 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('get-update-json', Array) #8 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('notification/li...', Array) #9 /home/riftside/domains/hub.riftside.net/public_html/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /home/riftside/domains/hub.riftside.net/public_html/index.php(25): yii\base\Application->run() #11 {main}`

**Comment by luke-** [comment]
Is this still a problem?

**Comment by davidjeddy** [comment]
Unknown, been nearly two years. I vote to close this issue.
