### ISSUE TITLE
SQLSTATE[28000] [1045] Access denied for user, While uploading project to server

### ISSUE THREAD

**Issue by nadilnadeem** [humhub/humhub#1753]
HI
I am facing SQLSTATE[28000] [1045] Access denied for user exception When i uploaded the humhub project and confiugred my database details
Below are the details which i configured under  protected/config/dynamic file

mysql host,dbname,username,password
![error_sql_user](https://cloud.githubusercontent.com/assets/19547376/15564028/9362dd32-232b-11e6-896b-ea2e68682eba.png)

**Comment by nadilnadeem** [comment]
@benmag can you please help me in this?

**Comment by negoguy** [comment]
Can you provide some information about how you solved your problem. i'm in the same situation and some insight would be more than welcome!

**Comment by buddh4** [comment]
This means your uses mysql username/password are not correct. If you have further questions, please consider asking the [community](https://community.humhub.com)
