### ISSUE TITLE
DOCS: bad link

### ISSUE THREAD

**Issue by HankBrown** [humhub/humhub#1755]
This page:
https://www.humhub.org/docs/guide-admin-installation.html

says

> Note: The composer update may have to be executed again after an update of your local repository by a git pull. Read more about updating (Update Guide)

But that link (Update Guide) goes to

http://localhost/codebase/doku/guide-admin-updating.html#gitcomposer-based-installations

**Comment by nadilnadeem** [comment]
Here you go...
https://www.humhub.org/docs/guide-admin-updating.html#gitcomposer-based-installations

All the Very Best!
