### ISSUE TITLE
humhub\components\bootstrap\mb_internal_encoding()

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1756]
1.1.0-beta.1
"It gives an error in the installation"

![ekran alintisi](https://cloud.githubusercontent.com/assets/7725575/15699254/44f07490-27d4-11e6-8716-6501ed4188d0.PNG)
PHP Fatal error:  Call to undefined function humhub\components\bootstrap\mb_internal_encoding() in /home/-----/public_html/protected/humhub/components/bootstrap/LanguageSelector.php on line 23
Fatal error: Class 'PDO' not found in /home/----/public_html/humhub-1.1.0-beta.1/protected/vendor/yiisoft/yii2/db/Connection.php on line 631

![1](https://cloud.githubusercontent.com/assets/7725575/15709728/f0cc9002-280e-11e6-8b28-018df493bbdf.PNG)

**Comment by cebe** [comment]
please check if mbstring is really installed, using phpinfo(). the information is also available via yii debug toolbar.
