### ISSUE TITLE
humhub\modules\space\models\Setting::findAll()

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1758]
exception 'yii\base\ErrorException' with message 'Call to undefined method humhub\modules\space\models\Setting::findAll()' in /home/ubuntu/workspace/humhub-1.1.0-beta.1/protected/humhub/modules/space/models/Space.php:197 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}

**Comment by buddha87** [comment]
Please always add when the error occured if possible. I assume this happened when deleting a space, am I right ?

**Comment by cagatayldzz** [comment]
...../space/manage/default/delete
It gives an error when deleting.
![ekran alintisi](https://cloud.githubusercontent.com/assets/7725575/15709187/0e46535a-280c-11e6-96ea-8847d45d3b9a.PNG)

**Comment by eddiepiazza** [comment]
I have same issue, but I don t understand the [fix](https://github.com/humhub/humhub/commit/240416407b0510b48a27495d877f91bfd27054ba), I have exactly same code...

**Comment by buddha87** [comment]
@eddiepiazza this only occures in Version 1.1 (beta) with modules which were not merged to v1.1 yet.
Can you explain where this happens, or can you provide a full error stack (Administrator -> Information -> Logging) Perhaps you just have to update some of your modules.

**Comment by bennassie** [comment]
Same issue here. I have the same exact code as the fix above. Also tried update all modules before deleting the site. still getting the internal server error page.

**Comment by buddha87** [comment]
If the red lines in the fix are present in your version, you are not running the fixed version.
The fix is part of v1.1.beta2

**Comment by bennassie** [comment]
@buddha87  thanks. I updated to v1.1beta2 and i'm now able to delete sites without any errors.
