### ISSUE TITLE
Invalid Configuration – yii\base\InvalidConfigException

### ISSUE THREAD

**Issue by Spirantz** [humhub/humhub#1760]
Upgraded to the latest version via the automatic upgrader module. Now I get this error: 

``` Invalid Configuration – yii\base\InvalidConfigException
humhub\components\Request::cookieValidationKey must be configured with a secret key. ```

I for the life of me can't find out where I would need to se the cookieValidationKey

**Comment by luke-** [comment]
Did you used the latest version of the updater module?

You can fix this error by running the database migrations manually:

```
cd path/to/humhub/protected
php yii migrate/up --includeModuleMigrations=1
```

**Comment by Spirantz** [comment]
I did run the latest version of the updater module.

In addition, I ran the command you noted and received the following output:
``` Error Info:
Array
(
    [0] => 42S01
    [1] => 1050
    [2] => Table 'contentcontainer_setting' already exists
)

```

**Comment by Spirantz** [comment]
So I tried reverting to an old build of HumHub and now I get this error: 

```
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: humhub\modules\user\models\User::super_admin
```

**Comment by Spirantz** [comment]
So I found out if you put 
```
        'enableCookieValidation' => true,
        'enableCsrfValidation' => true,
        'cookieValidationKey' => 'xxxxxxx',
```
In web.php you can log in. However once logging you you get the following:

```
Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'group_key' in 'group statement'
The SQL being executed was: SELECT COUNT(*) FROM (SELECT `notification`.*, count(distinct(originator_user_id)) as group_count, max(created_at) as group_created_at, min(seen) as group_seen FROM `notification` WHERE ((`seen`=0) OR (`seen` IS NULL)) AND (`user_id`=4) GROUP BY COALESCE(group_key, id), `class` ORDER BY `group_seen`, `group_created_at` DESC) `c`

Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'group_key' in 'group statement'
)

↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'group_key' in 'group statement'

in /home2/frontwire/public_html/devpanel/protected/vendor/yiisoft/yii2/db/Command.php at line 900
```

**Comment by Spirantz** [comment]
After more investigation, it seems the migration was partially successful. What I did was

- Remove the database
- Restored a backup (PRE-migration attempt)
- Ran the migration via the console

This time there were no errors and I was able to log into HumHub. 

HOWEVER, after logging in I now receive:

```
Invalid Configuration – yii\base\InvalidConfigException
"humhub\modules\user\models\User" must have a primary key.

```

**Comment by buddha87** [comment]
We have some problems with the automatic updater, probably a php timeout issue. I don't think the primary key error was a update/migration problem. I rather think they got lost with the restored backup

**Comment by ValeSauer** [comment]
We got the very same error after updating humhub via git: https://github.com/humhub/humhub/issues/1760

For us it helped to delete all cache-files in /protected/runtime/cache/hu/* by
`
cd /var/www/humhub/protected/runtime/cache/hu/
sudo rm -r *`

**Comment by worldwildweb** [comment]
i do not have hu directory? cd /var/www/humhub/protected/runtime/cache/hu/ sudo rm -r *
