### ISSUE TITLE
Database Exception – yii\db\Exception (1.1.0-beta.1)

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1761]
![11](https://cloud.githubusercontent.com/assets/7725575/15738208/f083c3be-28b2-11e6-9d00-8af34fd4990d.PNG)

![2](https://cloud.githubusercontent.com/assets/7725575/15738244/1f1e1cd8-28b3-11e6-92f7-44b81320382c.PNG)
giving this error in the database setup phase

**Comment by NikhilDikshit** [comment]
Hi Cagatayldzz.

For the LDAP support, you need to apply some changes your php.ini file. Just open it, and look for 'LDAP'. And uncomment the LDAP extension. For, APC Support, you have to download a few libraries. Judt google it. And it will do!

Thanks.

**Comment by buddha87** [comment]
@NikhilDikshit I think this is not his problem. This happend within a migration I assume
