### ISSUE TITLE
Where should I put shoppingCart and PaymentGateway in humhub?

### ISSUE THREAD

**Issue by alirezastack** [humhub/humhub#177]
I want to code the shopping cart module and a payment gateway to Humhub. Where should I put my code? Should I put it in modules_core or module or somewhere else? thanks

**Comment by 50euros** [comment]
Hi @zoodroom, did you successfully implement a payment gateway for HumHub? 
We need one, but I'd like to avoid reinventing the wheel. 

Thanks 
Ian
