### ISSUE TITLE
Users can't login after 1.1.0 update

### ISSUE THREAD

**Issue by Censtudios** [humhub/humhub#1770]
Title says it all. No errors, nothing, the login just acts as if the password was incorrect, but that's not the case at all. Registration does submit (it says the email is sent), though I can't check yet if the emails are indeed sent and being received.

EDIT: Users that are already logged in can go to account settings, connect to facebook and that will allow them to login through facebook, but the regular login doesn't work. So if they aren't logged in yet they can't connect to facebook obviously.

**Comment by Censtudios** [comment]
This is a huge issue. I have tried to look where it can lie, but I can't figure it out.

Members can't login at all, unless they have previously connected their facebook account (which nobody has obviously because it started in the 1.1 update)

**Comment by Censtudios** [comment]
New information:

I tried to use the login through the API (luckily I had that module installed so I can test it) and the failed login there does in fact create an entry in the errorlogs. It's as followed:

`exception 'yii\base\ErrorException' with message 'Undefined class constant 'AUTH_MODE_LOCAL'' in /home/user/domains/url/public_html/protected/humhub/modules/user/models/forms/AccountLogin.php:51 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}`

I think it's the cause of why the normal login doesn't work either. Just because it's through a seperate module this time it actually creates an errorlog

**Comment by Censtudios** [comment]
Update:

The issue still exists, but I found that if you have this API module installed https://github.com/petersmithca/humhub-api you can use it to login.

So as a temporary solution I'm currently working on a seperate login and login_modal that will use that API to login

**Comment by luke-** [comment]
Can you please add this issue to the humhub-api repo?

**Comment by Censtudios** [comment]
But this issue is not happening because of the API. I managed to bypass the issue thanks to the API.

If not for making my own login form using the API, users would still not be able to login after the 1.1.0 update

**Comment by ideadel** [comment]
same problem, only with ldap users.
