### ISSUE TITLE
login (#globalModal) won't open - v1.2-dev

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#1773]
![ekran alintisi](https://cloud.githubusercontent.com/assets/7725575/15799606/ba9c0400-2a6a-11e6-891b-ce8bd59d3d69.PNG)
infinite loop in

**Comment by buddha87** [comment]
v1.2 is in a rather early state, we migrated from 1.1 recently, this is probably causing the problem.

**Comment by cagatayldzz** [comment]
Only 1.2 installed from scratch . Update from version 1.1 did not

**Comment by luke-** [comment]
Please do not open bugs related to development branch.
It's totally work in progress...

**Comment by eddiepiazza** [comment]
it wasn't supposed to be released this month? I am so anxious!!!!! Every day I am checking for this new update. News please!
