### ISSUE TITLE
Support SQL_Mode: ONLY_FULL_GROUP_BY

### ISSUE THREAD

**Issue by nejcneo** [humhub/humhub#1777]
https://i.snag.gy/YHwF3c.jpg
That is what i got after installing In Requirements I got only 2 alerts both are yellow type.
After that I go all trough and after login I hit this error.
![image](https://cloud.githubusercontent.com/assets/1667825/15820229/6b9a7286-2be8-11e6-90a7-bf31332dddcf.png)

**Comment by luke-** [comment]
You need to turn off the sql_mode ONLY_FULL_GROUP_BY. At the moment HumHub doesn't support this mode.

**Comment by michaelgeisler** [comment]
how to turn off this mode?

**Comment by buddha87** [comment]
Set the follwoing value in your my.ini:

`sql_mode=TRADITIONAL`
