### ISSUE TITLE
Space.php calls undefined method on Setting (findAll)

### ISSUE THREAD

**Issue by atiyehk** [humhub/humhub#1778]
in /Users/calatiyeh/Sites/xsports/protected/humhub/modules/space/models/Space.php at line 197
188189190191192193194195196197198199200201202203204205206

 
        return parent::beforeSave($insert);
    }
 
    /**
     * @inheritdoc
     */
    public function beforeDelete()
    {
        foreach (Setting::findAll(['space_id' => $this->id]) as $spaceSetting) {
            $spaceSetting->delete();
        }
 
        foreach ($this->getAvailableModules() as $moduleId => $module) {
            if ($this->isModuleEnabled($moduleId)) {
                $this->disableModule

**Comment by buddha87** [comment]
Hi, this is already fixed an will be part in the stable (or next beta)
