### ISSUE TITLE
How to change the author of the post to another person in a Module

### ISSUE THREAD

**Issue by nadilhassan** [humhub/humhub#1780]
In my module , users are able to post a message on space. but i want to change the author while posting the message, because one person will post messages on behalf of another person.
How can i do this?

**Comment by luke-** [comment]
You can switch the author with following code:

```php
$post->content->created_by = $anotherUser->id;
$post->content->save();
```

**Comment by nadilnadeem** [comment]
Am i need to set the content->created_by to the My Post Model or anything else?
and i would like to know, how to get a a user from the user list? then i can get the user id.

**Comment by luke-** [comment]
You need to set it in your content model.

What do you mean with get user from the user list?

**Comment by nadilnadeem** [comment]
I mean , If i type in a text field i want to get the relevant user and to assign the author is that particular user, So i am asking how to get the users while i am typing in textfield
