### ISSUE TITLE
Question/concern: All uploads going to single folder?

### ISSUE THREAD

**Issue by HankBrown** [humhub/humhub#1781]
Is this true, or have I not yet stumbled on a config option?
We have tens of thousands of user uploads.
Experience says that will create headaches under unix.
Too many files to list, copy, delete, browse, sync, whatever...

I want to expand upload folders to include a trie,
so that EG uploads from user with id 123 are stored at ./files/1/2/3/...

New to HH so asking before I dig. Thank you for any advice.

**Comment by luke-** [comment]
@HankBrown Unfortunately there is no folder nesting yet - but it's planned in 1.2
