### ISSUE TITLE
CronJob stop works after update to 1.1.0

### ISSUE THREAD

**Issue by nguyen-matthias** [humhub/humhub#1788]
I have this windows task: 
Start Programm: E:\xampp\php\php.exe 
Argument: E:\xampp\htdocs\protected/yii cron/hourly >/dev/null 2>&1

normaly it's work, but now after the update it's stop work and i get failures:

ERROR:
yii\base\ErrorException: Undefined index: scheme in E:\xampp\htdocs\protected\humhub\components\console\Application.php:44
Stack trace:
#0 E:\xampp\htdocs\protected\humhub\components\console\Application.php(44): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 44, Array)
#1 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Object.php(107): humhub\components\console\Application->init()
#2 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Application.php(206): yii\base\Object->__construct(Array)
#3 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\console\Application.php(85): yii\base\Application->__construct(Array)
#4 E:\xampp\htdocs\protected\yii(28): yii\console\Application->__construct(Array)
#5 {main}

Information:
$_SERVER = [
    'ALLUSERSPROFILE' => 'C:\\ProgramData'
    'APPDATA' => 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Roaming'
    'CommonProgramFiles' => 'C:\\Program Files (x86)\\Common Files'
    'CommonProgramFiles(x86)' => 'C:\\Program Files (x86)\\Common Files'
    'CommonProgramW6432' => 'C:\\Program Files\\Common Files'
    'COMPUTERNAME' => 'SERVER34'
    'ComSpec' => 'C:\\Windows\\system32\\cmd.exe'
    'DEFLOGDIR' => 'C:\\ProgramData\\McAfee\\DesktopProtection'
    'FP_NO_HOST_CHECK' => 'NO'
    'LOCALAPPDATA' => 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local'
    'NUMBER_OF_PROCESSORS' => '4'
    'OS' => 'Windows_NT'
    'Path' => 'C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;'
    'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC'
    'PROCESSOR_ARCHITECTURE' => 'x86'
    'PROCESSOR_ARCHITEW6432' => 'AMD64'
    'PROCESSOR_IDENTIFIER' => 'Intel64 Family 6 Model 37 Stepping 1, GenuineIntel'
    'PROCESSOR_LEVEL' => '6'
    'PROCESSOR_REVISION' => '2501'
    'ProgramData' => 'C:\\ProgramData'
    'ProgramFiles' => 'C:\\Program Files (x86)'
    'ProgramFiles(x86)' => 'C:\\Program Files (x86)'
    'ProgramW6432' => 'C:\\Program Files'
    'PSModulePath' => 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\'
    'PUBLIC' => 'C:\\Users\\Public'
    'SystemDrive' => 'C:'
    'SystemRoot' => 'C:\\Windows'
    'TEMP' => 'C:\\Windows\\TEMP'
    'TMP' => 'C:\\Windows\\TEMP'
    'USERDOMAIN' => '<our Domainname>'
    'USERNAME' => 'SERVER34$'
    'USERPROFILE' => 'C:\\Windows\\system32\\config\\systemprofile'
    'VSEDEFLOGDIR' => 'C:\\ProgramData\\McAfee\\DesktopProtection'
    'windir' => 'C:\\Windows'
    'PHP_SELF' => 'E:\\xampp\\htdocs\\protected/yii'
    'SCRIPT_NAME' => 'E:\\xampp\\htdocs\\protected/yii'
    'SCRIPT_FILENAME' => 'E:\\xampp\\htdocs\\protected/yii'
    'PATH_TRANSLATED' => 'E:\\xampp\\htdocs\\protected/yii'
    'DOCUMENT_ROOT' => ''
    'REQUEST_TIME_FLOAT' => 1465453078.8747
    'REQUEST_TIME' => 1465453078
    'argv' => [
        0 => 'E:\\xampp\\htdocs\\protected/yii'
        1 => 'cron/hourly'
        2 => '>/dev/null'
        3 => '2>&1'
    ]
    'argc' => 4
]

**Comment by nguyen-matthias** [comment]
![humhubcronejob](https://cloud.githubusercontent.com/assets/16917852/16406777/700fa5aa-3d10-11e6-8b1c-94d4459fcf97.png)

Please, i need helps i don't now what i have to do :/

**Comment by cebe** [comment]
seems your `baseUrl` settings entry is broken, i.e. not a valid URL.

**Comment by cebe** [comment]
The error seems to occur here according to the stacktrace: https://github.com/humhub/humhub/blob/44812328fc78acae0e5dfb962734d92b7e86b612/protected/humhub/components/console/Application.php#L44

**Comment by cebe** [comment]
You should check for `baseUrl` entry in `protected/config/dynamic.php` and make sure it is an absolute URL.

**Comment by nguyen-matthias** [comment]
hmm this here ist my application.php contains:
`
/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) 2015 HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */

namespace humhub\components\console;

use Yii;
use humhub\models\Setting;

/**
 * Description of Application
 *
 * @author luke
 */
class Application extends \yii\console\Application
{

    /**
     * @event ActionEvent an event raised on init of application.
     */
    const EVENT_ON_INIT = 'onInit';

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();
        $this->trigger(self::EVENT_ON_INIT);

        if ($this->isDatabaseInstalled()) {
            $baseUrl = Setting::get('baseUrl');
            Yii::setAlias(("@web"), $baseUrl);
            $this->urlManager->scriptUrl = $baseUrl;
            $this->urlManager->baseUrl = $baseUrl;
        }
    }

    /**
     * Returns the configuration of the built-in commands.
     * @return array the configuration of the built-in commands.
     */
    public function coreCommands()
    {
        return [
            'help' => 'yii\console\controllers\HelpController',
            'cache' => 'yii\console\controllers\CacheController',
            'asset' => 'yii\console\controllers\AssetController',
            'fixture' => 'yii\console\controllers\FixtureController',
        ];
    }

    /**
     * Checks if database is installed
     * 
     * @return boolean is database installed/migrated
     */
    public function isDatabaseInstalled()
    {
        if (in_array('setting', Yii::$app->db->schema->getTableNames())) {
            return true;
        }
            
        return false;
    }

}
`

**Comment by nguyen-matthias** [comment]
an the baseURl begins with http://<url>.de

**Comment by nguyen-matthias** [comment]
hmmm... ok now i get this error :/
yii\base\ErrorException: Undefined index: email in E:\xampp\htdocs\protected\humhub\modules\user\authclient\ZendLdapClient.php:312
Stack trace:
#0 E:\xampp\htdocs\protected\humhub\modules\user\authclient\ZendLdapClient.php(312): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 312, Array)
#1 E:\xampp\htdocs\protected\humhub\modules\user\Events.php(138): humhub\modules\user\authclient\ZendLdapClient->syncUsers()
#2 [internal function]: humhub\modules\user\Events::onHourlyCron(Object(yii\base\Event))
#3 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Event.php(205): call_user_func(Array, Object(yii\base\Event))
#4 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Component.php(549): yii\base\Event::trigger('humhub\\commands...', 'hourly', Object(yii\base\Event))
#5 E:\xampp\htdocs\protected\humhub\commands\CronController.php(41): yii\base\Component->trigger('hourly')
#6 [internal function]: humhub\commands\CronController->actionHourly('>/dev/null', '2>&1')
#7 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#8 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('hourly', Array)
#10 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('hourly', Array)
#11 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\console\Application.php(176): yii\base\Module->runAction('cron/hourly', Array)
#12 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\console\Application.php(143): yii\console\Application->runAction('cron/hourly', Array)
#13 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 E:\xampp\htdocs\protected\yii(29): yii\base\Application->run()
#15 {main}

**Comment by buddha87** [comment]
Please create a new ticket for this issue, seems to be related with the creation of a ldap user.
