### ISSUE TITLE
Deleting a user does only partially remove their attendance state on calendar events

### ISSUE THREAD

**Issue by benedetto** [humhub/humhub#1793]
### Steps to reproduce:

1. Create a calendar event
2. Let a user choose any state (attend, maybe, do not attend) on this event.
3. Delete this user's account
4. In the numbers counting the three attendance states, the deleted user is still counted, i.e. the user count is wrong by one. If he was the only user in the respective state, clicking on the state to see the people within results in a "No users found" message. 

### Expected behaviour:
If a user is deleted, also the events where he has clicked a state about his attendance should be updated.

### Version info:
- Humhub: 1.0.1
- OS: CentOS 5.11
- PHP: 5.6.21
- Apache: 2.2.3
- MySQL 5.0.95

**Comment by buddha87** [comment]
I opened an issue on the calendars module repositry: https://github.com/humhub/humhub-modules-calendar/issues/38
