### ISSUE TITLE
Using 'Custom Pages' module, how to include JS to connect to nodejs socketio with the Username

### ISSUE THREAD

**Issue by ChStark** [humhub/humhub#1794]
Hi community, I want to include a chat inside a custom page, how can I retrieve or what is the "best way" to do that

**Comment by buddha87** [comment]
You could include your js dependencies in "/protected/humhub/views/layouts/head.php and simply copy your script in the content of your custom page. But if you really want to implement such a functionality I would rather suggest writing a module.
