### ISSUE TITLE
opengraph error for Login home page and share buttons

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#1802]
It´s difficult to show a site in Facebook when it´s presented without image and a description as "Error - Sitename". Logically, this info is being taken from login page.

I try by few methods to introduce opengraphs to Index.php but all was giving back frontpage errors.

Also, by sharing an entry is showing same issue using Social Share module.

You can check it: http://www.opengrow.es/community/

https://developers.facebook.com/tools/debug/sharing/?q=opengrow.es%2Fcommunity%2F

**Comment by eddiepiazza** [comment]
Maybe by remplace?

\protected\humhub\modules\user\views\layouts\main.php
\protected\humhub\views\layouts\main.php

18 <title><?php echo $this->pageTitle; ?></title>

By
		<title>Site title</title>
<meta property="og:title" content="Site name" />
<meta property="og:type" content="" />
<meta property="og:url" content="http://www.site.com" />
<meta property="og:image" content="http://site.es/logo.png" />

**Comment by buddha87** [comment]
you can add meta tags to /protected/humhub/views/layouts/head.php, but you are right would be great if this could be configured somewhere in the backend.
