### ISSUE TITLE
Error :: Settings :: Notifications => Change Setting for "Send Activities"...

### ISSUE THREAD

**Issue by gseilheimer** [humhub/humhub#1803]
error
the changed of the status of the daily summary (account settings -> settings -> notifications -> change send activities) will not be saved in the system.
=> if you go back in the menu and check this point again - the default of the system is active again (checked in the demo of community.humhub.org)

**Comment by buddha87** [comment]
Hi, thanks this was already fixed on master and will be part of the next release.
