### ISSUE TITLE
Latest activities... Where is the PRIVACY ?

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#1806]
Well, cool module for an admin and also nice for follow the activity os your friends but....

Why all users can see the activity of everyone ???
Why this module is not filtering information?

Well, this is the code of panel. Can someone give an idea for not totally disable it restrinct view for users? Or much better but this will need time and coding, make it filtering content only for subscribed spaces and friends?

```
<div class="panel panel-default panel-activities">

    <div
        class="panel-heading"><?php echo Yii::t('ActivityModule.widgets_views_activityStream', '<strong>Latest</strong> activities'); ?></div>
    <div id="activityStream">
        <div id="activityEmpty" style="display:none">
            <div
                class="placeholder"><?php echo Yii::t('ActivityModule.widgets_views_activityStream', 'There are no activities yet.'); ?></div>
        </div>
        <ul id="activityContents" class="media-list activities">
            <li id="activityLoader">
                <?php echo \humhub\widgets\LoaderWidget::widget(); ?>
            </li>
        </ul>

    </div>
</div>
```

Thank you ;)

**Comment by davidjeddy** [comment]
Filting content person A can see of person B would require a permissions system, ATM the only user who has any permissions different from a normal user is the admin. the dev team did tell me they do plan to add a access control layer to HumHub soon; an ACL system would facilitate the type of functionality you are describing. IIRC I think 1.1 has the beginnings of the ACL system.

**Comment by buddha87** [comment]
I added this to our wishlist, I think for some communities especially smaller ones the current logic is preferred. But this should be configurable.
