### ISSUE TITLE
Upgrading error

### ISSUE THREAD

**Issue by mdpmartin** [humhub/humhub#1810]
Today I was trying to upgrade my humhub installation, following the guidelines with git and composer. 
`git pull`
`composer update`
`cd protected
php yii migrate/up --includeModuleMigrations=1`

After that I deleted all my cache under /protected/cache/hu/\* and deactivate nginx sendfile=off.

Everythings looks great, but when I tried to login con my admin account everything was broken. Following the error logs from nginx I found this:

`2016/06/21 16:22:01 [error] 3178#3178: *37 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'humhub.notification.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php:900
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(900): PDOStatement->execute()
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(388): yii\db\Command->queryInternal('fetchColumn', 0)
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Query.php(398): yii\db\Command->queryScalar()
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(329): yii\db\Query->queryScalar('COUNT(*)', NULL)
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Query.php(300): yii\db\ActiveQuery->queryScalar('COUNT(*)', NULL)
#5 /var/www/humhub/protecte" while reading response header from upstream, client: 176.83.67.23, server: agora.daetsam.es, request: "GET /index.php?r=user%2Faccount%2Fedit HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "agora.daetsam.es", referrer: "https://agora.daetsam.es/index.php?r=admin%2Fuser"

`

**Ubuntu**: 16.04
**nginx**: 1.11.1
**mysql**: 5.7.12
**php**: 7.0.4

What I did wrong? How can I fix it?

Thank you very much for your amazing work and for this super product.and community.
Best regards.

**Comment by boppy** [comment]
If you don't need [that feature](http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by): turn it off. ;)

I found **[that guide that's quite detailed](https://www.sitepoint.com/quick-tip-how-to-permanently-change-sql-mode-in-mysql/#permanently-changing-sql-mode)** to "fix" it. Worked for me.

The fix on the humhub side would probably be a little bit more "in-depth": #1777.

**Comment by cebe** [comment]
> cd protected php yii migrate/up --includeModuleMigrations=1

this looks wrong to me, it should be more like:

```
cd protected && php yii migrate/up --includeModuleMigrations=1
```
