### ISSUE TITLE
Not entirely translated to spanish

### ISSUE THREAD

**Issue by ChStark** [humhub/humhub#1816]
Hi team. I have noticed that not all the platform is translated, so I want to know how can I translate the emails, registration form, etc., Do I need to modify the core?

Regards

**Comment by cebe** [comment]
You can join http://translate.humhub.org/ and help with the translations.

**Comment by ChStark** [comment]
No language available, I have this kind of issues all over the place http://prntscr.com/blu704

username instead "nombre de usuario"
password instead of "contraseña"
Remember Me instead "recordarme"

etc,

I dónt have any experience with Yii whatsoever, can you give me tips to see what can I do to fix this (before I jump into the code and discover ho to do it in 3 or 4 hours instead of 20 minutes reading a tutorial or something)

**Comment by buddha87** [comment]
As cebe wrote, join the translation community and join the space of your language code:
http://translate.humhub.org/index.php?r=space%2Fspace&sguid=53a2d61d-6047-4bb2-8fd4-18bcda042724 then you should be able to translate you language, these changes will be available within the next release.

**Comment by ChStark** [comment]
When I try to translate I get 

PHP Warning – yii\base\ErrorException

file_put_contents(/srv/www/translate.humhub.org/htdocs/protected/humhub/messages/es/base.php): failed to open stream: Permission denied

http://prntscr.com/buk4ez

**Comment by luke-** [comment]
Is fixed, sorry!
