### ISSUE TITLE
Bug: Administration-Panel unreachable

### ISSUE THREAD

**Issue by michaelscheurer** [humhub/humhub#1817]
After the last humhub-update, the admin-panael is no longer available. The following error-message appears permanently (see image).

Very painful to manage the community now...

Do you have any idea? Need further informations?

![image](https://cloud.githubusercontent.com/assets/5489205/16434518/ad853d2a-3d90-11e6-9888-00e70d445c91.png)

**Comment by michaelscheurer** [comment]
We updated to the latest version of humhub (1.1.0-beta.1). Before we had also the latest version.


The exactly same error occoured before the latest update when we wanted to open the users overview (verzeichnis). When we then updated to 1.1.0-beta.1 the error disapeared. Instead we have now this error occouring on the admin-panel.


Funnily enogh I can enter the admin panel by clicking on the "starter help -> administration (module)" (see image below).
![hilfebeimstart](https://cloud.githubusercontent.com/assets/5489205/16457108/9b0c2fd4-3e1a-11e6-98d9-f23c05628960.jpg)

In the image bellow you can find the error log. 
![error_log_humhub](https://cloud.githubusercontent.com/assets/5489205/16457125/a81071cc-3e1a-11e6-8ade-5a1595214237.jpg)

Do you have any idea? 


Thanks a lot!

**Comment by buddha87** [comment]
Hmm seems like a strange behaviour, while trying to translate a profile field 'Email', somehow there is an invalid translation category '1'. I think this needs some investigation, could you please open a ticket on github: https://github.com/humhub/humhub

Can you check your database if there is a non null value for column 'translation_category' in table 'profile_field' (probably with internal_name 'Email' (or in table 'profile_field_category')

Furthermore do you use LDAP ?

**Comment by michaelscheurer** [comment]
Yes, LDAP is active and we had no problem with it so far.

I will have a look on the database and let you know.

Thank you for the help!

**Comment by michaelscheurer** [comment]
Ok, we had a look now in the table as you mentioned. And it was exactly the case. The row had a non null value. We then changed from 1 to null and it worked. Thanks for this. 

But the question still remains: How came, that we have suddenly a "1" in the row? Update? 

We will keep you up-to-date.

Thanks again!
