### ISSUE TITLE
cron hourly failed

### ISSUE THREAD

**Issue by MatthiasHertel** [humhub/humhub#1819]
after update to version 1.1.0 beta - i got the following issue by execute the cron/hourly

PHP Notice 'yii\base\ErrorException' with message **'Undefined index: email'**

```bash
administrator@bb-intranet-test:/var/www/html/humhub/protected$ php yii cron/hourly
Executing hourly tasks:

Sending update e-mails to users... done - 0 email(s) sent.
Optimizing search index... done.
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: email'

in /var/www/html/humhub/protected/humhub/modules/user/authclient/ZendLdapClient.php:312

Stack trace:
#0 /var/www/html/humhub/protected/humhub/modules/user/authclient/ZendLdapClient.php(312): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/h...', 312, Array)
#1 /var/www/html/humhub/protected/humhub/modules/user/Events.php(138): humhub\modules\user\authclient\ZendLdapClient->syncUsers()
#2 [internal function]: humhub\modules\user\Events::onHourlyCron(Object(yii\base\Event))
#3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Event.php(205): call_user_func(Array, Object(yii\base\Event))
#4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(549): yii\base\Event::trigger(Object(humhub\commands\CronController), 'hourly', NULL)
#5 /var/www/html/humhub/protected/humhub/commands/CronController.php(41): yii\base\Component->trigger('hourly')
#6 [internal function]: humhub\commands\CronController->actionHourly()
#7 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('hourly', Array)
#10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('hourly', Array)
#11 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('cron/hourly', Array)
#12 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('cron/hourly', Array)
#13 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /var/www/html/humhub/protected/yii(29): yii\base\Application->run()
#15 {main}
```

the cron/daily works

```
administrator@bb-intranet-test:/var/www/html/humhub/protected$ php yii cron/daily
Executing daily tasks:

Checking for new HumHub version... done. 
Sending update e-mails to users... done - 0 email(s) sent.
Deleting old unassigned files... done.
Deleting old notifications... done.


All cron tasks finished.

administrator@bb-intranet-test:/var/www/html/humhub/protected$ 
```

what can i do to prevent this failure ?

**Comment by MatthiasHertel** [comment]
maybe the problem is that i fetch/have some users **without email** that i do not filter with my ldap query ?

```
ERROR  Mon, 27 Jun 2016 06:30:07 +0200  application
Could not create or update ldap user: max.mustermann! (Array ( [email] => Array ( [0] => Email darf nicht leer sein. ) ) )
ERROR  Mon, 27 Jun 2016 06:30:07 +0200  application
Could not create or update ldap user: max.mustermann2! (Array ( [email] => Array ( [0] => Email darf nicht leer sein. ) ) )
ERROR  Mon, 27 Jun 2016 06:30:06 +0200  application
Could not create or update ldap user profil for user max.mustermann3! (Array ( [firstname] => Array ( [0] => Vorname darf nicht leer sein. ) ) )
ERROR  Mon, 27 Jun 2016 06:30:06 +0200  application
Could not create or update ldap user profil for user max.mustermann4! (Array ( [firstname] => Array ( [0] => Vorname darf nicht leer sein. ) ) )
ERROR  Mon, 27 Jun 2016 06:30:06 +0200  application
Could not create or update ldap user: max.mustermann5! (Array ( [email] => Array ( [0] => Email darf nicht leer sein. ) ) )
ERROR  Mon, 27 Jun 2016 06:30:06 +0200  application
Could not create or update ldap user: max.mustermann6! (Array ( [email] => Array ( [0] => Email darf nicht leer sein. ) ) )
ERROR  Mon, 27 Jun 2016 06:30:06 +0200  application
Could not create or update ldap user: max.mustermann7! (Array ( [email] => Array ( [0] => Email darf nicht leer sein. ) ) )
```


but the cronjob work with version 1.0 - that its curious

**Comment by MatthiasHertel** [comment]
ok if i deactivate the ldap function in the administration user ldap menu - the cron job works

now i have set an email for the users above ... but the cronjob failed again ... 

i believe the required field email is the problem ...

**Comment by MatthiasHertel** [comment]
ok the cronjob now works

i have to filter the member without emails 

in the administration menue - user - ldap 

```
(&(objectCategory=person)(objectClass=user)  (!(userAccountControl:1.2.840.113556.1.4.803:=2))(mail=*))
```

so i only fetch user that have an email ...

**Comment by nguyen-matthias** [comment]
@MatthiasHertel hello, i have the same issuse. What did you put in to witch field?

![screen](https://cloud.githubusercontent.com/assets/16917852/16442637/3a2d43ba-3dd4-11e6-8a48-f963ea44b4f0.JPG)

**Comment by MatthiasHertel** [comment]
@nguyen-matthias 

try to filter out the ldap member that have not an email ... 
that fix the issue ... 

```
(&(objectCategory=person)(objectClass=user)(mail=*)
```

the filter above fetch only members with attribute mail ...

**Comment by nguyen-matthias** [comment]
@MatthiasHertel hmm i have now this
![screen](https://cloud.githubusercontent.com/assets/16917852/16444013/1ef16da8-3ddc-11e6-92a1-526c8a5be93c.JPG)

it's not work :/ If i disable the ldap it's not work too.

i have this error

yii\base\ErrorException: Undefined index: email in E:\xampp\htdocs\protected\humhub\modules\user\authclient\ZendLdapClient.php:312
Stack trace:
#0 E:\xampp\htdocs\protected\humhub\modules\user\authclient\ZendLdapClient.php(312): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 312, Array)
#1 E:\xampp\htdocs\protected\humhub\modules\user\Events.php(138): humhub\modules\user\authclient\ZendLdapClient->syncUsers()
#2 [internal function]: humhub\modules\user\Events::onHourlyCron(Object(yii\base\Event))
#3 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Event.php(205): call_user_func(Array, Object(yii\base\Event))
#4 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Component.php(549): yii\base\Event::trigger('humhub\\commands...', 'hourly', Object(yii\base\Event))
#5 E:\xampp\htdocs\protected\humhub\commands\CronController.php(41): yii\base\Component->trigger('hourly')
#6 [internal function]: humhub\commands\CronController->actionHourly('>/dev/null', '2>&1')
#7 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#8 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('hourly', Array)
#10 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('hourly', Array)
#11 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\console\Application.php(176): yii\base\Module->runAction('cron/hourly', Array)
#12 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\console\Application.php(143): yii\console\Application->runAction('cron/hourly', Array)
#13 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 E:\xampp\htdocs\protected\yii(29): yii\base\Application->run()
#15 {main}

**Comment by MatthiasHertel** [comment]
i made the following steps ... 

1. deactivate ldap -> the cron job success 

2. ok set the filter with mail and then reactivate ldap auth

3. try the cronjob -> success

**Comment by MatthiasHertel** [comment]
> it's not work :/ If i disable the ldap it's not work too.

ah ok the cronjob does not work if u deactivate ldap ... that is strange ...

**Comment by nguyen-matthias** [comment]
@MatthiasHertel Yes it is...

**Comment by MatthiasHertel** [comment]
try to remove the entry for mail ... leave it empty

**Comment by nguyen-matthias** [comment]
ok i leave the mail field empty and its failed again

**Comment by nguyen-matthias** [comment]
oh but i see the daly job it's work but the hourly not works

**Comment by nguyen-matthias** [comment]
allright. Its work now :dancer: there was an email adress double. Thanks for your help ;)
