### ISSUE TITLE
URL parser bug in post

### ISSUE THREAD

**Issue by primantok** [humhub/humhub#1822]
Hello,

I have a problem with the url parser in post. I thinks this problem also happen in HumHub community site. Here is the sample link https://community.humhub.com/content/perma?id=68119

If you read comment #5 by Julian Harrer, you will open a 404 page because the url parser also include a "comma".

Here as the screenshot https://s32.postimg.org/d3heh6glx/Screenshot_2016_06_30_03_36_12.png

**Comment by 3cst4sy** [comment]
can be solved with a better regex pattern for url finding: 
[https://github.com/humhub/humhub/commit/78645ba798a0a3b4a63a26318b03ad577475dc8b](url)

**Comment by 3cst4sy** [comment]
sry wrong link: [https://github.com/3cst4sy/humhub/commit/78645ba798a0a3b4a63a26318b03ad577475dc8b](url)

**Comment by 3cst4sy** [comment]
sry wrong link https://github.com/3cst4sy/humhub/commit/78645ba798a0a3b4a63a26318b03ad577475dc8b

**Comment by buddha87** [comment]
Not really a bug but I think you are right ending punctuation marks have to be excluded from the link, its pretty annoying.

**Comment by cebe** [comment]
you might want to use this regex: https://github.com/cebe/markdown/blob/master/inline/UrlLinkTrait.php#L25-L31

**Comment by cebe** [comment]
some examples on how it works: http://markdown.cebe.cc/try?flavor=gfm&text=check+https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FAustrian_presidential_election%2C_2016%2C+or+other%3F%0D%0AIt+also+deals+with+links+like+https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSinus_%2528anatomy%2529+which+can+have+parenthesis+written+like%3A%0D%0Ahttps%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSinus_%28anatomy%29+and+if+you+put+it+in+parenthesis+itself%2C+it+also+works+%28https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSinus_%28anatomy%29%29.

**Comment by buddha87** [comment]
@cebe thanks I'll have a look

**Comment by buddha87** [comment]
hey @cebe , thanks again. 

I tried to use your regexp as is in our RichText: https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/RichText.php#L70 but it does not match any links.

I've also tried the following modified regexp, but the parentheses examples do not work:

`/(https?:\/\/(([^\s()]+)|(?R))+(?<![\.,:;\'"!\?\s]))/i`

Unfortunately I'am not that into regular expessions  do you have any suggestions?
It would be great if we could integrate this into v1.1.

**Comment by buddha87** [comment]
ok, got it with:
```
/(?(R) # in case of recursion match parentheses
				 \(((?>[^\s()]+)|(?R))*\)
			|      # else match a link with title
				(https?|ftp):\/\/(([^\s()]+)|(?R))+(?<![\.,:;\'"!\?\s])
			)/x
```
