### ISSUE TITLE
Database Exception – yii\db\Exception  

### ISSUE THREAD

**Issue by badis** [humhub/humhub#1823]
I have just installed HumHub 1.1.0-beta.1 , I got this error.

-------------------------------------------------------------------------
Database Exception – yii\db\Exception

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
The SQL being executed was: ALTER TABLE `contentcontainer_setting` ADD UNIQUE INDEX `settings-unique` (`module_id`, `contentcontainer_id`, `name`)
Error Info: Array
(
    [0] => 42000
    [1] => 1071
    [2] => Specified key was too long; max key length is 1000 bytes
)
↵
Caused by: PDOException

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

in C:\wamp64\www\humhub110\protected\vendor\yiisoft\yii2\db\Command.php at line 844

-------------------------------------------------------------------------------

I can provide more details if necessary.
Thank you for your help.

**Comment by luke-** [comment]
Fixed https://github.com/humhub/humhub/commit/776b50df0858c2e39b2b56fad086345024b428ad
