### ISSUE TITLE
Humhub : Can we change the landing page of a user.

### ISSUE THREAD

**Issue by shyamkrishna123** [humhub/humhub#1828]
actually i want to change the landing page of a user to a custom page or one of the admin space . is it possible

**Comment by MatthiasHertel** [comment]
i need that feature to ... have to setup the route after login redirect .... i believe that is no rocket science

**Comment by shyamkrishna123** [comment]
Do anybody have any idea

**Comment by cebe** [comment]
you could set [$returnUrl] in application config. http://www.yiiframework.com/doc-2.0/yii-web-user.html#$returnUrl-detail

**Comment by MatthiasHertel** [comment]
i would like to set this return url to an custom page ... which file i have to set the `$returnURL` ?

**Comment by cebe** [comment]
```php
[
    'components' => [

    // ...

        'user' => [
            'returnUrl' => ['/custom_pages/view/index', 'id' => 1],
        ],
    ]
];
```

where `id` is the ID of the custom page you want to show.

**Comment by MatthiasHertel** [comment]
works like a charm ... awesome!

**Comment by shyamkrishna123** [comment]
Can we us it for space?

**Comment by cebe** [comment]
> Can we us it for space?

sure, any url should work

**Comment by shyamkrishna123** [comment]
how can find id for space?

**Comment by MatthiasHertel** [comment]
can i set the defaultRoute in:
humhub/protected/humhub/config/web.php

```
'defaultRoute' => '/dashboard/dashboard',
```

to a custom page like ?

```
'defaultRoute' => '/index.php?r=custom_pages%2Fview&id=2',
```

my problem is that i want to redirect the request to a custom page ... eg. open humhub with open session i a new tab ... the routing is set to dashboard ... i want to route to my custom page... 

is it possible ?

**Comment by davadmin** [comment]
Hello, Can we us it for space? 

Like this ?

`'returnUrl' => ['/index.php?r=space%2Fspace&sguid=c711e9f3-a99e-4230-a90c-2d32947878a9'],`

it does not work

**Comment by buddh4** [comment]
Try:
`'returnUrl' => ['/space/space', 'sguid' => 'c711e9f3-a99e-4230-a90c-2d32947878a9']`

**Comment by davadmin** [comment]
Thank you Buddh4 !! it works great!

**Comment by davadmin** [comment]
Re !
I just saw that new subscribers still falls on the newsfeed page .. how to make new subscribers fall on the space page? thank you

**Comment by buddh4** [comment]
Please aks such questions in the [Community](https://community.humhub.com)

**Comment by abhijit-iterate** [comment]
> Try:
> `'returnUrl' => ['/space/space', 'sguid' => 'c711e9f3-a99e-4230-a90c-2d32947878a9']`

Instead of static value what If i have to pass a dynamic value like 'sguid'=>'dynamic value'.
How to do it im unable to locate it in humhub space.
Thanks.

**Comment by buddh4** [comment]
You should not use dynamic values in the config, since the config will be cached. Perhaps open a feature request and describe your specific use-case. I'am sure this could be implemented as custom module.

**Comment by abhijit-iterate** [comment]
> You should not use dynamic values in the config, since the config will be cached. Perhaps open a feature request and describe your specific use-case. I'am sure this could be implemented as custom module.

Thanks for the fast reply @buddh4 . I wanted to add dynamic space url inside Invite.php
Where invite is sent to the user, I did this         
$spaceUrl = Url::to(['/space/space', 'cguid' => '6d17b403-4626-401e-b148-76a8fa928277'], true);

And passed it as  'registrationUrl' => $spaceUrl .

So user gets the invite and after login he's redirect to that particular space.

So instead of static value here I wanted to pass dynamic space guid.

Sorry I dont know how to open a feature request to replying here.

Thanks.

**Comment by buddh4** [comment]
Just create an issue here on github.
