### ISSUE TITLE
Database Exception – yii\db\Exception

### ISSUE THREAD

**Issue by worldwildweb** [humhub/humhub#1832]
HELP PLEASE.
After upgrading to humhub-1.0.1-1.1.0-beta.1

log available at http://apese06.fr/hub/

Database Exception – yii\db\Exception

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'apese06_fr_humhub.contentcontainer_setting' doesn't exist
The SQL being executed was: SELECT * FROM `contentcontainer_setting` WHERE (`module_id`='tour') AND (`contentcontainer_id`=1)
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'apese06_fr_humhub.contentcontainer_setting' doesn't exist
)
↵
Caused by: PDOException

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'apese06_fr_humhub.contentcontainer_setting' doesn't exist

in /var/home/vhosts/apese06.fr/public_html/hub/protected/vendor/yiisoft/yii2/db/Command.php at line 900

**Comment by benmag** [comment]
Have you run the migrations after you upgraded?

**Comment by buddha87** [comment]
I assume u used the updater module for your update, some user had timeout issues with the update, we'll provide a new updater version for the stable release of 1.1. As benmag said, you'll have to try to run the migrations manually:

```
cd protected
php yii migrate/up --includeModuleMigrations=1
```

**Comment by worldwildweb** [comment]
Yes i have used the module update.
Please let us know when a fix is available.
