### ISSUE TITLE
Invalid Configuration – yii\base\InvalidConfigException

### ISSUE THREAD

**Issue by worldwildweb** [humhub/humhub#1834]
can someone help please?

http://apese06.fr/hub/

ApcCache requires PHP apc extension to be loaded.

**Comment by worldwildweb** [comment]
Question would it be possible and how deactivate APC?

THANKS

**Comment by buddha87** [comment]
Please explain your problem in more detail:
- Full Stack trace (error)
- Where does it happen
- What would be possible
