### ISSUE TITLE
Humhub google authentication show error

### ISSUE THREAD

**Issue by shyamkrishna123** [humhub/humhub#1835]
The configuration for the "authClientCollection" component must contain a "class" element.

**Comment by buddha87** [comment]
Are you using v1.1 with the following configuration: https://www.humhub.org/docs/guide-admin-authentication.html#google ?

**Comment by duythien** [comment]
@buddha87 Can you provide a url callback for google. I have take a look documents but I don't see it after that I tries to a callback url like this http://fb.phanbook.com/index.php?r=user/auth/external

But it will a error ```Error: redirect_uri_mismatch

```

**Comment by buddh4** [comment]
http://docs.humhub.org/admin-authentication.html
