### ISSUE TITLE
Migration error while manually updating from 1.0.1 to 1.1.0-beta.1

### ISSUE THREAD

**Issue by frey1esm** [humhub/humhub#1836]
I did a manual update per [Option 2](https://www.humhub.org/docs/guide-admin-updating.html) and then executed the migration command `php yii migrate/up --includeModuleMigrations=1`

Then I got this database exception error:

```
> add foreign key fk_user_id: user_auth (user_id) references user (id) ...**Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table 'db_humhub.#sql-167a_dc' (errno: 150)
The SQL being executed was: ALTER TABLE `user_auth` ADD CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE'**
```

`Error Info:
Array
(
    [0] => HY000
    [1] => 1005
    [2] => Can't create table 'db_humhub.#sql-167a_dc' (errno: 150)
)`

**Comment by cebe** [comment]
looks like a foreign key issue, i.e. the data in the table does not reference existing user ids.
