### ISSUE TITLE
Search box auto-completion and improvements

### ISSUE THREAD

**Issue by ekerazha** [humhub/humhub#1839]
When I begin typing in the search box, it would be nice to have an auto-complete feature (e.g. users suggestions etc.).

**Comment by nadilnadeem** [comment]
It's Already there, You have to type at least 3 characters to pop up the auto-complete

**Comment by ekerazha** [comment]
It doesn't work.

1) Create a HumHub demo with demo content
2) There's a demo "David Roberts" user
3) Go to the search box, begin typing "Dav"
-> NO auto-complete popup

**Comment by nadilnadeem** [comment]
OK, Does your notification list showing the notifications? And Your recent activities widget showing the list of activities ?

**Comment by ekerazha** [comment]
Yes

**Comment by buddha87** [comment]
@nadilnadeem I think he means the global search, which do not have any autocomplete functionality.

**Comment by ekerazha** [comment]
Yes, the global search

**Comment by ekerazha** [comment]
Is this feature planned? It's a deal breaker for me, I can't use HumHub because of this missing feature.

**Comment by buddha87** [comment]
V1.2 will provide an enhanced space chooser which will include non member spaces in the search result and users can also be searched in the directory. The only thing the autocomplete could facilitate is the user search.

**Comment by spoorun** [comment]
This is the number one issue our users talk of.
To simply open someone's profile seems a chore to them, when they are used to just starting to type the name of a User or Space... which is increasingly the kind of user interface other systems deploy - from Windows 10, Android SMS, to Facebook, to Linux, to WhatsApp, bots etc... I realise that search will still come up, but it's a step, and it then throws many items, when the user just wanted to open someone's profile or a space.
