### ISSUE TITLE
restrict allowed languages does not work

### ISSUE THREAD

**Issue by richhl** [humhub/humhub#1841]
Hi, as of https://www.humhub.org/docs/guide-admin-adv-config.html#loading-order is it possible to restrict available languages with this content in config/common.php

```
return [
    'params' => [
        'allowedLanguages' => ['de', 'fr']
    ]
];
```
but this is not working for the stable branch

**Comment by buddha87** [comment]
Sorry this feature is only available for v1.1. Should not be part of the documentation yet.

**Comment by richhl** [comment]
any way to access doc by version?

**Comment by buddha87** [comment]
Only on github: https://github.com/humhub/humhub/tree/stable/protected/humhub/docs/guide
