### ISSUE TITLE
LDAP authentication with mail address

### ISSUE THREAD

**Issue by T-Rock** [humhub/humhub#1842]
I am using KOLAB as a LDAP backend.
In KOLAB the complete mail address is used as an username like: mustermann@domain.de
But the HumHub LDAP authentication always splits the mail address and only uses the part before the @-sign („mustermann“) and the authentication fails.
I could not find any possibility in the LDAP Admin Settings in HumHub to change this behavior.
I found that in zend-ldap in the zendframework the setting „tryUsernameSplit“ has the default value „true“.
file: protected/vendor/zendframework/zend-ldap/src/Ldap.php
line: 239
If I change it there, the authentication with a mail address works fine.

**Comment by cperreault** [comment]
Thanks a lot! We encountered the same weird problem. You saved me lots of time digging into it. I think that Humhub should definitively take the username as-is. It appears absurd to check the LDAP directory with a different one...
