### ISSUE TITLE
Error on saving translation

### ISSUE THREAD

**Issue by J-Setzer** [humhub/humhub#1853]
I have translated a couple of labes without problems so far. But this one does not work.

Module: custom_pages
Language: de
File: views_admin_add
URL: [http://translate.humhub.org/index.php?r=translation%2Ftranslate&moduleId=custom_pages&language=de&file=views_admin_add](http://translate.humhub.org/index.php?r=translation%2Ftranslate&moduleId=custom_pages&language=de&file=views_admin_add)

**Original (en):**
`<strong>Add</strong> new page`

**Translated (de):**
`Neue Seite <strong>erstellen</strong>`

After Saving:

```
PHP Warning – yii\base\ErrorException

file_put_contents(/srv/www/translate.humhub.org/modules/custom_pages/messages/de/views_admin_add.php): failed to open stream: Permission denied
```

I first thought it was because of the HTML-Tags, but it doesn't work even without HTML-Tags.

**Comment by J-Setzer** [comment]
![image](https://cloud.githubusercontent.com/assets/20423093/16773675/1372fb5e-4859-11e6-82ed-44df5e43d0e9.png)

**Comment by J-Setzer** [comment]
![image](https://cloud.githubusercontent.com/assets/20423093/16773711/2f733d1e-4859-11e6-8190-10d66ad599d4.png)

**Comment by buddha87** [comment]
Can be an git conflict. We'll check this. 

Furthermore note that the translation for 

`<strong>Add</strong> new page`

should be translated to:

`<strong>Neue Seite</strong> erstellen` 

or 

`<strong>Seite</strong> erstellen` 

since the heading should always start with bold text.
