### ISSUE TITLE
Binding requires username in DN form

### ISSUE THREAD

**Issue by ideadel** [humhub/humhub#1856]
Hi, i can't configure my ldap.
if i add a username i get this error: "Binding requires username in DN form"
i wrote DOMAIN\ADMINISTRATOR.

thanks.

**Comment by luke-** [comment]
DN form e.g.  cn=administrator,dc=example,dc=com

**Comment by ideadel** [comment]
Thanks! now i get status ok but 0 users fetched.
I have lot of users but no one is imported.
