### ISSUE TITLE
Reverse Https Proxy Links use Http

### ISSUE THREAD

**Issue by weisental** [humhub/humhub#1859]
Hi,

humhub Version: 1.0.1

Setup  
Nginx SSL -> ProxyPass  -> docker 3333:80 apache

BaseUrl Setting https://hum.dikas.de

Problem:
Uploaded Files links to http://hum.dikas.de/...

Nginx
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_buffering off;
                proxy_set_header Host $http_host;

Thx

Jürgen Weisental

**Comment by b17** [comment]
@weisental Try to add to your nginx config:
```
 proxy_set_header        X-Forwarded-Proto $scheme;
```

**Comment by weisental** [comment]
@b17 

Thanks, works like a charm

**Comment by verement** [comment]
FYI for anyone finding this doesn’t seem to work, I found it also necessary to modify the Yii configuration which, [by default](https://www.yiiframework.com/doc/api/2.0/yii-web-request#$secureHeaders-detail), filters the `X-Forwarded-Proto` (and other) headers unless explicitly [whitelisted](https://www.yiiframework.com/doc/api/2.0/yii-web-request#$trustedHosts-detail).

If your setup is already sufficiently firewalled such that only the reverse proxy has access, one solution could be to eliminate the header filtering via the following (in `protected/config/web.php`):

```php
return [
        'components' => [
                'request' => [
                        'secureHeaders' => [],
                ],
        ]
];
```

Alternatively you can set an IP whitelist via `trustedHosts`.
