### ISSUE TITLE
Overwriting $app->version breaks modules...

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1861]
Specifically the mail module when $app->version is set to > 1.0.1

As HumHub is created to be expandable and build on, allowing your consumers to run their own version number is very important.

Request: Use .env or other environmental containment system to hold data, uniquely name keys with hh_\* prefix; hh_app_name, hh_version, hh_admin_email, etc.

Ref: https://github.com/vlucas/phpdotenv

**Comment by luke-** [comment]
We assume that HumHub Core is always the base application.

HumHub itself is extensible and customizable but it is not thought that only single components will be used.

**Comment by davidjeddy** [comment]
Agreed, HH is the core. However, module version should not be locked / limited to be equal to or lower than HH's.
