### ISSUE TITLE
Feature: merge page editor and wiki features

### ISSUE THREAD

**Issue by rondonjon** [humhub/humhub#1865]
The new wiki introduces redundancy in the application, which is confusing to end users.

IMO the two features should be merged into one:
- add an installation/update script that automatically migrates all existing "pages" to "wiki pages"
- remove the old page editor in favor of the (feature-richer?) wiki editor as soon as possible
- make the wiki editor a core feature
- add two extra fields to the wiki editor (checkbox "show in navigation" and "sort order in navigation")
- remove the wiki icon from the navigation

I know this will result in extra effort, but seriously, what's the alternative? End users should not have to worry about two features that do virtually the same thing.

**Comment by buddha87** [comment]
Hi,

1. I don't understand which pages you want to migrate ?
2. Do you mean the markdown editor ?
3. If you mean the markdown editor, its already part of the core
4. Could be implemented, but perhaps the custom_pages module is more suitable for such pages, also the custom pages will be updated soon with an integrated templating system.

I don't know what you mean with two features, perhaps you have installed two different versions of the same module?
