### ISSUE TITLE
Feature: comment and stream editors should have a keyboard shortcut for the submit button

### ISSUE THREAD

**Issue by rondonjon** [humhub/humhub#1867]
Pressing ENTER in the comment and stream editor produces a newline (which is OK for me).

What I would like in addition is a shortcut (e.g. SHIFT+ENTER or CTRL+ENTER) to submit the text without having to switch to the mouse or touchpad every single time.

**Comment by buddh4** [comment]
You can submit posts in 1.4 with `Ctrl + s`
