### ISSUE TITLE
Feature: search should open without page reload

### ISSUE THREAD

**Issue by rondonjon** [humhub/humhub#1868]
Clicking the search button results an a page load, with the result page showing not much more than a search field and some optional extended options.

Seriously? In 2016? :-1:

IMO, clicking the search button should unhide an input field to the left (CSS transition?) which the user can then populate; pressing ENTER should then trigger the actual search.

Extended options (like the restriction to certain spaces) could be made available through a custom search syntax (people know this from Google, e.g. "site:") an explained in a help page.

**Comment by buddha87** [comment]
we'll introduce a single page "feeling" for some pages in version 1.2

**Comment by luke-** [comment]
#1839
