### ISSUE TITLE
Details in custom page/iframe/php

### ISSUE THREAD

**Issue by Guardian1983** [humhub/humhub#1872]
Is it possible to pull details about users into a iframe/php page or another selfcoded page? Something aimpe as $_GET[id] or similar..?

**Comment by Guardian1983** [comment]
Nothing about this? ;-)

**Comment by MatthiasHertel** [comment]
hey guardian ...

u can retrieve the phpsessid in the header ... then u can query it in the db the table is user_http_session... and u can implement a handshake between an external (iframe) applikation and humhub ... 

maybe that is a solution for u ...

**Comment by Guardian1983** [comment]
Thank you ;-) Worked like a charm ;-) Joined the user table with the user_http_session :-P
