### ISSUE TITLE
ldap user create automatically failed

### ISSUE THREAD

**Issue by MatthiasHertel** [humhub/humhub#1873]
i have found this in my logfiles ... i dont understand the problem:

![image](https://cloud.githubusercontent.com/assets/8426566/16913643/31cfa128-4cec-11e6-85d4-b2c57a2a00e2.png)

my filter is this one:
![image](https://cloud.githubusercontent.com/assets/8426566/16913613/f533ae12-4ceb-11e6-9ceb-ec05e73b150f.png)

what are the required attributes ?

the first import works good ... but if the domaincontroller has a new user .. this problem appears ... 

maybe the required attributes in the profile settings ?

![image](https://cloud.githubusercontent.com/assets/8426566/16913690/9412df76-4cec-11e6-8fbc-88c070b1e800.png)

**Comment by MatthiasHertel** [comment]
okay the problem was ... i has to set the default group ... on a specific value ... not dropdown ... strange

![image](https://cloud.githubusercontent.com/assets/8426566/16914286/296c59e0-4cf1-11e6-92d6-8ca4ca5086d8.png)

**Comment by Itacua** [comment]
@MatthiasHertel : I've the exact same problem, but I don't have success to make it work with your solution. I created a group and make it default for new user, but still can't import new users from LDAP.
