### ISSUE TITLE
ldap connection ok, get 9 users but no new users in humhub

### ISSUE THREAD

**Issue by ideadel** [humhub/humhub#1874]
Hi, 
my ldap connection it works, i get 9 users but i can't find these users in humhub.
There is something to do more?

**Comment by MatthiasHertel** [comment]
u have to run the cron/hourly job to sync it in the database...

```
administrator@bb-intranet-test:/var/www/html/humhub/protected$ php yii cron/hourly
Executing hourly tasks:

Sending update e-mails to users... done - 0 email(s) sent.
Optimizing search index... done.


All cron tasks finished.
```


after that the users should be in humhub database ...

**Comment by ideadel** [comment]
i'm on windows, i tried to create a php page and call it via wget and do this, but it wont work:

<?php
	echo exec('30 * * * * C:\wamp\www\humhub\protected/yii cron/hourly >/dev/null 2>&1');
	echo exec('00 18 * * * C:\wamp\www\humhub\protected/yii cron/daily >/dev/null 2>&1');
	echo exec('*/5 * * * * su -c "C:\wamp\www\humhub\protected/yii  cron/hourly" SYSTEM    >/dev/null 2>&1');
	echo exec('0 18 * * * su -c "C:\wamp\www\humhub\protected/yii  cron/daily" SYSTEM >/dev/null 2>&1');
	echo "fatto."
?>
any help?

**Comment by MatthiasHertel** [comment]
puuuuhhh u dont need a php file ... 

u have to only run 

```
php yii cron/hourly
```

how to run the cron under windows ... i dont know ... but you have to "compile" the yii calling ... like php yii ... or in laravel php artisan and so on ... 

why u installed it under windows ... its so tricky without a CLI/bash 

u can use a vagrant box ... for easy deploying 

look at this one:
```
git clone https://github.com/MatthiasHertel/humhub_box
vagrant up
```
and then u have out of the box working humhub on linux box ..

**Comment by ideadel** [comment]
i can't, all my servers are windows.  i create a batch running php and yii with this command scheduled task.
