### ISSUE TITLE
Error on Images and in certain textboxes

### ISSUE THREAD

**Issue by PenguinNexus** [humhub/humhub#1878]
HumHub version: 1.0.1
PHP: 5.6.21

When I upload an image, next to the image where it should show the image size, I instead get the following:
{nFormatted} {n, plural, =1{kilobyte} other{kilobytes}}
![bugreport](https://cloud.githubusercontent.com/assets/16801642/16943736/1b12de92-4d95-11e6-9c0d-210e3bc31798.PNG)
Logs:
Formatting message for language 'en-US' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ILLEGAL_CHARACTER. The message being formatted was: {nFormatted} {n, plural, =1{kilobyte} other{kilobytes}}.

Also when choosing default spaces...
![defaultspacebugreport](https://cloud.githubusercontent.com/assets/16801642/16943756/37a8e704-4d95-11e6-87bc-8402a02bfccf.png)
Logs:
WARNING  Tue, 19 Jul 2016 03:40:26 -0500  yii\i18n\I18N::format
Formatting message for language 'en' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ILLEGAL_CHARACTER. The message being formatted was: Add {n,plural,=1{space} other{spaces}}.

**Comment by Penguinexpert1** [comment]
If I understand the logs correctly, do I need to just re-install the en and en-us language folders? If so, where would I find these in my directory (using FTP)

**Comment by awrelll** [comment]
I got the same issue in my logs. Any help?
