### ISSUE TITLE
ZendLuceneSearch - Exception

### ISSUE THREAD

**Issue by alvarocantador** [humhub/humhub#1879]
I'm having troubles with ZendLuceneSearch. It started when my database increased the size (4000 spaces).

When I search for something:

![erro_lucene](https://cloud.githubusercontent.com/assets/4078365/16951322/e0432a78-4d9a-11e6-9093-fa2574930785.png)

If i set $_termsPerQueryLimit = 0, the timeout limit is exceeded.

PHP 5.5 - Ubuntu 14

Any Idea?

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/issues/2526
