### ISSUE TITLE
Erro Humhub

### ISSUE THREAD

**Issue by henriquepl** [humhub/humhub#1880]
![2345](https://cloud.githubusercontent.com/assets/20547792/16971813/4604227e-4dfd-11e6-957f-87936339bedb.png)
![2345](https://cloud.githubusercontent.com/assets/20547792/16971855/8cbbc08c-4dfd-11e6-936d-a852c2e600d2.png)

The error that appears in my Humhub and on the login screen that appears, the password is incorrect.
Creating new accounts and testing does not work to recover the password and try again, it does not work well.

**Comment by buddha87** [comment]
please check your server logs for error messages.
