### ISSUE TITLE
HumHub LDAP not working

### ISSUE THREAD

**Issue by gfilon00** [humhub/humhub#1888]
Hi! 

I'm trying to log in users using LDAP, but it always shows me "Incorrect username or password.", although I can see the users in Ldapadmin for windows and the configuration on humhub seems to be working fine, it find my users:
![capi](https://cloud.githubusercontent.com/assets/20646133/17109072/cdb65be2-526c-11e6-8c5d-fb141ca5c20e.png)

You can see them in the ldapadmin:

![capii](https://cloud.githubusercontent.com/assets/20646133/17109104/f199fdfc-526c-11e6-9d6f-360f4a7c3007.png)

But I can't log in:

![caoiii](https://cloud.githubusercontent.com/assets/20646133/17109115/fe8747a4-526c-11e6-8a8a-7e482cb33f5f.png)

I tried with no password and then tried setting a password with the ldapadmin for windows and using it to log in with humhub with no happy resoults...

Any help will be appreciated !

**Comment by Itacua** [comment]
Hello, I've the same issue. Did you find something to fix it? Thanks in advance.
