### ISSUE TITLE
Mobile Interface Doesn't Show Conversations

### ISSUE THREAD

**Issue by aforsythe** [humhub/humhub#1890]
In [v1.1.0-beta.2](https://github.com/humhub/humhub/tree/v1.1.0-beta.2) some spaces the mobile interface doesn't display conversations.  Pressing the "Load More" button doesn't work.  
![img_2998](https://cloud.githubusercontent.com/assets/309001/17147824/3fbfdd06-5319-11e6-863a-6820ff5b3c14.jpg)

**Comment by buddha87** [comment]
The community runs on v1.1.beta1, I can't reproduce this on the community with Android/Chrome which browser do you use and does this also happen on your own site?
