### ISSUE TITLE
Rest Notification API

### ISSUE THREAD

**Issue by shirbor** [humhub/humhub#1894]
Hi,

I am trying to create custom notifications from an external php script.
My goal is to notify all the users of a given space on an event. 
I've tried by myself, found the BaseNotification class but after playing with it, I am still missing some informations to do what I want.
I didn't find any topic on how to implement custom notifications, but i wouldn't be surprised if someone already did this.
Any help?
Don't hesitate to question me if you need more details

**Comment by buddha87** [comment]
have your read this https://www.humhub.org/docs/guide-dev-notifications.html ?

**Comment by shirbor** [comment]
Yes, that's what I used.
I was able to create a new notification based on this page and the existing "NewComment" notification, but I never got it to work from my external script. I have in fact no idea how to create the notification from outside of the humhub folder. When I replace the "NewComment" notification with my own, it works. The problem does not seem to come from my class construction.

After multiple tentatives all I can get is a "Class 'EditionNotification' not found in /var/www/html/humhub/protected/modules/xxx/modules/notification/components/file.upload.php on line 10"
and line 10 is :
"$notification = new \modules\xxx\modules\notification\components\EditionNotification();"
and my EditionNotification.php is in components. the file.upload.php is the script I use, from another folder initially but I actually tried to get it to work there.

I don't know if it's clear enought, english isn't my native language, ask if you need precisions

**Comment by shirbor** [comment]
Any help?

**Comment by ArchBlood** [comment]
Can be done with Rest API module;
https://github.com/humhub/rest/blob/master/definitions/NotificationDefinitions.php
