### ISSUE TITLE
Using proxy, server gives proxy ip/hostname not humhub server

### ISSUE THREAD

**Issue by randomboygh** [humhub/humhub#1895]
I get many broken links like a attached files in post, login page and even in registration email:
![img](http://storage4.static.itmages.ru/i/16/0729/h_1469824186_3288842_00c547a996.png)

![img](http://storage5.static.itmages.ru/i/16/0729/h_1469824429_2438696_ad00335e0f.png)
![img](http://storage5.static.itmages.ru/i/16/0729/h_1469824429_5699534_8914d8e184.png)

Maybe public function _getHostInfo()_ in _protected\vendor\yiisoft\yii2\web\Request.php_ works wrong. I commented this function and all work right.

![img](http://storage7.static.itmages.ru/i/16/0729/h_1469824593_7689913_46c75a14e9.png)

**Comment by cebe** [comment]
if the external hostinfo is different from where the application is located behind the proxy there is no way to auto detect hostinfo and baseUrl. In this case you have to configure them explicitly in the config.

**Comment by randomboygh** [comment]
Thanks for advice, but how i can configure this variables?
I have Apache behind proxy, so users go to the proxy server first, which connect to the Apache from 127.0.0.1

**Comment by cebe** [comment]
See https://github.com/humhub/humhub/blob/master/protected/humhub/docs/guide/admin-adv-config.md 


```php
[
    'components' => [

    // ...

        'request' => [
            'hostInfo' => 'http://www.example.com',
            'pathInfo' => '', // url path to the application if it is not directly after the URL.
        ],
    ]
];
```
see also
http://www.yiiframework.com/doc-2.0/yii-web-request.html

**Comment by randomboygh** [comment]
Thank you, it helps
But it works only if proxy have same hostname always

**Comment by randomboygh** [comment]
In last version all works well
