### ISSUE TITLE
iOS phone rotates image uploads 90 degrees

### ISSUE THREAD

**Issue by johncyork** [humhub/humhub#1897]
Hello,
whenever I use humhub on my iPhone and upload images that I have taken with the iPhone camera (Front camera and back camera), the image is saved and shown rotated 90 degrees to the left. The exception to this occurring is if I use a screenshot image(pressing the home button and power button simultaneously on the iPhone). These pictures upload without any issues. This problem does not happen on Android and Mac/PC devices. 
![fullsizerender](https://cloud.githubusercontent.com/assets/4119408/17279424/7a413dcc-5741-11e6-97cb-64db59d9e233.jpg)

**Comment by cebe** [comment]
Might be caused by EXIF orientation Tag: http://keyj.emphy.de/exif-orientation-rant/

**Comment by buddh4** [comment]
Can't reproduce, at least with the new gallery.
