### ISSUE TITLE
folder protected/vendor is empty in Latest Stable Version!!!!

### ISSUE THREAD

**Issue by DenisTimanovskiy** [humhub/humhub#1898]
folder protected/vendor is empty in Latest Stable Version!!!!

**Comment by DenisTimanovskiy** [comment]
PHP Fatal error:  require(): Failed opening required '/var/www/denis/data/www/humhub/protected/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/denis/data/www/humhub/index.php on line 13

**Comment by cebe** [comment]
you can run `composer install` to install the dependencies.

**Comment by tfont** [comment]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/jquery-timeago could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package bower-asset/jquery-nicescroll could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package bower-asset/jquery-knob could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package bower-asset/jquery-placeholder could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package bower-asset/blueimp-file-upload could not be found in any version, there may be a typo in the package name.
  Problem 6
    - The requested package bower-asset/fontawesome could not be found in any version, there may be a typo in the package name.
  Problem 7
    - The requested package bower-asset/bootstrap-markdown could not be found in any version, there may be a typo in the package name.
  Problem 8
    - The requested package bower-asset/select2 could not be found in any version, there may be a typo in the package name.
  Problem 9
    - The requested package bower-asset/bluebird could not be found in any version, there may be a typo in the package name.
  Problem 10
    - The requested package bower-asset/select2-bootstrap-theme could not be found in any version, there may be a typo in the package name.
  Problem 11
    - The requested package bower-asset/jquery.cookie could not be found in any version, there may be a typo in the package name.
  Problem 12
    - The requested package bower-asset/jquery-color could not be found in any version, there may be a typo in the package name.
  Problem 13
    - The requested package bower-asset/autosize could not be found in any version, there may be a typo in the package name.
  Problem 14
    - The requested package bower-asset/nprogress could not be found in any version, there may be a typo in the package name.
  Problem 15
    - The requested package bower-asset/at.js could not be found in any version, there may be a typo in the package name.
  Problem 16
    - The requested package bower-asset/animate.css could not be found in any version, there may be a typo in the package name.
  Problem 17
    - The requested package bower-asset/html5shiv could not be found in any version, there may be a typo in the package name.
  Problem 18
    - The requested package bower-asset/clipboard.js could not be found in any version, there may be a typo in the package name.
  Problem 19
    - The requested package bower-asset/jplayer could not be found in any version, there may be a typo in the package name.
  Problem 20
    - The requested package bower-asset/imagesloaded could not be found in any version, there may be a typo in the package name.
  Problem 21
    - yiisoft/yii2 2.0.12 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.11.2 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.11.1 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.11 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 ~2.0.11 -> satisfiable by yiisoft/yii2[2.0.11, 2.0.11.1, 2.0.11.2, 2.0.12].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by buddh4** [comment]
did you run `php composer.phar global require "fxp/composer-asset-plugin:~1.3"` as described in the [doc](http://docs.humhub.org/dev-git-installation.html)

**Comment by sasqwatch** [comment]
php C:\ProgramData\Composer\bin\composer.phar global require "fxp/composer-asset-plugin:~1.3"
