### ISSUE TITLE
In 1.1.0-beta.2 version: yii\db\Exception  this is incompatible with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by denoll** [humhub/humhub#1900]
Hi, when I, first time logined, I get exeption:  (using php.7x64)

Database Exception – yii\db\Exception
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'abantu.notification.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
The SQL being executed was: SELECT COUNT(*) FROM (SELECT `notification`.*, count(distinct(originator_user_id)) as group_count, max(created_at) as group_created_at, min(seen) as group_seen FROM `notification` WHERE ((`seen`=0) OR (`seen` IS NULL)) AND (`user_id`=1) GROUP BY COALESCE(group_key, id), `class` ORDER BY `group_seen`, `group_created_at` DESC) `c`

 Caused by: PDOException
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'abantu.notification.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/1777
