### ISSUE TITLE
cron hourly failed after Update to 1.1.0-beta.2

### ISSUE THREAD

**Issue by nguyen-matthias** [humhub/humhub#1902]
After the fix from Issue "cron hourly failed #1819" @MatthiasHertel
I got this issue again after a update..... Same Problem with code:

`yii\base\ErrorException: Undefined index: memberof in E:\xampp\htdocs\protected\modules\enterprise\modules\ldap\authclient\ZendLdapClientEnterprise.php:69
Stack trace:
#0 E:\xampp\htdocs\protected\modules\enterprise\modules\ldap\authclient\ZendLdapClientEnterprise.php(69): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'E:\\xampp\\htdocs...', 69, Array)
#1 [internal function]: humhub\modules\enterprise\modules\ldap\authclient\ZendLdapClientEnterprise->onUpdateUser(Object(yii\web\UserEvent))
#2 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Component.php(541): call_user_func(Array, Object(yii\web\UserEvent))
#3 E:\xampp\htdocs\protected\humhub\modules\user\authclient\AuthClientHelpers.php(119): yii\base\Component->trigger('update', Object(yii\web\UserEvent))
#4 E:\xampp\htdocs\protected\humhub\modules\user\authclient\ZendLdapClient.php(324): humhub\modules\user\authclient\AuthClientHelpers::updateUser(Object(humhub\modules\enterprise\modules\ldap\authclient\ZendLdapClientEnterprise), Object(humhub\modules\user\models\User))
#5 E:\xampp\htdocs\protected\humhub\modules\user\Events.php(138): humhub\modules\user\authclient\ZendLdapClient->syncUsers()
#6 [internal function]: humhub\modules\user\Events::onHourlyCron(Object(yii\base\Event))
#7 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Event.php(205): call_user_func(Array, Object(yii\base\Event))
#8 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Component.php(549): yii\base\Event::trigger('humhub\\commands...', 'hourly', Object(yii\base\Event))
#9 E:\xampp\htdocs\protected\humhub\commands\CronController.php(41): yii\base\Component->trigger('hourly')
#10 [internal function]: humhub\commands\CronController->actionHourly('>/dev/null', '2>&1')
#11 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#12 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#13 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('hourly', Array)
#14 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('hourly', Array)
#15 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('cron/hourly', Array)
#16 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('cron/hourly', Array)
#17 E:\xampp\htdocs\protected\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#18 E:\xampp\htdocs\protected\yii(29): yii\base\Application->run()
#19 {main}`

But now i find the problem self but i can't solve that T_T

If i disable (Administration) Users>Settings>LDAP "automatically update user" the cron hourly job works.

Can someone help me, please?

![issue cronjob](https://cloud.githubusercontent.com/assets/16917852/17379166/6c14d4c0-59c1-11e6-9b2e-f0f19b037187.JPG)

**Comment by luke-** [comment]
Should be fixed in the latest Enterprise Edition module.
