### ISSUE TITLE
Exception – yii\base\Exception

### ISSUE THREAD

**Issue by LeonidLyalin** [humhub/humhub#1903]
Hi!

Apache/2.4.18 (Unix) PHP/5.5.36
OS X Captain 10.11.6
MySQL 5.7.14
humhub 1.0-2.1
Safari 9.1.2

http://localhost/humhub-1.0-2.1/
![2016-08-04 10 54 50](https://cloud.githubusercontent.com/assets/15928483/17394472/56aa7044-5a3a-11e6-9be4-d3ec06e29dda.png)

Error message:

http://localhost/humhub-1.0-2.1/
Exception – yii\base\Exception

Failed to create directory "/Library/WebServer/Documents/humhub-1.0-2.1/protected/runtime/logs": mkdir(): Permission denied
↵
Caused by: yii\base\ErrorException

mkdir(): Permission denied

in /Library/WebServer/Documents/humhub-1.0-2.1/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php at line 483

**Comment by buddha87** [comment]
I think you forgot to set the file permissions as described here: https://www.humhub.org/docs/guide-admin-installation.html#setting-up

**Comment by LeonidLyalin** [comment]
Yes, you are right! 
Thank you!
