### ISSUE TITLE
Warning: humhub/installer/protected/vendor/autoload.php): failed to open stream: No such file or directory in 

### ISSUE THREAD

**Issue by LeonidLyalin** [humhub/humhub#1904]
Hi!

Apache/2.4.18 (Unix) PHP/5.5.36
OS X Captain 10.11.6
MySQL 5.7.14
humhub 1.0-2.1
Safari 9.1.2

http://localhost/humhub
![2016-08-04 12 41 54](https://cloud.githubusercontent.com/assets/15928483/17397461/411b9cda-5a49-11e6-95c8-d4ba25df5713.png)
/

Warning: require(/Library/WebServer/Documents/humhub/installer/protected/vendor/autoload.php): failed to open stream: No such file or directory in /Library/WebServer/Documents/humhub/installer/index.php on line 13

Fatal error: require(): Failed opening required '/Library/WebServer/Documents/humhub/installer/protected/vendor/autoload.php' (include_path='.:') in /Library/WebServer/Documents/humhub/installer/index.php on line 13

**Comment by buddha87** [comment]
If you try to install a git branch follow the installation instructions, you probably forgot to run a composer update: https://www.humhub.org/docs/guide-admin-installation.html#via-gitcomposer
