### ISSUE TITLE
How to make link list & wiki module available for guest visitor

### ISSUE THREAD

**Issue by primantok** [humhub/humhub#1908]
Hi all,

Any advise how to make link list & wiki module available for guest visitor (non-logged in user) similar to pool module?

HumHub version: 1.1.0-beta.2
Module version: latest (installed from module admin page)

Thanks

**Comment by 001101** [comment]
Same question here and I really don't understand why the permission settings not working correctly.
Hub is set to visible to guests and one space is set also to public and a wikipage as default, but I just get "no public content available"

Not nice to see this in Search Engines and not a friendly welcome to guests....

**Comment by luke-** [comment]
This requires an enhancement of the wiki module. At the moment all wiki pages are always private content and only accessible by space members.

You can create and feature request in the wiki module for that:
https://github.com/humhub/humhub-modules-wiki/issues
