### ISSUE TITLE
Disable follow and unfollow

### ISSUE THREAD

**Issue by seba6196** [humhub/humhub#1911]
Hi every one

I have a problem with Humhub.
I've got Humhub down on my web space and so on. But the problem is that the user must follow other users to see what is being put up. Can it be made such that all users are not able to follow and unfollow. But that all users just follow each other from the start, they are created so that everyone can see everyone's postings on Dashboard.

**Comment by bambooLoutre** [comment]
+1, very useful for small networks

**Comment by motohub1** [comment]
+1, this would be great...too many users for new users to follow each one at this point

**Comment by luke-** [comment]
Integrated since 1.2+
