### ISSUE TITLE
Names in header got cropped

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#1914]
Hello,

having noticed that names with for example g or y got cut from something.

Have tried to resolve it in inspector, but could not find the value.

Have just changed colors and nothing about text or text size.

greets

![2016-08-08_051127](https://cloud.githubusercontent.com/assets/8197408/17468299/df664ec8-5d26-11e6-9b56-a8151e1fbebe.png)

**Comment by primantok** [comment]
Did you use custom theme in your HumHub apps?

Please try to adjust text spacing (line height) & text size.

Example:
font-size: 14px;
line-height: 16px;
display: block (or inline-block)

If this not solved your problem, try to adjust the container height.
Example:
<div style="min-height:20px"><p style="font-size: 14px;line-height: 16px;display:block;>Title</p></div>

HTH

**Comment by primantok** [comment]
Sorry my code example truncate because wrong markdown sintax

```html
<div style="min-height:20px">
    <p style="font-size: 14px; line-height: 16px; display: block">
        Title
    </p>
</div>
```

If this method worked, then copy this inline styling to your css file.

**Comment by 001101** [comment]
Sure, but just copied and changed fast some colors in .css
Did not make any changes on text, as I said.

On which selector I should activate your suggestion?
Not working on given div class 'col-md-12'

**Comment by buddha87** [comment]
Depending on the stylesheet you are changing perhaps you have to clear the cache of your site.

**Comment by 001101** [comment]
As I said, have just changed the colors, nothing more. 
And I have changed the color in the profile banner with Photoshop color change, so I didn't make any changes about size of banner, text or box model attributes. 

Cache clearing not working.

**Comment by 001101** [comment]
I have fixed it!

theme.css
Was:
.panel-profile .panel-profile-header .img-profile-data h2.space {overflow:hidden;}

Should be
.panel-profile .panel-profile-header .img-profile-data h2.space {overflow:**visible**;}
