### ISSUE TITLE
redirect to a custom page

### ISSUE THREAD

**Issue by MatthiasHertel** [humhub/humhub#1915]
can i set the defaultRoute in:
humhub/protected/humhub/config/web.php

```
'defaultRoute' => '/dashboard/dashboard',
```

to a custom page like ?

```
'defaultRoute' => '/index.php?r=custom_pages%2Fview&id=2',
```

my problem is that i want to redirect the request to a custom page ... eg. open humhub with open session in a new tab ... the routing is still set to dashboard ... i want to route to my custom page... 

here i got a request on `192.168.33.22` and humhub route me to the dashboard but i want to route to my custom landing page ...

![image](https://cloud.githubusercontent.com/assets/8426566/17374380/9f429158-59ac-11e6-84fa-d7805c358d36.png)

is it possible ?

**Comment by 001101** [comment]
I have no idea if it can work, maybe it's not the besst way to archive your goal, could break something. BUT try and error makes always fun and smarter :dancers: 

You can define custom rules, which could help you?
http://www.yiiframework.com/doc/guide/1.1/de/topics.url

**Comment by MatthiasHertel** [comment]
your link is yii 1.1 ? ... is it correct ... not yii 2.* ?

**Comment by MatthiasHertel** [comment]
ok i fixed that with a simple if clause in the index.php

but it is just a hack - it would be nice to set the feature in administration menu from humhub 

```php
if ($_SERVER[REQUEST_URI]=='/') {
  // set the new header location and die
  $newURL = 'uritocustompage';
  header('Location: '.$newURL);
  die();
}
```

**Comment by marc-fun** [comment]
Works, but is they nothing better than writing in the index.php file ?

**Comment by buddh4** [comment]
Perhaps this helps https://github.com/humhub/humhub/issues/1828

**Comment by funkycram** [comment]
@buddh4 this post explain how to customize the landing page after a user logins, but not how to change the redirection of / actually configured to /dashboard to an other customized page.

And I didn't found any possibility to change the landing page after a user registers (adding the `returnUrl` in `protected/config/web.php` works only after login).

Thanks

**Comment by alexraynes** [comment]
Hello guys please I need someone help here , how can I send my user to login/register page when the person browse my humhub site for example www.example.com  am geting little pain in the but, all my user are accessing the dashboard%2Fdashboard with out getting directed to /user/auth/login  an using  Humhub 1.2.3 version please  help

**Comment by welgamas** [comment]
i am beginner to program.!
can i add to display group name and png image on profile top menu bar and user post. how can i customize this. can i help me any one.
