### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'obsolete_target_object_model'; check that column/key exists The SQL being executed was: ALTER TABLE `notification` DROP COLUMN `obsolete_target_object_model`

### ISSUE THREAD

**Issue by michaelgeisler** [humhub/humhub#1919]
I tryed to install humhun but i still get this error message:

Database Exception – yii\db\Exception
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'obsolete_target_object_model'; check that column/key exists
The SQL being executed was: ALTER TABLE `notification` DROP COLUMN `obsolete_target_object_model`
Error Info: Array
(
    [0] => 42000
    [1] => 1091
    [2] => Can't DROP 'obsolete_target_object_model'; check that column/key exists
)
↵
Caused by: PDOException 
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'obsolete_target_object_model'; check that column/key exists
in C:\Inetpub\vhosts\noverserver.de\httpdocs\protected\vendor\yiisoft\yii2\db\Command.php at line 844

**Comment by 001101** [comment]
provide information about system, try to use download version instead of github

**Comment by buddha87** [comment]
Which mysql version and which DB engine are you using InnoDB or MyISam?

**Comment by michaelgeisler** [comment]
My mysql Version is 5.6.26. 
I retryed it with a difrent database an new installation and now im getting an other Error
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'contentcontainer_id'
The SQL being executed was: ALTER TABLE `content` ADD `contentcontainer_id` int(11)
Error Info: Array
(
    [0] => 42S21
    [1] => 1060
    [2] => Duplicate column name 'contentcontainer_id'
)
↵
Caused by: PDOException 
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'contentcontainer_id'
in C:\Inetpub\vhosts\noverserver.de\httpdocs\protected\vendor\yiisoft\yii2\db\Command.php at line 844

**Comment by michaelgeisler** [comment]
I'm using Windows Server with plesk and the plesk mysql database.

**Comment by buddha87** [comment]
what are your installation steps? Such errors normally occure if you run a migration twice.

**Comment by michaelgeisler** [comment]
First I copy the files on the server and check the php.ini then I create the database and after that I run the setup
