### ISSUE TITLE
module "Custom Pages" can't install

### ISSUE THREAD

**Issue by viva-chegevara** [humhub/humhub#1923]
hello friends! humhub very cool :)
a can't install module Custom Pages
all other module good update and install
test on 1.1.0-beta.1 and 1.1.0-beta.2

**Comment by buddha87** [comment]
please open an issue on the modules repository: https://github.com/humhub/humhub-modules-custom-pages and provide some additional information as the errormessage which should be logged under "Administration -> Information -> Logging"
