### ISSUE TITLE
Cronjobs not working

### ISSUE THREAD

**Issue by AresAllen** [humhub/humhub#1925]
I was given these two cronjob codes to put into my cpanel but when I copy and paste them in there they won't work cpanel says invalid entry.

These are the codes. 
Crontab of user: 
30 \* \* \* \* /home/vol2_1/rf.gd/rfgd_18733973/epeepz.com/htdocs/protected/yii cron/hourly >/dev/null 2>&1
00 18 \* \* \* /home/vol2_1/rf.gd/rfgd_18733973/epeepz.com/htdocs/protected/yii cron/daily >/dev/null 2>&1

PLEASE HELP

**Comment by 001101** [comment]
then try to resolve the correct paths, its basic linux stuff and not worth posting it on issues, your wasting the mods energy

**Comment by AresAllen** [comment]
*it's , *you're

**Comment by 001101** [comment]
learn linux and dont try to correct me!!!

**Comment by tomtomsen** [comment]
its probably the blank in your path. have you tried to surround them with quotes (")

30 * * * * "/home/vol2_1/rf.gd/rfgd_18733973/epeepz.com/htdocs/protected/yii cron/hourly" >/dev/null 2>&1
