### ISSUE TITLE
Publish and upload buttons not displaying on iOS / Android

### ISSUE THREAD

**Issue by scienceapps** [humhub/humhub#1930]
This happens randomly. When I click on "What's on your mind" input text, Upload and Publish buttons don't display. I have to reload the page to make it work.

Is there a way to change code to display Publish and Upload buttons at page load, that would avoid the problem ?

Thanks !

OS : iOS 9, Android 4.4 & 5

**Comment by 001101** [comment]
Same is on Opera WIndows, but they appear when i click outside the box and again in.
