### ISSUE TITLE
&amp shown in space title

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#1931]
Hello,

just noticed another not so nice bug, when i am on a user profile and hovering over the miniature pictures of the spaces the '&' char is shown as HTML char '&amp'

BUT it is the only scenario where I found that behavior, no big thing I hope :)

greets

![and](https://cloud.githubusercontent.com/assets/8197408/17713877/730aee72-63fd-11e6-84be-f654b2191f45.jpg)

**Comment by green-coder** [comment]
There is also the same problem when the '<' and '>' characters are inside markdown's formatted block : They show up as "&lt;" and "&gt;" on the end user reading the wiki.
