### ISSUE TITLE
 Sometimes notification letters are duplicated

### ISSUE THREAD

**Issue by zhelyabuzhsky** [humhub/humhub#1932]
Sometimes I receive duplicated letters simultaneously. Why?

**Comment by 001101** [comment]
Have the same issue today, I think this are changed posts, can you verify it?

**Comment by zhelyabuzhsky** [comment]
No, e.g. letter about joining to the space

**Comment by buddha87** [comment]
Is this the same behaviour as in https://github.com/humhub/humhub/issues/1936?
Which kind of notifications are affected?

**Comment by zhelyabuzhsky** [comment]
For example joining to the space
