### ISSUE TITLE
Wrong members link on directory?

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#1937]
Hello,

have found a possible wrong link in the Directory, when i go to **http://URL/directory/directory/groups**, which is default route from menuitem 'directory', i have the link **zeige alle Mitglieder** (show all members), but it brings me to this **http://URL/directory/members?keyword=&groupId=1** and only show a few users instead of all and the pagiation on bottom isn't available.

Why not simply link to **http://URLS/directory/members** as it is on the left menu point?

greets

**Comment by buddha87** [comment]
I think this button is used to view all members of a specific group in case there are more than a certain amount of member in this group. E.g if your group has hundreds of users they won't be all visible in the directory group overview.

**Comment by 001101** [comment]
But i just have one group (except admins and mods), that's users...

**Comment by buddha87** [comment]
If you have more than one group marked with "Show At Directory" the group view is shown in the directory, otherwise the members view is the default directory view. Note that only groups with existing members and the setting "Show At Directory" are listed in this view

**Comment by 001101** [comment]
Ahh, thanks, had also mods enabled to show, now it looks better :)
Would be very good if there would be a settings tab for the directory, like setup a seperate directory page (with new custom pages templates surly a very good thing) and decide if spaces or members should be startpage, because some users don't get the space thing very quick and so they see directly the spaces :)
