### ISSUE TITLE
Additional breaks in posts/comments (Richtext)

### ISSUE THREAD

**Issue by buddha87** [humhub/humhub#1942]
There are additional breaks (2 breaks instead of one) in posts and comments and an additional break after links.

**Comment by wolfmarco** [comment]
I have the same problem with 

- HumHub Version 1.1.0
- PHP Version 5.5.9

![post](https://cloud.githubusercontent.com/assets/3786816/17880064/4801131a-68f7-11e6-9b78-84d1ed544528.png)

![result](https://cloud.githubusercontent.com/assets/3786816/17880067/4d8b0976-68f7-11e6-8b3e-c7d155942e94.png)
