### ISSUE TITLE
Can't log in (first time) as administrator

### ISSUE THREAD

**Issue by LeonidLyalin** [humhub/humhub#1948]
Database Exception – yii\db\Exception
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'humhub.notification.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
The SQL being executed was: SELECT COUNT(*) FROM (SELECT `notification`.*, count(distinct(originator_user_id)) as group_count, max(created_at) as group_created_at, min(seen) as group_seen FROM `notification` WHERE ((`seen`=0) OR (`seen` IS NULL)) AND (`user_id`=1) GROUP BY COALESCE(group_key, id), `class` ORDER BY `group_seen`, `group_created_at` DESC) `c`
Error Info: Array
(
    [0] => 42000
    [1] => 1055
    [2] => Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'humhub.notification.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
)
↵
Caused by: PDOException
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'humhub.notification.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 900
* 		1. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/db/Schema.php at line 633                        624 625 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642  
* 		        $exceptionClass = '\yii\db\Exception';
* 		        foreach ($this->exceptionMap as $error => $class) {
* 		            if (strpos($e->getMessage(), $error) !== false) {
* 		                $exceptionClass = $class;
* 		            }
* 		        }
* 		        $message = $e->getMessage()  . "\nThe SQL being executed was: $rawSql";
* 		        $errorInfo = $e instanceof \PDOException ? $e->errorInfo : null;
* 		        return new $exceptionClass($message, $errorInfo, (int) $e->getCode(), $e);
* 		    }
* 		 
* 		    /**
* 		     * Returns a value indicating whether a SQL statement is for read purpose.
* 		     * @param string $sql the SQL statement
* 		     * @return boolean whether a SQL statement is for read purpose.
* 		     */
* 		    public function isReadQuery($sql)
* 		    {
* 		 
* 		2. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 915  – yii\db\Schema::convertException(PDOException, 'SELECT COUNT(*) FROM (SELECT `no...')  
* 		3. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 388  – yii\db\Command::queryInternal('fetchColumn', 0)  
* 		4. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/db/Query.php at line 398  – yii\db\Command::queryScalar()  
* 		5. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php at line 334  – yii\db\Query::queryScalar('COUNT(*)', null)  
* 		6. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/db/Query.php at line 300  – yii\db\ActiveQuery::queryScalar('COUNT(*)', null)  
* 		7. in /Library/WebServer/Documents/humhub/protected/humhub/modules/notification/controllers/ListController.php at line 108  – yii\db\Query::count()                 102 103 104 105 106 107 108 109 110 111 112 113 114  
* 		        $query = Notification::findGrouped()
* 		                ->andWhere(['seen' => 0])
* 		                ->orWhere(['IS', 'seen', new \yii\db\Expression('NULL')])
* 		                ->andWhere(['user_id' => $user->id]);
* 		 
* 		        $update['newNotifications'] = $query->count();
* 		        $query->andWhere(['desktop_notified' => 0]);
* 		 
* 		        $update['notifications'] = array();
* 		        foreach ($query->all() as $notification) {
* 		            if (Yii::$app->getModule('notification')->settings->user()->get("enable_html5_desktop_notifications", Yii::$app->getModule('notification')->settings->get('enable_html5_desktop_notifications'))) {
* 		                $update['notifications'][] = $notification->getClass()->render(BaseNotification::OUTPUT_TEXT);
* 		 
* 		8. in /Library/WebServer/Documents/humhub/protected/humhub/modules/notification/widgets/Overview.php at line 31  – humhub\modules\notification\controllers\ListController::getUpdates()                 25 26 27 28 29 30 31 32 33 34 35 36 37     public function run()
* 		    {
* 		        if (Yii::$app->user->isGuest)
* 		            return;
* 		 
* 		        return $this->render('overview', array(
* 		                    'update' => \humhub\modules\notification\controllers\ListController::getUpdates(),
* 		                    'updateInterval' => Yii::$app->getModule('notification')->pollClientUpdateInterval
* 		        ));
* 		    }
* 		 
* 		}
* 		 
* 		 
* 		9. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/base/Widget.php at line 102  – humhub\modules\notification\widgets\Overview::run()  
* 		10. in /Library/WebServer/Documents/humhub/protected/humhub/widgets/BaseStack.php at line 92  – yii\base\Widget::widget([])                 86 87 88 89 90 91 92 93 94 95 96 97 98         $i = 0;
* 		        foreach ($this->getWidgets() as $widget) {
* 		            $i++;
* 		 
* 		            $widgetClass = $widget[0];
* 		 
* 		            $out = $widgetClass::widget($widget[1]);
* 		 
* 		            if ($out != "") {
* 		                $content .= $out;
* 		                if ($i != count($this->getWidgets()))
* 		                    $content .= $this->seperator;
* 		            }
* 		 
* 		11. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/base/Widget.php at line 102  – humhub\widgets\BaseStack::run()  
* 		12. in /Library/WebServer/Documents/humhub/protected/humhub/views/layouts/main.php at line 101  – yii\base\Widget::widget(['widgets' => [['humhub\modules\notification\widg...', [], ['sortOrder' => 10]]]])                 95 96 97 98 99 100 101 102 103 104 105 106 107  
* 		                <div class="notifications pull-right">
* 		 
* 		                    <?php
* 		                    echo \humhub\widgets\NotificationArea::widget(['widgets' => [
* 		                            [\humhub\modules\notification\widgets\Overview::className(), [], ['sortOrder' => 10]],
* 		                    ]]);
* 		                    ?>
* 		 
* 		                </div>
* 		 
* 		            </div>
* 		 
* 		 
* 		13. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 325  – require('/Library/WebServer/Documents/hum...')  
* 		14. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 247  – yii\base\View::renderPhpFile('/Library/WebServer/Documents/hum...', ['content' => '<div class="container"> <div...'])  
* 		15. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 393  – yii\base\View::renderFile('/Library/WebServer/Documents/hum...', ['content' => '<div class="container"> <div...'], humhub\modules\dashboard\controllers\DashboardController)  
* 		16. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 379  – yii\base\Controller::renderContent('<div class="container"> <div...')  
* 		17. in /Library/WebServer/Documents/humhub/protected/humhub/modules/dashboard/controllers/DashboardController.php at line 64  – yii\base\Controller::render('index', ['showProfilePostForm' => null])               58 59 60 61 62 63 64 65 66 67 68     {
* 		        if (Yii::$app->user->isGuest) {
* 		            return $this->render('index_guest', array());
* 		        } else {
* 		            return $this->render('index', array(
* 		                        'showProfilePostForm' => Yii::$app->getModule('dashboard')->settings->get('showProfilePostForm')
* 		            ));
* 		        }
* 		    }
* 		 
* 		}
* 		 
* 		18.  humhub\modules\dashboard\controllers\DashboardController::actionIndex()  
* 		19. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55  – call_user_func_array([humhub\modules\dashboard\controllers\DashboardController, 'actionIndex'], [])  
* 		20. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 154  – yii\base\InlineAction::runWithParams([])  
* 		21. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 454  – yii\base\Controller::runAction('', [])  
* 		22. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 87  – yii\base\Module::runAction('', [])  
* 		23. in /Library/WebServer/Documents/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 375  – yii\web\Application::handleRequest(humhub\components\Request)  
* 		24. in /Library/WebServer/Documents/humhub/index.php at line 25  – yii\base\Application::run()           19 20 21 22 23 24 25     require(__DIR__ . '/protected/humhub/config/web.php'),
* 		    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
* 		    require(__DIR__ . '/protected/config/common.php'),
* 		    require(__DIR__ . '/protected/config/web.php')
* 		);
* 		 
* 		(new humhub\components\Application($config))->run();
* 		 
$_COOKIE = [
    'pm_new-people-panel' => 'expanded',
    'pm_new-spaces-panel' => 'expanded',
    'PHPSESSID' => '3njt7gqoir301380k7on3k7jr1',
    '_csrf' => 'af0a4386d0989887bc92c9d8580cbe1edbb226d55acb0cf848d44a5ecf001f17a:2:{i:0;s:5:"_csrf";i:1;s:32:"NsJs0AE6FLtI4JAY5w5Q6MRLX_SANdU0";}',
    '_identity' => '5eb2f304f78894718ef70761b25e805ca3bd1ad8243ed560408db9043ddfe6f1a:2:{i:0;s:9:"_identity";i:1;s:50:"[1,"5e6981ff-0e08-4c46-9a83-7bb0baa432fd",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 1,
    'currentAuthClientId' => 'local',
];
￼
2016-08-21, 18:50:25
Apache/2.4.18 (Unix) PHP/5.6.23
Yii Framework/2.0.9

**Comment by buddha87** [comment]
please see https://github.com/humhub/humhub/issues/1777

**Comment by LeonidLyalin** [comment]
Yes. Thank you!
