### ISSUE TITLE
LDAP with multiple email addresses

### ISSUE THREAD

**Issue by scith** [humhub/humhub#1949]
Hello,
If a LDAP user has several email addresses in the mail attribute, there is a bug in HumHub auth: (database exception, string given). An array of the emails is passed to HumHub, hence the bug

Thanks

**Comment by gvde** [comment]
Just ran into the same problem. User with multiple values for the mail attribute will break the sync:

> Exception 'yii\db\Exception' with message 'PDOStatement::bindValue() expects parameter 3 to be long, string given
Failed to prepare SQL: INSERT INTO `user` (`username`, `email`, `guid`, `language`, `auth_mode`, `last_activity_email`, `status`, `time_zone`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (:qp0, :qp1, :qp2, :qp3, :qp4, NOW(), :qp5, :qp6, NOW(), :qp7, NOW(), :qp8)'
>
> in /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/db/Command.php:231

**Comment by nils-van-zuijlen** [comment]
Hello, I think this issue was fixed, I do not need that patch to get HumHub working with multiple emails in my LDAP.

I believe it's thanks to these lines
https://github.com/humhub/humhub/blob/906fc16b66f89623cf1a53ba7e369fe6dee0a7de/protected/humhub/modules/ldap/authclient/LdapAuth.php#L310-L319

**Comment by luke-** [comment]
@nils-van-zuijlen thanks for the hint. That' true, these lines should fix the problem. HumHub will always use the first (primary) email address in such cases.
