### ISSUE TITLE
Calendar notifcations

### ISSUE THREAD

**Issue by Nazort** [humhub/humhub#1952]
Hi i just start with Humhub and I'm trying to add notification when someone create an event and invited you, just like the meetings module.
I read the documentation of the notification and did the same as the like notification.
I tried to add the [Send Notifications](https://www.humhub.org/docs/guide-dev-notifications.html#send-notifications) into calendar/models/CalendarEntryParticipant.php but nothing :/
If you can help me with this...

**Comment by buddha87** [comment]
Did you create an own branch on github? Without your code no one will be able to help you. :)

**Comment by Nazort** [comment]
@buddha87 Thanks you for your answer. I done it [here](https://github.com/Nazort/CalendarHumH)

**Comment by Nazort** [comment]
I just find the problem but i don't really know how to solve it. I was working on other stuff and I understand that it's because I added a new table (Calendar_Parcipant) in the migration initial file but i don't know how can I "push" it to use it after in my code.

Same problem if I add a new member in a table that already exist for example "calendar_entry" and try to use it after in the class CalendarEntry he will just tell me "undefined reference...."

Can someone help me with Migration or how to add table/members?
