### ISSUE TITLE
Making Directory private??

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#1954]
Hello,

how can i make the directory not available for guest access, unfortunatly i see now that anyone can look it up without permission.

greets

**Comment by 001101** [comment]
Okay too late, they screaped my total directory and each user!!

United States → District of Columbia → Washington
Operating system (detailed): Linux (other or unknown)
Browser: Safari
Resolution: 800x600

**Comment by markgraf** [comment]
Yes, keeping the directory private would really be appreciated.

So, "Me too!" basically...

**Comment by 001101** [comment]
I mean what the heck, why didn't I get a answer in 10 days, it's a real problem and no one can say me that it is ACL in controller?? 


Solution:

**Changes: /protected/humhub/modules/directory/controllers/DirectoryController.php
**



```

  public function behaviors()
    {
        return [
            'acl' => [
                'class' => \humhub\components\behaviors\AccessControl::className(),
                'guestAllowedActions' => ['groups', 'index', 'members', 'spaces', 'user-posts', 'stream']
            ]
        ];
    }

```

**change to**

```


public function behaviors()
    {
        return [
            'acl' => [
                'class' => \humhub\components\behaviors\AccessControl::className(),
                'guestAllowedActions' => []
            ]
        ];
    }

```

**Comment by markgraf** [comment]
There's an easier way:
Uncheck "Allow limited access for non-authenticated users" in the user settings.

![humhub-privacy](https://cloud.githubusercontent.com/assets/1706270/18212897/e9591d7e-7145-11e6-9152-31f8f604fe9e.png)

NOT displaying members should really be the default here...

**Comment by 001101** [comment]
Not for me, because I want a "snippet" preview of the activity and two posts on the startpage, when I check this anything is private and that don't bring people to register to see more.

**Comment by 001101** [comment]
Addition for module

https://github.com/humhub/humhub-modules-mostactiveusers/issues/11

**Comment by patrikalienus** [comment]
Like you, @001101, I want to display a Custom Page to all guests, but require membership for everything else.
In fact, I'd most like to disable the directory alltogether...

**Comment by 001101** [comment]
> In fact, I'd most like to disable the directory alltogether...

You can't just disable it, because it's the main point where your users have the complete overview of spaces and other users, so it is elementary.

**Comment by 001101** [comment]
thanks for letting me know, good that I still running 1.2.4

I don't get it why underlying access features can easily get overwritten with new features, that is highly inconsistent, it is not the first time and the devs mostly just don't care about such essential security.

**Comment by buddh4** [comment]
You should not overwrite core files. In order to prevent any guest on a controller use this in your "custom" controllers without overwriting the `behaviours` function:

```
    public function getAccessRules()
    {
        return [
             ['login']
        ];
    }
```

In one of the upcoming versions we'll make the directory access and some other parts configurable.

**Comment by vinzBad** [comment]
@buddh4 I think directory access should be hidden by default, I don't want to expose the names of all members

**Comment by vinzBad** [comment]
So I found this in `humhub/modules/directory/Module.php`
```php
    /**
     * @var bool defines if the directory is available for guest users, this flag will only have effect if guest access is allowed and the module is active
     */
    public $guestAccess = false;
```
Can I configure this in `protected/config/common.php`? I'm not used to this type of configuration as explained here: https://www.yiiframework.com/doc/guide/2.0/en/concept-configurations

**Comment by buddh4** [comment]
@vinzBad I've added a guide how to overwrite thoes configurations here: https://github.com/humhub/humhub/blob/master/protected/humhub/docs/guide/admin/advanced-configuration.md#module-configuration
