### ISSUE TITLE
Custom Pages v0.61 - Template - Container add brings json

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#1958]
hello,

on new custom pages v0.61 the function from adding a container to template is not working, brings up json:

{"success":false,"content":"<div class=\"modal-dialog modal-dialog-large\">\r\n    <div class=\"modal-content\">\r\n        <form id=\"h354548w0\" action=\"/custom_pages/template/admin/add-element?template_id=4&amp;content_type=humhub%5Cmodules%5Ccustom_pages%5Cmodules%5Ctemplate%5Cmodels%5CContainerContent\" method=\"post\">\n<input type=\"hidden\" name=\"_csrf\" value=\"WU5paWZoZDAfPQoAAC0qRT4iHRkHXS56N3k9OjQLPmY.BQRbKVsDcQ==\">            <div class=\"modal-header\">\r\n                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n                <h4 class=\"modal-title\" id=\"myModalLabel\">\r\n                   <strong>Add</strong> new Container element                </h4>\r\n            </div>\r\n            <div class=\"modal-body\">\r\n                <div class=\"clearfix\">\r\n                                        <small class=\"pull-right\">\r\n                        <span class=\"label label-success\">Container</span>\r\n                    </small>\r\n                </div>\r\n                \r\n                                    <div class=\"form-group field-templateelement-name required has-error\">\n<label class=\"control-label\" for=\"templateelement-name\">Element name</label>\n<input type=\"text\" id=\"templateelement-name\" class=\"form-control\" name=\"TemplateElement[name]\" value=\"Webmail\">\n\n<div class=\"help-block\">The given element name is already in use for this template.</div>\n</div>                                \r\n                                \r\n                \r\n    <hr class=\"hr-text\" data-content=\"Default Content\">\r\n                \r\n                \r\n<div class=\"form-group field-templateelement-name\">\r\n<label class=\"control-label\" for=\"templateelement-name\">Allowed Templates</label>\r\n<select class=\"form-control multiselect_dropdown\" name=\"ContainerContent[definitionPostData][allowedTemplateSelection][]\" multiple=\"\" size=\"4\" style=\"style=&quot;width: 100%&quot;\">\n<option value=\"3\">webmail-login</option>\n</select></div>\r\n\r\n<div class=\"form-group field-containercontent-definitionpostdata-allow_multiple\">\n\n<input type=\"hidden\" name=\"ContainerContent[definitionPostData][allow_multiple]\" value=\"0\"><label><input type=\"checkbox\" id=\"containercontent-definitionpostdata-allow_multiple\" name=\"ContainerContent[definitionPostData][allow_multiple]\" value=\"1\" checked> Allow Multiple</label>\n\n<div class=\"help-block\"></div>\n</div>\r\n<div class=\"form-group field-containercontent-definitionpostdata-is_inline\">\n\n<input type=\"hidden\" name=\"ContainerContent[definitionPostData][is_inline]\" value=\"0\"><label><input type=\"checkbox\" id=\"containercontent-definitionpostdata-is_inline\" name=\"ContainerContent[definitionPostData][is_inline]\" value=\"1\" checked> Inline</label>\n\n<div class=\"help-block\"></div>\n</div>\r\n<script>\r\n    checkForMultiSelectDropDowns();\r\n</script>                \r\n                                \r\n            </div>\r\n            <div class=\"modal-footer\">\r\n                                <button id=\"editTemplateSubmit\" class=\"btn btn-primary\" data-ui-loader>Save</button>\r\n                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">Cancel</button>\r\n                            </div>\r\n        </form>    </div>\r\n</div>\r\n\r\n<script type=\"text/javascript\">\r\n    $('#editTemplateSubmit').on('click', function (evt) {\r\n        evt.preventDefault();\r\n        \r\n        var $form = $(this).closest('form');\r\n        var action = $form.attr('action');\r\n\r\n        $('textarea.ckeditorInput').each(function () {\r\n            var $textarea = $(this);\r\n            $textarea.val(CKEDITOR.instances[$textarea.attr('id')].getData());\r\n         });\r\n\r\n        $.ajax(action, {\r\n            type: 'POST',\r\n            dataType: 'json',\r\n            data: $form.serialize(),\r\n            success: function (json) {\r\n                for(name in CKEDITOR.instances)\r\n                {\r\n                    CKEDITOR.instances[name].destroy(true);\r\n                }\r\n                if(json.success) {\r\n                    $(document).trigger('templateElementEditSuccess', [json]);\r\n                } else {\r\n                    $('#globalModal').html(json.content);\r\n                }\r\n            },\r\n            error: function () {\r\n                $(document).trigger('templateElementEditError');\r\n            }\r\n        });\r\n    });\r\n    \r\n    </script>","name":"Webmail","id":null}

using beta2, windows 8.1, newest opera

can this please be tested a bit longer until it works?

greets

**Comment by buddha87** [comment]
Hi,

1. Please open a ticket in the modules repository https://github.com/humhub/humhub-modules-custom-pages

2. Provide some additional information about how to reproduce the problem (Step by Step)

3. I suggest upgrading to v1.1 stable, since there are some issues with the templating feature and this beta version.
