### ISSUE TITLE
Share content inside HumHub

### ISSUE THREAD

**Issue by alirezastack** [humhub/humhub#196]
I couldn't find a share link! Can we share something on our space/dashboard?

**Comment by WASasquatch** [comment]
Any update on planned features for this? Would be really awesome to start networking spaces from within our networks easier then users simply having to have the idea in their head to search for the space. Discovery is a awesome way to find stuff.

**Comment by indrasandika** [comment]
how want add fiture share in humhub?

**Comment by indrasandika** [comment]
what the status of the modules share a friend to our profile and our dashboard ??? if there is please to share

**Comment by indrasandika** [comment]
you have module share humhub.?

**Comment by indrasandika** [comment]
exemple: friend status will in share with our ....

**Comment by saurabhchris1** [comment]
Please add share inside humhub feature

**Comment by vipul1994** [comment]
Any update on the share feature internal to the humhub platform.

**Comment by flaugere** [comment]
I think there's a repo in development : https://github.com/humhub/humhub-modules-sharebetween
