### ISSUE TITLE
Urgent problem signing in with LDAP user after upgrading to 1.1

### ISSUE THREAD

**Issue by djcf** [humhub/humhub#1961]
Hi Humhub team. We've recently updated to 1.1. Great work on fixing the LDAP bug where users couldn't log in with their email addresses! But it looks like the new ZendLDAPClient auth library may have caused some more problems, at least with older users. Whenever a user logs in, they get the error "Could not automatically determine unique user ID from LDAP node" from line 195 in ./protected/humhub/modules/user/authclient/ZendLdapClient.php.

It looks to me like this is caused by code which checks the LDAP $attributes array within the getUserAttributes function which returns an aray list of user attributes. It seems to be checking for the existence of a key named objectguid, but none exists on the users I've tried with. There _is_ a key named entryuuid which seems to hold the Humhub's user UUID. All of the other attributes seem to be populated without problem. I did try changing the code to also accept the 'entryuuid' key as a substitute for 'objectguid', but without any luck. What am I doing wrong?

Thanks so much in advance,

Daniel

`
            if (isset($attributes['objectguid'])) {
                $this->idAttribute = 'objectguid';
                $this->userTableIdAttribute = 'guid';
            } /*elseif (isset($attributes['entryuuid'])) {
                $this->idAttribute = 'entryuuid';
                $this->userTableIdAttribute = 'guid';
            } */elseif (isset($attributes['mail'])) {
                $this->idAttribute = 'mail';
                $this->userTableIdAttribute = 'email';
            } else {
                throw new \yii\base\Exception("Could not automatically determine unique user id from ldap node!");
            }
`

**Comment by djcf** [comment]
Ah, I was able to fix it by forcing the attribute lookup to use the username key. This is surprising because I believe the settings in the admin control panel to be correct, leastways they have not changed during the update. For the curious, here is my fix:

`elseif (isset($attributes['uid'])) {
                        $this->idAttribute = 'uid';
                        $this->userTableIdAttribute = 'username';
               } ` (line 205, ZendLdapClient.php)

**Comment by tjmidnight** [comment]
Any chance you could give a bit more information? Even a larger snippet of where you placed that addition would be great, as line 205 of ZendLdapClient.php has apparently changed since the end of August, as it appears as the end of a comment (@return Node the users ldap node) for me. Thanks in advance for any help you can give.

**Comment by djcf** [comment]
I'm not sure if my earlier response is in error, or if my file changed substantially since I opened this issue. Most likely the latter. In any case, here is the ZendLdapClient.php which I have been using with the fix/workaround for the bug. My changes are on line 185:

`            } elseif (isset($attributes['uid'])) {
        		$this->idAttribute = 'uid';
        		$this->userTableIdAttribute = 'username';
	       }`
[ZendLdapClient.php.txt](https://github.com/humhub/humhub/files/679864/ZendLdapClient.php.txt)

**Comment by Felli** [comment]
@djcf Using that will break the Prerequisites tab in Information, I suggest using `} elseif (isset($attributes['uid'])) { $this->idAttribute = 'uid'; $this->userTableIdAttribute = 'username';` only so not to break and cause an error on line 191. :+1:

**Comment by djcf** [comment]
Good to know! Thanks for that, will make the change.

**Comment by valentin-vogel** [comment]
I get the same error message "Could not automatically determine unique user id from ldap node!" on ldap sync by hourly cron command.

**Comment by Felli** [comment]
@valentin-vogel have you already tried #2184 ?
