### ISSUE TITLE
PHP Core Dump by Changing a Single Line of Code

### ISSUE THREAD

**Issue by backstageel** [humhub/humhub#1963]
Just a reference for anyone o gets this error too:

I have this line of code as a parte of a Humhub(Yii) application:

```
    if ($this->isSpaceOwner($this->getMembership()->user_id)) {
        return self::USERGROUP_OWNER;
    }
```

and when opening the page, i got Error 500 in Apache and Core Dumped on PHP-FPM. The issue gets resolved by changing this code to:

$membership = $this->getMembership()->user_id;
        if ($this->isSpaceOwner($membership)) {
            return self::USERGROUP_OWNER;
        }
Is there any logical difference in this two snippets? Is chaining methods inside method call not allowed in PHP? I'm confused.

For the record, $this->getMembership()->user_id; returns 38 and in the first snippet the isSpaceOwner doesnt get even executed!

https://ma.ttias.be/generate-php-core-dumps-segfaults-php-fpm/

**Comment by cebe** [comment]
this should not happen and seems to be a bug in PHP, that should be reported to PHP if there is a way to reproduce it. Which PHP version are you using?

**Comment by backstageel** [comment]
PHP 7.0.8
