### ISSUE TITLE
Custom Pages - icons list enhancement

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#1964]
Hello,

i am very annoyed of scrolling the huge list for the menu items for the custom pages, it would be thousand times better if the icons just come up as the smilies without the names or if there are names (what would also be good), then please without the fa- in front of, so you could just press a button and go to the first letter.

thanks!!

**Comment by buddha87** [comment]
duplicate https://github.com/humhub/humhub-modules-custom-pages/issues/35
