### ISSUE TITLE
"Likes" notifications in 1.1.0

### ISSUE THREAD

**Issue by CCRS-WEB** [humhub/humhub#1966]
Hello,

I've installed humhub 1.1.0, now there's no more notifications and email for "likes" on posts and comments.

Regards,

**Comment by CCRS-WEB** [comment]
Found that this is a feature
https://github.com/humhub/humhub/commit/c0fa2ab8d68a14e646262fd484b689b461069af1

Would be nice, it could be configurable to choose options for like Notification

**Comment by buddh4** [comment]
Should be available in 1.2
