### ISSUE TITLE
Post from dashboard

### ISSUE THREAD

**Issue by aliogul** [humhub/humhub#1970]
Hi,

Is it possible to put post form on dashboard/homepage so the users can post directly without going to their profile?

**Comment by cebe** [comment]
The Dashboard summarizes posts from multiple places. Where should posts appear that are posted form the Dashboard?

**Comment by aliogul** [comment]
This is what i mean actually . I hope it s clear. 
![untitled-4](https://cloud.githubusercontent.com/assets/10399011/18130155/96d1e000-6f96-11e6-9d00-d617ce83feed.png)

**Comment by buddha87** [comment]
This already exists, but you have to activate it under Administration -> Settings -> General -> Show user profile post form on dashboard

**Comment by aliogul** [comment]
Thank you Buddha87. You made me feel stupid :)

I missed that option.

Thanks
