### ISSUE TITLE
Directory Search fails for some keywords

### ISSUE THREAD

**Issue by simon-roderus** [humhub/humhub#1971]
The directory search works for most search terms, but I found a specific search term ("IN") where it leads to an internal failure.

Steps to reproduce:
- Open the Directory
- Search for ("IN")

![fehlermeldung](https://cloud.githubusercontent.com/assets/9551133/18131682/04e3b8b4-6f94-11e6-91e7-79af5ef87dbc.PNG)

**Comment by buddha87** [comment]
Could not reproduce this. Please check the logs for errors.

**Comment by simon-roderus** [comment]
Thank you for trying to reproduce the error. As you suggested, the log does provide an answer:

> exception 'ZendSearch\Lucene\Exception\OutOfBoundsException' with message 'Terms per query limit is reached.' in /var/www/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Wildcard.php:183 Stack trace: #0 /var/www/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Boolean.php(132): ZendSearch\Lucene\Search\Query\Wildcard->rewrite(Object(ZendSearch\Lucene\Index)) #1 /var/www/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php(669): ZendSearch\Lucene\Search\Query\Boolean->rewrite(Object(ZendSearch\Lucene\Index)) #2 /var/www/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php(120): ZendSearch\Lucene\Index->find(Object(ZendSearch\Lucene\Search\Query\Boolean)) #3 /var/www/humhub/protected/humhub/modules/directory/controllers/DirectoryController.php(138): humhub\modules\search\engine\ZendLuceneSearch->find('IN', Array) #4 [internal function]: humhub\modules\directory\controllers\DirectoryController->actionSpaces() #5 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('spaces', Array) #8 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('directory/direc...', Array) #9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /var/www/humhub/index.php(25): yii\base\Application->run() #11 {main}

We do have about 20-40 spaces tagged with "IN". However, I believe HumHub should not throw an error for this amount of search results.

**Comment by martinbeek** [comment]
Change 1024 to 2048:

private static $_termsPerQueryLimit = 2048; // was 1024

in ./protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Lucene.php

This solves the problem !

**Comment by Buliwyfa** [comment]
I have the same problem and I have to increase it 10 times no the site is really slow.
