### ISSUE TITLE
Error 500 first access

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#1973]
Hello, I just downloaded the Zip and placed it under http://social.pokemap.com.br/ root folder.
I extracted the zip and moved files from humhub_master to the root folder.

I am using nginx on ubuntu server VPS.

This is my nginx Cfg to this website:

`server {
        listen 80;
        listen [::]:80;

```
    server_name social.pokemap.com.br;

    root /var/www/socialPOKE;
    index index.html index.php;

    location / {
```
# index index.html index.php;

```
            try_files $uri $uri/ =404;
    }
    location ~ \.php$ {
            include snippets/fastcgi-php.conf;
    #
    #       # With php7.0-cgi alone:
    #       fastcgi_pass 127.0.0.1:9000;
    #       # With php7.0-fpm:
            fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location /zionsql {
        alias /usr/share/phpmyadmin;
        index  index.php index.html index.htm;
    }

    location ~ /\.ht {
            deny all;
    }
```

}`

As you can see accessing the refered domain i am getting the following error:
HTTP ERROR 500

I tried a different set of cfgs and permissions over the folders.
I tried 755 and even 777. No results.

I also changed the chown settings of the root folder from www-data to a different user and reversed the action again because i did not had any change.
I'm out of ideas, and i have searched around from a previous scenario which i could not find.

I am seeking to find a solution and i can guarantee i'll update this ticket as soon as i got an answer, but meanwhile if you could help me i would be very greatful.

Sorry for my rushed and probably bad english,
Thanks in advance.

**Comment by uknzaeinozpas** [comment]
I had the same issue, see if you have installed the right php version (5.4+)
