### ISSUE TITLE
Question : context

### ISSUE THREAD

**Issue by Nazort** [humhub/humhub#1975]
Hi, 

I have a question, i'm trying to get the list of the members of a space.
I found this in the space module (humhub/modules/space/views/_layout.php) : 

$space = $this->context->contentContainer;
(give the members list of the current space)

This is just what I need, but I don't really understand what is context ? Because I want to use it on my code.

**Comment by buddh4** [comment]
please ask developement related questions in the community http://community.humhub.com/
