### ISSUE TITLE
post of other user on my wall

### ISSUE THREAD

**Issue by andrerudi95** [humhub/humhub#1979]
Hi! On my version of Humhub I allow other user write post on my profile going in the security option and till here nothing new.
 But when I go in the dashboard i see only the user that have write the post in my profile but no one can Know that the post is on my profile because there is only the image of WHO write the post and not WHERE. I need something like the space. When i write a post in a space, in the dashboard I can see that i write the post in that space because there is the small image and the name of the space where the post is posted. I think I need to edit something in the content view "wall entry" in php...  where there is: `Show space image, if you are outside from a space`   something like 'Show user image, if you are outside from a user' I hope you've understood.  
Like facebook, If i write a post on a user wall in the post there is "my name" to "user name" (where the post is set". 
Thanks for the attention
Andrea

**Comment by helnokaly** [comment]
Try this

```
<!-- show profile owner name -->
<?php if (!Yii::$app->controller instanceof ContentContainerController && $container instanceof User && $object->content->created_by != $object->content->user_id): ?>
    <?php echo Yii::t('ContentModule.views_wallLayout', 'in'); ?> <strong><a
            href="<?php echo $container->getUrl(); ?>"><?php echo Html::encode($container->displayName); ?></a></strong>&nbsp;
<?php endif; ?>
```

**Comment by andrerudi95** [comment]
It doens't work :/ But I think it's not so far to be correct.

2016-09-07 0:37 GMT+02:00 Hany El Nokaly <notifications@github.com>:

**Comment by andrerudi95** [comment]
![asdfsadf](https://cloud.githubusercontent.com/assets/20684466/18304964/a0efc8aa-74e5-11e6-8f7e-0fc9dcd759a4.PNG)

**Comment by andrerudi95** [comment]
Perfect! Thanks.
It will be interesting also add the pics with the name  :)
