### ISSUE TITLE
If we install humhub on NginX how we should config X-sendfile

### ISSUE THREAD

**Issue by alirezastack** [humhub/humhub#198]
As far as I know in NginX we call it X-Accel-Redirect. So we should set a different header for static files. Does anyone have any idea about this? How to do it and where?

I'm pretty sure that I'll gain a much better performance on nginX rather than Apache.

Regards,
Hoseini

**Comment by martinbeek** [comment]
Hi there. Which $options are you referring to?
Where can i make this setting? 

Thanks!
