### ISSUE TITLE
Validate required checkbox in 'Sign up' form. 

### ISSUE THREAD

**Issue by maxdonetsk** [humhub/humhub#1983]
Hi guys, could you help me to validate this form with custom checkbox which I would like to have as required?

It's in login_modal.php:

<?php $form = ActiveForm::begin(); ?>

                        <?php echo $form->field($invite, 'email')->textInput(['id' => 'register-email', 'placeholder' => Yii::t('UserModule.views_auth_login', 'email')]); ?>
                        <?php echo $form->field($invite, 'check')->checkbox(['id' => 'check', 'uncheck' => null])->label(Yii::t('UserModule.views_auth_login', 'I have read and accept') . ' <a href="#">' . Yii::t('UserModule.views_auth_login', 'Terms & Conditions') . '</a> ' . Yii::t('UserModule.views_auth_login', 'and') . ' <a href="#">' . Yii::t('UserModule.views_auth_login', 'Privacy Policy') . '</a>' . '.'); ?>
                        <hr>

                        <?php
                        echo \humhub\widgets\AjaxButton::widget([
                            'label' => Yii::t('UserModule.views_auth_login', 'Register'),
                            'ajaxOptions' => [
                                'type' => 'POST',
                                'beforeSend' => new yii\web\JsExpression('function(){ setModalLoader(); }'),
                                'success' => 'function(html){ $("#globalModal").html(html); }',
                                'url' => Url::to(['/user/auth/login']),
                            ],
                            'htmlOptions' => [
                                'class' => 'btn btn-primary', 'id' => 'registerBtn'
                            ]
                        ]);
                        ?>

                        <?php ActiveForm::end(); ?>

And this is in Invite.php:

return [
            [['user_originator_id', 'space_invite_id', 'created_by', 'updated_by'], 'integer'],
            [['token'], 'unique'],
            [['firstname', 'lastname'], 'string', 'max' => 255],
            [['email', 'source', 'token'], 'string', 'max' => 45],
            [['language'], 'string', 'max' => 10],
            [['email'], 'required'],
            [['email'], 'unique'],
            [['email'], 'email'],
            [['email'], 'unique', 'targetClass' => \humhub\modules\user\models\User::className(), 'message' => Yii::t('UserModule.base', 'E-Mail is already in use! - Try forgot password.')],
            [['check'], 'required', 'requiredValue' => 1, 'message'=>'bla-bla-bla'],
        ];

I would like to make registration form invalid if both 'email' is invalid and 'check' is unchecked.
Thanks in advance!

**Comment by buddha87** [comment]
Hi, you'll have to implement a custom validator as described here: http://www.yiiframework.com/doc-2.0/guide-input-validation.html#creating-validators

**Comment by maxdonetsk** [comment]
buddha87, Thank you very much!
