### ISSUE TITLE
Humhub 1.1.0 no register menu

### ISSUE THREAD

**Issue by Flowwz** [humhub/humhub#1984]
I just update my Humhub manually to 1.1.0, I run the database migration tool, without any problem
But now when I load my homepage I have this : 
![homepage](https://cloud.githubusercontent.com/assets/22056752/18318469/0bd2ca82-7522-11e6-93dc-cb23ccc70f9d.PNG)

The url is like this : /index.php?r=user%2Fauth%2Flogin

So I'm on the **fail login** page, I can't register, I mean just have my basic home page with login and  no register menu

Before the update everything was fine so I don't really understand

**Comment by buddha87** [comment]
But you are able to login?

Check the following setting:
"Administration -> User -> Settings -> Anonymous users can register"

**Comment by Flowwz** [comment]
No I can't login because when I update to 1.1.0 I had reset my database, so I don't have any account to try with.

In the dynamic.php file : "'anonymousRegistration' => '1',"

**Comment by Flowwz** [comment]
Fixed, It was a problem with my database, thx for the help !
