### ISSUE TITLE
Your tests are broken...

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub#1992]
...seriously? Why are your tests trying to use a blank username?

vagrant@localhost {app_name}]$ codecept build -c ./protected/humhub/tests/
Building Actor classes for suites: acceptance, functional, unit
 -> AcceptanceTesterActions.php generated successfully. 0 methods added
\AcceptanceTester includes modules: PhpBrowser
 -> FunctionalTesterActions.php generated successfully. 0 methods added
\FunctionalTester includes modules: Filesystem, Yii2
 -> UnitTesterActions.php generated successfully. 0 methods added
\UnitTester includes modules: 
[2]+  Exit 1                  php -S localhost:8080 > /dev/null 2>&1
[vagrant@localhost {app_name}]$ php ./protected/humhub/tests/codeception/bin/yii installer/auto
**Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'humhub_test''**

in /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/db/Connection.php:550

Stack trace:
#0 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/db/Connection.php(864): yii\db\Connection->open()
#1 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/db/Connection.php(851): yii\db\Connection->getMasterPdo()
#2 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
#3 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/db/Command.php(894): yii\db\Command->prepare(true)
#4 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/db/Command.php(405): yii\db\Command->queryInternal('fetchAll', 7)
#5 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/db/mysql/Schema.php(348): yii\db\Command->queryColumn()
#6 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/db/Schema.php(231): yii\db\mysql\Schema->findTableNames('')
#7 /var/www_vagrant/{app_name}/protected/humhub/components/console/Application.php(66): yii\db\Schema->getTableNames()
#8 /var/www_vagrant/{app_name}/protected/humhub/components/ModuleManager.php(68): humhub\components\console\Application->isDatabaseInstalled()
#9 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\components\ModuleManager->init()
#10 [internal function]: yii\base\Object->__construct(Array)
#11 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/di/Container.php(373): ReflectionClass->newInstanceArgs(Array)
#12 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/di/Container.php(154): yii\di\Container->build('\\humhub\\compone...', Array, Array)
#13 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('\\humhub\\compone...', Array, Array)
#14 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(133): yii\BaseYii::createObject(Array)
#15 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(71): yii\di\ServiceLocator->get('moduleManager')
#16 /var/www_vagrant/{app_name}/protected/humhub/components/bootstrap/ModuleAutoLoader.php(52): yii\di\ServiceLocator->__get('moduleManager')
#17 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/base/Application.php(315): humhub\components\bootstrap\ModuleAutoLoader->bootstrap(Object(humhub\components\console\Application))
#18 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/base/Application.php(267): yii\base\Application->bootstrap()
#19 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#20 /var/www_vagrant/{app_name}/protected/humhub/components/console/Application.php(32): yii\console\Application->init()
#21 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\components\console\Application->init()
#22 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object->__construct(Array)
#23 /var/www_vagrant/{app_name}/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#24 /var/www_vagrant/{app_name}/protected/humhub/tests/codeception/bin/yii(29): yii\console\Application->__construct(Array)
#25 {main}
[vagrant@localhost {app_name}]$

**Comment by buddha87** [comment]
Where have you configured your db auth for your tests, it should be configured in

/humhubroot/protected/humhub/tests/codeception/config/config.php

We heavily revised our test system in v1.2 to facilitate module testing and will provide a better test coverage soon.

**Comment by davidjeddy** [comment]
TY; I look forward to seeing the fruits of your labor come 1.2's release
