### ISSUE TITLE
Remove space

### ISSUE THREAD

**Issue by komurka** [humhub/humhub#1996]
Hello,

HumHub version: 1.1.0-beta.1
when using remove space button, I saw this error:

PHP Fatal Error 'yii\base\ErrorException' with message 'Call to undefined method humhub\modules\space\models\Setting::findAll()' 

/.../public_html/hub/protected/humhub/modules/space/models/Space.php:197

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

**Comment by buddha87** [comment]
Hi, yes this is a beta issue, please update to the stable version 1.1.0 which is already released.
I think a 1.1.1 will be follow soon.
