### ISSUE TITLE
X Hours ago

### ISSUE THREAD

**Issue by SphinxTwo** [humhub/humhub#2001]
I recently installed this version via zip file, however, there seems to be a problem with the timing, such as messages being sent "about 5 hours ago" which was sent only about a few minutes ago. Is there a fix to this issue yet?

![posted x hours ago](https://i.thebeast.tech/1474680488)
![x hours ago](https://i.thebeast.tech/1474680507)

**Comment by buddha87** [comment]
perhaps check the timezone of your mysql server.

**Comment by SphinxTwo** [comment]
Okay, Thanks. That fixed the issue.
