### ISSUE TITLE
PHP 7 + ZendOpcache + APCu

### ISSUE THREAD

**Issue by Twilek-de** [humhub/humhub#2005]
Hi,

I use PHP 7, ZendOpcache and APCu extension with Apache2. Humhub reports APC support as not installed although APCu should have the required functionality as a cache.

**Comment by 001101** [comment]
Is humhub working flawlessly with PHP7?

**Comment by Twilek-de** [comment]
Works perfectly for me so far. And is blindingly fast with opcache enabled.

**Comment by 001101** [comment]
Cool, then I know what to do now :) :+1:
