### ISSUE TITLE
Enhancement: Admin can add users to space without them having to accept an invitation

### ISSUE THREAD

**Issue by cboulanger** [humhub/humhub#2006]
Use case: We use Humhub's spaces to organize teams including people from outside which are not particularly keen on using another social media platform, so in order to make them participate, the entry barrier has to be extremely low. We do this by creating accounts for them and sending them login and password by email, so all they have to do is click on a link and enter their credentials. Still, some of them never log in. Our aim is that they still should receive the daily digest to be informed of what's going on and to incentivise them to eventually log in when an interesting message is posted. For this to work, they need to be added to the space. Inviting them doesn't work (since they don't log in to accept the invitation). So we end up logging in, "becoming them" and accepting the invite for them. That is not ideal. 

Solution: The administrators (at least the site admin) should be able to add people to spaces just as they can add people to groups.

**Comment by luke-** [comment]
Integrated in HumHub 1.3+

**Comment by cboulanger** [comment]
Great, thanks.

**Comment by ashraffouda** [comment]
Can this be done throught the API?
