### ISSUE TITLE
Can't post on a space / create new space

### ISSUE THREAD

**Issue by ruihildt** [humhub/humhub#2007]
Hi, I just installed Humhub 1.1.1 on my server (siteground) via softaculous.

Everything tworks fine, but after some time (I can't specify exactly when), I'm not able to post anymore, anywhere, nor comment: I get a continous loading screen.
More than that, the number of posts I did appears correctly, but no post is visible.

I also get a continuous loading when I try to setup new spaces.

Here's a screenshot: 
![capture d ecran de 2016-10-01 01-25-43](https://cloud.githubusercontent.com/assets/13787166/19009664/7df33000-8776-11e6-97ac-11255dbc3f8e.png)

I wanted to check the logs, but there's no log to be found.

**Comment by buddha87** [comment]
open the developer console of your browser (Ctrl + Shift + i in most browsers) and check for javascript errors, perhaps you'll have to clear the cache or delte the content of the 'assets' directory within the root of your humhub installation.

**Comment by ruihildt** [comment]
Ok so first I open the conssole, and I can see that my POST request throw a 500 internal server error.
I'm really not used to debug, so if you can maybe give me more direction, I'm really willing to go further.
![humhub-bug](https://cloud.githubusercontent.com/assets/13787166/19017440/6fae2d38-8839-11e6-83cd-fa8f7592c1c3.png)

I join here info I could get about it, no idea if it's helpful or not.

>>>
_csrf=ZWhjSFB4bloRCVsSEgABMFYHK2U1HzsrJCMmEgcCHw9SWlUdGiIFLw==
message=eéeé
notifyUserInput
containerGuid=9fe01856-21bf-4a02-aa04-cd91045bf5e1
containerClass=humhub\modules\user\models\User
fileList
visibility=1
>>>

>>>
POST /index.php?r=post%2Fpost%2Fpost&uguid=9fe01856-21bf-4a02-aa04-cd91045bf5e1 HTTP/1.1
Host: social.mydomain.tld
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://social.mydomain.tld
X-CSRF-Token: ZWhjSFB4bloRCVsSEgABMFYHK2U1HzsrJCMmEgcCHw9SWlUdGiIFLw==
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 235
Cookie: _identity=badc8960eabd966a1ba5bd5ef306dc921db90c99b867e0d18346282989787d10a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%229fe01856-21bf-4a02-aa04-cd91045bf5e1%22%2C2592000%5D%22%3B%7D; PHPSESSID=sga5q6p56jckv8cr0i6irkect1; _csrf=70a89b3ef0af9465a0743528e099e94347f431212e6a4aa90ed5a3d3c12da874a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22ta8ZBxoj3oH-egUqAKEZWzqU726UJZku%22%3B%7D; pm_getting-started-panel=expanded
Connection: keep-alive
>>>

>>>
HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Sat, 01 Oct 2016 22:25:35 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Host-Header: 192fc2e7e50945beb8231a492d6a8024
>>>

**Comment by ruihildt** [comment]
@buddha87 I also tried wlearing the cache (browser) and deleting everything inside the assets folder. but nothing change.

**Comment by buddha87** [comment]
Hmm, if there is a 500 Internal Server Error there should be an error in the logs. Have you set the right file permission mentioned in https://www.humhub.org/docs/guide-admin-installation.html#file-modes-permissions and also installed all required packages: https://www.humhub.org/docs/guide-admin-requirements.html

**Comment by skleveno** [comment]
Everything is working fine that code just shows up in the Box. If I remove
my default space in the settings  you just see that  piece of code. I'm
still able to select a default space and then the code shows  underneath
the space I selected.  However everything works fine.  I'll double check
file permissions when I get home from work and other stuff.  I will upload
some screen shots also.  Just weird that code is showing in the selection
box.

**Comment by ruihildt** [comment]
@buddha87 Here's the prerequisite summary, it looks fine to me : 
![capture d ecran de 2016-10-03 15-05-26](https://cloud.githubusercontent.com/assets/13787166/19038229/e9ee4c44-897a-11e6-8ffc-af936b1d0b11.png)

Now that @skleveno mentions it -and I need to confirm this- it seems the issue starts appearing when I remove the default space, delete it and choose my own. 

Would that make any sense?

**Comment by skleveno** [comment]
I believe that's what I did also not positive. Going through it today

**Comment by skleveno** [comment]
I don't believe I deleted the initial space but renamed it or edited it
somehow.  I did notice that I have a few issues in the prerequisites that I
need to lookup and fix. Could this be the issue?  I installed using cpanel
and softaculous. I then did the latest updated using the auto updater.
Here are the screenshots of my error and the log files.

<p><a href="http://www.sellstate-gallery.com/agenthub/error1.JPG
">error1</a></p>
<p><a href="http://www.sellstate-gallery.com/agenthub/error2.JPG
">error2</a></p>
<p><a href="http://www.sellstate-gallery.com/agenthub/error3.JPG">error
3</a></p>

**Comment by buddha87** [comment]
@skleveno you have to install or update your INTL ICU package.

**Comment by buddha87** [comment]
@ruihildt you are sure there are no errors under "Administration -> Information -> Logging" internal server errors should definetly be logged there.

**Comment by ruihildt** [comment]
@buddha87 Yup, not a single entry in the logging tab: 
![capture d ecran de 2016-10-04 10-22-06](https://cloud.githubusercontent.com/assets/13787166/19067192/520500fa-8a1d-11e6-933b-c5f884623889.png)

Regarding permissions, could you please confirm the permissions in binaries to make sure I haven't overlooked anything?
