### ISSUE TITLE
Problems Upload Media

### ISSUE THREAD

**Issue by carbans** [humhub/humhub#2008]
I have a problem when I upload media. Disappear the button to send message.

PD: Attach a capture of screen
![captura-humhub](https://cloud.githubusercontent.com/assets/5936829/19014444/0eaa7e8e-87ed-11e6-8bf4-8c3f53877ac8.png)

**Comment by buddha87** [comment]
please check for javascript errors in the developer console of your browser (Ctrl + Shift +i)

**Comment by acs-ferreira** [comment]
Same issue here, either the action (Submit buttons) disappear or the Upload just **don't start** after selecting the file to upload (PDF); no upload ba, no network activity, nothing..

Console is completely empty, tried on PHP 5.6 and 7.0.

**Comment by acs-ferreira** [comment]
Also, sometimes i edit and upload a file to the post, nothing happens.
Save the post, no file appears on the post. 

I then do `CTRL+F5` and the file appears after page refresh.

**Comment by acs-ferreira** [comment]
Is this line really necessary?
I've removed it to make some tests and my problems are all gone. I think there is no need to hide the container.

https://github.com/humhub/humhub/blob/3bcc3e67addbe61852c625891f593dc83b3655e3/protected/humhub/modules/content/widgets/views/wallCreateContentForm.php#L87
