### ISSUE TITLE
Error under admin and settings menu

### ISSUE THREAD

**Issue by skleveno** [humhub/humhub#2009]
Error under admin and settings/config menu.  Language is set to English.  Tried to select something else and then back to English and save. Still shows error.   I select gallery wall (name of space) which is the only space we use and works but shows code in the box : Add {n,plural,=1{space} oth (cutsoff).  Under logging it says WARNING  Sat, 01 Oct 2016 12:36:14 -0400  yii\i18n\I18N::format
Formatting message for language 'en' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ILLEGAL_CHARACTER. The message being formatted was: Add {n,plural,=1{space} other{spaces}}.

I just seen this somewheres else on Google search regarding language set to English, but I am using the latest version and all my language is set to English..

Please help. Ty kindly scott

**Comment by skleveno** [comment]
I don't believe I deleted the initial space but renamed it or edited it somehow.  I did notice that I have a few issues in the prerequisites that I need to lookup and fix. Could this be the issue?  I installed using cpanel and softaculous. I then did the latest updated using the auto updater.  Here are the screenshots of my error and the log files.  

<p><a href="http://www.sellstate-gallery.com/agenthub/error1.JPG">error1</a></p>
<p><a href="http://www.sellstate-gallery.com/agenthub/error2.JPG">error2</a></p>
<p><a href="http://www.sellstate-gallery.com/agenthub/error3.JPG">error 3</a></p>

**Comment by buddha87** [comment]
As mentioned in #2007 you probably have to update your INTL ICU package.

**Comment by skleveno** [comment]
Okay will do that I'm going to have to do a reinstall anyways because I
added a module from GitHub and enabled it and it won't let me log in and
crashed everything.

**Comment by buddha87** [comment]
was it an official module?

**Comment by skleveno** [comment]
no.. some chat module from a search on github.. looking for an instant
messenger so our team can talk and see whose online. I am going to post
something on freelancers and see if I can hire a programmer to do that. I
also want to make the space the default page when logging in instead of
dash. Any recommendations on anyone who does custom work?

**Comment by buddha87** [comment]
yeah a chat module is definetly planed after version 1.2
