### ISSUE TITLE
Wamp local Install error sql2006

### ISSUE THREAD

**Issue by Lokyaziis** [humhub/humhub#2012]
Hi..
I can't install it on my local wampserver !! I get the error  "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" !!

I tried many thing (found online such as increase "max_allowed_packet") but nothing seem to work !!
Wamp/3.0.6-32bit --- Apache/2.4.23p:8085  --- PHP/5.6.25 --- MySQL/5.7.14p:3308
Config (my.ini):
- under [wampmysqld]
max_allowed_packet = 256M
wait_timeout = 28800
innodb_lock_wait_timeout = 28800

- under[mysqldump] and [mysqld]
max_allowed_packet = 256M
wait_timeout = 28800

Config (php.ini):
max_execution_time = 120
memory_limit = 256M
upload_max_filesize = 20M
max_file_uploads = 20
post_max_size = 0
mysql.cache_size = 2000
mysql.max_persistent = -1
mysql.max_links = -1
mysql.connect_timeout = -1

(I tried bigger, but change nothing to the issue)
Thanks for any help !!

**Comment by buddha87** [comment]
Do you have full stacktrace in your server logs?
Where exactly does it occure, after setting the db data in the installer?

**Comment by Lokyaziis** [comment]
ok... I don't know where it come from, but after a clean install it work... I think it was related to the sql-mode !!
