### ISSUE TITLE
Special character at first

### ISSUE THREAD

**Issue by RudolfFussek** [humhub/humhub#2022]
Hey,

I have a User with the Username .:Deutschland:, he can't post anythings. The error is .: at first.

Image -> https://s17.postimg.org/y9t44k4gf/Bildschirmfoto_2016_10_12_um_17_34_06.png

**Comment by RudolfFussek** [comment]
Anyone a idea?

**Comment by buddha87** [comment]
The only error I see in your console is a 403 which means the user is not allowed to access a certain route are there any errors in the logs and which humhub version are you using?

**Comment by RudolfFussek** [comment]
Error only that there is no user with the URL. The user is also **.:Deutschland:** therefore, special words are not allowed first ...?

My Version -> 1.1.1

**Comment by acs-ferreira** [comment]
I've created a user with the username `.:Deutschland:`, not able to reproduce, everything works just fine.
http://s11.postimg.org/nphl2f5z7/screenshot_139.png

Also:
http://s11.postimg.org/7v7a6a6mb/screenshot_139.png

**Comment by RudolfFussek** [comment]
Yes but you can't  go to the Userprofile....

**Comment by acs-ferreira** [comment]
No, i can do everything: go to user profile, post something, edit user profile, etc.
http://s18.postimg.org/nsx8sxtsp/screenshot_139.png

**Comment by RudolfFussek** [comment]
I became this error:

You don't have permission to access /u/.:deutschland:/ on this server.

**Comment by acs-ferreira** [comment]
When you access `/u/.%3Adeutschland%3A/user/profile/home`?

**Comment by acs-ferreira** [comment]
or `/u/.%3Adeutschland%3A/`?
Both works fine for me.

**Comment by RudolfFussek** [comment]
No, don't work... Can you send me your .htaccess?

**Comment by acs-ferreira** [comment]
This one, no modifications made:
https://github.com/humhub/humhub/blob/master/.htaccess.dist

**Comment by RudolfFussek** [comment]
Oh... Thanks, my .htaccess looks different. Now it func.

Thanks 👍
