### ISSUE TITLE
strange timetamps

### ISSUE THREAD

**Issue by ThomasKaule** [humhub/humhub#2024]
The humhub cache directory contains files strange time information.

The following has a modify time one hour in the future:

[root@humhub hu]# stat humhubf7384d1c7064e08cc22e716be171de0c.bin
  File: ‘humhubf7384d1c7064e08cc22e716be171de0c.bin’
  Size: 2925            Blocks: 8          IO Block: 4096   regular file
Device: fd02h/64770d    Inode: 100863189   Links: 1
Access: (0644/-rw-r--r--)  Uid: (   48/  apache)   Gid: (   48/  apache)
Context: system_u:object_r:httpd_sys_rw_content_t:s0
Access: 2016-10-13 11:18:57.282499581 +0200
Modify: 2016-10-13 12:17:45.000000000 +0200
Change: 2016-10-13 11:17:45.720469009 +0200
 Birth: -

This one has access and modify one year in the future:

[root@humhub hu]# stat humhubfe1f53570cd3a3887475308791c338db.bin
  File: ‘humhubfe1f53570cd3a3887475308791c338db.bin’
  Size: 903             Blocks: 8          IO Block: 4096   regular file
Device: fd02h/64770d    Inode: 100864966   Links: 1
Access: (0644/-rw-r--r--)  Uid: (   48/  apache)   Gid: (   48/  apache)
Context: system_u:object_r:httpd_sys_rw_content_t:s0
Access: 2017-10-13 11:17:46.000000000 +0200
Modify: 2017-10-13 11:17:46.000000000 +0200
Change: 2016-10-13 11:17:46.160469197 +0200
 Birth: -

The cache was cleared before ..

**Comment by cebe** [comment]
the file cache expiry is handled via file times, so if you see it is one year in the future, the cached entry is valid for one year.

**Comment by ThomasKaule** [comment]
Ok, I understand. The second issue is the ownership:

[root@humhub hu]# ls -l
total 1504
-rw-r--r--. 1 root   root      22 Oct 13  2017 humhub00261cc067266151ec6ec02f57447ce3.bin
-rw-r--r--. 1 root   root      22 Oct 13  2017 humhub003305e411ce9b6c6d4448462f0e4cc4.bin
-rw-r--r--. 1 apache apache    22 Oct 13  2017 humhub00431082a7e39cffdde9916b5f7c4b94.bin
-rw-r--r--. 1 apache apache  1606 Oct 13  2017 humhub0111d6b9a787c361e740eafe05a28e4b.bin
-rw-r--r--. 1 root   root      22 Oct 13  2017 humhub01e407f54b0f684ab822e6303d3469b8.bin
   ...

So I've entries which belongs to root. Which leads to:

Unable to write cache file '/var/www/humhub-1.1.0/protected/runtime/cache/hu/humhub20f2df274fcba02bc191ab35f6590f77.bin': file_put_contents(/var/www/humhub-1.1.0/protected/runtime/cache/hu/humhub20f2df274fcba02bc191ab35f6590f77.bin): failed to open stream: Permission denied 

The web server runs as apache and should only create apache cache entries. Could it be, that the cronjobs - which runs as root - are responsible for this ?

[root@humhub hu]# cat /etc/cron.d/humhub 
30  * * * * root /var/www/humhub/protected/yii cron/hourly >/dev/null 2>&1
 0 18 * * * root /var/www/humhub/protected/yii cron/daily >/dev/null 2>&1

Should they run as another user ?

**Comment by cebe** [comment]
> The web server runs as apache and should only create apache cache entries. Could it be, that the cronjobs - which runs as root - are responsible for this ?

yes, they should not run as root, but as the same user the web application uses.
