### ISSUE TITLE
Change Test mode & production

### ISSUE THREAD

**Issue by mat-l** [humhub/humhub#2025]
Hello,

I am more or less suddenly running my humhub instance in test mode as well as in beta branch.
I downloaded the file as a zip in the past and extracted them.
How can I change to stable and also to production mode?

regards
matl

**Comment by cebe** [comment]
set `YII_DEBUG` to `false` and `YII_ENV` to 'prod' in index.php: https://github.com/humhub/humhub/blob/master/index.php#L10-L11

**Comment by mat-l** [comment]
Great, works for me. Thanks a lot :-)

**Comment by nabibux0244** [comment]
works for me. Thanks
