### ISSUE TITLE
failed update

### ISSUE THREAD

**Issue by ThomasKaule** [humhub/humhub#2026]
I tried to update humhub from version 1.1.0 to 1.1.1 via web interface. Result:

Error!
Es ist ein interner Serverfehler aufgetreten.

i.e. internal server error

Log:
exception 'Exception' with message 'Make sure all files are writable!' in /var/www/humhub-1.1.0/protected/modules/updater/modules/packageinstaller/controllers/InstallController.php:54 Stack trace: #0 [internal function]: humhub\modules\updater\modules\packageinstaller\controllers\InstallController->actionValidate() #1 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #2 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #3 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('validate', Array) #4 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('package-install...', Array) #5 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /var/www/humhub-1.1.0/index.php(25): yii\base\Application->run() #7 {main}

That's not much. I'd like to know which files are not writable to fix it ...

**Comment by buddha87** [comment]
There is a new updater module version (2.0.2) which should output a more specific error message in this case.

**Comment by ThomasKaule** [comment]
Ok, the new updater is more specific:

exception 'Exception' with message 'Make sure all files are writable! (/var/www/humhub/.htaccess.dist, /var/www/humhub/js/app.js, /var/www/humhub/js/ekko-lightbox-modified.js, /var/www/humhub/protected/vendor/jbroadway/urlify/URLify.php, /var/www/humhub/protected/vendor/jbroadway/urlify/tests/URLifyTest.php, /var/www/humhub/...)' in /var/www/humhub-1.1.0/protected/modules/updater/modules/packageinstaller/controllers/InstallController.php:58 Stack trace: #0 [internal function]: humhub\modules\updater\modules\packageinstaller\controllers\InstallController->actionValidate() #1 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #2 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #3 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('validate', Array) #4 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('package-install...', Array) #5 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /var/www/humhub-1.1.0/index.php(25): yii\base\Application->run() #7 {main} 

But those files listed above (and it seems only the first ones are shown) don't belong to directories which should be writable by the webserver according to humhub docu:

Make the following directories/files writable by the webserver

    /assets
    /protected/config/
    /protected/modules
    /protected/runtime
    /uploads/*

So either the docu is wrong or the updater doesn't work.

And a comment from a humhub developer:
make sure, all files are writable by PHP, e.g.: chmod -R a+rw /path/to/HumHub

tells me humhub and security doesn't fit together.

Anyone successfully updated humhub ?
