### ISSUE TITLE
Android Mobile App Uploading photo 

### ISSUE THREAD

**Issue by zelectron** [humhub/humhub#2034]
Hello, Photo Upload (to update profile or send post ..) is not working in Android App. 
Seems to be working fine if you open from Android Browser.

**Comment by mkhulisi** [comment]
is there an update yet

**Comment by Felli** [comment]
Just to note, HumHub doesn't have its own app released, you're most likely experiencing this from a third-party app, although HumHub devs are working on a mobile app as we speak.

**Comment by buddh4** [comment]
As Felli mentioned there is no official android app, please contact the app authors. We'll provide an official mobile app soon.
