### ISSUE TITLE
error with "formatting message" - invalid message pattern

### ISSUE THREAD

**Issue by clairedc** [humhub/humhub#2035]
I have this error message in my logs :
Formatting message for language 'fr' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ILLEGAL_CHARACTER. The message being formatted was: {nFormatted} {n, plural, =1{# kilooctet} other{# kilooctets}}. 

Could you please help me ?

Thanks

**Comment by buddha87** [comment]
Hi, which humhub version and where exactly does this occure?

**Comment by clairedc** [comment]
My version is 1.1.1.
yii\i18n\I18N::format I don't know if there is a link but my cron jobs aren't working.

**Comment by cebe** [comment]
@clairedc 

> It is also recommended that you use an ICU version equal or greater than version 49. This will ensure you can use all the features described in this document. For example, an ICU version below 49 does not support using # placeholders in plural rules. 
> http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#setup-environment

please check the ICU version you have installed on your sever.

**Comment by clairedc** [comment]
Hi,
My host provider doesn't want to change the ICU version. Do you think that this error is linked with my cron problems (cron jobs don't work on my humhub site) ?
Thank you.

**Comment by clairedc** [comment]
Hi,
My version of Humhub is 1.2.0-beta.2 and my version of ICU is 52.1 and when I run my cronjobs, I have the following error message in my logs : 
Formatting message for language 'fr' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ILLEGAL_ARGUMENT_ERROR. The message being formatted was: Ce champ de téléchargement ne permet qu'un maximum de {n, pluriel, = 1 {# fichier} sur {# fichiers}}..

My hourly cron jobs don't mention "E-mail sent....done" but only
Executing hourly tasks:
Optimizing search index... done.

I have the same message when I try to send invitation to space...

What's wrong ?

**Comment by cebe** [comment]
> `sur {# fichiers}`

this is invalid syntax, it should be `other {# fichiers}`

**Comment by buddh4** [comment]
such errors seem to occure in other places/languages too, we should somehow validate the message strings in the translation module.

**Comment by danielrodd** [comment]
https://github.com/yiisoft/yii2/issues/2209
