### ISSUE TITLE
Installation Stopped functioning half way through

### ISSUE THREAD

**Issue by myHub24** [humhub/humhub#2038]
Hi,

I did run into a problem while trying to install HumHub on a subdomain. I had closly followed the instruction on the website and the installer started off well except a couple warnings about setting the timezone. It stopped working completely however after the initial step of filling the info for the database and the user. No matter what i did I couldn't restart the process and it would only display a warning about the timezone.

This is the warning it displays: Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/wbadmin/connect.bairamian.com/humhub-1.1.1/protected/humhub/components/Application.php on line 52

Any idea how I can go about fixing this?

Thanks.

**Comment by cebe** [comment]
it is in the error message, you need to set the `date.timezone` setting in php.ini.

**Comment by myHub24** [comment]
Thank you for your response, Turns out I was lacking the entire php.ini file in the subdomain root directory.
