### ISSUE TITLE
AGPL license for Humhub modules ?

### ISSUE THREAD

**Issue by Mariick** [humhub/humhub#2040]
Hi everyone,

Are all modules developped for Humhub automatically under AGPL license ? 
Because i want to contribute to a humhub dying module (last commit 6 months ago and many bugs), to add several new features (humhub-basic-chat from [https://github.com/petersmithca/humhub-basic-chat](https://github.com/petersmithca/humhub-basic-chat)), but the author dont mention any information about the license and dont response to my questions.

This is why i ask you for advices

Thanks

**Comment by Mariick** [comment]
I have my answer, must be gpl compliant license due tu humhub agpl license:
https://www.gnu.org/licenses/gpl-faq.html#GPLAndPlugins

someone from humhub can confirm ?

**Comment by 001101** [comment]
I would say, if there is no licence, there is no license ;)

**Comment by Mariick** [comment]
inb4 AGPLv3 term of use violation ;)

**Comment by cebe** [comment]
HumHub itself is licensed unter AGPL but that does not mean any module provided by other developer has the same license. If there is no license from the author that means you can not use that module without the authors permission and you should contact him and ask him to put a license on the code.

**Comment by Mariick** [comment]
K gud.
Iill go contribute to another social network.

**Comment by 001101** [comment]
Who says that source code without license is not just without license?

**Comment by cebe** [comment]
@001101 a license is there to grant you some rights on what you are allowed to do with the software. If there is no license you have no rights to do anything with it. See for example: http://choosealicense.com/no-license/

**Comment by 001101** [comment]
Too bad :-/

Thanks for the link @cebe
