### ISSUE TITLE
New expontaneous error - Impossible to post

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#2042]
Hi, I enter in my social network for check some new activities and post something for my clients and I noticed that nobody had activity for last days.

In fact, I posted something and loading points didn t end to work. I refreshed the page and I posted again but nothing.

I went to loggin and I discovered 2 new kind of messages never existed before:

This one is an error:

`ZendSearch\Lucene\Exception\Iexception 'ZendSearch\Lucene\Exception\InvalidFileFormatException' with message 'Segment compound file doesn't contain _e3.fnm file.' in /home/opengrow/public_html/es/community/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index/SegmentInfo.php:542 Stack trace: #0 /home/opengrow/public_html/es/community/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index/SegmentInfo.php(283): ZendSearch\Lucene\Index\SegmentInfo->openCompoundFile('.fnm') #1 /home/opengrow/public_html/es/community/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index/SegmentWriter/DocumentWriter.php(209): ZendSearch\Lucene\Index\SegmentInfo->__construct(Object(ZendSearch\Lucene\Storage\Directory\Filesystem), '_e3', 1, -1, NULL, true, true) #2 /home/opengrow/public_html/es/community/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index/Writer.php(740): ZendSearch\Lucene\Index\SegmentWriter\DocumentWriter->close() #3 /home/opengrow/public_html/es/community/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php(1158): ZendSearch\Lucene\Index\Writer->commit() #4 /home/opengrow/public_html/es/community/protected/humhub/modules/search/engine/ZendLuceneSearch.php(70): ZendSearch\Lucene\Index->commit() #5 /home/opengrow/public_html/es/community/protected/humhub/modules/search/engine/ZendLuceneSearch.php(76): humhub\modules\search\engine\ZendLuceneSearch->add(Object(humhub\modules\post\models\Post)) #6 /home/opengrow/public_html/es/community/protected/humhub/modules/content/Events.php(152): humhub\modules\search\engine\ZendLuceneSearch->update(Object(humhub\modules\post\models\Post)) #7 [internal function]: humhub\modules\content\Events::onContentActiveRecordSave(Object(yii\db\AfterSaveEvent)) #8 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Event.php(205): call_user_func(Array, Object(yii\db\AfterSaveEvent)) #9 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Component.php(549): yii\base\Event::trigger(Object(humhub\modules\post\models\Post), 'afterInsert', Object(yii\db\AfterSaveEvent)) #10 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(916): yii\base\Component->trigger('afterInsert', Object(yii\db\AfterSaveEvent)) #11 /home/opengrow/public_html/es/community/protected/humhub/modules/content/components/ContentActiveRecord.php(192): yii\db\BaseActiveRecord->afterSave(true, Array) #12 /home/opengrow/public_html/es/community/protected/humhub/modules/post/models/Post.php(80): humhub\modules\content\components\ContentActiveRecord->afterSave(true, Array) #13 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(468): humhub\modules\post\models\Post->afterSave(true, Array) #14 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(427): yii\db\ActiveRecord->insertInternal(NULL) #15 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(598): yii\db\ActiveRecord->insert(true, NULL) #16 /home/opengrow/public_html/es/community/protected/humhub/modules/content/widgets/WallCreateContentForm.php(139): yii\db\BaseActiveRecord->save() #17 /home/opengrow/public_html/es/community/protected/humhub/modules/post/controllers/PostController.php(40): humhub\modules\content\widgets\WallCreateContentForm::create(Object(humhub\modules\post\models\Post), Object(humhub\modules\user\models\User)) #18 [internal function]: humhub\modules\post\controllers\PostController->actionPost() #19 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #20 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #21 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('post', Array) #22 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('post/post/post', Array) #23 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #24 /home/opengrow/public_html/es/community/index.php(25): yii\base\App`

This one is Info:

`$_GET = [ 'uguid' => '6052fbd8-77ba-4499-8c4e-f1a5cf5ff783' ] $_SERVER = [ 'CONTENT_LENGTH' => '225' 'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8' 'CONTEXT_DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'CONTEXT_PREFIX' => '' 'DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate' 'HTTP_ACCEPT_LANGUAGE' => 'es,en-GB;q=0.8,en;q=0.6,fr;q=0.4,pt-PT;q=0.2,pt;q=0.2' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_COOKIE' => 'G_ENABLED_IDPS=google; language=171f215eabfc3ad44c23b882291a1fc4f46e59efc26e0a3ea46fdf298dbc9952a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22es%22%3B%7D; PHPSESSID=580e789b1e3c2098c770d25fb14555b1; _csrf=674460e885674c944b322befcd2cda691375e270fe48dc6928c139510490986aa%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22bA1nwcnkUy7ddl5vP6gQovm6B4L5kaSA%22%3B%7D; _identity=3a9ad0ccab810ed194075869573792d29226e240a7e3ff06a36c0ce89355457da%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%226052fbd8-77ba-4499-8c4e-f1a5cf5ff783%22%2C2592000%5D%22%3B%7D' 'HTTP_HOST' => 'www.gropedia.com' 'HTTP_MOD_REWRITE' => 'On' 'HTTP_ORIGIN' => 'http://www.gropedia.com' 'HTTP_REFERER' => 'http://www.gropedia.com/' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36' 'HTTP_X_CSRF_TOKEN' => 'eWMtcXFiZy4bIhwfBgEJRSwaGhUVDlJYKVVKIB4UChg7V2FEGgM0bw==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => '' 'REDIRECT_HTTP_MOD_REWRITE' => 'On' 'REDIRECT_STATUS' => '200' 'REDIRECT_UNIQUE_ID' => 'WAx2BiU97MUABEyiBTAAAAAL' 'REDIRECT_URL' => '/u/eddie/post/post/post' 'REMOTE_ADDR' => '81.40.173.32' 'REMOTE_PORT' => '24395' 'REQUEST_METHOD' => 'POST' 'REQUEST_SCHEME' => 'http' 'REQUEST_URI' => '/u/eddie/post/post/post' 'SCRIPT_FILENAME' => '/home/opengrow/public_html/es/community/index.php' 'SCRIPT_NAME' => '/index.php' 'SERVER_ADDR' => '37.61.236.197' 'SERVER_ADMIN' => 'webmaster@gropedia.open-grow.co.uk' 'SERVER_NAME' => 'www.gropedia.com' 'SERVER_PORT' => '80' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'UNIQUE_ID' => 'WAx2BiU97MUABEyiBTAAAAAL' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' =>`

Please, I need help, users need interact with the social network for get support.

Thank you very much.

**Comment by eddiepiazza** [comment]
I get an strange solution....

My cpanel from my host let me config as max 

memory_limit	512M
post_max_size	128M

and I had upload_max_filesize set to 128mb because i was receiving this message in logging about the difference of size between upload_max_filesize and post_max_size.

So now I set upload_max_filesize to 1GB.

An explanation ??
