### ISSUE TITLE
ActiveForm submit issue

### ISSUE THREAD

**Issue by Erald91** [humhub/humhub#2050]
I have downloaded recently HumHub version 1.1.0. Then I have installed all external dependencies using composer.json provided. After all configuration steps and logged as administrator I tried to create a new profile field (/admin/user-profile/edit-field). In the moment that I hit save and submitted the form, nothing happens. The page is not reloaded and the data is not submitted. This happens for all types of fields. Also no error its thrown from HumHub or printed in browser console. It seems that \yii\widgets\ActiveForm doesn't respond. 

The same thing happens with HumHub version 1.1.1. It works only with HumHub 1.0.0.

In my testing server I have installed HumHub version 1.1.1 and could not create new profile fields. I plan to release beta version of my site soon, so any help will be very appreciated. Thanks in advance!

**Comment by buddha87** [comment]
This problem occured after the update from yii 2.0.9 to 2.0.10 because of some changes in the ActiveForm scripts. This is already fixed in the master branch. I'd suggest either to change your composer dependency to yii 2.0.9 manually or update to the master branch.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/issues/12803 and there is no fix yet.

**Comment by buddha87** [comment]
@cebe I meant the humhub master branch contains a workaround. The problem occured for loader buttons since the activeform is now submitted by calling trigger('click') on the button instead of $form.submit()  which triggers our click handler twice. Since we try to prevent multiple click event we returned false in this case.

https://github.com/humhub/humhub/blob/master/js/app.js#L176

**Comment by cebe** [comment]
I see, thanks for clarification.

**Comment by Erald91** [comment]
@buddha87 thanks for your suggestion. I tried to change yii2 version manually in composer file and now it's working as expected. Thanks!
