### ISSUE TITLE
Replacing markdownEditor

### ISSUE THREAD

**Issue by elbotho** [humhub/humhub#2056]
A simple wysiwyg-editor would be way better for most of the users in my hub.
Right now I'm thinking about http://summernote.org/ because it is based on bootstrap as well, but the options are countless. 

**Does anybody have experience with replacing the built in markdownEditor (based on bootstrap-markdown) with another editor?** 

Thank you!

**Comment by elbotho** [comment]
This is also an suggestion, because the usability is just so much better 😄

**Comment by mkey2000** [comment]
I'm also very interested in this.

**Comment by Felli** [comment]
I myself would rather have [Quill](http://quilljs.com/) replace the Markdown Editor being used over Summernote...

**Comment by 001101** [comment]
Would be really a very good drive to more us**er**bility

**Comment by Felli** [comment]
HumHub now uses a [ProseMirror editor](https://github.com/humhub/humhub-prosemirror), as to answer your question, I used @bizley's yii2 quill implementation at one time, but don't at this time.
