### ISSUE TITLE
How to get Humhub registration working without a mail server

### ISSUE THREAD

**Issue by xr09** [humhub/humhub#2060]
I've installed humhub for a local wireless network, no internet, no mail server so far.

I'd like to modify the registration form to redirect directly to the "emailed" link, I've worked with Symfony and Laravel, but Yii way is somewhat different, anyone could point me on the right direction? 

Where are registration links generated? Where is the controller to modify?

Thanks!

**Comment by mbh-dev** [comment]
try downloading a mail server application that can run on your platform and then configure to run on your internal network only. I suggest Mercury 32 Mail Server: http://www.pmail.com/downloads_s3_t.htm

**Comment by xr09** [comment]
We could set up a postfix or wathever, the thing is: there are too many users with no central auth, we don't want to create all humhub accounts by hand, just leave free registration.

**Comment by xr09** [comment]
Solved!!

Added this function to Invite model:
```

public function registrationUrl()
    {
        return Url::to(['/user/registration', 'token' => $this->token], true);
    }
```

Then changed AuthController a little bit.

```
      // Self Invite 
        $invite = new Invite();
        $invite->scenario = 'invite';
        if ($invite->load(Yii::$app->request->post()) && $invite->selfInvite()) {
                return $this->redirect($invite->registrationUrl());
        }
```

This way any new user can register without the need of confirmation by mail.

**Comment by xr09** [comment]
@luke- @buddha87  Any chance we could make this easier for future users? Like a setting to bypass mail completely?

**Comment by 001101** [comment]
you can use yandex

pdd.yandex.com/domains_add/

**Comment by nareshnaik143** [comment]
xr09 Sir can you tell me perfect location of Invit Model?

**Comment by nareshnaik143** [comment]
xr09 Sir can you tell perfect detail how to change for any new user can register without the need of confirmation.
location of Invit Model?

**Comment by xr09** [comment]
@nareshnaik143  The files to modify are `protected/humhub/modules/user/models/Invite.php` and `protected/humhub/modules/user/controllers/AuthController.php`

**Comment by nareshnaik143** [comment]
thankyou sir

**Comment by ekavade** [comment]
hi, 
i followed the steps to remove email verification. But it gives me error as
PHP Notice – yii\base\ErrorException

Trying to get property of non-object
1. in C:\wamp\www\humhub\protected\humhub\components\i18n\Formatter.php at line 38 
please do help.
