### ISSUE TITLE
HUMHUB database password reset

### ISSUE THREAD

**Issue by NasheedAhmad** [humhub/humhub#2062]
Dear,
I am totally new to HubHub i want to reset the database password through config file but the the config file does not show me the the present db password and db user, i am wondering i how reset, I am afraid if change the the database password in  mysql through channel i wont be able config the new password in HUMHUB 
please advise how to do it.

**Comment by xr09** [comment]
Check `protected/config/dynamic.php`

    array (
      'class' => 'yii\\db\\Connection',
      'dsn' => 'mysql:host=localhost;dbname=humhub',
      'username' => 'humuser',
      'password' => 'humhub',
      'charset' => 'utf8',

**Comment by NasheedAhmad** [comment]
Dear Thanks a Ton
this was  very helpful.
Regard.
