### ISSUE TITLE
Package yiisoft/yii2-codeception is abandoned

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2068]
Install from Git produces a Warning:

`Package yiisoft/yii2-codeception is abandoned, you should avoid using it. Use codeception/codeception instead.`

This package is deprecated. All the features were intergrated into Codeception Yii2 module. Refer to official documentation here: http://codeception.com/for/yii

**Comment by cebe** [comment]
the package is deprecated but it still works. You can still use it but no other features will be added as the preferred way of using codeception is to use native support. Changing this needs changes in test folder structure like they have been made in the application templates of the framework in release of version 2.0.10.
