### ISSUE TITLE
Invite members by email (only in german) ?

### ISSUE THREAD

**Issue by gseilheimer** [humhub/humhub#2071]
**Problem:**
How is it possible to change the language of the email to invite new users to spaces?
=> currently the default language of the email is german

**Wish:**
- the default language of space decides the language of the invite by email or
- you can set up the language of the invite email during before it will send out

**Comment by luke-** [comment]
Currently only the application default language (defined in Administration -> Settings) is used for invite e-mails.

There is no extra language option for spaces.
