### ISSUE TITLE
Online users widget not working with Redis

### ISSUE THREAD

**Issue by xr09** [humhub/humhub#2079]
For performance reasons I'm using redis for cache and sessions, but it looks like some parts of humhub are bound to mysql for the sessions.

**Comment by acs-ferreira** [comment]
Are you using https://github.com/yiisoft/yii2-redis ?

**Comment by xr09** [comment]
@acs-ferreira yes, that is a requirement for the redis connection to work, the thing is some parts of the app like the "online users" widget are assuming sessions are on mysql exclusively, need more indirection on that side.

**Comment by acs-ferreira** [comment]
HumHub uses use `yii\web\DbSession`
You should fork and use `yii\redis\Session` (and write the correct function)

File [session.php](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/components/Session.php#L12)

See [Custom Session Storage](http://www.yiiframework.com/doc-2.0/guide-runtime-sessions-cookies.html)

**Comment by xr09** [comment]
I get what you mean, I think this happens because `yii\redis\Session` has no `getOnlineUsers()` method.

**Comment by 001101** [comment]
I don't think you need redis.

**Comment by xr09** [comment]
@001101 Using Redis is a performance choice, the underlying Yii framework has support for this, but it seems Humhub is assuming mysql sessions.

**Comment by 001101** [comment]
Performance for what? Are you planning to make the next Facebook?? Then you should implement that, but for

**Comment by acs-ferreira** [comment]
> but it seems Humhub is assuming mysql sessions

Session handler must be completely rewrited (override) to use Redis.

**Comment by xr09** [comment]
@001101 Performance because yes, smart solutions beats throwing hardware every time. A relational db is not well suited for social networks (relationships have graph-like structure), sql joins go nuts after a number of "friendships", everything you can throw to a key-value db will be a performance gain.

**Comment by 001101** [comment]
Sure maybe, but you did not answer the question.
If you need this for large scale network, than you should be able to implement it.

**Comment by xr09** [comment]
@acs-ferreira can't tell if user @001101 is trolling or actual feedback. is hi/she/it related to humhub development in some way? These kind of answers will push feedback away.

We're all adults here, the fact that I'm reporting issues to this project already says I'm using it, I find it valuable to spend time with it, I choose this over competence and I'm trying to contribute in some way.

Please don't take feedback as a personal attack, this is software, software change, adapts and improve everyday.

I'm closing this issue, already achieved what I wanted with humhub, can't afford to dive into Yii just to get it the way I'd like. So long and thanks for the fish.

**Comment by acs-ferreira** [comment]
@xr09 NoSQL is definitely something interesting, but not on the actual road-map of HumHub (AFAIK).

If you want something a bit more simple to achieve that will definitely boost the performance of your social network, take a look at `yii\caching\MemCache`

See http://www.yiiframework.com/doc-2.0/yii-caching-memcache.html

But in any case, development is required, feel free to submit a PR if you achieve this (this is open source community driven after all).

> Regarding @001101 the only thing i can tell, is that (s)he as stolen my avatar (joking...).

**Comment by 001101** [comment]
@xr09 Are you trolling with this conversation?
If you want and can make a contribution, then take a look at the bugs.
