### ISSUE TITLE
Update Moment.js library

### ISSUE THREAD

**Issue by coliff** [humhub/humhub#2084]
Latest version at time of writing is 2.15.2
REF: https://github.com/moment/moment/blob/develop/CHANGELOG.md

**Comment by buddha87** [comment]
I think some of those libararies are not in use, hope we'll get rid of them in v1.2, please check the v1.2-dev branch.

**Comment by acs-ferreira** [comment]
@buddha87 1.2-dev branch is 48 commits behind master, is it planned to merge them ?

**Comment by buddha87** [comment]
yeah of course. should be done soon.
