### ISSUE TITLE
Posts images are being served as dynamic content, not using browser cache

### ISSUE THREAD

**Issue by xr09** [humhub/humhub#2091]
I'm running Humhub on a wireless network (city size), our (self) hosting and bandwith is reaching its limits, we need to squeeze every little bit of performance.

Deployed last friday, already have more than 700 users, 80-160 concurrent, people love it.

Current setup is nginx, php-fpm, mariadb and redis for cache and sessions.

I just realized images are being served as dynamic content, not directly from disk, that is a huge performance blow, if nginx could serve those images directly the server would fly.

Don't know how rooted is this behavior to your architecture but seriously, this could be that low hanging fruit which could fire your scalability to the clouds.

See here, every time I hit refresh the content images are being re-downloaded.

![pic34](https://cloud.githubusercontent.com/assets/1380243/20191277/c79e5b2a-a752-11e6-812a-b610d86fdc6c.jpeg)

**Comment by xr09** [comment]
Here's a video of a prototype using Chrome with throttling to show the re-download of images every time.

![vid2](https://cloud.githubusercontent.com/assets/1380243/20219049/6d57c6ee-a7f5-11e6-9a0e-6cce752ecff3.gif)

**Comment by acs-ferreira** [comment]
Check PR https://github.com/humhub/humhub/pull/2093

**Comment by xr09** [comment]
Sweet!!! Testing asap...

**Comment by xr09** [comment]
@acs-ferreira The 1.2 branch is needed for this patch to work? I'm getting errors patching this file by hand.

**Comment by acs-ferreira** [comment]
No, just copy/past the entire file content: https://raw.githubusercontent.com/acs-ferreira/humhub/a2572af2887477920488a70cdab3c9ffd4a4639e/protected/humhub/modules/file/controllers/FileController.php

On `/protected/humhub/modules/file/controllers/FileController.php`

If you're having any errors, please post them here.

**Comment by xr09** [comment]
I'm getting this error on image download.

![pic35](https://cloud.githubusercontent.com/assets/1380243/20266078/61bbe4f6-aa42-11e6-982a-33bd580098c2.jpeg)

**Comment by acs-ferreira** [comment]
Your behaviour should be like this, is it the case?

````
public function behaviors()
    {
        return [
            'acl' => [
                'class' => \humhub\components\behaviors\AccessControl::className(),
                'guestAllowedActions' => ['download']
            ],
            'httpCache' => [
                'class' => 'yii\filters\HttpCache',
                'cacheControlHeader' => 'public, max-age=31536000',
                'etagSeed' => function ($action, $params) {
                    return serialize([\yii\helpers\Url::current()]);
                },
            ],
        ];
    }
````

**Comment by xr09** [comment]
Working great, thanks!

Some assets aren't being cached, are those served somewhere else?

![pic36](https://cloud.githubusercontent.com/assets/1380243/20267308/124979c8-aa48-11e6-941e-db24269ba437.jpeg)

**Comment by acs-ferreira** [comment]
All my assets are being cached (304).
But maybe it comes from my nGinx setup.

See https://www.nginx.com/blog/nginx-high-performance-caching/

**Comment by xr09** [comment]
All good now, I was confused by some [200 vs 304](http://stackoverflow.com/questions/1665082/http-status-code-200-cache-vs-status-code-304) browser details. Thanks @acs-ferreira!!
