### ISSUE TITLE
Class \kartik\grid\Module does not exist

### ISSUE THREAD

**Issue by niklasenB** [humhub/humhub#2092]
I am getting an exception after upgrading to v 1.1.1

in line 422 of humhub/protected/vendor/yiisoft/yii2/di/Container.php

$reflection = new ReflectionClass($class);

anyone experienced this as well?

**Comment by buddha87** [comment]
Did you update by a github pull? If yes you'll probably have to run a composer update.

**Comment by niklasenB** [comment]
I was using the humhub updater

**Comment by buddha87** [comment]
Can you post the full erro stack?

**Comment by niklasenB** [comment]
sure, have a look:

`Class \kartik\grid\Module does not exist
1. in /var/www/html/directory/humhub/protected/humhub/commands/MigrateController.php at line 149
140141142143144145146147148149150151152153154155156157158     * Returns the migration paths of all enabled modules
     * 
     * @return array
     */
    protected function getMigrationPaths()
    {
        $migrationPaths = ['base' => $this->migrationPath];
        foreach (\Yii::$app->getModules() as $id => $config) {
            if (is_array($config) && isset($config['class'])) {
                $reflector = new \ReflectionClass($config['class']);
                $path = dirname($reflector->getFileName()) . '/migrations';
                if (is_dir($path)) {
                    $migrationPaths[$id] = $path;
                }
            }
        }
        return $migrationPaths;
    }
 
2. in /var/www/html/directory/humhub/protected/humhub/commands/MigrateController.php at line 149 – ReflectionClass::__construct('\kartik\grid\Module')
143144145146147148149150151152153154155     */
    protected function getMigrationPaths()
    {
        $migrationPaths = ['base' => $this->migrationPath];
        foreach (\Yii::$app->getModules() as $id => $config) {
            if (is_array($config) && isset($config['class'])) {
                $reflector = new \ReflectionClass($config['class']);
                $path = dirname($reflector->getFileName()) . '/migrations';
                if (is_dir($path)) {
                    $migrationPaths[$id] = $path;
                }
            }
        }
3. in /var/www/html/directory/humhub/protected/humhub/commands/MigrateController.php at line 98 – humhub\commands\MigrateController::getMigrationPaths()
9293949596979899100101102103104        if (!$this->includeModuleMigrations) {
            return parent::getNewMigrations();
        }
 
        $this->migrationPathMap = [];
        $migrations = [];
        foreach ($this->getMigrationPaths() as $migrationPath) {
            $this->migrationPath = $migrationPath;
            $migrations = array_merge($migrations, parent::getNewMigrations());
            $this->migrationPathMap[$migrationPath] = $migrations;
        }
 
        sort($migrations);
4. in /var/www/html/directory/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php at line 102 – humhub\commands\MigrateController::getNewMigrations()
5. yii\console\controllers\BaseMigrateController::actionUp(0)
6. in /var/www/html/directory/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\commands\MigrateController, 'actionUp'], [0])
7. in /var/www/html/directory/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams([])
8. in /var/www/html/directory/humhub/protected/vendor/yiisoft/yii2/console/Controller.php at line 119 – yii\base\Controller::runAction('up', [])
9. in /var/www/html/directory/humhub/protected/humhub/commands/MigrateController.php at line 172 – yii\console\Controller::runAction('up')
166167168169170171172173174175176177178        ob_start();
        $controller = new self('migrate', Yii::$app);
        $controller->db = Yii::$app->db;
        $controller->interactive = false;
        $controller->includeModuleMigrations = true;
        $controller->color = false;
        $controller->runAction('up');
        return ob_get_clean();
    }
 
    /**
     * Executes migrations in a specific folder
     * 
10. in /var/www/html/directory/humhub/protected/humhub/modules/admin/controllers/InformationController.php at line 61 – humhub\commands\MigrateController::webMigrateAll()
55565758596061626364656667    {
        return $this->render('prerequisites', ['checks' => \humhub\libs\SelfTest::getResults()]);
    }
 
    public function actionDatabase()
    {
        return $this->render('database', ['migrate' => \humhub\commands\MigrateController::webMigrateAll()]);
    }
 
    /**
     * Caching Options
     */
    public function actionCronjobs()
11. humhub\modules\admin\controllers\InformationController::actionDatabase()
12. in /var/www/html/directory/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\admin\controllers\InformationController, 'actionDatabase'], [])
13. in /var/www/html/directory/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'admin/information/database'])
14. in /var/www/html/directory/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('database', ['r' => 'admin/information/database'])
15. in /var/www/html/directory/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 87 – yii\base\Module::runAction('admin/information/database', ['r' => 'admin/information/database'])
16. in /var/www/html/directory/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
17. in /var/www/html/directory/humhub/index.php at line 25 – yii\base\Application::run()
19202122232425    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'admin/information/database',
];

$_COOKIE = [
...];

$_SESSION = [
    '__flash' => [],
    '__id' => 1,
];`

**Comment by niklasenB** [comment]
any ideas?
