### ISSUE TITLE
AuthClient

### ISSUE THREAD

**Issue by simongloel** [humhub/humhub#2097]
The message "Missing E-Mail Attribute from AuthClient." comes when I click the Google sign up button. Can somebody help me ?

**Comment by buddha87** [comment]
I think this means, the client could not read the email from your google account. Does this happen for all accounts or just some accounts.

**Comment by luke-** [comment]
Does this also happens on our community at: https://community.humhub.com

**Comment by user4536** [comment]
no only by my community i think :(   and it`s by all my accounts

**Comment by user4536** [comment]
And when I click on the Google sign up button, google requires the right to retrieve the email address.

But you can connect after the manually registration with a google account and sign in

**Comment by user4536** [comment]
Hello? can somebody help me?

**Comment by buddha87** [comment]
Can you post your Authclient configuration (remove your client id and/secret)

**Comment by user4536** [comment]
Yes wait!

**Comment by user4536** [comment]
<?php
return [

    'components' => [

        'authClientCollection' => [
            'clients' => [

                'facebook' => [
           'class' => 'yii\authclient\clients\Facebook',
'clientId' => '+++++++',
'clientSecret' => '+++++',
                ],
'google' => [
                'class' => 'yii\authclient\clients\GoogleOAuth',
       'clientId' => '++++',
               'clientSecret' => '++++++',
                 
           ],

            ],
        ],

    ],

];

**Comment by user4536** [comment]
Its a very good support (irony). Im waiting 14 days, that somebody answer... but nothing!
It is so unfair! I`m going to uninstall the platform! I am so angry about that!

**Comment by buddha87** [comment]
Sorry, as you can imagin we have a mass of requests from different channels beside developing the platform and we provide the github/community support for free if time allows. It's likely to overlook a github issue.

I'll try to reproduce your issue.

**Comment by luke-** [comment]
Maybe you need to enable email access somehwere in your Google App configuration?

**Comment by user4536** [comment]
Ok thank you but i can`t wait anymore! I fixed it about 1 hour ago

**Comment by buddh4** [comment]
Nice, perhaps other users would be interested how you solved it.

**Comment by aruntk** [comment]
@user4536 I'm facing the same issue. Could you share how you solved it?

**Comment by Buliwyfa** [comment]
Face same issue

**Comment by gomonkey** [comment]
I solved.
I discover if you have more than one account in google, it is return emails.

I put this code after line 126 from this file https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/controllers/AuthController.php

```
// Check if google have more accounts
if (!isset($attributes['email']) && isset($attributes["emails"])) {
   $attributes['email'] = $attributes["emails"][0]["value"];
} 
```

this part of code must to be before checking email

**Comment by Felli** [comment]
I think this would be better ran through the [Google](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/authclient/Google.php) auth client, not within the AuthController as not all services work the same as Google does. :thinking:

**Comment by buddh4** [comment]
Shouldn't google return the single email of the account you selected, or how to reproduce this?
I've multiple google accounts, but could not recreate this yet. If you like, open a new issue with some more detailed information.

**Comment by gomonkey** [comment]
@buddh4 in my case I did a var_dump and I found out it did not exist "email" key in the object but "emails"
something like this:
["emails" => [ 0 => "my@email"]]

**Comment by buddh4** [comment]
Hmm thanks I'll have to try reproducing this.
