### ISSUE TITLE
Using Gii - wrong path to typeahead.js

### ISSUE THREAD

**Issue by valentin-vogel** [humhub/humhub#2102]
Did anyone using Gii - the yii generator platform? If i call ```index.php?r=gii``` the following error is displayed:

The file or directory to be published does not exist: ```/var/www/project_url/protected/vendor/bower/typeahead.js/dist```

I can fix that problem copying the typeahead.js folder into bower folder.

My question is: How can i fix this problem in composer install process?

**Comment by acs-ferreira** [comment]
You should try on the Git of the project: https://github.com/yiisoft/yii2-gii/issues

**Comment by buddha87** [comment]
Have you done a composer update?

Also consider using the following module, we'll enhance this with/after the v1.2 release: https://github.com/humhub/humhub-modules-devtools

We'll also include some showcases for widget/js api

**Comment by valentin-vogel** [comment]
Thank you. I have done a composer update But it doesn't solve the problem. I hope the next HumHub release will soon appear.
