### ISSUE TITLE
pdo_pgsql.so issue

### ISSUE THREAD

**Issue by joelvital** [humhub/humhub#2104]
Since i've updated HumHub i got this issue:

> PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_pgsql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_pgsql.so: cannot open shared object file: No such file or directory

I dont know what to do, i'm getting crazy! Please help me solve this!

**Comment by buddha87** [comment]
Seems to be an issue with your php environment. Check the extension_dir of you php.ini and the path for the mentioned extension pdo_pgsql.so
