### ISSUE TITLE
Emoji Selector

### ISSUE THREAD

**Issue by gigabytedevelopers** [humhub/humhub#2105]
How can I add an emoji picker or selector in the textarea. I want it to be possible for users to click on the button, then choose which emoji they want instead of making them type : before selecting their of choice?

**Comment by buddha87** [comment]
This is not supported, perhaps you can implement this by yourself in your theme.

**Comment by gigabytedevelopers** [comment]
Could you guide me through on how to implement this? Thanks.

**Comment by buddha87** [comment]
Sorry not really, but have a look at the current richtext implementation: https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/views/richTextEditor.php#L21

**Comment by gigabytedevelopers** [comment]
Ok.. How about spellchecker for the text editor? It doesn't seem to show wrong spellings when a user is typing. How can I make that work?

**Comment by buddha87** [comment]
The spellchecker depends on the browser i think for example you'll have to install a dictionary on firefox https://addons.mozilla.org/de/firefox/language-tools/. On chrome it's working for me.
