### ISSUE TITLE
Costumize the TopMenu

### ISSUE THREAD

**Issue by Diarselimi** [humhub/humhub#2106]
I am trying to change the icon of the dashboard and other TobMenu from a *module* but i can't find a way to do that, is there a way to costumize the images and other things from a module ?

**Comment by stothew** [comment]
hi there,

why not just change the content in CSS?

find your "font-awesome.css" every symbol has its content there.

for example:

```
.fa-envelope:before {
  content: "\f0e0";
}
```

you can just change the content to an image if you want

```
.fa-envelope:before {
  content: url(img.png)
}
```

or use another symbol like this:

[http://astronautweb.co/snippet/font-awesome/](http://astronautweb.co/snippet/font-awesome/)

be aware this is gone if this is getting replaced by updates and its global everywhere the icon was used.

hope it helps.

**Comment by buddha87** [comment]
Perhaps we can define own classes and make them changable in the themes by importing the font-awesome variables.

something like this: http://stackoverflow.com/questions/19602812/less-mixin-a-variable-class-name/19603404#19603404

```
i {
  .fa;
  .fa-lg;
  &:before{
    content: @fa-var-github;
  }
}
```

**Comment by BDSM-Master** [comment]
Do any of you know which file to edit to remove items from the menu or re-arrange menu list?

**Comment by Mimanolis** [comment]
I know that this is a dead thread but @stothew can you please elaborate a little more on the issue? 
I have found the fontawesome.css and min.css in the assets, I change the code and nothing happens. The icons stay the same

> hi there,
> 
> why not just change the content in CSS?
> 
> find your "font-awesome.css" every symbol has its content there.
> 
> for example:
> 
> ```
> .fa-tachometer:before {
>   content: "\f0e4";
> }
> ```
> 
> you can just change the content to an image if you want
> 
> ```
> .fa-tachometer:before {
>   content: url(img.png);
> }
> ```
> 
> or use another symbol like this:
> 
> http://astronautweb.co/snippet/font-awesome/
> 
> be aware this is gone if this is getting replaced by updates and its global everywhere the icon was used.
> 
> hope it helps.

**Comment by Mimanolis** [comment]
Thank you @marc-farre but I would prefer handling it straight to the metal. Also my version is prior to 1.16 required by the module
