### ISSUE TITLE
My Profile > Edit Account > Security,  exception

### ISSUE THREAD

**Issue by justme24x7** [humhub/humhub#2107]
Whenever I go to My Profile > Edit Account > Security, this exception occurs (image attached).
![screen shot 2016-11-14 at 6 56 31 pm](https://cloud.githubusercontent.com/assets/19655777/20425788/3a87bd34-ada2-11e6-922c-dc3e6f9cefad.png)

**Comment by buddha87** [comment]
Which humhub version are you using and could you post the full stacktrace "Administration -> Information -> Logging"

**Comment by justme24x7** [comment]
Hi, I am using Humhub v1.1.1. Posting the stack trace below:

$_SERVER = [ 'UNIQUE_ID' => 'WDSmKn8AAAEAAArOWgUAAAAF' 'HTTP_HOST' => 'crohum1p2.com' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:48.0) Gecko/20100101 Firefox/48.0' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate' 'HTTP_REFERER' => 'http://crohum1p2.com/index.php/user/account/edit' 'HTTP_COOKIE' => 'mysheet=none; language=6c10bbabc3401c3a8bfe91558df4ec1a3df4084bbb20b0b05d8641eef098ace5a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; _identity=1cf0e3b907ce86d6352a20c02ae38ed7770e6572a84210179e7c4d17a29ae737a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22e682eb76-bb0b-4061-baf8-585d7b0a41b3%22%2C2592000%5D%22%3B%7D; PHPSESSID=65jh2rhhf6048496dp5pgn5r97; freichat_user=LOGGED_IN; _csrf=f96277d8e53a220ab304d61a0255e5a0b5028a86f50dc26c93c6d0212cc6b5e9a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22lHaVRRD58Je_0ez2N9ZUmEVTg1eosIG4%22%3B%7D; __session:0.2563630755355072:=http:' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin' 'DYLD_LIBRARY_PATH' => '/Applications/XAMPP/xamppfiles/lib' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache/2.4.17 (Unix) OpenSSL/1.0.1q PHP/5.6.15 mod_perl/2.0.8-dev Perl/v5.16.3' 'SERVER_NAME' => 'crohum1p2.com' 'SERVER_ADDR' => '127.0.0.1' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '127.0.0.1' 'DOCUMENT_ROOT' => '/Users/apple/Documents/workspace/web/crohum1p2' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/Users/apple/Documents/workspace/web/crohum1p2' 'SERVER_ADMIN' => 'you@example.com' 'SCRIPT_FILENAME' => '/Users/apple/Documents/workspace/web/crohum1p2/index.php' 'REMOTE_PORT' => '53940' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => '' 'REQUEST_URI' => '/index.php/user/account/security' 'SCRIPT_NAME' => '/index.php' 'PATH_INFO' => '/user/account/security' 'PATH_TRANSLATED' => '/Users/apple/Documents/workspace/web/crohum1p2/user/account/security' 'PHP_SELF' => '/index.php/user/account/security' 'REQUEST_TIME_FLOAT' => 1479845418.818 'REQUEST_TIME' => 1479845418 ]
Error  Wed, 23 Nov 2016 01:40:18 +0530  yii\base\Exception
exception 'yii\base\Exception' with message 'Invalid permission state' in /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/libs/BasePermission.php:171 Stack trace: #0 /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/modules/user/components/PermissionManager.php(224): humhub\libs\BasePermission::getLabelForState(true) #1 /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/modules/user/widgets/PermissionGridEditor.php(78): humhub\modules\user\components\PermissionManager->createPermissionArray('u_user') #2 /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/modules/user/widgets/PermissionGridEditor.php(39): humhub\modules\user\widgets\PermissionGridEditor->getDataProvider() #3 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\modules\user\widgets\PermissionGridEditor->init() #4 [internal function]: yii\base\Object->__construct(Array) #5 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/di/Container.php(379): ReflectionClass->newInstanceArgs(Array) #6 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/di/Container.php(154): yii\di\Container->build('humhub\\modules\\...', Array, Array) #7 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('humhub\\modules\\...', Array, Array) #8 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Widget.php(101): yii\BaseYii::createObject(Array) #9 /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/modules/user/views/account/security.php(21): yii\base\Widget::widget(Array) #10 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/View.php(325): require('/Users/apple/Do...') #11 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/Users/apple/Do...', Array) #12 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/Users/apple/Do...', Array, Object(humhub\modules\user\controllers\AccountController)) #13 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Controller.php(378): yii\base\View->render('security', Array, Object(humhub\modules\user\controllers\AccountController)) #14 /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/modules/user/controllers/AccountController.php(152): yii\base\Controller->render('security', Array) #15 [internal function]: humhub\modules\user\controllers\AccountController->actionSecurity() #16 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #17 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #18 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('security', Array) #19 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('user/account/se...', Array) #20 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #21 /Users/apple/Documents/workspace/web/crohum1p2/index.php(25): yii\base\Application->run() #22 {main}
Info  Wed, 23 Nov 2016 01:38:17 +0530  application
$_SERVER = [ 'UNIQUE_ID' => 'WDSlsX8AAAEAAArUbXYAAAAI' 'HTTP_HOST' => 'crohum1p2.com' 'HTTP_COOKIE' => '__session:0.24814698821945025:=http:; _identity=fdc22960589e2d74b4e7968af1d735c6af71aeee590811c6800278d1f06eec45a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B7%2C%22efbeea08-cecc-4124-a4bd-a9e46bc3f4fe%22%2C2592000%5D%22%3B%7D; freichat_user=LOGGED_IN; mysheet=none; PHPSESSID=ku58u80kdi0ennu20s5tik49h1; pm_getting-started-panel=expanded; _csrf=c961fa65786dda75f4e33427451e11b38371461f1aacb4876bc299cd1ebd867ca%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22ZjLUMgHB_z9em_FWUXnK1EXhzxdKp9Fw%22%3B%7D; language=1a57e718796e14f5cd3c27edca0787e82b6b780ee65cea45d34c9f9fc314aea7a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A3%3A%22enc%22%3B%7D' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50' 'HTTP_REFERER' => 'http://crohum1p2.com/index.php/user/account/edit' 'HTTP_ACCEPT_LANGUAGE' => 'en-us' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate' 'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin' 'DYLD_LIBRARY_PATH' => '/Applications/XAMPP/xamppfiles/lib' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache/2.4.17 (Unix) OpenSSL/1.0.1q PHP/5.6.15 mod_perl/2.0.8-dev Perl/v5.16.3' 'SERVER_NAME' => 'crohum1p2.com' 'SERVER_ADDR' => '127.0.0.1' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '127.0.0.1' 'DOCUMENT_ROOT' => '/Users/apple/Documents/workspace/web/crohum1p2' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/Users/apple/Documents/workspace/web/crohum1p2' 'SERVER_ADMIN' => 'you@example.com' 'SCRIPT_FILENAME' => '/Users/apple/Documents/workspace/web/crohum1p2/index.php' 'REMOTE_PORT' => '53845' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => '' 'REQUEST_URI' => '/index.php/user/account/security' 'SCRIPT_NAME' => '/index.php' 'PATH_INFO' => '/user/account/security' 'PATH_TRANSLATED' => '/Users/apple/Documents/workspace/web/crohum1p2/user/account/security' 'PHP_SELF' => '/index.php/user/account/security' 'REQUEST_TIME_FLOAT' => 1479845297.428 'REQUEST_TIME' => 1479845297 ]
Error  Wed, 23 Nov 2016 01:38:17 +0530  yii\base\Exception
exception 'yii\base\Exception' with message 'Invalid permission state' in /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/libs/BasePermission.php:171 Stack trace: #0 /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/modules/user/components/PermissionManager.php(224): humhub\libs\BasePermission::getLabelForState(true) #1 /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/modules/user/widgets/PermissionGridEditor.php(78): humhub\modules\user\components\PermissionManager->createPermissionArray('u_user') #2 /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/modules/user/widgets/PermissionGridEditor.php(39): humhub\modules\user\widgets\PermissionGridEditor->getDataProvider() #3 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\modules\user\widgets\PermissionGridEditor->init() #4 [internal function]: yii\base\Object->__construct(Array) #5 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/di/Container.php(379): ReflectionClass->newInstanceArgs(Array) #6 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/di/Container.php(154): yii\di\Container->build('humhub\\modules\\...', Array, Array) #7 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('humhub\\modules\\...', Array, Array) #8 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Widget.php(101): yii\BaseYii::createObject(Array) #9 /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/modules/user/views/account/security.php(21): yii\base\Widget::widget(Array) #10 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/View.php(325): require('/Users/apple/Do...') #11 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/Users/apple/Do...', Array) #12 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/Users/apple/Do...', Array, Object(humhub\modules\user\controllers\AccountController)) #13 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Controller.php(378): yii\base\View->render('security', Array, Object(humhub\modules\user\controllers\AccountController)) #14 /Users/apple/Documents/workspace/web/crohum1p2/protected/humhub/modules/user/controllers/AccountController.php(152): yii\base\Controller->render('security', Array) #15 [internal function]: humhub\modules\user\controllers\AccountController->actionSecurity() #16 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #17 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #18 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('security', Array) #19 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('user/account/se...', Array) #20 /Users/apple/Documents/workspace/web/crohum1p2/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #21 /Users/apple/Documents/workspace/web/crohum1p2/index.php(25): yii\base\Application->run() #22 {main}

**Comment by justme24x7** [comment]
Hi.. It seems the issue was there because I edited a file 
/protected/modules/mail/permissions/SendMail.php

Fixed that.. No worries. Original humhub doesn't have this issue
