### ISSUE TITLE
No follow option for users that have ANY friends. 

### ISSUE THREAD

**Issue by justme24x7** [humhub/humhub#2108]
If a user is friends with ANYBODY, it doesn't show the follow option in his profile. 
Assume there are 3 users - X, Y, and Z.

X and Y are friends. In this case, Z is not able to see any follow button in either X or Y's profile.

That is if I visit the profile of an user who is NOT friends with me but has ANY OTHER friends, the follow button was invisible. Only the "Add Friend" button was visible

This can be fixed by editing protected/humhub/modules/user/widgets/UserFollowButton.php around line no. 90

if (Yii::$app->getModule('friendship')->getIsEnabled()) {
            // Don't show follow button, when friends
           $sql = 'SELECT id FROM user_friendship WHERE user_id = '.Yii::$app->user->getIdentity()->id. ' AND friend_user_id = '.$this->user->id;
            $isfriend = Yii::$app->db->createCommand($sql)->queryScalar();
            if($isfriend != null){
                return;
            }
           /*
            if (Friendship::getFriendsQuery($this->user)->one() !== null) {
                return;
            }
            */
        }

**Comment by iceuponfire** [comment]
I have the same issue and this code fixed it.

**Comment by MRaihane** [comment]
Hey EveryBody,

There's some news about this Bug ? 

Thanks all

**Comment by Felli** [comment]
Hello, @MRaihane, please provide what version of HumHub you're using? As of right now, I believe this isn't a problem with `v1.2.2`.

**Comment by MRaihane** [comment]
Hello @Felli Actually we are using V1.2.2.
And i just made a test if the users are not friends, the follow button is available and not when they are friends.

**Comment by Felli** [comment]
This is on purpose because once you become friends you inherit the following action ability.

**Comment by MRaihane** [comment]
I see.
Thanks @Felli  for you support !
