### ISSUE TITLE
Error 500 when upload

### ISSUE THREAD

**Issue by Hesiode** [humhub/humhub#2109]
Hi,

i have Error 500 when i upload image, in chrome console :
POST http://intranet.xxx.fr/file/file/upload?objectModel=&objectId= 500 (Internal Server Error)

No error in apache log.

Have you an idea ?
Thank you

**Comment by MuriloFrade** [comment]
Hi,
Do you know if your php max upload size is enough for the your images?

**Comment by Hesiode** [comment]
yes, my image si 56ko :)

**Comment by Hesiode** [comment]
I retrieved error message :

>  Image dimensions are too big to be processed with current server memory limit!

Here my image
![avatar-guillaume](https://cloud.githubusercontent.com/assets/5263119/20475950/b4c628c8-afce-11e6-9e6b-b08e5eba87ce.jpg)

**Comment by Hesiode** [comment]
Ok, i found this problem but i dont understand why.
I have down memory_limit from 2G to 512M and now thats work..

**Comment by buddha87** [comment]
Consider using ImageMagick, which has to be installed and configured in "Administration -> Settings -> Advanced -> Files"

**Comment by victorpdiez** [comment]
Same problem we had php memory limit set to 2048mb, move it down to 512mb and start working.

So the error should be "Image dimensions are too big to be processed with current server memory limit, please decrease server memory" 👎 

something that make no sense...
