### ISSUE TITLE
Only need to specify one Apple Touch icon in the HEAD

### ISSUE THREAD

**Issue by coliff** [humhub/humhub#2110]
I propose to remove this from the HEAD:

```
 <link rel="apple-touch-icon" sizes="57x57" href="/ico/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/ico/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="//ico/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/ico/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/ico/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/ico/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/ico/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/ico/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/ico/apple-icon-180x180.png">
```

And instead just have:
`<link rel="apple-touch-icon" href="apple-touch-icon.png">`

The apple-touch-icon.png icon then just needs to be supplied once, at 180x180px.

This is recommended by HTML5Boilerplate, which is usually a reliable guide for best practises
REF: https://github.com/h5bp/html5-boilerplate/blob/master/dist/doc/extend.md#apple-touch-icons

**Comment by buddha87** [comment]
Thanks!

**Comment by acs-ferreira** [comment]
Don't totally agree, see https://mathiasbynens.be/notes/touch-icons#sizes (whole article)

**Comment by cebe** [comment]
I agree with @acs-ferreira, to highlight from the linked article:

>  It’s perfectly possible to just create one high-resolution icon and use that for all devices. [...] The downside is that these devices load the large high-quality image, while a much smaller file would have worked just as well. This wastes bandwidth and affects performance negatively for the end user whenever the site is added to the home screen.

**Comment by 001101** [comment]
As I made new Icons for my site, I can say that the size differences are really huge and would not make a better user experience, just for purification or minimalism, it is the wrong way to go.
