### ISSUE TITLE
Update to jQuery 3.1.1

### ISSUE THREAD

**Issue by coliff** [humhub/humhub#2118]
jQuery 3.1.1 is, at the time of writing, the latest stable version of jQuery. Should we update to this version? If so, I'll open a pull request.

If Internet Explorer 8 should be supported I'd suggest that we should revert back to v1.12.4.

**Comment by acs-ferreira** [comment]
Handled by `yii`, on milestone [2.1.x](https://github.com/yiisoft/yii2/milestone/6) see https://github.com/yiisoft/yii2/issues/12029
