### ISSUE TITLE
How to get Humhub registration working without a mail server

### ISSUE THREAD

**Issue by nareshnaik143** [humhub/humhub#2121]
I've installed humhub for a local wireless network, no internet, no mail server so far.

I'd like to modify the registration form to redirect directly to the "emailed" link, I've worked with Symfony and Laravel, but Yii way is somewhat different, anyone could point me on the right direction?

Where are registration links generated? Where is the controller to modify?
please any one give me suggetion/

Thanks!

**Comment by cebe** [comment]
- registration is made by the following controller action in user module:
  https://github.com/humhub/humhub/blob/f650bade9e675ec97bc41d9a93274835a4c4c698/protected/humhub/modules/user/controllers/RegistrationController.php#L57-L93
- this calls register() on the model: https://github.com/humhub/humhub/blob/f650bade9e675ec97bc41d9a93274835a4c4c698/protected/humhub/modules/user/models/forms/Registration.php#L236-L271
- If after registration, the user status is `status === User::STATUS_ENABLED` he will be logged in directly.

**Comment by 1BB3** [comment]
Which part of the code should be edited, where is the action that looks for the token and redirects to the sign up page?

**Comment by bug0000** [comment]
The question is urgent.
Does anyone know how to make the registration available without sending mail and other confirmations?
