### ISSUE TITLE
Error: Unknown or bad timezone

### ISSUE THREAD

**Issue by omur-dalan** [humhub/humhub#2122]
I got this error when i try to create an event in calendar module. But not all installations.I could not find the difference between them. Can you provide a required timezone configuration for at least Ubuntu 16.04, PHP 7 and MySQL 5.7 ?

**Comment by cebe** [comment]
how about using UTC?

**Comment by oyepez003** [comment]
I got the same issue in the master branch (using the calendar module: creating a new event).

**Comment by cebe** [comment]
duplicate of https://github.com/humhub/humhub-modules-calendar/issues/41#issuecomment-242161878

**Comment by oyepez003** [comment]
But it is an error of the humhub core code: Yii::$app->formatter->timeZone is null

**Comment by cebe** [comment]
it is `Europe/Berlin` in my humhub setup... Seems you are missing some setting.

**Comment by cebe** [comment]
on URL `humhub/index.php?r=user%2Faccount%2Fedit-settings` you can select a timezone. afaik that is set automatically to a default value for every user.

**Comment by oyepez003** [comment]
Yes but that settings is saved in Yii::$app->timeZone, Yii::$app->formatter->timeZone is for the User timezone.
