### ISSUE TITLE
Login as a friend

### ISSUE THREAD

**Issue by cdiegosr** [humhub/humhub#2123]
Hi guys! Humhub is awesome!

But I have a little problem: when some member access the website, sometimes (a lot) the user logged in isn´t the same.

Example: John did the login succefully, but when inside the system is logged as Peter.

This happened 3 times until now, with 3 months of installation. I can´t discover problem/solution about this bug, it´s happenning just a few times!

Anybody can send me tips for some help? Thanks!

**Comment by buddha87** [comment]
Very strange behaviour does this happen on a client where multiple users login/logout? The only "similar" problem I experienced was when using the "Become this member" function within the admin section.

**Comment by cdiegosr** [comment]
Hi @buddha87 !

This happened 3 times, that I know, at one community with 11 users. One time was with admi user, other 2 normal users. We did the normal login with correct user/pass, not in the same client/computer or network.

My installation was made with Softaculous, maybe this could be the problem...
