### ISSUE TITLE
Unicode emojis are removed on submitting a post.

### ISSUE THREAD

**Issue by binarynos** [humhub/humhub#2129]
If i use any Unicode emojis other than those suggested by humhub, they are automatically removed by Humhub.
How do I stop this?

**Comment by buddha87** [comment]
I could fix this by using the charset 'utf8mb4' for my database and tables ( http://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5) and in the yii connection string (protected/config/dynamic.php')

**Comment by binarynos** [comment]
@buddha87 it works thanks

**Comment by 001101** [comment]
How can I insert unicode to posts?
I want to add a dot "U+2022"

**Comment by Felli** [comment]
In MariaDB with InnoDB installed enter the following in SQL and it'll convert the post table over;
`ALTER TABLE post CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

**Comment by Tie-fighter** [comment]
This also breaks Kanji and other typesets.
Please patch this :/

**Comment by Felli** [comment]
As of right now, v1.3, utf8mb4 is the default recommended.
