### ISSUE TITLE
Problems running 'composer install' in a new box

### ISSUE THREAD

**Issue by arimourao** [humhub/humhub#2130]
After creating a brand new vagrant box running Ubuntu Trusty x64 14, PHP 7.0 on a  Nginx Server, cloning the repo and running 'composer install' I get the following errors:

 Problem 1
    - The requested package bower-asset/jquery-timeago could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package bower-asset/jquery-nicescroll could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package bower-asset/jquery-knob could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package bower-asset/jquery-placeholder could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package bower-asset/blueimp-file-upload could not be found in any version, there may be a typo in the package name.
  Problem 6
    - The requested package bower-asset/fontawesome could not be found in any version, there may be a typo in the package name.
  Problem 7
    - The requested package bower-asset/bootstrap-markdown could not be found in any version, there may be a typo in the package name.
  Problem 8
    - The requested package bower-asset/select2 could not be found in any version, there may be a typo in the package name.
  Problem 9
    - The requested package bower-asset/select2-bootstrap-theme could not be found in any version, there may be a typo in the package name.
  Problem 10
    - yiisoft/yii2 2.0.9 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.4 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.10 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 ~2.0.4 -> satisfiable by yiisoft/yii2[2.0.10, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by buddha87** [comment]
Have you tried a composer self-update: https://getcomposer.org/doc/03-cli.md#self-update ?

**Comment by cebe** [comment]
composer asset plugin seems to be missing.

**Comment by arimourao** [comment]
Actually, with the help of this thread:
http://stackoverflow.com/questions/25882271/cannot-update-yii2-via-composer-bower-asset-jquery-could-not-be-found

I did the following:

- run `sudo composer global require "fxp/composer-asset-plugin:1.*"

- `sudo composer self-update`

I'm presented with the following error: 

`Could not fetch https://api.github.com/repos/jquery/jquery-dist/contents/bower.json?ref=91cd1587ed4a1d4f3834227e8eb3cc30cb385409, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+dev-humhub+2016-12-03+1840
to retrieve a token. It will be stored in "/home/vagrant/.composer/auth.json" for future use by Composer.
Token (hidden): `

**Comment by cebe** [comment]
that is not an error, these are instructions on how to proceed :)

**Comment by arimourao** [comment]
Yes, actually I solved it doing exactly this. But is there anyway to avoid a new user being hassled with this? It was the first time that I had to generate this github token for anything composer related.

**Comment by cebe** [comment]
The github API limit thing could possibly resolved by using something like this: https://github.com/yiisoft/yii2/pull/13100/files

**Comment by arimourao** [comment]
Good research @cebe . Somebody gotta test this on a new environment, and if it works, submit a PR.

**Comment by arimourao** [comment]
Well, I tested and your snippet works @cebe . Should I submit a PR with this fix?

**Comment by cebe** [comment]
would be a good idea to add this, yes

**Comment by arimourao** [comment]
Can I also remove the zend-ldap dependency? In the docs says it is an optional package. And it makes sense. It is not everybody who will use zend-ldap.
