### ISSUE TITLE
Moving posts from one space to another

### ISSUE THREAD

**Issue by hfortune** [humhub/humhub#2134]
Is there a way to move a post from one space to another?

On our instance, we have a general space and then more local spaces. We'd like the ability to move posts from the general space to more specific spaces if necessary.

I noticed in the database structure that it seems that content is assigned to a space in one field. Is that the only thing that tells it where to display the content? If so, is it possible to just change that to a different space if needed?

Any thoughts or suggestions are appreciated!

**Comment by buddha87** [comment]
Currently not possible, there is a share module in progress, but I don't know the state of this module, perhaps it's possible to add a move option within the module.

**Comment by 001101** [comment]
1+

**Comment by 001101** [comment]
Is this now integrated or why is it closed?

**Comment by Felli** [comment]
@001101 this is implemented into core.

**Comment by 001101** [comment]
@Felli How can I see this from here, where is the reference?

**Comment by Felli** [comment]
You can test this via a free HumHub instance hosted by HumHub or via your own server.

**Comment by buddh4** [comment]
It's part of the v1.3 release and accessible by wall entry dropdown menu. This is not implemented for all content types yet.
