### ISSUE TITLE
Top Menu Bar Overlap

### ISSUE THREAD

**Issue by mbh-dev** [humhub/humhub#2135]
Hi All,

At present, the more links you add to the top bar, there seems to be an overlapping onto the content below, therefore making it difficult to navigate some external sites within iframes as the menu button blocks the links within the top of a page within the iframe.

Is there anyway that links do not spill onto the below frames and as such add a drop down option after the maximum number of links are allowed on the top bar.

If not is someone able to advise in how to re-write the menu bar to display to the left or right.

Many thanks

**Comment by 001101** [comment]
There is a hack out where you can add more Navs which will get separated in a extra dropdown menu, I will look later where it was.
