### ISSUE TITLE
Auto scroll down to latest message

### ISSUE THREAD

**Issue by ShalokShalom** [humhub/humhub#2136]
Chat doesnt scroll down to the latest message, after clicking on the entry in the new message notification.

**Comment by buddha87** [comment]
This should be added to modules repository https://github.com/humhub/humhub-modules-mail after v1.2 we'll enhance some of the existing modules.

**Comment by ShalokShalom** [comment]
Ähm and how do you remind about it? I mean, how get such things handled in your project?

Since i so no enhancement tag, nor a milestone entry but you already closed the issue.

**Comment by Felli** [comment]
@ShalokShalom This was closed because the messaging system used is a module which is separate from the software itself and has it's own repository. :+1:

**Comment by ShalokShalom** [comment]
Ah, ok, can you move it?
