### ISSUE TITLE
Add real time support for the notifications

### ISSUE THREAD

**Issue by ShalokShalom** [humhub/humhub#2137]
The notifications need a refresh currently, which is especially in the Chat application annoying.

**Comment by buddha87** [comment]
The mail module is not meant to be a chat module, but you are right a message update would be nice. A kind of realtime feature is planned for v1.2. For an efficient realtime communication we'd need to add a node.js/websocket solution instead of polling, which would be the next step.

**Comment by ShalokShalom** [comment]
Will this find its appearance in 1.2?

**Comment by Felli** [comment]
@ShalokShalom should have somewhat of real-time support already implemented within the beta versions, just slightly buggy is all.

**Comment by buddh4** [comment]
We'll provide "realtime" updates for the message module soon. HumHub 1.2 supports by default a simple update mechanism by polling in the future there will be an additional websockets/nodejs option.

**Comment by ShalokShalom** [comment]
Thanks a lot

**Comment by ShalokShalom** [comment]
So i can close this now?

**Comment by Felli** [comment]
At the moment HumHub only has half realtime support.

**Comment by benklop** [comment]
There is now a new PHP library (https://github.com/web-push-libs/web-push-php) and a web push API (https://www.w3.org/TR/push-api/) that could be used to do this without requiring a separate node.js component.

**Comment by luke-** [comment]
There will be an experimental support for it in the upcoming v1.3 using a NodeJS server.
https://www.npmjs.com/package/humhub-pushservice
