### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by ShalokShalom** [humhub/humhub#2138]
The search feature appears to be implemented as a workaround, is this correct?

It seems obviously, that it fits nicely into the toolbar, why does it open a separate window?

**Comment by ShalokShalom** [comment]
Hi?

**Comment by buddh4** [comment]
Wasn't this already answered in the community ?

**Comment by ShalokShalom** [comment]
Ah yeah, i see this now - wasnt in for a while. Yeah, a collapse input field is great too
