### ISSUE TITLE
Is there a way to receive an e-mail when you are tagged?

### ISSUE THREAD

**Issue by Crupuk** [humhub/humhub#2139]
When i tag someone i don't see any trace of a mail in /var/log/maillog.

I did a lot of test :
- Mention on someone who's not connected to humhub
- Mention someone with "Always send notifications" set on her profil

And still no mail.

Is there a way to configure this ? 

Thanks

**Comment by buddha87** [comment]
Hi, I think this is currently not supported but a good idea.

**Comment by Buliwyfa** [comment]
+1

**Comment by coliff** [comment]
+1
