### ISSUE TITLE
field  name on profile are not being transalated

### ISSUE THREAD

**Issue by Buliwyfa** [humhub/humhub#2141]
Hi,

I check the translation and they are translated to Spanish:
http://translate.humhub.org/index.php?r=translation%2Ftranslate&moduleId=user&language=es&file=models_ProfileFieldType

However,  fields like Country or Birthdya (in fact, all the fields) are in English, the rest; menus, tabs, etc t is translated.

Thanks

**Comment by luke-** [comment]
Fixed https://github.com/humhub/humhub/commit/231114607bffb92aeaecf567986dc541cede488e
