### ISSUE TITLE
cannot execute migrations (php yii migrate/up --includeModuleMigrations=1)

### ISSUE THREAD

**Issue by 42robots** [humhub/humhub#2143]
Hi!

currently i am not able to run the yii migration command.

I get the following error:

PHP Warning:  require(/home/humhub/protected/humhub/config/common.php): failed to open stream: No such file or directory in /home/humhub/protected/yii on line 21
PHP Fatal error:  require(): Failed opening required '/home/humhub/protected/humhub/config/common.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/humhub/protected/yii on line 21

The config is present, though.

Best,
Christian

**Comment by LThecross** [comment]
To help people who might experience that (as 42robots and me), this can be fixed by using the permissions recommended in this post: [https://community.humhub.com/content/perma?id=143717](https://community.humhub.com/content/perma?id=143717)
