### ISSUE TITLE
Add Web.config file for Windows Server (IIS)

### ISSUE THREAD

**Issue by coliff** [humhub/humhub#2144]
A .htaccess file is included in the Humhub project which is used for Apache server. Windows Server (IIS) uses web.config files instead. I use Humhub on a Windows server and created a web.config file with support for URL Rewriting for pretty urls (works great!). Do you think this should be included in this project for all users? If so I can open a PR with a new web.config file in the root dir with the following code:

```
<configuration>
    <system.webServer>
        <defaultDocument>
            <files>
                <clear />
                <add value="index.php" />
                <add value="default.html" />
                <add value="Default.htm" />
                <add value="Default.asp" />
                <add value="index.htm" />
                <add value="index.html" />
                <add value="iisstart.htm" />
                <add value="default.aspx" />
            </files>
        </defaultDocument>
        <rewrite>
    <rules>
        <!--# otherwise forward it to index.php-->
        <rule name="Imported Rule 1">
            <match url="." ignoreCase="false" />
            <conditions>
                <!--# prevent httpd from serving dotfiles (.htaccess, .svn, .git, etc.) - except let's encrypt challenge-->
                <!--# RewriteBase is required in some hosting environments (Amazon EC2, ...)-->
                <!--#RewriteBase /-->
                <!--# if a directory or a file exists, use it directly-->
                <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                <!--# prevent application 404 errors-->
                <add input="{REQUEST_FILENAME}" pattern="robots\.txt" ignoreCase="false" negate="true" />
                <add input="{REQUEST_FILENAME}" pattern="favicon\.ico" ignoreCase="false" negate="true" />
            </conditions>
            <action type="Rewrite" url="index.php" />
        </rule>
    </rules>
</rewrite>
    </system.webServer>
</configuration>
```

**Comment by razuro** [comment]
Hi Coliff,

May I know which version of IIS you're using? Tried installing fresh on IIS 7.5 resulting in 500 error.

Thanks!

**Comment by buddh4** [comment]
Thanks, rather start a PR and we'll have a look.

**Comment by seowebchecker** [comment]
What is the equivalent of below .htaccess ???
I need to use in my new website http://seowebchecker.com 
It is in Shared windows Godaddy account.

Options +FollowSymLinks
Options -Indexes
Options -Multiviews
RewriteEngine on

<FilesMatch "\.(inc|sql|bak|dat|ini|tdata|sdata|addonpk)$">
Deny from all
</FilesMatch>

    <filesMatch "\.(js|css|html|php)$">
        SetOutputFilter DEFLATE
    </filesMatch>


 RewriteCond %{THE_REQUEST} ^.*/index\.php 
 RewriteRule ^(.*)index.php$ /$1 [R=301,L] 

 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule ^admin/(.*)$ admin/index.php?route=$1 [L] 

 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule ^twitter/login(.*)$ index.php?route=twitter/login [L,QSA]  
 RewriteRule ^twitter(.*)$ index.php?route=twitter [L,QSA]  

 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule ^(.*)$ index.php?route=$1 [L]
