### ISSUE TITLE
Enhancement: Auto-Follow for new users to all members

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#2146]
Hello,

my community grows very well, but the users don't get the system, so most are missing many posts, because they don't follow each other, now I am thinking about just follow all on join and using the blacklist option instead the whitelist, which is default now.

Who else thinks it is the better way of interaction for users, vote a +1!

greets

**Comment by motohub1** [comment]
+1 Pleeeease....with close to 1000 users there is no way new users are going to go back now through the directory and follow everyone

**Comment by luke-** [comment]
https://humhub.org/de/marketplace/details?id=39

**Comment by kaoz3000** [comment]
Hey @luke- The Plugin is promising, but you have to input all the usernames manually.
I think @motohub1 and @001101 are looking for a way that a new user automatically follows ALL existing Users and ALL existing users will follow the new user automatically. Anyway this is what I am looking for. Would't that be a relatively easy enhancement of the plugin?

And isn't the "space" option of the plugin the same as the "Standardspace" option of the configuration except you can add them to existing users?

**Comment by buddh4** [comment]
Think you could [disable the user following](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/Module.php#L84) and enable [this module setting](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/dashboard/Module.php#L38) to `all`.

With the `all` setting each user should see each others public profile content on the dashboard.

**Comment by kaoz3000** [comment]
Thank you @buddh4! This is a great tipp. The disadvantage is that nobody can unfollow a person and everyone sees its own post in the dashboard. But thats ok for now. 
And also these changes could be overwritten by a system update in the feature ...

Maybe the Plugin gets an update, @luke- ?

**Comment by 001101** [comment]
> Think you could [disable the user following](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/Module.php#L84) and set [this module setting](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/dashboard/Module.php#L38) to `all`.
> 
> With the `all` setting each user should see each others public profile content on the dashboard.

I am just wondering why there are those hidden functions and no way to just pull a button to enable it, there is much hidden code in the backend.

**Comment by Felli** [comment]
The reason is so that the backend doesn't get cluttered, at some point we'll end up having to move things around to better the admin panel layout. :thinking:

**Comment by 001101** [comment]
@Felli There is no reason to have unused code

I would really like to see to boost up the frontend with all available options and settings from backend to fine grain the settings of the site. Take a look at Hubzilla or Friendica, there are massive options to set the community site as you like to and also for the user for their preferences.

**Comment by Felli** [comment]
As I said, we'll have to rework the backend so that it wouldn't be cluttered with long lists of features, so that these hidden functions can be better used in the future.

**Comment by buddh4** [comment]
@kaoz3000 such settings can be configured e.g. in `protected/config/common.php`:

```
return [
  'modules' => [
    'user' => [
       'disableFollow' => true
     ],
     'dashboard' => [
        'autoIncludeProfilePosts' => 'all'
      ]
  ]
]
```

**Comment by bananacy** [comment]
Well that worked :-) thanks!  

Ability to unfollow and follow all by default would be great to have in future versions.

thanks!

/J
