### ISSUE TITLE
Bug in userpicker messenger

### ISSUE THREAD

**Issue by Progressed36** [humhub/humhub#2150]
When testing humhub i encountered an error in the userpicker when trying to send a message to another user. The userpicker pops up, but i cant choose the person who is my display. No errors in console just an notify message that the reciever field may not be empty. When I finish the name in the input field and press send it gives me the same message. 

I can give you access to the enviroment as it is a playground to test humhub.

PS direct message from the user does work. only not from the messages screen.

**Comment by buddh4** [comment]
Is the username grayed out?

**Comment by Progressed36** [comment]
then this may be closed or maybe a change that when you have no rights your not able to search for that person ORRR an notication that you are no friends with the person en thus unable to send a message to that person.

**Comment by buddh4** [comment]
As I said there will be a tooltip on hover in v1.2, I think this way it's more obvious than excluding the user.
