### ISSUE TITLE
facebook and tweeter, rss fillers ?

### ISSUE THREAD

**Issue by Spartacus2018** [humhub/humhub#2152]
Hello, 
well i want make my own humhub community, but of course i need to add data on it, to using it evry day :!!

so the idea is to add information on humhub, even people are not here, the idea is create my own zone, with all stuff i want to see.

Exemple : 

for tweeter or facebook, i want see the message from people but not for other.

so i create a humhub user refenrenced with the profil of the person on tweeter and facebook, and all the post are automaticly integred on my humhub.

and with that i can post a message on my humhub community, that's will not on facebook and tweeter.

and make the sames things with rss from webSite, Exemple : I create a user NewYorkTimes, and all articles are on the post of this users.
Exemple if i have a facebook acount, when i post something on facebook, i want it automaticly on humhub

can we do that please ?

**Comment by 001101** [comment]
You can do anything, if you know how to code it.

**Comment by Spartacus2018** [comment]
hello, can a module out whith this features ?

thanks

**Comment by buddh4** [comment]
There will be a RSS module soon, other than that you probably won't find anyone to implement such a module for you, at least not without paying. As you can imagine there are endless open todos and module ideas around. We've recently discussed a way to inject "dynamic" stream entries as for example rss feeds into the currently "static" stream, but such a concept will take some time and needs to be added to the HumHub core. So for now you can only wait for the RSS module as a starting point.
