### ISSUE TITLE
Max number of file attachments in a post 

### ISSUE THREAD

**Issue by binarynos** [humhub/humhub#2153]
Is there a way of setting the maximum number of files that can be attached with a single post?

**Comment by binarynos** [comment]
Not really am issue, closing it.

**Comment by buddh4** [comment]
We could consider adding this in 1.2 since the upload component supports an max attribute. Think it's not a bad idea.

**Comment by binarynos** [comment]
Thanks but I just wanted to know which files need to be modified to achieve this, where is the `max attribute`?

**Comment by buddh4** [comment]
The upload widget has been rewritten: https://github.com/humhub/humhub/blob/v1.2-dev/protected/humhub/modules/file/widgets/UploadInput.php#L80 / https://github.com/humhub/humhub/blob/v1.2-dev/protected/humhub/modules/file/widgets/UploadButton.php

**Comment by binarynos** [comment]
So, this feature will be available in version 1.2, right?

**Comment by buddh4** [comment]
I've added it to our 1.2 todos.

**Comment by binarynos** [comment]
Any updates on this? I tried the version 1.2 beta but couldn't find Such a setting?

**Comment by buddh4** [comment]
sorry, forgot about this I think we'll make this configurable in beta2 by a module setting, will get back to you if this is implemented

**Comment by buddh4** [comment]
It's available now in the master branch: https://github.com/humhub/humhub/commit/1f9e55770c46c7e014ed63dda860ed06a36bc433

You'll have to set the configuration as follows in your /protected/config/common.php:

```
'modules' => [
     'content' => [
        'maxAttachedFiles' => 5
    ]
]
```

The change will be available in beta2.

**Comment by binarynos** [comment]
Thanks
