### ISSUE TITLE
Request: Gitter.im

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#2154]
Hello,

is it possible that you create a gitter.im room for the community to share and help?

Best Wishes!

**Comment by cebe** [comment]
What is wrong with https://community.humhub.com/ ?
There are also a few discussions on Humhub topics on the #yii IRC channel on freenode (http://www.yiiframework.com/chat/) from time to time.

**Comment by 001101** [comment]
That is not a chat cebe ;)

Gitter is also more dev focused, the HumHub Community is not very qualified or focosed.
Gitter is a Website, not idlething like boring IRC, where you need to wait hours for answers, i don't use IRC any more, because it is a useless time consumer.

**Comment by cebe** [comment]
and you expect people in gitter to respond faster than on IRC?

**Comment by 001101** [comment]
Yes!

I made one, only GitHub Accs allowed, join if you want

https://gitter.im/humhub-devs/Lobby

**Comment by Felli** [comment]
One of the main reasons this wasn't done is because the devs are busy with working on Humhub to answer questions, every minute spent on answering questions is time they don't have to fix issues, or add features that are asked for. :smiley:

**Comment by 001101** [comment]
Sure, but it is also more a place for people who want to contribute, but need assist or want to learn coding and not for the professional makers :)

**Comment by buddh4** [comment]
I discussed this a bit with @001101 within the community. My suggestion would be to open an invite only space within the communtiy for more experienced devs/contributors, to discuss new features API and so on, perhaps with file module task module etc. I'am aware of the benefits of gitter (quicker postings etc) but I think we should stay with HumHub and detect and solve shortcomings of the platform. 

I think the inline chat like communication for example can be implemented in HumHub 1.3. But I would also join a gitter group or something if enough people are interested.

**Comment by 001101** [comment]
Would be good to see some more devs or potential devs to join at Gitter, the marketplace is coming :1st_place_medal:
