### ISSUE TITLE
Bug: Youtube video got removed after edit

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#2155]
Hello,

have noticed a bug this evening, Clients was Dolphin Browser v9 and Opera 41, both the same.

The Youtube video link inside two text blocks just got removed after deleting some lines and spaces.

Could not find anything in Opera error console or logging, but running productive.

Running HumHub Download Version 1.1.1, maintained with HumHub Updater, NGinx, PHP-FPM, PHP 5.6, MySQL 5.5 at Debian 8

greets

**Comment by buddh4** [comment]
Thanks, could recreate it seems that the backend does not detect embedded objects.
