### ISSUE TITLE
humhub Images scale and ekko-lightbox-container size

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#2157]
Hi, I need to understand why humhub has so much problems with images. Published images are not resizing, and by establishing a max size in admin is not resolving the problem because depending if you are in Overview or in a Space, principal form has different sizes so is needed to set as max image size the Space wall size.
From other side, if you are in mobile, also images are not resizing and be totally out of screen scale. In addition to that, while clicking on images, ekko-lightbox-container has same size than embed image when in fact, it can be hugest. the logical is ti see it in max dimension or with a margin from left and right borders of screen if it´s really huge image.
![bug](https://cloud.githubusercontent.com/assets/8577866/21099941/00ea72cc-c069-11e6-9760-75cafdd9037c.jpg)

Well, definitely, images on humhub is a headache in all aspects, and even in official community you have this bug but even with ekko-lightbox-container totally broken.

![bug-humhub](https://cloud.githubusercontent.com/assets/8577866/21099945/0c7cc50e-c069-11e6-9149-fc2b1d8dce40.JPG)

Solutions?

Thank you all for take in consideration this.

**Comment by buddh4** [comment]
Hi, the ekko lightbox will be removed in 1.2 we switched to blueimp gallery.

**Comment by eddiepiazza** [comment]
omg that´s porn for my ears. When will be 1.2 release?

May I have an early release or beta ?

**Comment by buddh4** [comment]
You can check out the 1.2-dev branch, but would definetly not recommend using it for production,. I think it will be beta in january, there are still some features missing.

**Comment by 001101** [comment]
having no issues with current gallery

**Comment by eddiepiazza** [comment]
Anyway, change Ekko lightbox by blueimp will not solve the problem of rescaling in the wall. This is much more important than the lightbox because it is a disaster for phone screens. The only sollution is to make little images for click them and see them huge in the lightbox but this is not really friendly. Imagine Facebook start to make thumbnails for all publications...

**Comment by buddh4** [comment]
The previews on the wall are already scaled down, or what do you mean?

**Comment by eddiepiazza** [comment]
For you take in consideration, the image size is the one marked in admin/settings.
The fact is that this has no sense because image should adapt to the form/div of post. First of all because from Space and Overview, Post size is different and that restincts the size to the little one. Secondly because in smartphones, all images are out of scale and brokes the responsibility of the site:

![scale](https://cloud.githubusercontent.com/assets/8577866/21144980/8034aec2-c144-11e6-9ee2-c8a21a223435.jpg)

**Comment by buddh4** [comment]
So you set your max width/height too big? 
Perhaps the blueimpl slider would solve your problem https://blueimp.github.io/Gallery/ also we should use a widget which can be overwritten in themes.

**Comment by eddiepiazza** [comment]
The problem is not that is too big or too small. Is that it hasn´t autosize in base of post form size.
A slider will not save the problem. Could be interesting in the case of publishing multiple photos.
For now, the only headache is the pics autosize.

**Comment by 001101** [comment]
@eddiepiazza  Would be interesting which version you are using, from Git or the Download one?

**Comment by buddh4** [comment]
Perhaps its an theme issue. The defaul theme seems to restrict the width/height: https://github.com/humhub/humhub/blob/master/themes/HumHub/css/theme.less#L2361

**Comment by 001101** [comment]
I made directly a child theme and had never the issue with the downloaded version and I also just made the changes in CSS file, but will need to rework it to LESS when i have time, but is it also persistent.

Just for notice

**Comment by buddh4** [comment]
I'd suggest waiting for v1.2 since the less structure will change, you'll just have to overwrite your changes in the new version.

**Comment by eddiepiazza** [comment]
@001101 I have the downloaded one. I have also one extra HH compilation installed today totally clean to make some tests. And yes, height is restricted to a mini thumbnail of 130px but the logic says that images should have max space size like in facebook. This makes more comfortable see the content without click on image to get the lightbox popup. I personally hate this kind of popups.

I think this shoud has a simple fix. Si the same concept of a background in **cover**/**contain** mode.

**Comment by eddiepiazza** [comment]
One question for Admins and developpers. I fully translated HumHub in spanish and also most of modules I have, officials and not officials.

Do you want I send you my files for you inlcude them in HH 1.2?

I am worry that next update will override all my translations...

**Comment by buddh4** [comment]
Either commit dem or do you use http://translate.humhub.org. Version 1.1.2 will be out by tomorrow I think so its too late for this version but you can commit it for version 1.2

**Comment by eddiepiazza** [comment]
Hi, I updated to 1.1.2 and surprise, now all images are in max size 200px.

![size1](https://cloud.githubusercontent.com/assets/8577866/21182484/4410dc2e-c1fb-11e6-891a-64e6c2a8edca.JPG)

The strange thing is that custom size is not working anymore:

![config](https://cloud.githubusercontent.com/assets/8577866/21182645/0145f3ba-c1fc-11e6-8a67-5e361e769690.JPG)

Well, after all conversation from the beginning, it still not existing an idea of how to delete this size restriction for images fits perfectly the size like perfectly happens with embed videos:

![video](https://cloud.githubusercontent.com/assets/8577866/21182705/58700b1c-c1fc-11e6-98c2-9744d29dd4c4.JPG)

No one has an idea how to give to images same rescale properties than videos?

**Comment by buddh4** [comment]
have you tried adding max-width: 100% in your theme for selector .post-files img also remove max-height

**Comment by eddiepiazza** [comment]
OH! Ohhhhhhh, fantaaastic !!!

Now I need to know only where how can I override or kill this style line code that has absolutely no sense (taking in consideration that size is already being controlled from Admin). I can search it with notepad++, but will takes me time to localize it.

<img src="http://www.gropedia.com/file/file/download?guid=c7149c42-aaee-49c4-948f-da340ad8a959&amp;suffix=pi_600x600" **style="max-height:200px;max-width:200px;**">

**Comment by eddiepiazza** [comment]
Take note for next 1.2 update:

-Delete style="max-height:200px;max-width:200px;" from images code (conflict with preview image size)
-Add in Advanced Settings/Files the option of Autosize all images (By css override)

**Comment by nguyen-matthias** [comment]
If this **style="max-height:200px;max-width:200px;"** remove from my code it's resolved my issues too ....
Someone finde this line to remove ?? I can't finde it

**Comment by nguyen-matthias** [comment]
I have a workaround via CSS editing 💃 

 i have add this Line to my .less file :
.post-files {
  img {
    vertical-align: top;
    margin-bottom: 3px;
    margin-right: 5px;
    **max-height: 600px !important;
    max-width: 500px !important;**

  }


on theme.css :

.post-files img{vertical-align:top;margin-bottom:3px;margin-right: 5px;**max-height: 600px !important;max-width: 500px !important;**}

the CSS will be overrite by _!important_ the element.style 

![after](https://cloud.githubusercontent.com/assets/16917852/21307409/aa01cb00-c5d5-11e6-9685-15ed971e61c5.png)
![bevore](https://cloud.githubusercontent.com/assets/16917852/21307410/aa1d1590-c5d5-11e6-82b9-89d352333389.png)

**Comment by eddiepiazza** [comment]
Some of my fixes (Just replace this lines):

1) Go to \js\ekko-lightbox-modified.js (line 42)

$(document.body).append('<div id="' + this.modal_id + '" class="ekko-lightbox modal" tabindex="-1"><div class="modal-dialog" style="padding-top:20px"><div class="modal-content">' + header + '<div class="modal-body"><div class="ekko-lightbox-container"><div></div></div></div>' + footer + '</div></div></div>');

2) protected\humhub\modules\file\widgets\views\showFiles.php (line 23)

<img src='<?= $file->getPreviewImageUrl($maxPreviewImageWidth ? $maxPreviewImageWidth : 1000, $maxPreviewImageHeight ? $maxPreviewImageHeight : 1000); ?>'>

3) themes\_YourTheme_\css\theme.css

.post-files img{
vertical-align:top;
margin-bottom:3px;
max-width: 97%;
border-radius:5px;
}

.post-files:hover img{
transition: all 0.5s ease;
box-shadow: 5px 5px 5px #afafaf;
}

Enjoy!
