### ISSUE TITLE
Bug: v1.1.1 no json load at zoomed page

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#2158]
Hello,

having now again the json bug, which is new with update on v1.1.1. 
Using Opera 41 and have zoomed in three or four times for better viewing and the posts get not loaded when i am on 120% or 130% zoom, i am at the bottom of the page, just zoom out to 110% and the loading works again, that is a strange behaviour and there is no error in console.

Have tried it on three different Hubs (my own productive, HumHub Community and gropedia.com) all the same.

greets

**Comment by buddh4** [comment]
You mean the automatic "load more" is not triggered on opera with zoom?

**Comment by 001101** [comment]
Yes

**Comment by acs-ferreira** [comment]
Are you talking about v1.1.1 or v1.1.**2** ?

**Comment by cebe** [comment]
v1.1.2 was released about 3hours ago ;)

**Comment by acs-ferreira** [comment]
Oups have not payed attention to time @cebe

**Comment by buddh4** [comment]
Seems to be fixed in 1.2
