### ISSUE TITLE
HumHub Sign up not working

### ISSUE THREAD

**Issue by noor1992** [humhub/humhub#2159]
Hi folks,
I have installed Humhub Community on our intranet, I have configured the mails server setting;
 
using

email sender address: admin email add
name : name
Mail transport type: SMTP
Hostname: smtp.gmail.com
username: username@gmail.com
port: 465

when new user sign up, get this error.

Swift_TransportException

Expected response code 220 but got code "", with message ""
1. in /var/www/html/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php at line 383
374375376377378379380381382383384385386387388389390391392        $valid = (empty($wanted) || in_array($code, $wanted));
 
        if ($evt = $this->_eventDispatcher->createResponseEvent($this, $response,
            $valid)) {
            $this->_eventDispatcher->dispatchEvent($evt, 'responseReceived');
        }
 
        if (!$valid) {
            $this->_throwException(
                new Swift_TransportException(
                    'Expected response code '.implode('/', $wanted).' but got code '.
                    '"'.$code.'", with message "'.$response.'"',
                    $code)
                );
        }
    }
 
    /** Get an entire multi-line response using its sequence number */
    protected function _getFullResponse($seq)
2. in /var/www/html/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php at line 289 – Swift_Transport_AbstractSmtpTransport::_assertResponseCode('', [220])
283284285286287288289290291292293294295        return $response;
    }
 
    /** Read the opening SMTP greeting */
    protected function _readGreeting()
    {
        $this->_assertResponseCode($this->_getFullResponse(0), array(220));
    }
 
    /** Send the HELO welcome */
    protected function _doHeloCommand()
    {
        $this->executeCommand(
3. in /var/www/html/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php at line 117 – Swift_Transport_AbstractSmtpTransport::_readGreeting()
111112113114115116117118119120121122123 
            try {
                $this->_buffer->initialize($this->_getBufferParams());
            } catch (Swift_TransportException $e) {
                $this->_throwException($e);
            }
            $this->_readGreeting();
            $this->_doHeloCommand();
 
            if ($evt) {
                $this->_eventDispatcher->dispatchEvent($evt, 'transportStarted');
            }
 
4. in /var/www/html/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php at line 79 – Swift_Transport_AbstractSmtpTransport::start()
73747576777879808182838485     */
    public function send(Swift_Mime_Message $message, &$failedRecipients = null)
    {
        $failedRecipients = (array) $failedRecipients;
 
        if (!$this->_transport->isStarted()) {
            $this->_transport->start();
        }
 
        $sent = 0;
 
        try {
            $sent = $this->_transport->send($message, $failedRecipients);
5. in /var/www/html/humhub/protected/vendor/yiisoft/yii2-swiftmailer/Mailer.php at line 146 – Swift_Mailer::send(Swift_Message)
140141142143144145146147148149150151152        $address = $message->getTo();
        if (is_array($address)) {
            $address = implode(', ', array_keys($address));
        }
        Yii::info('Sending email "' . $message->getSubject() . '" to "' . $address . '"', __METHOD__);
 
        return $this->getSwiftMailer()->send($message->getSwiftMessage()) > 0;
    }
 
    /**
     * Creates Swift mailer instance.
     * @return \Swift_Mailer mailer instance.
     */
6. in /var/www/html/humhub/protected/vendor/yiisoft/yii2/mail/BaseMailer.php at line 260 – yii\swiftmailer\Mailer::sendMessage(yii\swiftmailer\Message)
7. in /var/www/html/humhub/protected/vendor/yiisoft/yii2/mail/BaseMessage.php at line 48 – yii\mail\BaseMailer::send(yii\swiftmailer\Message)
8. in /var/www/html/humhub/protected/humhub/modules/user/models/Invite.php at line 128 – yii\mail\BaseMessage::send()
122123124125126127128129130131132133134                'token' => $this->token,
                'registrationUrl' => $registrationUrl
            ]);
            $mail->setFrom([Yii::$app->settings->get('mailer.systemEmailAddress') => Yii::$app->settings->get('mailer.systemEmailName')]);
            $mail->setTo($this->email);
            $mail->setSubject(Yii::t('UserModule.views_mails_UserInviteSelf', 'Registration Link'));
            $mail->send();
        } elseif ($this->source == self::SOURCE_INVITE && $this->space !== null) {
 
            if($module->sendInviteMailsInGlobalLanguage) {
                Yii::$app->language = Yii::$app->settings->get('defaultLanguage');
            }
 
9. in /var/www/html/humhub/protected/humhub/modules/user/models/Invite.php at line 100 – humhub\modules\user\models\Invite::sendInviteMail()
949596979899100101102103104105106        if ($existingInvite !== null) {
            $this->token = $existingInvite->token;
            $existingInvite->delete();
        }
 
        if ($this->allowSelfInvite() && $this->validate() && $this->save()) {
            $this->sendInviteMail();
            return true;
        }
 
        return false;
    }
 
10. in /var/www/html/humhub/protected/humhub/modules/user/controllers/AuthController.php at line 84 – humhub\modules\user\models\Invite::selfInvite()
78798081828384858687888990            return $this->onAuthSuccess($login->authClient);
        }
 
        // Self Invite 
        $invite = new Invite();
        $invite->scenario = 'invite';
        if ($invite->load(Yii::$app->request->post()) && $invite->selfInvite()) {
            if (Yii::$app->request->getIsAjax()) {
                return $this->render('register_success_modal', ['model' => $invite]);
            } else {
                return $this->render('register_success', ['model' => $invite]);
            }
        }
11. humhub\modules\user\controllers\AuthController::actionLogin()
12. in /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\user\controllers\AuthController, 'actionLogin'], [])
13. in /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'user/auth/login'])
14. in /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('login', ['r' => 'user/auth/login'])
15. in /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 100 – yii\base\Module::runAction('user/auth/login', ['r' => 'user/auth/login'])
16. in /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
17. in /var/www/html/humhub/index.php at line 25 – yii\base\Application::run()
19202122232425    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'user/auth/login',
];

$_POST = [
    '_csrf' => 'cFFSSzdZLkECMhQHZTVbJkYkFT1Zb0MDOjhmHUUudjEEZiAYTm9DCQ==',
    'Invite' => [
        'email' => 'sonu@mounttalent.com',
    ],
];

$_COOKIE = [
    'pm_getting-started-panel' => 'expanded',
    'pm_space-members-panel' => 'expanded',
    'pm_groups-statistics-panel' => 'expanded',
    'pm_new-people-panel' => 'expanded',
    'pm_user-statistics-panel' => 'expanded',
    'pm_new-spaces-panel' => 'expanded',
    'pm_spaces-statistics-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_profile-friends-panel' => 'expanded',
    'pm_user-tags-panel' => 'expanded',
    '_csrf' => '669e589450d3a571ea466b5d601da068e864c16a3d18300879e6d019ecb47afca:2:{i:0;s:5:"_csrf";i:1;s:32:"rcFLRlug6uGvn6mBJi4VrwXpt7rSy6mH";}',
    'language' => '066b2f2a934613d96935be69482a1e86c06ad8c92ce5cf49c7240487f2b2ab9fa:2:{i:0;s:8:"language";i:1;s:2:"en";}',
    'PHPSESSID' => 'rkqj963tro4potmgi2n8h41d54',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/index.php',

**Comment by buddh4** [comment]
Have a look at the following ticket: https://github.com/piwik/piwik/issues/8613

**Comment by noor1992** [comment]
Thanks @buddh4 , it says that I should enable Google Less Seure app, it is already enabled and Imap & pop forwarding are enabled too.

**Comment by buddh4** [comment]
What are your encryption settings?

**Comment by noor1992** [comment]
I tested on both SSL and TLS, non of em worked now I disabled SSL and TLS

**Comment by noor1992** [comment]
It worked thanks
