### ISSUE TITLE
Georgin language translation

### ISSUE THREAD

**Issue by dacdacdac** [humhub/humhub#2161]
https://en.wikipedia.org/wiki/Georgian_language

I already created space
http://translate.humhub.org/index.php?r=space%2Fspace&sguid=f8437152-6e65-483d-b389-6f49fe0f7ac4

**Comment by dacdacdac** [comment]
how to add Georgian language?

**Comment by buddh4** [comment]
If it's a new language we have to add it to humhub first, I'll forward your request.
