### ISSUE TITLE
Uploaded mp3 not playing, it shows 0B.

### ISSUE THREAD

**Issue by noor1992** [humhub/humhub#2162]
When upload the mp3 file, it shows the uploading process complete but after that it only shows 0B.
Cant be played. 
Video files cant be uploaded either, it shows uploaded process but it quiets uploading at end.
![mp3](https://cloud.githubusercontent.com/assets/24589033/21260774/95f29894-c3ad-11e6-9b0a-4fb77cff6ac8.jpg)

**Comment by buddh4** [comment]
Could not reproduce this, does this happen for all mp3s? Also get sure the uploaded files do not exceed the upload limit set in "Administration -> Settings -> Advanced -> Files".

Also check the upload_max_filesize of your php.ini

**Comment by noor1992** [comment]
I have set the file upload size limit to 50 MB, still the same issue.

**Comment by buddh4** [comment]
Did you also check the following settings in your php.ini:

; Maximum allowed size for uploaded files.
upload_max_filesize = 40M

; Must be greater than or equal to upload_max_filesize
post_max_size = 40M

**Comment by noor1992** [comment]
@buddh4 Thanks for that, it worked, I have changed upload max size in php.in
, but still there is an issue with uploaded video file, it can not be played on humhub, I think humhub lacks any kinda player or plugin to allow play video files.

**Comment by buddh4** [comment]
Hi yes, there is no video player yet, hope we are able to include thi sin v1.2
