### ISSUE TITLE
List of new errors after update 1.1.2

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#2163]
Well, is normal to get some new errors after updates, I will start to publish the first one I get in my case:

ERROR  Thu, 15 Dec 2016 17:40:07 +0000  yii\web\HttpException:405
exception 'yii\web\HttpException' with message 'El módulo no está habilitado en este contenedor de contenido!' in /home/opengrow/public_html/es/community/protected/humhub/modules/content/components/ContentContainerController.php:102 Stack trace: #0 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\modules\content\components\ContentContainerController->init() #1 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(84): yii\base\Object->__construct(Array) #2 [internal function]: yii\base\Controller->__construct('page', Object(humhub\modules\wiki\Module), Array) #3 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/di/Container.php(373): ReflectionClass->newInstanceArgs(Array) #4 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/di/Container.php(154): yii\di\Container->build('humhub\\modules\\...', Array, Array) #5 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/BaseYii.php(340): yii\di\Container->get('humhub\\modules\\...', Array) #6 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(569): yii\BaseYii::createObject('humhub\\modules\\...', Array) #7 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(522): yii\base\Module->createControllerByID('page') #8 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(514): yii\base\Module->createController('page/view') #9 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(448): yii\base\Module->createController('wiki/page/view') #10 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('wiki/page/view', Array) #11 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 /home/opengrow/public_html/es/community/index.php(25): yii\base\Application->run() #13 {main}

**Comment by eddiepiazza** [comment]
This error is coming always with an INFO message before:

$_GET = [ 'title' => 'Tutorial de configuración de cámaras IP' 'sguid' => 'af5145aa-f034-4556-ade8-fc35485d85ae' ] $_SERVER = [ 'CONTEXT_DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'CONTEXT_PREFIX' => '' 'DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'es,en-GB;q=0.8,en;q=0.6,fr;q=0.4,pt-PT;q=0.2,pt;q=0.2' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_COOKIE' => 'pm_space-members-panel=expanded; G_ENABLED_IDPS=google; _csrf=a77daf17120ff3c185de79b17cd9de89756a737327d2a24d1eee744592681e75a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22hRMx9clhzPgsCqO6OFMf_xiL1RZ38jcV%22%3B%7D; pm_getting-started-panel=expanded; pm_online-users-panel=expanded; _ga=GA1.2.1762731330.1481629008; language=171f215eabfc3ad44c23b882291a1fc4f46e59efc26e0a3ea46fdf298dbc9952a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22es%22%3B%7D; PHPSESSID=6017a91944774b1018b918db69fb4434; _identity=3a9ad0ccab810ed194075869573792d29226e240a7e3ff06a36c0ce89355457da%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%226052fbd8-77ba-4499-8c4e-f1a5cf5ff783%22%2C2592000%5D%22%3B%7D' 'HTTP_HOST' => 'www.gropedia.com' 'HTTP_MOD_REWRITE' => 'On' 'HTTP_REFERER' => 'http://www.gropedia.com/s/grupo-privadopublico-de-testers-espana/' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => 'title=Tutorial+de+configuraci%C3%B3n+de+c%C3%A1maras+IP' 'REDIRECT_HTTP_MOD_REWRITE' => 'On' 'REDIRECT_QUERY_STRING' => 'title=Tutorial+de+configuraci%C3%B3n+de+c%C3%A1maras+IP' 'REDIRECT_STATUS' => '200' 'REDIRECT_UNIQUE_ID' => 'WFLVdyU97MUABrHOoJ0AAAAv' 'REDIRECT_URL' => '/s/grupo-privadopublico-de-testers-espana/wiki/page/view' 'REMOTE_ADDR' => '176.79.118.201' 'REMOTE_PORT' => '61253' 'REQUEST_METHOD' => 'GET' 'REQUEST_SCHEME' => 'http' 'REQUEST_URI' => '/s/grupo-privadopublico-de-testers-espana/wiki/page/view?title=Tutorial+de+configuraci%C3%B3n+de+c%C3%A1maras+IP' 'SCRIPT_FILENAME' => '/home/opengrow/public_html/es/community/index.php' 'SCRIPT_NAME' => '/index.php' 'SERVER_ADDR' => '37.61.236.197' 'SERVER_ADMIN' => 'webmaster@gropedia.open-grow.co.uk' 'SERVER_NAME' => 'www.gropedia.com' 'SERVER_PORT' => '80' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'UNIQUE_ID' => 'WFLVdyU97MUABrHOoJ0AAAAv' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1481823607.6809 'REQUEST_TIME' => 1481823607 'argv' => [ 0 => 'title=Tutorial' 1 => 'de' 2 => 'configuraci%C3%B3n' 3 => 'de' 4 => 'c%C3%A1maras' 5 => 'IP' ] 'argc' => 6 ]

**Comment by buddh4** [comment]
When trying to access the wiki module on space with guid af5145aa-f034-4556-ade8-fc35485d85ae it throws this error, it seems the wiki module is not enabled on this space. Doesn't seem like an update issue.

**Comment by eddiepiazza** [comment]
New problem discovered while executing by SSH php yii integrity/run

After fix this next errors, all modules that had "establish by default for all spaces/users" went to disabled.
Before the update never happens, and after this update, I run 2 times this command and happens the same.

Deleting space module 37 without existing space! (yes|no) [no]:y
Deleting space module 36 without existing space! (yes|no) [no]:y
Deleting space module 35 without existing space! (yes|no) [no]:y
Deleting space module 41 without existing space! (yes|no) [no]:y
Deleting space module 39 without existing space! (yes|no) [no]:y
Deleting space module 40 without existing space! (yes|no) [no]:y
Validating: Space Module - Memberships (287 entries)
Validating: User Module - Users (83 entries)
Validating: User Module - Password (87 entries)
Validating: User Module - Profile (83 entries)

Validating: User Module - Mentioning (5 entries)
Validating: User Module - Follow (243 entries)
Validating: User Module - Modules (6 entries)
Deleting user-module 15 of non existing user! (yes|no) [no]:y
Deleting user-module 16 of non existing user! (yes|no) [no]:y
Deleting user-module 17 of non existing user! (yes|no) [no]:y
Deleting user-module 17 of non existing user! (yes|no) [no]:y

*** All integrity checks done
