### ISSUE TITLE
500 Internal Server Error for some images while loading

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#2165]
I noticed a strange loading page error when some of images were broken. This is totally aleatory and once page is updated, broken image could be fixed and by scrolling and seeing more content, other images present same problem. Is clear that is a problem related with how images are being shown because I copied URL and it works perfectly. In my opinion is a synchronisation problem with the rescale command.

I will try to make me better explain. Here is what I see:
![1](https://cloud.githubusercontent.com/assets/8577866/21359331/d8f33530-c6d3-11e6-8590-344e6dffa64a.JPG)

This is the error:
![error](https://cloud.githubusercontent.com/assets/8577866/21359342/e3475d5e-c6d3-11e6-9cf4-77280d1c6366.JPG)

This is once the page is being updated:
![ok](https://cloud.githubusercontent.com/assets/8577866/21359356/f07ca574-c6d3-11e6-99f7-dc610c5a701f.JPG)

I made a Test by deleting the size restriction (in my case 500px):
![image](https://cloud.githubusercontent.com/assets/8577866/21359439/3596ad8a-c6d4-11e6-91c7-e2211b77c43b.png)

And it works perfectly so this is why I considere that the problem is from here:

![image](https://cloud.githubusercontent.com/assets/8577866/21359540/79121b80-c6d4-11e6-8676-5ff50f5536bc.png)

**Comment by buddh4** [comment]
Please check your error logs, all 500 errors should be logged.
