### ISSUE TITLE
Template layout discarded 

### ISSUE THREAD

**Issue by thomaswillecomme** [humhub/humhub#2166]
When creating a new static page,
I set the layout to system_one_column_layout.
When submitting the field is not validated with the green border.
Wen editing back the page, the layout is system_two_column_layout instead of system_one_column_layout.

**Comment by thomaswillecomme** [comment]
I only have the problem on a hosted install built with composer from the master following your documentation (by the way everything went smoothly).
* I built it locally and uploaded it to my provider (i had to remove the symlinks under protected as they weren't supported by the remote server)
* then i updated the core and modules until having the 1.1.2. maybe it is related to the database migration.

**Comment by buddh4** [comment]
Hi, I could recreate this issue.
In my case only the displayed layout in the page configuration is wrong, the applied page layout is correct, can you confirm this?

I'll fix this within the next days, thanks for noting.
By the way, there are seperate repositories for our modules which should be prefered when creating issues https://github.com/humhub/humhub-modules-custom-pages

**Comment by thomaswillecomme** [comment]
Hello buddh4,
Yes, I confirm this behavior. The page content cannot be edited as well, it shows 

> Empty
> Container

Ok, i'll be more careful when reporting a new bug.

By the way, I have to say that i am really impressed by the quality of humhub and how easy it is to install. :+1:

**Comment by buddh4** [comment]
Thanks for the positive feedback ;)

Empty Container means, that there is a container placeholder which can be filled with either only one or multiple container items (depending on the container block setting). Container Templates are defined under  "Administration -> Custom Pages -> Templates -> Container" and can be embeded into defined container placeholder blocks which is just a type of placeholder beside e.g. Richtext,Image etc.

The content area of your layout for example does only contain a container placeholder which can be filled with a header, some articles etc..

You can add container items when you are in edit mode and hover the empty container. When hovering there should be a small edit nav with container name and a plus button.

The usability of this module will definetly be enhanced after the v1.2 release, wich some more help texts and a small guide or something.

**Comment by buddh4** [comment]
will close this issue, if you have other questions, switch to the other issue I created.
