### ISSUE TITLE
APCu Support

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2167]
When will APCu Support be available in Humhub if ever?

**Comment by cebe** [comment]
duplicate of #2005, if you have time you can complete #2015 to get it merged.

**Comment by Felli** [comment]
@cebe thanks for bring those up, but this is a general question of when it will be supported that is all, I am guessing it will be available in 1.2 hopefully. :smile:

**Comment by cebe** [comment]
you can already use it by manual configuration. It is just not automatic. Also this is open source, you can have it in 1.1.x if the pull request gets completed ;)
