### ISSUE TITLE
Activity Stream leading to 500 Error

### ISSUE THREAD

**Issue by georgigrant** [humhub/humhub#2168]
Here is what chrome dev. tools is saying:

`jquery.js?v=1482311038:9175 GET http://***.com/index.php?r=space%2Fspace%2Fstream&limit=10&from=&mode=activity&sguid=ac61f16b-096c-4f86-b8e7-716042d69b03 500 (Internal Server Error)send 
@ jquery.js?v=1482311038:9175ajax 
@ jquery.js?v=1482311038:8656jQuery.(anonymous function) 
@ jquery.js?v=1482311038:8807getJSON 
@ jquery.js?v=1482311038:8788loadMoreActivities 
@ activies.js?v=1481653562:79(anonymous function) 
@ activies.js?v=1481653562:114fire 
@ jquery.js?v=1482311038:3187fireWith 
@ jquery.js?v=1482311038:3317ready 
@ jquery.js?v=1482311038:3536completed 
@ jquery.js?v=1482311038:3552

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.` jquery.js?v=1482311038:9064 

Everythng on my server config is green, any idea what's causing this?

George

**Comment by buddh4** [comment]
If its a Internal Server Error, please check the logs under "Administration -> Information -> Logging" also which HumHub version are you using?

**Comment by georgigrant** [comment]
wow, thanks for the fast reply! 

I am using 1.1.2. Log is clean. It has something to do with the activity stream. It either loads the main stream (space) or the 'latest activities' on the right side. 

Do you want me to give you a test account? 

Thanks a lot for the fast response. 

George

**Comment by georgigrant** [comment]
Got three entries now in the log, seems like it needed more time:

> $_GET = [ 'r' => 'admin/setting/design' ] $_SERVER = [ 'CONTEXT_DOCUMENT_ROOT' => '/home/georgigr/public_html/thirtytrio.com' 'CONTEXT_PREFIX' => '' 'DOCUMENT_ROOT' => '/home/georgigr/public_html/thirtytrio.com' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 'HTTP_ACCEPT_ENCODING' => 'gzip' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,de;q=0.6,bg;q=0.4,zh-CN;q=0.2,zh;q=0.2' 'HTTP_CF_CONNECTING_IP' => '69.88.134.87' 'HTTP_CF_IPCOUNTRY' => 'US' 'HTTP_CF_RAY' => '314a94aec1c133a3-HKG' 'HTTP_CF_VISITOR' => '{\"scheme\":\"http\"}' 'HTTP_CONNECTION' => 'Keep-Alive' 'HTTP_COOKIE' => '__cfduid=d14a49e77e622e14848b85aa760fa5cff1482225474; _csrf=531357137b5e347daad8c0941c1c517c653324b2200c61b453baa16a71d3abe8a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22AquahJM7otSy3RTBEEcnaQnrO2cg6JLA%22%3B%7D; PHPSESSID=mkvovp8gj5f0mkqkr7fp9clj35; pm_getting-started-panel=expanded; pm_space-members-panel=expanded; pm_user-tags-panel=expanded; pm_user-spaces-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; _identity=401a2cd54b043d8f552e8584cfcf195864ed7766e2d6fb376eef80c495a3b8f0a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%220c933e9a-2f99-47e1-a490-e1e9cef9218a%22%2C2592000%5D%22%3B%7D' 'HTTP_HOST' => 'thirtytrio.com' 'HTTP_REFERER' => 'http://thirtytrio.com/index.php?r=admin%2Fsetting%2Fbasic' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36' 'HTTP_X_FORWARDED_FOR' => '69.88.134.87' 'HTTP_X_FORWARDED_PROTO' => 'http' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => 'r=admin%2Fsetting%2Fdesign' 'REDIRECT_STATUS' => '200' 'REMOTE_ADDR' => '162.158.178.35' 'REMOTE_PORT' => '22173' 'REQUEST_METHOD' => 'GET' 'REQUEST_SCHEME' => 'http' 'REQUEST_URI' => '/index.php?r=admin%2Fsetting%2Fdesign' 'SCRIPT_FILENAME' => '/home/georgigr/public_html/thirtytrio.com/index.php' 'SCRIPT_NAME' => '/index.php' 'SERVER_ADDR' => '103.44.161.57' 'SERVER_ADMIN' => 'webmaster@thirtytrio.georgigrancharov.com' 'SERVER_NAME' => 'thirtytrio.com' 'SERVER_PORT' => '80' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'UNIQUE_ID' => 'WFpWkWcsoTIAAMcnJOcAAACK' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1482315409.7095 'REQUEST_TIME' => 1482315409 ]

and: 

> Wed, 21 Dec 2016 18:16:49 +0800  yii\validators\FileValidator::getSizeLimit
PHP.ini's 'post_max_size' is less than 'upload_max_filesize'.

even though I didn't try to upload anything. 
My knowledge is not the best, any help would be highly appreciated. 

George

**Comment by buddh4** [comment]
Hmm seems to be unrelated to your problem but nontheless you should check your php.ini file and check the value of  'post_max_size' and 'upload_max_filesize'.

You can also check in your developer console -> Network, which request fails and check the server response. The response should contain the actual error stack.

**Comment by Felli** [comment]
I know what he means, in the browser console it's showing a XMLHttpRequest warning on the main thread because of ``xhr.open(`` which is line 9064 of jquery.js might need looked over to see if this needs fixed, it also appears on Humhub's community site. :smiley:

**Comment by buddh4** [comment]
The warning is not the problem, this is triggered by the synchronous scrip loading of yii I think, which is required to ensure the script loading order.

**Comment by globeFrEak** [comment]
Hi, i have the same issue.
I have found out that it is only for normal users. As admin no error occures and the activity stream is shown.
![2017-02-05 13_47_19-](https://cloud.githubusercontent.com/assets/589071/22626303/ae37e9e8-ebaa-11e6-914c-58847cf49f48.png)

**Comment by buddh4** [comment]
This happens in case of integrity issues, try running "php yii integrity/run" in your protected directory. Also which HumHub version are you using, such errors should be caught in newer versions.
