### ISSUE TITLE
1.2 dev installation error

### ISSUE THREAD

**Issue by soju7** [humhub/humhub#2169]
http://prntscr.com/dm5py4
Trying to install humhub1.2 dev .unfortunately i got **SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'humhub'.**  why this happen? . i can able to install humhub 1.1.2  with no errors. Thanks in advance.

**Comment by 001101** [comment]
cause your password is wrong??!

**Comment by ajilmv138** [comment]
I am also stuck in the same issue. When I am trying to install humhub1.2 dev, first page shows this error message.  "SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'humhub'". How can i solve this. please help me. Thanks in advance

**Comment by soju7** [comment]
no actually the error is from protected/humhub/config/common.php .
http://prntscr.com/doe69e
this happen during first step.
 http://localhost/humhubv1.2/index.php?r=installer%2Findex
i never had this issue on other versions installation.
pls help

**Comment by buddh4** [comment]
Seems to be an issue with the new View logic.

**Comment by soju7** [comment]
still got the same error after pulling new changes

**Comment by buddh4** [comment]
Sorry there was a file missing in the commit.

**Comment by spsinghats** [comment]
I have both these commits and I am having the same issue. Tried, v.1.2.0-beta.1 and the master as on 23 Feb 2017.
