### ISSUE TITLE
The CSRF token could not be verified after updating domain name

### ISSUE THREAD

**Issue by naveenabt** [humhub/humhub#2170]
After changing domain name, i am getting below issue.
Exception Message:

The CSRF token could not be verified.

**Comment by 001101** [comment]
Delete your cookies, try private browser tab or/and different browser

**Comment by naveenabt** [comment]
Thanks, I have deleted cookies and tried i am getting same issue.

**Comment by 001101** [comment]
Also cache and used a different browser? Can you edit php.ini?

**Comment by naveenabt** [comment]
please tel me. what i need to do in php.ini

**Comment by naveenabt** [comment]
yes tried in different machine, same issue getting

**Comment by 001101** [comment]
Try to set higher upload_max_filesize variable and  post_max_size to minimum 32M

**Comment by naveenabt** [comment]
before changing domain name it was working fine. After changing domain i am facing this issue

**Comment by buddh4** [comment]
Where exactly does this occure, on all forms? Check if the csrf token is send with your post requests. And as @001101 suggested clear your cache (Administration -> Settings -> Advanced -> Caching. And check the base url in Administration -> Settings -> Basic.

**Comment by naveenabt** [comment]
In all form showing same issue. But in all form CSRF token is there.

**Comment by naveenabt** [comment]
I have checked CSRF tocken not storing in session

**Comment by naveenabt** [comment]
Issue resolved:
ini_set('session.cookie_domain', '.localhost' );
we need to set cookie domain name
