### ISSUE TITLE
Fatal Error in Line ...

### ISSUE THREAD

**Issue by HarryM61** [humhub/humhub#2172]
Hello i'm new here in the board.

I've installed the HumHub Program with the Tools Softaculous on an VPS with CentOs6.3
By the Registration Process from Users i get the registruation lik, but in the mask with password and full name i get an Error Message by saving:
Whats going wrong?

Here the text in the browser after saving.
Many thx for replies of this issue.
 
PHP Fatal Error – yii\base\ErrorException PHP Fa PHP Fatal Error – yii\base\ErrorException
Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

    1. in /home/fazebuch/public_html/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php at line 99
    90919293949596979899100101102103104105106107108

     
                // matched string
                $matchedWord = $match[0][0];
     
                // binary position of the matched word in the input stream
                $binStartPos = $match[0][1];
     
                // character position of the matched word in the input stream
                $startPos = $this->_position +
                            iconv_strlen(substr($this->_input,
                                                $this->_bytePosition,
                                                $binStartPos - $this->_bytePosition),
                                         'UTF-8');
                // character postion of the end of matched word in the input stream
                $endPos = $startPos + iconv_strlen($matchedWord, 'UTF-8');
     
                $this->_bytePosition = $binStartPos + strlen($matchedWord);
                $this->_position     = $endPos;
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'user/registration',
    'token' => 'te4C4h1QCMe9',
];

$_POST = [
    '_csrf' => 'Qnk3R1M3Q0YPGlwUKUQ3dzJJZwkfAXYgIyZZKgxjBxEnS1oYHXgTKQ==',
    'User' => [
        'username' => 'Test99',
    ],
    'GroupUser' => [
        'group_id' => '2',
    ],
    'Password' => [
        'newPassword' => 'test99',
        'newPasswordConfirm' => 'test99',
    ],
    'Profile' => [
        'firstname' => 'test',
        'lastname' => 'user',
    ],
    'save' => '',
];

$_COOKIE = [
    'PHPSESSID' => '4aut5b1isqa0it3u9eg46r28m6',
    '_csrf' => '1e35956c652bc71b98b7912a122c22e5e74d487e844182bc5b7d058a00cdf60ba:2:{i:0;s:5:"_csrf";i:1;s:32:"MckSzst1p0PNL65fa_nm_TDWe2m_NOPo";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/index.php?r=',
];

Yii Framework

2016-12-24, 12:23:30

Apache

Yii Framework/2.0.10
tal Error – yii\base\ErrorException
Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

    1. in /home/fazebuch/public_html/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php at line 99
    90919293949596979899100101102103104105106107108

     
                // matched string
                $matchedWord = $match[0][0];
     
                // binary position of the matched word in the input stream
                $binStartPos = $match[0][1];
     
                // character position of the matched word in the input stream
                $startPos = $this->_position +
                            iconv_strlen(substr($this->_input,
                                                $this->_bytePosition,
                                                $binStartPos - $this->_bytePosition),
                                         'UTF-8');
                // character postion of the end of matched word in the input stream
                $endPos = $startPos + iconv_strlen($matchedWord, 'UTF-8');
     
                $this->_bytePosition = $binStartPos + strlen($matchedWord);
                $this->_position     = $endPos;
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'user/registration',
    'token' => 'te4C4h1QCMe9',
];

$_POST = [
    '_csrf' => 'Qnk3R1M3Q0YPGlwUKUQ3dzJJZwkfAXYgIyZZKgxjBxEnS1oYHXgTKQ==',
    'User' => [
        'username' => 'Test99',
    ],
    'GroupUser' => [
        'group_id' => '2',
    ],
    'Password' => [
        'newPassword' => 'test99',
        'newPasswordConfirm' => 'test99',
    ],
    'Profile' => [
        'firstname' => 'test',
        'lastname' => 'user',
    ],
    'save' => '',
];

$_COOKIE = [
    'PHPSESSID' => '4aut5b1isqa0it3u9eg46r28m6',
    '_csrf' => '1e35956c652bc71b98b7912a122c22e5e74d487e844182bc5b7d058a00cdf60ba:2:{i:0;s:5:"_csrf";i:1;s:32:"MckSzst1p0PNL65fa_nm_TDWe2m_NOPo";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/index.php?r=',
];

Yii Framework

2016-12-24, 12:23:30

Apache

Yii Framework/2.0.10

Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

    1. in /home/fazebuch/public_html/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php at line 99
    90919293949596979899100101102103104105106107108

     
                // matched string
                $matchedWord = $match[0][0];
     
                // binary position of the matched word in the input stream
                $binStartPos = $match[0][1];
     
                // charact PHP Fatal Error – yii\base\ErrorException
Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

    1. in /home/fazebuch/public_html/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php at line 99
    90919293949596979899100101102103104105106107108

     
                // matched string
                $matchedWord = $match[0][0];
     
                // binary position of the matched word in the input stream
                $binStartPos = $match[0][1];
     
                // character position of the matched word in the input stream
                $startPos = $this->_position +
                            iconv_strlen(substr($this->_input,
                                                $this->_bytePosition,
                                                $binStartPos - $this->_bytePosition),
                                         'UTF-8');
                // character postion of the end of matched word in the input stream
                $endPos = $startPos + iconv_strlen($matchedWord, 'UTF-8');
     
                $this->_bytePosition = $binStartPos + strlen($matchedWord);
                $this->_position     = $endPos;
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'user/registration',
    'token' => 'te4C4h1QCMe9',
];

$_POST = [
    '_csrf' => 'Qnk3R1M3Q0YPGlwUKUQ3dzJJZwkfAXYgIyZZKgxjBxEnS1oYHXgTKQ==',
    'User' => [
        'username' => 'Test99',
    ],
    'GroupUser' => [
        'group_id' => '2',
    ],
    'Password' => [
        'newPassword' => 'test99',
        'newPassword PHP Fatal Error – yii\base\ErrorException
Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

    1. in /home/fazebuch/public_html/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php at line 99
    90919293949596979899100101102103104105106107108

     
                // matched string
                $matchedWord = $match[0][0];
     
                // binary position of the matched word in the input stream
                $binStartPos = $match[0][1];
     
                // character position of the matched word in the input stream
                $startPos = $this->_position +
                            iconv_strlen(substr($this->_input,
                                                $this->_bytePosition,
                                                $binStartPos - $this->_bytePosition),
                                         'UTF-8');
                // character postion of the end of matched word in the input stream
                $endPos = $startPos + iconv_strlen($matchedWord, 'UTF-8');
     
                $this->_bytePosition = $binStartPos + strlen($matchedWord);
                $this->_position     = $endPos;
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'user/registration',
    'token' => 'te4C4h1QCMe9',
];

$_POST = [
    '_csrf' => 'Qnk3R1M3Q0YPGlwUKUQ3dzJJZwkfAXYgIyZZKgxjBxEnS1oYHXgTKQ==',
    'User' => [
        'username' => 'Test99',
    ],
    'GroupUser' => [
        'group_id' => '2',
    ], PHP Fatal Error – yii\base\ErrorException
Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

    1. in /home/fazebuch/public_html/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php at line 99
    90919293949596979899100101102103104105106107108

     
                // matched string
                $matchedWord = $match[0][0];
     
                // binary position of the matched word in the input stream
                $binStartPos = $match[0][1];
     
                // character position of the matched word in the input stream
                $startPos = $this->_position +
                            iconv_strlen(substr($this->_input,
                                                $this->_bytePosition,
                                                $binStartPos - $this->_bytePosition),
                                         'UTF-8');
                // character postion of the end of matched word in the input stream
                $endPos = $startPos + iconv_strlen($matchedWord, 'UTF-8');
     
                $this->_bytePosition = $binStartPos + strlen($matchedWord);
                $this->_position     = $endPos;
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'user/registration',
    'token' => 'te4C4h1QCMe9',
];

$_POST = [
    '_csrf' => 'Qnk3R1M3Q0YPGlwUKUQ3dzJJZwkfAXYgIyZZKgxjBxEnS1oYHXgTKQ==',
    'User' => [
        'username' => 'Test99',
    ],
    'GroupUser' => [
        'group_id' => '2',
    ],
    'Password' => [
        'newPassword' => 'test99',
        'newPasswordConfirm' => 'test99',
    ],
    'Profile' => [
        'firstname' => 'test',
        'lastname' => 'user',
    ],
    'save' => '',
];

$_COOKIE = [
    'PHPSESSID' =>  PHP Fatal Error – yii\base\ErrorException
Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

    1. in /home/fazebuch/public_html/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php at line 99
    90919293949596979899100101102103104105106107108

     
                // matched string
                $matchedWord = $match[0][0];
     
                // binary position of the matched word in the input stream
                $binStartPos = $match[0][1];
     
                // character position of the matched word in the input stream
                $startPos = $this->_position +
                            iconv_strlen(substr($this->_input,
                                                $this->_bytePosition,
                                                $binStartPos - $this->_bytePosition),
                                         'UTF-8');
                // character postion of the end of matched word in the input stream
                $endPos = $startPos + iconv_strlen($matchedWord, 'UTF-8');
     
                $this->_bytePosition = $binStartPos + strlen($matchedWord);
                $this->_position     = $endPos;
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'user/registration',
    'token' => 'te4C4h1QCMe9',
];

$_POST = [
    '_csrf' => 'Qnk3R1M3Q0YPGlwUKUQ3dzJJZwkfAXYgIyZZKgxjBxEnS1oYHXgTKQ==',
    'User' => [
        'username' => 'Test99',
    ],
    'GroupUser' => [
        'group_id' => '2',
    ],
    'Password' => [
        'newPassword' => 'test99',
        'newPasswordConfirm' => 'test99',
    ],
    'Profile' => [
        'firstname' => 'test',
        'lastname' => 'user',
    ],
    'save' => '',
];

$_COOKIE = [ PHP Fatal Error – yii\base\ErrorException
Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

    1. in /home/fazebuch/public_html/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php at line 99
    90919293949596979899100101102103104105106107108

     
                // matched string
                $matchedWord = $match[0][0];
     
                // binary position of the matched word in the input stream
                $binStartPos = $match[0][1];
     
                // character position of the matched word in the input stream
                $startPos = $this->_position +
                            iconv_strlen(substr($this->_input,
                                                $this->_bytePosition,
                                                $binStartPos - $this->_bytePosition),
                                         'UTF-8');
                // character postion of the end of matched word in the input stream
                $endPos = $startPos + iconv_strlen($matchedWord, 'UTF-8');
     
                $this->_bytePosition = $binStartPos + strlen($matchedWord);
                $this->_position     = $endPos;
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'user/registration',
    'token' => 'te4C4h1QCMe9',
];

$_POST = [
    '_csrf' => 'Qnk3R1M3Q0YPGlwUKUQ3dzJJZwkfAXYgIyZZKgxjBxEnS1oYHXgTKQ==',
    'User' => [
        'username' => 'Test99',
    ],
    'GroupUser' => [
        'group_id' => '2',
    ],
    'Password' => [
        'newPassword' => 'test99',
        'newPasswordConfirm' => 'test99',
    ],
    'Profile' => [
        'firstname' => 'test',
        'lastname' => 'user',
    ],
    'save' => '',
];

$_COOKIE = [ PHP Fatal Error – yii\base\ErrorException
Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

    1. in /home/fazebuch/public_html/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php at line 99
    90919293949596979899100101102103104105106107108

     
                // matched string
                $matchedWord = $match[0][0];
     
                // binary position of the matched word in the input stream
                $binStartPos = $match[0][1];
     
                // character position of the matched word in the input stream
                $startPos = $this->_position +
                            iconv_strlen(substr($this->_input,
                                                $this->_bytePosition,
                                                $binStartPos - $this->_bytePosition),
                                         'UTF-8');
                // character postion of the end of matched word in the input stream
                $endPos = $startPos + iconv_strlen($matchedWord, 'UTF-8');
     
                $this->_bytePosition = $binStartPos + strlen($matchedWord);
                $this->_position     = $endPos;
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'user/registration',
    'token' => 'te4C4h1QCMe9',
];

$_POST = [
    '_csrf' => 'Qnk3R1M3Q0YPGlwUKUQ3dzJJZwkfAXYgIyZZKgxjBxEnS1oYHXgTKQ==',
    'User' => [
        'username' => 'Test99',
    ],
    'GroupUser' => [
        'group_id' => '2',
    ],
    'Password' => [
        'newPassword' => 'test99',
        'newPasswordConfirm' => 'test99',
    ],
    'Profile' => [
        'firstname' => 'test',
        'lastname' => 'user',
    ],
    'save' => '',
];

$_COOKIE = [
    'PHPSESSID' => '4aut5b1isqa0it3u9eg46r28m6',
    '_csrf' => '1e35956c652bc71b98b7912a122c22e5e74d487e844182bc5b7d058a00cdf60ba:2:{i:0;s:5:"_csrf";i:1;s:32:"MckSzst1p0PNL65fa_nm_TDWe2m_NOPo";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/index.php?r=',
];

Yii Framework

2016-12-24, 12:23:30

Apache

Yii Framework/2.0.10

    'PHPSESSID' => '4aut5b1isqa0it3u9eg46r28m6',
    '_csrf' => '1e35956c652bc71b98b7912a122c22e5e74d487e844182bc5b7d058a00cdf60ba:2:{i:0;s:5:"_csrf";i:1;s:32:"MckSzst1p0PNL65fa_nm_TDWe2m_NOPo";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/index.php?r=',
];

Yii Framework

2016-12-24, 12:23:30

Apache

Yii Framework/2.0.10

    'PHPSESSID' => '4aut5b1isqa0it3u9eg46r28m6',
    '_csrf' => '1e35956c652bc71b98b7912a122c22e5e74d487e844182bc5b7d058a00cdf60ba:2:{i:0;s:5:"_csrf";i:1;s:32:"MckSzst1p0PNL65fa_nm_TDWe2m_NOPo";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/index.php?r=',
];

Yii Framework

2016-12-24, 12:23:30

Apache

Yii Framework/2.0.10
'4aut5b1isqa0it3u9eg46r28m6',
    '_csrf' => '1e35956c652bc71b98b7912a122c22e5e74d487e844182bc5b7d058a00cdf60ba:2:{i:0;s:5:"_csrf";i:1;s:32:"MckSzst1p0PNL65fa_nm_TDWe2m_NOPo";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/index.php?r=',
];

Yii Framework

2016-12-24, 12:23:30

Apache

Yii Framework/2.0.10

    'Password' => [
        'newPassword' => 'test99',
        'newPasswordConfirm' => 'test99',
    ],
    'Profile' => [
        'firstname' => 'test',
        'lastname' => 'user',
    ],
    'save' => '',
];

$_COOKIE = [
    'PHPSESSID' => '4aut5b1isqa0it3u9eg46r28m6',
    '_csrf' => '1e35956c652bc71b98b7912a122c22e5e74d487e844182bc5b7d058a00cdf60ba:2:{i:0;s:5:"_csrf";i:1;s:32:"MckSzst1p0PNL65fa_nm_TDWe2m_NOPo";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/index.php?r=',
];

Yii Framework

2016-12-24, 12:23:30

Apache

Yii Framework/2.0.10
Confirm' => 'test99',
    ],
    'Profile' => [
        'firstname' => 'test',
        'lastname' => 'user',
    ],
    'save' => '',
];

$_COOKIE = [
    'PHPSESSID' => '4aut5b1isqa0it3u9eg46r28m6',
    '_csrf' => '1e35956c652bc71b98b7912a122c22e5e74d487e844182bc5b7d058a00cdf60ba:2:{i:0;s:5:"_csrf";i:1;s:32:"MckSzst1p0PNL65fa_nm_TDWe2m_NOPo";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/index.php?r=',
];

Yii Framework

2016-12-24, 12:23:30

Apache

Yii Framework/2.0.10
er position of the matched word in the input stream
                $startPos = $this->_position +
                            iconv_strlen(substr($this->_input,
                                                $this->_bytePosition,
                                                $binStartPos - $this->_bytePosition),
                                         'UTF-8');
                // character postion of the end of matched word in the input stream
                $endPos = $startPos + iconv_strlen($matchedWord, 'UTF-8');
     
                $this->_bytePosition = $binStartPos + strlen($matchedWord);
                $this->_position     = $endPos;
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'user/registration',
    'token' => 'te4C4h1QCMe9',
];

$_POST = [
    '_csrf' => 'Qnk3R1M3Q0YPGlwUKUQ3dzJJZwkfAXYgIyZZKgxjBxEnS1oYHXgTKQ==',
    'User' => [
        'username' => 'Test99',
    ],
    'GroupUser' => [
        'group_id' => '2',
    ],
    'Password' => [
        'newPassword' => 'test99',
        'newPasswordConfirm' => 'test99',
    ],
    'Profile' => [
        'firstname' => 'test',
        'lastname' => 'user',
    ],
    'save' => '',
];

$_COOKIE = [
    'PHPSESSID' => '4aut5b1isqa0it3u9eg46r28m6',
    '_csrf' => '1e35956c652bc71b98b7912a122c22e5e74d487e844182bc5b7d058a00cdf60ba:2:{i:0;s:5:"_csrf";i:1;s:32:"MckSzst1p0PNL65fa_nm_TDWe2m_NOPo";}',
];

$_SESSION = [ PHP Fatal Error – yii\base\ErrorException
Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

    1. in /home/fazebuch/public_html/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php at line 99
    90919293949596979899100101102103104105106107108

     
                // matched string
                $matchedWord = $match[0][0];
     
                // binary position of the matched word in the input stream
                $binStartPos = $match[0][1];
     
                // character position of the matched word in the input stream
                $startPos = $this->_position +
                            iconv_strlen(substr($this->_input,
                                                $this->_bytePosition,
                                                $binStartPos - $this->_bytePosition),
                                         'UTF-8');
                // character postion of the end of matched word in the input stream
                $endPos = $startPos + iconv_strlen($matchedWord, 'UTF-8');
     
                $this->_bytePosition = $binStartPos + strlen($matchedWord);
                $this->_position     = $endPos;
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'user/registration',
    'token' => 'te4C4h1QCMe9',
];

$_POST = [
    '_csrf' => 'Qnk3R1M3Q0YPGlwUKUQ3dzJJZwkfAXYgIyZZKgxjBxEnS1oYHXgTKQ==',
    'User' => [
        'username' => 'Test99',
    ],
    'GroupUser' => [
        'group_id' => '2',
    ],
    'Password' => [
        'newPassword' => 'test99',
        'newPasswordConfirm' => 'test99',
    ],
    'Profile' => [
        'firstname' => 'test',
        'lastname' => 'user',
    ],
    'save' => '',
];

$_COOKIE = [
    'PHPSESSID' => '4aut5b1isqa0it3u9eg46r28m6',
    '_csrf' => '1e35956c652bc71b98b7912a122c22e5e74d487e844182bc5b7d058a00cdf60ba:2:{i:0;s:5:"_csrf";i:1;s:32:"MckSzst1p0PNL65fa_nm_TDWe2m_NOPo";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/humhub/index.php?r=',
];

Yii Framework

2016-12-24, 12:23:30

Apache

Yii Framework/2.0.10

    '__flash' => [],
    '__returnUrl' => '/humhub/index.php?r=',
];

Yii Framework

2016-12-24, 12:23:30

Apache

Yii Framework/2.0.10

**Comment by buddh4** [comment]
Hmm perhaps the following ticket is helpful: https://github.com/humhub/humhub/issues/886

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/891c43cb6670fcc1ce3b3b5947bd9008cdf0d9b8
