### ISSUE TITLE
Problems with oembed

### ISSUE THREAD

**Issue by binarynos** [humhub/humhub#2173]
There are some problems with embeds:
If there is a post with embed, the post doesn't appear after reloading the page. After clearing the cache, it appears.
For some embeds like from Instagram the post shows the read more button but this is visible Firefox only, not in Chrome or Opera.
Removing the hidden class works but after clicking on the button nothing happens so you can't see the embed.

**Comment by buddh4** [comment]
which humhub version?

**Comment by binarynos** [comment]
Latest 1.1.2

**Comment by binarynos** [comment]
Another cache problem: can't logout in Chrome without clearing the cache!
