### ISSUE TITLE
New User Sign Up Failure

### ISSUE THREAD

**Issue by TezzahhH** [humhub/humhub#2175]
I have a new installation of v 1.1.2. (with some content, spaces, etc, but no code changes)
New user signup fails with the following:

$_SERVER = [ 'CONTENT_LENGTH' => '112' 'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8' 'DOCUMENT_ROOT' => '/home/simplybe/public_html/LWC' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'HTTP_ACCEPT' => '*/*' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate' 'HTTP_ACCEPT_LANGUAGE' => 'en-GB,en-US;q=0.8,en;q=0.6' 'HTTP_COOKIE' => '_csrf=76efb60f61c5340963f29fa1c1bdc80855b6850c446ab456854197e7227253d6a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22-fX0R-fn8ccqaiIq3yTD7lQEY0kgHyyR%22%3B%7D; pm_new-people-panel=expanded; pm_new-spaces-panel=expanded; pm_user-statistics-panel=expanded; PHPSESSID=7035e46b4f87a849670605363dca8273; language=87d334b4182f60c3da5a3bff47e29966deba09db93a4309b5164e8a477223764a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; _asomcnc=1' 'HTTP_HOST' => 'livingwithchange.net' 'HTTP_ORIGIN' => 'http://livingwithchange.net' 'HTTP_REFERER' => 'http://livingwithchange.net/' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36' 'HTTP_X_CSRF_TOKEN' => 'ZzBfWjQxdUlKVgdqZhwTJ19TPCtVWDw4VEkLHgNdJAw.ADQ9fEgMGw==' 'HTTP_X_FORWARDED_FOR' => '202.172.113.3' 'HTTP_X_REAL_IP' => '202.172.113.3' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => '' 'REDIRECT_STATUS' => '200' 'REDIRECT_UNIQUE_ID' => 'WGQbNoF5sMEAAE-G-DoAAAAV' 'REDIRECT_URL' => '/user/auth/login' 'REMOTE_ADDR' => '202.172.113.3' 'REMOTE_PORT' => '55775' 'REQUEST_METHOD' => 'POST' 'REQUEST_URI' => '/user/auth/login' 'SCRIPT_FILENAME' => '/home/simplybe/public_html/LWC/index.php' 'SCRIPT_NAME' => '/index.php' 'SERVER_ADDR' => '149.47.147.235' 'SERVER_ADMIN' => 'webmaster@livingwithchange.360focus.org' 'SERVER_NAME' => 'livingwithchange.net' 'SERVER_PORT' => '80' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'UNIQUE_ID' => 'WGQbNoF5sMEAAE-G-DoAAAAV' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1482955574.94 'REQUEST_TIME' => 1482955574 'argv' => [] 'argc' => 0 ]

I really like the ease of HumHub but user registration is sorta important.  
I can patch code but not really fluent enough to write it.
Help??

Thanks

**Comment by TezzahhH** [comment]
did a test and it is the SIGNUP feature that is not working.  I have tried backing up a the old SQL to a fresh install, so it is 99.9% in the files, somewhere.

**Comment by buddh4** [comment]
The mentioned log is not the actual error it's just a request log, there should be an error stack underneath this information.

**Comment by TezzahhH** [comment]
And 

ERROR  Wed, 11 Jan 2017 08:43:56 +1100 Swift_TransportException
exception 'Swift_TransportException' with message 'Failed to authenticate on SMTP server with username "admin" using 2 possible authenticators' in /home/simplybe/public_html/LWC/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:181 Stack trace: #0 /home/simplybe/public_html/LWC/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(334): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport)) #1 /home/simplybe/public_html/LWC/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand() #2 /home/simplybe/public_html/LWC/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start() #3 /home/simplybe/public_html/LWC/protected/vendor/yiisoft/yii2-swiftmailer/Mailer.php(146): Swift_Mailer->send(Object(Swift_Message)) #4 /home/simplybe/public_html/LWC/protected/vendor/yiisoft/yii2/mail/BaseMailer.php(260): yii\swiftmailer\Mailer->sendMessage(Object(yii\swiftmailer\Message)) #5 /home/simplybe/public_html/LWC/protected/vendor/yiisoft/yii2/mail/BaseMessage.php(48): yii\mail\BaseMailer->send(Object(yii\swiftmailer\Message)) #6 /home/simplybe/public_html/LWC/protected/humhub/modules/user/models/Invite.php(128): yii\mail\BaseMessage->send() #7 /home/simplybe/public_html/LWC/protected/humhub/modules/user/models/Invite.php(100): humhub\modules\user\models\Invite->sendInviteMail() #8 /home/simplybe/public_html/LWC/protected/humhub/modules/user/controllers/AuthController.php(84): humhub\modules\user\models\Invite->selfInvite() #9 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin() #10 /home/simplybe/public_html/LWC/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #11 /home/simplybe/public_html/LWC/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #12 /home/simplybe/public_html/LWC/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('login', Array) #13 /home/simplybe/public_html/LWC/protected/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('user/auth/login', Array) #14 /home/simplybe/public_html/LWC/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #15 /home/simplybe/public_html/LWC/index.php(25): yii\base\Application->run() #16 {main}

**Comment by TezzahhH** [comment]
Appears that using the default SMTP setting prevented the popup.  Switched to PHP and at least now the popup is happening and email is sent.

**Comment by buddh4** [comment]
Yes, sorry for the late answer seems to be a mailing issue. Probably invalid email server settings.
