### ISSUE TITLE
Renaming Spaces (to Communities)

### ISSUE THREAD

**Issue by TezzahhH** [humhub/humhub#2176]
I have a 1.1.2 install and am trying to rename Spaces to Communities.
I have looked in the DB, the /protected/humhub/modules folder and in the theme but cant see where to do that for all menus (i don't care that the code actually needs that to work.

Ideas?  Thanks

**Comment by Felli** [comment]
You could always just change the name within the language files, this is a quick work around without damaging your site too badly.

**Comment by TezzahhH** [comment]
I have found language folders for messages but not the My Spaces menu item in Dashboard or Spaces in the directory menu.

Help?
Thanks, Sarah!

**Comment by Felli** [comment]
@TezzahhH You should be able to find it within widgets_views_spaceChooser.php line 5 of almost every language, if you don't see it in your language then add ``` 'My spaces' => 'My Communities',``` .

**Comment by TezzahhH** [comment]
Forgive my unfamiliarity but I start in the root of the install, go to the protected folder, then humbug then follow your instructions? When I then go into widgets, then views, there is not spacechoosr.php file.

I have tried a search in the entire tree, but only see spacechooser.js (which is the underlying engine, I believe.)  

Sorry to be a pain, but if I understood why things were where they were (or at least the entire file path) I could probably follow better.  

As for language,, I see no ‘en’ folder in root/protected/humhub/messages, I assume that is because the en  language in in the base code?

**Comment by Felli** [comment]
That is because English is a default for all community, if you wish you can always add your own en folder.

**Comment by TezzahhH** [comment]
As you said earlier, the simplest and lest risky thing is just to edit where My Spaces is currently at.

**Comment by barrelmonkey** [comment]
Were you ever able to find a solution to this? I am in the same situation, I would like to change the reference to 'Spaces' to something else, but I can't find out how.
I've created a new /protected/humhub/messages/en folder, and in there I have an archive.json, base.php, errors.php and a widgets_views_markdownEditor.php.

**Comment by githubjeka** [comment]
http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#2-configure-one-or-multiple-message-sources
