### ISSUE TITLE
Link in FAQ

### ISSUE THREAD

**Issue by ShalokShalom** [humhub/humhub#2177]
4) Which is the best way to adapt HumHub to my needs?

https://community.humhub.com/p/1

Click on the "modules" link

I get: 

![screenshot_20161229_091729](https://cloud.githubusercontent.com/assets/6344099/21539522/ed3acc9e-cda7-11e6-8436-fbd96612c9eb.png)

**Comment by Felli** [comment]
Should be changed to https://www.humhub.org/en/marketplace

**Comment by buddh4** [comment]
The documentation will be reworked with version 1.2 the current documentation is available under: https://www.humhub.org/docs/
