### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by binarynos** [humhub/humhub#2178]
There are some caching issues with Humhub:
Using latest version 1.1.2, PHP 5.6 and file caching

- Cannot logout, after clicking on logout, I see the same page which i see when logged in, however when i post something i get a 403 error. Clearing the browser cache takes me back to the login page.
Any suggestions?
Thanks

**Comment by buddh4** [comment]
Never experienced such an issue, could you check your logs for any errors?

**Comment by binarynos** [comment]
Log has info entries and errors:
All errors are : `Could not connect to HumHub API! Error in cURL request: Operation timed out after 30000 milliseconds with 0 out of 0 bytes received`
Should i share the info entries too?

**Comment by Felli** [comment]
Sometimes server security blocks Humhub ip for updates & download/install this could be one of the issues you're having.

**Comment by binarynos** [comment]
Okay it was just a test install so I deleted it and reinstalled version 1.1.2 and this issue remained there without any log entries at all. Then, I installed version 1.1.1 and everything works just fine. This issue disappears. So I think this issue is present only in version 1.1.2
Any suggestions?
Thanks a lot

**Comment by buddh4** [comment]
The full error stack would be interesting, as Felli said, this normally only happens when updating/installing modules if no connection can be established to humhub.

**Comment by binarynos** [comment]
This appears to be a problem with my test environment and not with Humhub because everything is working fine now.  This can be closed now.
Thanks for your help
