### ISSUE TITLE
Mail Module Bug

### ISSUE THREAD

**Issue by gigabytedevelopers** [humhub/humhub#2181]
Least I forget, there is this bug on humhub in the mail module (a very huge bug). If User A and User B is chatting, and User A decides to exit the conversation, the conversation clears on both User A and User B's accounts instead of only on User A's account (the person who exitted the conversation).

**Comment by Felli** [comment]
I'd suggest moving this over on [humhub-modules-mail](https://github.com/humhub/humhub-modules-mail) :+1:
