### ISSUE TITLE
Create new user via API

### ISSUE THREAD

**Issue by hilltopmediadesign** [humhub/humhub#2187]
Is there any documentation on creating a new user and setting permissions via an API call? I've seen a few mentions but no clear method of implementation.

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-rest

**Comment by stephenhodgkiss** [comment]
Does the function call still send the welcome emails out to the new user? It doesn't seem to be doing that for me.

If not is there a way to customize the code so it does?

**Comment by marc-farre** [comment]
No. It would require adding this feature in the module.

**Comment by stephenhodgkiss** [comment]
> No. It would require adding this feature in the module.

Thanks. Any ideas to point me in the right direction to customize a particular script for that?

**Comment by marc-farre** [comment]
@stephenhodgkiss Sorry, I forgot there is an endpoint to invite users: https://marketplace.humhub.com/module/rest/docs/html/user.html#tag/Invite

Is that what you was looking for?

**Comment by stephenhodgkiss** [comment]
> @stephenhodgkiss Sorry, I forgot there is an endpoint to invite users: https://marketplace.humhub.com/module/rest/docs/html/user.html#tag/Invite
> 
> Is that what you was looking for?

Thanks for your reply.
I have already called the API to create a new account. However, the welcome emails are not being sent out as what would happen if they were created from the front-end.

**Comment by marc-farre** [comment]
What do you mean with the welcome email exactly? Do you mean the email sent to confirm the email address?

**Comment by stephenhodgkiss** [comment]
> What do you mean with the welcome email exactly? Do you mean the email sent to confirm the email address?

Well possibly yes. Just an initial email they get after signing up for the first time.

**Comment by marc-farre** [comment]
This email is not really a welcome text. It's part of the process to create the account. While the email address is not confirmed (after clicking on the button in the email), the account is not fully created.

So if your need is to send a welcome email after account creation, you should create a small custom module with an event:
https://docs.humhub.org/docs/develop/modules-event-handler/#registration-events -> "Registration::EVENT_AFTER_REGISTRATION"

See also: https://docs.humhub.org/docs/develop/events/#register-event-listener

Then, you can either send a notification (which will also send an email): https://docs.humhub.org/docs/develop/notifications/
Or only an email:

```php
/**
/* @var $user humhub\modules\user\models\User
/* @var $message string
*/

Yii::$app->i18n->setUserLocale($user);

$toEmail = $user->email;
$subject = Yii::t('MyModule.base', 'Subject');
$message = 'The HTML message';
try {
	$mail = Yii::$app->mailer->compose(
		['html' => '@humhub/views/mail/TextOnly'],
		['message' => $message]
	);
	$mail->setTo($toEmail);
	$mail->setSubject($subject);
	$mail->send();
} catch (Exception $ex) {
	Yii::error('Could not send mail to: ' . $toEmail . ' - Error:  ' . $ex->getMessage());
}

Yii::$app->i18n->autosetLocale();
```

**Comment by ArchBlood** [comment]
> This email is not really a welcome text. It's part of the process to create the account. While the email address is not confirmed (after clicking on the button in the email), the account is not fully created.
> 
> So if your need is to send a welcome email after account creation, you should create a small custom module with an event: https://docs.humhub.org/docs/develop/modules-event-handler/#registration-events -> "Registration::EVENT_AFTER_REGISTRATION"
> 
> See also: https://docs.humhub.org/docs/develop/events/#register-event-listener
> 
> Then, you can either send a notification (which will also send an email): https://docs.humhub.org/docs/develop/notifications/ Or only an email:
> 
> ```
> /**
> /* @var $user humhub\modules\user\models\User
> /* @var $message string
> */
> 
> Yii::$app->i18n->setUserLocale($user);
> 
> $toEmail = $user->email;
> $subject = Yii::t('MyModule.base', 'Subject');
> $message = 'The HTML message';
> try {
> 	$mail = Yii::$app->mailer->compose(
> 		['html' => '@humhub/views/mail/TextOnly'],
> 		['message' => $message]
> 	);
> 	$mail->setTo($toEmail);
> 	$mail->setSubject($subject);
> 	$mail->send();
> } catch (Exception $ex) {
> 	Yii::error('Could not send mail to: ' . $toEmail . ' - Error:  ' . $ex->getMessage());
> }
> 
> Yii::$app->i18n->autosetLocale();
> ```

I'd also like to note that an email to finish the account creation is sent after `save()` is done;
https://github.com/humhub/rest/blob/master/controllers/user/InviteController.php#L56
After this as @marc-farre stated a custom module should be created to send any welcome emails after the process is completed, if you mean you're not getting this email then it's probably a configuration issue.
