### ISSUE TITLE
Notification not received when someone post in a space where i am

### ISSUE THREAD

**Issue by Astroop** [humhub/humhub#2188]
Notifications work when someone comments on my posts but not when someone posts on a space where I am a member and subscriber :(
Any ideas ? And if its not supported is it possible to send a mail to all members when someone create a post ?
Thanks in advance !

**Comment by buddh4** [comment]
This will be supported in v1.2. You'll be able to define from which spaces you want to receive ContentCreated notifications and to which target (Mail/Web).

**Comment by Astroop** [comment]
Thanks for your answer !
