### ISSUE TITLE
Set sql_mode on database so we users don't recieve this error. 

### ISSUE THREAD

**Issue by jeremiahtenbrink** [humhub/humhub#2191]
Hello, first I wanted to say thank you to everyone who has been working on this project. I'm currently getting it setup on a home ubuntu server running lamp. I got this error and just wanted to fw it on to all of you in hopes that there is a way for you it to be fixed. The sql_mode= (?) instead of sql_mode=only_full_group_by... This was the first log in attempt after installing the database. 

![capture](https://cloud.githubusercontent.com/assets/17443353/21748276/34c328ac-d53e-11e6-8c87-3a42396ffcd3.GIF)

**Comment by jeremiahtenbrink** [comment]
![capture](https://cloud.githubusercontent.com/assets/17443353/21748527/5cdb5138-d544-11e6-84d9-3d41413e506f.GIF)

I added this line to the bottom of /etc/mysql/my.cnf to fix the problem for now.

**Comment by buddh4** [comment]
This is a known problem: https://github.com/humhub/humhub/issues/1777
