### ISSUE TITLE
Why is the outdated APC in use?

### ISSUE THREAD

**Issue by ShalokShalom** [humhub/humhub#2192]
Humhub recommend me on the installation, to add APC, which is without any stable release since more than 5 years:

http://funkyimg.com/i/2nbtL.png

http://pecl.php.net/package/apc

Why that?

**Comment by ShalokShalom** [comment]
Does APCu work?

http://php.net/manual/de/book.apcu.php

**Comment by buddh4** [comment]
Please check the following issues:

https://github.com/humhub/humhub/issues/659

https://github.com/humhub/humhub/issues/2005
