### ISSUE TITLE
Password recovery calling exception

### ISSUE THREAD

**Issue by TomMcHugh** [humhub/humhub#2193]
Whenever I go to password recovery and correctly type in the email and captcha code to reset I get an exception about a contentcontainer ID being 0. Running PHP 5.6, Latest version of HumHub.

<img width="1242" alt="screen shot 2017-01-09 at 10 35 48 am" src="https://cloud.githubusercontent.com/assets/1643741/21774320/b5a8e6cc-d657-11e6-887e-792120742fa7.png">

**Comment by buddh4** [comment]
Could you add the whole error stack under Administration -> Information -> Logging
