### ISSUE TITLE
Theme issues

### ISSUE THREAD

**Issue by petrk94** [humhub/humhub#2194]
Hello,
I have a problem with the theming.
I have tried fews and got a PHP error
```

views/layouts/main.php at line 7
12345678910111213141516<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- start: Meta -->
    <meta charset="utf-8">
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <!-- end: Meta -->
 
    <!-- start: Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- end: Mobile Specific -->
 
    <?php $ver = HVersion::VERSION; ?>
 
    <!-- start: CSS -->
2. yii\base\ErrorHandler::handleFatalError()
```

Now I have deleted the broken theme and tried a other one what is broken to, but the system is running. I have deleted it and activated the main theme again, but now I dont get the main theme design back. What I need to do to get it back? I even have deleted the main theme and made it again.
Please help. Thanks

**Comment by Becold** [comment]
Did you try to disable the cache ?

**Comment by petrk94** [comment]
Hi @Becold ,
I have disabled the cache in the HumHub Administration settings, but it didn't worked.
I could restore a snapshot of the system 1 day before, so now its running, but I would like to understand why it happened and how to prevent this again.
Why are not more themes available? I have tested themes but all seems to be 2 years old and is not working.

**Comment by Becold** [comment]
Seems like you want to [uodate/migrate an old theme](https://www.humhub.org/docs/guide-theming-migrate.html). Old themes aren't compatible with newer versions of Humhub.
(PS: I'm just a user of Humhub)

**Comment by Felli** [comment]
I'd suggest copying this part [here](https://github.com/humhub/humhub/blob/master/protected/humhub/views/layouts/main.php) then editing it how you wish and uploading it to your /theme/views/layouts :+1:

**Comment by petrk94** [comment]
Thanks for your help.
For the moment I will use the standard theme, maybe I will look in future again to this issue ;)
