### ISSUE TITLE
Is it possible to customize a core module functionality in a theme or a module ?

### ISSUE THREAD

**Issue by badis** [humhub/humhub#2201]
Hello,

I want to disable receiving activity emails and notifications when a user joined or left a space.
the code for this is : 

```
        $activity = new \humhub\modules\space\activities\MemberAdded;
        $activity->source = $this->owner;
        $activity->originator = $user;
        $activity->create();

```
inside SpaceModelMembership.php.
this file is located in the core module Space of humhub.
Is there a way to change this behavior inside a theme or a module.

I am using HumHub 1.1.1

Thank you for your time and consideration.

**Comment by Felli** [comment]
I would think it would be possible, but I've never actually tried.

**Comment by buddh4** [comment]
We are currently rewriting the notification/activity feature, so you will be able to decide which information you want to receive for which target (Web/Mail). This will be avialable in v1.2

**Comment by badis** [comment]
Sounds great !  thank you @buddh4
