### ISSUE TITLE
Emails Language Bug

### ISSUE THREAD

**Issue by eddiepiazza** [humhub/humhub#2202]
Today I discovered a funny and BAD bug related with emails and notifications.

While a using is using one language, for example french, and sending a message to an other user that has another language, the second user is receiving in his mailbox the humhub notification in sender´s language.

So... yes, no sense. Why humhub is not sending this message in receiver's language???

**Comment by buddh4** [comment]
I've opened a issue within the mail module repository: https://github.com/humhub/humhub-modules-mail/issues/113
