### ISSUE TITLE
HTML Editor custom pages in space

### ISSUE THREAD

**Issue by petrk94** [humhub/humhub#2203]
Hallo,
does anyone know why the custom pages in the humhub spaces doesnt allow HTML editor?
Cant really understand why this is not working :/
any idea?

Thanks

**Comment by buddh4** [comment]
You just have to allow the the template template container for spaces. This was done since a html editor can be prone for attacks. But I think there should not be a problem.

**Comment by petrk94** [comment]
@buddh4 so you mean that I need to create a template on the administration site and so I can use it to give it to the space? I think this is not really good solved

**Comment by buddh4** [comment]
I thought you meant template based pages. The problem with html pages in communities is, that you can inject any code etc... which is rather dangerous in public communities where users can create own spaces. Perhaps we could add an admin setting to allow html pages in spaces for networks where this is not a problem.

**Comment by petrk94** [comment]
@buddh4 yes this were great, I administrate a humhub network and want to see whats working now.
The Option to make HTML based pages in the spaces only for administrator of the network is a good option.

**Comment by buddh4** [comment]
I've added this feature request to the modules repository: https://github.com/humhub/humhub-modules-custom-pages/issues/52 

After the release of the upcoming version we'll improve some of the existing modules.
