### ISSUE TITLE
HumHub chat module not longer in development

### ISSUE THREAD

**Issue by petrk94** [humhub/humhub#2204]
Hey guys,

wanted tell you, that the HumHub chat module repository,
is not longer in development, dont know whether it got communicated here already.

https://github.com/ychoucha/HUMHUB-module-chat/issues/2#event-920398435

**Comment by WebCrew** [comment]
@petrk94 that issue has **nothing to do with the HumHub core developer team**. It is a project from a HumHub **user**, so please ask him about that problem. 

Thanks for your understanding and have a nice day :+1:

**Comment by petrk94** [comment]
@WebCrew its more the information, maybe you can make a list of not longer developed plugins?
This would help to avoid issues. I even have tried it and saw that its not working.. And he said that its not longer working

**Comment by WebCrew** [comment]
I understand you mate, but it would be a huge work to find out which HumHub module projects are active or outdated. **All the default HumHub Modules which you can find at HumHubs marketplace get always updated**, but here at GitHub are minimum around 100 projects and most of them are done by **normal HumHub users** like you and me. It is _the task of the module creators to inform peoples_ about if the module works or not, or get updated or not, or with which version of HumHub it is working. So thats not a task of or for the HumHub developer team. The HumHub core team are **only around 2-4 active developers** and they have enough work to do.

The only thing you can do is to read the README files of the modules or to ask the developers of the module if you can use it or if it is working and get updated. 

Kind regards, Andy

**Comment by petrk94** [comment]
@WebCrew  yeah I see, thats why I wanted notify the main developer here, thats why I have asked the develper and wanted to reduce the work to collect the information :) 
https://github.com/ychoucha/HUMHUB-module-chat/issues/2#event-920398435

**Comment by WebCrew** [comment]
@petrk94 thanks for your understanding and for trying to help. If you want you can check out that page and help to keep it updated: https://community.humhub.com/s/module-development/wiki/page/view?title=3rd-Party+Modules
