### ISSUE TITLE
Task issues "assigned"

### ISSUE THREAD

**Issue by petrk94** [humhub/humhub#2205]
Hello,
a collegaue has added some tasks to humhub and assigned it to few people.
Now Im getting this error:

`

1. in /var/www/virtual/petrk/humhub.kirpeit-solutions.de/protected/modules/tasks/notifications/views/assigned.php at line 6
1234567891011121314<?php
 
use yii\helpers\Html;
 
echo Yii::t('TasksModule.views_notifications_taskAssigned', '{userName} assigned you to the task {task}.', array(
    '{userName}' => '<strong>' . Html::encode($originator->displayName) . '</strong>',
    '{task}' => '"'.Html::encode($source->getContentDescription()).'"'
));
?>

There are some other issues in the error message too, may someone can check it, what happened?
`

**Comment by petrk94** [comment]
ok, I dont know what thats for shit of bug, but even running the backup back doesn't solve the issue.
Is humhub really usable for productive use or not?
Which version can be used to run safe without issues?

**Comment by Felli** [comment]
v1.1.2 should be stable enough to be used.

**Comment by petrk94** [comment]
@Felli the problem is, that I have this version already and I get this bug

**Comment by buddh4** [comment]
Can you provide us the full error stack?
