### ISSUE TITLE
file module deactivation / all data gone?

### ISSUE THREAD

**Issue by desertrockxxx** [humhub/humhub#2207]
hi, i just deactivated the file module and i'm afraid that all my actual data is deleted.

is there a possibility to revive the data or do a system recovery?  

greetings DesertRock

**Comment by Felli** [comment]
From what I remember yes all data is removed, also you should create this post over on [cfile](https://github.com/humhub/humhub-modules-cfiles/issues). :smile:

**Comment by desertrockxxx** [comment]
ok thank you, how i can remove this post to cfile?


PS: im also crying.

**Comment by 001101** [comment]
That is unfortunately a common problem in HumHub which should really be fixed soon, also when a user deletes himself all his data will wiped out, which is not a nice way to have a reliable communication platform in business, it breaks conversations and interactions.

**Comment by luke-** [comment]
@001101 there is a user soft delete in the meantime.
