### ISSUE TITLE
language

### ISSUE THREAD

**Issue by gadgondhali** [humhub/humhub#2212]
I want to add indic language i.e. Marathi in this software so please guide me to do this

**Comment by Becold** [comment]
Officially, you need to go on http://translate.humhub.org/

If you need to overwrite already existants translations, have a look at "Overwrite default texts" in the doc : https://www.humhub.org/docs/guide-admin-adv-config.html#language

If your langage doesnt exist or if there are missings translations, you can do it yourself (as I did in #2190). The langage files are located in those directories (don't forget to save as UTF-8 on each files) : 
- protected/humhub/messages/
- modules/*/messages/

Then, in the file `protected/config/dynamic.php`, change the "langage" to yours.

**Comment by Felli** [comment]
You have to wait till the devs add a mar folder with all the needed files for translation, or help by creating the needed files in a a mar folder if it isn't already added. :+1: .

**Comment by gadgondhali** [comment]
Can I edit it manually by adding folder name as mar or mr
if can i do this then please guide how to do it
till the whole application converted to marathi language as default language.
please guide me as early as possible because i have to do it in 3 days

**Comment by githubjeka** [comment]
If you need add new language to Humhub core:

1. Create fork
2. Add ISO-639 standard code of your language [like this commit](https://github.com/humhub/humhub/commit/003d02165f08b06c0c95a5886e6233512627f781)
3. Run command `php yii message/extract-module MODULE_NAME` to automatical create new folder with file-messages for one module(MODULE_NAME)
4. Translate this messages in new files.
5. PUSH your fork to Humhub repo
