### ISSUE TITLE
 PHP Fatal Error – yii\base\ErrorException 

### ISSUE THREAD

**Issue by mostafa-hosseinmardi** [humhub/humhub#2215]
hi

there is error when i try to install the humhub
please help

thank you

---------------------------

    1. in /home2/............................/protected/vendor/yiisoft/yii2/db/Connection.php at line 614
    605606607608609610611612613614615616617618619620621622623

        /**
         * Initializes the DB connection.
         * This method is invoked right after the DB connection is established.
         * The default implementation turns on `PDO::ATTR_EMULATE_PREPARES`
         * if [[emulatePrepare]] is true, and sets the database [[charset]] if it is not empty.
         * It then triggers an [[EVENT_AFTER_OPEN]] event.
         */
        protected function initConnection()
        {
            $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            if ($this->emulatePrepare !== null && constant('PDO::ATTR_EMULATE_PREPARES')) {
                $this->pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, $this->emulatePrepare);
            }
            if ($this->charset !== null && in_array($this->getDriverName(), ['pgsql', 'mysql', 'mysqli', 'cubrid'], true)) {
                $this->pdo->exec('SET NAMES ' . $this->pdo->quote($this->charset));
            }
            $this->trigger(self::EVENT_AFTER_OPEN);
        }
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'installer/index/go',
];

$_COOKIE = [
    'wp-settings-2' => 'wplink=1&libraryContent=browse&align=center&urlbutton=post&editor=tinymce&ed_size=465&hidetb=1&advImgDetails=show&imgsize=full&posts_list_mode=list',
    'wp-settings-time-2' => '1484483484',
    'wp-settings-1' => 'advImgDetails=show&hidetb=1&editor=tinymce&posts_list_mode=list&libraryContent=browse&align=center&urlbutton=post&imgsize=full&mfold=o',
    'wp-settings-time-1' => '1484908715',
    '_csrf' => '918fe0d156d97ae1a2c519b1ac49dbcf92a9bb4c3fddb3c84c8cd065bb300bb2a:2:{i:0;s:5:"_csrf";i:1;s:32:"5Y6gA2k7S7MvwLth-kpnopFPSy1E3CCQ";}',
    'language' => '983415dbe7fa884fbae9563f44806e157e266d02d7659a0cd1430448d9ebf811a:2:{i:0;s:8:"language";i:1;s:5:"fa_ir";}',
];

**Comment by buddh4** [comment]
The actual error message is missing, perhaps you forgot to enable the, get sure you have installed all required php extension mentioned here: https://www.humhub.org/docs/guide-admin-requirements.html (especially the mysql extension)

**Comment by mostafa-hosseinmardi** [comment]
hi

all required php extension is activate, but i have error yet
i need help please

thank you

`

    1. in /home2/...................../protected/vendor/yiisoft/yii2/db/Connection.php at line 614
    605606607608609610611612613614615616617618619620621622623

        /**
         * Initializes the DB connection.
         * This method is invoked right after the DB connection is established.
         * The default implementation turns on `PDO::ATTR_EMULATE_PREPARES`
         * if [[emulatePrepare]] is true, and sets the database [[charset]] if it is not empty.
         * It then triggers an [[EVENT_AFTER_OPEN]] event.
         */
        protected function initConnection()
        {
            $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            if ($this->emulatePrepare !== null && constant('PDO::ATTR_EMULATE_PREPARES')) {
                $this->pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, $this->emulatePrepare);
            }
            if ($this->charset !== null && in_array($this->getDriverName(), ['pgsql', 'mysql', 'mysqli', 'cubrid'], true)) {
                $this->pdo->exec('SET NAMES ' . $this->pdo->quote($this->charset));
            }
            $this->trigger(self::EVENT_AFTER_OPEN);
        }
     

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'r' => 'installer/index/go',
];

$_COOKIE = [
    'wp-settings-2' => 'wplink=1&libraryContent=browse&align=center&urlbutton=post&editor=tinymce&ed_size=465&hidetb=1&advImgDetails=show&imgsize=full&posts_list_mode=list',
    'wp-settings-time-2' => '1484483484',
    'wp-settings-1' => 'advImgDetails=show&hidetb=1&editor=tinymce&posts_list_mode=list&libraryContent=browse&align=center&urlbutton=post&imgsize=full&mfold=o',
    'wp-settings-time-1' => '1484908715',
    'language' => '983415dbe7fa884fbae9563f44806e157e266d02d7659a0cd1430448d9ebf811a:2:{i:0;s:8:"language";i:1;s:5:"fa_ir";}',
    '_csrf' => '4683e3f5b7da9ee63cdfbed835616ea6ed0dc1151c964526cc0f10ae430cce04a:2:{i:0;s:5:"_csrf";i:1;s:32:"n6e-F70iaWCy_XMwcJx136hXNppYJwyV";}',
    'wordpress_test_cookie' => 'WP Cookie check',
    'PHPSESSID' => 'i93eit2qn4f9j54ccddk0scfg5',
    'wordpress_logged_in_f8c6cf48b62293bde39bd855f711585a' => 'MH-67@Del|1485341095|5ziUmpuILHb7cz2mqDfesSJaRVCOMmaXwFArzI88QIU|b27eecabd4e363ff875b8184f2de349cdd49c5e7c6b48486b70d7d92312e8761',
    'wfwaf-authcookie-c69f1f04079aa69bc6c307eb8edeb953' => '1|administrator|734853c0d936d44de64f25f65e9c9238b1a64573d25627872e10b41493bbdf03',
];

Yii Framework

2017-01-23, 14:18:26

Apache

Yii Framework/2.0.10
Fatal error: Call to a member function setAttribute() on null in /home2/........../protected/vendor/yiisoft/yii2/db/Connection.php on line 614 `

**Comment by buddh4** [comment]
As, I said you probably did not enable your pdo_mysql extension in your php.ini, have you checked this, and also check the other extension https://www.humhub.org/docs/guide-admin-requirements.html ?

**Comment by mostafa-hosseinmardi** [comment]
hi
all general requirements extension are enable except Shell access (because the server not allow to enable it)
but there is error
thank you

**Comment by WebCrew** [comment]
So maybe here you have your issue - you dont have shell access and HumHub **needs** it.

**Comment by 001101** [comment]
I think those basic install issues should just be deleted, they are consuming useless time and effort.

Github is no Webspace Support Hotline
