### ISSUE TITLE
User or Password incorrect for newly created hub

### ISSUE THREAD

**Issue by obojdi** [humhub/humhub#2216]
Just created a new HumHub instance, trying to login with admin username/email and password results in error. I try then to reset password, and after submitting I get this:

>Oooops... It looks like you may have taken the wrong turn.
>An internal server error occurred.

And that's it. No verification/password reset emails in inbox.

**Comment by buddh4** [comment]
Can you check, your server logs regarding the reset password issue?

**Comment by obojdi** [comment]
@buddh4 nope, any link at `/user/password-recovery` redirects to login screen

**Comment by buddh4** [comment]
An internal server error occurred. I mean your server error log, something should be logged (An internal server error occurred.)
