### ISSUE TITLE
Logging config doesn't work

### ISSUE THREAD

**Issue by valentin-vogel** [humhub/humhub#2217]
Hello,

the logging page of humhub "/admin/logging" contains all error types. How can i only show errors and warnings?

I try it with this config:
`return [
    'components' => [
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\DbTarget',
                    'levels' => ['error', 'warning'],
                ]
            ],
        ],
    ],
    'bootstrap' => ['log'],
];`

Does anyone have an idea why it does not work?

**Comment by buddh4** [comment]
Are you sure, it should only show errors and the related request log of the error?

**Comment by valentin-vogel** [comment]
For example (a wrong url): creates an error and info message. Why?

**Comment by valentin-vogel** [comment]
Maybe i found the problem. I think some errors are displayed with the label 'info'.

**Comment by buddh4** [comment]
This is the related request log I mentioned. Each error is logged with additional request information, this can be helpful to analyze some errors.
