### ISSUE TITLE
E-Mail Notification get layout break through Google Maps Link

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#2219]
Hello,

have noticed that a enormous long Google Maps Link breaks the layout for the Mail Notification (daily/weekly overview mail).

Only thing which I found out in short that the link does not get quoted, maybe something rings?

Viewed on Yandex Webmailer

Looks than like this:

![2017-01-24_182305](https://cloud.githubusercontent.com/assets/8197408/22258892/892a6658-e263-11e6-9dd0-2aa45a42bca2.jpg)

greets

**Comment by buddh4** [comment]
We'll have a look thx.
