### ISSUE TITLE
Absolute file URLs in showFiles.php are wrong behind a firewall

### ISSUE THREAD

**Issue by Lercher** [humhub/humhub#2220]
Hi

When placing a humhub installation behind a reverse proxy, links to images on a space point to absolute URLs using the hostname of the humhub installation. This is problematic, when the humhub installation is behind a firewall that doesn't allow access to the humhub host. E.g. say you have the humhub installation at say http://humhub.internal.somedomain.example/humhub and you publish it to the world as  https://www.somedomain.example/humhub via a reverse proxy, the image urls on some space https://www.somedomain.example/humhub/s/some-space are generated as e.g. http://humhub.internal.somedomain.example/humhub/file/file/download?guid=b5b79913-7195-4e5c-9e73-c35d7e7529f5#.jpeg which is not accessible from the outside.

There is a general configuration entry that is called Base URL, but it doesn't seem to have an effect here. So it would be nice if these URLs could be generated in a relative way or else with the Base URL taken into account. Thanks, Martin.

I'm not familiar with php, so this might be the problematic location or not. See:
https://github.com/humhub/humhub/blob/4912d9196b5c8f47b808972c6b7989a1f8e677fa/protected/humhub/modules/file/widgets/views/showFiles.php#L22
and 
https://github.com/humhub/humhub/blob/4912d9196b5c8f47b808972c6b7989a1f8e677fa/protected/humhub/modules/file/models/File.php#L192

**Comment by randomboygh** [comment]
I have the same issue.
And after login it redirect from _somedomain.example_ to _humhub.internal.somedomain.example_ sometimes.

**Comment by marcus67** [comment]
I encountered the same problem. Somehow, the URL resolution for `File.php` is not retrieved from the general setting in the `settings/core` section of the file `dynamic.php`. However, by browsing through the documentation of the class `UrlManager` I found that this class has a config section of its own:

    'components' => 
        array (
            'urlManager' => 
                array (
                     'hostInfo' => 'https://my.external.url',
                     'baseUrl' => '/my/external/basepath',
                 ),
            ...
        ),

This worked for me.

**Comment by randomboygh** [comment]
What do I do if I have more than one domain name at one host?

**Comment by marcus67** [comment]
The setting above seems to be application specific since the script `dynamic.php` is sourced by the application. Unless the same application has to react to different domain names, it should be fine.

**Comment by buddh4** [comment]
You should not edit the dynamic.php file, you can overwrite the configuration within the protected/config/common.php (http://docs.humhub.org/admin-advanced-configuration.html)

**Comment by madmas** [comment]
Hi, 
that hint with the urlManager config actually helped me as well, thank a lot!

I've configured humhub to run within a docker and serve it to the outside via apache using a reverse proxy taht handles SSL.
Everything was woking fin execpt the fact that image URLs were written using http:// instead of https:// . Setting `urlManager` `hostInfo` helped, but I think it should at least be better documented, if not made obbsolete, e.g. by only generating relative URLs instead of complete ones including the protocol.
