### ISSUE TITLE
Question: Possible to add a 3rd Party Modules link at navigation?

### ISSUE THREAD

**Issue by WebCrew** [humhub/humhub#2224]
Hi,

this is not a bug but a question for community enhancement.
A lot of people are missing the "WIKI-pages" at the Module Development Space. So my question is:

Would it be possible, you guys create a link at the community main navigation with the title "3rd Party" and with the following link:

https://community.humhub.com/s/module-development/wiki/page/list

Kind regards and thanks for your great job mates!
I hope you guys are fine, we miss Julian and Lucas at the community :)

**Comment by 001101** [comment]
It could be made possible with Custom Pages, but where will this lead the community and who will have the rights to create those buttons?

**Comment by WebCrew** [comment]
**En:** I think it will help the community users to find the WIKI entries about 3rd party modules etc a lot easier. Most of users have no idea that the WIKI page with all these extra cool 3rd party things exist. Thats why I asked the HumHub developers if it is possible to add a link at the main navigation (yes with custom pages).

De: Es wäre genial wenn ein Link in der HumHub Community Hauptnavigation zum WIKI Eintrag mit all den Drittanbieter Infos und Modulen existieren würde. Viele HumHub Nutzer haben keine Ahnung, dass diese informativen Einträge dort vorhanden sind oder übersehen das WIKI. Mit Hilfe des Custom Pages Moduls ist das eine Angelegenheit von 3 Minuten, eigentlich gar nicht Wert darüber gross zu diskutieren :)

Kind regards, Andy

**Comment by Felli** [comment]
Would be pretty interesting for Wikis to be integrated into Custom Pages module if you asked me. :wink:

**Comment by 001101** [comment]
> Feli: Would be pretty interesting for Wikis to be integrated into Custom Pages module if you asked me. 

Than it  would be much better to give the user's the ability to customize those seperate menu entrys and to make them drag and drop sortable.
