### ISSUE TITLE
About Page always visible as group member/administrator

### ISSUE THREAD

**Issue by Drocona** [humhub/humhub#2226]
Hello,

I'm new to HumHub and currently exploring the works. 
Due to privacy I don't want all members to see eachothers About Page details, so it's on deny. However, administrators and member managers need to see the About Page at all times.

Did I miss an option or can I change some code somewhere to include certain user groups?
In the ViewAboutPage Permission file I found some related to groups but have no clue where to start.

If someone can point me in the right direction that would be great!

Thanks in advance!
Drocona

**Comment by 001101** [comment]
I don't have a About Page...

**Comment by Drocona** [comment]
After some more reading into the source of the user module and the ViewAboutPage permission configuration I'm 100% sure I'm missing some information to be able to understand what puts a user in a certain group and eventually create a new group with connected users.

In essence, I see everything pointing to this file (ViewAboutPage) for permission check:
`class ViewAboutPage extends \humhub\libs\BasePermission
{

    /**
     * @inheritdoc
     */
    public $defaultAllowedGroups = [
        User::USERGROUP_SELF,
        User::USERGROUP_FRIEND,
    ];`

What I want to do is to have a User::USERGROUP_MANAGEMENT or User::USERGROUP_ADMINS which can always access the About page of a users profile as if they were the user themselves.

Is there anyone that can explain where these groups originate from and how the groups are added to certain users? This will help me understand how the system works.
I guess I can then figure out how to add a new group and link users to it.

**Comment by buddh4** [comment]
For this you'd need to use global permissions. In your backend under "Administration->User->Groups" you can manage global groups and global group permissions. You can check a permission like:

Yii::$app->user->can(new ManageUser());

Here is an example of a ManageUser permission which is available in v1.2: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/admin/permissions/ManageUsers.php
