### ISSUE TITLE
Updating profile pictures seems to hang?

### ISSUE THREAD

**Issue by ttownsend** [humhub/humhub#2228]
Hi all,,
Just installed HH in a shared environment.

When updating either profile pics or space pics the upload progress bar completes, but the screen never refreshes and is left as shown...

Any ideas for a fix?

![meh](https://cloud.githubusercontent.com/assets/7128995/22597130/535333ca-e9fc-11e6-9f37-8a1cd285c199.PNG)

**Comment by cebe** [comment]
does the upload succeed? check the browser debug tools for errors.

**Comment by ttownsend** [comment]
Thanks Cebe,

Upload does not succeed - picture stays as the default when the page is refreshed.

Can you advise on where/how to sue Chrome's debug tools?  I'll post results back here.

**Comment by cebe** [comment]
afaik you open it with F12. check the "Console" Tab.

**Comment by ttownsend** [comment]
Got it ... here's what I see returned...

https://<<REMOVED>>.com/centre/index.php?r=user%2Faccount%2Fprofile-image-upload&userGuid=31d0c8d1-447c-4c60-9e21-13ac622b88fe Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by cebe** [comment]
you can see the full error message in the logs in the admin section.

**Comment by ttownsend** [comment]
Hmmm...seems this might be it.  Checking now...looks like the fileinfo PHP extension is not installed.  I'll contact the hosting company.


`ERROR  Fri, 03 Feb 2017 11:40:53 -0500  yii\base\InvalidConfigException
exception 'yii\base\InvalidConfigException' with message 'The fileinfo PHP extension is not installed.' in /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:142 Stack trace: #0 /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/validators/FileValidator.php(356): yii\helpers\BaseFileHelper::getMimeType('/tmp/phptrjgYr', NULL, false) #1 /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/validators/FileValidator.php(251): yii\validators\FileValidator->validateExtension(Object(yii\web\UploadedFile)) #2 /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/validators/FileValidator.php(215): yii\validators\FileValidator->validateValue(Object(yii\web\UploadedFile)) #3 /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/validators/Validator.php(265): yii\validators\FileValidator->validateAttribute(Object(humhub\models\forms\UploadProfileImage), 'image') #4 /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/base/Model.php(356): yii\validators\Validator->validateAttributes(Object(humhub\models\forms\UploadProfileImage), Array) #5 /home/c3iica/carrebourquehudson.com/centre/protected/humhub/modules/space/modules/manage/controllers/ImageController.php(90): yii\base\Model->validate() #6 [internal function]: humhub\modules\space\modules\manage\controllers\ImageController->actionBannerUpload() #7 /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #8 /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #9 /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('banner-upload', Array) #10 /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('space/manage/im...', Array) #11 /home/c3iica/carrebourquehudson.com/centre/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 /home/c3iica/carrebourquehudson.com/centre/index.php(25): yii\base\Application->run() #13 {main}`

**Comment by buddh4** [comment]
make sure all required php packages are installed: http://docs.humhub.org/admin-requirements.html#required-php-extensions
