### ISSUE TITLE
Unable to display images on HumHub (no pictures)

### ISSUE THREAD

**Issue by kazzz57** [humhub/humhub#2229]
Hello

I congratulate all programmers of the HumHub program, which is really great

After installing HumHub on OVH hosting, I noticed that the image display did not work.

I have already installed HumHub on other OVH hosting and everything works impeccably.
That's why I do not understand where the problem comes from.
Here is my configuration
HumHub version: 1.1.2
Accommodation OVH:
PHP Version MYSQL 5.6
I checked and changed the maximum size of image files
In parameter> advanced> Files : That is 10Mo
I unchecked the option (Use X-Sendfile for download?)
I even deleted all the files as well as reset the SQL database to redo a complete new installation ... but without success I still have the same problem

![image14](https://cloud.githubusercontent.com/assets/25533885/22600988/40caae36-ea3d-11e6-96b8-de79929a297b.jpg)

**Comment by kazzz57** [comment]
Ok for informations

I just deleted all the files of the Humhub, and I just redo an installation with the previous version either version 1.1.0 and the images work

Apparently version 1.1.2 has bugs, in any case with OVH hosting

**Comment by 001101** [comment]
github ist no fucking webspace support board!!!!!!!!!!!!

**Comment by Oncle-BOB** [comment]
Hello, i have the same problem with ovh (mutualized). Did you find a solution with the latest version humhub 1.2.2 ? or an idea of which file is problematic.

**Comment by kazzz57** [comment]
Hello, 
No, I dont have the solution.... I stay in 1.1.0 👎

**Comment by Felli** [comment]
@Oncle-BOB you should then use the imagemagick PHP extension.

**Comment by sam11fr** [comment]
Is there not a file rights issue ? I remember once, I had played with it and the result was the same.
Can you check that ?

**Comment by Oncle-BOB** [comment]
In reality this does not only concern images but all file, zip, txt,... (you confirm user ovh ?)

Yet the rights on the upload folder (755) its correct and file size posted on the site is correct. But when i click on the link, it displays a 500 error (i disabled the .htaccess no difference).

**Comment by sam11fr** [comment]
Hi,
Can you give me the logs of humhub and apache (just to see) ?

**Comment by buddh4** [comment]
Check the logs of the 500 "Administration -> Information -> Logging"

**Comment by Oncle-BOB** [comment]
Hello, here is what i see in the logs (i do not have much thing this is a test site)
<a href="https://www.hostingpics.net/viewer.php?id=437264humhub500.jpg"><img src="https://img11.hostingpics.net/thumbs/mini_437264humhub500.jpg" alt="Heberger image" /></a>
And log apache
`[Fri Sep 22 10:40:17 2017] [error] [client xxx] [host www.xxx.com] End of script output before headers: index.php, referer: https://www.xxx.com/humhub/dashboard
[Fri Sep 22 10:40:21 2017] [error] [client xxx] [host www.xxx.com] End of script output before headers: index.php, referer: https://www.xxx.com/humhub/dashboard`

I did another test i copied my site locally (xampp) i sent a picture (it works) after i send the site local to my web hosting. When i clicked on the image link, always the same 500 error.

I conclude that we can rule out a concern with upload. But a problem with reading.

My question is this... what is the difference between humhub 1.1.0 and humhub 1.2.0 that would cause a denial of access to an uploaded file ? or watched ?

**Comment by Felli** [comment]
One would think the biggest changes would be the JavaScript API rework, and the other would most likely be that the change to the blueimp gallery and the implementation of the HTML5 player was implemented around `v1.2.0` which in of itself had a lot of issues that had required beta version releases, or nightly builds before the full release could come, the other thing would be some of the changes that came with database entries. I believe that I had to do a forced migration via composer on my production site, and a manual database change with my test environment.

**Comment by Felli** [comment]
As for the error that I'm seeing, it looks like the formatting is off in your `fr` messages folder.

**Comment by Oncle-BOB** [comment]
Sorry i meant between humhub 1.1.0 and humhub 1.1.2 because says kazzz57 that the bug appears to this version with ovh hosting.

**Comment by Felli** [comment]
I think most of the changes dealing with 1.1.0 to 1.1.2 were a lot of LDAP issues, also a few translation issues, there were also issues with Yii 2.0.11 now that I think of it.

But to better understand the changes I suggest going to the [download site](https://humhub.org/en/download) and finding the versions you're looking for and clicking "Open release notes" to find what changed between versions.

**Comment by Oncle-BOB** [comment]
Thanks felli, you got me in the good direction, i looked info on the LDAP and "ovh shared" and i realized that "[php execution environment](https://www.ovh.com/us/g1999.hosting_how_to_configure_php_from_your_customer_account)" was on "legacy" instead of "stable"

That solved the problem for me and you user ovh ?

**Comment by Felli** [comment]
From what it looks, a lot of OVH users have been having issues like this lately, I myself find a few minor issues with CloudLinux (CentOS) 6 but that can easily be fixed, I'll make sure to note the issue of `legacy` and `stable` in the `troubleshooting` guides.

**Comment by sam11fr** [comment]
Indeed, the stable version 5.6 was positioned on "Stable" and not "Legacy" on my hosting. So, everything works.

**Comment by Robisar** [comment]
Hi, for your information, I also had recently an issue of not being able to see the images displayed in my platform after moving it to an OVH hosting. As this page is the first source of information I found while looking for a solution, I am sharing what solved my problem here for whoever might find it useful : I actually had corrupted all the images during the transfer to the OVH server through FTP. The solution was to reinstall the platform and switch the transfer mode of my filezilla to "binary" (instead of "auto" or "ASCII") during the transfer of my backup information. More information in this post to the humhub community : https://community.humhub.com/s/installation-and-setup/?contentId=215950, and many thanks to Reuns Snuer for the help !
