### ISSUE TITLE
New message count not updated without reloading page after you’re a member icon was introduced

### ISSUE THREAD

**Issue by Buliwyfa** [humhub/humhub#2230]
Today I see a cool new feature on Humhub community the icon your are member of this space.

Ate the begining, when I visit a space new message count was updated and no new message show on my spaces :). 

Now the problem or bug:
I visit all spaces starting with Announcements, when I hit General Discussion space the new message count stop to be updated, I always have new message. Same for the spaces than follow. I visit them and keep it showing new message.

The message count was reset when I reload the page.

It is worked without reloading at the begging… gut the I have to reload the page.

Hope this helps!

**Comment by WebCrew** [comment]
There is a member with a similar issue - he was trying to create a new post and the post count was working as it should, but the posting text itself was not displayed (not rendered). He has done a video of the problem - you can check it out here: https://youtu.be/ciQILYSd45Q 

I think thats a issue Luke or Julian should see. @luke-

**Comment by Buliwyfa** [comment]
In addition, sometimes after reading a notification all new messages get somehow reset and under my spaces, all spaces have many new messages.

I know this is not a good report to track a bug, but it happens on Community version (my sites are under 1.1.2) so I cannot provide more info.

I just want to let you know about the bug.

**Comment by buddh4** [comment]
The update issue should be solved in the latest branch. I don't really understand the other issue ;) You mean after opening the notification dropdown the notification count is reset?
