### ISSUE TITLE
Notifications Broken After Dev Test Post

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2240]
So after a test post was done by Julian Harrer it looks like the notifications are broken? :laughing:
![screenshot_1](https://cloud.githubusercontent.com/assets/2011633/22705862/278f326a-ed3b-11e6-9ae7-d85e10784d22.png)

**Comment by buddh4** [comment]
Do you still have this issue? Should be solved by now.

**Comment by Felli** [comment]
The issues look to have been fixed.
