### ISSUE TITLE
MySQL Error while updating to 1.0.2

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#2242]
Hi, I have 2 builds of HH, one public and other for testing with all default. In both versions I get this error:

Error!
{"status":"ok"}Database Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away The SQL being executed was: SELECT `id` FROM `user_http_session` WHERE `id`='20db058f9c9cdbafe9f27de809f36eb9'

**Comment by jeremiahtenbrink** [comment]
Do you have yii2 debug on. If so can you pin point the file this error code is coming from, and what does your log say.

**Comment by eddiepiazza** [comment]
I just activated those two lines in index:

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

let´s see the result.

**Comment by eddiepiazza** [comment]
{"status":"ok"}Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away The SQL being executed was: SELECT `id` FROM `user_http_session` WHERE `id`='20db058f9c9cdbafe9f27de809f36eb9'' in /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/Schema.php:631 Stack trace: #0 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/Command.php(915): yii\db\Schema->convertException(Object(PDOException), 'SELECT `id` FRO...') #1 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/db/Command.php(388): yii\db\Command->queryInternal('fetchColumn', 0) #2 /home/opengrow/public_html/es/community/protected/humhub/modules/user/components/Session.php(56): yii\db\Command->queryScalar() #3 [internal function]: humhub\modules\user\components\Session->writeSession('20db058f9c9cdba...', '__flash|a:0:{}_...') #4 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Session.php(186): session_write_close() #5 [internal function]: yii\web\Session->close() #6 {main}

**Comment by jeremiahtenbrink** [comment]
Looks like the code is coming from humhub/modules/user/components/Session  on line 56.

**Comment by jeremiahtenbrink** [comment]
Looking at the code in session. I want to know if you are logged into humhub when you are running it or have you not logged it yet?

**Comment by eddiepiazza** [comment]
I really don´t know, I disabled all modules to try, but nothing. I dont´t know what to do with this error on this line. Have I to replace the file?

I need a solution because we release an update of our software and some users will come to visit our release.

**Comment by eddiepiazza** [comment]
Of course I am logged, I cannot update outside admin panel...

**Comment by eddiepiazza** [comment]
I replaced the session.php file by new one from HH 1.0.2 and still not working.

**Comment by eddiepiazza** [comment]
if I replace the old HH files by new ones and I proceed with a new installation connecting to same database, do you think it will keep all HH content exactly how it was? Images, comments, users, mails etc... ???

**Comment by eddiepiazza** [comment]
OMG ! I enabled again custom pages module and all my pages disappeared...

May I have a bit of assistance to fix this chaos please ?

**Comment by jeremiahtenbrink** [comment]
it may, but better not take the chance. run a backup of the database, in different formats. Then hopefully you can import the data back in if it changes stuff.

**Comment by buddh4** [comment]
check https://dev.mysql.com/doc/refman/5.7/en/gone-away.html
