### ISSUE TITLE
Polish language support

### ISSUE THREAD

**Issue by glombers** [humhub/humhub#2243]
where edit the language? I will add Polish language support

**Comment by Felli** [comment]
@glombers if it's not [here](https://github.com/humhub/humhub/tree/master/protected/humhub/messages) then it has to be added.

**Comment by glombers** [comment]
@Felli thanks!!. It is but it must be improved. Likewise, the lack of documentation of Polish language I think it's a good step ...

**Comment by Felli** [comment]
@glombers I'd suggest joining over at [Humhub Traslate](translate.humhub.org) and using the translation tool which is provided and easy to use, first join then request to join the pl space and then you'll be able to use the translation tool in the menu. :smile:
