### ISSUE TITLE
PHP 5.5 and 5.6 compatibility issue

### ISSUE THREAD

**Issue by eddiepiazza** [humhub/humhub#2251]
Hi, I get crazy installing HH 1.0.2 in brute force by installing it clean to my HH 1.0.1 database and replacing all my HH 1.0.1 files by new one (I did it because the problem I get trying to update #2242). On installation I saw that my PHP version was not compatible and I had to pass from 5.5 to 5.6.

All right, seems it works, but I started to see after one day some errors comming from people who try to regfister, and surprise, registry was not working. I supposed that was related with my brute force installation and I installed again my Backup from HH 1.0.1 with its database.

All seems fine and registry still giving the same error.  I remembered that the only change I made was PHP version, and I get back to 5.5

Surprise it´s fixed...

Well I will piblish here my error and the config for PHP 5.5 and 5.6 for you localise the error with mailing system.

ERROR  Fri, 10 Feb 2017 09:58:10 +0000  Swift_TransportException
exception 'Swift_TransportException' with message 'Connection could not be established with host localhost [ #0]' in /home/opengrow/public_html/es/community/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269 Stack trace: #0 /home/opengrow/public_html/es/community/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection() #1 /home/opengrow/public_html/es/community/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array) #2 /home/opengrow/public_html/es/community/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start() #3 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2-swiftmailer/Mailer.php(146): Swift_Mailer->send(Object(Swift_Message)) #4 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/mail/BaseMailer.php(260): yii\swiftmailer\Mailer->sendMessage(Object(yii\swiftmailer\Message)) #5 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/mail/BaseMessage.php(48): yii\mail\BaseMailer->send(Object(yii\swiftmailer\Message)) #6 /home/opengrow/public_html/es/community/protected/humhub/modules/user/models/Invite.php(128): yii\mail\BaseMessage->send() #7 /home/opengrow/public_html/es/community/protected/humhub/modules/user/models/Invite.php(100): humhub\modules\user\models\Invite->sendInviteMail() #8 /home/opengrow/public_html/es/community/protected/humhub/modules/user/controllers/AuthController.php(84): humhub\modules\user\models\Invite->selfInvite() #9 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin() #10 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #11 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #12 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('login', Array) #13 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('user/auth/login', Array) #14 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #15 /home/opengrow/public_html/es/community/index.php(25): yii\base\Application->run() #16 {main}

PHP 5.5 config:
![image](https://cloud.githubusercontent.com/assets/8577866/22823223/92ac3f84-ef7a-11e6-9663-6acf9a888e59.png)

PHP 5.6 config:
![image](https://cloud.githubusercontent.com/assets/8577866/22823239/a41b7afa-ef7a-11e6-9dba-83744007a30d.png)

**Comment by buddh4** [comment]
The error just indicates that there is no connection to your mail server 'Connection could not be established with host localhost' check your mail settings "Administration -> Settings -> Advancec -> E-Mail"

**Comment by eddiepiazza** [comment]
I understood that there is a problem with mails, but I have it configured in SMTP and when I change PHP from 5.5 to  5.6, mail system stop to work. All SMTP config is fine.

The only reason I am changing the php version is because a Kind of uncompatibility with php 5.5.38
![image](https://cloud.githubusercontent.com/assets/8577866/22854254/104f8512-f062-11e6-85e6-3940bcf521dd.png)

With all info I posted about php config, you cannot help me to find the source of the problem please ?

**Comment by eddiepiazza** [comment]
Problem located and fixed. Passing from php 5.5 to 5.6, "localhost" as SMTP server is not anymore working.
