### ISSUE TITLE
Doubled nav in 1.1.2 fresh install

### ISSUE THREAD

**Issue by blendsoft** [humhub/humhub#2253]
I just installed fresh version of 1.1.2, cloned from github

It looks like onTopMenuInit event is triggered two times for some reason.
![screenshot-localhost 8081-2017-02-10-16-50-57](https://cloud.githubusercontent.com/assets/1213251/22833264/9071b14a-efb1-11e6-8f36-d13f4e9045fe.png)

**Comment by Felli** [comment]
How are you installing Humhub? From what I've seen a lot of users are having this issue when installing via composer.

**Comment by blendsoft** [comment]
I found the problem already

in
humhub\widgets\BaseMenu

`
 public function init()
    {
        $this->addItemGroup(array(
            'id' => '',
            'label' => ''
        ));
        $this->trigger(self::EVENT_INIT);
        return parent::init();
    }
`

triggers init event then runs parents init which triggers init second time. 
every init event adds module position to nav. 

Should look lie this

` public function init()
    {
        $this->addItemGroup(array(
            'id' => '',
            'label' => ''
        ));
        parent::init();        
    }`

parent returns nothing, so its not needed here.

**Comment by scysys** [comment]
Same here on New Installs (latest stable today) and Updates on existing installations

**Comment by buddh4** [comment]
This is due to a Yii Update make sure to set the composer dependency to 2.0.10 in composer.json and make a composer update.

**Comment by Poulin-L** [comment]
Hi.
I've the same problem and I don't understand which dependency you told to update.
I also have this: 
`Package yiisoft/yii2-codeception is abandoned, you should avoid using it. Use codeception/codeception instead.`
Is it linked to your solution?

**Comment by buddh4** [comment]
You'll have to set the Yii version down to 2.0.10 here: 
https://github.com/humhub/humhub/blob/master/composer.json#L18

and run a composer update.

**Comment by Poulin-L** [comment]
The fact is that I'm on the stable branch with the version `2.0.4` for yii2 and changing to `2.0.10` didn't change anything...

**Comment by blendsoft** [comment]
Guys, uou  shoud not ever make such advice, to downgrade yii, fix your code first.

**Comment by cperreault** [comment]
Cherry-picking the fix commit e99955f on a 1.1.2 version updated from 1.0.1 worked for me! Thanks!
