### ISSUE TITLE
Display bugs in 1.2beta

### ISSUE THREAD

**Issue by garthh** [humhub/humhub#2256]
Since I've update Humhub to 1.2beta, I'vo got a display issue on word-breaks and on social icon positions. Here's a screenshot : 
![pb1 2b](https://cloud.githubusercontent.com/assets/1765394/22853532/176d3640-f059-11e6-9085-b91e2fc96f01.JPG)

**Comment by buddh4** [comment]
This is already fixed in the latest master branch, will be available with beta2. Thanks for the report anyways!
