### ISSUE TITLE
Module as default Bug in 1.2 Beta-1

### ISSUE THREAD

**Issue by globeFrEak** [humhub/humhub#2257]
I have found a bug, i cannot set a module as default. I tested some modules (cfiles, calender) all with the same error.

It is a fresh installation from Humhub 1.2 Beta-1
(downloaded from https://www.humhub.org/de/download)

### Error:
> Sat, 11 Feb 2017 16:41:03 +0100  yii\db\IntegrityException
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`humhub_12`.`space_module`, CONSTRAINT `fk_space_module-space_id` FOREIGN KEY (`space_id`) REFERENCES `space` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)' in C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\Command.php:846 Stack trace: #0 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\Command.php(846): PDOStatement->execute() #1 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\Schema.php(454): yii\db\Command->execute() #2 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\ActiveRecord.php(494): yii\db\Schema->insert('space_module', Array) #3 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\ActiveRecord.php(461): yii\db\ActiveRecord->insertInternal(NULL) #4 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\BaseActiveRecord.php(635): yii\db\ActiveRecord->insert(true, NULL) #5 C:\xampp\htdocs\humhub12\protected\humhub\modules\admin\controllers\ModuleController.php(330): yii\db\BaseActiveRecord->save() #6 [internal function]: humhub\modules\admin\controllers\ModuleController->actionSetAsDefault() #7 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) #8 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array) #9 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('set-as-default', Array) #10 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('admin/module/se...', Array) #11 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 C:\xampp\htdocs\humhub12\index.php(25): yii\base\Application->run() #13 {main} Next exception 'yii\db\IntegrityException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`humhub_12`.`space_module`, CONSTRAINT `fk_space_module-space_id` FOREIGN KEY (`space_id`) REFERENCES `space` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) The SQL being executed was: INSERT INTO `space_module` (`module_id`, `space_id`, `state`) VALUES ('calendar', 0, 2)' in C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\Schema.php:636 Stack trace: #0 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\Command.php(856): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `sp...') #1 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\Schema.php(454): yii\db\Command->execute() #2 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\ActiveRecord.php(494): yii\db\Schema->insert('space_module', Array) #3 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\ActiveRecord.php(461): yii\db\ActiveRecord->insertInternal(NULL) #4 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\db\BaseActiveRecord.php(635): yii\db\ActiveRecord->insert(true, NULL) #5 C:\xampp\htdocs\humhub12\protected\humhub\modules\admin\controllers\ModuleController.php(330): yii\db\BaseActiveRecord->save() #6 [internal function]: humhub\modules\admin\controllers\ModuleController->actionSetAsDefault() #7 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) #8 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array) #9 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('set-as-default', Array) #10 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('admin/module/se...', Array) #11 C:\xampp\htdocs\humhub12\protected\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 C:\xampp\htdocs\humhub12\index.php(25): yii\base\Application->run() #13 {main} Additional Information: Array ( [0] => 23000 [1] => 1452 [2] => Cannot add or update a child row: a foreign key constraint fails (`humhub_12`.`space_module`, CONSTRAINT `fk_space_module-space_id` FOREIGN KEY (`space_id`) REFERENCES `space` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) )

### Info:
> $_GET = [ 'r' => 'admin/module/set-as-default' 'moduleId' => 'calendar' ] $_SERVER = [ 'MIBDIRS' => 'C:/xampp/php/extras/mibs' 'MYSQL_HOME' => '\\xampp\\mysql\\bin' 'OPENSSL_CONF' => 'C:/xampp/apache/bin/openssl.cnf' 'PHP_PEAR_SYSCONF_DIR' => '\\xampp\\php' 'PHPRC' => '\\xampp\\php' 'TMP' => '\\xampp\\tmp' 'HTTP_HOST' => 'localhost' 'HTTP_CONNECTION' => 'keep-alive' 'CONTENT_LENGTH' => '161' 'HTTP_ACCEPT' => '*/*' 'HTTP_ORIGIN' => 'http://localhost' 'HTTP_X_CSRF_TOKEN' => 'LV9nd1Z6TXVvDyI5JzV/F0EtNUcePT8cQmk9EwkyCCIaaCoUMAwAMA==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' 'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8' 'HTTP_DNT' => '1' 'HTTP_REFERER' => 'http://localhost/humhub12/index.php?r=admin%2Fmodule%2Flist' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'de,en-US;q=0.8,en;q=0.6,fr-CA;q=0.4,fr;q=0.2' 'HTTP_COOKIE' => 'pm_new-people-panel=expanded; pm_new-spaces-panel=expanded; pm_getting-started-panel=expanded; has_js=1; CSRF_TOKEN=b219c544b2598692241432d8be9d31a08b6d27d6; fusion44B56_visited=yes; language=en; sin=6iefhfishqdjr83ebi87eabj67; _csrf=a0c846de29407d9b0290ac5e442f4d50dda09749d8f8fc88b038d8f8029c9cdba%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22BPENqO2blrR0HGrio6Zd_HEW77McfvME%22%3B%7D; PHPSESSID=d3ogucquoaagc9t3mmmki7ibf1; _identity=4cde6e7f337096888c6e813de1f9d601bfda364f0758b3ae12bf1ca2d872b9afa%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22f87fb6ec-0517-4402-b687-46c2e72fc625%22%2C2592000%5D%22%3B%7D' 'PATH' => 'C:\\Program Files\\ImageMagick-6.9.2-Q16;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\xampp\\php;C:\\Program Files\\Java\\jdk1.8.0_25\\bin;C:\\Program Files (x86)\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\ComposerSetup\\bin;C:\\Program Files\\nodejs\\;C:\\WINDOWS\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft Emulator Manager\\1.0\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\FileBot\\;C:\\Program Files\\TortoiseGit\\bin;C:\\Users\\globeFrEak\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\;C:\\Users\\globeFrEak\\AppData\\Local\\Programs\\Python\\Python36-32\\;C:\\Ruby22-x64\\bin;C:\\Users\\globeFrEak\\AppData\\Local\\atom\\bin;C:\\Users\\globeFrEak\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\globeFrEak\\AppData\\Roaming\\Composer\\vendor\\bin;C:\\Program Files (x86)\\Microsoft VS Code\\bin;C:\\Users\\globeFrEak\\AppData\\Roaming\\npm' 'SystemRoot' => 'C:\\WINDOWS' 'COMSPEC' => 'C:\\WINDOWS\\system32\\cmd.exe' 'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC' 'WINDIR' => 'C:\\WINDOWS' 'SERVER_SIGNATURE' => '<address>Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21 Server at localhost Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.21' 'SERVER_NAME' => 'localhost' 'SERVER_ADDR' => '::1' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '::1' 'DOCUMENT_ROOT' => 'C:/xampp/htdocs' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => 'C:/xampp/htdocs' 'SERVER_ADMIN' => 'postmaster@localhost' 'SCRIPT_FILENAME' => 'C:/xampp/htdocs/humhub12/index.php' 'REMOTE_PORT' => '64608' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'POST' 'QUERY_STRING' => 'r=admin%2Fmodule%2Fset-as-default&moduleId=calendar' 'REQUEST_URI' => '/humhub12/index.php?r=admin%2Fmodule%2Fset-as-default&moduleId=calendar' 'SCRIPT_NAME' => '/humhub12/index.php' 'PHP_SELF' => '/humhub12/index.php' 'REQUEST_TIME_FLOAT' => 1486828292.167 'REQUEST_TIME' => 1486828292 ]

**Comment by dmitrydrynov** [comment]
I have found this bug too
