### ISSUE TITLE
Allow to invite users by URL

### ISSUE THREAD

**Issue by Oreolek** [humhub/humhub#226]
Many social networks allow to generate a unique invite URL. It's easier than email invite for the user because a link can be easily sent via any other social network.

**Comment by cboulanger** [comment]
+1

**Comment by nlmunro** [comment]
I'm was also looking for this and have started work on it - WIP:
https://github.com/nlmunro/humhub

**Comment by funkycram** [comment]
Duplicated with https://github.com/humhub/humhub/issues/5699 which is done in Humhub 1.14.
@luke- I think you could close this issue.
