### ISSUE TITLE
Move docs to rootpath

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#2260]
Hello,

would be much more access able if the docs under 
`/humhub/protected/humhub/docs`

are just under 

`/humhub/docs`

greets

**Comment by Felli** [comment]
@001101 I'm interested in why this would help? I can understand it being easier to access without having to navigate through the repository, but why would it benefit being moved?

**Comment by 001101** [comment]
@Felli ehm, because it is more logical, more ease of use and less hidden?

**Comment by buddh4** [comment]
Would be a bit more comfortable, but on the other hand, the root directory should be held as clean as possible.

**Comment by 001101** [comment]
docs is default at root
