### ISSUE TITLE
Fresh install 1.2 beta - problem with PHP version

### ISSUE THREAD

**Issue by claudiusheitz** [humhub/humhub#2262]
As a limit of my hoster I can only user PHP 5.5 together with the ldap extension.
The problem: Humhub 1.2 beta 1 doesn't allow me to use PHP 5.5 - although it should be enough according to the error message - see screenshot.

![bildschirmfoto 2017-02-13 um 23 14 06](https://cloud.githubusercontent.com/assets/1027097/22907032/83a1d006-f247-11e6-8be2-a2de9c016f71.png)

**Comment by eddiepiazza** [comment]
seems a bug, I had it also, change your PHP version to 5.6 and you have to know also that while configuring your SMTP server for mails you need to use in mail server your server and not "localhost".

I had "localhost" as server with PHP 5.5 but is not working anymore with php 5.6
