### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2264]
When displaying oEmbed links this is what you get after v1.2beta-1 release, most likely caused by Markdown being implemented into posts, and comments.
![](http://image.prntscr.com/image/71a29c2c55c54a7f8672a6b131f8adc7.png)

**Comment by garthh** [comment]
For me, no error in logs or when I add a Youtube link, but no video are dislayed... except when I edit the post...

**Comment by OataO** [comment]
Same here i checked apache log, humhub logs, no error. Nothing is displayed.

**Comment by Felli** [comment]
The error normally happens when you try pressing the "save" button after you've tried editing the post. :+1:

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/commit/0d50f3f69d7a0710a0104b7932ade6ad9920265a
