### ISSUE TITLE
Tamil font not visible in wall

### ISSUE THREAD

**Issue by deepakpachiannan** [humhub/humhub#2267]
Tamil font not visible in wall
![untitled-1](https://cloud.githubusercontent.com/assets/25788994/22966060/89db5b28-f386-11e6-8b21-4a41b15b20d7.png)

how to enable it?

**Comment by Felli** [comment]
Are you using the [`utf8_general_ci` collate](http://docs.humhub.org/admin-installation.html#database)?

**Comment by deepakpachiannan** [comment]
no utf8_unicode_ci collate. 

Which one i have to set?

**Comment by deepakpachiannan** [comment]
Still problem exist after change to...

![capture](https://cloud.githubusercontent.com/assets/25788994/22974562/eb957278-f3a8-11e6-9ef4-b92b08faaf1f.PNG)

**Comment by Felli** [comment]
You have to change all the database tables to match the utf8_general_ci collate.
