### ISSUE TITLE
Time spans are printed in German

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2268]
v1.2.0-beta.1: independent from any locale or language settings, humhub reports time of post in German. Also on the official humhub community site.
![schermafbeelding 2017-02-15 om 10 34 32](https://cloud.githubusercontent.com/assets/6781157/22968465/c3e7b3fa-f36a-11e6-8a98-41426eba23fa.PNG)

**Comment by buddh4** [comment]
This is fixed in the current master branch and will be available in the next beta2.
