### ISSUE TITLE
Humhub crashed in iOS Safari with "apple-mobile-web-app-capable"

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2269]
v.1.2.0-beta.1: If humhub is saved as a desktop web app by iOS mobile safari, using the common meta tag <meta name="apple-mobile-web-app-capable" content="yes">, the humhub application will hang despite any other humhub setting. No errors in debug reported.

**Comment by buddh4** [comment]
Did this work with older versions of HumHub?
