### ISSUE TITLE
Solved: HumHub header Viewport meta tag not working or overruled

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2270]
v.1.2.0-beta.1: The meta tag <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"> is not working, or is overruled on another level. The meta tag above, which is part of the standard humhub header, implies that the browser screen can not be zoomed. Adding user-scalable=0 also does not work. Screens remain zoomable (pinch, etc.).
This issue (along with [issue 2269](https://github.com/humhub/humhub/issues/2269) ) makes humhub unsuitable to function as a stand-alone web app on mobile devices.

**Comment by martinbeek** [comment]
SOLVED!  
Since iOS 10.1, user-scalable=0 on viewports (to disable zooming) is disabled / ignored in Safari! 
Only workaround is a javascript that forces the viewport after page load. 

This is what i've made to get Safari prevent page zooming (in the head.php file or main.php of your theme):

```
<script>
function restrictAppScale() {

    if (navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i)) {
  
		var viewportmeta = document.querySelector('meta[name="viewport"]');
		if (viewportmeta) {  
		      	  
			setTimeout(function(){
        		viewportmeta.content = 'width=device-width, height=device-height, minimum-scale=1, maximum-scale=1, initial-scale=1, user-scalable=no, target-densitydpi=device-dpi';                  
            },444);
		
			// prevent pinch to restrict zoom
            document.addEventListener('touchstart', function(event) {
            	if (event.touches.length > 1) {
                	event.preventDefault();                  	                
                }                                      
			}, false);
                  
		  	document.addEventListener('gestureend', function(e) {                  
            	setTimeout(function(){
					viewportmeta.content = 'width=device-width, height=device-height, minimum-scale=1, maximum-scale=1, initial-scale=1, user-scalable=no, target-densitydpi=device-dpi';
                },444);
		  	}, false);

		  	document.addEventListener('touchend', function(e) {                  
            	setTimeout(function(){
					viewportmeta.content = 'width=device-width, height=device-height, minimum-scale=1, maximum-scale=1, initial-scale=1, user-scalable=no, target-densitydpi=device-dpi';
                },444);
		  	}, false);		  
        }                
   }
}

$(document).ready(function () {
	setTimeout(function(){     
		restrictAppScale();
	},666);
});
</script>

```

This solves the problem with Viewport scaling on iOS.

**Comment by buddh4** [comment]
I'll close this for now, the feature was disabled for new webkit/ios browsers. Your workaround can be added to custom themes if someone requires it. Thanks for your investigation!

**Comment by latamclickcom** [comment]
hi, how change this: <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">

**Comment by marc-farre** [comment]
> hi, how change this: "viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"

You must overwrite this view file: https://github.com/humhub/humhub/blob/master/protected/humhub/views/layouts/main.php
using a custom theme. See https://docs.humhub.org/docs/theme/views
