### ISSUE TITLE
Post deleted despite Cancel !

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2273]
v1.2beta1: if i select Delete on a post, and select Cancel from the "are you sure" confirmation pop-up, the post is deleted anyway!

**Comment by Felli** [comment]
Need to provide an error stack from the Admin panel -> Information -> Logging if one is shown.

**Comment by martinbeek** [comment]
I will try this again later today, but the problem also exists on the humbub community site - not on my site only - so you can check it out easily. I think it's a major (and dangerous) bug

**Comment by martinbeek** [comment]
GOOGLE CHROME JS DEBUGGER:

When Delete button is clicked (on a post):

humhub.log.js?v=1487242046:158 DEBUG - humhub.modules.action: Detected unhandled action ActionBinding {parent: document, eventType: "click", event: "click.humhub-action", selector: "[data-action-click]", directHandler: undefined}
humhub.log.js?v=1487242046:160 DEBUG - humhub.modules.action: Update action bindings
humhub.log.js?v=1487242046:158 DEBUG - humhub.modules.action: Handle Action ActionBinding {parent: document, eventType: "click", event: "click.humhub-action", selector: "[data-action-click]", directHandler: undefined}

**Comment by buddh4** [comment]
This is fixed in the current master branch.

**Comment by stAMy** [comment]
This still seem to be an issue on deleting events (activities)

**Comment by buddh4** [comment]
@stAMy should be fixed by: https://github.com/humhub/humhub-modules-calendar/commit/5ad11ec1735d712efd5a72df26ed6e26f347c48f
