### ISSUE TITLE
No post and attachment buttons on Safari iPad, and Chrome on all iOS devices

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2274]
v.1.2beta1:  when i enter the status input box, the submit and attachment buttons do not appear.
Tested on Chrome on iPhone 7:iOS 10
![image](https://cloud.githubusercontent.com/assets/6781157/23000114/3fdffa2a-f3df-11e6-81bd-5a15ded72d09.png)

**Comment by Felli** [comment]
Need to provide an error stack from the Admin panel -> Information -> Logging if one is shown.

**Comment by martinbeek** [comment]
No errors are shown in the logging. The problem is with every humbug 1.2beta site - by the way - not just my installation.

**Comment by buddh4** [comment]
Probably a javascript issue, can you somehow check the browser console if there is one, I currently don't have a iPhone to test.

**Comment by martinbeek** [comment]
Hi. I suspect it's a Mobile Chrome issue, I'll check it on an android device later today (easier to debug...).

Thanks
Martin.

**Comment by martinbeek** [comment]
Oops, my iPad (iOS 9.4) w. Safari does never show the update and attachment burtons!

**Comment by buddh4** [comment]
Would be great if you can check the javascript console with your iPad, perhaps there are some javascript errors logged https://www.wickedlysmart.com/hfjsconsole/

**Comment by buddh4** [comment]
Did you have the chance to check the developer console yet?

**Comment by martinbeek** [comment]
Yes i did. No messages show up in the debugger. The problem still exists on both IPad and iPhone. I have been told that the document.ready event is processed differently sometimes in Safari and that the sequence of loading JavaScript is sometimes disturbed. This clearly is the case "sometimes" because it works well eight times out of ten. 
To cut a long story short... No clue from the debugger. It happened three times today on the Humhub community site on my iPhone 6... bugger...

**Comment by martinbeek** [comment]
Again, the first time this hour I try again on the HumHub community site, and bingo!
No buttons and I have to reload three times to get it working.
![img_3294](https://cloud.githubusercontent.com/assets/6781157/23959594/e103699c-09a5-11e7-9198-3bb4eeceb27e.PNG)

**Comment by martinbeek** [comment]
There is no cursor too, maybe that is a clue.
Also happens on Chrome browser on iOS but that is logical, because it's the same browser underneath.

**Comment by buddh4** [comment]
Perhaps it's a problem with the richtext since this is not an normal input but an editable div.

**Comment by buddh4** [comment]
Could not recreate this with iPhone5/6 with iOs 10.3. Don't know about iOS 9.4, but I assume the old safari browser is missing some html5 features.

**Comment by martinbeek** [comment]
I'm myself am on a brand new iphone 7 and i use humhub mostly on this phone.  My colleague Donny is on an iPhone 6 plus with latest iOS update. My colleague Sonja is on an iPhone 6 w . iOS 10.3.1. My colleague Barry is on an iPad Air with ios 10.1 -  
We all experience this problem several times per day. 
On our humhub, but also on the community humhub site.

M.

Ps. you have set the status " Unable to reproduce" but i can show you many screenshots if you like, from me and three other people. From our site, and from the humhub site...

**Comment by buddh4** [comment]
Unable to reproduce means, that I can't provide any steps for reproducing the issues. It seems this issue happens at random. Another problem is that it's very hard for me to debug this issue since I have no developer console for iOs.

The following file is responsible for fading in https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/resources/js/humhub.content.form.js#L37 somehow the handler is not executed in your case, perhaps you are able to debug this. I'll try my best to reproduce this issue with some test output.
