### ISSUE TITLE
FAILED UPDATE

### ISSUE THREAD

**Issue by TezzahhH** [humhub/humhub#2275]
my HumHub was working fine until I just accepted the latest update.
<img width="1573" alt="humhub_error_post-upgrade" src="https://cloud.githubusercontent.com/assets/24807791/23049031/a9528e62-f50d-11e6-95ed-c2bd09190963.png">

Cannot use the admin console, nothing.   Looks like the files are in unknown states and the script cannot complete.

HELP!?

**Comment by Felli** [comment]
I'm just going off a hunch that you mean updating from v1.1.2 to v1.2? If so I'd suggest deleting all of the v1.1.2 files & folders from your server then downloading and then uploading the v1.2 files & folders to your server, of course, you and then just use the same database you were using before the update.

**Comment by Felli** [comment]
Also, you should check the new requirements out in the new [docs](http://docs.humhub.org/admin-requirements.html).

**Comment by buddh4** [comment]
which php version are you running?

**Comment by buddh4** [comment]
You probably have to update your php version to 5,6 or later.
