### ISSUE TITLE
Shopping cart module

### ISSUE THREAD

**Issue by huuthanhdtd** [humhub/humhub#2276]
Please create it for free or $.  Thanks

**Comment by 001101** [comment]
@huuthanhdtd i can make you a cart for 2000$

**Comment by huuthanhdtd** [comment]
@001101 : Pls show demo if you can. Thanks

**Comment by 001101** [comment]
@huuthanhdtd i make a demo if i have the half ahead and we have a contract

**Comment by ArchBlood** [comment]
Should be closed;

https://marketplace.humhub.com/module/ecommerce/description
