### ISSUE TITLE
Meta data (rotation) not respected for camera images

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2280]
v.1.2.beta1
Rotation metadata is ignored (or removed?) while displaying camera images.
Landscape and portrait images are all shown in landscape. 

UPDATE: this is ONLY when using the "Image Magick convert command (optional)" in the settings.

Example: add an image to your post using the webcam of your laptop, or the camera of your mobile phone. Take it portrait-style (easy with a phone). Upload and post. 

In the example image below, you see two images posted from my iphone, one was taken holding the camera horizontally, the other holding the camera vertically. Both are wrongly displayed in landscape view. 
![schermafbeelding 2017-02-18 om 11 55 33](https://cloud.githubusercontent.com/assets/6781157/23092698/42113ee6-f5d1-11e6-8aef-f9297857987d.PNG)

**Comment by martinbeek** [comment]
UPDATE: this is ONLY when using the "Image Magick convert command (optional)" in the settings.

**Comment by martinbeek** [comment]
**Solution**:  add "-auto-orient" to each imagemagick command in ./protected/humhub/modules/file/libs/ImageConverter.php

**Comment by luke-** [comment]
Thank you for the investigation!
