### ISSUE TITLE
Background scipts? Timespan language skips back to german without any update or action

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2281]
v.1.2.beta1
I re-installed HumHub from scratch and the problem with German timespans was solved.

Now, after 24 hours of spending no time on my Humhub site - no updates, no posting, nothing - suddenly the timespans are all in German again! There were zero views - this is not a public website.

What kind of communication is going on "behind the screens"? Installations do not change magically by themselves.... So, what changes my current installation without me behind the wheel?? 

I find this pretty concerning...

**Comment by buddh4** [comment]
Is fixed in master.
