### ISSUE TITLE
Oembed Youtube

### ISSUE THREAD

**Issue by NENJAK** [humhub/humhub#2285]
Hi,

does someone has working 
Endpoint Url for Youtube on Version 1.2.?
Thanks

**Comment by Felli** [comment]
I believe this is due to the implementation of Markdown into both posts and comments, as this also would happen when you would implement Markdown via JavaScript which had you edit the head.php so that it would call the Script. #2264

**Comment by NENJAK** [comment]
Hi Felli,

So how I can check that and where (in code)
and is it any workaround?

**Comment by Felli** [comment]
This should be fixed now. 50b3e06

**Comment by NENJAK** [comment]
Unfortunately I have still the same problem.

**Comment by NENJAK** [comment]
I guess they will fix it in Ver. 2.0

**Comment by buddh4** [comment]
Yes, will be available with beta2

**Comment by twopizza** [comment]
@buddh4, may you show exact commit? I can`t make full update now

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/commit/0d50f3f69d7a0710a0104b7932ade6ad9920265a
