### ISSUE TITLE
Profile banner and profile image cropping not updated

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2287]
v.1.2beta1 
If you edit the profile banner or image, by cropping it, etc. - the image is not updated in the browser and changes seem to be lost. I assume the edited (recropped) image is saved under the same name (id), so that the browser's cache does not see a difference. I've disabled caching in my browser and caching in the NGinx server headers for this directory, but to no avail. 
Reloading the page after a few minutes does show the change.

**Comment by martinbeek** [comment]
This is still a serious issue. We have a few members on our site now, and all are complaining ;-) 
Tested with all types of browesers and devices / PCs / macs. 
Cropping or repositioning banner only works once; then caching kicks in.

**Comment by buddh4** [comment]
In my case the page reloads after cropping the image. Can you check if you have errors in your logs, perhaps the images are too big and there is an memory issue. In this case you should install imagemagic.

**Comment by martinbeek** [comment]
I'm using imagemagic. I have the debugger running but no errors. But the issue is that the cropped image is saved under the same name and ?guid so there is no difference for the cache. Therefore it will show the cropped image after the cache expires.

**Comment by martinbeek** [comment]
We run nginx through cloudflare with a very elaborate caching - I've checked our caching logs and it indeed detects no difference in the saved versions, so the file is not updated in the cache.

**Comment by martinbeek** [comment]
I spent four hours yesterday, setting up a new bare bones install of nginx, php-fpm, mysql and humhub 1.2beta2, but nothing has changed. No caching, no cloudflare, everything out of the box.
So it must be the combination of nginx and Debian I suppose...
Meanwhile, this is a huge problem. Even uploading a new image results in the old image staying in view; I have to force browser reload four or five times to see the change.

**Comment by martinbeek** [comment]
I've read the following [on php.net](http://php.net/manual/en/function.filemtime.php) regarding the filemtime function you use as querystring for each saved version of the image. 

![img_3209](https://cloud.githubusercontent.com/assets/6781157/23599506/d76e7b76-0241-11e7-8349-1ab9227510b2.JPG)

Maybe it's a far shot, but I'm out of options...

Martin

**Comment by martinbeek** [comment]
A recap, and again a request for help.

Yesterday we've sat together with two other developers to tackle this problem and we dis so until very early in the morning, to no avail at all. Problem NOT solved. 


We even changed server, to another fresh  vps and we did two clan humhub installs; the stable version an beta4. 
Tried a full non caching setup with no cache headers on all served files, et ceteta.
Tested on chrome and safari, but the profile image and banner image is NOT refreshed in the browser if the file filemtime querystring changes on the image.

We tried to install cloudflare on the domain and have a cachebusting rule to handle it, but no luck there.
We sat together with three people with three different laptops and were kept having the same problems; identical on mobile.

Images update after one minute. So if you hit Refresh in your browser a minute long, the updated image evetually appears. Changing the querystring manually does not work.

Just telling you this to ensure you that we have done everything we can.

One main constant factor in all we tried: we insist on using Nginx. That's our webserver of choice.
I've tried several bare-bones nginx configurations and php/php-fpm switches. 

If analysed in the chrome debugger:
Cropped images do all have a nocache header and opening a cropped image in a new browser screen AND changing the querystring does not even work!  All the browsers keep serving the same from cache. Clearing the browser cache is the only thing that helps. There are no debug messages.

So what makes browsers insistantly serving a caches image without regard of the querystring?
Is it in the name? Or is it some hidden nginx thing?

I invite you to log in on our site and analyse the image headers yourself - you'll be amazed. Bit i'm giving up after weeks of struggling with this and the help of many people. 

I reversed everything back to the original settings and beta4. If one of the developers want to take a look, let me know.

Martin.

**Comment by Felli** [comment]
The only thing that I can think of is browser cache is overruling your site cache somehow?
I've read a little about this happening before and ways of forcing cache updates.
http://stackoverflow.com/questions/22958865/forcing-cache-update-in-browser

**Comment by martinbeek** [comment]
All the correct headers are there, i'm at a complete loss here...

**Comment by buddh4** [comment]
Are you sure it's an humhub issue or perhaps more a cloudflare/caching issue?

**Comment by martinbeek** [comment]
No, we did an installation without cloudflare or anything with the same results.

I suspect nginx. I have a lot of experience with nginx, for many years and for some large projects, and i've tried to disable any form of caching, but the browser keeps caching the images despite the querystring.
Really really troublesome....

I am really impressed by humhub and i'd really like to use humhub for our social media projects; so i'll try to find a solution that works. Something that will work, of course, is saving the cropped images under a new name... Maybe i'll dig into that part of the code.

Martin
