### ISSUE TITLE
Google oAuth redirect URL no longer accepted by Google 

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2288]
v.1.2beta.1
Google OAuth login redirect URI is no longer recognized as a Authorized Redirect URI.  
I’ve tried https://bsmug.com/user/auth/external  and https://bsmug.com/index.php?r=user/auth/external  to no avail… 

Google keeps coming with: 
The redirect URI in the request, https://bsmug.com/user/auth/external?query=user%2Fauth%2Flogin&authclient=google&pjax=%23layout-content&=1487602378149, does not match the ones authorized for the OAuth client.

I did not change anything on the google console end.

**Comment by Felli** [comment]
This is an issue that deals with Pjax.

**Comment by martinbeek** [comment]
No @gigabytedevelopers , i run this on www.bsmug.com

**Comment by nminelle** [comment]
Same problem than @martinbeek 
Google URI redirect must be a constant.

**Comment by Felli** [comment]
@luke- would Facebook and the other Social Logins also have to follow the same method as Google's? As this also affects the other social logins in their own ways, mostly Live.
```
http://domain/path-to-humhub/user/auth/external?authclient=SOCIALNAME (With clean urls enabled)
http://domain/path-to-humhub/index.php?r=user%2Fauth%2Fexternal&authclient=SOCIALNAME (Without clean urls)
```

**Comment by dmitrydrynov** [comment]
the problem is relevant

**Comment by buddh4** [comment]
does it still occure with beta4 ?

**Comment by nminelle** [comment]
fixed in beta4 !
:)

**Comment by iadj** [comment]
@nminelle What should the redirect URIs be in beta4?

**Comment by Felli** [comment]
@iadj please read the [Docs](http://docs.humhub.org/admin-authentication.html#google).
