### ISSUE TITLE
CSS: word-break setting of [data-ui-markdown] does an ugly job

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2289]
v.1.2beta1  - UPDATED

Sentences are broken off in a strange fashion on HumHub. See image.
I tried to use "word-break: break-word" on paragraphs, but that is not working! 
It seems that the original text is formatted and broken off at time of saving the post.

This is the original text:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultrices, urna at commodo convallis, ipsum diam fermentum mauris, eu aliquet ante odio sollicitudin odio. Duis pharetra vehicula diam, eget condimentum ipsum gravida vitae."  

Watch the word fermentum in the screendump.

This is what HumHub makes of it (words are broken in the middle):
"`Lorem&nbsp;ipsum&nbsp;dolor&nbsp;sit&nbsp;amet,&nbsp;consectetur&nbsp;adipiscing&nbsp;elit.&nbsp;Nunc&nbsp;ultrices,&nbsp;urna&nbsp;at&nbsp;commodo&nbsp;convallis,&nbsp;ipsum&nbsp;diam&nbsp;fermentum&nbsp;mauris,&nbsp;eu&nbsp;aliquet&nbsp;ante&nbsp;odio&nbsp;sollicitudin&nbsp;odio.&nbsp;Duis&nbsp;pharetra&nbsp;vehicula&nbsp;diam,&nbsp;eget&nbsp;condimentum&nbsp;ipsum&nbsp;gravida&nbsp;vitae.`" 

![schermafbeelding 2017-02-20 om 16 22 56](https://cloud.githubusercontent.com/assets/6781157/23131038/dfb62144-f788-11e6-850c-45ed9c41b7fe.PNG)
#

**Comment by buddh4** [comment]
This is already fixed in the latest branch.
