### ISSUE TITLE
Auto update stream

### ISSUE THREAD

**Issue by krhebbar** [humhub/humhub#229]
Can we have auto update on the feed, if new post or comment is posted from other user. It automatically popups in the feed.

**Comment by codinglover** [comment]
nothing added like that yet :S

**Comment by buddha87** [comment]
We are currently rewriting our javascript frontend for version 1.2. We plan to provide a real time server communication for issues like that in a subsequent version.

**Comment by buddh4** [comment]
Will assamble some ideas at https://github.com/humhub/humhub/issues/3429
