### ISSUE TITLE
Cron - PHP Parse Error after updating to 1.2.0-beta1

### ISSUE THREAD

**Issue by clairedc** [humhub/humhub#2290]
Hi,
I have the following error after updating to 1.2.0-beta1 as I run my hourly or daily cronjobs :

Status: 500 Internal Server Error
X-Powered-By: PHP/5.4.45
Content-type: text/html

PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$''
in /home/conseilshi/hub-cctorcy/protected/humhub/components/queue/Queue.php:32
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

**Comment by buddh4** [comment]
You probably have to update to php 5.6 or later.

**Comment by clairedc** [comment]
The console says "PHP 5.4.45" but my hosting is in PHP 7.0.1. I tried to change to 5.6 but the error is the same.

**Comment by buddh4** [comment]
I'am pretty sure its a php version problem, make sure the right php version is used by apache.

**Comment by clairedc** [comment]
Humhub recognizes that it's the good version, isn't it ?
![image](https://cloud.githubusercontent.com/assets/3533230/23266378/eb6c0204-f9e7-11e6-85ba-4cdd22d67330.png)

**Comment by buddh4** [comment]
When does the error occure? If it's still the same error is there still the line "X-Powered-By: PHP/5.4.45" present in the error?

**Comment by clairedc** [comment]
The error occures when daily or hourly cron jobs are running ![image](https://cloud.githubusercontent.com/assets/3533230/23270684/f0eac7f8-f9f4-11e6-917a-183918536e7f.png)

**Comment by buddh4** [comment]
You cron jobs probably using another php version than your webserver.

**Comment by clairedc** [comment]
The Cron jobs use PHP 5.6. I don't think that the problem comes from PHP version.

**Comment by clairedc** [comment]
The Cron jobs use PHP 5.6. I don't think that the problem comes from PHP version.

**Comment by clairedc** [comment]
I tried with another Humhub installation & provider with PHP 7.0. All work fine with Humhub 1.1.2 and after updating, the same error occures. Any idea ? Because without cronjobs, Humhub is not so useful...

**Comment by buddh4** [comment]
It fails in the following line: https://github.com/humhub/humhub/blob/master/protected/humhub/components/queue/Queue.php#L32

which uses: `Queue::class`, this syntax is available since PHP 5.5 I think. In HumHub 1.1.2 the min php version was still 5.4 and we did not use the mentioned syntax.

In case this is not an PHP version issue, this error should occure almost everywhere in your installation. (creating posts/spaces/joining/...).

Can you reproduce the error message:

```
Status: 500 Internal Server Error
X-Powered-By: PHP/5.4.45
Content-type: text/html

PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$''
in /home/conseilshi/hub-cctorcy/protected/humhub/components/queue/Queue.php:32
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```
Since the version is mentioned in the error.

**Comment by clairedc** [comment]
You're right ! The pb came from the PHP version of my SSH... Thanks.

**Comment by bistanil98** [comment]
I face same problem and when i change the php version to 5.6 it works fine 
so please change php version then check
