### ISSUE TITLE
Clicking My Spaces button on mobile devices zooms in

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2294]
v.1.2.beta1
When the My Spaces button is clicked on iOS or android device, the current viewport changes and the page is zoomed-in. This is annoying because you'll have to zoom out again (pinch) to get the whole page in view. Probably caused by a JavaScript .focus() command (?).

See before/after pics.

![img_3156](https://cloud.githubusercontent.com/assets/6781157/23297591/64f08194-fa7a-11e6-932b-b32f1e876a75.PNG)
![img_3157](https://cloud.githubusercontent.com/assets/6781157/23297592/65285aa6-fa7a-11e6-9d2e-8f1199035229.PNG)

Plus a reminder that the viewport setting is totally overruled on iOS devices, making hubbub not fit for saving in the iOS desktop.

**Comment by Felli** [comment]
What version of android are you using because 4.4+ I've not seen any issues with auto zoom in, as for iOS I've not tried this yet.

**Comment by buddh4** [comment]
Can't not reproduce on Android either,.

**Comment by martinbeek** [comment]
I guess this is a iOS only problem then, because the scaling is successfully locked on android (viewport tag) and the viewport tag is failing on iOS. In retrospect, I guess that's where the problem lies.
The Sony android device I have (I'm an apple user really), is five years old, so that could be a version issue.

**Comment by buddh4** [comment]
Thanks for the info, I'll do some tests as soon as I have a iPhone device at hand.

**Comment by martinbeek** [comment]
Oh please check the infinite scroll and Load More button! See the issues posted on github.
Thanks!

**Comment by martinbeek** [comment]
SOLVED - see issue @2296
