### ISSUE TITLE
Interface Issue

### ISSUE THREAD

**Issue by ramalhoruben** [humhub/humhub#2295]
I think that scrolling through all available icons when trying to add an iframe widget is quite cumbersome. The combobox should allow the user to search from the list of icons, which is quite extensive, using the keyboard. Just a suggestion.

Thanks

**Comment by buddh4** [comment]
Thanks for the feedback. Note that all modules have an repository: https://github.com/humhub/humhub-modules-custom-pages. I'll add this feature request to the module.
