### ISSUE TITLE
SOLVED: Sorry, here I go again: iOS limitations

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2296]
v.1.2.beta.x
Infinite scroll, Load More button click and smooth scroll are not working on Safari on iOs devices.

Sometimes I can get infinite scroll to work by scrolling up and down many times, but usually I'm stuck at the bottom and the Load More button fails 9 times out of 10.
This also happens on the humhub community site. 
Google chrome works fine on iOS.

I find the number of issues with humhub on Safari alarming and it hampers me rolling this out for our intranet, since 75% of our users will use an iPhone to access the site. 

I guess the developers are more Andoid oriented; but need to take care that they don't alienate iOS users.

**Comment by buddh4** [comment]
There were major javascript changes in v1.2 it's possible that even smaller safari incompatibilities are leading those issue. Therefore it would be important for us to know if there ary any javascript errors in the developer console. Of course we'll investigate those issue before the stable release.

**Comment by martinbeek** [comment]
I found out, that when the phone is rotated to landscape mode, infinite scroll works fine in Safari - so I guess it's a computational issue (pixels from bottom, or other infinite scroll calculation).

**Comment by martinbeek** [comment]
SOLVED!  
Also see issue 2270.

Infinite scroll, as used in humhub (./protected/humhub/modules/stream/resources/js/humhub.stream.js) is not working on iOS devices running iOS 10.1 or higher. Apple is no longer returning reliable window.scrollTop() and  window.height() variables. This has to do with their "view" of how the viewport is implemented during scroll. 

I have amended the infinite scroll method (line 893 of ./protected/humhub/modules/stream/resources/js/humhub.stream.js) with the following. Since the viewport information is not reliable on mobile devices, i am using the bottom of the wallStream element as a reference. 

```
/* original
            var $window = $(window);
            var scrollTop = $window.scrollTop();
            var windowHeight = $window.height();
            if(scrollTop === ($(document).height() - $window.height())) {
                if(stream && !stream.loading && !stream.isShowSingleEntry() && !stream.lastEntryLoaded) {
                    stream.loadEntries({loader: true});
                }
            }
*/

/* replacement by MB */

            var $window = $(window);
            var windowHeight = $window.height();
            var windowBottom = $window.scrollTop() + windowHeight;
            var elementBottom = $('#wallStream').offset().top  + $('#wallStream').outerHeight();
            var remaining = elementBottom - windowBottom;
            if (remaining <= 10) {
                if(stream && !stream.loading && !stream.isShowSingleEntry() && !stream.lastEntryLoaded) {
                    $('#btn-load-more').hide();
                    setTimeout( function() { stream.loadEntries({loader: true}); });
                }
            }
```

Tested on several mobile devices and desktop browsers.
This solves the problem of failing infinite scroll on iOS devices and some older Android devices.
