### ISSUE TITLE
Error while uplading image in Post EDIT mode + solution

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2297]
v1.2.beta.x 
When editing an existing post, and adding (uploading) a picture, i get the following error:

ERROR  Fri, 24 Feb 2017 19:49:00 +0100  yii\base\ErrorException:2
exception 'yii\base\ErrorException' with message 'finfo_file(/tmp/phpuEdEMf): failed to open stream: No such file or directory' in /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:148 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'finfo_file(/tmp...', '/var/www/bsmug....', 148, Array) #1 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(148): finfo_file(Resource id #11, '/tmp/phpuEdEMf') #2 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/validators/FileValidator.php(357): yii\helpers\BaseFileHelper::getMimeType('/tmp/phpuEdEMf', NULL, false) #3 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/validators/FileValidator.php(251): yii\validators\FileValidator->validateExtension(Object(yii\web\UploadedFile)) #4 /var/www/bsmug.com/httpdocs/protected/humhub/modules/file/validators/FileValidator.php(50): yii\validators\FileValidator->validateValue(Object(yii\web\UploadedFile)) #5 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/validators/FileValidator.php(215): humhub\modules\file\validators\FileValidator->validateValue(Object(yii\web\UploadedFile)) #6 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/validators/Validator.php(267): yii\validators\FileValidator->validateAttribute(Object(humhub\modules\file\models\FileUpload), 'uploadedFile') #7 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/base/Model.php(358): yii\validators\Validator->validateAttributes(Object(humhub\modules\file\models\FileUpload), Array) #8 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(564): yii\base\Model->validate(NULL) #9 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(637): yii\db\ActiveRecord->update(true, NULL) #10 /var/www/bsmug.com/httpdocs/protected/humhub/modules/file/components/FileManager.php(65): yii\db\BaseActiveRecord->save() #11 /var/www/bsmug.com/httpdocs/protected/humhub/modules/file/actions/UploadAction.php(86): humhub\modules\file\components\FileManager->attach(Object(humhub\modules\file\models\FileUpload)) #12 /var/www/bsmug.com/httpdocs/protected/humhub/modules/file/actions/UploadAction.php(65): humhub\modules\file\actions\UploadAction->handleFileUpload(Object(yii\web\UploadedFile)) #13 [internal function]: humhub\modules\file\actions\UploadAction->run() #14 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #15 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array) #16 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('upload', Array) #17 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('file/file/uploa...', Array) #18 /var/www/bsmug.com/httpdocs/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #19 /var/www/bsmug.com/httpdocs/index.php(25): yii\base\Application->run() #20 {main}

**Comment by martinbeek** [comment]
SOLVED! 
Reason of error: mimetype was requested twice, while second time already known en temp upload file was already gone. 

Changed:
in ./protected/vendor/yiisoft/yii2/validators/FileValidator.php  check if mimetype is already known

From row 356 change:
```
            $mimeType = FileHelper::getMimeType($file->tempName, null, false);
            if ($mimeType === null) {
                return false;
            }
``` 

Into:
```
			if ($file->type == "") {
            	$mimeType = FileHelper::getMimeType($file->tempName, null, false);
            	if ($mimeType === null) {
                	return false;
            	}
			} else 
				$mimeType=$file->type;

```

Martin

**Comment by luke-** [comment]
Can you please provide steps to reproduce?

**Comment by martinbeek** [comment]
I am sorry for the hassle and happy for us all; but the problem seems to be solved or only seems a problem in my installation. I can't reproduce it anymore so I'm closing this issue.

**Comment by luke-** [comment]
No problem, my colleague saw this problem also once - but we can't reproduce...

**Comment by Felli** [comment]
I think it is a server related issue when installing Humhub, I know something like this happened with my CloudLinux server.
