### ISSUE TITLE
LinkPreview: previous posted link is copied to each new post

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2298]
v.1.2.beta2
If i post a message with an URL AND with the Link Preview module enabled, each following post will get the url preview attached too! 

Example: posted a link with no text (only url). Next posted a message with only "test".

![schermafbeelding 2017-02-24 om 19 58 20](https://cloud.githubusercontent.com/assets/6781157/23316712/d302f83c-facb-11e6-8252-d3cbaf75d45e.PNG)

**Comment by buddh4** [comment]
Thanks, should be fixed in the latest version.

**Comment by martinbeek** [comment]
I have installed the version of today; which has this problem.

**Comment by buddh4** [comment]
There should be another verion 1.5 available, which was recently uploaded.

**Comment by martinbeek** [comment]
Ok! Great service! Updating now...
