### ISSUE TITLE
LDAP users with the same email address dangerously matched

### ISSUE THREAD

**Issue by cperreault** [humhub/humhub#2299]
I tested on v1.1.2 and this problem is still there with LDAP authentication. If two or multiple users have the same email address (it can happen for pertinent reasons!), then one logs in, it can be incorrectly matched with another entry of the user table having the same email address. This persons then takes over the other one's identity/session. This appears to be a dangerous behavior. HumHub should not presume that multiple accounts having the same email address are for the same person.

I can contribute to develop a fix for that. I would appreciate any help to point me where to dive in the code. Thanks.

**Comment by luke-** [comment]
We lookup the username by the given e-mail address and authenticate with that username and given password.

Lookup username by e-mail: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/authclient/ZendLdapClient.php#L225-L231

Login with the username + given password:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/authclient/ZendLdapClient.php#L234

We also only use the first e-mail address found in ldap. 
Alternatively you can specify another unique e-mail attribute via AuthClient user attribute map or we could add an optional flag to prohibit login by e-mail for LDAP users.

**Comment by cperreault** [comment]
Thanks a lot for the reference into the code! I should be able to dig into in the next month. Besides, why did you close this issue if it was not fixed? I would be happy to contribute to it.
