### ISSUE TITLE
Play animated GIFs in the stream

### ISSUE THREAD

**Issue by gallandp** [humhub/humhub#230]
At the moment, animated GIFs are shown as a static jpeg in the stream of a space. Do you think it's possible to play them directly without open the lightbox?

**Comment by tatianaJacques** [comment]
Hello, 

I want to do the same but when I try I have the message that my command is not good. Can you help me, I don't understand what I have to do. I don't know how Image Magick works. 

Thank you a lot.

**Comment by buddha87** [comment]
You have to install imagemagick and point to your executable.
Here is an example of your image magic command input:

/usr/bin/convert
