### ISSUE TITLE
Notifications in 1.2 Beta 1+2 don´t work for me

### ISSUE THREAD

**Issue by Twilek-de** [humhub/humhub#2301]
I have upgraded an older Humhub Installation first to v1.2 beta 1, then to beta 2. In both installations the notifications are not formatted and look wrong. I have enabled modules Custom Pages, Mail, Polls, Tasks, Updater and Wiki.
![2017-02-26 08_58_18-design - administration - iron](https://cloud.githubusercontent.com/assets/8283684/23338137/62dd43cc-fc02-11e6-9ae3-1aeac26a56c1.png)
![2017-02-26 08_58_35- iron](https://cloud.githubusercontent.com/assets/8283684/23338138/62e4f176-fc02-11e6-93fc-494746c23e86.png)

**Comment by buddh4** [comment]
Any errors under "Administration -> Information -> Logging" or in the developer console of your browser?

**Comment by Twilek-de** [comment]
Nothing in the Humhub Log (I have cleared it and opened hte messages and no new entries in the log were genrated). I do not find any errors in the Firefox developers console. Any pointers what I should be looking for?

**Comment by Twilek-de** [comment]
Tried Chrome Console. Didn´t show any errors...

**Comment by buddh4** [comment]
Check the server response after opening the notification dropdown. 
Which kind of notifications are shown in your notification overview, perhaps they are from an old module version. (Perhaps task module?)
Have you updated all your modules?
Have you installed any non official modules?
Are you using a custom theme?

**Comment by Twilek-de** [comment]
What do you mean by server response?
All modules are up to date and from the market place. The notifications are for new posts or answered posts. There are old notifications but they do not show as well as the new ones.
I use the official theme with some colors changed (but changing back to standart theme doesn´t help).
The problem is that the notifications are there, they are just not formatted at all. You can select stuff in the "empty" notification drop down...
![2017-02-28 18_23_13- iron](https://cloud.githubusercontent.com/assets/8283684/23416484/4219bc96-fde3-11e6-971a-de645c9bb38a.png)

**Comment by Twilek-de** [comment]
I completely emptied the notification table in the database to get only new notifications. Then I created a Test user and followed it. This notification worked. When the Test user wrote something in my post, that notification was borked again

**Comment by Twilek-de** [comment]
Could it be an issue with "Custom Pages" which I use quite a lot. I would love to deactivate it to see what happens, but I do not want to lose all my content.

**Comment by Twilek-de** [comment]
This is getting weird. Suddenly one notification is formatted right and the next fails again.... I cannot see what is different for the one that got through...

![2017-03-02 08_36_32](https://cloud.githubusercontent.com/assets/8283684/23497536/ca21dc04-ff23-11e6-9d91-7613ab1b9f62.png)
![2017-03-02 08_37_36](https://cloud.githubusercontent.com/assets/8283684/23497537/ca22e306-ff23-11e6-9362-b338fdca7298.png)

**Comment by Twilek-de** [comment]
I think I solved it. The updater seemed to have left over some files from the old installation. I did a recursive diff of a fresh unpacked humhub and my installation and deleted the old stuff. Now it seems to work again!
