### ISSUE TITLE
Solution for playing embedded Youtube video's inline on iOS devices

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2303]
If you embed a youtube video in your humhub post, iPhones and iPads will open the video fullscreen and will not play the video inline within the margins of your post. This is because the embed code returned by Youtube's oEmbed json is not exactly what we want. First, the "allowfullscreen" parameter has to be removed (only impacts ios devices), further the option "playsinline" and "webkit-playsinline" need to be added to both the iframe code and the url. Last, the option "feature=oembed" has to be removed from the embed url. 
If that all has been done, your youtube video's play beautifully inline, in your post! 
Mark Zuckerberg will be jealous of HumHub now... ;-) 

To enable this feature, the following lines have to be added to the file ./protected/humhub/models/UrlOembed.php, inserting on row 115 (before "if (isset ...").

```
                    // MB prevent auto fullscreen and enable inline play on iOS devices
                    $data['html'] = str_ireplace("allowfullscreen", " playsinline=1 webkit-playsinline=1", $data['html']);
                    $data['html'] = str_ireplace("?feature=oembed", "?autoplay=0&playsinline=1&webkit-playsinline=1", $data['html']);
                    //end MB
                              
```
 

Cheers!

**Comment by luke-** [comment]
Hmmm, i'm not a big fan of such hacks, also we haven't currently any IOS device to test.

Maybe this will be fixed by Youtube if this problem also appears on FB?

**Comment by martinbeek** [comment]
Hello Luke.

It's not really a hack, its's suggested by both apple and youtube to do it this way; using nocookie.youtube.com 

I'm an Apple developer and my speciality is devloping web apps and this is the way we do it for many years already.

But no problem; i've changed the code in my installation.

It's a pity that you not develop and test on the iOS platform. Its the number two platform in the world (safari) with billions of users.
But, hey - i'll do the testing on iOS for you and will continue to make suggestions  :-)

By the way... using the nocookie youtube url also eliminates google tracking cookies and i like that ;-)

Martin

**Comment by martinbeek** [comment]
Oh, i forgot to enlight you on the nocookie principle :-(

The youtube movies will autoplay on iOS web apps! That is very annoying, and can only be stopped by using nocookie.youtube.com as movie URL.

I forgot to mention that.

This in combination with the "hack" is the only way to play movies inline on an ios device, while disabling autoplay.

**Comment by martinbeek** [comment]
But why not always add the playsinline comamndline options? What harm can it do? It's not such a bad "hack"..?

**Comment by luke-** [comment]
Ok, we can add this to the core - but we need to make sure that this string replace only affects Youtube responses?

Can you submit a PR?
