### ISSUE TITLE
Double "Read more" on post : Undefined link + Read more, after upgrading to 1.2.0-beta2

### ISSUE THREAD

**Issue by JimmyJanisson** [humhub/humhub#2305]
Hi,

We got a selfhosted humhub that we upgrade this weekend from 1.1.0-beta1 to 1.2.0-beta2 with the Humhub Updater plugin without problems.

The only thing, is since the update, too long posts that requires "read more" links doesn't work as expected, we have : 
- an "undefined" link, when we click on it : it shows the real "read more" link, then it stays and can be re-click to hide the "read more" button
- the  real "read more" link, when we click on it : it show the entire post and disappear (leaving the "undefined" button in his state)

Only long posts have this issue, no short one neither comments. 

The posts are limited by an inline style rule defining max-height 310px in 2 containers.

I tried to show that in that screenshot : 
![screenshot1](https://cloud.githubusercontent.com/assets/20086774/23359344/1fa51910-fce6-11e6-9da7-0adf413b316a.png)

And the one after clicking on the "undefined" link : 
![screenshot2](https://cloud.githubusercontent.com/assets/20086774/23359347/215ec86e-fce6-11e6-93ec-9b8a7bfd9104.png)

I was unable to find a reference searching in source code, and have seen nothing on respectives issues pages of my plugins, neither here. 

I put you here our plugins list : 
- Birthday Widget 1.0.8
- Breaking News 1.0.2
- Calendar - Beta 0.4.1
- Custom Pages 0.7.3
- Most Active Users Widget 0.2.5
- Polls Activé 0.9.7
- Report Content 0.2.3
- Social Share 1.0.1
- Humhub Updater 2.0.6
- Wiki 1.1.6 

By the way, thank you for your work on that great tool.

**EDIT :** we also have this type of errors in our logs : 
 Warning  Mon, 27 Feb 2017 16:19:13 +0100  yii\i18n\I18N::format
Formatting message for language 'fr' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ILLEGAL_ARGUMENT_ERROR. The message being formatted was: Ce champ de téléchargement ne permet qu'un maximum de {n, pluriel, = 1 {# fichier} sur {# fichiers}}..

**Comment by buddh4** [comment]
Have you overwritten the following view in your theme: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/post/widgets/views/wallEntry.php

If yes, align this file to the v1.2 version

**Comment by JimmyJanisson** [comment]
No this is the Default Theme and i haven't modify any file manually in this version.
But i conceed

**Comment by JimmyJanisson** [comment]
No, this is the default theme.
But when i was in 1.1.0-beta1, i modified that view just to change the `2000px` in `auto` to solve the long post bug, but this file contained much more code than now : 

```php
/var/www/humhub/protected/humhub/modules/post/widgets/views/wallEntry.php:
48 if (_state == "down") {
49
50: $('#post-content-' + post_id).css('max-height', '2000px');
```

It was the only change manually made on this HumHub installation, the update overwrite correctly that file : now it's the same than this repository.

**Comment by buddh4** [comment]
which browser are you using?

**Comment by JimmyJanisson** [comment]
Firefox, but Chrome and IE have the same behaviour. 
Desktop and mobiles versions. 
I think it's a server-side problem.

I have detected two others bugs since my upgrade, i referenced here :

**Comment by buddh4** [comment]
I'll try to reproduce this issue.

**Comment by buddh4** [comment]
Are you running your site in production mode or in debugging mode? Try clearing your assets "Administration -> Settigns -> Advanced -> Caching -> Flush Caches.

I assume somehow you have an old versoin of the stream js module loaded.

**Comment by Felli** [comment]
I can confirm this does happen, and after flushing cache from the admin panel, it would seem that browser cache overrules the website cache.

**Comment by JimmyJanisson** [comment]
Yes it works ! Thanks for your quick answer. I'll mind to empty server cache after next update.
It also solved another problem I got since the upgrade, which is referenced in this [issue](https://github.com/humhub/humhub/issues/2304)
