### ISSUE TITLE
Cannot invite users to pre-existing space 1.2.0-beta.2

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub#2308]
After an update, I can no longer invite existing users to an existing space I get "an unexpected error occurred while loading the search result."

**Comment by rapidpage** [comment]
also, when "assigning" to a user it gives the same error

**Comment by RaulMcKay** [comment]
Moreover, adding users to groups give the same error. It's connected with my issue.
Please check your logs list and verify that they are similar to mine https://github.com/humhub/humhub/issues/2304

**Comment by rapidpage** [comment]
yes, it is the same...

**Comment by RaulMcKay** [comment]
Solution from #2304 is working here either, so issue could be closed.
