### ISSUE TITLE
Pinned post appears twice on stream

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2312]
v.1.2.beta2
Pinned posts seem to appear again after stream loads more posts. See picture of pinned post in the middle of the stream.
![img_3190](https://cloud.githubusercontent.com/assets/6781157/23441490/ed56306e-fe22-11e6-9535-eb5f1dc551cf.PNG)

**Comment by Felli** [comment]
Might be a loading issue for iOS mobile as I've not seen this in Android 4.4+.

**Comment by martinbeek** [comment]
This is not on inkt a phone, also on all browsers. Inhalen a mac and a nummer of Dell laptops with different browsers, all showing this.
Also on clean 1.2beta2 Install - so please take a look again.

**Comment by buddh4** [comment]
Could you provide a guide for reproducing the issue?
Somehting like: 1. Create a Space 2. Create x posts 3. Pin post 3 etc..

Haven't seen such an issue yet.

**Comment by Felli** [comment]
When you load the page drop down to the bottom of the page and quickly push the Load More button and it should load in the Pinned post..

**Comment by martinbeek** [comment]
Go to a stream width a pinned post
scroll down until the load more (infinite load) fires
And voila ...
