### ISSUE TITLE
Private posts visible for new user

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2313]
v.1.2.brta2
I was sent the following screendump by a concerned member.
After login, he can see posts that are flagged Private on the stream of another user!

![img_3183](https://cloud.githubusercontent.com/assets/6781157/23441582/61e1ed7e-fe23-11e6-9e6d-95cd4fd70769.PNG)

**Comment by buddh4** [comment]
As discussed in the community this was a misunderstanding regarding private posts within a space.
