### ISSUE TITLE
Steam not initialized error

### ISSUE THREAD

**Issue by RaulMcKay** [humhub/humhub#2314]
I noticed error connected with image file in comments in posts. When I add comment with image (I tested png file format), I got an error "Steam not initialized" on steam where this comment was posted. For example: If I comment "Hello" with picture on steam named "Test" then this occur a problem and I can't see nothing except "Steam not initialized".

In logging I found:
"yii\base\ErrorException:64
exception 'yii\base\ErrorException' with message 'Cannot use yii\helpers\Html as Html because the name is already in use' in /home/users/futeral/public_html/fut.edu.pl/futurysta/protected/humhub/libs/Markdown.php:6 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}"

Humhub 1.20 beta2

**Comment by buddh4** [comment]
Please check your logs "Administration -> Information -> Logging" if there is an error right before this error.

**Comment by RaulMcKay** [comment]
$_GET = [ 'mode' => 'normal' 'StreamQuery' => [ 'sort' => 'c' 'from' => '0' 'limit' => '8' 'suppressionsOnly' => 'false' ] ] $_SERVER = [ '

[...] - cut server information


 'mode=normal&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=8&StreamQuery%5BsuppressionsOnly%5D=false' 'REDIRECT_URL' => '/dashboard/dashboard/stream' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'mode=normal&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=8&StreamQuery%5BsuppressionsOnly%5D=false' 'REQUEST_URI' => '/dashboard/dashboard/stream?mode=normal&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=8&StreamQuery%5BsuppressionsOnly%5D=false' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1488232646.308 'REQUEST_TIME' => 1488232646 'argv' => [ 0 => 'mode=normal&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=8&StreamQuery%5Bsu

**Comment by RaulMcKay** [comment]
@buddh4 
Thanks, it works!

It was related with any file format whick appear on your stream (directly in post or in comments). I don't use Wiki.
