### ISSUE TITLE
Humhub installation humhub/protected/vendor/autoload.php is missing

### ISSUE THREAD

**Issue by petrk94** [humhub/humhub#2315]
Hello, 

I have tried to run humhub, again, on my uberspace and the uberspace team told me that there is a file missed called autoload.php

[Wed Mar 01 09:27:04 2017] [warn] [client 176.199.140.49] mod_fcgid: stderr: PHP Warning:  require(/var/www/virtual/xxx/html/humhub/protected/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/virtual/xxx/html/humhub/index.php on line 13
[Wed Mar 01 09:27:04 2017] [warn] [client 176.199.140.49] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/virtual/xxx/html/humhub/protected/vendor/autoload.php' (include_path='.:/package/host/localhost/php-5.6.21/lib/php') in /var/www/virtual/xxx/html/humhub/index.php on line 13

Please tell me why this is gone and which version I can try again?
Thanks

**Comment by cebe** [comment]
you need to install dependencies via composer.

**Comment by petrk94** [comment]
@cebe 
thanks for your help I could solve that by doing:

```
wget https://getcomposer.org/installer
php installer
php composer.phar global require "fxp/composer-asset-plugin:~1.1.1"
```

But now I have the problem, that the icons in the top menu are double:
![humhub](https://cloud.githubusercontent.com/assets/19719052/23484842/f7540dd2-fed8-11e6-8a37-3e626e636444.PNG)

Do you know why that happened?

**Comment by buddh4** [comment]
please see https://github.com/humhub/humhub/issues/2253

**Comment by petrk94** [comment]
Just for information, Im facing the issue with the latest version again, that autoload.php is missing after download of the git hub release as well from the website.

**Comment by buddh4** [comment]
Did you follow [this](http://docs.humhub.org/dev-environment.html#get-humhub) isntallation guide including the `composer/install`?
