### ISSUE TITLE
Which chmod right permission is right?

### ISSUE THREAD

**Issue by petrk94** [humhub/humhub#2320]
Hello,
Im looking currently for the right permission set for the folders which are listed in the installation document here: https://www.humhub.org/docs/guide-admin-installation.html

Can you tell me which one is right for a server?
For my tests I have used chmod 777 %folder%/

**Comment by Felli** [comment]
If you follow the [docs](http://docs.humhub.org/admin-installation.html#file-permissions) to an exact you'll be able to find what you're looking for. :+1:

**Comment by petrk94** [comment]
@Felli this is not the right answer:

> Make the following directories/files writable by the webserver

Does it mean 777 is right or not?
For a productive usage it should been save enough

**Comment by Felli** [comment]
777 does work but isn't always a good thing, I'd suggest 755.

**Comment by petrk94** [comment]
Thats what I meant, so 755 is better.

**Comment by Felli** [comment]
In some case yes. :+1:

**Comment by jeremiahtenbrink** [comment]
What user would humhub be considered in a Unix environment?

**Comment by Felli** [comment]
Hmm... That would be a good question.
Something like this? (I've never had to use a Unix environment and the below is an example from [here](https://www.tutorialspoint.com/unix/unix-file-permission.htm))
```
$ chmod 755 testfile
$ls -l testfile
-rwxr-xr-x  1 amrood   users 1024  Nov 2 00:10  testfile
$chmod 743 testfile
$ls -l testfile
-rwxr---wx  1 amrood   users 1024  Nov 2 00:10  testfile
$chmod 043 testfile
$ls -l testfile
----r---wx  1 amrood   users 1024  Nov 2 00:10  testfile
```

**Comment by jeremiahtenbrink** [comment]
I was just curious. You didn't need to go looking around for the answer if you didn't know of the top of your head. Just wanted to clarify some things up in case others are reading this post. 

So after looking around, it looks like the default settings for ubuntu apache server is to run the scripts as www-data. So in a production environment I wouldn't think it smart to give the user www-data write permissions to anything except folders where it needs to do such things such as save pictures. 

I'm not the best person to be asking about security protocols but this can be accomplished in a number of ways that I can think of. You use the chown command and make the folder owned by www-data or you could add www-data to a group and give group write permissions for the folder. I would probably go with adding www-data to a group. As for users who come into the system. I would think all they would need is x permissions. 

If anyone else has any more insight and would like to share I would be interested to hear what you have to say. 

If your curious and want to know which user your php scripts are running under there are php commands that will echo out the user info for the server. I don't know what these are so you would have to Google them to find out.

**Comment by cebe** [comment]
Here is what I am using on production servers:

Webserver runs as user `www-data` with group `www-data`, files are owned by `humhub` or other user, does not matter for the following:

```
cd humhub
chgrp www-data  assets protected/runtime/ protected/modules/ protected/config/ uploads uploads/*
chmod g+w  assets protected/runtime/ protected/modules/ protected/config/ uploads uploads/*
```

**Comment by jeremiahtenbrink** [comment]
Thanks for the insight. That helps alot. Just so everyone is clear. He gave ownership of the folders listed in the chgrp command to the user which humhub runs under. Normally the user www-data. Then he gave those folders write permissions to the group www-data group. 

So the chmod command would be 775 for those folders. And 755 for all others.
