### ISSUE TITLE
Better Search Bar

### ISSUE THREAD

**Issue by gigabytedevelopers** [humhub/humhub#2321]
This is not actually an issue but rather an enhancement idea/suggestion.. Won't it feel better if the search button on the second navbar is an input/form field and not a button whereby there is an autocomplete feature and search suggestions that can be made in real-time as the user is typing into the box. Imagine it and see what I mean, just like Facebook's search bar, I really think it would be nice.

**Comment by devcline** [comment]
vote up !

- autocomplete 
- fuzzy search
- when active is large, when inactive its just icon

**Comment by luke-** [comment]
Duplicate #1839
