### ISSUE TITLE
Many 404 errors on mobile devices: .map files missing

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2326]
v.1.2beta
When I finally connected a laptop to my iPhone to do some JavaScript debugging on Safari, I was alarmed by the huge number of errors that humhub reports on iOS. My main concern are many 404 errors complaining that .map files could not be loaded. 
I know that this also happens with bootstrap sites and that you can switch off the use of map files in code, but that is way over my head.
Probably happens on Android too.

**Comment by buddh4** [comment]
Are you running in production mode and can you make a screenshot of the errors?

**Comment by martinbeek** [comment]
Yep thanks!! The debug mode did it ;-) switching to production removed the errors.

Did find some errors by the way in the theme.css though;  double double-quotes (;;)  and " !important" after the closing ";" tag - e.g.  "; !important"
