### ISSUE TITLE
Statistics input field in admin is obsolete, tracking not working 

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2327]
The Statistics input field in admin has lost it’s function. Google analytics or other visitor tracking codes will no longer work as expected, because humhub pages are loaded through Ajax. Only the first hit to the site will be registered, but consecutive pages will not trigger the tracking code and therefore will not show up in the statistics. 
I’ve solved this problem some time ago for other dynamically loading webpages. 
The way to implement Google analytics is described in [this URL](https://mjau-mjau.com/blog/ajax-universal-analytics/) . It needs part of the code to be triggered in the stream-loading mechanism - which would be stream.js on humhub, in the part that takes care of the page load and the part that takes care of the infinite load. 
The “Statistics” input field is obsolete and could be changed for a “google analytics ID, where humhub will insert the right Google tracking codes in the right places.

**Comment by luke-** [comment]
We could add another field called "Ajax tracking code" in _Administration -> Settings -> Advanced -> Statistics_.

This code could be executed on each PJAX page load.

Could this be a solution for your problem?

**Comment by martinbeek** [comment]
Absolutely. I managed to implement it in the following way, that works.
We're are using Piwik instead of Google analytics but that is roughly the same. 

There are there places where something I'd happening. 

-1 put the standard tracking code as high as possible in the code, which should be main.php
E.g.:
```
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//{$PIWIK_URL}/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', {$IDSITE}]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
```

-2 Start an interval timer to check URL changes and trigger the "partial code". There currently is no cross-browser DOM event that facilitates this.
E.g. at the bottom of main.php:

```
var oldLocation = location.href;
setInterval(function() {
if(location.href != oldLocation) {
// Trigger partial tracking code
_paq.push(['setCustomUrl', location.href]);
_paq.push(['setDocumentTitle', document.title]);
_paq.push(['trackPageView']);
_paq.push(['deleteCustomVariables', 'page']);
_paq.push(['setGenerationTimeMs', 0]);
_paq.push(['trackPageView']);
oldLocation = location.href
}
}, 2000);



```

-3 trigger the same partial code in humhub.stream.js around the "load more" (infinite load) part.


This is the way I got it working. The "triggered part" usually needs a document URL and title.

Martin.

**Comment by martinbeek** [comment]
Since the last step is only for measuring the online time, that part could be skipped which means that the other two parts can probably be inserted in the current way? As one code block in the Admin->Advanced -> Statistics input? Will that work?

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/blob/master/protected/humhub/docs/guide/admin/advanced-configuration.md#statisticstracking

This should solve your issue.
