### ISSUE TITLE
errors messages on invite (email or user)

### ISSUE THREAD

**Issue by brucelane** [humhub/humhub#2333]
see these screenshots
![hhinvit 2](https://cloud.githubusercontent.com/assets/138158/23575182/5d376bc4-0089-11e7-8d52-0a5116391e1b.jpg)
![hhinvit2](https://cloud.githubusercontent.com/assets/138158/23575181/5d37751a-0089-11e7-966f-8d4bd985330f.jpg)

**Comment by Felli** [comment]
Is this relevant to #2316 by any chance?

**Comment by brucelane** [comment]
it's a brand new install with new users, so I guess it's not the same issue

**Comment by webncut** [comment]
So maybe this helps?
https://github.com/humhub/humhub/issues/2304

**Comment by buddh4** [comment]
Is this still an issue with beta4?

**Comment by brucelane** [comment]
thank you
