### ISSUE TITLE
closed tasks don't display correctly

### ISSUE THREAD

**Issue by brucelane** [humhub/humhub#2334]
see screencap
![hhtask 1](https://cloud.githubusercontent.com/assets/138158/23575207/dce578ca-0089-11e7-8471-7faf4f737fc8.jpg)

**Comment by stothew** [comment]
i already fixed this but pull request is not accepted yet.

see:

[https://github.com/humhub/humhub-modules-tasks/issues/42](https://github.com/humhub/humhub-modules-tasks/issues/42)

hope it helps

**Comment by brucelane** [comment]
great, thank you @stothew !

**Comment by brucelane** [comment]
fixed by https://github.com/humhub/humhub-modules-tasks/pull/43
