### ISSUE TITLE
Number of users online not working

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2335]
The "online right now" display is not working. 
I'm logged in on three different accounts from three different ip addresses...

![image](https://cloud.githubusercontent.com/assets/6781157/23583113/5146b092-013b-11e7-9c4b-cc1230cb8dfb.jpeg)

**Comment by Felli** [comment]
Hmm... Are all three accounts a part of custom groups or default group? As I've only seen this happen when a member isn't in a group. Other than that it's working on my test environment. Also, could you check the admin panel -> information -> logging as well as the browser console for errors?

**Comment by martinbeek** [comment]
Hello Felli.

The users are in the group Users (the standard group that humhub creates).
No errors.
Is there a minimal time or maximum (expiry) time for users to show up?
Thanks.

**Comment by Felli** [comment]
Hmm, what type of server are you using, and what version of Humhub are you using?
