### ISSUE TITLE
Username sometimes displayed as a variable "displayNames"

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2336]
I see it on my v1.2beta2 install but also on this site; sometimes a user is displayed without a name, but as displayed as in the attached image.

![image](https://cloud.githubusercontent.com/assets/6781157/23583140/01fb6f7c-013c-11e7-98f1-b4e1e573fbe2.jpeg)

**Comment by buddh4** [comment]
What kind of notification is this, I assume a comment?

**Comment by martinbeek** [comment]
Yes indeed! It's a comment.
