### ISSUE TITLE
Link list module, parts not translated

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2337]
Module v.0.5.6
Humhub v1.2.beta2

Some screens and input elements are not translated, at least not in Dutch.

![img_3210](https://cloud.githubusercontent.com/assets/6781157/23599728/0ba2cc66-0243-11e7-97f7-a329279f7b18.JPG)
![img_3211](https://cloud.githubusercontent.com/assets/6781157/23599729/0bbeb188-0243-11e7-9859-64389adcd7bc.JPG)

**Comment by buddh4** [comment]
Have checked if those labels are already translated @ humhub translation? https://github.com/humhub/humhub-modules-linklist/blob/master/models/Category.php#L76
