### ISSUE TITLE
To improve set default language for guest users

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2339]
Default language is wrong for any new users on login page now.

Because the language determitate by browser user-preferred language. For me 'en' always instead default `ru` by setting from database.

IMHO [this code](https://github.com/humhub/humhub/blob/master/protected/humhub/components/i18n/I18N.php#L80-L83)
```php
            if ($language === null) {
                // Use browser preferred language
                $language = Yii::$app->request->getPreferredLanguage(array_keys($this->getAllowedLanguages()));
            }
```

should be replaced to 

```php
            if ($language === null) {
                $language = Yii::$app->settings->get('defaultLanguage');
                if ($language === null) {
                    // Use browser preferred language
                    $language = Yii::$app->request->getPreferredLanguage(array_keys($this->getAllowedLanguages()));
                }
            }
```

I can sent PR

ref #1409

**Comment by luke-** [comment]
Hmm, in this case the browser language will be never used if a defaultLanguage is set.

- Maybe we can use this http://www.yiiframework.com/doc-2.0/yii-web-request.html#getAcceptableLanguages()-detail method and use "defaultLanguage" when it's within this "acceptableLanguages"

- Or we use your snippet optionally with a configuration flag.

**Comment by githubjeka** [comment]
> Humhub perfect for individual:
> - Social Intranets
> - Enterprise Social Networks
> - Private Social Networks

I think soo and because administrator better know what language need to used by users.
Now I get english always although the browser is russian, the country is russian, everything is russian :(

**Comment by githubjeka** [comment]
For me `Yii::$app->request->getAcceptableLanguages` returns `"en-US"` instead  expected `"ru"` :/

**Comment by hiltonkBR** [comment]
> Default language is wrong for any new users on login page now.
> 
> Because the language determitate by browser user-preferred language. For me 'en' always instead default `ru` by setting from database.
> 
> IMHO [this code](https://github.com/humhub/humhub/blob/master/protected/humhub/components/i18n/I18N.php#L80-L83)
> 
> ```
>             if ($language === null) {
>                 // Use browser preferred language
>                 $language = Yii::$app->request->getPreferredLanguage(array_keys($this->getAllowedLanguages()));
>             }
> ```
> 
> should be replaced to
> 
> ```
>             if ($language === null) {
>                 $language = Yii::$app->settings->get('defaultLanguage');
>                 if ($language === null) {
>                     // Use browser preferred language
>                     $language = Yii::$app->request->getPreferredLanguage(array_keys($this->getAllowedLanguages()));
>                 }
>             }
> ```
> 
> I can sent PR
> 
> ref #1409

It would be really cool if they implement that.

**Comment by luke-** [comment]
@hiltonkBR Since always/mostly a default language is set, this would never use the browser language?

**Comment by hiltonkBR** [comment]
@luke- Hi, I had to set my language as the only "allowedLanguages" as documented on https://docs.humhub.org/docs/admin/translations to not load the browser language, just set default language on the configuration humhub page doesn't  work.

**Comment by luke-** [comment]
If you only want to use the default language, that would be a solution, too.

**Comment by ushbyorg** [comment]
> @luke- Hi, I had to set my language as the only "allowedLanguages" as documented on https://docs.humhub.org/docs/admin/translations to not load the browser language, just set default language on the configuration humhub page doesn't work.

You made a new config file or edited a current one ? I don't know which config to put this code at ..

**Comment by ArchBlood** [comment]
Personally speaking, this should be extending more than just for Guests now, as of now when notifications are sent out they're not sent in the user's preferred language but the platform's even when the user sets their preferred language, which is a bad user experience, overall for the idea of a default language being up to a guest I have no need for it personally so making this configurable would be preferred. 🤔
