### ISSUE TITLE
Update to 1.2.0-beta 1

### ISSUE THREAD

**Issue by SegelSack** [humhub/humhub#2340]
When I start the automatic updating procedure everything went fine until the end, there I get the message:
Error!
rename(/var/....../protected/vendor,/var/..../protected/runtime/updater/backups/vendor_1488797893): Permission denied

**Comment by luke-** [comment]
Make sure that the vendor & static directory is writable by the PHP user.

**Comment by luke-** [comment]
We'll add a check for this to the updater module.

**Comment by SegelSack** [comment]
They have all the same rights like other directories where I don't have any
php writing rights problems. And I Can't find the static directory? Or what
is meant by that?

Mit freundlichen Grüßen

*Philipp Sack*
Dipl. Des.
____________________________
pr-ide | pr + design
Spanische Allee 58
14129 Berlin

Postfach 38 01 31
14111 Berlin

pr-ide | city
Sybelstr. 41
10629 Berlin

Fon +49(30) 6860203
Fax +49(30) 6860207
Mob: +491708342142

www.pr-ide.de  Der Designergrill <http://zack.pr-ide.de>




2017-03-18 12:27 GMT+01:00 Lucas Bartholemy <notifications@github.com>:
