### ISSUE TITLE
Embedding of jPlayer for MP3 not working

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2346]
v.1.2.beta.2 
in ./protected/humhub/modules/file/widgets/views/showFiles.php i see on row 24:
```
<?php if ($fileExtension == "mp3") : ?>
                <!-- Integrate jPlayer -->
                <?= xj\jplayer\AudioWidget::widget(array(
                    'id' => $file->id,
                    'mediaOptions' => [
                        'mp3' => $file->getUrl(),
                        'title' =>  Html::encode(Helpers::trimText($file->file_name, 40))
                    ],
                    'jsOptions' => [
                        'smoothPlayBar' => true
                    ]
                ))
?>

```

Is this a new undocumented feature? It's not working - that's a pity... Would be great if that worked AND worked with video files too (mp4,m4v,mpg,mov,avi . etc...)

**Comment by buddh4** [comment]
Works for me in beta2, this widget was replaced with a playlist widget to enable one player with playlist of all tracks https://github.com/humhub/humhub/issues/2359#issuecomment-286913496 this will be part of the upcoming beta. 

The new widget uses the latest JPlayer version, perhaps this will fix your issue.
For videos I think we'll prefer the blueimp player in the future.

**Comment by martinbeek** [comment]
Ah yes , it works indeed! Sorry - probably tried to upload a corrupt MP3.
I've added the videoplayer too, inserted in ./protected/humhub/modules/file/widgets/views/showFiles.php at row 44:
![schermafbeelding 2017-03-16 om 19 14 01](https://cloud.githubusercontent.com/assets/6781157/24012268/a788d016-0a7d-11e7-87f8-a2ed167d9723.PNG)


```
                <!-- Integrate jPlayer -->
                <?= xj\jplayer\VideoWidget::widget(array(
                    'id' => $file->id,
                    'tagClass' => 'jp-video jp-video-360p',
                    'mediaOptions' => [
                        'm4v' => $file->getUrl(),
                        'title' =>  Html::encode(Helpers::trimText($file->file_name, 40))
                    ],
                    'jsOptions' => [
                        'smoothPlayBar' => true,
                        'keyEnabled' => true,
                        'remainingDuration' => true,
                        'toggleDuration' => true,
                        'supplied' => "webmv, ogv, m4v",
                        'size' => [
                                'width' => "640px",
                                'height' => "360px",
                                'cssClass' => "jp-video-360p"
                        ]

                    ]
                ))?>
            <?php endif; ?>
```

**Comment by buddh4** [comment]
looks nice, but note this file contains some additional enhancements in beta3 https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/widgets/views/showFiles.php#L32

**Comment by martinbeek** [comment]
Aha! Nice job!  I will be patient ;-)  I'll stop experimenting myself and wait for beta 3. 
Thanks!

**Comment by martinbeek** [comment]
Very nice indeed. And good to have in in the gallery.  
I did only change height="130" to width="100%" on the video element for a nice full screen video. And style="width:100%; max-width:100%;" on the video's <a element. 
So i now have: 
```
            <?php elseif (in_array(FileHelper::getExtension($file->file_name), array("mp4", "m4v", "avi", "mpg"))) : ?>
                <a style="width:100%; max-width:100%;padding-right:5px;" data-ui-gallery="<?= "gallery-" . $object->getUniqueId(); ?>" type="video/mp4" href="<?= $file->getUrl(); ?>#.mp4" title="<?= Html::encode($file->file_name) ?>">
                    <video src="<?= $file->getUrl() ?>" width="100%" />
                </a>
            <?php elseif (in_array(FileHelper::getExtension($file->file_name), array("ogv", "webm", "3gp"))) : ?>
                <a style="width:100%; max-width:100%;padding-right:5px;" data-ui-gallery="<?= "gallery-" . $object->getUniqueId(); ?>" type="video/ogg" href="<?= $file->getUrl(); ?>#.ogv" title="<?= Html::encode($file->file_name) ?>">
                    <video src="<?= $file->getUrl() ?>" width="100%" />
                </a>
            <?php endif; ?>
```

But that is to my personal taste ;-) 
See resulting images for one and multiple videos. 

![schermafbeelding 2017-03-16 om 20 54 17](https://cloud.githubusercontent.com/assets/6781157/24016039/dc4e1f42-0a8a-11e7-9152-f0f0d1b647f4.PNG)
![schermafbeelding 2017-03-16 om 20 53 51](https://cloud.githubusercontent.com/assets/6781157/24016038/dc4df3aa-0a8a-11e7-9533-fd642dcde309.PNG)
