### ISSUE TITLE
Enable post submits on dashboard for the own profile or different spaces 

### ISSUE THREAD

**Issue by andystrobel** [humhub/humhub#235]
![selected](https://cloud.githubusercontent.com/assets/6032728/4496553/84fa2cb8-4a66-11e4-8822-b94101bbdf38.png)

![dropdown](https://cloud.githubusercontent.com/assets/6032728/4496560/899c4896-4a66-11e4-82a9-df137b421c25.png)

**Comment by WASasquatch** [comment]
+2. Cause there is two of us looking. xD

**Comment by kkayacan** [comment]
+1

**Comment by WASasquatch** [comment]
I think I am confident enough to take this on. I am looking at sources now.
