### ISSUE TITLE
Add all users as recipients 

### ISSUE THREAD

**Issue by dziugasmeskauskas** [humhub/humhub#2352]
I want to add a feature that allows to add all members with a button click as recipients.
However I can't figure out a way to fetch all users. Is there maybe a function already for that ?
If not, how would I go and create one ?

**Comment by acs-ferreira** [comment]
Notify all registered users? Or all space members?

**Comment by dziugasmeskauskas** [comment]
All registered users. When I create a new message I want to be able to add all users instead of manually adding one by one.

**Comment by jeremiahtenbrink** [comment]
Inside of a user's model you need to setup a active record query with a where clause is set to all active.

**Comment by acs-ferreira** [comment]
https://yii2-framework.readthedocs.io/en/stable/guide/db-active-record/
