### ISSUE TITLE
Feature: styled Like/Comment buttons

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2355]
I've worked on styling the **Comment** and **Like/Unlike** buttons to my own template and would like to know if this interests HumHub globally so i can submit a PR.

> The style here is to fit my template, i would use HumHum default template colors if a PR is pushed.

Let me know.
_First button is `hovered`_

![image](https://cloud.githubusercontent.com/assets/12234510/23917716/9cf30600-08f0-11e7-9d4f-519661b35fc9.png)

_(Before, it was)_
![image](https://cloud.githubusercontent.com/assets/12234510/23917806/eb81a632-08f0-11e7-8afc-98d1568477c9.png)

**Comment by jeremiahtenbrink** [comment]
Looks good. I can dig it.

**Comment by Felli** [comment]
Something like this has been done in the [Flathub](https://github.com/GreenVolume/humhub-themes-flathub) theme, but the theme itself needs updated for v1.2 which I haven't done just yet.
