### ISSUE TITLE
Wiki for spaces - Handler not found after the update to beta2

### ISSUE THREAD

**Issue by bposlon** [humhub/humhub#2356]
Hi, 

I have humhub in two locations. One of them was run through the update and everything went well while the other one... not so much. 

Everything went well as far as files go but I keep getting Handler not found error toasted when I try to enable wiki module on my spaces. 

To make things more confusing, wiki is enabled in the default space but I cannot enable it in any other space. 

Any ideas?

**Comment by buddh4** [comment]
Please post the full error stack.

**Comment by bposlon** [comment]
I got around to it somehow... I had to turn on the modules in beta 1 and only THEN update to beta 2.

Weird but did the trick.

**Comment by buddh4** [comment]
Hmm the problem was fixed in beta2 (https://github.com/humhub/humhub/issues/2257) either the migration was not executed or this is another issue.

**Comment by gitael** [comment]
Hello,

i do have the same problem. When i try to enable the Module "Linklist" i get an error:
"Während der letzten Aktion ist ein Fehler aufgetreten. (Handler not found)
content.container.enableModule"

I some Spaces the Linklist is enabled an working.

I also tried to flush the cache. Then i got this Warning:
"PHP Warning – yii\base\ErrorException
Zend OPcache API is restricted by "restrict_api" configuration directive"

Humhub Version: 1.2.0-beta.3

**Comment by buddh4** [comment]
Delete the content of the `assets` directory within your humhub root directory. Regardting the cache error, please open another issue.
