### ISSUE TITLE
Multiple Audio Issue

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2359]
Would seem that when you upload multiple audio files you're able to play **ALL** of the files at one time, this shouldn't be possible, possible fix would be generating a audio gallery that shuffles between files.

https://community.humhub.com/content/perma?id=98788

**Comment by acs-ferreira** [comment]
Easily fixed with `$(this).jPlayer("pauseOthers");`

http://www.jplayer.org/latest/developer-guide/#jPlayer-pauseOthers

**Comment by Felli** [comment]
Just checked this option but it's not a 100% fix for the issue, switching over to a audio gallery or playlist shuffle would be much better.

http://jplayer.org/latest/demo-02-jPlayerPlaylist/
