### ISSUE TITLE
Private space doesn't showed in Directory/Spaces

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2362]
In url `index.php?r=directory%Fdirectory%2Fspaces` private spaces can not be searched and displayed.

**But for me this spaces allowed** and this spaces allowed in widget `New Spaces` (\humhub\modules\directory\widgets\NewSpaces) which is on the same page

**Comment by githubjeka** [comment]
Ref #1238

**Comment by luke-** [comment]
Hmm, the main difference between public and private spaces is that they doesn't show up in the directory.
The NewSpaces shows also only public spaces and only private spaces if the current user is member.

**Comment by githubjeka** [comment]
Hmmm, I can't reproduce this now. Now I see all allowed spaces for me :/
