### ISSUE TITLE
Trying to install the Custom Pages Mobule | Error in cURL request: Operation timed out

### ISSUE THREAD

**Issue by LoriSan** [humhub/humhub#2363]
Hello there,

i am trying to install the Custom Pages Module (v 0.7.3) on HumHub 1.2.0-beta.2 but it keeps showing me an internal server error. The error is shown below.

Other modules work fine, so it should be no general issue.

This is the error showing up:

Zend\Http\Client\Adapter\Exception\RuntimeException
Zend\Http\Client\Adapter\Exception\RuntimeException: Error in cURL request: Operation timed out after 29967 milliseconds with 3538546 out of 8642148 bytes received in /www/htdocs/w00c89ac/home/protected/vendor/zendframework/zend-http/src/Client/Adapter/Curl.php:425 Stack trace: #0 /www/htdocs/w00c89ac/home/protected/vendor/zendframework/zend-http/src/Client.php(1384): Zend\Http\Client\Adapter\Curl->write('GET', Object(Zend\Uri\Http), '1.1', Array, '') #1 /www/htdocs/w00c89ac/home/protected/vendor/zendframework/zend-http/src/Client.php(893): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'GET', true, Array, '') #2 /www/htdocs/w00c89ac/home/protected/humhub/modules/admin/libs/OnlineModuleManager.php(84): Zend\Http\Client->send() #3 /www/htdocs/w00c89ac/home/protected/humhub/modules/admin/controllers/ModuleController.php(116): humhub\modules\admin\libs\OnlineModuleManager->install('custom_pages') #4 [internal function]: humhub\modules\admin\controllers\ModuleController->actionInstall() #5 /www/htdocs/w00c89ac/home/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #6 /www/htdocs/w00c89ac/home/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #7 /www/htdocs/w00c89ac/home/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('install', Array) #8 /www/htdocs/w00c89ac/home/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/module/in...', Array) #9 /www/htdocs/w00c89ac/home/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /www/htdocs/w00c89ac/home/index.php(25): yii\base\Application->run() #11 {main}

Thanks in advance for any help :)

**Comment by buddh4** [comment]
If this keeps happening try raising your [max_execution_time](http://php.net/manual/de/info.configuration.php#ini.max-execution-time) setting  in your php.ini

**Comment by LoriSan** [comment]
Hello buddh4,

since i'm on shared hosting, i dont have access to the php.ini unfortunately.

But i did create a .htaccess file with the following commands:

```
AddHandler php71-cgi .php
php_value memory_limit 512M
php_value max_execution_time 259200
```
Did not work either.

I was using php 5.6 at the first place, then raised to 7.1 - Both have this problem tho.

**Comment by buddh4** [comment]
Hmm, it's a bit strange that the 8mb could not be loaded within 30sec, seems to be related with a slow network connection.

**Comment by LoriSan** [comment]
Hmm, the problem still persists.

I will try again tomorrow - Should help if is currently experiencing some load peaks. I hope... Will let you know.

**Comment by LoriSan** [comment]
Hello buddh4,

i tried for several times now but still there is no success :-(

Installation of all other modules i wanted to use went just fine.

I dont know what to do :-(

Best wishes,
Dominik

**Comment by LoriSan** [comment]
Hello,

Update to 1.2.0 stable solved this issue for me.

Best wishes,
Dominik

**Comment by MayhemOfHell** [comment]
I myself still get this error with a new install / latest version.. 
While i could not easily find the config file to define the "timeout" parameter... Still need better documentation...

What i did do to get around this during the start to install modules was add the following line to the Curl.php file..

`curl_setopt($this->curl, CURLOPT_TIMEOUT, 400);` below line 211, this overrides the defaul timeout and got me up and running. You can find the file in `protected/vendor/zendframework/zend-http/src/Client/Adapter`
