### ISSUE TITLE
Can Wiki for spaces be public?

### ISSUE THREAD

**Issue by bposlon** [humhub/humhub#2365]
I am baffled by the lack of the option to make Wiki for spaces public. Maybe I missed the option but as I see it, Wiki should have this option by default, isn't that what Wiki concept is all about? I would like to keep the discussion (i.e. wall) private for registered users and members of the space while keeping wiki publicly available since it should serve as a project repository. Sort of.

If there is such an option available, I humbly beg you to point me to it :)

If there isn't, is there a workaround to it being public directly in the database? I looked at it but couldn't find a security/privacy option for wiki only.

**Comment by martinbeek** [comment]
The wiki in my spaces are public! Put the space "default content visibility" to public and Bob's your uncle!

Martin

**Comment by githubjeka** [comment]
Now wiki inherit secrity setting from space, therefore you can't

**Comment by bposlon** [comment]
So basically, I would have to make my stream (wall) publicly available for guests? That inheritance doesnt really make sense... 

Is there a way around it?

**Comment by githubjeka** [comment]
wall or only wiki ?

**Comment by bposlon** [comment]
I would like to make wiki publicly available (free for all, even without registration) but commenting, wall visibility and basically all of interaction only for registered users who are members of the space.

**Comment by githubjeka** [comment]
This issue should be lock and move to https://github.com/humhub/humhub/issues/2365#issuecomment-287695226

**Comment by bposlon** [comment]
I agree. I tried there also but it seems nobody seems to care much about the issues posted in the repo

**Comment by buddh4** [comment]
We'll work on some of the older modules after the 1.2 release, we'll definetly have a look at the issues.

**Comment by DeepakTivari** [comment]
Hi, any update on this? It is a very important feature, is there any workaround at all?
