### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2366]
On last `master` version i can't upload images anymore. **Error 500**.

`PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 4096 bytes) in protected/humhub/modules/file/libs/ImageConverter.php on line 357
`

It is related to https://github.com/humhub/humhub/pull/2331
@luke- @githubjeka

PHP 7.1.3

**Comment by githubjeka** [comment]
Windows ?

**Comment by acs-ferreira** [comment]
Ubuntu

**Comment by githubjeka** [comment]
I have same the trooble on 7.1 Windows...

**Comment by githubjeka** [comment]
But It's not related with #2331. .This is a bug of GD

**Comment by acs-ferreira** [comment]
Ok, but i've face this AFTER merged that PR.

**Comment by githubjeka** [comment]
FROM commit ?

**Comment by githubjeka** [comment]
OK, I'll try to fix this for myself on Windows

**Comment by githubjeka** [comment]
On Debian master branch work correctly for me now

**Comment by githubjeka** [comment]
@acs-ferreira  can you show actual `memory_limit` from you php.ini ?

**Comment by acs-ferreira** [comment]
```
memory_limit = 128M
```

**Comment by githubjeka** [comment]
And haven't bug #2331 ? Strange

**Comment by githubjeka** [comment]
I have a fix for your trouble.... I'll send later

**Comment by acs-ferreira** [comment]
Avoid using `Helper` works fine.

Just removing `$memoryLimit = Helpers::getBytesOfIniValue($memoryLimit) * 1048576;`

**Comment by githubjeka** [comment]
@acs-ferreira try

**Comment by acs-ferreira** [comment]
Nop, same error with https://github.com/humhub/humhub/pull/2367/files

**Comment by githubjeka** [comment]
Sorry for my bug and thanks for u posting
