### ISSUE TITLE
"undefined" in browser tab

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2368]
Latest master, in browser when i'm on the Dashboard _(root)_, if i hit **F5**, page reloads but in the browser i get:

![image](https://cloud.githubusercontent.com/assets/12234510/24056861/8ebe9336-0b45-11e7-9ab0-e86a3c21b719.png)

**Comment by buddh4** [comment]
Are your running in production mode?
Did you try to clear your assets/cache?

**Comment by acs-ferreira** [comment]
I've switched to prod and it is good now.
But is it normal in dev mode? I've never faced this before, always in dev.

**Comment by buddh4** [comment]
I assume it was an asset issue. There was a small change which lead to this issue, but this should alrady be fixed in the master branch.
