### ISSUE TITLE
Testing APCu

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2369]
I've enabled [APCu](https://github.com/humhub/humhub/pull/2238), but:
`PHP APC(u) Extension missing - Type not available!`

But it is, used by another projects on the same server.

![image](https://cloud.githubusercontent.com/assets/12234510/24065379/ba18c20c-0b6a-11e7-80f0-583d6539a0b1.png)

**Comment by Felli** [comment]
Did you try 3f135214a6ebc62766afd82119690687a890405e or just #2238 itself?

**Comment by acs-ferreira** [comment]
I'm working with the last `master` so all commits loaded.

**Comment by Felli** [comment]
Try replacing 
`if ($this->type == 'yii\caching\ApcCache' && !function_exists('apc_add') && !function_exists('apc_addu')) {`
protected/humhub/modules/admin/models/forms/CacheSettingsForm.php with `if ($this->type == 'yii\caching\ApcCache' && !function_exists('apc_add') && !function_exists('apcu_add')) {`

**Comment by acs-ferreira** [comment]
Yep there is a typo...works fine, you can commit. Thanks :)
