### ISSUE TITLE
Migrate from CActiveForm to ActiveForm

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2372]
Actually both are available and used, shouldn't we use only `ActiveForm` along the whole project?

Are there any cons to not migrate everything?

I can see that some commits on this sense had already been submitted: https://github.com/humhub/humhub/commit/f0bd0035f8b74370dab13569516a7a76845b4e5e

**Comment by luke-** [comment]
Yes, CActiveForm should completely removed but the class itself should be still available for potential usage in modules. (Maybe until 1.3 or 1.4)

**Comment by acs-ferreira** [comment]
Thanks @luke- modules are not maintained like the Core is, i think that some modules need a good update like Calendar or Tasks, as these provide good functions to any social network and they have some annoying bugs/lack of functionalities.

_My2cents ;-)_
