### ISSUE TITLE
LDAP sync attributes

### ISSUE THREAD

**Issue by kroerig** [humhub/humhub#2373]
Hello,

I use "mailLocalAddress" attribute as the users primary mail address (mailbox name). Additional incoming mail addresses are in the "mail" attribute.

So I set "Eigenschaften der E-Mail-Adresse" to "mailLocalAddress", but this setting gets ignored when users are synced from LDAP.

I hardcoded my settings in ZendLdapClient.php

`
        // Try to automatically set id and usertable id attribute by available attributes
        if ($this->getIdAttribute() === null || $this->getUserTableIdAttribute() === null) {
            if (isset($attributes['objectguid'])) {
                $this->idAttribute = 'objectguid';
                $this->userTableIdAttribute = 'guid';
            } elseif (isset($attributes['mailLocalAddress'])) {
                $this->idAttribute = 'mailLocalAddress';
                $this->userTableIdAttribute = 'email';
            } elseif (isset($attributes['uid'])) {
                $this->idAttribute = 'uid';
                $this->userTableIdAttribute = 'username';
`

**Comment by githubjeka** [comment]
> So I set "Eigenschaften der E-Mail-Adresse" to "mailLocalAddress", but this setting gets ignored when users are synced from LDAP.

ignored ??? How it manifests, explain please. May be `mailLocalAddress` has no valid email ?
