### ISSUE TITLE
UI/UX: Comment already commented topic does nothing

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2374]
1. Post a new topic
2. Reply to that topic by clicking on Comment link on the topic and post a reply
3. Click again on Comment link on the topic
**-> Does nothing**

It should **focus** on the comment input area.

**Comment by acs-ferreira** [comment]
Closed by #2381

**Comment by githubjeka** [comment]
Open please and improve

> It should focus on the comment input area.
Click again -> should collapse comment block

Fist click - should focus on the comment input area.

**Comment by acs-ferreira** [comment]
@githubjeka this has been "fixed" by @buddh4 with https://github.com/humhub/humhub/commit/f75ea2a but your behavior is not implemented.

**Comment by githubjeka** [comment]
I tried to use this fix and it works as I wrote.

**Comment by acs-ferreira** [comment]
Ok i see, but IMO it should `unfocus` when/after you post the comment.

**Comment by githubjeka** [comment]
No difference to me
