### ISSUE TITLE
Dropbox module should be rewrite or removed

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2375]
As per [APIv1 being shut down](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/), this module can no longer be used **unless a Drop-In App has been created before 28 June 2016**. This kind of app can no longer be created.

Also, the module (without update) will be completely unusable after 06/28/2017.

As consequence, this module can no longer be used **unless** it is completely rewrite to use [APIv2](https://www.dropbox.com/developers/reference/migration-guide)

So keeping it as is in the Marketplace is a non-sense.

**Comment by buddh4** [comment]
Thanks for the info, the module needs to be updated anyways, would also be great to use the new file api to import/export files to/from the cfiles module.

**Comment by luke-** [comment]
Done
