### ISSUE TITLE
Modules icons don't show up in Profile Menu

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2380]
See 
![image](https://cloud.githubusercontent.com/assets/12234510/24101473/bfe07ec2-0d78-11e7-81f1-59ddc757fe46.png)

It's OK in Space perhaps
![image](https://cloud.githubusercontent.com/assets/12234510/24101490/d41cf230-0d78-11e7-93ec-cb5828362dc3.png)

**Comment by buddh4** [comment]
yeah, the profile menu icons are new, don't know why there were misisng in first place, but those have to be set in module updates.

**Comment by Felli** [comment]
Might be a cache problem as I can see the icons.

![](http://image.prntscr.com/image/edb8d4b22d574136842b8eb86899110c.png)

**Comment by acs-ferreira** [comment]
In Space it is OK, see my screenshot, **not** in Profile Menu.

**Comment by Felli** [comment]
Wonder if a profile was forgotten?
