### ISSUE TITLE
Member stats / Spaces stats "knob" widget empty

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2382]
v.1.2.beta3 

The Stats are empty after update to 1.2beta3.

Martin.
![schermafbeelding 2017-03-20 om 21 42 41](https://cloud.githubusercontent.com/assets/6781157/24121006/eedfb916-0db6-11e7-9c4c-d06c96a61a5a.PNG)

**Comment by Felli** [comment]
How did you update your site?

**Comment by martinbeek** [comment]
Hi Felli. 
Through the automatic update (module).


Martin.

**Comment by martinbeek** [comment]
Aha!  The reappeared after the hourly crontab run !

Sorry... ;-)
