### ISSUE TITLE
Where can i change my user profile tags?

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2383]
v.1.2beta.x
Or i'm getting crazy, or this is a feature that has been forgotten in 1.2.x:  the Tags i can set at time of registration - where can i edit them? 

Martin

**Comment by Felli** [comment]
User tags are found in Account settings > Settings > User settings at the top.

**Comment by martinbeek** [comment]
Thanks!  Just didn't see it - humhub blindness... ;-)
