### ISSUE TITLE
Only five tags shown in user directory

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2384]
v.1.2beta.3 

Only 5 profile tags are shown instead of many. In v.1.2beta2 this was still OK. 
I'd like to see all tags; leaving some out makes no sense.  The user in the screendump has 8 tags.

![schermafbeelding 2017-03-20 om 22 27 43](https://cloud.githubusercontent.com/assets/6781157/24122572/a6d5464e-0dbc-11e7-9da1-8df29d67e527.PNG)

**Comment by martinbeek** [comment]
Aha.... 
In ./directory/widgets/UserTagList.php :  public $maxTags = 5;  

Why? 



Martin.

**Comment by Felli** [comment]
I think because this was just random and `5` is most used throughout Humhub.
