### ISSUE TITLE
When accessing Admin > Setting > Advanced > Files get the error

### ISSUE THREAD

**Issue by Buliwyfa** [humhub/humhub#2388]
When accessing to Setting Advanced Files get the error

yii\base\ErrorException: A non well formed numeric value encountered in C:\_webs_\xxxxxxxxxxxxx.com\public\protected\humhub\libs\Helpers.php:127 Stack trace: 
0 C:\_webs_\xxxxxxxxxxxxx.com\public\protected\humhub\libs\Helpers.php(127): yii\base\ErrorHandler->handleError(8, 'A non well form...', 'C:\\_webs_\\socia...', 127, Array) 
1 C:\_webs_\xxxxxxxxxxxxx.com\public\protected\humhub\modules\admin\controllers\SettingController.php(188): humhub\libs\Helpers::GetBytesOfPHPIniValue('2M') 
2 [internal function]: humhub\modules\admin\controllers\SettingController->actionFile() 
3 C:\_webs_\xxxxxxxxxxxxx.com\public\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) 
4 C:\_webs_\xxxxxxxxxxxxx.com\public\protected\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array) 
5 C:\_webs_\xxxxxxxxxxxxx.com\public\protected\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('file', Array) 
6 C:\_webs_\xxxxxxxxxxxxx.com\public\protected\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('admin/setting/f...', Array) 
7 C:\_webs_\xxxxxxxxxxxxx.com\public\protected\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) 
8 C:\_webs_\xxxxxxxxxxxxx.com\public\index.php(25): yii\base\Application->run() 
9 {main} 

using PHP 7.1.13 on IIS-10/windows 2016

I fix it by adding to \public\protected\humhub\libs\Helpers.php this

----------------------------------------------------------------------------------
    public static function GetBytesOfPHPIniValue($val)
    {

        $val = trim($val);
        $last = strtolower($val[strlen($val) - 1]);
		
$val = (int)$val; <----------------------------------------------------------------------------

        switch ($last) {
            case 'g':
                $val *= 1024;
            case 'm':
                $val *= 1024;
            case 'k':
                $val *= 1024;
        }

        return $val;
    }
----------------------------------------------------------------------------------

Hope this help others.

Thanks

**Comment by acs-ferreira** [comment]
@githubjeka

**Comment by githubjeka** [comment]
Function `GetBytesOfPHPIniValue` is deprecated
