### ISSUE TITLE
Markdown #### <H4> broken in v.1.2beta.3

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2393]
As the subject says...  Markdown in posts is not working anymore; instead the `<h4>` tag is shown instead. 

Martin.

**Comment by Felli** [comment]
I can confirm this. The `####` is replaced with plain html tags `<h4></h4>`

### Screenshots
![](http://image.prntscr.com/image/4fafb2dd02d4460b9cd48b34d9b476cd.png)
![](http://image.prntscr.com/image/7d421da71bb346838663319e9cc2f88d.png)
