### ISSUE TITLE
HumHub Calendar throwing PDO exceptions in logs

### ISSUE THREAD

**Issue by cmoore-mayesh** [humhub/humhub#2395]
Had an epic crash of the underlying OS -- had to backup the database and copy all the humhub files over to a new system.  Everything seems to be working okay, however we are getting this error in the logging files whenever the calendar is accessed.

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.user_id' in 'where clause' in /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php:900 Stack trace: #0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(900): PDOStatement->execute() #1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL) #2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Query.php(210): yii\db\Command->queryAll() #3 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL) #4 /var/www/humhub/protected/modules/calendar/models/CalendarEntry.php(244): yii\db\ActiveQuery->all() #5 /var/www/humhub/protected/modules/calendar/controllers/GlobalController.php(73): humhub\modules\calendar\models\CalendarEntry::getEntriesByRange(Object(DateTime), Object(DateTime), Array, Array) #6 [internal function]: humhub\modules\calendar\controllers\GlobalController->actionLoadAjax() #7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('load-ajax', Array) #10 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('calendar/global...', Array) #11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 /var/www/humhub/index.php(25): yii\base\Application->run() #13 {main} Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.user_id' in 'where clause' The SQL being executed was: SELECT `calendar_entry`.* FROM `calendar_entry` LEFT JOIN `content` ON `calendar_entry`.`id` = `content`.`object_id` LEFT JOIN `contentcontainer` ON `content`.`contentcontainer_id` = `contentcontainer`.`id` LEFT JOIN `user` ON `content`.`created_by` = `user`.`id` LEFT JOIN `calendar_entry_participant` ON calendar_entry.id=calendar_entry_participant.calendar_entry_id AND calendar_entry_participant.user_id=2056 LEFT JOIN `space_membership` ON contentcontainer.pk=space_membership.space_id AND contentcontainer.class='humhub\\modules\\space\\models\\Space' AND space_membership.user_id=2056 LEFT JOIN `space` ON contentcontainer.pk=space.id AND contentcontainer.class='humhub\\modules\\space\\models\\Space' LEFT JOIN `user` `cuser` ON contentcontainer.pk=cuser.id AND contentcontainer.class='humhub\\modules\\user\\models\\User' WHERE ((((((((`start_datetime` >= '2017-02-26 00:00:00') AND (`end_datetime` <= '2017-04-09 00:00:00')) AND ((contentcontainer.pk=2056 AND class='humhub\\modules\\user\\models\\User') OR (contentcontainer.pk IN (SELECT `sm`.`id` FROM `space_membership` LEFT JOIN `space` `sm` ON sm.id=space_membership.space_id WHERE space_membership.user_id=2056 AND space_membership.status=3) AND contentcontainer.class = 'humhub\\modules\\space\\models\\Space') OR (contentcontainer.pk IN (SELECT `sf`.`id` FROM `user_follow` LEFT JOIN `space` `sf` ON sf.id=user_follow.object_id AND user_follow.object_model='humhub\\modules\\space\\models\\Space' WHERE user_follow.user_id=2056 AND sf.wall_id IS NOT NULL) AND contentcontainer.class = 'humhub\\modules\\space\\models\\Space') OR (contentcontainer.pk IN (SELECT `uf`.`id` FROM `user_follow` LEFT JOIN `user` `uf` ON uf.id=user_follow.object_id AND user_follow.object_model='humhub\\modules\\user\\models\\User' WHERE user_follow.user_id=2056 AND uf.wall_id IS NOT NULL AND contentcontainer.class='humhub\\modules\\user\\models\\User')))) AND (space.id IS NOT NULL AND ( (space_membership.status=3) OR (content.visibility=1 AND space.visibility != 0)) OR cuser.id IS NOT NULL AND ( (content.visibility = 1) OR (content.visibility = 0 AND content.created_by=2056)))) AND (`calendar_entry_participant`.`participation_state`=3)) AND (`calendar_entry_participant`.`id` IS NULL)) AND (`content`.`user_id`=2056)) AND (`content`.`object_model`='humhub\\modules\\calendar\\models\\CalendarEntry')) AND (`content`.`object_model`='humhub\\modules\\calendar\\models\\CalendarEntry') ORDER BY `start_datetime` in /var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:631 Stack trace: #0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(915): yii\db\Schema->convertException(Object(PDOException), 'SELECT `calenda...') #1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('fetchAll', NULL) #2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Query.php(210): yii\db\Command->queryAll() #3 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL) #4 /var/www/humhub/protected/modules/calendar/models/CalendarEntry.php(244): yii\db\ActiveQuery->all() #5 /var/www/humhub/protected/modules/calendar/controllers/GlobalController.php(73): humhub\modules\calendar\models\CalendarEntry::getEntriesByRange(Object(DateTime), Object(DateTime), Array, Array) #6 [internal function]: humhub\modules\calendar\controllers\GlobalController->actionLoadAjax() #7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('load-ajax', Array) #10 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('calendar/global...', Array) #11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 /var/www/humhub/index.php(25): yii\base\Application->run() #13 {main} Additional Information: Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'content.user_id' in 'where clause' )

If additional info is required, happy to provide it.
Current versions of software installed:

humhub - 1.1.2
calendar module - 0.4.1

system information:
ubuntu 16.04-2
Apache/2.4.18 (Ubuntu)
php 7.0.15-0ubuntu0.16.04.4
apcu 	5.1.3
curl 	7.47.0
mysql 5.7.17

**Comment by buddh4** [comment]
Seems to be an issue with the "My events" filter, which uses an old database column. If this filter is not selected it should work.

**Comment by cmoore-mayesh** [comment]
The problem is -- no one can create any events either because of this error.  After submitting a new event it just sits at a loading screen with the triple blinking dots, or it drops back to the calendar and the event doesn't show regardless of the the filters selected.

**Comment by buddh4** [comment]
There should be a fixed version available, please update your module and test again.
