### ISSUE TITLE
Dutch translation is awfully formal and old worldly - please change translator!! 

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2401]
I don't know if this is the place to report this, but the following is annoying the hell out of me and causing me a LOT of extra work.

English: 
The Dutch translation of Humhub as it is now, is an insurmountable obstacle for us to start using HumHub in a production environment. The translation is utterly formal and uses words and sentences that can be loosely called "oldworldly" and too formal for our (young / adolescent) public.
Can you supply a more informal translation of the Dutch language please? Thanks.
Or teach me how to make these changes myself? 
I am a member of the translation site, but no help, no files and info offered there... 

Dutch:
Ik heb onoverkomelijke problemen met de toon van de Nederlandse vertaling. Het gebruik van "U" in plaats van "jij/jouw/je" vind ik erg afstandelijk en het gebruik als woorden als "gelieve" vind ik niet van deze tijd. 
Graag zou ik een wat "lossere" en modernere versie van de vertaling zien. 
Onze sites zijn bedoeld voor jongeren en die worden niet met U aangesproken, et cetera.  Zo lang als deze oubollige taalversie in stand blijft, gaan wij Humhub in elk geval NIET gebruiken.

Martin.

**Comment by luke-** [comment]
If you're registered on the translation site and member of the "NL" language space, you should be able to edit the translation and communicate with other translators.

![image](https://cloud.githubusercontent.com/assets/4736168/24310442/46497874-10d0-11e7-9099-d2350259fe8b.png)
