### ISSUE TITLE
Custom Page on the User Profile menu

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2403]
While creating a Custom page, it is possible to add a link to the **User Account menu (Settings)**, is it possible to add it to the **User Profile Menu**?

Also, i would like to use some variables in that Custom (HTML) Page _(like the user's `Name` and/or `Address`)_ is it possible? Is this HTML only or can we use **PHP** here?

Thanks for the help.

**Comment by Felli** [comment]
To answer you questions.
- First part is not implemented, but I'm sure could be with ease.
- For the second part, I've been working on adding PHP to the [module](https://github.com/Felli/humhub-modules-custom-pages/tree/ext) but haven't completed it yet, but back to the main questions, no this is for HTML only, as for `Name` and/or `Address`, I'm not sure this would work with it being normal HTML.
