### ISSUE TITLE
profile pics

### ISSUE THREAD

**Issue by ramialhilli98** [humhub/humhub#2404]
when i change my profile pic on any profile it wont change but it apear when i edit it 
p.s i installed humhub on localhost xampp to be exact and i cant upload photos too

**Comment by Felli** [comment]
This is a widely known issue, and is an issue dealing with a site's [cache](https://github.com/humhub/humhub/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20cache).

**Comment by martinbeek** [comment]
I have currently three social network software test instances running on the same server. Wowonder, crea8social and humhub. All caches switched off and set Expire:epoch set to instruct browser caches to reload all content.
Humhub is the only one still having the problem that profile images and banners are not refreshed.
An absolute showstopper. If inspected in the debugger, images do have a no-cache header, but the browser sees no difference.

I hope this problem can be addresses with the highest priority and that humhub changes its strategy of handling the image updates (currently:using the same name with a querystring based on filetime). And, with all due respect, please stop blaming it on people's servers or browsers.
If you say it's a widely know issue, then why is the problem not handled at the core?

To be frank, apart from the exotic Dutch translation, it's the only real issue that withholds me from choosing humhub as our future platform!

**Comment by Felli** [comment]
@martinbeek which cache option are you using? At the moment APC(u) is the only option that is working for myself.

**Comment by martinbeek** [comment]
I have several options, serverside like Zend OPCache, but i've currently all switched them off, except for the humhub APCu, which i can switch on or off without any change.

**Comment by acs-ferreira** [comment]
Can't reproduce this, i'm using Redis Cache only.
I don't need to clean any cache to see updates.

**Comment by martinbeek** [comment]
I hope, again, that humhub will consider changing the way they store the images (using same name and filemtime querystring). It's a blocking issue for us.
