### ISSUE TITLE
Images Preview - popOver Content

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2413]
Having a strange isue with images preview.
When editing a post to delete some files, if image is hovered then popOver stays at screen.

See this screenshot, the images at the screen are already deleted.

![image](https://cloud.githubusercontent.com/assets/12234510/24366163/8e749e4a-1318-11e7-9ebb-365d2b183b09.png)

**Comment by buddh4** [comment]
hmm think this happens since now the popup is appended to the body because of visibility issues in modals.

**Comment by 001101** [comment]
i am having a different issue with the feature, on normal stream the image is not in the box

![image bug](https://cloud.githubusercontent.com/assets/8197408/24603606/d1d1e460-1861-11e7-8f63-f65b6f744987.jpg)

**Comment by buddh4** [comment]
@001101 Does this always happen, or just for specific images or at random?

**Comment by 001101** [comment]
@buddh4 yes, happens on every popup image, different spaces. 
Not a big issue, but I have also no idea how to debug it...
