### ISSUE TITLE
Feature: Reactions

### ISSUE THREAD

**Issue by solracsf** [humhub/humhub#2415]
Full CSS+jQuery **Reactions**
See here for full _(yet simple)_ front-end code http://bootsnipp.com/snippets/yvbBV

![image](https://cloud.githubusercontent.com/assets/12234510/24377977/93ac0f8c-1341-11e7-9bb9-1bb6bbac0f88.png)

**Comment by Buliwyfa** [comment]
💯 Eeven github has it ;)

**Comment by NENJAK** [comment]
👍

**Comment by NENJAK** [comment]
How you can integrate it?

**Comment by buddh4** [comment]
This could probably be implemented as a module which overwrites the LikeLink widget and adds a `type` attribute to the like table and some javascript. Just a rough idea.
I think this feature is a nice to have but not that important at the moment.

**Comment by acs-ferreira** [comment]
@buddh4 as you've said, not that important, but IMHO, HumHub has important features but not "nice" ones like this, so it should be considered. It could lead the software less "rough" and more "cool".

**Comment by Felli** [comment]
@buddh4 I think that is a good idea, maybe update the label.

**Comment by NENJAK** [comment]
@buddh4 I spoke with lots of people, everybody said that they like stickers / reactions very much.

**Comment by NENJAK** [comment]
I think reactions and stickers are an must for any better Social Network

**Comment by caveman86** [comment]
does anyone reach to any point to allow me continue or contribute with him from that point ?

**Comment by spoorun** [comment]
> does anyone reach to any point to allow me continue or contribute with him from that point ?

@caveman86 
If you're interested in contributing to this, my organisation can provide some money contribution...

**Comment by caveman86** [comment]
yes , I am interested , please send me on this email : mis.developing@gmail.com .. or whatsapp : 00905316059824
BTW: I have finished of my project .. I can show it to you

**Comment by caveman86** [comment]
> > does anyone reach to any point to allow me continue or contribute with him from that point ?
> 
> @caveman86
> If you're interested in contributing to this, my organisation can provide some money contribution...

yes , I am interested , please send me on this email : mis.developing@gmail.com .. or whatsapp : 00905316059824
BTW: I have finished of my project .. I can show it to you

**Comment by samuk** [comment]
+1 I'd like this

**Comment by SusanRussell-SignalWire** [comment]
+1 Please and thank you <3

**Comment by psychedel** [comment]
+1
It's an interesting feature as it provides a way to "rate" posts in a simpler way.
F.e. to have 3 different reactions for the media materials and show specific rating.

Here is one example how it's implemented for Discourse and it's widely used there.
https://github.com/discourse/discourse-reactions
https://meta.discourse.org/t/discourse-reactions/183261

**Comment by maxhaslbeck** [comment]
+1 I consider this feature very important in order to foster community engagement. The Like-button is too one-dimensional!

**Comment by spoorun** [comment]
> Done here: https://marketplace.humhub.com/module/reaction/description
> 
> @luke- maybe you'll like to close this issue now.

Is there a Github or other space for raising issues for the reactions module @marc-farre ?

Primarily, was wondering if it could be extended to work in the Messages module, as it's quite a core expectation of messaging :)

(Thanks for your work on this)

**Comment by ArchBlood** [comment]
> > Done here: https://marketplace.humhub.com/module/reaction/description
> > 
> > @luke- maybe you'll like to close this issue now.
> 
> Is there a Github or other space for raising issues for the reactions module @marc-farre ?
> 
> Primarily, was wondering if it could be extended to work in the Messages module, as it's quite a core expectation of messaging :)
> 
> (Thanks for your work on this)

I believe it to be a good idea for all modules even those that are commercial modules.

**Comment by marc-farre** [comment]
> Is there a Github or other space for raising issues for the reactions module @marc-farre ?

I've thought about having a GitHub repository for each module allowing posting issues, but since I have very few support requests, I'm not sure it's worth it at the moment.

I use 2 way to communicate:
- [Support form](https://www.cuzy.app/support/) for people how have a valid licence key
- [Community space](https://community.humhub.com/s/cuzyapp/home) for questions, module ideas and feature requests

The support form link is [in the description of the modules](https://marketplace.humhub.com/module/reaction/description), but I'll add a paragraph to make it clearer.

> extended to work in the Messages module

That's a very good idea.
Maybe related to https://github.com/humhub/mail/issues/188 if we want to unify the way the Like and Reaction modules work.
I'll have a look to the difficulty to develop this feature and keep you informed.
