### ISSUE TITLE
Link Preview module not showing images or descriptions

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2418]
I'm testing [Link Preview module](https://www.humhub.org/en/modules/marketplace/details?id=23) on a Humhub free instance, but **any** of links tested _(more then 10 different from different websites like Amazon, NYT...)_ get image or description, does this module still works?

**Comment by mrbandicoot** [comment]
I bought the module, registered the license and enabled it in admin but it's not working with latest humhub 1.2.0-beta.4

**Comment by buddh4** [comment]
Did you recently updated the module?

**Comment by mrbandicoot** [comment]
Bought and installed v1.6 today

**Comment by acs-ferreira** [comment]
What do you mean by « not working »? Same issues than me?

**Comment by mrbandicoot** [comment]
I expected it to be like facebook where you c&p a url and the post populates with a picture, since I installed the module I see no difference in humhub

**Comment by Felli** [comment]
@mrbandicoot The link should render into a preview, just like how a YouTube video is rendered from it's link.

**Comment by mrbandicoot** [comment]
a heads up guys, I found that just pasting the url and clicking submit does not render a preview, you need to press return on the keyboard before you click submit, then it works, thanks for all your replies, see link for screenshot

https://i.imgsafe.org/5adfdda6c3.png

**Comment by Felli** [comment]
Would seem that a space is a requirement after the link for it to render, and sadly if you remove the link in editing and replace it with normal text the link preview goes away. I wonder if it would be possible to do the link converting method that embed links does?
