### ISSUE TITLE
Allow multiple default spaces for groups

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#242]

**Comment by 001101** [comment]
You can add default autojoin to spaces in table 'space' on column 'auto_add_new_members' with a 1

**Comment by inluxc** [comment]
I would like to be able to associate space to users that belong to a group, instead of associating one by one.

**Comment by aleksander-gorski** [comment]
+1

**Comment by MasterHans** [comment]
Hello everyone,

At the moment system can assign the default space to the user group  
![assign_spac_to_group](https://user-images.githubusercontent.com/17376109/96372407-4add6f00-116f-11eb-98c3-d77088b48859.png)

All users of group **My group2** will by default added to space **My Space** as a member.

**Comment by ArchBlood** [comment]
@MasterHans not exactly, this was created so that more than one space could be added to any given user group, meaning multiple default spaces to one user group

**Comment by luke-** [comment]
@MasterHans Yes, this is about several such spaces. e.g. MySpace2a, MySpace2b...
Probably we have to create our own database table here.

Maybe it would be good to add an option to force the default spaces again. If later Spaces are added to a group.
However, this should then be set up using an ActiveJob in the background (queue).

**Comment by MasterHans** [comment]
Hi guys,

As I can see we have to approach to solve this:

1) To make on **settings** tab of the **Group** edit page extra **SpacePickerField::widget** field.
And play to it as many spaces as we want.
Like this:
![Spaces_To_Group](https://user-images.githubusercontent.com/17376109/97209788-ce313d00-17cd-11eb-93d6-6898f8e6a2d5.png)

What is the actual propose of **Default Space** field? 
Could we make it as a Default Space**S**
Make it plural? 
and use only one field for automatic space assignment to the group users?
2) The second approach is to make new tab **Spaces** in the  **Group** edit page
Like this:
![Spaces_To_Group_2](https://user-images.githubusercontent.com/17376109/97210710-0a18d200-17cf-11eb-8924-b7e369538825.png)

Second approach is similar to Member adding to the group tab.

Qhat you think about it?

See you
Alex

**Comment by luke-** [comment]
Thanks for your suggestions, I would prefer 1, that we simply allow multiple spaces in the `Default Space` field.
The current default spaces should be added to the new `group_space` (singular) table via a migration.

![image](https://user-images.githubusercontent.com/4736168/97329919-dfcf1f00-1877-11eb-8227-b09c6825f6d5.png)

When this is done, we can add a button or checkbox to recreate the group/space mapping. (e.g. for existing group members)
