### ISSUE TITLE
Linkpreview in comment copies itself to next input box

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2421]
v1.2beta4 with Linkpreview module enabled

If i place an url in a comment and press space to create a link preview, this same preview is copied to the next comment input box. See picture.
![img_3374](https://cloud.githubusercontent.com/assets/6781157/24455753/13b71802-1491-11e7-94c1-b4f3e62aadf7.PNG)

**Comment by buddh4** [comment]
We are currently working on LinkPreview Module.

**Comment by martinbeek** [comment]
Ok. Fyi, It did not occur with the previous version.
I don't know if you are interested, but I rewrote parts of the link preview module already in regard to the layout. See picture.

Martin.
![img_3376](https://cloud.githubusercontent.com/assets/6781157/24467595/6fc48624-14b5-11e7-91f6-e4171eaa3049.PNG)

**Comment by buddh4** [comment]
There is a new version available, hope this fixes the issues. Make a backup of your changes, otherwise they are lost. Looks nice! Whats the problem with the mentioning?

**Comment by martinbeek** [comment]
I'll test the new version soon!

**Comment by martinbeek** [comment]
The problem still exists in the new version.
