### ISSUE TITLE
No error message shown (anymore) if invalid characters appear in Wiki page title.

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2425]
If invalid characters exist in the title field of a wiki page, the user used to get a error message with explanation. 
Now, in 1.2beta4, no error or warning is shown and it looks like the page is saved. 
This way i've already lost two new wiki pages, not knowing that they were not saved.

Martin.

**Comment by Felli** [comment]
Need more information, what characters are being used?

**Comment by martinbeek** [comment]
If I choose "Wiki / FAQ (page 1)" for a title, the page is not saved, and no error is shown. 
In the background humhub does not allow the '/'  I guess. Before beta 4, an error was displayed, but not alarming enough imho. Too easy to miss it and browse to another page and loose all your work...

Martin.

**Comment by Felli** [comment]
Hmm... You are right, foreign characters don't work within the Wiki module title.

**Comment by acs-ferreira** [comment]
I've made a little test, and i have a liitle message when i try to save.

![image](https://cloud.githubusercontent.com/assets/12234510/24577416/aa4fa0ac-16cd-11e7-83a6-f75f6cc43bd4.png)

**Comment by martinbeek** [comment]
In my installation (1.2beta4) no message appears and the user is at loss...

**Comment by buddh4** [comment]
Could not reproduce thit. But the error message should be red, think this issue does already exist on the repository.
