### ISSUE TITLE
Make public or private > ERROR

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2427]
When trying to make a post PRIVATE, i get:

```
TypeError: target is undefined_executeAction@https://example.tld/static/js/humhub/humhub.action.js?v=1489453108:405:1
ActionBinding.prototype.handle@https://example.tld/static/js/humhub/humhub.action.js?v=1489453108:384:17
bindAction/<@https://example.tld/static/js/humhub/humhub.action.js?v=1489453108:604:13
jQuery.event.dispatch@https://example.tld/assets/aaedcdd4/jquery.js?v=1490608938:4736:16
jQuery.event.add/elemData.handle@https://example.tld/assets/aaedcdd4/jquery.js?v=1490608938:4549:6
```

when make PUBLIC:

```
TypeError: target is undefined_executeAction@https://example.tld/static/js/humhub/humhub.action.js?v=1489453108:405:1
ActionBinding.prototype.handle@https://example.tld/static/js/humhub/humhub.action.js?v=1489453108:384:17
updateBindings/
```

Errors triggered on **Firefox 52**

**Comment by Felli** [comment]
Hmm... Just tried and couldn't reproduce this with v1.2beta-4 are there any errors within the `ACP -> Settings -> Information -> Logging`? Also Firefox is known to block some action related JavaScript for security reasons.

**Comment by acs-ferreira** [comment]
Nothing on logging. Same on Chrome.

**Comment by buddh4** [comment]
Have you cleared your cache/assets? If you update by using git you should always clear your cache.
Furthermore, are you running in production or debugging mode?

**Comment by acs-ferreira** [comment]
@buddh4 yes, cache is cleared after each deployment.

I've tried both, Debugging and Production mode, same error.

**Comment by acs-ferreira** [comment]
Same error on https://community.humhub.com

**Comment by buddh4** [comment]
Worked for me after clearing the cache at the community.

**Comment by acs-ferreira** [comment]
No chances here... :(

I've also tried to:

```
php yii asset humhub/config/assets.php humhub/config/assets-prod.php

Loading configuration from 'humhub/config/assets.php'...
Collecting source bundles information...
Creating output bundle 'all':
  Compressing JavaScript files...
public/protected/humhub/config/../../../static/js/all-temp.js.tmp>> Local Npm module "grunt-shell" not found. Is it installed?

Running "uglify:assets" (uglify) task
[D] Task source: public/node_modules/grunt-contrib-uglify/tasks/uglify.js
File public/protected/humhub/config/../../../static/js/all-temp.js created: 1.64 MB â 825.45 kB
>> 1 file created.

Done.
  JavaScript files compressed into 'public/protected/humhub/config/../../../static/js/all-temp.js'.
  Compressing CSS files...
public/protected/humhub/config/../../../static/css/all-temp.css.tmp>> Local Npm module "grunt-shell" not found. Is it installed?

Running "cssmin:target" (cssmin) task
>> 1 file created. 329.41 kB â 286.28 kB

Done.
  CSS files compressed into 'public/protected/humhub/config/../../../static/css/all-temp.css'.

Creating new bundle configuration...
Output bundle configuration created at 'humhub/config/assets-prod.php'.
```

Then:
- Cleared all caches (OPcache, Redis, Browser Cache)

New assets are correctly loaded by the browser. Same...

**Comment by buddh4** [comment]
Please check if there are any javascript initialization errors in your developer console, perhaps a module could not be initialized.

Check if this function is present in the stream.js file:

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/stream/resources/js/humhub.stream.js#L236

Are you using a custom theme, if yes have you overwritten the following file: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/views/layouts/wallEntry.php#L20?

The error suggests, that the StreamEntry component could not be determined.

**Comment by acs-ferreira** [comment]
Humm...it is present on the file, but **not** in the generated asset (verified in debug mode).

How to clear all assets and generate them again?

**Comment by acs-ferreira** [comment]
Ok, i've just cleared my `/assets` folder and it works now, thanks !
But...

Now, when i try tu upload a file, i have this:

![image](https://cloud.githubusercontent.com/assets/12234510/24608538/38e0fd5c-1877-11e7-80ea-04e92192ca0d.png)
