### ISSUE TITLE
Issues after Update to 1.2

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#2428]
Hello,

i am not very happy with the update from 1.1 to 1.2rc2, have now waited some time and used the humhub updater. have updated any modules before the update and afterwards.

these issues causing now some big problems:

1. no youtube embed is shown, any links are gone, is this a new feature?
2. sometimes stream can not initialized -> but no log about it
3. log: exception 'yii\base\ErrorException' with message 'Undefined class constant 'self::EDIT_MODE_MODAL'' in public_html/protected/humhub/modules/content/components/ContentActiveRecord.php:147 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}
4. cfiles got corrupted after update and is not working with github replacement, i know, seperate module, seperate github issue, but I had to say it.

greets

*edit: have now run complete update to 1.2rc4 and it is a bit better, cfiles now working again, but now the directory, member and any other statics are complete gone, just blank page.
will investigate  it in a few days, but it's working so far and the youtube embed is also back, which is good.

**Comment by Felli** [comment]
The main issue with updated with the Humhub Updater that I had was that it didn't remove all the unneeded files and folders and replace them with what is needed, I had to manually remove any files and folders then upload the new ones.

**Comment by 001101** [comment]
Which one are these unneeded folder?

For 1.1 updates the updater worked very well, but with the new messaging and core extensions I already knew that it will get problems, this is normal, but when the software with update will get mature for enterprise, it should be more testings integrated in the updater and rollback features.

**Comment by Felli** [comment]
Your directory should look almost like the [master branch](https://github.com/humhub/humhub).

**Comment by 001101** [comment]
Yes some dirs are not deleted, but they are empty, but that is not important for me, just stuff.
System works now almost like before updates and the few bugs are gone (thanks to @buddh4 for ultra fast custom-pages fix!).

Most important that I also had no stream loading error after cleaning up every cache, proxy and cloudflare a couple of times, maybe just cronjob had to be run a few times for new system to initialized.

So I am very happy now on 1.2, it's a big performance win and will be almost faster on new VPS with 5 vcores and PHP 7.1 :)
