### ISSUE TITLE
Emoticon and emoji not working in comments

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2429]
V.1.2beta4
Humhub's build-in emoticons and hand-typed emoji are ignored and the whole message is truncated after the emoticon.

**Comment by martinbeek** [comment]
In comments

**Comment by acs-ferreira** [comment]
No problem here.

![image](https://cloud.githubusercontent.com/assets/12234510/24578320/9634494a-16de-11e7-82a3-a53a66071865.png)

**Comment by martinbeek** [comment]
In comments?!

**Comment by acs-ferreira** [comment]
Yes

**Comment by martinbeek** [comment]
Im trying this NOW on the humhub community site and it is NOT working, sorry.

**Comment by martinbeek** [comment]
Note, Im talking about emoji

**Comment by acs-ferreira** [comment]
Give me an example...

**Comment by martinbeek** [comment]
Here is an example, but i'm not really in the mood to have a discussion every time i try to help out by posting bugs. To get a reply EVERY TIME like "its working fine here" is like saying "you are talking shit"... 



![img_3380](https://cloud.githubusercontent.com/assets/6781157/24578366/a08bfbb2-16df-11e7-9f1e-052a9468b378.PNG)
![img_3381](https://cloud.githubusercontent.com/assets/6781157/24578367/a0a51bec-16df-11e7-8e1a-185b268085df.PNG)

**Comment by acs-ferreira** [comment]
Dear friend, no problem, i'm just trying to help, not saying you're talking "shit"... :)

But i repeat, it's working on my side on:
- My own install
- One HumHub free instance
- HumHub Community, see:

![image](https://cloud.githubusercontent.com/assets/12234510/24578447/c55faff0-16e0-11e7-89dd-5306142c44f4.png)

**No more discussion then.**

**Comment by Felli** [comment]
Might be a rendering issue over iOS mobile devices.

**Comment by martinbeek** [comment]
It's only an issue in comments; posting on wall is working fine with both emoji and humhub emoticons. My colleague is having the same issue on a Android tablet, i'll speak to him later today.

Because you suspect it's a mobile issue, i'll attach the javascript debug to my phone later today and let you know if there is any debug info worth mentioning.

Martin.

**Comment by Felli** [comment]
Thanks, that should help a lot.

**Comment by martinbeek** [comment]
A recap. Emoji's and humhub emoticons do only work on mobile if on the first position of a new message. If further on in the messagtext; all goes wrong. As well as in posts as in answers; no difference, depsite my first assumption.
Maybe that helps...
Still no debug info; haven't been close to a PC today yet.

**Comment by Felli** [comment]
It would seem to be working somewhat on Android 5.1, but switching between public and private will cause an emoji to disappear.
![screenshot_2017-04-01-16-59-51](https://cloud.githubusercontent.com/assets/2011633/24582386/0e7179a0-16fd-11e7-9d8f-dc4e0996f72b.png)

**Comment by buddh4** [comment]
Regarding unicode emojis, see https://github.com/humhub/humhub/issues/2129

**Comment by martinbeek** [comment]
Ooo!  Going to patch that in RIGHT NOW 👍

**Comment by martinbeek** [comment]
No, alas, that is not working - but at least is the text not truncated anymore and shows a "?" instead of the emoji.

**Comment by buddh4** [comment]
Did you change the charset of the database and all your tables? Worked for me, at least with an new installation. I'll do some tests soon.

**Comment by martinbeek** [comment]
wait...

**Comment by martinbeek** [comment]
Yes sir! Brilliant! 

I've changed the database charset:
`
ALTER DATABASE
    humhub
    CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;
`

Two tables: 
`
ALTER TABLE
    post
    CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

ALTER TABLE
    comment
    CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;`
`

And the following fields :
`
ALTER TABLE
    post
    CHANGE message message
    TEXT
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

ALTER TABLE
    post
    CHANGE message2trash message2trash
    TEXT
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;


ALTER TABLE
    comment
    CHANGE message message
    MEDIUMTEXT
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

`

Great stuff! 

Any other tables/fields i should explicitly convert?
Thanks a lot!

![img_3391](https://cloud.githubusercontent.com/assets/6781157/24608115/5bb63eb6-1875-11e7-9cee-04dd7f96a075.PNG)

**Comment by dosones** [comment]
hello

the emoji's works on phone but while viewing from PC browsers it doesn't

**Comment by Felli** [comment]
@dosones could you provide any console errors? Did you follow https://github.com/humhub/humhub/issues/2429#issuecomment-291122225 ?

**Comment by dosones** [comment]
![capture](https://user-images.githubusercontent.com/11355926/29487765-3e9a6b22-851c-11e7-8e06-87b41f1eec30.PNG)

Yes, I followed that #2429. I am sorry I am noob and I don't know how to provide console errors. 
(In Image (Chrome for PC) the first two comments are Android keyboard emojis. The remaining ones are Humhub's :-D posted from Chrome on Android)


FYI even the android emoji's are not working anymore even on phone. (right now)
I followed martinbreek's comment.

**Comment by Felli** [comment]
HumHub's format is like this example;  `:smile:` I'm not sure that normal `:D` will work within HumHub's platform at this time, although it could be extended to render the emojis better.

**Comment by arnfinnkristensen** [comment]
I also followed martinbreek comment but it did not work for me either.

**Comment by buddh4** [comment]
does it make any difference to set the db component charset as mentionend here: https://github.com/humhub/humhub/issues/2129 ?

**Comment by arnfinnkristensen** [comment]
@buddh4  Thank you. that did it. Now it works.

**Comment by funkycram** [comment]
This is what I made on Humhub 1.2, if it can help some of you (remove lines concerning modules not installed in your Humhub) :

```
ALTER DATABASE `plateforme_seve_org_humhub` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

ALTER TABLE `space` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `post` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `comment` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `message_entry` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `calendar_entry` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `custom_pages_container_page` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `wiki_page_revision` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `poll` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `profile` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `task` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE `announcement` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

ALTER TABLE `space` CHANGE `description` `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `post` CHANGE `message` `message` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `post` CHANGE `message_2trash` `message_2trash` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `comment` CHANGE `message` `message` MEDIUMTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `message_entry` CHANGE `content` `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `custom_pages_container_page` CHANGE `page_content` `page_content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `wiki_page_revision` CHANGE `content` `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `poll` CHANGE `question` `question` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `message_entry` CHANGE `content` `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `profile` CHANGE `about` `about` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `task` CHANGE `description` `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `announcement` CHANGE `message` `message` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```

add to `common.php` :
```
return [
  'components' => [
        'db' => [
        'charset' => 'utf8mb4'
        ]
    ]
]
```
