### ISSUE TITLE
Newly invited members get error at registration time

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2431]
V1.2beta4
I invited a large number of friends to our new humhub site, but they almost all, except a few, are rejected with an error at time of registration (choose username and password)!
English error message on user's screen is (translated) "unable to verify this information".

This is the error in the log:
`INFO  Sun, 02 Apr 2017 09:31:48 +0200  application
$_GET = [ 'query' => 'user/auth/login' ] $_SERVER = [ 'USER' => 'www-data' 'HOME' => '/var/www' 'FCGI_ROLE' => 'RESPONDER' 'MOD_X_ACCEL_REDIRECT_ENABLED' => 'on' 'GEOIP_ADDR' => '141.101.105.117' 'GEOIP_COUNTRY_CODE' => 'NO' 'GEOIP_COUNTRY_NAME' => 'Norway' 'GEOIP_REGION' => '07' 'GEOIP_REGION_NAME' => 'Noord-Holland' 'GEOIP_CITY' => 'Amsterdam' 'GEOIP_AREA_CODE' => '0' 'GEOIP_LATITUDE' => '52.3500' 'GEOIP_LONGITUDE' => '4.9167' 'GEOIP_POSTAL_CODE' => '1091' 'SCRIPT_FILENAME' => '/var/www/bsmug.nl/httpdocs/index.php' 'SCRIPT_NAME' => '/index.php' 'QUERY_STRING' => 'query=user/auth/login' 'REQUEST_METHOD' => 'POST' 'CONTENT_TYPE' => 'application/x-www-form-urlencoded' 'CONTENT_LENGTH' => '190' 'REQUEST_URI' => '/user/auth/login' 'DOCUMENT_URI' => '/index.php' 'DOCUMENT_ROOT' => '/var/www/bsmug.nl/httpdocs' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'HTTPS' => 'on' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_SOFTWARE' => 'nginx/1.6.2' 'REMOTE_ADDR' => '141.101.105.117' 'REMOTE_PORT' => '17736' 'SERVER_ADDR' => '145.131.21.89' 'SERVER_PORT' => '443' 'SERVER_NAME' => 'bsmug.nl' 'REDIRECT_STATUS' => '200' 'HTTP_MOD_REWRITE' => '1' 'HTTP_HOST' => 'bsmug.nl' 'HTTP_CONNECTION' => 'Keep-Alive' 'HTTP_ACCEPT_ENCODING' => 'gzip' 'HTTP_CF_IPCOUNTRY' => 'NL' 'HTTP_X_FORWARDED_FOR' => '80.56.109.196' 'HTTP_CF_RAY' => '3492173319467331-AMS' 'HTTP_CONTENT_LENGTH' => '190' 'HTTP_X_FORWARDED_PROTO' => 'https' 'HTTP_CF_VISITOR' => '{\"scheme\":\"https\"}' 'HTTP_CACHE_CONTROL' => 'max-age=0' 'HTTP_ORIGIN' => 'https://bsmug.nl' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 5.0.1; GT-I9515 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36' 'HTTP_CONTENT_TYPE' => 'application/x-www-form-urlencoded' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 'HTTP_DNT' => '1' 'HTTP_REFERER' => 'https://bsmug.nl/user/auth/login' 'HTTP_ACCEPT_LANGUAGE' => 'nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4' 'HTTP_CF_CONNECTING_IP' => '80.56.109.196' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1491118308.8155 'REQUEST_TIME' => 1491118308 ]
ERROR  Sun, 02 Apr 2017 09:31:48 +0200 yii\web\HttpException:400
exception 'yii\web\BadRequestHttpException' with message 'Het is niet mogelijk uw verstrekte gegevens te verifiëren.' in /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/web/Controller.php:166 Stack trace: #0 /var/www/bsmug.nl/httpdocs/protected/humhub/components/Controller.php(146): yii\web\Controller->beforeAction(Object(yii\base\InlineAction)) #1 /var/www/bsmug.nl/httpdocs/protected/humhub/modules/user/controllers/AuthController.php(58): humhub\components\Controller->beforeAction(Object(yii\base\InlineAction)) #2 /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Controller.php(154): humhub\modules\user\controllers\AuthController->beforeAction(Object(yii\base\InlineAction)) #3 /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('login', Array) #4 /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('user/auth/login', Array) #5 /var/www/bsmug.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /var/www/bsmug.nl/httpdocs/index.php(24): yii\base\Application->run() #7 {main}`

**Comment by Felli** [comment]
This is an `INFO` not the actual error stack, the error stack normally comes after this. Another thing are you using  custom theme or default?

**Comment by martinbeek** [comment]
Hello Felli.

I use a custom theme. I use the theme.css, and main.php and head.php in views/layouts.
I cleared the log this afternoon :-(
We'll have to wait until one of the others logs in. There are still six or seven who have not tried yet. 
I'll get back to you!

Martin

**Comment by martinbeek** [comment]
identical to #2433
