### ISSUE TITLE
Very alarming: New members react to invitation and take another user's identity!  +SOLUTION

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2433]
I have two reports of people that have clicked on my invitation to join my humhub site, entered their information (username and password), and entered the website totally logged in **as the previous user** - for them somebody who is a total stranger - and have **full access** to their account. 

I've just received a screendump from a new user (report number three) - just accepted the invitation - and has FULL access to my sister's account. They were invited from the same Space, through invitation by email.

My log is empty!  This is very very worrying and i need some advice on this, or i have to close down the site for now. 

v.1.2beta4

Martin

**Comment by martinbeek** [comment]
Because this all happens "behind my back" i have no means of debugging.
Only thing i can say and contribute is that i was working in the Translation module at that time. 

Martin

**Comment by githubjeka** [comment]
Who is previous user ?

**Comment by martinbeek** [comment]
In that case, the user who responded to the space invitation before this person.

Meanwhile, all but two where NOT able to register on the humhub site. Apart from the issue reported here, they all got the "oops you've taken a wrong turn" message and did not know what to do.... They all registered through a space invitation mail.

**Comment by martinbeek** [comment]
We have solved the problem (we are 99% sure). 

We had a brainstorm session about another issue, and stumbled upon the solution to this issue! 

We use NGINX for webserver with fastcgi microcache. 

If ANY idiot on the internet EVER suggests to include the following parameter in your nginx server config php block:

**_fastcgi_ignore_headers "Cache-Control" "Expires" "Set-Cookie";_**
or
**_fastcgi_ignore_headers "Set-Cookie";_**

SHOOT THEM IN THE *SS !!    ;-)

This is what you get if you follow "expert advice" on the internet, and just copy/paste the "expert advice" into your config. :-( 

So, if you are using NGINX, make sure to NEVER use anything stupid like ignoring cookies in your php block. It will break your site's security 100%. 

I apologize for being a copy-paster from time to time... 👎 

Martin

**Comment by martinbeek** [comment]
This issue can be closed.

**Comment by buddh4** [comment]
Glad it works now ;)
