### ISSUE TITLE
Poll module : emojis not working

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2444]
When trying to put an amoji on a poll by initiating it with `:` we get

![image](https://cloud.githubusercontent.com/assets/12234510/24619945/1a8dafce-189c-11e7-8262-463428202e58.png)

And after posting, emoji is not converted.

**Comment by buddh4** [comment]
https://github.com/humhub/humhub-modules-polls/commit/e1ff9727bcf455b470215aa56f8c5878e08756fc
