### ISSUE TITLE
Formatting message for language 'en' failed with error:

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub#2447]
Currently installed version: 1.2.0-beta.4
Error Message:
Formatting message for language 'en' failed with error: Message pattern is invalid: Constructor failed. The message being formatted was: {n,plural,=1{# new entry} other{# new entries}} since your last visit.

**Comment by buddh4** [comment]
Where exactly does this occure? Is any functionality blocked by this error?

**Comment by rapidpage** [comment]
The loading time of the site is dreadful

**Comment by rapidpage** [comment]
I have over 2500 errors logged

**Comment by buddh4** [comment]
Did you use the updater module or git update?

**Comment by rapidpage** [comment]
Updater module.

**Comment by buddh4** [comment]
Clear your cache "Administration -> Settings ->Advanced -> Cache -> Flush" and post the full error stack if possible.

Are you using a custom theme?
Did you run beta3 before without problems?
Are your modules up to date?

**Comment by rapidpage** [comment]
I went from beta 2 to beta 4, all plugins are up to date, in fact i
disabled them and reenabled them, no custom theme and did clear cache
before sending this issue.

**Comment by buddh4** [comment]
I still don't know where this happens and which feature is affected nor have you posted the full error (if ther is any). 
Are thosw 2500 errors new or old and what kind of errors do you get? Is this the only issue you have after the update?

**Comment by rapidpage** [comment]
Those 2500 errors are all related to language error.  These errors happened
only after upgrade. The errors that i am getting are unable to @(user) in
posts or comments or invite to a space. Also, the cron job is sending back
an error.

**Comment by buddh4** [comment]
Can't reproduce this, check your ICU version (Administration -> Information -> Prerequisites)

**Comment by rapidpage** [comment]
PHP - Version - 7.0.17

 PHP - GD Extension

 PHP - INTL Extension

 PHP - INTL Extension - ICU Version (4.4.1)(Hint: ICU Data 4.8.1 or higher
is required)

 PHP - INTL Extension - ICU Data Version (4.4.0.1) (Hint: ICU Data 4.8.1 or
higher is required)

 PHP - EXIF Extension

 PHP - FileInfo Extension

 PHP - Multibyte String Functions

 PHP - cURL Extension

 PHP - ZIP Extension

 LDAP Support (Hint: Optional - Install PHP LDAP Extension and Zend LDAP
Composer Package)

 PHP - APC(u) Support (Hint: Optional - Install APCu Extension for APC
Caching)

 PHP - SQLite3 Support

 PHP - PDO MySQL Extension

 Permissions - Runtime

 Permissions - Assets

 Permissions - Uploads

 Permissions - Module Directory

 Permissions - Dynamic Config

**Comment by rapidpage** [comment]
Tue, 04 Apr 2017 11:09:31 -0400 application
$_GET = [ 'r' => 'dashboard/dashboard/stream' 'mode' => 'normal'
'StreamQuery' => [ 'sort' => 'c' 'from' => '0' 'limit' => '8'
'suppressionsOnly' => 'false' ] ] $_SERVER = [ 'REDIRECT_SCRIPT_URL' =>
'/index.php' 'REDIRECT_SCRIPT_URI' => 'http://humhub.ca/index.php'
'REDIRECT_DOCUMENT_ROOT' => '/kunden/homepages/5/d673757836/htdocs/humhub'
'REDIRECT_UI_SUEXEC_FSTATD_UNIXSOCKET' =>
'/var/run/ui-fstatd.suexec.socket' 'REDIRECT_DBENTRY_HOST' => 'humhub.ca'
'REDIRECT_DBENTRY_VALUE' =>
'/kunden/homepages/5/d673757836/htdocs/humhub:d0000#CPU 300 #MEM 256000
#CGI 786762 #NPROC 120 #TAID 88640530 #LANG 3 #STAT 1 #CHROOT 8'
'REDIRECT_DBENTRY_DOCROOT' =>
'/kunden/homepages/5/d673757836/htdocs/humhub' 'REDIRECT_DBENTRY_HASH' =>
'd0000' 'REDIRECT_DBENTRY__CPU' => '300' 'REDIRECT_DBENTRY__MEM' =>
'256000' 'REDIRECT_DBENTRY__CGI' => '786762' 'REDIRECT_DBENTRY__NPROC' =>
'120' 'REDIRECT_DBENTRY__TAID' => '88640530' 'REDIRECT_DBENTRY__LANG' =>
'3' 'REDIRECT_DBENTRY__STAT' => '1' 'REDIRECT_DBENTRY__CHROOT' => '8'
'REDIRECT_DBENTRY' =>
'/kunden/homepages/5/d673757836/htdocs/humhub:d0000#CPU 300 #MEM 256000
#CGI 786762 #NPROC 120 #TAID 88640530 #LANG 3 #STAT 1 #CHROOT 8'
'REDIRECT_HANDLER' => 'x-mapp-php5.5' 'REDIRECT_STATUS' => '200'
'SCRIPT_URL' => '/index.php' 'SCRIPT_URI' => 'http://humhub.ca/index.php'
'DBENTRY_HOST' => 'humhub.ca' 'DBENTRY_VALUE' =>
'/kunden/homepages/5/d673757836/htdocs/humhub:d0000#CPU 300 #MEM 256000
#CGI 786762 #NPROC 120 #TAID 88640530 #LANG 3 #STAT 1 #CHROOT 8'
'DBENTRY_DOCROOT' => '/kunden/homepages/5/d673757836/htdocs/humhub'
'DBENTRY_HASH' => 'd0000' 'DBENTRY__CPU' => '300' 'DBENTRY__MEM' =>
'256000' 'DBENTRY__CGI' => '786762' 'DBENTRY__NPROC' => '120'
'DBENTRY__TAID' => '88640530' 'DBENTRY__LANG' => '3' 'DBENTRY__STAT' => '1'
'DBENTRY__CHROOT' => '8' 'DBENTRY' =>
'/kunden/homepages/5/d673757836/htdocs/humhub:d0000#CPU 300 #MEM 256000
#CGI 786762 #NPROC 120 #TAID 88640530 #LANG 3 #STAT 1 #CHROOT 8'
'HTTP_HOST' => 'humhub.ca' 'HTTP_ACCEPT' => 'application/json,
text/javascript, */*; q=0.01' 'HTTP_X_CSRF_TOKEN' =>
'TEdDTWhydko.CxAJO0c.LBQ2Ln4kGDUvFgxzPSsGNwY.DhUYGREyBw=='
'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' =>
'Mozilla/5.0 (Linux; Android 7.0; LG-H831 Build/NRD90U) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36'
'HTTP_REFERER' => 'http://humhub.ca/index.php?r=dashboard%2Fdashboard'
'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' =>
'en-CA,en-GB;q=0.8,en-US;q=0.6,en;q=0.4' 'HTTP_COOKIE' =>
'_csrf=186381eb83b19cf0589a349ee1bdaeda72e65218736b3b628792e521652ba5aba%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22rLSDS5HfXqm3LjCeZK0pCtALrIVUqcDM%22%3B%7D;
pm_getting-started-panel=expanded;
PHPSESSID=71e523a29334856359c23ceab2cce14f;
_identity=f3482bddb20ccea9e0b94a1cf718ad49db97beaa1700d46c4cff120f6889c7e2a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%225bbe247e-2411-4ff7-aab6-8413d647afdb%22%2C2592000%5D%22%3B%7D'
'PATH' => '/bin:/usr/bin' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' =>
'Apache' 'SERVER_NAME' => 'humhub.ca' 'SERVER_ADDR' => '172.30.80.19'
'SERVER_PORT' => '80' 'REMOTE_ADDR' => '209.171.88.190' 'DOCUMENT_ROOT' =>
'/kunden/homepages/5/d673757836/htdocs/humhub' 'SERVER_ADMIN' => '
webmaster@humhub.ca' 'SCRIPT_FILENAME' =>
'/kunden/homepages/5/d673757836/htdocs/humhub/index.php' 'REMOTE_PORT' =>
'51344' 'REDIRECT_QUERY_STRING' =>
'r=dashboard%2Fdashboard%2Fstream&mode=normal&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=8&StreamQuery%5BsuppressionsOnly%5D=false'
'REDIRECT_URL' => '/index.php' 'GATEWAY_INTERFACE' => 'CGI/1.1'
'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' =>
'r=dashboard%2Fdashboard%2Fstream&mode=normal&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=8&StreamQuery%5BsuppressionsOnly%5D=false'
'REQUEST_URI' =>
'/index.php?r=dashboard%2Fdashboard%2Fstream&mode=normal&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=8&StreamQuery%5BsuppressionsOnly%5D=false'
'SCRIPT_NAME' => '/index.php' 'STATUS' => '200' 'ORIG_PATH_INFO' =>
'/index.php' 'ORIG_PATH_TRANSLATED' =>
'/kunden/homepages/5/d673757836/htdocs/humhub/index.php' 'PHP_SELF' =>
'/index.php' 'REQUEST_TIME_FLOAT' => 1491318571.8917 'REQUEST_TIME' =>
1491318571 'argv' => [ 0 => 'r=dashboard%2Fdashboard%2Fstream&mode=normal

**Comment by buddh4** [comment]
```
PHP - INTL Extension - ICU Version (4.4.1)(Hint: ICU Data 4.8.1 or higher is required) 
PHP - INTL Extension - ICU Data Version (4.4.0.1) (Hint: ICU Data 4.8.1 or higher is required)
```

You'll have to update this package.

**Comment by rapidpage** [comment]
Ok

**Comment by rapidpage** [comment]
Please close this issue, I have moved my instance of humhub to a new server and it is working
