### ISSUE TITLE
Meeting module : task can't pick user

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2448]
User selection doesn't work on Task (OK for moderators).

## Tasks
![image](https://cloud.githubusercontent.com/assets/12234510/24634533/b2896eee-18ce-11e7-88fc-35e47762b607.png)

## Moderators
![image](https://cloud.githubusercontent.com/assets/12234510/24634555/c6959c28-18ce-11e7-9f06-ec007e339698.png)

**Comment by paviro** [comment]
I am having the same problem..

**Comment by acs-ferreira** [comment]
I think module is using deprecated method `UserPicker` instead of `UserPickerField` so it must be updated.

**Comment by acs-ferreira** [comment]
Take this file as example `protected/modules/tasks/views/task/edit.php` and you should solve it easily.
I can't help more as i'm not using the module.
