### ISSUE TITLE
Bug for \zhuravljov\yii\queue\Queue

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2450]
Invalid Configuration – yii\base\InvalidConfigException
Object configuration must be an array containing a "class" element.

in [/humhub/protected/vendor/zhuravljov/yii2-queue/src/Queue.php:46](https://github.com/humhub/humhub/commit/ac3ef620565f3c5592d6ae75103e74aac00052d4#commitcomment-21616291)

Ref https://github.com/humhub/humhub/commit/ac3ef620565f3c5592d6ae75103e74aac00052d4

**Comment by luke-** [comment]
Did you ran composer update?

**Comment by githubjeka** [comment]
Oh, no )))
