### ISSUE TITLE
User picker not working

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub#2452]
When i type @(user) no results happen

**Comment by buddh4** [comment]
Which user picker (where)?
Which HumHub version, did you recently updated your installation?
What happens exactly, is it loading or is there a text saying no result?
Please always add as much information as possible.

**Comment by rapidpage** [comment]
Sorry for being so vague, it is the latest community version beta 4, yes i
did update, it is when i am trying to reply to a thread or sending a new
thread, i am using php v7

**Comment by rapidpage** [comment]
Please close this issue, I have moved my instance of humhub to a new server and it is working
