### ISSUE TITLE
Cron not working

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub#2453]
Version beta 4
Error message:
$_GET = [ 'r' => 'admin/information/cronjobs' ] $_SERVER = [ 'REDIRECT_SCRIPT_URL' => '/index.php' 'REDIRECT_SCRIPT_URI' => 'http://humhub.ca/index.php' 'REDIRECT_DOCUMENT_ROOT' => '/kunden/homepages/5/d673757836/htdocs/humhub' 'REDIRECT_UI_SUEXEC_FSTATD_UNIXSOCKET' => '/var/run/ui-fstatd.suexec.socket' 'REDIRECT_DBENTRY_HOST' => 'humhub.ca' 'REDIRECT_DBENTRY_VALUE' => '/kunden/homepages/5/d673757836/htdocs/humhub:d0000#CPU 300 #MEM 256000 #CGI 786762 #NPROC 120 #TAID 88640530 #LANG 3 #STAT 1 #CHROOT 8' 'REDIRECT_DBENTRY_DOCROOT' => '/kunden/homepages/5/d673757836/htdocs/humhub' 'REDIRECT_DBENTRY_HASH' => 'd0000' 'REDIRECT_DBENTRY__CPU' => '300' 'REDIRECT_DBENTRY__MEM' => '256000' 'REDIRECT_DBENTRY__CGI' => '786762' 'REDIRECT_DBENTRY__NPROC' => '120' 'REDIRECT_DBENTRY__TAID' => '88640530' 'REDIRECT_DBENTRY__LANG' => '3' 'REDIRECT_DBENTRY__STAT' => '1' 'REDIRECT_DBENTRY__CHROOT' => '8' 'REDIRECT_DBENTRY' => '/kunden/homepages/5/d673757836/htdocs/humhub:d0000#CPU 300 #MEM 256000 #CGI 786762 #NPROC 120 #TAID 88640530 #LANG 3 #STAT 1 #CHROOT 8' 'REDIRECT_HANDLER' => 'x-mapp-php5.5' 'REDIRECT_STATUS' => '200' 'SCRIPT_URL' => '/index.php' 'SCRIPT_URI' => 'http://humhub.ca/index.php' 'DBENTRY_HOST' => 'humhub.ca' 'DBENTRY_VALUE' => '/kunden/homepages/5/d673757836/htdocs/humhub:d0000#CPU 300 #MEM 256000 #CGI 786762 #NPROC 120 #TAID 88640530 #LANG 3 #STAT 1 #CHROOT 8' 'DBENTRY_DOCROOT' => '/kunden/homepages/5/d673757836/htdocs/humhub' 'DBENTRY_HASH' => 'd0000' 'DBENTRY__CPU' => '300' 'DBENTRY__MEM' => '256000' 'DBENTRY__CGI' => '786762' 'DBENTRY__NPROC' => '120' 'DBENTRY__TAID' => '88640530' 'DBENTRY__LANG' => '3' 'DBENTRY__STAT' => '1' 'DBENTRY__CHROOT' => '8' 'DBENTRY' => '/kunden/homepages/5/d673757836/htdocs/humhub:d0000#CPU 300 #MEM 256000 #CGI 786762 #NPROC 120 #TAID 88640530 #LANG 3 #STAT 1 #CHROOT 8' 'HTTP_HOST' => 'humhub.ca' 'HTTP_CACHE_CONTROL' => 'max-age=0' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 7.0; LG-H831 Build/NRD90U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 'HTTP_REFERER' => 'android-app://com.google.android.googlequicksearchbox' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'en-CA,en-GB;q=0.8,en-US;q=0.6,en;q=0.4' 'HTTP_COOKIE' => 'PHPSESSID=8f22ad1abff46f2ac2ab0d30f4d10e16; _csrf=186381eb83b19cf0589a349ee1bdaeda72e65218736b3b628792e521652ba5aba%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22rLSDS5HfXqm3LjCeZK0pCtALrIVUqcDM%22%3B%7D; pm_getting-started-panel=expanded; _identity=f3482bddb20ccea9e0b94a1cf718ad49db97beaa1700d46c4cff120f6889c7e2a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%225bbe247e-2411-4ff7-aab6-8413d647afdb%22%2C2592000%5D%22%3B%7D' 'PATH' => '/bin:/usr/bin' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SERVER_NAME' => 'humhub.ca' 'SERVER_ADDR' => '172.30.80.19' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '209.171.88.190' 'DOCUMENT_ROOT' => '/kunden/homepages/5/d673757836/htdocs/humhub' 'SERVER_ADMIN' => 'webmaster@humhub.ca' 'SCRIPT_FILENAME' => '/kunden/homepages/5/d673757836/htdocs/humhub/index.php' 'REMOTE_PORT' => '40398' 'REDIRECT_QUERY_STRING' => 'r=admin%2Finformation%2Fcronjobs' 'REDIRECT_URL' => '/index.php' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=admin%2Finformation%2Fcronjobs' 'REQUEST_URI' => '/index.php?r=admin%2Finformation%2Fcronjobs' 'SCRIPT_NAME' => '/index.php' 'STATUS' => '200' 'ORIG_PATH_INFO' => '/index.php' 'ORIG_PATH_TRANSLATED' => '/kunden/homepages/5/d673757836/htdocs/humhub/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1491303612.3297 'REQUEST_TIME' => 1491303612 'argv' => [ 0 => 'r=admin%

**Comment by buddh4** [comment]
This is only a request log, please add the acutal error, which should reside under this info block.

**Comment by acs-ferreira** [comment]
And what means "not working"? This is not an error.

**Comment by rapidpage** [comment]
Sorry, will be more specific

**Comment by acs-ferreira** [comment]
This can be helpful in intranets where some posts are merely informative 
and we don't need to have discussions about it.

**Comment by rapidpage** [comment]
Formatting message for language 'en' failed with error: Message pattern is
invalid: Constructor failed. The message being formatted was: This field
only allows a maximum of {n,plural,=1{# space} other{# spaces}}.


[image: photo]
*Nicholas Hughes*
CEO, RapidPage.ca
p: 1-866-496-3073 | c: 1-905-818-7884 | f: 1-888-496-3073 <fax:c:
1-905-818-7884> | sales@rapidpage.ca | http://rapidpage.ca | Skype:
rapidpage <#> |
Caledonia, ON
<http://www.facebook.com/rapidpage.ca/>
<http://www.linkedin.com/company/rapidpage>  <http://twitter.com/rapidpage>
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=700224463896219>

**Comment by rapidpage** [comment]
Please close this issue, I have moved my instance of humhub to a new server
