### ISSUE TITLE
Duplicate menu items

### ISSUE THREAD

**Issue by frey1esm** [humhub/humhub#2454]
I ham seeing multiple cases of duplicate menu entries, both on the dashboard and also in admin. 

This happened on two completely different servers. One on an existing Humhub 1.0 installation (on a php 5.4 machine) and one on a fresh 1.2 beta install (using php7). 

![image](https://cloud.githubusercontent.com/assets/1666098/24656526/e9dafc04-1910-11e7-8507-124fc49cc003.png)

------------------------------

![image](https://cloud.githubusercontent.com/assets/1666098/24656536/f8c302fc-1910-11e7-8dbb-9771042703e8.png)

**Comment by buddh4** [comment]
This was fixed by https://github.com/humhub/humhub/commit/e99955f71bdada061f3a6975840afc98bdeb3c1b

**Comment by frey1esm** [comment]
OK. I searched "duplicate" and "multiple," but not "double."
