### ISSUE TITLE
ContentContainerController should be cut in half

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2459]
ContentContainerController::init too complicated in support.

For example 
[\humhub\modules\space\controllers\MembershipController::actionSearch](https://github.com/humhub/humhub/blob/45d3f273a2546c0afd1cd8c0627d77591bc7e626/protected/humhub/modules/space/controllers/MembershipController.php#L48-L64)

This action uses `$this->getSpace();` 
Although this action can be called from the user profile, then container will be the user, not a space.
This provide to the error 
> Calling unknown method: humhub\modules\space\controllers\MembershipController::getSpace()

**Comment by buddh4** [comment]
You mean a SpaceContainerController and UserContainerController as subclasses of ContentContainerController, and get rid of the SpaceController and ProfileController Behaviours.
Sounds good, but I think there are cases where you need this mixed behaviour. Perhaps just implement a SpaceController which blocks non space container requests.
