### ISSUE TITLE
ColorPickerField Uncaught TypeError: $container.colorpicker is not a function

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2460]
I just generate new CRUD gii and added the code in form

```php
<div id="<?= $containerId = time().'space-color-chooser-edit'; ?>">
        <?= \humhub\widgets\ColorPickerField::widget([
            'model' => $model,
            'field' => 'color',
            'container' => $containerId,
        ]) ?>
</div>
```

Widget doesn't  show and I get this js error in console

**Comment by buddh4** [comment]
Seems that the `@web-static/js/colorpicker/js/bootstrap-colorpicker-modified.js` was not loaded. The `humhub\assets\HumHubColorPickerAsset` should depend on this file.
