### ISSUE TITLE
To deprecated \humhub\components\Controller::$subLayout

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2463]
This property is  redundant, because the problems that it solves can be solved by 
[nested-layouts](http://www.yiiframework.com/doc-2.0/guide-structure-views.html#nested-layouts)

And when I use this property as `$this->subLayout= 'main';` in my action
this profile menu and options menus doesn't work,(no clicked)
![image](https://cloud.githubusercontent.com/assets/874234/24707189/565e9812-1a1b-11e7-971b-dc3ee9275e72.png)

to fix this I change to ` $this->layout = 'main';` and 
```php
<?php $this->beginContent('@app/humhub/views/layouts/main.php'); ?>
<div class="container">
    <?= $content ?>
</div>
<?php $this->endContent(); ?>
```

Declare this property deprecated and cut out it in the future ...

**Comment by luke-** [comment]
Yes, we're migrate step by step to view wrappers.
