### ISSUE TITLE
Mobile Scrolling

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2465]
At the moment when you're scrolling it's pretty easy, but once you open notifications or even My Spaces you'll find that scrolling is very hard to do, this needs fixed, I see that the fix is however found within the mail module. So my guess is that a `container` is missing somewhere?

**Android version: 5.1+**

**Comment by acs-ferreira** [comment]
We should use` .modal-open` nuke on Bootsrap.
https://github.com/twbs/bootstrap/pull/6342

Add that class to `body` when dropdown is opened.

**But...** 
HumHum is blocking the Nuke, any reason for this??
https://github.com/humhub/humhub/blob/45d3f273a2546c0afd1cd8c0627d77591bc7e626/static/less/modal.less#L16

**Comment by Felli** [comment]
Using the following somewhat helps.
```
.modal-open {
  overflow: scroll;
}
```
But I'm guessing using `auto` would be one of the best way of fixing this issue to some extent.

**Comment by Felli** [comment]
I've somewhat found a way of fixing this within an Andoird app, tho it might end up being a slight hack-osh way of doing so.
http://stackoverflow.com/questions/3866499/two-directional-scroll-view

**Comment by buddh4** [comment]
I'am also not sure why this was blocked in the first place, seems to be a relict and is rather annoying.

**Comment by buddh4** [comment]
Seems to be an issue with nicescroll, unfortunately the nicescroll project does not seem to be very active at the moment...
The following script worked for me for the space chooser:

```
this.$chooser.on('touchmove', function(evt) {
    evt.preventDefault();
});
```
after https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/resources/js/humhub.space.chooser.js#L42

**Comment by Felli** [comment]
@buddh4 I like nicescroll and all but I find [smoothscroll](https://github.com/cferdinandi/smooth-scroll) seems more stable, is there any reason behind nicescroll still being used?

**Comment by buddh4** [comment]
Don't know, but smoothscroll seems to focus on scroll animations and not the styling of scrollbars?

**Comment by Felli** [comment]
@buddh4 You're right with that statement, smoothscroll focuses on scroll animation over styling of the scrollbars themselves, in other words it leaves styling up to the browser being used. The only other option that I can think of that would be just as good would be [nanoScroller](https://github.com/jamesflorentino/nanoScrollerJS), which does supports the use of [Overthrow](https://github.com/filamentgroup/Overthrow/) which I will fully support for responsive design.

**Comment by buddh4** [comment]
Doesn't seem very active either. I don't know how flexible this framework is, but I prefer the modest nicescroll style. But if you like, you could integrate this into the community theme, perhaps it fits as well with a bit styling. I'll test the newest nicescroll version with one of the suggested patches.

**Comment by Felli** [comment]
I've already tried using scrollme which wasn't a bad choice, but  I'll take you up on your suggestion. :smile:

**Comment by Felli** [comment]
>Seems to be an issue with nicescroll, unfortunately the nicescroll project does not seem to be very active at the moment...
The following script worked for me for the space chooser:
> ```
> this.$chooser.on('touchmove', function(evt) {
>    evt.preventDefault();
> });
> ```
> after https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/resources/js/humhub.space.chooser.js#L42

Hmm... After trying this it would seem to make things slightly worse off for custom themes, I'll try some more things to fix this later today.

**Comment by acs-ferreira** [comment]
What about replace all those things with "one size fits all" like **Swiper**?

http://idangero.us/swiper/
https://github.com/nolimits4web/swiper/

Very active, tiny, powerful, mobile ready and a lot of functions built in.

**Comment by Felli** [comment]
@acs-ferreira & @buddh4 do you think adding `<meta name="HandheldFriendly" content="true">` to [main.php](https://github.com/humhub/humhub/blob/master/protected/humhub/views/layouts/main.php) after line 12 could help?

**Comment by acs-ferreira** [comment]
This tag is completely obsoleted by `viewport` tag. https://github.com/humhub/humhub/blob/master/protected/humhub/views/layouts/main.php#L13

**Comment by Felli** [comment]
@acs-ferreira I bring this up because of reading [this](http://blog.javierusobiaga.com/stop-using-the-viewport-tag-until-you-know-ho). Continued reading from another post [here](http://a11yproject.com/posts/never-use-maximum-scale/).

**Comment by acs-ferreira** [comment]
Link 1 : Yes, viewport should be used only on responsives sites.

Link2 : Agree and disagree. Sometimes zoom can be a pain in th a** so 
there are pros and cons.
The disabled zoom offers you an "app like" experience and IMO it is a 
good option in HumHub.

But, i repeat, the tag is obsolete :)

**Comment by Felli** [comment]
Only brought the tag up as an alternative means, removing `maximum-scale=1.0` which also helped make what @buddh4 provided in https://github.com/humhub/humhub/issues/2465#issuecomment-292551435

**Comment by acs-ferreira** [comment]
IMHO, the best option is to suppress background scroll.
My [1st comment](https://github.com/humhub/humhub/issues/2465#issuecomment-292368210).

**Comment by Felli** [comment]
Hmm... I've been working on it slightly. And with some work adding the following plus what @buddh4 provided it is somewhat smoother when scrolling via mobile, tho the notification dropdown still has this issue.

```
.modal-open {
  overflow: hidden;
}

.modal {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: $zindex-modal;
  display: none;
  overflow-y: hidden;
  outline: 0;
```

**Comment by martinbeek** [comment]
In response to the "viewport" related messages:

Regarding Apple.
As per ios 10.1, trying to disable zooming on ios devices by means of meta tags is disabled. Big brother Apple thinks it's a better experience if we all are able to zoom, despite what the designer of the site has in mind... 

So, on iOS devices, the only way to prevent zooming is via javascript.  
See my solution in #2270 

This is what i use, and many others, who like to restrict webapp zooming on ios. 

Martin.

**Comment by Felli** [comment]
@martinbeek thank you for the insight, tho I also believe that zooming is alright to a degree, for example; one of the members from the old community of Humhub was creating a site for the elderly, if you're creating a community site for the elderly then you'll most likely want this feature. As for overall the above code plus that of @buddh4's makes the issue with double scrolling for "My Spaces" & the normal site scrolling, disappear, now all that is needed is that of the notifications.

**Comment by martinbeek** [comment]
How i solved this on a few other websites, is to introduce a function "releaseAppScale()" that i call when i open a lightbox or gallery; and i call "restrictAppScale()" again when i close the lightbox or gallery.  
I've found the place to put the call to my releaseAppScale() in humhub (click on image), but 
I'm still looking for the right place in humhub to detect closure of the gallery. 

Martin

**Comment by martinbeek** [comment]
By the way, if you DO enable zooming on humhub, some clicks will jump and zoom like crazy on mobile - at least on my iphone 7. E.g. clicking the My Spaces button auto-zooms to the spaces list and when clicking the new comments toggle, i'm totally "off the map" and i'm launched all the way to the top of to the bottom of the stream. Disabling zoom solves that. 

M

**Comment by Felli** [comment]
@martinbeek I believe this is an issue with [nicescroll](https://github.com/inuyaksa/jquery.nicescroll) itself not HumHub.
