### ISSUE TITLE
Q: Override translations

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2466]
What is the best way to override translations and keep them after an update?
Any docs?

Thanks.

**Comment by buddh4** [comment]
http://docs.humhub.org/admin-translations.html#overwrite-translation-messages

**Comment by acs-ferreira** [comment]
@buddh4 i've override everything with success, but i can't override this file:

`protected/humhub/modules/activity/messages/en/views_activities_ActivitySpaceMemberAdded.php`

I've tried `ActivityModule.views_activities_ActivitySpaceMemberAdded.php` but nothing...

What i'm doing wrong? Thanks.
