### ISSUE TITLE
Restricting users to one group

### ISSUE THREAD

**Issue by frey1esm** [humhub/humhub#2467]
Version 1.1 added the ability for users to belong to multiple groups.

Is there a way to switch this new capability off? This totally mashed my API!

**Comment by buddh4** [comment]
There is no built-in way, perhaps you can listen to the BEFORE_SAVE event of the [GroupUser](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/GroupUser.php) model, and block it in case the user is already assigned to a group.
