### ISSUE TITLE
Empty default group dropdown in administration humhub 1.1.2

### ISSUE THREAD

**Issue by dcantos** [humhub/humhub#2468]
Empty default group dropdown in administration humhub 1.1.2

please help.-

![humhub](https://cloud.githubusercontent.com/assets/6325635/24776719/b455e2fa-1ae7-11e7-9630-b79977e0e8dd.png)

**Comment by buddh4** [comment]
Have you defined a default group at "Administration -> Users -> Settings -> Default Group"?`
Otherwise you could create a group and selecte the "Show At Registration" in the group settings.
