### ISSUE TITLE
Q: Disable "Read full post..."

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2469]
I would like to disable the mention "**Read full post...**" and always have the full post at the screen.

How can i disable this functionality?

![image](https://cloud.githubusercontent.com/assets/12234510/24801928/58a25992-1ba6-11e7-9261-12dc16f0f1e8.png)

**Comment by buddh4** [comment]
this script should do it
```
humhub.event.on('humhub:modules.ui.showMore:beforeInit', function(evt, module) {
 module.init = function() {};
});
```

**Comment by acs-ferreira** [comment]
Perfect, thanks. 👍

**Comment by 001101** [comment]
How is that possible for comments?

**Comment by 001101** [comment]
I integrated it, but there is still the "load more" button text when the post has many comments.

**Comment by buddh4** [comment]
Unfortunately this is currently hardcoded [here](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/comment/widgets/Comments.php#L32). I'll add this to the wishlist for the upcoming version.

**Comment by 001101** [comment]
Ahh cool, thank you very much for showing it me directly in the code, that is perfect, it is still not so easy for me to find such things. 

I will change it there ☺️

**Comment by BaconTriple** [comment]
I know this is from 2017 but that script above doesn't change the behavior for me so I assume functionality has changed. I really need the site to show the full post all the time and completely remove the read more option. Is there a way of extending how long a post can be before this kicks in or disable it altogether as there's no information online except this thread.

Thank you,

Josh

**Comment by luke-** [comment]
@BaconTriple With Humhub 1.11 there is a direct post link always with full texts. Maybe this helps.

**Comment by DHS1001** [comment]
> this script should do it
> 
> ```
> humhub.event.on('humhub:modules.ui.showMore:beforeInit', function(evt, module) {
>  module.init = function() {};
> });
> ```

Can you please advise where to put this scrip? Thanks a lot
