### ISSUE TITLE
Reported Posts are displayed as blank line in Notifications

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2473]
v1.2beta4
If a user reports content, there is no notification to the admin anymore. It seems that the report is notified as a blank line in the Notifications list. No email to admin either.
There is no way to know if a report is made, apart from going to the report content admin screen.

**Comment by acs-ferreira** [comment]
Isn't this related to https://github.com/humhub/humhub-modules-reportcontent ?

**Comment by martinbeek** [comment]
Perhaps...
