### ISSUE TITLE
Q: Disable comments

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2476]
**Question:** Is it possible to:
- Disable comments per **_post_**
- Disable comments per **_space_**

Thanks.

**Comment by Felli** [comment]
Not that I know of, of course you're able to disable comments completely, but not recommended.

**Comment by acs-ferreira** [comment]
This can be helpful in intranets where some posts are merely informative and we don't need (want) to have discussions about it.

**Comment by redlaguna** [comment]
@acs-ferreira I have seen it in the space permissions that if possible, but there is no option for it to be for each post 
![comments](https://cloud.githubusercontent.com/assets/26610628/24834372/a97271f6-1ca8-11e7-9b0d-5fe1012f2a5e.png)

**Comment by Felli** [comment]
@redlaguna this is because it would have to be extended sadly.

**Comment by acs-ferreira** [comment]
Thanks @redlaguna i've missed that setting, it helps a lot! 👍
