### ISSUE TITLE
Users can not upload profile banner >3.146mb

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2477]
My php and admin settings are set much higher, but users get error. Also on the community humhub site.
See pics.

![img_3413](https://cloud.githubusercontent.com/assets/6781157/24837856/9e172b5e-1d3d-11e7-8d99-783e06f842aa.PNG)
![img_3414](https://cloud.githubusercontent.com/assets/6781157/24837857/9e3d8d76-1d3d-11e7-8fad-ee729793b488.PNG)

**Comment by acs-ferreira** [comment]
It is defined as is in the code: https://github.com/humhub/humhub/blob/dc6ad90fb506920895fe43603f56abbb1252364e/protected/humhub/models/forms/UploadProfileImage.php#L35

The value on Admin settings apply only to uploaded files on the Stream.

**Comment by martinbeek** [comment]
Thanks, that's cool. 

M.
