### ISSUE TITLE
Can I use this web application which lincesed under AGPL for my closed source project

### ISSUE THREAD

**Issue by heisenberg1901** [humhub/humhub#248]
I want to develop my own site using your app Humhub.
I want to modify it for matching with my requirements.
Also I want my code to be closed source for security reasons, is this possible?

**Comment by heisenberg1902** [comment]
@andystrobel, any updates on this topic?
I have sent you mail regarding this months back, but you want me to reveal identity and product details, which is not possible, cause my product name is self-explanatory.
:laughing:

**Comment by mtangoo** [comment]
Any update?

**Comment by luke-** [comment]
https://www.humhub.org/en/commercial
