### ISSUE TITLE
How to refresh current content wallEntry via js?

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2483]
I have a button to send ajax

```js
var btnAjax= function (evt) {
        client.post(evt.url).then(function (response) {

           // ??? How to refresh current wallEntry

        }).catch(function (err) {
            module.log.error(err, true);
        });
    };
```

in controller:
```php
    return $this->renderAjaxContent($myContentAR->getWallOut());
```

p.s. Now I get error when click the button
>An unexpected error occured. If this keeps happening, please contact a site administrator.
![image](https://cloud.githubusercontent.com/assets/874234/24863506/c6119e88-1e09-11e7-891e-a8f68a8a2392.png)

**Comment by Felli** [comment]
Something similar to [this](http://stackoverflow.com/questions/19889100/ajax-reload-div-content-on-click-button)?

**Comment by githubjeka** [comment]
Thanks, but I thought maybe it's already implemented in js core

**Comment by buddh4** [comment]
Something like this should work:
```
var stream = require('stream').getStream();

// Get stream entry by content id (Note stream entry has to be present in the stream):
var entry = stream.entry(contentId);

// reload stream entry
entry.reload();

// replace whole entry node
entry.replaceWith(node);

// replace only content
entry.replaceContent(contentNode);
```

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/stream/resources/js/humhub.stream.js

You can render the full stream entry (with streamentry wrapper) with https://github.com/humhub/humhub/blob/master/protected/humhub/modules/stream/actions/Stream.php#L277

**Comment by githubjeka** [comment]
Thanks @buddh4 
My raw solution, but working...

**Button** (for me it in WallEntryAddons...)
```php
 <?= \humhub\libs\Html::a(\Yii::t('TrackerIssuesModule.views', 'Finish issue'), '#',
        [
            'data-action-click' => 'tracker.finishIssue',
            'data-action-url' => $object->content->container->createUrl(
                '/' . \tracker\Module::getIdentifier() . '/issue/edit',
                ['id' => $object->id]
            ),
        ]
    ) ?>
```

**javascript code** for the button

```js
humhub.module('tracker', function (module, require, $) {
    var stream = require('stream').getStream();

    var finishIssue = function (evt) {
        var entry = stream.entry(
            evt.$target.closest(".wall-entry").data('contentKey')
        );
        client.post(evt.url, {
            'data': {'IssueRequest[status]': 40},
            'dataType': 'html'
        }).then(function () {
            entry.reload();
        }).catch(function (err) {
            module.log.error(err, true);
        });
    };

};
```

**Controller**(no difference)
```php
       if ($model->load(\Yii::$app->request->post())) && $model->save()) {
                return $this->renderAjaxContent($model->getWallOut());
       }
```

**Comment by buddh4** [comment]
In case you do not use the backend action in another place you could also return something like this in your controller:
```
return $this->asJson(['success' => true]);
```

so you could get rid of the `dataType` setting.

Don't forget to export your actions (I think you just did not include it in your example)

```
module.export({
  finishIssue: finishIssue
})
```

**Comment by githubjeka** [comment]
I can't because this action used by EDIT FORM too. When:

```
<button type="submit" class="btn btn-block btn-primary btn-sm"            
                data-ui-loader
                data-action-click="editSubmit"
                data-action-url="...."          
        >Save</button>
```

`editSubmit` from core js requires `$this->renderAjaxContent($model->getWallOut());`
