### ISSUE TITLE
 Update version 1.201 Beta 4 but I can not add new users.

### ISSUE THREAD

**Issue by dcantos** [humhub/humhub#2484]
I get the following error when I try to add new users.

Help.

`PHP Fatal Error – yii\base\ErrorException

Class 'Locale' not found
1. in /home/lmcfoods/public_html/intra/intra/protected/humhub/libs/Iso3166Codes.php at line 527
518519520521522523524525526527528529530531532533534535536        "WF" => "681",
        "EH" => "212",
        "YE" => "967",
        "ZM" => "260",
        "ZW" => "263"
    );
 
    public static function country($code, $translate = true)
    {
        return \Locale::getDisplayRegion("_$code", $translate ? Yii::$app->language : 'en');
    }
 
    public static function phoneCode($code)
    {
        return (isset(static::$phoneCodes[strtoupper($code)])) ? static::$phoneCodes[strtoupper($code)] : 'N/A';
    }
 
    public static function isValid($code)
    {
2. yii\base\ErrorHandler::handleFatalError()
$_GET = [
    'r' => 'admin/user/add',
];

$_COOKIE = [
    'pm_getting-started-panel' => 'expanded',
    'pm_new-people-panel' => 'expanded',
    'pm_user-statistics-panel' => 'expanded',
    'pm_space-members-panel' => 'expanded',
    'language' => '4f1baab50c0967c8d3c9358e6af034f6ce14e982bbe5519d9ba70eb47da23b09a:2:{i:0;s:8:"language";i:1;s:2:"es";}',
    'PHPSESSID' => 'mv3u646hehtpnj9e1caidtmeg2',
    '_csrf' => '8ce79a3f3d61a668f710deca455e7ef8e1a2a36f651d24e79f32ea64ad1cb7f9a:2:{i:0;s:5:"_csrf";i:1;s:32:"y0D1yOS_VNh2XJL9bDShFQiHZT0jqC3e";}',
    '_identity' => '9a3580ddd50392ebd5710eba12c19957df7095b665ff0b60f4a03e7fe151de57a:2:{i:0;s:9:"_identity";i:1;s:50:"[1,"31d0c8d1-447c-4c60-9e21-13ac622b88fe",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 1,
    '__expire' => 1491844442,
    'user.canSeeAdminSection' => true,
    'live.poll.lastQueryTime' => 1491843037,
];`

**Comment by buddh4** [comment]
Make sure you have all required packages installed: http://docs.humhub.org/admin-requirements.html#required-php-extensions

Also check "Administration -> Information -> Prerequisites"
