### ISSUE TITLE
Stream could not be initialized!

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub#2487]
Event occurs only on 1 space, if i keep scrolling the page down i eventually get this:
![capture](https://cloud.githubusercontent.com/assets/8636793/24890305/1c1a0ada-1e3d-11e7-985d-534750b7f902.JPG)

Version: Currently installed version: 1.2.0-beta.4

ERROR:
exception 'yii\base\ErrorException' with message 'getimagesize(): corrupt JPEG data: 1 extraneous bytes before marker' in /home/bvke2bbg/public_html/humhub/protected/humhub/modules/file/libs/ImageConverter.php:106 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'getimagesize():...', '/home/bvke2bbg/...', 106, Array) #1 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/file/libs/ImageConverter.php(106): getimagesize('/home/bvke2bbg/...') #2 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/file/libs/ImageConverter.php(85): humhub\modules\file\libs\ImageConverter::allocateMemory('/home/bvke2bbg/...') #3 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/file/converter/PreviewImage.php(58): humhub\modules\file\libs\ImageConverter::Resize('/home/bvke2bbg/...', '/home/bvke2bbg/...', Array) #4 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/file/converter/BaseConverter.php(53): humhub\modules\file\converter\PreviewImage->convert('v6159add5') #5 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/file/converter/BaseConverter.php(64): humhub\modules\file\converter\BaseConverter->getFilename() #6 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/file/converter/PreviewImage.php(49): humhub\modules\file\converter\BaseConverter->getUrl() #7 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/file/widgets/views/showFiles.php(17): humhub\modules\file\converter\PreviewImage->render() #8 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/View.php(328): require('/home/bvke2bbg/...') #9 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/bvke2bbg/...', Array) #10 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/bvke2bbg/...', Array, Object(humhub\modules\file\widgets\ShowFiles)) #11 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(234): yii\base\View->render('showFiles', Array, Object(humhub\modules\file\widgets\ShowFiles)) #12 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/file/widgets/ShowFiles.php(45): yii\base\Widget->render('showFiles', Array) #13 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\modules\file\widgets\ShowFiles->run() #14 /home/bvke2bbg/public_html/humhub/protected/humhub/widgets/BaseStack.php(85): yii\base\Widget::widget(Array) #15 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\BaseStack->run() #16 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/content/widgets/views/wallEntry.php(81): yii\base\Widget::widget(Array) #17 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/View.php(328): require('/home/bvke2bbg/...') #18 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/bvke2bbg/...', Array) #19 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/bvke2bbg/...', Array, Object(humhub\modules\post\widgets\WallEntry)) #20 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(234): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\post\widgets\WallEntry)) #21 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/content/widgets/WallEntry.php(157): yii\base\Widget->render('@humhub/modules...', Array) #22 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(134): humhub\modules\content\widgets\WallEntry->renderWallEntry() #23 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/stream/actions/Stream.php(286): humhub\modules\content\components\ContentActiveRecord->getWallOut() #24 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/stream/actions/Stream.php(319): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\post\models\Post), false) #25 /home/bvke2bbg/public_html/humhub/protected/humhub/modules/stream/actions/Stream.php(232): humhub\modules\stream\actions\Stream::getContentResultEntry(Object(humhub\modules\content\models\Content)) #26 [internal function]: humhub\modules\stream\actions\Stream->run() #27 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #28 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array) #29 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('stream', Array) #30 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('space/space/str...', Array) #31 /home/bvke2bbg/public_html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #32 /home/bvke2bbg/public_html/humhub/index.php(25): yii\base\Application->run() #33 {main}

**Comment by gino909** [comment]
Same here after upgrading from 1.1.2 to 1.2 (not beta release)

![grafik](https://cloud.githubusercontent.com/assets/3649450/25765825/47e06b62-31ef-11e7-9eed-26b34cd0fcf7.png)

{
    "url": "/dashboard/dashboard/stream?mode=activity",
    "status": 500,
    "response": {
        "name": "Exception",
        "message": "Could not get contents underlying object! - contentid: 87",
        "code": 0,
        "type": "yii\\base\\Exception",
        "file": "/var/www/humhub/humhub-1.2.0/protected/humhub/modules/stream/actions/Stream.php",
        "line": 308,
        "stack-trace": [
            "#0 /var/www/humhub/humhub-1.2.0/protected/humhub/modules/stream/actions/Stream.php(232): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
            "#1 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
            "#2 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
            "#3 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
            "#4 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
            "#5 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('dashboard/dashb...', Array)",
            "#6 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
            "#7 /var/www/humhub/humhub-1.2.0/index.php(25): yii\\base\\Application->run()",
            "#8 {main}"
        ]
    },
    "textStatus": "error",
    "dataType": "json",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"name\":\"Exception\",\"message\":\"Could not get contents underlying object! - contentid: 87\",\"code\":0,\"type\":\"yii\\\\base\\\\Exception\",\"file\":\"/var/www/humhub/humhub-1.2.0/protected/humhub/modules/stream/actions/Stream.php\",\"line\":308,\"stack-trace\":[\"#0 /var/www/humhub/humhub-1.2.0/protected/humhub/modules/stream/actions/Stream.php(232): humhub\\\\modules\\\\stream\\\\actions\\\\Stream::getContentResultEntry(Object(humhub\\\\modules\\\\content\\\\models\\\\Content))\",\"#1 [internal function]: humhub\\\\modules\\\\stream\\\\actions\\\\Stream->run()\",\"#2 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)\",\"#3 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\\\base\\\\Action->runWithParams(Array)\",\"#4 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\\\base\\\\Controller->runAction('stream', Array)\",\"#5 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\\\base\\\\Module->runAction('dashboard/dashb...', Array)\",\"#6 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\\\web\\\\Application->handleRequest(Object(humhub\\\\components\\\\Request))\",\"#7 /var/www/humhub/humhub-1.2.0/index.php(25): yii\\\\base\\\\Application->run()\",\"#8 {main}\"]}",
        "responseJSON": {
            "name": "Exception",
            "message": "Could not get contents underlying object! - contentid: 87",
            "code": 0,
            "type": "yii\\base\\Exception",
            "file": "/var/www/humhub/humhub-1.2.0/protected/humhub/modules/stream/actions/Stream.php",
            "line": 308,
            "stack-trace": [
                "#0 /var/www/humhub/humhub-1.2.0/protected/humhub/modules/stream/actions/Stream.php(232): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
                "#1 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
                "#2 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
                "#3 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
                "#4 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
                "#5 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('dashboard/dashb...', Array)",
                "#6 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
                "#7 /var/www/humhub/humhub-1.2.0/index.php(25): yii\\base\\Application->run()",
                "#8 {main}"
            ]
        },
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "name": "Exception",
    "message": "Could not get contents underlying object! - contentid: 87",
    "code": 0,
    "type": "yii\\base\\Exception",
    "file": "/var/www/humhub/humhub-1.2.0/protected/humhub/modules/stream/actions/Stream.php",
    "line": 308,
    "stack-trace": [
        "#0 /var/www/humhub/humhub-1.2.0/protected/humhub/modules/stream/actions/Stream.php(232): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
        "#1 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
        "#2 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
        "#3 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
        "#4 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
        "#5 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('dashboard/dashb...', Array)",
        "#6 /var/www/humhub/humhub-1.2.0/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
        "#7 /var/www/humhub/humhub-1.2.0/index.php(25): yii\\base\\Application->run()",
        "#8 {main}"
    ],
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

**Comment by buddh4** [comment]
@gino909 run ` php yii integrity/run` in your protected directory

**Comment by gino909** [comment]
Hi @buddh4 
That solved my issue, thank you!
Gino

**Comment by 1337god** [comment]
PHP Core Warning 'yii\base\ErrorException' with message 'PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/xsl.so' - /usr/lib/php/20151012/xsl.so: undefined symbol: php_dom_create_object'

in ./Unknown:0

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

**Comment by githubjeka** [comment]
http://php.net/manual/en/xsl.installation.php
