### ISSUE TITLE
Enh: Add MarkdownEditor (SimpleMDE) to posts

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2488]
I would like to add actual **MarkdownEditor** to posts _(new post or post edit)_, any hints on how to accomplish this ?

What about this?
https://github.com/iisns/yii2-simplemde-markdown

**Demo:** https://simplemde.com/

Thanks.

**Comment by Felli** [comment]
You can implement this via theming with a little bit of JavaScript & CSS, just have a call to the original MarkdownEditor.

**Comment by buddh4** [comment]
We thought about using http://prosemirror.net/ in the future, it seems very flexible and includes collaborative editing features which would be nice fore wikis etc. But unfortunately its still in beta.

**Comment by acs-ferreira** [comment]
Thanks @buddh4 it looks promising.

But as the stable version as no ETA at this time, is there any possibility to include another editor, non-collaborative, to the posts?

The need is very small on a "normal" social network, but in an Intranet, the posts need to be a minimum formatted, and a lot of users just don't know what Markdown means...

Also take a look at https://stackedit.io/

**Comment by Felli** [comment]
@acs-ferreira for the theming it would be pretty nice, but the issue that I see with using StackEdit is the sheer size of it, ProseMirror is much smaller and does basically the same things without all of the unneeded stuff, even Quill is much smaller than StackEdit and does a lot of the same things, and has a open API already published. :smile:

**Comment by acs-ferreira** [comment]
Also OOTB:

• https://github.com/icron/yii2-simplemde-editor
• https://github.com/panwenbin/yii2-simplemde-markdown-editor
• https://github.com/iisns/yii2-simplemde-markdown

**Comment by acs-ferreira** [comment]
I've made a quick test, it could be integrated quickly & easily i think.

![image](https://cloud.githubusercontent.com/assets/12234510/25131412/ee141ef0-2445-11e7-9522-ab10438283ee.png)

**Comment by Felli** [comment]
@acs-ferreira I like the easiness of how it can be implemented. It also has CodeMirror bundled in, the only issue I have is autosaving.

**Comment by acs-ferreira** [comment]
Why is it an issue? It can be enabled or disabled.

**Comment by Felli** [comment]
Autosaving for me personally isn't needed, but if it can be disabled by toggling then I could understand using it.

**Comment by acs-ferreira** [comment]
The settings just need to be passed as an array in the widget.
See https://github.com/NextStepWebs/simplemde-markdown-editor/#configuration

Something like:

```
mdeOptions' => [
    'autosave' => [
        'enabled' => true,
        'uniqueId' => 'post_input_'. $post->id, //HumHum Post ID
        'delay' => 1000, //milliseconds between each autosave
    ],
]
```

It is disabled as default.

**Comment by buddh4** [comment]
looks, good, but does it also allow to integrate the current richtext features as emoji and mentionings? The thing is we don't want to switch those editors in every version and if possible only use one editor for all purposes, and prosemirror seems very clean and extensible and furthermore provides collaboration.

**Comment by acs-ferreira** [comment]
Yes, but as you've said they're on beta stage, and we have absolutely no idea about an ETA to stable versions.

Collaboration in a social network, i can see some pros in Wiki pages, but no more than that.

But it agree that it is a non-sense to switch between editors in time - _unless they're abandoned/not supported anymore_.

MDE is needed **today** IMHO, not in v2/next year ;-)

**Comment by Jonatasmz** [comment]
Someone could explain how can i implement the default MarkdownEditor on posts?

**Comment by buddh4** [comment]
The new wysiwyg richtext is already integrated in Humhub v1.3. HumHub v1.3 also added an abstraction for the Richtext and RichtextEditor widgets so you are able to implement own custom rich-texts and use them as default by configuration.

**Comment by hazmaniameur** [comment]
@buddh4  sorry to come back to this subject, but can you provide tutorial or any thing that can help me to implement another editor ........ please :D
