### ISSUE TITLE
Hi, I Can,t Login To HumHub As Admin

### ISSUE THREAD

**Issue by JoshuaLovesCode** [humhub/humhub#2489]
Hi, 
 I Can,t Login To HumHub!
My UserName Is Admin.
But It Won,t Let Me In! :'(

**Comment by buddh4** [comment]
Self hosted solution or HumHub cloud? If your projects is hosted in the cloud, contanct info@humhub.com

**Comment by JoshuaLovesCode** [comment]
Thanks! I Will Contact [info@humhub.com](mailto:info@humhub.com)!!

**Comment by JoshuaLovesCode** [comment]
Not Working :(

**Comment by buddh4** [comment]
What is not working? Didn't you get an answer or whats the problem?
