### ISSUE TITLE
Video Player ?

### ISSUE THREAD

**Issue by andrejvasilj** [humhub/humhub#2493]
Could you in next update integrate video player, every time  someone posts video i need to download it.

**Comment by buddh4** [comment]
There is a simple video player for mp4 files in 1.2.

**Comment by andrejvasilj** [comment]
where?

**Comment by Felli** [comment]
@andrejvasilj Humhub uses a simple but basic [jPlayer](http://jplayer.org/), this is of course used for MP3 as well as  MP4 files.

**Comment by andrejvasilj** [comment]
but why then I can't view videos that I uploaded in my space under FILES ? I CAN just download them

**Comment by petrk94** [comment]
@andrejvasilj  do you have a screenshot? This would help maybe

**Comment by buddh4** [comment]
are you sure v1.2 is installed or did you perhaps overwrite the file [protected/humhub/modules/file/widgets/views/showFiles.php](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/widgets/views/showFiles.php) file in your theme or something?

**Comment by Felli** [comment]
If you mean within the File module, then I would understand your problem, other than this, once you upload a MP4 file to a post then publish it just click on the video and it should start right up.

**Comment by andrejvasilj** [comment]
Yea, I was talking about File module, I can't view video only download it when I upload it in files

**Comment by acs-ferreira** [comment]
Player is not implemented on the **CFiles** module.
You can report/request it here https://github.com/humhub/humhub-modules-cfiles

**Comment by andrejvasilj** [comment]
tnx
