### ISSUE TITLE
unable to select recipient when entering new message

### ISSUE THREAD

**Issue by boonduck** [humhub/humhub#2496]
I am running a demo humhub site to check things out.
When I click the <New Message> button the <New Message> modal comes up.
I start typing the user's name in field <Recipient>, and a small selection windows pops up underneath the input field.
This popup lists the names of the users having these characters in their name.
As soon as I type enough letters to uniquely identify an user, I select the entry in the popup by clicking it.
Nothing happens.
Also, pressing <ENTER> does nothing.
I am unable to select the suggested user.
I tested this in recent versions of Google Chrome and Mozilla Firefox with identical results.
This behavior makes it impossible to enter new messages.
Can somebody please help to solve this? 

--boonduck
![unable-to-enter-recipient-in-new-message-3](https://cloud.githubusercontent.com/assets/24510107/25173111/485807fc-24f3-11e7-94bf-258c80138b76.jpg)

**Comment by boonduck** [comment]
UPDATE -- I just found out that this behavior occurs whan I am logged in as Administrator.
Logged in as a regular user, I am able to select the suggested user from the popup and continue entering the new message.

**Comment by buddh4** [comment]
Is your friendship system active? If yes, your users have to allow non friends to send them message. This will be "fixed" soon. But this behaviour should normaly be the same for all users.

**Comment by boonduck** [comment]
Thanks, buddh4, that did it. My friendship system was active in Administration / Settings. However, the user I was trying to message had in his Account Settings / Security / tab Other Users the setting Send Mail (allows the user to send mails) set on Default - Deny. Switching it to Allow solved the issue.
