### ISSUE TITLE
Search for content

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#25]

**Comment by LucasR93** [comment]
@bbrala I maybe just found something. Have a look into the file PostModule.
The code for adding a post to the search index is not active

```php
public static function onSearchRebuild($event)
    {
        foreach (Post::model()->findAll() as $obj) {
            #    HSearch::getInstance()->addModel($obj);
            print "p";
        }
    }
```

**Comment by chandruxp** [comment]
I was looking for a means to search on post and its comments. Is it possible with current humhub code?

**Comment by LateForLunch** [comment]
Would love to see this too!

**Comment by simon-roderus** [comment]
Me too :+1:

**Comment by deMENSEN-JVD** [comment]
+1

**Comment by christophlehmann** [comment]
+1

**Comment by binitprads** [comment]
+1

**Comment by binitprads** [comment]
+1

**Comment by luke-** [comment]
Will come in 0.12
https://github.com/humhub/humhub/commit/86f3d155af6f69caaa5773c378d554c6687351c8
