### ISSUE TITLE
oEmbed providers for Youtube report Syntax Error for "unauthorized videos"

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2501]
Youtube videos that are marked "embedding prohibited" by the movie's uploader give a api result of "unauthorized". The humhub oembed mechanism reports a App Syntax Error in the logfile for each time the URL is parsed; resulting in hudnreds of errors each day per video.

Example video that does not allow embedding: 

https://www.youtube.com/oembed?scheme=https&url=https://youtu.be/VIgqx7wjFc0&format=json&maxwidth=450

**Comment by acs-ferreira** [comment]
Try https://github.com/humhub/humhub/pull/2502

**Comment by martinbeek** [comment]
Top!
