### ISSUE TITLE
markdown links have no target attribute

### ISSUE THREAD

**Issue by globeFrEak** [humhub/humhub#2504]
Markdown links have no target attribute!

https://github.com/humhub/humhub/blob/master/protected/humhub/libs/Markdown.php#L51

I think, that external pages need an `target="_blank"` attribute!!

found on HumHub 1.2.0

**Comment by poeticpenguin** [comment]
This also happens when you created a site using the "Rich-Text-Editor". :(

**Comment by funkycram** [comment]
I think this issue should be closed. This one deals with the same subject and is more recent: https://github.com/humhub/humhub/issues/3989

**Comment by luke-** [comment]
@funkycram thanks!
