### ISSUE TITLE
Get information from other network 

### ISSUE THREAD

**Issue by Spartacus2018** [humhub/humhub#2506]
hello there, 

how explain that : 

First imagine I create a group with google Actualité, and i want feed this group automticaly with one post with one information comes from google actuality ?

Other thinks, with google u can create same alert, so can i integrate this alert and who him diretcly in humHub ?

exemple with Twetter, can i Create contact and get thier post dirtcly on humhub ?

the way is to make, all information u have on the humhub timeline, i don't want show information, only on my humhub, what do u think about this

thanks to all

**Comment by Felli** [comment]
At the moment you can only share to these via module, but there are modules that you can get content streamed from Facebook and Twitter via side widget. As for Google Plus you could create a Snippet with the Custom Pages module for this.

### Modules
[Facebook Module](https://github.com/GreenVolume/humhub-facebook-module)
[Twitter Module](https://github.com/WebCrew/HumHub-Twitter-Module)

> Note: Please read both of the module's `README.md` file before installing them!

**Comment by ychoucha** [comment]
Hello :

NOTE: I will no longer make use of HumHub and I stop updating my modules and themes for HumHub. It is up to you, you are welcome to update the modules and themes in the future.

so this module can't be used :/

**Comment by Spartacus2018** [comment]
Hello, 

can i have more information about this 

please

**Comment by Felli** [comment]
I've completely reworked the Twitter module itself, so it should work with HumHub v1.2+.
