### ISSUE TITLE
Including Custom Pages within views

### ISSUE THREAD

**Issue by barrelmonkey** [humhub/humhub#2507]
Is there currently a way to include custom page content within a view as part of an overall page?
On a related note is there currently a way to upload images or other assets that can then be included in views / content other than manually adding to the static folder?

Example.
I am customising the Dashboard view, replacing the Latest Activities panel with marketing panels. I have created a custom widget, and I would like this to be able to render content from a custom view that can be changed by the Administrators eg. sidePanel1. My widget would take a parameter of the custom page name / title / url and render it.

**Comment by Felli** [comment]
Hmm... I wonder if creating a  /views/custom_pages/views & /views/custom_pages/widgets folder then placing the needed files would work? :wink:

**Comment by buddh4** [comment]
Don't 100% understand the usecase but the custom pages module supports snippets.
