### ISSUE TITLE
Linkpreview module fails to show og-image

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2510]
Many times, the linkpreview module can't find the image for a linked url, even when the og-image tag is present on that site. About half of all links don't show an image. No errors in logs. 
Here is one such link that never shows an image although the og-image tag is there:

http://www.nu.nl/wetenschap/4642545/sterrenkundige-en-presentator-chriet-titulaer-73-overleden.html

**Comment by acs-ferreira** [comment]
Not sure about this, but it seems that module search for `<meta property` and not `<meta name`.

**Comment by martinbeek** [comment]
I'll parse them both, if property resolves to null or empty. Works fine now!

**Comment by acs-ferreira** [comment]
Yous should submit/share your code, it may help others :)

**Comment by martinbeek** [comment]
Oh yes sure, i'd be glad to do so, but hesitated to do so, because this is a commercial module.

**Comment by acs-ferreira** [comment]
Yes i know, i'm not using it, but nobody can do anything with only JS file.
I've "debugged" it with only accessing source code in a browser...

**Comment by buddh4** [comment]
think a selector like `meta[property="og:image"], meta[name="og:image"]` should work in this case?
