### ISSUE TITLE
Login Page not shown using IE 11

### ISSUE THREAD

**Issue by poeticpenguin** [humhub/humhub#2511]
Good morning,

I am experiencing a peculiar behavior when trying to login into Humhub using IE.

If someone tries to open "https://intra.[ourcompanyname].de", he will be redirected straight to the dashboard. The buttons to the login-page doesn't work either.

![error_ie](https://cloud.githubusercontent.com/assets/27803194/25330214/28756fd4-28df-11e7-896a-22df34d9267c.png)

Manually opening the url using "https://intra.[ourcompanyname].de/index.php?r=user%2Fauth%2Flogin" still redirects to the dashboard.

Out of six tested clients, just ONE Windows client (Win 8.1, IE11, newest IE updates installed) showed it correctly and got the login page.

It's all working fine in other browsers on all clients, whether it's Firefox, Chrome, Vivaldi, Opera, it works.

Hell, even Netscape Communicator is much more clever, although the overall design is broken!
![even_netscape](https://cloud.githubusercontent.com/assets/27803194/25330658/b30b4bb8-28e0-11e7-9361-f7fc3ea7e9c9.png)

Does anyone got a clue?

By the way, we are using LDAP-authentication, but a login-page should anyway shown nevertheless.

Thanks in advance

Best regards
Christian

**Comment by acs-ferreira** [comment]
If you enable `urlrewrite`, does it helps?
https://www.humhub.org/docs/guide-admin-installation.html#enable-url-rewriting-optional

Can't reproduce it on my side (IE11 or Edge, or any other browser).

**Comment by petrk94** [comment]
@poeticpenguin I would recommend to use Google Chrome instead an outdated IE 11 ;)

**Comment by poeticpenguin** [comment]
@acs-ferreira Hi there,
enabling URL-rewriting causes HumHub to not open at all, after editing the common.php file.

@petrk94 We are already deploying Firefox and Chrome in our company, don't worry. It's just that we still have some IE users in our company which would like to stick with IE.
And beside that, we are using some Windows servers (_To calm everyone down, we also use Ubuntu and OpenSuse <(") )_ on which we would like to stick with the default tools, thus meaning having the possibility to access Humhub using the IE.

**Comment by acs-ferreira** [comment]
Can you post your `common.php` content file please?

**Comment by petrk94** [comment]
@poeticpenguin maybe some off-topic, but does the user need IE for a special application?

**Comment by buddh4** [comment]
Did you disable guest access on your site? If you don't need it you should disable it under "Administration -> User -> Settings".

**Comment by poeticpenguin** [comment]
@buddh4 Yes, it is disabled, no guest access allowed at the moment.

@petrk94 Good question, but actually no, not for HumHub. But we do have software in the company for which the IE is the prefered browser and some users are just getting used to use IE for everything.

@acs-ferreira 

`return [
'params' => [
        'allowedLanguages' => ['de', 'en', 'fr', 'ar', 'bg', 'ca', 'cs', 'hu', 'ru', 'ja', 'pl', 'vi', 'nl', 'ko']
    ]
];
`

Adding the URL Rewrite-code causes Humhub not to start at all, so i removed it.

The .htaccess file looks like this:

`RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
`

If somebody would announce, that HumHub is not supported to be used with the IE, i would be totally fine with it But the fact, that it works for some people and for some not on very similar clients, that is weird.

**Comment by acs-ferreira** [comment]
Your `.htaccess` is not good and it is normal that it doesn't work.
See https://github.com/humhub/humhub/blob/master/.htaccess.dist

You can then add you own content after the line `RewriteEngine on`.

**Comment by petrk94** [comment]
@poeticpenguin I know a company which use SAP applications and need IE11 for that.
You can try to force the company IT to use Chrome with this extension which force the website to IE mode
https://chrome.google.com/webstore/detail/ie-tab/hehijbfgiekmjfkfjpbkbammjbdenadd?hl=de
Maybe its something interesting for you.

**Comment by poeticpenguin** [comment]
@acs-ferreira 
Thanks for the hint, i have now adjusted it and now i can get at least a login screen and login.
However, all the spaces are missing and it's still on the fritz. :(

![kaputte_ansicht](https://cloud.githubusercontent.com/assets/27803194/25475243/6399d8c6-2b36-11e7-89c5-a555d49c5382.png)

**Comment by acs-ferreira** [comment]
Sorry, i really don't understand German :)

Ave you any errors at **Administration > Information > Logging** page?

**Comment by poeticpenguin** [comment]
Yes, it is the latest version of HumHub.
There is no error shown at the logging page.

**Comment by buddh4** [comment]
You seem to use a custom theme, do you have the same problems with the default theme?

**Comment by poeticpenguin** [comment]
@buddh4 Yes same problem with the default theme. In fact, I've only adjusted the hex values for the colours to replace the overall blue to an overall green. 

So no big changes were made with the CSS-files.

**Comment by buddh4** [comment]
Have you updated to 1.2 recently or is this a fresh installation? As @acs-ferreira mentioned check the logs "Administration -> Information -> Logging" and also the developer console (`f12` in IE)  for errors.

**Comment by poeticpenguin** [comment]
@buddh4 
It is a fresh installation. However, i managed to find the bug, thanks to the developer mode.

I got this error when opening HumHub:

> the attached page targets document mode 7. some console apis and features may not be available

After some research, it seems like "Compatibility View" in IE causes this.
You have to untick the option "Display intranet sites in Compatibility View"! 🐧 

Thank you all so much for the help, it helped alot. :)

Cheers
poeticpenguin
