### ISSUE TITLE
Archived space still shows up in Directory and "new spaces" widget

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2515]
I've archived a space that contained content that is not allowed on our site. But the space still shows up in the Directory and in the space widget. It's fully accessible.

Is this a bug? Or, if not, what is the whole idea behind archiving? 

See picture of space in Directory and in widget on the right.

Thanks.
Martin

![schermafbeelding 2017-04-24 om 23 18 19](https://cloud.githubusercontent.com/assets/6781157/25359271/d2338af0-2944-11e7-8beb-06439c60e66e.PNG)

**Comment by buddh4** [comment]
Can't you just delete the space? The archived feature is rather intendet for archive a space which is not used anymore, but the content should be accessible for research purposes for example for old projects etc. If an archived space should be displayed in the directory is discussible. Perhaps we can make it configurable.
