### ISSUE TITLE
Bug in ./protected/humhub/modules/friendship/widgets/ManageMenu.php

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2516]
"Requests" and "Sent requests" sentences are never translated because the closing ")" is in the wrong place.

Row 46 reads:
`            'label' => Yii::t('FriendshipModule.base', 'Requests' . ' (' . $receivedRequestsCount . ')'),`
should read:
`            'label' => Yii::t('FriendshipModule.base', 'Requests') . ' (' . $receivedRequestsCount . ')',`

Row 54 reads:
`            'label' => Yii::t('FriendshipModule.base', 'Sent requests' . ' (' . $sentRequestsCount . ')'),`
should read:
`            'label' => Yii::t('FriendshipModule.base', 'Sent requests') . ' (' . $sentRequestsCount . ')',`

Martin

**Comment by acs-ferreira** [comment]
I've submitted a PR https://github.com/humhub/humhub/issues/2516 to fix this, thanks.
