### ISSUE TITLE
Summary emails received twice

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2519]
I receive **summary emails** twice.

Any other email like notifications/mentions are only received once.

Any idea about this behavior?

**Comment by Felli** [comment]
Do you have both Cron jobs settings setup? ( i.e hourly & daily)

**Comment by acs-ferreira** [comment]
Yes, both running.

**Comment by Felli** [comment]
The only time I get multiple Summary mail is when both of the following are used at the same time.

```
Crontab of user: USER
30 * * * * /home/USER/SITE/protected/yii cron/hourly >/dev/null 2>&1
00 18 * * * /home/USER/SITE/protected/yii cron/daily >/dev/null 2>&1

Or Crontab of root user
*/5 * * * * su -c "/home/USER/SITE/protected/yii  cron/hourly" USER >/dev/null 2>&1
0 18 * * * su -c "/home/USER/SITE/protected/yii  cron/daily" USER >/dev/null 2>&1
```

**Comment by acs-ferreira** [comment]
Only the first one is setup.

**Comment by Felli** [comment]
Try just using one of them to see if that fixes the issue.

**Comment by acs-ferreira** [comment]
What do you mean ?

My cron is

```
30 * * * * /home/USER/SITE/protected/yii cron/hourly >/dev/null 2>&1
00 18 * * * /home/USER/SITE/protected/yii cron/daily >/dev/null 2>&1
```

**Comment by Felli** [comment]
Just use one of those

### Example
`30 * * * * /home/USER/SITE/protected/yii cron/hourly >/dev/null 2>&1`
or
`00 18 * * * /home/USER/SITE/protected/yii cron/daily >/dev/null 2>&1`

**Comment by acs-ferreira** [comment]
Hum...

Each cron have different functions, both must be running.
