### ISSUE TITLE
email notification not working

### ISSUE THREAD

**Issue by danieldanizy** [humhub/humhub#252]
my email notification not working...i try to registe on humhub site..with a new email..and it worked.. i was redirected to a page saying thanks for registering..an email has ben sent to continue your registration...but when i checked....they didn't sent me any email..pls help

**Comment by Kanasagra-Jaydip** [comment]
@danieldanizy 
I have same issue on it!!!!
Can you tell me how to fix it?

Thanks,

**Comment by nunthu** [comment]
Same issue. Not getting email for notifications. No errrors. 

Help please

**Comment by gsivaprabu** [comment]
Hi,

Possible to check test mail() in humhub ?I am using Mail Transport Type => PHP
![mail](https://cloud.githubusercontent.com/assets/2444608/11385151/feb07cb4-933b-11e5-9e7c-be9b0b064be3.png)

**Comment by lukibsubekti** [comment]
If you have configured your Mailing settings in Administration page correctly, you need to run cronjob in your server. You can go to Cron Jobs menu in Administration page to see the cronjob commands. 
If you are in Windows server (eg. using XAMPP), you can try run the cronjob command via Windows command prompt to make sure your email notification is running well. The steps:
1. open command prompt
2. go to humhub protected directory (eg. `> cd "C:\web-projects\humhub\protected"`)
3. run `> yii cron/hourly`
4. check your user email

**Comment by LeftUse** [comment]
guys can u help me ?

**Comment by buddh4** [comment]
@LeftUse this is a closed and also pretty old issue, please consider asking the [Community](https://community.humhub.com) for help.
