### ISSUE TITLE
Erro na instalação 

### ISSUE THREAD

**Issue by edsantos213** [humhub/humhub#2521]
Se alguém puder ajudar por favor

Failed to create directory "/home/u132593945/public_html/protected/runtime/logs": mkdir(): Disk quota exceeded

**Comment by acs-ferreira** [comment]
As the message states, you have exceeded you disk quota on your hosting.
_(Como a mensagem indica, nao tem espaço livre no seu alojamento. Tente escrever em inglês por favor)._
