### ISSUE TITLE
Password policy/strength for invited users

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#2525]
Invited users can use passwords with just one letter (!)

It would be great if password policy can be set somewhere in the admin panel (length, upper-/lower case, mix of letters and numbers, special characters etc.)

Humhub version: 1.2.0

**Comment by acs-ferreira** [comment]
This should be, **at least**, hard-coded to a minimum default, like **5**.

**Comment by simonfranzen** [comment]
Can someone explain where I can find the password validator and is it possible to write a plugin with a custom validator. We have one installation where we need alls the stuff like "add number, upper and lower case character, ..." and one installation where the user can define whatever he likes, but it has to be a minumum of 12 characters. @luke- ? An override in a theme could also work for us, I just need a starting point. thanks you

**Comment by simonfranzen** [comment]
Why don't we use something like this https://github.com/kartik-v/yii2-password in the project?

**Comment by danielkesselberg** [comment]
I agree with you that register/self-invite/password-change logic looks a bit confusing right now. As a starting point i would look into https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/Password.php and try to overwrite the rules there. 

When a user receives a self invitation link or oauth is enabled you hit the registration controller first: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/controllers/RegistrationController.php. The form itself is managed by https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/forms/Registration.php and there is also the Password in use.

**Comment by acs-ferreira** [comment]
I agree, yii2-password could be easily implemented, at least their strength validator.
https://github.com/kartik-v/yii2-password#strengthvalidator-1

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/commit/4814c94ee11ece6862eeb5e80151803af6f530f5
