### ISSUE TITLE
Members disappearing from Directory and not accessible. Database issue?

### ISSUE THREAD

**Issue by eddiepiazza** [humhub/humhub#2530]
Hi, I have my community since long time working with 143 users.
I can see the list of all of them from Admin Panel but Directory only list around 50 of them.

My own account "as admin and first user" is not listed. this could be not a problem if people could still tagging me by @myuser, but the fact that even this function is not founding my profile.

There is a way to rescue all missing users and restore the list?

New users are correctly being listed. I am actually on HH 1.2

**Comment by buddh4** [comment]
Try rebuilding your search index: http://docs.humhub.org/admin-search.html#index-rebuilding

**Comment by eddiepiazza** [comment]
1.000.000 Thanks !
