### ISSUE TITLE
Error: "Attempt to steal file", what does it mean?

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2536]
My log is full with "Attempt to steal file". What does it mean?

Martin.

**Comment by martinbeek** [comment]
I have four pages of this error in one day:

Attempted to steal file: 49d89f09-0055-45ba-a551-fbdcae8a64ce

**Comment by Felli** [comment]
What exactly is the full error stack?

**Comment by martinbeek** [comment]
That is the full error stack....  
I will wait to later today 'til i have a few again, so i can copy the request part too. 

Martin.

**Comment by martinbeek** [comment]
It's in the code here: protected/humhub/modules/file/components/FileManager.php

```

34	     * @param string|array|File $files of File records or comma separeted list of file guids or single File record
35	     * @param boolean $steal steal when already assigned to other record
36	     */
37	    public function attach($files, $steal = false)
…	
59	                Yii::warning('Attempted to steal file: ' . $file->guid);
60	                continue;
```

**Comment by martinbeek** [comment]
INFO  Sun, 07 May 2017 10:45:35 +0200 application
$_GET = [ 'query' => 'u/snoekkie/post/post/post' 'uguid' => 'd7af0807-965f-4662-9c3e-9284a4cd3181' ] $_SERVER = [ 'USER' => 'www-data' 'HOME' => '/var/www' 'FCGI_ROLE' => 'RESPONDER' 'MOD_X_ACCEL_REDIRECT_ENABLED' => 'on' 'GEOIP_ADDR' => '162.158.111.106' 'GEOIP_COUNTRY_CODE' => '' 'GEOIP_COUNTRY_NAME' => '' 'GEOIP_REGION' => '' 'GEOIP_REGION_NAME' => '' 'GEOIP_CITY' => '' 'GEOIP_AREA_CODE' => '' 'GEOIP_LATITUDE' => '' 'GEOIP_LONGITUDE' => '' 'GEOIP_POSTAL_CODE' => '' 'SCRIPT_FILENAME' => '/var/www/pryv.nl/httpdocs/index.php' 'SCRIPT_NAME' => '/index.php' 'QUERY_STRING' => 'query=u/snoekkie/post/post/post' 'REQUEST_METHOD' => 'POST' 'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8' 'CONTENT_LENGTH' => '372' 'REQUEST_URI' => '/u/snoekkie/post/post/post' 'DOCUMENT_URI' => '/index.php' 'DOCUMENT_ROOT' => '/var/www/pryv.nl/httpdocs' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'HTTPS' => 'on' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_SOFTWARE' => 'nginx/1.6.2' 'REMOTE_ADDR' => '162.158.111.106' 'REMOTE_PORT' => '28091' 'SERVER_ADDR' => '145.131.21.89' 'SERVER_PORT' => '443' 'SERVER_NAME' => 'pryv.nl' 'REDIRECT_STATUS' => '200' 'HTTP_MOD_REWRITE' => '1' 'HTTP_HOST' => 'pryv.nl' 'HTTP_CONNECTION' => 'Keep-Alive' 'HTTP_ACCEPT_ENCODING' => 'gzip' 'HTTP_CF_IPCOUNTRY' => 'NL' 'HTTP_X_FORWARDED_FOR' => '92.108.150.12' 'HTTP_CF_RAY' => '35b2e765483f0ca7-AMS' 'HTTP_CONTENT_LENGTH' => '372' 'HTTP_X_FORWARDED_PROTO' => 'https' 'HTTP_CF_VISITOR' => '{\"scheme\":\"https\"}' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_ORIGIN' => 'https://pryv.nl' 'HTTP_X_CSRF_TOKEN' => 'RW9LOC1jUTADIQ5hHzU7YwspCA1vIgVZARYFaGtaFl4sIX9RVBE.fQ==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.9.4.3000 Chrome/39.0.2146.0 Safari/537.36' 'HTTP_CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8' 'HTTP_DNT' => '1' 'HTTP_REFERER' => 'https://pryv.nl/dashboard' 'HTTP_ACCEPT_LANGUAGE' => 'nl-NL' 'HTTP_COOKIE' => '__cfduid=dbcff089246982a73ab5ac1b6ae5f80ea1493133672; language=9c2c48f8ccececa78db90effe08f2de5f1b2e176942b361619e086c13369d2c0a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22nl%22%3B%7D; _csrf=321cbb67430f3c51ec9592b481f8c4cfc2285565a6b8448523b0ab23a74ca8fca%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22FNEY2VjSNFC5BATiDyNPF9GniN4iyroM%22%3B%7D; mb_img_req=2d8076c7f6997caf4535c7cc129506c12e5eec1d692578f9bea5af45212acb97a%3A2%3A%7Bi%3A0%3Bs%3A10%3A%22mb_img_req%22%3Bi%3A1%3Bs%3A26%3A%22lqfgf41ct5ii9b385u0klbmo80%22%3B%7D; pm_getting-started-panel=expanded; _pk_id.4.fd1d=9307de94d398db91.1493133672.19.1494146606.1494146606.; _pk_ses.4.fd1d=*; PHPSESSID=ip0l08cfsqao25cg3ott5love0; _identity=69537284ba5ddc013eedabe1acd2b3e9f48b9c622853591027fa901901ed5216a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A52%3A%22%5B109%2C%22d7af0807-965f-4662-9c3e-9284a4cd3181%22%2C2592000%5D%22%3B%7D' 'HTTP_CF_CONNECTING_IP' => '92.108.150.12' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1494146735.3279 'REQUEST_TIME' => 1494146735 ]


WARNING  Sun, 07 May 2017 10:45:35 +0200  

Attempted to steal file: 7dd7e7d2-8b86-438f-8cb6-c6968c660a66

**Comment by martinbeek** [comment]
So, nobody can answer this problem? Not even the people who wrote the source above?!
Very peculiar...

**Comment by buddh4** [comment]
This means that a file is already assigned to a model. And there is an attemp to assign it again to a model which fails. Can you somehow recreate the issue?

**Comment by martinbeek** [comment]
Meanwhile, i have around 15 pages of this error daily. It's driving me crazy...
Can it do any harm?  I have no idea what the user experience is - no errors reported to our helpdesk so far.

![schermafbeelding 2017-07-09 om 16 46 10](https://user-images.githubusercontent.com/6781157/27997130-edbf836c-64f1-11e7-95fe-948daab0aeb0.png)

**Comment by buddh4** [comment]
Do you know which kind of files these are? Uploaded to the stream or in the cfiles module etc?

**Comment by LThecross** [comment]
I got the same problem, recurrently. The "file" named in the warning is actually a folder from /uploads/ that contains some uploaded pictures. The message is generated by FileManager.php. Does anyone knows what triggers this warning ?

**Comment by ntinti** [comment]
Same here...

**Comment by Cynicroute** [comment]
Same stack here...
In my case, though, this file was uploaded in the News module i'm using (Nadil Hassan's).

**Comment by samsheridan** [comment]
I found the issue and potential solutions.

A [migration](https://github.com/humhub/humhub/blob/4b2ff3cee2651333ef6a997608c32144e89dca0d/protected/humhub/modules/file/migrations/m140930_210142_fix_default.php#L12) changed the `file.object_id` column from `int` to `varchar(100)`. When a file is added, a check is run to see if it's already attached to another post, etc. The [test](https://github.com/humhub/humhub/blob/4b2ff3cee2651333ef6a997608c32144e89dca0d/protected/humhub/modules/file/models/File.php#L187) `$this->object_id === $record->getPrimaryKey()` assumes that both will be integers, but it's a string now.

To reproduce the warning, embed a picture into the rich text widget of a post, save, and then edit and save the post again. The second time it's saved the file will already be assigned to the post, but it will think it's a different post.

I see two solutions to this problem.
1. Change the column back to `int`. The problem with this is that some files (in my database at least) have `object_model` and `object_id` set to an empty string `""`, so I couldn't simply alter my database without potentially affecting those files.
2. Stop comparing types [here](https://github.com/humhub/humhub/blob/4b2ff3cee2651333ef6a997608c32144e89dca0d/protected/humhub/modules/file/models/File.php#L187) when comparing the primary key. This worked for me.
 `$this->object_id === $record->getPrimaryKey()` becomes `$this->object_id == $record->getPrimaryKey()`

I'm not an expert. Is there a better solution?

**Comment by buddh4** [comment]
@samsheridan thank you very much I'll try to reproduce this.
