### ISSUE TITLE
Auto Delete Runtime Backup Files (Module Marketplace, Updater)

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2537]
I find a huge amount of files taking up a lot of space in ./protected/runtime/updater/backups 
Can these be safely deleted?

Martin

**Comment by acs-ferreira** [comment]
Yes, these are there to restore if you need after a bad update.

But you should backup the entire app on a daily basis.

**Comment by martinbeek** [comment]
So, with YES you mean that i can safely delete them? 
I have daily backups of all my sites.

**Comment by acs-ferreira** [comment]
> Can these be safely deleted?

> Yes

:-)

And also the content of **module_backups** and **module_downloads**

**Comment by luke-** [comment]
Fixed with 1.4
