### ISSUE TITLE
Dashboard doesn't inmediatly update after new publishment

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#2538]
Hi, I don't know if it´s an issue of last HH version 1.2 but when I publish something directly on dashboard, the page is not showing my publishment. I discovered this error because users were publishing few times same entry. I never noticed this problem because I always publish on spaces and this ones works correclty showing last post inmediatly.

Is it a known issue?

I will attach here the only two errors I get from my logs in case they are connected with the problem.
If they are not, well, I will appreciate if you can help me to solve them all.

Thank you very much.

ERROR  Tue, 02 May 2017 10:19:08 +0000  yii\base\UnknownMethodException

exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: humhub\modules\sharebetween\models\ShareForm::getSpaces()' in /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Component.php:290 Stack trace: #0 /home/opengrow/public_html/es/community/protected/modules/sharebetween/controllers/ShareController.php(28): yii\base\Component->__call('getSpaces', Array) #1 /home/opengrow/public_html/es/community/protected/modules/sharebetween/controllers/ShareController.php(28): humhub\modules\sharebetween\models\ShareForm->getSpaces() #2 [internal function]: humhub\modules\sharebetween\controllers\ShareController->actionIndex() #3 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #4 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #5 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('index', Array) #6 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('sharebetween/sh...', Array) #7 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #8 /home/opengrow/public_html/es/community/index.php(25): yii\base\Application->run() #9 {main}

ERROR  Tue, 02 May 2017 10:01:27 +0000  OutOfBoundsException

exception 'yii\base\ErrorException' with message 'ArrayIterator::seek(): Array was modified outside object and internal position is no longer valid' in /home/opengrow/public_html/es/community/protected/humhub/modules/search/engine/ZendLuceneSearch.php:131 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(8, 'ArrayIterator::...', '/home/opengrow/...', 131, Array) #1 [internal function]: ArrayIterator->seek(25) #2 /home/opengrow/public_html/es/community/protected/humhub/modules/search/engine/ZendLuceneSearch.php(131): LimitIterator->rewind() #3 /home/opengrow/public_html/es/community/protected/humhub/modules/directory/controllers/DirectoryController.php(106): humhub\modules\search\engine\ZendLuceneSearch->find('eddie', Array) #4 [internal function]: humhub\modules\directory\controllers\DirectoryController->actionMembers() #5 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #6 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #7 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('members', Array) #8 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('directory/direc...', Array) #9 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /home/opengrow/public_html/es/community/index.php(25): yii\base\Application->run() #11 {main} Next exception 'OutOfBoundsException' with message 'Seek position 25 is out of range' in /home/opengrow/public_html/es/community/protected/humhub/modules/search/engine/ZendLuceneSearch.php:131 Stack trace: #0 [internal function]: ArrayIterator->seek(25) #1 /home/opengrow/public_html/es/community/protected/humhub/modules/search/engine/ZendLuceneSearch.php(131): LimitIterator->rewind() #2 /home/opengrow/public_html/es/community/protected/humhub/modules/directory/controllers/DirectoryController.php(106): humhub\modules\search\engine\ZendLuceneSearch->find('eddie', Array) #3 [internal function]: humhub\modules\directory\controllers\DirectoryController->actionMembers() #4 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #5 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #6 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('members', Array) #7 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('directory/direc...', Array) #8 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #9 /home/opengrow/public_html/es/community/index.php(25): yii\base\Application->run() #10 {main}

**Comment by acs-ferreira** [comment]
What do you mean by "publish on Dashboard"?
The only actions available on the Dashboard are comments.

**Comment by eddiepiazza** [comment]
![image](https://cloud.githubusercontent.com/assets/8577866/25672250/a9cc20c6-302a-11e7-832d-9dac3c3345bc.png)


XD?

**Comment by acs-ferreira** [comment]
This is a **custom theme**, such option is not available on HumHub, so check with the theme developer.

**Comment by eddiepiazza** [comment]
oh XD thanks sorry...

Well anyway it seems more or less usefull to have this option there, could be interresting to include it.
Is it possible to move this publishment to requests?

**Comment by buddh4** [comment]
This is a humhub feature which can be enabled in `Administration -> Settings ->Show user profile post form on dashboard`.

The error seems to be related with the `sharebetween` module which is not even in beta yet i think.

**Comment by acs-ferreira** [comment]
Yes @buddh4 , i've never used that option before. Sorry @eddiepiazza
