### ISSUE TITLE
SSO with windows

### ISSUE THREAD

**Issue by V3R4DE** [humhub/humhub#2542]
Hello,

is there a way to use single sign on on Humhub so i can log in with my windows credentials? I am using the newest version. 

Thanks!

**Comment by buddh4** [comment]
There is a JWT SSO in the enterprise edition http://docs.humhub.org/ee-jwt.html

**Comment by V3R4DE** [comment]
Thank you for your answer.
So, there is no way to use sso with windows login in the free version of humhub?

**Comment by buddh4** [comment]
Not that I know of.

**Comment by acs-ferreira** [comment]
@V3R4DE there is always the option to develop it yourself (or hire a developer) and integrate it, like https://github.com/sizeg/yii2-jwt
