### ISSUE TITLE
Humhub refuses to logout of admin account.

### ISSUE THREAD

**Issue by Mutondi** [humhub/humhub#2543]
Greetings

I am done installing an instance of humhub but I encounter a problem. I have to click logout of my admin account a few times before it actually logouts.

It refuses to logout and merely redirects to the dashboard and if a normal visitor navigates to my website they will have access to my admin account. 

Please could someone assist urgently

**Comment by buddh4** [comment]
Which environment are you using, any content deliver networks etc, which type of caching?

**Comment by Mutondi** [comment]
I selected 'file' under administration. What would u recommend

**Comment by martinbeek** [comment]
You use Nginx if i'm not mistaken? 
Can you paste your Nginx sites-available config here? Thanks!

**Comment by martinbeek** [comment]
Make sure that the following lines do **NOT** occur in your php location block:

fastcgi_ignore_headers "Cache-Control" "Expires" "Set-Cookie";
or
fastcgi_ignore_headers "Set-Cookie";

remove any of these headers if they are present.
