### ISSUE TITLE
Avoid username

### ISSUE THREAD

**Issue by acsfer** [humhub/humhub#2550]
I would like to know if it is possible to avoid using a `username` at the whole process (registration and so on) and use the `email` as username only.

**Comment by Felli** [comment]
Hmm I can agree that there should be a optional toggle to switch between using `username` & `email` for login, although you're already able to use either of them to login.

**Comment by acs-ferreira** [comment]
I know, but asking for it (and even store it) is not necessary in many cases. :)

**Comment by luke-** [comment]
See: https://github.com/humhub/team_tasks/issues/131
