### ISSUE TITLE
"Show more" in stream not working for Files

### ISSUE THREAD

**Issue by Zacki78** [humhub/humhub#2553]
The "Show more" in the stream seems to be not working for files. 

Scenario:
Within a space I uploaded 5 Files to a specific folder. In the stream it is showing the first two files and then an option "Show 3 more". 
![show_more_option](https://cloud.githubusercontent.com/assets/26620636/25770565/d401a4f0-3238-11e7-96b1-a428de977a32.JPG)

When I click on that button it disappears, but the other files are not shown there.
![after_clicking_it](https://cloud.githubusercontent.com/assets/26620636/25770566/d75dccf0-3238-11e7-8fe5-b5821e6b605c.JPG)

In the log there are no entries afterwards.

**Comment by buddh4** [comment]
Can you check the developer console of your browser (Ctrl + i in chrome/firefox).

**Comment by Zacki78** [comment]
What exactly should I look for? Unfortunately I am not so familiar with web development and the developer tools in the browser.
In the Console there are no errors shown after pressing "show more".

Additional information: For appointments the button is working.

**Comment by buddh4** [comment]
1. Open your developer console as described.
2. Clear your Network tab
3. Press show more
4. Check if there are any errors in the "Console" Tab
5. Check the response for space/space/stream as in the following image 
![devconsole](https://cloud.githubusercontent.com/assets/9800854/25772027/4a133a78-3261-11e7-80e4-7e32ed41489c.PNG)

**Comment by Zacki78** [comment]
I did the described steps, there are no errors in the Console tab and the response for space/space/stream shows the following:
![network_preview](https://cloud.githubusercontent.com/assets/26620636/25779868/7b4588de-3320-11e7-92ff-4c1e84cbf04d.JPG)

**Comment by buddh4** [comment]
Is this a public site, perhaps I can have a look. It's also strange that you only get one wallentry. I can't reproduce this.

**Comment by Zacki78** [comment]
It's a private site, but I could send you an invite for testing purposes. I already created a Space for testing only, so this could easily be deleted afterwards.

**Comment by buddh4** [comment]
julian.harrer@humhub.com

**Comment by Zacki78** [comment]
sent you an invite. let me know if you need anything else.

**Comment by buddh4** [comment]
ok, you have to approve my account `Administration -> User`

**Comment by buddh4** [comment]
Hi, so I did some tests on your page, could you check if this is theme related, since you have a custom theme and there is also a small problem with the stream entry option menu.

Also are there any errors in the logs?

And is the stable 1.2.0 installed or a beta.

**Comment by Zacki78** [comment]
I checked it with the default theme, the problem is there as well (I also cleared cache after switching the theme).
There are no entries in the error log and it is stable 1.2.0 with all modules updated to current versions.

**Comment by buddh4** [comment]
Did you update to 1.2 or is this a fresh installation?

**Comment by Zacki78** [comment]
Updated to 1.2. I think I started with beta 3, but not 100% sure anymore.

**Comment by buddh4** [comment]
Hi, can you check if your default stream order is "By creation" or "By update" under "Administration -> Settings -> General", and also check if the problem occures if the it's set to "By creation date".

**Comment by Zacki78** [comment]
Hi, the default stream order is set to "By update". I just switched it and the problem does not occur when the stream is sorted "By creation date".

**Comment by buddh4** [comment]
Thanks I could recreate the issue and will do some tests.

**Comment by buddh4** [comment]
It seems this is related with entries which share the same updated_at time and sort order by update.
