### ISSUE TITLE
No visible public content to guests / Solved - Closed

### ISSUE THREAD

**Issue by eddiepiazza** [humhub/humhub#2556]
Hi, since 3 hours I read all entries related to guest permissions to give them access to public streams and posts.

I setup all HH default configs to make this possible but there is no way.

#1791 it´s supposed fix but is not working on HH 1.2

Here #1550 another post with same problem but there is not solution...

Some info in this two urls but I didn't arrived to solve it:
http://docs.humhub.org/dev-permissions.html
http://docs.humhub.org/humhub-components-behaviors-accesscontrol.html

Someone can help me please?

Thank you very much

![image](https://cloud.githubusercontent.com/assets/8577866/25848220/3912c3d6-34b1-11e7-98c3-2c47fe177f20.png)

I have also this errors that maybe are related:

`INFO  Tue, 09 May 2017 11:30:11 +0000  application
$_SERVER = [ 'CONTEXT_DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'CONTEXT_PREFIX' => '' 'DOCUMENT_ROOT' => '/home/opengrow/public_html/es/community' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'HTTPS' => 'on' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch, br' 'HTTP_ACCEPT_LANGUAGE' => 'es,en-GB;q=0.8,en;q=0.6,fr;q=0.4,pt-PT;q=0.2,pt;q=0.2' 'HTTP_CACHE_CONTROL' => 'max-age=0' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_COOKIE' => 'language=171f215eabfc3ad44c23b882291a1fc4f46e59efc26e0a3ea46fdf298dbc9952a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22es%22%3B%7D; _csrf=be5b2882b8af514d5c1aa3c6956f1801e64a3589271c0487d218153bf1332570a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22RzYJWzr2gTAv7vMu6yKOe6ZHVuZBfxk3%22%3B%7D; pm_online-users-panel=expanded; pm_space-members-panel=expanded; PHPSESSID=jen6s8itnjkc11p3bp37v7bcf0; pm_groups-statistics-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; _identity=3a9ad0ccab810ed194075869573792d29226e240a7e3ff06a36c0ce89355457da%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%226052fbd8-77ba-4499-8c4e-f1a5cf5ff783%22%2C2592000%5D%22%3B%7D' 'HTTP_HOST' => 'www.gropedia.com' 'HTTP_MOD_REWRITE' => 'On' 'HTTP_REFERER' => 'https://www.gropedia.com/dashboard' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36' 'HTTP_X_HTTPS' => '1' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => '' 'REDIRECT_HTTPS' => 'on' 'REDIRECT_HTTP_MOD_REWRITE' => 'On' 'REDIRECT_SCRIPT_URI' => 'https://www.gropedia.com/dashboard' 'REDIRECT_SCRIPT_URL' => '/dashboard' 'REDIRECT_SSL_TLS_SNI' => 'www.gropedia.com' 'REDIRECT_STATUS' => '200' 'REDIRECT_UNIQUE_ID' => 'WRGoQyU97MUADL3Mt@YAAAAm' 'REDIRECT_URL' => '/dashboard' 'REMOTE_ADDR' => '188.82.197.149' 'REMOTE_PORT' => '64335' 'REQUEST_METHOD' => 'GET' 'REQUEST_SCHEME' => 'https' 'REQUEST_URI' => '/dashboard' 'SCRIPT_FILENAME' => '/home/opengrow/public_html/es/community/index.php' 'SCRIPT_NAME' => '/index.php' 'SCRIPT_URI' => 'https://www.gropedia.com/dashboard' 'SCRIPT_URL' => '/dashboard' 'SERVER_ADDR' => '37.61.236.197' 'SERVER_ADMIN' => 'webmaster@gropedia.open-grow.co.uk' 'SERVER_NAME' => 'www.gropedia.com' 'SERVER_PORT' => '443' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SSL_TLS_SNI' => 'www.gropedia.com' 'UNIQUE_ID' => 'WRGoQyU97MUADL3Mt@YAAAAm' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1494329411.7721 'REQUEST_TIME' => 1494329411 ]`

`ERROR  Tue, 09 May 2017 11:30:12 +0000  yii\base\ErrorException:2
exception 'yii\base\ErrorException' with message 'call_user_func() expects parameter 1 to be a valid callback, class 'humhub\modules\discord\Events' not found' in /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Event.php:217 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'call_user_func(...', '/home/opengrow/...', 217, Array) #1 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Event.php(217): call_user_func(Array, Object(yii\base\Event)) #2 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Component.php(553): yii\base\Event::trigger(Object(humhub\modules\dashboard\widgets\Sidebar), 'init', NULL) #3 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Widget.php(72): yii\base\Component->trigger('init') #4 /home/opengrow/public_html/es/community/protected/humhub/widgets/BaseStack.php(67): yii\base\Widget->init() #5 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\widgets\BaseStack->init() #6 [internal function]: yii\base\Object->__construct(Array) #7 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array) #8 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array) #9 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('humhub\\modules\\...', Array, Array) #10 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Widget.php(136): yii\BaseYii::createObject(Array) #11 /home/opengrow/public_html/es/community/protected/humhub/modules/dashboard/views/dashboard/index.php(27): yii\base\Widget::widget(Array) #12 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/View.php(328): require('/home/opengrow/...') #13 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/opengrow/...', Array) #14 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/opengrow/...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #15 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(381): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #16 /home/opengrow/public_html/es/community/protected/humhub/modules/dashboard/controllers/DashboardController.php(63): yii\base\Controller->render('index', Array) #17 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #18 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #19 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #20 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array) #21 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('dashboard/dashb...', Array) #22 /home/opengrow/public_html/es/community/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #23 /home/opengrow/public_html/es/community/index.php(25): yii\base\Application->run() #24 {main}`

**Comment by eddiepiazza** [comment]
In fact, hat is ridicoulous is that the important part that is the posts and spaces are not visible but the most private that is "more active users" "New users" and "online users" is visible.

A part fix the problem with public content non shown, is it possible to hide all this widgets to guests?

**Comment by Felli** [comment]
So  ACP --> Users --> User Settings --> General `Allow limited access for non-authenticated users (guests)` & `Default user profile visibility` set to `Visible for members+guests` doesn't work for you? Of course posts that were posted before doing this I won't guarantee to automatically switch to public.

**Comment by eddiepiazza** [comment]
Hi @Felli I have actually this option activated but still not working.
![image](https://cloud.githubusercontent.com/assets/8577866/25854324/7fe70054-34c7-11e7-8d98-99ec17c4756e.png)

I made some tests creating new posts but still not being shown. is it possible that a site created before even by publishing as publish HH ignores all its posts?

**Comment by eddiepiazza** [comment]
I solved the situation by changing the visibility to "2" on database for each Space, but it´s really important to have access to change this from the config, I really don' t understand why this option doesn´t exist.

Thank you for all.

**Comment by Felli** [comment]
I also see that you've got an error with a Discord module, which one are you using at the moment?

**Comment by eddiepiazza** [comment]
Well, I installed last version and just by activating it I got an Internal server error. So I had to deactivate it from PhPmyadmin and uninstall it.
Here is where I downloaded it https://github.com/GreenVolume/humhub-discordapp-module

I usually install new modules to try to improve my community, but this errors are strange because the module was being updated 2 days ago and is not working on my HH 1.2

**Comment by Felli** [comment]
This module isn't ready for use, it's still under development, I recommend using [this](https://github.com/WebCrew/HumHub-Discord-Module) one that is in working order till I'm able to implement the fixes for the backend call to discord server id.
