### ISSUE TITLE
Profile Field Regex Usage Causes Error 

### ISSUE THREAD

**Issue by alec-hs** [humhub/humhub#2557]
When creating a custom profile field, using regex causes error when editing users.

A custom profile field was setup using the following attributes:

- Fieldtype: Text
- Max Length: 255
- Validator: URL
- Regexp: https://steamcommunity.com/id/.*

Next, you go to edit a user profile, this page does not render properly and shows like this:

https://gyazo.com/bad3f2ce4e2526d46a69c51b2629dfb5

Then you make a change then hit "Save" at this point the following is shown:

https://gyazo.com/fb397a2cb938f2969e1df399e9fd4302

This setup caused the following issues to appear in logging:
Info - https://pastebin.com/EmfRQxZu
Error - https://pastebin.com/sHJpyyJH

When I removed the Regexp the edit user page renders correctly and the errors no longer occur.

**Comment by Felli** [comment]
Might be an issue with Regex in general as I'm not able to even use image url regex.

**Comment by buddh4** [comment]
Does it work if you surround your like `/regex/`

**Comment by alec-hs** [comment]
Nope same issue with the /regex/.

**Comment by Felli** [comment]
I've tried and the issue is still there, I've even tried the above `/^STEAM_[0-5]:[01]:\d+$/` (Steam JavaScript Regex) which doesn't work sadly.

**Comment by buddh4** [comment]
I'll test it tomorrow.

**Comment by buddh4** [comment]
Tested a simple regex `/^[a-zA-z]{3}$/` and it worked fine, note that the regex is evaluated in php.
