### ISSUE TITLE
Image Convertion Error

### ISSUE THREAD

**Issue by eddiepiazza** [humhub/humhub#2561]
Hi, I got today a new kind of error and I would like to know what is it happening and if my users are getting problems to upload images:

![error](https://cloud.githubusercontent.com/assets/8577866/25955875/4596b876-3662-11e7-9d70-3bd37bbd7f45.png)

**Comment by acs-ferreira** [comment]
This can be raised with some (not all) malformed JPEGs.
See https://github.com/humhub/humhub/issues/2561 for a possible fix.

**Comment by eddiepiazza** [comment]
I added your fix to the file. Thank you.

**Comment by eddiepiazza** [comment]
Hi @acs-ferreira I got today this errors and I don t know if it´s related with your fix #2561
![error](https://cloud.githubusercontent.com/assets/8577866/26054182/92c7cf8c-3963-11e7-9128-e54205328f0a.jpg)
