### ISSUE TITLE
error  - invite people to a space

### ISSUE THREAD

**Issue by clairedc** [humhub/humhub#2564]
When I try to invite people to a space, I have the following error (Humhub 1.2.0): 

SyntaxError: missing ) after argument listglobalEval@https://cocirco.faistaloi.org/static/js/all-7f0f082eed9d37a5f5363efa8b9c5636.js?v=1492524851:19:14515
w@https://cocirco.faistaloi.org/static/js/all-7f0f082eed9d37a5f5363efa8b9c5636.js?v=1492524851:19:4608
append@https://cocirco.faistaloi.org/static/js/all-7f0f082eed9d37a5f5363efa8b9c5636.js?v=1492524851:30:6129
m.prototype.setDialog@https://cocirco.faistaloi.org/static/js/all-7f0f082eed9d37a5f5363efa8b9c5636.js?v=1492524851:217:26888
s/<@https://cocirco.faistaloi.org/static/js/all-7f0f082eed9d37a5f5363efa8b9c5636.js?v=1492524851:217:29732
d@https://cocirco.faistaloi.org/static/js/all-7f0f082eed9d37a5f5363efa8b9c5636.js?v=1492524851:175:9363
[22]

**Comment by buddh4** [comment]
This is a language specific bug and is already fixed in current master see https://github.com/humhub/humhub/commit/32ffda6739b04ff3e0499a1a9e8e66cd556f3d73
