### ISSUE TITLE
No refresh of LDAP attribute values

### ISSUE THREAD

**Issue by V3R4DE** [humhub/humhub#2565]
Hello,

i have a question about LDAP and user profiles. If i change the value of an ldap attribute, the value in the user profile does not refresh after hours of waiting. Is this refresh normally done by the cronjob? We do not have the cronjob running.

Thank you for your help!

**Comment by acs-ferreira** [comment]
Yes, the mapping is handled by the hourly cron job
You **should** run the cron jobs (both) as they also provide some useful maintenance operations.

**Comment by V3R4DE** [comment]
I have successfully installed the cron jobs, but the LDAP content is not refreshing?

**Comment by V3R4DE** [comment]
Any ideas?
