### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes The SQL being executed was: ALTER TABLE `user_module` ADD UNIQUE INDEX `index_user_module` (`user_id`, `module_id`)

### ISSUE THREAD

**Issue by Joe2824** [humhub/humhub#2566]
Hi, 
I tried to install humhub but got the following error code

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
The SQL being executed was: ALTER TABLE `user_module` ADD UNIQUE INDEX `index_user_module` (`user_id`, `module_id`)
Error Info: Array
(
    [0] => 42000
    [1] => 1071
    [2] => Specified key was too long; max key length is 767 bytes
)
↵
Caused by: PDOException

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

in /var/www/virtual/xxxxxx/humhub/htdocs/protected/vendor/yiisoft/yii2/db/Command.php at line 846

how can I fix this problem?

**Comment by acs-ferreira** [comment]
Are you tables in `utf8mb4` format ?
If yes, try switch (at least the table `user_module`) to `utf8`.

---

Or maybe (not tested) change [this line](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/migrations/m131213_165552_user_optimize.php#L26) to:

`$this->createIndex('index_user_module', 'user_module', 'user_id, module_id', true)->append('CHARACTER SET utf8 COLLATE utf8_unicode_ci');`

**Comment by Joe2824** [comment]
I tried both solutions. Yes the tables are in utf8mb4 format but I got the same error. Here is the full error Message I hope this can help:

Database Exception – yii\db\Exception

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'unique_email'
The SQL being executed was: ALTER TABLE `user` ADD UNIQUE INDEX `unique_email` (`email`)
Error Info: Array
(
    [0] => 42000
    [1] => 1061
    [2] => Duplicate key name 'unique_email'
)
↵
Caused by: PDOException

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'unique_email'

in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/db/Command.php at line 846
1. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/db/Schema.php at line 636
627628629630631632633634635636637638639640641642643644645 
        $exceptionClass = '\yii\db\Exception';
        foreach ($this->exceptionMap as $error => $class) {
            if (strpos($e->getMessage(), $error) !== false) {
                $exceptionClass = $class;
            }
        }
        $message = $e->getMessage()  . "\nThe SQL being executed was: $rawSql";
        $errorInfo = $e instanceof \PDOException ? $e->errorInfo : null;
        return new $exceptionClass($message, $errorInfo, (int) $e->getCode(), $e);
    }
 
    /**
     * Returns a value indicating whether a SQL statement is for read purpose.
     * @param string $sql the SQL statement
     * @return bool whether a SQL statement is for read purpose.
     */
    public function isReadQuery($sql)
    {
2. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/db/Command.php at line 856 – yii\db\Schema::convertException(PDOException, 'ALTER TABLE `user` ADD UNIQUE IN...')
3. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/db/Migration.php at line 458 – yii\db\Command::execute()
4. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/humhub/modules/user/migrations/m131213_165552_user_optimize.php at line 12 – yii\db\Migration::createIndex('unique_email', 'user', 'email', true)
6789101112131415161718class m131213_165552_user_optimize extends Migration
{
 
    public function up()
    {
 
        $this->createIndex('unique_email', 'user', 'email', true);
        $this->createIndex('unique_username', 'user', 'username', true);
        $this->createIndex('unique_guid', 'user', 'guid', true);
        $this->createIndex('unique_wall_id', 'user', 'wall_id', true);
 
        $this->createIndex('unique_admin', 'group_admin', 'user_id,group_id', true);
 
5. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php at line 654 – m131213_165552_user_optimize::up()
6. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php at line 166 – yii\console\controllers\BaseMigrateController::migrateUp('m131213_165552_user_optimize')
7. yii\console\controllers\BaseMigrateController::actionUp(0)
8. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([humhub\commands\MigrateController, 'actionUp'], [0])
9. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php at line 156 – yii\base\InlineAction::runWithParams([])
10. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/console/Controller.php at line 128 – yii\base\Controller::runAction('up', [])
11. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/humhub/commands/MigrateController.php at line 174 – yii\console\Controller::runAction('up')
168169170171172173174175176177178179180        ob_start();
        $controller = new self('migrate', Yii::$app);
        $controller->db = Yii::$app->db;
        $controller->interactive = false;
        $controller->includeModuleMigrations = true;
        $controller->color = false;
        $controller->runAction('up');
 
        return ob_get_clean();
    }
 
    /**
     * Executes migrations in a specific folder
12. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/humhub/modules/installer/controllers/SetupController.php at line 126 – humhub\commands\MigrateController::webMigrateAll()
120121122123124125126127128129130131132        Yii::$app->cache->flush();
 
        // Disable max execution time to avoid timeouts during database installation
        @ini_set('max_execution_time', 0);
 
        // Migrate Up Database
        \humhub\commands\MigrateController::webMigrateAll();
 
        DynamicConfig::rewrite();
 
        $this->module->setDatabaseInstalled();
 
        return $this->redirect(['/installer/config/index']);
13. humhub\modules\installer\controllers\SetupController::actionInit()
14. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([humhub\modules\installer\controllers\SetupController, 'actionInit'], [])
15. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php at line 156 – yii\base\InlineAction::runWithParams(['r' => 'installer/setup/init'])
16. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/base/Module.php at line 523 – yii\base\Controller::runAction('init', ['r' => 'installer/setup/init'])
17. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/web/Application.php at line 102 – yii\base\Module::runAction('installer/setup/init', ['r' => 'installer/setup/init'])
18. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/protected/vendor/yiisoft/yii2/base/Application.php at line 380 – yii\web\Application::handleRequest(humhub\components\Request)
19. in /var/www/virtual/web41520.pfweb.eu/j0e.space/humhub/htdocs/index.php at line 25 – yii\base\Application::run()
19202122232425    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'installer/setup/init',
];

$_COOKIE = [
    '_csrf' => '9eb776d2d27802b50ebfa97304f609f093287ba67c658947943dc646745932d7a:2:{i:0;s:5:"_csrf";i:1;s:32:"qOUwbDNLJZ7XQRaoPAWFevNBE_9xwq2R";}',
];
Yii Framework
2017-05-12, 19:40:26

Apache/2.4.10 (Debian)
Yii Framework/2.0.11.2

**Comment by acs-ferreira** [comment]
If you're trying to install for the first time (no data):
- Drop all tables from your database (or drop database and recreate it)
- Make sure it's `utf8`
- Try to install

**Comment by Joe2824** [comment]
perfect I didn't change the whole database to utf8.
Thanks a lot

**Comment by acs-ferreira** [comment]
Great, feel free to close this.
