### ISSUE TITLE
No results in directory search containing single quote ( ' )

### ISSUE THREAD

**Issue by pelletiermaxime** [humhub/humhub#2567]
Hi,

I have a member with the keyword "l'information". When searching for that keyword in the members directory, I have no results (/index.php?r=directory%2Fdirectory%2Fmembers&_pjax=%23layout-content&keyword=+l%27information). Searching for "information" works.

PHP 7.0
Humhub 1.2.0

Thanks!

**Comment by Felli** [comment]
Hmm, I believe that this is because `'` is being seen as a `,` which then cuts the search for `l'information` into `l` and `information` if you get what I'm saying.
