### ISSUE TITLE
Last Login registry ignoring first login after registration

### ISSUE THREAD

**Issue by eddiepiazza** [humhub/humhub#2571]
Hi,
Noticed that HH is not taking in consideration first login after an user is registering. By consequence I don't really know which users came only one time and never again, and which ones are so old that doesn't appear the date.

Is it possible to force the command once the user introduce its user name and pass and enter to his account?

Thanks.

**Comment by eddiepiazza** [comment]
Closed means... there is a fix?

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/commit/8e538c90b35f79b83ef0e66bf23182c922da1c8d
