### ISSUE TITLE
Error generating activity mail summary/digest

### ISSUE THREAD

**Issue by ValiValpas** [humhub/humhub#2573]
I installed humhub 1.2.0 on an Apache Server with PHP 5.6.30. Unfortunately, the activity mail summary cannot be generated:

`2017-05-16 20:07:39 [-][-][-][error][activity] Could not send activity mail to: Generic Joe  (Calling unknown method: yii\console
\Request::get())
    in /homepages/u40820/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php:73
    in /homepages/u40820/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php:36
    in /homepages/u40820/humhub/protected/vendor/zhuravljov/yii2-queue/src/Queue.php:95`

I migrated the database from humhub.org

**Comment by buddh4** [comment]
Unfortunately the error is not very significant. 

Make sure your cronjobs are executed with your [php cli](http://stackoverflow.com/questions/9315714/what-is-difference-between-php-cli-and-php-cgi)

To get a (hopefully) more significatn stack trace replace the following [line](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/activity/components/MailSummaryProcessor.php#L73)

with:

`Yii::error($ex, 'activity')`

**Comment by ValiValpas** [comment]
@buddh4 thank you for the quick answer. I indeed used the wrong cronjob, i.e. using `php-cli` instead of `php` fixed this issue for me. Closed.
