### ISSUE TITLE
No valid component class found for given node

### ISSUE THREAD

**Issue by alec-hs** [humhub/humhub#2574]
When a user selects "Account Settings" from the main menu (top right) they receive an error:

    _No valid component class found for given node_

The full message can be found at this Pastebin: https://pastebin.com/Zy81wfyy

This results in the account setting tabbed interface not rendering correctly.

https://i.gyazo.com/cff91d8942d94db479e695775920512c.png

**Comment by buddh4** [comment]
Flush your cache `Administration -> Settings -> Advanced -> Cache` and make sure you have the latest stable version installed.

**Comment by alec-hs** [comment]
Hi, 

Latest stable is installed - cache flushed. No luck there. 

Console reports - https://gyazo.com/c846bfd300ddbb92962d3c3cc18d1262

Network - only file not able to load is an analytics one.  -https://gyazo.com/77f317d28a7f505a6145711f45894f38

**Comment by buddh4** [comment]
Check if the `humhub.ui.form.js` is loaded, perhaps its a caching issue with cloudflare or something.

**Comment by alec-hs** [comment]
Yea - it was CloudFlare. Either the Rocketloader or the cache string was causing the browser to not load the file. All fixed now thanks.
