### ISSUE TITLE
Instalaltion Failed  1.2.0

### ISSUE THREAD

**Issue by mgamboa** [humhub/humhub#2579]
i just try to start the setup and i get the following error

 PHP Compile Error – yii\base\ErrorException
Can't use method return value in write context

    1. in /var/www/html/hum/protected/humhub/components/Module.php at line 339
    330331332333334335336337338339340341342343344345346347348

     
        /**
         * Determines whether the module has notification classes or not
         *
         * @since 1.2
         * @return boolean has notifications
         */
        public function hasNotifications()
        {
            return !empty($this->getNotifications());
        }
     
        /**
         * Returns a list of activity class names this modules provides.
         *
         * @since 1.2
         * @return array list of activity class names
         */
        public function getActivityClasses()

    2. yii\base\ErrorHandler::handleFatalError()

$_COOKIE = [
    'redirect' => '0',
    'PHPSESSID' => '0bha74egahn6lloa25g0ap9qk4',
];

Yii Framework

2017-05-20, 20:23:51

Apache/2.4.6 (CentOS) PHP/5.4.16

Yii Framework/2.0.11.2

**Comment by buddh4** [comment]
You require PHP 5.6 or later: http://docs.humhub.org/admin-requirements.html

**Comment by mgamboa** [comment]
nice is working now
