### ISSUE TITLE
1.2.0 I can`t login with username and password.

### ISSUE THREAD

**Issue by vickysw** [humhub/humhub#2583]
Any help me.? I can not login with username and password after  successfully register.

Thanks and have a nice day.

**Comment by buddh4** [comment]
You mean in the humhub cloud or on your own server?

**Comment by vickysw** [comment]
Out own server.

**Comment by vickysw** [comment]
Hi buddh4,

Did you check it ?

**Comment by buddh4** [comment]
Yeah, did a test, but can't tell you why. Can you still login with your account? Also check the logs "Administration -> Information -> Logging" and check if the newly registered users are activated.

**Comment by vickysw** [comment]
Thanks for you reply.

**Comment by vickysw** [comment]
In logging tag verything is working fine.  But when I am disable auth client then I login with my username and password.  Can you pls  assist me ?

**Comment by buddh4** [comment]
show your auth client configuration

**Comment by vickysw** [comment]
I have added authClienConfig code in humhub/protected/config/common.php 

/*        'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [
/*
                'facebook' => [
                    'class' => 'yii\authclient\clients\Facebook',
                    'clientId' => '1868418723420499',
                    'clientSecret' => 'a6b9efe9b9bfe97b8a5fe570ee79d056',
                ],

                'linkedin' => [
                    'class' => 'yii\authclient\clients\LinkedIn',
                    'clientId' => '78vlnuqsgkri6y',
                    'clientSecret' => 'NlEdm5uEwiMxTeE1',
                ],

                'twitter' => [
                    'class' => 'yii\authclient\clients\Twitter',
                    'consumerKey' => 'twitter_consumer_key',
                    'consumerSecret' => 'twitter_consumer_secret',
                ],*
            ],
        ],*/

**Comment by vickysw** [comment]
Did you check mu OAuth client? I think that is right. Any other solution?

**Comment by buddh4** [comment]
Seems to be a bit destroyed, but think it's because of your comments. Perhaps try adding one by one and check if a specific authclient is the problem. I'll do some tests soon.

**Comment by vickysw** [comment]
Thanks for your reply, I ll do same and let you know.

**Comment by vickysw** [comment]
I have tried to add one by one specific authclient But still, I am facing the issue.   Have you got any luck ?

**Comment by buddh4** [comment]
I've did a test with google and it worked fine, sorry could not recreate the issue.

**Comment by gomonkey** [comment]
I have the same problem, after added oAuth, the normal login is not work anymore. If i remove the code  in configuration file, login is working perfectely. oAuth is working too

**Comment by martincodeinc** [comment]
Here too. The facebook auth module does nothing. But adding it to common.php it works, but the normal login seizes to work! So then it's login with Facebook only and not with username and password.

This disables the default username / password login:

'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [

                'facebook' => [
                    'class' => 'yii\authclient\clients\Facebook',
                    'clientId' => 'xxxxxx',
                    'clientSecret' => 'xxxxxxx',
                ],
                
            ],
         ],
