### ISSUE TITLE
allow ifram or embed or img html tag

### ISSUE THREAD

**Issue by byndstd** [humhub/humhub#2584]
I'm sorry I don't know if it the good place for my post
I'm using Humhub and I'm trying to allow post of youtube video or any video are embed or iframe and  post of images from <img> tag but i can't find how to do that on RichText.php how to do to allow tags like iframe and embed or [img] or <a> tag.

**Comment by buddh4** [comment]
Youtube videos should be embeded by default if you post a youtube link.
Images can be embedded by using markdown syntax unfortunately this currently does not work for uploaded post images, but should work for example for uploaded cfile images eg:

```
![my image](http:://someurl.com/image.jpg)
```

You should not allow direct iframe input, rahter use [oEmbed](http://oembed.com/) if available.

**Comment by byndstd** [comment]
thank you for your answer 
for iframe because there are other web like youtube who use iframe or embed tag that why, i don't want just youtube who will be add but also other videos from other web

**Comment by buddh4** [comment]
Most services as youtube, soundcloud etc can be embeded by means of oembed. Perhaps ask the [community](https://community.humhub.com) or search here for github issues regarding oembed drivers.

Also have a look at https://github.com/humhub/humhub/issues/2126

**Comment by byndstd** [comment]
ah ok , thank you so much for your time, I never used oembed to know how to use it

**Comment by martinbeek** [comment]
Image tags are unfortunately not working in posts. I'd love to have that enabled but i can't find where. Currently any ![my image](http:://someurl.com/image.jpg) tag is converted to a readable line in the post: <img src="http:://someurl.com/image.jpg" alt="my image" title="" />

**Comment by Felli** [comment]
@martinbeek could you provide any error stacks or console errors, also what version of HumHub are you using?

**Comment by buddh4** [comment]
@martinbeek could not reproduce this.

**Comment by martinbeek** [comment]
You can not reproduce this. That's weird...
I'm doing this on your community site and it's not working. Never has.

**Comment by martinbeek** [comment]
Just paste an markdown image tag on your profile on the community site. It's not working.

**Comment by buddh4** [comment]
https://community.humhub.com/content/perma?id=118862

**Comment by Felli** [comment]
Is this on mobile or web?

**Comment by buddh4** [comment]
@martinbeek I've checked your test in the community, you just copied my previous example, which uses an invalid url (it was meant to show the markdown syntax instead of an actual example), The (invalid) example renders just the image text which is indeed a bit strange, but existing image urls should work. Even github just renders an empty post instead of the alt text. 

It's planned to replace the frontend markdown parser in v1.3.

**Comment by byndstd** [comment]
I tried to post images on my post with the code of images
```
<a href="https://ibb.co/f3hrTR"><img src="https://preview.ibb.co/hi0Oa6/Chrysanthemum.jpg" alt="Chrysanthemum" border="0"></a>
<a href="https://ibb.co/cCAOa6"><img src="https://preview.ibb.co/kfhEhm/Desert.jpg" alt="Desert" border="0"></a>
<a href="https://ibb.co/jCvZhm"><img src="https://preview.ibb.co/i2Uuhm/Hydrangeas.jpg" alt="Hydrangeas" border="0"></a>
<a href="https://ibb.co/gWVZhm"><img src="https://preview.ibb.co/fzv0Nm/Jellyfish.jpg" alt="Jellyfish" border="0"></a>
```
but all I see is text I can't see the images, how can I allow posting images by just insert the code

**Comment by buddh4** [comment]
```
[![](https://www.humhub.org/static/img/logo.png)](https://www.humhub.org)

which is consist of an image:
![](https://www.humhub.org/static/img/logo.png)

within a link:

[!<image>](https://www.humhub.org)
```

In v1.3 there will be a wysiwyg editor so you won't need any markdonw syntax.
