### ISSUE TITLE
using ms sql server 2012 for database

### ISSUE THREAD

**Issue by cruzer24** [humhub/humhub#2585]
hi, guys.. is it possible to implement humhub on IIS Server (PHP on IIS) and for database using MS SQL Server 2012. does anyone ever do it ?

**Comment by tomtomsen** [comment]
humhub is based on yii, which uses PDO to connect to a database.
I've never tried it, but i think it should definitly be possible.

found this thread: http://www.yiiframework.com/forum/index.php/topic/18946-how-to-connect-mssql-database/

**Comment by Buliwyfa** [comment]
@cruzer24 will love to ear your experiences wiht MSSQL/HumHub and why you went for MSSQL (I am too using mostly IIS) if you want to do it privately buliwyfa()gmail.com

Thanks a lot!
