### ISSUE TITLE
1.2.0 I cannot login with ldap user

### ISSUE THREAD

**Issue by T-Rock** [humhub/humhub#2591]
I have one installation updated to 1.2.0 and I have another installation newly installed.
Both have the same behavior:
- LDAP configuration in "User Settings" says "Status: OK!" and shows the number of users
- after cronjob was running users are shown as active in the "User administration"
- all users have a synced email address
- users from ldap cannot login
- "Logging" stopped working with the updated installation and never started with the new installation

Environment:
- Debian Jessie
- Apache and Kolab LDAP with the updated installation
- Nginx and iRedMail LDAP (openldap) with the new installation

The updated installation worked fine before the update, there were no changes.
Anyway I am only interested in getting the new installation running, I just wonder about the same behavior like the updated installation.

**Comment by Itacua** [comment]
Hello T-Rock , I have the same issue : imported LDAP users cannot connect. Do you make work it?

**Comment by buddh4** [comment]
@Itacua perhaps ask in the [community](https://community.humhub.com/dashboard) for help.

**Comment by Itacua** [comment]
Hello Budh4, this what I did before coming here.

**Comment by T-Rock** [comment]
I am sorry, no progress on my side.
I hoped somebody from the team will fix it in the standard release.
If I find a solution, I will update the issue here.

**Comment by T-Rock** [comment]
Oh, I didn't want to close it ...

**Comment by Aneadiel** [comment]
+1
