### ISSUE TITLE
Bug: Url with russian text by Markdown

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2594]
For URL with russian text `[link text](http://example.com/wiki-s/doku.php?p=русский)`

got markdown

![image](https://cloud.githubusercontent.com/assets/874234/26552484/0261f9ee-4490-11e7-8e29-461e47230573.png)

<hr>

Should be

`[link text](http://example.com/wiki-s/doku.php?p=русский)`

[link text](http://example.com/wiki-s/doku.php?p=русский)

**Comment by githubjeka** [comment]
Thanks

**Comment by buddh4** [comment]
Hmm unfortunately I have to revert the change, since the uri encoding destroyed other links. The problem is that javascript regexp has problems with unicode characters, don't know whats the best solution for this ,(

**Comment by githubjeka** [comment]
May be the /u modifier help to fix it

**Comment by githubjeka** [comment]
Ah javascript regexp...

**Comment by githubjeka** [comment]
https://mathiasbynens.be/notes/es6-unicode-regex

**Comment by buddh4** [comment]
thanks, should work now this also includes fixes for direct links (without markdown syntax)

**Comment by githubjeka** [comment]
Thanks
