### ISSUE TITLE
CSS: Select.form-control from Humhub theme

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2601]
This styles 
![image](https://cloud.githubusercontent.com/assets/874234/26620621/366400d6-45ec-11e7-85d8-32d469e4e455.png)
break default correct css and provide to the visual error
![image](https://cloud.githubusercontent.com/assets/874234/26620674/6acf0028-45ec-11e7-9735-ead18fc6bde8.png)

Without 

![image](https://cloud.githubusercontent.com/assets/874234/26620712/91d2ccb8-45ec-11e7-8e4b-ce0a8ca629f8.png)

element has correctly visual
![image](https://cloud.githubusercontent.com/assets/874234/26620769/cc834fc2-45ec-11e7-8039-ab01f2feeea0.png)

**Comment by githubjeka** [comment]
Same for Select with multiple and rows

```php
 <div class="modal-dialog modal-dialog-normal animated fadeIn">
    <div class="modal-content">
        <div class="modal-body">
            <?php $form = \humhub\widgets\ActiveForm::begin() ?>
            <?=
            $form->field($formModel, 'tags')
                ->dropDownList([1,2,3,4,5,6,7,8,9,10],
                    ['text' => 'Please select', 'multiple' => true, 'class'=>'select-form']
                );
            ?>
            <?php \humhub\widgets\ActiveForm::end(); ?>
        </div>
    </div>
</div>
```


![image](https://user-images.githubusercontent.com/874234/26868167-b06029c6-4b70-11e7-8756-89a454ade499.png)

Should be 

![image](https://user-images.githubusercontent.com/874234/26868226-ed0c282a-4b70-11e7-8d38-27f5c9df47ca.png)

**Comment by buddh4** [comment]
Could not recreate the first issue, honestly the default style looks kind of crappy. 
If I remove the width:100% it looks like this:

![form-control](https://user-images.githubusercontent.com/9800854/26885989-74bc58e8-4ba4-11e7-8243-a33dd36cb078.PNG)

Which browser did you use for testing?
For the multi select I'll provide a fix.

**Comment by githubjeka** [comment]
I use chrome google.
In last master version Humhub is same issues too  

My php
```php
<?php $form = \yii\bootstrap\ActiveForm::begin(['layout' => 'inline']); ?>

<?= $form->field($searchModel, 'name')
            ->textInput([ 'placeholder' => 'Filter by name',]) ?>

<?= $form->field($searchModel, 'type')
            ->dropDownList($types, ['prompt' => '-']) ?>

<?php \yii\bootstrap\ActiveForm::end(); ?>
```

![image](https://user-images.githubusercontent.com/874234/28672664-07772738-72e9-11e7-9fbb-3b562025b616.png)

baseline is different
![image](https://user-images.githubusercontent.com/874234/28672686-18bc7f5c-72e9-11e7-8af8-b3260aa6092d.png)

when I check to off 

![image](https://user-images.githubusercontent.com/874234/28672785-616b54e4-72e9-11e7-9c86-fd6614a9b249.png)

![image](https://user-images.githubusercontent.com/874234/28672813-73a81ec6-72e9-11e7-87c9-671cb5ce7fc8.png)

baseline is same
![image](https://user-images.githubusercontent.com/874234/28672842-89846d6c-72e9-11e7-8661-5f3073cd3d5f.png)
