### ISSUE TITLE
Class from installed Composer package not found

### ISSUE THREAD

**Issue by iadj** [humhub/humhub#2602]
I'm trying to use a composer package (vlucas/dotenv). I'm using composer to install it, but including it in my project doesn't appear to work. These are the steps I undertook:

1. In project root: `composer require vlucas/dotenv`
2. Add `env.php` in `protected` folder. env.php:
```
<?php
/**
 * Require helpers
 */
use Dotenv\Dotenv;
/**
 * Load application environment from .env file
 */
$dotenv = new Dotenv(dirname(__DIR__));
$dotenv->load();
```
2. In root `index.php`, add the following line under the autoload.php requirement:
```
//env helper file
require(__DIR__ . '/protected/env.php');
```

This results in the following error:
```
( ! ) Error: Class 'Dotenv\Dotenv' not found in /shared/httpd/wcloud/htdocs/protected/env.php on line 12
```

**Comment by Felli** [comment]
[This should help a little with this](https://stackoverflow.com/questions/30645324/dotenv-requires-env-file-on-production). Also here's an [example](https://github.com/StrongSquirrel/yii2-dotenv-app) of dotenv done in Yii2.

**Comment by iadj** [comment]
@Felli From the error message it appears that it's not directly related to Dotenv, but to the composer package itself not being loaded?

**Comment by Felli** [comment]
Adding this should help then update me on if it works.
```
"autoload": {
        "files": [
            "helpers/env.php"
        ]
    },
```

**Comment by Felli** [comment]
Should look something like this.
```
{
    "name": "humhub/humhub",
    "description": "HumHub - The flexible Open Source Social Network Kit for Collaboration",
    "keywords": ["humhub", "yii2", "framework"],
    "homepage": "http://www.humhub.com/",
    "type": "project",
    "license": "AGPL-3.0",
    "support": {
        "issues": "https://github.com/humhub/humhub/issues?state=open",
        "forum": "http://community.humhub.com",
        "wiki": "http://community.humhub.com",
        "irc": "irc://irc.freenode.net/humhub",
        "source": "https://github.com/humhub/humhub"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.6.0",
        "yiisoft/yii2": "~2.0.11",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "yiisoft/yii2-authclient": "~2.0.0",
        "yiisoft/yii2-imagine": "~2.0.0",
        "raoul2000/yii2-jcrop-widget": "*",
        "cebe/markdown": "1.0.2",
        "yiisoft/yii2-jui": "~2.0.0",
        "zendframework/zend-http": "*",
        "jbroadway/urlify": "^1.0",
        "nqxcode/zendsearch": "^2.0",
        "xj/yii2-jplayer-widget": "*",
        "zendframework/zend-ldap": "^2.5",
        "zhuravljov/yii2-queue": "^0.11",
        "vlucas/phpdotenv": ">=2.2",
        "bower-asset/jquery-timeago": "1.4.*",
        "bower-asset/jquery-nicescroll": "3.6.*",
        "bower-asset/jquery-knob": "1.2.*",
        "bower-asset/jquery-placeholder": "^2.3.0",
        "bower-asset/blueimp-file-upload": "9.11.*",
        "bower-asset/fontawesome": "^4.7.0",
        "bower-asset/bootstrap-markdown": "2.10.*",
        "bower-asset/select2": "^4.0.2",
        "bower-asset/bluebird": "^3.3.5",
        "bower-asset/select2-bootstrap-theme": "0.1.0-beta.4",
        "bower-asset/jquery.cookie": "^1.4.1",
        "bower-asset/jquery-color": "^2.1.2",
        "bower-asset/autosize": "1.*",
        "bower-asset/nprogress": "*",
        "bower-asset/At.js": "^1.5.1",
        "bower-asset/animate.css": "*",
        "bower-asset/html5shiv": "^3.7",
        "bower-asset/clipboard.js": "*",
        "bower-asset/jPlayer": "2.9.2"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "~2.0.0",
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "yiisoft/yii2-apidoc": "~2.0.0"
    },
    "config": {
        "process-timeout": 1800,
        "vendor-dir": "protected/vendor"
    },
   "autoload": {
        "files": [
            "helpers/env.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "protected/runtime": "0777",
                    "assets": "0777",
                    "protected/yii": "0755",
                    "protected/modules": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "protected/config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "protected/vendor/npm",
            "bower-asset-library": "protected/vendor/bower"
        }
    }
}
```

**Comment by githubjeka** [comment]
One question: Can changed `composer.json` after upgrade HumHub system via admin/panel?

**Comment by iadj** [comment]
@Felli What file are you talking about? I don't have any composer file that looks like that. My root composer.json looks like this: 
```
{
    "require": {
        "vlucas/phpdotenv": "^2.4"
    }
}
```

I do have a composer.lock file, which I don't believe should be modified.

**Comment by iadj** [comment]
Got it working by adding the following line to my root index.php file:
```
require(__DIR__ . '/vendor/autoload.php');
```
I just hope this doesn't cause all those packages to be loaded twice, since they appear to be in both the root and protected folder.

**Comment by githubjeka** [comment]
You are working incorrectly with Composer.

[I asked, not for nothing it is.](https://github.com/humhub/humhub/issues/2602#issuecomment-305412147)

By default HumHub project use root file `composer.json` . See structure files of https://github.com/humhub/humhub

I don't know why you have composer.json like this:

```
{
    "require": {
        "vlucas/phpdotenv": "^2.4"
    }
}
```

But this will lead to a crash when Humhub upgraded, sooner or later.
Because your composer store vendors in `/vendor`, HumHub - `/protected/vendors`. After upgrade HumHub replace your composer.json to their.

**Comment by githubjeka** [comment]
To fix 
See comment https://github.com/humhub/humhub/issues/2602#issuecomment-305263315

```
"require": {
        "php": ">=5.6.0",
        "yiisoft/yii2": "~2.0.11",
        ...
        "vlucas/phpdotenv": ">=2.2",
        ...
    },
```

But any way after upgrade HumHub replace this changes...

**Comment by Felli** [comment]
Also you'll have to create a .env file for this which I myself can not do for you sadly.

**Comment by iadj** [comment]
@Felli Don't worry about the .env file :) It was more about the installed class not being found.

**Comment by Felli** [comment]
Well as @githubjeka stated adding the composer.json update that I posted in https://github.com/humhub/humhub/issues/2602#issuecomment-305263315 should fix this for you, although after that it would be pretty useless unless you plan on manually updating your installation after doing this.
