### ISSUE TITLE
SMTP SSL encryption can not be used normally

### ISSUE THREAD

**Issue by MyPuppet** [humhub/humhub#2606]
SMTP SSL encryption can not be used normally

Account password server address configuration is correct, 25 can be used. But China requires the use of SSL, Humhub SSL can not be used normally, which used a lot of mail service providers have failed. The error message is as follows:
`[Swift_TransportException] Swift_TransportException: Connection could not be established with host smtp.ym.163.com [ohq0tjefc8nbpah4b76qbe554e] [error] [Swift_TransportException]`

I believe there are a lot of people like me, if received please help Thank you

**Comment by MyPuppet** [comment]
`[dhg94h8pqlipera4phq2j5bcrm][error][Swift_TransportException] Swift_TransportException: Connection could not be established with host smtp.exmail.qq.com [ #0]`

**Comment by acs-ferreira** [comment]
Try:
- port 465 with SSL
- port 587 with TLS
