### ISSUE TITLE
username encoding with pretty url

### ISSUE THREAD

**Issue by Adri7** [humhub/humhub#2613]
If you enable pretty url in configuration (web.php or common.php, inside protected/config) :

> 'components' =>[
>   'urlManager' => [
>             'enablePrettyUrl' => true,
>         ],
> ],

Then the user module (and space), creates the URLs like this: 
    http://localhost/index.php/u/username/user/profile/home
The problem here is the urlencode. The user module UrlRule does this:
`$url = "u/" . urlencode(strtolower($username)) . "/" . $route;`

So when the $username have special characters, strtolower() returns some ilegal characters, and so the urlencode() returns a bad encoding, which throws "page not found" errors anytime you try to go to this malformed URLs. You cannot go to "My profile" for example.
Just for note, when you log in through linkedin, many countries have special characters in their names, and these name becomes the username.

Anyway I've fixed this, just replace the line of code with the following:
`$url = "u/" . urlencode(mb_strtolower($username)) . "/" . $route;`

**Comment by githubjeka** [comment]
In Space `\humhub\modules\space\components\UrlRule` this is not used even

```php
 $url = "s/" . urlencode($urlPart) . "/" . $route;
```

although UrlRule of Space and User was created  at the same time (by history of git) :)

It's bug 100% - easily reproduce it

**Comment by victorpdiez** [comment]
thanks it fix my problem with user like "César"
