### ISSUE TITLE
Error after sending message via latest Mail module

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2615]
The latest updated Mail module gives a 500 error after sending a mail. Display is not updated either. No error in HumHub, only in the javascript debugger.

``VM836:34 POST https://test.pryv.nl/mail/mail/show?id=8 500 ()
send	@	jquery.js:555
ajax	@	jquery.js:531
(anonymous)	@	VM836:34
dispatch	@	jquery.js:272
elemData.handle	@	jquery.js:259
``

**Comment by buddh4** [comment]
Check the backend logs, 500 Errors means there was an error on server side.

**Comment by martinbeek** [comment]
I'll do that. 

I have a working setup, i update the Mail module and it stops working.., so that's pretty mysterious. 
I'll see what i can find.

Martin

**Comment by martinbeek** [comment]
The problem seems to be solved. If the SMTP server is not correctly configured (on my test server u use a fake smtp server) sending of mail fails with an error 500. 
Thanks.
M.
