### ISSUE TITLE
Call to a member function isAttributeRequired() on null

### ISSUE THREAD

**Issue by frey1esm** [humhub/humhub#2616]
Got this after manual update from 1.01 to 1.2

` in /var/www/vhosts/hilois.com/subdomains/hub/httpdocs/web-app/protected/vendor/yiisoft/yii2/widgets/ActiveField.php`

Triggered at this page:
`/user/auth/login`

on this line:
859   `if (!isset($options['aria-required']) && $this->model->isAttributeRequired($this->attribute)) {`

What could be causing this?

**Comment by buddh4** [comment]
Please add the full error stack.

**Comment by frey1esm** [comment]
Solved. Some of my tables were MyISAM, and changing all of them to InnoDB allowed a smooth update.
