### ISSUE TITLE
Files are not downloading

### ISSUE THREAD

**Issue by raghureddysa** [humhub/humhub#2620]
Hi All,

I activated X-Sendfile and uploaded file, but when I download, I am not able to see any contentent in the file (File become empty.) Once deactivate X-Sendfile and try to download a file, but I am getting follwing error This site can’t be reached

The webpage at http://xxx.xxx.xxx/xxxx/index.php?r=file%2Ffile%2Fdownload&guid=d63a3318-8f70-4f5a-a517-8da6fd074cac might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE 

Thanks,
Raghu.

**Comment by raghureddysa** [comment]
[Mon Jun 12 20:59:07.739742 2017] [:error] [pid 21839] [client 192.168.1.34:35978] PHP Fatal error: Maximum execution time of 300 seconds exceeded in /var/www/html/iconmahub/protected/vendor/yiisoft/yii2/web/Response.php on line 396 
[Mon Jun 12 20:59:07.739760 2017] [:error] [pid 21839] [client 192.168.1.34:35978] PHP Stack trace: 
[Mon Jun 12 20:59:07.739781 2017] [:error] [pid 21839] [client 192.168.1.34:35978] PHP 1. {main}() /var/www/html/iconmahub/index.php:0 
[Mon Jun 12 20:59:07.739784 2017] [:error] [pid 21839] [client 192.168.1.34:35978] PHP 2. yii\base\Application->run() /var/www/html/iconmahub/index.php:25 
[Mon Jun 12 20:59:07.739793 2017] [:error] [pid 21839] [client 192.168.1.34:35978] PHP 3. yii\web\Response->send() /var/www/html/iconmahub/protected/vendor/yiisoft/yii2/base/Application.php:386 
[Mon Jun 12 20:59:07.739796 2017] [:error] [pid 21839] [client 192.168.1.34:35978] PHP 4. yii\web\Response->sendContent() /var/www/html/iconmahub/protected/vendor/yiisoft/yii2/web/Response.php:316 
[Mon Jun 12 20:59:07.739799 2017] [:error] [pid 21839] [client 192.168.1.34:35978] PHP 5. set_time_limit() /var/www/html/iconmahub/protected/vendor/yiisoft/yii2/web/Response.php:396
Like

**Comment by buddh4** [comment]
Have you configured your apache according to: http://docs.humhub.org/admin-performance.html#x-sendfile
or do you use nginx?

**Comment by kidsinhalf** [comment]
Hi, I have the same problem.
It's really strange because the files are correctly uploaded. 
It may be a .htaccess problem or a access configuration.

https://xxxx/index.php?r=file%2Ffile%2Fdownload&guid=94c12e3c-56d5-457d-8462-2c6344248a49

**Comment by kidsinhalf** [comment]
I tried to activate or desactivate the X-Send, it doesn't work in both cases.
I also tried to change the .htacess file with uncommenting but it is worth.

# uncomment to force https requests
# RewriteCond %{HTTPS} !=on
# RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/.*$ [NC]
# RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

**Comment by hausmaen** [comment]
I'm running on a shared hoster and have no access to any configuration but I experience same issue.
