### ISSUE TITLE
Module translation

### ISSUE THREAD

**Issue by wesleyguirra** [humhub/humhub#2632]
Hello there,

first of all I've read the guidelines to post here but the community.humhub.org is off, because of that I'm asking here

 I'm working on a translation in my local humhub project, and I want to keep it versioned, I did it in the config/common.php this way: https://gist.github.com/wesleyguirra/f51cff9cd65b643979f2d67703188db2

I'm not sure if this is the right way, but I'm assuming that this file is much long, there's some method to do it  in a better way?

**Comment by Felli** [comment]
I suggest reading the [docs](http://docs.humhub.org/dev-modules-i18n.html) about this. 👍

**Comment by buddh4** [comment]
I think [this](http://docs.humhub.org/admin-translations.html#overwrite-translation-messages) is what you are looking for
