### ISSUE TITLE
Administration menu still available after using admin option "login as this user" on a non-admin user

### ISSUE THREAD

**Issue by BastusIII** [humhub/humhub#2636]
![2017-06-21_12h54_12](https://user-images.githubusercontent.com/4225867/27381108-d051b71a-5681-11e7-9bc4-a614899a5f42.png)

Maybe Cookie dependencies or something similar. You cannot access the Admin menu as the non-admin user but are redirected to "no permission to view this page", so this is just a minor problem.

**Comment by buddh4** [comment]
This is a known issue, since this is saved in the user session.

**Comment by luke-** [comment]
Fixed
