### ISSUE TITLE
PHP wrong detection - can`t install humhub

### ISSUE THREAD

**Issue by volkomorov** [humhub/humhub#2643]
Hi, can`t install humhub 1.2.1. I got an error in requirements. Humhub shows me that I have 5.5.9-1ubuntu4.21, but php -v shows: 

`PHP 7.1.6-2~ubuntu14.04.1+deb.sury.org+1 (cli) (built: Jun 14 2017 05:58:40) ( NTS )`

![2017-06-27 22-15-29](https://user-images.githubusercontent.com/29736617/27600672-380e0008-5b86-11e7-923d-48cad8434a8e.png)

Please, help me to fix it,I want to use Humhub.

**Comment by moosesystems** [comment]
You need to upgrade your PHP version .... 

Sudo apt-get update
Sudo apt-get upgrade

**Comment by buddh4** [comment]
Your apache probably runs another php version: https://serverfault.com/questions/428800/how-do-i-tell-apache-which-php-to-use

**Comment by volkomorov** [comment]
@moosesystems, done, 

php -v:
`PHP 7.1.6-2~ubuntu14.04.1+deb.sury.org+1 (cli) (built: Jun 14 2017 05:58:40) ( NTS )`

**Comment by moosesystems** [comment]
and now what's happening?

**Comment by volkomorov** [comment]
@moosesystems nothing, the same error, unfortunately :( trying to understand previous advice of @buddh4

**Comment by buddh4** [comment]
My link was just one of the first on google, perhaps you'll find some better advice, perhaps also check https://serverfault.com/questions/149039/how-to-change-what-version-of-php-apache2-uses

**Comment by volkomorov** [comment]
thank you so much, sorry for my stupidity :)
sudo a2dismod php5.6 
sudo a2enmod php7.1 
sudo service apache2 restart
works!
