### ISSUE TITLE
Call to a member function get() on null

### ISSUE THREAD

**Issue by thurti** [humhub/humhub#2648]
Hi,

since two days, I get a 500 Internal Server Error on every page. 
The log says:

`Error: Call to a member function get() on null in [...]protected/humhub/components/i18n/Formatter.php:38
`

It looks like the function `Yii::$app->getModule('admin')` returns `null` which produces the error. I have no idea why this is happening.

Humhub 1.2.0
PHP 7.1 (also tried 5.6)

Does anyone have an idea?

Thanks
Thomas

**Comment by buddh4** [comment]
It rather seems that the `->settings->get('...')` is the problem.
Did you run any update or composer update or installed a new module?
Are there any other errors in your logs?

**Comment by thurti** [comment]
I did a var_dump on `Yii::$app->getModule('admin')` which was `null`... 

I didn't do any composer update or installed any module. The only change I made, was enabling let's encrypt for the sub domain where humhub is installed. But there where no problems after doing this. I also tried to switch off ssl again, but I still get the error.

The last error before the first occurrence of this `Call to a member function get() on null` was a DB error during the cronjob.

`[warning][yii\log\Dispatcher::dispatch] Unable to send log via yii\log\DbTarget: Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No route to host' in humhub/protected/vendor/yiisoft/yii2/db/Connection.php:568`

And there is also this one:
`[error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Unable to locate message source for category 'AdminModule.base'. in humhub/protected/vendor/yiisoft/yii2/i18n/I18N.php:200`

Could there be some kind of caching issue? I already deleted the files in `protected/runtime/cache/hu` but still no luck...

**Comment by buddh4** [comment]
Check if the admin module is present `humhub/protected/modules/admin` and check your db connection settings. And check your db connection setting `humhub/protected/config/dynamic.php`

**Comment by thurti** [comment]
The admin module is present in `humhub/protected/modules/admin`.
The database connection works. Login to the page works, so I guess there is no problem with the db connection.?

**Comment by thurti** [comment]
Ok, I have found the problem. 

The admin module could not be loaded due to a php error: `fopen(): STDIN access is disabled in /protected/humhub/vendor/yiisoft/yii2/console/Application.php on line 15`

As a quick workaround I commented out the specific lines in `.../console/Application.php`. Now everything seems to work again. Is reading from  the STDIN a requirement for humhub?

By the way, the error was not shown, because the module loading in `protected/humhub/components/bootstrap/ModuleAutoLoader.php` is wrapped in a try-catch block, but without handling the exception. Maybe there should be some exception handling, eg. writing it to the log. 

```
protected/humhub/components/bootstrap/ModuleAutoLoader.php:41

try {
    $modules[$moduleDir] = require($moduleDir . DIRECTORY_SEPARATOR . 'config.php');
} catch (\Exception $ex) {

}

```

Thanks again for you quick response and help.

**Comment by buddh4** [comment]
Thanks for the note, will add a error log in the catch, STDIN is required for the console Application, but I don't know why the console Application is requested for web calls, do you have the full error stack?

**Comment by thurti** [comment]
The module loader loads `protected/humhub/modules/admin/config.php`. The `config.php` imports the console application through `use humhub\components\console\Application;`. 
This class itself extends `\yii\console\Application` which caused the problem, because of this line: `15: defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));`

Unfortunately I don't have access to the webserver error logs. But here is the first part of the  exception:
```
object(yii\base\ErrorException)#25 (8) {
  ["message":protected]=>
  string(33) "fopen(): STDIN access is disabled"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(2)
  ["file":protected]=>
  string(82) "/humhub/protected/vendor/yiisoft/yii2/console/Application.php"
  ["line":protected]=>
  int(15)
  ["trace":"Exception":private]=>
  array(16) {
    [0]=>
    array(4) {
      ["function"]=>
      string(11) "handleError"
      ["class"]=>
      string(21) "yii\base\ErrorHandler"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(5) {
        [0]=>
        int(2)
        [1]=>
        string(33) "fopen(): STDIN access is disabled"
        [2]=>
        string(82) "/humhub/protected/vendor/yiisoft/yii2/console/Application.php"
        [3]=>
        int(15)
        [4]=>
        array(2) {
          ["className"]=>
          string(23) "yii\console\Application"
          ["classFile"]=>
          string(82) "/humhub/protected/vendor/yiisoft/yii2/console/Application.php"
        }
      }
    }
    [1]=>
    array(4) {
      ["file"]=>
      string(82) "/humhub/protected/vendor/yiisoft/yii2/console/Application.php"
      ["line"]=>
      int(15)
      ["function"]=>
      string(5) "fopen"
      ["args"]=>
      array(2) {
        [0]=>
        string(11) "php://stdin"
        [1]=>
        string(1) "r"
      }
    }
    [2]=>
    array(4) {
      ["file"]=>
      string(70) "/humhub/protected/vendor/yiisoft/yii2/BaseYii.php"
      ["line"]=>
      int(292)
      ["args"]=>
      array(1) {
        [0]=>
        string(82) "/humhub/protected/vendor/yiisoft/yii2/console/Application.php"
      }
      ["function"]=>
      string(7) "include"
    }
    [3]=>
    array(4) {
      ["function"]=>
      string(8) "autoload"
      ["class"]=>
      string(11) "yii\BaseYii"
      ["type"]=>
      string(2) "::"
      ["args"]=>
      array(1) {
        [0]=>
        string(23) "yii\console\Application"
      }
    }
    [4]=>
    array(4) {
      ["file"]=>
      string(80) "/humhub/protected/humhub/components/console/Application.php"
      ["line"]=>
      int(19)
      ["function"]=>
      string(17) "spl_autoload_call"
      ["args"]=>
      array(1) {
        [0]=>
        string(23) "yii\console\Application"
      }
    }
    [5]=>
    array(4) {
      ["file"]=>
      string(70) "/humhub/protected/vendor/yiisoft/yii2/BaseYii.php"
      ["line"]=>
      int(292)
      ["args"]=>
      array(1) {
        [0]=>
        string(80) "/humhub/protected/humhub/components/console/Application.php"
      }
      ["function"]=>
      string(7) "include"
    }
    [6]=>
    array(4) {
      ["function"]=>
      string(8) "autoload"
      ["class"]=>
      string(11) "yii\BaseYii"
      ["type"]=>
      string(2) "::"
      ["args"]=>
      array(1) {
        [0]=>
        string(37) "humhub\components\console\Application"
      }
    }
    [7]=>
    array(4) {
      ["file"]=>
      string(70) "/humhub/protected/humhub/modules/admin/config.php"
      ["line"]=>
      int(36)
      ["function"]=>
      string(17) "spl_autoload_call"
      ["args"]=>
      array(1) {
        [0]=>
        string(37) "humhub\components\console\Application"
      }
    }
    [8]=>
    array(4) {
      ["file"]=>
      string(87) "/humhub/protected/humhub/components/bootstrap/ModuleAutoLoader.php"
      ["line"]=>
      int(43)
      ["args"]=>
      array(1) {
        [0]=>
        string(70) "/humhub/protected/humhub/modules/admin/config.php"
      }
      ["function"]=>
      string(7) "require"
    }
```

**Comment by buddh4** [comment]
Thanks for the clarification, I've added the error logs to the module loader.
We could probably solve this by using strings only in the event configuration.
