### ISSUE TITLE
Enhancement: Add date of events into mail digest

### ISSUE THREAD

**Issue by benedetto** [humhub/humhub#2651]
We use humhub to coordinate our sports team. Accordingly we have events called "Training" that occur on a weekly basis. Unfortunately, if people change their attendance state on one of the training events, the mail digest says something along the lines of "[Name] takes part in 'Training' in Space [...]". This text does not give any hint about which of the upcoming four or five training dates the person has edited.

As a workaround, we can give every training event an individual name that includes the date. However, that is error prone in the long run. Therefore it would be great if the mail notification could contain the date of the event that was changed.

I would also try to implement that myself if someone could point me to the file where the mail notification text is generated.

**Comment by SupeRobbY** [comment]
You can try on the  translation module.


Il 03/lug/2017 20:31, "benedetto" <notifications@github.com> ha scritto:

**Comment by buddh4** [comment]
I've added an enhacement ticket to the module respository.
