### ISSUE TITLE
Custom Pages snippet and templates

### ISSUE THREAD

**Issue by byndstd** [humhub/humhub#2653]
Hello friends I'm using humhub and custom pages but I don't know what snippet and templates 
templates : Templates allow you to define combinable page fragments with inline edit functionality.
snippet ?
Can anyone explain more or if that plugin have tutorial 

Thank you

**Comment by buddh4** [comment]
Hi, I've planned to write a small tutorial this week. I'll let you know once finished. Snippets are sidebar panels (for example the Activity stream panel). The custom pages module allows you to create snippet layouts and page layouts.

**Comment by byndstd** [comment]
thank you very much
I appreciate your tutorial and your reply

**Comment by funkycram** [comment]
Hy @buddh4 , I would be great if they was a small explanation of the Templates part. Pages an snippets are really wonderful and very easy to use. Thanks a lot for this great module !!

**Comment by buddh4** [comment]
Thanks for the feedback, we are currently working on enhancing the module descriptions/guides etc.

**Comment by Buliwyfa** [comment]
👍

**Comment by petrk94** [comment]
@buddh4 
how far are you with the tutorial? I would like to check that, any link?
Thanks
