### ISSUE TITLE
Ubuntu / Apache2 / Lets encrypt / URL rewrite

### ISSUE THREAD

**Issue by RAFd3v** [humhub/humhub#2656]
I have a massive problem.

I'm running humhub on ubuntu 16.04 server with apach2 / php7.
SSL cert from lets encrypt.

How can I get the URL rewrite running?
In the manual aren't enough informations to get it running for me :(

always getting the error:

Not Found

The requested URL /dashboard was not found on this server.

**Comment by acs-ferreira** [comment]
This shoul be enough (i have the same config): http://docs.humhub.org/admin-installation-configuration.html#url-rewriting-optional

**Comment by RAFd3v** [comment]
That's what I did. Any further instructions?
Is there any other file which I need to edit? Or do I have to point at the edited file?

**Comment by acs-ferreira** [comment]
No, just be sure you have the `.htaccess` file at the root with [this content](https://raw.githubusercontent.com/humhub/humhub/master/.htaccess.dist) and the `protected/config/common.php` file with [that content](http://docs.humhub.org/admin-installation-configuration.html#url-rewriting-optional).

I can't see why it shouldn't work _if_ Apache is configured properly...

**Comment by RAFd3v** [comment]
with a2enmod rewrite?

**Comment by Felli** [comment]
Pull up your terminal and type `a2enmod rewrite` then try restarting your Apache2, after please provide any issues that popup.

**Comment by 001101** [comment]
I am thinking about how it is possible to rewrite the ugly UGID (user ID) at profiles, any suggestions?

**Comment by Felli** [comment]
@001101 might be for the best to create a new question issue with more detail into what you're wanting to do with the user ID.
