### ISSUE TITLE
m160220_013525_contentcontainer_id does not work if the User identity class is overridden

### ISSUE THREAD

**Issue by devantoine** [humhub/humhub#2657]
I've overridden the User's identity class in common.php.
When a user post a `content`, the `class` in `contentcontainer` is set to my custom class.

When running the `m160220_013525_contentcontainer_id` migration (which removes the `space_id` and `column_id` in the `content` table it results in a lot of NULL values for the `content.contentcontainer_id` column because it can't find a match due to the overridden identity not being used:

```php
$this->update('content', [
            'contentcontainer_id' => new Expression('(SELECT id FROM contentcontainer WHERE class=:userModel AND pk=user_id)', [':userModel' => \humhub\modules\user\models\User::className()])
                ], ['IS', 'space_id', new Expression('NULL')]
        );`
```

Context: migrating from 1.0.1 to 1.2.1.

**Comment by githubjeka** [comment]
Migrations should not use code which can be updated/deleted by anytime. That why it's bug.

**Comment by githubjeka** [comment]
It's hard to say how it should be in that migration so that it works with any code.

**Comment by devantoine** [comment]
@githubjeka Why not just take the current user's identity class?

**Comment by githubjeka** [comment]
because it's console layer. user component not loaded

**Comment by devantoine** [comment]
@githubjeka No way to parse the common.php file,

**Comment by githubjeka** [comment]
:) this code BC and because can be fixed manually. It's correct way, others - сrutches.

**Comment by devantoine** [comment]
Well, it's the actual line in the migration file.

Any way, I've wrote a custom migration for this so it's not an issue for me but I just wanted to let you know.
