### ISSUE TITLE
Error when uploading zip

### ISSUE THREAD

**Issue by AsimPervez93** [humhub/humhub#2658]
Apologies if this has already been answered.

I'm trying to upload a 5mb zip file to the Files module and get the below error:
![image](https://user-images.githubusercontent.com/17923501/28162122-e88767ce-67bd-11e7-8be3-658a48fdaa76.png)

I've made changes to my php as the error suggests:
![image](https://user-images.githubusercontent.com/17923501/28162159-0883281a-67be-11e7-934c-d84e77c34789.png)
![image](https://user-images.githubusercontent.com/17923501/28162168-14a04484-67be-11e7-9d34-d1f71d53234b.png)

Still the error persists.  Any advice?

**Comment by Felli** [comment]
First please try clearing your cache then after this try again, if it still doesn't work for you please provide any full error stacks in ACP > Information > Logging as well as any browser console errors that might show up.

**Comment by AsimPervez93** [comment]
@Felli, Thanks for your reply.

I cleared my cache and still not working.  I don't actually think I have APC installed, I can't see anything referring to it in the php info.  I've tried to find some instructions on how to install php-apc but I get errors when I try and install.  Can you point me in the right direction on how to install php-apc?

**Comment by AsimPervez93** [comment]
@Felli ,

I tried installing memcached, cleared cache, and tried uploading again but still getting the error.

Running out of ideas...

**Comment by AsimPervez93** [comment]
I managed to figure this out.  It was incredibly basic...I found this option in the settings and increased the limit to match PHP:
![image](https://user-images.githubusercontent.com/17923501/28176348-ed9b70ee-67ee-11e7-99c2-b947e6a62c53.png)
