### ISSUE TITLE
Add a simple script

### ISSUE THREAD

**Issue by MrCapone98** [humhub/humhub#2663]
Hello, I would like to add a script to the page in the <head> but it is not loaded in any of the files. In what file should I add the script?

This is my script:

<script>$(".visible-md a[href*='custom']").parent().prependTo(".nav.pull-right");</script>

**Comment by buddh4** [comment]
You can add scripts to https://github.com/humhub/humhub/blob/master/protected/humhub/views/layouts/head.php which will be apended to your html head. Note that you have to add  your script into [$( document ).ready()](https://learn.jquery.com/using-jquery-core/document-ready/)

**Comment by MrCapone98** [comment]
I added this in my head.php file and not worked: 
```
<script >
		$(function() {
  			 $(".visible-md a[href*='custom']").parent().prependTo(".nav.pull-right");
});</script>

```

**Comment by buddh4** [comment]
sorry, I won't help you with your javascript code, add a `debugger;` and check for yourself and check the javascript console etc.

**Comment by MrCapone98** [comment]
In the javascript console works fine i tested
