### ISSUE TITLE
Multiple LDAP hosts

### ISSUE THREAD

**Issue by mpndev1** [humhub/humhub#2665]
Are there any possibilites to add multiple LDAP Hosts. I want to connect multiple Active Directorys from different hosts. 
Thank you in advance 👍

**Comment by Felli** [comment]
I'm not sure that this is possible with HumHub, @buddh4 or @luke- would have to discuss something like this.

**Comment by acs-ferreira** [comment]
Try to array them on common.php config file (not tested):

'params' => [ 'ldap' => [ 'dn' => [ 'somedn'], ...],

Just like for Facebook, see http://docs.humhub.org/admin-authentication.html

(Only guessing)

**Comment by luke-** [comment]
Possible with Professional Edition
