### ISSUE TITLE
Notification tab issue with *.jpg in Media

### ISSUE THREAD

**Issue by sergelapaev** [humhub/humhub#2666]
Hello,
When somebody "likes" a picture in gallery. I got notification on top bell icon ( "somebody likes pictures", it seem like everything is ok. ) But if I make a left click to this notification, it trying to open something and show "non human" readable information at the end. 

If I make right click and click "Open link in new tab" it opens normally in new tab.

Thank you for your help

![56](https://user-images.githubusercontent.com/30300491/28389259-3f0e25d0-6c8a-11e7-8493-3a79de734433.JPG)

![after](https://user-images.githubusercontent.com/30300491/28386794-90ea8f96-6c81-11e7-943f-4f0d854598b6.JPG)

**Comment by Felli** [comment]
I can confirm this is an issue.

**Comment by buddh4** [comment]
Should be fixed https://github.com/humhub/humhub-modules-gallery/commit/56c65106fb360a39c5f4eb46ad1b1e9a951e7134
