### ISSUE TITLE
Posting a comment returns a 500: yii\base\Exception: Could not find content of addon!

### ISSUE THREAD

**Issue by devantoine** [humhub/humhub#2668]
After saving a comment, `Comment::afterSave()` is called. This method calls `BaseNotification::sendBulk()` which instances `SendBulkNotification` to be serialized in `Queue::push()`.

The error occurs when the application is in the `STATE_AFTER_REQUEST` state. In this state the queue runs all the jobs (`Sync::run()`) and thus, unserializes the `SendBulkNotification` object.

What happens is that this serialized object doesn't hold neither the `$_content` nor `$_source` properties, which are (at least one is) mandatory to get the content of the `Comment` hold by `SendBulkNotification`.

When an object is serialized by Yii, the `ActiveRecord::serialize()` method is called. It calls `Model::getAttributes()` without any argument. `Model::getAttributes()` without argument calls `ActiveRecord::attributes()` to get the attributes to be serialized. This methods, as the doc states:

> Returns the list of all attribute names of the model.
The default implementation will return all column names of the table associated with this AR class.

The issue is right there: "all column names of the table". Neither `$_content` nor `$_source` are columns, they are just some sort of meta data properties.

The almost right method to be called should be `Model::attributes()` which uses the reflection to get all the public properties but since `$_content` and `$_source` are private it wouldn't work either.

The only ugly fix I've found is to extend `Comment::serialize()` like this:

```php
<?php
namespace foo\modules\comment\models;

class Comment extends \humhub\modules\comment\models\Comment
{
    /**
     * @inheritdoc
     */
    public function serialize()
    {
        $attributes = $this->attributes();
        $attributes[] = '_content';
        $attributes[] = '_source';

        return serialize([
            'attributes' => $this->getAttributes($attributes),
            'oldAttributes' => $this->getOldAttributes()
        ]);
    }
}

```

And then copy/paste `CommentController::postAction()` to use my own model.

**Comment by buddh4** [comment]
Can you post the full error stack please? Is this thrown when creating the comment mail?

**Comment by devantoine** [comment]
@buddh4 Here you go:

```
2017-07-21 11:39:33 [172.18.0.1][1][52d320fa9a45b1b65e6cad2072fd06cb][error][yii\base\Exception] yii\base\Exception: Le contenu du add-on n'a pu être trouvé ! in /var/www/html/vendor/humhub/humhub/protected/humhub/modules/content/components/ContentAddonActiveRecord.php:74
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/Component.php(132): humhub\modules\content\components\ContentAddonActiveRecord->getContent()
#1 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(286): yii\base\Component->__get('content')
#2 /var/www/html/vendor/humhub/humhub/protected/humhub/components/SocialActivity.php(165): yii\db\BaseActiveRecord->__get('content')
#3 /var/www/html/vendor/humhub/humhub/protected/humhub/components/SocialActivity.php(213): humhub\components\SocialActivity->getContent()
#4 /var/www/html/vendor/humhub/humhub/protected/humhub/components/SocialActivity.php(176): humhub\components\SocialActivity->getContentContainer()
#5 /var/www/html/vendor/humhub/humhub/protected/humhub/components/SocialActivity.php(186): humhub\components\SocialActivity->getSpace()
#6 /var/www/html/vendor/humhub/humhub/protected/humhub/modules/notification/components/BaseNotification.php(226): humhub\components\SocialActivity->getSpaceId()
#7 /var/www/html/vendor/humhub/humhub/protected/humhub/components/SocialActivity.php(394): humhub\modules\notification\components\BaseNotification->about(Object(foo\modules\comment\models\Comment))
#8 [internal function]: humhub\components\SocialActivity->unserialize('a:2:{s:6:"sourc...')
#9 /var/www/html/vendor/zhuravljov/yii2-queue/src/serializers/PhpSerializer.php(32): unserialize('O:53:"humhub\\mo...')
#10 /var/www/html/vendor/zhuravljov/yii2-queue/src/Queue.php(87): zhuravljov\yii\queue\serializers\PhpSerializer->unserialize('O:53:"humhub\\mo...')
#11 /var/www/html/vendor/humhub/humhub/protected/humhub/components/queue/driver/Sync.php(68): zhuravljov\yii\queue\Queue->handleMessage('O:53:"humhub\\mo...')
#12 /var/www/html/vendor/humhub/humhub/protected/humhub/components/queue/driver/Sync.php(48): humhub\components\queue\driver\Sync->run()
#13 [internal function]: humhub\components\queue\driver\Sync->humhub\components\queue\driver\{closure}(Object(yii\base\Event))
#14 /var/www/html/vendor/yiisoft/yii2/base/Component.php(545): call_user_func(Object(Closure), Object(yii\base\Event))
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(382): yii\base\Component->trigger('afterRequest')
#16 /var/www/html/web/index.php(21): yii\base\Application->run()
#17 {main}
2017-07-21 11:39:33 [172.18.0.1][1][52d320fa9a45b1b65e6cad2072fd06cb][info][application] $_SERVER = [
    'REDIRECT_STATUS' => '200'
    'HTTP_HOST' => 'localhost'
    'HTTP_CONNECTION' => 'keep-alive'
    'CONTENT_LENGTH' => '191'
    'HTTP_ORIGIN' => 'http://localhost'
    'HTTP_X_CSRF_TOKEN' => 'L4kG8WoBsZGTw-09sOxBd4pA8sqUatWdy2_7Nu2ziDPryoKdJAE2H-dz8h5SovEsbstarVuttsFay-7Y2fbBLQ=='
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'
    'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8'
    'HTTP_ACCEPT' => '*/*'
    'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
    'HTTP_REFERER' => 'http://localhost/event/event/show?id=73'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,fr;q=0.6'
    'HTTP_COOKIE' => 'XDEBUG_SESSION=PHPSTORM; language=816fa8f6232f554eddb0c2593d1cecbe77380c21445289783daf77059c30f98fa%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22fr%22%3B%7D; _csrf=1c1b50f205a58b05b92285183f0a02fc36fe570a28a156bd8e9d8d6a5e4f1e2ea%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22%C4C%84lN%00%87%8Et%B0%1F%23%E2N%B0%5B%E4%8B%A8g%CF%C7c%5C%91%A4%15%EE4EI%1E%22%3B%7D; PHPSESSID=52d320fa9a45b1b65e6cad2072fd06cb; _gat=1; _ga=GA1.1.1693793194.1499868017; _gid=GA1.1.540667668.1500280307; _identity=5f940483a78721ccc28193b79ce4058983594885dbfdb370c3230e85477158dba%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%227d9f57e4-0734-41b4-aa07-717d6cd51536%22%2C2592000%5D%22%3B%7D'
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'SERVER_SIGNATURE' => '<address>Apache/2.4.10 (Debian) Server at localhost Port 80</address>
'
    'SERVER_SOFTWARE' => 'Apache/2.4.10 (Debian)'
    'SERVER_NAME' => 'localhost'
    'SERVER_ADDR' => '172.18.0.3'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => '172.18.0.1'
    'DOCUMENT_ROOT' => '/var/www/html/web'
    'REQUEST_SCHEME' => 'http'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/web'
    'SERVER_ADMIN' => 'webmaster@localhost'
    'SCRIPT_FILENAME' => '/var/www/html/web/index.php'
    'REMOTE_PORT' => '60782'
    'REDIRECT_URL' => '/comment/comment/post'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'POST'
    'QUERY_STRING' => ''
    'REQUEST_URI' => '/comment/comment/post'
    'SCRIPT_NAME' => '/index.php'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1500629973.296
    'REQUEST_TIME' => 1500629973
    'argv' => []
    'argc' => 0
]
```

**Comment by buddh4** [comment]
Hmm, the `ContentAddonActiveRecord` should be able to lazily load the `source` and therefore also the content since `$this->source->content` will call [ContentAddonActiveRecord ::getSource()](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/ContentAddonActiveRecord.php#L85) and load the content in [this](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/ContentAddonActiveRecord.php#L68) line. For me it seems that the comment has no valid source data set (object_model, object_id) furthermore I could not reproduce this issue yet. 

Correct me if I missed something, I just did a quick check of the code.

Does this happen for all comments on all content types (Posts/Polls etc) or only for certain types.

**Comment by devantoine** [comment]
I can post a screen of the debugger showing that the `$_source` and `$_content` properties are set before serializing the object.

`ContentAddonActiveRecord` can't load the source because there's no content/source on the object when being unserialized (because it hasn't been in the first place).

It happens on Post and a custom Event module. I have no other content to test.

**Comment by buddh4** [comment]
Yes, `$_source` and `$_content` are the cached values, it should not matter if they are null. If `$_source` is null the source model should be loaded when calling `$this->source`. 
Can you check the values of `object_model` and `object_id` of your ContentAddonActiveRecord. 

Perhaps the source model was not saved correctly.

**Comment by devantoine** [comment]
Here's the debug's dump of `NewComment` object before it's serialized. As you can see it holds the `Comment` as the `source` property and the attributes looks fine.

![hh-bug-source](https://user-images.githubusercontent.com/1639739/28515000-5967b524-705c-11e7-97f0-8747af5c9869.png)

When trying to deserialize it in `ContentAddonActiveRecord::getContent()` everything is null.

**Comment by buddh4** [comment]
As I said please check the `object_model` and `object_id` attributes of your `ContentAddonActiveRecord` instance. As long as those attributes are pointing to a valid ActiveRecord which is already persisted in the db `ContentAddonActiveRecord::getContent()` should always return a valid content no matter if `source` or `_source` or `_content` is null.

I'am aware that `source` is not serialized but it should be retrieved lazily.

**Comment by devantoine** [comment]
@buddh4 You can see in the screen the `object_model` and `object_id` of the `Comment` instance, both set.
I'm just wondering if it makes sense to have an`object_model` set to `Event` and not `Comment`?

**Comment by devantoine** [comment]
Here's the `Comment` dump when unserialization raises the exception:

![hh-bug-unserialize](https://user-images.githubusercontent.com/1639739/28615369-13b44030-71f9-11e7-9e04-a7770a09138e.png)
