### ISSUE TITLE
Different mistakes

### ISSUE THREAD

**Issue by Bernd-Wessel** [humhub/humhub#2670]
In my HumHub installation several mistakes have turned out meanwhile.
   
  1. The function notes does not go, they cannot be put on
  2. The rights also do not go, I had the Funktion Spaces flat provide put down and members Spaces could still provide.
  3. Presenters and other Admins are not marked obviously
  4. The functions of the visibility for the Spaces flat also do not function well. Then in spite of flawless settings (Obviously) they are not visible.
  5. Invitations in the Spaces  flat do not go out any more by mail to the members.
![humhub](https://user-images.githubusercontent.com/30322887/28455480-81f1622e-6dff-11e7-9258-8fab03edcfd1.JPG)

**Comment by buddh4** [comment]
You should open distinct issues for your problems, it's hard to discuss all of them at once, also provide some further information. 

- What fails exactly?
- How to reproduce?
- Which HumHub version?
- Did this occure after an update, and did it work before?
- etc..

Which function "Notes" do you mean do you mean the Etherpad Notes module?
Also sorry but I don't understand some of the issues. If you like, you can also join the communiy (https://community.humhub.com) there is a german space, perhaps it's more convenient for you.
