### ISSUE TITLE
zhuravljov/yii2-queue is abandoned

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2671]
Code has been moved to `yii` namespace.
https://github.com/yiisoft/yii2-queue

See commit https://github.com/humhub/humhub/commit/ac3ef620565f3c5592d6ae75103e74aac00052d4

**Comment by acorncom** [comment]
Looks like this has been resolved

**Comment by acs-ferreira** [comment]
1.3 ?
