### ISSUE TITLE
Sticker / Emoji

### ISSUE THREAD

**Issue by NENJAK** [humhub/humhub#2673]
Hi,
Is somebody working on sticker and emoji module?

**Comment by acs-ferreira** [comment]
Emojis are already implemented, just type `:` and they should appear.

**Comment by NENJAK** [comment]
I know about : 
I need / ask about real emojis / stickers like Facebook has,
It should be clickable and placed in the bar next to upload image

**Comment by acs-ferreira** [comment]
I've submitted a similar feature here https://github.com/humhub/humhub/issues/2415
