### ISSUE TITLE
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method

### ISSUE THREAD

**Issue by tfont** [humhub/humhub#2674]
I've receiving

`Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: humhub\modules\file\models\File::getPath()'`

 when running migrations `php yii migrate/up --includeModuleMigrations=1` from a freshly download version of 1.2.1?

What's going on?

**Comment by tfont** [comment]
I've actually downloaded from the site 1.2.1 and attempted to do a fresh installation. After step one of putting in the database credentials, I received the same error on the next page:

`
An Error occurred while handling another error:
exception 'ReflectionException' with message 'Method humhub\modules\file\models\File::getPath() does not exist' in ...\protected\vendor\yiisoft\yii2\web\ErrorHandler.php:195`

**Comment by buddh4** [comment]
please add the full error stacfk

**Comment by tfont** [comment]
`$ php yii migrate/up --includeModuleMigrations=1`

Yii Migration Tool (based on Yii v2.0.12)

Total 37 new migrations to be applied:
        m160125_053702_stored_filename
        m160205_203840_foreign_keys
        m160205_203913_foreign_keys
        m160205_203939_foreign_keys
        m160205_203955_foreign_keys
        m160205_204000_foreign_keys
        m160205_204010_foreign_keys
        m160205_205540_foreign_keys
        m160216_160119_initial
        m160217_161220_addCanLeaveFlag
        m160220_013525_contentcontainer_id
        m160221_222312_public_permission_change
        m160225_180229_remove_website
        m160227_073020_birthday_date
        m160229_162959_multiusergroups
        m160309_141222_longerUserName
        m160408_100725_rename_groupadmin_to_manager
        m160415_180332_wall_remove
        m160501_220850_activity_pk_int
        m160507_202611_settings
        m160508_005740_settings_cleanup
        m160509_214811_spaceurl
        m160517_132535_group
        m160523_105732_profile_searchable
        m160714_142827_remove_space_id
        m161031_161947_file_directories
        m170110_151419_membership_notifications
        m170110_152425_space_follow_reset_send_notification
        m170111_190400_disable_web_notifications
        m170112_115052_settings
        m170118_111823_queuetable
        m170118_162332_streamchannel
        m170119_160740_initial
        m170123_125622_pinned
        m170211_105743_show_in_stream
        m170224_100937_fix_default_modules
        m170307_170300_queuelater

Apply the above migrations? (yes|no) [no]:yes
*** applying m160125_053702_stored_filename
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: humhub\modules\file\models\File::getPath()'

in C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\vendor\yiisoft\yii2\base\Component.php:290

Stack trace:
#0 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\humhub\modules\file\migrations\m160125_053702_stored_filename.php(12): yii\base\Component->__call('getPath', Array)
#1 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\humhub\modules\file\migrations\m160125_053702_stored_filename.php(12): humhub\modules\file\models\File->getPath()
#2 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(671): m160125_053702_stored_filename->up()
#3 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(183): yii\console\controllers\BaseMigrateController->migrateUp('m160125_053702_...')
#4 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#5 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#6 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#7 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\vendor\yiisoft\yii2\console\Controller.php(128): yii\base\Controller->runAction('up', Array)
#8 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\vendor\yiisoft\yii2\base\Module.php(523): yii\console\Controller->runAction('up', Array)
#9 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#10 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate/up', Array)
#11 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\vendor\yiisoft\yii2\base\Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 C:\Users\Travis\Dropbox\www (wamp)\wwwroot\site\protected\yii(29): yii\base\Application->run()
#13 {main}

**Comment by happyfredo** [comment]
Ok i'l try to manual update version by version to analyse if it happen...

**Comment by luke-** [comment]
Can you please try to replace following file:
https://github.com/humhub/humhub/commit/d1cbaa7abda601cd4c3e53f65b8a3e8808ec2580

Full file:
https://raw.githubusercontent.com/humhub/humhub/d1cbaa7abda601cd4c3e53f65b8a3e8808ec2580/protected/humhub/modules/file/migrations/m160125_053702_stored_filename.php

And restart migration...
