### ISSUE TITLE
Translations (translate.humhub.org)

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2679]
When you update translation from translate.humhub.org then you reset translation which that has been added in GitHub

See for example https://github.com/humhub/humhub/commits/master/protected/humhub/modules/space/messages/ru/widgets_SpacePickerField.php

Please check your method to update from translate.humhub.org

and apply my commit please again https://github.com/humhub/humhub/commit/68539807b3f1fad2db2e5c1ab4cbf2c8a4b7e840

UPDATE: https://github.com/humhub/humhub/pull/2680 PR to revert

**Comment by buddh4** [comment]
Don't know how the synchronization is done in translat.humhub.org, but translations over translate.humhub.org are prefered over direct git commits, since there can be conflicts with bot commits.
