### ISSUE TITLE
Pending user registrations

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2692]
For https://github.com/humhub/humhub/commit/3f741da0a298a0ba7e516d1188c44a7904ae6a62

- Exported XLSX is corrupted (CSV OK)
- We should be able to delete pending registrations (check-boxes and delete action)
- Perhaps also maybe re-send invitations to those users (check-boxes and re-send action)
- PHPExcel (_abandoned_) is used, we should use maintained (_dev-master_) version from the same vendor, https://github.com/PHPOffice/PhpSpreadsheet

**Comment by buddh4** [comment]
Thanks was the wrong mime type.
Regarding the other features yes this was pretty much a last minute feature, will try to migrate to phpspreadsheet, thanks.

**Comment by buddh4** [comment]
> However PhpSpreadsheet is still unstable and not yet released.

**Comment by acs-ferreira** [comment]
I understand, here we're using this to export to CSV and TSV on another Yii2 project, maybe you can consider this: https://github.com/yii2tech/csv-grid

**Comment by buddh4** [comment]
Looks, nice we'll definetly consider it once its stable, of course we should not depend on abonded libraries, thanks for the info!
