### ISSUE TITLE
Better error message when mail sending is failing

### ISSUE THREAD

**Issue by arnfinnkristensen** [humhub/humhub#2699]
This is probably an issue that is not commen but I think it is good to creat a better error message anyway. The case is like this:
I have instaled HumHub on my local computer for testing. I have registerd the correct mail info for sending mail from HumHub into the system (using gmail), BUT I have not opend in my gmail account for sending emails from humhub (it is a security setting that I can switch of and on). 
So when I tried to registrer a new user into my local HumHub instalation I got a crazy error message shown below: 
![image](https://user-images.githubusercontent.com/30318362/28960534-5d5289f6-78ff-11e7-8533-eab4411b1290.png)

I understand the reason why and can fix it, BUT the system should tell the user that an error has happend. For a normal user the might think that they have done something wrong. 

My conclusion:
Make a better error message when mail sending is failing.

**Comment by githubjeka** [comment]
```php
try {
} catch() {
Yii::t('error', 'Message not sent');
// continue
}
