### ISSUE TITLE
Group with Manager User permission can edit Administrators user

### ISSUE THREAD

**Issue by kakadanhem** [humhub/humhub#2700]
I created a group with Manager User permission. All user in that group can manager users, that is expected. But I think they MUST NOT be able to manage users in Administrators group at all as currently those users with Manager User permission can manage anyone.

**Comment by githubjeka** [comment]
![image](https://user-images.githubusercontent.com/874234/28962048-11acbdd8-790d-11e7-9833-1c5c3c410721.png)

Funny
