### ISSUE TITLE
Remove the spaces and make the site a "global space"

### ISSUE THREAD

**Issue by hotgeart** [humhub/humhub#2701]
Hi,

There's a way to just have a "global space" ? I want to use humhub like an intranet (15 persons), so we don't need to create more than one space. There's a way to hide the space system and just make a default and global space ?

Thx

**Comment by buddh4** [comment]
You could just disallow users to create spaces, and set a central space as home page. In your theme you could hide/overwrite the space chooser and just add a home icon or something.

Nontheless I think the space concept is useful in most cases to seperate content, perhaps you have seperated projects/discussions/topics.
