### ISSUE TITLE
[BUG] Directory module is ignoring Yii ACL

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#2703]
Hacked around the /protected/humhub/modules/directory/controllers/DirectoryController.php
Is now complete ignored since HumHub 1.2.2

**:::Before::::**
```
  public function behaviors()
    {
        return [
            'acl' => [
                'class' => \humhub\components\behaviors\AccessControl::className(),
                'guestAllowedActions' => ['groups', 'index', 'members', 'spaces', 'user-posts', 'stream']
            ]
        ];
    }
```

**:::After::::**
```

public function behaviors()
    {
        return [
            'acl' => [
                'class' => \humhub\components\behaviors\AccessControl::className(),
                'guestAllowedActions' => []
            ]
        ];
    }
```
Please fix asap, because it allows to have a basic information about the site, without revealing any spaces, users and stats to crawlers, many thanks!!

greets

**Comment by buddh4** [comment]
So you mean you changed manually from "before" to "after".
The problem is with your config is if no actions are given the a rule is considered to be controller global, just add "login" rule to only grant logged in users and remove the guestAllowedActions rule.

**Comment by 001101** [comment]
@buddh4 Thank you very much for the quick fix, it is working now just like before, great!

But I have found some more issues and just wondering why those deprecated functions did not got replaced within the update.

For me this is a update Wahn, because old working features got screwed up for new one which also not works perfectly, in the end result the product got hurt, so please be a bit more careful with changing such elementary things.

I hope after the weekend I have some hours free time to figure out the other bugs I found.

best wishes

**Comment by buddh4** [comment]
The `guestAllowedActions` was never intended to disallow guest access on controller level, there always have been a `loggedInOnly` and `adminOnly` flag in the [AccessControl](https://github.com/humhub/humhub/blob/master/protected/humhub/components/behaviors/AccessControl.php#L81) behaviour alongside the `guestAllowedActions`. 

One reason for rewriting the controller access layer was testability, now the actual logic is not stuck in an ActionFilter anymore but resides in a more convenient [ControllerAccess](https://github.com/humhub/humhub/blob/master/protected/humhub/components/access/ControllerAccess.php) class, which is way more flexible.

Normally we introduce such changes only in major releases, but this change was rather important.
