### ISSUE TITLE
The verification of permissions. Permission for guests.

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2704]
```php
class MyPermission extends \humhub\libs\BasePermission
{
    /**
     * Deny access for Guest
     */
    protected $fixedGroups = [
        User::USERGROUP_GUEST
    ];
}
```

But to check this permission need write code in every places:
```php
if (Yii::$app->user->isGuest || !Yii::$app->user->can(new MyPermission()) {
  $this->forbidden();
}
```

```php
if (!Yii::$app->user->isGuest && Yii::$app->user->can(new MyPermission()) {
  echo HtmlButtoon::widget();
}
```

faced?

**Comment by buddh4** [comment]
The User::USERGROUP_GUEST and SPACE::USERGROUP_GUEST are contentcontainer related usergroups, which can't be verified for global group permissions.

In v1.2.2 you should be able to handle controller access like this:

```
public function getAccessRules()
{
    return [
        ['permission' => MyPermission::class, 'actions' => ['action1', 'action2']]
    ];
}
```

But global permissions currenlty can't be granted for guest users.

**Comment by githubjeka** [comment]
I haven't `$container` on my a page. 
```php
DashboardController extends \humhub\components\Controller {
}
```

This page availible for guest. But button should be checked by Permission

```php
if (!Yii::$app->user->isGuest && Yii::$app->user->can(new MyPermission()) {
  echo HtmlButtoon::widget();
}
```

It's problem for me.

Need [like this](http://www.yiiframework.com/doc-2.0/yii-rbac-checkaccessinterface.html#checkAccess()-detail):

```
Yii::$app->authManager->checkAccess(Yii::$app->user, new MyPermission())
```

**Comment by buddh4** [comment]
You could use the Button api (since 1.2.2):

```
Button::primary('text')->visible(Yii::$app->user->can(MyPermission::class));
```

Does it throw an exception for users or what is your problem, normally `Yii::$app->user->can(new MyPermission())` should exclude guest users?

**Comment by githubjeka** [comment]
So, once again

I haven't $container on my a page. This page availible for guest. When you write `Yii::$app->user->can(...`
to show button you get error because `Yii::$app->user` is NULL for guest. 

In RBAC have 
```
Yii::$app->authManager->checkAccess(Yii::$app->user, new MyPermission())
```
In HumHub no elegant solution was found. The code:

```
if (!Yii::$app->user->isGuest && Yii::$app->user->can(new MyPermission()) {
  echo HtmlButtoon::widget();
}
```
is bad, because MyPermission involves checking for guest access by
```php
class MyPermission extends \humhub\libs\BasePermission
{
    /**
     * Deny access for Guest
     */
    protected $fixedGroups = [
        User::USERGROUP_GUEST
    ];
}
```

🥀

**Comment by buddh4** [comment]
`Yii::$app->user` is not null for guests only `Yii::$app->user->identity` which is not a problem if you call `Yii::$app->user->can(MyPermission::class)` this call should always return false for guest users, in case you get an error nonetheless , please show me the error stack.

**Comment by githubjeka** [comment]
Overworked, sorry for the trouble.

**Comment by buddh4** [comment]
Haha, no problem, I know the struggle ;)
