### ISSUE TITLE
Session cookie should have secure flag if set over https

### ISSUE THREAD

**Issue by stoennies** [humhub/humhub#2706]
This cookie, which has been sent over an encrypted channel, doesn't have the secure flag set. As a result, an active network attacker can easily recover it.

**Comment by acs-ferreira** [comment]
@stoennies @githubjeka see #2708 if it helps.

**Comment by githubjeka** [comment]
https://github.com/yiisoft/yii2/issues/13486

**Comment by stoennies** [comment]
@acs-ferreira this worked! Thanks!
