### ISSUE TITLE
HumHub Link should point to HTTPS

### ISSUE THREAD

**Issue by stoennies** [humhub/humhub#2707]
The HumHub Link on the LoginForm should link to the secure version of the HumHub-Website.

**Comment by githubjeka** [comment]
on the LoginForm? Where .. link please.

**Comment by githubjeka** [comment]
![image](https://user-images.githubusercontent.com/874234/29072754-afadc2ba-7c51-11e7-93ee-c2689aaf448a.png)

**Comment by githubjeka** [comment]
![image](https://user-images.githubusercontent.com/874234/29072762-bc5fb194-7c51-11e7-868a-e70e02163b0d.png)

**Comment by stoennies** [comment]
I am writing about the "Powered by" line on the login form.

![grafik](https://user-images.githubusercontent.com/3594190/29109813-b5f59182-7ce4-11e7-89e6-22e25e40d607.png)

**Comment by Felli** [comment]
Shouldn't really matter as it should auto direct you to the HTTPS link, but I can understand if you're wanting to have your site full HTTPS.

**Comment by luke-** [comment]
Already fixed in latest version. Thanks!
