### ISSUE TITLE
How to send notification to all users with specific subject

### ISSUE THREAD

**Issue by tvskish** [humhub/humhub#2709]
Friends, I wanted to send a notifications to all Hub users with related subject. If I post something in Open Space, with hourly cron job, notifications being delivered to users with subject as "Latest News". Here many users overlooking them. But if the important notification delivers with selected Subject over mail, will have good reach ability.

Thanks!

**Comment by githubjeka** [comment]
http://docs.humhub.org/dev-notifications.html

**Comment by tvskish** [comment]
Thank you githubjeka, will try that.
