### ISSUE TITLE
Redirect from www to non www inline with the existing htaccess file

### ISSUE THREAD

**Issue by stoennies** [humhub/humhub#2710]
Dear all,

I am not an Apache Rewrite good, that's why I a ask how to chnage the rewrite rules in the htaccess.dist file to enable url rewrite AND to redirect users from www.subdomain.domain.tld to subdomain.domain.tld

Any ideas?!

Bests 
Sascha

**Comment by buddh4** [comment]
Please ask such questions within the [community ](http://community.humhub.com/)
