### ISSUE TITLE
Bug, @Mention is clickable when no user selected

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2713]
- Type `@`
- Click on "Please type..."
![image](https://user-images.githubusercontent.com/12234510/29145405-47821ada-7d5d-11e7-8eec-d2fd7e0d325c.png)
- Publish as is
![image](https://user-images.githubusercontent.com/12234510/29145425-5b57bf42-7d5d-11e7-88ef-3a3515abba0f.png)
- Bug
![image](https://user-images.githubusercontent.com/12234510/29145436-6787ecc4-7d5d-11e7-8dde-e3e1693de567.png)

**Comment by Felli** [comment]
I can confirm this on the community site.
