### ISSUE TITLE
$backdrop for ModalGlobal doesn't work

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2714]
After this commit https://github.com/humhub/humhub/commit/dd7545f19dd7476706d346ef3729d21b54456389

`\humhub\widgets\GlobalModal::$backdrop` doesn't work

```php
class GlobalModal extends Modal
{
    /**
     * @inheritdoc
     * It's false because it's often used for serious work, for example html forms,
     * accidental closing of which can lead to loss of user data.
     */
    public $backdrop = false;
}
```

Please revert or fix it. It's very critical for UI forms of Global Modal

P.S. To fix it need just delete js from static/js/humhub/humhub.ui.modal.js by the [commit](https://github.com/humhub/humhub/commit/dd7545f19dd7476706d346ef3729d21b54456389).

**Comment by buddh4** [comment]
This should be handled by the `closable` flag of [ModalDialog](https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/ModalDialog.php#L46), some dialogs require this behaviour and some do not. Perhaps we should set the `closable` flag to false by default?

**Comment by githubjeka** [comment]
```php
class GlobalModal extends Modal
{
    /**
     * @inheritdoc
     * It's false because it's often used for serious work, for example html forms,
     * accidental closing of which can lead to loss of user data.
     */
    public $backdrop = false;
    public $closable = false;
}
```

This code doesn't help to fix tihs issue.

**Comment by githubjeka** [comment]
After added console.log in static/js/humhub/humhub.ui.modal.js
![image](https://user-images.githubusercontent.com/874234/29258895-46c34af8-80c6-11e7-85b3-50042963c4f8.png)

in console of browser you can see

![image](https://user-images.githubusercontent.com/874234/29258913-74e9512a-80c6-11e7-9ab9-aefe04edd41a.png)

**Comment by githubjeka** [comment]
Ok, let see on InviteModal
![image](https://user-images.githubusercontent.com/874234/31877784-6de0713c-b7e0-11e7-9006-f4e4faa0ef69.png)

To show this widget your use \humhub\widgets\ModalDialog that is some kind of subwidget of GlobalModal and render html

```html
<div id="globalModal" class="modal in" data-backdrop="static" data-keyboard="false" data-ui-widget="ui.modal.Modal">

<div id="h539914w0" class="modal-dialog" data-backdrop="static" data-keyboard="false" data-ui-widget="ui.modal.Modal">
```

there are redundant and duplicating attributes `data-backdrop` `data-keyboard` `data-ui-widget`.
It code work but this old code break down.

This code is official from bootstrap and it does not work:
```html
<div id="globalModal" class="modal in" data-backdrop="static" data-keyboard="false" data-ui-widget="ui.modal.Modal">
<div class="modal-dialog">
```

For what you add this commit https://github.com/humhub/humhub/commit/dd7545f19dd7476706d346ef3729d21b54456389 I don't understand?

**Comment by githubjeka** [comment]
Ah
>  some dialogs require this behaviour and some do not. 
Ok, need to think...
