### ISSUE TITLE
Please return STRICT MODE for MySQL

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2715]
Please fix it https://github.com/humhub/humhub/commit/83f69c8b0972bb2ed098a7ed1c4fccdff5f0faf2#commitcomment-23601222

or describe your problem about the grouping of notification

**Comment by luke-** [comment]
Sorry this was a hotfix because the notification grouping was broken by https://github.com/humhub/humhub/commit/b26a23502b9c23db619222f017e10ecf377be67e

We need a better solution which allows notification grouping in strict mode.
Maybe multiple queries...
