### ISSUE TITLE
 PHP Warning – yii\base\ErrorException/ I get this error when trying to register

### ISSUE THREAD

**Issue by skraver** [humhub/humhub#2716]
` 
Error
PHP Warning – yii\base\ErrorException
escapeshellcmd() has been disabled for security reasons

    1. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php at line 259
    250251252253254255256257258259260261262263264265266267268

         * Note that escapeshellarg and escapeshellcmd are inadequate for our purposes, especially on Windows.
         *
         * @param string $string The string to be validated
         *
         * @return bool
         */
        private function _isShellSafe($string)
        {
            // Future-proof
            if (escapeshellcmd($string) !== $string || !in_array(escapeshellarg($string), array("'$string'", "\"$string\""))) {
                return false;
            }
     
            $length = strlen($string);
            for ($i = 0; $i < $length; ++$i) {
                $c = $string[$i];
                // All other characters have a special meaning in at least one common shell, including = and +.
                // Full stop (.) has a special meaning in cmd.exe, but its impact should be negligible here.
                // Note that this does permit non-Latin alphanumeric characters based on the current locale.

    2. yii\base\ErrorHandler::handleError(2, 'escapeshellcmd() has been disabl...', '/home/vol9_6/rf.gd/rfgd_20528298...', 259, ...)
    3. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php at line 259 – escapeshellcmd('social@example.com')
    253254255256257258259260261262263264265

         *
         * @return bool
         */
        private function _isShellSafe($string)
        {
            // Future-proof
            if (escapeshellcmd($string) !== $string || !in_array(escapeshellarg($string), array("'$string'", "\"$string\""))) {
                return false;
            }
     
            $length = strlen($string);
            for ($i = 0; $i < $length; ++$i) {
                $c = $string[$i];

    4. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php at line 288 – Swift_Transport_MailTransport::_isShellSafe('social@example.com')
    282283284285286287288289290291292293294

         *
         * @return string|null
         */
        private function _formatExtraParams($extraParams, $reversePath)
        {
            if (false !== strpos($extraParams, '-f%s')) {
                if (empty($reversePath) || false === $this->_isShellSafe($reversePath)) {
                    $extraParams = str_replace('-f%s', '', $extraParams);
                } else {
                    $extraParams = sprintf($extraParams, $reversePath);
                }
            }
     

    5. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php at line 176 – Swift_Transport_MailTransport::_formatExtraParams('-f%s', 'social@example.com')
    170171172173174175176177178179180181182

                $headers = str_replace("\r\n.", "\r\n..", $headers);
                $subject = str_replace("\r\n.", "\r\n..", $subject);
                $body = str_replace("\r\n.", "\r\n..", $body);
                $to = str_replace("\r\n.", "\r\n..", $to);
            }
     
            if ($this->_invoker->mail($to, $subject, $body, $headers, $this->_formatExtraParams($this->_extraParams, $reversePath))) {
                if ($evt) {
                    $evt->setResult(Swift_Events_SendEvent::RESULT_SUCCESS);
                    $evt->setFailedRecipients($failedRecipients);
                    $this->_eventDispatcher->dispatchEvent($evt, 'sendPerformed');
                }
            } else {

    6. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php at line 85 – Swift_Transport_MailTransport::send(Swift_Message, [])
    79808182838485868788899091

                $this->_transport->start();
            }
     
            $sent = 0;
     
            try {
                $sent = $this->_transport->send($message, $failedRecipients);
            } catch (Swift_RfcComplianceException $e) {
                foreach ($message->getTo() as $address => $name) {
                    $failedRecipients[] = $address;
                }
            }
     

    7. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/yiisoft/yii2-swiftmailer/Mailer.php at line 146 – Swift_Mailer::send(Swift_Message)
    140141142143144145146147148149150151152

            $address = $message->getTo();
            if (is_array($address)) {
                $address = implode(', ', array_keys($address));
            }
            Yii::info('Sending email "' . $message->getSubject() . '" to "' . $address . '"', __METHOD__);
     
            return $this->getSwiftMailer()->send($message->getSwiftMessage()) > 0;
        }
     
        /**
         * Creates Swift mailer instance.
         * @return \Swift_Mailer mailer instance.
         */

    8. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/yiisoft/yii2/mail/BaseMailer.php at line 262 – yii\swiftmailer\Mailer::sendMessage(humhub\components\mail\Message)
    9. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/yiisoft/yii2/mail/BaseMessage.php at line 48 – yii\mail\BaseMailer::send(humhub\components\mail\Message)
    10. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/humhub/modules/user/models/Invite.php at line 137 – yii\mail\BaseMessage::send()
    131132133134135136137138139140141142143

                        ], [
                    'token' => $this->token,
                    'registrationUrl' => $registrationUrl
                ]);
                $mail->setTo($this->email);
                $mail->setSubject(Yii::t('UserModule.views_mails_UserInviteSelf', 'Welcome to %appName%', ['%appName%' => Yii::$app->name]));
                $mail->send();
            } elseif ($this->source == self::SOURCE_INVITE && $this->space !== null) {
     
                if($module->sendInviteMailsInGlobalLanguage) {
                    Yii::$app->language = Yii::$app->settings->get('defaultLanguage');
                }
     

    11. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/humhub/modules/user/models/Invite.php at line 110 – humhub\modules\user\models\Invite::sendInviteMail()
    104105106107108109110111112113114115116

            if ($existingInvite !== null) {
                $this->token = $existingInvite->token;
                $existingInvite->delete();
            }
     
            if ($this->allowSelfInvite() && $this->validate() && $this->save()) {
                $this->sendInviteMail();
                return true;
            }
     
            return false;
        }
     

    12. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/humhub/modules/user/controllers/AuthController.php at line 80 – humhub\modules\user\models\Invite::selfInvite()
    74757677787980818283848586

                return $this->onAuthSuccess($login->authClient);
            }
     
            // Self Invite 
            $invite = new Invite();
            $invite->scenario = 'invite';
            if ($invite->load(Yii::$app->request->post()) && $invite->selfInvite()) {
                if (Yii::$app->request->isAjax) {
                    return $this->renderAjax('register_success_modal', ['model' => $invite]);
                } else {
                    return $this->render('register_success', ['model' => $invite]);
                }
            }

    13. humhub\modules\user\controllers\AuthController::actionLogin()
    14. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([humhub\modules\user\controllers\AuthController, 'actionLogin'], [])
    15. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php at line 156 – yii\base\InlineAction::runWithParams(['r' => 'user/auth/login'])
    16. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/yiisoft/yii2/base/Module.php at line 523 – yii\base\Controller::runAction('login', ['r' => 'user/auth/login'])
    17. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/yiisoft/yii2/web/Application.php at line 102 – yii\base\Module::runAction('user/auth/login', ['r' => 'user/auth/login'])
    18. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/protected/vendor/yiisoft/yii2/base/Application.php at line 380 – yii\web\Application::handleRequest(humhub\components\Request)
    19. in /home/vol9_6/rf.gd/rfgd_20528298/htdocs/index.php at line 25 – yii\base\Application::run()
    19202122232425

        require(__DIR__ . '/protected/humhub/config/web.php'),
        (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
        require(__DIR__ . '/protected/config/common.php'),
        require(__DIR__ . '/protected/config/web.php')
    );
     
    (new humhub\components\Application($config))->run();

Yii Framework

2017-08-13, 20:17:52

Apache

Yii Framework/2.0.12
`
I hope you can give me a solution, regards.

**Comment by Felli** [comment]
You don't have shell access, that or mail service is disabled on your server.

**Comment by skraver** [comment]
How could I activate it?

**Comment by Felli** [comment]
That you'd have to speak to your server providers about.

**Comment by acs-ferreira** [comment]
You should use SMTP instead of `mail()`
