### ISSUE TITLE
Cron job on OVH's servers.

### ISSUE THREAD

**Issue by sam11fr** [humhub/humhub#2718]
Hello.
Managing CRON tasks on OVH servers is disastrous and does not allow you to use the settings.
Is it possible to have a command type cronhourly.php and crondaily.php to work around this problem please? Or if not, would you have a workaround?
Thank you in advance for your feedback.
Regards,
Sam

**Comment by Felli** [comment]
For OVH all you have to do is call to a single `cron.php` file on your server from what I remember, works somewhat like Plesk servers.

**Comment by sam11fr** [comment]
Hello Felli. 
Yes I know it. But since I can not pass parameter, this solution is not the right one.
Ideally, I would need a script that does the job directly and without parameters. I tried with a system call (via exec) but with no success.
Cordially

**Comment by Felli** [comment]
At the moment all I can refer you to is the [Cron Job Setup](https://community.humhub.com/s/installation-and-setup/wiki/page/view?title=Cron+Job+Setup) wiki on the community site, I'll continue looking into more ways of using the Cron Jobs for different server types, and if I can find some scripts that work or can be modified I'll release them to the public through that wiki post. :+1:

**Comment by sam11fr** [comment]
Oh yes, thank you very much for your work ahead. I have already made the rounds of the Wiki pages and other pages too. No solution proposed works. At OVH, the site is mounted on a partition and the Apache server is not the same as the CRON. The whole problem is there in addition to the prohibition of passing parameters. I am desperate and rely heavily on a solution without parameters.
Thank you.
Best regards,
Sam

**Comment by acs-ferreira** [comment]
Create a `php` file and `exec` them inside it:

```
<?php
exec ('php /public/protected/yii cron/hourly');
exec ('php /public/protected/yii cron/daily');
```

than call your `php` file trough OVH.

**Comment by sam11fr** [comment]
Hello, here is the script that I created but that does not work:
#!/usr/local/php5.6/bin/php
<?php
$PDIR=realpath(dirname(__FILE__));
echo "YII CRON/HOURLY\n";
exec("$PDIR/yii cron/hourly");
?>

**Comment by Felli** [comment]
Should be something like `#!/usr/local/php5.6/bin/cron.php`

**Comment by sam11fr** [comment]
No:
ls -l /usr/local/php5.6/bin
total 28424
-rwxr-xr-x 1 root root      852 janv. 27  2017 pear
-rwxr-xr-x 1 root root      873 janv. 27  2017 peardev
-rwxr-xr-x 1 root root      789 janv. 27  2017 pecl
lrwxrwxrwx 1 root root        9 janv. 27  2017 phar -> phar.phar
-rwxr-xr-x 1 root root    14836 janv. 27  2017 phar.phar
-rwxr-xr-x 1 root root 14544684 janv. 27  2017 php
-rwxr-xr-x 1 root root 14515828 janv. 27  2017 php-cgi
-rwxr-xr-x 1 root root     4115 janv. 27  2017 php-config
-rwxr-xr-x 1 root root     4543 janv. 27  2017 phpize

**Comment by sam11fr** [comment]
See on errors logs where cron job run:
request failed: error reading the headers

**Comment by sam11fr** [comment]
I dream of a module that allows me to execute the actions of the program yii from the site administration interface. Is it possible to develop this module?
There are many benefits:
resolves the CRON problems of OVH servers.
settles cases where there is no cron (free) or access SSH (free)
thank you in advance

**Comment by acs-ferreira** [comment]
Some options here https://github.com/humhub/humhub/issues/98

**Comment by Oncle-BOB** [comment]
Hello, i have ovh hosting (shared) this works, here is the procedure based on php 5.6. Create two files cronh.php and crond.php in the root site.

For cronh.php
`<?php
$humhubh = '/usr/local/php5.6/bin/php '.__DIR__.'/protected/yii cron/hourly ';
exec($humhubh);
?>`

And for crond.php
`<?php
$humhubd = '/usr/local/php5.6/bin/php '.__DIR__.'/protected/yii cron/daily ';
exec($humhubd);
?>`

After in the ovh panel click on hosting -> your domain and "More +" -> "Scheduled tasks - Cron" -> "Add planning"
Add path www/cronh.php and following the form, same applies to www/crond.php

Finally you can check the execution in your site admin -> info -> cronjobs

**Comment by sam11fr** [comment]
Yesss !
Sucess Full ! It's work.

Thank you very much !
Bests regards,
Sam

**Comment by Oncle-BOB** [comment]
Good ! tell me... you do not have this [problem](https://github.com/humhub/humhub/issues/2229) with hosting ovh ?

**Comment by Felli** [comment]
@Oncle-BOB could you please provide your solution for this issue and update this [here](https://github.com/buddh4/humhub-docs/blob/master/admin/cron-jobs.md#ovh)?

**Comment by sam11fr** [comment]
Well if, rightly

**Comment by Oncle-BOB** [comment]
Ok sam11fr i invite you to follow this problem.

@Felli ok i do that.
