### ISSUE TITLE
Meeting produces error

### ISSUE THREAD

**Issue by dhoffmann1979** [humhub/humhub#2719]
I get the following error when entering a meeting with a topic without duration.

`TypeError: Argument 2 passed to humhub\modules\meeting\models\Meeting::populateTime() must be an instance of DateTime, null given, called in /var/www/html/protected/modules/meeting/models/Meeting.php on line 303 and defined in /var/www/html/protected/modules/meeting/models/Meeting.php:333 Stack trace: #0 `

**Comment by buddh4** [comment]
Thanks for the note, there is a new version available, which should fix the issue.
