### ISSUE TITLE
Bug: Commenting Issues

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2722]
# Issue 1
So it would seem that you're able to comment on a post then remove text and save and it'll be a blank comment, this shouldn't be possible (Tested on Community site)

### Before
![screenshot_1](https://user-images.githubusercontent.com/2011633/29433343-a666b8e8-8353-11e7-9e5f-36c64c4b9e9b.png)

### After
![screenshot_2](https://user-images.githubusercontent.com/2011633/29433365-baf7bba4-8353-11e7-94c2-917a4f4e54e5.png)

# Issue 2
You're able to submit a comment and it's shown as `comments (2)` where there should be an error that should display, although there is no actual comment made (Again tested on Community site.)

![screenshot_3](https://user-images.githubusercontent.com/2011633/29433463-0ba2c26a-8354-11e7-8299-023a4a5b82e4.png)

**Comment by acs-ferreira** [comment]
Confirm both, latest `master`

**Comment by githubjeka** [comment]
And when comment was deleted then the info-label of "Comment (2)" doesn't update to "Comment (1)"
