### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by PatmanAA** [humhub/humhub#2725]
Hi when I enter 2 letters in the search I get an Error:
Trying to get property of non-object

1. in C:\inetpub\wwwroot\home\protected\humhub\modules\stream\actions\Stream.php at line 309

  if(is_bool($options)) {
            $partial = $options;
            $options = [];
        }
 
        if(isset($options['jsWidget'])) {
            $jsWidget = $options['jsWidget'];
            unset($options['jsWidget']);
        } else {
            $jsWidget = $record->getWallEntryWidget()->jsWidget;
        }
 
        if ($partial) {
            return Yii::$app->controller->renderPartial('@humhub/modules/content/views/layouts/wallEntry', [
                'content' => $record->getWallOut($options),
                'jsWidget' => $jsWidget,
                'entry' => $record->content
            ]);
        } else {

**Comment by buddh4** [comment]
Is probably fixed by https://github.com/humhub/humhub/pull/2676

**Comment by PatmanAA** [comment]
Awsome thanks!
