### ISSUE TITLE
Not receiving any emails.

### ISSUE THREAD

**Issue by xSynthx** [humhub/humhub#2726]
Hello, I just recently installed HumHub, and I went to make a test user, and upon registration, I did not receive a registration email of any sort. I signed up using a gmail account, I have not tested any other email providers so far. I am using the PHP mail option. I have checked the spam folder, as well as all other folders.

**Comment by xSynthx** [comment]
I just noticed that it is still in debug mode, could this be the issue?

**Comment by Felli** [comment]
You also have to follow [Email Setup](http://docs.humhub.org/admin-installation-configuration.html#e-mails) & [Cron Job](http://docs.humhub.org/admin-installation-configuration.html#cronjobs), for the Cron Job setup please read this [Wiki](https://community.humhub.com/s/installation-and-setup/wiki/page/view?title=Cron+Job+Setup), if your server type isn't listed please provide a server type and I'll do my best to update the wiki.

**Comment by xSynthx** [comment]
@Felli Yeah, my server isnt there, I am running Debian 8 jessie. If you could, maybe someone else might need it, add Ubuntu as well.

**Comment by xSynthx** [comment]
Do I have to put both the hourly, and daily?

**Comment by xSynthx** [comment]
Also @Felli could the email problem be caused by humhub still being in debug mode?

**Comment by Felli** [comment]
I would take it out of debug mode, as for the other two, I'll work on getting those both in the wiki post. :smile:

**Comment by xSynthx** [comment]
Okay @Felli Thanks! :)

**Comment by Felli** [comment]
I've updated the wiki, although I've not gotten around to any examples as of yet, so please do check that out. :+1:

**Comment by xSynthx** [comment]
@Felli I have taken my site off of debug mode, and I tried signing up with another user, and nothing happened, this time I tried having it send to the provider: protonmail.
In the cronjob settings, which I set up by the way, it says that neither the hourly, nor daily have been run, and im pretty sure that the cronjob has been set for at least an hour.

**Comment by Felli** [comment]
Are you using PHP or SMTP?

**Comment by xSynthx** [comment]
PHP, as stated in original problem message 😉

**Comment by xSynthx** [comment]
It should work, as I have previously used mybb on this same server, and it worked just fine.

**Comment by xSynthx** [comment]
I am leaving soon, so I wont be able to answer any questions until tomorrow.

**Comment by Felli** [comment]
Hmm... Very strange, could you look in `ACP --> Information --> Logging` for any error stacks?

**Comment by xSynthx** [comment]
I am not 100% sure what happened, but I tried setting up SMTP through google, and it didnt work, then I was looking through that logging page, and I was like, well, let me just flush the entries, and try to troubleshoot this PHP mail thing, and all of a sudden, when I switched back to PHP mail, *after I flushed entries on the logging page* it now sends the emails.
