### ISSUE TITLE
issue mentioning two-part / hyphenated names

### ISSUE THREAD

**Issue by EtienneDemers** [humhub/humhub#2730]
Hi,

I use humhub ver 1.1.2 and when i try to mention a user with a two part name, i can't find the user.

But i can find him if i start the mentionning with the second part of the name. For instance, if i try to mention Jean-Pierre Smith, typing @Jean-pierre will show nothing; but typing @Pierre will find the correct user. It's the same behaviour with two-part  last names. 

I did a quick search trough existing issues and saw nothing related to the subject. Is is still an existing issue on new versions? If not, at what point was the problem solved? 

Thanks!

**Comment by EtienneDemers** [comment]
![mentioning_1](https://user-images.githubusercontent.com/30266107/29528099-cadcd00a-8668-11e7-843a-6c5d9ad1407c.png)
![mentioning_2](https://user-images.githubusercontent.com/30266107/29528098-cada5f8c-8668-11e7-9d8b-a9be0f89181f.png)
![mentioning_3](https://user-images.githubusercontent.com/30266107/29528097-cad9f83a-8668-11e7-913c-72060f55d9f6.png)


Some screenshots from the community humhub...

**Comment by Felli** [comment]
I think that if you start a @mention with the first name and then don't find your target, adding the last name will always find it. I believe this isn't exactly a bug, just somewhat of a flaw within mentioning.

## Examples

#### Name
![screenshot_1](https://user-images.githubusercontent.com/2011633/29532330-717cd70a-8661-11e7-956f-1dd66d68eebb.png)
#### Exact Name
![screenshot_2](https://user-images.githubusercontent.com/2011633/29532329-717ca654-8661-11e7-8c0c-ce138bc1b2d6.png)
#### Last name
![screenshot_3](https://user-images.githubusercontent.com/2011633/29532425-ec47762a-8661-11e7-9288-2989a30e4dae.png)

**Comment by buddh4** [comment]
perhaps we just have to align the regex a bit

**Comment by EtienneDemers** [comment]
I'll give it a try when i have time / when i find the regex.

If i find a fix, it will be for version 1.1.2 but i'll let you know about it and i'm sure it won't need too much work to adapt to the new version.

On the other hand, if you could pinpoint the file and function/lines/bloc concerned, i'd be more than happy. I still spend way too much time to find the right code in the source before doing actual fixes.

Thanks for the quick feedback!

**Comment by buddh4** [comment]
Hmm I could fix it by adding `-` to the [first array](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/search/engine/ZendLuceneSearch.php#L112), will do some further testing tomorrow.

**Comment by Felli** [comment]
@buddh4  wouldn't it also be a better idea to use
`$keyword = str_replace(array('*', '?', '_', '$'), ' ', mb_strtolower($keyword, 'utf8mb4'));` instead?

**Comment by EtienneDemers** [comment]
After my first tests, adding '-' to the array seems to work well on version 1.1.2 (yay!)

I haven't tried changing mb_strtolower($keyword, '**utf8mb4**') though, i'll wait buddh4's opinions on the subject.

**Comment by buddh4** [comment]
think utf8mb4 is mysql specific

**Comment by Felli** [comment]
Using `$keyword = str_replace(array('-', '*', '?', '_', '$'), ' ', mb_strtolower($keyword, 'utf-8'));` showed no finds when testing in `v1.2.2` for me, but switching over to `$keyword = str_replace(array('-', '*', '?', '_', '$'), ' ', mb_strtolower($keyword, 'utf8mb4'));` picked up searches, maybe make it optional?

**Comment by buddh4** [comment]
As I said utf8mb4 is mysql specific php supports the following encodings: http://php.net/manual/en/mbstring.supported-encodings.php

**Comment by Felli** [comment]
Hmm... Then I'll be doing some test to see why utf-8 isn't working on my server...
