### ISSUE TITLE
Enhancement proposition: WYSIWYG text editor

### ISSUE THREAD

**Issue by negoguy** [humhub/humhub#2731]
Hi,

This is just a proposition to have a WYSWIG kind of editor to create/edit posts with basic alignement, bold/italic, indent and title support.

The rich text editor is very well implemented in the platform but adding these feature would make it perfect.

Thanks!

**Comment by buddh4** [comment]
This is planned for v.1.3, thanks for the feedback.

**Comment by acs-ferreira** [comment]
@buddh4 what's the editor choice for v1.3?
_And...what's the ETA? :-)_

**Comment by githubjeka** [comment]
gain popularity
https://github.com/nhnent/tui.editor

**Comment by buddh4** [comment]
We'll use a [Prosemirror](https://prosemirror.net/) based editor with some extensions as default richtext editor. We'll try to make the api flexible so its possible to replace the richtext implementation if required.
