### ISSUE TITLE
Round images/ images with transparency losing transparency.

### ISSUE THREAD

**Issue by xSynthx** [humhub/humhub#2733]
When I upload an image as my avatar that has transparency in it, it loses its transparency, and it turns the transparent parts to red or black, in this case, red. Any way to fix this?
*My avatar is round, but im not asking to have round avatars for everyone.*
[![https://gyazo.com/e2e5e5322dc0653d2b0a9242a5ff4302](https://i.gyazo.com/e2e5e5322dc0653d2b0a9242a5ff4302.png)](https://gyazo.com/e2e5e5322dc0653d2b0a9242a5ff4302)
This is my original image:

[![https://sinister.ly/uploads/avatars/avatar_76165.png?dateline=1503421415](https://sinister.ly/uploads/avatars/avatar_76165.png?dateline=1503421415)](https://sinister.ly/uploads/avatars/avatar_76165.png?dateline=1503421415)

**Comment by buddh4** [comment]
[This](https://github.com/humhub/humhub/pull/2678/files) pr should solve your issue (only the image part):

- protected/humhub/libs/ProfileImage.php
-  protected/humhub/modules/file/libs/ImageConverter.php
- protected/humhub/modules/space/modules/manage/views/image/crop.php
- protected/humhub/modules/space/modules/manage/views/image/cropBanner.php
-  protected/humhub/modules/user/views/image/crop.php

We'll have to test this first, so it's possible this won't be available before v1.3, if you like you could test those changes for yourself if you need the feature earlier.

**Comment by luke-** [comment]
Related to #3402
