### ISSUE TITLE
Markdown Image Resizer for Comments

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2734]
Just wanted to test how larger images would affect the Markdown editor and find that images using Markdown don't resize well with larger images, but do with smaller ones.

### Example
![screenshot_2](https://user-images.githubusercontent.com/2011633/29605274-1e0da678-879f-11e7-8ef3-0284b29c8e08.png)

> [Possible fix](https://stackoverflow.com/questions/14675913/how-to-change-image-size-markdown)

**Comment by acs-ferreira** [comment]
What about:
```
img {
    max-width: 100%;
}
```
I've implemented this on my custom theme.

**Comment by Felli** [comment]
That should work for normal images, but within comments I'm not sure it'll work with the Markdown editor.

**Comment by acs-ferreira** [comment]
I've tested it, it's full CSS.

**Comment by acs-ferreira** [comment]
Another little issue, if Markdown isn't well formatted, it results in a blank comment.
Try to post this `[](http://news.images.itv.com/image/file/842473/img.jpg)` (note the missing `!`) the comment will be blank.

**Comment by Felli** [comment]
Closing seems to have been fixed in the Community site.
