### ISSUE TITLE
Clean url double links

### ISSUE THREAD

**Issue by matroidde** [humhub/humhub#2737]
If i activate clean url for my community and go to mail or directory the link in browser is like this domain.de/directory/directory/groups. I see on community.humhub.org it's the same. But i wan't it to only show /directory/groups. Is it possible?

Sorry for bad english,
Thank You!

**Comment by Felli** [comment]
I'm not sure it's possible to remove the extra `directory` within the url because or how the views are setup.

**Comment by acs-ferreira** [comment]
It's possible by [Parameterizing Routes](http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#parameterizing-routes)

Example [here](http://fellowtuts.com/yii/hide-or-remove-controller-name-from-url-in-yii-2-0/)

**Comment by matroidde** [comment]
Thank You! 
But first I have to understand this 😆 

I have another question. Is it possible to make the directory and search invisible and cut the users. 
I wan't that users can only see other users if there in same space.
