### ISSUE TITLE
Humhub Paypal modul donation

### ISSUE THREAD

**Issue by ychoucha** [humhub/humhub#2738]
Hello, 
 i m looking for a module to use the paypal donation on HUMHUB 

like do wordpresse 👍 
https://fr.wordpress.org/plugins/subscriptions-memberships-for-paypal/

do u know if i can found it, or i need to make it on my own ?

thanks

**Comment by Felli** [comment]
Why not just create a snippet? Should solve this issue.

**Comment by acs-ferreira** [comment]
You should ask this at https://community.humhub.com/s/module-development/

**Comment by Felli** [comment]
I've created a basic [Patreon button](https://github.com/GreenMeteor/humhub-patreon-module) module, for the time being, it's planned to have a goals loader.
