### ISSUE TITLE
'like' disappears automatically on profile posts even after liking it

### ISSUE THREAD

**Issue by dosones** [humhub/humhub#2743]
Liking a post for SPACE post is working perfectly.

BUT for Personal Profile posts like disappears automatically even after liking it. **like** for personal profile posts are only temporary.

I received notifications and it shows like(2) in my posts but after reloading the page all the likes disappear from my page and even from the page of the person who liked my page.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2 (latest)
| PHP version      |  7.1
| Operating system | Linux

**Comment by Felli** [comment]
Could you provide more information? Please read what's needed when [reporting an issue](https://github.com/humhub/humhub/blob/master/CONTRIBUTING.md#report-an-issue).

**Comment by dosones** [comment]
Even if i **like** someone's __(eg. Tommy's)__ personal post (*posts made in spaces are excluded*) by visiting their profile, my **like** disappears after I reload the page. And I have to re-like again but that doesn't work either.

And that **like** disappears even from Tommy's account too.

**Comment by Felli** [comment]
Are you a super admin? Could you give any error stacks or browser console errors?

**Comment by acs-ferreira** [comment]
This could be a cache issue.

Are your SQL queries cached? I've face a similar issue using [MaxScale](https://mariadb.com/products/technology/maxscale) with an aggressive configuration regarding query cache.
