### ISSUE TITLE
Call to a member function getCommentedRecord() on null

### ISSUE THREAD

**Issue by bkmeneguello** [humhub/humhub#2752]
### What steps will reproduce the problem?

I did not reproduced, but I suppose the problem happens when there is a notification of a comment and this comment is removed.

### Additional info

1. in /app/humhub/protected/humhub/modules/comment/notifications/NewComment.php at line 178
```
171    /**
172     * The commented record e.g. a Post
173     *
174     * @return \humhub\modules\content\components\ContentActiveRecord
175     */
176    public function getCommentedRecord()
177    {
178        return $this->source->getCommentedRecord();
179    }
```
2. yii\base\ErrorHandler::handleFatalError()

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.0 (docker)

**Comment by buddh4** [comment]
Try running the integrity check within the protected directory of your installation:

```
php yii integrity/run
```

**Comment by bkmeneguello** [comment]
I had resolved by deleting the orphaned notifications directly at database
and worked. I'll take note of this command for the future.
I think the point is that this situation should not happen, maybe, check if
the comment is null.

Em 13 de set de 2017 18:49, "buddh4" <notifications@github.com> escreveu:

**Comment by leuprechtroman** [comment]
We have the same issue as @bkmeneguello, on Humhub 1.2.1 (docker).

We are trying to figure out how to reproduce the exception and will comment any findings
