### ISSUE TITLE
humhub 1.1.2 issue with LDAP user creation when fistname longer than 20 chars

### ISSUE THREAD

**Issue by EtienneDemers** [humhub/humhub#2753]
### What steps will reproduce the problem?
Having LDAP users with firstname longer than 20 chars with humhub 1.1.2

### What is the expected result?
Humhub creates the user normally

### What do you get instead?
the ZendLDAPClient makes this warning: Could not automatically create LDAP user  - check required attributes! when the user fails the validation functions from Register.php

### Additional info
this issue affects less than 10 users out of 5000+ and they're the only ones with first names longer than 20 characters. They also all have 3-4 part names.

warning log stack:
2017-09-12 10:30:22 [-][7727][-][warning][application] Could not automatically create LDAP user  - check required attributes!
in /var/www/humhub/protected/humhub/modules/user/authclient/ZendLdapClient.php:321
    in /var/www/humhub/protected/humhub/modules/user/Events.php:136
    in /var/www/humhub/protected/humhub/commands/CronController.php:41

### Conclusion
I've browsed trough the community but didn't found anyone talking about the issue. 

Is it an existing behaviour with current versions?
Is it just that humhub dosen't allow names longer than 20 chars at all?
Where can i change the first name length limit? Is the a setting for that?

Any feedback from the community is welcome, i don't expect very precise solutions but quick insight would be great!

Thanks!

| Q                | A
| ---------------- | ---
| HumHub version   | 1.1.2
| Operating system | ubuntu

**Comment by Felli** [comment]
I think this was fixed with v1.2?

**Comment by EtienneDemers** [comment]
i'll look the changelogs of 1.2 and try to find what i'm looking for!

I've logged the profile object i'm trying to validate and found this validator for the fistname field:

`[2] => yii\validators\StringValidator Object
                        (
                            [length] => 
                            [max] => 20
                            [min] => 
                            [message] => {attribute} must be a string.
                            [tooShort] => 
                            [tooLong] => {attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.
                            [notEqual] => 
                            [encoding] => UTF-8
                            [attributes] => Array
                                (
                                    [0] => firstname
                                )

                            [on] => Array
                                (
                                )

                            [except] => Array
                                (
                                )

                            [skipOnError] => 1
                            [skipOnEmpty] => 1
                            [enableClientValidation] => 1
                            [isEmpty] => 
                            [when] => 
                            [whenClient] => 
                            [_events:yii\base\Component:private] => Array
                                (
                                )

                            [_behaviors:yii\base\Component:private] => 
                        )`

Now i just have to find from where the validator is created with this max length parameter and where the value comes from but validators are very new for me!

Thanks for the feedback!

**Comment by EtienneDemers** [comment]
These settings used to be in the installer's config controller (see [this ](https://github.com/humhub/humhub/commit/5dccadaf77f61ccb7ceb49992780ea57824bf74c)commit) but they're not in there anymore. I finally decided to browse the DB to see if it could contain the settings and there it is! In the profile_field table in the field_type_config column. I'll update the values first thing tomorrow and i'll close the issue when everything's working

**Comment by EtienneDemers** [comment]
I've successfully changes the values in the DB and everything is working now.
