### ISSUE TITLE
After form save, page content was duplicated

### ISSUE THREAD

**Issue by fatihemre** [humhub/humhub#2754]
### What steps will reproduce the problem?

Any form action (for example User Settings form) if you save your settings, page content was duplicated. Please watch the screen capture video: https://fatihemre.tinytake.com/sf/MTk1MTkwM182MTk0OTky

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      | 5.6.31
| Operating system | Windows Server 2012 R2
| Web Server | IIS 8.5

### Screenshot
![Screenshot for this issue](https://i.imgur.com/wnHHSu4.png)

**Comment by Felli** [comment]
Are you using a custom theme by any chance? If so please note that some custom themes that are found on GitHub aren't 100% up-to-date, even some of my own themes are in need of updating.

**Comment by fatihemre** [comment]
@Felli not, only color palette is changed from default theme. Actually this is default theme. I update the less file for color palette.

**Comment by Felli** [comment]
Could you check `ACP --> Information --> Logging` as well as your browser console for errors?

**Comment by fatihemre** [comment]
There is no error on ACP and Browser Console.

Note: If i refresh duplicated page with F5 or CTRL + R, the problem continues. But I refresh the page with CTRL + SHIFT + R, solved. is this a javascript page load problem?

![ACP](https://i.imgur.com/zKsk8S5.png)

**Comment by Felli** [comment]
Might be another issue with pjax.

**Comment by fatihemre** [comment]
Okey, this is an automatic update problem 1.2.2 from 1.2.1 via Humhub Updater. I uploaded assets manually, the problem was solved
