### ISSUE TITLE
Class 'humhub\modules\post\models\Post' not found

### ISSUE THREAD

**Issue by sisqi** [humhub/humhub#2757]
everytime i try the search button i get this error  :

Class 'humhub\modules\post\models\Post' not found

 in /home/admin/web/localhost/public_html/protected/humhub/modules/search/libs/SearchResultSet.php

any ideas how to fix it ?

thank you

**Comment by Felli** [comment]
Hmm... You might need to rebuild the search index.

**Comment by sisqi** [comment]
How please ?

**Comment by Felli** [comment]
Here's the command; `php yii search/rebuild`

**Comment by sisqi** [comment]
Sorry but i have never worked with yii framework and my knowledge is very basic i've already found the command but i dont know where to put it, thanks for your help my dear 

ps : im on a shared hosting

**Comment by Felli** [comment]
You must have access to SSH, normally Shared Hosting doesn't provide this or uses software such as PuTTY to access.

**Comment by sisqi** [comment]
it gives me this error : Could not open input file: yii

**Comment by sisqi** [comment]
do i really need to install the composer and the framework in order to reproduce one thing ?

**Comment by buddh4** [comment]
You have to execute this within the `protected` directory of your installation. You don't need composer etc. But seems to be a strange issue, does the installation work beside the search?

**Comment by sisqi** [comment]
im trying to execute it on public_html directory, yes everything, the only issue is the search button function, even the search in groups is working :(

**Comment by buddh4** [comment]
Change the directory to [the protected](https://github.com/humhub/humhub/tree/3bcc3e67addbe61852c625891f593dc83b3655e3/protected) directory and execute the command, also check `Administration -> Information -> Logging` for any other errors, perhaps there is another root problem like permissions or missing requirments.

**Comment by sisqi** [comment]
`Error: Class 'humhub\modules\post\models\Post' not found in /home/admin/web/humhub.ml/public_html/protected/humhub/modules/search/libs/SearchResultSet.php:55 Stack trace: #0 /home/admin/web/humhub.ml/public_html/protected/humhub/modules/search/controllers/SearchController.php(86): humhub\modules\search\libs\SearchResultSet->getResultInstances() #1 [internal function]: humhub\modules\search\controllers\SearchController->actionIndex() #2 /home/admin/web/humhub.ml/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #3 /home/admin/web/humhub.ml/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #4 /home/admin/web/humhub.ml/public_html/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('index', Array) #5 /home/admin/web/humhub.ml/public_html/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('search/search/i...', Array) #6 /home/admin/web/humhub.ml/public_html/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #7 /home/admin/web/humhub.ml/public_html/index.php(25): yii\base\Application->run() #8 {main}`
