### ISSUE TITLE
Change in module

### ISSUE THREAD

**Issue by ogimihail** [humhub/humhub#2761]
Could you please help me with Humhub's module Tasks. I'd like to add a filter by executor and date in it. I want to make it as a separate module, which can be switched in module manager. Is it possible to enable automatically my module, when Tasks is open, and let it change the page structure, like to filter the client's tasks. Or there is no acces to Tasks for my module and I should modify Tasks itself?

Q | A
-- | --
HumHub version | 1.2.2
PHP version | 5.6
Operating system | Linux (Ubuntu 14)

**Comment by buddh4** [comment]
Please, ask this in the [Task Module Repository](https://github.com/humhub/humhub-modules-tasks)
I'd rather suggest adding this feature to the module itself. The module is currently not very flexible and will hopefully be reworked soon.
