### ISSUE TITLE
community.humhub.com error when click on directory

### ISSUE THREAD

**Issue by Buliwyfa** [humhub/humhub#2763]
### What steps will reproduce the problem?
Login as user to
https://community.humhub.com

Click on directory

### What is the expected result?
The directory with users, groups, spaces, etc

### What do you get instead?
No directory access and this screen:

![2017-09-20_214238](https://user-images.githubusercontent.com/13509685/30664088-d29df1b0-9e4c-11e7-81fd-8cb54a0db584.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

**Comment by Felli** [comment]
You're right, I'm sure that this is being worked on for some reason or another.

**Comment by buddh4** [comment]
Should be fixed, was a missing migration, thanks for noticing.

**Comment by buddh4** [comment]
Seems still to be an asset problem.

**Comment by Felli** [comment]
@buddh4 I believe this is now fixed? I'm able to view the member group directory now.
