### ISSUE TITLE
Missing transaltion 'Hook' on Friendship core module

### ISSUE THREAD

**Issue by Buliwyfa** [humhub/humhub#2764]
### What steps will reproduce the problem?
Log in to any HumHub installation 

Enable friendship system.

Login with a user with language that is not English. My case Spanish.

Get a friend

Check list

### What is the expected result?
All to be translated to Spanish

### What do you get instead?

![imagen](https://user-images.githubusercontent.com/13509685/30775819-a1989380-a09b-11e7-915e-8201bf1e360c.png)

### Additional info
To fix it

...\protected\humhub\modules\friendship\views\manage\list.php

22 - 'header' => 'Actions',
     + 'header' => Yii::t('FriendshipModule.base', 'Actions'),

32 - return Html::a('Unfriend', ['/friendship/request/delete', 'userId' => $model->id], ['class' => 'btn btn-danger btn-sm', 'data-method' => 'POST']);
     + return Html::a(Yii::t('FriendshipModule.base', 'Unfriend'), ['/friendship/request/delete', 'userId' => $model->id], ['class' => 'btn btn-danger btn-sm', 'data-method' => 'POST']);

And to all 

....\public\protected\humhub\modules\friendship\messages\\**xx**\base.php
add
16 +   'Actions' => ''

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      | 7.0
| Operating system | Windows 2016

**Comment by Buliwyfa** [comment]
I never try before contributing code...
Will try it with these fixes

**Comment by victorpdiez** [comment]
Thanks if fix it for me

**Comment by buddh4** [comment]
Sorry overlooked your PR, thanks anyways ;)
