### ISSUE TITLE
File upload on iphone using Chrome

### ISSUE THREAD

**Issue by Buliwyfa** [humhub/humhub#2768]
### What steps will reproduce the problem?
Log on to any humhub
Try to write a post and add a 2mb video

### What is the expected result?
The file is upload after a progress bar end

### What do you get instead?
The progress bar appears but nothing happens

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      |  no idea on humhub.com
| Operating system |  no idea on humhub.com

**Comment by Felli** [comment]
HumHub using the minimum PHP version, which is `5.6`, as for OS, I'm not sure.

**Comment by Buliwyfa** [comment]
Ok let update data

domain is free humhun hosting https://1010.humhub.com/



PHP - Version - 5.6.30-0+deb8u1
![imagen](https://user-images.githubusercontent.com/13509685/30835178-380fd33e-a257-11e7-9e33-ab1f069e0838.png)


Operating system -  11
![imagen](https://user-images.githubusercontent.com/13509685/30835607-413b8c80-a259-11e7-9837-01d5c1725328.png)

**Comment by Felli** [comment]
From what I remember a lot of issues have happened with iOS 11 coming out, could you check your logging or browser console?
