### ISSUE TITLE
Error on open space

### ISSUE THREAD

**Issue by Frank1751** [humhub/humhub#2769]
{
    "url": "/intranet/home/index.php?r=space%2Fspace%2Fstream&mode=normal&sguid=32947002-8fbb-419c-a529-a1149ac2a8cb",
    "status": 500,
    "response": {
        "name": "Exception",
        "message": "Could not get contents underlying object! - contentid: 137",
        "code": 0,
        "type": "yii\\base\\Exception",
        "file": "C:\\wamp\\www\\intranet\\home\\protected\\humhub\\modules\\stream\\actions\\Stream.php",
        "line": 308,
        "stack-trace": [
            "#0 C:\\wamp\\www\\intranet\\home\\protected\\humhub\\modules\\stream\\actions\\Stream.php(232): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
            "#1 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
            "#2 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Action.php(94): call_user_func_array(Array, Array)",
            "#3 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Controller.php(156): yii\\base\\Action->runWithParams(Array)",
            "#4 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
            "#5 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\web\\Application.php(102): yii\\base\\Module->runAction('space/space/str...', Array)",
            "#6 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
            "#7 C:\\wamp\\www\\intranet\\home\\index.php(25): yii\\base\\Application->run()",
            "#8 {main}"
        ]
    },
    "textStatus": "error",
    "dataType": "json",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"name\":\"Exception\",\"message\":\"Could not get contents underlying object! - contentid: 137\",\"code\":0,\"type\":\"yii\\\\base\\\\Exception\",\"file\":\"C:\\\\wamp\\\\www\\\\intranet\\\\home\\\\protected\\\\humhub\\\\modules\\\\stream\\\\actions\\\\Stream.php\",\"line\":308,\"stack-trace\":[\"#0 C:\\\\wamp\\\\www\\\\intranet\\\\home\\\\protected\\\\humhub\\\\modules\\\\stream\\\\actions\\\\Stream.php(232): humhub\\\\modules\\\\stream\\\\actions\\\\Stream::getContentResultEntry(Object(humhub\\\\modules\\\\content\\\\models\\\\Content))\",\"#1 [internal function]: humhub\\\\modules\\\\stream\\\\actions\\\\Stream->run()\",\"#2 C:\\\\wamp\\\\www\\\\intranet\\\\home\\\\protected\\\\vendor\\\\yiisoft\\\\yii2\\\\base\\\\Action.php(94): call_user_func_array(Array, Array)\",\"#3 C:\\\\wamp\\\\www\\\\intranet\\\\home\\\\protected\\\\vendor\\\\yiisoft\\\\yii2\\\\base\\\\Controller.php(156): yii\\\\base\\\\Action->runWithParams(Array)\",\"#4 C:\\\\wamp\\\\www\\\\intranet\\\\home\\\\protected\\\\vendor\\\\yiisoft\\\\yii2\\\\base\\\\Module.php(523): yii\\\\base\\\\Controller->runAction('stream', Array)\",\"#5 C:\\\\wamp\\\\www\\\\intranet\\\\home\\\\protected\\\\vendor\\\\yiisoft\\\\yii2\\\\web\\\\Application.php(102): yii\\\\base\\\\Module->runAction('space/space/str...', Array)\",\"#6 C:\\\\wamp\\\\www\\\\intranet\\\\home\\\\protected\\\\vendor\\\\yiisoft\\\\yii2\\\\base\\\\Application.php(380): yii\\\\web\\\\Application->handleRequest(Object(humhub\\\\components\\\\Request))\",\"#7 C:\\\\wamp\\\\www\\\\intranet\\\\home\\\\index.php(25): yii\\\\base\\\\Application->run()\",\"#8 {main}\"]}",
        "responseJSON": {
            "name": "Exception",
            "message": "Could not get contents underlying object! - contentid: 137",
            "code": 0,
            "type": "yii\\base\\Exception",
            "file": "C:\\wamp\\www\\intranet\\home\\protected\\humhub\\modules\\stream\\actions\\Stream.php",
            "line": 308,
            "stack-trace": [
                "#0 C:\\wamp\\www\\intranet\\home\\protected\\humhub\\modules\\stream\\actions\\Stream.php(232): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
                "#1 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
                "#2 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Action.php(94): call_user_func_array(Array, Array)",
                "#3 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Controller.php(156): yii\\base\\Action->runWithParams(Array)",
                "#4 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
                "#5 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\web\\Application.php(102): yii\\base\\Module->runAction('space/space/str...', Array)",
                "#6 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
                "#7 C:\\wamp\\www\\intranet\\home\\index.php(25): yii\\base\\Application->run()",
                "#8 {main}"
            ]
        },
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "name": "Exception",
    "message": "Could not get contents underlying object! - contentid: 137",
    "code": 0,
    "type": "yii\\base\\Exception",
    "file": "C:\\wamp\\www\\intranet\\home\\protected\\humhub\\modules\\stream\\actions\\Stream.php",
    "line": 308,
    "stack-trace": [
        "#0 C:\\wamp\\www\\intranet\\home\\protected\\humhub\\modules\\stream\\actions\\Stream.php(232): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
        "#1 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
        "#2 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Action.php(94): call_user_func_array(Array, Array)",
        "#3 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Controller.php(156): yii\\base\\Action->runWithParams(Array)",
        "#4 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
        "#5 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\web\\Application.php(102): yii\\base\\Module->runAction('space/space/str...', Array)",
        "#6 C:\\wamp\\www\\intranet\\home\\protected\\vendor\\yiisoft\\yii2\\base\\Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
        "#7 C:\\wamp\\www\\intranet\\home\\index.php(25): yii\\base\\Application->run()",
        "#8 {main}"
    ],
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

### What steps will reproduce the problem?

open space

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.21
| PHP version      |  5.6.25
| Operating system | WampServer Version 3.0.6 32bit

**Comment by buddh4** [comment]
Sorry for the late reply run `php yii integrity/run` within the `protected` directory of your installation.
