### ISSUE TITLE
Bug when searching space

### ISSUE THREAD

**Issue by soju7** [humhub/humhub#2770]
### What steps will reproduce the problem?
Search something in chooser widget. http://prntscr.com/gpv3q0
### What is the expected result?
Search spaces related to the keyword.
### What do you get instead?
Show spaces that are not in the keyword.

### Additional info
1)type "mo" in search box
2)see screenshot .http://prntscr.com/gpv6jy
3)it shows spaces that don't contain search keyword "mo" marked in the red box.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2?
| PHP version      | 7
| Operating system |windows

**Comment by buddh4** [comment]
The space chooser search searches for title,tags and description of spaces.

**Comment by Buliwyfa** [comment]
I experience similar issues and I am trying to document it and find a way to always reproduce the behavior.

When it happens I even get spaces than does not exits... and spaces that have no match on nay place ( title, tags and description)

**Comment by soju7** [comment]
@luke hi,
 I install a fresh humhub and try searching.it works fine until I run the command ./yii search/rebuild .now I can replicate the issue. I suspect it was some Zend search issue. Please take a look.thanks.

**Comment by victorpdiez** [comment]
+1
yes please look into it
thanks

**Comment by buddh4** [comment]
Thanks for the info, never experienced such issues, we'll try to reproduce this.
