### ISSUE TITLE
files module: checkboxes not shown

### ISSUE THREAD

**Issue by pelennart** [humhub/humhub#2771]
### What steps will reproduce the problem?
no idea, there are other spaces were it still works

### What is the expected result?
checkboxes are shown in front of files and folder icons and can be selected and I am able to delete folders

### What do you get instead?
no checkboxes to select files and folders

### Additional info
![bildschirmfoto 2017-09-29 um 11 22 29](https://user-images.githubusercontent.com/14274679/31009919-5e25f2c4-a509-11e7-8d3c-5d45ad0f2b0b.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      | 5.6.30-10+deb.sury.org~xenial+2
| Operating system | Ubuntu 16.04

**Comment by pelennart** [comment]
I imagine people opening attached image might think it's a problem with the scrollbar. Maybe it is, but it is not possible to scroll any further to the left.

**Comment by acs-ferreira** [comment]
This is related to HumHub cFiles module, not HumHub Core.
https://github.com/humhub/humhub-modules-cfiles

**Comment by buddh4** [comment]
The checkboxes are shown if either of the two conditions are met:

- The user has Manage File Permissions (Can be set in Space Permission Settings)
- Zip support is active (Can be managed global  module configuration)

Please open an issue to the cfiles repository if not already done.
