### ISSUE TITLE
CAN NOT UPLOAD AND REPLACE AVATAR

### ISSUE THREAD

**Issue by gibran2000** [humhub/humhub#2772]
### What steps will reproduce the problem?
upload button and change avatar profile does not work in mobile/webview mode
### What do you get instead?
the upload button can work in mobile / webview mode

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      | 5.6.30
| Operating system |

**Comment by Felli** [comment]
Q 1: Are you using an android app? If so these are third-party apps and aren't official apps.

Q 2: Have you checked #2228? As this would be a similar issue it would seem, that is if you're not using a third-party mobile app.
