### ISSUE TITLE
iFrame in space menu

### ISSUE THREAD

**Issue by gituser317** [humhub/humhub#2777]
Hello,

we would like to have an iFrame embedded in an Space, accessible over the space menu.
So if we click on "link" in the menu of a space, then it opens a site in iFrame under the Space.

Is this makeable?

Thank you for your help!

**Comment by buddh4** [comment]
check the [Custom Pages](https://www.humhub.org/de/marketplace/details?id=13) module.

**Comment by Felli** [comment]
@buddh4 I added a small note to the issue_template.md seen here in #2778 about this.

**Comment by buddh4** [comment]
Thanks.
