### ISSUE TITLE
PDOException Error while installing humhub on localhost

### ISSUE THREAD

**Issue by grushler** [humhub/humhub#2779]
### What steps will reproduce the problem?
New installation on local windows laptop.

### What is the expected result?
Installation should be successful.

### What do you get instead?
Database Exception – yii\db\Exception

SQLSTATE[HY000]: General error: 1025 Error on rename of '.\humhub\#sql-2778_4' to '.\humhub\user' (errno: 13 "Permission denied")
The SQL being executed was: ALTER TABLE `user` CHANGE `language` `language` varchar(5) DEFAULT NULL
Error Info: Array
(
    [0] => HY000
    [1] => 1025
    [2] => Error on rename of '.\humhub\#sql-2778_4' to '.\humhub\user' (errno: 13 "Permission denied")
)
↵
Caused by: PDOException
SQLSTATE[HY000]: General error: 1025 Error on rename of '.\humhub\#sql-2778_4' to '.\humhub\user' (errno: 13 "Permission denied")

in C:\xampp\htdocs\mobiphy\protected\vendor\yiisoft\yii2\db\Command.php at line 842

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      | 7.1.9
| Operating system | Windows 10

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administratoin --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
Seems your humhub database user does not have the required permissions.

Check the second line in the [Installation Guide](http://docs.humhub.org/admin-installation.html#database)

**Comment by grushler** [comment]
This worked fine after deleting and recreating DB with privileges given in Humhub installation guide.
