### ISSUE TITLE
Admin Creation in Setup fails when PHP iconv extension is not installed

### ISSUE THREAD

**Issue by leuprechtroman** [humhub/humhub#2785]
Obviously it happens quite some time that the iconv extension is enabled, but not loaded.
There are already issues about that: #2172, #886

The Humhub Installation does not test if the needed iconv extension is actually loaded. This extension may be included by default but must often be loaded by referencing it in the php.ini.
Since ZendSearch relies on that, it'll fail when creating the admin user during the setup.
After this error, the admin is created but misses the specified password.

I'll do a pull request that includes a check for the iconv extension. That should prevent that from happening and will save people time.

### What steps will reproduce the problem?

1) Start HumHub Installation with the iconv extension disabled
2) Continue and on the Admin-Step in the setup, click "create admin".
3) Humhub will crash and the admin will be created but without password. So this user cannot login.

### What is the expected result?

Admin user will be created and then be able to login.
Actually: The setup should already complain about the missing extension earlier.

### What do you get instead?

Admin user is unable to login.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      |  7.1.10
| Operating system | Linux 4.13.6-1-ARCH

There was no error stack printed to the browser console.
The Error is: Call to undefined function ZendSearch\Lucene\Analysis\Analyzer\Common\iconv_strlen()

After activating the iconv extension, everything works fine.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/891c43cb6670fcc1ce3b3b5947bd9008cdf0d9b8 thank you for the PR
