### ISSUE TITLE
Stream could not be initialized!

### ISSUE THREAD

**Issue by ygrosyeux** [humhub/humhub#2790]
### What steps will reproduce the problem?
Go to a space, using the drop-down list of spaces

### What is the expected result?
Viewing the list of latest activities

### What do you get instead?
Error message : Stream could not be initialized!

### Additional info
{
    "url": "/myvariotest/s/accueil/space/space/stream?mode=activity",
    "status": 500,
    "response": {
        "name": "Internal Server Error",
        "message": "Une erreur de serveur interne s'est produite.",
        "code": 0,
        "status": 500
    },
    "textStatus": "error",
    "dataType": "json",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"name\":\"Internal Server Error\",\"message\":\"Une erreur de serveur interne s'est produite.\",\"code\":0,\"status\":500}",
        "responseJSON": {
            "name": "Internal Server Error",
            "message": "Une erreur de serveur interne s'est produite.",
            "code": 0,
            "status": 500
        },
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "name": "Internal Server Error",
    "message": "Une erreur de serveur interne s'est produite.",
    "code": 0,
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

In the log (admin/logging) there is the following exception : 
ERROR  Thu, 19 Oct 2017 09:55:14 +0200  yii\base\InvalidParamException exception 'yii\base\InvalidParamException' with message '**Malformed UTF-8 characters, possibly incorrectly encoded.**' in D:\ProgramData\Apache24Data\htdocs\myvariotest\protected\vendor\yiisoft\yii2\helpers\BaseJson.php:132 Stack trace: #0 D:\ProgramData\Apache24Data\htdocs\myvariotest\protected\vendor\yiisoft\yii2\helpers\BaseJson.php(66): yii\helpers\BaseJson::handleJsonError(5) #1 D:\ProgramData\Apache24Data\htdocs\myvariotest\protected\vendor\yiisoft\yii2\web\JsonResponseFormatter.php(89): yii\helpers\BaseJson::encode(Array, 320) #2 D:\ProgramData\Apache24Data\htdocs\myvariotest\protected\vendor\yiisoft\yii2\web\JsonResponseFormatter.php(73): yii\web\JsonResponseFormatter->formatJson(Object(humhub\components\Response)) #3 D:\ProgramData\Apache24Data\htdocs\myvariotest\protected\vendor\yiisoft\yii2\web\Response.php(1028): yii\web\JsonResponseFormatter->format(Object(humhub\components\Response)) #4 D:\ProgramData\Apache24Data\htdocs\myvariotest\protected\vendor\yiisoft\yii2\web\Response.php(334): yii\web\Response->prepare() #5 D:\ProgramData\Apache24Data\htdocs\myvariotest\protected\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Response->send() #6 D:\ProgramData\Apache24Data\htdocs\myvariotest\index.php(25): yii\base\Application->run() #7 {main}

Problem already exists in 1.2.0, and still exists after upgrade to 1.2.2

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      | 5.6.17
| Operating system | Windows

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
What database are you using? Also please provide the collation you're using, at the moment `utf8mb4_unicode_ci` is the default you should use, or you could use  `utf8_general_ci` which is the fallback.

**Comment by ygrosyeux** [comment]
Hello,

MySQL 5.7.10
Database & Table Collation : utf8_general_ci

Yann

**Comment by buddh4** [comment]
Can you reproduce this in a fresh space, perhaps by using any specific special characters within a post?
Which modules do you have installed within this space?
