### ISSUE TITLE
@mentioned person gets notified even if he can't read the post

### ISSUE THREAD

**Issue by Themroc** [humhub/humhub#2791]
### What steps will reproduce the problem?
As user_a, create an invitation-only, private space, post something with "@user_b" in it. user_b will get a notification but can't read that posting.

### What is the expected result?
user_b shouldn't appear in the selection-popup user_a got after typing @use

### What do you get instead?
user_b now knows user_a talks about him behind his back...

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.0
| PHP version      | 7.0.15
| Operating system | ubuntu server 16.04.4 "xenial"

**Comment by Felli** [comment]
I believe this is to be expected, if its a private space and someone not within this space that is mentioned then they shouldn't be able to view it because they aren't a part of this space, a notification stopper could be implemented for such reasons, but I don't think its 100% needed, I believe no matter what if someone is mentioning you you should know about it. :smiley:

**Comment by Themroc** [comment]
:) Well, i beg to differ. Its never good for you to overhear something thats not meant for you. And in this case, its not even your decision to look into others peoples secrets. Instead, HumHub forces you to notice it - but then gives you some kind of 404-Error-Page instead of the conversation.

**Comment by Felli** [comment]
Hmm.. I wonder if it would be a good idea to send user_b to a popup to request membership to private space in this case, @buddh4 what are your thoughts?

**Comment by Themroc** [comment]
I'd rather keep it simple and not allow user_a to mention someone whos not member of the private space. Just maybe add a "invite ppl. to this space"-button instead of "nothing found". Plus, i think that a private space should be absolutely private. Noone outside it should even know it exists.

**Comment by Felli** [comment]
That I believe would be the more complicated route, although it's one way of many to fix this. :laughing:

**Comment by buddh4** [comment]
So, this will only happen in public posts within a private space. In case the post is private the user does not get a notification.

In my opinion you should not be able to create public posts within private spaces at all. The mentioning should stay as is, so we can link other user outside of the space (without a notification in this case), this could for example be helpful in a admin space etc.

**Comment by Themroc** [comment]
Thanks, that is fixed, no more bogus notification. But: The main purpose of @mention is to send someone a "looky here, you should read this posting"-message. And that purpose is defeated now. user_a thinks that user_b will be notified, but he isn't.

**Comment by Themroc** [comment]
@buddh4 How about something like

```
    public function actionMentioning()
    {
        \Yii::$app->response->format = 'json';

        $results = array();
        $keyword = Yii::$app->request->get('keyword', "");
# added:
        $sguid= Yii::$app->request->get('sguid', "");
        $space= empty($sguid) ? null : Space::findOne(['guid' => $sguid]);
        $check= $space != null; /* should be something like
        $check= $space != null && $space->isPrivate();
        but i dunno how to do that. Without it, even in public spaces you can @mention only members of that space :-/ */
# /added

        $searchResultSet = Yii::$app->search->find($keyword, [
            'model' => array(User::className(), Space::className()),
            'pageSize' => 10
        ]);
        
        foreach ($searchResultSet->getResultInstances() as $container) {
# added:
            if ($check && $container instanceof User) {
                // Make sure only users who have a chance to access a private space can be selected
                $user_b = User::findOne(['guid' => $container->guid]);
                $membership = Membership::findOne(['space_id' => $space->id, 'user_id' => $user_b->id]);
                if ($membership == null || $membership->status != Membership::STATUS_MEMBER)
                    continue;
            }
# /added
            $results[] = array(
                'guid' => $container->guid,
                'type' => ($container instanceof Space) ? "s" : "u",
                'name' => $container->getDisplayName(),
                'image' => ($container instanceof Space) ? Image::widget(['space' => $container, 'width' => 20]) : "<img class='img-rounded' src='" . $container->getProfileImage()->
                'link' => $container->getUrl()
            );
        };

        return $results;
    }
```

would you accept it, if i sent you a PR? After i found out how $space->isPrivate() is done, of course.

**Comment by buddh4** [comment]
We'll discuss this, I for myself think it's nice beeing able to easily mention/link users also in posts the user can't access, and I've used this in some situations. Perhaps we could add an icon with tooltip to users which do not receive notifications in the result list. 

In v1.3 we'll add a new richtext, perhaps we could think about this feature when reworking the richtext.

**Comment by funkycram** [comment]
Some news ? The problem is still there in v1.3. Thanks !
