### ISSUE TITLE
@mention lookup fails

### ISSUE THREAD

**Issue by Themroc** [humhub/humhub#2794]
### What steps will reproduce the problem?
* Install fresh https://github.com/humhub/humhub/commit/8bce26e7dc6f4fa15de50d1d622fe0e60782ed0c
* Add user
login: lmaa
givenname: lutz
surname: m
* As admin, try to mention him. Type into "whats on your mind"-box:
"@lut" 
"@lma"
* As admin, try to look him up:
http://spock/humhub-master/index.php?r=search%2Fsearch%2Fmentioning&keyword=lut
http://spock/humhub-master/index.php?r=search%2Fsearch%2Fmentioning&keyword=lma

### What is the expected result?
User "lutz m" should appear 4 times

### What do you get instead?
Typing "@l..." gave 0 hits in both cases, the json-query gave a [] with keyword=lut but the expected result with keyword=lma

### Additional info
Looks like 2 different bugs... By the way, isn't the 3-character-minimum obsolete? Why not give out the full list when users are too lazy to type anything (or can't remember the name, but would recognize the avatar)? Should i open another issue for that?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 5.6.30
| Operating system | Debian "jessie"

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
Try to [rebuild the search index](http://docs.humhub.org/admin-search.html#index-rebuilding).

**Comment by Themroc** [comment]
Thanx, that helped. Now, json works with both and the RichTextField only with "lut" (but not with "lma", which is ok for me). But shouldn't the search index get updated automatically when a new user is confirmed? Maybe just the lines
`* * * * * <?= Yii::getAlias('@app/yii'); ?> search/rebuild >/dev/null 2>&1`
and
`* * * * * su -c "<?= Yii::getAlias('@app/yii'); ?> search/rebuild " <?= $currentUser; ?> >/dev/null 2>&1`
are missing in protected/humhub/modules/admin/views/information/cronjobs.php ? :D

**Comment by buddh4** [comment]
The search index gets updated automatically, but somehow it breaks from time to time, I also think this is a bit annoying, but can't tell you why it's happening ,/

**Comment by Themroc** [comment]
Yeah, that kind of bugs really suck. I'll try to reproduce it with another fresh install. If it happens again, it should be possible to track it down. How do you debug that stuff? I once tried eclipse with that php-plugin, but it was buggy&slow - no fun...
