### ISSUE TITLE
Implement "Lastname Firstname" format for names

### ISSUE THREAD

**Issue by mocsa** [humhub/humhub#2795]
In Hungarian, people’s names are written in "Lastname Firstname" format. In other words, family name is written first, followed by the given name. Japanese names have the same format.

Please add a new option “Settings -> Appearance -> Display Name (Format) -> Lastname Firstname (e.g. Doe John)”

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      |  5.6.30
| Operating system | Windows

**Comment by luke-** [comment]
In the meantime, you can change the display name format via configuration (protected/config/common.php)

```
<?php

return [
   'modules' = [
       'user' => [
             'displayNameCallback' => function($user) {
                      return $user->profile->lastname.' '.$user->profile->firstname;
             }
       ]
  ]
];


```

**Comment by mocsa** [comment]
There is a small typo in your code. The 4th line should be:
`'modules' => [`
With this correction it works perfectly. Thank you!

**Comment by moln4rvilmos** [comment]
Többnyelvű oldalhoz, ha ott magyarok is (vagy főleg magyarok) vannak:
`<?php
return [
   'modules' => [
       'user' => [
             'displayNameCallback' => function($user) {
                 // Ha magyar nyelv van beállítva, akkor a "Vezetéknév Keresztnév" formátumot használjuk
                 if (Yii::$app->language == 'hu') {
                     return $user->profile->lastname.' '.$user->profile->firstname;
                 }
                 // Más nyelveken marad a "Keresztnév Vezetéknév" formátum
                 return $user->profile->firstname.' '.$user->profile->lastname;
             },
       ],
   ],
];`

**Comment by moln4rvilmos** [comment]
Többnyelvű oldalnál, ha ott főleg magyarok (vagy magyarok is) vannak:

<?php
return [
   'modules' => [
       'user' => [
             'displayNameCallback' => function($user) {
                 // Ha magyar nyelv van beállítva, akkor a "Vezetéknév Keresztnév" formátumot használjuk
                 if (Yii::$app->language == 'hu') {
                     return $user->profile->lastname.' '.$user->profile->firstname;
                 }
                 // Más nyelveken marad a "Keresztnév Vezetéknév" formátum
                 return $user->profile->firstname.' '.$user->profile->lastname;
             },
       ],
   ],
];

**Comment by moln4rvilmos** [comment]
A keleti nyelveknél a névsorrendet (vezetéknév keresztnév) formátumban a protected/config/common.php fájlt az alábbiak szerint érdemes módosítani:
```
<?php
/**
 * This file provides to overwrite the default HumHub / Yii configuration by your local common (Console and Web) environments
 * @see http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html
 * @see http://docs.humhub.org/admin-installation-configuration.html
 * @see http://docs.humhub.org/dev-environment.html
 */
return [
    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ],
   'modules' => [
       'user' => [
             'displayNameCallback' => function($user) {
                  // A keleti nyelvek: magyar, mongol, japán, koreai, kínai, khmer
                  $easternLanguages = ['hu', 'mn', 'ja', 'ko', 'zh', 'km'];
                  if (in_array(Yii::$app->language, $easternLanguages)) {
                      return $user->profile->lastname.' '.$user->profile->firstname;
                  }
                  // Más nyelveken marad a "Keresztnév Vezetéknév" formátum
                  return $user->profile->firstname.' '.$user->profile->lastname;
             }
       ],
  ]
];
```
Így ezeknél a nyelvi beállításoknál a névsorrend megfordul.

**Comment by ArchBlood** [comment]
> A keleti nyelveknél a névsorrendet (vezetéknév keresztnév) formátumban a protected/config/common.php fájlt az alábbiak szerint érdemes módosítani:
> 
> ```
> <?php
> /**
>  * This file provides to overwrite the default HumHub / Yii configuration by your local common (Console and Web) environments
>  * @see http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html
>  * @see http://docs.humhub.org/admin-installation-configuration.html
>  * @see http://docs.humhub.org/dev-environment.html
>  */
> return [
>     'components' => [
>         'urlManager' => [
>             'showScriptName' => false,
>             'enablePrettyUrl' => true,
>         ],
>     ],
>    'modules' => [
>        'user' => [
>              'displayNameCallback' => function($user) {
>                   // A keleti nyelvek: magyar, mongol, japán, koreai, kínai, khmer
>                   $easternLanguages = ['hu', 'mn', 'ja', 'ko', 'zh', 'km'];
>                   if (in_array(Yii::$app->language, $easternLanguages)) {
>                       return $user->profile->lastname.' '.$user->profile->firstname;
>                   }
>                   // Más nyelveken marad a "Keresztnév Vezetéknév" formátum
>                   return $user->profile->firstname.' '.$user->profile->lastname;
>              }
>        ],
>   ]
> ];
> ```
> 
> Így ezeknél a nyelvi beállításoknál a névsorrend megfordul.

I've had clients use the following in their `common.php`;
```php
<?php
/**
 * This file provides to overwrite the default HumHub / Yii configuration by your local common (Console and Web) environments
 * @see http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html
 * @see http://docs.humhub.org/admin-installation-configuration.html
 * @see http://docs.humhub.org/dev-environment.html
 */

return [
    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ],
    'modules' => [
        'user' => [
            'displayNameCallback' => function ($user) {
                if (!isset($user->profile)) {
                    return $user->username;
                }

                $targetLanguages = ['ja', 'ko', 'zh'];
                if (in_array(Yii::$app->language, $targetLanguages, true)) {
                    return $user->profile->lastname . ' ' . $user->profile->firstname;
                }

                return $user->profile->firstname . ' ' . $user->profile->lastname;
            },
        ],
    ],
];
```
