### ISSUE TITLE
Strange image issue

### ISSUE THREAD

**Issue by mafd66** [humhub/humhub#2797]
Hello,

If I upload an image to a steam it has no preview and if you click on it, the picture is not shown.
If I upload an image to a gallery it has also no preview, but if you click on the picture name it is shown in a new tab and also in the gallery widget.
If I open the list of galleries, only the "Click here to add new Gallery" picture is shown, but not the existing galleries - most of the time; sometimes they are shown, but when I click on it, no image shows up.
The strange thing is that there are no errors in the log...
Any ideas what the issue is?
Thank you.

Best regards,
Manfred

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      | 7.1.10
| Operating system |Arch Linux

![bildschirmfoto vom 2017-10-22 00-02-47](https://user-images.githubusercontent.com/32990019/31856244-6480f88e-b6bc-11e7-8e9f-89b8e3457e31.png)
![bildschirmfoto vom 2017-10-22 00-03-26](https://user-images.githubusercontent.com/32990019/31856249-72e89576-b6bc-11e7-8c86-f4d1ea10d7fb.png)

![bildschirmfoto vom 2017-10-21 23-50-45](https://user-images.githubusercontent.com/32990019/31856140-cb377a6e-b6ba-11e7-99fb-a7929cb4e053.png)

**Comment by Felli** [comment]
I have a few additional questions to ask

### Have you enable ImageMagick and properly configurated?

### Is X-Sendfile checked and properly configurated?

**Comment by mafd66** [comment]
Hi,
Thank you for your response.
Yes, Imagemagick is properly configured and X-Sendfile is disabled.
I think that I have found the issue, but don't know how to solve it at the moment.
I have an Apache proxy server, which redirects all traffic to the "real" Apache server, where humbub runs.
If I connect directly to the webserver (without the proxy server), all images are shown.
Currently I only have a ProxyPass and ProxyPassReverse directive in the config file.
So you know how to configure the proxy server correctly to work with humhub?
Thanks a lot.

Best regards,
Manfred

**Comment by Felli** [comment]
Should be able to do this via the `.htaccess` file, but as for how to do so, I'm not sure.

**Comment by allyraza** [comment]
@mafd66 can you post your config file for proxy server

**Comment by mafd66** [comment]
Hi,
My virtual host file looks like this:
-----------------
<VirtualHost *:443>
ServerName www.external.address
SSLEngine on
SSLProxyEngine On
ProxyRequests Off
ProxyPass "/humhub" "https://www.internal.address/humhub"
ProxyPassReverse "/humhub" "https://www.internal.address/humhub"
SSLCertificateFile ...
SSLCertificateKeyFile ...
</VirtualHost>
-----------------
BR Manfred
