### ISSUE TITLE
"Write a new comment…" field error

### ISSUE THREAD

**Issue by KitsuneSolar** [humhub/humhub#2800]
### What steps will reproduce the problem?

**Firefox 56.0.1**

In "Write a new comment…" field not write text, but push "Send" button several times.

### What is the expected result?

Error.

### What do you get instead?

https://community.humhub.com/u/kitsunesolar/user/profile/home

![screenshot-2017-10-23 kitsune solar - humhub community](https://user-images.githubusercontent.com/12877339/31897784-16fd6114-b820-11e7-95a4-0a03cc950f9e.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.3
| PHP version      | --
| Operating system | --

**Comment by acs-ferreira** [comment]
Can confirm this.

**Comment by Felli** [comment]
Nice catch!

**Comment by ShalokShalom** [comment]
#3059 shows how to reproduce it precisely

**Comment by ShalokShalom** [comment]
Why is this closed?

**Comment by Felli** [comment]
Because this issue was fixed.

**Comment by ShalokShalom** [comment]
thanks
