### ISSUE TITLE
Register Process // Break at end

### ISSUE THREAD

**Issue by ygrosyeux** [humhub/humhub#2806]
### What steps will reproduce the problem?
Fresh install of 1.2.3
New user try to register : 
 - 1st step : receive email : OK
 - 2nd step : Register form : OK, but at the end page break
![endofregister](https://user-images.githubusercontent.com/16611866/32066567-7eeed908-ba80-11e7-9c94-ec2e807dd45e.png)

Error 500, but no error in logs

### What is the expected result?
Success message after register

### What do you get instead?
Page break up

### Additional info
User is created, but the page breaks

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.3
| PHP version      |  5.6.17
| Operating system | Windows

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
> Note: Also provide the full error stacks from Administration --> Information --> Logging and errors from your browser console if possible.

**Comment by Felli** [comment]
Might be a custom theme issue from the looks of it.

**Comment by ygrosyeux** [comment]
Sorry,

I've put in production (i've comment debug in index.php).

![2017-10-27 08_26_39-yii_base_errorexception](https://user-images.githubusercontent.com/16611866/32090655-cc0fdc26-baf0-11e7-8987-e7c687ee41d5.png)

![2017-10-27 08_28_43-journaux - administration - club clients variopositif](https://user-images.githubusercontent.com/16611866/32090684-e460df78-baf0-11e7-8948-4ddb43273800.png)

**Comment by Felli** [comment]
@ygrosyeux on [line 12](https://github.com/humhub/humhub/blob/master/protected/humhub/components/Widget.php#L12) remove this, and on [line 49](https://github.com/humhub/humhub/blob/master/protected/humhub/components/Widget.php#L49) change `Event` to `\yii\base\Event` and see if this fixes anything.

**Comment by ygrosyeux** [comment]
Great fix ! 👍 

That's ok

**Comment by buddh4** [comment]
But why should this fail? Don't see a reason for it.

**Comment by Felli** [comment]
@buddh4 could be a self-hosted issue with Windows servers, I myself haven't ran into this on Linux based servers.
