### ISSUE TITLE
Users not appearing on Directory -> Members page

### ISSUE THREAD

**Issue by XtremePlayzCODE** [humhub/humhub#2809]
### What steps will reproduce the problem?
1. Download HumHub 1.2.3
2. Set up as normal, follow all prerequisites
3. Add ~25 members
4. Go to the Directory -> Members page
5. Almost all members are not listed.

### What is the expected result?
All users should be shown.

### What do you get instead?
Only 2 users (myself and another admin)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.3
| PHP version      | 7.0.22
| Operating system | Online host w/ Apache

**Comment by buddh4** [comment]
How did you add the members? Within the Admin interface, or by registration? You can rebuild the search index by executing the following command within the `protected` directory:

`php yii search/rebuild`

**Comment by XtremePlayzCODE** [comment]
I built them using the admin interface and some users (about 5) were created by registration. Another admin was created by the admin interface.

**Comment by luke-** [comment]
Does the rebuild fixes your problem?

**Comment by XtremePlayzCODE** [comment]
Issue fixed on rebuild, thanks!

**Comment by topherjamesknoll** [comment]
> How did you add the members? Within the Admin interface, or by registration? You can rebuild the search index by executing the following command within the `protected` directory:
> 
> `php yii search/rebuild`

How do I rebuild on a shared server? Is this command line or something I add to a PHP file?
