### ISSUE TITLE
Internal Server Error Occurred

### ISSUE THREAD

**Issue by motohub1** [humhub/humhub#2810]
Internal Server Error Occurred…was browsing files in my hosting file manager (changed nothing) cannot get to my site now…following log files…any ideas? 

Output of recent error log on Hosting Server:
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40]     'SCRIPT_FILENAME' => '/home/themotoh/public_html/index.php',
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40]     'DOCUMENT_ROOT' => '/home/themotoh/public_html',
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #12 /home/themotoh/public_html/index.php(25): yii\\base\\Application->__construct(Array)
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #11 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/base/Application.php(206): yii\\base\\Object->__construct(Array)
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #10 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\\base\\Application->init()
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #9 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/base/Application.php(267): yii\\web\\Application->bootstrap()
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #8 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/web/Application.php(67): yii\\base\\Application->bootstrap()
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #7 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/base/Application.php(315): humhub\\components\\bootstrap\\LanguageSelector->bootstrap(Object(humhub\\components\\Application))
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #6 /home/themotoh/public_html/protected/humhub/components/bootstrap/LanguageSelector.php(25): yii\\di\\ServiceLocator->__get('user')
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #5 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(71): yii\\di\\ServiceLocator->get('user')
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #4 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(133): yii\\BaseYii::createObject(Array)
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #3 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/BaseYii.php(344): yii\\di\\Container->get('humhub\\\\modules\\\\...', Array, Array)
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #2 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/di/Container.php(154): yii\\di\\Container->build('humhub\\\\modules\\\\...', Array, Array)
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #1 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/di/Container.php(362): yii\\di\\Container->getDependencies('humhub\\\\modules\\\\...')
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] #0 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/di/Container.php(422): ReflectionClass->__construct('humhub\\\\modules\\\\...')
[Wed Nov 01 15:38:24 2017] [error] [client 75.128.190.40] ReflectionException: Class humhub\\modules\\user\\components\\User does not exist in /home/themotoh/public_html/protected/vendor/yiisoft/yii2/di/Container.php:422

Output of php yii integrity/run (ran on protected directory via SSH):

PHP Warning 'yii\base\ErrorException' with message 'call_user_func() expects parameter 1 to be a valid callback, class 'humhub\modules\admin\Events' not found'

in /home/themotoh/public_html/protected/vendor/yiisoft/yii2/base/Event.php:216

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'call_user_func(...', '/home/themotoh/...', 216, Array)
#1 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/base/Event.php(216): call_user_func(Array, Object(yii\base\Event))
#2 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/base/Component.php(548): yii\base\Event::trigger('humhub\\componen...', 'onInit', Object(yii\base\Event))
#3 /home/themotoh/public_html/protected/humhub/components/console/Application.php(32): yii\base\Component->trigger('onInit')
#4 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\components\console\Application->init()
#5 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object->__construct(Array)
#6 /home/themotoh/public_html/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#7 /home/themotoh/public_html/protected/yii(28): yii\console\Application->__construct(Array)
#8 {main}

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
Seems to be fixed. https://community.humhub.com/content/perma?id=127340
