### ISSUE TITLE
Discord chat / audio /video / streaming module does not load

### ISSUE THREAD

**Issue by NENJAK** [humhub/humhub#2812]
### Additional info 
I installed Discord module an although in group are 2 Members they are not visible in HumHub.
I installed / configured properly Discord Widget URL but plugin still can not find any active members 

| Q                | A
| ---------------- | ---
| HumHub version   | version: 1.2.3
| PHP version      |  PHP 7.1.4-1+deb.sury.org~xenial+1 (cli) (built: Apr 11 2017 22:12:32) ( NTS )
| Operating system | Ubuntu 16.04

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by NENJAK** [comment]
.. but I tried now also to include it as Iframe it is also not functioning, I guess there is something wrong with Discort?

**Comment by Felli** [comment]
Did you enable the Discord widget from Discord's side as well?

**Comment by NENJAK** [comment]
Hi Felli,

I created channel, is there any additional setting to enable it for Humhub?

**Comment by NENJAK** [comment]
Hello,

ok thanks I found,
https://blog.discordapp.com/add-the-discord-widget-to-your-site-d45ffcd718c6
regards

**Comment by Felli** [comment]
I also would recommend updating the module manually till me and the devs can better schedule releases, you'll find it via @GreenMeteor under `humhub-discordapp-module `.

**Comment by NENJAK** [comment]
OK, thanks
