### ISSUE TITLE
Dark/Night mode

### ISSUE THREAD

**Issue by devcline** [humhub/humhub#2813]
Can we have a dark/night mode or a theme?

**Comment by Felli** [comment]
It's been proven possible with the FlatHub theme.

**Comment by buddh4** [comment]
Yeah, rather a theming issue, think this won't be included into the core.
Please rather ask such questions in the [Community](https://community.humhub.com)

**Comment by petrk94** [comment]
I would like that function as a switch function in admin backend or for each user on client site in the user settings

**Comment by devcline** [comment]
As for the DARK MODE, as you can see its a 2018 feature that every site making, like reddit, youtube etc
