### ISSUE TITLE
Enable Discord widget for individual Spaces

### ISSUE THREAD

**Issue by olantrust** [humhub/humhub#2814]
It would be more useful to allow the Discord module to be enabled for individual spaces.

This would permit each space to have a module linked to a relevant (and different) Discord forum.

Only permitted users of that space would thus have access to the forum.

**Comment by Felli** [comment]
I'll think about implementing this in a separate module as I don't believe it to be useful as of right now, also note that this even though it is in the marketplace, it is still third-party module and isn't maintained by HumHub, I suggest closing this issue and opening on @GreenMeteor's repository. :+1:

**Comment by olantrust** [comment]
Thanks Sarah, will close.

Look forward to more useful integrated module.
