### ISSUE TITLE
How to get Humhub registration working without a confirmations?

### ISSUE THREAD

**Issue by bug0000** [humhub/humhub#2815]
How to "disable" any mail confirmations for registration?
HumHub version  1.2.3

**Comment by Felli** [comment]
Please refer to the [community site](https://community.humhub.com) for questions on customizing HumHub

**Comment by buddh4** [comment]
There is no build in way for this yet, you'll need to overwrite the registration process as noted in https://github.com/humhub/humhub/issues/2121

You can also contact info@humhub.com for customization requests etc.

Also as Felli suggested, please ask such questions in the community.
