### ISSUE TITLE
activity mail error

### ISSUE THREAD

**Issue by Joe2824** [humhub/humhub#2818]
### What steps will reproduce the problem?
don't know

### What is the expected result?
humhub send activity mails
### What do you get instead?
`Could not send activity mail to: Name Name (Calling unknown method: yii\console\Request::get())`
<img width="850" alt="bildschirmfoto 2017-11-11 um 08 32 48" src="https://user-images.githubusercontent.com/4028085/32687378-183f5326-c6bb-11e7-8f1f-353a61239837.png">

### Additional info

<img width="515" alt="bildschirmfoto 2017-11-11 um 08 35 24" src="https://user-images.githubusercontent.com/4028085/32687393-621d17a8-c6bb-11e7-8e85-a84c8ed841b7.png">

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.3
| PHP version      | 7.1
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by acs-ferreira** [comment]
See https://github.com/humhub/humhub/issues/2573 if it helps

**Comment by Joe2824** [comment]
perfect that fixed my problem.
