### ISSUE TITLE
New Installation Errors

### ISSUE THREAD

**Issue by XxPoNaGeXx** [humhub/humhub#2819]
### What steps will reproduce the problem?
Download 
Extract
Go to your installation path on chrome

### What is the expected result?

installer to appear 

### What do you get instead?

An Error occurred while handling another error:
yii\base\InvalidConfigException: Unable to locate message source for category 'FileModule.widgets_UploadInput'. in /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/i18n/I18N.php:200
Stack trace:
#0 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/components/i18n/I18N.php(168): yii\i18n\I18N->getMessageSource('FileModule.widg...')
#1 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/i18n/I18N.php(88): humhub\components\i18n\I18N->getMessageSource('FileModule.widg...')
#2 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/components/i18n/I18N.php(139): yii\i18n\I18N->translate('FileModule.widg...', 'Sorry, you can ...', Array, 'en-US')
#3 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/BaseYii.php(509): humhub\components\i18n\I18N->translate('FileModule.widg...', 'Sorry, you can ...', Array, 'en-US')
#4 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/modules/file/widgets/UploadInput.php(189): yii\BaseYii::t('FileModule.widg...', 'Sorry, you can ...', Array)
#5 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/widgets/JsWidget.php(97): humhub\modules\file\widgets\UploadInput->getData()
#6 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/modules/file/widgets/UploadInput.php(144): humhub\widgets\JsWidget->getOptions()
#7 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/modules/file/widgets/UploadButton.php(72): humhub\modules\file\widgets\UploadInput->run()
#8 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/components/Widget.php(58): humhub\modules\file\widgets\UploadButton->run()
#9 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/widgets/views/markdownFieldModals.php(15): humhub\components\Widget::widget(Array)
#10 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/View.php(330): require('/opt/lampp/htdo...')
#11 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/opt/lampp/htdo...', Array)
#12 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/opt/lampp/htdo...', Array, Object(humhub\widgets\MarkdownFieldModals))
#13 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Widget.php(234): yii\base\View->render('markdownFieldMo...', Array, Object(humhub\widgets\MarkdownFieldModals))
#14 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/widgets/MarkdownFieldModals.php(24): yii\base\Widget->render('markdownFieldMo...')
#15 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/components/Widget.php(58): humhub\widgets\MarkdownFieldModals->run()
#16 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array)
#17 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\BaseStack->run()
#18 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/components/View.php(252): yii\base\Widget::widget()
#19 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/views/errorHandler/exception.php(451): humhub\components\View->endBody()
#20 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/View.php(330): require('/opt/lampp/htdo...')
#21 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/opt/lampp/htdo...', Array)
#22 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(249): yii\base\View->renderFile('/opt/lampp/htdo...', Array, Object(yii\web\ErrorHandler))
#23 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(115): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#24 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\Exception))
#25 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\Exception))
#26 {main}
Previous exception:
yii\base\ErrorException: mkdir(): Permission denied in /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:499
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'mkdir(): Permis...', '/opt/lampp/htdo...', 499, Array)
#1 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(499): mkdir('/opt/lampp/htdo...', 509)
#2 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/log/FileTarget.php(90): yii\helpers\BaseFileHelper::createDirectory('/opt/lampp/htdo...', 509, true)
#3 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\log\FileTarget->init()
#4 [internal function]: yii\base\Object->__construct(Array)
#5 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#6 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\log\\FileTar...', Array, Array)
#7 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\log\\FileTar...', Array, Array)
#8 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/log/Dispatcher.php(102): yii\BaseYii::createObject(Array)
#9 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\log\Dispatcher->init()
#10 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/log/Dispatcher.php(90): yii\base\Object->__construct(Array)
#11 [internal function]: yii\log\Dispatcher->__construct(Array)
#12 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#13 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\log\\Dispatc...', Array, Array)
#14 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\log\\Dispatc...', Array, Array)
#15 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#16 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Application.php(307): yii\di\ServiceLocator->get('log')
#17 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#18 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/components/Application.php(46): yii\web\Application->bootstrap()
#19 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Application.php(272): humhub\components\Application->bootstrap()
#20 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\base\Application->init()
#21 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#22 /opt/lampp/htdocs/social/humhub-1.2.3/index.php(25): yii\base\Application->__construct('[<span class="s...')
#23 {main}

Next yii\base\Exception: Failed to create directory "/opt/lampp/htdocs/social/humhub-1.2.3/protected/runtime/logs": mkdir(): Permission denied in /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:504
Stack trace:
#0 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/log/FileTarget.php(90): yii\helpers\BaseFileHelper::createDirectory('/opt/lampp/htdo...', 509, true)
#1 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\log\FileTarget->init()
#2 [internal function]: yii\base\Object->__construct(Array)
#3 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#4 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\log\\FileTar...', Array, Array)
#5 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\log\\FileTar...', Array, Array)
#6 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/log/Dispatcher.php(102): yii\BaseYii::createObject(Array)
#7 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\log\Dispatcher->init()
#8 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/log/Dispatcher.php(90): yii\base\Object->__construct(Array)
#9 [internal function]: yii\log\Dispatcher->__construct(Array)
#10 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#11 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\log\\Dispatc...', Array, Array)
#12 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\log\\Dispatc...', Array, Array)
#13 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#14 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Application.php(307): yii\di\ServiceLocator->get('log')
#15 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#16 /opt/lampp/htdocs/social/humhub-1.2.3/protected/humhub/components/Application.php(46): yii\web\Application->bootstrap()
#17 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Application.php(272): humhub\components\Application->bootstrap()
#18 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\base\Application->init()
#19 /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#20 /opt/lampp/htdocs/social/humhub-1.2.3/index.php(25): yii\base\Application->__construct('[<span class="s...')
#21 {main}

Notice: Trying to get property of non-object in /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/log/Dispatcher.php on line 186

Notice: Trying to get property of non-object in /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/log/Dispatcher.php on line 186

Notice: Trying to get property of non-object in /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/log/Dispatcher.php on line 186

Notice: Trying to get property of non-object in /opt/lampp/htdocs/social/humhub-1.2.3/protected/vendor/yiisoft/yii2/log/Dispatcher.php on line 186

**Comment by buddh4** [comment]
Please add some information about your environment as php version humhub version operating system etc.

**Comment by bumrufus** [comment]
same problem!
Environment is Win 2012 Server with PHP 7.1.7 MySQL 5.5 latest humhub Version 1.2.3

**Comment by bumrufus** [comment]
fixed it, i had to run the yi.bat file on the server!

**Comment by bumrufus** [comment]
tried to install it in linux and now i got the same error, but i cant run the .bat on a linux machine!!

**Comment by Felli** [comment]
With Linux make sure that all of your permissions are exact, if you don't then you won't be able to run HumHub, also to note could you provide what type of Linux server you're running CentOS 6 & 7 works pretty well for me.

**Comment by bumrufus** [comment]
Centos 7 and i did chmod -R 777 on the humhub folder

**Comment by Felli** [comment]
You shouldn't use 777 on the Humhub folder, just use 744 on the [required one](http://docs.humhub.org/admin-installation.html#file-permissions)

**Comment by bumrufus** [comment]
Yeah i just want to test if it will work with 777 on the humhub folder! With 744 in the required folders its not working

**Comment by bumrufus** [comment]
I have no clue why its not working

**Comment by Felli** [comment]
I would think this would be a server side issue you'd have to take up with your hosting providers.

**Comment by bumrufus** [comment]
I have installed it on my own esx server, other php projects are working good there

**Comment by bumrufus** [comment]
fixed it by running this command: setenforce 0

**Comment by bumrufus** [comment]
I have the problem too (in CentOS7). I tried to change the owner and group, but it didn't work. Finally, I closed the selinux, and it work.setenforce 0If you want to close it forever, you can change the /etc/selinux/config file:SELINUX=disabled
-- | --
