### ISSUE TITLE
Default space rather than dashboard

### ISSUE THREAD

**Issue by motohub1** [humhub/humhub#2821]
The weird thing is upon logging in I can get the Space to be the default page, but close the browser tab and re-entering the site (still logged in) it reverts back to the dashboard as the default page? Here is the file I changed to get to where I am. Is there another file I need to edit?protected/config/web.php: 
return [ 
    ‘components’ => [

    // …

        ‘user’ => [ 
            ‘returnUrl’ => [‘space/space’, ‘sguid’=> ‘db0f7450-6e8b-4399-8bf1-aca51027bc82’], 
        ], 
    ] 
];
| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by acs-ferreira** [comment]
Maybe check the `defaultRoute` http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#default-route

**Comment by motohub1** [comment]
Thank you!
