### ISSUE TITLE
 Space notifications

### ISSUE THREAD

**Issue by motohub1** [humhub/humhub#2822]
Not receiving notifications on public space? No one is receiving notification on a public space when post is liked or commented on?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by luke-** [comment]
There is a Mail Summary for this type of information.
