### ISSUE TITLE
Hide Dashboard button

### ISSUE THREAD

**Issue by motohub1** [humhub/humhub#2823]
I would like to know if there is a way to hide the Dashboard button from the top Navigation? As I am now using a Default Space instead
| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Please keep all questions about customizing HumHub within the [community site](https://community.humhub.com/dashboard), or as @buddh4 has said before contact `info@humhub.com`. :smiley:

**Comment by motohub1** [comment]
Will do...thank you
