### ISSUE TITLE
New Installation warning message

### ISSUE THREAD

**Issue by byndstd** [humhub/humhub#2824]
I'm trying to install Humhub 1.2.3 on my localhost but I get this message
" Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in I:\zzerver\Uwamp\www\hmhb\hh1\protected\humhub\components\Application.php on line 98"

I changed the 3 files :  php.ini , php_uwamp.ini , php_initial.ini 

;date.timezone = 
to 
;date.timezone ="America/New_York"

but I still get the same error message at the beginning of installation

**Comment by allyraza** [comment]
Hi there,

you have set the timezone but you did not uncomment to enable it

```ini
;date.timezone ="America/New_York"
to
date.timezone ="America/New_York"
```
notice the semicolon in front

**Comment by byndstd** [comment]
ah OK , now it's working 
Thank you very much
