### ISSUE TITLE
Cronjob on OVH 

### ISSUE THREAD

**Issue by kazzz57** [humhub/humhub#2825]
Traduction
Désactiver la traduction instantanée
1289/5000
Hello
I come to you for help,
I try unsuccessfully, and with several techniques to set up CronJob on my host OVH, concerning my script of social network of companies (HumHub)

I create a php file that I run from the OVH CronJob executor without success

```
#! / Usr / local / bin / php

<? Php

$ path = dirname ("/ homez.2069 / login / www / humhub / protected / yii search / rebuild> / dev / null 2> & 1");
$ path = dirname ("/ homez.2069 / login / www / humhub / protected / yii search / optimize> / dev / null 2> & 1");
$ path = dirname ("/ homez.2069 / login / www / humhub / protected / yii cron / daily> / dev / null 2> & 1");
$ path = dirname ("/ homez.2069 / login / www / humhub / protected / yii cron / hourly> / dev / null 2> & 1");
$ path = dirname ("/ homez.2069 / login / www / humhub / protected / yii integrity / run> / dev / null 2> & 1");

?>
```

the script needs to run these commands:
/ home / login / www / humhub / protected / yii search / rebuild
/ home / login / www / humhub / protected / yii search / optimize
/ home / login / www / humhub / protected / yii cron / daily
/ home / login / www / humhub / protected / yii cron / hourly
/ home / login / www / humhub / protected / yii integrity / run

when I use the SSH terminal, it works without problems, but I can not automate it in a CronJob

could you help me ?

cordially
S.Casanova
Google Traduction pour les entreprises :Google Kit du traducteurGadget Traduction
À propos de Google TraductionCommunautéMobile
À propos de GoogleConfidentialité et conditions d'utilisationAideEnvoyer des commentaires

**Comment by Felli** [comment]
Please check out this [wiki](https://community.humhub.com/s/installation-and-setup/wiki/page/view?title=Cron+Job+Setup) for Cron Job Setup. :smiley:

**Comment by kazzz57** [comment]
yes, I found all this information, and I understand how to plan CronJob on OVH, but it does not tell me how to create the php file, and what are the indications to put in.
the exact coding without making mistakes.

**Comment by acs-ferreira** [comment]
See https://github.com/humhub/humhub/issues/2718#issuecomment-330910142

**Comment by Felli** [comment]
@acs-ferreira I completely forgot about that post, I've added an example for OVH Cron Tasks in a PR to the doc rework as well as the wiki on the community site. :laughing:

**Comment by acs-ferreira** [comment]
You should just add a note to replace `php5.6` with the expected version like `php7.0` or `php7.1`

**Comment by kazzz57** [comment]
Ok, I solved my case
you must actually put the cron.php files at the root of the hosting.
I created 5 files because I have 5 commands to execute.
cron1.php
cron2.php
...

I put as right on the files 605

here is the file cron1.php

`#! / Usr / local / bin / php

<? php $ humhubh = '/usr/local/php5.6/bin/php/home/ (login) / www / humhub / protected / yii search / rebuild'; exec ($ humhubh); ?>`

the most difficult being finding the exact code to put in this file cron.php

I try dozens of solutions without success, what to become crazy

Of course, you have to pay attention to the absolute path used

and then we create the CRON tasks on the BackOffice part of OVH

**Comment by sayalivaidya** [comment]
I have my project on OVH server , i have to set cron which should run in every 1 minutes but in OVH server there is no any option to set cron for 1 minuets ,what script i have to use? and how?

**Comment by danielkesselberg** [comment]
Hey @sayalivaidya,

please consider https://community.humhub.com for questions in general. You find some information about cron in humhub backend and http://docs.humhub.org/admin-installation-configuration.html#cronjobs. For specific questions about your ovh server you may ask ovh.
