### ISSUE TITLE
Make Notification and Latest Activities messages easier to translate

### ISSUE THREAD

**Issue by mocsa** [humhub/humhub#2826]
The messages in the Notifications list (bell icon at the top of the page) and the Latest Activities box are assembled from short fragments. One example is:

1. {username}
1. answered the
1. Poll
1. {poll title}

Unfortunately, when these fragments are translated into Hungarian, the final message sounds very(!) awkward and silly. I guess, other languages which are non-Germanic have the same problem (although I'm not a language expert).

I suggest to make up such messages from only two fragments:

1. {username}
1. answered the Poll {poll title}

or, which is even more flexible, one fragment:

1. {username} answered the Poll {poll title}

Please also keep {poll title} as a movable variable.

That way it would be possible to translate such messages into almost perfect Hungarian. The Hungarian word order in case of 2 fragments would be (written with English words):

1. {username}
1. answered the {poll title} titled Poll

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      |  5.6.30
| Operating system | Windows

**Comment by xaro1** [comment]
+1
Similar situation in French.

**Comment by luke-** [comment]
Should be in one fragment in the meantime.

e.g. 
https://github.com/humhub/humhub-modules-polls/blob/master/activities/views/newVote.php#L5
