### ISSUE TITLE
New publication > Mail Subject : {Originator} in subject

### ISSUE THREAD

**Issue by ygrosyeux** [humhub/humhub#2829]
### What steps will reproduce the problem?
Set a new publication on a space. Mail is sent with the new publication. Mais is received with {Originator} in subject

### What is the expected result?
Name of the user who set the publication, and not {Originator}

### What do you get instead?
{Originator}

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      | 
| Operating system | Windows Server
![bugsubjectmail](https://user-images.githubusercontent.com/16611866/32944008-51624456-cb8e-11e7-8525-d9feeff9a6dc.png)

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by xaro1** [comment]
Already fixed in translation.
