### ISSUE TITLE
Ldap user - can add administrator group on a user

### ISSUE THREAD

**Issue by Spartacus2018** [humhub/humhub#2830]
### What steps will reproduce the problem?
Connect with administrator user.
Found a user who from ldap import
![image](https://user-images.githubusercontent.com/301074/33074269-d780497c-cec5-11e7-9545-fa5ec127d578.png)
Add group administrator to it.
![image](https://user-images.githubusercontent.com/301074/33074276-df7dd824-cec5-11e7-8bc3-f0983ed371cc.png)
Saved : 
![image](https://user-images.githubusercontent.com/301074/33074286-e7b42e80-cec5-11e7-8a37-72a986f20929.png)
go to index.php from the website.
go to user with new admin group.
and this user don"t have the admin group
![image](https://user-images.githubusercontent.com/301074/33074323-04e6648c-cec6-11e7-85cf-23f85f2c4676.png)

### What is the expected result?
I want my user have adminstrators group.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | : 1.2.3
| PHP version      |  PHP - Version - 7.0.22-0ubuntu0.16.04.1
| Operating system | ubuntu serveur

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by luke-** [comment]
So you can't add your LDAP users into other groups manually?
