### ISSUE TITLE
Limit Single Mentioned User

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2832]
You shouldn't be to able mention a single person within a post multiple times, an error warning should show instead.
![](https://image.prntscr.com/image/7hZ1p9SfSPizoTaKcV2w3Q.png)

**Comment by acs-ferreira** [comment]
Don't agree, sorry. :)
Why?

Take the case where you're writing a long post: you must mention the same user many times.
Just like:

```
@user1, you do this.
@Felli, you do that.
@another-user, what about this?
Also, @Felli, what about that?
...
```

_I frequently do so on HumHub, but also on GitHub. But it's just my opinion._

**Comment by buddh4** [comment]
I also don't think such restrictions are worth implementing and would just add more complexity. Or did you receive multiple emails or something?

**Comment by Felli** [comment]
At the moment I only receive multiple emails on mentioning + comments (When I'm a part of the conversation and have commented on it and then am replied to), as for this issue, I can see why it's not wanted to restrict it, but I don't believe it isn't 100% not necessary to restrict this, limiting users to a bare minimum of 3 mentions of a single user wouldn't hurt the platform itself, but if it's not seen as a useful restriction I'll go ahead and close this. :smile:
