### ISSUE TITLE
the new user changed the language in setting,the web page error.

### ISSUE THREAD

**Issue by djktv** [humhub/humhub#2839]
humhub version：1.2.3
lamp1.4x
php7.1.7

I used a test account login in my webste:  yeahba.com , and select Setting>>languages,I select chinese language,then my website show me errer page.

but when I clean the browser's cookies, my website Can be accessed normally. only the test user visit error.

this is the error page:
-----------------------------
`An Error occurred while handling another error:
ParseError: syntax error, unexpected quoted-string (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /home/wwwroot/www.yeahba.com/protected/humhub/messages/zh_tw/widgets_views_markdownEditor.php:3
Stack trace:
#0 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/i18n/PhpMessageSource.php(72): yii\i18n\PhpMessageSource->loadMessagesFromFile('/home/wwwroot/w...')
#1 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/i18n/MessageSource.php(107): yii\i18n\PhpMessageSource->loadMessages('widgets_views_m...', 'zh_tw')
#2 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/i18n/MessageSource.php(87): yii\i18n\MessageSource->translateMessage('widgets_views_m...', 'Bold', 'zh_tw')
#3 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/i18n/I18N.php(89): yii\i18n\MessageSource->translate('widgets_views_m...', 'Bold', 'zh_tw')
#4 /home/wwwroot/www.yeahba.com/protected/humhub/components/i18n/I18N.php(139): yii\i18n\I18N->translate('widgets_views_m...', 'Bold', Array, 'zh_tw')
#5 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/BaseYii.php(509): humhub\components\i18n\I18N->translate('widgets_views_m...', 'Bold', Array, 'zh_tw')
#6 /home/wwwroot/www.yeahba.com/protected/humhub/widgets/CoreJsConfig.php(93): yii\BaseYii::t('widgets_views_m...', 'Bold')
#7 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\CoreJsConfig->run()
#8 /home/wwwroot/www.yeahba.com/protected/humhub/components/View.php(248): yii\base\Widget::widget()
#9 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/views/errorHandler/exception.php(451): humhub\components\View->endBody()
#10 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/View.php(330): require('/home/wwwroot/w...')
#11 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/wwwroot/w...', Array)
#12 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(249): yii\base\View->renderFile('/home/wwwroot/w...', Array, Object(yii\web\ErrorHandler))
#13 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(115): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#14 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(ParseError))
#15 [internal function]: yii\base\ErrorHandler->handleException(Object(ParseError))
#16 {main}
Previous exception:
ParseError: syntax error, unexpected ''Add image/file'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /home/wwwroot/www.yeahba.com/protected/humhub/messages/zh_tw/widgets_views_markdownEditor.php:3
Stack trace:
#0 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/i18n/PhpMessageSource.php(72): yii\i18n\PhpMessageSource->loadMessagesFromFile('/home/wwwroot/w...')
#1 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/i18n/MessageSource.php(107): yii\i18n\PhpMessageSource->loadMessages('widgets_views_m...', 'zh_tw')
#2 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/i18n/MessageSource.php(87): yii\i18n\MessageSource->translateMessage('widgets_views_m...', 'Bold', 'zh_tw')
#3 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/i18n/I18N.php(89): yii\i18n\MessageSource->translate('widgets_views_m...', 'Bold', 'zh_tw')
#4 /home/wwwroot/www.yeahba.com/protected/humhub/components/i18n/I18N.php(139): yii\i18n\I18N->translate('widgets_views_m...', 'Bold', Array, 'zh_tw')
#5 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/BaseYii.php(509): humhub\components\i18n\I18N->translate('widgets_views_m...', 'Bold', Array, 'zh_tw')
#6 /home/wwwroot/www.yeahba.com/protected/humhub/widgets/CoreJsConfig.php(93): yii\BaseYii::t('widgets_views_m...', 'Bold')
#7 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\CoreJsConfig->run()
#8 /home/wwwroot/www.yeahba.com/protected/humhub/components/View.php(248): yii\base\Widget::widget()
#9 /home/wwwroot/www.yeahba.com/protected/humhub/views/layouts/main.php(58): humhub\components\View->endBody()
#10 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/View.php(330): require('/home/wwwroot/w...')
#11 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/wwwroot/w...', Array)
#12 /home/wwwroot/www.yeahba.com/protected/humhub/components/Controller.php(135): yii\base\View->renderFile('/home/wwwroot/w...', Array, Object(humhub\modules\dashboard\controllers\DashboardController))
#13 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/Controller.php(382): humhub\components\Controller->renderContent('\n<div class="co...')
#14 /home/wwwroot/www.yeahba.com/protected/humhub/modules/dashboard/controllers/DashboardController.php(62): yii\base\Controller->render('index', Array)
#15 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex()
#16 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#18 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array)
#19 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('dashboard/dashb...', Array)
#20 /home/wwwroot/www.yeahba.com/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#21 /home/wwwroot/www.yeahba.com/index.php(25): yii\base\Application->run()
#22 {main}`
--------------------------
you can test it in my website  yeahba.com.
could you help me please?thankyou very much!

**Comment by Felli** [comment]
Your translations for `/protected/humhub/messages/zh_tw/widgets_views_markdownEditor.php` are what is causing the problem, could you post the translations you've made for the `widgets_views_markdownEditor.php` file? Also, please note that HumHub may have some unknown issues with PHP 7.1 while you're using it.

**Comment by djktv** [comment]
this is `widgets_views_markdownEditor.php`page:
`<?php
return array (
  'Add image/file' => '添加圖片或文件',
  'Add link' => '增加鏈結',
  'Bold' => '加粗',
  'Code' => '代碼',
  'Enter a url (e.g. http://example.com)' => '輸入一個url(例如 http://example.com)',
  'Heading' => '標題',
  'Image' => '圖片',
  'Image/File' => '圖片/文件',
  'Insert Hyperlink' => '插入超鏈結',
  'Insert Image Hyperlink' => '插入圖片超鏈結',
  'Italic' => '斜體',
  'List' => '列表',
  'Please wait while uploading...' => '請稍候正在上載中...',
  'Preview' => '預覽',
  'Quote' => '引用',
  'Target' => '目標',
  'Title of your link' => '鏈結的標題',
  'URL/Link' => 'URL/鏈結',
  'code text here' => '代碼在這裡',
  'emphasized text' => '強調文本',
  'enter image description here' => '在這裡輸入圖像描述',
  'enter image title here' => '在這裡輸入圖像標題',
  'enter link description here' => '在這裡輸入鏈結描述',
  'heading text' => '標題文本',
  'list text here' => '列表在這裡',
  'quote here' => '這裡引用',
  'strong text' => '加粗文本',
  'Close' => '關閉',
  'Title' => '標題',
  'Unordered List' => '無序列表',
  'Ordered List' => '有序列表',
);`
