### ISSUE TITLE
No Auto save in wiki pages

### ISSUE THREAD

**Issue by OMereveille** [humhub/humhub#2840]
### What steps will reproduce the problem?
When I write or edit a wki page and I move to another page or function, my work on the wiki page disappears.
### What is the expected result?
It should save automatically a draft of my work before exiting.
### What do you get instead?
My draft is lost...
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.3
| PHP version      |  ?
| Operating system | Linux Ubuntu

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Could you please keep any official module issues on their right repositories? You'll find the wiki module issues [here](https://github.com/humhub/humhub-modules-wiki/issues). As for the question at hand, I'm not able to reproduce this within the community nor through localhost, more information would be needed before any action can be taken.

**Comment by buddh4** [comment]
Would be a great feature, as @Felli  said, please add this to the Wiki repo, in the future such feature request should be discussed in the community only, once the marketplace is open.
