### ISSUE TITLE
After placing a comment, the next comment input field is not empty

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2842]
### What steps will reproduce the problem?
Submit a comment and directly try to place a new comment below the new one.

### What is the expected result?
An empty comment input field when entered.

### What do you get instead?
The new input field will still contain the placeholder text "Write a new comment..." but will not go away, but becomes part of the input field. 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.? community website
| PHP version      | 
| Operating system |

Browsers: chrome and safari.
Tested on community website.

![img_4791](https://user-images.githubusercontent.com/6781157/33325063-9114d07a-d451-11e7-94d6-5cf5e47e99b0.jpg)

**Comment by Felli** [comment]
This is already been mentioned in #2800, but thanks. :+1:

**Comment by martinbeek** [comment]
Ok! Are you sure this is the same issue? I can’t exactly understand what the author of the other issue means.

**Comment by Felli** [comment]
The issue is the same, on both issues, it's possible to edit and press send and the text that isn't supposed to be sendable can be sent, this is also a bug within the community site as well.
