### ISSUE TITLE
content notification in badge-notifications ?

### ISSUE THREAD

**Issue by byndstd** [humhub/humhub#2843]
is it possible to add notification about new content to badge-notifications; the badge-notifications is notifying comments , likes, but no notify about new content.

**Comment by buddh4** [comment]
Sorry I don't 100% understand the issue what do you mean with badge-notifications. Do you mean the summary mail?

**Comment by acs-ferreira** [comment]
Maybe the Number on the bell icon?
![image](https://user-images.githubusercontent.com/12234510/33451107-3634c2c8-d60e-11e7-9487-071434128d42.png)

**Comment by buddh4** [comment]
Ah ok, so you set the "Receive notifications for new content" for a space, but the notificaiont badge is not updated when this space has new content?

**Comment by acs-ferreira** [comment]
@buddh4 i'm just guessing :)

Bur for the record, the option (in every space) is:
![image](https://user-images.githubusercontent.com/12234510/33451728-35cb8180-d610-11e7-9305-e4e7442ed5c2.png)

**Comment by byndstd** [comment]
I did set receive notification for new content, but the Number on the bell icon change only if I get a new comments, or a like, but don't change for new content I don't know why
