### ISSUE TITLE
Exception error in member search

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2844]
### What steps will reproduce the problem?
Go to the directory.
Go to the members page.
Go to the second page of member results.
Search for "John" or any other name

### What is the expected result?
A filtered list of users.

### What do you get instead?
You took a wrong turn, exception error

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.3
| PHP version      | 7
| Operating system | Debian

Error log: 
`OutOfBoundsException: Seek position 25 is out of range in /var/www/friendweb.nl/httpdocs/protected/humhub/modules/search/engine/ZendLuceneSearch.php:131 Stack trace: #0 [internal function]: ArrayIterator->seek(25) #1 /var/www/friendweb.nl/httpdocs/protected/humhub/modules/search/engine/ZendLuceneSearch.php(131): LimitIterator->rewind() #2 /var/www/friendweb.nl/httpdocs/protected/humhub/modules/directory/controllers/DirectoryController.php(106): humhub\modules\search\engine\ZendLuceneSearch->find('john', Array) #3 [internal function]: humhub\modules\directory\controllers\DirectoryController->actionMembers() #4 /var/www/friendweb.nl/httpdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #5 /var/www/friendweb.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #6 /var/www/friendweb.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('members', Array) #7 /var/www/friendweb.nl/httpdocs/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('directory/direc...', Array) #8 /var/www/friendweb.nl/httpdocs/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #9 /var/www/friendweb.nl/httpdocs/index.php(25): yii\base\Application->run() #10 {main}`

**Comment by Felli** [comment]
Have you tried rebuilding the search index?

**Comment by martinbeek** [comment]
Yes i rebuild the index and ran the integrity check. 

Martin

**Comment by pelletiermaxime** [comment]
Just ran into the exact same problem. It seems it adds the keyword to the already existing query, so the url is "index.php?r=directory%2Fdirectory%2Fmembers&_pjax=%23layout-content&_=1513115926329&keyword=test1&page=2&per-page=25&_pjax=%23layout-content&keyword=test2". I guess it then tries to find results for the second page and there is no second page for that search query.

**Comment by pelletiermaxime** [comment]
Thanks!
