### ISSUE TITLE
Max file uploads per post in space

### ISSUE THREAD

**Issue by byndstd** [humhub/humhub#2845]
How can I change the max number of file that can be upload per post in space to only 1 file per post

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.3
| PHP version      |   5.6.18
| Operating system |  Uwamp

**Comment by Felli** [comment]
This is done via `upload_max_filesize` within your PHP extension settings, in the future please ask such questions on the [community site](https://community.humhub.com).
