### ISSUE TITLE
Empty PHP Timezone breaks Stream

### ISSUE THREAD

**Issue by devcline** [humhub/humhub#2846]
today while i connection to my humhub i see this error in my inspector
```
humhub.log.js?v=1509743052:149 ERROR - humhub.modules.stream: An unexpected server error occurred. If this keeps happening, please contact a site administrator. 
"datefmt_create: no such time zone: 'UTC': U_ILLEGAL_ARGUMENT_ERROR"
response: {name: "Invalid Configuration", message: "datefmt_create: no such time zone: 'UTC': U_ILLEGAL_ARGUMENT_ERROR", 
```
**humhub version: 1.2.3**

**Comment by Felli** [comment]
Check your `ACP --> Information --> Logging` for the full error stack.

**Comment by buddh4** [comment]
Also check `Administration -> Information -> Prerequisites` for the ICU verison. And try setting a valid timezone @  `Administration -> Settings-> Server Zimezone`

**Comment by devcline** [comment]
well i cant access to a Administration section : 

```
PHP Fatal Error – yii\base\ErrorException

Call to a member function getPattern() on null
1. in /var/www/x.war.fish/protected/vendor/yiisoft/yii2/helpers/BaseFormatConverter.php at line 329
320321322323324325326327328329330331332333334335336337338                    $locale = Yii::$app->language;
                }
                if ($type === 'date') {
                    $formatter = new IntlDateFormatter($locale, self::$_icuShortFormats[$pattern], IntlDateFormatter::NONE);
                } elseif ($type === 'time') {
                    $formatter = new IntlDateFormatter($locale, IntlDateFormatter::NONE, self::$_icuShortFormats[$pattern]);
                } else {
                    $formatter = new IntlDateFormatter($locale, self::$_icuShortFormats[$pattern], self::$_icuShortFormats[$pattern]);
                }
                $pattern = $formatter->getPattern();
            } else {
                return static::$juiFallbackDatePatterns[$pattern][$type];
            }
        }
        // http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax
        // escaped text
        $escaped = [];
        if (preg_match_all('/(?<!\')\'.*?[^\']\'(?!\')/', $pattern, $matches)) {
            foreach ($matches[0] as $match) {
2. yii\base\ErrorHandler::handleFatalError()

```

**Comment by devcline** [comment]
Today upgraded my php to a new version, and  i connect to my humhub and there was a same error.
I have no clue because the date.timezone = Europe/Berlin line in php.ini was uncommented.
So i comment it and everything back to normal. strange.

here is a log:
`exception 'yii\base\InvalidConfigException' with message 'datefmt_create: no such time zone: 'UTC': U_ILLEGAL_ARGUMENT_ERROR' in /var/www/protected/vendor/yiisoft/yii2/i18n/Formatter.php:618 Stack trace: #0 /var/www/protected/vendor/yiisoft/yii2/i18n/Formatter.php(493): yii\i18n\Formatter->formatDateTimeValue(Object(DateTime), 'medium', 'date') #1 /var/www/protected/modules/calendar/models/CalendarDateFormatter.php(48): yii\i18n\Formatter->asDate(Object(DateTime), 'medium') #2 /var/www/protected/modules/calendar/models/CalendarDateFormatter.php(119): humhub\modules\calendar\models\CalendarDateFormatter->getFormattedStartDate('medium', 'UTC') #3 /var/www/protected/modules/calendar/models/CalendarDateFormatter.php(36): humhub\modules\calendar\models\CalendarDateFormatter->getFormattedAllDay('medium') #4 /var/www/protected/modules/calendar/widgets/views/upcomingEvents.php(37): humhub\modules\calendar\models\CalendarDateFormatter->getFormattedTime('medium') #5 /var/www/protected/vendor/yiisoft/yii2/base/View.php(330): require('/var/www/....') #6 /var/www/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/....', Array) #7 /var/www/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/var/www/....', Array, Object(humhub\modules\calendar\widgets\UpcomingEvents)) #8 /var/www/protected/vendor/yiisoft/yii2/base/Widget.php(234): yii\base\View->render('upcomingEvents', Array, Object(humhub\modules\calendar\widgets\UpcomingEvents)) #9 /var/www/protected/modules/calendar/widgets/UpcomingEvents.php(48): yii\base\Widget->render('upcomingEvents', Array) #10 /var/www/protected/humhub/components/Widget.php(57): humhub\modules\calendar\widgets\UpcomingEvents->run() #11 /var/www/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array) #12 /var/www/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\BaseStack->run() #13 /var/www/protected/humhub/modules/dashboard/views/dashboard/index.php(27): yii\base\Widget::widget(Array) #14 /var/www/protected/vendor/yiisoft/yii2/base/View.php(330): require('/var/www/....') #15 /var/www/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/....', Array) #16 /var/www/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/var/www/....', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #17 /var/www/protected/vendor/yiisoft/yii2/base/Controller.php(381): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #18 /var/www/protected/humhub/modules/dashboard/controllers/DashboardController.php(63): yii\base\Controller->render('index', Array) #19 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #20 /var/www/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #21 /var/www/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #22 /var/www/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array) #23 /var/www/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('dashboard/dashb...', Array) #24 /var/www/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #25 /var/www/index.php(25): yii\base\Application->run() #26 {main}`

**Comment by devcline** [comment]
this issue still appears sometimes... 
`  "message": "datefmt_create: no such time zone: 'Europe/Paris': U_ILLEGAL_ARGUMENT_ERROR",`

**Comment by buddh4** [comment]
Don't know if it makes any difference but did you try:

```
date.timezone = "Europe/Berlin"
```

**Comment by diego22100** [comment]
Hi, i had the same problem, i searched an issue and finally found it :

I am in France, when i am adding a post, i saw the post date with -6 hours.

So i have configured my timezone in my server (UTC+2 Europe/Paris) and for humhub i have choosen (UTC-4 - America/Detroit) and now it works for me; post dates are correct !

To find UTC that you must choose, you must do it : 

- put the UTC of your official timezone (for me **UTC+2** Paris) in your server 
- AND YOU HAVE TO SUSTRACT the time that you see on post date (for me it was **-6 hours**),
- so **UTC+2**  -   **UTC -6**
- so you must choose an UTC with -4 in Humhub choices

Hope that you have understand, i thin it will help you !
