### ISSUE TITLE
Birthday date picker does not allow to set birthday more than 80 years ago

### ISSUE THREAD

**Issue by enguerrand** [humhub/humhub#2848]
### What steps will reproduce the problem?
In the profile edit view, try to set a birthday more than 80 years ago through the date picker and hit "save".

### What is the expected result?
That the birthday is set to the chosen date.

### What do you get instead?
An error message next to the birthday field that states that the birthday must be before today and the current value set to the current date.

### Additional info
The problem can be worked around by manually entering the full year into the input field (e.g. 1936)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.2
| PHP version      | 7.0
| Operating system | Server: Debian Stretch: Client: Arch Linux with firefox 57

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by enguerrand** [comment]
Additional info: This issue can also be worked around by using the custom date display format in the admin settings. (Which leads to the date being entered as in the workaround mentioned before)

**Comment by Felli** [comment]
A known workaround for this would be just using full year format `05/12/1918` or `05/12/2018` to differentiate between the years used from the past to the years in the future.

**Comment by danielkesselberg** [comment]
@Felli @enguerrand is this issue fixed?

**Comment by Felli** [comment]
For me, yes. :smile:

**Comment by enguerrand** [comment]
Sorry, did not get the chance to look into this earlier. I just tested in version 1.2.4 using the default date format and the problem still occurs. For me personally the workaround to use a different date format ist fine though.

**Comment by danielkesselberg** [comment]
@buddh4 @enguerrand patch for this issue has been merged to 1.3-dev branch (https://github.com/humhub/humhub/pull/2881). Issue should be close.
