### ISSUE TITLE
Mpg / mpeg no longer embedded in v 1.2.3

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2850]
### What steps will reproduce the problem?
Upload a mpeg movie
### What is the expected result?
Embedded movie
### What do you get instead?
File icon
### Additional info

Tested on local and on community installs

Screenshot 1 v.1.2.1
Screenshot 2 v.1.2.3

![screenshot_2017-12-09-15-16-09](https://user-images.githubusercontent.com/6781157/33796466-1c4f88b4-dcf5-11e7-859c-a57cf2a2bf65.png)
![screenshot_2017-12-09-15-12-31](https://user-images.githubusercontent.com/6781157/33796468-2737138c-dcf5-11e7-83ef-f9a5fbea40cb.png)

Any idea how to get my mpg's back?

Martin

**Comment by buddh4** [comment]
Has there ever been mpg support by default? I remember you've overwritten the preview view in your theme? Also I think it depends on the browser if they are able to embed mpg videos.

**Comment by martinbeek** [comment]
Mmmmm.... you might be correct there... I'll check my own documentation ;-)
