### ISSUE TITLE
UserPickerField don't support array attribute in model 

### ISSUE THREAD

**Issue by KonstantinZhidkovskiy** [humhub/humhub#2851]
### What steps will reproduce the problem?
Try to use the model with array attribute which indexed:  
```
    <?= humhub\modules\user\widgets\UserPickerField::widget([
        'model' => $model,
        'attribute' => "assignedUsers[$index]",
        'maxSelection' => 5,
        'maxInput' => 30
    ]) ?>
```
### What is the expected result?
Multiple UserPickerField fields for model attribute which could be indexed

### What do you get instead?
Exception:  Unknown Property – yii\base\UnknownPropertyException

### Additional info
| HumHub version   | 1.2.3
| PHP version      | 7.0.8

**Comment by Felli** [comment]
I would suggest using the devtools module to better understand how to use the UserPickerField.

**Comment by KonstantinZhidkovskiy** [comment]
Thanks, @Felli!  I debugged a bit and this bug on the back-end in BasePickerField.php.
