### ISSUE TITLE
Upload file for only Images

### ISSUE THREAD

**Issue by byndstd** [humhub/humhub#2853]
I'm trying to create an other button for upload only images so I can have two buttons one for files and the other one for images, but i don't understand how to upload file work bouth buttons upload imaes and all extension i set on admin I did create a new model "FileUpload.php" I call it "FileUploadPhoto.php"
and a new action call it "UploadActionPhoto.php", and I add to controller this line 
"'uploadgallery' => [
                'class' => UploadActionGallery::className(),
            ],"
but what I want is the photo button check 1st if the file is jpg or png if not don't upload I don't know how to use FileValidator.php with the 2nd button for that to see if is image will upload else don't upload
I don't want to use gallery module it show every image as post, and also don't count gallery as post.

**Comment by Felli** [comment]
Why not just only allow `.img-filetype` from the ACP?

**Comment by byndstd** [comment]
ACP ?

**Comment by Felli** [comment]
ACP stands for Admin Control Panel. :smile:

**Comment by byndstd** [comment]
if you mean Admin Control Panel, I'm on localhost, 
what I want to do is to have two buttons one for files (audio and video ) and one for galleries so if someone upload photo he clique on photo button , if he want to upload video or audio click on file button. because file button allow only one file to be uploaded , but photo button allow more than one photo to be uploaded, like that user can't upload bunch of video at the same time.
https://image.ibb.co/hoFnnw/index.png
so how can the gallery button validate extention befor upload

**Comment by Felli** [comment]
I'm still not exactly sure what you're wanting, but the following `/protected/humhub/modules/file/validators/FileValidator.php` looks to be what you're looking for?

**Comment by byndstd** [comment]
how to use FileValidator with gallery button so if gallery will accept only image file if file will accept only audio and video, I'm trying but I didn't can't find how to do it, to validate extension if is gallery button

**Comment by byndstd** [comment]
I don't know how the file input use uploadAction, because if I allow user upload files he can upload many videos at once, or audio
