### ISSUE TITLE
Lack of Administrator Control? WTF?

### ISSUE THREAD

**Issue by BDSM-Master** [humhub/humhub#2871]
Can someone tell me why Administrators can not delete another members Space page?

**Comment by githubjeka** [comment]
Can't reproduce your problem

**Comment by BDSM-Master** [comment]
That was pretty self explanatory. An administrator is not allowed to delete space page created by another user. So if you use humhub and have pages created by someone else, go try to delete it and you will see exactly what I am referring to. To add insult to injury if you "become that member", you still still need that persons password to delete the page. Why would someone program something so stupid?

**Comment by Felli** [comment]
I'd say it's a fallback in case of admin power abuse, or those that have the permissions, although this is already a known thing and is on the list of things to enhance/fix.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/2721

Currently you need to use the "become user" feature to delete the space as the owner.

**Comment by BDSM-Master** [comment]
Wow, re-read what I said!  You need the users password if you become the user. Furthermore I don't care about admin abuse. I am and will be the admin and I'm not going to have abusive members keep things out of my control given that I am the owner.

**Comment by luke-** [comment]
Oh yes sorry. 

Currently, the only option is to transfer the space owner ship to your admin user and then delete the space.

**Comment by BDSM-Master** [comment]
Hey, now we are cooking. If there are any humhub developers in here, I would seriously consider fixing that. And creating a multiple relationship plugin.
