### ISSUE TITLE
Summary emails not working

### ISSUE THREAD

**Issue by woodl3y** [humhub/humhub#2874]
### What steps will reproduce the problem?
The summary e-mails (daily or hourly) never send, there is no log to indicate any error, and they are not in the spam folder in any user's mailboxes.  Interestingly the other notification emails **do work properly** (e.g. received a new message, someone posted in a space).
Also tried running the cron jobs directly, and they work successfully however this is no mention of any email related tasks being run

e.g.
![image](https://user-images.githubusercontent.com/4141825/34459721-838c880c-ee4c-11e7-82b5-0566d1d53284.png)

### What is the expected result?
Summary emails are delivered as configured (hourly or daily etc.)

### What do you get instead?
No summary emails.

### Additional info
PHP version: 7.1
HumHub version: 1.2.4
Ubuntu: Ubuntu 17.10
Apache: 2.4.27
MySQL version: 10.1.25-MariaDB-1
Chrome version: 63.0.3239.108

**Comment by Felli** [comment]
That's very interesting, although I'm not having this issue myself, I'd like to have you do some [Troubleshooting](https://github.com/buddh4/humhub-docs/blob/master/admin/troubleshooting.md#cron-job-setup) and I can give you a link to the remodeled [Docs](https://github.com/buddh4/humhub-docs/blob/master/admin/cron-jobs.md) where there are some examples.

**Comment by woodl3y** [comment]
Thanks for replying, I've read through the links you provided but I can't see anything that helps. My cron jobs are running properly, here's how they're configured:

```
sudo -u www-data crontab -e

30 * * * * /var/www/html/humhub/protected/yii cron/hourly > /dev/null 2>&1
00 18 * * * /var/www/html/humhub/protected/yii cron/daily > /dev/null 2>&1
```

cron status within humhub (note that I ran the jobs manually again just a few minutes ago)
![image](https://user-images.githubusercontent.com/4141825/34465095-ba1a1866-eef2-11e7-828e-f63f095e479d.png)

Let me know if there's anything else I can provide.  Also this is running on a Digital Ocean droplet if that helps at all.

Thank you

**Comment by acs-ferreira** [comment]
Remember that "These settings can be overwritten by users in their account settings page. "

What do you have in your profile?
