### ISSUE TITLE
Directory : "Show all members" of a specific group show less members than expected

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#2877]
### What steps will reproduce the problem?

1. Go to https://community.humhub.com/directory/directory/groups and click the button "show all members"
2. Go to the last page : ![image](https://user-images.githubusercontent.com/23310825/34466507-43559e92-eed6-11e7-8175-fb4aae28bc0f.png)
3. Look at the page number (today : 287)
4. Go to https://community.humhub.com/directory/members and go to the last page
5. Look at the page number (today : 315)

This problem occurs also in 2 platforms I have installed to.

### What is the expected result?

There is a different of 28 pages, so more or less 700 members. As all users are member of the `Users` group (except the 9 persons of the team), there should be the same number of pages.

### What do you get instead?

For example, instead of 57 members, I have only 16 showing...

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 7
| Operating system | Ubuntu 16.04

**Comment by Felli** [comment]
I think that the search index needs to be rebuilt is all, easy fix. :+1:

**Comment by funkycram** [comment]
Great ! It worked !! Thanks for your quick reply.
Do you advise to rebuild the search index every weeks for example with a cron ?

**Comment by Felli** [comment]
I'll speak to the core devs to see if it would be possible to do this through Cron (Which would be a great idea!) but at this time a weekly rebuild for large communities would be advised. :smile:
