### ISSUE TITLE
How to remove Calendar from menu bar?

### ISSUE THREAD

**Issue by BDSM-Master** [humhub/humhub#2878]
I have relocated the calendar link to the drop down menu, but I can not seem to remove it from the main menu bar. What file can I edit to remove calendar from the main menu bar?

**Comment by Felli** [comment]
I believe you'd need to remove this function without trying to get any error(s).

Starting [line 18](https://github.com/humhub/humhub-modules-calendar/blob/master/Events.php#L18) to ending [line 29](https://github.com/humhub/humhub-modules-calendar/blob/master/Events.php#L29)
```
    public static function onTopMenuInit($event)
    {
        if (SnippetModuleSettings::instantiate()->showGlobalCalendarItems()) {
            $event->sender->addItem([
                'label' => Yii::t('CalendarModule.base', 'Calendar'),
                'url' => Url::to(['/calendar/global/index']),
                'icon' => '<i class="fa fa-calendar"></i>',
                'isActive' => (Yii::$app->controller->module && Yii::$app->controller->module->id == 'calendar' && Yii::$app->controller->id == 'global'),
                'sortOrder' => 300,
            ]);
        }
    }
```

**Comment by BDSM-Master** [comment]
And what file would this code be in?

**Comment by Felli** [comment]
The `Events.php` file included in every calendar module install.

**Comment by BDSM-Master** [comment]
That unfortunately killed the entire site, modifying or removing. Next suggestion?

**Comment by Felli** [comment]
That would be the only suggestion that I can give as that is the core function that controls the display of the menu item. :frowning:

**Comment by BDSM-Master** [comment]
Why am I having to edit individual files to alter the main menu bar? Why isn't there a single menu.php that contains all the menu items that can be removed and re-arranged at the users discretion?

**Comment by danielkesselberg** [comment]
I have another suggestion for you: 

Search for `return !self::instantiate()->showIfInstalled || (!Yii::$app->user->isGuest && Yii::$app->user->getIdentity()->isModuleEnabled('calendar'));` in SnippetModuleSettings.php and replace the whole line with `return false;`

**Comment by githubjeka** [comment]
> Starting line 18 to ending line 29

No right, Felli. ;)  

Starting line 21 to ending line 27

**Comment by Felli** [comment]
Removing anything from those lines still breaks site but as you said those are the lines needed removed @githubjeka :+1:

**Comment by BDSM-Master** [comment]
@danielkesselberg Would you happen to know the path of that file? I am still baffled that people have to jump through so many hoops to do something so simple.

**Comment by danielkesselberg** [comment]
protected/modules/calendar/models/SnippetModuleSettings.php

**Comment by BDSM-Master** [comment]
@Felli I want to thank you. You have given me half of the answer to my problem. I was able to remove calendar and messages off the menu bar with what you gave me only in a different manner.
Here is what I have done. I took what you gave me and did not remove the core coding, but I did remove the name, url and changed the sort number. It made the menu link disappear, but did not affect the function. So Thank YOU! I did the same to Messages from the events.php file.

public static function onTopMenuInit($event)
    {
        if (SnippetModuleSettings::instantiate()->showGlobalCalendarItems()) {
            $event->sender->addItem([
                'label' => Yii::t('CalendarModule.base', ''), /*Calendar*/
                'url' => Url::to(['']),/*/calendar/global/index*/
                'isActive' => (Yii::$app->controller->module && Yii::$app->controller->module->id == '' && Yii::$app->controller->id == 'global'),/*id == 'calendar'*/
                'sortOrder' => 1800, /*300*/
            ]);
        }
    }

**Comment by Felli** [comment]
@BDSM-Master just take note that once an update is available for the Calendar module and you update it, it will require being changed again because your changes are overwritten by the update. :smile:

**Comment by BDSM-Master** [comment]
Not worried about the update. I have implemented an override file that will not be affected by any update.
But thanks for info.

**Comment by codiflow** [comment]
If you just want to remove the calendar from the navbar for guest users you can simply replace [this line](https://github.com/humhub/calendar/blob/6b29ceccb15a0499ffc10d5d0d48bd11a35bff12/models/SnippetModuleSettings.php#L77):
```php
return !self::instantiate()->showIfInstalled || (!Yii::$app->user->isGuest && Yii::$app->user->getIdentity()->moduleManager->isEnabled('calendar'));
```

with this:
```php
return (!Yii::$app->user->isGuest) ? (!self::instantiate()->showIfInstalled || (!Yii::$app->user->isGuest && Yii::$app->user->getIdentity()->moduleManager->isEnabled('calendar'))) : false;
```

But this modification is **NOT update proof**.

**Comment by marc-farre** [comment]
@codiflow Other options:
- Administration -> Modules -> Calendar -> Snippet -> uncheck "Only show top menu item and snippet if the module is installed in the users profile"
- https://marketplace.humhub.com/module/menu-manager/description

**Comment by codiflow** [comment]
@marc-farre Thanks for pointing those options out. Especially your free menu manager module sounds like a good solution. The other option is not an option for me because I cannot guarantee that all users have the calendar activated in their profile. So some would see the option and others won't. This would confuse registered users too much in my case.
