### ISSUE TITLE
Packageinstaller\Module' not found

### ISSUE THREAD

**Issue by swapnil2sutar** [humhub/humhub#2879]
### What steps will reproduce the problem?
I am trying to migrate my files from shared host to VPS, While migration I have checked system requirements & installed necessary. After configuring Database & User I am seeing an error. I have attached screenshots for the same.   
### What is the expected result?
I am expecting to work old setup as it is on new host

### What do you get instead?
I am receiving an error `call_user_func() expects parameter 1 to be a valid callback, class 'humhub\modules\updater\modules\packageinstaller\Module' not found
`
### Additional info
![instation_error](https://user-images.githubusercontent.com/16332853/34467658-e688f590-ef1d-11e7-8430-03681bdc6478.png)
![installation_error2](https://user-images.githubusercontent.com/16332853/34467660-eb2de650-ef1d-11e7-9afd-8da09495c845.png)
| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
Please ask such questions in the [Community](https://community.humhub.com), perhaps you have to update your updater module.
