### ISSUE TITLE
Notification written in white on white

### ISSUE THREAD

**Issue by xilmen** [humhub/humhub#2882]
Hello everybody,

That's my problem ...
I have my notifications that are written in white on white ... see the screens shot (test on firefox and google chrome)

![s-hum2](https://user-images.githubusercontent.com/14809093/34504581-a84d647a-f01f-11e7-8290-1ef3250df0ee.jpg)
![s-hum1](https://user-images.githubusercontent.com/14809093/34504580-a833182c-f01f-11e7-93ad-0852944b8615.jpg)

### What steps will reproduce the problem?
As soon as I have a notification

| HumHub version   | 1.2.3
| PHP version :
php56w-5.6.31-2.w7.x86_64
php56w-intl-5.6.31-2.w7.x86_64
php-php-gettext-1.0.12-1.el7.noarch
php56w-common-5.6.31-2.w7.x86_64
php56w-xml-5.6.31-2.w7.x86_64
php56w-process-5.6.31-2.w7.x86_64
php-fedora-autoloader-1.0.0-1.el7.noarch
php56w-gd-5.6.31-2.w7.x86_64
php56w-mbstring-5.6.31-2.w7.x86_64
php56w-pdo-5.6.31-2.w7.x86_64
php56w-bcmath-5.6.31-2.w7.x86_64
php56w-tidy-5.6.31-2.w7.x86_64
php-tcpdf-6.2.13-1.el7.noarch
php56w-opcache-5.6.31-2.w7.x86_64
php56w-ldap-5.6.31-2.w7.x86_64
php56w-cli-5.6.31-2.w7.x86_64
php56w-mysqlnd-5.6.31-2.w7.x86_64
php-tcpdf-dejavu-sans-fonts-6.2.13-1.el7.noarch

| Operating system | CentOS 7 

stack trace firefox :
Failed to load for <script> element whose source is "https: //url.local/site/assets/f5508126/ui/minified/widget.js? V = 1.2.4 ".

Thank you for this project!
Thanks in advance :)

**Comment by Felli** [comment]
Are you using any external scripts or modules that use external scripts?

**Comment by BDSM-Master** [comment]
Or change the color of the notification background in the css file.
-------
FIND THE FOLLOWING
.dropdown-menu {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 160px;
    padding: 5px 0;
        padding-top: 5px;
        padding-bottom: 5px;
    padding-top: 5px;
    padding-bottom: 5px;
    margin: 2px 0 0;
        margin-left: 0px;
    font-size: 14px;
    text-align: left;
    list-style: none;
    background-color: #fff;  <---- (CHANGE THIS TO ANOTHER COLOR, I USE #000 which is black)
    -webkit-background-clip: padding-box;
    background-clip: padding-box;
    border: 1px solid #ccc;
    border: 1px solid rgba(0, 0, 0, .15);
    border-radius: 1px;
    -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, .175);
    box-shadow: 0 6px 12px rgba(0, 0, 0, .175);
}

**Comment by Felli** [comment]
@BDSM-Master humhub uses the LESS approach in 1.2+ now so it's recommended to do this within you `themes/YOUR_THEME/less/variables.less` for changing the colors.

**Comment by xilmen** [comment]
i dont use external script, and i dont use theme. the changes i made is the max_execution_time / memory_limit / post_max_size / upload_max_filesize / max_file_uploads from php.ini but à need tu upload lot of picture on same time.

if you need other log, ask me :)

**Comment by xilmen** [comment]
I backup and reinstall all humhub ... this solved my problem. Thanks anyway :)
