### ISSUE TITLE
errors on fresh install

### ISSUE THREAD

**Issue by awsmthx** [humhub/humhub#2883]
### What steps will reproduce the problem?
when i try to change server mail settings i get:

An Error occurred while handling another error:
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php:915
Stack trace:
#0 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php(915): PDOStatement->execute()
#1 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php(376): yii\db\Command->queryInternal('fetch', NULL)
#2 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Query.php(253): yii\db\Command->queryOne()
#3 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(294): yii\db\Query->one(NULL)
#4 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/ActiveRelationTrait.php(158): yii\db\ActiveQuery->one()
#5 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(287): yii\db\ActiveQuery->findFor('profile', Object(humhub\modules\user\models\User))
#6 /home/u#######/public_html/portal/protected/humhub/modules/user/models/User.php(150): yii\db\BaseActiveRecord->__get('profile')
#7 /home/u#######/public_html/portal/protected/humhub/modules/user/models/User.php(477): humhub\modules\user\models\User->__get('profile')
#8 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/Component.php(132): humhub\modules\user\models\User->getDisplayName()
#9 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(285): yii\base\Component->__get('displayName')
#10 /home/u#######/public_html/portal/protected/humhub/modules/user/models/User.php(158): yii\db\BaseActiveRecord->__get('displayName')
#11 /home/u#######/public_html/portal/protected/humhub/modules/user/models/UserPicker.php(152): humhub\modules\user\models\User->__get('displayName')
#12 /home/u#######/public_html/portal/protected/humhub/modules/user/models/UserPicker.php(124): humhub\modules\user\models\UserPicker::createJSONUserInfo(Object(humhub\modules\user\models\User), NULL, NULL, NULL)
#13 /home/u#######/public_html/portal/protected/humhub/widgets/CoreJsConfig.php(27): humhub\modules\user\models\UserPicker::asJSON(Object(humhub\modules\user\models\User))
#14 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\CoreJsConfig->run()
#15 /home/u#######/public_html/portal/protected/humhub/components/View.php(248): yii\base\Widget::widget()
#16 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/views/errorHandler/exception.php(451): humhub\components\View->endBody()
#17 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/View.php(330): require('/home/u14993787...')
#18 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/u14993787...', Array)
#19 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(249): yii\base\View->renderFile('/home/u14993787...', Array, Object(yii\web\ErrorHandler))
#20 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(115): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#21 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\db\Exception))
#22 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#23 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
The SQL being executed was: SELECT * FROM `profile` WHERE `user_id`=1 in /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Schema.php:636
Stack trace:
#0 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php(930): yii\db\Schema->convertException(Object(PDOException), 'SELECT * FROM `...')
#1 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php(376): yii\db\Command->queryInternal('fetch', NULL)
#2 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Query.php(253): yii\db\Command->queryOne()
#3 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(294): yii\db\Query->one(NULL)
#4 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/ActiveRelationTrait.php(158): yii\db\ActiveQuery->one()
#5 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(287): yii\db\ActiveQuery->findFor('profile', Object(humhub\modules\user\models\User))
#6 /home/u#######/public_html/portal/protected/humhub/modules/user/models/User.php(150): yii\db\BaseActiveRecord->__get('profile')
#7 /home/u#######/public_html/portal/protected/humhub/modules/user/models/User.php(477): humhub\modules\user\models\User->__get('profile')
#8 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/Component.php(132): humhub\modules\user\models\User->getDisplayName()
#9 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(285): yii\base\Component->__get('displayName')
#10 /home/u#######/public_html/portal/protected/humhub/modules/user/models/User.php(158): yii\db\BaseActiveRecord->__get('displayName')
#11 /home/u#######/public_html/portal/protected/humhub/modules/user/models/UserPicker.php(152): humhub\modules\user\models\User->__get('displayName')
#12 /home/u#######/public_html/portal/protected/humhub/modules/user/models/UserPicker.php(124): humhub\modules\user\models\UserPicker::createJSONUserInfo(Object(humhub\modules\user\models\User), NULL, NULL, NULL)
#13 /home/u#######/public_html/portal/protected/humhub/widgets/CoreJsConfig.php(27): humhub\modules\user\models\UserPicker::asJSON(Object(humhub\modules\user\models\User))
#14 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/Widget.php(139): humhub\widgets\CoreJsConfig->run()
#15 /home/u#######/public_html/portal/protected/humhub/components/View.php(248): yii\base\Widget::widget()
#16 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/views/errorHandler/exception.php(451): humhub\components\View->endBody()
#17 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/View.php(330): require('/home/u14993787...')
#18 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/u14993787...', Array)
#19 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(249): yii\base\View->renderFile('/home/u14993787...', Array, Object(yii\web\ErrorHandler))
#20 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(115): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#21 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\db\Exception))
#22 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#23 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 2006
    [2] => MySQL server has gone away
)

Previous exception:
yii\base\ErrorException: PDOStatement::execute(): MySQL server has gone away in /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php:915
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'PDOStatement::e...', '/home/u14993787...', 915, Array)
#1 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php(915): PDOStatement->execute()
#2 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php(376): yii\db\Command->queryInternal('fetch', NULL)
#3 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Query.php(253): yii\db\Command->queryOne()
#4 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(294): yii\db\Query->one(NULL)
#5 /home/u#######/public_html/portal/protected/humhub/libs/BaseSettingsManager.php(67): yii\db\ActiveQuery->one()
#6 /home/u#######/public_html/portal/protected/humhub/components/Theme.php(175): humhub\libs\BaseSettingsManager->set('colorDefault', '#ededed')
#7 /home/u#######/public_html/portal/protected/humhub/components/Theme.php(84): humhub\components\Theme->storeColorsToConfig()
#8 /home/u#######/public_html/portal/protected/humhub/libs/ThemeHelper.php(110): humhub\components\Theme->beforeActivate()
#9 /home/u#######/public_html/portal/protected/humhub/libs/DynamicConfig.php(169): humhub\libs\ThemeHelper::getThemeConfig(Object(humhub\components\Theme))
#10 /home/u#######/public_html/portal/protected/humhub/modules/admin/models/forms/MailingSettingsForm.php(99): humhub\libs\DynamicConfig::rewrite()
#11 /home/u#######/public_html/portal/protected/humhub/modules/admin/controllers/SettingController.php(162): humhub\modules\admin\models\forms\MailingSettingsForm->save()
#12 [internal function]: humhub\modules\admin\controllers\SettingController->actionMailingServer()
#13 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#15 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('mailing-server', Array)
#16 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/setting/m...', Array)
#17 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#18 /home/u#######/public_html/portal/index.php(25): yii\base\Application->run()
#19 {main}

Next yii\db\Exception: PDOStatement::execute(): MySQL server has gone away
The SQL being executed was: SELECT * FROM `setting` WHERE (`module_id`='base') AND (`name`='colorDefault') in /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Schema.php:636
Stack trace:
#0 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php(930): yii\db\Schema->convertException(Object(yii\base\ErrorException), 'SELECT * FROM `...')
#1 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php(376): yii\db\Command->queryInternal('fetch', NULL)
#2 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Query.php(253): yii\db\Command->queryOne()
#3 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(294): yii\db\Query->one(NULL)
#4 /home/u#######/public_html/portal/protected/humhub/libs/BaseSettingsManager.php(67): yii\db\ActiveQuery->one()
#5 /home/u#######/public_html/portal/protected/humhub/components/Theme.php(175): humhub\libs\BaseSettingsManager->set('colorDefault', '#ededed')
#6 /home/u#######/public_html/portal/protected/humhub/components/Theme.php(84): humhub\components\Theme->storeColorsToConfig()
#7 /home/u#######/public_html/portal/protected/humhub/libs/ThemeHelper.php(110): humhub\components\Theme->beforeActivate()
#8 /home/u#######/public_html/portal/protected/humhub/libs/DynamicConfig.php(169): humhub\libs\ThemeHelper::getThemeConfig(Object(humhub\components\Theme))
#9 /home/u#######/public_html/portal/protected/humhub/modules/admin/models/forms/MailingSettingsForm.php(99): humhub\libs\DynamicConfig::rewrite()
#10 /home/u#######/public_html/portal/protected/humhub/modules/admin/controllers/SettingController.php(162): humhub\modules\admin\models\forms\MailingSettingsForm->save()
#11 [internal function]: humhub\modules\admin\controllers\SettingController->actionMailingServer()
#12 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#14 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('mailing-server', Array)
#15 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('admin/setting/m...', Array)
#16 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#17 /home/u#######/public_html/portal/index.php(25): yii\base\Application->run()
#18 {main}
Additional Information:
Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away The SQL being executed was: SELECT `id` FROM `user_http_session` WHERE `id`='t85tjqhahqjl8ngq277gte6od1'' in /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Schema.php:636 Stack trace: #0 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php(930): yii\db\Schema->convertException(Object(PDOException), 'SELECT `id` FRO...') #1 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/db/Command.php(388): yii\db\Command->queryInternal('fetchColumn', 0) #2 /home/u#######/public_html/portal/protected/humhub/modules/user/components/Session.php(56): yii\db\Command->queryScalar() #3 [internal function]: humhub\modules\user\components\Session->writeSession('t85tjqhahqjl8ng...', '__flash|a:0:{}_...') #4 /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/web/Session.php(187): session_write_close() #5 [internal function]: yii\web\Session->close() #6 {main}
Warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/tmp) in /home/u#######/public_html/portal/protected/vendor/yiisoft/yii2/web/Session.php on line 187

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by danielkesselberg** [comment]
Hey, this issue is related to your server/webhosting. The error "MySQL server has gone away" means that the connection to the MySQL server interrupts. You may talk to your webhosting company.

**Comment by awsmthx** [comment]
thanks - seems to be the case
i now installed it on my synology ds and here it works
therefore i get errormessage on cronjobs:

    [0] => Exception 'yii\db\Exception' with message 'could not find driver'
    [1] => 
    [2] => in /volume1/web/portal/protected/vendor/yiisoft/yii2/db/Connection.php:584
    [3] => 
    [4] => Stack trace:
    [5] => #0 /volume1/web/portal/protected/vendor/yiisoft/yii2/db/Connection.php(928): yii\db\Connection->open()
    [6] => #1 /volume1/web/portal/protected/vendor/yiisoft/yii2/db/Connection.php(915): yii\db\Connection->getMasterPdo()
    [7] => #2 /volume1/web/portal/protected/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
    [8] => #3 /volume1/web/portal/protected/vendor/yiisoft/yii2/db/Command.php(910): yii\db\Command->prepare(true)
    [9] => #4 /volume1/web/portal/protected/vendor/yiisoft/yii2/db/Command.php(405): yii\db\Command->queryInternal('fetchAll', 7)
    [10] => #5 /volume1/web/portal/protected/vendor/yiisoft/yii2/db/mysql/Schema.php(352): yii\db\Command->queryColumn()
    [11] => #6 /volume1/web/portal/protected/vendor/yiisoft/yii2/db/Schema.php(234): yii\db\mysql\Schema->findTableNames('')
    [12] => #7 /volume1/web/portal/protected/humhub/components/console/Application.php(87): yii\db\Schema->getTableNames()
    [13] => #8 /volume1/web/portal/protected/humhub/components/ModuleManager.php(70): humhub\components\console\Application->isDatabaseInstalled()
    [14] => #9 /volume1/web/portal/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\components\ModuleManager->init()
    [15] => #10 [internal function]: yii\base\Object->__construct(Array)
    [16] => #11 /volume1/web/portal/protected/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array)
    [17] => #12 /volume1/web/portal/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('\\humhub\\compone...', Array, Array)
    [18] => #13 /volume1/web/portal/protected/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('\\humhub\\compone...', Array, Array)
    [19] => #14 /volume1/web/portal/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(135): yii\BaseYii::createObject(Array)
    [20] => #15 /volume1/web/portal/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(73): yii\di\ServiceLocator->get('moduleManager')
    [21] => #16 /volume1/web/portal/protected/humhub/components/bootstrap/ModuleAutoLoader.php(51): yii\di\ServiceLocator->__get('moduleManager')
    [22] => #17 /volume1/web/portal/protected/vendor/yiisoft/yii2/base/Application.php(320): humhub\components\bootstrap\ModuleAutoLoader->bootstrap(Object(humhub\components\console\Application))
    [23] => #18 /volume1/web/portal/protected/vendor/yiisoft/yii2/base/Application.php(272): yii\base\Application->bootstrap()
    [24] => #19 /volume1/web/portal/protected/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
    [25] => #20 /volume1/web/portal/protected/humhub/components/console/Application.php(35): yii\console\Application->init()
    [26] => #21 /volume1/web/portal/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\components\console\Application->init()
    [27] => #22 /volume1/web/portal/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
    [28] => #23 /volume1/web/portal/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
    [29] => #24 /volume1/web/portal/protected/yii(28): yii\console\Application->__construct(Array)
    [30] => #25 {main}

**Comment by githubjeka** [comment]
> could not find driver
Add `php-mysql` extension on your server

**Comment by buddh4** [comment]
> Note: Please use the [community](https://community.humhub.com) site for any questions of this kind.
