### ISSUE TITLE
composer.json of branch master outdated

### ISSUE THREAD

**Issue by lweddewer** [humhub/humhub#2887]
### What steps will reproduce the problem?

Starting with this Commit into the master branch the composer.json has some outdated Entries.
2017-12-22 13:49:00 | 8343681 | Lucas Bartholemy <lucas@bartholemy.com> | Revert "Merge branch 'v1.3-dev' into master"Mehr>>
-- | -- | -- | --

A  composer update brings following error:

The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.                               

  Problem 1
    - The requested package bower-asset/jquery-timeago 1.4.* exists as bower-asset/jquery-timeago[v1.5.4] but these are rejected by your constraint.
  Problem 2
    - The requested package bower-asset/blueimp-file-upload 9.11.* exists as bower-asset/blueimp-file-upload[v9.18.0, 9.19.2] but these are rejected by your constraint.
  Problem 3
    - The requested package bower-asset/at.js could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

When I switch to branch "v1.3-dev" anything works fine.

### What is the expected result?
The cloned master branch works as expected.

### What do you get instead?
Due to missing packages the master branch crashes:

    1. in /var/www/vhosts/feuerwehr-mb.de/community/protected/humhub/components/queue/driver/Sync.php at line 24
    15161718192021222324252627282930313233

    use zhuravljov\yii\queue\ErrorEvent;
    use zhuravljov\yii\queue\Queue;
     
    /**
     * Sync queue driver
     *
     * @since 1.2
     * @author Luke
     */
    class Sync extends Queue
    {
     
        /**
         * @var boolean
         */
        public $handle = true;
     
        /**
         * @var array

    2. yii\base\ErrorHandler::handleFatalError()

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4 (git branch master)
| PHP version   | 7.0.24 and 7.1.12  | 
| Operating system | Ubuntu 16.04|

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

Repards
Lothar

**Comment by githubjeka** [comment]
Confirm

[I asked about this commit "Merge branch 'v1.3-dev"](https://github.com/humhub/humhub/commit/834368140af6359eeb075b96127477c4339059d6#commitcomment-26636322), but don't get reply :(

Many corrected commits are lost and revert by "Merge branch 'v1.3-dev".

**Comment by luke-** [comment]
@githubjeka sorry I answered by email and somehow it didn't work.

 I've accidentally merged the v1.3-dev branch into the master branch. All changed (e.g. the configuration phpdoc) should be still available in the v1.3-dev branch. 

The current master branch should work as before.

@lweddewer did you installed the FXP plugin as described here: http://docs.humhub.org/dev-git-installation.html#get-humhub

The FXP Plugin is not longer required in the v1.3 branch

**Comment by lweddewer** [comment]
@luke- Still wondering why I have to do this for ar simple update. 

But it makes a small update:

composer global require "fxp/composer-asset-plugin:^1.4.2"
Changed current directory to /var/www/vhosts/feuerwehr-mb.de/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating fxp/composer-asset-plugin (v1.3.1 => v1.4.2): Downloading (100%)         
Writing lock file
Generating autoload files

1 use fixed.
But 2 still remaining! 

The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.                               

  Problem 1
    - The requested package bower-asset/jquery-timeago 1.4.* exists as bower-asset/jquery-timeago[v1.5.4] but these are rejected by your constraint.
  Problem 2
    - The requested package bower-asset/blueimp-file-upload 9.11.* exists as bower-asset/blueimp-file-upload[v9.18.0, 9.19.2] but these are rejected by your constraint.

As I've written it looks like the composer.json file in master branch seams to be replaced by a rather old version by the update on 2017-12-22.

May be I have forgotten to mention that the installation with the master branch was running without any problem before this update!

Regards
Lothar

**Comment by lweddewer** [comment]
Sorry wrong button. :(

**Comment by lweddewer** [comment]
I think I found the root cause. 
Switching to the v1.3-dev seams to mash up the composer packages.
Manually dropping all the libraries in the vendor-directory and reload them via composer fix it.
