### ISSUE TITLE
Permalink Popover Issue

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2888]
### What steps will reproduce the problem?
Once you've created a post use the copy to clipboard option and close the popover then reopen the Permalink option.

### What is the expected result?
The opening of the Permalink popover.

### What do you get instead?
![](https://image.prntscr.com/image/hfnESjLbSJOgLPLLByldpw.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4 (Community site?)
| PHP version      | 5.6 (Community site?)
| Operating system | (Community site?)

**Comment by Felli** [comment]
Must use a force refresh to make the popover display again.

**Comment by githubjeka** [comment]
![image](https://user-images.githubusercontent.com/874234/34597850-74fd8ece-f1fa-11e7-8145-c4b4a9311efc.png)
On localhost when click on the link -> show flash message with OK

On humhub.com - no

Maybe it's cause of the problem

**Comment by Felli** [comment]
@githubjeka that's one possibility, I'll wait for @buddh4 or @luke- to look into this issue. :+1:

**Comment by luke-** [comment]
I've updated the community site to the latest master - now it seems working again.

@Felli Thanks for pointing this out!

**Comment by githubjeka** [comment]
@luke- probably need rebuild assets too, for lasted some css fixes
