### ISSUE TITLE
OutOfBoundsException ZendLuceneSearch

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub#2893]
### What steps will reproduce the problem?
Open `/index.php?r=directory%2Fdirectory%2Fmembers&page=2&per-page=25` and push any text into search username/tag field
### What is the expected result?
find the user
### What do you get instead?

```
OutOfBoundsException: Seek position 25 is out of range in /usr/share/nginx/html/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php:150Stack trace: #0 [internal function]: ArrayIterator->seek(25) 
#1 /usr/share/nginx/html/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php(150): LimitIterator->rewind() 
#2 /usr/share/nginx/html/humhub/protected/humhub/modules/directory/controllers/DirectoryController.php(106): humhub\modules\search\engine\ZendLuceneSearch->find('\xD0\xB0\xD1\x81\xD1\x83', Array) 
#3 [internal function]: humhub\modules\directory\controllers\DirectoryController->actionMembers() 
#4 /usr/share/nginx/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) 
#5 /usr/share/nginx/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) 
#6 /usr/share/nginx/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('members', Array) 
#7 /usr/share/nginx/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('directory/direc...', Array) 
#8 /usr/share/nginx/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) 
#9 /usr/share/nginx/html/humhub/index.php(25): yii\base\Application->run()
 #10 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 7.0.15
| Operating system | Linux

**Comment by acs-ferreira** [comment]
@githubjeka is https://github.com/humhub/humhub/issues/2834 related and does the @cebe PR helps?

**Comment by githubjeka** [comment]
need investigation.....

**Comment by Felli** [comment]
Doesn't appear to be happening with PrettyUrl enabled in `v1.2.4` for Linux servers, make sure that the `mb_string` PHP extension is enabled and up-to-date.

**Comment by githubjeka** [comment]
for PrettyUrl all be same. mb_string enable and updated... All it's nothing to do with it

https://stackoverflow.com/questions/6631579/object-limititerator-outofboundsexception

Error in row [ZendLuceneSearch.php#L150](https://github.com/humhub/humhub/blob/v1.3-dev/protected/humhub/modules/search/engine/ZendLuceneSearch.php#L150)

To fix it need something like this

```php
        $hits = new \LimitIterator($hits->getIterator(), ($options['page'] - 1) * $options['pageSize'], $options['pageSize']);

        try {
            foreach ($hits as $hit) {
                $document = $hit->getDocument();

                $result = new SearchResult();
                $result->model = $document->getField('model')->getUtf8Value();
                $result->pk = $document->getField('pk')->getUtf8Value();
                $result->type = $document->getField('type')->getUtf8Value();

                $resultSet->results[] = $result;
            }
        } catch (\OutOfBoundsException $e) {
            // offset param is not valid for \LimitIterator
        }
```

` foreach ($hits` implicitly causes `$hits->rewind()` and after `$hits->seek(($options['page'] - 1) * $options['pageSize'])` . Seek is cause for `OutOfBoundsException`


my proposed correction does not suit because the user (who is run a search) waiting for a correct response by `&keyword=` param. And by my fix user get 0 members, because a page is out of bounds 

IMHO `page` and `per-page` params should be cleared for first request by `keyword` param. This params should available only for Pagination widget

**Comment by Felli** [comment]
There isn't a function to throw an `OutOfBoundsException` so using `catch(\OutOfBoundsException $e)` doesn't seem needed, is there a reason why you'd want to just add it this way?
