### ISSUE TITLE
Images from Gallery  

### ISSUE THREAD

**Issue by NENJAK** [humhub/humhub#2894]
Hi,

I installed Gallery (v. Version: 1.0.8) and image on wall (stream) on PC appears OK
but in IOS image on the wall is too big and is wider than far right  border of  wall. 
I believe it is CSS/Less issue, is it a way to fix it?

Thanks

 
![26648581_1829001993811620_224686805_n](https://user-images.githubusercontent.com/25792378/34640396-23bb14ac-f2f2-11e7-9e94-c55cd6a44119.jpg)

### What steps will reproduce the problem?
Opening in ios/Android
### What is the expected result?
Smaller image/preview
### What do you get instead?
Image overlapped with wall border
### Additional info
N/A
| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
dd

**Comment by Felli** [comment]
I'm not seeing this issue with HumHub 1.2.4 & Gallery 1.0.8 could be your Image Library PHP extension that's the cause.

**Comment by NENJAK** [comment]
Hi,
That's a case, I think also.
You know exactly which Image Library  should be updated?
Thanks
Nenad

**Comment by Felli** [comment]
By default the GD library is normally used, I would suggest switching to the imagemagick library.

**Comment by NENJAK** [comment]
Thanks
