### ISSUE TITLE
Short passwords accepted while creating account

### ISSUE THREAD

**Issue by LThecross** [humhub/humhub#2895]
Dear Humhub team,

### What steps will reproduce the problem?
Go to the login page of your Humhub instance.
On the "sign up" box, enter an e-mail address to create an account.
Go to your mailbox and follow the link to complete the account creation.
A page asks you to enter your pseudo, your full name and your password.

### What is the expected result?
Humhub should prevent users from using small passwords, as in the account settings where you're not allowed to enter less than 5 characters.

### What do you get instead?
I was able to enter a 3-character password.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      |  7.0

In all the cases, thanks for this great software.

**Comment by acs-ferreira** [comment]
Hi, can you try https://github.com/humhub/humhub/pull/2896 ?

**Comment by LThecross** [comment]
Well done, it seems to work, thanks for the quick reply ! I've tested several use case (password change, account creation with various password sizes, disconnection and reconnection):
- it prevents entering password of <5 characters
- it does not generate any error message on the browser's console and in apache's logs.

It is important to prevent users using weak passwords, especially for a social network where there is a lot of personal data to secure. Fortunately, there seem to be a fix ongoing: [#2432](https://github.com/humhub/humhub/pull/2432)

**Comment by luke-** [comment]
#3401
