### ISSUE TITLE
humhub/humhub v1.2.4 requires bower-asset/at.js ^1.5.1 -> no matching package found

### ISSUE THREAD

**Issue by devantoine** [humhub/humhub#2898]
Hi,

I've got the following error when trying to install Humhub 1.2.4 from Github:

> humhub/humhub v1.2.4 requires bower-asset/at.js ^1.5.1 -> no matching package found

 It seems it's a common issue related to the composer-asset-plugin (which is a terrible idea btw):
* https://github.com/fxpio/composer-asset-plugin/issues/70
* https://github.com/yiisoft/yii2/issues/8688
* https://github.com/hiqdev/asset-packagist/issues/26

So, how do you guys do to install Humhub's dependencies? If you did add `bower-asset/At.js` to the list of dependencies I guess you were able to run `composer update` successfully?

**Comment by acs-ferreira** [comment]
CAP will be removed on 1.3. 

Did you run `composer global require "fxp/composer-asset-plugin:^1.4.2"` before `composer update` ?

**Comment by githubjeka** [comment]
if you use `hiqdev/asset-packagist#26` this bug https://github.com/hiqdev/asset-packagist/issues/26#issuecomment-285351515

To fix it I manually rewrite at to `At`

**Comment by devantoine** [comment]
@acs-ferreira YOu're right, I was using the 1.4.1 version, problem solved, thanks!
