### ISSUE TITLE
How can I manage ldap users?

### ISSUE THREAD

**Issue by cndlhvn** [humhub/humhub#290]
I wanted to auth user using ldap.
So,I builded ldap server.
And I set up 4 users.

This is one of user setting.

# user1001, People, open_ldap.com
dn: uid=user1001,ou=People,dc=open_ldap,dc=com
uid: user1001
cn: LDAP user1001
objectClass: account
objectClass: posixAccount
objectClass: top
loginShell: /bin/bash
uidNumber: 1001
gidNumber: 1000
homeDirectory: /home/user1001
serPassword:: *************************************

I connected to ldap server from humhub admin ldap management console.

this is setting.
Base DN 
ou=People,dc=open_ldap,dc=com

Login Filter 
(uid=%s)

User Filer 
(objectClass=posixAccount)

Username Attribute 
uid

I checked "Status: OK! (4 Users)" on ldap management console.
But, humhub users management console showed me only one user except admin user.

How can I manage ldap users?
please.

**Comment by Tagussan** [comment]
I met the similar problem before. When I configured LDAP, some users were not created. The reason was their email was invalid(the email didn't contained "@" because of human error). When I read the source code, Humhub seems to have the email validator. I don't think it's bug.

**Comment by nguyenchuc153** [comment]
please me about LDAP seting

**Comment by Liz-Gtz** [comment]
Hi!

I'm new and I wanted to auth user using ldap but I'm getting this error:

Status: ¡Error! (Mensaje: 0x34 (Server is unavailable; 00000000: LdapErr: DSID-0C090F7B, comment: Error initializing SSL/TLS, data 0, v2580): 192.168.1.6:389)

Please help me
Thanks
