### ISSUE TITLE
Remove Humhub tag from search?

### ISSUE THREAD

**Issue by BDSM-Master** [humhub/humhub#2907]
I need someone to tell me how to remove the Humhub tag from a search result. When you search a key parameter of a user, for example when I search my name 3 tags show up below my listing. Administration, Support and Humhub. I need to know how to remove Humhub from the search result.

![tag](https://user-images.githubusercontent.com/34822287/34855244-91588080-f70c-11e7-8b14-e2cd8f3b6d86.png)

**Comment by githubjeka** [comment]
![image](https://user-images.githubusercontent.com/874234/34862180-0f378a92-f77a-11e7-91ce-af8ff169e41b.png)

**Comment by BDSM-Master** [comment]
Excellent! Now do you know how to remove user without removing the other tags?

![user](https://user-images.githubusercontent.com/34822287/34871443-ad248292-f75b-11e7-8470-ae3b1f121d73.png)

**Comment by githubjeka** [comment]
![image](https://user-images.githubusercontent.com/874234/34871785-ebc2de9c-f79f-11e7-8793-37dc5e55309c.png)

**Comment by buddh4** [comment]
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
