### ISSUE TITLE
while editing user account 

### ISSUE THREAD

**Issue by balajiks** [humhub/humhub#2909]
Error
Class 'Locale' not found

    1. in /var/www/html/spiffy/protected/humhub/libs/Iso3166Codes.php at line 527
    518519520521522523524525526527528529530531532533534535536

            "WF" => "681",
            "EH" => "212",
            "YE" => "967",
            "ZM" => "260",
            "ZW" => "263"
        );
     
        public static function country($code, $translate = true)
        {
            return \Locale::getDisplayRegion("_$code", $translate ? Yii::$app->language : 'en'

**Comment by githubjeka** [comment]
`sudo apt-get install php5-intl`

**Comment by acs-ferreira** [comment]
And whats the output of `Administration --> Information --> Prerequisites` ?
Should be all GREEN.

**Comment by balajiks** [comment]
Thanks now its working.

I have another issue. email notification not working

**Comment by Felli** [comment]
@balajiks Make sure that your Cron Jobs are running.

**Comment by balajiks** [comment]
I have setup it on ubuntu not yet check on cron job

**Comment by githubjeka** [comment]
please use https://community.humhub.com to post your local problems. GitHub is bug tracker
