### ISSUE TITLE
Composer Install/Update fails when php-ldap not present

### ISSUE THREAD

**Issue by kesselb** [humhub/humhub#2919]
### What steps will reproduce the problem?

1. Clone Humhub (master) from git.
2. Run composer install (ensure that php-ldap is not enabled).

### What is the expected result?

When php-ldap is not present composer install should work anyway.

### What do you get instead?

`Loading composer repositories with package information`
`Updating dependencies (including require-dev)`
`Your requirements could not be resolved to an installable set of packages.`
`Problem 1`
` - zendframework/zend-ldap 2.8.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.`
`- zendframework/zend-ldap 2.7.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.`
`- Installation request for zendframework/zend-ldap ^2.5 -> satisfiable by zendframework/zend-ldap[2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.7.0, 2.7.1, 2.8.0].`

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | master
| PHP version      | 5.6 / 7.0 / 7.1 / 7.2
| Operating system | Ubuntu 16.04.3

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by githubjeka** [comment]
>What is the expected result?
When php-ldap is not present composer install should work anyway.

No... because `zendframework/zend-ldap` in "require" section of `composer.json`

**Comment by githubjeka** [comment]
And I don't know could have working HumHub without `zendframework/zend-ldap`

**Comment by danielkesselberg** [comment]
> because zendframework/zend-ldap in "require" section of composer.json

Thats the issue ;-) Optional packages like zend-ldap should be in suggest section: https://getcomposer.org/doc/04-schema.md#suggest

**Comment by githubjeka** [comment]
I agree, but 
> And I don't know could have working HumHub without zendframework/zend-ldap

Do you have any working app for this case?

**Comment by danielkesselberg** [comment]
After some adjustments humhub works fine without zend-ldap (e.g. https://github.com/humhub/humhub/pull/2920).
