### ISSUE TITLE
Enhance Mentioning

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2944]
I believe it should be possible to allow users to mention other users just by one name when mentioning them, at the moment it's possible to do this when Display Name (Format) is set to Username, but I believe this is going backward when implementing the mentioning feature it should be possible to mention a user no matter which is toggled.

### Before
`Hello, @Julian Harrer how are you?` or `Hello, @Julian how are you?`

### After
`Hello, @Julian how are you?` & `Hello, @Julian Harrer how are you?`

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/issues/2944
