### ISSUE TITLE
onCronDailyRun deletes files stored using the markdown editor because of missing object_model/object_id in the file table

### ISSUE THREAD

**Issue by arnfinnkristensen** [humhub/humhub#2945]
We have discovered a critical error in the markdown editor. When a user add a pictures and save the file is uploaded to the server and stored and everything seems to be correct. The problem is that in the table file the object_model and object_id is not saved. This applayses for all mark down editors. The problem happend when the daily cron job is going due to the function located in protected/humhub/modules/file/Events.php:
  
` public static function onCronDailyRun($event)`

The documentation tells me the foloowing:
`    /**
     * On cron daily run do some cleanup stuff.
     * We delete all files which are not assigned to object_model/object_id
     * within 1 day.
     *
     * @param type $event
     */`

This function deletes all the pictures stored/uploaded with the markdown editor.

I strongly recomand that you fix this inside the markdown editor quickly.

### What steps will reproduce the problem?
* Switch on the daily corn job
* Create an event and add a picture to the markdown editer (description field).

### What is the expected result?
* The pictuer should not be deleted

### What do you get instead?
* The pictuer are deleted

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4 (First discoverd in 1.2.2)
| PHP version      | 7.x
| Operating system | linux (on server side) win (client)

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
The files have to be attached manually in the save logic of the model. Which Markdown input are your refering to?

**Comment by arnfinnkristensen** [comment]
If I use the description (and all other places where this controll is use) the values in database is not stored.

From create an event:
![image](https://user-images.githubusercontent.com/30318362/35033519-442bcbd8-fb6b-11e7-859a-32af36ec7458.png)

From database this field will be empty:

![image](https://user-images.githubusercontent.com/30318362/35033637-ae70fdce-fb6b-11e7-9107-6b11ad17462b.png)

When this field in the table are missing the onCronDailyRun will delet this files.

From OnCronDailyRun in the protected\humhub\modules\file\Event.php

     /**
     * On cron daily run do some cleanup stuff.
     * We delete all files which are not assigned to object_model/object_id
     * within 1 day.
     *
     * @param type $event
     */
`
    public static function onCronDailyRun($event)
    {

        $controller = $event->sender;
        $controller->stdout("Deleting old unassigned files... ");

        // Delete unused files
        $deleteTime = time() - (60 * 60 * 24 * 1); // Older than 1 day
        foreach (File::find()->andWhere(['<', 'created_at', date('Y-m-d', $deleteTime)])->andWhere('(object_model IS NULL or object_model = "")')->all() as $file) {
            $file->delete();
        }

        $controller->stdout('done.' . PHP_EOL, \yii\helpers\Console::FG_GREEN);
    }`

**Comment by arnfinnkristensen** [comment]
It is to solutions to this problem.

Fix the saving from the mark down editor
or
If the guid in the table exsist also in the folder structur the OnCroneDailyRun do not delete the files. 

I understand that OnCronDailyRun shall delete files that is not in the DB to avoid to many files just "hanging around". 

I hope you @buddh4  can provide us with a solution quickly since this are avoiding us to implement functionality into the cron job.

**Comment by arnfinnkristensen** [comment]
@luke- I'm not sure if I understand you correctly. Do you mean that we shall implement this function by our self?

**Comment by buddh4** [comment]
https://github.com/humhub/humhub-modules-calendar/issues/114
