### ISSUE TITLE
Issue with Synology servers

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2946]
Issue provided by the [community site](https://community.humhub.com/content/perma?id=136451)

On [line 99](https://github.com/humhub/humhub/blob/master/protected/humhub/components/Application.php#L99) it's required to use `date_default_timezone_set()` not `date_default_timezone_get()`, should update this so that either could be used in the likelihood one or the other is requested.

**Comment by danielkesselberg** [comment]
Not sure about it. This looks like a configuration issue to me. In fact line [line 99](https://github.com/humhub/humhub/blob/master/protected/humhub/components/Application.php#L98) depends on a properly configured timezone. When no timezone defined in $config then use the default one (according to line 98).

**Comment by danielkesselberg** [comment]
@acs-ferreira pointed us to https://github.com/yiisoft/yii2/blob/2.0.12/framework/base/Application.php#L243. I guess we may ask @luke- about it. Maybe its something < Yii2 and could be removed.

**Comment by Felli** [comment]
@danielkesselberg I believe the function still works, although I'm not sure if it works for all servers or server types, we should take into account server types that don't flow within UTC (e.g GMT)

**Comment by acs-ferreira** [comment]
Check here why: https://github.com/yiisoft/yii2/issues/9135#issuecomment-122267988

Yii2 handles it correctly, not Humhub.

**Comment by Felli** [comment]
@acs-ferreira it's worth discussing with @luke- about this. :+1:

**Comment by luke-** [comment]
Probably our preInit should not be necessary (anymore).
I removed it in the develop branch.

Thank you all!
