### ISSUE TITLE
Module disable on space trows error

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2949]
### What steps will reproduce the problem?

Disable a Module inside a Space.

### What is the expected result?

Module is disabled and a Success message appears.

### What do you get instead?

Module is disabled **but** with a Pjax error:

```
TypeError: c.pjax is undefinedh@https://my.ekinops.net/static/js/all-30bdc6203ae4795831c2b8d2fbfb5fb6.js?v=1515832155:135:3755
h@https://my.domain.net/static/js/all-30bdc6203ae4795831c2b8d2fbfb5fb6.js?v=1515832155:129:6613
i/<@https://my.domain.net/static/js/all-30bdc6203ae4795831c2b8d2fbfb5fb6.js?v=1515832155:140:7392
d@https://my.domain.net/static/js/all-30bdc6203ae4795831c2b8d2fbfb5fb6.js?v=1515832155:85:9369
[22]
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | master
| PHP version      | 7.1

**Comment by buddh4** [comment]
Seems to be the same issue here, can't reproduce this either.
