### ISSUE TITLE
Modal stays open on pjax page load

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#2950]
### What steps will reproduce the problem?
1. Open a modal with pjax link
2. Click the link

### What is the expected result?
The new page should load and Modal should be closed

### What do you get instead?
Modal stays open and the page loads in the background

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2

**Comment by yurabakhtin** [comment]
@buddh4 @luke- I tested this with a link "Forgot your password?" on the modal login window:

1) Currently the link has the following code https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/views/auth/login_modal.php#L60:

```html
<a id="recoverPasswordBtn" href="#" data-action-click="ui.modal.load" data-action-url="<?= Url::to(['/user/password-recovery']) ?>">
```

On click, the page `/user/password-recovery` is loaded in the same modal window as expected.

2) If I change that to `<a href="<?= Url::to(['/user/password-recovery']) ?>">` then on click the page is loaded in background and the modal window is not hidden. I guess we should fix this problem.

3) Here https://github.com/humhub/humhub/blob/master/static/js/jquery.pjax.modified.js#L104-L107 I find the code:

```js
// Ignore links with data-pjax="0"
if ($link.data('pjax') == 0) {
    return;
}
```

3a) If add the attribute `data-pjax="0"` to the `<a href=...>` then it works as required, i.e. modal is closed and new page is opened with the URL from `href`. It may be as solution \#1.

4) solution \#2 is to modify the js code to `if ($link.data('pjax') == 0 || $link.attr('href') !== '#') {...`.
But I am not sure I can modify the file, what if some links will be broken in some modal windows. Or all correct links in modal window should have the attributes like `data-action-url` and if a link has only `href="some-ulr"` then such link should be opened as normal page then we can apply the fix.

What do you think?
Is it enough solution \#1?
Can we modify the file for solution \#2?

**Comment by buddh4** [comment]
Maybe we can just close all open modals within the `unload` function of the modal js module?

**Comment by yurabakhtin** [comment]
@buddh4 I don't find the `unload` function in the modal js module. But please see again here https://github.com/humhub/humhub/blob/master/static/js/jquery.pjax.modified.js#L104-L127 what ignore cases we have for the pjax click:

```js
// Ignore links with data-pjax="0"
if ($link.data('pjax') == 0) {
    return;
}

if (link.tagName.toUpperCase() !== 'A')
    throw "$.fn.pjax or $.pjax.click requires an anchor element"

// Middle click, cmd click, and ctrl click should open
// links in a new tab as normal.
if (event.which > 1 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey)
    return

// Ignore cross origin links
if (location.protocol !== link.protocol || location.hostname !== link.hostname)
    return

// Ignore case when a hash is being tacked on the current URL
if (link.href.indexOf('#') > -1 && stripHash(link) == stripHash(location))
    return

// Ignore event with default prevented
if (event.isDefaultPrevented())
    return
```

I think it is a good place to add a new ignore case here like:

```js
// Ignore normal link from modal window in order to close the modal
if (link.href !== '#' && link.href.length && $link.closest('.modal').length)
    return
```

You can check how it works in draft PR https://github.com/humhub/humhub/pull/4812

**Comment by buddh4** [comment]
But we do not want to suppress pjax, we rather want to close all modals once we've loaded a pjax page.

Something like this here: https://github.com/humhub/humhub/blob/master/static/js/humhub/humhub.ui.modal.js

```
module.initOnPjaxLoad = true;
var init(pjax) {
    if(pjax) {
        $('.modal').each(function() {
            let modal = Modal.instance(this);
            if(modal) {
               modal.close(); 
           }
        });
        return; //skip other init code in case of pjax
   }
   //...
}
```

**Comment by yurabakhtin** [comment]
@buddh4 Ok, I have understood we should not suppress pjax. Please review new solution https://github.com/humhub/humhub/pull/4812/commits/6a255e9ff548b76aded9f0a5cf283c258f7d5e54
