### ISSUE TITLE
Invalid Parameter – yii\base\InvalidParamException - The file does not exist: /protected/vendor/bower/bluebird - alias needed?

### ISSUE THREAD

**Issue by Qixuga** [humhub/humhub#2954]
Hi @all,

after updating humhub to actual version 1.24 on php 7.1 webserver because of the "dublicate menu problem" (already found in the tickets) i also update composer and the packages.

actualy i got the following error:
```
Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: /protected/vendor/bower/bluebird
in /protected/vendor/yiisoft/yii2/web/AssetManager.php at line 454 

```
i#m not firm with the composer and so i thought that vendor/bowser seems to be replaces with vendor/bowser-assets

so i thought to insert a alias in composer.json
```
    "alias": {
        "@bower":       "@vendor/bower-asset",
        "@npm":         "@vendor/npm-asset"
    }
```

But i think humhub/yii also need that alias, right?
where i should place it also?

the bluebird-files will be found at
`/vendor/bower-asset/bluebird`

instead of
`/vendor/bower/bluebird`

Thank you!

**Comment by Qixuga** [comment]
quick & dirty i created a symbolic link in the file-system to "solve" it.
after that - i got another error:

Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: /protected/vendor/bower/At.js

    1. in /protected/vendor/yiisoft/yii2/web/AssetManager.php line 454

**Comment by Qixuga** [comment]
Another error, sorry for this fast reponse to the same ticket:
during the same update - i don't know solving the errors above.

i thought to follow the following suggestion:
`Package zhuravljov/yii2-queue is abandoned, you should avoid using it. Use yiisoft/yii2-queue instead.`

composer remove zhuravljov/yii2-queue
composer require yiisoft/yii2-queue

```
PHP Fatal Error – yii\base\ErrorException
Class 'zhuravljov\yii\queue\Queue' not found

in /protected/humhub/components/queue/driver/Sync.php at line 24 

```

**Comment by danielkesselberg** [comment]
Hey, we already fixed some of this issues (some at master and some at 1.3-dev). 

1) Please ensure that you have to "repositories" section (see https://github.com/humhub/humhub/blob/v1.3-dev/composer.json) in your composer.json

2) The right place for alias is here and its correct for 1.3 already (https://github.com/humhub/humhub/blob/v1.3-dev/protected/humhub/config/common.php)

3) Im not sure about the At.js issue. Here is the Asset configuration (https://github.com/humhub/humhub/blob/v1.3-dev/protected/humhub/assets/AtJsAsset.php) for 1.3. Does this help?

4) Please stay with zhuravljov/yii2-queue for 1.2.

**Comment by Qixuga** [comment]
hey, thank you!
that help a lot but why are the files from /protected/config are'nt in the latest release?
i have to update the file so many errors seems to go away.

4.) it seems i can't role back or did i something wrong?


5.) actualy i got a new one and hope you could help:
`PHP Fatal error:  Uncaught Error: Class 'humhub\components\Application' not found in /index.php:25`

Line 25:
`(new humhub\components\Application($config))->run();`

`/protected/humhub/components/Application.php are given?!`

**Comment by danielkesselberg** [comment]
When you use the package from humhub.org (zip or tar.gz) the composer stuff is prepared. Dont run composer update or install.

**Comment by Qixuga** [comment]
Thank you - so the 500 is fixed now.
System repond again with following error:

```
 PHP Fatal Error – yii\base\ErrorException
Class 'zhuravljov\yii\queue\Queue' not found

    1. in /protected/humhub/components/queue/driver/Sync.php at Line 24
...

```

May be me uninstall of the extension above raise that error?

**Comment by danielkesselberg** [comment]
1) Make a Backup (even if your current setup is broken)
2) Delete composer.json, composer.lock and protected/vendor.
3) Copy vendor from zip or tar.gz to protected/vendor.

**Comment by Qixuga** [comment]
I like to give you a late feedback how i solved the problem.
Your hint doesn't work.

Backup all files and database
Download the actual version from website, overwrite all files
Fullfill missing dependencies with composer
Major problems seems to be the zhuravljov-moduls - i removed them and installed the yiisoft-variants and it work
I also update lots of other libs and
Install some missing one

So at the end everything work fine.

But a few new problems outcome:
Some Update-Files could not be integrated. I checked the source and some changes allready might be there.
Major-problem - it seems that the admin-structure changed. The old admin isn't an admin any more.

How can i change this or how can i create a new admin user?
Are there any updates to the structure i can restart manualy?

The odysee i drive on a secondary dev-system and if realy everythink is fine - i will roll it out live.
Thank you!

**Comment by danielkesselberg** [comment]
Composer support has been significantly improved with 1.3. Did you tried with 1.3?
