### ISSUE TITLE
ascii and apostrophe

### ISSUE THREAD

**Issue by verbre** [humhub/humhub#2968]
Hi,
in French when we fly over the wigdet, for example, which show in a profile the spaces of which a user is a member, and the name of the space contains terms with an apostrophe, the display is incorrect.

![ascii](https://user-images.githubusercontent.com/34917479/35440188-a3a88bb6-029e-11e8-88f9-ac6a95fa6b00.jpg)

**Comment by acs-ferreira** [comment]
Maybe this should be `true` as content is passed as `HTML::encode`?

https://github.com/humhub/humhub/blob/955d83be8b9e20183b1db209141db7ab24d048a3/static/js/humhub/humhub.ui.additions.js#L121

**Comment by mfrb** [comment]
I have modified this file (html: true,) but hat does not solve the problem.

**Comment by mfrb** [comment]
and the same problem appears in the "calendar" module.
![35044350-5a9282c0-fb90-11e7-81f7-1c48a925c6ec](https://user-images.githubusercontent.com/34917479/35779591-020f6f16-09d0-11e8-84c8-b63006fa702d.JPG)

**Comment by acs-ferreira** [comment]
Normal, you have to regenerate assets.
http://docs.humhub.org/dev-core-build-assets.html

![image](https://user-images.githubusercontent.com/12234510/35779870-516a7f5c-09d4-11e8-8443-1fcbc39b517e.png)

**Comment by mfrb** [comment]
Thank you but I do not understand what I have to do

**Comment by mfrb** [comment]
@acs-ferreira 
I followed the procedure and it farted the CSS.
So I went back and so it's not resolved!

**Comment by acs-ferreira** [comment]
As you can see on my screenshot, _if things are done properly_, this fixes those problems.
Perhaps, this is NOT a official fix, only a "fix suggestion".

You should wait for an official fix.

**Comment by verbre** [comment]
Yet we followed the procedure but it broke the CSS for an unknown reason. Maybe because of our VPS.
Anyway thank you for the help and indeed we will wait for an official fix.

**Comment by buddh4** [comment]
Displaynames are Html encoded in the backend, perhaps we should validate space names and filter out special characters. The asset build is not neccessary.

**Comment by verbre** [comment]
Hi @buddh4 I have modified the file humhub/static/js/humhub/humhub.ui.additions.js (line 121) (html: true,) but hat does not solve the problem.

**Comment by buddh4** [comment]
The problem is this file is only in use when in debug mode, in production mode the merged assets are in use thats why @acs-ferreira suggested to run the asset build.

**Comment by verbre** [comment]
Thanks i will wait for an official fix so.

**Comment by acs-ferreira** [comment]
Should be fixed also in modules, like CFiles.
![image](https://user-images.githubusercontent.com/12234510/37219494-dbe11dcc-23c3-11e8-9249-03cb10dd5ad5.png)

**Comment by buddh4** [comment]
@acs-ferreira Please open a ticket in the files module, with a more descriptive sceenshot I assume this is also a tooltip ;)

**Comment by funkycram** [comment]
Same problem here in production mode (Humhub 1.2.4) with the calendar module and notifications.
Example in the mail subject I receive in my mailbox :
![image](https://user-images.githubusercontent.com/23310825/38739695-e978f918-3f35-11e8-933b-7770837cace7.png)
