### ISSUE TITLE
Posts, Texts, Likes loading forever and never showing the after effect without refreshing

### ISSUE THREAD

**Issue by agiann** [humhub/humhub#2970]
### What steps will reproduce the problem?
Just download humhub and check if it doesn't work properly
### What is the expected result?
Click Reply and the reply goes instantly
### What do you get instead?
Infinite circle, bar that never refreshes
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 7.1.8
| Operating system |Mac OS X 10.10

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by acs-ferreira** [comment]
Also provide the full error stacks from `Administration --> Information --> Logging` (if any) and errors from [your browser console](https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors) if possible.
