### ISSUE TITLE
Grunt Problem

### ISSUE THREAD

**Issue by 1337god** [humhub/humhub#2972]
### What steps will reproduce the problem?

sudo npm install grunt --save-dev

### What is the expected result?

Grunt Installed?

### What do you get instead?

The website doesn't work at all, it says connection refused

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | lastes
| PHP version      | 7.0
| Operating system | Ubuntu 16

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by danielkesselberg** [comment]
Please follow [Getting Started](http://docs.humhub.org/admin-README.html).

**Comment by Felli** [comment]
To further help could you provide an error log? From what I'm getting it's more of a permissions issue. :smile:

**Comment by buddh4** [comment]
What are you trying to achieve? Grunt is only used for building production assets and themes anc creating migrations. If you want to install HumHub follow the Installation guide as danliel noted.
