### ISSUE TITLE
registration problem

### ISSUE THREAD

**Issue by marinerge** [humhub/humhub#2976]
Hello, when new person writes his E-mail it writes that check your account for continuing registration, But they dont get email from my side, what can i do? I configured gmail smtp it does not work, then i wrote mine but still did not work

**Comment by Felli** [comment]
You must setup your [Cron Jobs](http://docs.humhub.org/admin-cron-jobs.html).

**Comment by buddh4** [comment]
Registration mails are not sent by Cron. Its hard to tell why it's not working, are there any errors in the logs? Since its probably rather an issue with your environenment, please ask such questions in the [Community](http://community.humhub.com/)
