### ISSUE TITLE
Link Preview - ignore non-https og:image 

### ISSUE THREAD

**Issue by joeworkman** [humhub/humhub#2977]
My humhub site is https however, the security is breached when the Link Preview loads images from a non-https link that was posted. 

The Link Preview module currently adding the open graph meta data, including images. However, if the image in question is http, it breaks the https on my site and the browser displays a warning to users that my site no not secure. 

I would love to see a feature where if the g:image is not https, the image is not added to the preview. This will keep the integrity of https connections on my site.

**Comment by joeworkman** [comment]
I know that this is a paid plugin. But I am unsure how to file bugs against it. Please let me know if I should report this somewhere else.

**Comment by LThecross** [comment]
Have you tried to block non https pictures through Content Security Policy ?
[https://www.html5rocks.com/en/tutorials/security/content-security-policy/](https://www.html5rocks.com/en/tutorials/security/content-security-policy/)
This could temporarily fix your problem.

**Comment by joeworkman** [comment]
Good call. I added the following to my theme... 

`<meta http-equiv="Content-Security-Policy" content="block-all-mixed-content">`

**Comment by Felli** [comment]
@joeworkman I believe this should be added core level rather than theme level for better protection, but seeings as overwriting is a thing with updates it would just be removed later, maybe @luke- could have it implemented into the core at some point?

**Comment by acs-ferreira** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests
