### ISSUE TITLE
Linkpreview triggered in console

### ISSUE THREAD

**Issue by devantoine** [humhub/humhub#2979]
Hi,

We've got a command which imports articles (a custom module from ours with a model extending `ContentActiveRecord`). It was working fine until we installed the linkpreview module.

Since then we've got the following error (which was damn hard to debug): 

> Calling unknown method: yii\console\Request::post()

This error is raised by linkpreview in Module.php:53 : `$preview->load(Yii::$app->request->post()`.

I don't know how it should be handled. Maybe it's still interesting to have the linkpreview triggered in console for models that extend `ContentActiveRecord` but then using the request to fill the model makes no sense.

In my opnion the module shouldn't be triggered in console at all.

To avoid this error I've added the following condition to the first if, line 41 : `|| \Yii::$app instanceof Yii\Console\Application` but maybe a nicer way of doing it would be to register the `onAfterContentSave` callback for console only but I don't think there's something for that in the Module mechanism.

**Comment by buddh4** [comment]
Thanks, we'll include this to the upcoming linkpreview version.
