### ISSUE TITLE
Enhancement for search: Fuzzy search

### ISSUE THREAD

**Issue by nepomuc** [humhub/humhub#2981]
As a user I want to be supported by a fuzzy search in case I spell something wrong.

**Comment by devcline** [comment]
vote up 
![image](https://user-images.githubusercontent.com/617020/49098582-7b604b00-f26f-11e8-9e94-31df742567f0.png)

**Comment by luke-** [comment]
This must be supported by the respective search engine. As far as I know, the MySQL full text search does not currently support this.

With Solr it should already be possible to activate this via the configuration.
