### ISSUE TITLE
PHP Warning – yii\base\ErrorException

### ISSUE THREAD

**Issue by matthewosbeta** [humhub/humhub#2999]
| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      |  7.0.26
| Operating system | Linux
When visiting the Administrator page I see:
PHP Warning – yii\base\ErrorException
include(/home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/grid/GridView.php): failed to open stream: No such file or directory
1. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/BaseYii.php at line 292
283284285286287288289290291292293294295296297298299300301        } elseif (strpos($className, '\\') !== false) {
            $classFile = static::getAlias('@' . str_replace('\\', '/', $className) . '.php', false);
            if ($classFile === false || !is_file($classFile)) {
                return;
            }
        } else {
            return;
        }
 
        include($classFile);
 
        if (YII_DEBUG && !class_exists($className, false) && !interface_exists($className, false) && !trait_exists($className, false)) {
            throw new UnknownClassException("Unable to find '$className' in file: $classFile. Namespace missing?");
        }
    }
 
    /**
     * Creates a new object using the given configuration.
     *
2. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/BaseYii.php at line 292 – yii\base\ErrorHandler::handleError(2, 'include(/home/u717701066/public_...', '/home/u717701066/public_html/soc...', 292, ...)
286287288289290291292293294295296297298                return;
            }
        } else {
            return;
        }
 
        include($classFile);
 
        if (YII_DEBUG && !class_exists($className, false) && !interface_exists($className, false) && !trait_exists($className, false)) {
            throw new UnknownClassException("Unable to find '$className' in file: $classFile. Namespace missing?");
        }
    }
 
3. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/BaseYii.php at line 292 – include()
286287288289290291292293294295296297298                return;
            }
        } else {
            return;
        }
 
        include($classFile);
 
        if (YII_DEBUG && !class_exists($className, false) && !interface_exists($className, false) && !trait_exists($className, false)) {
            throw new UnknownClassException("Unable to find '$className' in file: $classFile. Namespace missing?");

        }
    }
 
4. yii\BaseYii::autoload('yii\grid\GridView')
5. in /home/u717701066/public_html/socialbook/protected/humhub/widgets/GridView.php at line 14 – spl_autoload_call('yii\grid\GridView')
891011121314151617181920 
namespace humhub\widgets;
 
/**
 * @inheritdoc
 */
class GridView extends \yii\grid\GridView
{
 
    const EVENT_INIT = 'init';
 
    /**
     * @inheritdoc
6. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/BaseYii.php at line 292 – include('/home/u717701066/public_html/soc...')
286287288289290291292293294295296297298                return;
            }
        } else {
            return;
        }
 
        include($classFile);
 
        if (YII_DEBUG && !class_exists($className, false) && !interface_exists($className, false) && !trait_exists($className, false)) {
            throw new UnknownClassException("Unable to find '$className' in file: $classFile. Namespace missing?");
        }
    }
 
7. yii\BaseYii::autoload('humhub\widgets\GridView')
8. in /home/u717701066/public_html/socialbook/protected/humhub/modules/admin/views/user/index.php at line 23 – spl_autoload_call('humhub\widgets\GridView')
9. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/base/View.php at line 330 – require('/home/u717701066/public_html/soc...')
324325326327328329330331332333334335336    {
        $_obInitialLevel_ = ob_get_level();
        ob_start();
        ob_implicit_flush(false);
        extract($_params_, EXTR_OVERWRITE);
        try {
            require($_file_);
            return ob_get_clean();
        } catch (\Exception $e) {
            while (ob_get_level() > $_obInitialLevel_) {
                if (!@ob_end_clean()) {
                    ob_clean();
                }
10. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/base/View.php at line 250 – yii\base\View::renderPhpFile('/home/u717701066/public_html/soc...', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\admin\models\UserSearch])
244245246247248249250251252253254255256                    $this->renderers[$ext] = Yii::createObject($this->renderers[$ext]);
                }
                /* @var $renderer ViewRenderer */
                $renderer = $this->renderers[$ext];
                $output = $renderer->render($this, $viewFile, $params);
            } else {
                $output = $this->renderPhpFile($viewFile, $params);
            }
            $this->afterRender($viewFile, $params, $output);
        }
 
        array_pop($this->_viewFiles);
        $this->context = $oldContext;
11. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/base/View.php at line 152 – yii\base\View::renderFile('/home/u717701066/public_html/soc...', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\admin\models\UserSearch], humhub\modules\admin\controllers\UserController)
146147148149150151152153154155156157158     * @throws InvalidCallException if the view cannot be resolved.
     * @see renderFile()
     */
    public function render($view, $params = [], $context = null)
    {
        $viewFile = $this->findViewFile($view, $context);
        return $this->renderFile($viewFile, $params, $context);
    }
 
    /**
     * Finds the view file based on the given view name.
     * @param string $view the view name or the [path alias](guide:concept-aliases) of the view file. Please refer to [[render()]]
     * on how to specify this parameter.
12. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/base/Controller.php at line 381 – yii\base\View::render('index', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\admin\models\UserSearch], humhub\modules\admin\controllers\UserController)
375376377378379380381382383384385386387     * These parameters will not be available in the layout.
     * @return string the rendering result.
     * @throws InvalidParamException if the view file or the layout file does not exist.
     */
    public function render($view, $params = [])
    {
        $content = $this->getView()->render($view, $params, $this);
        return $this->renderContent($content);
    }
 
    /**
     * Renders a static string by applying a layout.
     * @param string $content the static string being rendered
13. in /home/u717701066/public_html/socialbook/protected/humhub/modules/admin/controllers/UserController.php at line 74 – yii\base\Controller::render('index', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\admin\models\UserSearch])
14. humhub\modules\admin\controllers\UserController::actionIndex()
15. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([humhub\modules\admin\controllers\UserController, 'actionIndex'], [])
16. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/base/Controller.php at line 156 – yii\base\InlineAction::runWithParams(['r' => 'admin/user'])
17. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/base/Module.php at line 523 – yii\base\Controller::runAction('', ['r' => 'admin/user'])
18. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/web/Application.php at line 102 – yii\base\Module::runAction('admin/user', ['r' => 'admin/user'])
19. in /home/u717701066/public_html/socialbook/protected/vendor/yiisoft/yii2/base/Application.php at line 380 – yii\web\Application::handleRequest(humhub\components\Request)
20. in /home/u717701066/public_html/socialbook/index.php at line 25 – yii\base\Application::run()
19202122232425    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();
 Yii Framework
2018-02-06, 10:31:15

Apache

Yii Framework/2.0.12

**Comment by danielkesselberg** [comment]
The error looks like an incomplete upload. Do you unpacked humhub on your pc and uploaded it with ftp/sftp? You may retry the upload.
