### ISSUE TITLE
Push translate.humhub.org to repo

### ISSUE THREAD

**Issue by xaro1** [humhub/humhub#3000]
Anyone at HumHub can push translate.humhub.org to repo please ?

**Comment by Felli** [comment]
A lot of the changes haven't been made on the Translation site that has been done on the GitHub repo, doing this now could cause issues with old unused translations being re-implemented, I suggest waiting a little bit longer before doing this. :smile:

**Comment by xaro1** [comment]
Ok but lot of changes have also been made on translation site since last push on Jan 16 (7464bb83fef2193b7f8a64c80fd01367333a6509) especially on FR translation.

Suggestion: both (translation & master repo) should be synchronized automatically.

**Comment by luke-** [comment]
@xaro1 done
