### ISSUE TITLE
Synchronization with LDAP is successful but users are not listed.

### ISSUE THREAD

**Issue by gueeme** [humhub/humhub#3001]
| HumHub version   | 1.2.4
| PHP version      | 5.6.32
| Operating system | Windows 10 Pro

Synchronization with LDAP is successful but users are not listed.
Is there any additional configuration to be made?

![issue_01](https://user-images.githubusercontent.com/19538568/35866856-63e19e10-0b3f-11e8-87fb-500b7341a1ba.png)
![issue_02](https://user-images.githubusercontent.com/19538568/35866857-6406ce92-0b3f-11e8-93a3-d10aef7a1bfe.png)

**Comment by gueeme** [comment]
Someone who can help???

**Comment by acs-ferreira** [comment]
Is the setting at the bottom at the page activated?

**Comment by gueeme** [comment]
Yes. It's checked.
My configuration is in the image below:

![humhub_ldap](https://user-images.githubusercontent.com/19538568/36037199-246baf76-0da3-11e8-816f-5d0f9fffc35a.png)

**Comment by gueeme** [comment]
About the cronjobs I did not check.
Where do I see this? The application is hosted on a Windows 10 machine for now.

**Comment by acs-ferreira** [comment]
Admin -> Information -> Cronjobs

They need to be running (both).
See 
https://community.humhub.com/s/installation-and-setup/wiki/page/view?title=Cron+Job+Setup

**Comment by acs-ferreira** [comment]
And also the good old RTFM :)
http://docs.humhub.org/admin-README.html

**Comment by githubjeka** [comment]
Try to use https://docs.microsoft.com/en-us/sysinternals/downloads/adexplorer
99% objectClass=person is the wrong condition for you

**Comment by gueeme** [comment]
Hello man

I've used other filters too, such as top, user, organizationalPerson and does not sync.
My cronjob synchronized too and nothing to sync the users.

![2018-02-14 15_03_36-administracao - sicoob credipinho social](https://user-images.githubusercontent.com/19538568/36217325-460b5d86-1198-11e8-83ef-31de9e7edc06.png)

**Comment by githubjeka** [comment]
# Try to use https://docs.microsoft.com/en-us/sysinternals/downloads/adexplorer

![image](https://user-images.githubusercontent.com/874234/36241590-5d4b7036-1228-11e8-81eb-9ae76a303540.png)

And after search use the condition (blue square) in setting LDAP on HumHub:

![image](https://user-images.githubusercontent.com/874234/36241449-73f0a96a-1227-11e8-9653-831e9cc6bdcf.png)

!!! AND `E-Mail Address Attribute` should be not empty for sync users on the ActiveDirectory server

**Comment by gueeme** [comment]
It worked perfectly now.
Thank you very much for your help.
