### ISSUE TITLE
Class 'm140830_145504_following' not found

### ISSUE THREAD

**Issue by ja129143** [humhub/humhub#3008]
I just recently installed the latest version of Humhub. While trying to install I encountered the following error: 
![image](https://user-images.githubusercontent.com/24374983/36002341-40bbc724-0cd6-11e8-96c9-380be107f787.png)

**Comment by buddh4** [comment]
Check if the file `protected/humhub/migrations/m140830_145504_following.php` is present.

**Comment by ja129143** [comment]
I found out the softaculous supports it so I hsed that instead, thanks though.
