### ISSUE TITLE
Change the Space URL raises 404 and looses Homepage settings

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3009]
### What steps will reproduce the problem?

Change a Space URL in Advanced settings.

### What is the expected result?

URL is changed and redirected.

Homepage settings are not lost.

### What do you get instead?

Redirection raises a `404` as redirection is made to the old URL.

Homepage settings are lost.

**Comment by buddh4** [comment]
Can provide a step by step description.
What do you set as `Homepage` exactly in order to reproduce this?

**Comment by acs-ferreira** [comment]
1. Set as this
![image](https://user-images.githubusercontent.com/12234510/37042854-8f818946-215f-11e8-9cbc-9d99c82c42cd.png)

2. Change URL ans SAVE
![image](https://user-images.githubusercontent.com/12234510/37042880-9dc533f4-215f-11e8-8c5a-f83b950b362d.png)

3. 404
![image](https://user-images.githubusercontent.com/12234510/37042897-a8c73ba8-215f-11e8-9e6a-cc02fc501eba.png)

4. Homepage setting is lost
![image](https://user-images.githubusercontent.com/12234510/37042931-bbc38cc0-215f-11e8-9ba8-d04e610a21cc.png)
