### ISSUE TITLE
Cannot make a post private before posting (on space content visibility = public)

### ISSUE THREAD

**Issue by Buliwyfa** [humhub/humhub#3010]
### What steps will reproduce the problem?
Got to any space where “Default content visibility” is public
Change the post to private
Post anything
Post is public
![a1](https://user-images.githubusercontent.com/13509685/36069266-8e582c36-0ee6-11e8-9fb0-07c50cc9dd47.png)
![a2](https://user-images.githubusercontent.com/13509685/36069267-8e7d5a10-0ee6-11e8-8b91-6170ba0db25c.png)
![a3](https://user-images.githubusercontent.com/13509685/36069268-8e9c498e-0ee6-11e8-8af4-fc7cc9868588.png)
![a5](https://user-images.githubusercontent.com/13509685/36069269-8eba91dc-0ee6-11e8-931a-9144c6ab49a1.png)
![a6](https://user-images.githubusercontent.com/13509685/36069270-8ed4bd1e-0ee6-11e8-8ef9-d53b85e14dff.png)

### What is the expected result?
The post to be private as I set it before posting

### What do you get instead?
The post is public NOT what I set it before posting

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?*
| PHP version      |  *
| Operating system | *
* NO idea using HumHub Pro hosting plan

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
DONE https://community.humhub.com/content/perma?id=139204
bug confirm

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
Nothing there

**Comment by acs-ferreira** [comment]
This is true, and to make that post Private, you should edit the post again an make it private.

**Comment by Felli** [comment]
@acs-ferreira unable to make the post private afterward as well, a reload is needed before, if not done like this then the post will just remain public till a reload is done. Could be related to #2950?

**Comment by MiraclePK** [comment]
I want to rename (SPACES) to Groups is it possible

**Comment by MiraclePK** [comment]
@buddh4  please tell me. this will very helpful for me
