### ISSUE TITLE
Localization/Filipino Translation

### ISSUE THREAD

**Issue by jcpuzs1** [humhub/humhub#3021]
I want to contribute by localizing some of your file to Filipino language.

**Comment by githubjeka** [comment]
http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#translating-module-messages

Add to `protected/humhub/config/i18n.php:14` and to `protected/humhub/config/common.php:156` your language and run `php yii message` from `protected` dir

**Comment by Felli** [comment]
Should be listed under `fil` if I'm correct... :thinking:

**Comment by simonfranzen** [comment]
Just to hop in: The language is Tagalog https://de.wikipedia.org/wiki/Tagalog

About the difference
https://en.wikipedia.org/wiki/Filipino_language#Filipino_vs._Tagalog
