### ISSUE TITLE
Error when I try to create a custom page

### ISSUE THREAD

**Issue by KarlKonan** [humhub/humhub#3022]
Hi masters of the web
### What steps will reproduce the problem?
I've installed humhub and now i want to create a custom page, it was impossible to download and install it automaticaly so I've done that manually. now I can't create page and the checkbox php based page unchecked even if a checked it and save.

### Additional info
this is what I get when I try to create a new page
`An Error occurred while handling another error:
exception 'ReflectionException' with message 'Method humhub\modules\custom_pages\models\Page::hasAllowedPhpViews() does not exist' in C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\web\ErrorHandler.php:195
Stack trace:
#0 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\web\ErrorHandler.php(195): ReflectionMethod->__construct('humhub\\modules\\...', 'hasAllowedPhpVi...')
#1 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\views\errorHandler\callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('humhub\\modules\\...')
#2 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\View.php(330): require('C:\\wamp64\\www\\l...')
#3 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('C:\\wamp64\\www\\l...', Array)
#4 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\web\ErrorHandler.php(249): yii\base\View->renderFile('@yii/views/erro...', Array, Object(yii\web\ErrorHandler))
#5 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\web\ErrorHandler.php(304): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\web\ErrorHandler.php(326): yii\web\ErrorHandler->renderCallStackItem('C:\\wamp64\\www\\l...', 113, 'humhub\\modules\\...', 'hasAllowedPhpVi...', Array, 7)
#7 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\views\errorHandler\exception.php(381): yii\web\ErrorHandler->renderCallStack(Object(yii\base\InvalidParamException))
#8 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\View.php(330): require('C:\\wamp64\\www\\l...')
#9 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('C:\\wamp64\\www\\l...', Array)
#10 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\web\ErrorHandler.php(249): yii\base\View->renderFile('@yii/views/erro...', Array, Object(yii\web\ErrorHandler))
#11 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\web\ErrorHandler.php(116): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#12 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\InvalidParamException))
#13 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\InvalidParamException))
#14 {main}
Previous exception:
exception 'yii\base\InvalidParamException' with message 'The dir argument must be a directory: C:\wamp64\www\lemarche\protected/modules\humhub-modules-custom-pages-master/views/custom/global_pages/' in C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\helpers\BaseFileHelper.php:404
Stack trace:
#0 C:\wamp64\www\lemarche\protected\modules\humhub-modules-custom-pages-master\components\Container.php(188): yii\helpers\BaseFileHelper::findFiles('C:\\wamp64\\www\\l...', Array)
#1 C:\wamp64\www\lemarche\protected\modules\humhub-modules-custom-pages-master\components\Container.php(169): humhub\modules\custom_pages\components\Container->getAllowedPhpViewFileSelection()
#2 [internal function]: humhub\modules\custom_pages\components\Container->hasAllowedPhpViews()
#3 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\Component.php(287): call_user_func_array(Array, Array)
#4 C:\wamp64\www\lemarche\protected\modules\humhub-modules-custom-pages-master\models\forms\AddPageForm.php(113): yii\base\Component->__call('hasAllowedPhpVi...', Array)
#5 C:\wamp64\www\lemarche\protected\modules\humhub-modules-custom-pages-master\models\forms\AddPageForm.php(113): humhub\modules\custom_pages\models\Page->hasAllowedPhpViews()
#6 C:\wamp64\www\lemarche\protected\modules\humhub-modules-custom-pages-master\views\common\add.php(83): humhub\modules\custom_pages\models\forms\AddPageForm->hasPHPFiles()
#7 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\View.php(330): require('C:\\wamp64\\www\\l...')
#8 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('C:\\wamp64\\www\\l...', Array)
#9 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\View.php(152): yii\base\View->renderFile('C:\\wamp64\\www\\l...', Array, Object(humhub\modules\custom_pages\controllers\AdminController))
#10 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\Controller.php(381): yii\base\View->render('@custom_pages/v...', Array, Object(humhub\modules\custom_pages\controllers\AdminController))
#11 C:\wamp64\www\lemarche\protected\modules\humhub-modules-custom-pages-master\controllers\AdminController.php(86): yii\base\Controller->render('@custom_pages/v...', Array)
#12 [internal function]: humhub\modules\custom_pages\controllers\AdminController->actionAdd(NULL)
#13 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#14 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#15 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('add', Array)
#16 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('custom_pages/ad...', Array)
#17 C:\wamp64\www\lemarche\protected\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#18 C:\wamp64\www\lemarche\index.php(25): yii\base\Application->run()
#19 {main}`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 5.5.12
| Operating system | win 10

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Upgrade to PHP 5.6.

**Comment by KarlKonan** [comment]
I've tried but It's imposible because a got wamp 2.5 and php 5.6 run on
wamp 3.x.x. but I can't download it on the wampserver webpage I can launch
the download but I get a error each time I try.
Thank to help me
Kind regards


2018-02-15 3:23 GMT+00:00 Sarah Tsumayoi <notifications@github.com>:

**Comment by Felli** [comment]
@KarlKonan then I would suggest going through their troubleshooting, as HumHub requires PHP 5.6 to run efficiently. :smile:

**Comment by KarlKonan** [comment]
Lol I'll do that right now.
Thanks a lot.

Le 16 févr. 2018 02:40, "Sarah Tsumayoi" <notifications@github.com> a
écrit :

**Comment by KarlKonan** [comment]
To resolve the last problem I've decided to put my project on a server with
the minimum config, I've found an host. So I've send the setup files on the
server it was too long but succesful tranfers so I want to start the setup
but there is a probleme.
Sorry to be too painful with my problems and my bad english.

I hope that you will able to help me.

this is what I get:

An Error occurred while handling another error:
yii\base\UnknownClassException: Unable to find 'yii\web\Request' in
file: /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/web/Request.php.
Namespace missing? in
/home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php:295
Stack trace:
#0 [internal function]: yii\BaseYii::autoload('yii\\web\\Request')
#1 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/humhub/components/Request.php(19):
spl_autoload_call('yii\\web\\Request')
#2 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php(292):
include('/home/vol14_7/h...')
#3 [internal function]: yii\BaseYii::autoload('humhub\\componen...')
#4 [internal function]: spl_autoload_call('humhub\\componen...')
#5 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(424):
ReflectionClass->__construct('humhub\\componen...')
#6 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(364):
yii\di\Container->getDependencies('humhub\\componen...')
#7 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(156):
yii\di\Container->build('humhub\\componen...', Array, Array)
#8 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php(348):
yii\di\Container->get('humhub\\componen...', Array, Array)
#9 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(135):
yii\BaseYii::createObject(Array)
#10 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(73):
yii\di\ServiceLocator->get('request')
#11 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/humhub/components/View.php(217):
yii\di\ServiceLocator->__get('request')
#12 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/views/errorHandler/exception.php(451):
humhub\components\View->endBody()
#13 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/View.php(330):
require('/home/vol14_7/h...')
#14 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/View.php(250):
yii\base\View->renderPhpFile('/home/vol14_7/h...', Array)
#15 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(249):
yii\base\View->renderFile('/home/vol14_7/h...', Array,
Object(yii\web\ErrorHandler))
#16 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(115):
yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#17 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(111):
yii\web\ErrorHandler->renderException(Object(yii\base\UnknownClassException))
#18 [internal function]:
yii\base\ErrorHandler->handleException(Object(yii\base\UnknownClassException))
#19 {main}
Previous exception:
yii\base\UnknownClassException: Unable to find 'yii\web\Request' in
file: /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/web/Request.php.
Namespace missing? in
/home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php:295
Stack trace:
#0 [internal function]: yii\BaseYii::autoload('yii\\web\\Request')
#1 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/humhub/components/Request.php(19):
spl_autoload_call('yii\\web\\Request')
#2 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php(292):
include('/home/vol14_7/h...')
#3 [internal function]: yii\BaseYii::autoload('humhub\\componen...')
#4 [internal function]: spl_autoload_call('humhub\\componen...')
#5 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(424):
ReflectionClass->__construct('humhub\\componen...')
#6 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(364):
yii\di\Container->getDependencies('humhub\\componen...')
#7 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(156):
yii\di\Container->build('humhub\\componen...', Array, Array)
#8 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php(348):
yii\di\Container->get('humhub\\componen...', Array, Array)
#9 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(135):
yii\BaseYii::createObject(Array)
#10 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(159):
yii\di\ServiceLocator->get('request')
#11 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/humhub/components/Application.php(36):
yii\web\Application->getRequest()
#12 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(272):
humhub\components\Application->bootstrap()
#13 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/Object.php(107):
yii\base\Application->init()
#14 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(205):
yii\base\Object->__construct(Array)
#15 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/index.php(25):
yii\base\Application->__construct(Array)
#16 {main}


2018-02-16 9:22 GMT+00:00 Konan Konan karl <konankonankarl@gmail.com>:

**Comment by Felli** [comment]
@KarlKonan does your server meet all the [Requirements](http://docs.humhub.org/admin-requirements.html) needed?

**Comment by KarlKonan** [comment]
Yes, I've believed that the db name is the source of the problem.

Le 17 févr. 2018 06:14, "Sarah Tsumayoi" <notifications@github.com> a
écrit :
