### ISSUE TITLE
probleme on my server

### ISSUE THREAD

**Issue by KarlKonan** [humhub/humhub#3028]
### What steps will reproduce the problem?
When I transfer the humhub 1.2.4 install files on my server and launch it I can't access to the setup step.
### What is the expected result?
I've tried on my local server there is no probleme
### What do you get instead?
An Error occurred while handling another error:
yii\base\UnknownClassException: Unable to find 'yii\web\Request' in file: /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/web/Request.php. Namespace missing? in /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php:295
Stack trace:
#0 [internal function]: yii\BaseYii::autoload('yii\\web\\Request')
#1 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/humhub/components/Request.php(19): spl_autoload_call('yii\\web\\Request')
#2 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php(292): include('/home/vol14_7/h...')
#3 [internal function]: yii\BaseYii::autoload('humhub\\componen...')
#4 [internal function]: spl_autoload_call('humhub\\componen...')
#5 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(424): ReflectionClass->__construct('humhub\\componen...')
#6 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('humhub\\componen...')
#7 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\componen...', Array, Array)
#8 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('humhub\\componen...', Array, Array)
#9 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#10 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(73): yii\di\ServiceLocator->get('request')
#11 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/humhub/components/View.php(217): yii\di\ServiceLocator->__get('request')
#12 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/views/errorHandler/exception.php(451): humhub\components\View->endBody()
#13 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/View.php(330): require('/home/vol14_7/h...')
#14 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/vol14_7/h...', Array)
#15 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(249): yii\base\View->renderFile('/home/vol14_7/h...', Array, Object(yii\web\ErrorHandler))
#16 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(115): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#17 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\UnknownClassException))
#18 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\UnknownClassException))
#19 {main}
Previous exception:
yii\base\UnknownClassException: Unable to find 'yii\web\Request' in file: /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/web/Request.php. Namespace missing? in /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php:295
Stack trace:
#0 [internal function]: yii\BaseYii::autoload('yii\\web\\Request')
#1 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/humhub/components/Request.php(19): spl_autoload_call('yii\\web\\Request')
#2 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php(292): include('/home/vol14_7/h...')
#3 [internal function]: yii\BaseYii::autoload('humhub\\componen...')
#4 [internal function]: spl_autoload_call('humhub\\componen...')
#5 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(424): ReflectionClass->__construct('humhub\\componen...')
#6 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('humhub\\componen...')
#7 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\componen...', Array, Array)
#8 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('humhub\\componen...', Array, Array)
#9 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#10 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(159): yii\di\ServiceLocator->get('request')
#11 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/humhub/components/Application.php(36): yii\web\Application->getRequest()
#12 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(272): humhub\components\Application->bootstrap()
#13 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/Object.php(107): yii\base\Application->init()
#14 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#15 /home/vol14_7/hebergratuit.net/heber_21619268/htdocs/index.php(25): yii\base\Application->__construct(Array)
#16 {main}

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 7.x 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
W

**Comment by buddh4** [comment]
Sorry, github is not a support forum, please consider asking the [community](http://community.humhub.com/) regarding such issues.
