### ISSUE TITLE
CR: Inserting an image with a link

### ISSUE THREAD

**Issue by daglex** [humhub/humhub#303]
Do you plan to feature the possibility to insert a picture into the message body by reference to the original image? Now perhaps only physically download the image on the server.

**Comment by gvelez17** [comment]
how do you do this with latest version?  I'm not finding protected/config/local/ directory

**Comment by buddha87** [comment]
Think this setting is not availalbe anymore: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/post/controllers/PostController.php#L34
