### ISSUE TITLE
Polling failure logic when user logged out

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#3050]
I have installed [OSSEC](https://ossec.github.io/) on my server and have errors with Humhub.

When a user put his computer to sleep and wake it up again later with Humhub opened on his browser, the javascript still tries to call `/mail/mail/get-new-message-count-json` periodically. But as Humhub has disconnected, it gives a 403 error.

If his browser has Humhub opened in multiple tabs, multiple 403 errors are given periodically and the user gets blacklisted by OSSEC.
The problem occurs also with `/live/poll?last=xxx` which gives a 500 error

**Is there a possibility, when Humhub disconnects, to automatically redirect to the guest dashboard (`dashboard/index_guest.php`) or the login page ?**

This question has been asked here but no answer : https://community.humhub.com/content/perma?id=140543

Thanks

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 7.1
| Operating system | Ubuntu

**Comment by funkycram** [comment]
Precision : users connect threw an IDP (SSO). And in that case the "Default Expire Time" value doesn't seams to change anything.

**Comment by buddh4** [comment]
Yes, the polling needs some failure logic, also tabs should be able to share the poll data so we can avoid some calls perhaps by using `localStorage`.

**Comment by funkycram** [comment]
@luke- I do not see this problem anymore, you can close this issue if outdated.
