### ISSUE TITLE
Add people on space ?

### ISSUE THREAD

**Issue by Spartacus2018** [humhub/humhub#3056]
Hello, 

i have a question about space, so i create my user first (thinking with active directory)
and after that i create my space.

so now i have to add user on space, how i can automticly add user on space?

i lnow how do it when it' s a new user.

but i have to do it with all old user ?

can u have a solution please ?

**Comment by danielkesselberg** [comment]
Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by buddh4** [comment]
There is a console command for adding all users to a certain space: https://github.com/humhub/humhub/blob/v1.3-dev/protected/humhub/docs/guide/admin/console.md

Also there is a [mass user import](https://www.humhub.org/de/marketplace/details?id=22) module.

And this can be done by means of LDAP groups.
