### ISSUE TITLE
Users not receiving confirmation emails

### ISSUE THREAD

**Issue by nichii124** [humhub/humhub#3063]
### What steps will reproduce the problem?
Click the sign up button and enter your email to register a new account.

### What is the expected result?
The user should receive an email with a confirmation link.

### What do you get instead?
The user never receives a confirmation email.

### Additional info

| HumHub version  | 1.2.4
| PHP version | 7.0
| Operating system | OS of webhost? I have no idea what OS they use. 

I had two users tell me that they couldn't register an account because they never received a confirmation email. I went into the email settings located at settings>>>>advanced>>>>E-Mail and changed the mail transport type from PHP to SMTP. I'm attaching a screenshot of the SMTP settings I used and a screenshot of the webmail SMTP settings that is used for my email. 

When I switched to SMTP the emails originally were being sent. This changed however the next day. I had a user who successfully registered an account using a gmail address and I had another user who registered an account with a gmail address and they never received a confirmation email. They checked their spam folder as well as their inbox. I can manually add the user, so it's not that much of a problem, but this kind of thing may stop potential members from joining my website if they don't receive an email. 

I talked with the gmail user directly and that's how I found out about how he never received an email. I obviously can't talk to every person trying to register that I'm not in contact with, so I can't create accounts for them if they don't receive an email. This is a pretty serious problem seeing how I could lose a lot of members who give up on registering when they don't receive an email. I need some help solving this please. I contacted my webhost and they said there's no problem on their end. It's either a problem with gmail or a problem with Hum Hub. They looked at the logs and it showed that all of the confirmation emails were successfully delivered. I verified this myself when I looked at the logs too.

-Nick

![mail client manual settings](https://user-images.githubusercontent.com/23606915/36847333-f73a0280-1d2b-11e8-8560-0e2853707bc8.png)

![ac email settings](https://user-images.githubusercontent.com/23606915/36847359-0d1f632e-1d2c-11e8-9c7c-79c7b4c032c0.png)

**Comment by acs-ferreira** [comment]
Give a try with a Free SMTP service; if emails are delivered, your actual SMTP service should be reviewed.

http://www.serversmtp.com/
or
https://www.sendinblue.com/

**Comment by nichii124** [comment]
Thank you. I'l give that a try if my confirmation emails still aren't being sent to users. Currently there's only one person who hasn't received a confirmation email. I don't know exactly why, but my confirmation email isn't being sent to this person and if one person if affected then there may be others too. If this keeps happening then I'll try your suggestion. I'd prefer to use my webhost email though. It looks more trustworthy if an email is being sent from the website's domain that the user registered on rather than a different domain used by a free service.

**Comment by acs-ferreira** [comment]
No, a "free" service send emails with you domain, not another one.

And, if emails are sent trough SMTP (and logs show that) this has nothing to do with HumHub, sorry.

**Comment by nichii124** [comment]
Well if it has nothing to do with HumHub then where's the problem? I talked to the support team of my webhost and they said that there's nothing wrong on their end. They checked the logs and every email was successfully delivered. It's either a problem with gmail (which I doubt because I was able to register an account with my gmail address) or a problem with HumHub. I've read a thread on here by another person who was having a similar issue, so it may indeed be a problem with HumHub. 

I didn't know SMTP services could send emails with my own domain. In that case I feel better about using one. I'm going to keep the SMTP settings as they are right now as long as there aren't anymore users who haven't received a confirmation email. If this continues then I'll use the free service that was mentioned.

**Comment by Felli** [comment]
If you're using Gmail/GSuite then you have to enable POP/IMAP, did you have anyone check their spam folder? Normally with self-signed SSL, this will still happen.

**Comment by nichii124** [comment]
Do you mean that the user that's supposed to receive the email has to have POP and IMAP enabled? Or were you saying I have to have it enabled? I checked and it's enabled on my account. I don't send the emails from gmail though. I send them through my webhost's domain. admin@asiacollective.net. I'm not sure what kind of email service they use, but I'm fairly certain that POP and IMAP are both enabled since I was able to add my email to thunderbird. 

As for the the user checking his spam folder, he did indeed check it and there was no email there. I registered a new account with my gmail address just to see if I would get an email and an email was indeed sent to my gmail address, but it was in my spam folder. Another user registered using a gmail address and they also received an email. I don't know why this user isn't receiving one. He tried two different gmail accounts and neither of them received any emails.

**Comment by Felli** [comment]
The email address that is being used to send an email should have POP/IMAP enabled if it's a Gmail or GSuite email client.

**Comment by nichii124** [comment]
The email I use to send emails is not a Gmail or GSuite email client. My email has tried delivering confirmation emails to one of my users who has a Gmail account, but the account sending the email is not Gmail and it has POP and IMAP enabled.

**Comment by Felli** [comment]
Might be an issue with the hostname then, I just tried it on my demo server and got my email verification. :thinking:

**Comment by nichii124** [comment]
I just talked to the support staff of my webhost and we managed to finally get this email issue resolved. Originally I was told that there was nothing they could do because the logs showed that the emails were being delivered. A different support team member changed something though which was able to fix this issue. My user finally got the confirmation email sent to him. The staff member I talked to said this:

"Since you're using our spamfilter servers, I have adjusted the internal routing to point directly to rosaline, the server your account is on.

I have also flushed the callout cache both inbound and outbound. Please test again"

I apologize for blaming my issue on Hum Hub. I was just upset and frustrated that I worked hard on my website and I wouldn't even be able to get new members to join because confirmation emails weren't being sent. 

The support staff originally told me that there wasn't any problem on their end, so I thought if it's not an issue on their end then it has to be an issue with Hum Hub. Fortunately that's not the case and everything is working fine now. Thank you everyone for trying to help me and giving me advice. I'll close this issue now.

**Comment by Alexandre5959** [comment]
Hello
I have exactly the same problem impossible to fix it
