### ISSUE TITLE
Photo albums

### ISSUE THREAD

**Issue by Durakoff** [humhub/humhub#310]
Do you plan to add photo albums?
Space, profile?

**Comment by jahd2602** [comment]
Hi, what about this? https://github.com/rifaideen/humhub-modules-album
Why isn't that module in the marketplace? Is there something wrong with it?

**Comment by WASasquatch** [comment]
It has no documentation, and is confusing to use (broken in most mobile browser, and has no appropriate mobile version)

**Comment by jahd2602** [comment]
I am testing it and yes, it has many problems like no translation support,
weak usability and no photo comments (only album comments). Do you think it
would be feasible to continue with that module development, or a new photos
module should be created? I am new to Yii and Humhub but willing to learn
and help.

**Comment by WASasquatch** [comment]
I would create a new one. Use "PhotoAlbum" as source model and make a new
system to extend the core module "file". That way you can capture posted
images in other places and also my a duplicate to their "PhotoAlbum" which
can display images posted to public spaces/profiles.

On Thu, May 14, 2015 at 6:44 PM, Jairo Honorio <notifications@github.com>
wrote:

> I am testing it and yes, it has many problems like no translation support,
> weak usability and no photo comments (only album comments). Do you think it
> would be feasible to continue with that module development, or a new photos
> module should be created? I am new to Yii and Humhub but willing to learn
> and help.
> El may 14, 2015 4:11 PM, "Jordan Thompson" <notifications@github.com>
> escribió:
>
> > It has no documentation, and is confusing to use (broken in most mobile
> > browser, and has no appropriate mobile version)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/humhub/humhub/issues/310#issuecomment-102170459>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/310#issuecomment-102218319>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*
