### ISSUE TITLE
Bug: Password Recovery link to Dashboard

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#3103]
### What steps will reproduce the problem?
Go to the [community site]() and then change `/dashboard` to `/user/password-recovery` which will open up password recovery after click on the HumHub logo and be taken to the dashboard with a broken display. :thinking: 

### What is the expected result?
![screenshot_1](https://user-images.githubusercontent.com/2011633/37575551-24bc5738-2b6b-11e8-9973-d55edf16218f.png)

### What do you get instead?
![screenshot_2](https://user-images.githubusercontent.com/2011633/37575570-37be7302-2b6b-11e8-8d97-33f4366e2ab4.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 5.6 , 7.0, & 7.1
| Operating system | Linux & whatever the community site is running on.

**Comment by acs-ferreira** [comment]
The problem here is the URL, user should be redirected to `/user/account/change-password` if logged in.

**Comment by somnathmondal6781-ship-it** [comment]
Rockets Mandal
