### ISSUE TITLE
Yii 2.0.14 BaseActiveRecord reset relation incompatibility

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3110]
Since Yii 2.0.14 the ` yii/db/BaseActiveRecord.php` resets relations within the `setAttribute()` function introduced by https://github.com/yiisoft/yii2/commit/74dc1cdc307d97757a5105aa38d617c139a0c1bc#diff-e1e996b8f4fad49a953291c4f5fc0931 

This breaks our current [ContentActiveRecord](https://github.com/humhub/humhub/blob/v1.3-dev/protected/humhub/modules/content/components/ContentActiveRecord.php#L346) save logic, since the `content` relation is cleared in https://github.com/yiisoft/yii2/blob/74dc1cdc307d97757a5105aa38d617c139a0c1bc/framework/db/ActiveRecord.php#L520 before the `afterSave` of ContentActiveRecord.

I'am afraid this could also affect other components and modules as well.

Related Yii Issue: https://github.com/yiisoft/yii2/pull/13618

**Comment by vercotux** [comment]
I'm having the exact same problem with one of my components. This is a rather critical issue. And they made everything `private` so it's nearly impossible to workaround.
