### ISSUE TITLE
Add the `space_type_id`field in the space's search attributes

### ISSUE THREAD

**Issue by devantoine** [humhub/humhub#3111]
Hi,

When using the spacetype module with the Enterprise Edition it would be nice to add the `space_type_id`field in the list of search attributes. Like that it would be possible to have a filter with Lucene to have multiple directory pages based on their type.

Currently the only way of doing it we've found is to extend the `Space` model to override the `getSearchAttributes()` method. Is there another way of doing it?

**Comment by devantoine** [comment]
Any update on this one?

**Comment by luke-** [comment]
@devantoine 

The space "type_id" is already added as attribute to search index.
The Enterprise module uses the Space::EVENT_SEARCH_ADD to inject this field to the search attributes.

To search spaces of a particular type, you can do:

```
$searchResultSet = Yii::$app->search->find($keyword, [
            'model' => \humhub\modules\space\models\Space::class,
            'filters' => [
                'type_id' => ($spaceType !== null) ? $spaceType->id : ''
            ]
        ]);
```
