### ISSUE TITLE
Beug email

### ISSUE THREAD

**Issue by Alexandre5959** [humhub/humhub#3113]
Hello, after about 10 hours of research I come to you for help if you can

when my users create an account they do not receive the email in their mailboxes ... I can not understand where the problem comes from I have all set well ..

Thankcs !

**Comment by Alexandre5959** [comment]
http://prntscr.com/ix2v1y
http://prntscr.com/ix2uqm

**Comment by danielkesselberg** [comment]
Hey @Alexandre5959,

you may ask the community (https://community.humhub.com) for help. Issues is for tracking issues ;-) With the given information its nearly impossible to help you. According to the screenshots you are using sendinblue as smtp provider. Do you setup everything correctly (like described here https://help.sendinblue.com/hc/en-us/articles/209463245--How-can-I-get-my-SendinBlue-SMTP-account-activated-).

How does the mail settings tab in humhub looks? Do you selected port 587 as port number and tls as encryption?

**Comment by Alexandre5959** [comment]
Hello @danielkesselberg 
Thancks for your help
it's my config of my pannel http://prntscr.com/ix66zn
it is a web hosting open to all
link : http://s731630660.onlinehome.fr

**Comment by danielkesselberg** [comment]
This looks good so far. You may ask 1and1 or sendinblue for further help.

**Comment by Alexandre5959** [comment]
it does not come from home
because when my users want to create an account they do not receive the mail and php and in smtp

**Comment by danielkesselberg** [comment]
Screenshot https://prnt.sc/ix2v1y says: Humhub could not open a connection to smtp-relay.sendinblue.com. You setup this host as smtp server and humhub tries to open a connection and send the email to your users. This is not working. Maybe Sendinblue SMTP is not enabled for your account or external connections are not allowed by 1and1. Do you tried as Mail Transport Type? You may setup an smtp account with 1and1 and use this as smtp.

**Comment by Alexandre5959** [comment]
I will try I'll let you know thank you!

**Comment by Alexandre5959** [comment]
@danielkesselberg 

Here is the configuration http://prntscr.com/ix6rzh
Error : http://prntscr.com/ix6ref
1and1 http://prntscr.com/ix6s5o

**Comment by danielkesselberg** [comment]
Port + Encryption is wrong. Like 1and1 says: Port 465 with TLS.

**Comment by Alexandre5959** [comment]
It's good ? http://prntscr.com/ix6vmz
@danielkesselberg

**Comment by danielkesselberg** [comment]
Does it work?

**Comment by Alexandre5959** [comment]
No :/ http://prntscr.com/ix6xn9

**Comment by Alexandre5959** [comment]
I have been there since this night and I do not understand anything why it does not work: /

**Comment by danielkesselberg** [comment]
Please share more information the internal server error:

![image](https://user-images.githubusercontent.com/3902676/37988528-6cbc650e-3201-11e8-844f-e833a2584027.png)

**Comment by Alexandre5959** [comment]
@danielkesselberg http://prntscr.com/ix741r

**Comment by danielkesselberg** [comment]
You may share more entries from the logging tab. Maybe you already know: Humhub also offers hosting plans: https://www.humhub.org/en/hosting you have no hussle with hosting/setup/updates etc and support humhub development.

**Comment by Alexandre5959** [comment]
@danielkesselberg 

it costs a lot of money a month
I just have to solve this problem is 400 users register directly on the site .. but it does not work ... and I saw many people with the same problem as me so I do not understand very well why it's so
What information do you need?

**Comment by danielkesselberg** [comment]
I guess 99€/Month is a fair deal but this is up to you. You may visit the logging page again, on the bottom right should be a button flush. Hit this button and then try to register/send an email again. After this you may see new entries at logging tab and share them.

Please keep in mind that the github issue tracker is for issues. You have a configuration issue unrelated to humhub.

**Comment by Alexandre5959** [comment]
it is my version to install on my FTP which bug can be?

**Comment by danielkesselberg** [comment]
> You may visit the logging page again, on the bottom right should be a button flush. Hit this button and then try to register/send an email again. After this you may see new entries at logging tab and share them.

**Comment by Alexandre5959** [comment]
http://prntscr.com/ix7o9j That's after trying to create an account

**Comment by danielkesselberg** [comment]
Looks like the same issue with sendinblue. You cannot connect from your webspace to smtp host. You better ask 1and1 about this issue.

**Comment by Alexandre5959** [comment]
I will contact them tomorrow, I'll get back to you when I have their answer

**Comment by Alexandre5959** [comment]
They said there was no problem on their side

**Comment by Felli** [comment]
Make sure that outgoing emails aren't blacklisted, 1&1 does this a lot as a security failsafe.

**Comment by danielkesselberg** [comment]
I wrote you a script to check smtp connectivity on your webhost: https://gist.github.com/danielkesselberg/17f1ec260b17344c20d43a75294a0a34

Please upload it to your server and execute it. The result on my server looks like this:
![image](https://user-images.githubusercontent.com/3902676/38028267-c1b4a468-3292-11e8-9d1f-5d53b675d99e.png)

**Comment by danielkesselberg** [comment]
In this thread (https://github.com/PHPMailer/PHPMailer/issues/816) cafiah wrote that he had luck with auth.smtp.1and1.fr with port 25 (tls or no encryption - try both)

**Comment by Alexandre5959** [comment]
The sending of mails work since this morning ..
I do not understand how it's arranged I'm not touching anything of the night
