### ISSUE TITLE
Hyperlinks with more than one GET parameter break in private messages

### ISSUE THREAD

**Issue by enguerrand** [humhub/humhub#3115]
### What steps will reproduce the problem?
Put a hyperlink with at least 2 GET parameters into a private message. E.g: 
https://www.example.com?foo=1&bar=2
Send the mail or preview it and click on the link. 

### What is the expected result?
That the browser goes to the clicked url.

### What do you get instead?
The second GET parameter is cut off because the of the ampersand being displayed as &amp;amp; 
This results in a broken link. 
E.g. humhub permalinks lead to "ooops, you took the wrong turn"

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
| Operating system |Server: Debian 9, Client: Debian 9, Firefox

Note that this does not occur in public posts, only in private messages.

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by acs-ferreira** [comment]
Should be posted at https://github.com/humhub/humhub-modules-mail

**Comment by enguerrand** [comment]
Thanks for the info, I opened [https://github.com/humhub/humhub-modules-mail/issues/135](url)
Will close this one...
