### ISSUE TITLE
problem with dynamic links where the web is running behind a proxy 

### ISSUE THREAD

**Issue by carlosvisser** [humhub/humhub#3116]
I apologize if some info is missing. This is my first time writing an issue on GitHub...

According the following [post](https://community.humhub.com/s/installation-and-setup/?contentId=145572) the web does not resolve correctly the dynamic URLs when it is running behind a proxy.

It this case some URLs points to the local IP of web server who it is not reachable.
My solution was modified the code in /protected/vendor/yiisoft/yii2/base/Request.php. Where and how I modified the code is in the linked post.

I don't know if the fix is the better solution but for my installation worked Ok.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | PHP Version 7.0.28-0ubuntu0.16.04.1
| Operating system | Ubuntu 16.04

**Comment by danielkesselberg** [comment]
Hey @carlosvisser! Thank you for reporting this issue. The good news is that with the next humhub release this issue should be solved. Yii2 (the framework humhub is built on) add support for X-Forwarded-Host (https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L712).

**Dont do this when you run Humhub 1.2.4 (the bundled yii2 version does not support this)**

By default headers set by external sources are ignored (https://www.yiiframework.com/doc/api/2.0/yii-web-request#$secureHeaders-detail). You should declare your reserve proxy as trusted host (https://www.yiiframework.com/doc/api/2.0/yii-web-request#$trustedHosts-detail).

The right place to configure a trusted host is protected/config/web.php (http://docs.humhub.org/admin-advanced-configuration.html). Add a section request to components array

```
'request' => [
  'class' => 'humhub\components\Request',
  'trustedHosts' => ['ip-of-reverse-proxy']
]
```

@luke- @buddh4 fyi
