### ISSUE TITLE
$user_id (Verified Accounts)

### ISSUE THREAD

**Issue by darien12** [humhub/humhub#3117]
I'm adding the following to profileheader.php

` <?php if ($user_id=(1)): { ?>  
                 <h1><?= Html::encode($user->displayName); ?> <img src="/admin.png" width="25px" height="auto" style="margin-left: -5px; padding-bottom:3px;"></h1> 
                 <?php } endif; ?> `

I'm wanting to only display the image next to the display name if it's user id 1 a.k.a the admin.

Although I find when I use it every profile the image appears next to the display name

**Comment by danielkesselberg** [comment]
Hey @darien12 ;-)

Please use the [community (https://community.humhub.com)](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by danielkesselberg** [comment]
The issue with your code above is that $user_id=(1) is an assignment. You may try `$user->id == 1`. 1x = assign value to variable, 2x == compare left with right. An assignment inside an if evaluates to true and this is the reason why you see the image next to each user.
