### ISSUE TITLE
Paris is +01:00

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#3120]
See [here](https://community.humhub.com/content/perma?id=146667)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | all
| Operating system | all

**Comment by acs-ferreira** [comment]
This is normal in [DST](https://en.wikipedia.org/wiki/Daylight_saving_time).
Not a bug.

![image](https://user-images.githubusercontent.com/12234510/38414606-4a4915e0-398f-11e8-8229-f74adad46811.png)
