### ISSUE TITLE
Admin not able to administer user who denies profile viewing permission when profile default route is "about"

### ISSUE THREAD

**Issue by enguerrand** [humhub/humhub#3121]
### What steps will reproduce the problem?
in common/config.php add the following setting to change the profile defaultRoute to about:

```php
<?php
return [
    'modules' => [
        'user' => [
             'profileDefaultRoute' => 'about'
        ]   
    ]   
 ];
```
Then change a user's security setting "view your about page" to "deny"
Login as another user and try to view the user's profile.
Login as administrator and try to edit or impersonate the user.

### What is the expected result?
Normal users should be redirected to the "home" section or get a descriptive error message such as "this user does not allow his profile to be viewed", ideally with a link to the user's "home" section.
Admins should still be able to view, edit or impersonate the user.

### What do you get instead?
In all cases, I only get an error message "Ooops, ..wrong turn, Forbidden"

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      |  PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
| Operating system | Debian stretch

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Are you using the `common.php` or `web.php`?

**Comment by enguerrand** [comment]
Not sure how the usage of web.php versus common.php would affect this issue, but my main concern is the fact that the administrator has no way to fix this other than temporarily setting the default route back to the default "home".

**Comment by Felli** [comment]
The `/protected/config/web.php` does pretty much the same in this case but isn't recommended to be used in this way. (I know I'm a rule breaker...)
