### ISSUE TITLE
Creating  a snippet to show files in the dashboard

### ISSUE THREAD

**Issue by ausdai** [humhub/humhub#3122]
### What steps will reproduce the problem?
creating a snippet in the dashboard to show all files in a specific space file directory or to display all available files. 

### What is the expected result?
n/a

### What do you get instead?
n/a

### Additional info

This may not be an issue as such probably more a feature request. Humhub is a great tool as we have just started using it. The main shortfall for this is File management and being able to view all files in the system or by space and directory. Then using the view of your choice in a snippet etc within the Dashboard like a quick reference for the staff. Having to tunnel into spaces and pages and then directories is tedious and off putting for most staff.  Is there anyway to code a snippet to view all files or file directories?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2
| PHP version      | 7.0
| Operating system | Ubuntu 16.04

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
Hi thanks I've added this feature to our whishlist as mentioned in the community thread. In the future please add such issues to the related [module repository](https://github.com/humhub/humhub-modules-cfiles). Once the marketplace is ready you should use the marketplace to discuss new features etc.
