### ISSUE TITLE
(Sometimes) Comments are not correctly aligned

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3123]
See an example here, second comment.

https://community.humhub.com/content/perma?id=136929

![image](https://user-images.githubusercontent.com/12234510/38415189-f8a85f3c-3990-11e8-8bb8-8788b2c04e49.png)

Produced also on my installation, HH `master`

**Comment by buddh4** [comment]
Does this always appear for you? I don't see this issue on firefox or chrome. Which borwser are you using?

**Comment by buddh4** [comment]
Would be great if you could inspect this issue a by means of the developer tools next time it occures. I've not noticed it yet, but I'll also keep an eye on it.

**Comment by acs-ferreira** [comment]
@buddh4 the (many) places where i can find this bug at the Community platform, i found that on thos comments, i have this code

![image](https://user-images.githubusercontent.com/12234510/38446238-4d1b0be4-39f7-11e8-9521-bcab9ed7a301.png)

Th loaded `<script>` and an empty `<a>`.

On bug free comments, i don't have these:

![image](https://user-images.githubusercontent.com/12234510/38446290-7e8d3b98-39f7-11e8-9cb2-297dec18eefd.png)

**Comment by buddh4** [comment]
Does it work after removing the empty `<a>` ?

**Comment by acs-ferreira** [comment]
Here: https://community.humhub.com/content/perma?id=156902

![image](https://user-images.githubusercontent.com/12234510/42639820-392476a2-85f1-11e8-94e0-052149c0c2f0.png)
