### ISSUE TITLE
Humhub 1.2.4 works only with PHP 7.1

### ISSUE THREAD

**Issue by petrk94** [humhub/humhub#3124]
Hello Github Community,

I just wanted tell you my last problem I have noticed.
On my shared host Uberspace I had PHP 7.2 activated. But this caused a problem with yii, that "object" seems to be reserved, see this here: https://github.com/yiisoft/yii2/issues/14823
If I try to open the site, I get a ERROR 500

After changing to PHP 7.1 it worked and I could enter all data, what it showed me was that the "query" table was in the MySQL database, after removing this created table, the installation was successful. 
Please notice it and write it somewhere in the documentation.

Thanks

**Comment by Felli** [comment]
This is already known and discussed many times, HumHub isn't ready just yet for PHP 7.2, it is recommended to use PHP 5.6/7.0/7.1 only.

**Comment by petrk94** [comment]
@Felli is it somewhere in the docs noticed?
Because I recommend here to update the requirements page:
http://docs.humhub.org/admin-requirements.html#server-requirements

> **Server Requirements**
> Shell access (e.g. ssh) to server
> **PHP 5.6 or later**
> MySQL (5.1 or later) or MariaDB with InnoDB storage engine installed
> A minimum 500 MB of free disk space
> A minimum 64 MB of memory allocated to PHP
> A minimum of 50 MB of database space

Everyone who has no information about it, will ask itself why its not working with PHP 7.2

**Comment by Felli** [comment]
Normally we always get this question on the community site, which we always answer the same, PHP 5.6 is the best recommendation for HumHub at this time Yii had issues with the `Object` class which was changed to `BaseObject` to fix this issue, HumHub hasn't done this as of yet in any live/stable versions of HumHub, it'll most likely work its way in around `v1.3` if not `v.1.4` will be the version it makes it in.

**Comment by acs-ferreira** [comment]
Only HumHub **v1.3** is PHP 7.2 ready.
See https://github.com/humhub/humhub/pull/3016

**Comment by petrk94** [comment]
Is there already a plan when v1.3 get released? I could not find a project/roadmap.

**Comment by acs-ferreira** [comment]
Work in progress. You can also contribute/test here
https://github.com/humhub/humhub/tree/v1.3-dev

**Comment by petrk94** [comment]
@acs-ferreira 
thanks for the information
