### ISSUE TITLE
I want to change background color of Login Page

### ISSUE THREAD

**Issue by MiraclePK** [humhub/humhub#3125]
##631  I want to change background color of login page.

please suggest 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Please ask these types of questions on the [community site](https://community.humhub.com/dashboard) with as much detail as possible.
