### ISSUE TITLE
When people sign up to new site the get 500 PHP warning esccapsheelcmd() disabled

### ISSUE THREAD

**Issue by rduinmaijer** [humhub/humhub#3129]
### What steps will reproduce the problem?
New site, new sign-up
From the open dashboard part, /index.php?r=dashboard%2Fdashboard
### What is the expected result?
Create an account

### Additional info
`
{
    "url": "/app/index.php?r=user%2Fauth%2Flogin",
    "status": 500,
    "response": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;escapeshellcmd() has been disabled for security reasons&#039; \n\nin /home/public_html/app/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php:259\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleError(2, &#039;escapeshellcmd(...&#039;, &#039;/home/duinma23/...&#039;, 259, Array)\n#1 /home/*/public_html/app/protected/vendor...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;escapeshellcmd() has been disabled for security reasons&#039; \n\nin /home/*/public_html/app/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php:259\n\nStack trace:\n#0
`
| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.5
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by acs-ferreira** [comment]
See https://github.com/humhub/humhub/issues/2716
