### ISSUE TITLE
Profile Picture Upload results in server error 400 (Bad Request)

### ISSUE THREAD

**Issue by javajim2018** [humhub/humhub#3130]
Hi all,

I'd be glad if anyone could help. The issues I found here offered no solution whatsoever.
Thanks alot in advance!!
 
So here we go:

### What steps will reproduce the problem?

Uploading the admins (my) profile picture or banner. 
The image is 200x200 pixel wide. I tried with bigger ones as well.

### What is the expected result?

I expected the progress bar to dissapear, the image to be uploaded and to be displayed.

### What do you get instead?

The progress bar gets to 100% and halts. That's where it stays. A refresh shows the default image.

The chrome console gives me this: 
"Failed to load resource: the server responded with a status of 400 (Bad Request)"

### Additional info

I'm using PHP 5.6.

The upload of the profile image and banner of a space on the other hand works like a charm. 

I tried with HumHub 1.25 and 1.24.
I also tried with chrome and firefox on MacOs High Sierra 10.13.4 (17E199). 

The installation showed no errors, said everything is fine. On top of my problem, I wasn't able to delete the example users. I was able to do this directly in the database though.

**Comment by acs-ferreira** [comment]
Are the **File Permissions** correctly set?
http://docs.humhub.org/admin-installation.html#file-permissions

**Comment by javajim2018** [comment]
Thanks for the reply! Yes, after several tries I chose the mallet method by changing the rights to 772 (write in every category) for the whole directories, files and subdirectories of "assets", "protected" and "uploads" as well.

**Comment by buddh4** [comment]
Is there any error visible in "Administration -> Information -> Logging" ?

**Comment by javajim2018** [comment]
Hello Luke, thanks for your reply. I'm embarassed to ask, but where do I find the php.ini? It's not in the humhub root directory on my webserver?

**Comment by luke-** [comment]
@javajim2018 this configuration needs to be set somewhere in your server configuration.
You can also try to add this to your .htaccess file or add following lines to your index.php

```
ini_set('arg_separator.output','&');
ini_set('arg_separator.input','&');
```

**Comment by javajim2018** [comment]
Thanks to all, luke found a solution to this. 
These two lines:

ini_set('arg_separator.output','&');
ini_set('arg_separator.input','&');

have to be inserted into humhubs "index.php" directly into the line after "<?php".

This did the trick!
