### ISSUE TITLE
Connection could not be established with host smtp.gmail.com [ #0]

### ISSUE THREAD

**Issue by watoo** [humhub/humhub#3140]
### What steps will reproduce the problem?
![image](https://user-images.githubusercontent.com/5346797/39098366-3a8ae6c8-4683-11e8-89f4-ec98f69b5c10.png)

### What is the expected result?
I'm using same email in another (Asp.Net MVC)application! but its not working in humhub.
### What do you get instead?

![capture](https://user-images.githubusercontent.com/5346797/39098425-43ecf37c-4684-11e8-91d7-64cb78e88927.PNG)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.5
| PHP version      |  7.0.29.0
| Operating system | Windows

**Detailed log error:**
exception 'Swift_TransportException' with message 'Connection could not be established with host smtp.gmail.com [ #0]' in D:\home\site\wwwroot\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:268 Stack trace: #0 D:\home\site\wwwroot\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection() #1 D:\home\site\wwwroot\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array) #2 D:\home\site\wwwroot\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start() #3 D:\home\site\wwwroot\protected\vendor\yiisoft\yii2-swiftmailer\Mailer.php(146): Swift_Mailer->send(Object(Swift_Message)) #4 D:\home\site\wwwroot\protected\vendor\yiisoft\yii2\mail\BaseMailer.php(262): yii\swiftmailer\Mailer->sendMessage(Object(humhub\components\mail\Message)) #5 D:\home\site\wwwroot\protected\vendor\yiisoft\yii2\mail\BaseMessage.php(48): yii\mail\BaseMailer->send(Object(humhub\components\mail\Message)) #6 D:\home\site\wwwroot\protected\humhub\modules\user\models\Invite.php(137): yii\mail\BaseMessage->send() #7 D:\home\site\wwwroot\protected\humhub\modules\user\models\Invite.php(110): humhub\modules\user\models\Invite->sendInviteMail() #8 D:\home\site\wwwroot\protected\humhub\modules\user\controllers\AuthController.php(80): humhub\modules\user\models\Invite->selfInvite() #9 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin() #10 D:\home\site\wwwroot\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) #11 D:\home\site\wwwroot\protected\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array) #12 D:\home\site\wwwroot\protected\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('login', Array) #13 D:\home\site\wwwroot\protected\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('user/auth/login', Array) #14 D:\home\site\wwwroot\protected\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #15 D:\home\site\wwwroot\index.php(25): yii\base\Application->run() #16 {main}

**Comment by watoo** [comment]
I found a solution on google, i.e, 
```
$options['ssl']['verify_peer'] = FALSE;
$options['ssl']['verify_peer_name'] = FALSE;
```

But when I found the code in protected/humhub/libs/DynamicConfig.php, the following code was commented:

              ```
if (Yii::$app->settings->get('mailer.allowSelfSignedCerts')) {
              $mail['transport']['ssl']['allow_self_signed'] = true;
              $mail['transport']['ssl']['verify_peer'] = false;
              }
```

When I uncommented the code, I got this error:
![image](https://user-images.githubusercontent.com/5346797/39203883-8d2994aa-480f-11e8-8779-7c4087615f01.png)

Can anyone please help me? I have tried all options but no one is working.

**Comment by danielkesselberg** [comment]
Could you try to check allow self signed certificates?

**Comment by watoo** [comment]
Hi @danielkesselberg , I have tried following combinations with allow self signed certificates checked. But no one seems to be working.

Port Number | Encrypton Type | Error
------------ | -------------
587 | SSL | Connection could not be established with host ..
587 | TLS | Connection could not be established with host..
465 | SSL | Connection could not be established with host ..
465 | TLS | Expected response code 200 but got response code

**Comment by danielkesselberg** [comment]
Please read this thread: https://github.com/humhub/humhub/issues/3113 and try this script https://gist.github.com/danielkesselberg/17f1ec260b17344c20d43a75294a0a34 (you may adjust $hostname to your needs).

**Comment by watoo** [comment]
![image](https://user-images.githubusercontent.com/5346797/39258559-b3a5d90e-48cd-11e8-90ad-ae79e159821c.png)

and when I tried to use this host name:
![image](https://user-images.githubusercontent.com/5346797/39258701-05a6d136-48ce-11e8-9347-97f9dcb69a91.png)

**Comment by danielkesselberg** [comment]
Could you https://mailtrap.io/ or another fake smtp service?

**Comment by danielkesselberg** [comment]
> If your Gmail account uses 2-Step-Verification, you must generate an App password and use it as the value of the mailer password. You must also ensure that you allow less secure apps to access your Gmail account.

http://symfony.com/doc/current/email.html#using-gmail-to-send-emails

Allow less secure apps: https://support.google.com/accounts/answer/6010255
Generate app password (only if 2-Step-Verification): https://support.google.com/accounts/answer/185833

**Comment by watoo** [comment]
Two step verification is off and access for less secure apps is on.

**Comment by watoo** [comment]
When I'm on TLS encryption type I get error:

stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

It's solution is to set verify_peer => false and verify_peer_name => false.

Maybe we should try this too. (Please see my second comment on this issue)

**Comment by watoo** [comment]
Finally, added this line in streamBuffer.php and it worked!
`
$options = array_merge($options, array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));`

**Comment by adeolaalabi2017** [comment]
Hello @watoo 
Kindly throw a little more little on this line in streamBuffer.php. 
$options = array_merge($options, array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));
i v tried without success.
Thanks in anticipation

**Comment by watoo** [comment]
I fixed email sending issue by adding following line in **protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport.streamBuffer.php**

![image](https://user-images.githubusercontent.com/5346797/40276460-37100760-5c24-11e8-82ee-c848841c6a98.png)

**Comment by adeolaalabi2017** [comment]
Ohh...waooow..
Thanks...so much.
Much appreciate.

**Comment by diorkhodja** [comment]
Hi @watoo !
Could you tell me where I can find this file "protected/humhub/libs/DynamicConfig.php" as you wrote above. I'm also cant solve this problem for about 2-3 hours. Also I tried everything which you guys have written here. Thanx for answer, before)

**Comment by watoo** [comment]
@diorkhodja , why you need DynamicConfig.php? You just have to change one line in streamBuffer.php.

https://github.com/humhub/humhub/issues/3140#issuecomment-390461822

**Comment by buddh4** [comment]
You should not overwrite an vendor classes rather do this by configuration as mentioned [here](https://stackoverflow.com/questions/31039204/swiftmailer-from-advanced-yii-2-0-does-not-work-with-gmail).

You'll have to add something like this to your `protected/config/common.php` (I've not tested this):
```
return [
  'components' => [
    'mailer' => [
      'transport' => [
        'streamOptions' => [ 
          'ssl' => [ 
            'allow_self_signed' => true,
            'verify_peer' => false,
            'verify_peer_name' => false,
          ]
        ]
      ]
    ]
  ]
];
```

**Comment by 8khan** [comment]
Yes, adding "streamOptions" at the "transport" config solve the problem on gmail and outlook smtp configurations

**Comment by az-vm** [comment]
Hello,

By default the configuration above works:

- smtp.google.com
- port: 587
- TLS
- SMTP AUTH Required - Checked
- Email
- Pass


In Other servers:

- smtp.google.com
- port: 465
- SLL
- SMTP AUTH Required - Checked
- Email
- Pass


I have tested and worked in some cases the second config.

Cheers,
Vitor

**Comment by sagar999-stack** [comment]
> Finally, added this line in streamBuffer.php and it worked!
> ` $options = array_merge($options, array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));`



> I fixed email sending issue by adding following line in **protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\streamBuffer.php**
> 
> ![image](https://user-images.githubusercontent.com/5346797/40276460-37100760-5c24-11e8-82ee-c848841c6a98.png)



> Finally, added this line in streamBuffer.php and it worked!
> ` $options = array_merge($options, array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));`

I have same issue. I added this line but can not solve

**Comment by dNanda777** [comment]
> Finally, added this line in streamBuffer.php and it worked!
> ` $options = array_merge($options, array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false)));`

Thanks for the solution! now the confirmation is sent.
