### ISSUE TITLE
PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_openssl.dll' 

### ISSUE THREAD

**Issue by Spartacus2018** [humhub/humhub#3143]
### What steps will reproduce the problem?
When i connect on internet explorer
### What is the expected result?
acces to  my humhub

### What do you get instead?

```
an page error : 

PHP Core Warning – yii\base\ErrorException 

PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_openssl.dll' - /usr/lib/php/20151012/php_openssl.dll: cannot open shared object file: No such file or directory



2.    yii\base\ErrorHandler::handleFatalError()  



$_COOKIE = [
    '_ga' => 'GA1.2.915029600.1489393530',
];
 

Yii Framework 
2018-05-07, 08:33:33

Apache/2.4.18 (Ubuntu)

Yii Framework/2.0.12
```
![image](https://user-images.githubusercontent.com/301074/39688175-c7ce7d16-51d1-11e8-8018-1bfe8f48c9f0.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | PHP 7.0.28-0ubuntu0.16.04.1
| Operating system | Ubuntu serveur 16.04

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
This is not related to humhub but rather your php environment.
