### ISSUE TITLE
Attachment upload doesn't work -> Attachment corrupted

### ISSUE THREAD

**Issue by dave90dave** [humhub/humhub#3145]
### What steps will reproduce the problem?
Uploading photo attachements in comments and posts
### What is the expected result?
That the upload finishes and shows the attachment when i click it
### What do you get instead?
We can't show the picture "site.com/img.jpg" because the image is corrupted.
When I take a look at the log files there is a warning with the text: File was only partially uploaded
I use firefox, but it gives the same problem on other browsers.
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.5
| PHP version      |  7.0.29
| Operating system | Windows 8.1

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by LThecross** [comment]
Could you try again and provide a truncated error log of apache/nginx/ISS... and the full error log in Administration --> Information --> Logging ?
