### ISSUE TITLE
Upload space picture dose not use file size setting in HumHub

### ISSUE THREAD

**Issue by arnfinnkristensen** [humhub/humhub#3148]
### What steps will reproduce the problem?
Go to the space and add a new space picture (the picture has to be over 3,2mb). Make sure that your local file size settings allow to upload pictures that are lagre then 3.2 mb. See the picture below:

![image](https://user-images.githubusercontent.com/30318362/40041083-18efaaa2-581d-11e8-851c-025f0e56998f.png)
 
This is the file I'm try to uploade:

![image](https://user-images.githubusercontent.com/30318362/40041505-827ec3ee-581e-11e8-93c0-dbe213ca3923.png)

### What is the expected result?
That the picture sould be uploaded.

### What do you get instead?
Message that tels me that the picture is to lagre.

![image](https://user-images.githubusercontent.com/30318362/40041106-30edd732-581d-11e8-9861-158e6f4d505a.png)

### Additional info

We have seen that this restricition is hard coded into the code, \humhub\models\forms\UploadProfileImage

![image](https://user-images.githubusercontent.com/30318362/40048800-73d592b8-5833-11e8-9221-322883eed3a6.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 7.1.x
| Operating system | Win 10

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by arnfinnkristensen** [comment]
@luke- Have you investigated this issue?

**Comment by acs-ferreira** [comment]
Try https://github.com/humhub/humhub/pull/3151/files
