### ISSUE TITLE
handleFatalError

### ISSUE THREAD

**Issue by sam11fr** [humhub/humhub#3149]
### What steps will reproduce the problem?
Step 1 = Upgrade Humhub 1.2.5 to 1.2.6.
Step 2 = consulte a profil's member.

### What is the expected result?
the profile of a member or even mine

### What do you get instead?
Error message:
exception 'yii\base\ErrorException' with message 'Cannot use humhub\modules\user\models\User as User because the name is already in use' in /protected/humhub/modules/user/components/BaseAccountController.php:12 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main} 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.6
| PHP version      | 5.6.33
| Operating system | I Don't know: OVH linux

Everything else works well so far.
Thank you in advance for any help you can give.
Sam

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/commit/77a76f5e7e39f334cc32eec20eb786cfd4a4db62

**Comment by sam11fr** [comment]
Okay, friends.
The problems disappeared when I disabled the module  "Legal Tools 1.0.3". So I'm going to post a ticket on the relevant module.
I'm closing this ticket.
Kind regards

**Comment by sam11fr** [comment]
Hello everyone.
Sorry to reopen this ticket. I still have problems accessing the profiles.

exception 'yii\base\ErrorException' with message 'Cannot use humhub\modules\user\models\User as User because the name is already in use' in /home/amoilalepy/www/protected/humhub/modules/user/components/BaseAccountController.php:12 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main} 

@buddh4 : Humhub is well upgraded to the latest version. This should solve this problem but it is not.

I used the shell / protected / yii to do a database check and a reindex of the search engine. Nothing I did had a positive effect.

I need help !

**Comment by sam11fr** [comment]
Fixed an issue by removing the "Legal Tools 1.0.3" module.
Cloture of the ticket.
Best regards

**Comment by sam11fr** [comment]
@buddh4: Thank you for your help.
I commented on line 12 of the file "/protected/humhub/modules/user/components/BaseAccountController.php" which contained "use humhub\modules\user\models\User;".
Since this change, everything is working properly.
Question: Should this change not have been done when upgrading to version 1.2.6?

Anyway thank you very much !!!

**Comment by buddh4** [comment]
This bug was introduced with 1.2.6. Today there will be a fixed version available, which will also add the legal module menu items (footer menu) to the profile dropdown navigation in the mobile view.

**Comment by sam11fr** [comment]
Oh ok !
I did not have this information. I will install the patch as soon as possible.
Thank you for the info.

Regards
