### ISSUE TITLE
Search rebuild issues

### ISSUE THREAD

**Issue by laurent7878** [humhub/humhub#3152]
## What steps will reproduce the problem?
grunt build-assets

OR 

php yii search/rebuild
### What do you get instead?
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.

OR 

PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /home/stw/www/myspace/protected/vendor/yiisoft/yii2/base/Object.php on line 77

### Additional info
I cannot rebuild search. I'm new to grunt, so where are files? How to solve yii problem with objects?(I've tried with helps only for yii framework but I get error 500)
| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.7
| PHP version    5.6.36  | 
| Operating system ubuntu 18 |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
HumHub requires PHP 5.6 or later

**Comment by acs-ferreira** [comment]
Can you provide the full error stacks from `Administration --> Information --> Logging`?

And also the output of `Administration --> Information --> Prerequisites`.

**Comment by buddh4** [comment]
Did you call your grunt command at the root or within the protected directory? The second error seems to be a php 7.2 error which is only supported in the upcoming HumHub v1.3
