### ISSUE TITLE
Public space is revealing members list

### ISSUE THREAD

**Issue by 001101** [humhub/humhub#3153]
### What steps will reproduce the problem?
Set up a public space, anything else is complete private

### What is the expected result?
Crawlers can list the members list under this URL
domain.net/s/thespace/space/membership/members-list?page=15&per-page=8
domain.net/s/thespace/space/membership/members-list?page=22&per-page=8
etc. pp.

### What do you get instead?
More privacy for the users

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.5
| PHP version      |  7.0
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
So you want `members-list` not to be accessible by guests?

**Comment by Felli** [comment]
Should be possible to make it so that space admin can choose between allowing guest access or not allowing it, I wouldn't mind such an addition to the platform. :thinking:

**Comment by Ace2213** [comment]
Similar to #3720 but also affecting header counters, for both spaces and user profiles.

**Comment by luke-** [comment]
Actually it is intentional that the member list of a public space is also public.

We do not currently plan to restrict this further - this would probably need a redesign to avoid leaks in many areas e.g. in search/mentioning/profiles/widgets etc..
