### ISSUE TITLE
Access denied for user in installation phase 

### ISSUE THREAD

**Issue by ShouldWeKnow** [humhub/humhub#3155]
### What steps will reproduce the problem?
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.7?
| PHP version      | 7
| Operating system  |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Please keep general issues on the community site, I've already answered the question you asked [there](https://community.humhub.com/content/perma?id=58765https://community.humhub.com/content/perma?id=153497).

**Comment by lisandi** [comment]
Hi Felli could you please correct the link- thanks. when following it shows "Oooops... It looks like you may have taken the wrong turn.
Could not find requested content!"

Thanks
