### ISSUE TITLE
ERROR: yii\base\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by Tahrz** [humhub/humhub#3164]
### What steps will reproduce the problem?

php 7.2 on server

### What is the expected result?

Installing HumHub

### What do you get instead?

error `yii\base\Object as Object because 'Object' is a special class name`

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.7
| PHP version    |  7.2 
| Operating system  | Ubuntu 18.05 LTS

**Comment by danielkesselberg** [comment]
https://github.com/humhub/humhub/issues/3124
