### ISSUE TITLE
Problem with pathMap

### ISSUE THREAD

**Issue by Tahrz** [humhub/humhub#3172]
### What steps will reproduce the problem?
add in protected/config/web.php 
```php
'components' => [
        'view' => [
            'theme' => [
                'pathMap' => [ 
                    '@app/vendor/onmotion/yii2-gallery/views' => '@app/../themes/HumHub/views/gallery',
                ],
            ],
        ],
    ],
```

### What is the expected result?

Change default views in onmotion gallery 

### What do you get instead?

Views doesn`t change...

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.7
| PHP version      |  7.1
| Operating system | Ubuntu

> Note: in Theme class you force change `pathMap` (55 line)... so any configuration to `pathMap` does not make sense. 
```php
public function init()
    {
        if ($this->getBasePath() == '') {
            $this->setBasePath('@webroot/themes/' . $this->name);
        }

        $this->pathMap = [
            '@humhub/views' => $this->getBasePath() . '/views',
        ];

        parent::init();
    }

```

> How i can change default views of module, without fix Theme class like: 

```php
 $this->pathMap = array_merge($this->pathMap, [
            '@humhub/views' => $this->getBasePath() . '/views',
        ]);
```
 ??

**Comment by buddh4** [comment]
Feel free to open a pull request.

**Comment by Tahrz** [comment]
Done -> [pull/3179](https://github.com/humhub/humhub/pull/3179)
