### ISSUE TITLE
New logo is not really saved 

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#3173]
### What steps will reproduce the problem?

1. I upload a new logo for my theme. A preview in the config line is shown, but when I press save the old logo is displayed in the headline.
2. So I tried deleting the old logo first, then upload the new one. Still switches back to the old logo after pressing the save button.
3. When deleting the old logo and pressing save button the logo gets canceled and is not displayed anymore, but when uploading the new logo in a second step and pressing the save button, the old - already canceled logo (!) - appears in the headline again. 

### What is the expected result?

The newly uploaded logo should be placed in my theme headline

### What do you get instead?

Always the old logo.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.7
| PHP version      |  5.6.34
| Operating system | n.a.

**Comment by acs-ferreira** [comment]
These are some strange cache behaviors for sure.

Also make a little search about this, there are other topics about this behavior.
