### ISSUE TITLE
Calendar module, can't add events from mobile phone

### ISSUE THREAD

**Issue by sarz4fun** [humhub/humhub#3174]
### What steps will reproduce the problem?

Android smartphone, chrome. 
Tap on a day to add an event in calendar module
### What is the expected result?
Open event popup form
### What do you get instead?
Nothing. 
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2. 7
| PHP version      | 7.0
| Operating system | wamp 64 / ws2008r2

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Please open an issue in the modules repo [here](https://github.com/humhub/humhub-modules-calendar/issues). :+1:
