### ISSUE TITLE
i want to add custom filter in calender module but filter is not working with i am selecting two of more checkbox but ..it is working fine with single select..please sove this issue as soon as possible.

### ISSUE THREAD

**Issue by pushpendra90** [humhub/humhub#3184]
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
Please add the issue to the modules repository https://github.com/humhub/humhub-modules-calendar

Also describe your problem within the "Write" textarea and not in the title. Describe your problem step for step so we can recreate it, your description is not very specific. Which filter did you activate etc....
