### ISSUE TITLE
Deactivate 'Account delete'

### ISSUE THREAD

**Issue by Richies97** [humhub/humhub#3186]
I am trying to make it impossible for users to attend the Page where they can delete there user (index.php?r=user%2Faccount%2Fdelete). But i just can't figure out which file to edit, nether can i figure out if you can deactivate it anyhow.

Is this even possible, if so where can i do this?

| Q                | A
| ---------------- | ---
| HumHub version   |  1.2.7

**Comment by luke-** [comment]
Currently, there is no option available for this.

You need to develop a module which uses events to deactive this.

**Comment by buddh4** [comment]
Note: in v1.3 there will be a soft delete which prevents data loss
