### ISSUE TITLE
Push Notification throw errors

### ISSUE THREAD

**Issue by Richies97** [humhub/humhub#3187]
I wanted to make it possible to have nice Push Notifications in HumHub so i followed the Tutorial on the HumHub-Page (http://docs.humhub.org/admin-push-updates.html)

So as described in the article we now should get now Push Notifications.

But all I get is this:

`ReflectionException: Class humhub\modules\live\driver\Push does not exist in /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/di/Container.php:424 Stack trace: #0 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/di/Container.php(424): ReflectionClass->__construct('humhub\\modules\\...') #1 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('humhub\\modules\\...') #2 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array) #3 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('humhub\\modules\\...', Array, Array) #4 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/humhub/modules/live/components/Sender.php(34): yii\BaseYii::createObject(Array) #5 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\modules\live\components\Sender->init() #6 [internal function]: yii\base\Object->__construct(Array) #7 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array) #8 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array) #9 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('humhub\\modules\\...', Array, Array) #10 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(135): yii\BaseYii::createObject(Array) #11 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(73): yii\di\ServiceLocator->get('live') #12 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/humhub/modules/live/controllers/PollController.php(57): yii\di\ServiceLocator->__get('live') #13 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Controller.php(154): humhub\modules\live\controllers\PollController->beforeAction(Object(yii\base\InlineAction)) #14 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array) #15 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('live/poll', Array) #16 /usr/www/users/gkuiyb/!asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #17 /usr/www/users/gkuiyb/!asset/versions/1.01/index.php(25): yii\base\Application->run() #18 {main}`

When i look to the directory where the config of HumHub expect the driver to be. There is nothing but BaseDriver.php und Database.php

I hope you can help me with this problem

### Additional info

Running HumHub: 1.2.7

**Comment by luke-** [comment]
Sorry, this documentation page belongs to the upcoming 1.3.x release.

**Comment by buddh4** [comment]
Also note that this is not a [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) implementation but rather a push mechanism for humhub live updates, which is by default handled by a polling job. A real Push API integration is planned soon.

**Comment by mzch** [comment]
In 1.3.13, the same exception is thrown:

```
An Error occurred while handling another error:
ReflectionException: Class \humhub\modules\live\driver\Push::class does not exist in /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php:428
Stack trace:
#0 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(428): ReflectionClass->__construct('\\humhub\\modules...')
#1 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('\\humhub\\modules...')
#2 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('\\humhub\\modules...', Array, Array)
#3 /srv/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('\\humhub\\modules...', Array, Array)
#4 /srv/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#5 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('live', true)
#6 /srv/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('live')
#7 /srv/humhub/protected/humhub/widgets/CoreJsConfig.php(40): yii\di\ServiceLocator->__get('live')
#8 /srv/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\widgets\CoreJsConfig->run()
#9 /srv/humhub/protected/humhub/modules/ui/view/components/View.php(247): yii\base\Widget::widget()
#10 /srv/humhub/protected/vendor/yiisoft/yii2/views/errorHandler/exception.php(526): humhub\modules\ui\view\components\View->endBody()
#11 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(336): require('/srv/humhub/pro...')
#12 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/srv/humhub/pro...', Array)
#13 /srv/humhub/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(266): yii\base\View->renderFile('/srv/humhub/pro...', Array, Object(yii\web\ErrorHandler))
#14 /srv/humhub/protected/vendor/yiisoft/yii2/web/ErrorHandler.php(126): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#15 /srv/humhub/protected/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(ReflectionException))
#16 [internal function]: yii\base\ErrorHandler->handleException(Object(ReflectionException))
#17 {main}
Previous exception:
ReflectionException: Class \humhub\modules\live\driver\Push::class does not exist in /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php:428
Stack trace:
#0 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(428): ReflectionClass->__construct('\\humhub\\modules...')
#1 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('\\humhub\\modules...')
#2 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('\\humhub\\modules...', Array, Array)
#3 /srv/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('\\humhub\\modules...', Array, Array)
#4 /srv/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#5 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('live', true)
#6 /srv/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('live')
#7 /srv/humhub/protected/humhub/widgets/CoreJsConfig.php(40): yii\di\ServiceLocator->__get('live')
#8 /srv/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\widgets\CoreJsConfig->run()
#9 /srv/humhub/protected/humhub/modules/ui/view/components/View.php(247): yii\base\Widget::widget()
#10 /srv/humhub/themes/FlatHub/views/layouts/main.php(61): humhub\modules\ui\view\components\View->endBody()
#11 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(336): require('/srv/humhub/the...')
#12 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/srv/humhub/the...', Array)
#13 /srv/humhub/protected/humhub/components/Controller.php(135): yii\base\View->renderFile('/srv/humhub/the...', Array, Object(humhub\modules\dashboard\controllers\DashboardController))
#14 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(385): humhub\components\Controller->renderContent('\n<div class="co...')
#15 /srv/humhub/protected/humhub/modules/dashboard/controllers/DashboardController.php(69): yii\base\Controller->render('index', Array)
#16 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex()
#17 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array)
#20 /srv/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array)
#21 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#22 /srv/humhub/index.php(25): yii\base\Application->run()
#23 {main}
```
