### ISSUE TITLE
Moving content stops content loading

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#3200]
### What steps will reproduce the problem?
Try moving content to another space then scroll down and loading will stop.

### What is the expected result?
In page loading should happen but doesn't.

### What do you get instead?
A stop of loading.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.0-beta.1
| PHP version      | 5.6/7.0
| Operating system | Linux/Community site OS

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
Can't reproduce this, are there any javascript errors?

**Comment by buddh4** [comment]
Ok is reproducable on the dashboard but not on space stream.
