### ISSUE TITLE
Create empty links on v1.3

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3209]
### What steps will reproduce the problem?
Create a post, immediately click on "Link" button on the MDE. (it's OFF but we can click).
Fill in form (link and tittle).

PS: We also can't insert `mailto` links.

![image](https://user-images.githubusercontent.com/12234510/42635138-7aec06e2-85e5-11e8-8d43-f84296ed6965.png)

### What is the expected result?
Link is created.

### What do you get instead?
Empty link.

![image](https://user-images.githubusercontent.com/12234510/42635157-8a7eb050-85e5-11e8-8f2c-ccf21e80e6a8.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3-beta1

**Comment by olekrisek** [comment]
I see I got a Javascript Console error when testing this function: 
![skjermbilde 2018-07-14 kl 10 41 52](https://user-images.githubusercontent.com/3278226/42722812-16cce842-8753-11e8-82bd-f76322076882.png)

Referring to this function: (See the path...)
![skjermbilde 2018-07-14 kl 10 44 19](https://user-images.githubusercontent.com/3278226/42722815-291e4680-8753-11e8-99a1-880753f94636.png)
- Ole

**Comment by acs-ferreira** [comment]
Exactly.

**Comment by olekrisek** [comment]
For the mailto links, I have done a patch to fix this, however, i did not see the vendors directory in here, so I just supply the patch for now. 
`
From 31631b4a9a376c53715d6d3bb81843d143f60441 Mon Sep 17 00:00:00 2001
From: Ole Kristian Ek Hornnes <ole@webapptech.no>
Date: Sat, 14 Jul 2018 14:12:38 +0200
Subject: [PATCH] Mailto links on v1.3 #3209

Added check for mailto and FTP links as well.

Signed-off-by: Ole Kristian Ek Hornnes <ole@webapptech.no>
---
 .../humhub-prosemirror-richtext/src/editor/core/plugins/link/menu.js    | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/protected/vendor/npm-asset/humhub-prosemirror-richtext/src/editor/core/plugins/link/menu.js b/protected/vendor/npm-asset/humhub-prosemirror-richtext/src/editor/core/plugins/link/menu.js
index 0ea2c4f..2ec93b1 100644
--- a/protected/vendor/npm-asset/humhub-prosemirror-richtext/src/editor/core/plugins/link/menu.js
+++ b/protected/vendor/npm-asset/humhub-prosemirror-richtext/src/editor/core/plugins/link/menu.js
@@ -33,7 +33,7 @@ function linkItem(context) {
                         label: context.translate("Link target"),
                         required: true,
                         clean: (val) => {
-                            if (!/^https?:\/\//i.test(val))
+                            if (!/^https?:\/\//i.test(val) && !/^mailto:/i.test(val) && !/^ftps?:\/\//i.test(val))
                                 val = 'http://' + val;
                             return val
                         }
-- 
2.14.3 (Apple Git-98)
`

**Comment by buddh4** [comment]
@olekrisek thanks for the pr I'll have a look, regarding the empty link problem I've opened an issue in the prosemirror repo https://github.com/ProseMirror/prosemirror/issues/821

**Comment by olekrisek** [comment]
I see the exact same function "linkItem" is defined in 3 other files, but they are probably all created from the same source: 

- assets/d5b78476/humhub-editor.js
- protected/vendor/npm-asset/humhub-prosemirror-richtext/dist/humhub-editor.js
- static/assets/8b1fa3cb/humhub-editor.js b/static/assets/8b1fa3cb/humhub-editor.js

All around line no 44759, - I had to update in all those and empty buffers in Safari to finally get it working. Probably the last one I tried :-)

**Comment by buddh4** [comment]
`protected/vendor/npm-asset/humhub-prosemirror-richtext/dist/humhub-editor.js` is the source of the external dependency (therefore it resides in vendor directory).

`assets/d5b78476/humhub-editor.js` is was copied by your server on the first run in no production environments.

`static/assets/8b1fa3cb/humhub-editor.js` is used by production environments

**Comment by olekrisek** [comment]
OK, so this humbug-editor.js is then created from `protected/vendor/npm-asset/humhub-prosemirror-richtext/src/` where there is many files - by some utility ?
