### ISSUE TITLE
Notification 

### ISSUE THREAD

**Issue by heikostueber** [humhub/humhub#3210]
I get a Server Error if I try to open the notification.

`{
    "url": "/notification/list",
    "status": 500,
    "response": {
        "name": "Internal Server Error",
        "message": "Es ist ein interner Serverfehler aufgetreten.",
        "code": 0,
        "status": 500
    },
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"name\":\"Internal Server Error\",\"message\":\"Es ist ein interner Serverfehler aufgetreten.\",\"code\":0,\"status\":500}",
        "responseJSON": {
            "name": "Internal Server Error",
            "message": "Es ist ein interner Serverfehler aufgetreten.",
            "code": 0,
            "status": 500
        },
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "json",
    "name": "Internal Server Error",
    "message": "Es ist ein interner Serverfehler aufgetreten.",
    "code": 0,
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3 beta
| PHP version      | 7.2
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
Check the error logs: `Administration -> Information -> Logging`

**Comment by heikostueber** [comment]
INFO  Thu, 12 Jul 2018 20:11:53 +0200  application $_GET = [ 'from' => '0' ] $_SERVER = [ 'REDIRECT_SERVER_PORT' => '443' 'REDIRECT_UNIQUE_ID' => 'W0eZ6SUR4FcAACl6JgsAAAAC' 'REDIRECT_HTTP_HOST' => 'zdz24.de' 'REDIRECT_HTTP_X_REAL_IP' => '77.186.112.128' 'REDIRECT_HTTP_X_FORWARDED_FOR' => '77.186.112.128' 'REDIRECT_HTTP_CONNECTION' => 'close' 'REDIRECT_HTTP_ACCEPT' => '*/*' 'REDIRECT_HTTP_DNT' => '1' 'REDIRECT_HTTP_X_CSRF_TOKEN' => 'DA82GIzDIjs-F0Dz1DPmMgJjFTKj_AqiePwN20j4b65nbUBP3vpvbAsuM5C7VaNnZwBRdsW2Pc9NmXu4GZsa5A==' 'REDIRECT_HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'REDIRECT_HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' 'REDIRECT_HTTP_REFERER' => 'https://zdz24.de/admin/logging' 'REDIRECT_HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'REDIRECT_HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9,de;q=0.8' 'REDIRECT_HTTP_COOKIE' => 'issuem_lp=%7B%22post%22%3A%5B%5D%7D; __stripe_mid=ed388286-7424-46ba-afcc-3764fbf93283; language=d3153d2cdbf8e5fc5d8d0f66f6e4b9425df108bf5ce2981b624ec863fd1b9c3fa%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22de%22%3B%7D; cookieconsent_status=dismiss; pm_space-members-panel=expanded; pm_groups-statistics-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_spaces-statistics-panel=expanded; pm_user-tags-panel=expanded; pm_user-spaces-panel=expanded; pm_profile-follower-panel=expanded; pm_profile-following-panel=expanded; pm_getting-started-panel=expanded; PHPSESSID=f9857b08cb5e718e283966de39be8fd1; _identity=e8618816d08f2d80b1bd95c7a2eef6f898228190707494f7f2e8939a19b70332a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22c4600fc8-1412-45ca-8a9f-d91d3e02a389%22%2C2592000%5D%22%3B%7D; _csrf=e2c8d70d298ba4c6266def28f40cb7b86bf1c4d4468b08c6784d5d3fbda4e6c6a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22kbvWR9MW59scofEUecDDfJ7m5evcQcuJ%22%3B%7D' 'REDIRECT_PATH' => '/usr/local/bin:/usr/bin:/bin' 'REDIRECT_SERVER_SIGNATURE' => '' 'REDIRECT_SERVER_SOFTWARE' => 'Apache' 'REDIRECT_SERVER_NAME' => 'zdz24.de' 'REDIRECT_SERVER_ADDR' => '37.17.224.87' 'REDIRECT_REMOTE_ADDR' => '77.186.112.128' 'REDIRECT_DOCUMENT_ROOT' => '/home/www/zdz24' 'REDIRECT_REQUEST_SCHEME' => 'https' 'REDIRECT_CONTEXT_PREFIX' => '' 'REDIRECT_CONTEXT_DOCUMENT_ROOT' => '/home/www/zdz24' 'REDIRECT_SERVER_ADMIN' => 'webmaster@zdz24.de' 'REDIRECT_SCRIPT_FILENAME' => '' 'REDIRECT_REMOTE_PORT' => '42686' 'REDIRECT_GEOIP_ADDR' => '77.186.112.128' 'REDIRECT_GEOIP_CONTINENT_CODE' => 'EU' 'REDIRECT_GEOIP_COUNTRY_CODE' => 'DE' 'REDIRECT_GEOIP_COUNTRY_NAME' => 'Germany' 'REDIRECT_GEOIP_REGION' => '16' 'REDIRECT_GEOIP_REGION_NAME' => 'Berlin' 'REDIRECT_GEOIP_CITY' => 'Berlin' 'REDIRECT_GEOIP_DMA_CODE' => '0' 'REDIRECT_GEOIP_METRO_CODE' => '0' 'REDIRECT_GEOIP_AREA_CODE' => '0' 'REDIRECT_GEOIP_LATITUDE' => '52.516701' 'REDIRECT_GEOIP_LONGITUDE' => '13.400000' 'REDIRECT_GEOIP_POSTAL_CODE' => '10405' 'REDIRECT_HTTPS' => 'on' 'REDIRECT_STATUS' => '200' 'UNIQUE_ID' => 'W0eZ6SUR4FcAACl6JgsAAAAC' 'HTTP_HOST' => 'zdz24.de' 'HTTP_X_REAL_IP' => '77.186.112.128' 'HTTP_X_FORWARDED_FOR' => '77.186.112.128' 'HTTP_CONNECTION' => 'close' 'HTTP_ACCEPT' => '*/*' 'HTTP_DNT' => '1' 'HTTP_X_CSRF_TOKEN' => 'DA82GIzDIjs-F0Dz1DPmMgJjFTKj_AqiePwN20j4b65nbUBP3vpvbAsuM5C7VaNnZwBRdsW2Pc9NmXu4GZsa5A==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' 'HTTP_REFERER' => 'https://zdz24.de/admin/logging' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9,de;q=0.8' 'HTTP_COOKIE' => 'issuem_lp=%7B%22post%22%3A%5B%5D%7D; __stripe_mid=ed388286-7424-46ba-afcc-3764fbf93283; language=d3153d2cdbf8e5fc5d8d0f66f6e4b9425df108bf5ce2981b624ec863fd1b9c3fa%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22de%22%3B%7D; cookieconsent_status=dismiss; pm_space-members-panel=expanded; pm_groups-statistics-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_spaces-statistics-panel=expanded; pm_user-tags-panel=expanded; pm_user-spaces-panel=expanded; pm_profile-follower-panel=expanded; pm_profile-following-panel=expanded; pm_getting-started-panel=expanded; PHPSESSID=f9857b08cb5e718e283966de39be8fd1; _identity=e8618816d08f2d80b1bd95c7a2eef6f898228190707494f7f2e8939a19b70332a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22c4600fc8-1412-45ca-8a9f-d91d3e02a389%22%2C2592000%5D%22%3B%7D; _csrf=e2c8d70d298ba4c6266def28f40cb7b86bf1c4d4468b08c6784d5d3fbda4e6c6a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22kbvWR9MW59scofEUecDDfJ7m5evcQcuJ%22%3B%7D' 'PATH' => '/usr/local/bin:/usr/bin:/bin' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SERVER_NAME' => 'zdz24.de' 'SERVER_ADDR' => '37.17.224.87' 'SERVER_PORT' => '443' 'REMOTE_ADDR' => '77.186.112.128' 'DOCUMENT_ROOT' => '/home/www/zdz24' 'REQUEST_SCHEME' => 'https' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/home/www/zdz24' 'SERVER_ADMIN' => 'webmaster@zdz24.de' 'SCRIPT_FILENAME' => '/home/www/zdz24/index.php' 'REMOTE_PORT' => '42686' 'REDIRECT_QUERY_STRING' => 'from=0' 'REDIRECT_URL' => '/notification/list' 'GEOIP_ADDR' => '77.186.112.128' 'GEOIP_CONTINENT_CODE' => 'EU' 'GEOIP_COUNTRY_CODE' => 'DE' 'GEOIP_COUNTRY_NAME' => 'Germany' 'GEOIP_REGION' => '16' 'GEOIP_REGION_NAME' => 'Berlin' 'GEOIP_CITY' => 'Berlin' 'GEOIP_DMA_CODE' => '0' 'GEOIP_METRO_CODE' => '0' 'GEOIP_AREA_CODE' => '0' 'GEOIP_LATITUDE' => '52.516701' 'GEOIP_LONGITUDE' => '13.400000' 'GEOIP_POSTAL_CODE' => '10405' 'HTTPS' => 'on' 'SSL_SERVER_S_DN_CN' => 'zdz24.de' 'SSL_SERVER_I_DN_C' => 'US' 'SSL_SERVER_I_DN_O' => 'Let\'s Encrypt' 'SSL_SERVER_I_DN_CN' => 'Let\'s Encrypt Authority X3' 'SSL_VERSION_INTERFACE' => 'mod_ssl/2.4.10' 'SSL_VERSION_LIBRARY' => 'OpenSSL/1.0.1t' 'SSL_PROTOCOL' => 'TLSv1.2' 'SSL_SECURE_RENEG' => 'true' 'SSL_COMPRESS_METHOD' => 'NULL' 'SSL_CIPHER' => 'ECDHE-RSA-AES128-GCM-SHA256' 'SSL_CIPHER_EXPORT' => 'false' 'SSL_CIPHER_USEKEYSIZE' => '128' 'SSL_CIPHER_ALGKEYSIZE' => '128' 'SSL_CLIENT_VERIFY' => 'NONE' 'SSL_SERVER_M_VERSION' => '3' 'SSL_SERVER_M_SERIAL' => '04A0A4A89A41EC579B574CCDCC156F58DA0B' 'SSL_SERVER_V_START' => 'Jul 9 10:04:49 2018 GMT' 'SSL_SERVER_V_END' => 'Oct 7 10:04:49 2018 GMT' 'SSL_SERVER_S_DN' => 'CN=zdz24.de' 'SSL_SERVER_I_DN' => 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US' 'SSL_SERVER_A_KEY' => 'rsaEncryption' 'SSL_SERVER_A_SIG' => 'sha256WithRSAEncryption' 'SSL_SESSION_ID' => 'a6ccecb8ed01f26e6b5faf3a077f723c21e8777350609aa4fcb2b8e99346fca1' 'SSL_SESSION_RESUMED' => 'Resumed' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.0' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'from=0' 'REQUEST_URI' => '/notification/list?from=0' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1531419113.433 'REQUEST_TIME' => 1531419113 'argv' => [ 0 => 'from=0' ] 'argc' => 1 ]

**Comment by heikostueber** [comment]
INFO  Thu, 12 Jul 2018 20:17:17 +0200  application $_GET = [ 'from' => '0' ] $_SERVER = [ 'REDIRECT_SERVER_PORT' => '443' 'REDIRECT_UNIQUE_ID' => 'W0ebLSUR4FcAACl6Jh0AAAAC' 'REDIRECT_HTTP_HOST' => 'zdz24.de' 'REDIRECT_HTTP_X_REAL_IP' => '77.186.112.128' 'REDIRECT_HTTP_X_FORWARDED_FOR' => '77.186.112.128' 'REDIRECT_HTTP_CONNECTION' => 'close' 'REDIRECT_HTTP_ACCEPT' => '*/*' 'REDIRECT_HTTP_DNT' => '1' 'REDIRECT_HTTP_X_CSRF_TOKEN' => 'v6FOVJvk-XIeSjyu9W5pAAX1fCuNgVUw85OgeJ_BdiTUwzgDyd20JStzT82aCCxVYJY4b-vLYl3G9tYbzqIDbg==' 'REDIRECT_HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'REDIRECT_HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' 'REDIRECT_HTTP_REFERER' => 'https://zdz24.de/admin/logging/index' 'REDIRECT_HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'REDIRECT_HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9,de;q=0.8' 'REDIRECT_HTTP_COOKIE' => 'issuem_lp=%7B%22post%22%3A%5B%5D%7D; __stripe_mid=ed388286-7424-46ba-afcc-3764fbf93283; language=d3153d2cdbf8e5fc5d8d0f66f6e4b9425df108bf5ce2981b624ec863fd1b9c3fa%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22de%22%3B%7D; cookieconsent_status=dismiss; pm_space-members-panel=expanded; pm_groups-statistics-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_spaces-statistics-panel=expanded; pm_user-tags-panel=expanded; pm_user-spaces-panel=expanded; pm_profile-follower-panel=expanded; pm_profile-following-panel=expanded; pm_getting-started-panel=expanded; PHPSESSID=f9857b08cb5e718e283966de39be8fd1; _identity=e8618816d08f2d80b1bd95c7a2eef6f898228190707494f7f2e8939a19b70332a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22c4600fc8-1412-45ca-8a9f-d91d3e02a389%22%2C2592000%5D%22%3B%7D; _csrf=e2c8d70d298ba4c6266def28f40cb7b86bf1c4d4468b08c6784d5d3fbda4e6c6a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22kbvWR9MW59scofEUecDDfJ7m5evcQcuJ%22%3B%7D' 'REDIRECT_PATH' => '/usr/local/bin:/usr/bin:/bin' 'REDIRECT_SERVER_SIGNATURE' => '' 'REDIRECT_SERVER_SOFTWARE' => 'Apache' 'REDIRECT_SERVER_NAME' => 'zdz24.de' 'REDIRECT_SERVER_ADDR' => '37.17.224.87' 'REDIRECT_REMOTE_ADDR' => '77.186.112.128' 'REDIRECT_DOCUMENT_ROOT' => '/home/www/zdz24' 'REDIRECT_REQUEST_SCHEME' => 'https' 'REDIRECT_CONTEXT_PREFIX' => '' 'REDIRECT_CONTEXT_DOCUMENT_ROOT' => '/home/www/zdz24' 'REDIRECT_SERVER_ADMIN' => 'webmaster@zdz24.de' 'REDIRECT_SCRIPT_FILENAME' => '' 'REDIRECT_REMOTE_PORT' => '48572' 'REDIRECT_GEOIP_ADDR' => '77.186.112.128' 'REDIRECT_GEOIP_CONTINENT_CODE' => 'EU' 'REDIRECT_GEOIP_COUNTRY_CODE' => 'DE' 'REDIRECT_GEOIP_COUNTRY_NAME' => 'Germany' 'REDIRECT_GEOIP_REGION' => '16' 'REDIRECT_GEOIP_REGION_NAME' => 'Berlin' 'REDIRECT_GEOIP_CITY' => 'Berlin' 'REDIRECT_GEOIP_DMA_CODE' => '0' 'REDIRECT_GEOIP_METRO_CODE' => '0' 'REDIRECT_GEOIP_AREA_CODE' => '0' 'REDIRECT_GEOIP_LATITUDE' => '52.516701' 'REDIRECT_GEOIP_LONGITUDE' => '13.400000' 'REDIRECT_GEOIP_POSTAL_CODE' => '10405' 'REDIRECT_HTTPS' => 'on' 'REDIRECT_STATUS' => '200' 'UNIQUE_ID' => 'W0ebLSUR4FcAACl6Jh0AAAAC' 'HTTP_HOST' => 'zdz24.de' 'HTTP_X_REAL_IP' => '77.186.112.128' 'HTTP_X_FORWARDED_FOR' => '77.186.112.128' 'HTTP_CONNECTION' => 'close' 'HTTP_ACCEPT' => '*/*' 'HTTP_DNT' => '1' 'HTTP_X_CSRF_TOKEN' => 'v6FOVJvk-XIeSjyu9W5pAAX1fCuNgVUw85OgeJ_BdiTUwzgDyd20JStzT82aCCxVYJY4b-vLYl3G9tYbzqIDbg==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36' 'HTTP_REFERER' => 'https://zdz24.de/admin/logging/index' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9,de;q=0.8' 'HTTP_COOKIE' => 'issuem_lp=%7B%22post%22%3A%5B%5D%7D; __stripe_mid=ed388286-7424-46ba-afcc-3764fbf93283; language=d3153d2cdbf8e5fc5d8d0f66f6e4b9425df108bf5ce2981b624ec863fd1b9c3fa%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22de%22%3B%7D; cookieconsent_status=dismiss; pm_space-members-panel=expanded; pm_groups-statistics-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_spaces-statistics-panel=expanded; pm_user-tags-panel=expanded; pm_user-spaces-panel=expanded; pm_profile-follower-panel=expanded; pm_profile-following-panel=expanded; pm_getting-started-panel=expanded; PHPSESSID=f9857b08cb5e718e283966de39be8fd1; _identity=e8618816d08f2d80b1bd95c7a2eef6f898228190707494f7f2e8939a19b70332a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22c4600fc8-1412-45ca-8a9f-d91d3e02a389%22%2C2592000%5D%22%3B%7D; _csrf=e2c8d70d298ba4c6266def28f40cb7b86bf1c4d4468b08c6784d5d3fbda4e6c6a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22kbvWR9MW59scofEUecDDfJ7m5evcQcuJ%22%3B%7D' 'PATH' => '/usr/local/bin:/usr/bin:/bin' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SERVER_NAME' => 'zdz24.de' 'SERVER_ADDR' => '37.17.224.87' 'SERVER_PORT' => '443' 'REMOTE_ADDR' => '77.186.112.128' 'DOCUMENT_ROOT' => '/home/www/zdz24' 'REQUEST_SCHEME' => 'https' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/home/www/zdz24' 'SERVER_ADMIN' => 'webmaster@zdz24.de' 'SCRIPT_FILENAME' => '/home/www/zdz24/index.php' 'REMOTE_PORT' => '48572' 'REDIRECT_QUERY_STRING' => 'from=0' 'REDIRECT_URL' => '/notification/list' 'GEOIP_ADDR' => '77.186.112.128' 'GEOIP_CONTINENT_CODE' => 'EU' 'GEOIP_COUNTRY_CODE' => 'DE' 'GEOIP_COUNTRY_NAME' => 'Germany' 'GEOIP_REGION' => '16' 'GEOIP_REGION_NAME' => 'Berlin' 'GEOIP_CITY' => 'Berlin' 'GEOIP_DMA_CODE' => '0' 'GEOIP_METRO_CODE' => '0' 'GEOIP_AREA_CODE' => '0' 'GEOIP_LATITUDE' => '52.516701' 'GEOIP_LONGITUDE' => '13.400000' 'GEOIP_POSTAL_CODE' => '10405' 'HTTPS' => 'on' 'SSL_SERVER_S_DN_CN' => 'zdz24.de' 'SSL_SERVER_I_DN_C' => 'US' 'SSL_SERVER_I_DN_O' => 'Let\'s Encrypt' 'SSL_SERVER_I_DN_CN' => 'Let\'s Encrypt Authority X3' 'SSL_VERSION_INTERFACE' => 'mod_ssl/2.4.10' 'SSL_VERSION_LIBRARY' => 'OpenSSL/1.0.1t' 'SSL_PROTOCOL' => 'TLSv1.2' 'SSL_SECURE_RENEG' => 'true' 'SSL_COMPRESS_METHOD' => 'NULL' 'SSL_CIPHER' => 'ECDHE-RSA-AES128-GCM-SHA256' 'SSL_CIPHER_EXPORT' => 'false' 'SSL_CIPHER_USEKEYSIZE' => '128' 'SSL_CIPHER_ALGKEYSIZE' => '128' 'SSL_CLIENT_VERIFY' => 'NONE' 'SSL_SERVER_M_VERSION' => '3' 'SSL_SERVER_M_SERIAL' => '04A0A4A89A41EC579B574CCDCC156F58DA0B' 'SSL_SERVER_V_START' => 'Jul 9 10:04:49 2018 GMT' 'SSL_SERVER_V_END' => 'Oct 7 10:04:49 2018 GMT' 'SSL_SERVER_S_DN' => 'CN=zdz24.de' 'SSL_SERVER_I_DN' => 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US' 'SSL_SERVER_A_KEY' => 'rsaEncryption' 'SSL_SERVER_A_SIG' => 'sha256WithRSAEncryption' 'SSL_SESSION_ID' => 'd763f1659525a812617e7fd1ae10586a47892e9ac57caae0aca07f95cfd00d1e' 'SSL_SESSION_RESUMED' => 'Resumed' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.0' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'from=0' 'REQUEST_URI' => '/notification/list?from=0' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1531419437.818 'REQUEST_TIME' => 1531419437 'argv' => [ 0 => 'from=0' ] 'argc' => 1 ]
ERROR  Thu, 12 Jul 2018 20:17:17 +0200  Error Error: Call to a member function getUrl() on null in /home/www/zdz24/protected/humhub/modules/user/notifications/Followed.php:45 Stack trace: #0 /home/www/zdz24/protected/humhub/components/SocialActivity.php(152): humhub\modules\user\notifications\Followed->getUrl() #1 /home/www/zdz24/protected/humhub/modules/notification/components/BaseNotification.php(138): humhub\components\SocialActivity->getViewParams(Array) #2 /home/www/zdz24/protected/humhub/components/rendering/ViewPathRenderer.php(69): humhub\modules\notification\components\BaseNotification->getViewParams(Array) #3 /home/www/zdz24/protected/humhub/modules/notification/components/BaseNotification.php(353): humhub\components\rendering\ViewPathRenderer->render(Object(humhub\modules\user\notifications\Followed)) #4 /home/www/zdz24/protected/humhub/modules/notification/controllers/ListController.php(48): humhub\modules\notification\components\BaseNotification->render() #5 [internal function]: humhub\modules\notification\controllers\ListController->actionIndex() #6 /home/www/zdz24/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #7 /home/www/zdz24/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #8 /home/www/zdz24/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #9 /home/www/zdz24/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('notification/li...', Array) #10 /home/www/zdz24/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 /home/www/zdz24/index.php(25): yii\base\Application->run() #12 {main}

**Comment by buddh4** [comment]
Try running `php yii integrity/run` within the `protected` directory of your installation.

**Comment by heikostueber** [comment]
Hi,
nothing happens.
But if I create a new admin account, the new account can view the notification.

**Comment by buddh4** [comment]
what do you mean with nothing happens? no output or no integrity issuse found? Its working for the other user since notifications are bound to a specific user.

**Comment by heikostueber** [comment]
Yes, it is only the first admin. In a further installation with democontent, the issue was active for a demouser.

Sorry, here is the output:

*** Performing database integrity checks

Validating: CFile Module (0 entries)
Validating: CFile Module (0 entries)
Validating: ReportContent Module (0 entries)
Validating: Activity Module (22 entries)
Validating: Comment Module (2 entries)
Validating: Content Objects (33 entries)
Validating: File Module (2 entries)
Validating: Like (3 entries)
Validating: Notification Module (12 entries)
Validating: Post  Module - Posts (9 entries)
Validating: Space Module - Spaces (3 entries)
Validating: Space Module - Memberships (5 entries)
Validating: User Module - ContentContainer (5 entries)
Validating: User Module - Users (5 entries)
Validating: User Module - Password (3 entries)
Validating: User Module - Profile (5 entries)
Validating: User Module - Mentioning (0 entries)
Validating: User Module - Follow (12 entries)
Validating: User Module - Content container (8 entries)

*** All integrity checks done

**Comment by heikostueber** [comment]
There was a NULL in a notification.originator_user_id.
I changed it to the ID of another user and now it works perfect.

A big THX to you !
