### ISSUE TITLE
[v1.3] Error under PHP7.2

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3213]
### What steps will reproduce the problem?
Install a fresh `v1.3` from `master`. Enable `PHP 7.2`

Dashboard works, but when entering to any Space:

```
yii\base\ErrorException: Cannot use 'Object' as class name as it is reserved
in /public/protected/vendor/yiisoft/yii2/base/Object.php:28
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main} 
```
No problem if i switch back to `PHP 7.1`
Console reports `Yii Migration Tool (based on Yii v2.0.15)`.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3-beta1

**Comment by danielkesselberg** [comment]
I guess this could be related to some modules installed during setup. Which modules do you selected during install?

**Comment by acs-ferreira** [comment]
The install was made under `7.1`, i've switched to `7.2` later.
Modules activated are:
- Birthday Widget
- Breaking News
- Calendar
- Files
- Custom Pages
- Legal Tools
- Link List
- Mail
- OnlyOffice
- Polls
- Tasks
- Wiki

**Comment by acs-ferreira** [comment]
Wiki module is not yet ready (fixed in Git, not released).
