### ISSUE TITLE
rspamd marks all humhub Mails as SPAM (problems caused by humhub)

### ISSUE THREAD

**Issue by jensliebau** [humhub/humhub#3222]
### What steps will reproduce the problem?
When ever someone is posting a new message in humhub, humhub is sending mails to members. These mails are marked as SPAM by rspamd (https://github.com/vstakhov/rspamd)

### What is the expected result?
The mails should be delivered to its recipients

### What do you get instead?
rspamd marks all mails as SPAM. Reasons for this are:

- HFILTER_URL_ONLY (2.2)[1]
- HTML_SHORT_LINK_IMG_1(2)
- SUBJ_EXCESS_QP(1.2)
- URI_COUNT_ODD(1)[9]
- SUBJECT_ENDS_SPACES(0.5)

Some of these problems should be easy to fix:
- SUBJECT_ENDS_SPACES -> remove unnecessary space
- SUBJ_EXCESS_QP -> Test if subject contains non ASCII Chars; encode only if necessary
- URI_COUNT_ODD -> Is caused by: Text in "text" vs "html" part of mail differs. This is related to https://github.com/humhub/humhub/issues/3104

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by luke-** [comment]
SUBJECT_ENDS_SPACES: Can you please provide an example of a subject which ends with a space? Maybe this is a problem in a translation.

SUBJ_EXCESS_QP: We're using Swiftmailer as sendling libary and there seems to be no option for this.
 
URI_COUNT_ODD: I've added the related ticket to our wishlist.

Sorry about that there seems to be no easy fix for your points yet.

**Comment by mtdcr** [comment]
Here's an example in German locale:

`Subject: <insert-name-of-user> schrieb gerade Beitrag "<insert-topic>" im Space
 =?utf-8?Q?<insert-name-of-space>=0A?=`

So there's an escaped trailing newline character. Btw., the name of the space only contains ascii characters, so it's a good example for the excessive quoting already mentioned above.
