### ISSUE TITLE
Conversations  problem in new meassage

### ISSUE THREAD

**Issue by kamranbhutto** [humhub/humhub#3230]
### What steps will reproduce the problem?
Conversations  problem in new meassage
### What is the expected result?
![image](https://user-images.githubusercontent.com/3133422/43550763-10bf2d98-95fe-11e8-8df6-fd4fb6167786.png)
problem new line in New meassage
![image](https://user-images.githubusercontent.com/3133422/43550797-30711e94-95fe-11e8-9e17-b2f732f56ba4.png)

| Q                | A
| ---------------- | ---
| HumHub Latest Stable Version| 1.2.8
| PHP version      |  7.0.10
| Operating system | windows 10 
|browser | google chrome, firefox

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
In markdown you must add a line.

**Comment by buddh4** [comment]
We'll integrate the new richtext to the mail module and other modules soon.

**Comment by kamranbhutto** [comment]
great Good
