### ISSUE TITLE
Queue not executed

### ISSUE THREAD

**Issue by ThomasKaule** [humhub/humhub#3231]
### What steps will reproduce the problem?

[root@humhub ~]# date
Tue Jul 31 12:04:52 CEST 2018

I've emptied the queue. After running the cron/hourly job, 5 entries are in the queue:

[root@humhub cache]# yii queue
Jobs
- waiting: 5
- delayed: 0
- reserved: 0
- done: 0

[root@humhub cache]# mysql humhub --execute 'select * from queue'
+------+---------+-----------------------------------------------------------------------------+------------+-----+-------+----------+-------------+---------+---------+
| id   | channel | job                                                                         | pushed_at  | ttr | delay | priority | reserved_at | attempt | done_at |
+------+---------+-----------------------------------------------------------------------------+------------+-----+-------+----------+-------------+---------+---------+
| 2094 | queue   | O:38:"humhub\modules\tasks\jobs\SendReminder":0:{}                          | 1533029401 | 300 |     0 |     1024 |        NULL |    NULL |    NULL |
| 2095 | queue   | O:44:"humhub\modules\activity\jobs\SendMailSummary":1:{s:8:"interval";i:1;} | 1533029401 | 300 |     0 |     1024 |        NULL |    NULL |    NULL |
| 2096 | queue   | O:40:"humhub\modules\live\jobs\DatabaseCleanup":0:{}                        | 1533029401 | 300 |     0 |     1024 |        NULL |    NULL |    NULL |
| 2097 | queue   | O:34:"humhub\modules\user\jobs\SyncUsers":0:{}                              | 1533029402 | 300 |     0 |     1024 |        NULL |    NULL |    NULL |
| 2098 | queue   | O:46:"humhub\modules\user\jobs\DeleteExpiredSessions":0:{}                  | 1533029402 | 300 |     0 |     1024 |        NULL |    NULL |    NULL |
+------+---------+-----------------------------------------------------------------------------+------------+-----+-------+----------+-------------+---------+---------+

2 days later:

[root@humhub ~]# date
Thu Aug  2 08:58:26 CEST 2018

Now the queue is filled up with 241 entries:

[root@humhub ~]# yii queue
Jobs
- waiting: 241
- delayed: 0
- reserved: 0
- done: 0

And the first one in the queue as of July 31st is still there:

[root@humhub ~]# mysql humhub --execute 'select * from queue where id=2094'
+------+---------+----------------------------------------------------+------------+-----+-------+----------+-------------+---------+---------+
| id   | channel | job                                                | pushed_at  | ttr | delay | priority | reserved_at | attempt | done_at |
+------+---------+----------------------------------------------------+------------+-----+-------+----------+-------------+---------+---------+
| 2094 | queue   | O:38:"humhub\modules\tasks\jobs\SendReminder":0:{} | 1533029401 | 300 |     0 |     1024 |        NULL |    NULL |    NULL |
+------+---------+----------------------------------------------------+------------+-----+-------+----------+-------------+---------+---------+

I can run the queue:

[root@humhub ~]# yii queue/run

And it is now empty:

[root@humhub ~]# yii queue
Jobs
- waiting: 0
- delayed: 0
- reserved: 0
- done: 0

But running the hourly job:

[root@humhub ~]# yii cron/hourly
Executing hourly tasks:

Optimizing search index... done.

... will include new jobs a before:

[root@humhub ~]# yii queue
Jobs
- waiting: 5
- delayed: 0
- reserved: 0
- done: 0

### What is the expected result?

Have the queue executed and emptied regulary

### What do you get instead?

Increasing job queue

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.0-beta.3
| PHP version      |  PHP - Version - 7.1.8
| Operating system | CentOS 7

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Could you provide the Cron Job you're using?

### Example
```
* * * * *  /usr/local/bin/php /home/USERNAME/public_html/WEB-DIRECTORY/protected/yii queue/run >/dev/null 2>&1
```

**Comment by ThomasKaule** [comment]
I'm using humhub for a long time without problems.

[root@humhub ~]# cat /etc/cron.d/humhub 
30  * * * * root sudo -u apache /var/www/humhub/protected/yii cron/hourly >/dev/null 2>&1
 0 18 * * * root sudo -u apache /var/www/humhub/protected/yii cron/daily >/dev/null 2>&1

And they are executed regularly:

[root@humhub ~]# grep 'cron/hourly' /var/log/cron | tail -5
Aug  2 05:30:01 humhub CROND[11085]: (root) CMD (sudo -u apache /var/www/humhub/protected/yii cron/hourly >/dev/null 2>&1)
Aug  2 06:30:01 humhub CROND[12965]: (root) CMD (sudo -u apache /var/www/humhub/protected/yii cron/hourly >/dev/null 2>&1)
Aug  2 07:30:01 humhub CROND[14854]: (root) CMD (sudo -u apache /var/www/humhub/protected/yii cron/hourly >/dev/null 2>&1)
Aug  2 08:30:01 humhub CROND[16841]: (root) CMD (sudo -u apache /var/www/humhub/protected/yii cron/hourly >/dev/null 2>&1)
Aug  2 09:30:01 humhub CROND[19465]: (root) CMD (sudo -u apache /var/www/humhub/protected/yii cron/hourly >/dev/null 2>&1)

[root@humhub ~]# grep 'cron/daily' /var/log/cron | tail -5
Jul 29 18:00:01 humhub CROND[13248]: (root) CMD (sudo -u apache /var/www/humhub/protected/yii cron/daily >/dev/null 2>&1)
Jul 30 18:00:01 humhub CROND[28802]: (root) CMD (sudo -u apache /var/www/humhub/protected/yii cron/daily >/dev/null 2>&1)
Jul 31 18:00:01 humhub CROND[8972]: (root) CMD (sudo -u apache /var/www/humhub/protected/yii cron/daily >/dev/null 2>&1)
Aug  1 18:00:01 humhub CROND[21289]: (root) CMD (sudo -u apache /var/www/humhub/protected/yii cron/daily >/dev/null 2>&1)

**Comment by danielkesselberg** [comment]
http://docs.humhub.org/beta/admin-installation-configuration.html#cronjobs-and-asynchronous-job-processing-v13

**Comment by ThomasKaule** [comment]
ok, so I now longer need to start regularly a cron/hourly and cron/daily script and start a cron/run and queue/run instead ? And they could be run once a hour ?

**Comment by danielkesselberg** [comment]
cron/run starts hourly and daily when required. Documentation recommends every minute. When u are concerned about executing cron/run every minute you can keep cron/daily and cron/hourly or use a higher value like every 15 minutes. 

queue/run should be executed every minute.

**Comment by ThomasKaule** [comment]
can be closed
