### ISSUE TITLE
Cannot use 'Object' as class name as it is reserved in \humhub\protected\vendor\yiisoft\yii2\base\Object.php on line 77

### ISSUE THREAD

**Issue by vinh28193** [humhub/humhub#3232]
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.7
| PHP version      | 7.2.3
| Operating system | 

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by danielkesselberg** [comment]
HumHub 1.3 is ready for php 7.2. See https://github.com/humhub/humhub/issues/3164

**Comment by dmitrydrynov** [comment]
I updated to 1.3 today and also have the error
Cannot use 'Object' as class name as it is reserved

**Comment by danielkesselberg** [comment]
Could you post a list of modules please? Maybe a module is not ready for humhub 1.3

**Comment by dmitrydrynov** [comment]
I found Object class in API and Wiki modules (changed to BaseObject) before

**Comment by Felli** [comment]
Clear your cache and check again, just to note any modules that I've created over on @GreenMeteor haven't been updated yet either.

**Comment by jeanleinaas** [comment]
I found the problem inside Steam module... changed from Object to ObjectBase inside event.php and all was good! :)

**Comment by Felli** [comment]
@jeanleinaas the newest version hasn't been posted to the market yet, for an updated version please always check the [repo](https://github.com/GreenMeteor/humhub-steam-module/blob/master/Events.php#L9).

**Comment by lisandi** [comment]
I have the same error right now after updating 2 sites to 1.9.1 from Github

```
{
    "url": "/dashboard/dashboard/stream",
    "status": 500,
    "response": "<pre>PHP Compile Error &#039;yii\\base\\ErrorException&#039; with message &#039;Cannot use &#039;Object&#039; as class name as it is reserved&#039; \n\nin /path/humhub/protected/vendor/yiisoft/yii2/base/Object.php:28\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleFatalError()\n#1 {main}</pre>",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Compile Error &#039;yii\\base\\ErrorException&#039; with message &#039;Cannot use &#039;Object&#039; as class name as it is reserved&#039; \n\nin /path/humhub/protected/vendor/yiisoft/yii2/base/Object.php:28\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleFatalError()\n#1 {main}</pre>",
        "status": 500,
        "statusText": "error"
    },
    "dataType": "html",
    "html": "<pre>PHP Compile Error &#039;yii\\base\\ErrorException&#039; with message &#039;Cannot use &#039;Object&#039; as class name as it is reserved&#039; \n\nin /path/humhub/protected/vendor/yiisoft/yii2/base/Object.php:28\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleFatalError()\n#1 {main}</pre>",
    "error": {},
    "errorThrown": "",
    "validationError": false
}
```

**Comment by ArchBlood** [comment]
> I have the same error right now after updating 2 sites to 1.9.1 from Github
> 
> `Got error 'PHP message: PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /path/humub/protected/vendor/yiisoft/yii2/base/Object.php on line 28', referer: https://domain.tld/dashboard`
> 
> ```
> {
>     "url": "/dashboard/dashboard/stream",
>     "status": 500,
>     "response": "<pre>PHP Compile Error &#039;yii\\base\\ErrorException&#039; with message &#039;Cannot use &#039;Object&#039; as class name as it is reserved&#039; \n\nin /path/humhub/protected/vendor/yiisoft/yii2/base/Object.php:28\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleFatalError()\n#1 {main}</pre>",
>     "textStatus": "error",
>     "xhr": {
>         "readyState": 4,
>         "responseText": "<pre>PHP Compile Error &#039;yii\\base\\ErrorException&#039; with message &#039;Cannot use &#039;Object&#039; as class name as it is reserved&#039; \n\nin /path/humhub/protected/vendor/yiisoft/yii2/base/Object.php:28\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleFatalError()\n#1 {main}</pre>",
>         "status": 500,
>         "statusText": "error"
>     },
>     "dataType": "html",
>     "html": "<pre>PHP Compile Error &#039;yii\\base\\ErrorException&#039; with message &#039;Cannot use &#039;Object&#039; as class name as it is reserved&#039; \n\nin /path/humhub/protected/vendor/yiisoft/yii2/base/Object.php:28\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleFatalError()\n#1 {main}</pre>",
>     "error": {},
>     "errorThrown": "",
>     "validationError": false
> }
> ```

You probably have 2 or more modules with a Events.php that hasn't been updated to use `BaseObject` yet

**Comment by lisandi** [comment]
It was running until the update and than suddenly I had that problem. I update regular since Version 1.8.1 via Github and no problems. - 1.9.1 did break it. All Modules where in there before too - we actually deinstalled some of them but did not install one additional. So what has changed since 1.9.0 to 1.9.1 that now that events.php is causing problems but did not cause problems in 1.9.0 or 1.8.*.

Can you tell me where or how to look for that Events.php? - until now we don't use the calendar even it is active but it is empty

**Comment by luke-** [comment]
@lisandi The problem is somehow related to your Composer dependencies. The Yii2 version is too old.

**Comment by lisandi** [comment]
why is Yii2 from Version 1.9 to 1.9.1 getting older - sounds like real life :-) every day one day older. uff. Can that Yii2 be upgraded or isn't it advised. They are actually working on Yii3 already and support for Yii2 with new features runs out in 2-3 years already.

**Comment by luke-** [comment]
Of course, this should not be. It is not in our official repo either.

**Comment by lisandi** [comment]
hmm strange as we always update via git pull from that repository. https://github.com/humhub/humhub. I will check and compare the Composer scripts
