### ISSUE TITLE
Missing column after 1.3.1 update

### ISSUE THREAD

**Issue by Richies97** [humhub/humhub#3237]
### What steps will reproduce the problem?

Press Background jobs in The Admin-Settings

### What is the expected result?

See what Crons are currently running

### What do you get instead?

Internal Server Error

And this in the Log:

`
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pushed_at' in 'field list' in /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/db/Command.php:1258 Stack trace: #0 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute() #1 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('INSERT INTO `qu...') #2 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(164): yii\db\Command->execute() #3 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2-queue/src/Queue.php(160): yii\queue\db\Queue->pushMessage('O:38:"humhub\\mo...', 300, 0, NULL) #4 /usr/www/users/gkuiyb/asset/versions/1.01/protected/modules/tasks/Events.php(213): yii\queue\Queue->push(Object(humhub\modules\tasks\jobs\SendReminder)) #5 [internal function]: humhub\modules\tasks\Events::onCronRun(Object(yii\base\Event)) #6 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\base\Event)) #7 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\commands...', 'hourly', Object(yii\base\Event)) #8 /usr/www/users/gkuiyb/asset/versions/1.01/protected/humhub/commands/CronController.php(100): yii\base\Component->trigger('hourly') #9 /usr/www/users/gkuiyb/asset/versions/1.01/protected/humhub/commands/CronController.php(68): humhub\commands\CronController->runHourly(true) #10 [internal function]: humhub\commands\CronController->actionHourly() #11 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #12 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #13 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('hourly', Array) #14 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('hourly', Array) #15 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('cron/hourly', Array) #16 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('cron/hourly', Array) #17 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #18 /usr/www/users/gkuiyb/asset/versions/1.01/protected/yii(29): yii\base\Application->run() #19 {main} Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pushed_at' in 'field list' The SQL being executed was: INSERT INTO `queue` (`channel`, `job`, `pushed_at`, `ttr`, `delay`, `priority`) VALUES ('queue', 'O:38:\"humhub\\modules\\tasks\\jobs\\SendReminder\":0:{}', 1533645181, 300, 0, 1024) in /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/db/Schema.php:664 Stack trace: #0 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `qu...') #1 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('INSERT INTO `qu...') #2 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(164): yii\db\Command->execute() #3 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2-queue/src/Queue.php(160): yii\queue\db\Queue->pushMessage('O:38:"humhub\\mo...', 300, 0, NULL) #4 /usr/www/users/gkuiyb/asset/versions/1.01/protected/modules/tasks/Events.php(213): yii\queue\Queue->push(Object(humhub\modules\tasks\jobs\SendReminder)) #5 [internal function]: humhub\modules\tasks\Events::onCronRun(Object(yii\base\Event)) #6 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\base\Event)) #7 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\commands...', 'hourly', Object(yii\base\Event)) #8 /usr/www/users/gkuiyb/asset/versions/1.01/protected/humhub/commands/CronController.php(100): yii\base\Component->trigger('hourly') #9 /usr/www/users/gkuiyb/asset/versions/1.01/protected/humhub/commands/CronController.php(68): humhub\commands\CronController->runHourly(true) #10 [internal function]: humhub\commands\CronController->actionHourly() #11 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #12 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #13 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('hourly', Array) #14 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('hourly', Array) #15 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('cron/hourly', Array) #16 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('cron/hourly', Array) #17 /usr/www/users/gkuiyb/asset/versions/1.01/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #18 /usr/www/users/gkuiyb/asset/versions/1.01/protected/yii(29): yii\base\Application->run() #19 {main} Additional Information: Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'pushed_at' in 'field list' )

`

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1
| PHP version      |   7.0.31

**Comment by danielkesselberg** [comment]
Do you updated from 1.3.o or 1.2.x? There is a migration with this [column](https://github.com/humhub/humhub/blob/v1.3.1/protected/humhub/modules/queue/migrations/m171025_142030_queue_update.php). I guess humhub would not work if queue table were missing.

Could you try to flush the cache? `php protected/yii cache/flush-all`

**Comment by luke-** [comment]
Are you used the "Updater" module?

Were any errors displayed during the update process?

**Comment by Richies97** [comment]
We used the Updater and no error occured. We can not exactly tell what fixed the problem but now it works.

We updated from 1.2.8 to 1.3.1.

`php protected/yii cache/flush-all` wasn't the only thing we tried but it helped to clear some Errors.
