### ISSUE TITLE
does not work space and users search in the directory version 1.3 centos 7 php 7.14

### ISSUE THREAD

**Issue by voganu** [humhub/humhub#3238]
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3
| PHP version      | 7.14
| Operating system |Centos 7

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by danielkesselberg** [comment]
Could you rebuild the search index?`php protected/yii search/rebuild`

**Comment by Felli** [comment]
@danielkesselberg don't forget you can also use the Search rebuild action via `ACP --> Information --> Database` now in v1.3. :wink:

**Comment by voganu** [comment]
All problems are solved
