### ISSUE TITLE
Can't update V 1.2.5 - "There is no new HumHub update available"

### ISSUE THREAD

**Issue by frey1esm** [humhub/humhub#3240]
### What steps will reproduce the problem?
Try to auto update version 1.2.5 using the "Humhub Updater" module

### What is the expected result?
"A new update is available - click to update"

### What do you get instead?
"There is no new HumHub update available!"

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.5
|  PHP - Version - 7.0.31
| Operating system | CentoOS 

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by luke-** [comment]
Should be fixed.
