### ISSUE TITLE
Space membership list count inconsistency

### ISSUE THREAD

**Issue by xaro1** [humhub/humhub#3241]
On user profile page, space membership count value is not correct and always the same as followed users list.

Since HH 1.3.x

**Comment by Felli** [comment]
You should always run `php protected/yii search/rebuild` or within v1.3 push the Search rebuild button under `ACP --> Information --> Database`.

**Comment by Felli** [comment]
Can you please provide more information? Browser, server OS, error logs, browser console errors, and etc.?
