### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1286

### ISSUE THREAD

**Issue by RausV** [humhub/humhub#3243]
Hello, I hope someone can help me. Have already searched here but found nothing suitable that would have helped. It is not so easy for me because my english is not as good I would like ...
Please give me start help, thanks!

### What steps will reproduce the problem?
Start install: homepage.com/humhub/index.php?r=installer%2Findex

### What is the expected result?
Run install ...

### What do you get instead?
Database Exception – yii\db\Exception
SQLSTATE[42000]: Syntax error or access violation: 1286 Unknown storage engine 'InnoDB'
The SQL being executed was: CREATE TABLE `queue` (
`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`channel` varchar(255) NOT NULL,
`job` blob NOT NULL,
`created_at` int(11) NOT NULL,
`started_at` int(11),
`finished_at` int(11)
) CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB
Error Info: Array
(
    [0] => 42000
    [1] => 1286
    [2] => Unknown storage engine 'InnoDB'
)
↵
Caused by: PDOException
SQLSTATE[42000]: Syntax error or access violation: 1286 Unknown storage engine 'InnoDB'
in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 1258

1. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/db/Schema.php at line 664
655656657658659660661662663664665666667668669670671672673                     
        $exceptionClass = '\yii\db\Exception';
        foreach ($this->exceptionMap as $error => $class) {
            if (strpos($e->getMessage(), $error) !== false) {
                $exceptionClass = $class;
            }
        }
        $message = $e->getMessage() . "\nThe SQL being executed was: $rawSql";
        $errorInfo = $e instanceof \PDOException ? $e->errorInfo : null;
        return new $exceptionClass($message, $errorInfo, (int) $e->getCode(), $e);
    }
 
    /**
     * Returns a value indicating whether a SQL statement is for read purpose.
     * @param string $sql the SQL statement
     * @return bool whether a SQL statement is for read purpose.
     */
    public function isReadQuery($sql)
    {
                
2. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 1263 – yii\db\Schema::convertException(PDOException, 'CREATE TABLE `queue` ( `id` int...')
3. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 1075 – yii\db\Command::internalExecute('CREATE TABLE `queue` ( `id` int...')
4. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/db/Migration.php at line 323 – yii\db\Command::execute()
5. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/humhub/modules/queue/migrations/m170118_111823_queuetable.php at line 20 – yii\db\Migration::createTable('{{%queue}}', ['id' => yii\db\mysql\ColumnSchemaBuilder, 'channel' => yii\db\mysql\ColumnSchemaBuilder, 'job' => yii\db\mysql\ColumnSchemaBuilder, 'created_at' => yii\db\mysql\ColumnSchemaBuilder, ...], 'CHARACTER SET utf8 COLLATE utf8_...')
14151617181920212223242526                                'id' => $this->primaryKey(),
            'channel' => $this->string()->notNull(),
            'job' => $this->binary()->notNull(),
            'created_at' => $this->integer()->notNull(),
            'started_at' => $this->integer(),
            'finished_at' => $this->integer(),
                ], $this->tableOptions);
 
        $this->createIndex('channel', $this->tableName, 'channel');
        $this->createIndex('started_at', $this->tableName, 'started_at');
    }
 
    public function down()
                
6. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php at line 725 – m170118_111823_queuetable::up()
7. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php at line 199 – yii\console\controllers\BaseMigrateController::migrateUp('m170118_111823_queuetable')
8. yii\console\controllers\BaseMigrateController::actionUp(0)
9. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([humhub\commands\MigrateController, 'actionUp'], [0])
10. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 157 – yii\base\InlineAction::runWithParams([])
11. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/console/Controller.php at line 148 – yii\base\Controller::runAction('up', [])
12. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/humhub/commands/MigrateController.php at line 184 – yii\console\Controller::runAction('up')
178179180181182183184185186187188189190                            ob_start();
        $controller = new self('migrate', Yii::$app);
        $controller->db = Yii::$app->db;
        $controller->interactive = false;
        $controller->includeModuleMigrations = true;
        $controller->color = false;
        $controller->runAction('up');
 
        return ob_get_clean();
    }
 
    /**
     * Executes migrations in a specific folder
                
13. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/humhub/modules/installer/controllers/SetupController.php at line 127 – humhub\commands\MigrateController::webMigrateAll()
121122123124125126127128129130131132133                            Yii::$app->cache->flush();
 
        // Disable max execution time to avoid timeouts during database installation
        @ini_set('max_execution_time', 0);
 
        // Migrate Up Database
        \humhub\commands\MigrateController::webMigrateAll();
 
        DynamicConfig::rewrite();
 
        $this->module->setDatabaseInstalled();
 
        return $this->redirect(['/installer/config/index']);
                
14. humhub\modules\installer\controllers\SetupController::actionInit()
15. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([humhub\modules\installer\controllers\SetupController, 'actionInit'], [])
16. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 157 – yii\base\InlineAction::runWithParams(['r' => 'installer/setup/init'])
17. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 528 – yii\base\Controller::runAction('init', ['r' => 'installer/setup/init'])
18. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 103 – yii\base\Module::runAction('installer/setup/init', ['r' => 'installer/setup/init'])
19. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 386 – yii\web\Application::handleRequest(humhub\components\Request)
20. in /home/.sites/938/site9988536/web/4uns.at/sub/humhub/index.php at line 25 – yii\base\Application::run()
19202122232425                        require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();
                
$_GET = [
    'r' => 'installer/setup/init',
];

$_COOKIE = [
    'wordpress_logged_in_06875cac1cdbe3d6111e5b6d2589b42f' => 'wordpressadmin|1534340595|QBn5L4lStwPhsoCKe6xmAuCUQcYrTQcmyfEJCBpKetj|f00db0e5c52115016df7a2e1a59baf4e4e790aca73def50e391c97b841337b0b',
    'wp-settings-1' => 'libraryContent=browse&imgsize=thumbnail',
    'wp-settings-time-1' => '1533130996',
    '_csrf' => 'b401eb3dbc7bbbadd474d45631e8c88e21debab11d842983747841778bf63aa5a:2:{i:0;s:5:"_csrf";i:1;s:32:"XLCqzZTsdfeejGchAg00e7Tb7qzEWpkh";}',
];
Yii Framework
2018-08-11, 16:27:28

Apache

Yii Framework/2.0.15

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.0
| PHP version      | 7.2 
| Operating system | macOS high sierra 10.13.6 (17G65)
| Database | MySQL 5.5

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

Thanks a lot for your help ..!

**Comment by danielkesselberg** [comment]
Can you ask your webhosting provider if innodb is available for mysql?

https://github.com/humhub/humhub/blob/68e7eff88194c60d3fc7cf3bc327cef4551809bb/protected/humhub/modules/queue/migrations/m170118_111823_queuetable.php#L9

To finish your setup you may edit the file above and remove 'ENGINE=InnoDB'. It should look like below than: 
`public $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci'; `

**Comment by RausV** [comment]
Oh great, many thx! Innodb is availabley at my hoster. But now I have to change the database data before I can run the installer, but no database issues are shown. Do you know how I can change this now? I deeply hope ... ;) thx!

**Comment by danielkesselberg** [comment]
I would try to run the installer again. Maybe you delete old tables first but make a backup before.

**Comment by RausV** [comment]
Of course, I deleted the old tables, but the database issues are not showen again. Where can I change this in this case?

**Comment by danielkesselberg** [comment]
Setup completed without error? Than you are good to go ;-)

**Comment by RausV** [comment]
Thank you so much! Setup completed now without error! Only the loading speed is very, very slow ...
Wish you a nice time ..! Thx!
