### ISSUE TITLE
Can't update 1.3.0-beta.3 to 1.3.1 -help?

### ISSUE THREAD

**Issue by pe-en** [humhub/humhub#3252]
I can't update my 1.3.0-beta.3 to 1.3.1. It always says: Internal server error. 

![server](https://user-images.githubusercontent.com/42466522/44260682-7d008880-a215-11e8-8e2d-d1b13c32df1a.JPG)

I already updates all modules and my php-Version. Any idea what else to do?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.0-beta.3
| PHP version      | 7.2.8
| Operating system |

**Comment by buddh4** [comment]
Check the logs for errors.

**Comment by pe-en** [comment]
Log says:

`$_GET = [ 'r' => 'mail/mail/get-new-message-count-json' ] $_SERVER = [ 'REDIRECT_UNIQUE_ID' => 'W4BR9NTjdhQAAFiMPE0AAAAL' 'REDIRECT_DOCUMENT_ROOT' => '/kunden/homepages/42/d327760558/htdocs/intra' 'REDIRECT_HTTPS' => 'on' 'REDIRECT_HANDLER' => 'x-mapp-php5.4' 'REDIRECT_STATUS' => '200' 'UNIQUE_ID' => 'W4BR9NTjdhQAAFiMPE0AAAAL' 'HTTPS' => 'on' 'HTTP_HOST' => '(website)' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_X_CSRF_TOKEN' => 'qRpdWJ9ezdXrMiZSdPY-yVDiSFCsWxv-NJBnBrI87TzoWQoSzg-hvaBBdjofxFGmHq4eO8Mtdp0E2jVc9QmdbQ==' 'HTTP_ACCEPT_LANGUAGE' => 'de-de' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15' 'HTTP_REFERER' => '(website)/index.php?r=admin%2Finformation' 'HTTP_ACCEPT_ENCODING' => 'br, gzip, deflate' 'HTTP_COOKIE' => '_identity=700b4b33424b856d59ad55745d7f555461bc7f3763e58367ea12e34ddfc6995ba%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22aef31a43-eb1a-4806-9760-7759c5f47ee4%22%2C2592000%5D%22%3B%7D; PHPSESSID=e6639b2a61b44ff160c8e625751c4be0; _ga=GA1.2.1075876512.1521300810; _gid=GA1.2.1998208456.1535100154; pm_space-members-panel=expanded; pm_calendar-upcoming-events-snippet=expanded; pm_panel-birthday=expanded; _csrf=41ad5243fb6fa81e9f85ef87301259736e4e5a01d20cdce3b88f927d88fc2ceea%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22ACWJQQlhKsPhk2ooNLVkovmc0JRZG5pQ%22%3B%7D; language=5b2a4dad6e93921d10d8ca67fcfc3a6296e02f2e0cccefdb86cf891ba134c5daa%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22de%22%3B%7D' 'PATH' => '/bin:/usr/bin' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SERVER_NAME' => '(website)' 'SERVER_ADDR' => '212.227.118.20' 'SERVER_PORT' => '443' 'REMOTE_ADDR' => '(IP)' 'DOCUMENT_ROOT' => '/kunden/homepages/42/d327760558/htdocs/intra' 'REQUEST_SCHEME' => 'https' 'CONTEXT_PREFIX' => '/system-bin/' 'CONTEXT_DOCUMENT_ROOT' => '/kunden/usr/lib/cgi-bin/' 'SERVER_ADMIN' => 'webmaster@(website)' 'SCRIPT_FILENAME' => '/kunden/homepages/42/d327760558/htdocs/intra/index.php' 'REMOTE_PORT' => '10582' 'REDIRECT_QUERY_STRING' => 'r=mail%2Fmail%2Fget-new-message-count-json' 'REDIRECT_URL' => '/index.php' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=mail%2Fmail%2Fget-new-message-count-json' 'REQUEST_URI' => '/index.php?r=mail%2Fmail%2Fget-new-message-count-json' 'SCRIPT_NAME' => '/index.php' 'STATUS' => '200' 'ORIG_PATH_INFO' => '/index.php' 'ORIG_PATH_TRANSLATED' => '/kunden/homepages/42/d327760558/htdocs/intra/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1535136244.9621 'REQUEST_TIME' => 1535136244 'argv' => [ 0 => 'r=mail%2Fmail%2Fget-new-message-count-json' ] 'argc' => 1 ]`

**Comment by Felli** [comment]
@pe-en please check file permissions

http://docs.humhub.org/admin-installation.html#file-permissions

**Comment by pe-en** [comment]
Solves the problem. The server @1&1 Hosting is at it's max number of files...
