### ISSUE TITLE
Oauth Enhancement

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#3253]
We need to implement token refreshing so that users aren't logged out as soon as they close the tab, or at least make it an option within the `Remember me` option.

**Comment by DeltaLima** [comment]
If you need some debugging Data, I can provide them. We have exactly this problem with our HumHub Instance.

**Comment by Felli** [comment]
The simple way of doing this would be using `$autoRefreshAccessToken` & `refreshAccessToken()` I believe.
