### ISSUE TITLE
Supervisor and incomplete setup warning

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3255]
I'm running workers under Supervisor (and running) but i have the incomplete setup warning widget at the sidebar.

- Queue: Redis Driver
- Worker Under Supervisor: http://docs.humhub.org/admin-asynchronous-tasks.html#daemon
- HH `1.3.2-dev`

Supervisor log:
`2018-08-19 13:33:18 [pid: 16550] - Worker is started`

![image](https://user-images.githubusercontent.com/12234510/44308651-0650c000-a3ba-11e8-871f-b73481b88c40.png)

Should i run **both** Cron and Supervisor or Warning is just not checking things properly?

**Comment by Felli** [comment]
I don't think HumHub is ready for Supervisor, shouldn't hurt using both though. :thinking:

**Comment by acs-ferreira** [comment]
HumHub **RECOMMENDS** using Supervisor:
http://docs.humhub.org/admin-asynchronous-tasks.html#daemon

**Comment by danielkesselberg** [comment]
Does it work when u switch queue driver to mysql?

**Comment by danielkesselberg** [comment]
Yes.

Cron: Recurring tasks (e.g. check integrity)
Queue: Long running tasks (e.g. delete one user, create data export)

Do you think we need more information about this topic within our documentation?

**Comment by acs-ferreira** [comment]
Yes i believe that documentation should be extended and also explain what each job does.

Le 19 août 2018 à 16:39, à 16:39, Daniel Kesselberg <notifications@github.com> a écrit:

**Comment by acs-ferreira** [comment]
This is not clear at all...

I have a Cronjob setup just like http://docs.humhub.org/admin-asynchronous-tasks.html#cronjob-default

(`* * * * *`)

but, in the ACP:

> CronJob Status
> Last run (hourly):
> 8 hours ago
> 
> Last run (daily):
> 2 days ago 

1. Why 8 hours ago for last hourly run?
2. What Cronjob should i set for Daily one?

Thanks.

**Comment by acs-ferreira** [comment]
Also, documentation states that NO cronjobs are needed if a job worker (liker Supervisor) is setup...

![image](https://user-images.githubusercontent.com/12234510/44313514-76873200-a40a-11e8-8d99-7894cc69e6be.png)

I believe that all this should be clarified.

**Comment by acs-ferreira** [comment]
Thanks @danielkesselberg 

> Yes. cron/run is required.

1. Does it stand for HOURLY cron? (see ACP)
2. What Cronjob should i set for DAILY one?

**Comment by danielkesselberg** [comment]
I wrote a bit more about cron/run here: https://github.com/humhub/humhub/issues/3231#issuecomment-409896303

**Comment by acs-ferreira** [comment]
Ok, but _(sorry...)_

I want Daily Summaries to be sent at **specific** time, how can i set this?

In `v1.2`, this was done by the manual Cronjob... (like `0 18 * * *` to run it at 6PM)

**Comment by danielkesselberg** [comment]
There are two ways
A) Ignore cron/run and add cron/daily and cron/hourly to crontab like with humhub 1.2.
B) Add dailyCronExecutionTime to your configuration file (in category params) and use it with cron/run

**Comment by acs-ferreira** [comment]
Ok got it, thanks 👍 
_(but initial problem remains)_

**Comment by luke-** [comment]
It's not fully correct.

The cron/hourly & cron/daily cronjobs are deprecated and should be not longer used.

Please use cron/run instead and you can configure "dailyCronExecutionTime" via the configuration file.

**Comment by acs-ferreira** [comment]
That's what i've done, thanks.
