### ISSUE TITLE
Google Oauth2 login broken on community.humhub.com and private self hosted instance as well

### ISSUE THREAD

**Issue by DeltaLima** [humhub/humhub#3260]
### What steps will reproduce the problem?
Having a HumHub Account registred with Google Oauth2
Log out, log in -> Server answer with 500 

Happens on private instance and on community.humhub.com as well!

### What is the expected result?
Get logged in as usual :) 
### What do you get instead?
HumHub Ooops Page:

"Uuuups... Du hast womöglich den falschen Weg eingeschlagen.
Es ist ein interner Fehler aufgetreten."

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1
| PHP version      | 7
| Operating system | Debian 9.5

From my HumHub Log:

yii\authclient\InvalidResponseException
yii\authclient\InvalidResponseException: Request failed with code: 400, message: { "error" : "redirect_uri_mismatch", "error_description" : "Bad Request" } in /var/www/html/protected/vendor/yiisoft/yii2-authclient/src/BaseOAuth.php:221 Stack trace: #0 /var/www/html/protected/vendor/yiisoft/yii2-authclient/src/OAuth2.php(125): yii\authclient\BaseOAuth->sendRequest(Object(yii\httpclient\Request)) #1 /var/www/html/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(392): yii\authclient\OAuth2->fetchAccessToken('4/###########...') #2 /var/www/html/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(209): yii\authclient\AuthAction->authOAuth2(Object(humhub\modules\user\authclient\Google)) #3 /var/www/html/protected/humhub/modules/user/authclient/AuthAction.php(35): yii\authclient\AuthAction->auth(Object(humhub\modules\user\authclient\Google)) #4 /var/www/html/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(194): humhub\modules\user\authclient\AuthAction->auth(Object(humhub\modules\user\authclient\Google)) #5 [internal function]: yii\authclient\AuthAction->run() #6 /var/www/html/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #7 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array) #8 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('external', Array) #9 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/auth/exter...', Array) #10 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 /var/www/html/index.php(25): yii\base\Application->run() #12 {main} 

local registred users working fine.

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by DeltaLima** [comment]
Just as note, yesterday everything worked fine! No changes are made, today i got supprised by this. Happens on my private selfhosted instance and on community.humhub.com as well!

**Comment by acs-ferreira** [comment]
See https://github.com/yiisoft/yii2-authclient/issues/241

**Comment by acs-ferreira** [comment]
So, as quick fix, you should add

`'returnUrl' => 'http://localhost:8080/admin/auth/auth?authclient=google',`

to
```
return [
    // ...
    'components' => [
        // ...
        'authClientCollection' => [
            'clients' => [
                // ...
                'google' => [
                    'class' => 'humhub\modules\user\authclient\Google',
                    'clientId' => 'Your Client ID here',
                    'clientSecret' => 'Your Client Secret here',
                    'returnUrl' => 'Your Return URL here',
                ],
            ],
        ],
        // ...
    ],
    // ...
];
```

**Comment by DeltaLima** [comment]
Thanks a million!! That did the trick, haven't found this yii ticket by myself.
But strange, why it's now necessary to define the returnURL in the config as well.

Best regards! :)

**Comment by acs-ferreira** [comment]
This will probably be fixed `Yii` side soon to remove the `scope`.

**Comment by acs-ferreira** [comment]
This has been fixed on the latest `yii2-authclient` release `2.1.7`.
https://github.com/yiisoft/yii2-authclient/commit/5d244801ea907928ea0b14eb5235989f37174a16

Can be closed.

**Comment by DevBrasil** [comment]
> So, as quick fix, you should add
> 
> `'returnUrl' => 'Your Return URL here',`
> 
> to
> 
> ```
> return [
>     // ...
>     'components' => [
>         // ...
>         'authClientCollection' => [
>             'clients' => [
>                 // ...
>                 'google' => [
>                     'class' => 'humhub\modules\user\authclient\Google',
>                     'clientId' => 'Your Client ID here',
>                     'clientSecret' => 'Your Client Secret here',
>                     'returnUrl' => 'Your Return URL here',
>                 ],
>             ],
>         ],
>         // ...
>     ],
>     // ...
> ];
> ```

Thankss, sooo much, solved my problem
