### ISSUE TITLE
Notifications not generated

### ISSUE THREAD

**Issue by chillusmaximus** [humhub/humhub#3263]
### What steps will reproduce the problem?
All of the actions in the system generating notifications aren't working, since we updated to 1.3.1

It seems like there have been a few problems with the notifications that were caused by a missing originator_user_id by other users.
This is not the problem we seem to have.

### What is the expected result?
Users should receive a notification.

### What do you get instead?
Nothing.

### Additional info
What have I done so far:
1. php yii integrity/run
-> I get an exception while validating the Activity Module:
`Exception 'yii\db\IntegrityException' with message 'Call to an inconsistent poly                                                    morphic relation detected on humhub\modules\activity\models\Activity (humhub\modules\user\models\Follow:88)'`

2. Looking for a NULL in notification.originator_user_id - all is fine

If I'm creating tasks or mention users in the timeline, I don't get any errors in Administration --> Information --> Logging.
The notification doesn't get created.

The last database entry in notification was created before we updated to 1.3.1.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1
| PHP version      |  7.1
| Operating system | Linux Gentoo

**Comment by acs-ferreira** [comment]
Is this related? https://github.com/humhub/humhub/issues/3194

**Comment by chillusmaximus** [comment]
I read that thread too. I also tried the offered solutions but it didn't work for me. And as far as I understood, they was a fix in 1.3.1 which didn't work for my problem.

**Comment by buddh4** [comment]
Did you configure the new crojobs/queue as mentionen in the [Upate Guide](http://docs.humhub.org/admin-updating-130.html) without those no notifications will be sent.

**Comment by chillusmaximus** [comment]
That was the problem. Thanks for your help! :)

**Comment by blu-IT** [comment]
I already configured the cron jobs and they are running, but I still have the problem that notifications are not sent.

**Comment by blu-IT** [comment]
I also did _php yii integrity/run_ but no error was shown, everything is fine.
