### ISSUE TITLE
Survey and calendar appointments can't be moved to other spaces (v.1.3.1)

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#3270]
### What steps will reproduce the problem?
Post a survey or a calendar appointment into one space and after that try to move that item to another spave

### What is the expected result?
Item is moved/posted in another space

### What do you get instead?
Message: "This type of item cant be moved"

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1
| PHP version      | 5.x
| Operating system | n.a

**Comment by buddh4** [comment]
The move behaviour has to be supported by the modules itself, this will be implemented soon, (in case of the claendar module this will be supported from v1.3.2) I'll close this for now since this is not a core issue.
