### ISSUE TITLE
Display queue of background jobs

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#3272]
### What steps will reproduce the problem?
With HumHub v. 1.3.1 there are some counters for "background jobs", e.g. waiting, reserved, completed... - can't see what jobs are inside that queues.

### What is the expected result?
Can*t see any jobs pending/what type of job it is.

### What do you get instead?
Only a visible counter.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1
| PHP version      |  5.x
| Operating system | n.a.

**Comment by buddh4** [comment]
As mentioned in your other issue you probably did not configure the queue worker see:

 - [Install Guide](http://docs.humhub.org/admin-installation-configuration.html#cronjobs-and-asynchronous-job-processing-v13)
- [Asynchronous Task Processing ](http://docs.humhub.org/admin-asynchronous-tasks.html)
