### ISSUE TITLE
Remove or hide image filenames in stream

### ISSUE THREAD

**Issue by iello** [humhub/humhub#3274]
### https://goo.gl/iSfZCD

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Under `ACP --> Settings --> Advanced --> Files` you'll find the option to hide file tags and only show the image.
