### ISSUE TITLE
Permalinks to comments

### ISSUE THREAD

**Issue by iello** [humhub/humhub#3275]
###Comment on a stream

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1
| PHP version      | 7
| Operating system | Ubuntu 16.04

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
This isn't possible in HumHub at this time, an interesting idea though!

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/4399#issuecomment-880665406
