### ISSUE TITLE
Problem with cron jobs

### ISSUE THREAD

**Issue by dmitrydrynov** [humhub/humhub#3279]
### What steps will reproduce the problem?
I receive the error after upgrade my ubuntu from 14.04 to 16.04 and remove apache. Now my server work on nginx + php-fpm + mysql. Everything works fine besides cron jobs.

### What do you get instead?
yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\queue\driver\MySQLCommand::phpBinary in /home/polygon/campus/protected/vendor/yiisoft/yii2/base/Component.php:154 Stack trace: #0 /home/polygon/campus/protected/humhub/modules/queue/driver/MySQLCommand.php(32): yii\base\Component->__get('phpBinary') #1 /home/polygon/campus/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(106): humhub\modules\queue\driver\MySQLCommand->handleMessage('9', 'O:44:"humhub\\mo...', '300', 33) #2 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}('9', 'O:44:"humhub\\mo...', '300', 33) #3 /home/polygon/campus/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(136): call_user_func(Object(Closure), '9', 'O:44:"humhub\\mo...', '300', 33) #4 /home/polygon/campus/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(84): yii\queue\cli\Queue->handleMessage('9', 'O:44:"humhub\\mo...', '300', 33) #5 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(yii\queue\cli\SignalLoop)) #6 /home/polygon/campus/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(108): call_user_func(Object(Closure), Object(yii\queue\cli\SignalLoop)) #7 /home/polygon/campus/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(94): yii\queue\cli\Queue->runWorker(Object(Closure)) #8 /home/polygon/campus/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false) #9 [internal function]: yii\queue\db\Command->actionRun() #10 /home/polygon/campus/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #11 /home/polygon/campus/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #12 /home/polygon/campus/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('run', Array) #13 /home/polygon/campus/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array) #14 /home/polygon/campus/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array) #15 /home/polygon/campus/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array) #16 /home/polygon/campus/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #17 /home/polygon/campus/protected/yii(29): yii\base\Application->run() #18 {main}

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version 1.3.2  | 
| PHP version   7.2.9   |  
| Operating system Ubuntu 16.04.5 LTS  |

**Comment by luke-** [comment]
Are you using the GitHub source directly?

If yes, please run "composer install".

**Comment by acs-ferreira** [comment]
Are you using PHP opCache?
If yes, try to restart PHP as old opcode may be present.

**Comment by dmitrydrynov** [comment]
I solved this problem. Deleted vendor folder and update composer.json (and .lock) and run composer install again. 
Thanks for the help.
