### ISSUE TITLE
Migration to new server failed; reinstall doesnt work

### ISSUE THREAD

**Issue by petrk94** [humhub/humhub#3280]
Hello,
I want to move my humhub installation on a new folder, but even after cloning the sql table as well changing the URL Base name in phpmyadmin, It didnt worked.

Due I could not got it running again (what is really bad), I wanted to set it up again, but even after using the modified .htaccess file from the original installation, it doesnt work.

I hope you can help, thanks

 [error] [pid 19657] mod_proxy_fcgi.c(834): [client xx.xx.xx.xx] AH01071: Got error 'PHP message: PHP Warning:  require(/var/www/virtual/digihz/humhub.xxx.de/protected/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/virtual/digihz/humhub.xxx.de/index.php on line 13\nPHP message: PHP Fatal error:  require(): Failed opening required '/var/www/virtual/digihz/humhub.xxx.de/protected/vendor/autoload.php' (include_path='.:/opt/remi/php72/root/usr/share/pear:/opt/remi/php72/root/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/virtual/digihz/humhub.xxx.de/index.php on line 13\n'

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.2
| PHP version      |  7.2
| Operating system | CentOS 7

**Comment by acs-ferreira** [comment]
As it at https://community.humhub.com as this is not a bug.

**Comment by petrk94** [comment]
Well, sorry, but it seems it is a bug.
Its missing the autoload.php. I have downloaded the latest github release und from the website.
PHP Fatal error: require(): Failed opening required '/var/www/virtual/digihz/humhub.xxx.de/protected/vendor/autoload.php'  is the error message, due the file doesnt exist in the folder, even not here in the github master repo. This cause the problem.
How to solve this?

**Comment by dreua** [comment]
For future me landing here via google:

```
sudo -u apache bash # adapt to your system, php yii command should be called as the www-data or apache or whatever user php usually runs on
php yii cache/flush-all
```

**Comment by karlquint** [comment]
This helped in my case as well. I moved to a new URL and also had to change the following config settings:

- in protected/config/dynamic.php: the mysql credentials
- in the sql dump: all references from the old URL to new URL
- new cronjob entries on the target system
- email settings in the admin dashboard (if not using the php.ini settings)
