### ISSUE TITLE
Bug: Private posts seen by friends

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#3283]
### What steps will reproduce the problem?
Create a private post on your profile then have someone friend you and they will be able to see the private post. They can also like and comment on these posts!

### What is the expected result?
The person who friends you shouldn't be able to see your private posts.

### What do you get instead?
Visible private posts.

### Additional info
<br>

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.2
| PHP version      |  7.1
| Operating system | Linux (CentOS 6)

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by acs-ferreira** [comment]
?

Public = **Anyone** can see
Private = **Only friends** can see _(so, correct behavior)_

Am i wrong?

**Comment by Felli** [comment]
Private posts should only be seen by those that are either tagged in via the Notify members option or via being public and tagged in the post, if a friend is able to see a private post then it's not truly a private post. :smile:

**Comment by acs-ferreira** [comment]
Humm...Private posts in **spaces** are visible by members, public ones by everyone... 🤔

**Comment by Felli** [comment]
I believe that if a post is meant to be private on a profile then it should be made truly private, unless someone is mentioned in **_Notify members_**.

**Comment by acs-ferreira** [comment]
Ok, not my opinion as Notify Members is only to fire a Notification to specific members.
But just my opinion 😄

Otherwise, private posts means that HumHub is not "social" anymore but a "private-note-taker". 😸

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/3818 Moved here
