### ISSUE TITLE
NewNotification count update invalid for grouped notifications.

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3286]
### What steps will reproduce the problem?

1. Create a Post
2. Comment on this post with two users at the same time

### What is the expected result?

Notification Count updated to 1

### What do you get instead?

Notification Count updated to 2
After opening the notification counter its reverted to 1.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by funkycram** [comment]
@luke- I don't have this bug on Humhub 1.10 (just tested), it seams to be solved.

**Comment by luke-** [comment]
@funkycram Thanks for the testing!
