### ISSUE TITLE
Code block is not rendered correctly

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3287]
See this screenshot:

#### Before post
![image](https://user-images.githubusercontent.com/12234510/45353266-b204be80-b5ba-11e8-8f89-0ad95713e276.png)

#### After submit
![image](https://user-images.githubusercontent.com/12234510/45353287-bd57ea00-b5ba-11e8-8694-95661e29ffca.png)

**Comment by buddh4** [comment]
Related to https://github.com/ProseMirror/prosemirror-markdown/issues/3
