### ISSUE TITLE
Can't update from 1.3.0-beta.1 to 1.3.2 with HumHub Updater, says: Update not found -help?

### ISSUE THREAD

**Issue by ivanlinares** [humhub/humhub#3288]
deleted and reinstalled HumHub updater with no luck.

Spanish language. 1.3.0B1 Version 

Kindly, any help?

**Comment by luke-** [comment]
If you're using a beta release, please make sure the "Beta Channel" is enabled in the updater module configuration.

**Comment by Tie-fighter** [comment]
Had the same problem, only noticed it by coming across this ticket by chance.

I'd like to ask you for two changes:

1. Stable channel should be able to upgrade to stable releases.
2. A more prominent placement of what the current stable version is. I couldn't find that info neither on the Homepage, nor on github, nor in my installation.

**Comment by Felli** [comment]
@Tie-fighter all stable releases are announced under the News tab on the HumHub website, and all releases can be found on the Downloads tab as well under the releases tab on the GitHub repo. :smiley:

**Comment by buddh4** [comment]
You should also receive a notification as administrator when there is a new core version available.
