### ISSUE TITLE
No valid component class found for given node

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3292]
### What steps will reproduce the problem?
Add tags to a space.
_(it can also be reproduced with other actions)_

### What is the expected result?
Tags added and message "Saved" appears

### What do you get instead?
Message appears:

`No valid component class found for given node `

containing:

```
{
    "0": {
        "jQuery321059110090791787712": {
            "uiWidget": "activity.ActivityStream"
        }
    },
    "length": 1
}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.2
| PHP version      | 7.2.9
| Operating system | Ubuntu

**Comment by wdevlop** [comment]
I'm having the same problem like you and I need Help

**Comment by buddh4** [comment]
@wdevlop check the javascript logs (http://docs.humhub.org/admin-troubleshooting.html) there may be other js issues. Also try flushing the cache `Administration -> Settings -> Advanced -> Cache`
