### ISSUE TITLE
Cron Jobs not working

### ISSUE THREAD

**Issue by NENJAK** [humhub/humhub#3293]
Hi,

recently I  installed version 1.3.2
and since then my Cron Jobs are not working any more, I got:
Warning incomplete setup!

    The cron job for the background jobs (queue) does not seem to work properly.
    The cron job for the regular tasks (cron) does not seem to work properly.

And I can not enter anything in HumHub (browser) 
In Background Jobs I have:
Queue Status
Driver
MySQL

Waiting
310

Delayed
0

Reserved
0

Done
2635

Thank you

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Please read from here (https://github.com/humhub/humhub/issues/3271#issuecomment-419673042) down.

**Comment by NENJAK** [comment]
Thanks, I will

**Comment by webikasite** [comment]
Good Day!
we have problem with humhub also **Warning incomplete setup!**
The cron job for the background jobs (queue) does not seem to work properly.
The cron job for the regular tasks (cron) does not seem to work properly.

pls help me

**Comment by Bechaker** [comment]
Hello
This error started to appear and I can't find any evidence that tells me why

"The cron job running jobs in the background (queue) doesn't seem to be working properly."
![Error1](https://user-images.githubusercontent.com/43526466/118207317-66250a00-b432-11eb-903e-3aa258111491.jpg)
![error2](https://user-images.githubusercontent.com/43526466/118207320-67eecd80-b432-11eb-90a4-9f8ccc2fb036.jpg)
