### ISSUE TITLE
Not an Issue -- Looking for a possible dev to handle some new items!

### ISSUE THREAD

**Issue by deehill** [humhub/humhub#3299]
Hi.

I apologize or this if the post steps on toes!

I'm thinking of using humhub, but I'd like to have some extra items/functions. I'm willing to discuss $$$. If someone has the dev skills, understands the guts of humhub, as well as the overall yii framework, fel free to hit me up.

thanks

**Comment by danielkesselberg** [comment]
https://www.humhub.org/en/service/customization

**Comment by deehill** [comment]
Hey Daniel,

Thanks -- not sure how I missed that!.  I recall seeing the "marketplace" section. Oh, do you know of a method/way to get in touch with any of the devs of the marketplace apps/modules? Any one of these could probably do what I need with no problem.

thanks

-bruce
badouglas@gmail.com

**Comment by danielkesselberg** [comment]
Most modules are developed by @humhub/official-developer-team. You can use "get in touch" on the above page. 

I know that @Felli (https://github.com/GreenMeteor) release a bunch of modules for humhub. I have seen other module authors but can't remember the names :see_no_evil:

**Comment by deehill** [comment]
Hi.

If you're up to making mods for humhub, hit me up and let's discuss.

-bruce
badouglas@gmail.com

**Comment by buddh4** [comment]
Please discuss such issues in the [Community](http://community.humhub.com/)
