### ISSUE TITLE
Destroyed Layout

### ISSUE THREAD

**Issue by sokobauno** [humhub/humhub#3301]
After installing Community Edition HumHub 1.3.2 
Layout looks like this  
![screenshot_2018-09-19 ubersicht - klasse3a](https://user-images.githubusercontent.com/29429441/45744309-8a3ad980-bbfe-11e8-9d39-74d71f6c7c13.png)

What could be wrong?

**Comment by Felli** [comment]
Clear cache and make sure that you're using a supported PHP version.

**Comment by buddh4** [comment]
Did you install by git and switched to production mode without building the production assets? If yes try: http://docs.humhub.org/dev-build.html#build-assets
