### ISSUE TITLE
smiley are not render into last activity module and email 

### ISSUE THREAD

**Issue by happyfredo** [humhub/humhub#3302]
### What steps will reproduce the problem?
Posting a smiley :slightly_smiling_face:
### What is the expected result?
Have a smiley
### What do you get instead?
":"slightly_smiling_face":" (doublequote for non render in github)
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.2
| PHP version      | 5.6
| Operating system | DEBIAN 8

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by acs-ferreira** [comment]
Confirmed.
