### ISSUE TITLE
Tag user

### ISSUE THREAD

**Issue by xilmen** [humhub/humhub#3303]
Hello !
I can not tag users with the "@user_name" feature even if the user exists he says "not found". 
I look in the stack trace ... I have no mistake ... 
I'm the only one in this case?

| HumHub version   | 1.3.2
| PHP version      |  5.6
| Operating system | CentOS 7

**Comment by buddh4** [comment]
Try rebuilding the [Search Index](http://docs.humhub.org/admin-search.html#index-rebuilding).

**Comment by xilmen** [comment]
It's work ty, 

i make : 
php yii queue/run 
php yii cron/run

well ... my crontab dont works now ... my bad
