### ISSUE TITLE
Error when manual upgrade

### ISSUE THREAD

**Issue by happyfredo** [humhub/humhub#3304]
### What steps will reproduce the problem?
Try to manual upgrade from 1.0 Beta 3 to 1.3.2
### What is the expected result?
When i launch php yii migrate/up --includeModuleMigrations=1
### What do you get instead?
Apply the above migrations? (yes|no) [no]:yes
*** applying m160125_053702_stored_filename
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: humhub\modules\file\models\File::getPath()'

in /var/www/clients/client2/web5/web/protected/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /var/www/clients/client2/web5/web/protected/humhub/modules/file/migrations/m160125_053702_stored_filename.php(12): yii\base\Component->__call('getPath', Array)
#1 /var/www/clients/client2/web5/web/protected/humhub/modules/file/migrations/m160125_053702_stored_filename.php(12): humhub\modules\file\models\File->getPath()
#2 /var/www/clients/client2/web5/web/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): m160125_053702_stored_filename->up()
#3 /var/www/clients/client2/web5/web/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(199): yii\console\controllers\BaseMigrateController->migrateUp('m160125_053702_...')
#4 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#5 /var/www/clients/client2/web5/web/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /var/www/clients/client2/web5/web/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /var/www/clients/client2/web5/web/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('up', Array)
#8 /var/www/clients/client2/web5/web/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('up', Array)
#9 /var/www/clients/client2/web5/web/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#10 /var/www/clients/client2/web5/web/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/up', Array)
#11 /var/www/clients/client2/web5/web/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 /var/www/clients/client2/web5/web/protected/yii(29): yii\base\Application->run()
#13 {main}

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.2
| PHP version      | 5.6
| Operating system |Debian 9

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by acs-ferreira** [comment]
Same as https://github.com/humhub/humhub/issues/2674

**Comment by buddh4** [comment]
Should be fixed by https://github.com/humhub/humhub/commit/d1cbaa7abda601cd4c3e53f65b8a3e8808ec2580
