### ISSUE TITLE
No notification sent after mention a person in a post

### ISSUE THREAD

**Issue by DeltaLima** [humhub/humhub#3305]
### What steps will reproduce the problem?

Write a post and mention a person with @personname

### What is the expected result?

You will get a notification that you got mentioned in a post

### What do you get instead?

No notification

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1
| PHP version      | PHP 7.0.30-0+deb9u1 
| Operating system | Debian 9.5

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
This is already fixed in current master.
