### ISSUE TITLE
Custom changes destroyed Calendar comment possibility

### ISSUE THREAD

**Issue by AlphabetoPT** [humhub/humhub#3306]
### What steps will reproduce the problem?
I have made some changes on the core, and now the Calendar module does not accept comments.
Reason that this is happening is because i can't retrieve the following object:

`$authorID = $this->parentContent->created_by;`

Note that this only happens when the calendar is the element being commented.
This happens because calendar module DB structure does not have the 'created_by' field.
That is OK.

### What is the expected result?
What i need to do is find a bypass, so, when the calendar event is being commented, that part is not read. 
My idea is something like:
`if($this->parentContent->contentModel == "humhub\modules\post\models\Post" OR $this->parentContent->contentModel){
// execute the code that is not compatible with calendar.
}`

I know there must be a way of executing the code only when the comment is NOT posted on a Calendar Event.

I am changing the code on `/protected/humhub/modules/comment/controllers/CommentController.php`

here is the Full code, the part that breaks with the CALENDAR event comments is flagged with a capslock comment. starting on line 111.

FULL CODE:
[https://pastebin.com/db4Bjd23](https://pastebin.com/db4Bjd23)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.2
| PHP version      |  7.0.32
| Operating system | Ubuntu Server 16.04.1

**Comment by buddh4** [comment]
Try `$this->parentContent->getContent()->created_by`. The underlying `Content` record should always have a `created_by` field.

You should also be able to call `$this->parentContent->getContent()->createdBy` to retreive the actual author user.

It seems you try to implement a user scoring. You should rather listen to create/update events of the `Comment` within a custom module instead of changing the core.

**Comment by AlphabetoPT** [comment]
i tested it on the following part:

`// THIS IS THE PART THAT ONLY WORKS WHEN ITS NOT A CALENDAR COMMENT

    $authorID = $this->parentContent->getContent()->created_by;
    //check if author different than comment author
      if($id != $authorID){
        $userTaker = \humhub\modules\user\models\User::findOne(['id' => $authorID]);
        $userTaker->score = $userTaker->score + 1;
        $userTaker->save();
      }`

it came out as error:
https://pastebin.com/4YHSHNKq

**Comment by buddh4** [comment]
Always add the full error logged in "Administration -> Information -> Logging". Please switch to our https://community.humhub.com/dashboard for such questions, we use github only for bug tracking.
