### ISSUE TITLE
New spaces are not shown in the directory

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#3308]
### What steps will reproduce the problem?
Create a new space, set visibility to "**public**" (default) and accessibility to everyone.
The space is **not visible/shown** in the directory for me (Admin) or other users.
I can find/see this space only when I look in the administration backend -> section spaces.

### What is the expected result?
I expect to see the newly ceated space.

### What do you get instead?
The space is not shown in the directory.

### Additional info
First time this behavior was reported by a user who created a new space with the settings told above.
I first thought it might be a problem with missing rights, so I first tried to take the ownership of this new space with my Humhub admin role. But that did not change anything. The new space is still invisible in the directory.
Then I created another new space, as the many I created before in the system (v. 1.2.8 ) and before the Humhub update to v. 1.3.1/v.1.3.2 - since this updates I have a lot of problems with Humhub. 

No error regarding the new created spaces in the logs

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1
| PHP version      | 5.6.31
| Operating system | -

**Comment by blu-IT** [comment]
I also looked directly into the mysql-db: The settings/values of the new spaces are exactly as the spaces created before in v. 1.2.8 (except guid), so it does not seem a wrong config or database issue to me.

**Comment by blu-IT** [comment]
Even if I use the search funtcion of the directory the space is not shown/found in the list.

**Comment by acs-ferreira** [comment]
Can you run these commands one by one with at least PHP5.6?

```
yii integrity/run
yii search/rebuild
yii cache/flush-all
```

If any errors, report them.

**Comment by Felli** [comment]
Rebuild the search index, you'll find how in the Docs, you can also use the button under `ACP --> Information --> Database` to activate a search index rebuild.

**Comment by blu-IT** [comment]
...and what happend now, is that I can see the new created space **BUT** all my members ins the directory are disappeared!

**Comment by danielkesselberg** [comment]
https://github.com/humhub/humhub/blob/f8a3b14c9b46f993080ff02db0e9b952bed025dc/protected/humhub/libs/Iso3166Codes.php#L526

When this fails php-intl is missing.

**Comment by blu-IT** [comment]
@danielkesselberg 

Well, dependency check in the Backend says:

```
PHP - INTL Extension - ICU Version (52.1)
PHP - INTL Extension - ICU Data Version (52.1)
``` 

is OK!

**Comment by acs-ferreira** [comment]
@blu-IT 
> I also retried to rebuild the index via webfrontend, the frontend still says "Search index rebuild in progress." while at the console it finished immediately with the error mentioned above.

These are processed by the Cronjobs, if they aren't running...it will not be processed.

Have you run the commands with:

`php yii ....`

or with

`/usr/local/bin/php56 yii ....` ?

Try the second one.

**Comment by acs-ferreira** [comment]
> 
> 
> @acs-ferreira
> @Felli
> 
> Thanks for your help!
> 
> I run the commands above, everything went fine - no errors, except the search/rebulid:
> 
> ```
> ./yii search/rebuild
> X-Powered-By: PHP/5.6.31
> Content-type: text/html; charset=UTF-8
> 
> Rebuild search index: PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'Locale' not found'
> 
> in /kunden/548428_64711/forum-test/protected/humhub/libs/Iso3166Codes.php:526
> 
> Stack trace:
> #0 [internal function]: yii\base\ErrorHandler->handleFatalError()
> #1 {main}
> ```

Instead of `./yii search/rebuild` run `/usr/local/bin/php56 yii search/rebuild`

**Comment by mk314** [comment]
I've had the same issues as @blu-IT . New spaces weren't added to the directory. That seemed to be related to #3271 . The same `404 Not Found` error appeared in my log when running `php yii queue/run`. Initially, I just wanted to share that I'm experiencing the same issues, but having spent hours on this problem, I rather accidentally found the solution (at least in my case):

Like blu-IT, I tried the `isolated` option because my installation is on shared hosting:
>     Note: If you're on a shared hosting environment, you may need to add the --isolated=0 option to the queue/run. e.g. /usr/bin/php /path/to/humhub/protected/yii queue/run --isolated=0

When I looked at the first file in the error trace, `\humhub\protected\vendor\yiisoft\yii2-queue\src\cli\Command.php`, I noticed this:

```
public function options($actionID)
    {
        $options = parent::options($actionID);
        if ($this->canVerbose($actionID)) {
            $options[] = 'verbose';
        }
        if ($this->canIsolate($actionID)) {
            $options[] = 'isolate';
            $options[] = 'phpBinary';
        }

        return $options;
    }
```

The option isn't called `isolated`, it's just `isolate`. Since I added the option `--isolate=0` to my `queue/run` cronjob, everything's fine, all new spaces are added to the directory and no more errors are shown in the log. I hope this helps you, @blu-IT !

**Comment by blu-IT** [comment]
@acs-ferreira 
I tried as you suggested

`/usr/local/bin/php56 yii search/rebuild`

still the same error and all my members are not displayed in the directory:

```
/usr/local/bin/php56 yii search/rebuild
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8

Rebuild search index: PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'Locale' not found'

in /kunden/548428_64711/forum-test/protected/humhub/libs/Iso3166Codes.php:526

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

@mk314 

Thanks for that impotant hint! I modified my `queue/run` task and will see if it works. Running manually at the console gave no me no error.
The `--isolate=0` option is only considered for `queue/run`, not for `cron/run` - right? 
Because it tells me 

```
/usr/local/bin/php56 ./yii cron/run --isolate=0
Status: 500 Internal Server Error
X-Powered-By: PHP/5.6.31
Content-type: text/html; charset=UTF-8

Unknown command: --isolate=0
```

**Comment by blu-IT** [comment]
@mk314 
@acs-ferreira

Well, unfortunately my problem with the cron jobs/notifications https://github.com/humhub/humhub/issues/3271 and the subsequent problems still persist. 
The notifications are not sent, the directory is not displaying the new space (until I run /usr/local/bin/php56 yii search/rebuild at the console), members still disapeared and also still gives me the error posted above.

**Comment by danielkesselberg** [comment]
`/usr/local/bin/php56 -v`
`/usr/local/bin/php56 -m | grep intl`

**Comment by blu-IT** [comment]
```
/usr/local/bin/php56 -v
PHP 5.6.31 (cgi-fcgi) (built: Oct  1 2017 11:48:18)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
`/usr/local/bin/php56 -m | grep intl` 
no output - so as you guessed php-intl is missing? 
But why does the dependency check say everything is OK?! So let me see if I can activate php-intl on that server (shared environment).

**Comment by blu-IT** [comment]
My php.ini has `extension = "intl.so"` but it seems ist is not loaded.
Even I configured to use latest PHP 5.6.34 ist seems to call 5.6.31 when working on the console. 
What a mess!

**Comment by danielkesselberg** [comment]
Because your webserver is using another php sapi. You can have different php.ini for each sapi. I guess for your webserver the module is loaded but not for `/usr/local/bin/php56`. 

For running php scripts from cli you should use php-cli. See the (cli) in the output below. 
This looks like a bad server configuration to me (placing a cgi-fcgi where you would expect a cli).

<pre>/usr/bin/php5.6 -v
PHP 5.6.37-1+ubuntu18.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
    with blackfire v1.22.0~linux-x64-non_zts56, https://blackfire.io, by Blackfire
</pre>

I would inspect `/usr/local/bin` and look for other php versions. Try `/usr/local/bin/ | grep php` maybe there is a "cli" or newer version.

**Comment by danielkesselberg** [comment]
I agree with you that (especially in shared hosting environments) finding the "right" php version could be a nightmare :see_no_evil:

**Comment by blu-IT** [comment]
@danielkesselberg 

**THANKS SO MUCH!!!** You saved my day!!! Jobs running, notifications working!!!!

You were right! I have to call my jobs on the console like this:

```
/usr/local/bin/php5.6.34-cli ./yii search/rebuild
/usr/local/bin/php5.6.34-cli ./yii queue/run --isolate=0
/usr/local/bin/php5.6.34-cli ./yii cron/run
```
Now I will have to see to get my cron job script done ;-)

**Thanks again to all of you who worked on this issue for your untiring patience!!!**
