### ISSUE TITLE
Can't change space ownership as humhub admin

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#3309]
### What steps will reproduce the problem?
A user created a new space. While detecting some errors posted here in this issue https://github.com/humhub/humhub/issues/3308 I wanted to transfer the ownership of this space to myself (humhub admin role), to see if the error of non-visibility does affect to the user rights. When I click at the transfer ownership, the dialog switches to "green", but the space ownership still belongs to the old user.

### What is the expected result?
The ownership is transferred to me.

### What do you get instead?
The space ownership still belongs to the old user.

### Additional info
I asked the user to transfer the ownership to me. He said he did, but was still displayed as owner.
Then I retried myself and this time I could select my account in the dropdown and the ownership was transferred to me. 
I expected as a Humhub **admin to be able to transfer ownership of spaces at any time** to myself **without any intervention by the user/owner** or do I get wrong something?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.2
| PHP version      |  5.6.34
| Operating system | -

**Comment by acs-ferreira** [comment]
You must be an `Administrator` of that space before transfer ownership. Is that the case?

**Comment by acs-ferreira** [comment]
I agree. But https://github.com/humhub/humhub/issues/2871 https://github.com/humhub/humhub/issues/2721 https://github.com/humhub/humhub/issues/2624 https://github.com/humhub/humhub/issues/2623 and so on... 💭

**Comment by blu-IT** [comment]
OK, thanks for the info and hint!
So I saw that some of the issues are already marked as "closed". 
Should I keep this one open, so that it is not goinmg to be lost on the roadmap? ;-)

**Comment by luke-** [comment]
Should be fixed in latest version
