### ISSUE TITLE
can't override  /protected/widgets/views/topNavigation.php

### ISSUE THREAD

**Issue by raxan** [humhub/humhub#331]
Hi

I am trying to override  /protected/widgets/views/topNavigation.php

which I create under /themes/mytheme/views/widgets/topNavigation.php

thanks

**Comment by sc0ttius** [comment]
I'm having a similar issue with tourPanel.php. Based on the documentation, it seems it should be mytheme/views/tour/widgets/tourPanel.php but that does not work.

**Comment by luke-** [comment]
Should be fixed

Comment:     views/comment/widgets/showComment.php
Tour Panel:   views/tour/widgets/tourPanel.php
