### ISSUE TITLE
Getting issue in install of HumHub 1.3.3

### ISSUE THREAD

**Issue by GaneshKandu** [humhub/humhub#3312]
### What steps will reproduce the problem?
Extract the humhub 1.3.3 into the htdocs folder of your webserver.
set permission mentioned on site
Open in your browser

### What do you get instead?
```
An Error occurred while handling another error:
exception 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'humhub'' in /home/user/public_html/manual/humhub133/protected/vendor/yiiuser/yii2/db/Connection.php:687

Next exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'humhub'' in /home/user/public_html/manual/humhub133/protected/vendor/yiiuser/yii2/db/Connection.php:624
```
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.3
| PHP version      | 5.6.37
| Operating system | CentOS
| Apache | 2.2.34

[humhub_error.txt](https://github.com/humhub/humhub/files/2414026/humhub_error.txt)

**Comment by acs-ferreira** [comment]
> Access denied for user ''@'localhost'

As y can see, you've not specified correct credentials for your database (user is empty).
Please verify that **Databse name, Host, User and Password** are correct.

User and Databse must be created **before** install HumHub.

**Comment by GaneshKandu** [comment]
is HumHub have any install wizard ? using browser

**Comment by mk314** [comment]
I had the same issue when trying to install HumHub 1.3.3. The error appears even before the web installer started, so it's not possible to enter any credentials. My workaround was to install HumHub 1.3.2 (without any errors) and then update with the HumHum Updater module.

**Comment by mk314** [comment]
Apparently, [version 1.3.4](https://humhub.org/de/download) is now available, fixing exactly this issue.

**Comment by GaneshKandu** [comment]
@acs-ferreira  @luke-  for fix
Working now
