### ISSUE TITLE
Error when i try to connect first time with ldap

### ISSUE THREAD

**Issue by happyfredo** [humhub/humhub#3315]
### What steps will reproduce the problem?
On a new fresh install. Connect for the first time with LDAP. The user are register but we have an error. It try to record twice the user. (We don't use automatic ldap user checkbox in settings ldap).
### What is the expected result?
Connect !
### What do you get instead?
2018-09-26 17:47:43 [46.218.94.163][-][cuj58eed61ilkupeffha39f6f7][error][yii\db\IntegrityException] exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9' for key 'PRIMARY'' in /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('INSERT INTO `pr...')
#2 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(544): yii\db\Schema->insert('profile', Array)
#4 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(510): yii\db\ActiveRecord->insertInternal(NULL)
#5 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(true, NULL)
#6 /var/www/clients/client2/web7/web/protected/humhub/modules/user/authclient/AuthClientHelpers.php(137): yii\db\BaseActiveRecord->save()
#7 /var/www/clients/client2/web7/web/protected/humhub/modules/user/controllers/AuthController.php(178): humhub\modules\user\authclient\AuthClientHelpers::updateUser(Object(humhub\modules\user\authclient\ZendLdapClient), Object(humhub\modules\user\models\User))
#8 /var/www/clients/client2/web7/web/protected/humhub/modules/user/controllers/AuthController.php(147): humhub\modules\user\controllers\AuthController->login(Object(humhub\modules\user\models\User), Object(humhub\modules\user\authclient\ZendLdapClient))
#9 /var/www/clients/client2/web7/web/protected/humhub/modules/user/controllers/AuthController.php(78): humhub\modules\user\controllers\AuthController->onAuthSuccess(Object(humhub\modules\user\authclient\ZendLdapClient))
#10 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin()
#11 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('login', Array)
#14 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/auth/login', Array)
#15 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#16 /var/www/clients/client2/web7/web/index.php(25): yii\base\Application->run()
#17 {main}

Next exception 'yii\db\IntegrityException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `profile` (`user_id`, `firstname`, `lastname`, `title`, `gender`, `street`, `zip`, `city`, `country`, `state`, `birthday`, `about`, `phone_private`, `phone_work`, `mobile`, `fax`, `im_skype`, `im_msn`, `im_xmpp`, `url`, `url_facebook`, `url_linkedin`, `url_xing`, `url_youtube`, `url_vimeo`, `url_flickr`, `url_myspace`, `url_googleplus`, `url_twitter`) VALUES (9, 'Test', 'SGI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)' in /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `pr...')
#1 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('INSERT INTO `pr...')
#2 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(544): yii\db\Schema->insert('profile', Array)
#4 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(510): yii\db\ActiveRecord->insertInternal(NULL)
#5 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(true, NULL)
#6 /var/www/clients/client2/web7/web/protected/humhub/modules/user/authclient/AuthClientHelpers.php(137): yii\db\BaseActiveRecord->save()
#7 /var/www/clients/client2/web7/web/protected/humhub/modules/user/controllers/AuthController.php(178): humhub\modules\user\authclient\AuthClientHelpers::updateUser(Object(humhub\modules\user\authclient\ZendLdapClient), Object(humhub\modules\user\models\User))
#8 /var/www/clients/client2/web7/web/protected/humhub/modules/user/controllers/AuthController.php(147): humhub\modules\user\controllers\AuthController->login(Object(humhub\modules\user\models\User), Object(humhub\modules\user\authclient\ZendLdapClient))
#9 /var/www/clients/client2/web7/web/protected/humhub/modules/user/controllers/AuthController.php(78): humhub\modules\user\controllers\AuthController->onAuthSuccess(Object(humhub\modules\user\authclient\ZendLdapClient))
#10 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin()
#11 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('login', Array)
#14 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/auth/login', Array)
#15 /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#16 /var/www/clients/client2/web7/web/index.php(25): yii\base\Application->run()
#17 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry '9' for key 'PRIMARY'
)
↵
Caused by: PDOException
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7' for key 'PRIMARY'
in /var/www/clients/client2/web7/web/protected/vendor/yiisoft/yii2/db/Command.php at line 1258

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.4
| PHP version      | 5.6
| Operating system | DEBIAN 9

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by OCI-Digital** [comment]
Hello, 

Same problem for me, does anyone have a solution ?

Thanks in advance

**Comment by OCI-Digital** [comment]
Hello,

Same problem for me, does anyone have a solution ?

Thanks in advance

**Comment by mirktmirkt** [comment]
Hello,

I have had the same issue just after installation of Humhub 1.3.4 (on Debian 9) and configuration of LDAP auth (Active Directory).. I have tried logging in with several AD users' credentials and have seen the same error as you, but after some time the problem gone. My guess (I have not tested/investigated it): humhub's cron jobs syncs AD info and solves the problem?

Do you have humhub's cron jobs set?
http://docs.humhub.org/admin-installation-configuration.html#cronjobs-and-asynchronous-job-processing-v13

**Comment by happyfredo** [comment]
> Hello,
> 
> I have had the same issue just after installation of Humhub 1.3.4 (on Debian 9) and configuration of LDAP auth (Active Directory).. I have tried logging in with several AD users' credentials and have seen the same error as you, but after some time the problem gone. My guess (I have not tested/investigated it): humhub's cron jobs syncs AD info and solves the problem?
> 
> Do you have humhub's cron jobs set?
> http://docs.humhub.org/admin-installation-configuration.html#cronjobs-and-asynchronous-job-processing-v13

The user is created even with the error. The cron are ok. I have three install of humhub and have the same error the three. Luke tag it as an error, so we have to wait for a commit or new version to correct the bug.
