### ISSUE TITLE
Meeting Module - Missing the time on print page

### ISSUE THREAD

**Issue by turbobasti** [humhub/humhub#3318]
### What steps will reproduce the problem?
When you want to print a meeting

### What is the expected result?
Print page should include all meeting items with time

### What do you get instead?
Time is missing on meeting items

### To fix this problem
Put this `<?php $meeting->getItemsPopulated(); ?>` in meeting/views/index/print.php

**Comment by buddh4** [comment]
Thanks for the report and fix! ;)
