### ISSUE TITLE
Directory search member not working ZendSearch searchItemLimit

### ISSUE THREAD

**Issue by Mouflin-Guillaume** [humhub/humhub#3321]
Hello everyone,

I have bug with Lucene searching directory member and searchItemLimit. I know that there are others topics on this kind issue but I don't find a real explanation. 

### What steps will reproduce the problem?
My keyword for this research with lucene is: "Le". 
When I search this, I have "ZendSearch\Lucene\Exception\OutOfBoundsException: Terms per query limit is reached"

I have set "searchItemLimit" in my common.php file to "8192" and define max_excution_time to 60 in my php.ini BUT I don't understand why only this keyword give me this error.

I think it's not a really good solution for this problem to change this values.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.3
| PHP version      | 7.1
| Operating system | CentOS

**Comment by helnokaly** [comment]
Maybe that will help

![image](https://user-images.githubusercontent.com/15964842/51293033-ac5e3000-1a15-11e9-9f03-c08a929e56eb.png)
https://framework.zend.com/manual/1.12/en/zend.search.lucene.searching.html
