### ISSUE TITLE
Comment permalink on email summary is wrong

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3326]
### What steps will reproduce the problem?
Comment any post.

### What is the expected result?
Comment is included in summary email, and a link points to the commented post (like the Activity link).

### What do you get instead?
Comment is included, but link behind "See online" is wrong.

Actually: https://my.example.com/?r=content%2Fperma&id=8546 _(redirects to Dashboard)_
Good one : https://my.example.com/s/space-here/?contentId=8546

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.5-dev

**Comment by luke-** [comment]
Did you added the URL Rewriting (http://docs.humhub.org/admin-installation-configuration.html#url-rewriting-optional) to the common.php file or web.php file?

**Comment by acs-ferreira** [comment]
Yes, i did.

```
return [
    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ],
    'params' => [
        'allowedLanguages' => ['en'],
    ],
    'modules' => [
        'stream' => [
            'streamSuppressQueryIgnore' => [
                'humhub\modules\tasks\models\Task',
                'humhub\modules\cfiles\models\File',
                'humhub\modules\wiki\models\WikiPage',
                'humhub\modules\calendar\models\CalendarEntry'
            ]
        ],
    ],
];
```

**Comment by acs-ferreira** [comment]
Issue on my local .htaccess: https://github.com/humhub/humhub/blob/master/.htaccess.dist#L18
