### ISSUE TITLE
groups for ldap users

### ISSUE THREAD

**Issue by kimat** [humhub/humhub#333]
I am trying to put my users into groups base on LDAP filters

- this is the base DN in auth settings : `OU=Users, DC=domain, DC=com`

I then create two groups and set the fields LDAP DN for each as such : 
- `OU=Students, OU=Users, DC=domain, DC=com`
- `OU=Teachers, OU=Users, DC=domain, DC=com`

or as such 
- `OU=Students`
- `OU=Teachers`

Then i ran : 
`php protected/yiic cron hourly`

Both ways, this just added all my users in the Group `Students`.

Can you enlighten me on the correct way to use the `LDAP DN` field when editing a Group and how to enforce it ?

**Comment by dap1995** [comment]
i have this problem

**Comment by nguyencongvu** [comment]
I have Status: Error! (Message: Could not load LDAP! - Check PHP Extension)

What next?
