### ISSUE TITLE
a error after installation in audit

### ISSUE THREAD

**Issue by devcline** [humhub/humhub#3333]
I just installed a fresh copy of humhub and in audit information i got this
i choose to customise myself a community and add a examples while installing

`ERROR  Mon, 15 Oct 2018 07:08:31 +0200  application SQLSTATE[HY000]: General error: 1005 Can't create table 'XXX.#sql-353_44d35' (errno: 150) The SQL being executed was: ALTER TABLE `space_module` ADD CONSTRAINT `fk_space_module-module_id` FOREIGN KEY (`module_id`) REFERENCES `module_enabled` (`module_id`) ON DELETE CASCADE ON UPDATE CASCADE`

**Comment by buddh4** [comment]
Which db engine are you using InnoDB or MyISAM?
