### ISSUE TITLE
Mentioning does not work

### ISSUE THREAD

**Issue by dakur** [humhub/humhub#3334]
### What steps will reproduce the problem?
Try to mention someone with `@username` syntax.

### What is the expected result?
User's name appears in a dropdown list.

### What do you get instead?
`No result` text in dropdown, nothing selectable.

### Additional info
- Does not work for any user.
- We use LDAP server for authentication.
- Screenshot:
![image](https://user-images.githubusercontent.com/9862581/46933799-d0e0ef80-d055-11e8-884d-ad44077d3e0c.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.6
| PHP version      | PHP 5.6.32-1+ubuntu14.04.1+deb.sury.org+1
| Operating system | Ubuntu 14.04.1

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

No errors found.

**Comment by buddh4** [comment]
Did you already try rebuilding the search index?

**Comment by dakur** [comment]
@buddh4 No and it solved it. But it's kinda stupid that I have to do one more step to have Humhub fully working after GUI update. There was not any mention about it either. Could not it be part of the update?

**Comment by buddh4** [comment]
This is not related to any gui change. This is related to a broken search index, which unfortunately can happen with zend lucene. In the upcoming v1.4 we'll not use the search index for mentionings and the directoy and also provide a guide how to switch from zend lucene to [solr](http://lucene.apache.org/solr/) which is way more performant and stable. I think the solr driver is currently only available in the [enterprise edition](http://docs.humhub.org/ee-solr.html), but in my opinion its too important provide the possibility to switch also in the community edition.

**Comment by dakur** [comment]
@buddh4 Yeah, but why couldn't be search reindex part of GUI update? (I mean update from GUI.) It does not break anything and it helps in case search index would be broken.

**Comment by buddh4** [comment]
I think since v1.3 there is a gui interface for this under "Administration -> Administration -> Database"

**Comment by dakur** [comment]
@buddh4 I know, I am asking, why this could not be part of update process.
