### ISSUE TITLE
Apple add to home screen not work anymore

### ISSUE THREAD

**Issue by arttu-uusikyyny** [humhub/humhub#3338]
Apple add to home screen not work anymore. Safari shows searching bar.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.6
| PHP version      | newest
| Operating system | IOS 12.1

**Comment by buddh4** [comment]
We'll rework the Progressive Webapp Compativility in v1.4

**Comment by luke-** [comment]
Fixed in 1.4
