### ISSUE TITLE
Enhancement: Multi Language Hubs

### ISSUE THREAD

**Issue by devcline** [humhub/humhub#3339]
Any future ideas how yo make a hubs multi language?
Instead of creating hubEN and hubFR it would be the same hub , but the information of title and description would defied by the selected language in profiles, would be sweet

**Comment by Felli** [comment]
You mean like https://translate.humhub.org ? From my understanding, HumHub supports a number of languages out of the box and can be changed via profile settings. Either way this would be better asked in the community site.

**Comment by devcline** [comment]
i mean each hub TITLE and DESCRIPTION is translates by hub manager it self and show for different languages differently, like the hub "TRANSLATION HUB" will only showed for EN users as "TRANSLATION HUB" and for french users their will be shown as "TRADUCTION HUB"

**Comment by buddh4** [comment]
You mean you want to make the space names translatable?

**Comment by devcline** [comment]
what is the php variable that defines a specific language? thanks

**Comment by danielkesselberg** [comment]
The language for the current user is here `\Yii::$app->language`
