### ISSUE TITLE
Warning incomplete setup! (cron job)

### ISSUE THREAD

**Issue by webikasite** [humhub/humhub#3342]
Good Day!
we have problem with humhub also Warning incomplete setup!
The cron job for the background jobs (queue) does not seem to work properly.
The cron job for the regular tasks (cron) does not seem to work properly.

pls help me

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.6
| PHP version      | 7.2.5
| Operating system | hosting beget.com

CronJob Status
Last run (hourly):
Never 

Last run (daily):
Never

**Comment by acs-ferreira** [comment]
See http://docs.humhub.org/beta/admin-installation-configuration.html

**Comment by webikasite** [comment]
thanks but I already have it.
I do not know where to start and how to use it.
