### ISSUE TITLE
Unable to post content because of crippled entry area

### ISSUE THREAD

**Issue by manuelbaumann-oviva** [humhub/humhub#3344]
### What steps will reproduce the problem?
In a space, click on "What's on your mind?"

### What is the expected result?
I can enter text and upload and media.

### What do you get instead?
A crippled white area:
<img width="222" alt="screen shot 2018-10-20 at 14 03 36" src="https://user-images.githubusercontent.com/29945136/47255408-172cb900-d471-11e8-9df3-46e11f2e377e.png">

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.4
| PHP version      | 7.2.10
| Operating system | Ubuntu0 18.04

**Comment by Felli** [comment]
This is most likely because you're using an outdated theme, please update your theme.css file, you can find an updated version in the default theme here on GitHub.

**Comment by manuelbaumann-oviva** [comment]
Thanks. I updated to the latest version and the issue is gone.
