### ISSUE TITLE
Maintenance mode (for updates)

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#3345]
Hello,

I'd like to see a "maintenance mode" switch for updates, that prevents at least users (expect admins) to log into the system while updating. What about something like that?

Regards,
Ivan

**Comment by blu-IT** [comment]
Thanks for the hint! I tried that module, but unfortunately it doesn't seem to work with HumHub v.1.3.6. It is 4 years old...
I would also would think that such a functionality should be implemented in Humhub it self.

**Comment by yurabakhtin** [comment]
@luke- As I understand we should implement some new general setting that locks the whole site for guests and users except admins.
I guess it should lock with a screen like for not approved user or "must change password" user, but such screen should be displayed even for guests. However, admins should have a possibility to sign in.

Then question where we should turn on the setting for "maintenance mode":
- Should it be some checkbox setting in back-office?
- Or this setting should be automatically turn on when the upgrade process is started and turn off when it is stopped? If yes then all new modifications should be done inside the module https://github.com/humhub/humhub-modules-updater, right?

**Comment by luke-** [comment]
I would suggest the following:

- Under "Administration -> Settings", there is a checkbox "Maintenance Mode".  
When active, there is a sidebar snippet on the dashboard with a red border (similar to Incomplete Setup warning), indicating that Maintenance Mode is Active and only administrators have access.
- When the check box is selected, all sessions should be terminated. Ideally there should also be a Confirm. 
- In addition, there should also be a possibility to activate/deactivate this mode via CLI.
- If this is implemented in the core, we can also do this in the updater module during an update. 

What do you think? Any other ideas?

**Comment by ArchBlood** [comment]
> I would suggest the following:
> 
> * Under "Administration -> Settings", there is a checkbox "Maintenance Mode".
>   When active, there is a sidebar snippet on the dashboard with a red border (similar to Incomplete Setup warning), indicating that Maintenance Mode is Active and only administrators have access.
> * When the check box is selected, all sessions should be terminated. Ideally there should also be a Confirm.
> * In addition, there should also be a possibility to activate/deactivate this mode via CLI.
> * If this is implemented in the core, we can also do this in the updater module during an update.
> 
> What do you think? Any other ideas?

Here's some points that I'd like to make when it comes to this topic
- I'd like to suggest a toggle switch instead of a checkbox if it were implemented in "Administration -> Settings" as it'd look more user friendly as a toggle switch than a checkbox
- I like the idea, I'd also like to suggest that this snippet be displayed with an admin login button not only on the sidebar but in place of the login/sign up form when enabled
- I have no qualms on this, I completely agree with this
- I would love this to be an option, as you never know when something could go wrong and if your session is ended and you're unable to login for various reasons
- Again this would be perfect with a toggle option over checkbox and probably easier to implement

**Comment by luke-** [comment]
@ArchBlood Actually a checkbox is a "toggle element". Maybe we should generally redesign all checkboxes and convert them into toggles. Or do you have a specific idea how this could look like?

**Comment by ArchBlood** [comment]
> @ArchBlood Actually a checkbox is a "toggle element". Maybe we should generally redesign all checkboxes and convert them into toggles. Or do you have a specific idea how this could look like?

Give me a few hours and I can have an example drawn up, but the general idea would be a standard left to right switch that would be toggling on/off

**Comment by luke-** [comment]
Take your time, I would then check if we can include something like this as a general form element in 1.8.

**Comment by buddh4** [comment]
https://uxmovement.com/buttons/when-to-use-a-switch-or-checkbox/

**Comment by yurabakhtin** [comment]
> https://uxmovement.com/buttons/when-to-use-a-switch-or-checkbox/

Ok, as I understand we should not use a "toggle element" together with a submit button, so if we really need this we can create a new separate tab "Maintenance Mode" with a single toggle element and on press it the Maintenance Mode will be enabled maybe ti ajax request without form submitting, but of course with a confirmation.

> When active, there is a sidebar snippet on the dashboard with a red border (similar to Incomplete Setup warning),

Do you think it is enough to inform about Maintenance Mode only on the dashboard sidebar?
I think it would be good to display some red message right under header on each page, so all admins will know this.

> indicating that Maintenance Mode is Active and only administrators have access.

I think here we can display the toggle element(only for admins) to turn off the Maintenance Mode.

> When the check box is selected, all sessions should be terminated.

All sessions except of already logged in admin, right? But should we allow to log in admin users?

**Comment by luke-** [comment]
I would first implement a simple checkbox, a separate tab would be too much, we are somewhat limited here anyway. 

You are welcome to check what kind of representation would be best. Here I am open whether sidebar snippet or red bar on each page. 

Yes, only non-admin sessions should be affected.

**Comment by yurabakhtin** [comment]
@luke- 

> - In addition, there should also be a possibility to activate/deactivate this mode via CLI.

Do we need a new separate command? if we can do this by already existing `php yii settings/...`:

- Activate: `php yii settings/set base maintenanceMode 1`
- Deactivate: `php yii settings/set base maintenanceMode 0` or `php yii settings/delete base maintenanceMode`

**Comment by luke-** [comment]
@yurabakhtin Ok, if it works that easy via the settings, then we don't need an extra action or command.

**Comment by yurabakhtin** [comment]
@luke- 

> Ok, if it works that easy via the settings, then we don't need an extra action or command.

Ok, then these specific commands should be documented somewhere, probably here https://docs.humhub.org/docs/admin/console#settings and add a link/button to this page from warning panel.

> When active, there is a sidebar snippet on the dashboard with a red border (similar to Incomplete Setup warning), indicating that Maintenance Mode is Active and only administrators have access.

Commit https://github.com/humhub/humhub/pull/4773/commits/cced590a55cced9bba38d1c1f3fdc00a00bac64a:
<img width="952" alt="maintenance_mode_panel" src="https://user-images.githubusercontent.com/6995524/104693515-d5a41a80-571a-11eb-9e2e-47a91153452a.png">

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub/pull/4773/commits/4a1d7018ee5cfbc7523b3240115a78e8cda6b200:

1) Non-admin users cannot log in when maintenance mode is enabled. Also register new users is disabled as well:

<img width="893" alt="login_restricted" src="https://user-images.githubusercontent.com/6995524/104751630-b4691b80-5766-11eb-8a1a-c4185d31a89e.png">

2) Confirmation on change maintenance mode:
<img width="879" alt="enable_maintenance_mode" src="https://user-images.githubusercontent.com/6995524/104751901-0ad65a00-5767-11eb-9116-5c1d6e06e2e2.png">
<img width="870" alt="disable_maintenance_mode" src="https://user-images.githubusercontent.com/6995524/104751917-0dd14a80-5767-11eb-9908-256874786090.png">

If this is enough then PR can be merged.

**Comment by luke-** [comment]
Please see my PR review, but apart from that it looks good!

**Comment by buddh4** [comment]
can be closed @luke- ?
