### ISSUE TITLE
Search for members in Space does not work with white space

### ISSUE THREAD

**Issue by Pooya-Oladazimi** [humhub/humhub#3347]
### What steps will reproduce the problem?
Searching for members in space and also searching for users in Administration does not work with white space, 

### What is the expected result?
for instance for query "pooya oladazimi" I suppose to get the user 

### What do you get instead?
But I got nothing

![space1](https://user-images.githubusercontent.com/16546640/47283444-ba054480-d5e3-11e8-8948-6a14fdc045a9.PNG)

### Additional info
If I search with query "pooya", I will get the user 

![space2](https://user-images.githubusercontent.com/16546640/47283466-d2755f00-d5e3-11e8-94eb-a0fe434bb049.PNG)

As I checked in community, the bug still exists in 1.3.6 version

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.2
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
I can confirm this in 1.3.6 as well.
