### ISSUE TITLE
Enhancement: Blank text/code module widget

### ISSUE THREAD

**Issue by devcline** [humhub/humhub#3348]
Can we have a widget that inserts a html, iframe or text to the right panel on default page?
I know its simple, but can it be integrated to the default modules? 

_or maybe instead of module it can be costume right space.._

thanks

**Comment by Felli** [comment]
At the moment I'm working on something similar to this request, the module is called [Codebox](https://github.com/GreenMeteor/humhub-codebox-module), at the moment it's not ready even if it does work I wouldn't recommend using it in production sites. The main issue with this module is that it permanently saves the code in ActiveRecord without being implemented in this way, it's rather strange to be honest and quite interesting.

**Comment by buddh4** [comment]
How about the [Custom Pages](https://github.com/humhub/humhub-modules-custom-pages) module?

**Comment by buddh4** [comment]
Sounds nice, but you can use php based snippets in the custom_pages module so you can simply include html. Also iframe based snippets are also available. I'll close this for now.

**Comment by devcline** [comment]
i agree with @Felli now i can see that i cant implement a sidebars with this
but i needed a time to understate how it works

How can i use a (php) variables in templates? For example to show the username or a country?

Also i saw this is in _system_headline_container_

```
{% if background.empty %}
    {% set bg = assets['bgImage2.jpg']  %}
{% else %}
    {% set bg =  background %}
{% endif %}

<div style="height:218px;overflow:hidden;color:#fff;background-image: url('{{ bg }}');background-position:50% 50%;text-align:center;">
	<div style="padding-top:40px;">
		<h1 style="color:#fff;font-size:36px;margin:20px 0 10px;">{{ heading }}</h1>
		<hr style="max-width:100px;border-width:3px;">
		 <span>{{ subheading }}</span>
  	 </div>
</div>

```

but didnt found any docs how to use such a variables ? Where to dig? thanks you very much

**Comment by buddh4** [comment]
You can activate php based custom pages in the module configuration and maintain your php views in the file system. Then you can use e.g. `Yii::$app->user->identity` to access the user etc. Of course you'll have to learn to know the basics of Yii framework.

**Comment by devcline** [comment]
that is so perfect, thank you !

**Comment by buddh4** [comment]
You should not add own classes or views or change existing classes/view in the HumHub core, since they probably will be overwritten in updates. Either overwrite views in your theme or extend the core through custom modules.

For complex cases you'll need to implement your own module, you can use the [Devtools](https://github.com/humhub/humhub-modules-devtools) module in order to create a module skeleton.
Also check the docs:

- [Module Developer Guide](http://docs.humhub.org/dev-modules.html)
- [Change core behavior](http://docs.humhub.org/dev-module-change-behavior.html#extend-menus)
