### ISSUE TITLE
Disk went full... humhub is broken

### ISSUE THREAD

**Issue by AlphabetoPT** [humhub/humhub#3353]
### What steps will reproduce the problem?
Yesterday i was doing backups from other software that is runing on my server and for a moment my disk went full... 
I didn't noticed for a while, after i did, i emptied the unnecessary files from the other software however humhub never recovered. 

During the diskfull state, mysql was stopped... then i fixed the space issue, rebooted server, mysql is ok, but the errors are still here. Cron job cron/run and cron/hourly simply give the error that we see below.

### Additional info

I have no idea how to react to this, i think i broke my entire website that i've been working for months just because my disk was full for 2 hours. 
Please help

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.2
| PHP version      | 7
| Operating system | ubtuntu server 16.

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

ERROR LOG IS: 
https://pastebin.com/sVUvwDsn

**Comment by fwhcat** [comment]
This error seems to be related to ZendSearch "Lucene" and is about reading empty files.

It seems one solution would be to clear the cache of that Lucene search module, but in your error log file, we don't see the path of the files that are read `/var/www/html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/File/AbstractFile.php(79): yii\base\ErrorHandler->handleError(8, 'Uninitialized s...', '/var/www/html/p...', 79, Array) #1 `

**Comment by AlphabetoPT** [comment]
@fwhcat in your opinion which files should i override from a previous backup?

**Comment by AlphabetoPT** [comment]
@fwhcat you are absolutely fantastic. Sometimes its right in front of us!
Thanks a lot.

I override the entire runtime folder and truncated cache/hu folder.

Thanks

**Comment by fwhcat** [comment]
@AlphabetoPT thanks, I just discovered this project and starred it then went to the first issue and it was yours. Glad I could help ;)
