### ISSUE TITLE
Problem with cron jobs configuration - cPanel

### ISSUE THREAD

**Issue by huesocik** [humhub/humhub#3354]
### What steps will reproduce the problem?
My notifications doesn't work. I have problem with configuration cron jobs, in humhub i have message: 
> Warning incomplete setup! The cron job for the regular tasks (cron) does not seem to work properly.

I tried different configurations, but I still have a problem. I'm using cPanel, in humhub I have debug mode disabled.

`*****/usr/local/bin/php /home/huesocik/public_html/humhub/protected/yii cron/run >/dev/null 2>&1 
*****/usr/local/bin/php /home/huesocik/public_html/humhub/protected/yii queue/run >/dev/null 2>&1`

### What is the expected result?
Working notifications.

### What do you get instead?
Problem with notifications. 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.7
| PHP version      |  7.2.8
| Operating system |

Logging:
`$_GET = [ 'r' => 'admin/information/background-jobs' '_pjax' => '#layout-content' '_' => '1540804381233' ] $_SERVER = [ 'PATH' => '/sbin:/usr/sbin:/bin:/usr/bin' 'PWD' => '/home/php-fastcgi/huesocik' 'SHLVL' => '0' 'ORIG_SCRIPT_NAME' => '/php-fcgi/php-fcgi-7.2.default' 'ORIG_PATH_TRANSLATED' => '/home/huesocik/public_html/humhub/index.php' 'ORIG_PATH_INFO' => '/index.php' 'ORIG_SCRIPT_FILENAME' => '/home/php-fastcgi/huesocik/php-fcgi-7.2.default' 'HTTP_CONNECTION' => 'close' 'SCRIPT_NAME' => '/index.php' 'REQUEST_URI' => '/index.php?r=admin%2Finformation%2Fbackground-jobs&_pjax=%23layout-content&_=1540804381233' 'QUERY_STRING' => 'r=admin%2Finformation%2Fbackground-jobs&_pjax=%23layout-content&_=1540804381233' 'REQUEST_METHOD' => 'GET' 'SERVER_PROTOCOL' => 'HTTP/2.0' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'REDIRECT_QUERY_STRING' => 'r=admin%2Finformation%2Fbackground-jobs&_pjax=%23layout-content&_=1540804381233' 'REDIRECT_URL' => '/index.php' 'REMOTE_PORT' => '59452' 'SCRIPT_FILENAME' => '/home/huesocik/public_html/humhub/index.php' 'SERVER_ADMIN' => 'webmaster@humhub.huesocik.webd.pro' 'CONTEXT_DOCUMENT_ROOT' => '/home/php-fastcgi/huesocik/' 'CONTEXT_PREFIX' => '/php-fcgi/' 'REQUEST_SCHEME' => 'https' 'DOCUMENT_ROOT' => '/home/huesocik/public_html/humhub' 'REMOTE_ADDR' => '217.99.104.237' 'SERVER_PORT' => '443' 'SERVER_ADDR' => '192.168.101.177' 'SERVER_NAME' => 'humhub.huesocik.webd.pl' 'SERVER_SOFTWARE' => 'Apache' 'SERVER_SIGNATURE' => '' 'CONTENT_LENGTH' => '0' 'HTTP_HOST' => 'humhub.huesocik.webd.pl' 'HTTP_COOKIE' => 'PHPSESSID=1f2cfe3416c98862544c442544cff471; _identity=de0c90fed5a750b5be3b70b3e6844c29ab7b583b78000b385115f7f8adf56eefa%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%220b888d42-9ffa-4659-8e6e-a5f5f7e72617%22%2C2592000%5D%22%3B%7D; _csrf=3f9b237ab53d10a8ed3c33c3582f82ebd5472624affc405f910289b551bdc53ba%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%227SwKq4T3OcDatNQp9BBFM3921E86GwDm%22%3B%7D; pm_getting-started-panel=expanded; pm_panel-activities=expanded; pm_space-members-panel=expanded' 'HTTP_ACCEPT_LANGUAGE' => 'pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_REFERER' => 'https://humhub.huesocik.webd.pl/index.php?r=admin%2Finformation' 'HTTP_X_PJAX_CONTAINER' => '#layout-content' 'HTTP_X_PJAX' => 'true' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_ACCEPT' => 'text/html, */*; q=0.01' 'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36' 'HTTP_X_CSRF_TOKEN' => '4hVUplbepMU8PlWOBMQ4Abz_BJtxsweG9dYsMeSkS9LVRiPtJ-rw9nNdEe9wimlxhb1G3TyAPrTEkxQHo9MPvw==' 'H2_STREAM_TAG' => '220-13' 'H2_STREAM_ID' => '13' 'H2_PUSHED_ON' => '' 'H2_PUSHED' => '' 'H2_PUSH' => 'on' 'H2PUSH' => 'on' 'HTTP2' => 'on' 'SSL_TLS_SNI' => 'humhub.huesocik.webd.pl' 'HTTPS' => 'on' 'QS_ConnectionId' => '15408050933829372110837' 'QS_AllConn' => '54' 'QS_SrvConn' => '54' 'UNIQUE_ID' => 'W9bR6T-lXlHd@A3zMhzABAAAAA0' 'REDIRECT_STATUS' => '200' 'REDIRECT_HANDLER' => 'php7.2-fastcgi' 'REDIRECT_H2_STREAM_TAG' => '220-13' 'REDIRECT_H2_STREAM_ID' => '13' 'REDIRECT_H2_PUSHED_ON' => '' 'REDIRECT_H2_PUSHED' => '' 'REDIRECT_H2_PUSH' => 'on' 'REDIRECT_H2PUSH' => 'on' 'REDIRECT_HTTP2' => 'on' 'REDIRECT_SSL_TLS_SNI' => 'humhub.huesocik.webd.pl' 'REDIRECT_HTTPS' => 'on' 'REDIRECT_QS_ConnectionId' => '15408050933829372110837' 'REDIRECT_QS_AllConn' => '54' 'REDIRECT_QS_SrvConn' => '54' 'REDIRECT_UNIQUE_ID' => 'W9bR6T-lXlHd@A3zMhzABAAAAA0' 'FCGI_ROLE' => 'RESPONDER' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1540805097.5834 'REQUEST_TIME' => 1540805097 ]`

**Comment by huesocik** [comment]
Prerequisites:
 PHP - Version - 7.2.8
 PHP - GD Extension
 PHP - GD Extension - JPEG Support
 PHP - GD Extension - PNG Support
 PHP - INTL Extension
 -PHP - INTL Extension - ICU Version (4.2.1) (Hint: ICU Data 4.8.1 or higher is required)
 -PHP - INTL Extension - ICU Data Version (0) (Hint: ICU Data 4.8.1 or higher is required)
 PHP - EXIF Extension
 PHP - FileInfo Extension
 PHP - Multibyte String Functions
 PHP - iconv Extension
 PHP - cURL Extension
 PHP - ZIP Extension
 -LDAP Support (Hint: Optional - Install PHP LDAP Extension and Zend LDAP Composer Package)
 -PHP - APC(u) Support (Hint: Optional - Install APCu Extension for APC Caching)
 PHP - SQLite3 Support
 PHP - PDO MySQL Extension
 Permissions - Runtime
 Permissions - Assets
 Permissions - Uploads
 Permissions - Module Directory
 Permissions - Dynamic Config

**Comment by buddh4** [comment]
Perhaps ask the [Community](https://community.humhub.com) for help, there are already many questions regarding cron jobs.

**Comment by huesocik** [comment]
I solved this. It was problem without connection with database. I changed localhost for ip connection.
