### ISSUE TITLE
Date time formating issues - calendar module

### ISSUE THREAD

**Issue by 22010** [humhub/humhub#3355]
### What steps will reproduce the problem?
The server locale is el_GR.UTF-8 and Greek is chosen as language in Account Settings > Settings > Language.
Create a new calendar event in a space.
### What is the expected result?
The date and time of the event to be registered in the calendar
### What do you get instead?
The date gets transformed to January 1970 and we get an error 'End time must be after start time'.
### Additional info
If the event has a start and end time there is a 'Start time format is invalid' error.
Tried with other languages in Account > Settings and it seems to be working fine

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.6
| PHP version      | 7.0.32-0ubuntu0.16.04.1
| Operating system | ubuntu server 16.04.5

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by 22010** [comment]
It may have something to do with the localization (greek for us)

**Comment by luke-** [comment]
Can you please open an issue in the calendar module for that?
