### ISSUE TITLE
Issues with the test instance (Confirmation Email not sending)

### ISSUE THREAD

**Issue by ShalokShalom** [humhub/humhub#3356]
### What steps will reproduce the problem?

Click on "Try online" on the homepage. Then enter your data. Check your email.

### What is the expected result?

Email comes. 

### What do you get instead?

Nothing. On 2 email accounts. Which are otherwise working

**Comment by Felli** [comment]
Could you provide what email provider you're using? Also, make sure that you check your spam folder. I personally can't reproduce this as I got an email to [finish setup](https://crew.humhub.com/dashboard).

**Comment by ShalokShalom** [comment]
https://protonmail.com

**Comment by buddh4** [comment]
Please contact info@humhub.com regarding hosting issues.

**Comment by ShalokShalom** [comment]
Forget me
