### ISSUE TITLE
Facebook login broken at the community

### ISSUE THREAD

**Issue by ShalokShalom** [humhub/humhub#3357]
### What steps will reproduce the problem?

Login via Email at the Community instance. 

### What is the expected result?

Login. 

### What do you get instead?

![screenshot_20181101_155939](https://user-images.githubusercontent.com/6344099/47859883-8dc1a300-ddef-11e8-9ede-6e3e1cd64f98.png)

### Additional info

This is the case since about a year or so.

**Comment by Felli** [comment]
I've already reported this from the team space, although it's been while since it was reported, thanks for the reminder. :wink:

**Comment by buddh4** [comment]
Isn't this rather a facebook configuration issue?

**Comment by Felli** [comment]
@buddh4 this would be the case. :+1:

**Comment by ShalokShalom** [comment]
Why is this closed? This is also the kind of support that is going on for paid members? 
No response for months/years and then just closing the case?
Wow.

**Comment by Felli** [comment]
This was closed because the Facebook login was taken down until we can fix the Facebook side of things as well as on the HumHub side of things as stated in both https://github.com/humhub/humhub/issues/3357#issuecomment-435142057 & https://github.com/humhub/humhub/issues/3357#issuecomment-436589217.

**Comment by ShalokShalom** [comment]
thanks a lot

**Comment by ShalokShalom** [comment]
It is still here: https://community.humhub.com/user/auth/login

**Comment by Felli** [comment]
The facebook login doesn't show for me on the community site. :thinking:
![screenshot_1](https://user-images.githubusercontent.com/2011633/53963674-c0401d00-40bb-11e9-822e-b5dffda61585.png)

**Comment by petrk94** [comment]
@Felli  I agree with @ShalokShalom 
I even see the Facebook login on the community site, see screenshot

![humhub](https://user-images.githubusercontent.com/19719052/54033764-79cee900-41b5-11e9-8d9a-4916c8757b58.PNG)

**Comment by ShalokShalom** [comment]
I see it as petrk

**Comment by Felli** [comment]
I still don't see the Facebook login button for the community site. :frowning_face:

**Comment by petrk94** [comment]
I use Windows 10 and Chrome, independent by the OS, if the function is removed from code site or disabled, after a refresh and disable of cache should solve the problem, but its still there :/

**Comment by buddh4** [comment]
Should work now @community.

**Comment by ShalokShalom** [comment]
![Screenshot_20190318_113545](https://user-images.githubusercontent.com/6344099/54524341-075ac780-4972-11e9-84f0-713a3d28a7ea.png)

**Comment by buddh4** [comment]
Could not reproduce this, please add some information when exactly this happed in your test, directly after clicking the facbook button?

**Comment by ShalokShalom** [comment]
Just by loading the community login, always :)
