### ISSUE TITLE
Authorise users to post on there own wall 

### ISSUE THREAD

**Issue by hazmaniameur** [humhub/humhub#3358]
Hi, can you help me, i'm using humhub 1.1.2, and i would like to enable the posting content profil

Actually i don't have the input area

when i try a VAR_DUMP(\humhub\modules\post\widgets\Form::widget(['contentContainer' => $user]) on the /humhub/module/user/view/home.php i got an empty var 

| Q                | A
| ---------------- | ---
| HumHub version   | 1.1.2
| PHP version      |  7.0
| Operating system | Ubuntu 16

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by luke-** [comment]
Please post questions in our community
