### ISSUE TITLE
Weekly email summaries are not sent on Humhub 1.2

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#3359]
### What steps will reproduce the problem?

Choose weekly email summaries in the account settings :
![image](https://user-images.githubusercontent.com/23310825/47950508-9c28cf80-df53-11e8-9d3b-ba9d3223a63d.png)

### What is the expected result?

Receive an email each week.

### What do you get instead?

No email.

### Additional info

Cronjobs for hourly and daily summaries are correctly installed and work fine (emails are received by members when they select this frequency) :
```
30 * * * * /path/to/humhub/protected/yii cron/hourly >/dev/null 2>&1
00 18 * * * /path/to/humhub/protected/yii cron/daily >/dev/null 2>&1
```
Discussion started on [Humhub Communty platform here](https://community.humhub.com/content/perma?id=171118).

Thanks,
Marc.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2
| PHP version      | 7.1
| Operating system | Ubuntu 16.04

**Comment by luke-** [comment]
The weekly e-mail summary is sent by the daily cronjob.

By default, the sending always takes place with execution on Sundays.
This behavior can be adjusted via the configuration file.

**Comment by funkycram** [comment]
Thanks for your answer.
Unfortunately, no summary emails are sent on Sundays whereas daily emails are sent (even Sunday, at 6pm). I'm sure of that as emails are sent threw a transactional mailing service, so I have all the logs.
Maybe a problem of configuration ?

Is the configuration file `protected/config/common.php` ? What should be written ? I could not find it in the documentation.

Thanks !

**Comment by luke-** [comment]
This is really strange, so users with a weekly summary option never receive an email?

You can change the day using following configuration (in file `protected/config/common.php`)

```php
<?php

/**
 * This file provides to overwrite the default HumHub / Yii configuration by your local common (Console and Web) environments
 * @see http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html
 * @see http://docs.humhub.org/admin-installation-configuration.html
 * @see http://docs.humhub.org/dev-environment.html
 */

return [
    'modules' => [
        'activity' => [
            'weeklySummaryDay' => 1, // 0 (for Sunday) through 6 (for Saturday)
        ]
    ]
];
```

**Comment by funkycram** [comment]
Great !!
Adding this configuration made it work, thanks a lot !

**Comment by luke-** [comment]
Are you sure that without this configuration change on Sunday no summaries will be sent?
I can't find any problem in that part.

**Comment by funkycram** [comment]
Yes, absolutely sure...

**Comment by luke-** [comment]
Indeed there is a problem in the code.
Please use 1=Monday, 7=Sunday as workaround until 1.3.8 release.
