### ISSUE TITLE
cronjobs are not running

### ISSUE THREAD

**Issue by Kachelkaiser** [humhub/humhub#3361]
### What steps will reproduce the problem?
Clearing manually the queue
Starting the jobs manually
### What is the expected result?
Clearing the queue automatically
### What do you get instead?
waiting items in the queue
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.7
| PHP version      | 7.1
| Operating system |?

Unfortunately the cron jobs are not running properly.

I use a CGI bridge at my web-hoster all-inkl.com

I created two scripts. Both run all 2 minutes, but I tried different scheduling as well.

**Script 1:** 

```
<?php

 exec("/usr/bin/php71 -d memory_limit=1024M /www/htdocs/w00xxxx/social/protected/yii cron/run >/dev/null 2>&1", $out, $result);
 echo "Returncode: " .$result ."<br>";
 echo "Ausgabe des Scripts: " ."<br>";
 echo "<pre>"; print_r($out);

 ?>
```

**Script2:**

```
<?php

 exec("/usr/bin/php71 -d memory_limit=1024M /www/htdocs/w00ff1cf/social/protected/yii queue/run --isolate=0 >/dev/null 2>&1", $out, $result);
 echo "Returncode: " .$result ."<br>";
 echo "Ausgabe des Scripts: " ."<br>";
 echo "<pre>"; print_r($out);

 ?>
```

As you can see I increased the memory, because I got failures in the logs regarding to too less memory.

Currently the jobs are running but the queue isn't cleared automatically. No failures in the logs.
I think the main issue is the second job.

When I run the first job manually, all is good
But I can't run the second job manually, because it times out.

The processes on the server were deleted many times by my webhoster all-inkl.com.

Does anybody have an idea, what I can do addtionally?

Edit: Now the timer switched, the hourly tasks were done,but now the queue increases. Maybe here ist he problem. Now I can't run the queue-job not manually. it times out. "cron" cron-job works manually.

![grafik](https://user-images.githubusercontent.com/38027013/48229671-0ce34800-e3a9-11e8-85fe-f0c4639eff1e.png)

**Comment by Felli** [comment]
@buddh4 would it be possible that the Cron Jobs look for an exact PHP path for `/usr/bin/php` and not PHP version path?

**Comment by Felli** [comment]
Try using something like the following;

```
/opt/alt/php71/usr/bin/php -q  memory_limit=1024M /www/htdocs/w00ff1cf/social/protected/yii queue/run --isolate=0 >/dev/null 2>&1
```

**Comment by Kachelkaiser** [comment]
Thanks for your comments, but I now found the cause of my issue. The module "external calneder" faced the problems.

When activated with hourly sync, the the corn-Jobs timed out every hour. I switched this to daily sync, then I faced the same problem at the same hour every day. 

As soon I deactivated the module, everything is fine.
