### ISSUE TITLE
Could not automatically create LDAP users

### ISSUE THREAD

**Issue by sigristlucas** [humhub/humhub#3362]
### Could not automatically create LDAP users
I'm having trouble importing users from active directory, can anybody help me?

**Stats: OK! (545 Users)**

### Config

- [ ] auth.ldap.hostname	10.172.10.1
- [ ] auth.ldap.port	389
- [ ] auth.ldap.encryption	
- [ ] auth.ldap.username	ldap
- [ ] auth.ldap.password	pass
- [ ] auth.ldap.baseDn	DC=sls,DC=net
- [ ] auth.ldap.loginFilter	(sAMAccountName=%s)
- [ ] auth.ldap.userFilter	(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))
- [ ] auth.ldap.usernameAttribute	sAMAccountName
- [ ] auth.ldap.emailAttribute	mail
- [ ] auth.ldap.idAttribute	

### Log  ... i dont understand the problem

> Fri, 09 Nov 2018 16:22:21 -0200  application Could not automatically create LDAP user - check required attributes! (Array ( [accountexpires] => 9223372036854775807 [badpasswordtime] => 131786617912030807 [badpwdcount] => 0 [cn] => pabx1 [codepage] => 0 [countrycode] => 0 [displayname] => PABX - Hospital São Lucas [distinguishedname] => CN=pabx1,OU=Users,OU=HSL,OU=ORG,DC=sls,DC=net [dn] => CN=pabx1,OU=Users,OU=HSL,OU=ORG,DC=sls,DC=net [dscorepropagationdata] => 16010101000000.0Z [givenname] => PABX- Hosp. São Lucas [instancetype] => 4 [lastlogoff] => 0 [lastlogon] => 131860099693657537 [lastlogontimestamp] => 131860099693657537 [logoncount] => 235 [memberof] => Array ( [0] => CN=PABX,OU=Groups,OU=HSL,OU=ORG,DC=sls,DC=net ) [name] => pabx1 [objectcategory] => CN=Person,CN=Schema,CN=Configuration,DC=sls,DC=com,DC=net [objectclass] => Array ( [0] => top [1] => person [2] => organizationalPerson [3] => user ) [objectguid] => 3ac1dc58-cbe1-4049-a757-561521564572 [objectsid] => 

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.8
| PHP version      | 7.0.30
| Operating system | deb9u1

**Comment by luke-** [comment]
Per default a first name, last name and e-mail attribute is required.

If this is not present in the LDAP record this error is thrown.
