### ISSUE TITLE
Emoticon parsing in Latest Activities

### ISSUE THREAD

**Issue by petecooper** [humhub/humhub#3365]
### What steps will reproduce the problem?

* spin up an online demo instance, install default content
* note the default comment from Sarah Schuster

### What is the expected result?

* comment and entry under Latest Activities should parse emoticon short codes.

### What do you get instead?

* comment parses short code (😩), Latest Activities entry does not (shows `;Weary;`)

![screen shot 2018-11-14 at 19 49 32](https://user-images.githubusercontent.com/226578/48508664-0a6c6c80-e847-11e8-95a3-92ee86173b05.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.7
| PHP version      | Hosted demo 5.6.38-0+deb8u1
| Operating system | Hosted demo 

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Would also seem to happen within emails. :thinking:
