### ISSUE TITLE
Problems with Pictures in mobile view

### ISSUE THREAD

**Issue by Drakemaster** [humhub/humhub#3366]
### What steps will reproduce the problem?
max width/height set to 500px

### What is the expected result?
Smartphone fitted Picture Size

### What do you get instead?
Pictures in posts are wider than the screen
Pictures in comments have a wrong ratio. Fix height an various width.

### Additional info
| HumHub version   | 1.3.7
| PHP version  7.2    | 
| Operating system |

**Comment by luke-** [comment]
What do you mean with max height to 500px?

**Comment by Felli** [comment]
I'm not sure on this one @luke- I don't see this issue on any viewpoints, both width & height should be set to `100%` so that responsive is used, might be a device compatibility issue? :thinking:

**Comment by luke-** [comment]
@Felli You're right, I'm closing the issue until we have more information.

**Comment by Drakemaster** [comment]
sorry, now I have further information:
If you upload a picture with "upload files", a static height is set:
<img class="animated fadeIn" src="https://xxxx" alt="senku wi.png" height="338">
with that the picture is too large for mobile view.

If you upload a picture with the upload function of the editor, everything is fine. There you have a dynamic size.
.wall-entry .content img {
    max-width: 100%;

**Comment by Drakemaster** [comment]
It happens with smartphones and I can also reproduce it with windows (Chrome, Firefox) if I use a small browser window.

Horizontal scrolling images on a mobile device was disabled but it makes no difference if I enable it.
