### ISSUE TITLE
All members by space receive same notifications regularly.

### ISSUE THREAD

**Issue by dmitrydrynov** [humhub/humhub#3386]
Hi everyone,
I have a problem with notifications in one of spaces
When I create a new post members receive notifications about it every 6 minutes.
It’s only in one space. In other spaces all right.

Can you help me?

HumHub 1.3.8
Ubuntu 16.04.5 LTS
PHP 7.2

![screenshot_41](https://user-images.githubusercontent.com/4089575/50155771-03b99500-02de-11e9-8995-375e009a77fc.jpg)

**Comment by dmitrydrynov** [comment]
Not yet solved the problem

My users still receive notifications multiple times
![image](https://user-images.githubusercontent.com/4089575/50373761-96b34180-05f4-11e9-93ca-68b00259a060.png)

**Comment by luke-** [comment]
Does this problem only affects one space? 
Any update on this in the meantime?
