### ISSUE TITLE
Apostrophe becomes weird symbols

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3389]
See this screenshot about a Notification email:

![image](https://user-images.githubusercontent.com/12234510/50229004-94a97280-03a9-11e9-9cea-1ca6ea05645e.png)

Should read **Season's greetings!**

**Comment by acs-ferreira** [comment]
Idem with "**é**"

![image](https://user-images.githubusercontent.com/12234510/50229860-9116eb00-03ab-11e9-86e6-9a2839f6a2d5.png)

Original post on the stream:

![image](https://user-images.githubusercontent.com/12234510/50229904-ae4bb980-03ab-11e9-8887-83b514aa2133.png)

notice also the missing space between "les" and "procéd"...

**Comment by buddh4** [comment]
Please use the issue template so we know your humhub version and stepts to reproduce, add some infos since e.g. when does this happen where does this happen etc. Also check the database encoding and how the data is represented within your database.
