### ISSUE TITLE
CFiles: Activities for files without rights

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3394]
### What steps will reproduce the problem?

A Space administrator posts a new file on a folder. This space is private (access to members of the space only). That activity is visible by a user (Admin) on the Activities widget. When he clicks on that activity, it trows a `500` error.

### What is the expected result?

Activity is only visible by users of that space with read rights and on click, the folder is opened.

### What do you get instead?

```
yii\web\HttpException: Could not find folder with id: 206 in /protected/modules/cfiles/controllers/BaseController.php:94
Stack trace:
#0 /protected/modules/cfiles/controllers/BrowseController.php(24): humhub\modules\cfiles\controllers\BaseController->getCurrentFolder()
#1 [internal function]: humhub\modules\cfiles\controllers\BrowseController->actionIndex()
#2 /protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('index', Array)
#5 /protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('cfiles/browse/i...', Array)
#6 /protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#7 /index.php(24): yii\base\Application->run()
#8 {main} 
```
But if a user of that space clicks on that activity, folder `206` and file are correctly accessed. 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | master (1.3.9-pre)
| PHP version      | 7.2
| Operating system | Ubuntu

**Comment by luke-** [comment]
Is this related to the cfiles module?
