### ISSUE TITLE
How can I change index.php file?

### ISSUE THREAD

**Issue by AleksaDeveloper** [humhub/humhub#3395]
Hello everyone, I would like to make changes to index.php file and add some things on my main page but when I try to make changes to index.php file I keep getting errors. So are we allowed to change the index.php file and how can I access and change it. In console I saw that there is actually a HTML code but I couldn't find it anywhere.

Thanks, have a great day/night!

**Comment by Felli** [comment]
Please use the [community site](https://community.humhub.com/dashboard) for such questions.
