### ISSUE TITLE
LDAP login working only with full DN of user

### ISSUE THREAD

**Issue by Aneadiel** [humhub/humhub#3396]
### What are the steps for reproducing this issue
Fresh install of 1.3.8, bind to LDAP -> OK 198 users, usernames and e-mails synced
Try to login using LDAP credentials -> wrong username/password

### What is the expected result?
Being able to login using credentials in LDAP (uid/mail)
### What do you get instead?
I am able to login using full DN of user but not using username atribute (uid/mail)
### Additional info
login filter "(uid=%s)"
username atribute "uid"
in DB user table is populated with correct values and auth_type ldap
user_password table is empty as expected

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.8
| PHP version      |  7.2.9
| Operating system | RHEL 7

logging is devoid of any errors

**Comment by Aneadiel** [comment]
@luke- OpenLDAP

**Comment by luke-** [comment]
Thanks, can you please also provide a screenshot of your HumHub settings?

**Comment by Aneadiel** [comment]
![screenshot from 2019-01-29 15-00-06](https://user-images.githubusercontent.com/16285832/51913445-c9f8a580-23d6-11e9-8abe-90c4debac3be.png)
![screenshot from 2019-01-29 15-00-03](https://user-images.githubusercontent.com/16285832/51913451-ce24c300-23d6-11e9-8bc0-82bc101506d2.png)

**Comment by tinkat69** [comment]
Maybe of use to someone:
We had the same issue (login working only with full DN of user) which for us using OpenLDAP with HH was solved by:

- ensuring users in the LDAP directory had a 'User Name' attribute (for HH username login)
- using 'Email' (not 'mail') as the E-Mail Address Attribute setting in HH (for email address login)
- having the ID Attribute setting in HH as 'uidNumber'

**Comment by luke-** [comment]
Please reopen if the problem still exists.
