### ISSUE TITLE
SQLSTATE[HY000] [1044] Access denied

### ISSUE THREAD

**Issue by xilmen** [humhub/humhub#3397]
Hello, i upgrade my site to 1.3.8.

I have problem if i use command :
`php yii space/assign-all-members <space id>`

Return :
`Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'humhub''`

i use **yii integrity/run** for check my upgade:

*** Performing database integrity checks

Validating: Polls Module - Answers (14 entries)
Validating: Polls Module - Answers User (25 entries)
Validating: Activity Module (2033 entries)
Validating: Comment Module (209 entries)
Validating: Content Objects (2334 entries)
Validating: File Module (9024 entries)
Validating: Like (139 entries)
Validating: Notification Module (185 entries)
Validating: Post  Module - Posts (297 entries)
Validating: Space Module - Spaces (59 entries)
Validating: Space Module - Memberships (1219 entries)
Validating: User Module - ContentContainer (21 entries)
Validating: User Module - Users (21 entries)
Validating: User Module - Password (37 entries)
Validating: User Module - Profile (21 entries)
Validating: User Module - Mentioning (39 entries)
Validating: User Module - Follow (649 entries)
Validating: User Module - Content container (80 entries)

*** All integrity checks done

| HumHub version   | 1.3.8
| PHP version      |  5.6.38
| Operating system | CentOS Linux release 7.6.1810 (Core)

Thanks in advance

**Comment by luke-** [comment]
Please create such issues in our community at: https://community.humhub.com
