### ISSUE TITLE
hello, i am angular,node and react developer and i want work this project please contact my mail aashishtyagig@gmail.com with your requirement

### ISSUE THREAD

**Issue by aashishtyagig** [humhub/humhub#3399]
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by buddh4** [comment]
Use the contact form on our [website](https://www.humhub.org), but note HumHub doesn't use react/angular/node.
