### ISSUE TITLE
Change default search engine

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3403]
[ZendSearch](https://github.com/zendframework/ZendSearch) is not compatible with PHP 7.3 due to a dependency to `zendframework/zend-stdlib: 2.*`.

See https://github.com/zendframework/zend-stdlib/pull/91 which is included in `zendframework/zend-stdlib: 3.2.1`

**Comment by acs-ferreira** [comment]
Alternatives:

https://github.com/teamtnt/tntsearch
https://github.com/pucene/pucene

**Comment by geirfp** [comment]
Could this also be an alternative (also referenced in issue #2499)?
https://github.com/yiisoft/yii2-elasticsearch

**Comment by buddh4** [comment]
As default search we'd prefer a build-in PHP based search index, which does not need to be installed seperately or requires any external services, this should be sufficient for smaller installations. For bigger installations there currently only is the [https://docs.humhub.org/docs/professional/solr](Solr) search available in the prefessional edition.
