### ISSUE TITLE
Richtext `Heading` text not translatable.

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3404]

**Comment by V-Kolodij** [comment]
This is not the correct solution to the problem, but it works for me:
I add context.translate() function to titles or labels, like "title: context.translate("Undo last change")" or "label: context.translate("Heading")" and for other text  in npm-asset/humhub-prosemirror-richtext/dist/humhub-editor.js, added yii::t for text like "Heading" => Yii::t('ContentModule.richtexteditor', "Heading") and others in ui.richtext.prosemirror module, key 'text'  to widget(humhub/protected/humhub/widgets/CoreJsConfig.php (str.103)),
added translation in message (modules/content/messages).
