### ISSUE TITLE
Notifications url use domain from SERVER variable not from settings

### ISSUE THREAD

**Issue by italo1983** [humhub/humhub#3408]
Clicking on notifications redirect user to the domain picked from SERVER variables instead of domain configured in settings.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.8
| PHP version      | 7.2
| Operating system | Ubuntu

**Comment by luke-** [comment]
If available the SERVER variables will be used.

**Comment by luke-** [comment]
You can overwrite this variables in the configuration file (protected/config/common.php) if required.

**Comment by italo1983** [comment]
Forcing baseUrl does not work:
```
return [
'components' => [
        'request' => [
                'baseUrl'  => 'http://intranet.domain.it'
        ]
]
```

And server name return this error: 
yii\base\InvalidCallException: Setting read-only property: humhub\components\Request::serverName
return [
```
'components' => [
        'request' => [
                'baseUrl'  => 'http://intranet.domain.it',
                'serverName' => 'http://intranet.domain.it'
        ]
]   
```

**Comment by luke-** [comment]
If you're using a proxy server, you may need to mark it as trusted.

```
return [
    'components' => [
        'request' => [
            'trustedHosts' => ['any']
        ]

    ]
];
```

**Comment by patofet** [comment]
setting 'trustedHosts' to ['any'] doesn't work for me
