### ISSUE TITLE
User admin should be able to set/change user passwords

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#3414]

**Comment by yurabakhtin** [comment]
@luke- Please see where I added the admin password edit form. Password is updated only when the fields are filled both without errors, if they are empty then password will not be changed:
<img width="1148" alt="admin_edit_pass_form" src="https://user-images.githubusercontent.com/6995524/97894503-9f721400-1d43-11eb-9b38-264beea6a63d.png">

**Comment by luke-** [comment]
Looks fine, we'll integrate this in 1.8

**Comment by yurabakhtin** [comment]
@luke- I detected a bug related to this task:
<img width="1163" alt="bug" src="https://user-images.githubusercontent.com/6995524/98337917-67f0b980-201a-11eb-8c83-d0830704f182.png">

**Comment by yurabakhtin** [comment]
Fixed in commit: https://github.com/humhub/humhub/pull/4598/commits/d066113e499d15a43690834d7babc1a37b511d89

**Comment by luke-** [comment]
Awesome!
