### ISSUE TITLE
Humhub Problem with Cronjob 'queue/exec

### ISSUE THREAD

**Issue by buchmayr** [humhub/humhub#3436]
I get the following stacktrace in the log, when the cron job is executed. People dont get mails when they are invited to spaces.

On the background job tab all seems to be fine, nothing in queue anymore. PN mail notifications are working.

I am using newest Humhub Version 1.3.8. Problem also existed in 1.3.7.

> ERROR  Fri, 01 Feb 2019 12:25:02 +0100  queue Could not execute queued job! Message: The command "'/usr/local/pd-admin2/php-7.1.24/bin/php' '' 'queue/exec' '2697' '300' '1' '6732' '--color='" failed. Exit Code: 255(Unknown error) Working directory: /home/solareb3/www.solartown.eu/humhub/protected Output: ================ Status: 404 Not Found Content-type: text/html; charset=UTF-8 No input file specified. Error Output: ================ PHP Warning: Unknown: Filename cannot be empty in Unknown on line 0 Trace:#0 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(125): humhub\modules\queue\driver\MySQLCommand->handleMessage('2697', 'O:49:"humhub\\mo...', '300', 1) #1 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}('2697', 'O:49:"humhub\\mo...', '300', 1) #2 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func(Object(Closure), '2697', 'O:49:"humhub\\mo...', '300', 1) #3 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage('2697', 'O:49:"humhub\\mo...', '300', 1) #4 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure)) #5 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure)) #6 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure)) #7 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false) #8 [internal function]: yii\queue\db\Command->actionRun() #9 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #10 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #11 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('run', Array) #12 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array) #13 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array) #14 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array) #15 /home/solareb3/www.solartown.eu/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #16 /home/solareb3/www.solartown.eu/humhub/protected/yii(28): yii\base\Application->run() #17 {main}

**Comment by buddh4** [comment]
Add your cron configuration.

**Comment by acs-ferreira** [comment]
> **Status**: 404 Not Found **Content-type**: text/html; charset=UTF-8

The `Status` and `Content-type` and headers are only printed when PHP is running as `CGI`.
You must use PHP `CLI` version for Cronjobs.

See https://github.com/humhub/humhub/blob/master/protected/humhub/docs/guide/admin/installation-configuration.md#cronjobs-and-asynchronous-job-processing-v13

**Comment by buchmayr** [comment]
> > **Status**: 404 Not Found **Content-type**: text/html; charset=UTF-8
> 
> The `Status` and `Content-type` headers are only printed when PHP is running as `CGI`.
> You must use PHP `CLI` version for Cronjobs.
> 
> See https://github.com/humhub/humhub/blob/master/protected/humhub/docs/guide/admin/installation-configuration.md#cronjobs-and-asynchronous-job-processing-v13

thank you, this fixed it for me!
