### ISSUE TITLE
Richtext code block after list item not working

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3441]
Inserting a code block after a list does not work:

1. Add a list item to post
2. Press enter two times
3. Change text type to code
4. Add some text
5. Submit

**Expected result:**

Code block after list

**Actual result:**

The text of code block is embedded into the list item without the code block

**Additional Info:**

1. Add a list item to post
2. Press enter one time
2. Press backspace one time
3. Change text type to code
4. Add some text
5. Submit

Result:

Embedded code block within first list item under paragraph.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/3440
