### ISSUE TITLE
Print/Export Content and Streams

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3445]
We need a way of printing and exporting content and streams.

### Is your feature request related to a problem? Please describe.

No content export/print available.

### Describe the solution you'd like

**Concept:**

- Adding a `StreamOptionsMenu` to the Stream filter navigation.
- A Stream can support beeing printed by implementing a `getPrintUrl()` e.g. by interface. This will add a Print link to the `StreamOptionsMenu`.
- The print action will render a print layout of the stream filtered by active filters.
- Ideally add a date filter (from/to) to the stream filter
- Stream entries should be able to provide an own print views, otherwise the shortdescription is printed

**Question**

- Determine the count of printed items (either by user definition, or count the visible stream entries in view)
- Would be greate to have a generic stream print action, without the need to provide an own for custom streams.
- Printing of single content entries vs multi content prints.
- Print options e.g. (Full content print vs summary, Max Count,...

**Comment by funkycram** [comment]
Related to https://github.com/humhub-contrib/legal/issues/20 ?

**Comment by luke-** [comment]
@funkycram Yes, the REST API could be also used to export content.
