### ISSUE TITLE
Any possibility to implement LaTeX/MathJax for science community?

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#3448]
Is there any possibility to implement LaTeX/MathJax targeted for science communities?

**Comment by Felli** [comment]
@buddh4 I rather like the idea behind [chanzuckerberg/czi-prosemirror](https://github.com/chanzuckerberg/czi-prosemirror), maybe something to look into? I'm sure that we might be able to find something useful. :wink:

**Comment by jdpark7** [comment]
https://github.com/Pai-Chai-University/humhub/tree/master/humhub-1.2.3-katex-support/static/resources/js/katex

**Comment by karnakitab** [comment]
@jdpark7 Very nice. Please update it to support the latest humhub version. It would be great if the whole thing is implemented as a complete module.

**Comment by buddh4** [comment]
@jdpark7 seems to be a nice approach, perhaps we could implement this without overwriting the wallEntry views.

**Comment by buddh4** [comment]
Here a module prototype https://github.com/humhub-contrib/katex this currently requires HumHub 1.7 to run.

**Comment by jdpark7** [comment]
I updated the version. https://github.com/Pai-Chai-University/humhub/tree/master/humhub-1.7.0-katex-support
