### ISSUE TITLE
Soft deleted (by admin) user can still add content

### ISSUE THREAD

**Issue by xaro1** [humhub/humhub#3451]
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.8
| PHP version      | 7.2.14
| Operating system | Linux

**Comment by xaro1** [comment]
I think the session remain active on user device. user_id appear in user_http_session table even if row previously deleted.

**Comment by luke-** [comment]
Is already fixed in 1.3.9
