### ISSUE TITLE
Soft deleted users is also included by Auto follow module operations

### ISSUE THREAD

**Issue by xaro1** [humhub/humhub#3453]
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.8
| PHP version      |  7.2.14
| Operating system | Linux

**Comment by luke-** [comment]
Fixed in auto-follow module v1.0.5

**Comment by xaro1** [comment]
Ok thanks but how to remove already subscribed soft deleted users from other users (previously added by auto follow module) ?

**Comment by xaro1** [comment]
@luke- Ok thanks but how to remove already subscribed soft deleted users from other users (previously added by auto follow module) ?
