### ISSUE TITLE
Is not possible to login with username/email password 

### ISSUE THREAD

**Issue by gomonkey** [humhub/humhub#3462]
Hello,
is not possible to login with username/email password if auth client is active.

```
return [
    'components' => [
        'authClientCollection' => [] // <----- just this line of code made the problem
];
```

Is not important if there are clients, if I remove that line is possible to login.

I try to remove from login.php view the part of code print the social login, but nothing happen.

It's return: user or password incorrect

same problem without solution it is here: https://github.com/humhub/humhub/issues/2583

**Comment by gomonkey** [comment]
I found the solution, I removed the class yii\authclient\Collection

```
'authClientCollection' => [
            //'class' => 'yii\authclient\Collection',
            'clients' => [
                'facebook' => [
                    'class' => 'yii\authclient\clients\Facebook', 
                    'clientId' => '***********',
                    'clientSecret' => '************',
                ],
                'google' => [
                    'class' => 'yii\authclient\clients\Google', 
                    'clientId' => '*********',
                    'clientSecret' => '******',
                ],
            ],
        ],
```

at the moment is look like working

**Comment by martincodeinc** [comment]
Yes, but then facebook login is not working anymore.
