### ISSUE TITLE
data-ui-loader in combination with type="submit" and client validation

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3465]
The loader button is not reset if the client side validation blocks the form submittion.

**Comment by baleks** [comment]
This error occurred only for HTML5 client validation and was fixed in "Added a captcha for the register form" ticket.
PR is already merged to master branch:
https://github.com/humhub/humhub/pull/3467/files#diff-94341aec78a3b5cb9caf7ed9259e7b38
