### ISSUE TITLE
Captcha in 1.3.9 breaks Sign Up form on /auth/login

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#3473]
### What steps will reproduce the problem?
Enable captcha in admin.

### What is the expected result?
New users can sign up via the login screen.

### What do you get instead?
Page reload, no errors in debugger.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.9
| PHP version      |  7.0
| Operating system | Ubuntu

No errors in humhub log.

**Comment by buddh4** [comment]
Can't recreate, 

- are there any javascript console errors, 
- did you try to flush the cache
- perhaps a theming issue?

**Comment by Felli** [comment]
I'm not exactly having this issue myself, but I have noticed that registration emails aren't going out once I've updated to v1.3.9, maybe a migration issue but not had any issues with the Captcha as a whole. :thinking:

**Comment by buddh4** [comment]
So I tested this within my test environment and a fresh 1.3.9 installation and could not recreate this. I tested with production assets on/off and captcha on/off and in any combination the registrations mails were sent as expected.

**Comment by niconacre** [comment]
Hi every one,
I’ve got an issue when I invite user by mail : The user correctly receive the invitation link, but he cannot activate it due to a registration fail error on the logging page.
I verify the entries in user_invite table and notice that no new line created after user has been invite, despite the invitation email correctly received..
I use mass user module, and I notice too that no new lines appear under the module tab when I load a invite .csv file
I precise that mass module has already run on my install
I use humhub 1.3.9, all module are up to date and I have no entries in log tab
I’ve got another running hh 1.3.8 with no issue about that

**Comment by martinbeek** [comment]
Meanwhile...  I've installed a new instance of humhub, out of the box, new database, still not working. If catcha enabled, the 'Sign up' form is no longer working. 


> Hi every one,
> I’ve got an issue when I invite user by mail : The user correctly receive the invitation link, but he cannot activate it due to a registration fail error on the logging page.
> I verify the entries in user_invite table and notice that no new line created after user has been invite, despite the invitation email correctly received..
> I use mass user module, and I notice too that no new lines appear under the module tab when I load a invite .csv file
> I precise that mass module has already run on my install
> I use humhub 1.3.9, all module are up to date and I have no entries in log tab
> I’ve got another running hh 1.3.8 with no issue about that

Yes here too...

**Comment by martinbeek** [comment]
> So I tested this within my test environment and a fresh 1.3.9 installation and could not recreate this. I tested with production assets on/off and captcha on/off and in any combination the registrations mails were sent as expected.

Here too, still same behavior

**Comment by martinbeek** [comment]
> Can't recreate,
> 
> * are there any javascript console errors,
> * did you try to flush the cache
> * perhaps a theming issue?

Out of the box fresh humhub community version install

**Comment by buddh4** [comment]
Ok, could recreate the issue with invite by mail.
