### ISSUE TITLE
/user/registration broken

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#3474]
### What steps will reproduce the problem?
Invite somebody via email, click on the link, which is e.g. https://community.humhub.com/user/registration

### What is the expected result?
A sign up form

### What do you get instead?
Error "Registration Failed" at the top of the login box.
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.9
| PHP version      | 7.1
| Operating system | Ubuntu

No errors in log, no errors in chrome debugger... 

This makes inviting people an embarassing event...

Martin.

**Comment by martinbeek** [comment]
By the way; can we get a quick and dorty fix? I've invited many people a few days ago, who now complain that they get an error... 

M.

**Comment by luke-** [comment]
The "Registration Failed" message should only appear if no token is attached to the URL as a parameter.
Without this token we cannot display the form, because the e-mail which requirement is not yet checked.

**Comment by luke-** [comment]
As DirtyFix you could simple delete this line:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/controllers/RegistrationController.php#L69

**Comment by martinbeek** [comment]
The problem lies again in the Captcha stuff. I have removed the captcha option and now it works again. 
By the way: **the error is on your own website too!**

**Comment by buddh4** [comment]
Could not recreate this on the community site. 

- I used the register form in the login page
- Received a mail, which links me to something like: https://community.humhub.com/user/registration?token=XXXXXXX
- opened the link and filled the registration form
- submitted the form and was logged in

I did the same test on the community some days ago with captcha active.

**Comment by clairedc** [comment]
I have the same bug. When I invite a new member by email from the administration, the link of the registration email contains no token and registration fails. Captcha is not active. 
When I invite a new member from a space, no email is sent at all. 
When auto-registration is active and someone registrates himself on the login page, the email is sended and the link is ok. It works.

**Comment by buddh4** [comment]
See the fix at https://github.com/humhub/humhub/commit/3144f6e1c6b1d561a62270e98411de47ceec3749 fixes the issue, hotfix version is comming soon.
