### ISSUE TITLE
oauth internal server error

### ISSUE THREAD

**Issue by arttu-uusikyyny** [humhub/humhub#3475]
I get this error:
2019-02-18 13:32:55 [195.148.33.20][1][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: humhub\components\UrlManager::authClientCollection in /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('authClientColle...', Array)
#1 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(humhub\components\UrlManager), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#4 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\componen...', Array, Array)
#5 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('humhub\\componen...', Array, Array)
#6 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#7 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('urlManager', true)
#8 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('urlManager')
#9 /home/vaajanva/public_html/intra/protected/humhub/components/ModuleManager.php(169): yii\di\ServiceLocator->__get('urlManager')
#10 /home/vaajanva/public_html/intra/protected/humhub/components/ModuleManager.php(110): humhub\components\ModuleManager->register('/home/vaajanva/...', Array)
#11 /home/vaajanva/public_html/intra/protected/humhub/components/bootstrap/ModuleAutoLoader.php(34): humhub\components\ModuleManager->registerBulk(Array)
#12 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/base/Application.php(327): humhub\components\bootstrap\ModuleAutoLoader->bootstrap(Object(humhub\components\Application))
#13 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#14 /home/vaajanva/public_html/intra/protected/humhub/components/Application.php(46): yii\web\Application->bootstrap()
#15 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/base/Application.php(273): humhub\components\Application->bootstrap()
#16 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\base\Application->init()
#17 /home/vaajanva/public_html/intra/protected/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#18 /home/vaajanva/public_html/intra/index.php(25): yii\base\Application->__construct(Array)
#19 {main}
2019-02-18 13:32:55 [195.148.33.20][1][-][info][application] $_GET = []

And my common.php looks this:

```
<?php
/**
 * This file provides to overwrite the default HumHub / Yii configuration by your local common (Console and Web) environments
 * @see http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html
 * @see http://docs.humhub.org/admin-installation-configuration.html
 * @see http://docs.humhub.org/dev-environment.html
 */
return [
    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        'authClientCollection' => [
            'clients' => [
                // ...
                'facebook' => [
                    'class' => 'humhub\modules\user\authclient\Facebook',
                    'clientId' => 'xxxxxxx',
                    'clientSecret' => 'xxxxxxx',
                ],
            ],
        ],
        ],
    ]
];
```

What i need to do?

**Comment by Felli** [comment]
There's an example of how to use the oauths with PrettyUrl enabled.

```
<?php

return [
    'components' => [
    // ...
        'authClientCollection' => [
            'clients' => [
                // ...
                'facebook' => [
                    'class' => 'humhub\modules\user\authclient\Facebook',
                    'clientId' => 'Your Facebook App ID here',
                    'clientSecret' => 'Your Facebook App Secret here',
               ],
              'github' => [
                    'class' => 'humhub\modules\user\authclient\GitHub',
                    'clientId' => 'Your GitHub Client ID here',
                    'clientSecret' => 'Your GitHub Client Secret here',
                    // require read access to the users email
                    // https://developer.github.com/v3/oauth/#scopes
                    'scope' => 'user:email',
               ],
               'google' => [
                    'class' => 'humhub\modules\user\authclient\Google',
                    'clientId' => 'Your Client ID here',
                    'clientSecret' => 'Your Client Secret here',
               ],
               'live' => [
                    'class' => 'humhub\modules\user\authclient\Live',
                    'clientId' => 'Your Microsoft application ID here',
                    'clientSecret' => 'Your Microsoft application password here',
                ],
               'twitter' => [
                'class' => 'humhub\modules\user\authclient\Twitter',
                   'attributeParams' => [
                       'include_email' => 'true'
                   ],
                    'clientId' => 'Your Twitter client key here',
                    'clientSecret' => 'Your Twitter client secret here',
                ],
               'linkedin' => [
                    'class' => 'humhub\modules\user\authclient\Linkedin',
                    'clientId' => 'Your Microsoft application ID here',
                    'clientSecret' => 'Your Microsoft application password here',
                ],
              ],
             ],
       //...
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ]
];
```
