### ISSUE TITLE
Random HTTP 500  Internal Server errors

### ISSUE THREAD

**Issue by Tie-fighter** [humhub/humhub#3476]
### What steps will reproduce the problem?
unknown

### What is the expected result?
Page loads normally

### What do you get instead?
500 internal server error

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.9
| PHP version      |  7.3
| Operating system | Debian (Webhoster)

Hi.
So I am having this weird issue where an seemingly random intervals I get 500 internal server errors that I can get rid of by pressing F5 or clicking on any displayed button.

It usually looks like this:
![image](https://user-images.githubusercontent.com/170315/52983890-6538d580-33ed-11e9-80f7-12b3f88638a2.png)

no httpd error.log entries

access.log:
`[redacted] - - [19/Feb/2019:01:08:25 +0000] community.thomas-steinbrenner.net "GET /index.php?r=dashboard%2Fdashboard HTTP/1.1" 500 18094 "https://community.thomas-steinbrenner.net/index.php?r=admin%2Finformation%2Fdatabase" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:08:25 +0000] community.thomas-steinbrenner.net "GET /themes/HumHub/css/theme.css?v=1540047171 HTTP/1.1" 200 14363 "https://community.thomas-steinbrenner.net/index.php?r=dashboard%2Fdashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:08:25 +0000] community.thomas-steinbrenner.net "GET /static/css/all-fe97aa401a1550480e3cfc3ed35fc5ce.css?v=1550172023 HTTP/1.1" 200 46800 "https://community.thomas-steinbrenner.net/index.php?r=dashboard%2Fdashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:08:25 +0000] community.thomas-steinbrenner.net "GET /static/js/jquery.pjax.modified.js?v=1550172023 HTTP/1.1" 200 9082 "https://community.thomas-steinbrenner.net/index.php?r=dashboard%2Fdashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:08:25 +0000] community.thomas-steinbrenner.net "GET /static/js/all-8db8e4b4683dc1ebf823584a8d4440fa.js?v=1550172023 HTTP/1.1" 200 481790 "https://community.thomas-steinbrenner.net/index.php?r=dashboard%2Fdashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:09:48 +0000] community.thomas-steinbrenner.net "GET /index.php?r=dashboard%2Fdashboard HTTP/1.1" 500 18094 "https://community.thomas-steinbrenner.net/index.php?r=admin%2Finformation%2Fdatabase" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:09:49 +0000] community.thomas-steinbrenner.net "GET /themes/HumHub/ico/favicon-32x32.png HTTP/1.1" 200 1654 "https://community.thomas-steinbrenner.net/index.php?r=dashboard%2Fdashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:09:51 +0000] community.thomas-steinbrenner.net "GET /index.php?r=dashboard%2Fdashboard HTTP/1.1" 302 346 "https://community.thomas-steinbrenner.net/index.php?r=admin%2Finformation%2Fdatabase" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:09:52 +0000] community.thomas-steinbrenner.net "GET /index.php?r=user%2Fauth%2Flogin HTTP/1.1" 200 6877 "https://community.thomas-steinbrenner.net/index.php?r=admin%2Finformation%2Fdatabase" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:11:46 +0000] community.thomas-steinbrenner.net "GET /index.php?r=admin%2Fmodule%2Flist HTTP/1.1" 403 17989 "https://community.thomas-steinbrenner.net/index.php?r=admin%2Finformation%2Fdatabase" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:11:48 +0000] community.thomas-steinbrenner.net "GET /index.php?r=user%2Fauth%2Flogin HTTP/1.1" 200 6898 "https://community.thomas-steinbrenner.net/index.php?r=admin%2Finformation%2Fdatabase" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:12:52 +0000] community.thomas-steinbrenner.net "POST /index.php?r=user%2Fauth%2Flogin HTTP/1.1" 500 35779 "https://community.thomas-steinbrenner.net/index.php?r=user%2Fauth%2Flogin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:12:53 +0000] community.thomas-steinbrenner.net "GET /assets/e09fdf45/js/humhub.mail.wall.js?v=1550515232 HTTP/1.1" 304 148 "https://community.thomas-steinbrenner.net/index.php?r=user%2Fauth%2Flogin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:12:53 +0000] community.thomas-steinbrenner.net "GET /assets/8ed96087/js/humhub.space.chooser.js?v=1550515232 HTTP/1.1" 200 3924 "https://community.thomas-steinbrenner.net/index.php?r=user%2Fauth%2Flogin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:12:53 +0000] community.thomas-steinbrenner.net "GET /assets/e09fdf45/js/humhub.mail.js?v=1550515232 HTTP/1.1" 200 1480 "https://community.thomas-steinbrenner.net/index.php?r=user%2Fauth%2Flogin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
[redacted] - - [19/Feb/2019:01:12:53 +0000] community.thomas-steinbrenner.net "GET /index.php?r=mail%2Fmail%2Fget-new-message-count-json HTTP/1.1" 200 602 "https://community.thomas-steinbrenner.net/index.php?r=user%2Fauth%2Flogin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
`
app.log shows errors but they seem to be random too:
`2019-02-19 02:09:48 [84.115.249.116][-][29b0d7fcf851c8fccccb85fd6eaed396][error][yii\base\ErrorException:32] yii\base\ErrorException: PHP Startup: Unable to load dynamic library 'mcrypt.so' (tried: /usr/lib/php/20180731/mcrypt.so (/usr/lib/php/20180731/mcrypt.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/mcrypt.so.so (/usr/lib/php/20180731/mcrypt.so.so: cannot open shared object file: No such file or directory)) in Unknown:0
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
2019-02-19 02:09:48 [84.115.249.116][-][29b0d7fcf851c8fccccb85fd6eaed396][info][application] $_GET = [
    'r' => 'dashboard/dashboard'
]
`

Integrity check works out, prerequisites are fine too.
I know this is very little to go with, but maybe somebody has an idea :/

**Comment by luke-** [comment]
Seams to be related to your server setup.
Please post such problems in our community.

**Comment by Tie-fighter** [comment]
How can this be? All pre-requisites are satisfied. 

On February 19, 2019 11:42:25 AM GMT+01:00, Lucas Bartholemy <notifications@github.com> wrote:
>Seams to be related to your server setup.
>Please post such problems in our community.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/humhub/humhub/issues/3476#issuecomment-465080541

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by buddh4** [comment]
Note that PHP 7.3 is currently not supported, we are working on this issue: https://github.com/humhub/humhub/issues/3403

**Comment by Tie-fighter** [comment]
Switched to PHP 7.2, error persists.

PS: I don't mind you closing the issue. I will keep documenting, maybe it comes in handy someday :)
