### ISSUE TITLE
Update yii2 AuthClient to 2.1.8

### ISSUE THREAD

**Issue by DeltaLima** [humhub/humhub#3477]
Hey folks! Google will shutdown Google+ APIs, including Google+ Sign-in. HumHub/Yii uses the plus.people.get method from the google+ api. On 7.3.2019 the API will be completely shutdown.
I guess the Oauth via Google will be broken after that date. 
Is this already a topic on the roadmap for the next release? 

Thanks and best regards!

### What steps will reproduce the problem?

See Google announcement about google+ api shutdown

> Hello Google+ Developer,

> The email below contains your most recent usage of Google+ APIs. Note: It includes Google+ OAuth > scope requests, which are also affected by the Google+ shutdown. A prior email sent to active API > callers did not include information about OAuth requests. One final reminder email will be sent in > February to users who still have active API or OAuth request activity.
> What do I need to know?

> On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a > progressive shutdown, with API calls starting to intermittently fail as early as January 28, 2019, and > OAuth requests for Google+ scopes starting to intermittently fail as early as February 15, 2019.
> What do I need to do?
> 
> Please update your projects listed below by March 7, 2019 and ensure they are no longer using Google+ APIs, or requesting Google+ OAuth scopes. The data below shows which Google+ API methods your projects have recently called, as well as Google+ OAuth scopes it has requested.

> Note: If you see calls to people.get, these can be the result of using the Google+ Sign-In feature in your application, which is now fully deprecated and is being shut down. Developers should migrate from the Google+ Sign-In feature to the more comprehensive Google Sign-in authentication system.

### What is the expected result?

users should be able to login

### What do you get instead?

users are not able to login via google oauth

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.8
| PHP version      | 7.0 Debian 
| Operating system | Debian 9.7

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by kesselb** [comment]
https://github.com/yiisoft/yii2-authclient/issues/258 a fix for yii2 authclient is available.
