### ISSUE TITLE
Unicode support in post and comments

### ISSUE THREAD

**Issue by pandeybk** [humhub/humhub#3482]
### Is your feature request related to a problem? Please describe.
Yes, I was writing post in Nepali using unicode, following text.

काठमाडौं नजिकै रहेका गोदावरी साहसिक पर्यटकको आकर्षक गन्तव्य हो । जहाँबाट करिब डेढ महिना अगाडिदेखि सुरू भएकाे प्याराग्लाइडिङ सेवा लिन सकिन्छ ।

It displayed and stored as following text,

???????? ????? ????? ??????? ?????? ???????? ?????? ??????? ?? ? ??????? ???? ??? ????? ????????? ???? ????? ?????????????? ???? ??? ?????? ?

I applied following patch to fix this issue, I wonder if we do this by default as a part of project itself.

```
ALTER DATABASE your_database_name CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE post CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE post CHANGE message message text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
 
ALTER TABLE comment CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE comment CHANGE message message text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

**Comment by buddh4** [comment]
See http://docs.humhub.org/admin-installation.html#database-setup `utf8mb4` is default since v1.3
