### ISSUE TITLE
Can't see the plugins list

### ISSUE THREAD

**Issue by Selecta72** [humhub/humhub#3499]
### What steps will reproduce the problem?

When I go to Modules/Plugins -> See Online/ Voir en ligne, i got nothing...

When I go to log I can see this error 👎 

`ERROR  Mon, 04 Mar 2019 16:09:41 +0100  application Could not connect to HumHub API! Error in cURL request: SSL certificate problem: self signed certificate in certificate chain`

`$_GET = [ 'r' => 'admin/information' '_pjax' => '#layout-content' '_' => '1551712055951' ] $_SERVER = [ 'MIBDIRS' => 'C:/xampp/php/extras/mibs' 'MYSQL_HOME' => '\\xampp\\mysql\\bin' 'OPENSSL_CONF' => 'C:/xampp/apache/bin/openssl.cnf' 'PHP_PEAR_SYSCONF_DIR' => '\\xampp\\php' 'PHPRC' => '\\xampp\\php' 'TMP' => '\\xampp\\tmp' 'HTTP_HOST' => 'localhost' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_X_CSRF_TOKEN' => 'UBs86KoqXa9n2WJ3whi2e_seBteMmY_B3O5ugyacLlAmU1qw62AV9QusOBmXcd4xqHF2mOLjxofptArlVaRGIg==' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36' 'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8' 'HTTP_ACCEPT' => 'text/html, */*; q=0.01' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_X_PJAX' => 'true' 'HTTP_X_PJAX_CONTAINER' => '#layout-content' 'HTTP_REFERER' => 'http://localhost/humhub/index.php?r=admin%2Fmodule%2Flist-online' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7' 'HTTP_COOKIE' => 'pm_calendar-upcoming-events-snippet=expanded; pm_getting-started-panel=expanded; pm_panel-activities=expanded; pm_new-people-panel=expanded; pm_space-members-panel=expanded; pm_user-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_spaces-statistics-panel=expanded; language=f2a2ed3ce37b33db639e6c19524c3b962576857e1d51134c0bc4d73f63eb6720a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22fr%22%3B%7D; PHPSESSID=es70c266v6fg09h93hkeeb111s; _identity=f0beebb3b9a043c2f7d4d9d748e0155e0f1304d362547863c0848b8c42b7ea64a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22445eb449-806c-4b65-adcf-87ba6a133634%22%2C2592000%5D%22%3B%7D; _csrf=141640956738b4498fdf066383ce64ecda3e5cd65b5ffca5d72b777a15392af9a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22vHfXAJHZluZnUihJSopOnzIF5Zdfs8hr%22%3B%7D' 'PATH' => 'C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\140\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\140\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\Binn\\ManagementStudio\\;C:\\Program Files\\Git\\cmd;C:\\xampp\\apache-ant/bin' 'SystemRoot' => 'C:\\Windows' 'COMSPEC' => 'C:\\Windows\\system32\\cmd.exe' 'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC' 'WINDIR' => 'C:\\Windows' 'SERVER_SIGNATURE' => '<address>Apache/2.4.34 (Win32) OpenSSL/1.1.0i PHP/7.2.10 Server at localhost Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.34 (Win32) OpenSSL/1.1.0i PHP/7.2.10' 'SERVER_NAME' => 'localhost' 'SERVER_ADDR' => '::1' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '::1' 'DOCUMENT_ROOT' => 'C:/xampp/htdocs' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => 'C:/xampp/htdocs' 'SERVER_ADMIN' => 'postmaster@localhost' 'SCRIPT_FILENAME' => 'C:/xampp/htdocs/humhub/index.php' 'REMOTE_PORT' => '24824' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=admin%2Finformation&_pjax=%23layout-content&_=1551712055951' 'REQUEST_URI' => '/humhub/index.php?r=admin%2Finformation&_pjax=%23layout-content&_=1551712055951' 'SCRIPT_NAME' => '/humhub/index.php' 'PHP_SELF' => '/humhub/index.php' 'REQUEST_TIME_FLOAT' => 1551712181.572 'REQUEST_TIME' => 1551712181`

Nothing in the error console log from google chrome

### What is the expected result?

See all the plugins list

### What do you get instead?

Nothing

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.10
| PHP version      | 7.2
| Operating system | Windows 10 + XAMPP

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Are you using some sort of proxy server or anti virus which may intercept the connection to the marketplace?
