### ISSUE TITLE
Wrong Base URL in some generated links

### ISSUE THREAD

**Issue by haqa** [humhub/humhub#3510]
Some links, such as the notifications bell, password change emails, invitations etc, are being created with the value of the `HTTP_HOST` header instead of the `Base URL` setting from the administrator settings page.

Note: This issue has been reported before and the tickets closed without resolution, does this mean it's somehow considered expected behaviour?

### What steps will reproduce the problem?
- Run HumHub behind a reverse proxy.
- Create content.
- Go to the notifications button.
- Click an update in the drop down.
- You get sent to the INTERNAL address (That contacted by the proxy) not the configured `Base URL`.

### What is the expected result?
All links should be relative to, or formed from the `Base URL`

### What do you get instead?
Some absolute links are formed using the `HTTP_HOST` header from the triggering request.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.11
| PHP version      | 7.2.15-0ubuntu0.18.04.1
| Operating system | Unbuntu 18.04 (Bionic)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by Felli** [comment]
Something similar to [this](https://stackoverflow.com/questions/15678945/is-it-possible-to-use-http-host-in-proxypass) would have to be done.

**Comment by haqa** [comment]
That sort of misses the point. Why ask the administrator to configure a "Base URL" if you are then going to use some other value instead?

I still, therefore, maintain that this is a bug. It ought to use the value that the administrator has configured and not try to make assumptions about the infrastructure in which it is running.

**Comment by luke-** [comment]
https://docs.humhub.org/docs/admin/reverse-proxy

**Comment by RiverDragon1** [comment]
So... How is this fixed? I dont see any way to fix this.

**Comment by luke-** [comment]
Unfortunately, I don't know much about IIS as a proxy, but you might have to do this: 
https://serverfault.com/questions/862951/iis-does-not-set-x-forwarded-host

Basically, the problem is that the reverse proxy has to pass on the correct URL to the application server.
