### ISSUE TITLE
Adding a new Profile field results in UnknownPropertyException

### ISSUE THREAD

**Issue by matsch-o0** [humhub/humhub#3513]
### What steps will reproduce the problem?

1. Go to Admin -> Users -> Profiles and "+ Add new field"
2. Create new field (see screenshot at the bottom for an example) and save.
3. Go to any particular user profile, navigate to About section.

### What is the expected result?

About section of the current user is shown.

### What do you get instead?

Humhub throws an UnknownPropertyException (see stacktrace below).

### Workaround

Merely re-saving the newly created field in the admin section (even without any changes) will resolve the error.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.11
| PHP version      | 
| Operating system | Linux

### Full error stack trace

yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\user\models\Profile::test in /var/www/eportfolio/protected/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/eportfolio/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get('test')
#1 /var/www/eportfolio/protected/humhub/modules/user/models/fieldtype/Text.php(192): yii\db\BaseActiveRecord->__get('test')
#2 /var/www/eportfolio/protected/humhub/modules/user/models/ProfileField.php(302): humhub\modules\user\models\fieldtype\Text->getUserValue(Object(humhub\modules\user\models\User), true)
#3 /var/www/eportfolio/protected/humhub/modules/user/models/Profile.php(307): humhub\modules\user\models\ProfileField->getUserValue(Object(humhub\modules\user\models\User))
#4 /var/www/eportfolio/protected/humhub/modules/user/models/Profile.php(276): humhub\modules\user\models\Profile->getProfileFields(Object(humhub\modules\user\models\ProfileFieldCategory))
#5 /var/www/eportfolio/protected/humhub/modules/user/views/profile/about.php(12): humhub\modules\user\models\Profile->getProfileFieldCategories()
#6 /var/www/eportfolio/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/eportf...')
#7 /var/www/eportfolio/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/eportf...', Array)
#8 /var/www/eportfolio/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/eportf...', Array, Object(humhub\modules\user\controllers\ProfileController))
#9 /var/www/eportfolio/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('about', Array, Object(humhub\modules\user\controllers\ProfileController))
#10 /var/www/eportfolio/protected/humhub/modules/user/controllers/ProfileController.php(88): yii\base\Controller->render('about', Array)
#11 [internal function]: humhub\modules\user\controllers\ProfileController->actionAbout()
#12 /var/www/eportfolio/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/eportfolio/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/eportfolio/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('about', Array)
#15 /var/www/eportfolio/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/profile/ab...', Array)
#16 /var/www/eportfolio/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#17 /var/www/eportfolio/index.php(25): yii\base\Application->run()
#18 {main}

### Add new Profile field screenshot

![Screenshot_2019-03-10 Userprofiles - Administration - Research Hub](https://user-images.githubusercontent.com/599237/54086195-8aaf6400-4347-11e9-928f-499ed2c0d769.png)

**Comment by Felli** [comment]
Might be the translation category ID? As it doesn't auto update any of the files once the field is used. :thinking:

**Comment by buddh4** [comment]
Are those all errors in the logs, or is there any error right after adding the field. Also check if the field is actually missing in the profile table.

**Comment by matsch-o0** [comment]
@Felli I'm using the platform in English, while others also experiencing the issue are using it in German.

@buddh4 There are no other errors - not when adding the field and not when browsing to a profile.

What is the profile table? Where should I check? (It's a completely new field I'm adding. I'm only adding it in the Admin interface. Am I supposed to be doing something else as well?)

**Comment by matsch-o0** [comment]
@buddh4 The new field does get added as a new column to the `profile` table in the DB when I'm adding it in the Admin interface. No change in the `profile` table after I'm re-saving the field in the Admin interface (which makes the error disappear).

**Comment by godsgood33** [comment]
I see the same issue.  I'll add that the new field does get added to the `profile` and `profile_field` tables.

**Comment by buddh4** [comment]
I've seen the same issue, seems that the cache has to be flushed after adding a new profile field. I thought this was fixed in the past, do you have any idea @luke- ?
