### ISSUE TITLE
Register problem (New users cannot register)

### ISSUE THREAD

**Issue by tholeb** [humhub/humhub#3514]
hello, I recently modify my htaccess of my webiste, and did a maintenance of it, and after that maintenance, new users cannot register :/ .

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.1
| PHP version      | latest
| Operating system | Windows 10 (server)

I tried to register with another account, and i got this error:
`Swift_TransportException: Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials u17sm13639698wrg.71 - gsmtp " in C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:383 Stack trace: #0 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('535-5.7.8 Usern...', Array) #1 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('RSET\r\n', Array, Array) #2 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\Esmtp\Auth\XOAuth2Authenticator.php(55): Swift_Transport_EsmtpTransport->executeCommand('RSET\r\n', Array) #3 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\Esmtp\AuthHandler.php(176): Swift_Transport_Esmtp_Auth_XOAuth2Authenticator->authenticate(Object(Swift_SmtpTransport), 'lifeinvader.bad...', 'tmmap49240') #4 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(332): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport)) #5 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand() #6 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start() #7 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2-swiftmailer\Mailer.php(146): Swift_Mailer->send(Object(Swift_Message)) #8 C:\xampp\htdocs\BadNight\Lifeinvader\protected\humhub\components\mail\Mailer.php(91): yii\swiftmailer\Mailer->sendMessage(Object(humhub\components\mail\Message)) #9 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\mail\BaseMailer.php(263): humhub\components\mail\Mailer->sendMessage(Object(humhub\components\mail\Message)) #10 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\mail\BaseMessage.php(49): yii\mail\BaseMailer->send(Object(humhub\components\mail\Message)) #11 C:\xampp\htdocs\BadNight\Lifeinvader\protected\humhub\modules\user\models\Invite.php(148): yii\mail\BaseMessage->send() #12 C:\xampp\htdocs\BadNight\Lifeinvader\protected\humhub\modules\user\models\Invite.php(122): humhub\modules\user\models\Invite->sendInviteMail() #13 C:\xampp\htdocs\BadNight\Lifeinvader\protected\humhub\modules\user\controllers\AuthController.php(84): humhub\modules\user\models\Invite->selfInvite() #14 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin() #15 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) #16 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array) #17 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('login', Array) #18 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('user/auth/login', Array) #19 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #20 C:\xampp\htdocs\BadNight\Lifeinvader\index.php(25): yii\base\Application->run() #21 {main}`

and that info:
`Swift_TransportException: Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials u17sm13639698wrg.71 - gsmtp " in C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:383 Stack trace: #0 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('535-5.7.8 Usern...', Array) #1 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('RSET\r\n', Array, Array) #2 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\Esmtp\Auth\XOAuth2Authenticator.php(55): Swift_Transport_EsmtpTransport->executeCommand('RSET\r\n', Array) #3 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\Esmtp\AuthHandler.php(176): Swift_Transport_Esmtp_Auth_XOAuth2Authenticator->authenticate(Object(Swift_SmtpTransport), 'lifeinvader.bad...', 'tmmap49240') #4 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(332): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport)) #5 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand() #6 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start() #7 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2-swiftmailer\Mailer.php(146): Swift_Mailer->send(Object(Swift_Message)) #8 C:\xampp\htdocs\BadNight\Lifeinvader\protected\humhub\components\mail\Mailer.php(91): yii\swiftmailer\Mailer->sendMessage(Object(humhub\components\mail\Message)) #9 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\mail\BaseMailer.php(263): humhub\components\mail\Mailer->sendMessage(Object(humhub\components\mail\Message)) #10 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\mail\BaseMessage.php(49): yii\mail\BaseMailer->send(Object(humhub\components\mail\Message)) #11 C:\xampp\htdocs\BadNight\Lifeinvader\protected\humhub\modules\user\models\Invite.php(148): yii\mail\BaseMessage->send() #12 C:\xampp\htdocs\BadNight\Lifeinvader\protected\humhub\modules\user\models\Invite.php(122): humhub\modules\user\models\Invite->sendInviteMail() #13 C:\xampp\htdocs\BadNight\Lifeinvader\protected\humhub\modules\user\controllers\AuthController.php(84): humhub\modules\user\models\Invite->selfInvite() #14 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin() #15 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) #16 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array) #17 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('login', Array) #18 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('user/auth/login', Array) #19 C:\xampp\htdocs\BadNight\Lifeinvader\protected\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #20 C:\xampp\htdocs\BadNight\Lifeinvader\index.php(25): yii\base\Application->run() #21 {main}`

I tried many things (also update humhub) and this doesn't work.

thanks for your anwsers.

**Comment by luke-** [comment]
This seems to be a configuratoin issue with your mail configuration (administration -> settings -> advanced -> email)

Swift_TransportException: Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials u17sm13639698wrg.71 - gsmtp " in 


Please use our community for such questions.
