### ISSUE TITLE
Please document proper use of `Image Magick convert command (optional)`

### ISSUE THREAD

**Issue by jusdino** [humhub/humhub#3521]
*Please document the intended use of the Administration->Advanced->Files->Image Magick convert command (optional) configuration option.*

### Is your feature request related to a problem? Please describe.
  I would like to have large images automatically down-sampled to a smaller resolution. It appears that this setting might be able to accomplish this goal but I can't find any reference to the option in your documentation anywhere!
### Describe the solution you'd like
  Please include this configuration option in your administration documentation. Description would need answers to questions such as:
  - When is the imagick command executed (part of the cron tasks? on file upload?)
  - What file names are available to the command?
  - If relative paths are needed, from where do they start?
  - If an output of the imagick command is intended to be picked up by Humhub, what does the output file need to be named?
  - How should the user reference the executable? Do they provide the path to the executable on the host OS or is there some PHP script/command that abstracts this?
  - Probably a link to the relevant imagick documentation would be a good idea as well.
### Describe alternatives you've considered
  - Documentation at http://docs.humhub.org/admin-advanced-configuration.html
  - Clearer explanations in the config GUI itself

**Comment by luke-** [comment]
It's not longer required with the upcoming 1.5+

**Comment by davidtessier** [comment]
> 
> 
> It's not longer required with the upcoming 1.5+

**I'm looking forward to this**. I really need a solution to compress or resize images that are being uploaded to my HumHub instance. The size of a phone-based photo is ridiculous now (5-20mb). I need to save space by resizing / compressing, and this Image Magic stuff had me boggled - I have no idea how to use it.

**Comment by luke-** [comment]
@davidtessier can you please create an extra issue for that feature. Currently there is no option for this and uploaded files are always saved in their original format.
