### ISSUE TITLE
how to setup cron job for windows server with xampp

### ISSUE THREAD

**Issue by aspkannan** [humhub/humhub#3525]
**Warning incomplete setup!**

The cron job for the background jobs (queue) does not seem to work properly. 
The cron job for the regular tasks (cron) does not seem to work properly. 

im using windows server 2012 with xampp

**Comment by githubjeka** [comment]
Just create tasks in scheduler windows for command `php yii ...`

**Comment by aspkannan** [comment]
Thank you working good.

**Comment by johnsonmercyi** [comment]
> Just create tasks in Windows scheduler for commands `PHP yii ...`

Sorry! Did you mean the CRON Job might not be necessary for that regard or is your solution coming after some CRON Job setups?

**Comment by UBIRAILTON** [comment]
I have the same problem. I do not know how to do. Can someone help me?
