### ISSUE TITLE
Dropdown-Option One Missing

### ISSUE THREAD

**Issue by pe-en** [humhub/humhub#3527]
Hey, 

I want to add a new category in my profil section for several questions with Dropdown answering option, like "Coffee or Tea?":

![bug1](https://user-images.githubusercontent.com/42466522/54986155-6b087480-4fb2-11e9-83af-a5d28b3fc008.JPG)

But in the final profil it only shows the answer when you chose option 2, 3 or more. NOT with option 1.

![bug2](https://user-images.githubusercontent.com/42466522/54986156-6ba10b00-4fb2-11e9-978f-3093c32ab194.JPG)

Any idea? 😟

**Comment by luke-** [comment]
Hmm, maybe it's not marked as Visible?

I cannot reproduce this.
