### ISSUE TITLE
yiisoft/yii2-apidoc:2.1.0 not php 7.2 compatible

### ISSUE THREAD

**Issue by prilka** [humhub/humhub#3529]
There is a dev-depency to `yiisoft/yii2-apidoc:2.1.0` wich is not compatible with php 7.2 (reserved word `Object` is used as classname). See: https://github.com/yiisoft/yii2-apidoc/blob/dd0918ccbce2c1bdea836667f54e8f8b99d27128/models/ParamDoc.php#L19

It's fixed in version `2.1.1`, so just bump the version with composer.

**Comment by buddh4** [comment]
I think we don't need the dependency, we use an external repo for building the doc.
