### ISSUE TITLE
File module -> File model -> isAssignedTo method

### ISSUE THREAD

**Issue by baleks** [humhub/humhub#3531]
[https://github.com/humhub/humhub/blob/59f5ca154060c0d6ec71f8b0784df4736bbe90f9/protected/humhub/modules/file/models/File.php#L185](url)

This method will never return true because strict equality is used in the second part of condition, but $record->object_id has varchar type (according to file table structure).

**Comment by samsheridan** [comment]
@baleks this is fixed now. See #2536
