### ISSUE TITLE
ldap user desactivat since last update

### ISSUE THREAD

**Issue by Spartacus2018** [humhub/humhub#3534]
### What steps will reproduce the problem?
Evry morning i come to my humhub and all my user from ldap are desactivate, ihave to connect in admin user and activate all user one by one

### What is the expected result?

All ldap user update or improrted for the first time have to be activated

### What do you get instead?
i got this problem since the last update HumHub 1.3.12 has just been released.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | Version installée actuellement : 1.3.12
| PHP version       PHP - Version - 7.0.33-0ubuntu0.16.04.3 | 
| Operating system ubuntu serveur |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by lutzministrator** [comment]
I'm having the same problem. Fresh install 1.3.12 on Ubuntu 18.04 with php 7.2. 
Cronjobs running, LDAP users imported successfully, but deactivated assumingly by the hourly cronjob. 
Logfile says 'Disabled user[username] (4) - not found in LDAP! '

**Comment by pe-en** [comment]
Same problem with my system too. HELP... 😫

**Comment by Spartacus2018** [comment]
Hello 
to solve this problem u have to do this : 

> Lucas Bartholemy 29 mars 2019 - 10:27
> 
> Try to set this attribute to “objectguid” and wait an hour (or run the php yii ldap/sync command)

Found here : 
https://community.humhub.com/s/general-discussion/?contentId=184494

**Comment by pe-en** [comment]
THX seems to work! 👍

**Comment by lutzministrator** [comment]
I can confirm setting an ID Attribute solves the issue. Why not make that field mandatory if it's necessary for LDAP to work properly?

**Comment by biznlinks** [comment]
Even with the added objectguid in the ID attribute, some users are still being disabled hourly. Assistance required urgently.

**Comment by aklamke** [comment]
> Even with the added objectguid in the ID attribute, some users are still being disabled hourly. Assistance required urgently.

Please check if you have a space behind the ID attribute. This happened to my because I copy/pasted from the hint on the page. Every run of "yii ldap/sync" forced every user to be disabled. After deleting the space and rerun of "yii ldap/sync" all users came back activated.

**Comment by svenjungnickel** [comment]
> Even with the added objectguid in the ID attribute, some users are still being disabled hourly. Assistance required urgently.

The ID attribute `objectguid` also did not work for me. But in my case we are using OpenLDAP for user authentication, not ActiveDirectory. For user using OpenLDAP you need to add `uidNumber` and run the `yii ldap/sync` in order to get all user activated again.

**Comment by AsimAJ33** [comment]
> > Even with the added objectguid in the ID attribute, some users are still being disabled hourly. Assistance required urgently.
> 
> Please check if you have a space behind the ID attribute. This happened to me because I copy/pasted from the hint on the page. Every run of "yii ldap/sync" forced every user to be disabled. After deleting the space and rerun of "yii ldap/sync" all users came back activated.

This resolved my issue.  I had a space after objectguid because I pasted from Active Directory.  After running `yii ldap/sync` all accounts are enabled.
