### ISSUE TITLE
Install the Hound GitHub app

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3535]
https://github.com/apps/hound

An admin of this repo would have to simply follow the link, click "Configure" and install Hound app on just this one repository.

More info at https://www.houndci.com/#how-it-works

**Comment by acs-ferreira** [comment]
Cc @luke- (as repo admin)

**Comment by luke-** [comment]
Thanks, I have activated it as for testing on a few module repos (Wiki, Tasks, Polls, Mail, Calendar).
