### ISSUE TITLE
Site-breaking bug on Firefox : Hidden Gallery

### ISSUE THREAD

**Issue by GaretSD** [humhub/humhub#3537]
Hi everyone,

I have a site-breaking bug on my Humhub installation.
A Pop-up called “Hidden Gallery” appear in Firefox only and it shows up right after logging in. I tested it on 4 different PCs with Firefox, it's the same.

It's a fresh install of Humhub (1.3.12), it's the community version. I have PHP 7.0 and MySQL 5.6.
I'm hosted by OVH, on a shared hosted environnement, on a sub-domain.
Note that it works just fine in a localhost.

Any idea on how to get rid of it? I don’t want my users on Firefox to be left out !

Thanks a lot,
![screenshot](https://user-images.githubusercontent.com/49170650/55360865-df24aa00-54d5-11e9-9f38-da89c40f89e4.PNG)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.12
| PHP version      | 7.0
| MySQL version | 5.6
| Hosting environment | Shared hosting, sub-domain

EDIT : I tried installing it on another server on the same hosting provider (OVH) and it works. So, this probably have to do with the sub-domain ?
Anyone know issues about sub-domain installation ?

Thanks again

**Comment by Felli** [comment]
Does this happen when Ad Blocker is disabled on site?

**Comment by GaretSD** [comment]
Hi Felli,

Yes, even when I disable entirely the AdBlock, the bug still happens.
The bug also occur on Firefox on MacOS

**Comment by GaretSD** [comment]
Update:
I manage to solve the issue.
I simply change my server's PHP version to 5.6 .

If you have the same problem, try it it might resolve it. Be careful, though as you may have other websites hosted on the same server with PHP7 functions only.

The bug on shared hosting environnement with PHP 7.0 on Mozilla Firefox is still present though.
