### ISSUE TITLE
Cron Job not working from con

### ISSUE THREAD

**Issue by MohammadRiyad** [humhub/humhub#3538]
I have installed humhub 1.3.12 on php7. Everything is good. But I cant solve the problem below where its shows background job doesn't seem to work properly.

please help.

![image](https://user-images.githubusercontent.com/13892492/55476674-0778e980-5639-11e9-9acf-cba3f64478a6.png)

![image](https://user-images.githubusercontent.com/13892492/55476870-7e15e700-5639-11e9-8591-37b4f68d1cf4.png)

**Comment by buddh4** [comment]
Did you already ask [the community](https://community.humhub.com/dashboard) for help? 
There is also a wiki available https://community.humhub.com/s/installation-and-setup/wiki/page/view?title=Cron+Job+Setup

Note that the github issues should not be used for support issues but rather for feature requests and bugs.
