### ISSUE TITLE
failed loading cafile stream: `C:\xampp\apache\bin\curl-ca-bundle.crt' 

### ISSUE THREAD

**Issue by aspkannan** [humhub/humhub#3540]
**Hi, anyone can help me on the following error when i click 'Send email invitation'. 
FYI, im using ofiice365 SMTP settings** 

yii\base\ErrorException: failed loading cafile stream: `C:\xampp\apache\bin\curl-ca-bundle.crt' in C:\xampp\htdocs\humhub\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:103
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'failed loading ...', 'C:\\xampp\\htdocs...', 103, Array)
#1 C:\xampp\htdocs\humhub\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php(103): stream_socket_enable_crypto(Resource id #408, true, 57)
#2 C:\xampp\htdocs\humhub\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(313): Swift_Transport_StreamBuffer->startTLS()
#3 C:\xampp\htdocs\humhub\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#4 C:\xampp\htdocs\humhub\protected\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#5 C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2-swiftmailer\Mailer.php(146): Swift_Mailer->send(Object(Swift_Message))
#6 C:\xampp\htdocs\humhub\protected\humhub\components\mail\Mailer.php(91): yii\swiftmailer\Mailer->sendMessage(Object(humhub\components\mail\Message))
#7 C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\mail\BaseMailer.php(263): humhub\components\mail\Mailer->sendMessage(Object(humhub\components\mail\Message))
#8 C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\mail\BaseMessage.php(49): 

yii\mail\BaseMailer->send(Object(humhub\components\mail\Message))
#9 C:\xampp\htdocs\humhub\protected\humhub\modules\user\models\Invite.php(148): yii\mail\BaseMessage->send()
#10 C:\xampp\htdocs\humhub\protected\humhub\modules\admin\controllers\PendingRegistrationsController.php(96): humhub\modules\user\models\Invite->sendInviteMail()
#11 [internal function]: humhub\modules\admin\controllers\PendingRegistrationsController->actionResend('6')
#12 C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('resend', Array)
#15 C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/pending-r...', Array)
#16 C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#17 C:\xampp\htdocs\humhub\index.php(25): yii\base\Application->run()
#18 {main}

**Comment by buddh4** [comment]
Seems to be a problem with your php installation and is not directly related to humhub. Please search in the web or ask at the [community ](http://community.humhub.com/) for help.
