### ISSUE TITLE
Notifications right away, out of the queue/cron

### ISSUE THREAD

**Issue by GaretSD** [humhub/humhub#3541]
Hi everyone,
Is there a way to send notifications right away without having to wait for the cron to activate ?
I get that humhub put them in cron  for potentially long running tasks, but with my configuration, but waiting every minute or even every hour (for shared env.) to send the notifications can be tedious.

So is there a way to execute background jobs right away in the code ?
If not, that would be a great feature,

Thanks a lot,

**Comment by buddh4** [comment]
Currently there is only a way to bypass the async queue for all jobs by configuring the [Sync or Instant queue](http://docs.humhub.org/admin-asynchronous-tasks.html#sync-and-instant-queue). But I don't recommend it. If you have a rather small userbase you can test it but some jobs like rebuilding the searchindex etc. are prone to fail with this configuration.

**Comment by GaretSD** [comment]
Thanks @buddh4 .
I'll still give it a try, I won't have to rebuild search indexes everyday. Do you know how to activate the function ? (http://docs.humhub.org/humhub-modules-queue-driver-instant.html)
I'm on a shared environment (OVH) if it can help,

Thanks a lot for your help

**Comment by buddh4** [comment]
Edit `humhub/config/common.php` as follows:

```
return [
  'components' => [
        'queue' => [
            'class' => \humhub\modules\queue\driver\Instant::class,
        ],
    ]
]
```

**Comment by GaretSD** [comment]
Guess Il'l try it, thank you !
