### ISSUE TITLE
A Way to leave "impersonate"

### ISSUE THREAD

**Issue by kaoz3000** [humhub/humhub#3546]
### Is your feature request related to a problem? Please describe.
As admin you can impersonate as an other user under:
Administration -> Users -> Users -> gear symbol -> Impersonate
but how to become admin again?

### Describe the solution you'd like
Instead, or as an addition, of the "Logout" button at the profile menu in the top right corner I would like to have a "Change back to [Admin User Name]" Button.

### Describe alternatives you've considered
The only solution I found was log out, and then logging back in as admin user.

**Comment by michaelh99** [comment]
+1 for this feature.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5278:

<img width="481" alt="relogin" src="https://user-images.githubusercontent.com/6995524/132494041-292d27c6-ba6b-4add-9a80-0e8ebb34af63.png">

**Comment by ArchBlood** [comment]
> @luke- PR https://github.com/humhub/humhub/pull/5278:
> 
> <img width="481" alt="relogin" src="https://user-images.githubusercontent.com/6995524/132494041-292d27c6-ba6b-4add-9a80-0e8ebb34af63.png">

I like the idea behind this, although I think it would be easier if you place and `if ($impersonate) {} else { $logout}` here, remove the extra account menu item all together

**Comment by luke-** [comment]
@yurabakhtin can you please see my review.

**Comment by luke-** [comment]
@ArchBlood Can you please give an example?

**Comment by ArchBlood** [comment]
> @ArchBlood Can you please give an example?

@luke- just like @yurabakhtin's example but instead of adding `Sign-in back as Yura Bakhtin` as a separate item use an `if ()` clause to replace the `Logout` if you're impersonating another user otherwise the Logout item will remain, at least that is how it would work 🤔

**Comment by yurabakhtin** [comment]
@luke- 

> can you please see my review.

I have done changes there for your review.

> @ArchBlood Can you please give an example?

As I understand @ArchBlood wants to display only single the new "Stop impersonation" instead of the "Logout", let me know if I should do this.

**Comment by luke-** [comment]
@yurabakhtin Thanks

@ArchBlood I would like to keep it that way for now, that both options are available. Maybe we can improve this again in the future.

**Comment by luke-** [comment]
@yurabakhtin That would be nice: https://github.com/humhub/humhub/pull/5278#pullrequestreview-749352663

**Comment by yurabakhtin** [comment]
@luke- Done - https://github.com/humhub/humhub/pull/5278#discussion_r707043383.

**Comment by luke-** [comment]
Thanks!
