### ISSUE TITLE
Font Family in System Mail

### ISSUE THREAD

**Issue by kaoz3000** [humhub/humhub#3547]
All Mails humhub sends are rendered with a serif font. I think some versions ago on an another installation the font was sans-serif.

### What steps will reproduce the problem?
View Mails in google Mail or Apple Mail, other systems not tested.

### What is the expected result?
Font should rendered in this Order:
Open Sans, Arial, Tahoma, Helvetica, sans-serif

### Additional info
In the Mail source code the Fonts are declared like this:
`<body style="font-size:12px; font-family: 'Open Sans,Arial,Tahoma,Helvetica,sans-serif'; background-color: #ededed;">`
There should be no quotes around the list of fonts
Instead it should be:
`<body style="font-size:12px; font-family: 'Open Sans',Arial,Tahoma,Helvetica,sans-serif; background-color: #ededed;">`
with quotes around _Open Sans_ and not the whole list.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.12
| PHP version      | 7.1.27

**Comment by acs-ferreira** [comment]
It has been introduced by https://github.com/humhub/humhub/pull/3330 and should be fixed on the `less` file.

**Comment by luke-** [comment]
@acs-ferreira Is everything okay here or do we have to fix something?

**Comment by acs-ferreira** [comment]
Not fixed yet. As stated, should be fixed on the less file.
