### ISSUE TITLE
Class not found between external modules directories

### ISSUE THREAD

**Issue by gdalyy** [humhub/humhub#3551]
### What steps will reproduce the problem?
I'm developing two modules in external directories and i've configured the *moduleAutoloadPaths* parameter like this : 
```
return [
    'params' => [
        'moduleAutoloadPaths' => ['/path/to/my/modules'],        
    ],
]
```
let's say **Module Foo** and **Module Bar** are my two modules that i work on.
in the *config.php* file for **Module Bar** i've the following : 

```
<?php

use humhub\modules\foo\models\FooModel;

return [
    'id' => 'bar',
    'class' => 'humhub\modules\bar\Module',
    'namespace' => ''humhub\modules\bar',
    'events' => [
        [
            'class' => FooModel::class,
            'event' => FooModel::EVENT_AFTER_INSERT,
            'callback' => ['humhub\modules\bar\EventHandler', 'onModelFooInsert']
        ],
    ],
];

```
### What is the expected result?
Expected that *FooModel* class can be found.

### What do you get instead?
Then this error occurs : 
```
Class 'humhub\modules\foo\models\FooModel' not found in '/path/to/my/modules/bar/config.php:13
```  
**PS : if i put the **Module Foo** under */path/to/humhub/installation/protected/humhub/modules/* the above code works perfectly**

Is it an autoload problem or what ?

**Comment by luke-** [comment]
The namespace 'humhub\modules\bar' is only available once the module has been enabled.

So you need to use following code in the events section:

```
    'events' => [
        [
            'class' => 'humhub\modules\bar\models\FooModel',
            'event' => humhub\components\ActiveRecord::EVENT_AFTER_INSERT,
            'callback' => ['humhub\modules\bar\EventHandler', 'onModelFooInsert']
        ],
    ],
```
Does this solve your problem?

**Comment by gdalyy** [comment]
Yes it works, but what if I have a specific event like `FooModel::EVENT_FOO` ?

**Comment by gdalyy** [comment]
@luke- sorry my problem is not solved , the event is not triggered or maybe it's triggered but the callback class is not found !

**Comment by luke-** [comment]
@gdalyy Unfortunately, you cannot use constants from "non core" modules at this stage. In this case you need to use the constant value directly.

**Comment by gdalyy** [comment]
Thank you @luke-  for the explanation , so i'm closing this issue :+1:
