### ISSUE TITLE
Integrated Login broken on community portal

### ISSUE THREAD

**Issue by DuvelCorp** [humhub/humhub#3552]
I can't login anymore using Google integrated login on the official community portal, for about 2 weeks. 
I expected the bug to be detected and fixed in the meantime but that is not the case. 
Since I can't report the bug directly on the community portal, I open a ticket here.

### What steps will reproduce the problem?
Go to https://community.humhub.com/user/auth/login
Try to login with Github, Google, or Live
You receive instantly an "Internal server error"

### What is the expected result?
Being logged in.

### What do you get instead?
Internal server error

**Comment by jeanfelski** [comment]
Anybody have a fix for this?

**Comment by DuvelCorp** [comment]
its both strange and scary that no staff member have replied or fixed the issue yet...

**Comment by Felli** [comment]
The dev team are tirelessly working hard on fixing other things at this time, and the fixes have yet to be implemented into the community site, at this moment the only login issue that I am seeing is for the Google login, which the fix has already been implemented in this repo https://github.com/humhub/humhub/commit/1bcfc7a0821d876e4fc98f85788a38f529a8a3f1 so worry not.
