### ISSUE TITLE
Add user posting box to the top of the dashboard

### ISSUE THREAD

**Issue by tedstrauss** [humhub/humhub#3554]
### Is your feature request related to a problem? Please describe.

HumHub is a fantastic clone of a social networking experience but is missing the #1 feature for ease of user posting. 

### Describe the solution you'd like

I'd like for the user posting box to appear at the top of the dashboard page, just like it does on other social networks like facebook, linkedin. 

### Describe alternatives you've considered

user posting is only from the profile page. this is a hassle for users who are accustomed to a faster posting interface.

Maybe there's a module for this feature I haven't found yet?

**Comment by Felli** [comment]
This is already possible, or am I missing something? Under the settings in `ACP --> Settings --> General` then scroll down. At the moment Spaces are the only thing that can't be posted to from the dashboard.

![Screenshot_1](https://user-images.githubusercontent.com/2011633/56927038-1cfafb00-6aa1-11e9-89bd-fd5342e45a3c.png)

**Comment by tedstrauss** [comment]
Wow, you're right. I just wasn't looking hard enough.
Sweet!
