### ISSUE TITLE
Fatal errors and warnings while installation of Humhub version 1.3.13

### ISSUE THREAD

**Issue by prbt2016** [humhub/humhub#3558]
### What steps will reproduce the problem?
Download Humhub from https://www.humhub.org/en/download/start?version=1.3.13&type=zip&ee=0 and try to manually install it and hit the browser.

### What is the expected result?
Installer should start.

### What do you get instead?
Warnings and fatal errors i.e 
Warning:require(/{{path}}/{{to}}/{{humhubdir}}/protected/vendor/composer/../codeception/verify/src/Codeception/function.php): failed to open stream: No such file or directory in /{{path}}/{{to}}/{{humhubdir}}/protected/vendor/composer/autoload_real.php on line 66 

Warning: require(/{{path}}/{{to}}/{{humhubdir}}/protected/vendor/composer/../codeception/verify/src/Codeception/function.php): failed to open stream: No such file or directory in /{{path}}/{{to}}/{{humhubdir}}/protected/vendor/composer/autoload_real.php on line 66 

Fatal error: require(): Failed opening required '/{{path}}/{{to}}/{{humhubdir}}/protected/vendor/composer/../codeception/verify/src/Codeception/function.php' (include_path='.:/usr/local/apps/php56/lib/php') in /{{path}}/{{to}}/{{humhubdir}}/protected/vendor/composer/autoload_real.php on line 66  

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.13
| PHP version      |  5.6.40
| Operating system | Centos 6.4 Final Linux.
| Web Server | Apache 2.2.34

When I checked further I found that 'codeception' folder is not included inside the '/protected/vendor/' directory, which is the reason why fatal error is thrown. Could you please check and replicate this issue at your end and fix this.?

**Comment by Seidel-Michael** [comment]
Same Problem here. V1.3.12 works just fine.

**Comment by Felli** [comment]
I can confirm that there were install issues with v1.3.13 that happened with the composer vendor. :thinking:

**Comment by Felli** [comment]
@buddh4 tagging for a quick check.

**Comment by luke-** [comment]
I've just rebuilded the download packages!

Thank you!
