### ISSUE TITLE
run cron/run and queue/run error on heroku

### ISSUE THREAD

**Issue by devskill1123** [humhub/humhub#3559]
I deploy humhub to heroku, it's so good but when i run cron/run and queue/run then exits error

`
~ $ ./.heroku/php/bin/php protected/yii queue/run
Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No such file or directory'

in /app/protected/vendor/yiisoft/yii2/db/Connection.php:624

Stack trace:
#0 /app/protected/vendor/yiisoft/yii2/db/Connection.php(996): yii\db\Connection->open()
#1 /app/protected/vendor/yiisoft/yii2/db/Connection.php(983): yii\db\Connection->getMasterPdo()
#2 /app/protected/vendor/yiisoft/yii2/db/Schema.php(463): yii\db\Connection->getSlavePdo()
#3 /app/protected/vendor/yiisoft/yii2/db/Connection.php(881): yii\db\Schema->quoteValue('yii\\queue\\db\\Qu...')
#4 /app/protected/vendor/yiisoft/yii2/db/Command.php(209): yii\db\Connection->quoteValue('yii\\queue\\db\\Qu...')
#5 /app/protected/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->getRawSql()
#6 /app/protected/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->logQuery('yii\\db\\Command:...')
#7 /app/protected/vendor/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0)
#8 /app/protected/vendor/yiisoft/yii2/mutex/MysqlMutex.php(64): yii\db\Command->queryScalar()
#9 [internal function]: yii\mutex\MysqlMutex->yii\mutex\{closure}(Object(yii\db\Connection))
#10 /app/protected/vendor/yiisoft/yii2/db/Connection.php(1070): call_user_func(Object(Closure), Object(yii\db\Connection))
#11 /app/protected/vendor/yiisoft/yii2/mutex/MysqlMutex.php(65): yii\db\Connection->useMaster(Object(Closure))
#12 /app/protected/vendor/yiisoft/yii2/mutex/Mutex.php(72): yii\mutex\MysqlMutex->acquireLock('yii\\queue\\db\\Qu...', 3)
#13 /app/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(177): yii\mutex\Mutex->acquire('yii\\queue\\db\\Qu...', 3)
#14 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(yii\db\Connection))
#15 /app/protected/vendor/yiisoft/yii2/db/Connection.php(1059): call_user_func(Object(Closure), Object(yii\db\Connection))
#16 /app/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(212): yii\db\Connection->useMaster(Object(Closure))
#17 /app/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(78): yii\queue\db\Queue->reserve()
#18 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure))
#19 /app/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#20 /app/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure))
#21 /app/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false)
#22 [internal function]: yii\queue\db\Command->actionRun()
#23 /app/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /app/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#25 /app/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('run', Array)
#26 /app/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array)
#27 /app/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
#28 /app/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array)
#29 /app/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#30 /app/protected/yii(29): yii\base\Application->run()
#31 {main}
`
**How can I fix it?**
| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.12
| PHP     |  7.3 
| Operating system |

**Comment by luke-** [comment]
Seems the database is not configured.

Can you execute other actions like: php yii theme
