### ISSUE TITLE
Deletion fails if password contains a less than character

### ISSUE THREAD

**Issue by arueckauer** [humhub/humhub#356]
When trying to delete hosted instance and password contains `<`, **deletion will fail** with the following message:
> Your password is incorrect!

The password form field contains the submitted password, but the end of the string is trimmed starting with the less than character.

#### Example:
Say the current password is `qwe<123`, the form will than be filled with just `qwe`.

## Workaround for users with same problem
My solution was to change the password and then delete the instance.

## Notes
:point_right: Note that changing the password (current password containing a less than character) does not fail.

:warning: I strongly recommend that the submitted password is not provided as a default value!

**Comment by arueckauer** [comment]
To inform future visitors: Although the issue is closed, this bug has not been fixed!

**Comment by luke-** [comment]
It's really fixed, we roll out the new version of the hosting info module to production in the next days.

**Comment by arueckauer** [comment]
Thank you very much for the update and bugfix! :+1:

**Comment by luke-** [comment]
You're welcome! Sorry, for the very long response time :-)
