### ISSUE TITLE
Delete the file validator "Double file extensions are not allowed!"

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#3562]
### What steps will reproduce the problem?

Upload a file with the name `Screenshot 2019-05-11 at 11.35.46.png`

### What is the expected result?

This is a valid file, it should work.

### What do you get instead?

`humhub\modules\file\validators\FileValidator.php` detect 2 extensions and throw the error "Double file extensions are not allowed!"

### Additional info

This is a problem, because some people that hasn't got good knowledge in computers doesn't understand why they can't upload their file and don't understand what to do.
Some people try to upload auto generated screenshot files containing "double extension".

`if(preg_match('/\.\w{2,3}\.\w{2,3}$/', $model->file_name))` should be removed.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.12
| PHP version      | 7.1
| Operating system | Ubuntu 16.04

**Comment by luke-** [comment]
Which exact Humhub Version are you using?

**Comment by funkycram** [comment]
1.3.12

**Comment by luke-** [comment]
In 1.3.13 this should already be implemented.
 
https://github.com/humhub/humhub/commit/a73588bc159841fbf574457a4993c87501bf814c

**Comment by funkycram** [comment]
Perfect ! Sorry, I didn't think I could have been solved in this last release !
