### ISSUE TITLE
Bug in models/filetype/CheckboxList.php

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#3566]
In this file : https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/fieldtype/CheckboxList.php

in the function getUserValue, `$options[$value]` creates a bug as $value is an array containing one element per value checked

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.13

**Comment by luke-** [comment]
In which scenario can $value be an array? 
 It can be at most one list (as string) on comma separated values?

**Comment by funkycram** [comment]
1. Create a checkboxList field :
![image](https://user-images.githubusercontent.com/23310825/60333734-118d5880-999a-11e9-9068-093d32ac4ec9.png)

2. Go to /user/account/edit :
![image](https://user-images.githubusercontent.com/23310825/60333561-a774b380-9999-11e9-8879-933bf8353fc0.png)

**Comment by luke-** [comment]
![scrn-2019-06-28-13-56-15](https://user-images.githubusercontent.com/4736168/60340718-a600b680-99ac-11e9-949e-f494ede31305.png)

Hmm, cannot reproduce this. e.g.

**Comment by funkycram** [comment]
To reproduce this, you must check this :
![image](https://user-images.githubusercontent.com/23310825/60754360-2d1ee180-9fe0-11e9-8a6f-4ae4202dd0d8.png)

And check values in /user/account/edit . E.g. check A and B
If you add `print_r($value);` in the getUserValue function, you'll see that this function is called twice.
First call print_r  gives `A,C`
Second call (only if "searchable is checked) gives `Array ( [0] => A [1] => C )`
This is the bug.

**Comment by luke-** [comment]
Hmm, unfortunately I still can't reproduce this error.

This is my output after adding print_r() to the getUserValue function.

![scrn-2019-07-11-14-29-06](https://user-images.githubusercontent.com/4736168/61051010-92ac0d00-a3e8-11e9-856f-6c82099c03b8.png)

**Comment by buddh4** [comment]
@funkycram you mean the values are currently not translatable because of this?

**Comment by funkycram** [comment]
Now, with Humhub version 1.3.19, I have this bug :
![image](https://user-images.githubusercontent.com/23310825/71322837-6551a800-24cc-11ea-8028-bcb1b68876ee.png)

I had to change the code to this to temporary solve the problem :
```
            if (is_string($value)) {
                foreach (explode(',', $value) as $v) {
                    if ($v === 'other' && !empty($user->profile->$internalNameOther)) {
                        $translatedValues[] = Html::encode($user->profile->$internalNameOther);
                    } elseif (isset($options[$v])) {
                        $translatedValues[] = Html::encode(Yii::t($this->profileField->getTranslationCategory(), $options[$v]));
                    }
                }

                return implode(', ', $translatedValues);
            }
            elseif (is_array($value)) {
                return $value;
            }
```

**Comment by buddh4** [comment]
When exactly does this happen? Can you show me the field settings?

**Comment by funkycram** [comment]
Bug seems to be resoled with Humhub 1.5.2

**Comment by funkycram** [comment]
This issue is still present in Humhub 1.6.3 even on a fresh install without any modules activated.

I give again the step to reproduce.

1. Create a CheckboxList field
1. Check `Visible`, `Editable` and `Searchable` (if unchecked the bug doesn't occurs)
1. Add theses options:
```
test1=>test1
test2=>test2
```
Save and go in your account settings.
Check "Test 1" and save.

You will have:
![image](https://user-images.githubusercontent.com/23310825/94912511-0df35600-04a8-11eb-856f-5780157ebea2.png)

**Comment by luke-** [comment]
PR here: https://github.com/humhub/humhub/pull/4433
