### ISSUE TITLE
Datepicker 404 - on english language

### ISSUE THREAD

**Issue by Bhoft** [humhub/humhub#3570]
I knew that this issue was already posted in this issue
https://github.com/humhub/humhub/issues/1829

But as this issue is from 2016 i prefer to open a new one.

I got the problem that the datepicker throws an 404 html error when trying to load the correct locale js file according to the app language.

the requests are e.g. for "german" (de)
/assets/6a2cf9e0/ui/i18n/datepicker-de.js?v=1558355234

but for language "en_gb" it trys to load
6a2cf9e0/ui/i18n/datepicker-en.js?v=1.3.13

which doesn't exist. What exists is 
"datepicker-en-GB.js"

The problem is that your language is set to "en_gb" instead of "en-GB"  in the language selector.

https://www.yiiframework.com/doc/guide/2.0/en/tutorial-i18n

> For consistency reasons, all locale IDs used in Yii applications should be canonicalized to the format of ll-CC, where ll is a two- or three-letter lowercase language code according to ISO-639 and CC is a two-letter country code according to ISO-3166. More details about locale can be found in the documentation of the ICU project.

Of course you could say that there isn't a fallback language.
But e.g. if you select language "Português do Brasil" which is according to your language selector "pt_br" the fallback "pt" language file is used even if a "datepicker-pt-BR.js" exists.

So the correct file isn't selected.
 
### What steps will reproduce the problem?

select language "English (UK) and edit profile

### What do you get instead?

a 404 error on pages with a datepicker e.g. profile -> birthday

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.13
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
With the upcoming version 1.4 we try to change our language codes to be standard conform.

Due to our translation system,  we have to do this shortly before the release.
