### ISSUE TITLE
Missing Confirm-Buttons when deleting modules in spaces in CHROME

### ISSUE THREAD

**Issue by hajonolte** [humhub/humhub#3573]
as an admin go to ADMINISTRATION -> SPACES. on the right all the spaces are displayed. go to SETTINGS. then press administrator modules (Module verwalten). If you then click on disable, a pop up shows "are you shure" and then there are no button to say YES or NO when working with CHROME. in IE everything works fine.

| ---------------- | ---
| HumHub version   | 1.3.13
| PHP version      | 7.3
| Operating system | Debian

**Comment by luke-** [comment]
Can you please provide more information?
e.g. screenshot, used HumHub version, ...

I'm unable to reproduce this.

**Comment by hajonolte** [comment]
hmmm, i am very sorry, the problem does not occur anymore at the moment! as i changed a lot in the meantime, i can´t tell from which changes this got fixed.

**Comment by luke-** [comment]
Ok no problem, should the problem occur again we can reopen this issue.
