### ISSUE TITLE
Different number of displayed comments in the space and inside the post

### ISSUE THREAD

**Issue by nfkrocky** [humhub/humhub#3574]
Hello.
As far as i understood from [this code](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/comment/widgets/Comments.php), the number of displayed comments is hardcoded and is the same no matter what page user is currently on. As the result, two displayed comments just simple isn't enough to read the discussion comfortably inside the post (user is basically forced to load more comments anyway). Increasing this value will lead to another problem on the spaces page — it'll make it huge, since every post will contain more comments.

The solution to this could be the ability of setting this value separate on the space page and inside the post. I'd probably even prefered to hide all comments on the space page at all, while increasing the number to 10-20 or even more inside the post.

Maybe i'm wrong and there is such a possibility at the moment?
Thanks.

**Comment by luke-** [comment]
Can you please provide more information?
e.g. screenshot, used HumHub version, ...

I'm unable to reproduce this.

**Comment by buddh4** [comment]
I think we should generally rework the single post view in order to make it more discussion friendly. E.g. by default show all comments (or at least more with scroll auto loader) and a different layout.

**Comment by Ace2213** [comment]
I think all comments should be hidden by default until the user clicks the "Comment" button (next to the Like button) and then they can all/10 can appear.

This way, those interested in comments can see more of them without clicking load more, and those uninterested in comments will not be polluted by them.

**Comment by nfkrocky** [comment]
> I think all comments should be hidden by default until the user clicks the "Comment" button (next to the Like button) and then all/10 comments can appear.

Our users main complain is that they visit the single post page mostly for reading the discussion and every time it requires additional actions to do that, which nobody likes. If i increase the number of displayed comments, space page becomes unusable due to the same page layout.

Also you can try changing
`$comments = \humhub\modules\comment\models\Comment::GetCommentsLimited($modelName, $modelId, 2);`
to
`$comments = \humhub\modules\comment\models\Comment::GetCommentsLimited($modelName, $modelId, 0);`
to hide all the comments, it probably should work

**Comment by Ace2213** [comment]
I think you misunderstood.

When I say 'click the "Comment" button' I don't mean going to that post's page. I mean showing the comments. 

E.g by default you see this:
![image](https://user-images.githubusercontent.com/12226710/70058055-fbc13680-15bc-11ea-90ae-d976b321a9d3.png)

But when you click the "Comment" button, the comments are hidden and you see this:
![image](https://user-images.githubusercontent.com/12226710/70058122-1dbab900-15bd-11ea-9b84-ecc61a8611fe.png)

If you click it again, they are shown again. Without any delay, reload or going to a different page.

I'm saying that the default behavior should be to have it hidden, to take up less wall space, and if the user is interested they can click that button (still on the wall, without needing to go to the post's page) to see the comments.

If comments had to be clicked to be visible, then it would be possible to show more of them without bothering other users.

**Comment by nfkrocky** [comment]
> I think you misunderstood.

No, i didn't. You can change the number of displayed comments directly in the code. I didn't check for 0 value, but it might work as well (we currently display one comment before loading more)

> If comments had to be clicked to be visible, then it would be possible to show more of them without bothering other users.

And bothering users by forcing them to click buttons for reading any comments in the first place (which is the main users complain in our case). Not a solution at all.

This issue is about different comment layouts for different pages (spaces/direct posts), not about the number of displayed comments, which you can simply edit by yourself.

**Comment by Ace2213** [comment]
So you want all comments to be permanently visible in the space page?

**Comment by nfkrocky** [comment]
I would prefer to be able to configure different number of displayed comments separately at the space page and "direct post" pages. For instance, to completely disable (or limit to 1) loading comments automatically at the space page and load it all (or limit it to 100...200) automatically when the user is inside the post (`/?contentId=XXX`)
That's the most flexible way i can imagine so everybody can get what they want.

**Comment by Ace2213** [comment]
Ok and I never disagreed with that. I said that the default behavior on the space/profile page should be to have the comments hidden. You think that's bothersome to users.
