### ISSUE TITLE
search form with get causes repeated staticking of url paramers

### ISSUE THREAD

**Issue by Bhoft** [humhub/humhub#3581]
### What steps will reproduce the problem?There is an issue on the User administration page "admin/user/list"
I guess the issue is also on every other page with a GridView and filter possibilities.

Every search parameter (UserSearch[freeText] and UserSearch[status]) is repeated after each search e.g. status change.

e.g. after 2 times status selection:
`user/list?UserSearch[freeText]=&UserSearch[status]=0&UserSearch[freeText]=&UserSearch[status]=1`

you could either add a fixed url to the controller action e.g.

    <?php $form = ActiveForm::begin(['method' => 'get', 'action' => Url::to(['user/list'])]); ?>

mentioned here:
https://www.yiiframework.com/wiki/668/form-with-get-method-causes-repeated-stacking-of-url-parameters

Or you could extend the Yii\helpers\Url with something like this

    public static function currentExcept(array $params = [], $except = null, $scheme = false)
    {
        $currentParams = Yii::$app->getRequest()->getQueryParams();
        if (isset($except) && ArrayHelper::keyExists($except, $currentParams, $caseSensitive = true)) {
            ArrayHelper::remove($currentParams, $except);
        }
        array_unshift($currentParams, '/' . Yii::$app->controller->getRoute());
        $route = ArrayHelper::merge($currentParams, $params);
        return static::toRoute($route, $scheme);
    }

and could use this 

    'action' => Url::currentExcept([], $searchModel->formName())

so that only the searchModel parameters are removed form the current Url (so other parameters are kept).

### What steps will reproduce the problem?
go to e.g. the adminstation user list and change the status several times

### What is the expected result?
only "one" parameter per search condition 

### What do you get instead?
stacking search parameter after each request which could end in
- an exception because max url is reached (~2000 chars) 
- problems with bookmarking, because the url is different

### Additional info
| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.13
| PHP version      | 
| Operating system |

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Thanks for pointing out!
