### ISSUE TITLE
Link Google account to existing account

### ISSUE THREAD

**Issue by jeanfelski** [humhub/humhub#3583]
### Is your feature request related to a problem? Please describe.

We could not link existing accounts to Google accounts with the same email. Any method to do that?

### Describe the solution you'd like

Link Google account to existing account

### Describe alternatives you've considered

Click and integrate account

**Comment by luke-** [comment]
Did you tried: /user/account/connected-accounts

**Comment by jeanfelski** [comment]
> Did you tried: /user/account/connected-accounts

I made this comment before seeing the commit they did [here](https://github.com/humhub/humhub/commit/1bcfc7a0821d876e4fc98f85788a38f529a8a3f1). I got it right now, thank you!
