### ISSUE TITLE
Tour module Error

### ISSUE THREAD

**Issue by Hamllet** [humhub/humhub#3587]
### What steps will reproduce the problem?
Go Home->Guide: Overview
Go Home->Guide: Spaces
### What is the expected result?
To show Guide modal
### What do you get instead?
We get the below error
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.13
| PHP version      | 7.1.27
| Operating system | 

ERROR  Wed, 26 Jun 2019 21:00:53 +0200  yii\base\UnknownMethodException yii\base\UnknownMethodException: Calling unknown method: humhub\modules\tour\widgets\Tour::loadResources() in /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/Component.php:300 Stack trace: #0 /var/www/html/algoetalk/protected/modules/enterprise/themes/enterprise/views/tour/widgets/guide_interface.php(5): yii\base\Component->__call('loadResources', Array) #1 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/html/a...') #2 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/html/a...', Array) #3 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/a...', Array, Object(humhub\modules\tour\widgets\Tour)) #4 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('guide_interface', Array, Object(humhub\modules\tour\widgets\Tour)) #5 /var/www/html/algoetalk/protected/humhub/modules/tour/widgets/Tour.php(52): yii\base\Widget->render('guide_interface') #6 /var/www/html/algoetalk/protected/humhub/components/Widget.php(58): humhub\modules\tour\widgets\Tour->run() #7 /var/www/html/algoetalk/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array) #8 /var/www/html/algoetalk/protected/humhub/components/Widget.php(58): humhub\widgets\BaseStack->run() #9 /var/www/html/algoetalk/protected/humhub/modules/ui/view/components/View.php(251): humhub\components\Widget::widget() #10 /var/www/html/algoetalk/protected/modules/enterprise/themes/enterprise/views/layouts/main.php(87): humhub\modules\ui\view\components\View->endBody() #11 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/html/a...') #12 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/html/a...', Array) #13 /var/www/html/algoetalk/protected/humhub/components/Controller.php(135): yii\base\View->renderFile('/var/www/html/a...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #14 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/Controller.php(385): humhub\components\Controller->renderContent('<div class="con...') #15 /var/www/html/algoetalk/protected/humhub/modules/dashboard/controllers/DashboardController.php(69): yii\base\Controller->render('index', Array) #16 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #17 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #18 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #19 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #20 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array) #21 /var/www/html/algoetalk/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #22 /var/www/html/algoetalk/index.php(25): yii\base\Application->run() #23 {main}

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Should be fixed in Enterprise module version 1.3.15
