### ISSUE TITLE
Youtube oembed fault

### ISSUE THREAD

**Issue by biztabs** [humhub/humhub#3588]
The Oembed parameters set in “settings -advanced” do not have any affect on a video post render anymore. In mobile vid’s are now off canvas yet you can see even with a maxwidth of 800 rules are not being obeyed on pc either. it used to fit/cover the width. Notice the gap where the red line is…

![image](https://user-images.githubusercontent.com/17250623/60269633-c0705c80-98e6-11e9-9064-82ff5faed057.png)

To reproduce just copy paste a utube url in a space. 

### What is the expected result?
Previously the post was adjusted to cover the preview up to to the declared Oembed width declared.

### What do you get instead?
Now the Oembed json values are ignored.

### Additional info
Note 1: 

After testing in browser dev mode I have noticed that data-class=oembed_snippet is not being obeyed. If I edit the front html and strip out “data-” the css class is then respected and we get a a proper render of the video thumb fitting the container width. 

The code is being generated in /protected/humhub/models/UrlOembed.php in the following function. 

/**
* Builds the oembed preview html result in case the given $data array is valid.
*
* @param $url
* @param []|null $data
* @return string|null
*/
protected static function buildHtmlPreview($url, $data = null)
{
if(static::validateOembedResponse($data)) {
return Html::tag('div', $data['html'], [
'data' => [
'guid' => uniqid('oembed-', true),
'richtext-feature' => 1,
'class' => 'oembed_snippet',
'url' => Html::encode($url)
]

        ]);
    }
    return null;
}

Note 2: 

Front side failing code - Note data-class :

<div data-guid="oembed-5cfeb4d6a3ec78.48600584" data-richtext-feature="1" data-class="oembed_snippet" data-url="https://www.youtube.com/watch?v=gP5TaUgBsog"><iframe width="612" height="344" src="https://www.youtube.com/embed/gP5TaUgBsog?feature=oembed" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>

![image](https://user-images.githubusercontent.com/17250623/60270616-ad5e8c00-98e8-11e9-873b-fb8ec5e14101.png)

Note 3: 

Front side hard fixed code - Note removal of “data-”class : 
<div data-guid="oembed-5cfeb4d6a3ec78.48600584" data-richtext-feature="1" class="oembed_snippet" data-url="https://www.youtube.com/watch?v=gP5TaUgBsog"><iframe width="612" height="344" src="https://www.youtube.com/embed/gP5TaUgBsog?feature=oembed" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>

![image](https://user-images.githubusercontent.com/17250623/60270695-d3842c00-98e8-11e9-827d-cb838178e88e.png)

Note 4: 

When you force use of class=oemebed_snippet front side by changing data-class="oembed_snippet" to class="oembed_snippet" by stripping the word data- from the code then all works as it should and oembed maxwidth parameters are fully respected.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.14
| PHP version      | 
| Operating system |

**Comment by danielrodd** [comment]
Add class element like this, replace line 265 on UrlOembed.php

            return  Html::tag('div', ['class' => 'oembed_snippet'], $data['html'], [

delete cache and rebuild database, it should work
