### ISSUE TITLE
Unable to give user persmissions to allow pending registrations

### ISSUE THREAD

**Issue by rbovenkampclearict** [humhub/humhub#3590]
Unable to give user persmissions to allow pending registrations or see the list with open invitations. Also see https://community.humhub.com/content/perma?id=191427 for screenshots and more information.

Rick van den Bovenkamp 24 jun. 2019
After flushing the logs and reproduce the error, there’s nothing to see in the logs.

Sarah Tsumayoi 24 jun. 2019
Should create a group under ACP —> Users —> Groups then look for the following permission and allow.

Rick van den Bovenkamp 25 jun. 2019 · Bijgewerkt
Hi Sarah, was already enabled. Looks like a bug if you look at the strange behaviour. The strangest part is that it worked before and as far as i know, nothing changed.

Rick van den Bovenkamp 25 jun. 2019
By the way, it is in Dutch, it says manage users > allow.

I also tried to play with the group priority, because the user is also member of a group without the permissions. But unfortunately without success. If I add the user to the administrator group it works as aspected. If I add a new group with all options allowed (exactly same as admin group), than the strange behaviour described as above happens.

Sarah Tsumayoi 25 jun. 2019
I will look into this, please make sure to check your browser console for JavaScript errors as well as check ACP —> Information —> Logging for error stacks in the mean time, as much information that you can provide will help us get this solved.

Rick van den Bovenkamp 25 jun. 2019 · Bijgewerkt
Chrome console log:

Thank you so much Sarah

Profielafbeelding van Rick van den Bovenkamp
Rick van den Bovenkamp 25 jun. 2019
It even broke the menu, see screenshots

menu still shown

image.png

Menu gone when clicked on Pending approvals

image.png

Sarah Tsumayoi 25 jun. 2019
I just ran some tests, if a user group that only has a selected permissions this will happen otherwise you should get an error like the following.

Sarah Tsumayoi 25 jun. 2019
I’ll continue looking into the other issue but I’m not sure what exact is going wrong at this time as I’m not able to reproduce it just yet. 🤔

Rick van den Bovenkamp 26 jun. 2019
Hi Sarah, at this site I also run into this error when I gave the group full access to everything like an admin group.

Rick van den Bovenkamp 26 jun. 2019
If you want to see this yourself I can arrange a login?

Rick van den Bovenkamp 27 jun. 2019
Any idea?

Sarah Tsumayoi 27 jun. 2019
So after looking around, doesn’t seem like the pending registrations section has an access permission settings, or isn’t connected to the Manage Users permissions as they should be, for some reason? In any case I’ll go ahead and tag @Lucas Bartholemy for this. 🤔

Lucas Bartholemy 27 jun. 2019
That really seems to be a bug. @Rick van den Bovenkamp Can you please open a ticket for this at: https://github.com/humhub/humhub/issues/new/choose

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.13
| PHP version      |  PHP - Version - 7.0.33-0+deb9u3
| Operating system | Apache/2.4.25 (Debian)

**Comment by luke-** [comment]
Should be fixed here: https://github.com/humhub/humhub/commit/2d065f58cae96cec7b68aae2fcbb682328954b89
