### ISSUE TITLE
User invited can't choose SSO provider to register

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#3593]
### What steps will reproduce the problem?

1. Install an [external authentication provider like Google or Facebook](http://docs.humhub.org/admin-authentication.html)
2. Invite somebody by email (using the button in a space)
3. The user receive a mail containing this URL : https://url-to-humhub.tdl/user/registration?token=jJGqczCgmGB6
4. A register form is shown to him

### What is the expected result?

On this register form, there should be the button to register throw Google or Facebook, as it is the case on https://url-to-humhub.tdl/user/auth/login

But only the Humhub registration form is show.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.13
| PHP version      | 7.1
| Operating system | Ubuntu

**Comment by ArchBlood** [comment]
I'm guessing this is what the outcome is wanted here?
Add the following to display OAuth clients in the registration form, I'm not sure if this will work completely but it's a start
https://github.com/humhub/humhub/blob/5083c093f506506e5c28dca27e1f50893d17d16e/protected/humhub/modules/user/views/auth/login.php#L36-L44

![Screenshot_1](https://user-images.githubusercontent.com/35392110/100670574-1394dd00-332d-11eb-8cc0-b8b9baf5c888.png)

**Comment by luke-** [comment]
Yes the approach is correct. We only have to consider cases here if e.g. the "free registration" is deactivated.

**Comment by ArchBlood** [comment]
> Yes the approach is correct. We only have to consider cases here if e.g. the "free registration" is deactivated.

Wouldn't that be where `$canRegister` comes into play? I have noticed that even if registration is disabled but invites are, guests can still be registered on a site through the invite token that they get in an email, I'm sure that in some communities that this is frowned upon, is this HumHub's default behavior?

### Example
- Admin disables registration while leaves invite by email enabled
- UserA invites UserB
- UserB gets email and can then register to the site still

Using the registration form Url will of course still throw you an error saying Registration Failed, imo it should be Registration Disabled, but if the token is included the registration process can continue, rather interesting way of doing things :thinking:

Another thing I noticed which is kind of silly, tokens can still be reused if the user isn't accepted by an admin when admin approval is enabled, although this doesn't work and it throws `An internal server error occurred.` which it shouldn't throw this type of error but instead throw an `Already registered` error :thinking:

Your thoughts @luke-?

**Comment by buddh4** [comment]
@ArchBlood "Anonymous users can register" just means that users can invite themself in the login view. Of course users need to be able to register once you invite them.

Regarding the internal server error, please open another issue for this.

**Comment by ArchBlood** [comment]
> Regarding the internal server error, please open another issue for this.

Done

**Comment by funkycram** [comment]
Same issue as https://github.com/humhub/humhub/issues/1991

**Comment by luke-** [comment]
Should we close this issue? I hope we can add the links in the next version

**Comment by funkycram** [comment]
Well, it's not resolved, but if it will be in next version, of course, it can be closed. Or perhaps closing https://github.com/humhub/humhub/issues/1991?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5694
Please note I have implemented to generate username automatically from provided fields `firstname`, `lasttname` and `family_name` if at least one is defined from SSO provider side, also random may be generated if username is already used in DB.

**Comment by funkycram** [comment]
Thanks a lot @yurabakhtin , that's great!

Just if it can help, I use this code to generate the username:
```
            $username = BaseInflector::id2camel(
                BaseInflector::slug(
                    $attributes['firstname'] . ' ' . $attributes['lastname']
                )
            )
```

**Comment by yurabakhtin** [comment]
@luke- If we will remove the line https://github.com/humhub/humhub/pull/5694/files#diff-efe928bf9d75e2ffa9db20e2ba5b7d8a81a3f15c4a4b5a18cfab58d920f80f60R181:

```php
$attributes['username'] = self::generateUsername($attributes);
```

then it will works like this:

![test_sso_username](https://user-images.githubusercontent.com/6995524/168973253-4e25def0-8b32-4ac8-b04d-7079e18cfc1f.png)

Should I remove the auto-generating username, so user will types it manually in case when SSO doesn't provide a username or if it is already used by system by another user?

**Comment by funkycram** [comment]
I think that, if SSO doesn't provide a username or if it is already used by system by another user, auto-generating username could still be useful. As the username field is visible, then the auto-generated username can be modified by the user.

**Comment by luke-** [comment]
@funkycram @yurabakhtin Ok then let the username generation in place for now. Thanks!
