### ISSUE TITLE
Mobile menu not working

### ISSUE THREAD

**Issue by 7seventy2** [humhub/humhub#3597]
Bit of an amateur so I apologise if this is silly question
my site https://end-of-tenancy-cleaning-cambridge.co.uk was working fine for but for some reason main menu when on mobile has disappeared. Haven't changed anything. Desktop/laptop is fine.
Have tried two different mobiles but no luck.
Any ideas?

**Comment by Felli** [comment]
Um... Does this have anything to do with HumHub? Because I'm not sure...  :rofl:
