### ISSUE TITLE
Tagging / Mentioning takes too long or doesn't work

### ISSUE THREAD

**Issue by gonzam88** [humhub/humhub#3604]
Tagging or mentioning somebody takes too long, like a minute or so to show results. I have rebuilt index many times. This error shows up in the web console.
![Screen Shot 2019-07-24 at 4 47 39 PM](https://user-images.githubusercontent.com/6289953/61824376-37403d00-ae34-11e9-8583-518a0a718846.png)
Unhandled rejection (<[function anonymous]>, no stack trace)

Each time I try this I get both of these reports in Information > Logging

> $_GET = [ 'r' => 'search/search/mentioning' 'keyword' => 'ga' ] $_SERVER = [ 'PATH' => '/usr/local/bin:/usr/bin:/bin' 'TEMP' => '/tmp' 'TMP' => '/tmp' 'TMPDIR' => '/tmp' 'PWD' => '/' 'HTTP_ACCEPT' => '*/*' 'HTTP_ACCEPT_LANGUAGE' => 'es-US,es;q=0.9,es-419;q=0.8,en;q=0.7,it;q=0.6' 'CONTENT_LENGTH' => '0' 'HTTP_COOKIE' => '_ga=GA1.2.1610975166.1563126547; language=c4e603ddd788e01c21aae08a73358f4ab118d86fd81dbd3be5688a7f2f84fff1a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22es%22%3B%7D; _identity=f41749e1b03cc0aaeca4a0d90f3c26283937f9fbca4708775289a7663a6a6f23a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A51%3A%22%5B27%2C%22641d17d0-cc04-40a6-b4f0-31250ce861df%22%2C2592000%5D%22%3B%7D; PHPSESSID=j63292jd2jmpsp22llfiabv486; _csrf=a161333940746426dd89e66ca54b7beb8085e199df2352f6a29c5b80fc04d802a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22qJLsS0OxvOG2a0NXwdRxdQqenTPc7-Ta%22%3B%7D; pm_custom-snippet-2=expanded; pm_getting-started-panel=expanded; pm_panel-activities=expanded; _gid=GA1.2.613597272.1563996946; _gat_gtag_UA_113892592_1=1; pm_user-spaces-panel=expanded; pm_profile-follower-panel=expanded' 'HTTP_HOST' => 'elsalon.org' 'HTTP_REFERER' => 'https://elsalon.org/index.php?r=dashboard%2Fdashboard' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' 'HTTP_X_FORWARDED_FOR' => '186.139.242.214' 'HTTP_X_FORWARDED_HOST' => 'elsalon.org' 'HTTP_X_FORWARDED_PORT' => '443' 'HTTP_X_FORWARDED_PROTO' => 'https' 'HTTP_X_FORWARDED_SERVER' => 'elsalon.org' 'HTTP_DNT' => '1' 'HTTP_X_CSRF_TOKEN' => '91Rdqpib0Pmax70oaQcv-MOJD5Mc9_RQ56LXRKjIqjiGHhHZy6ufgeyI-hoIN2GgtO1d63imhTWJ9ocnn-X-WQ==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_X_HTTPS' => '1' 'UNIQUE_ID' => 'XTi4AGRSkqnWISHZMFLS1AAAAQw' 'SCRIPT_URL' => '/index.php' 'SCRIPT_URI' => 'https://elsalon.org/index.php' 'HTTPS' => 'on' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SERVER_NAME' => 'elsalon.org' 'SERVER_ADDR' => '142.44.156.46' 'SERVER_PORT' => '443' 'REMOTE_ADDR' => '186.139.242.214' 'DOCUMENT_ROOT' => '/home/elsalono/public_html' 'REQUEST_SCHEME' => 'https' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/home/elsalono/public_html' 'SERVER_ADMIN' => 'webmaster@elsalon.org' 'SCRIPT_FILENAME' => '/home/elsalono/public_html/index.php' 'REMOTE_PORT' => '38084' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=search%2Fsearch%2Fmentioning&keyword=ga' 'REQUEST_URI' => '/index.php?r=search%2Fsearch%2Fmentioning&keyword=ga' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1563998208.5045 'REQUEST_TIME' => 1563998208 ]

> ZendSearch\Lucene\Exception\OutOfBoundsException: Terms per query limit is reached. in /home/elsalono/public_html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Wildcard.php:183 Stack trace: #0 /home/elsalono/public_html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Search/Query/Boolean.php(132): ZendSearch\Lucene\Search\Query\Wildcard->rewrite(Object(ZendSearch\Lucene\Index)) #1 /home/elsalono/public_html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php(669): ZendSearch\Lucene\Search\Query\Boolean->rewrite(Object(ZendSearch\Lucene\Index)) #2 /home/elsalono/public_html/protected/humhub/modules/search/engine/ZendLuceneSearch.php(178): ZendSearch\Lucene\Index->find(Object(ZendSearch\Lucene\Search\Query\Boolean)) #3 /home/elsalono/public_html/protected/humhub/modules/search/controllers/SearchController.php(114): humhub\modules\search\engine\ZendLuceneSearch->find('ga', Array) #4 [internal function]: humhub\modules\search\controllers\SearchController->actionMentioning() #5 /home/elsalono/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #6 /home/elsalono/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #7 /home/elsalono/public_html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('mentioning', Array) #8 /home/elsalono/public_html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('search/search/m...', Array) #9 /home/elsalono/public_html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /home/elsalono/public_html/index.php(25): yii\base\Application->run() #11 {main}

### What steps will reproduce the problem?
In a post comment, writing @ and a few letters

### What is the expected result?
To quickly get a list of results

### What do you get instead?
A spinning wheel

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.14
| PHP version      | 7.0
| Operating system | Linux Redhat

**Comment by luke-** [comment]
With HumHub 1.4+ we not longer use PHP/Zend Lucence for the user search (e.g. also mentioning) and so this bug should be fixed.

In the meantime you could try use SOLR Search (if Enterprise Edition) http://docs.humhub.org/ee-solr.html or also a faster drive (e.g. SSD) may help.
