### ISSUE TITLE
Vcard Popover css breaks tour css

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub#3605]
### What steps will reproduce the problem?
Start a tour with addon Vcard popover installed. The tour popup has no margins.

### What is the expected result?
Popup with margins

| HumHub version   | 1.3.4
| PHP version      7.2
| Operating system  Linux

Details:
In popover.css: line 58
.popover-content {
    padding: 0px !important;   <-- should not use !important, make it popover specific.
}
breaks the padding  in theme.css line 1
.popover .popover-content {
    font-size: 13px;
    padding: 5px 15px;
    color: #555;
}

**Comment by luke-** [comment]
Can you please recreate this issue here: https://github.com/humhub-contrib/popover-vcard
