### ISSUE TITLE
Photo Tags in Gallery

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#3606]
When adding photos to Gallery albums, I can later go back and add/edit the text description of the individual photo.  I would like to have a practical way to tag users or topics as well.

I do see a Topics option for the connected post.  But I haven't figured out any way to insert a user tag here.

**Comment by luke-** [comment]
Can you please post this issue here: https://github.com/humhub-contrib/gallery

**Comment by miqrogroove** [comment]
https://github.com/humhub-contrib/gallery/issues/37
