### ISSUE TITLE
Gallery Menu Doesn't Work on Android

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#3607]
If I go to any individual gallery using my phone, the gear icon for the menu is overlapped slightly by the "Back to overview" button and is unusable.

HumHub v1.3.14
Chrome 75
Android 8.1

**Comment by luke-** [comment]
Gallery repo is here: https://github.com/humhub-contrib/gallery

**Comment by miqrogroove** [comment]
https://github.com/humhub-contrib/gallery/issues/38
