### ISSUE TITLE
Change of System administration Account 

### ISSUE THREAD

**Issue by vineetsampat** [humhub/humhub#3610]
Hi All,

I have System Administration Account and I want to sunset that account , but I want to make other user as System Administration holder .

Can anyone please help and guide. 

Thanks .

![System Administration - Change](https://user-images.githubusercontent.com/33293319/62225276-1de44700-b386-11e9-8a16-031b6627f611.PNG)

Regards,
Vineet Sampat

**Comment by luke-** [comment]
Please use our community at https://community.humhub.com for questions.
