### ISSUE TITLE
Provide an easy way to change the default page

### ISSUE THREAD

**Issue by jesimon** [humhub/humhub#3612]
Please add an option in the Admin screen to easily change the default page. Instead of going to the dashboard, I'd like it to go to another page. There does not seem to be an easy way of doing this without modifying code.

**Comment by Felli** [comment]
Using `/protected/config/web.php`
#### Space as default home.
```php
<?php

return [
   'homeUrl' => ['/space/space', 'sguid' => '<space-id>'],
];
```

#### Directory as default home.
```php
<?php

return [
   'homeUrl' => ['/directory/directory'],
];
```

After clear your browser & server cache.

#### Custom Pages Module
```php
<?php

return [
   'homeUrl' => ['/p/startpage'],
];
```
