### ISSUE TITLE
Modules can cause infinite loop

### ISSUE THREAD

**Issue by Themroc** [humhub/humhub#3616]
[mail-in.tar.gz](https://github.com/humhub/humhub/files/3494929/mail-in.tar.gz)
### What steps will reproduce the problem?
Install Community Edition 1.3.14
Unzip the attached module skeleton into protected/modules
Go to Administration - Modules and activate "Mail in"
Go to Welcome Space - Gear menu - Modules and enable "Mail in"
disable "Mail in"

### What is the expected result?
"Mail in" should be disabled in Welcome Space

### What do you get instead?
"An unexpected error occurred. If this keeps happening, please contact a site administrator."

Mysql-log saying

> tainer_module.module_id='mail-in' WHERE (`contentcontainer_module`.`module_state`=1) OR (`contentcontainer_module`.`module_state`=2)
>                   136 Query     SELECT * FROM `space` WHERE `id`=1
>                   136 Query     SELECT `contentcontainer`.* FROM `contentcontainer` LEFT JOIN `contentcontainer_module` ON contentcontainer_module.contentcontainer_id=contentcontainer.id AND contentcon

over&over again.

Admin/Information/Logging says

> INFO  Tue, 13 Aug 2019 02:13:50 +0200  application $_GET = [ 'r' => 'space/manage/module/disable' 'moduleId' => 'mail-in' 'cguid' => 'f8d26f16-0841-4f5e-b86b-487cfffc22f2' ] $_SERVER = [ 'USER' => 'www-data' 'HOME' => '/var/www' 'HTTP_COOKIE' => 'pm_calendar-upcoming-events-snippet=expanded; pm_getting-started-panel=expanded; pm_panel-activities=expanded; pm_space-members-panel=expanded; PHPSESSID=0h844hio88tsdl3i1asjlee0v1; _identity=a7309c2cb0741404d20cd0ea8761a581d12b4180a783e2af9eb79c2d5f17d5aea%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%2287700811-94d7-48d6-87bf-bbfc6fe009a5%22%2C2592000%5D%22%3B%7D; _csrf=ab9adc393813fedf2377460a7e3cc4e80ae88cff5573d2ada7e4ea5c35a01322a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22_a9GSWn8zyFTyN8KIsq6q_ye7hzMm4wI%22%3B%7D' 'HTTP_ACCEPT_LANGUAGE' => 'en,de;q=0.9,en-US;q=0.8,da;q=0.7,fr;q=0.6' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_REFERER' => 'https://test.REDACTED/index.php?r=space%2Fmanage%2Fmodule&cguid=f8d26f16-0841-4f5e-b86b-487cfffc22f2' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux i686 (x86_64)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_X_CSRF_TOKEN' => 'aCGAAgQYBMH1B1AfLmiJTZZImGy6yoWg0aGZCMScYSQ3QLlFV09q-Y9-FktXJrEG3zvpWsuV_MXmyeNFqagWbQ==' 'HTTP_ORIGIN' => 'https://test.REDACTED 'HTTP_ACCEPT' => '*/*' 'HTTP_CONTENT_LENGTH' => '0' 'HTTP_HOST' => 'test.REDACTED' 'REDIRECT_STATUS' => '200' 'SERVER_NAME' => 'test.REDACTED' 'SERVER_PORT' => '443' 'SERVER_ADDR' => 'REDACTED' 'REMOTE_PORT' => '45166' 'REMOTE_ADDR' => 'REDACTED' 'SERVER_SOFTWARE' => 'nginx/1.16.0' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'HTTPS' => 'on' 'REQUEST_SCHEME' => 'https' 'SERVER_PROTOCOL' => 'HTTP/2.0' 'DOCUMENT_ROOT' => '/www/test/html' 'DOCUMENT_URI' => '/index.php' 'REQUEST_URI' => '/index.php?r=space%2Fmanage%2Fmodule%2Fdisable&moduleId=mail-in&cguid=f8d26f16-0841-4f5e-b86b-487cfffc22f2' 'SCRIPT_NAME' => '/index.php' 'CONTENT_LENGTH' => '0' 'CONTENT_TYPE' => '' 'REQUEST_METHOD' => 'POST' 'QUERY_STRING' => 'r=space%2Fmanage%2Fmodule%2Fdisable&moduleId=mail-in&cguid=f8d26f16-0841-4f5e-b86b-487cfffc22f2' 'SCRIPT_FILENAME' => '/www/test/html/index.php' 'PATH_INFO' => '' 'FCGI_ROLE' => 'RESPONDER' 'PHP_SELF' => '' 'REQUEST_TIME_FLOAT' => 1565655230.3682 'REQUEST_TIME' => 1565655230 ]
> ERROR  Tue, 13 Aug 2019 02:16:05 +0200  yii\base\ErrorException:1 yii\base\ErrorException: Maximum execution time of 120 seconds exceeded in /www/test/html/protected/vendor/yiisoft/yii2/log/Logger.php:148 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main} Flush entries
 
In Administration - Modules - Mail in - disable or uninstall i get a "504 Gateway Time-out".

### Additional info
Now, i'm pretty shure i've done something wrong in this Module. However, HumHub shouldn't behave that evil, IMO. This thingie was generated with dev-tools, then i changed "mail-in" to "mail_in" in namespaces, changed "Mail-inModule.base" to "MailInModule.base" and when i tried to get a config-button in the Welcome Space/gear menu/module-area by copying over stuff from linklist, disaster happend and screwed my testing setup. Clearing protected/runtime/cache doesn't help, i can't get rid of that module once it is installed. Unless i clear the DB and upload a fresh one...

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.14
| PHP version      | PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
| Operating system | Devuan GNU/Linux 2.0 (ascii)

**Comment by Felli** [comment]
Use `public function disable()` instead for disable in `Module.php`. :wink:

**Comment by luke-** [comment]
I'm not sure, but if I understand it correctly, you changed the "moduleId" during module development.
Unfortunately there are then of course problems with the mapping.

Is that correct?

**Comment by luke-** [comment]
Ok, I found the problem with the endless loop, the method "disableContentContainer" in your Module class calls the wrong parent method.

![scrn-2019-08-13-15-43-21](https://user-images.githubusercontent.com/4736168/62946670-6fa6bb80-bde1-11e9-8b65-b232d3bd2b43.png)

**Comment by Themroc** [comment]
That's what devtools generated.

**Comment by Themroc** [comment]
Ok, thanks a million for your help!
It must be
```
    public function disableContentContainer(ContentContainerActiveRecord $container)
    {
        parent::disableContentContainer($container);
    }
```
Gonna complain at devtools.
