### ISSUE TITLE
Slash in usernames

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#3617]
It is possible to create a new user account that contains a slash in its name, for example Foo/Bar. This leads to a 404 error when trying to open the profile page of this user (URL /u/Foo%2FBar).

https://community.humhub.com/content/perma?id=194929

**Comment by zogith** [comment]
Hi, a user put a slash in their username on my Humhub install (version 1.7.1) and the same thing happened, so perhaps this bug has shown up again.
