### ISSUE TITLE
If user is following a space of which he is also a member, it shows up twice under "my spaces"

### ISSUE THREAD

**Issue by Themroc** [humhub/humhub#3625]
### What steps will reproduce the problem?
Install fresh 1.3.14, choose "set up everything manually" and "no example content"
Rebuild search index
Install&activate "Auto Follow", configure it to have "Welcome Space" in its spaces list
Add some user via Administration menu
Log in as that user
Click "My Spaces"

### What is the expected result?
"Welcome space" once, with "you are member" and "you are following" badges

### What do you get instead?
"Welcome space" with "you are member"
"Welcome space" again, but with "you are following"

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.14
| PHP version      | PHP 7.0.33-0+deb9u3
| Operating system | Devuan GNU/Linux 2.0 (ascii)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

Log is empty, no errors in ​browser console.

A possible fix would be https://github.com/Themroc/humhub/commit/210ab1b33f5768b30863814fed65ffbb6f440628. I'm not sure though if that is the way to go. If beeing a member of a space always entails following it, then a decent fix should happen somewhere else, imo.

**Comment by luke-** [comment]
https://github.com/humhub-contrib/auto-follow/commit/29fda16ac919beb9bdd17c5587f4df7bddce2b6c
