### ISSUE TITLE
It would be better if modules were space-bound, and not global

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3627]
I'm finding a lot of modules are unusable because they apply to the entire site, instead of being defined by each user/space.

All the social modules (steam, discord, patreon) and even productivity ones like tasks would make much more sense if they weren't global. Tasks should only exist inside the space, so that members can collaborate. Having only one list of tasks for the entire site is very limiting. Users also should be able to add their own steam, discord, patreon widgets to their profiles.

I understand if you don't think this is a good idea to change for everyone, but at least give us the option for those of us who want it.

**Comment by luke-** [comment]
Can you please create a feature request for the specific module.

You can find module repos here:
- https://github.com/humhub
- https://github.com/humhub-contrib
