### ISSUE TITLE
Can't remove the birthday module without causing problems

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3630]
I decided to remove the birthday module because it is global, not friend-based. i.e Everyone sees every user's birthday without needing to know who they are, which doesn't suit my use case. Check #3627 for more info.

I couldn't disable it. The module page kept refreshing without doing anything. So I uninstalled it. First, it refreshed without doing anything then on the second try, the whole website crashed. The module page, as well as other pages within the admin panel and ALL pages outside of the admin panel started giving the "Oops, you must have taken a wrong turn" error.

To rectify this, with the help of Google, I found out that I needed to run my cron jobs as apache, not as root. So I did that and the website came back to life.

But the birthday widget still appears in certain spaces. The module itself doesn't appear under any "modules" page, but it persists on the side panel of certain spaces, with seemingly no way of getting rid of it.

This is related to #3627 , but is an actual bug within the Humhub platform. I haven't had any issues with other modules yet, but frankly I worry about disabling them now.

**Comment by luke-** [comment]
Unfortunately I can't reproduce the problem myself.
Are there any entries in the logfiles or under Administration -> Information -> Logging. 

Can you reproduce the problem on our hosting? 

Important is, there are two different birthday widgets. One is provided by the calendar module and one is a standalone module for the dashboard.

**Comment by luke-** [comment]
So many log entries sound like a bigger problem and there's probably the error in disabling the birthday widget just a side effect.

If there are still error messages in the logfile, feel free to post it here or on a new issue.

**Comment by Ace2213** [comment]
Yes, this was a few days ago when I was still setting everything up. I guess I should be happy that I wasn't getting any log entries for a few days.

They're back now. Mostly [info] and cache write failure which doesn't really matter.
