### ISSUE TITLE
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'show_in_stream' 

### ISSUE THREAD

**Issue by danielrodd** [humhub/humhub#3633]
Everything is fine with the new update except for when I visit 
humhub/admin/information/database

It crashes with the following error:

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'show_in_stream' The SQL being executed was: ALTER TABLE `file` ADD `show_in_stream` tinyint(1) DEFAULT TRUE

### What steps will reproduce the problem?
Upon installing new update and when I visit that specific page in the admin section

Ok, So I tried to 
1. manually delete the column (mysql table file -> column show_in_stream) in my humhub mysql database, 
2. deleted cookies, 
3. rebuild search, 
4 deleted cache, 
5. went as far as to delete the file m170211_105743_show_in_Stream.php itself from folder protected -> humhub -> modules > file -> migrations 

and now I get the same error pointing to migration history. So I did a little digging and found this:

yiiframework.com/doc/guide/2.0/en/db-migrations#modifying-migration-history

### What is the expected result?
I suppose we should see the admin interface instead of the error page?

### What do you get instead?
The error page

### Additional info
It happened upon updating humhub from the previous version (HumHub 1.3.14) to the latest version (HumHub 1.3.15)

| Q                | A
| ---------------- | ---
| HumHub version   | HumHub 1.3.15?
| PHP version      |  7.1
| Operating system | Linux (hostgator shared plan)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

  PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'show_in_stream' in /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/db/Command.php:1258 Stack trace: #0 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute() #1 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE `fi...') #2 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute() #3 /home3/changedtoavoidhack/public_html/app/protected/humhub/modules/file/migrations/m170211_105743_show_in_Stream.php(9): yii\db\Migration->addColumn('file', 'show_in_stream', Object(yii\db\mysql\ColumnSchemaBuilder)) #4 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): m170211_105743_show_in_stream->up() #5 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(199): yii\console\controllers\BaseMigrateController->migrateUp('m170211_105743_...') #6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0) #7 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #8 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #9 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('up', Array) #10 /home3/changedtoavoidhack/public_html/app/protected/humhub/commands/MigrateController.php(184): yii\console\Controller->runAction('up') #11 /home3/changedtoavoidhack/public_html/app/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll() #12 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase() #13 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #14 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #15 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('database', Array) #16 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/informati...', Array) #17 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #18 /home3/changedtoavoidhack/public_html/app/index.php(25): yii\base\Application->run() #19 {main} Next yii\db\Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'show_in_stream' The SQL being executed was: ALTER TABLE `file` ADD `show_in_stream` tinyint(1) DEFAULT TRUE in /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/db/Schema.php:664 Stack trace: #0 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `fi...') #1 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE `fi...') #2 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute() #3 /home3/changedtoavoidhack/public_html/app/protected/humhub/modules/file/migrations/m170211_105743_show_in_Stream.php(9): yii\db\Migration->addColumn('file', 'show_in_stream', Object(yii\db\mysql\ColumnSchemaBuilder)) #4 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): m170211_105743_show_in_stream->up() #5 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(199): yii\console\controllers\BaseMigrateController->migrateUp('m170211_105743_...') #6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0) #7 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #8 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #9 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('up', Array) #10 /home3/changedtoavoidhack/public_html/app/protected/humhub/commands/MigrateController.php(184): yii\console\Controller->runAction('up') #11 /home3/changedtoavoidhack/public_html/app/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll() #12 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase() #13 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #14 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #15 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('database', Array) #16 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/informati...', Array) #17 /home3/changedtoavoidhack/public_html/app/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #18 /home3/changedtoavoidhack/public_html/app/index.php(25): yii\base\Application->run() #19 {main} Additional Information: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'show_in_stream' )

**Comment by danielrodd** [comment]
Ok, So I tried to 
1. manually delete the column (mysql table file -> column show_in_stream) in my humhub mysql database, 
2. deleted cookies, 
3. rebuild search, 
4 deleted cache, 
5. went as far as to delete the file m170211_105743_show_in_Stream.php itself from folder protected -> humhub -> modules > file -> migrations 

and now I get the same error pointing to migration history. So I did a little digging and found this:

https://www.yiiframework.com/doc/guide/2.0/en/db-migrations#modifying-migration-history

**Comment by luke-** [comment]
Can you pleas try to uncomment following line and try it again? 
https://github.com/humhub/humhub/blob/58c42652c8a6519a861a98080f1509b1686a3303/protected/humhub/modules/file/migrations/m170211_105743_show_in_stream.php#L9

**Comment by danielrodd** [comment]
Hi, I'm giving up on this one, the line was already uncommented

**Comment by luke-** [comment]
Sorry, I meant of course you can comment out or delete this line?
