### ISSUE TITLE
Set default space notifications for all members of a space.

### ISSUE THREAD

**Issue by tedstrauss** [humhub/humhub#3634]
### Is your feature request related to a problem? Please describe.

Users that join a space do not receive notifications of space activity unless they manually turn on notifications under space settings. Users don't know about that setting and so it's never turned on. 

### Describe the solution you'd like

The admin needs a method to activate space notifications by default for all users.
I propose this solution:

- Space > Gear icon > Security > Add a new  checkbox that says "Default setting for new members to receive notifications of new content."

Toggling the checkbox affects the default setting of 'receive notifications' for **new** members to the space. Doesn't affect existing members.

![Sur Place Internal - The Rink](https://user-images.githubusercontent.com/930560/63952631-e97bad80-ca4d-11e9-80b2-f831f2b5ab17.png)

### Describe alternatives you've considered

The same setting could be added globally as: Administration > Setttings > Notifications > new entry called: Space Notifications.

**Comment by buddh4** [comment]
Isn't this already available as admin under `Administration -> Settings -> Notification -> Receive 'New Content' Notifications for the following spaces` this will set the default value for all which did not already configured their notification settings.
