### ISSUE TITLE
The way banners are handled is just so messy

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3639]
Banners, in their default state, are almost entirely useless. They are very small and show a very small/narrow portion of the image. And in order to use them effectively, you have to upload an image with the right proportions and the right resolution to show what you want.

Increasing the size of the banner via theme.css only changes the size of the placeholder, not the actual amount of image that is shown, since the image still stretches those same 192 pixels to fill the placeholder.

Then there's the ProfileBannerImage.php mentioned in #1426, which actually does allow us to change the forced dimensions of the image.  But it ultimately doesn't make sense because if you set it up for one image then it won't necessarily work for any other. And for such a global setting it really needs to be flexible and work for everyone.

I tried cropping and reducing the resolution of the image before uploading to make it fit better and while that did help increasing the viewed real estate, it still gets stretched and with the lower resolution it looks even worse. So even expecting users to do their own fitting is not a solution.

And all of that only affects the auto-cropping done at the time of upload. If you try to adjust it yourself after the fact, none of the prior modifications matter, because cropping is handled by yet another script (cropBanner.php using jCrop), that I wasn't able to manipulate no matter how hard I tried.

I think an easy fix to all of these problems is to simply remove the dimension enforcing and replace it with aspect ratio enforcing. And either have the aspect ratio automatically update if the banner size is manipulated, or at least provide documentation on how to manually change the set aspect ratio to suit modifications.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/3402

**Comment by Ace2213** [comment]
I was able to "fix" this by changing the max-height element in [profileHeader.php](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/widgets/views/profileHeader.php) from 192 to my desired value and the crop aspect ratio in [ImageController.php](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/controllers/ImageController.php) and the "48" value in setSelect. I changed them as per aspect ratio calculations based on the default (unchanged) width and the change in height from 192 to my desired value.

**Comment by Ace2213** [comment]
In case anyone is interested in my values, my max-height is now 350px and the aspect ratio is 3.46. I'm not sure if it was necessary to change the cropsetSelect value but I changed it from 48 to 86.

There might be additional modification necessary on the CSS side (I can't remember) to increase the profile header size, but these are the only changes required in the code.

This is how it looks: 
350px viewport:
![image](https://user-images.githubusercontent.com/12226710/65930831-93e44900-e3dd-11e9-878d-bd5e5dd83f98.png)

540px viewport:
![image](https://user-images.githubusercontent.com/12226710/65930781-65ff0480-e3dd-11e9-9228-b47a81423ff1.png)

1150px viewport:
![image](https://user-images.githubusercontent.com/12226710/65930858-b9715280-e3dd-11e9-8219-40559872f3b5.png)
