### ISSUE TITLE
Improve loading speed performance on mobile

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3640]
I'm not sure if I'm doing something wrong, but according to these tests, it takes 18 seconds to load on mobile, compared to 4 seconds on desktop. The same recommendations exist for both, but seem to be hindering mobile performance significantly more. 

I should note that these numbers do not reflect real-world use. It takes me also about 4-5 seconds to load the page on my phone. I'm just curious why Google's PageSpeedInsight (17.9s) and TestMySite (13.5s) are having so much trouble with it. The former gave it a score of 2%, as opposed to the desktop which got 43%, both of which are considered "slow". I ran them several times with the same results.

Is there anything I can do about this or can these optimizations only be implemented through official updates?
![image](https://user-images.githubusercontent.com/12226710/64097683-4e2f5480-cd3b-11e9-8124-8ac3ae571a57.png)

**Comment by ArchBlood** [comment]
Web speed tests are normally only used for single page loads in HTML, JS, and CSS and are pretty useless for frameworks, to best use HumHub you should always pre-configure your server for HumHub use then re-configure after HumHub is installed for better loading speed, it all comes down to your server and how well it operates under heavy stress testing.

**Comment by luke-** [comment]
Did you enabled production mode?
http://docs.humhub.org/admin-security.html#enable-production-mode

**Comment by Ace2213** [comment]
I did, but I did it this way, and I'm pretty sure it worked because the admin panel was no longer saying that it's in debug mode.

/**defined('YII_DEBUG') or define('YII_DEBUG', true);
*defined('YII_ENV') or define('YII_ENV', 'dev');
*/

Is there anything else I was supposed to do to enable production mode?

**Comment by Ace2213** [comment]
@ArchBlood  how do you mean pre- and post-configure? I wasn't aware I could do any optimizations on my end, other than going with a newer version of PHP. When those tests ran I had 7.2. I now have 7.3. I'll rerun those tests and see if it makes a difference. I'll also properly comment out the debug mode lines.

**Comment by Ace2213** [comment]
I was finally able to run the test again with PHP 7.3. With debug mode on, it was getting a score of 0% on mobile and desktop. With debug mode off, 3% on mobile and 43% on desktop.

**Comment by miqrogroove** [comment]
One area that I would like to see improvement is the load time for the gallery slideshow.  It seems to be bandwidth intensive, as though it preloads all of the full resolution photos before displaying even the first image.

**Comment by buddh4** [comment]
We definetly should work on enhancing the overall performance in one of the upcoming versions. Perhaps we can assemble some issues as:

- More Script/Style optimization/minimization
- Image/Video optimization
- General code analysis and optimization
- Better optimization documentation (Caching/Cloud/Files/Server/etc.)

**Comment by luke-** [comment]
We should open one issue per point and close this one...

**Comment by Ace2213** [comment]
I still don't understand why pages load slower on mobile than they do on desktop, even though there's less content to generate and load (sidebars, logo).
