### ISSUE TITLE
LDAP connection is not responsible for given node

### ISSUE THREAD

**Issue by Blastiel** [humhub/humhub#3641]
Hi,

I've got humhub up and running as an internal site and so far so good. LDAP has been configured and the required users have synced over correctly HOWEVER when you try and log in as one of these users an unexpected server error is generated.

This is the error appearing in the logs;

ERROR  Mon, 02 Sep 2019 09:01:33 +0100  Zend\Ldap\Exception\LdapException Zend\Ldap\Exception\LdapException: 0x50: LDAP connection is not responsible for given node. in /var/www/humhub/protected/vendor/zendframework/zend-ldap/src/Node.php:148 Stack trace: #0 /var/www/humhub/protected/vendor/zendframework/zend-ldap/src/Node.php(88): Zend\Ldap\Node->attachLdap(Object(Zend\Ldap\Ldap)) #1 /var/www/humhub/protected/vendor/zendframework/zend-ldap/src/Node.php(276): Zend\Ldap\Node->__construct(Object(Zend\Ldap\Dn), Array, true, Object(Zend\Ldap\Ldap)) #2 /var/www/humhub/protected/vendor/zendframework/zend-ldap/src/Ldap.php(1855): Zend\Ldap\Node::fromLdap(Object(Zend\Ldap\Dn), Object(Zend\Ldap\Ldap)) #3 /var/www/humhub/protected/humhub/modules/ldap/authclient/LdapAuth.php(368): Zend\Ldap\Ldap->getNode('CN=John Smith...') #4 /var/www/humhub/protected/humhub/modules/ldap/authclient/LdapAuth.php(272): humhub\modules\ldap\authclient\LdapAuth->getUserNode() #5 /var/www/humhub/protected/humhub/modules/user/models/forms/Login.php(82): humhub\modules\ldap\authclient\LdapAuth->auth() #6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Model.php(369): humhub\modules\user\models\forms\Login->afterValidate() #7 /var/www/humhub/protected/humhub/modules/user/controllers/AuthController.php(77): yii\base\Model->validate() #8 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin() #9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('login', Array) #12 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/auth/login', Array) #13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #14 /var/www/humhub/index.php(25): yii\base\Application->run() #15 {main}

I'm not entirely sure where to look to resolve the issue, I'm quite new to this.

Hope someone can shine a light, thanks in advance.

**Comment by luke-** [comment]
Please use our community for configuration related questions.

**Comment by luke-** [comment]
Related: https://github.com/laminas/laminas-ldap/issues/4
