### ISSUE TITLE
Unable to modify common.php without breaking the website

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3644]
The only modification I've been able to successfully make to common.php was hidePoweredBy. Caching, auth and URL rewrite all break the whole website when I try to add them. I gave up on URL rewrite entirely because it caused irreparable harm to my installation. At least caching and auth I'm able to comment out. I don't receive any errors when it happens either, neither in logs nor if I enable displaying errors. It just says internal error.

Here's my working common.php file. The commented out parts are necessary to keep the website working. Am I doing something wrong? I copied the lines from the documentation and only replaced the server name in cache with localhost and my app ID and secret for auth.

`<?php`
         `return [`
          `'components' => [`
           `     'queue' => [`
            `            'class' => 'humhub\modules\queue\driver\MySQL',`
             `         ],`
              ` #        'cache' => [`
               `#            'class' => 'yii\caching\MemCache',`
                `#            'servers' => [`
              `#                [       `
             `#                    'host' => 'localhost',`
              ` #                   'port' => 11211,`
              `#                    'weight' => 60,`
             `#                ],`
            `#],`
           `#],        `
           `],`
           `    # 'authClientCollection' => [`
            `  #           'clients' => [`
          `#              'facebook' => [`
           `    #                 'class' => 'humhub\modules\user\authclient\Facebook',`
    `#                'clientId' => 'xxxxxxxxxxxx',`
     `#               'clientSecret' =>  'xxxxxxxxxxxxxxxxxxxxxxxx',`
      `     #          ],`
       `      #     ],`
         `        #],`
        `               'params' => [`
          `        'hidePoweredBy' => true`
           `       ],`

 `                 ];`

**Comment by ArchBlood** [comment]
Here's a modified version of my common.php file.

```php
<?php

return [
    'modules' => [
        'user' => [
            'emailRequired' => true,
            ],
        'directory' => [
            'active' => true,
            'guestAccess' => false
            ],
    ],
    'params' => [
            'allowedLanguages' => ['en', 'ja'],
            'hidePoweredBy' => false
    ],
    'components' => [
    // ...
        'authClientCollection' => [
            'clients' => [
                // ...
              'facebook' => [
                    'class' => 'humhub\modules\user\authclient\Facebook',
                    'clientId' => '***************************',
                    'clientSecret' => '******************************************************',
               ],
              ],
             ],
       //...
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
      ],
   ],
];
```

The use of this is unneeded because MySQL is the default option.
```php
'queue' => [
'class' => 'humhub\modules\queue\driver\MySQL',
],
```

I'd suggest reading to Yii docs about MemCache to better understand it's uses.
> Note: [there is no security measure to protected data in Memcache. All data in Memcache can be accessed by any process running in the system.](https://www.yiiframework.com/doc/api/2.0/yii-caching-memcache)


```php
        'cache' => [
            'class' => 'yii\caching\MemCache',
            'servers' => [
                [
                    'host' => 'localhost', // You can change this depending on if you have a server that handles this or not
                    'port' => 11211, // Depends on the server used generally 11211 is noticed as localhost
                    'weight' => 60,
                ],
            ],
        ],
```

**Comment by luke-** [comment]
Please use our Community for questions regarding the configuration.

**Comment by Ace2213** [comment]
Thank you @ArchBlood . That worked perfectly. Could you help me understand what was wrong with mine? I can't see the difference.

Regarding memcache, I only read Humhub's documentation about it, not Yii's. I appreciate you pointing out its lack of security, but I'm not concerned as I'll only be running it on the same server, and would like to see if I can benefit from the performance boost.

**Comment by ArchBlood** [comment]
As @luke- suggested contact me over on the community site and I'll try to do as best I can, although changing to MemCache from ACPu or ACP alone won't make much a difference, either way, I use ACPu myself and it works wonders. :smile:
