### ISSUE TITLE
Disabling the directory through group permissions doesn't affect guests

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3645]
I disabled access to the directory for users using group permissions, for privacy reasons. Now the button is gone from the top bar for users but they can still use search functionality using the search button that is persistent on all pages, which is awesome.

But, the directory is still visible and accessible for guests that are not logged in.

Shouldn't guests automatically have less rights than users? If not, is it possible to add a group for guests and decide what permissions they have?

**Comment by ArchBlood** [comment]
> ```
> <?php
> 
> return [
>     'modules' => [
>         'directory' => [
>             'active' => true,
>             'guestAccess' => false
>             ],
>     ],
> ];
> ```
> ```

Answered here https://github.com/humhub/humhub/issues/3644#issuecomment-529259326

**Comment by Ace2213** [comment]
Thank you @ArchBlood . I was not aware that option existed, as I had asked about this previously and was told it'll be coming soon.
