### ISSUE TITLE
Marketplace & HumHub Module Version Handling

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#3648]
### What steps will reproduce the problem?
When going by the [docs](http://docs.humhub.org/dev-modules-structure.html#meta-data-modulejson) on how to setup your _**module.json**_ the following is recommended

```json
{
    "id": "example",
    "version": "1.0",
    "name": "My Example Module",
    "description": "My testing module.",
    "humhub": {
        "minVersion": "1.2",
		"maxVersion": "2.0"
    },
    "keywords": ["my", "cool", "module"],
    "screenshots": ["assets/screen_1.jpg"],
	"homepage": "https://www.example.com",
    "authors": [
        {
            "name": "Tom Coder",
            "email": "tc@example.com",
            "role": "Developer"
        },
        {
            "name": "Sarah Mustermann",
            "email": "sm@example.com",
            "homepage": "http://example.com",
            "role": "Translator"
        }
    ]	
}
```
But using `"minVersion": "1.2", "maxVersion": "1.3"` will cause a compatibility issue with newer versions of HumHub (Example: https://github.com/GreenMeteor/humhub-freshdesk-module/issues/4) in the marketplace so for minor releases of HumHub these modules are shown as incompatible even if the module actually works, so would it be safer to use `"maxVersion": "1.3.*"` within _**module.json**_ just in case of a minor release of HumHub or is there another solution that can be used other than adding more bulk coding?

### What is the expected result?
`maxVersion` should pass the compatibility checker even if the platform's (e.g HumHub) version is set under a minor release.

### What do you get instead?
![](https://user-images.githubusercontent.com/12226710/64837957-6159e400-d5c7-11e9-96d5-13a5f1e4b1bd.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.x
| PHP version      | 5.6, 7.0, 7.1, 7.2, 7.3
| Operating system | CentOS

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Currently you need to use minVersion=1.2 and maxVersion=1.4 to only allow 1.3.x versions.

In the future, the MaxVersion can also be updated via the partner backend to prevent any future incompatibilities.

We also plan to switch to Composer SemVer to allow composer like version tags in future. 
https://github.com/humhub/humhub/issues/3656
