### ISSUE TITLE
Documentation link leads to closed area

### ISSUE THREAD

**Issue by benedetto** [humhub/humhub#3652]
The link  to the documentation pages (http://docs.humhub.org/) on the humhub website leads to a closed area (see screenshot below) instead of the documentation pages which could be found there in the past. Is this on purpose or due to some mistake?

![image](https://user-images.githubusercontent.com/2790650/64926817-79697780-d802-11e9-9601-612d6cbb67e9.png)

**Comment by ArchBlood** [comment]
Not seeing any problems like this.

**Comment by benedetto** [comment]
Ah, got it. HTTPS Everywhere (https://www.eff.org/de/https-everywhere) had forwarded the http link to the https site which is obviously the internal documentation. Manually forcing the url back to http did fix this for me.

Whether it is a good idea to have different sites behind the http and https version of the same url is a differnt question...
