### ISSUE TITLE
Hard code the 'Receive notifications for new content' for all user in all spaces.

### ISSUE THREAD

**Issue by tedstrauss** [humhub/humhub#3654]
### What steps will reproduce the problem?

Users have a binary setting in all spaces called "Receive notifications for new content". It is off by default for all users for all spaces.

### What is the expected result?

I would like to hard code (i.e. hack) the humhub source to make this setting ON by default, for all users in all spaces. As a result, users will get notifications & emails for space activity. This is what I want as admin of a small community humhub.

Can you tell me where in the code I could do that? 
Thank you.

### What do you get instead?

The setting "Receive notifications for new content" is off by default for all users for all spaces.

### Additional info

related issue: https://github.com/humhub/humhub/issues/3634

**Comment by luke-** [comment]
The email summary feature is designed for this use case. For example, it can send an summary (hourly) of all network activity to your users.

You can activate new content notifications by default for some spaces, under Administration -> Settings -> Notifications.

In general we do not recommend any hardcoded changes to the Humhub source code (e.g. updates, etc.).

Anyway to hardcode, you may can return here all spaces of the user:
https://github.com/humhub/humhub/blob/4ad0e8a7671ab04bbf5742015736d15664fbb3fb/protected/humhub/modules/notification/components/NotificationManager.php#L257
