### ISSUE TITLE
Text is not ttranslatable (and not usefull at all)

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub#3659]
Line 716 in humhub/protected/humhub/views/mail/layouts/html.php with the text

HumHub is a free social network software and framework built to give you the tools to make communication and collaboration easy and successful.
It's lightweight, powerful and comes with an user-friendly interface. With HumHub you can create your own customized social network, social intranet or huge social enterprise application that really fits your needs.
Boost your business, support your customers, teach your students or organize your football club. It's on you.

is not translatable.

Moreover, the text membership approved is translated in the message files, but not applied in the message send. 

The text  in itself is useless. The user is already signed in. Display the description of the space instead and encourage the user to make use of the space.

**Comment by ArchBlood** [comment]
https://github.com/humhub/humhub/issues/3600

**Comment by buddh4** [comment]
Duplicate
