### ISSUE TITLE
Security vulnerabilities in the email system

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3660]
1. Humhub accepts more than one email address in the post request, and sends verification emails to all of them.

This was done via Chrome DevTools.

2. Humhub has no built-in limitations for spam bots continually sending verification emails to the same address.

This was done by tinfoilsecurity.com that successfully sent over 1000 registration requests to the same email address within the span of a few minutes. 

Edit 1: (DO NOT TRY THIS ON YOUR OWN PRODUCTION SERVER. THEY NEVER STOP, EVEN AFTER YOU DELETE YOUR ACCOUNT WITH THEM)

This results in not only potential spam, but also anti-spam measures being taken against the website/mail server itself in the form of negative reputation or flagging the content of the verification email as spam or flat out blocks on outgoing mail, depending on the provider.

Edit 2: Possibly also a DDoS vulnerability since the server needs to process all the registered emails and add them to the database.

**Comment by luke-** [comment]
Please send security related issues to hello@humhub.com

**Comment by Ace2213** [comment]
Done

**Comment by ArchBlood** [comment]
@luke- maybe it would be a good idea to add a [Security policy](https://github.com/humhub/humhub/security/policy) to the repo?
