### ISSUE TITLE
Ampersand is displayed as `&amp;` in groups and emails

### ISSUE THREAD

**Issue by mroberg** [humhub/humhub#3662]
When we use an ampersand in groups it is displayed as `&amp;` .
This problem is also in notfication e-mails when an ampersand is used in the text from the stream.

At all other areas there is no problem with displaying the character correctly.

| HumHub version   | 1.3.14
| PHP version      |  7.2.22

**Comment by buddh4** [comment]
C

**Comment by MasterMindNET** [comment]
> in groups, it is displayed as `&amp;`

Where do you mean? Could you provide me with instructions, where I can find groups, please?
As a solution, 2 things come to mind.

The 1st one is it to use [str_replace()](https://www.php.net/manual/en/function.str-replace.php):
`str_replace('&amp;', '&', $text);`
We can also create an array of signs  which we would need  to convert like
```
/* @var array $singArray contains character($key) which would be replaced with its value($value) */
$singArray = [
    '&amp;' => '&', 
    '&lt;' => '<', 
    '&gt;' => '>'
];
```
The 2nd solution is to use [html_entity_decode()](https://www.php.net/manual/en/function.html-entity-decode.php)

The 2nd solution can be dangerous to use in some cases, so please let me know which solution is preferable or advice yours.


Thank you!

**Comment by luke-** [comment]
If there are still cases of the issue, we should directly post screenshots as an example. 

@MasterMindNET We should rather look for the cause of the double encoding instead of encoding back the double encoding.

**Comment by MasterMindNET** [comment]
> @MasterMindNET We should rather look for the cause of the double encoding instead of encoding back the double encoding.

I believe we can track from where to where these data is passed and then debug where the root of the issue.
