### ISSUE TITLE
oEmbed scripts are not executed when the stream is loaded a second time with pjax

### ISSUE THREAD

**Issue by GGG-KILLER** [humhub/humhub#3665]
### What steps will reproduce the problem?
1. Add the twitter oEmbed provider:
    1. Url Prefix: `twitter.com`
    1. Endpoint Url: `https://publish.twitter.com/oembed?url=%url%&omit_script=1&maxwidth=450`
1. Go to your profile
1. Make a post on your profile with a twitter post URL: `https://twitter.com/SwiftOnSecurity/status/1176331614894338052`
1. Reload the stream through pjax by clicking on the stream link: 
![image](https://user-images.githubusercontent.com/5892127/65895595-16d7b600-e382-11e9-8d70-d4a0631e6660.png)

### What is the expected result?
The oEmbed loads as usual like in the screenshot taken before reloading the stream.

### What do you get instead?
The twitter post is rendered as a `<blockquote>` and remains that way because the `<script>` associated with the oEmbed is not being executed:
![image](https://user-images.githubusercontent.com/5892127/65895731-4e466280-e382-11e9-8cf8-7585580eb7ee.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.15
| PHP version      | PHP 7.2
| Server Operating system | Ubuntu Server 16.04 LTS
| Client Operating system | Windows 10
| Browser | Google Chrome Version 77.0.3865.90

**Comment by ArchBlood** [comment]
It's not as much PJax's fault it's more of the script itself not supporting how PJax loads elements, a good example of a broken script on PJax would be Ko-fi's widget script GreenMeteor/humhub-ko_fi-module/issues/3.

**Comment by GGG-KILLER** [comment]
Perhaps we could include a compatibility layer then?

After experimenting a bit, I've found that if you use `Element.appendChild` instead of settings the `Element.innerHTML`, the scripts are executed properly.

**Comment by luke-** [comment]
@GGG-KILLER That could be the solution - can you prepare a PR with the innerHTML fix? 
@buddh4 Is there anything against using innerHTML from your side?

**Comment by GGG-KILLER** [comment]
Actually @luke-, the solution would be to make PJax stop using `innerHTML` and use `appendChild` instead. This change could have quite a bit of unexpected effects so it'll take a while to test everything but I'll check if this change fixes the issue (without breaking anything else) and report back.

**Comment by GGG-KILLER** [comment]
Ok, after digging more, it seems the issue has nothing to do with pjax after all.

It seems the way streams are loaded (and they're loaded after pjax does its job) isn't compatible with the oEmbeds that use scripts to power themselves. I believe it might not be re-executing scripts but I'll keep investigating.

**Comment by buddh4** [comment]
See https://github.com/humhub/humhub/commit/e6af969fb30513da8eb85af42faecf844e46bc4a as a workaround until v1.4 you could add the script of my previous comment e.g. under `Administration -> Advanced -> Statistics`

**Comment by GGG-KILLER** [comment]
I forgot to mention, but imgur also needs to have its scripts reloaded, so the full list would actually be:

- `https://platform.twitter.com/widgets.js`
- `//s.imgur.com/min/embed.js`

Thank you for finding a better solution @buddh4. Seems my search wasn't thorough enough.

**Comment by buddh4** [comment]
No problem, we should assemble some default urls. I've also implemented a way for modules to add such urls.

**Comment by ArchBlood** [comment]
@buddh4  you should be able to load this via your common.php no?

#### Example
```php
    'modules' => [
        'admin' => [
            'class' => 'humhub\modules\admin\Module',
                    'defaultReloadableScripts' => ['https://platform.twitter.com/widgets.js', 'Whatever_other_URL_Needed' ],
        ],
],
```

**Comment by buddh4** [comment]
In 1.4

```
 'modules' => [
        'admin' => [
                    'defaultReloadableScripts' => ['https://platform.twitter.com/widgets.js', 'Whatever_other_URL_Needed' ]
        ]
```

But you can also define those under `Administration -> Settings -> Advanced -> Cache`, which is better since you don't overwrite the defaults.

**Comment by ArchBlood** [comment]
@buddh4 would seem that this doesn't work on a menu to widget level maybe for the next beta? :thinking:

E.g: [Example](http://community.greenmeteor.pcriot.com/dashboard) click dashboard to reload and it doesn't work.

**Comment by buddh4** [comment]
I think you have another problem, besides other javascript error logs i see:

![grafik](https://user-images.githubusercontent.com/9800854/67272576-1af87e80-f4bd-11e9-926d-b46c11f0b293.png)

**Comment by ArchBlood** [comment]
We're still working on fixing those manually :sweat_smile:

We have something new that we're still working on implementing into the Patreon module but you're right a lot of JavaScript errors after updating to 1.4-beta.1 looks like we're going to need a lot more finetuning on our end of things :thinking:
