### ISSUE TITLE
post per page setting

### ISSUE THREAD

**Issue by andreakru** [humhub/humhub#367]
Hi

post per page setting seem not work, I try change to 20

I suppose that this is how much post load on dashboard/space/user profile, right?

**Comment by vipul1994** [comment]
I have changed the value of above mentioned variable but the stream still shows only 4posts at a time.

**Comment by vipul1994** [comment]
Resolved after changing the values in 
humhub/humhub/protected/humhub/modules/content/components/actions/Stream.php

Thanks.
