### ISSUE TITLE
Links to an UNC path are not rendered correctly

### ISSUE THREAD

**Issue by marco-bertschi** [humhub/humhub#3675]
**What steps will reproduce the problem?**

Post a link in a comment to a UNC share, for example

[ Test ] (file://///storage/My/Unc/Path)

It will render as

> &#x3C; a href="file://///storage/My/Unc/Path" target="_blank" rel="noopener noreferrer"&#x3E;Test

### What is the expected result?

Link correctly rendered

### What do you get instead?
> &#x3C; a href="file://///storage/My/Unc/Path" target="_blank" rel="noopener noreferrer"&#x3E;Test

**Comment by marco-bertschi** [comment]
- HumHub 1.2.8
    - PHP 7
    - OS: alpine:3.7

**Comment by luke-** [comment]
There is a missing "a" in the link tag?

**Comment by marco-bertschi** [comment]
No, sorry  -  That was me struggling to put HTML into here. Corrected it.

Another example:

> [ Link ] (\\storage\SQLBackups\Integration)

Gives me

> &#x3C; a href="\storage\SQLBackups\Integration" target="_blank" rel="noopener noreferrer"&#x3E;Link

**Comment by luke-** [comment]
Hmm, can still reproduce this. 

Can you give me steps to reproduce?

**Comment by marco-bertschi** [comment]
Add link
![grafik](https://user-images.githubusercontent.com/25186516/66919025-db471800-f020-11e9-8bbf-6335fdd80ae5.png)


Rendered as HTML:
![grafik](https://user-images.githubusercontent.com/25186516/66919008-cff3ec80-f020-11e9-9b07-35189852715d.png)

**Comment by luke-** [comment]
Seems this is a bug with the old markdown editor which was replace since HumHub 1.3.
Can you try to update to the latest Humhub version?

**Comment by marco-bertschi** [comment]
Okay. We had this discussion elsewhere already, a non-markdown editor isn't an option for us.

**Comment by luke-** [comment]
Ah ok, I remember the topic. Unfortunately, we currently have not enough resources to address the topic of exchangeable editors.

**Comment by marco-bertschi** [comment]
Yeah, was a part of #3594 - That's sad. How much effort would this be, anyways? Is it the replacing of the editor that is an issue or needing to maintain more than one editor?
