### ISSUE TITLE
The requested URL /file/medias/upload was not found on this server.

### ISSUE THREAD

**Issue by wdevlop** [humhub/humhub#3683]
Need help in changing the upload url 
I’m trying to change the url for uploading file

so I did

```
/** * Can be set to overwrite the default file upload route. * * @var type */ 

public $url = '/file/medias/upload';
```

but I get error

The requested URL /file/medias/upload was not found on this server.

I have created controller in : file/controllers/MediasControllers 

I don’t know where is the error

I tried :

`public $url = \yii\helpers\Url::to(['/file/medias/upload']);
`
but i get : Constant expression contains invalid operations

**Comment by luke-** [comment]
Pleae use our community for questions and help
