### ISSUE TITLE
User profile field type selection not hidden

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#3687]
### What steps will reproduce the problem?

Changing field types of user profile fields

### What is the expected result?

No dropdown if the change is not possible

### What do you get instead?

Possibility to change the field type and error message

### Additional info

| HumHub version   | 1.3.15

**Comment by Ace2213** [comment]
Are you referring to the fields that can't be removed? If so, I agree.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4817
