### ISSUE TITLE
Wrong Calendar Time

### ISSUE THREAD

**Issue by fsainovich** [humhub/humhub#3691]
When add a new calendar item after certain date, humhub save with +1 hour. 

This year my country dont have daylight time. Dont find configuration for this.

![image](https://user-images.githubusercontent.com/27427085/67006455-90c6a980-f0bb-11e9-9902-b5a9cf4ee03d.png)

![image](https://user-images.githubusercontent.com/27427085/67006477-a045f280-f0bb-11e9-80f6-6baafc501422.png)

**Comment by luke-** [comment]
Please use the calendar repo to post issues.
