### ISSUE TITLE
Icon Upload Problems

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#3692]
### What steps will reproduce the problem?
Install HumHub 1.4-beta.1 try to upload any image file type and it will not save and ico file type is shown as not supported.

### What is the expected result?
- First, the Icon Upload should support ico file types by default but doesn't.
- Second, when uploading (any file size or image file extension) it should auto-scale to fit it's intended use and then save.

### Additional info
![Screenshot_1](https://user-images.githubusercontent.com/35392110/67052036-faba6f80-f10a-11e9-8f4b-a3881a1ed632.png)
![Screenshot_2](https://user-images.githubusercontent.com/35392110/67052039-fdb56000-f10a-11e9-9fdc-65ffed834c9d.png)
![Screenshot_3](https://user-images.githubusercontent.com/35392110/67051861-589a8780-f10a-11e9-8f30-ddbd6bdd728c.png)
![Screenshot_4](https://user-images.githubusercontent.com/35392110/67051924-9a2b3280-f10a-11e9-9517-e6c6af92a7e3.png)

| Q                | A
| ---------------- | ---
| HumHub version   |  1.4.0-beta.1
| PHP version      | 7.2
| Operating system | CloudLinux (CentOS 6)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Should be fixed in beta.2

Unfortunately we cannot support ICO file types as these are not provide high quality.
