### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ryusei-koseki** [humhub/humhub#3693]
### What steps will reproduce the problem?
The installation will attempt to create a database.

### What is the expected result?
Proceed to the next step after successfully creating the database.

### What do you get instead?
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'humhub.contentcontainer' doesn't exist
The SQL being executed was: UPDATE `content` SET `contentcontainer_id`=(SELECT id FROM contentcontainer WHERE class='humhub\\modules\\space\\models\\Space' AND pk=space_id) WHERE `space_id` IS NOT NULL

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.17
| PHP version      |  7.2.20
| Operating system | windows7

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Did you created the database as described here?
http://docs.humhub.org/admin-installation.html#database-setup

**Comment by ryusei-koseki** [comment]
yes.It has already been solved.
