### ISSUE TITLE
PWA App Install Banner stops working

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#3695]
### What steps will reproduce the problem?
Once you first load up a HumHub instance (any at all) that are using v1.4, instead of installing, reload the page and the option disappears from use and doesn't reappear.

### What is the expected result?
Once you visit the HumHub instance the install banner should appear in the search bar as it did on the first load of the HumHub instance.

### What do you get instead?
The app install banner doesn't show up on reload nor after clearing browser cache of the selected HumHub instance, even on the community site, this happens.

### Additional info
I found this mentioning of what is happening for me exactly
https://developers.google.com/web/fundamentals/app-install-banners/

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4-beta.1
| PHP version      | 7.1, 7.2, 7.3
| Operating system | CentOS and etc

**Comment by ArchBlood** [comment]
Seems to have been fixed in later updates.

**Comment by luke-** [comment]
Thanks for the update!
