### ISSUE TITLE
Guide for moving a HumHub installation to another server

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3696]
Add documentation/guide about how moving an existing HumHub installation to a new server.

**Comment by Ace2213** [comment]
I've done this several times by backing up the entire Humhub folder and the database, and then restoring both on the new server, after installing all the pre-requisites.

If this method is correct, can I write the guide? I should point out that my experience is limited to CentOS.

**Comment by buddh4** [comment]
Of course, feel free to start this documentation part, perhaps @luke- can review and may add some parts.

**Comment by Ace2213** [comment]
[Here](https://docs.google.com/document/d/1dOh28borOwjqffVgZ7IdKtnQHP6iIqEOjFE-iwyAFcU/edit?usp=sharing)

**Comment by buddh4** [comment]
@luke- can you have a look?

**Comment by luke-** [comment]
Looks very good, we should integrate that as soon as we have our own docs repo.

**Comment by spoorun** [comment]
What's the link in the docs for this?
(Had a look but wasn't apparent, sorry if I missed it!)
