### ISSUE TITLE
Amiguous attribute in WHERE-clause (@-search for users in comment)

### ISSUE THREAD

**Issue by thoerb** [humhub/humhub#3700]
We have a problem with the '@...' search. When we search for users via e.g. "@tho" the JS crashes and there's the error message seen in the attachment given in the error log in HumHub. The email field is ambiguous because it's given two times in the WHERE-clause. When you delete the second email attribute, the query is ok.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.0-beta.1 (same with stable version)
| PHP version    7.1  | 
| Operating system Debian |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by buddh4** [comment]
I don't see any attachment or error log.
