### ISSUE TITLE
Mentioning leak 

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#3701]
### What steps will reproduce the problem?

Mention someone in private content who is not a Space member

### What is the expected result?

Mentioned user does not get access to the content

### What do you get instead?

The mentioned user gets access to the private content

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.15

**Comment by buddh4** [comment]
Could not recreate this. 
Tested with private space ->No notification was sent to mentioned space member and no access to post.
Tested with public space and private content -> No notification was sent, user could access stream but did not see the post
Tested with public space and public content -> Notification was sent, user could access post
