### ISSUE TITLE
Public space is not displayed when guest user accesses "Space directory".

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#3704]
### What steps will reproduce the problem?

1. Administration -> Users-> Settings -> General -> Enable "Allow limited access for non-authenticated users (guests)"

1. Create a public space (VISIBILITY_ALL) that guests and registered users can access.

1. Access "Space directory" as a guest user. (Directory -> Spaces)

### What is the expected result?
Public space is displayed.
### What do you get instead?
Public space is not displayed.
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.0-beta.1
| PHP version      | 7.1

**Comment by buddh4** [comment]
Could not reproduce this issue, you probably have to rebuild the search index. http://docs.humhub.org/admin-search.html#index-rebuilding

**Comment by sakurafarm** [comment]
The search index was rebuilt, but public space is not visible to guest users.

It is displayed without problems for the logged-in user.

It may be a wrong fix, but if I set the `space.visibility` of [ActiveQuerySpace.php (Line56)](https://github.com/humhub/humhub/blob/1e166bc849d613557042c5304e0312b2b0a8936d/protected/humhub/modules/space/components/ActiveQuerySpace.php#L56) to 2, it will be displayed correctly even for guest users.

**Comment by buddh4** [comment]
Yes there is a public visibility (members only) and a public visibility (members and guests) this can be changed in the space security settigns

**Comment by sakurafarm** [comment]
@buddh4 
It was not displayed even in 1.4.0-beta.2.
![2019-12-18_10h26_57](https://user-images.githubusercontent.com/38252517/71048395-86d82a00-2182-11ea-9e51-0d570b62bfc9.png)

**Comment by buddh4** [comment]
@luke- , I can only imagin a search index issue? Any idea?

**Comment by sakurafarm** [comment]
@buddh4 
I noticed that public spaces(members and guests)  where the logged-in user is not a member are not displayed in the space directory.

![2019-12-19_09h33_15](https://user-images.githubusercontent.com/38252517/71135262-99b33300-2244-11ea-8026-b4cec78314f5.png)

I think the cause is the [humhub\modules\space\components\ActiveQuerySpace visible ()](https://github.com/humhub/humhub/blob/d73ffac9c24ac0ed24e90fae9e55f4351f0cbe27/protected/humhub/modules/space/components/ActiveQuerySpace.php#L35).

**Comment by buddh4** [comment]
@luke- there is space visibility_all missing in the visibility query: https://github.com/humhub/humhub/blob/d73ffac9c24ac0ed24e90fae9e55f4351f0cbe27/protected/humhub/modules/space/components/ActiveQuerySpace.php#L52 ?

**Comment by sakurafarm** [comment]
@luke- 0ffed46332e24d2fe991d511ed3084a779cd42d1 is not compatible with Humhub1.3 for displaying results.

In Humhub 1.3, the space `VISIBILITY_REGISTERED_ONLY` and `VISIBILITY_ALL` will be displayed to guest users. I think this specification is desirable.

Is it possible to include both `VISIBILITY_REGISTERED_ONLY` and `VISIBILITY_ALL `in the search condition when a guest user?

**Comment by ArchBlood** [comment]
I believe you'd have to use something like this

#### Not tested
```php
            }, Membership::findAll(['user_id' => $user->id]));
            $this->andWhere(['OR',
                ['space.visibility' => 1],
                ['!=', 'space.visibility', Space::VISIBILITY_REGISTERED_ONLY && Space::VISIBILITY_ALL],
                ['IN', 'space.id', $spaceIds]
            ]);
        } else {
            $this->andWhere(['space.visibility' => 1]);
            $this->andWhere(['space.visibility' => Space::VISIBILITY_REGISTERED_ONLY && Space::VISIBILITY_ALL]);
        }
        return $this;
    }
```

**Comment by buddh4** [comment]
Should this be configurable, I'am not sure if its obvious that VISIBILITY_REGISTERED_ONLY spaces are visible for guests in the directory. But I see that this can be desirable in some cases.

**Comment by buddh4** [comment]
@luke- what do you think?
