### ISSUE TITLE
When the guest user accesses the public space, the space setting menu button is displayed.

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#3705]
### What steps will reproduce the problem?
1. Administration -> Users-> Settings -> General -> Enable "Allow limited access for non-authenticated users (guests)"

1. Create a public space (VISIBILITY_ALL) that guests and registered users can access.

1. Access the public space as a guest user.

### What is the expected result?
The settings menu button should not be displayed when the guest user accesses the space.
### What do you get instead?
The space setting menu button is displayed. (Menu is empty)
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.0-beta.1
| PHP version      | 7.1

**Comment by buddh4** [comment]
Can't reproduce this for me it looks like this:

![grafik](https://user-images.githubusercontent.com/9800854/67783552-b021e700-fa6a-11e9-80b7-d67fc84b8dc8.png)

**Comment by sakurafarm** [comment]
No, I use the default theme.
When I click the settings button, an empty menu is displayed.
![2019-10-30_10h43_06](https://user-images.githubusercontent.com/38252517/67821934-19086e00-fb02-11e9-9543-62925c2cb974.png)

The beta version was downloaded from https://www.humhub.org and installed. The theme also uses the default.
