### ISSUE TITLE
A space mention cannot be entered.

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#3706]
After updating to 1.4.0-beta.1, I can't enter mentions for spaces.
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.0-beta.1
| PHP version      | 7.1

**Comment by buddh4** [comment]
Did you try rebuilding the search index: http://docs.humhub.org/admin-search.html#index-rebuilding

**Comment by sakurafarm** [comment]
The search index was rebuilt but the results were the same.

I can't enter the space mention (@ + space name) on the Humhub community site. Is there anything related to it?

For now, I will wait for the official release of version 1.4.

**Comment by st5000** [comment]
I confirm this issue with HH 1.4.beta1
