### ISSUE TITLE
LDAP Simple Paged Results

### ISSUE THREAD

**Issue by ThomasKaule** [humhub/humhub#3707]
### What steps will reproduce the problem?

appears periodically in the log file:

2019-10-29 10:56:03 [-][-][-][error][ldap] Could not connect to LDAP instance: 0
xc (Critical extension is unavailable; The server is not configured to pass thro
ugh control 1.2.840.113556.1.4.319): searching: (&(objectclass=posixAccount)(!(n
sAccountLock=true))(|(o=...)))
    in /var/www/humhub/protected/humhub/modules/ldap/authclient/LdapAuth.php:522
    in /var/www/humhub/protected/humhub/modules/user/jobs/SyncUsers.php:37
    in /var/www/humhub/protected/humhub/modules/queue/ActiveJob.php:33

### What is the expected result?

Our LDAP Server (Oracle) doesn't support this control. Since it is optional you just shouldn't use it instead of sening an error message

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.17
| PHP version      |  7.2.10
| Operating system | CentOS 7

It firts occurred in the logs October 8th. After upgrading to 1.3.17

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Fixed in 1.5 

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/ldap/Module.php#L22-L25
