### ISSUE TITLE
1.4 beta causes a focus for input on ios mobile.

### ISSUE THREAD

**Issue by KnaiKnia** [humhub/humhub#3711]
The 1.4 beta causes a focus for input on mobile. With the new scrolling navigation bar that replaces the “tabs”, you can’t get the mobile browser to focus on the text input box. It accepts the input, but its hidden under a layer. Tried on IOS both Chrome and Safari.

![IMG_9746](https://user-images.githubusercontent.com/57151945/67798246-231e6400-fa51-11e9-9262-e8a8f2abb1fa.PNG)
![IMG_9747](https://user-images.githubusercontent.com/57151945/67798248-231e6400-fa51-11e9-8544-4caa7ca37c39.PNG)

Any help on this is appreciated.

**Comment by Twilek-de** [comment]
Seeing that as well using Ios 13.3 beta and safari on community.humhub.com and my own installation.

**Comment by geekaroni** [comment]
Sorry I just made a new issue for this. Will this be fixed? It's been nearly a month and no dev response. Thank you!
