### ISSUE TITLE
Remove auto extended richtext on mobile (1.4)

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3712]
See https://community.humhub.com/content/perma?id=201995

**Comment by Ace2213** [comment]
Or add a floating submit button in the bottom right corner above the keyboard? Or bring back "enter to submit" functionality.

As long as the back button closes it, that should be good enough.

**Comment by buddh4** [comment]
In the beta you can submit by `ctrl + s`.

**Comment by Ace2213** [comment]
That's great, but doesn't help on mobile devices. Personally, I want to enable enter to submit for my installation. That would be a workaround for this bug.

For everyone else, I think floating buttons for submit and upload files would be the best approach. Or just disabling it.

**Comment by Ace2213** [comment]
@buddh4 how do I apply that commit to my installation? I can't find index.js

**Comment by buddh4** [comment]
I'll have to release the new humhub-prosemirror version first, this will be part of the beta2, which will be available soon.
