### ISSUE TITLE
Help with custom SSO provider (Auth0)

### ISSUE THREAD

**Issue by Saibot6** [humhub/humhub#3726]
Hi there!

I'm using Humhub for some time now and I still love it. But since I use multiple webapps that all include oauth authentication I decided to start using Auth0. I've written a new SSO provider for Humhub but I can't figure out why I'm getting a error. The authentication succeeds on the Auth0 side so it's the local Humhub where the error is. The error is:

`yii\base\ErrorException: Undefined index: user_id in /var/www/html/protected/humhub/modules/user/authclient/Auth0.php:32`

So I've done some investigation and came to the conclusion that there should be in the request fom Auth0 a variable 'user_id'. On their website it notes (https://auth0.com/docs/users/normalized/auth0/normalized-user-profile-schema) that there is in every request a variable 'user_id'. But still Humhub won't catch the variable. 

The SSO client I've written for Humhub is:

```
<?php

namespace humhub\modules\user\authclient;

use yii\authclient\OAuth2;

class Auth0 extends OAuth2
{
    public $authUrl = 'https://NAME.eu.auth0.com/authorize';

    public $tokenUrl = 'https://NAME.eu.auth0.com/oauth/token';

    public $apiBaseUrl = 'https://NAME.eu.auth0.com/userinfo';

    public $attributeNames = [
        'user_id',
        'username',
        'first_name',
        'last_name',
    ];

    protected function defaultNormalizeUserAttributeMap()
    {
        return [
            'user_id' => function ($attributes) {
                return $attributes['user_id'];
            },
            'username' => 'name',
            'firstname' => 'given_name',
           },
            'lastname' => 'family_name',
            },
            'email' => 'email',
                },
        ];
    }
    protected function initUserAttributes()
    {
        return $this->api('userinfo', 'GET');
    }

}
```

So can someone please help me with the issue? I already tried several times changing the 'id' to other variables but they won't work...

Thanks in advance!

**Comment by ArchBlood** [comment]
You didn't add `email` to your `$attributeNames`, and normally you'd use `id` not `user_id`. :thinking:

**Comment by Saibot6** [comment]
Thanks for your response! I've changed the variables and added them to the SSO provider. Unfortunately it gives me the same error...

**Comment by ArchBlood** [comment]
Just tested this and it looks to be working for me.

### Main Auth Code
```php
<?php

namespace humhub\modules\user\authclient;

use yii\authclient\OAuth2;

class Auth0 extends OAuth2
{
    public $authUrl = 'https://NAME.auth0.com/authorize';

    public $tokenUrl = 'https://NAME.auth0.com/oauth/token';

    public $apiBaseUrl = 'https://NAME.auth0.com/api/';

    public $attributeNames = [
        'id',
        'username',
        'first_name',
        'last_name',
        'email',
        
    ];

    protected function defaultNormalizeUserAttributeMap()
    {
        return [
            'id' => function ($attributes) {
                return $attributes['id'];
            },
            'username' => 'name',
            'firstname' => 'given_name',
            'lastname' => 'family_name',
            'email' => 'email',

        ];
    }
    protected function initUserAttributes()
    {
        return $this->api('v2/userinfo', 'GET');
    }

    /**
     * @inheritdoc
     */
    protected function defaultName()
    {
        return 'auth0';
    }

    /**
     * @inheritdoc
     */
    protected function defaultTitle()
    {
        return 'Auth0';
    }

    /**
     * @inheritdoc
     */
    protected function defaultViewOptions()
    {
        return [
            'popupWidth' => 860,
            'popupHeight' => 480,
            'cssIcon' => 'fa fa-sign-in',
            'buttonBackgroundColor' => '#395697',
        ];
    }

}
```
### Common File Code
```php
                'auth0' => [
                    'class' => 'humhub\modules\user\authclient\Auth0',
                    'clientId' => 'CLIENT_ID',
                    'clientSecret' => 'CLIENT_SECRET',
                    'returnUrl' => 'https://YOUR-DOMAIN.com/user/auth/external?authclient=auth0',
                ],
```

**Comment by Saibot6** [comment]
Hi thank you so much for your code! 
I've tested it and it gives me this error:

`yii\authclient\InvalidResponseException: Request failed with code: 404, message: {"statusCode":404,"error":"Not Found","message":"Not Found"} in /var/www/html/protected/vendor/yiisoft/yii2-authclient/src/BaseOAuth.php:233`

When I change the lines:

`    public $apiBaseUrl = 'https://name.eu.auth0.com/api/';`

and,

`        return $this->api('v2/userinfo', 'GET');`

To:

`    public $apiBaseUrl = 'https://name.eu.auth0.com/';`

and,

`        return $this->api('/userinfo', 'GET');`

I'll get this error:

`yii\base\ErrorException: Undefined index: id in /var/www/html/protected/humhub/modules/user/authclient/Auth0.php:28`

So I don't get why it gives me those errors...
Auth0 gives me those endpoints from their website:
![Schermafbeelding 2019-11-07 om 16 31 40](https://user-images.githubusercontent.com/57457935/68402922-67f67900-017c-11ea-99a4-b5d257cc9052.png)

**Comment by ArchBlood** [comment]
Did you create an API identifier? Should be under the APIs tab.
![Screenshot_1](https://user-images.githubusercontent.com/35392110/68403670-4fba3600-014b-11ea-8783-530c6e202478.png)

**Comment by Saibot6** [comment]
Yess for the Auth0 Management API right?
I also allowed Humhub all the permissions that are available.

**Comment by ArchBlood** [comment]
The API url given from that tab is the one you use for `public $apiBaseUrl = '',` otherwise it won't work.

**Comment by Saibot6** [comment]
Thanks! It's weird because when I navigate to that url it would say (from a normal browser) unauthorized but it says "404 not found". 
![Schermafbeelding 2019-11-07 om 16 59 50](https://user-images.githubusercontent.com/57457935/68405651-c6bdf180-0180-11ea-8321-39fc002713a5.png)

**Comment by ArchBlood** [comment]
Make sure that you set Allowed Callback URLs (Example: `https://YOUR-DOMAIN.com/user/auth/external?authclient=auth0`), Application Login URI (Example: `https://YOUR-DOMAIN.com/user/auth/login`), & Allowed Logout URLs (Example: `https://YOUR-DOMAIN.com/user/auth/logout`) as well and your `returnUrl` from your common file must be set to the same URL as your callback URL or you'll get an error.

**Comment by Saibot6** [comment]
Thanks! I've checked them triple and they all checkt out...

**Comment by kaonsa** [comment]
> Thanks! I've checked them triple and they all checkt out...

I think you need to remove **/api** from  `$apiBaseUrl`, it should be the bare domain

**Comment by ArchBlood** [comment]
> > Thanks! I've checked them triple and they all checked out...
> 
> I think you need to remove **/api** from `$apiBaseUrl`, it should be the bare domain

Removing `/api` wouldn't help because you must be calling the exact API domain if you don't then you'll get a malformed url similar to how you'd get one for WordPress.

**Comment by Saibot6** [comment]
When I remove the `/api` I get this error:

`yii\base\ErrorException: Undefined index: id in /var/www/html/protected/humhub/modules/user/authclient/Auth0.php:42`

And with the `/api` I get this error:

`yii\authclient\InvalidResponseException: Request failed with code: 404, message: {"statusCode":404,"error":"Not Found","message":"Not Found"} in /var/www/html/protected/vendor/yiisoft/yii2-authclient/src/BaseOAuth.php:233`

**Comment by marcelaopimenta** [comment]
@Saibot6 Were you able to implement? I managed to authenticate myself, but it does not redirect, it is always on the login screen.

**Comment by Saibot6** [comment]
> @Saibot6 Were you able to implement? I managed to authenticate myself, but it does not redirect, it is always on the login screen.
> 
> I have the same problem...
> 
> yii\base\ErrorException: Undefined index: id in /var/www/html/protected/humhub/modules/user/authclient/Auth0.php:42

Unfortunately I did not proceed with the project, but I still can authenticate myself but I will not get any redirects to Humhub..

**Comment by marcelaopimenta** [comment]
@Saibot6 How to resolve this problem?

yii\base\ErrorException: Undefined index: id in /var/www/html/protected/humhub/modules/user/authclient/Auth0.php:42

**Comment by ArchBlood** [comment]
> @Saibot6 How to resolve this problem?
> 
> yii\base\ErrorException: Undefined index: id in /var/www/html/protected/humhub/modules/user/authclient/Auth0.php:42

I believe this is related to #4355 in some way?
