### ISSUE TITLE
Update nicescroll version to 3.7.*

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3730]
Update nicescroll to latest 3.7.

> Note: We did stick to 3.6 since there were some issues with early 3.7 version. see https://github.com/inuyaksa/jquery.nicescroll/issues/664

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/3983

**Comment by buddh4** [comment]
We should skip the update. Tried to update not long ago, but there were strange issues on mobile.

**Comment by luke-** [comment]
@sahartak2025 ok, let skip the update
@buddh4 Should we close this issue?

**Comment by buddh4** [comment]
Yes, we rather need to replace the library in the future.
