### ISSUE TITLE
Open profile counter in new tab

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3733]
When opening a profile counter e.g. user spaces in a new tab, the space list modal opens in a new tab without any other layout.

**Comment by luke-** [comment]
We should find a way to ensure that Ajax Actions are not called directly. There must be a header or request type that we can use to identify this.

An action filter / middleware or similar would be good here. 

If such a method is called directly, a definable URL should be called (if not specified dashboard) and a status message should appear (The specified URL cannot be called directly).

**Comment by buddh4** [comment]
Also we should use buttons or links without href attribute in such cases in order to disable the option in the browser.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4814

**Comment by buddh4** [comment]
Can we add some documentation for this when and how to use it (at least in the migration guide). I assume no one will think of using this access rule and the `open in new tab` issue when implementing a new feature otherwise.
