### ISSUE TITLE
Request: Theme store

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3736]
As mentioned in #654, 

> most "questions" regarding HumHub are how to theme it.

And the enterprise edition theming is also very basic. So why not set up a theme store like the module marketplace?

This way you would:
1. Advertise the power, flexibility and capability of Humhub
2. Provide examples of what can be done with it and how drastically it can be changed
3. Provide one or two basic free themes as "teasers"
4. Provide an opportunity for developers to sell their own themes
5. Also sell widgets/scripts that make more sense as themes than modules (eg Dark Mode)
6. Provide a "demo" link where people can try the theme
7. Make money by charging a percentage
8. Let developers make money by keeping the rest of the money
9. Incentivize the community to collaborate and share their work
10. Once they pay, all you have to do is show the code with instructions on adding it to view files

**Comment by luke-** [comment]
In principle, this should already be possible with the current marketplace.

Marketplace categories are also introduced with 1.4. Here we can create a own "Themes" category as soon as there are enough theme modules available.

We are also more and more opening the marketplace for third party developers/designers.

**Comment by Ace2213** [comment]
I think themes are fundamentally different from modules because of the way they are installed. In most cases they require manually copying view files or stylesheets, which I don't think would be possible to automate with a one click install without affecting the existing installation.

**Comment by luke-** [comment]
A (marketplace) module can already provide an own "themes" folder with all required files (views, assets, stylesheets). The file copying etc. is also automatically handled by HumHub.

This works already fine with the Enterprise edition theme.
