### ISSUE TITLE
No user icon bottom padding

### ISSUE THREAD

**Issue by st5000** [humhub/humhub#3741]
Users icons list displayed in groups or New members module is not padded at bottom.

![Screen Shot 2019-11-16 at 13 36 23](https://user-images.githubusercontent.com/57590912/68993263-5432cd00-0876-11ea-9ba6-48dbf6f27857.png)

**Comment by luke-** [comment]
Can you please provide a better screenshot?
Can you reproduce this on our community?

**Comment by st5000** [comment]
Same behavior on community site. Here's the screenshots:

![Screenshot_2019-11-23 Annuaire - HumHub Community](https://user-images.githubusercontent.com/57590912/69485122-60e98f00-0e3b-11ea-918e-d993fefe7ac7.png)

![Screenshot_2019-11-23 Membres - Annuaire - HumHub Community](https://user-images.githubusercontent.com/57590912/69485139-8d051000-0e3b-11ea-8906-e476778a1b82.png)

**Comment by buddh4** [comment]
Seems to be fixed by https://github.com/humhub/humhub/commit/f00927c38547188127e7654bbff946a83bd74461 the actual user link was missing.
