### ISSUE TITLE
OAuth timeout doesn't respect configured timeout

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3742]
### What steps will reproduce the problem?
Using OAuth
### What is the expected result?
For the session to last for the duration configured in settings
### What do you get instead?
When authenticated via OAuth, the session expires much more quickly.
### Additional info
Similar to #3253 but it doesn't require closing the tab. The session expires even with the tab open, which is a bigger issue.

#3486 would be a nice workaround, but not a real fix.

I couldn't find any related directives in /user/authclient or AuthController but that's probably where it needs to be configured.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4 beta
| PHP version      | 7.3.11
| Operating system | CentOS 7

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
This is probably because no OAuth that has been created uses the Session component that HumHub provides in its core user module.

**Comment by Ace2213** [comment]
Well how can we get them to speak to each other?
