### ISSUE TITLE
Snipped-Layouts does not work in HH 1.4.0-beta

### ISSUE THREAD

**Issue by wantprikol** [humhub/humhub#3743]
Hello, help with the right column issue in HH 1.4.0-beta. Does not show elements such as groups from social networks that are added with js code. Although in 1.3.18 everything worked. The script in the browser simply hides and finds nothing.
https://ibb.co/vs4CXbF
Here is the group code from classmates
```
<div id="ok_group_widget"></div>
<script>
!function (d, id, did, st) {
  var js = d.createElement("script");
  js.src = "https://connect.ok.ru/connect.js";
  js.onload = js.onreadystatechange = function () {
  if (!this.readyState || this.readyState == "loaded" || this.readyState == "complete") {
    if (!this.executed) {
      this.executed = true;
      setTimeout(function () {
        OK.CONNECT.insertGroupWidget(id,did,st);
      }, 0);
    }
  }};
  d.documentElement.appendChild(js);
}(document,"ok_group_widget","59031977721913",'{"width":240,"height":230}');
</script>
```
https://ibb.co/sCNpkhs
It seems to force js script to be hidden

**Comment by luke-** [comment]
Seems to be related to the new CSP security headers.

@buddh4 How to deal with such scripts?

**Comment by buddh4** [comment]
Are there any csp errors in the developer browser console?
