### ISSUE TITLE
TypeError: Argument 1 passed to humhub\modules\friendship\models\Friendship::getFriendsQuery() must be an instance of humhub\modules\user\models\User, null given, called in

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3744]
I've disabled the UserListBox widgets and their modals on the counters for privacy reasons. i.e Friends, Member of Spaces, Followers, Following , Space members and space followers. I addressed this in issue #3720 

I've been trying to recreate them so they can be optional per user and per space, and also to be controlled via permissions (in terms of who can view them). For spaces, this was easy. For user profiles, it's been nothing but trouble.

When I wasn't able to recreate the Friend panel, I decided to simply call the official one via module. And I got the same error. So the problem is with the user system.

I've tried to reference the user using $user, $this->user, $contentContainer, $this->contentContainer and $this->context->contentContainer and they all eventually fail, saying they're undefined or null.

This is my Events.php
![image](https://user-images.githubusercontent.com/12226710/69109243-e80ebf80-0a55-11ea-9044-585f10fc8075.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4 beta
| PHP version      |  7.3.11
| Operating system | CentOS 7

**Comment by ArchBlood** [comment]
Are you not extending the existing model in a new module model, and why are you using the `as ProfileSidebar` entry? It's useless if you name it the same thing as what it's already called, only use this if you're using two entries of the same name when using the `Sidebar::class`. :sweat_smile: 

### Example
```php
use /humhub/modules/space/widget/Sidebar as SpaceSidebar;
```
or
```php
use /humhub/modules/user/widget/Sidebar as UserSidebar;
```

You should also be able to extend the existing Events.php from your module with this method. :thinking: 

### Example

```php
<?php

use \humhub\modules\friendship\Events as FriendshipEvents;

class Events extends FriendshipEvents`

**Comment by Ace2213** [comment]
You mean like this? No result and no errors.

![image](https://user-images.githubusercontent.com/12226710/69139139-abb38180-0a9e-11ea-9c18-3e23086d3be5.png)

**Comment by Ace2213** [comment]
It's not just this case. Every time I try to do anything using the user model it doesn't work. Especially permissions.

**Comment by Ace2213** [comment]
There's clearly something broken with the user model in 1.4. Even integrity run throws an error, as pointed out in #3729 

![image](https://user-images.githubusercontent.com/12226710/69194577-354b6980-0b08-11ea-8df8-ea86d390dd43.png)

**Comment by luke-** [comment]
#3729 was related to some removed deprecated methods
http://docs.humhub.org/dev-modules-migrate.html#removed-deprecated-methods

Can you reproduce your problem also with the standard friends panel?

**Comment by Ace2213** [comment]
Well, I tried to re-enable the standard friends panel by uncommenting the lines in the profile view but now it won't appear. I did too good of a job hiding it 😆

It does appear correctly using the default theme though.
