### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by larigyn** [humhub/humhub#3746]
hello,

I tried reaching out in the community but no one dares to answer my question. I have cloned the laters version of humhub, later I explore the application and found out some problems. Please correct me If I'm wrong. When I tried to run this ( **./yii migrate/fresh** ) inside the protected folder it shows an error 
**Yii Migration Tool (based on Yii v2.0.15)

YII_ENV is set to 'prod'.
Refreshing migrations is not possible on production systems.**

When I tried to check the index.php I saw this as a config 
**defined('YII_DEBUG') or define('YII_DEBUG', FALSE);
defined('YII_ENV') or define('YII_ENV', 'dev');**

I also tried to read the documentations written here
**http://docs.humhub.org/dev-build.html#build-assets**

I need help with this. Since the community is not responding. Thanks

**Comment by ArchBlood** [comment]
Not sure all Yii commands are supported by default, namely the ones that deal with the database entries. :thinking:

**Comment by luke-** [comment]
Sorry, please use our community for such questions.
