### ISSUE TITLE
I want the content posted in HumHub to be in Japanese

### ISSUE THREAD

**Issue by saur099** [humhub/humhub#3748]
If you have a question or problem about HumHub that is not a bug report or feature
request, please post it in https://community.humhub.com!

Questions posted to this repository will be closed.
Hii I am getting issue in posting a japanese language post and creating a menu which will show every non-registered users as post. Please guide me. 

I did change the language from settings in Administration but after that all posts i am posting in any space becomes question mark or dont accept. I want it to be completely working in Japanese language.

Please guide me.

**Comment by ArchBlood** [comment]
Is your database using `utf8mb4` with `utf8mb4_unicode_ci` collation? If not then that's your problem.
