### ISSUE TITLE
Make richtext editor more user-friendly

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3751]
### Is your feature request related to a problem? Please describe.
Most users aren't familiar with markdown syntax or how to pull up the emoji panel.
### Describe the solution you'd like
Emoji button in the prosemirror menu and a pop-up showing a markdown cheat sheet, like this example from [hashover](https://github.com/jacobwb/hashover):

Collapsed:
![image](https://user-images.githubusercontent.com/12226710/69445537-4aefa780-0d31-11ea-9e4c-54d3da3195bf.png)

Expanded:
![image](https://user-images.githubusercontent.com/12226710/69445580-5fcc3b00-0d31-11ea-8e91-f75d6e85a5ca.png)

### Describe alternatives you've considered
The [docs](http://docs.humhub.org/humhub-modules-content-widgets-richtext-prosemirrorrichtext.html) don't talk about this and they include a link to [Prosemirror's docs](https://prosemirror.net/docs/) which includes instructions on how to make modifications, but I can't find the Prosemirror files in my install to do them manually.

**Comment by luke-** [comment]
The actual markdown editor (prosemirror) doesn't require any Markdown syntax?

**Comment by Ace2213** [comment]
No, but it supports it. The primary way of using the editor is via the menubar, but most users, most of the time, will not find most of those options useful just to make a quick comment/post. 

So I've opted to hide most menubar options via CSS and provide a cheat sheet pop-up for those who are interested in more advanced styling.
![image](https://user-images.githubusercontent.com/12226710/69485454-7e5c3000-0e1e-11ea-81ba-81526919ae5e.png)

Once the autoexpand by default bug is patched in 1.4, I'm going to remove the fullscreen button as well.

**Comment by Ace2213** [comment]
As for emojis, there's no way for the user to know they're even supported. For this, a dedicated button (preferably next to the submit button) would be ideal. Since that's what most users are used to from other social websites.

I understand if these aren't necessary changes to add to core, but I'd like to implement them for my instance and I can't find any information on how to modify the richtext editor.

**Comment by buddh4** [comment]
https://github.com/humhub/humhub-prosemirror/issues/8
https://github.com/humhub/humhub-prosemirror/issues/7
