### ISSUE TITLE
Option to reply particular comment (and comments order supporting that)

### ISSUE THREAD

**Issue by 4ong** [humhub/humhub#3752]
### Is your feature request related to a problem? Please describe.
In a long discussion, it's hard to find if the comment was answered somewhere later.

### Describe the solution you'd like
Any form of nested comments, like 
https://foxsanantonio.com/resources/media/a59bec26-8b47-40ed-b9ba-5a4af24ae9fa-large16x9_facebookpic1.jpg?1479936796536
![image](https://user-images.githubusercontent.com/13717891/69459110-4ea31e80-0d71-11ea-9ceb-f4578c2ae090.png)

### Describe alternatives you've considered
Visually reply can be posted just next to the original comment, with small indent.
I'm not sure what is the shortest way to implement this, will try to investigate soon.

**Comment by Ace2213** [comment]
#3680

**Comment by MIS-Center** [comment]
sorry but why did you closed this issue while it still needed ?
do you know another way or plugin can did that "reply on comment" ability ?
please provide it for us

**Comment by luke-** [comment]
Duplicate: https://github.com/humhub/humhub/issues/3938
