### ISSUE TITLE
Push notifications?

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3765]
Version 1.4 beta 1 officially brought push notification support, but either it's not working properly or the docs on how to set it up are lacking.

Feedback discussing it on the announcement post of beta 1: https://community.humhub.com/content/perma?id=200860

**Comment by ArchBlood** [comment]
With a valid SSL I have push working rather well make sure to test it.

**Comment by Ace2213** [comment]
I have valid SSL as well. The issue is the installation process that is either poorly documented or the docs are for an older implementation of push notifications.

**Comment by luke-** [comment]
We will soon release the Firebase Push module as beta version.
