### ISSUE TITLE
Web notifications not working 

### ISSUE THREAD

**Issue by TheCl3m** [humhub/humhub#3782]
### What steps will reproduce the problem?
Everything that should trigger a notification (messages, likes...). Web notifications are activated on the admin panel.
### What is the expected result?
Desktop notifications
### What do you get instead?
Nothing
### Additional info
Running HumHub 1.3.18. Website is asking for notification permissions. Read something about having Node.js to enables web notifications, which I do not have on my web server, could that be it ?

Thank you !
| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.18
| PHP version      | 7.2
| Operating system | Apache ? Linux? (idk about that sorry) 

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
A basic version of web push notification is implemented into v1.4 beta as for v1.3.x SSL and an open tab is required.

**Comment by TheCl3m** [comment]
All the test were being made with an open tab, to you suggest updating to v1.4 beta ?

**Comment by ArchBlood** [comment]
Me personally it's much easier plus PWA support isn't bad, but I'd wait till beta 2 or stable release of v1.4 is out.

**Comment by luke-** [comment]
https://www.humhub.com/en/marketplace/details?id=59

**Comment by ViFigueiredo** [comment]
> https://www.humhub.com/en/marketplace/details?id=59

It's only for mobile e.e
