### ISSUE TITLE
a tag link target is not working on custom page editing.

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#3783]
Hi, everyone.
I have made a custom link page on humhub 1.3.17, but that page's hyper-link can not open on target. If I try any target kind, but it always open on "_top" and rewrite the humhub page.
Is that a malfunction, isn't that?

**Comment by buddh4** [comment]
You can't configure a target, but the `open page in new window` setting was ignored, this i fixed in the latest module version.
