### ISSUE TITLE
Post box not extending when typing on v1.4

### ISSUE THREAD

**Issue by TheCl3m** [humhub/humhub#3788]
### What steps will reproduce the problem?
Typing in the box to post content 
### What is the expected result?
Box should extend if new lines are added
### What do you get instead?
Box isn't extending, looks like the written line is disapearing.
### Additional info
Also, I tested the Firebase notification module and it's working great ! Thanks :)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4
| PHP version      | 7.2
| Operating system | Tested on Chrome mobile & desktop + Firefox on Windows

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by buddh4** [comment]
Hmm could not recreate the issue.

- Please check the browser console for any javascript error.
- Does this happen for 1.4.beta2 or beta1?
- Did you try to flush the cache `Administration -> Settings -> Advanced -> Cache`

**Comment by TheCl3m** [comment]
No javascript error seems to show up regarding post form box. Do you know which script is handling this? 
It happens for 1.4 beta2 .
Cache flush didn't resolve anything.

**Comment by buddh4** [comment]
[Here](https://github.com/humhub/humhub-prosemirror) is the richtext repo. The file should be `humhub-editor.js`. Are you running in production mode or in debug mode (http://docs.humhub.org/admin-security.html#enable-production-mode) and is the site publicly accessible, perhaps I can have a quick look?

**Comment by TheCl3m** [comment]
Thanks for the answer, I emailed you all the informations.

**Comment by buddh4** [comment]
You seem to use a custom theme, I assume with the default theme it works? Make sure to rebuild your theme: http://docs.humhub.org/theme-css.html. (Or try the theme builder module). I assume you updated from an older version? If yes which version was installed prior to beta2?

**Comment by TheCl3m** [comment]
Yeah that's it ! Theme was transfered from my v1.3.18 installation. So rebuilding a theme should solve the problem? Thanks

**Comment by TheCl3m** [comment]
Got it to work; I only had to rebuild the theme. Note that running the command `lessc build.less css/theme.css` generated the theme.css inside the /less/css folder and I had to copy it to the themes /css in order to make it work. 
Thanks !

**Comment by buddh4** [comment]
Great, for the future, please make sure the issues are not related with your custom theme by testing the default theme. If you have trouble with a custom theme, ask the [Community](community.humhub.com/) for help.
