### ISSUE TITLE
Description value of a profile field isn't shown anywhere?

### ISSUE THREAD

**Issue by Mazvy** [humhub/humhub#3792]
### What steps will reproduce the problem?
Create a description for a profile input field

![](https://i.imgur.com/QXlfPWJ.png)

### What is the expected result?
To see it somewhere?

### What do you get instead?
It's not shown on the registration page, the users profile page or the edit profile page

![](https://i.imgur.com/fX4SwSa.png)
---
![](https://i.imgur.com/vbbbJrC.png)
---
![](https://i.imgur.com/Z3EDDbe.png)

**Comment by buddh4** [comment]
The description should be added as help block.
