### ISSUE TITLE
Guest users can't access public posts from 'Latest activities'

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#3796]
Guest users cannot access public posts from 'Latest activities' in the public space (members and guests).

![2019-12-19_10h13_04](https://user-images.githubusercontent.com/38252517/71136781-48597280-2249-11ea-8144-985a934f50ec.png)
---
![2019-12-19_10h17_45](https://user-images.githubusercontent.com/38252517/71136790-4ee7ea00-2249-11ea-90f5-f254debed137.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4-beta2
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by buddh4** [comment]
Fixed in https://github.com/humhub/humhub/commit/91da3f069305cfb4256e3817c24fd2a89e74a79d
