### ISSUE TITLE
Adding a new header link every time text is saved

### ISSUE THREAD

**Issue by lweddewer** [humhub/humhub#3803]
### What steps will reproduce the problem?
The editor added a new link to every header line when ever one save the text.

Tested for header h1 to h4.

### What is the expected result?
Only one link is added ones per headline.

### What do you get instead?
Every headline has as number of links added.

![image](https://user-images.githubusercontent.com/8478427/71320349-5b1eb200-24aa-11ea-8dcd-37e0e3961c9a.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.0-beta-2 as of 20.12.2019
| PHP version      | 7.2.24
| Operating system | ubnutu 18.04LTS

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by buddh4** [comment]
Do you have the wiki module installed, and can you confirm that this only happens when a wiki post is present somewhere in the same stream.
