### ISSUE TITLE
Inconsistency in NotificationManager->getSpaces() function

### ISSUE THREAD

**Issue by globalcow** [humhub/humhub#3806]
### What steps will reproduce the problem?
Register a new user with default settings for notifications. Add user to an existing space.
The new user clicks on "Receive notifications for new content" in that space.

The issue can be reproduced in the community installation.

### What is the expected result?
In the user's notification settings, the space should be listed in "Receive 'New Content' Notifications for the following spaces".

### What do you get instead?
The space is not listed is the user's notifications settings.

### Additional info
I think the reason is in https://github.com/humhub/humhub/blob/6a4f1887ad0d8f8f69397694b95ab73ea754e220/protected/humhub/modules/notification/components/NotificationManager.php#L257

Here, it is checked if the "notification.like_email" setting is initialised for the user. However, as the new user never changed the notification settings before, and still has the defaults, there is no such entry. As a result of that, the spaces listed in the user's notifications settings are not found correctly.

I checked this by setting the $isLoaded variable always true and the behaviour is correct. What is the reason for the isLoaded check here?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.0-beta.2

**Comment by buddh4** [comment]
The `isLoaded` should check if the notification settings have already been saved by the user, and if not use display the defaults, which is not the case if an user just uses the receive notifications menu item of a space.
