### ISSUE TITLE
Humhub Error on namecheap softaculous

### ISSUE THREAD

**Issue by Thronia** [humhub/humhub#3808]
### What steps will reproduce the problem?
Installation of humhub in namecheap softaculous
### What is the expected result?
Complete deployment of humhub without errors
### What do you get instead?
Warning incomplete setup!
 The cron job for the background jobs (queue) does not seem to work properly.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Please contact namecheap or softaculous.
