### ISSUE TITLE
SSL termination conflict with file attachment URL

### ISSUE THREAD

**Issue by st5000** [humhub/humhub#3815]
When using SSL termination (outside of HH instance which runs in clear http) all file attachment URL ("/file/file/download?guid=...") are always sent in http while client connection is forced https (also specified in Settings -> General -> Base URL)

This situation triggers _"Connection Is Not Secure"_ alerts at client side an cause some strange behavior on some browsers.

**Comment by luke-** [comment]
You need to specify a the SSL proxy server as trusted host:
https://www.yiiframework.com/doc/api/2.0/yii-web-request#$trustedHosts-detail

e.g. protected/config/web.php
(You should replace any with the ip of the server.)

```
return [
    'components' => [
        'request' => [
            'trustedHosts' => ['any']
        ]

    ]
];
``` 

Or you can add following before the return:
$_SERVER['HTTPS'] = 'on';

**Comment by st5000** [comment]
Added trustedHosts field and it works normally.

Thanks for the tip ! :+1:

**Comment by luke-** [comment]
We should leave this open, to enhance the documention...

**Comment by luke-** [comment]
https://docs.humhub.org/docs/admin/reverse-proxy
