### ISSUE TITLE
The space avatar and my own avatar are one and the same

### ISSUE THREAD

**Issue by FelixFester** [humhub/humhub#3819]
### What steps will reproduce the problem?
When trying to load / delete an avatar or header.

### What is the expected result?
I would like everything to work fine and avatar with a hat the spaces were different from what is in the profile.

### What do you get instead?
If the profile has an avatar and a header, when you try to remove an avatar from space, the avatar from the profile is also deleted. Same thing with a hat. 

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.20
| PHP version      |  7.3
| Operating system | Android

### Additional Info
This thing don't have error stack. 

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by FelixFester** [comment]
Very strange bug. For it appears to me after some time, i.e. sometimes everything is normally deleted, and sometimes it is deleted like that https://pasteboard.co/IPwJ9C6.png and https://pasteboard.co/IPwJtjt.png

**Comment by FelixFester** [comment]
I found the cause of this bug. Sometimes after deleting an avatar, the avatar remains in place (until the page is refreshed). And if at this moment you delete the avatar again, it will be deleted from the profile https://pasteboard.co/IPwPBeD.png

**Comment by ArchBlood** [comment]
Not seeing any bugs here. The Space menu displays Space avatars, if it doesn't have an avatar then it shows letters as shown in your screenshots, if you upload an image for your space avatar then it should change to the same image you uploaded, if your server's cache settings aren't configured then you'll be required to refresh the page to show the page updates.
