### ISSUE TITLE
Error: spaces return to 404 page

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#3820]
Can someone help me? I can't open any space and they return to error page

`yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\space\models\Space::profile in /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Component.php:154 Stack trace: #0 /home/amigos/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('profile') #1 /home/amigos/public_html/themes/Bronha/views/content/widgets/views/containerProfileHeader.php(58): yii\db\BaseActiveRecord->__get('profile') #2 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #3 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #4 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\content\widgets\ContainerProfileHeader)) #5 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('containerProfil...', Array, Object(humhub\modules\content\widgets\ContainerProfileHeader)) #6 /home/amigos/public_html/protected/humhub/modules/content/widgets/ContainerProfileHeader.php(116): yii\base\Widget->render('containerProfil...', Array) #7 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\ContainerProfileHeader->run() #8 /home/amigos/public_html/protected/humhub/modules/space/widgets/views/header.php(10): humhub\components\Widget::widget(Array) #9 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #10 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #11 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\space\widgets\Header)) #12 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('header', Array, Object(humhub\modules\space\widgets\Header)) #13 /home/amigos/public_html/protected/humhub/modules/space/widgets/Header.php(34): yii\base\Widget->render('header', Array) #14 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\modules\space\widgets\Header->run() #15 /home/amigos/public_html/protected/humhub/modules/space/views/space/_layout.php(22): yii\base\Widget::widget(Array) #16 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #17 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #18 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\space\controllers\SpaceController)) #19 /home/amigos/public_html/protected/humhub/components/Controller.php(124): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\space\controllers\SpaceController)) #20 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(387): humhub\components\Controller->renderContent('\n<div class="pa...') #21 /home/amigos/public_html/protected/humhub/modules/space/controllers/SpaceController.php(106): yii\base\Controller->render('home', Array) #22 /home/amigos/public_html/protected/humhub/modules/space/controllers/SpaceController.php(88): humhub\modules\space\controllers\SpaceController->actionHome() #23 [internal function]: humhub\modules\space\controllers\SpaceController->actionIndex() #24 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #25 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #26 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #27 /home/amigos/public_html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('space/space', Array) #28 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #29 /home/amigos/public_html/index.php(43): yii\base\Application->run() #30 {main}`

**HumHub version** 1.4.0-beta.2
**PHP version** 7.3

**Comment by buddh4** [comment]
Seems to be an issue with your theme, this is the core file which should work https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/widgets/views/containerProfileHeader.php

Use `<?php if($container instanceof User) : ?>` conditions for container type specific changes
