### ISSUE TITLE
PDF file inline view broken with 1.4+

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#3823]
With HumHub 1.4 on some clients the PHP inline view shows a blank page.

**Comment by buddh4** [comment]
Could not recreate the issue, but I noticed for example that in HumHub < 1.4 the developer console shows a network request whereas HumHub 1.4 does not show a network request. May be related to new security headers.

**Comment by luke-** [comment]
The original reporter can no longer reproduce it either. Strange but then we close it...
