### ISSUE TITLE
User Settings language drop-down is incorrectly selected for System default of "English (US)"

### ISSUE THREAD

**Issue by triteamz** [humhub/humhub#3826]
### What steps will reproduce the problem?

- Set the default language to "English (US)" in `Administration > Settings`
- Add a new user
- Notice in the `user` table the `language` is set to "en-US"
- Log in as the user and go to `Account Settings > Settings`
- Notice the Language is set to the first item "Aragonés"
- Change the language to `en` directly in the database
- The User's Setting page now correctly defaults to "English (US)"

### What is the expected result?

- For the system default language "English (US)," the language drop-down in the User's Settings page should have "English (US)" selected

### What do you get instead?

- The language instead defaults to the first language in the list. (In my case, "Aragonés")

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.20
| PHP version      | 7.2.16
| Operating system | CentOS Linux release 7.6.1810 (Core)

**Comment by luke-** [comment]
The upcoming HumHub 1.4 should solves this issue.
Here we have fundamentally improved the locale handling.

Can you please try it again with 1.4+?
