### ISSUE TITLE
Characters are duplicated when typing in the rich text editor using IME.

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#3827]
If use the IME to enter an at sign or colon to enter a mention or emoji, it will be duplicated.

![2020_01_18_08 18 01_edit](https://user-images.githubusercontent.com/38252517/72653129-d81b4980-39cc-11ea-9d53-0c011f606946.jpg)

![2020_01_18_08 18 37_edit](https://user-images.githubusercontent.com/38252517/72653162-013bda00-39cd-11ea-8517-5eb51da8612a.jpg)

**Conditions that occur**
- Windows10 + Japanese IME
- Android + Japanese keyboard application

There is no problem with humhub 1.3.20.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4-beta2
| PHP version      | 
| Operating system |

**Comment by buddh4** [comment]
Probably related to https://github.com/ProseMirror/prosemirror/issues/944

**Comment by sakurafarm** [comment]
Add the information of the environment I verified.

**Windows10 Home (32bit)**

| Browser | IME ON | IME OFF
| ----- | ----- | -----
| Chrome 79.0.3945.130 | Duplicated | No problem
| Opera 66.0.3515.36 | Duplicated | No problem
| Firefox 72.0.1 | **Does not accept character input** |  No problem
| | **The caret is not displayed when the focus is on the rich text editor** | **The caret is not displayed when the focus is on the rich text editor**

**Android 7.0**

| Browser | IME ON | IME OFF
| ----- | ----- | -----
| Chrome 79.0.3945.116 | Duplicated | No problem
| Opera 55.2.2719.50740 | Duplicated | No problem
| Firefox 68.4.1 | Duplicated | No problem
