### ISSUE TITLE
Unused modules are displayed in the space security settings.

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#3828]
All installed modules available in the space will appear in the security settings, even if have not enabled them in the space.

![2020_01_18_08 42 42](https://user-images.githubusercontent.com/38252517/72653857-4ad9f400-39d0-11ea-9ee8-f142709c9c30.jpg)

![2020_01_18_08 43 50](https://user-images.githubusercontent.com/38252517/72653867-588f7980-39d0-11ea-93d4-cf168caaffea.jpg)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3 - 1.4beta2
| PHP version      | 
| Operating system |

**Comment by buddh4** [comment]
This is more a problem of the current module behavior, the module should decide when to export a permission, currently those modules do not check for a container installation. We implemented a container installation check outside of the module, but this prevented global modules as the mail module to inject permissions. So all container modules should add something like this:

```
public function getPermissions($contentContainer = null)
{
    if ($container && $container->isModuleEnabled('mymoduleid')) {
      return [new SomePermission]
    }
   return [];
}

```

**Comment by buddh4** [comment]
Modules to review:

- [ ] Calendar
- [ ] CFiles
- [ ] CustomPages
- [ ] External Calendar
- [ ] Gallery
- [ ] Meeting
- [ ] Polls
- [ ] Wiki
- [ ] Taks
