### ISSUE TITLE
Guest user access to counter set freezes

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#3829]
The page will remain loading when guest users access the following profile or space counter sets.  Can only return by reloading the page!

**Profile Counter sets**
- Followers
- Following
- Spaces

**Space Counter sets**
- Followers

![2020_01_18_09 21 30](https://user-images.githubusercontent.com/38252517/72655390-c3907e80-39d7-11ea-8dcd-7dd54473be84.jpg)

This is because the controller does not allow the guest user to perform the corresponding action, but another problem is that the sidebar displays a widget with relevant information.

For example, the sidebar on the profile page shows "User Followers" widgets to guests. This is clearly inconsistent.

I think it would be nice to add a new permission class so that space admins and users themselves could use security settings to control access to guests and other users.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3 - 1.4beta2
| PHP version      | 
| Operating system |

**Comment by buddh4** [comment]
I've disabled the access for guest users for now, we need some general privacy settings for this i guess as mentioned in https://github.com/humhub/humhub/issues/1869.
