### ISSUE TITLE
ERROR: can't open stream after update calendar module

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#3830]
I cant unistall calendar module. It returns to error page. I try using phpmyadmin in "module_enalbled", but the same thing happen.

``
ReflectionException: Class humhub\modules\calendar\models\CalendarEntry does not exist in /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php:447 Stack trace: #0 /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php(447): ReflectionClass->__construct('humhub\\modules\\...') #1 /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php(374): yii\di\Container->getDependencies('humhub\\modules\\...') #2 /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('humhub\\modules\\...', Array, Array) #3 /home/amigos/public_html/protected/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('humhub\\modules\\...', Array) #4 /home/amigos/public_html/protected/humhub/modules/content/models/ContentType.php(46): yii\BaseYii::createObject('humhub\\modules\\...') #5 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\content\models\ContentType->init() #6 /home/amigos/public_html/protected/humhub/modules/content/models/ContentType.php(71): yii\base\BaseObject->__construct(Array) #7 /home/amigos/public_html/protected/humhub/modules/content/models/ContentType.php(83): humhub\modules\content\models\ContentType::getContentTypes(NULL) #8 /home/amigos/public_html/protected/humhub/modules/content/widgets/ContentTypePicker.php(41): humhub\modules\content\models\ContentType::getContentTypeSelection(NULL) #9 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\content\widgets\ContentTypePicker->init() #10 [internal function]: yii\base\BaseObject->__construct(Array) #11 /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array) #12 /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('humhub\\modules\\...', Array, Array) #13 /home/amigos/public_html/protected/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->get('humhub\\modules\\...', Array, Array) #14 /home/amigos/public_html/protected/humhub/components/Widget.php(60): yii\BaseYii::createObject(Array) #15 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/views/pickerInput.php(14): humhub\components\Widget::widget(Array) #16 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #17 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #18 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\ui\filter\widgets\PickerFilterInput)) #19 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('pickerInput', Array, Object(humhub\modules\ui\filter\widgets\PickerFilterInput)) #20 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/FilterInput.php(76): yii\base\Widget->render('pickerInput', Array) #21 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\ui\filter\widgets\FilterInput->run() #22 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/views/filterListBlock.php(24): humhub\components\Widget::widget(Array) #23 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #24 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #25 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\ui\filter\widgets\FilterBlock)) #26 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('filterListBlock', Array, Object(humhub\modules\ui\filter\widgets\FilterBlock)) #27 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/FilterBlock.php(64): yii\base\Widget->render('filterListBlock', Array) #28 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\ui\filter\widgets\FilterBlock->run() #29 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/views/filterPanel.php(21): humhub\components\Widget::widget(Array) #30 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #31 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #32 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\ui\filter\widgets\FilterPanel)) #33 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('filterPanel', Array, Object(humhub\modules\ui\filter\widgets\FilterPanel)) #34 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/FilterPanel.php(41): yii\base\Widget->render('filterPanel', Array) #35 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\ui\filter\widgets\FilterPanel->run() #36 /home/amigos/public_html/themes/Bronha/views/stream/widgets/wallStreamFilterNavigation.php(37): humhub\components\Widget::widget(Array) #37 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #38 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #39 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\stream\widgets\WallStreamFilterNavigation)) #40 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('wallStreamFilte...', Array, Object(humhub\modules\stream\widgets\WallStreamFilterNavigation)) #41 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/FilterNavigation.php(150): yii\base\Widget->render('wallStreamFilte...', Array) #42 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\ui\filter\widgets\FilterNavigation->run() #43 [internal function]: humhub\components\Widget::widget(Array) #44 /home/amigos/public_html/protected/humhub/modules/stream/widgets/StreamViewer.php(173): call_user_func('humhub\\modules\\...', Array) #45 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\stream\widgets\StreamViewer->run() #46 /home/amigos/public_html/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array) #47 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\widgets\BaseStack->run() #48 /home/amigos/public_html/themes/Bronha/views/dashboard/dashboard/index.php(28): humhub\components\Widget::widget(Array) #49 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #50 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #51 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #52 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(386): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #53 /home/amigos/public_html/protected/humhub/modules/dashboard/controllers/DashboardController.php(69): yii\base\Controller->render('index', Array) #54 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #55 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #56 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #57 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #58 /home/amigos/public_html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array) #59 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #60 /home/amigos/public_html/index.php(43): yii\base\Application->run() #61 {main} Next yii\base\InvalidConfigException: Failed to instantiate component or class "humhub\modules\calendar\models\CalendarEntry". in /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php:449 Stack trace: #0 /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php(374): yii\di\Container->getDependencies('humhub\\modules\\...') #1 /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('humhub\\modules\\...', Array, Array) #2 /home/amigos/public_html/protected/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('humhub\\modules\\...', Array) #3 /home/amigos/public_html/protected/humhub/modules/content/models/ContentType.php(46): yii\BaseYii::createObject('humhub\\modules\\...') #4 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\content\models\ContentType->init() #5 /home/amigos/public_html/protected/humhub/modules/content/models/ContentType.php(71): yii\base\BaseObject->__construct(Array) #6 /home/amigos/public_html/protected/humhub/modules/content/models/ContentType.php(83): humhub\modules\content\models\ContentType::getContentTypes(NULL) #7 /home/amigos/public_html/protected/humhub/modules/content/widgets/ContentTypePicker.php(41): humhub\modules\content\models\ContentType::getContentTypeSelection(NULL) #8 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\content\widgets\ContentTypePicker->init() #9 [internal function]: yii\base\BaseObject->__construct(Array) #10 /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array) #11 /home/amigos/public_html/protected/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('humhub\\modules\\...', Array, Array) #12 /home/amigos/public_html/protected/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->get('humhub\\modules\\...', Array, Array) #13 /home/amigos/public_html/protected/humhub/components/Widget.php(60): yii\BaseYii::createObject(Array) #14 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/views/pickerInput.php(14): humhub\components\Widget::widget(Array) #15 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #16 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #17 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\ui\filter\widgets\PickerFilterInput)) #18 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('pickerInput', Array, Object(humhub\modules\ui\filter\widgets\PickerFilterInput)) #19 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/FilterInput.php(76): yii\base\Widget->render('pickerInput', Array) #20 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\ui\filter\widgets\FilterInput->run() #21 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/views/filterListBlock.php(24): humhub\components\Widget::widget(Array) #22 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #23 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #24 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\ui\filter\widgets\FilterBlock)) #25 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('filterListBlock', Array, Object(humhub\modules\ui\filter\widgets\FilterBlock)) #26 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/FilterBlock.php(64): yii\base\Widget->render('filterListBlock', Array) #27 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\ui\filter\widgets\FilterBlock->run() #28 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/views/filterPanel.php(21): humhub\components\Widget::widget(Array) #29 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #30 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #31 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\ui\filter\widgets\FilterPanel)) #32 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('filterPanel', Array, Object(humhub\modules\ui\filter\widgets\FilterPanel)) #33 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/FilterPanel.php(41): yii\base\Widget->render('filterPanel', Array) #34 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\ui\filter\widgets\FilterPanel->run() #35 /home/amigos/public_html/themes/Bronha/views/stream/widgets/wallStreamFilterNavigation.php(37): humhub\components\Widget::widget(Array) #36 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #37 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #38 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\stream\widgets\WallStreamFilterNavigation)) #39 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('wallStreamFilte...', Array, Object(humhub\modules\stream\widgets\WallStreamFilterNavigation)) #40 /home/amigos/public_html/protected/humhub/modules/ui/filter/widgets/FilterNavigation.php(150): yii\base\Widget->render('wallStreamFilte...', Array) #41 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\ui\filter\widgets\FilterNavigation->run() #42 [internal function]: humhub\components\Widget::widget(Array) #43 /home/amigos/public_html/protected/humhub/modules/stream/widgets/StreamViewer.php(173): call_user_func('humhub\\modules\\...', Array) #44 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\modules\stream\widgets\StreamViewer->run() #45 /home/amigos/public_html/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array) #46 /home/amigos/public_html/protected/humhub/components/Widget.php(63): humhub\widgets\BaseStack->run() #47 /home/amigos/public_html/themes/Bronha/views/dashboard/dashboard/index.php(28): humhub\components\Widget::widget(Array) #48 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/amigos/...') #49 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/amigos/...', Array) #50 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/amigos/...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #51 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(386): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #52 /home/amigos/public_html/protected/humhub/modules/dashboard/controllers/DashboardController.php(69): yii\base\Controller->render('index', Array) #53 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #54 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #55 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #56 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #57 /home/amigos/public_html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array) #58 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #59 /home/amigos/public_html/index.php(43): yii\base\Application->run() #60 {main}
``

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.0-beta.2
| PHP version      |  7.3

**Comment by buddh4** [comment]
Try running the [integrity check](http://docs.humhub.org/admin-troubleshooting.html#data-integrity)
