### ISSUE TITLE
Impossible to access space member administration menu

### ISSUE THREAD

**Issue by TheCl3m** [humhub/humhub#3831]
### What steps will reproduce the problem?
When wanting to manage members from a space, I get an error and nothing is displayed. (/space/manage/member)
### What is the expected result?
Access to the space member administration page.
### What do you get instead?
Internal server error 
### Additional info
Seems the problem first appeared when installing the galery module. Only some spaces have that issue, I can't determine why.
`Error: Call to a member function getProfileImage() on null in /home/hucl4012/ponto-network.fr/protected/humhub/modules/user/widgets/Image.php:52 Stack trace: #0 /home/hucl4012/ponto-network.fr/protected/humhub/components/Widget.php(63): humhub\modules\user\widgets\Image->run() #1 /home/hucl4012/ponto-network.fr/protected/humhub/modules/user/grid/ImageColumn.php(36): humhub\components\Widget::widget(Array) #2 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/grid/Column.php(111): humhub\modules\user\grid\ImageColumn->renderDataCellContent(Object(humhub\modules\space\models\Membership), 14829260, 0) #3 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/grid/GridView.php(525): yii\grid\Column->renderDataCell(Object(humhub\modules\space\models\Membership), 14829260, 0) #4 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/grid/GridView.php(494): yii\grid\GridView->renderTableRow(Object(humhub\modules\space\models\Membership), 14829260, 0) #5 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/grid/GridView.php(358): yii\grid\GridView->renderTableBody() #6 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(160): yii\grid\GridView->renderItems() #7 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/grid/GridView.php(326): yii\widgets\BaseListView->renderSection('{items}') #8 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(135): yii\grid\GridView->renderSection('{items}') #9 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array) #10 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(138): preg_replace_callback('/{\\w+}/', Object(Closure), '{summary}\n{item...') #11 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/grid/GridView.php(301): yii\widgets\BaseListView->run() #12 /home/hucl4012/ponto-network.fr/protected/humhub/widgets/GridView.php(33): yii\grid\GridView->run() #13 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\widgets\GridView->run() #14 /home/hucl4012/ponto-network.fr/protected/humhub/modules/space/modules/manage/views/member/index.php(111): yii\base\Widget::widget(Array) #15 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/hucl4012/...') #16 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/hucl4012/...', Array) #17 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/hucl4012/...', Array, Object(humhub\modules\space\modules\manage\controllers\MemberController)) #18 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/base/Controller.php(386): yii\base\View->render('index', Array, Object(humhub\modules\space\modules\manage\controllers\MemberController)) #19 /home/hucl4012/ponto-network.fr/protected/humhub/modules/space/modules/manage/controllers/MemberController.php(76): yii\base\Controller->render('index', Array) #20 [internal function]: humhub\modules\space\modules\manage\controllers\MemberController->actionIndex() #21 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #22 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #23 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #24 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('space/manage/me...', Array) #25 /home/hucl4012/ponto-network.fr/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #26 /home/hucl4012/ponto-network.fr/index.php(25): yii\base\Application->run() #27 {main} `
| Q                | A
| ---------------- | ---
| HumHub version   | 1.4 beta 2
| PHP version  7.2  | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by buddh4** [comment]
Are you using an MyISAM or InnoDB database?

**Comment by TheCl3m** [comment]
Hello,

Thanks for the information. You were right, a wrong entry was in the space_membership table. I can explain that because we have a script that adds entries to that specific table and an unexisting user was added. Problem solved :)

**Comment by buddh4** [comment]
ok, nice to hear its resolved but please always add such information about modifications/custom modules/custom themes, since for us its impossible to reproduce and nontheless time consuming to investigate.
