### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#3832]
`exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "hourly/run".' in /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Module.php:537 Stack trace: #0 /home/amigos/public_html/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('hourly/run', Array) #1 /home/amigos/public_html/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('hourly/run', Array) #2 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #3 /home/amigos/public_html/protected/yii(29): yii\base\Application->run() #4 {main} Next exception 'yii\console\UnknownCommandException' with message 'Unknown command "hourly/run".' in /home/amigos/public_html/protected/vendor/yiisoft/yii2/console/Application.php:183 Stack trace: #0 /home/amigos/public_html/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('hourly/run', Array) #1 /home/amigos/public_html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #2 /home/amigos/public_html/protected/yii(29): yii\base\Application->run() #3 {main}`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.0-beta.2
| PHP version      |  7.4

**Comment by buddh4** [comment]
Did you follow: http://docs.humhub.org/admin-installation-configuration.html#cronjobs-and-asynchronous-job-processing-v13 ?
