### ISSUE TITLE
Many entries in the top menu crashing layout

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#3834]
![image](https://user-images.githubusercontent.com/38326726/72740391-dce72580-3ba5-11ea-87fc-61e403c6389d.png)

| HumHub version   | 1.3.18

**Comment by buddh4** [comment]
The question is, what is the expected result? Perhaps a scrollable nav similiar to the mobile space nav, or we only allow a certain amount of icons and add a dropdown for others menu icons.

**Comment by SimJoSt** [comment]
I can confirm this issue. In tablet view no more than 8 and in desktop view no more than 10 items are possible without this occuring.

An overflow menu would also be possible solution. Similar to the one used in the mobile view. All items over 8, respectively 10, could be listed there.

**Comment by buddh4** [comment]
I think this also depends on the item label length, I consider a dynamic javascript solution, should not be too hard.
