### ISSUE TITLE
Make pre- and lastname not required

### ISSUE THREAD

**Issue by hauptDev** [humhub/humhub#3842]
### Is your feature request related to a problem? Please describe.
Somewhat. I plan to switch from another hub to humhub but the users in my community won't share their real names but work with usernames only. Pre- and lastname are required fields but aren't really necessary when people are identified on posts etc. with their username whats configureable in the admin panel.

### Describe the solution you'd like
I'd like that pre- and lastname aren't required fields anymore.

### Describe alternatives you've considered
There isn't really an alternative. The only way would be that people fill in fake names what wouldnt make any sense and is confusing to the users.

Thanks for noticing my post. I'd be happy if this change is possible.

**Comment by luke-** [comment]
Is it not yet possible to remove the "Required" flag from both profile fields?
