### ISSUE TITLE
Social network content loading slowly

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#3843]
When the dashboard opens (or any user content), it loads slowly. Especially when it has any media in the post.
What is happening?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.0-beta.2
| PHP version      |  7.4
| Operating system | Linux

**Comment by luke-** [comment]
Can you reproduce this on our hosting? 

Can you provide steps to reproduce?
