### ISSUE TITLE
Add directory menu icons

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3844]
Add menu icons to the directory menu.

**Comment by luke-** [comment]
Any suggestions for which icon?

**Comment by buddh4** [comment]
- Group: https://fontawesome.com/v4.7.0/icon/users
- Members: https://fontawesome.com/v4.7.0/icon/user
- Spaces: https://fontawesome.com/v4.7.0/icon/dot-circle-o
- User profile posts:  https://fontawesome.com/v4.7.0/icon/commenting
