### ISSUE TITLE
Error page does not use theme @1.4

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3848]
The error page does not load the theme.

### What steps will reproduce the problem?

- Create a custom page with admin_only setting
- Logout and access the page as guest

### What is the expected result?

Proper error page

### What do you get instead?

![grafik](https://user-images.githubusercontent.com/9800854/73611421-fe063800-45e1-11ea-93b3-b5b5c7fc8759.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4 (dev branch)

**Comment by buddh4** [comment]
Any thoughts @luke- ?

**Comment by buddh4** [comment]
Here are the css assets:

![grafik](https://user-images.githubusercontent.com/9800854/73611737-3e1aea00-45e5-11ea-80e4-90b08afc365e.png)

**Comment by buddh4** [comment]
Probably found the cause: https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L108 think this line was added in one of the latest Yii versions.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/0a03d894c19f6cb79cbfa3e9a398fad15c3bdc72
