### ISSUE TITLE
support for lightbox galleries 

### ISSUE THREAD

**Issue by andreakru** [humhub/humhub#385]
Hi

I notice that lightbox used don't support galleries like explained here:
http://ashleydw.github.io/lightbox/#global-galleries

Its a custom version or just require upgrade?

**Comment by thehiddennepali** [comment]
HI I have some issue with this light box,  I am building gallery and I am suing code as beow taking reference form the space module

`<div class="post-files" id="post-files-<?php echo Yii::$app->controller->getSpace()->guid; ?>">
        <?php foreach ($galleries as $gallery) : ?>
           
                <?php
                //Note: We need to add "#.jpeg" to the full url for image  detection of ekko lightbox.
                ?>
                <a data-toggle="lightbox" data-gallery="<?php
                if (count($galleries) > 1) {
                    echo "gallery-" . Yii::$app->controller->getSpace()->guid.'_'.$gallery->id;
                }
                ?>" href="<?php echo Yii::$app->getUrlManager()->getBaseUrl().'/uploads/gallery_image/'.$gallery->name; ?>#.jpeg"  data-footer='<button type="button" class="btn btn-primary" data-dismiss="modal"><?php echo Yii::t('FileModule.widgets_views_showFiles', 'Close'); ?></button>'>
                    <img src='<?php echo Yii::$app->getUrlManager()->getBaseUrl().'/uploads/gallery_image/'.$gallery->name; ?>' width='200' height='200'>
                </a>
            

        <?php endforeach; ?>
    </div>`

the things happens like when I click on the image it will load up the first image and even I can see the nex and prev button but when I click on those button they no next image or previous images is loaded, so any one could suggest me, I had check the light box js which there.

Thank you waiting for your response.
