### ISSUE TITLE
Optimize directory performance

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#3850]
The user directory does not seem to use optimized database queries (indices) in all situations, e.g. for profile last name or user status.

For larger sites such as the HumHub community with over 10k users, the loading time is poor.

Caching should also be used here.

It becomes especially relevant that since HumHub 1.4 for the directory, the database is used directly as data source rather than the search engine.

**Comment by ArchBlood** [comment]
@luke- this could be closed or does HumHub still plan on doing something similar in nature with the new sections?

**Comment by luke-** [comment]
@ArchBlood Good Catch & Happy New Year! ;-)
