### ISSUE TITLE
Migrate components from ZendFramework to Laminas

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#3851]
tbd

**Comment by geirfp** [comment]
I see that Laminas has some component regarding LDAP, but I have been unable to find that Laminas has any components regarding search which could replace the Zend Lucene search in HumHub. Maybe better to consider using ElasticSearch, as mentioned in issue #2499?

**Comment by luke-** [comment]
@geirfp Sorry for the late reply. Yes we will have to rewrite the search system in one of the next major releases and look for alternatives to ZendSearch.

PR here: https://github.com/humhub/humhub/pull/4507
