### ISSUE TITLE
Lot's of 400 errors, bad request

### ISSUE THREAD

**Issue by derixithy** [humhub/humhub#3854]
### What steps will reproduce the problem?
For example, deleting a post on stream wil result in an error, and the post wil not be deleted.

### What is the expected result?
Post wil be deleted

### What do you get instead?
```
{
    "url": "/content/content/delete",
    "status": 400,
    "response": {
        "error": true,
        "message": "Het is niet mogelijk uw verstrekte gegevens te verifiëren."
    },
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"error\":true,\"message\":\"Het is niet mogelijk uw verstrekte gegevens te verifiëren.\"}",
        "responseJSON": {
            "error": true,
            "message": "Het is niet mogelijk uw verstrekte gegevens te verifiëren."
        },
        "status": 400,
        "statusText": "Bad Request"
    },
    "dataType": "json",
    "error": true,
    "message": "Het is niet mogelijk uw verstrekte gegevens te verifiëren.",
    "errorThrown": "Bad Request",
    "validationError": true
}
```
### Additional info
Logging is on and there are no errors logged for this time frame.
I also started new from scratch but that did not work.
Using the example above, going to the permalink i can delete the post but sometimes it wil need a refresh (ctrl+shift+r)

Another example, adding a friend will fail always.

-edit: formatting

I'm on the newest version. I also have this on 1.3.
The problems are also with default theme

Plugins i use are:
Birthday Widget
Breaking News
Gallery
Link List
Mail
Most Active Users
Polls
Report Content
Social Share
Tasks

**Comment by luke-** [comment]
Can you please provide more information?

e.g. HumHub Version, Modules/Themes used, Customizations, etc.

**Comment by derixithy** [comment]
I update the original post with version number and plugins
Disabling Report Content and Breaking news plugins seems to fix everything again. But i'm not sure it still need some testing.

**Comment by luke-** [comment]
Are there any javascript errors on your installation?

The error is related to the CSRF protection. Somehow the csrf token is not correctly transmitted.

Does this error occur on 1.3+ and 1.4+ Humhub versions?

**Comment by luke-** [comment]
Can you test it on another browser?

**Comment by derixithy** [comment]
Javascript console gave an error
Failed to load resource: the server responded with a status of 400 (Bad Request) on https://usershare.nl/u/eddie/post/post/post

I tried in midori, firefox and chromium on different linux distributions and nomadbsd.

I did not have problems on a earlier 1.3 humhub version, but i don't know when the problem first creeped in.

I'm using php 7.3.14, all php extensions are green on https://usershare.nl/admin/information/prerequisites except apc caching.

I also tested the integrity of the files and all was in order.

**Comment by luke-** [comment]
Thanks for the insight, really weird. Did you made any changes in the configuration file(s)?

**Comment by derixithy** [comment]
prtoected/config/common.php
```
<?php
/**
 * This file provides to overwrite the default HumHub / Yii configuration by your local common (Console and Web) environments
 * @see http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html
 * @see http://docs.humhub.org/admin-installation-configuration.html
 * @see http://docs.humhub.org/dev-environment.html
 */
return [
    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ]
];
```

index.php moved top humhub.php and new one created
```
<?php


function isSecure() {
    return (
        (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
     || $_SERVER['SERVER_PORT'] == 443
     || (
            (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
         || (!empty($_SERVER['HTTP_X_FORWARDED_SSL'])   && $_SERVER['HTTP_X_FORWARDED_SSL'] == 'on')
        )
    );
}

if (!isSecure()) {
header('Location: https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'], TRUE, 301);
exit;
}


include 'humhub.php';
```

**Comment by derixithy** [comment]
I totaly forgot i added the ugly redirect hack, i will try without it.

**Comment by luke-** [comment]
Can you please comment out the following two lines as a little test?
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/web/Events.php#L29-L30

**Comment by derixithy** [comment]
> Can you please comment out the following two lines as a little test?
> https://github.com/humhub/humhub/blob/master/protected/humhub/modules/web/Events.php#L29-L30

done

**Comment by luke-** [comment]
This fixes the problem for me as soon as I empty the browser cache.

**Comment by luke-** [comment]
Can you confirm this? @buddh4 somehow this seem to be related to the security headers.

**Comment by derixithy** [comment]
Having tried the workaround for a few days i can say the problems are a lot less but not completely fixed.

**Comment by derixithy** [comment]
Any updates? This has still not been resolved.

**Comment by buddh4** [comment]
@luke- could you reproduce this issue and if yes how?

**Comment by derixithy** [comment]
It's intermittend but happens more often then not.
It's an issue right after login and for all users/platforms/browsers.

**Comment by luke-** [comment]
Can you please describe your server setup in more detail and show configurations if necessary?

**Comment by derixithy** [comment]
I'm on shared hosting, i could give @luke- access to the application and ftp if that helps.

**Comment by luke-** [comment]
@derixithy Do you still have the problem?

**Comment by derixithy** [comment]
> @derixithy Do you still have the problem?

Still the same, just upgraded to 1.6.2 but the problem persists

**Comment by luke-** [comment]
@derixithy So you still can't delete any posts? If the problem is really so clearly reproducible, maybe you can send the url and a account to lucas@humhub.com?

**Comment by buddh4** [comment]
@luke- is this worth documenting or a common restriction on some servers?

**Comment by luke-** [comment]
Not so in the documentation, but that would be something for the Wiki in the community.

**Comment by buddh4** [comment]
Maybe just mark such issues with solution with a troubleshooting tag here on github in order to keep track of rare but hard to debug issues.

**Comment by derixithy** [comment]
Just to clarify the problem seemed to be in the varnish configuration of my hosting.
