### ISSUE TITLE
Delete notification when publication has been opened from email

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#3855]
When a content creates a notification, if you receive it by email and click on the button "View online", the notification should bee marked as seen.

Technically, when a link containing `?contentId=xxxx` is opened, the content with id number xxxx should be removed from the notification table.

**Comment by luke-** [comment]
That should already be the case. As soon as a user clicks on the "View Online" in the mail, the notification model is loaded, marked as read and the user is redirected to the content.

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/notification/controllers/EntryController.php#L64

The notification is never deleted here, but only marked as seen.

In the case of an deleted notification, there is a new parameter "contentId" in the link of the e-mail. (Not sure what the dev. status is here).  Using this parameter the NotificationController is able to redirect the user without the existing Notification.

**Comment by funkycram** [comment]
I'm very sorry, you are right, it does work. It was a report from users, but after testing it is ok. Sorry for the time you spent to answer me and thanks for the interesting explanations !

**Comment by luke-** [comment]
No problem, the fallback (introduced with 1.4+) is available here:
https://github.com/humhub/humhub/issues/3822
