### ISSUE TITLE
Table 'humhub.fcmpush_user' doesn't exist on fresh installation

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#3857]
### What steps will reproduce the problem?
Go to (any) Account -> Settings -> Notifications

### What is the expected result?
Notifications settings window

### What do you get instead?
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'humhub.fcmpush_user' doesn't exist
The SQL being executed was: SELECT COUNT(*) FROM `fcmpush_user` WHERE `user_id`=1

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.0
| PHP version      |  7.3
| Operating system | Linux CentOS

yii\base\InvalidConfigException: The table does not exist: fcmpush_user in /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php:438 Stack trace: #0 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(262): yii\db\ActiveRecord::getTableSchema() #1 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(234): yii\db\ActiveRecord::filterValidColumnNames(Object(yii\db\Connection), Array) #2 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(191): yii\db\ActiveRecord::filterCondition(Array, Array) #3 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array) #4 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/modules/fcm-push/controllers/TokenController.php(24): yii\db\BaseActiveRecord::findOne(Array) #5 [internal function]: humhub\modules\fcmPush\controllers\TokenController->actionUpdate() #6 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #7 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #8 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('update', Array) #9 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('fcm-push/token/...', Array) #10 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/index.php(25): yii\base\Application->run() #12 {main}

**UPDATE:** HERE IS THE PROBLEM
Yii Migration Tool (based on Yii v2.0.32)

Total 1 new migration to be applied:
	m190819_210853_initial

*** applying m190819_210853_initial
    > create table fcmpush_user ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'
The SQL being executed was: CREATE TABLE `fcmpush_user` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`token` varchar(255),
	`user_id` int(11) NOT NULL,
	`created_at` datetime DEFAULT NOW(),
	`updated_at` datetime
) (/var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `f...')
#1 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('CREATE TABLE `f...')
#2 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/modules/fcm-push/migrations/m190819_210853_initial.php(20): yii\db\Migration->createTable('fcmpush_user', Array)
#4 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(114): m190819_210853_initial->safeUp()
#5 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): yii\db\Migration->up()
#6 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(200): yii\console\controllers\BaseMigrateController->migrateUp('m190819_210853_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#8 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('up', Array)
#11 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/humhub/commands/MigrateController.php(184): yii\console\Controller->runAction('up')
#12 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll()
#13 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase()
#14 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('database', Array)
#17 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/informati...', Array)
#18 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#19 /var/www/vhosts/friendweb.nl/test2.friendweb.nl/humhub/index.php(25): yii\base\Application->run()
#20 {main}
*** failed to apply m190819_210853_initial (time: 0.003s)

0 from 1 migrations were applied.

**Comment by luke-** [comment]
Can you please create an issue in the module repo here: 
https://github.com/humhub-contrib/fcm-push

**Comment by karimbernardet** [comment]
Hi
Got this error too (same config)
Cheers
Karim

**Comment by karimbernardet** [comment]
Hi

Was it fixed please ?

Cheers

Karim

**Comment by ArchBlood** [comment]
@karimbernardet make sure that you check your MySQL and MariaDB see [docs](https://docs.humhub.org/docs/admin/requirements/#database) for minimum requirements

Also check the community for such things as it was also reported there
https://community.humhub.com/s/general-discussion/?contentId=223849
