### ISSUE TITLE
Send message without clicking a button

### ISSUE THREAD

**Issue by hramrach** [humhub/humhub#3863]
### Is your feature request related to a problem? Please describe.

When sending a message you have to mouse to "Send" button and press it  after you have just typed the text.

### Describe the solution you'd like

Many messaging systems have an alternate shortcut for sending message like Ctrl+Enter or Shift+Enter or automatically coalesce consecutive messages sent by the same user which are sent simply by pressing Enter.

### Describe alternatives you've considered

It is sometimes possible to press Tab to activate the "Send" button which is slightly less jarring than having to grab a mouse but it does not seem to work reliably. Even when it works there is no visual feedback that the button is activated, it is not obvious that this is supposed to work, especially with the Send button displayed inside the text edit area.

**Comment by buddh4** [comment]
You should be able to submit by `Crtl + s` since HumHub 1.4. Currently this is not configurable `Ctrl + Enter` is reserved for hard breaks.

**Comment by hramrach** [comment]
it's useless when not discoverable

**Comment by hramrach** [comment]
Unsurprising Ctrl+s invokes browser save dialog. There is absolutely no way to tell this is supposed to send the message and it does not work.

**Comment by buddh4** [comment]
Works fine for me, can you recreate the issue on the [Community](https://community.humhub.com/)? Just type something on your profile post input (or comment) and press `Ctrl+s`. If this does not work, tell me which browser / operating system you are using.

> There is absolutely no way to tell this is supposed to send the message and it does not work.

Now you know... An info dialog for the editor would be great, there is already a feature request for this. And as I said this may be configurable in the future.

**Comment by hramrach** [comment]
It works on the community humhub.

**Comment by dreua** [comment]
Come on, Ctrl+Return or Shift+Return or, if you must, Ctrl+Shift+Return is a *very* common shortcut for sending messages, can we please have it in Humhub? (Ctrl+s is save in almost all applications and reassigning it to send is bad UX imo.)

If no: Would it be possible to create a Plugin just for this shortcut? I'd install it and donate a Beer to the dev!

**Comment by dreua** [comment]
Test

**Comment by ArchBlood** [comment]
HumHub uses control + tab to send

**Comment by dreua** [comment]
> HumHub uses control + tab to send

Ctrl+Tab switches tabs in my Firefox, it doesn't send any humhub messages. Ctrl+S works for sending but I would rather not remember a special shortcut for each application when a common solution exists and would be usable.

**Comment by dreua** [comment]
My use case is the chat / PMs. Ctrl+S for saving posts is acceptable, but when it comes to comments I think that Ctrl/Shift+Return would still be the better choice in all cases. Feel free to support both.

**Comment by luke-** [comment]
@dreua There is a open issue here: https://github.com/humhub/humhub/issues/1454

**Comment by dreua** [comment]
> @dreua There is a open issue here: #1454

Thanks, my search terms only found this closed issue.
