### ISSUE TITLE
User logged publish as another user (the big confusion)

### ISSUE THREAD

**Issue by st5000** [humhub/humhub#3867]
Some users logged (with session opened long time ago) (?) publish content in place of another user, resulting in a big confusion.

This behavior appear sometimes since working in SSL termination. Tested and confirmed with or without Redis cache enabled.

Workaround: User must logout and login again to recover his identity.

**Comment by luke-** [comment]
Unfortunately I can't really trace this behaviour and it probably has more to do with your web server/proxy/SSL setup than with HumHub.

Can you perhaps provide steps to reproduce?

**Comment by st5000** [comment]
No step to reproduce since appears randomly but one thing is almost certain is sessions that have been open for a long time are mainly impacted.

BTW, I never managed to force closure/expiry of HumHub session, even by deleting all entries in database and all PHP session files. HumHub users always still logged. I think the root cause is near there (Yii Framework ?)

Another thing: On ±250 rows in user_http_session, user_id is almost set to NULL. Only 3 have a value. Never found any documentation regarding this.

**Comment by luke-** [comment]
When a session is removed from the "user_http_session" table, the session is also terminated.
However, if the user uses the "Remember me" function, a new session is automatically created.

A session is also created for visitors who are not logged in. (User ID = Null) This is used for security features such as CSRF or Captchas or also to save the language selection.

Some web crawlers or other bots may be the reason for so many sessions here.

**Comment by st5000** [comment]
Is there a way to force deletion of a session with "Remember me" flag ? It would be a temporary solution until the bug is found.

**Comment by luke-** [comment]
I don't know. Maybe the Yii2 forum can help here?

But back to the original problem: I really don't think the problem has anything to do with HumHub or Yii2.  Probably your proxy server caches/shares the cookie/session id somehow?

**Comment by st5000** [comment]
Yes, I think so BUT don't know why since this setup works smoothly with 10 other services (who do not use the Yii2...) also using php sessions.

Looking for a workaround to mitigate the problem, is there a way to reduce _identity expires value which is currently fixed to 1 month ?

**Comment by luke-** [comment]
This is really weird. Can you please reopen the ticket if you have any updates here?

You can rename or modify the cookie here (protected/config/web.php):
```
   'components' => [
        'user' => [
            'identityCookie' => [
                'name' => '_identity',
                //'expire' => timestamp
                'sameSite' => PHP_VERSION_ID >= 70300 ? yii\web\Cookie::SAME_SITE_LAX : null,
            ],
        ],
    ]
```

**Comment by st5000** [comment]
Thanks. I'll try and keep you informed.

**Comment by st5000** [comment]
Changed expiry time. Too early to notice a difference but found an additional detail that may help:

User C connected, user C see user B in profile (top right) and user C publish as user A.

**Comment by st5000** [comment]
@luke- Changed expiry time. Too early to notice a difference but found an additional detail that may help:

User C connected, user C see user B in profile (top right) and user C publish as user A.

**Comment by st5000** [comment]
@luke- It's normal that user_http_session.id value differ from md5 hash ?

Buggy session have id like `pl35n1i18rlihsffe66aok11bu` and working session have id like `0dc97fcdbe5bb30481073ab0d1b860f9`
