### ISSUE TITLE
Cannot tell what version of humhub I am using

### ISSUE THREAD

**Issue by hramrach** [humhub/humhub#3869]
### What steps will reproduce the problem?

Log in

### What is the expected result?

An about option somewhere in menu or fineprint in the page showing humhub version.

### What do you get instead?

no version information

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | unknown
| PHP version      | unknown
| Operating system |unknown

**Comment by buddh4** [comment]
There is `Administration -> Information -> About HumHub`

**Comment by hramrach** [comment]
Don't see any Administration

**Comment by buddh4** [comment]
![grafik](https://user-images.githubusercontent.com/9800854/74739861-099c6480-525a-11ea-8978-98c0e6072651.png)

**Comment by hramrach** [comment]
yes, that link is not there

**Comment by buddh4** [comment]
As long as your are logged in with an admin account you should see the menu item.

**Comment by hramrach** [comment]
I am not
