### ISSUE TITLE
Login page / redirection not functionally after change of PHP (5.6 -> 7.2)

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#3876]
Hello,

I have a running instance of humhub v. 1.3.20 that works fine.
I have to change the PHP version on the webserver due to ending support and switched from PHP 5.6.40 to PHP 7.2.11 / 7.2.19 / 7.2.23 and after that the login page is not displayed correctly. It says:

```
Oops ... you may have gone the wrong way.
An internal error occured.

Return to the overview (button)
```

When I click the overview button, then the login page is shown. After login the same message again 
"Oops...", but I can access internal content, the humhub menue is shown.

So what are my steps:

**PHP 5.6**
1. I load the page https://humhub.myserver.org (which works fine) and redirects me to
2. https://humhub.myserver.org/index.php?r=user%2Fauth%2Flogin
3. I log in and everything is fine

**PHP 7.2**
1. I load the page https://humhub.myserver.org and get the "Ooops"-error mentioned above
2. I click the "return to the overview" button and the site https://humhub.myserver.org/index.php?r=user%2Fauth%2Flogin is shown.
3. I log in and get the "Ooops..."-message again, but can see the internal humhub menue and start using humhub.

Any ideas?

Thanks!

Regards,

**Comment by buddh4** [comment]
Check error logs at `Administration -> Information -> Logs` or under `protected/runtime/logs` you'll probably be able to access the admin interface: https://humhub.myserver.org/index.php?r=admin

**Comment by blu-IT** [comment]
Hi,

logs tell me this:

```
Error  Sat, 22 Feb 2020 11:16:24 +0100  yii\base\ErrorException:32
yii\base\ErrorException: Module 'intl' already loaded in Unknown:0 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main} 
```

**Comment by buddh4** [comment]
Seems to be related with your PHP environment not with HumHub itself. Somehow the `intl` php module is loaded twice. Perhaps check your `php.ini` configuration and/or `mods-available` directory for any duplicates. I'll close this now since its not humhub related.
