### ISSUE TITLE
Security Breach - When user name same as domain name

### ISSUE THREAD

**Issue by CSPSolutions-Dev** [humhub/humhub#3878]
### What steps will reproduce the problem?

1- Install on domain other than .com for example patient.health
2- Create admin username patient.health
3- The system will automatically login to admin user patient.health on postback of empty user name password, or even any fake credentials, exposing the admin user to all users

Causing major security breach

### What is the expected result?

Expect only users with the correct credentials to login, not anyone who enters any credentials, logs to the administration

### What do you get instead?
Any user entering anything will automatically be logged by the system as "patient.health" admin user, even if you enter nothing just on refresh of the login page it auto logs in, or even entering  user blabla , password bla it goes to admin "patient.health"  

This is a major security breach!

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.1
| PHP version      |  7.1
| Operating system | Linux - SiteGround Shared

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Please send us any security relevant issues directly via e-mail.
https://github.com/humhub/humhub/blob/master/CONTRIBUTING.md#report-an-issue
