### ISSUE TITLE
CSS presentation issue for tables wider than the container and videos missing borders.

### ISSUE THREAD

**Issue by areasas** [humhub/humhub#3887]
### What steps will reproduce the problem?
1. Create a post including a table larger than the container.
2. Create a post including a video

### What is the expected result?
1. Presenting and editing the table content which is not showed.
2. Presenting the media-player container with borders.

### What do you get instead?
1. Table is showed partially (the right side is hidden) both during the presentation and editing.
2. Posts with videos only show the "play" symbol. When you click it then it enlarge to show the contents.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | from 1.3.2 till current 1.4.2
| PHP version      | PHP 7.0
| Operating system | Safary/Firefox/Chrome/Opera MacOs 10.13.6

> Note: To solve, I always have to duplicate the theme naming it HumHub_Plus and add these declarations in theme.css o fHumHub_Plus:

`
.media,.media-body {
  overflow: hidden !important
}

[data-ui-markdown],
[data-ui-richtext] {
  overflow-x: auto;
  overflow-wrap: break-word
}

audio,canvas,progress,video {
  display: inline-block;
  vertical-align: baseline;
  border: solid 1px #000;
  max-width: 100%;
  height: auto
}
`

1. Presentation (HumHub theme)
![Schermata 2020-02-29 alle 18 59 59](https://user-images.githubusercontent.com/2221328/75613018-41908b00-5b29-11ea-8870-51e6c5f31456.png)

1. Presentation (HumHub_Plus theme)
![Schermata 2020-02-29 alle 19 00 47](https://user-images.githubusercontent.com/2221328/75613019-42c1b800-5b29-11ea-8bf3-4111c7227d1b.png)

1. Editing (HumHub theme)
![Schermata 2020-02-29 alle 19 01 34](https://user-images.githubusercontent.com/2221328/75613028-62f17700-5b29-11ea-8cd3-2dd586b93a3c.png)

1. Editing (HumHub_Plus theme)
![Schermata 2020-02-29 alle 19 01 11](https://user-images.githubusercontent.com/2221328/75613029-6684fe00-5b29-11ea-9b78-d104481e2e18.png)

2. Media-player (HumHub theme)
![Schermata 2020-02-29 alle 19 02 46](https://user-images.githubusercontent.com/2221328/75613039-87e5ea00-5b29-11ea-9448-af559dec5b5b.png)

2. Media-player (HumHub_Plus theme)
![Schermata 2020-02-29 alle 19 03 35](https://user-images.githubusercontent.com/2221328/75613040-916f5200-5b29-11ea-920f-dfc544253f12.png)

**Comment by buddh4** [comment]
Thanks!

**Comment by areasas** [comment]
I am honoured!
