### ISSUE TITLE
SiteIcon overwrites 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#3889]
Add the possiblity to overwrite the automatic site icon handling (1.4+) with individual files using configuration. e.g. transparent image files for in app usage 

See also:
https://community.humhub.com/content/perma?id=208742

**Comment by yurabakhtin** [comment]
@luke- As I understand theme may appends icon tags like `<link rel="icon" type="image/png" href="some_favicon.png">` in `<head>` from the file `themes/{THEME_NAME}/views/layouts/head.php`.
Also new icon setting(v1.4+) from "Administration > Settings > Appearance" adds same tags in `<head>` too by code https://github.com/humhub/humhub/blob/master/protected/humhub/modules/web/pwa/widgets/SiteIcon.php#L125-L137:

```
public static function registerMetaTags(View $view)
{
    ...
    $view->registerLinkTag(['rel' => 'apple-touch-icon', 'href' => static::getUrl(152), 'sizes' => '152x152']);
    ...
    $view->registerLinkTag(['rel' => 'icon', 'href' => static::getUrl(192), 'sizes' => '192x192']);
    ...
}
```

So we should not register the meta tags by class `SiteIcon` if some icon is defined in configuration.
Could please tell me what configuration you mean?
Thanks.

**Comment by luke-** [comment]
At the moment the handling works like this:

1.) User uploads a new icon (Administration -> Settings -> Appereance)
2.) The original icon is stored at: /uploads/icon/icon.png
3.) SiteIcon::getUrl(128) - creates (if needed) and stores a scaled version of the icon, and returns the url (currently at: assets/siteicon/128x128.png)

Now we want to allow an admin to prevent automatic scaling and upload an icon himself.
This should be done, by manually uploading a image to /uploads/icon/128x128.png

Now Step 3:) need to check if the image exists and returns the uploaded variant url or fallback to the default behavior.

I hope I could clarify the issue.

**Comment by yurabakhtin** [comment]
@luke- Yes, thanks for the clear instruction, please check PR https://github.com/humhub/humhub/pull/4470.
