### ISSUE TITLE
Mixed content warning - Resources not loaded over https when served behind reverse proxy

### ISSUE THREAD

**Issue by jplette** [humhub/humhub#3901]
Resources that someone uploads like images, videos etc are not loaded over secure https.
Chrome is claiming about mixed content and says the page is unsecure.

`Mixed Content: The page at 'https://mydomain/dashboard' was loaded over HTTPS, but requested an insecure image 'http://mydomain/file/file/download?guid=b74699a8-c2ab-45d8-9404-09625b24575f'. This content should also be served over HTTPS.`

HumHub is running behind a revers proxy (HA Proxy) which is doing the SSL termination.
It seems that only resources are affected which a user uploads in a post. All other resources like logo, userimages and other resources directly from humhub are loaded correctly.

### What steps will reproduce the problem?
Run HumHub behind a reverse proxy (HA Proxy) which is doing the SSL termination. Load the dashboard and check the google chrome console. 
An image which was posted before is loaded with http and not with https

### What is the expected result?
Resources should be loaded over https to prevent mixed content warnings. Chrome is claiming an unsecure page even if it is served over https

### What do you get instead?
The resources are loaded over http

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.3
| PHP version      |  7.2.24
| Operating system | Ubuntu Docker

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/3815
