### ISSUE TITLE
Administration > Mailing does not exists

### ISSUE THREAD

**Issue by e-edgren** [humhub/humhub#3902]
Hi.

In the installation guide, you can go to [Administration > Mailing](https://docs.humhub.org/docs/admin/installation#e-mail-configuration) to change SMTP server something-something. But that option doesn't exists at all for me.

Has this menu been removed?

**Comment by luke-** [comment]
The correct click path is "Administration -> Settings -> Advanced -> Email".

**Comment by e-edgren** [comment]
Then I suggest that the real path mentioned in the guide will be changed to "Administration -> Settings -> Advanced -> Email". However, I can't change any SMTP providor on that page. I only have the following settings:

- E-Mail sender address
- E-Mail sender name
- Mail Transport Type
  - File
  - PHP
  - SMTP

SMTP Options:
- Hostname
- Username
- Password
- Port number
- Encryption
- Encryption Options
  - Allow Self-Signed Certificates?

However. I have selected SMTP in the select field on that page and filled the same information in the text fields as I have done for PHPMailer on my other projects and it's working perfectly there. But on HumHub it doesn't work at all! I get the following error message: `Swift_TransportException: Connection could not be established with host smtp.gmail.com [Connection timed out #110]`.

Do I get this error message because I am required to have SendGrid, Postmark, Amazon SES or Mailgun installed on my server? If yes, why? And again, if yes, can I use PHPMailer for it?

If I choose PHP in the select instead, the website report to have sent the email, but nothing is coming through. I haven't changed the mail settings in `php.ini`. It's perhaps because of that? I would prefer to use the SMTP option on HumHub, though. Easier to configure.

**Comment by luke-** [comment]
The guide should be fixed: https://docs.humhub.org/docs/admin/installation#e-mails

Please use our community regarding setup questions.
