### ISSUE TITLE
Humhub 1.4 bug : Don't show emojis when typing the `:` character

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#3906]
### What steps will reproduce the problem?

In French, you need to have a space before `:` char.

So when typing text, we constantly have the emojis window opening. Since Humhub 1.4, if you continue typing, your text appears in the search input for emojis... So you have to close manually (with the mouse) the window...

Please remove this feature, as we can add emoji with the emoticons button in the richtext bar menu.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.3

**Comment by buddh4** [comment]
Do you think it would be sufficient to remove only the focus? Then the behavior would be the same as before?

**Comment by funkycram** [comment]
Yes, thanks !

**Comment by funkycram** [comment]
Tested (after recreating the dist directory with grunt) and it works perfectly, thanks for your reactivity !

**Comment by funkycram** [comment]
I have updated to Humhub 1.4.4 (automatic update), and the problem is till there :
![image](https://user-images.githubusercontent.com/23310825/77512193-cd6cad00-6e72-11ea-8262-ca87c80c1336.png)

**Comment by funkycram** [comment]
I open this issue again because it is not solved.
I have installed a brand new Humhub 1.4.4 and it is still not possible to write : without having to close the emojis windows with the mouse (event ESC key doesn't work !).

@buddh4 [commit](https://github.com/humhub/humhub/commit/3470b04848c1522944a72aa5b2cdc619935f1deb) works (but not in all environments) but doesn't seem to be integrated in Humhub 1.4.4

Thanks

**Comment by buddh4** [comment]
What do you mean by "not all environments"?
I'am not sure why this was not part of 1.4.4, seems somehow the npm version did not update.

**Comment by funkycram** [comment]
OK, I have investigated a bit.

When I have patched Humhub 1.43 with your modifications, I have done npm build in protected/vendor/npm-asset/humhub-prosemirror-richtext and reloading Humhub cache it worked.

But it works only in debug mode, with theses lines in index.php :
```
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
```

If I comment theses lines, I don't have humhub-editor.js loaded, as this line is not in the source code :
```
<script src="/assets/6a2e814c/humhub-editor.js?v=1585755252"></script>
```

And the patch doesn't work.

But with Humhub 1.44, the patch doesn't work at all, even in debug mode.
Thanks.

**Comment by buddh4** [comment]
Hmm, maybe an issue with the production asset build. @luke- do you think the npm issue in the 1.4.4 somehow messed up the production asset build?

**Comment by funkycram** [comment]
Yes, I think you didn't do this command before releasing Humhub 1.4.4 for rebuilding `@humhub/static/js/all-*.js` :
```
php yii asset humhub/config/assets.php humhub/config/assets-prod.php
```

**Comment by luke-** [comment]
Does it work with the 1.5-beta1?

**Comment by funkycram** [comment]
Yes, on 1.5-beta1 it is fine.
