### ISSUE TITLE
Display update stream badge once an update is available

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3924]
### Feature description:

Once a content update is available for the current stream (Space/User/dashboard), render an update badge which prepends new content on top of the stream when clicked.

### Concept:

In case an update is avialable and the top of the stream is currently not visible, render the badge with `position:fixed` on the stream top for a few seconds and then attach it to the top of the stream. If the top of the stream is visible immediately attach the badge to the top of the stream:

Floating:

![grafik](https://user-images.githubusercontent.com/9800854/76884636-47eb6a80-687e-11ea-9145-b779bdea54a2.png)

Attached:

![grafik](https://user-images.githubusercontent.com/9800854/76884300-cbf12280-687d-11ea-9e0c-e80adc957c3f.png)

Only render badge if:

 - Space/User/Dashboard wall stream
 - No stream filters are active
 - Not a single entry stream (permalink)
 - Live update actually contains new content for this container and stream

#### Backend:

- [x] Implement `StreamQuery->$to` field and query (similiar to `from`)

#### Frontend:

- [x] Keep track of the last loaded top entry as `Stream.topEntry` which
    - is not a pinned entry
    - was not created in the same window (post form)
- [x] Listen to `humhub:modules:content:live:NewContent` in `Stream` widget
- [x] Implement `Stream.isUpdateAvailable(events)` to determine if there is an actual update present for this stream
- [x] Implement `Stream.loadUpdate()` used to request updates based on the `to` parameter and the id of `topEntry`
- [x] Implement `Stream.loadUpdate()`
- [x] Implement `Stream.options.autoUpdate` for streams with auto update mechanism e.g. activity stream

### To discuss
 - Badge label text
 - Styling

**Comment by Semir1212** [comment]
The indicator seems rather small, might be worth considering changing that it in the future.

**Comment by luke-** [comment]
@orangiene What do you think?

**Comment by orangiene** [comment]
@luke- @buddh4 
I like the idea, the position is fine. It should be more prominent and my contrast checker dislikes the colour combination. I designed an alternate version. If you like it, I can upload it on zeplin.

![02_display-update-stream](https://user-images.githubusercontent.com/62644500/79247255-94749680-7e7a-11ea-8aba-52fa4d247b0e.jpg)

**Comment by ArchBlood** [comment]
Would probably be best to change the color in accordance with an info tag like the original but I like the idea behind @orangiene's, would also be easier on mobile devices.
