### ISSUE TITLE
Translations not updated in enterprise module since Humhub 1.4

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#3931]
Humhub 1.4
Enterprise module version 1.4.2

Some translations are not updated in enterprise module since Humhub 1.4

Example :
In `modules/enterprise/themes/enterprise/views/space/widgets/membershipButton.php`, `Yii::t('SpaceModule.widgets_views_membershipButton', 'Accept Invite')` should be `Yii::t('SpaceModule.base', 'Accept Invite')`

**Comment by funkycram** [comment]
And submenu doesn't show the possibility to deny an invitation, `display:none` is still active :
![image](https://user-images.githubusercontent.com/23310825/76995294-f27f8e00-694f-11ea-8cc0-a3a8e4fd4479.png)

**Comment by luke-** [comment]
Should be fixed with Enterprise Module 1.4.4 or EnterpriseTheme 1.0.7
