### ISSUE TITLE
Lacking translation in admin module for Humhub 1.4

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#3933]
In `protect/humhub/modules/admin/messages/xx/notification.php` this translation is lacking :
```
'{displayName} added you to group {groupName}'
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4

**Comment by luke-** [comment]
The translation can be now modified at translate.humhub.org

The translation will then be available in HumHub version 1.5 (beta releases next week).
