### ISSUE TITLE
Problem with registration

### ISSUE THREAD

**Issue by ZentrenFR** [humhub/humhub#3935]
Good morning, sir,

I'm a brand new user of HumHub! I've just finished setting up HumHub on my site except that the problems are starting! I have when I want to create an account on it, I get an error message that redirects me to my site and in my log I get the 2 errors below (I display 1 error because the other one, I have confidential information).

This is HumHub - Community Edition : version: 1.4.3

---

yii\base\ErrorException: Interface 'Swift_Filterable' not found in /home/breizhso/public_html/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php:16 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}

---

Anyone have any ideas on how to solve the problem ?

**Comment by luke-** [comment]
Which PHP Version are you using?
