### ISSUE TITLE
2nd level commenting

### ISSUE THREAD

**Issue by tedstrauss** [humhub/humhub#3938]
### Is your feature request related to a problem? Please describe.

UX issue. Not a problem but an improvement.
Users of a certain social media platform are accustomed to having 2nd level commenting. 
It allows for more flexible and effective converstaions.
HumHub's comments are 1-dimensional, by comparison.

![2nd-lvlb](https://user-images.githubusercontent.com/930560/77318786-0c202d00-6ce4-11ea-8539-da8d5b8c45c7.png)

### Describe the solution you'd like

2nd level commenting, so each comment in a thread can have it's own sub-thread.
No, this is not meant to lead towards 3rd level or 4th level commenting. 2nd level is plenty!

### Describe alternatives you've considered

After using humhub with a community for 9 months, I don't see an alternative to this.

**Comment by caveman86** [comment]
does anyone reach to any point to allow me continue or contribute with him from that point ?

**Comment by tedstrauss** [comment]
sorry what do you mean?

**Comment by caveman86** [comment]
I meant that if anyone has some progress for this feature .. then I can working with him as I need this feature too ..

**Comment by tedstrauss** [comment]
You can ask them on the community forum here https://community.humhub.com/content/perma?id=211921

**Comment by luke-** [comment]
@caveman86 Would be great if you want to work and contribute this feature! 

We can discuss development-related topics here in this GitHub issue.

**Comment by caveman86** [comment]
ok then , thanks for reply .. 
now I am trying to create an dummy module to get knowledge of basic concepts 
but I have two  questions 
first : what is the best way to show errors and debugging  as I tried a lot of ways like : var_dumb , print_r , Yii::warning , VarDumper::dump , Yii::trace and die() but without any results !
second: what is your initial suggestion to do that ? , should we build a new separate module ? or update the existing one ?

**Comment by buddh4** [comment]
You should be able to use print_r etc just fine, ideally configure xdebugger within your ide. Multi level commenting should be part of the core. We are currently working on improving the stream styling, maybe we should include the nested comment feature and consider it for HumHub 1.6.

**Comment by caveman86** [comment]
ok then .. @buddh4 
I am ready to any help .. 
if you want , assign me a small tasks to make me involved .. 
I am working on new module for reactions "like facebook reactions" ..
so please advice me how can I help you , and which time do you expect to release that feature "nested comment" ? 
Regards

**Comment by tedstrauss** [comment]
This is really exciting! Thank you.

What release will this be part of?

**Comment by luke-** [comment]
Is already included in Beta 1.6. Hopefully the 1.6 will be released as a stable version in the next days.

**Comment by caveman86** [comment]
thanks a lot guys ..
I needed this feature ..
additionally , I have worked a lot on rest api plugin as it was poor , that allow me to develop a mobile application by Flutter ..
I hope this project grow up more and more :)

**Comment by luke-** [comment]
Great, feel free to contribute your features back to the Rest API module!

Thank you!

**Comment by caveman86** [comment]
sure .. 
as soon as finish my project after 10 days .. 
I will be  honourable to contribute with u .. :)

**Comment by tedstrauss** [comment]
upgraded to 1.6 & testing the new feature.
there's no submit/send button on the 2nd level comment.

is it because i'm replying to my own comment?

![image](https://user-images.githubusercontent.com/930560/89248149-0402c300-d5dd-11ea-9253-f71aea9f2215.png)

**Comment by klauswagner** [comment]
> upgraded to 1.6 & testing the new feature.
> there's no submit/send button on the 2nd level comment.
> 
> is it because i'm replying to my own comment?

![image](https://user-images.githubusercontent.com/7679272/89256192-d3924780-d623-11ea-8be0-b29cc548faa4.png)

@tedstrauss You should check your theme and recompile your CSS package, see https://docs.humhub.org/docs/theme/css/#compile-css-package.

In HumHub 1.6.1 there was also a fix for Dropdown https://github.com/humhub/humhub/issues/4282

**Comment by ArchBlood** [comment]
Also applies to the default theme, as for if it is a cache issue or not, I've already cleared browser and server cache and problem still there.
![Screenshot_2](https://user-images.githubusercontent.com/35392110/89261123-8dc18900-d5fb-11ea-9cd3-f903a476e237.png)

**Comment by luke-** [comment]
Fyi: I have opened a separate issue for the bug. Was the problem already there with the 1.6.0?

**Comment by tedstrauss** [comment]
@ArchBlood how do you clear the server cache?

**Comment by ArchBlood** [comment]
> @ArchBlood how do you clear the server cache?

`php yii cache/flush-all` in your protected directory.
In my case I also had to do this via Linux command as well
```shell
# echo 1 > /proc/sys/vm/drop_caches
# free -m
```

**Comment by tedstrauss** [comment]
Working for me in version 1.6.2 release.
