### ISSUE TITLE
Stream input field overlays the dropdown list when pressing the notification icon

### ISSUE THREAD

**Issue by J0000** [humhub/humhub#3948]
![humhub-bug](https://user-images.githubusercontent.com/8221545/77661554-160f8d80-6f7b-11ea-86ba-19e9ea43acb2.png)

### What steps will reproduce the problem?
Klicking the Notification icon 
### What is the expected result?
show dropdown without overlays
### What do you get instead?
overlaying input box when actually in a space
### Additional info
maybe css z-index will solve the problem?
| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.3
| PHP version      | default (SaaS)
| Operating system | Linux/Win10

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Hmm, unable to reproduce

![scrn-2020-03-26-16-29-36](https://user-images.githubusercontent.com/4736168/77665028-596bfb00-6f7f-11ea-9927-0bf4fee35604.png)

**Comment by J0000** [comment]
There is a second theme.css in /assets/67fd3af1/css/theme.css?v=1584996516 
where 

.ProsemirrorEditor .ProseMirror-menubar-wrapper {
    z-index: 200
}

Maybe because of individual theme?

**Comment by J0000** [comment]
Ah, i haven't seen the information, that you have to recompile your own theme after every update. Perhaps this information could be set more prominent in the SaaS-Version?
