### ISSUE TITLE
The cron job for the regular tasks (cron) does not seem to work properly, after setting up queue worker

### ISSUE THREAD

**Issue by adrianharabula** [humhub/humhub#3949]
### What steps will reproduce the problem?
Run queue worker with `php yii queue/listen`.

### What is the expected result?
Background jobs to work, and they work.

### What do you get instead?
But I get this warning in HumHub interface:
![image](https://user-images.githubusercontent.com/2271038/77663313-9c30d180-6f85-11ea-9686-6a6ac13899b2.png)

### Additional info
I'm not sure if I have to have them both cron and queue worker or only one of them.
| Q                | A
| ---------------- | ---
| HumHub version   | 1.4.4
| PHP version      |  PHP 7.1.33
| Operating system | docker on linux

**Comment by luke-** [comment]
Did you installed the ``php yii cron/run``cronjob?

**Comment by adrianharabula** [comment]
As I'm running in docker container, `php yii cron/run` seems to run and exit the container. if the cron is still mandatory need to use an additional customization for docker. Thanks for fast reply.
