### ISSUE TITLE
Include non profile content to users profile timeline

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#3950]
### Is your feature request related to a problem? Please describe.

Many user timelines are empty because users are active in Spaces but do not post directly on their profile.

### Describe the solution you'd like

To change this, it would be good if all content created by the user is available in his profile. (Optional)

### Describe alternatives you've considered
-

**Comment by st5000** [comment]
Really annoying for some people. Adding admin option to disable this this feature will be great.

**Comment by luke-** [comment]
@st5000 to disable, change your protected/config/common.php 

```
'modules' => [
   'user' => [
       'includeAllUserContentsOnProfile' => false
   ],
]

```

**Comment by ArchBlood** [comment]
Should do something like how the [stream core module](https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/stream/Module.php#L23) does for excluded content or something similar, which is related to the other issue @st5000 is having. :thinking:
