### ISSUE TITLE
Dynamic Space guid url

### ISSUE THREAD

**Issue by abhijit-iterate** [humhub/humhub#3951]
I wanted to add dynamic space url inside Invite.php, sendInviteMail() function.
Where invite is sent to the user, I did this
$spaceUrl = Url::to(['/space/space', 'cguid' => '6d17b403-4626-401e-b148-76a8fa928277'], true);

And passed it as 'registrationUrl' => $spaceUrl .

So user gets the invite and after login he's redirect to that particular space.

So instead of static value here I wanted to pass dynamic space guid so it will be redirect to the new space from which invite request is sent.

Thanks.

**Comment by luke-** [comment]
You can use the Space attribute to create a url.

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/Invite.php#L162 

e.g. $this->space->createUrl()

**Comment by abhijit-iterate** [comment]
> You can use the Space attribute to create a url.
> 
> https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/Invite.php#L162
> 
> e.g. $this->space->createUrl()

Thanks Luke, It solved my issue I added createUrl($this->space->guid);
Which gave me particular guid id of the space.
Works like charms.
Thank you again.
