### ISSUE TITLE
Jitsi meet module for easy integration of videoconferencing 

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#3957]
Hello,

I know that it's not a big deal to send around a link for "**Jitsi meet**" link for videoconferencing,
but I like the way it has been integrated/solved in slack for example.

I think it would also be a nice feature to offer _space-specific_ and _individual_ jitsi-meet integration for Humhub. Especially in these times...

Regards

**Comment by luke-** [comment]
Can you please reopen the issue here: 
https://github.com/humhub-contrib/jitsi-meet

Also some more details (screenshots of Slack) would be interesting.
