### ISSUE TITLE
word-break issue on space navigation

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3972]
### What steps will reproduce the problem?

Create a custom space page with a rather long single word name

### What is the expected result?

Some sort of word break in the space navigation

### What do you get instead?

![grafik](https://user-images.githubusercontent.com/9800854/78561177-8fc73700-7817-11ea-95dc-9e8ea4da97d8.png)

### Solution

Use of `word-break: break-all` style

**Comment by MasterMindNET** [comment]
I have fixed this issues by addting this style to the `.layout-nav-container` in `static/less/base.less` file.
![image](https://user-images.githubusercontent.com/22347676/90316099-cf6e0000-df28-11ea-9286-a11762227b63.png)

Here is similar PR:
https://github.com/humhub/humhub/pull/4321
I have just encountered the same problem and here is the PR for the `.panel` class fix with a screenshot attached, so, please take a look.
https://github.com/humhub/humhub/pull/4324
