### ISSUE TITLE
Unable to scroll MY SPACES list on mobile device

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#3977]
The list in MY SPACES drop-down menu cannot be scrolled.

Confirmed with Chrome and FireFox on Android 9.

The same happens on [community sites](https://community.humhub.com/).

![Screenshot_20200408_180149](https://user-images.githubusercontent.com/38252517/78765638-38fe6080-79c3-11ea-9cfb-7295e6dd928c.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.0-beta.1
| PHP version      | 7.3

**Comment by st5000** [comment]
I confirm this.

**Comment by buddh4** [comment]
Seems to be related with the nicescroll version in use. The version in use at 1.5 is 3.6.8 whereas the version in use is 3.6.6. This was probably due to the npm version. I'll test the latest version or otherwise revert back to 3.6.6.

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/issues/3983
