### ISSUE TITLE
Compress or resize photos automatically on upload

### ISSUE THREAD

**Issue by davidtessier** [humhub/humhub#3978]
### Is your feature request related to a problem? Please describe.
Phones today take photos that are roughly 5mb to 20mb in size. This is eating up my server's hard drive space and slowing down loading times on the Dashboard

### Describe the solution you'd like
I would love it if HumHub could compress or re-size photos when uploaded to save space and improve dashboard loading times. 

This would have to be a configurable option because some users may not want it by default, but I sure do and I'm sure I'm not alone. 

### Describe alternatives you've considered
I was under the impression that what I'm asking for was accomplished with Image Magick commands - but there's no support or examples on the HumHub documentation on how to use it and after talking in #3521 I was told to create a feature request. 

I can't ask my users to pre-compress / resize their photos ahead of time because that's too technical for some of my users.

Thank you for considering this.

**Comment by st5000** [comment]
This is an old issue (#430) which has never been taken seriously.

**Comment by fsainovich** [comment]
Need this feature back again. David is correct.

**Comment by larsnsonsk** [comment]
I agree this is _extremely_ important.
Without resizing i can't use it productively, otherwise i run out off space in no time.
Hope we can solve this soon!  :)
