### ISSUE TITLE
Cannot use yii\helpers\Html as Html because the name is already in use

### ISSUE THREAD

**Issue by SameerRathod** [humhub/humhub#3986]
Hi,
post-upgrade  I am getting this error

Cannot use yii\helpers\Html as Html because the name is already in use

when clicking on myspace

**Comment by buddh4** [comment]
Please add the full error stack. Also add the version you updated to.

**Comment by SameerRathod** [comment]
No worries I commented that line in vim htdocs/protected/humhub/libs/ProfileBannerImage.php
error resolved

**Comment by buddh4** [comment]
Glad you could fix the issue, but perhaps tell us which line in which version, so we can fix the issue in the codebase.
