### ISSUE TITLE
Implement StrictController

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3990]
### Is your feature request related to a problem? Please describe.

Beside ContentContainerController there currently is only the base Controller class available, which does not use StrictAccess by default. StrictAccess handles guest user control if the guest mode is not active and currently needs to be manually set as follows:

```php
public $access = StrictAccess::class
```

Since the base Controller class is also in use in cases where non protected external access is required e.g. for sharing documents or jitsi meetings with non members. We should add a StrictAccessController which should be used for most non container related actions and adds strict access control by default and only use the base Controller if we need non protected access from non members.

**Comment by luke-** [comment]
Strict should be default in 1.6

**Comment by buddh4** [comment]
So we'll set strict access in the base humhub controller class. Should only require a small migration in rare cases.

**Comment by luke-** [comment]
Case Overview:

Case 1: Everybody (Not logged in)                                             (Login, Sharing)
Case 2: Logged in                                                                       (Primarily user actions)
Case 3: Logged in & Guests (if enabled)                                    (View stuff)
