### ISSUE TITLE
Invisible text in login-container less

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3993]
The login.less contains hardcoded colors for headlines h1,h2 making them invisible in 
richtext profile fields.

## What steps will reproduce the problem?

- Create a richtext profile field and allow it in the registration form.
- Register with new user
- Add headline to the richtext

### What is the expected result?

- The headline to be visible

### What do you get instead?

- The headline has the same color as background

### Additional info

Due to `login.less`:
```
  h1,
  h2 {
    color: #fff !important;
  }
```

**Comment by luke-** [comment]
1.5 or 1.6?
