### ISSUE TITLE
Live event legitimation array does not include followed users

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3994]
The live container legitimation includes followed spaces but not followed users at:

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/live/Module.php#L86

**Comment by fae7em** [comment]
@buddh4 Could you please explain it more?
As I checked when user A follows user B, user A can see user B profile posts and user B posts in common spaces in her/his dashboard. But if user B creates a public post in a public space that user A is not a member or follower of it, this post is not displayed in user A dashboard. 
does it your mean?

**Comment by buddh4** [comment]
This issue is related to live events, which are used for live updates in the frontend. E.g. when there is a new content in a space, all currently active users who are member of this space get a live event in the background. The ui then e.g. shows a new "New Updates" badge on the dashboard or the space stream.

The problem is, this currently does not work for followed users. So my frontend does not receive live update events from users I follow. [This](https://github.com/humhub/humhub/blob/1ee06c88ebb2fedb31b117bb3d9d14452682388e/protected/humhub/modules/live/Module.php#L49) function is responsible for fetching all containers and related visibilities used for the live event ditribution. We need to add a block for followed users and public visibility similar to the usage of [getFollowedSpacesQuery()](https://github.com/humhub/humhub/blob/1ee06c88ebb2fedb31b117bb3d9d14452682388e/protected/humhub/modules/live/Module.php#L83)

**Comment by buddh4** [comment]
Furthermore: It seems the `cache` argument is not even in use. If `cache` is false, this function should always do a reload and refresh the cache.
