### ISSUE TITLE
Profile: Introduce filter for profile only contents

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#3995]
### Is your feature request related to a problem? Please describe.

Since 1.5 all user contents are included in the profile timeline.
However, this makes direct profile content less visible. 

### Describe the solution you'd like

Add a filter to only include direct profile content. 
Make default of this filter flexibel.

### Describe alternatives you've considered
TBD

**Comment by buddh4** [comment]
Not sure about the naming of the filter:

![grafik](https://user-images.githubusercontent.com/9800854/86539858-44005880-bf00-11ea-989b-a63e965074b5.png)

**Comment by Semir1212** [comment]
- Show all posts
- Profile posts only

- I'm Involved
- Created by me
- With attachment

- Private
- Public
- Archived 

(Sort by)

- Creation date
- Last update

**Comment by buddh4** [comment]
So visibility (including archived) should be a radio selection i think. We should not include archived content, but rather only show archived content.
