### ISSUE TITLE
Missing strings for translation

### ISSUE THREAD

**Issue by hide-me** [humhub/humhub#4004]
**In the process of localizing HubHum into Russian, I noticed that these phrases are not in the files for translation. On each screenshot, the missing phrases are circled, the pages on which the phrases are present can be recognized by the icons and appearance, so I did not indicate the page names.**

### These lines will be in English no matter what language you switched to, because these lines are not in the translation files.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.X
| PHP version      | 7.X
| Operating system | In this case, it is doesn't matter

.
.
.

![0](https://user-images.githubusercontent.com/45032974/79459120-797d6000-7ffb-11ea-9016-35b666e43ba6.png)
![1](https://user-images.githubusercontent.com/45032974/79459129-7a15f680-7ffb-11ea-9b53-753f97340d82.png)
![2](https://user-images.githubusercontent.com/45032974/79459133-7bdfba00-7ffb-11ea-9fb6-7cf064e38c44.png)
![3](https://user-images.githubusercontent.com/45032974/79459136-7d10e700-7ffb-11ea-8d63-a4d7390f2771.png)
![4](https://user-images.githubusercontent.com/45032974/79459138-7e421400-7ffb-11ea-9995-b9c1ed12bfd8.png)
![5](https://user-images.githubusercontent.com/45032974/79459141-7f734100-7ffb-11ea-9571-71eb562c836a.png)
![6](https://user-images.githubusercontent.com/45032974/79459147-80a46e00-7ffb-11ea-8109-f749bd2bc06f.png)
![7](https://user-images.githubusercontent.com/45032974/79459153-81d59b00-7ffb-11ea-8c46-72deb6df5728.png)
![8](https://user-images.githubusercontent.com/45032974/79459158-8306c800-7ffb-11ea-902d-e89599d79c13.png)

**Comment by luke-** [comment]
Thanks for your issue.

- Can you please add an extra issue for Mail module (e.g. Conversations) related messages here: https://github.com/humhub/humhub-modules-mail

- Some Module Marketplace texts e.g. "Module categories" are only available in English yet.

-  Not sure if we can/should also translate the logging message category (application) or logging level status.

**Comment by ArchBlood** [comment]
Would also be nice to be able to also translate custom fields but that's pretty close to impossible as well, already tried implementing it myself. :thinking:

**Comment by hide-me** [comment]
> Can you please add an extra issue for Mail module
Sorry, but I didn't get it, for what I should do it?

> Some Module Marketplace texts e.g. "Module categories" are only available in English yet.
Maybe we should also add these strings to translation?
