### ISSUE TITLE
Some richtext images are embedded as Base64

### ISSUE THREAD

**Issue by samsheridan** [humhub/humhub#4008]
_Updated as a bug report with new information from the comments:_
### What steps will reproduce the problem?
Paste an image into Prosemirror and save the post.

### What is the expected result?
The image will be stored in the uploads directory.

### What do you get instead?
The image is stored in the database with the post's text in base64 format.

**Comment by akuckartz** [comment]
> potentially reduced performance, a larger caching requirement ..., larger ... backups, and even search indexing failure.
> ... but poses a long term performance issue for larger sites.

These statements are questionable. Can they be substantiated?

**Comment by samsheridan** [comment]
I noticed this after I was viewing a log and saw that adding a post to the search index failed because it was too large. It wasn't a long post. It just had a base64 image in it.

> "msg":"Exception writing document id 4a4ab91c-83c1-4ca8-a50f-5a883fc856fc to the index; possible analysis error: Document contains at least one immense term in field=\"message\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: '[redacted UTF8 codes]...', original message: bytes can be at most 32766 in length; got 159934. Perhaps the document has an indexed string field which is too large","code":400

More data in the database = larger SQL backups. I prefer to backup files separately and at different intervals because my 2 GB database is no trouble to back up, but 100 GB of user uploaded files is a lot to handle. I don't currently use incremental backups. My goal is to start hosting old uploads offsite, but that won't be possible if they're trapped in the database.

I configured MariaDB to cache tables in RAM for better performance. I don't think images are worth their space in RAM. My site has over 1,000 user accounts, 120,000 posts, and 100,000 uploaded files from the past three years, and an average of 100 users online at the same time during the day. I need the software to continue to be scalable as the database grows and we gain more active users.

I'm not sure how much the size of the data in a column impacts the speed of queries. What I do know is that typically we want images to be requested after the main content is loaded. By storing them together, we delay the loading of the entire post.

**Comment by buddh4** [comment]
Images are stored in markdown format, no images are embedded in the richtext. If you have trouble with the search index, please open another issue with the full error stack.

**Comment by buddh4** [comment]
Seems whenpasting the image its saved in base64 format. I'll have a look.

**Comment by samsheridan** [comment]
My mistake, sorry. I didn't fully investigate it before opening the issue.
