### ISSUE TITLE
Yii queue error handling broken

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4009]
### What steps will reproduce the problem?

- Trigger a queue error

### What is the expected result?

No error

### What do you get instead?

Log Entry

```
Error message:
TypeError: Argument 1 passed to yii\queue\Queue::handleError() must be an instance of yii\queue\ExecEvent, string given, called in 
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5

**Comment by fsainovich** [comment]
same here:

TypeError: Argument 1 passed to yii\queue\Queue::handleError() must be an instance of yii\queue\ExecEvent, string given, called in /var/www/html/protected/humhub/modules/queue/driver/MySQLCommand.php on line 68 and defined in /var/www/html/protected/vendor/yiisoft/yii2-queue/src/Queue.php:288 Stack trace: #0 /var/www/html/protected/humhub/modules/queue/driver/MySQLCommand.php(68): yii\queue\Queue->handleError('33024', Object(humhub\modules\activity\jobs\SendMailSummary), '300', 16, Object(Symfony\Component\Process\Exception\ProcessTimedOutException)) #1 /var/www/html/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(126): humhub\modules\queue\driver\MySQLCommand->handleMessage('33024', 'O:44:"humhub\\mo...', '300', 16) #2 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}('33024', 'O:44:"humhub\\mo...', '300', 16) #3 /var/www/html/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func(Object(Closure), '33024', 'O:44:"humhub\\mo...', '300', 16) #4 /var/www/html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage('33024', 'O:44:"humhub\\mo...', '300', 16) #5 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure)) #6 /var/www/html/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure)) #7 /var/www/html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure)) #8 /var/www/html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false) #9 [internal function]: yii\queue\db\Command->actionRun() #10 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #11 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #12 /var/www/html/protected/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('run', Array) #13 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array) #14 /var/www/html/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array) #15 /var/www/html/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array) #16 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #17 /var/www/html/protected/yii(29): yii\base\Application->run() #18 {main}


### What steps will reproduce the problem?
Error in logs after try run queue

### What is the expected result?
Run queue normaly

### What do you get instead?
error attached in top

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5
| PHP version      |  7.2.24
| Operating system | Ubuntu 18.04

**Comment by luke-** [comment]
@fsainovich  Does PR solve your problem?
