### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by Adela01** [humhub/humhub#401]
Hi!

 Can anyone please help me with the following situation?

 I have deleted a user from the Hum Hub platform installed on our server. Afterwards, I have send him again an invitation but when trying to register (no matter what he writes: letters, numbers etc) in the User name section he receives as error message and cannot proceed to the next step. 

Do you have any suggestions on how to fix this?

Thank you!

**Comment by Felli** [comment]
Users aren't able to register on site, it'll give them an error message telling them something went wrong, that's basically what this is saying from the looks of it.
