### ISSUE TITLE
Images are not rotated correctly...

### ISSUE THREAD

**Issue by niklasMD** [humhub/humhub#4036]
Inserting photos into a post that are vertical are always displayed horizontal. I guess with the new image processing, the data from the photos is not read out correctly. This only affects new photos inserted after the upgrade to humhub1.5.0/1.5.1

### What steps will reproduce the problem?
Make a photo vertical and horizontal with your cell phone and insert both images into a post. 

### What is the expected result?
One photo horizontal, and one vertical.

### What do you get instead?
Two horizontal photos.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      |  7.3
| Operating system | Ubuntu 18.04

**Comment by luke-** [comment]
seem to be related: https://github.com/yiisoft/yii2-imagine/issues/44

**Comment by manichardtiger** [comment]
Can verify this on a new installation of 1.5.1 with php 7.4 and fpm, on raspbian buster

No imagemagick, default GD used

**Comment by niklasMD** [comment]
Could I issue a feature request to rotate images within HumHub after they are uploaded to remedy this problem? I posted a feature request on the community board as well, but I am not sure how closely it is monitored...
Thanks and Cheers, Niklas

**Comment by samsheridan** [comment]
I can confirm this issue too. In the past, imagemagick was doing that so I didn't use it. As soon as upgraded to 1.5 with Imagine it became a problem again.

If you save the sideways image from HumHub, it's still sideways. Then if you fix the rotation in say, MS Paint, and upload it again it will be fine. This tells me that the EXIF orientation data isn't being processed properly, just like they're saying in yiisoft/yii2-imagine#44.

**Comment by niklasMD** [comment]
Hi Lucas,

Thanks. I immediately patched my HumHub instance. ;-) While it works for 
the smaller preview images, it still has the same problems when showing 
the original full size images, i.e. when clicking on one of the images.

Thanks and Cheers,
Niklas

**Comment by luke-** [comment]
@niklasMD  
Thanks for testing! The original file is not modified by HumHub. Which browser are you using? Can you test it with Google Chrome?

**Comment by niklasMD** [comment]
Interesting, I did not expect that browsers would handle this 
differently. Chrome is correct, Firefox (75.0) is not.
Any possibility to make this more homogeneous?

Thanks and Cheers,
Niklas

**Comment by luke-** [comment]
Can you try also this fix:
https://github.com/humhub/humhub/pull/4062/commits/be8cf42c41ced72d22d68aeacb9e99b4fd76c6a6

**Comment by niklasMD** [comment]
Thank you, Lucas, it now also works with Firefox. Great work.

**Comment by samsheridan** [comment]
My users are still having this issue on 1.5.2.

**Comment by luke-** [comment]
@samsheridan Where do the users have the problem? In the Gallery Module? There is a separate update here.

**Comment by samsheridan** [comment]
@luke- I've been noticing it in profile pictures.
