### ISSUE TITLE
Adding new text field to a category database exeption

### ISSUE THREAD

**Issue by lubign** [humhub/humhub#4037]
### What steps will reproduce the problem?
Settings -- Profiles -- Category -- Add new field --- Fill the form - Select text -- Save

### What is the expected result?
To create a new field
### What do you get instead?
> )PDOException: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs in /home/user/reclutamiento.consemargroup.com/protected/vendor/yiisoft/yii2/db/Command.php:1293 Stack trace: #0 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute() #1 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE `pr...') #2 /home/user/mydomain.com/protected/humhub/modules/user/models/fieldtype/Text.php(147): yii\db\Command->execute() #3 /home/user/mydomain.com/protected/humhub/modules/admin/controllers/UserProfileController.php(159): humhub\modules\user\models\fieldtype\Text->save() #4 [internal function]: humhub\modules\admin\controllers\UserProfileController->actionEditField(NULL, '4') #5 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #6 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #7 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('edit-field', Array) #8 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/user-prof...', Array) #9 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /home/user/mydomain.com/index.php(25): yii\base\Application->run() #11 {main} Next yii\db\Exception: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs The SQL being executed was: ALTER TABLE `profile` ADD `emisor4` VARCHAR(255) in /home/user/mydomain.com/protected/vendor/yiisoft/yii2/db/Schema.php:674 Stack trace: #0 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `pr...') #1 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE `pr...') #2 /home/user/mydomain.com/protected/humhub/modules/user/models/fieldtype/Text.php(147): yii\db\Command->execute() #3 /home/user/mydomain.com/protected/humhub/modules/admin/controllers/UserProfileController.php(159): humhub\modules\user\models\fieldtype\Text->save() #4 [internal function]: humhub\modules\admin\controllers\UserProfileController->actionEditField(NULL, '4') #5 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #6 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #7 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('edit-field', Array) #8 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/user-prof...', Array) #9 /home/user/mydomain.com/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /home/user/mydomain.com/index.php(25): yii\base\Application->run() #11 {main} Additional Information: Array ( [0] => 42000 [1] => 1118 [2] => Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs )
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      |  7.4
| Operating system | Cpanel - Shared hosting - namecheap

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

![error hum](https://user-images.githubusercontent.com/63674241/79819995-37d11a00-8359-11ea-9e03-d4bd9580777c.png)

**Comment by luke-** [comment]
Can't you add any profile fields at all? Or just not of a certain type?

**Comment by buddh4** [comment]
Think you've hit your db limits, check your db settings.
