### ISSUE TITLE
exception 'yii\base\ErrorException' with message 'Cannot use yii\helpers\Html as Html because the name is already in use'

### ISSUE THREAD

**Issue by caumons** [humhub/humhub#4038]
After upgrading to Humhub 1.5.1 I can no longer access the spaces nor my profile page and the following error appears at the logs:

`exception 'yii\base\ErrorException' with message 'Cannot use yii\helpers\Html as Html because the name is already in use' in /path/to/app/protected/humhub/libs/ProfileBannerImage.php:13 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}`

If I comment [this line](https://github.com/humhub/humhub/blob/master/protected/humhub/libs/ProfileBannerImage.php#L13) the error disappears and I can access again to the spaces and my profile page.

**Comment by luke-** [comment]
Thanks for the report. 
Which PHP version are you using?

**Comment by caumons** [comment]
Hi @luke-,

Thank you for your quick response.

I was using PHP 5.6, upgrading it to 7.2 fixed the issue and I'm now able to uncomment the mentioned line without errors.

Cheers.
