### ISSUE TITLE
Cannot permanently delete user

### ISSUE THREAD

**Issue by efelon** [humhub/humhub#4042]
### What steps will reproduce the problem?

1. Login with a new ldap user.
2. Login as admin
3. Delete user in admin. menu (got somehow renamed to "deleted-6")
4. Select "Deleted Users" as user list filter
5. Goto the context menu of the deleted user and click "Permanently delete"

### What is the expected result?

User is removed from the GUI and database.

### What do you get instead?

The page just reloads without any visible effect. The user is still there an the process can be repeated in the same way. This is the database entry of this user:

```
+----+--------------------------------------+--------+-----------+-----------------------------+-----------+---------------------------------+----------+---------------------+------------+---------------------+------------+---------------------+------------+---------------+---------------------+---------------+
| id | guid                                 | status | username  | email                       | auth_mode | tags                            | language | created_at          | created_by | updated_at          | updated_by | last_login          | visibility | time_zone     | contentcontainer_id | authclient_id |
+----+--------------------------------------+--------+-----------+-----------------------------+-----------+---------------------------------+----------+---------------------+------------+---------------------+------------+---------------------+------------+---------------+---------------------+---------------+
|  6 | 1ccf2ae1-fda9-46e2-b48e-639c9f4f5f06 |      3 | deleted-6 | NULL                        | ldap      | NULL                            | de       | 2020-04-22 12:00:05 |       NULL | 2020-04-22 12:00:05 |       NULL | 2020-04-24 00:39:58 |          1 | Europe/Berlin |                  13 | NULL          |
+----+--------------------------------------+--------+-----------+-----------------------------+-----------+---------------------------------+----------+---------------------+------------+---------------------+------------+---------------------+------------+---------------+---------------------+---------------+
```

### Additional info

The user was also deleted from LDAP but I can't recall the exact order. I'm pretty sure I deleted it first in LDAP and tried afterwards to delete it inside humhub.

Can I just remove the user from the database user? 

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      | 7.3.14
| Database     | MariaDB 10.3.22
| Operating system | Raspbian

### Errors
No errors in browser console or admin. logs.

**Comment by luke-** [comment]
What is the queue status in "Administration -> Information -> Background jobs"?

**Comment by efelon** [comment]
Sorry, I looked at it but forgot to mention it:

```
./yii queue/info
Jobs
- waiting: 0
- delayed: 0
- reserved: 0
- done: 0
```
GUI:
```
Queue Status
Driver
MySQL

Waiting
0

Delayed
0

Reserved
0

Done
23320
```

**Comment by luke-** [comment]
Does this only affect LDAP users?
