### ISSUE TITLE
Error message when i am wanting to create a new user

### ISSUE THREAD

**Issue by diego22100** [humhub/humhub#4043]
**I have this message when i am wanting to create a new user** 
![test](https://user-images.githubusercontent.com/64316836/80281774-c7861800-870d-11ea-9dd9-2f7b0d4a0cf3.png)
**: "Group ID ne peut être vide."**

**Could you help me please ?**

**Comment by diego22100** [comment]
i am admin, so i have all rights in my webite, but when i am wanting to create a new user i have the error message : 

**Group ID ne peut être vide** 

In english it's "**Group ID can't be empty**"

**Comment by luke-** [comment]
Which HumHub version?

**Comment by diego22100** [comment]
Bonjour, it's the 1.5.1 version



________________________________
De : Lucas Bartholemy <notifications@github.com>
Envoyé : samedi 25 avril 2020 20:21
À : humhub/humhub <humhub@noreply.github.com>
Cc : diego22100 <didmetz@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [humhub/humhub] Error message when i am wanting to create a new user (#4043)


Which HumHub version?

**Comment by diego22100** [comment]
I have found issue. In fact i haven't created all groups for admin and users. Now i can create new user, it works. 👍🏼😁

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
From: Online DMF <didmetz@hotmail.com>
Sent: Saturday, April 25, 2020 8:34:22 PM
To: humhub/humhub <reply@reply.github.com>
Subject: RE: [humhub/humhub] Error message when i am wanting to create a new user (#4043)

Bonjour, it's the 1.5.1 version



________________________________
De : Lucas Bartholemy <notifications@github.com>
Envoyé : samedi 25 avril 2020 20:21
À : humhub/humhub <humhub@noreply.github.com>
Cc : diego22100 <didmetz@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [humhub/humhub] Error message when i am wanting to create a new user (#4043)


Which HumHub version?
