### ISSUE TITLE
Jitsi connection fails from Android devices

### ISSUE THREAD

**Issue by micoots** [humhub/humhub#4047]
### What steps will reproduce the problem?

Try and start Jitsi Meet from Humhub

### What is the expected result?

Jitsi Meet connects to meet.jit.si and opens a room.

### What do you get instead?

Endless circling as discussed here:

[https://community.humhub.com/s/general-discussion/?contentId=215626](https://community.humhub.com/s/general-discussion/?contentId=215626)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      |  7.3
| Operating system | CentOS Linux release 8.1.1911 (Core)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

No errors exist, just connection to meet.jit.si from Android devices I've tested never works. 

Have tested on different Android devices - 3 different model phones and 1 Samsung tablet. Works fine from a PC and web browser.

Have also tested from HumHub.com cloud by creating a domain there and testing, also fails from Android devices.

From the same devices, I can start and use the Jitsi Android App by itself from the Android devices, opens and can start a room no problems.

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Can you please re-create the issue here:
https://github.com/humhub-contrib/jitsi-meet
