### ISSUE TITLE
Dashboard: include Spaces content

### ISSUE THREAD

**Issue by dakur** [humhub/humhub#405]
Dashboard now does not include the content from Spaces, which I am a member of. If the idea of whole network is built on grouping, I think it should be essential to display the group news on dashboard, otherwise the dashboard is not useful for many things, it seems to me. :-)

**Comment by lcnphp** [comment]
I check the code and database, it seems the content's visibility field cause the problem, all of the content's visibility field default to be "0: but "null"
![1](https://cloud.githubusercontent.com/assets/944108/8271335/db274d36-1843-11e5-8e8a-fac17a00a6bd.jpg)

![2](https://cloud.githubusercontent.com/assets/944108/8271336/f60b9684-1843-11e5-9946-0f5ad3b33eb9.jpg)
