### ISSUE TITLE
Unnecessary newlines are added to table cells in the rich text editor

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#4053]
1. Create a table in the rich text editor.
![2020-04-30_15h18_19](https://user-images.githubusercontent.com/38252517/80680131-2a562580-8af9-11ea-8ed5-f7e88d651909.png)

1. When saved, unnecessary newlines are added to each cell.
![2020-04-30_15h18_45](https://user-images.githubusercontent.com/38252517/80680496-d861cf80-8af9-11ea-869b-04d15e68499a.png)

1. If edit, more new lines will be added.
![2020-04-30_15h19_10](https://user-images.githubusercontent.com/38252517/80680994-bfa5e980-8afa-11ea-9168-84167c88d73b.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      | 7.3

**Comment by Oremountainflorian** [comment]
Hey, this issue was already mentioned here https://github.com/humhub/humhub-prosemirror/issues/11 and here https://github.com/humhub/humhub-modules-wiki/issues/123 and was transfered to planned developments!

**Comment by sakurafarm** [comment]
@Oremountainflorian- Thank you for sharing this with me.  I would like to close this issue and wait for it to be fixed.
