### ISSUE TITLE
[fix] css theme bugs

### ISSUE THREAD

**Issue by warshell** [humhub/humhub#4054]
I will post here a small css fixes that i found:

 Tooltip have 2 font weight properties (theme.css)

```
.tooltip-inner{
   font-weight:300;
    font-weight:bold;
}
```

Dropdown have 2 borders (dropdowns.less)
its normal? maybe its a IE fix?:)

```
.dropdown-menu {
    border: 1px solid #ccc;
    border: 1px solid rgba(0, 0, 0, 0.15);
 }
```

**Comment by luke-** [comment]
Thanks for the hint, I can't find the dropdown border value?
https://github.com/humhub/humhub/blob/master/static/less/dropdown.less#L4

**Comment by warshell** [comment]
@luke- ![image](https://user-images.githubusercontent.com/617020/81086994-7b02bf80-8ef9-11ea-9159-ae0e7b4886b5.png)

**Comment by luke-** [comment]
Thanks, this seems to be related to a Bootstrap file:
./protected/vendor/bower-asset/bootstrap/less/dropdowns.less
