### ISSUE TITLE
Uploaded image files with markdown profile fields are not displayed

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#4056]
### What steps will reproduce the problem?
1. Add a markdown type field to the profile field.
1. Upload an image file with a markdown type field in profile.
![2020-04-30_17h51_08](https://user-images.githubusercontent.com/38252517/80691456-41057800-8b0b-11ea-9904-8e9a9e50b95b.png)
1. View About page from profile.

### What is the expected result?
Uploaded image file is displayed in the markdown type field of about page.

### What do you get instead?

1. The uploaded image file is not displayed, but a markdown code is displayed.
![2020-04-30_17h56_41](https://user-images.githubusercontent.com/38252517/80692177-34cdea80-8b0c-11ea-93d9-c8c61742480d.png)

1. After this I emptied the contents of the markdown type field and saved it. However, the uploaded image files are not deleted, **but remain under /uploads/file.**

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      | 7.3

**Comment by ArchBlood** [comment]
Can confirm this issue.
