### ISSUE TITLE
Getting Google ads to show with the AdSense module

### ISSUE THREAD

**Issue by micoots** [humhub/humhub#4057]
### What steps will reproduce the problem?

Install AdSense module from Browse online area

### What is the expected result?

AdSense works without a problem

### What do you get instead?

Refused to load the script 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js' because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-_someverylongstring_' 'unsafe-inline' 'unsafe-eval' 'report-sample'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      |  7.4
| Operating system | CentOS 8

There's no error from HumHub, this error is seen using Chrome developer console (ctrl-shft-J).

Because of the CSP, google ads don't show up on the site.

I've spend 3 hours on this already reading up on CSP items and changing my rules in:

/home/somepath/protected/config/web,php

but to no avail.

I have to full CSP defined here:

[https://docs.humhub.org/docs/admin/security/#web-security-configuration](https://docs.humhub.org/docs/admin/security/#web-security-configuration)

With my script-src section showing:

                                        "script-src" => [
                                                "self" => true,
                                                "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",
                                                "unsafe-inline" => true,
                                                "unsafe-eval" => true,
                                                "report-sample" => true
                                        ],

I did also try an:

                                        "script-src" => [
                                                "self" => true,
                                                "allow" => [
                                                "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",
                                                ],
                                                "unsafe-inline" => true,
                                                "unsafe-eval" => false,
                                                "report-sample" => true
                                        ],

but both do the same thing.

Please assist it's tricky!

**Comment by ArchBlood** [comment]
Can you please report this here?

https://github.com/GreenMeteor/humhub-adsense-module

**Comment by micoots** [comment]
OK done. Thanks.
