### ISSUE TITLE
Android Can't Paste Before Typing

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#4058]
### What steps will reproduce the problem?

Any of the new post or comment boxes, when I tap to place the cursor, then long tap to bring up the paste option (such as to add a video URL), it never works unless I start typing something first.  The cursor just blinks and I can't get to the paste button.

Default theme is in use.

### What is the expected result?

Long tap on Androud should display a little context menu.

### What do you get instead?

Nothing.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1

**Comment by buddh4** [comment]
I'am pretty sure this is due to the old placeholder behavior, which should be fixed in 1.5.2

**Comment by buddh4** [comment]
Should work in 1.5.2
