### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#4059]
### What steps will reproduce the problem?
At user profile administration page, the "Edit Category" button label does not be translated.

### What is the expected result?
Button label should be translated.

### What do you get instead?
To match with message\(lang)\user.php dictionary file.
Correct the string like bellow.

### Additional info
I suggest ...

\protected\humhub\modules\admin\views\user-profile\_fieldGrid.php
Line 20: 'Edit category'  -> 'Edit profile category'

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      |  7.2
| Operating system | WindowsServer2016

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
The string is now available in the `develop` branch for 1.6 version.
https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/admin/messages/de/user.php#L134

If you want to translate this for 1.5, you need to create a pull request for the `master` branch.

Thanks!
