### ISSUE TITLE
Photos Not Rotated in Gallery

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#4064]
I've noticed a couple times recently, when photos get uploaded from cell phones, the slideshow displays them correctly rotated, but the Dashboard thumbnails are sideways.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1

**Comment by ArchBlood** [comment]
Seems related to #4036

**Comment by miqrogroove** [comment]
https://github.com/humhub/humhub/commit/c39054b55f63691af3772ee51caabd663c0d2146 fixes this for me.  Thank you.

**Comment by miqrogroove** [comment]
Correction, this is not fixed in the gallery.

**Comment by geekaroni** [comment]
Created a demo sandbox on the site today and confirmed this is still an issue. Sideways mobile photos.

**Comment by luke-** [comment]
Fixed in gallery module 1.1.2

**Comment by DamArnd** [comment]
Hello,

I would take the liberty of reacting to this issu, which was resolved with version 1.5.2.
I had the same problem previously explained but the 1.5.2 update does not fully solve it.
Pictures loaded as "profile picture" are still rotated when it comes from a smartphone..

version used: 1.5.2
