### ISSUE TITLE
Setting Album in Profile users

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4071]
Hello
Не могу понять смысл этой настройки
I can not understand the meaning of the setting

Не переходит в настройки при нажатии на настройку альбома
It does not go to the settings by clicking on the album setting

Это правильно работает?
It works correctly?
Так и должно быть ?
So it should be?

![Screenshot_149](https://user-images.githubusercontent.com/36643871/81728088-912cf480-9492-11ea-97e2-09abd6b189b9.png)
next
![Screenshot_151](https://user-images.githubusercontent.com/36643871/81728115-9d18b680-9492-11ea-8ca3-a7147eb276f2.png)
end

**Comment by luke-** [comment]
Related here: https://github.com/humhub-contrib/gallery

**Comment by andrewua85** [comment]
вчера обновился Альбом...
last updated Album ...
