### ISSUE TITLE
I don't find yii cron HELP ME!

### ISSUE THREAD

**Issue by serhatakgl** [humhub/humhub#4072]
**There are two red problem on my website. (Cron and Queue) and my search doesn’t work. I searched on the internet and they say follow this path:**

**_php /path/to/humhub/protected/yii cron/run_**

**But there is no _yii cron_ or _yii queue/run_ in my ftp. What can I do?**

**I looked here:** https://docs.humhub.org/docs/admin/cron-jobs/

**Comment by ArchBlood** [comment]
`php /path/to/humhub/protected/yii cron/run` is an example you should place the absolute path to your HumHub instance.

**Comment by serhatakgl** [comment]
If this is an example path, where is this real path how can I found it? can you help me. this is my ftp:  https://i.ibb.co/vxQmyFk/avci.png

**Comment by ArchBlood** [comment]
In my case it would be `/home/USERNAME/public_html/protected/yii`

**Comment by serhatakgl** [comment]
I tried but there is no solve.

**Comment by serhatakgl** [comment]
Okay. I solved it. There is no red problem table. But This search and notifications etc still don't work. I entered the Cpanel and add it: 
/usr/local/bin/php /home/MY-DB-NAME/public_html/protected/yii cron/run >/dev/null 2>&1
/usr/local/bin/php /home/MY-DB-NAME/public_html/protected/yii queue/run >/dev/null 2>&1

my php version is 7.3 therefore I wrote ea-php73 in "php" and tried it. This still doesn't work. What should I do?

**Comment by ArchBlood** [comment]
Add `--isolate=0` at the end of `/usr/local/bin/php /home/MY-DB-NAME/public_html/protected/yii queue/run >/dev/null 2>&1`
