### ISSUE TITLE
What version of the kernel(core) yii ?

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4073]
Не могу найти, где указанно ядро фреймворка на котором построен humhub и обновляется он вместе с выходом новой версии yii ?

I can not find where said core framework which is built humhub and it is updated with a new version of yii??

**Comment by luke-** [comment]
All dependencies are managed (and related versions) via Composer.

**Comment by buddh4** [comment]
Master uses `2.0.34`

**Comment by andrewua85** [comment]
> Master uses `2.0.34`

Thanks
