### ISSUE TITLE
css button and menu  not fine

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4074]
исправьте пожалуйста отображение кнопок и больших в мобильной версии, убирать текст и оставлять иконку в место описание кнопки или сделать выпадающим меню. Это же не сложно , сделать в выпадающем списке, даже через html это можно сделать, спасибо ;)

Please correct the display of buttons and big in the mobile version, remove the text and leave the icon in place of the buttons description, or to make a drop-down menu. It's not hard to do in the drop-down list, even through html can do, thank you;)

![изображение_viber_2020-05-12_23-20-08](https://user-images.githubusercontent.com/36643871/81741755-afe9b600-94a7-11ea-871b-e81819ebb7f4.jpg)
![изображение_viber_20-05-12_23-20-08](https://user-images.githubusercontent.com/36643871/81741759-b24c1000-94a7-11ea-9e0a-62faa2356121.jpg)

**Comment by luke-** [comment]
Thanks for the report.

Can you please create one issue per problem.

The first point is also more related to the mail module:
https://github.com/humhub/humhub-modules-mail

**Comment by andrewua85** [comment]
> 
> 
> Thanks for the report.
> 
> Can you please create one issue per problem.
> 
> The first point is also more related to the mail module:
> https://github.com/humhub/humhub-modules-mail

Что это ? What is it ?
Я за CSS отображение кнопок говорил )
I am for the CSS display of buttons saying
