### ISSUE TITLE
Spaces: files module

### ISSUE THREAD

**Issue by dakur** [humhub/humhub#408]
In Spaces, I miss there possibility to see all uploaded files at once. For example I know that somebody some months ago uploaded something, so I have to scroll down all the history and search for it. Instead, there would be a link Files in the Space menu and by clicking it I would be able to see all uploaded files.
It could be made as a module, I guess.

**Comment by koekje1eten** [comment]
What is the status on this one? It would be a great module, because now it's too social and too less business.

**Comment by secondtruth** [comment]
I agree with @dakur.

Maybe for user profiles, too? @macagoraga @AjVilanovailaGeltru

**Comment by MalteHorstmann** [comment]
Any update on this one?

**Comment by 3ruce** [comment]
Likewise, would be a great addition!

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-cfiles

We hope to finish this in the next weeks.

**Comment by 3ruce** [comment]
Thanks Luke, I think this would be excellent once it's done!

**Comment by SupeRobbY** [comment]
Hi, 

how I can install the module on my humhub?
Have you any docs about?
Is it stable?
Thanks 
Roberto

**Comment by Felli** [comment]
In Humhub 12+ you upload the module to >protected>modules and enable them via the admin control panel under Modules.

**Comment by dakur** [comment]
The module is in progress so this issue can be closed.
