### ISSUE TITLE
/static/assets/img/*.png path not valid (remove /assets/)

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub#4084]
Version 1.5.1 Checking links with https://validator.w3.org/checklink
gives on my site these errors:        
```
error Line: (N/A) https://website/static/assets/img/play-pause.png
    Status: 404 Not Found

    The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link. 
error Line: (N/A) https://website/static/assets/img/video-play.svg
error Line: (N/A) https://website/static/assets/img/error.png
error Line: (N/A) https://website/static/assets/img/error.svg
error Line: (N/A) https://website/static/assets/img/play-pause.svg
error Line: (N/A) https://website/static/assets/img/loading.gif
error Line: (N/A) https://website/static/assets/img/video-play.png
```
The correct link is in https://website/static/img/play-pause.png,
not in https://website/static/assets/img/play-pause.png
The difference is the **/assets/**

In the transfer to humhub-app.css somewhere the relative path is changed to one higher in the path.

**Comment by buddh4** [comment]
Those assets are probably not build due to: https://github.com/humhub/humhub/blob/master/protected/humhub/assets/BlueimpGalleryAsset.php#L37
