### ISSUE TITLE
Post image (Where here grid or flex?)

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4085]
Режет глаз в 2020 году
It hurts the eyes in 2020

Можно реализовать корректное отображение изображений ?
You can implement the correct display of images?

for example:
сейчас так...
now so...
1.
![Screenshot_152](https://user-images.githubusercontent.com/36643871/81821147-3353e780-953a-11ea-995c-f7d2603e5495.png)

Можно сделать отображений таким способом:
You can make maps in this way:

![Screenshot_153](https://user-images.githubusercontent.com/36643871/81821325-65654980-953a-11ea-9311-160058133c2e.png)

Or:
![Screenshot_154](https://user-images.githubusercontent.com/36643871/81821403-76ae5600-953a-11ea-9a02-cf47220ed534.png)

Thanks!

**Comment by buddh4** [comment]
We should use the `object-fit` css:

![image_2020_04_19T11_53_04_976Z](https://user-images.githubusercontent.com/9800854/82078975-5d480e00-96e2-11ea-916e-1b1d8a15ea53.png)

**Comment by andrewua85** [comment]
> 
> 
> We should use the `object-fit` css:
> 
> ![image_2020_04_19T11_53_04_976Z](https://user-images.githubusercontent.com/9800854/82078975-5d480e00-96e2-11ea-916e-1b1d8a15ea53.png)

Или так...
or so...

**Comment by buddh4** [comment]
What about smaller preview images as here:

![grafik](https://user-images.githubusercontent.com/9800854/87453731-41d68200-c603-11ea-8565-9e9c08551049.png)

**Comment by luke-** [comment]
How about making the size of the thumbnails relative to the number of images?

**Comment by buddh4** [comment]
Part of https://github.com/humhub/humhub/pull/4397
