### ISSUE TITLE
Error during updating: Cannot use yii\base\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by ellingen** [humhub/humhub#4090]
When updating Humhub to the latest version, PHP is throwing an error on the "Update installed modules" step.

### What steps will reproduce the problem?

I’ve been following this guide to update my instance of Humhub to the latest version: https://docs.humhub.org/docs/admin/updating/

When running `php yii module/update-all` an error is thrown. 

### What is the expected result?

Modules to be updated, Yii not throwing errors. 

### What do you get instead?

```
PHP Fatal error:  Cannot use yii\base\Object as Object because 'Object' is a special class name in /var/www/virtual/NAME/html/protected/modules/custom_pages/components/PageUrlRule.php on line 12


PHP Compile Error 'yii\base\ErrorException' with message 'Cannot use yii\base\Object as Object because 'Object' is a special class name'

in /var/www/virtual/NAME/html/protected/modules/custom_pages/components/PageUrlRule.php:12

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      | 7.4 (also tried 7.3 and 7.2)
| Operating system | CentOS 7

**Comment by buddh4** [comment]
- Is there a full error stack available, perhaps in the [logs](https://docs.humhub.org/docs/about/support#errors-and-logs)?
- Did you update your PHP version prior to the HumHub update?

**Comment by ellingen** [comment]
Hi buddh4, thanks for the swift response!

>Is there a full error stack available, perhaps in the logs?

```
2020-05-14 10:41:25 [79.140.121.247][-][-][error][yii\base\ErrorException:64] yii\base\ErrorException: Cannot use yii\base\Object as Object because 'Object' is a special class name in /var/www/virtual/linden90/html/protected/modules/custom_pages/components/PageUrlRule.php:12
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
2020-05-14 10:41:25 [79.140.121.247][-][-][info][application] $_GET = []

$_SERVER = [
    'USER' => 'linden90'
    'HOME' => '/home/linden90'
    'SCRIPT_NAME' => '/index.php'
    'REQUEST_URI' => '/'
    'QUERY_STRING' => ''
    'REQUEST_METHOD' => 'GET'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'REDIRECT_URL' => '/'
    'REMOTE_PORT' => '38282'
    'SCRIPT_FILENAME' => '/var/www/virtual/linden90/html/index.php'
    'SERVER_ADMIN' => 'hallo@uberspace.de'
    'CONTEXT_DOCUMENT_ROOT' => '/var/www/virtual/linden90/html'
    'CONTEXT_PREFIX' => ''
    'REQUEST_SCHEME' => 'https'
    'DOCUMENT_ROOT' => '/var/www/virtual/linden90/html'
    'REMOTE_ADDR' => '79.140.121.247'
    'SERVER_PORT' => '443'
    'SERVER_ADDR' => '127.0.0.1'
    'SERVER_NAME' => 'hub.linden9091.berlin'
    'SERVER_SOFTWARE' => 'Apache/2.4.39 (Unix)'
    'SERVER_SIGNATURE' => ''
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'
    'HTTP_COOKIE' => '_csrf=046046772fa4c7e288a905d9c88564292ddfc712921f53f540baa58c4451bae9a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22%9Ae%8D%F6%7F%DFp1%15%BBg%D3%A1b%F8%40k61Z%AAD2%28%60%26Qj%C2%1D%40L%22%3B%7D; pm_calendar-upcoming-events-snippet=expanded; pm_space-members-panel=expanded; PHPSESSID=df3leh8obgk9228do0l546hmto'
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_SEC_FETCH_DEST' => 'document'
    'HTTP_SEC_FETCH_USER' => '?1'
    'HTTP_SEC_FETCH_MODE' => 'navigate'
    'HTTP_SEC_FETCH_SITE' => 'none'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
    'HTTP_CACHE_CONTROL' => 'max-age=0'
    'HTTP_X_FORWARDED_FOR_ANON' => '79.140.0.0'
    'HTTP_X_FORWARDED_FOR' => '79.140.121.247'
    'HTTP_X_FORWARDED_PORT' => '443'
    'HTTP_X_FORWARDED_PROTO' => 'https'
    'HTTP_HOST' => 'hub.linden9091.berlin'
    'HTTP_CONNECTION' => 'close'
    'SCRIPT_URI' => 'https://hub.linden9091.berlin/'
    'SCRIPT_URL' => '/'
    'UNIQUE_ID' => 'Xr0ENb687vccM5Dv-IqRmAAAAAA'
    'HTTP_AUTHORIZATION' => '***'
    'HTTPS' => 'on'
    'REDIRECT_STATUS' => '200'
    'REDIRECT_SCRIPT_URI' => 'https://hub.linden9091.berlin/'
    'REDIRECT_SCRIPT_URL' => '/'
    'REDIRECT_UNIQUE_ID' => 'Xr0ENb687vccM5Dv-IqRmAAAAAA'
    'REDIRECT_HTTP_AUTHORIZATION' => ''
    'REDIRECT_HTTPS' => 'on'
    'FCGI_ROLE' => 'RESPONDER'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1589445685.5822
    'REQUEST_TIME' => 1589445685
]
```

>Did you update your PHP version prior to the HumHub update?

No, I was on 7.3 prior to updating. I then tried 7.4 and 7.3 once I ran into the issue.

**Comment by buddh4** [comment]
I've deleted your response, since it contained sensitive data. Unfortunately this was only the request data. Did the installation worked prior to the update, this error should always be thrown in old custom pages module versions with PHP < 7.2 and was fixed by https://github.com/humhub/humhub-modules-custom-pages/commit/066d6fc0245abacd16f67afe7bba52a5bbc6bf1a?

**Comment by ellingen** [comment]
Thanks for deleting, I wasn’t sure whether it had sensitive data.

The installation was running for two years without a hitch, but stopped working yesterday. It did in fact throw the same error, but in a different place. I then had a look at my webhost’s changelog but they didn’t apply any changes to the server configuration around that time.

I then thought I might as well update Humhub to the latest version to see whether that fixes the issue.

Is there any way I can update the modules in a different way?

**Comment by aronbos** [comment]
Tip: disable all modules and find the incorrect one. Guess.

**Comment by buddh4** [comment]
Can you access the admin interface? Perhaps you can update the custom pages module within the marketplace, but I assume you can't acces the admin interface because of this issue. You can try replacing the lines of https://github.com/humhub/humhub-modules-custom-pages/commit/066d6fc0245abacd16f67afe7bba52a5bbc6bf1a manually.

**Comment by buddh4** [comment]
- In `humhub/protected/modules/custom_pages/Events.php` just remove `extends \yii\base\Object`

- In `humhub/protected/modules/custom_pages/components/PageUrlRule.php`  add the `use yii\base\Component;` line and replace `class PageUrlRule extends Object implements UrlRuleInterface` with `class PageUrlRule extends Component implements UrlRuleInterface`

Then hope that there are not any other pre PHP 7.2 modules.

**Comment by ellingen** [comment]
Thanks, I was able to apply these changes manually and was then able to run the update modules command. It’s working now.
