### ISSUE TITLE
"Share" the post on other space.

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#4095]
### Is your feature request related to a problem? Please describe.
Add a post-content menu "share":
Copy the post-content to another space. 

### Describe the solution you'd like
"move" menu leaves as it is, add "share" (or "copy", "re-post") menu.
The "share" function is  to makes a new post copy of the post-content on other space. That does not need that's commnets. And created date is a new date.

### Describe alternatives you've considered
Is that a action called re-post?

**Comment by buddh4** [comment]
I think it should not copy the post, but rather create a shared post with slightly different post layout etc.

**Comment by tomofu74** [comment]
Thank you for your interesting about this as a enhancement, and I'm grad to we have a time about discuss about this issue.
I think it just "post" type content should be enable to  come to another space. It become a new post, new created_at date data, but sentences message copied by original. Original content's layout is ignored, but follows the new space's, or markdown is kept its layout, isn't it? If it has incidental data like link preview, attached files are it should be created as a new post on new space or copy record and set new id, and make a relation with new post...
I have no idea about calendar events... If it was repeated event, the all repeated event copy to new space, or just only an event? ..mmm... complex usage... Calendar module's "event type" property extended with "multi space" and it should select spaces (tag select, like user's group) when it is edited.

**Comment by luke-** [comment]
There is some older prototype module for this:
https://github.com/humhub-contrib/sharebetween

**Comment by tomofu74** [comment]
Thank you, luke. I'll try it.

**Comment by luke-** [comment]
@tomofu74 It's work in progress and not suitable for use.

**Comment by tomofu74** [comment]
@luke- Sure, I try to customize coding. Thank you.

**Comment by tomofu74** [comment]
I made a customize branch. And, run on my test humhub server. Thank you very much, luke-.
https://github.com/tomofu74/sharebetween

**Comment by luke-** [comment]
Great!

Would be awesome if you can contribute changes/fixes/enhancements back to the original repository!

**Comment by tomofu74** [comment]
@luke- 
Of cause, I would like to contribute to grow the original repository up.
By the way, I'm working for  customization a humhub Enterprise edition which licensed to Japanese User 'Osintech'. The boss says, "It is pleasure, if we could contribute for enhancements of Humhub."
I'll send a pull request later. Thanks.
