### ISSUE TITLE
Error trying to configure LDAP

### ISSUE THREAD

**Issue by emperorjm** [humhub/humhub#410]
I have tried everything I could think of but still getting the following error: Status: Error! (Message: 0x31 (Invalid credentials; 80090308: LdapErr: DSID-0C090334, comment: AcceptSecurityContext error, data 525, vece):

I am trying to connect to a Microsoft Active Directory server.

Can anyone help me out please.

![2014-11-20 15-20-25](https://cloud.githubusercontent.com/assets/1245772/5132167/198fd40e-70c8-11e4-83c7-11fa5633fcc8.png)

**Comment by Liz-Gtz** [comment]
I can login into this page
http://community.humhub.com/u/luke/home

I wanted to auth user using ldap but  I'm getting this error:

Status: ¡Error! (Mensaje: 0x34 (Server is unavailable; 00000000: LdapErr: DSID-0C090F7B, comment: Error initializing SSL/TLS, data 0, v2580): 192.168.1.6:389)

Please help me
Thanks

**Comment by nguyencongvu** [comment]
I got the error 

Status: Error! (Message: Could not load LDAP! - Check PHP Extension)

Whats the problem?
(tested by LDAP client tool ok to connected)

**Comment by ece31316** [comment]
Also getting this error.. What seems to be the problem? the link above are no longer working

**Comment by tobciu** [comment]
```
Status: Error! (Message: Could not load LDAP! - Check PHP Extension)
```
means, that you have to enable the LDAP-PHP-Extension in your Apache/NGINX-Webserver 

let me google it for you ;-) -> https://www.google.de/search?q=apache2%20enable%20ldap

**Comment by ece31316** [comment]
thanks tobciu i already done that, what i mean is i cant get it to work i'm getting this error

error Status: Error! (Message: 0x31 (Invalid credentials; 80090308: LdapErr: DSID-0C09030B, comment: AcceptSecurityContext error, data 525, v893): CN=XXXX,CN=Users,DC=XXXX,DC=COM)
