### ISSUE TITLE
Powerd by HumHub is not showing up

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#4107]
When the only thing see in the footer is Powerd By HumHub, it doesn't show up.

If install a Legal module or something like that and have more than two things showing up in the footer, it will show up.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1

**Comment by luke-** [comment]
That is so correct and wanted. Only when the footer navigation is displayed, "Powered By HumHub" appears.
