### ISSUE TITLE
Issues Cropping Images

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#4111]
# Image sticks out of the dialog
When try to crop a large profile image or cover image on a mobile device, the image sticks out of the edit dialog.

# Radio button? is displayed
On both desktop and mobile devices, a radio button appears in the upper left corner when open the crop screen a second time or later.

![Screenshot_20200516-163844 (1)](https://user-images.githubusercontent.com/38252517/82115143-fe46cf80-979b-11ea-98ef-0f77b0710b55.png)

# Crop frame cannot be moved by key operation
The radio button is displayed because JCrop is "Enable key operation('keySupport'=true)". But, the crop frame can't be moved by key operations.

I think it's okay to disable key operations.If so, the radio button will not be generated.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1

**Comment by sakurafarm** [comment]
I made a pull request. #4112

**Comment by buddh4** [comment]
@sakurafarm I could not recreate the issue, can you tell me the image dimension you've used and the theme ratio in case you've overwritten the ratio.
