### ISSUE TITLE
Definitive user deletion doesn't work

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4116]
### What steps will reproduce the problem?

1. Create an account with SSO login
2. Logout and login with a super admin account
3. Soft delete user (untick "delete all user contributions") and wait 1 minute for queue deletion
4. Go to users submenu "Delete users" : `/admin/user/list?UserSearch[freeText]=&UserSearch[status]=3`
5. Go to definitive user deletion : `/admin/user/delete?id=17` and click on the "Delete account" red button

### What is the expected result?

Account deletion

### What do you get instead?

I get back to the same page with this URL : `/admin/user/delete?id=17&_pjax=%23layout-content&_=1589778612118`

If I execute the command `protected/yii queue/run` nothing happens, account is still there.

### Additional info

In `/admin/logging` I have no message.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      | 7.1
| Operating system | Ubuntu 16.04

**Comment by samsheridan** [comment]
This happens without SSO too. If I set the status for the softdeleted user back to enabled (using the database), I'm able to perform a successful hard delete in the admin panel.

**Comment by ArchBlood** [comment]
First off I want to make sure that you know the difference between [soft](https://docs.humhub.org/docs/develop/modules-users/#soft-delete) & [hard](https://docs.humhub.org/docs/develop/modules-users/#hard-delete) delete, as a fix I wonder if [`authCancel()`](https://www.yiiframework.com/extension/yiisoft/yii2-authclient/doc/api/2.2/yii-authclient-authaction#authCancel) could be used in this way or open the option. :thinking:

**Comment by funkycram** [comment]
Yes, I know what is soft and hard delete.
Both work well. But If I do a soft delete, user is still in present in submenu "Delete users" (/admin/user/list?UserSearch[freeText]=&UserSearch[status]=3).
The bug is in this menu, when I try to hard delete a user that has been soft deleted.

**Comment by funkycram** [comment]
Great ! Thanks !
