### ISSUE TITLE
Youtube oembed does not work proberly with playlists

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4118]
### What steps will reproduce the problem?

Copy paste a youtube playlist link with `&index=3`.

### What is the expected result?

The embedded youtube video to display the video with the given index.

### What do you get instead?

The first playlist video is embedded to the richtext.

### Additional info

Unfortunately, this seems to be an issue with the youtube oembed backend.

**Comment by buddh4** [comment]
Maybe we should manually create the iframe:

```html
<iframe width="720" height="405" src="https://www.youtube.com/embed/?listType=playlist&list=RDCLAK5uy_k0oJ5JQqsSSQQvYS8xzcAh29CFryqs0mc&index=3" frameborder="0" allowfullscreen>
```

**Comment by ArchBlood** [comment]
I've seen some plugins using something like this and replacing `width=""` & `height=""` completely.
```
<iframe src="https://www.youtube.com/embed/?listType=playlist&list=RDCLAK5uy_k0oJ5JQqsSSQQvYS8xzcAh29CFryqs0mc&index=3" onload="this.width=screen.width;this.height=screen.height;" frameborder="0" allowfullscreen>
```

**Comment by buddh4** [comment]
Not a probem with the dimensions, but rather that youtube oembed does not respect the index parameter.

**Comment by buddh4** [comment]
I'll close this this is not an humhub issue but an issue with the youtube oembed interface and probably won't be fixed.
