### ISSUE TITLE
Missing Link

### ISSUE THREAD

**Issue by gerhardbeck** [humhub/humhub#4122]
My installation of Humhub shows me problems with the cronjob. (Setup incomplete)
When clicking the "documentation" button I expected to get the right page in the documentation.
It opened https://docs.humhub.org/admin-installation-configuration.html#cronjobs-and-asynchronous-job-processing-v13, showing "Page not found"

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5
| PHP version      7.2

**Comment by luke-** [comment]
Thanks, already fixed in upcomign 1.5.2
https://github.com/humhub/humhub/commit/8dd64329707e96fe33a5d7c60c31b8d3b1ad2aed
