### ISSUE TITLE
Inodes files to server

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4135]
На сервере постоянно увеличивается количество файлов, с чем это может быть связанно и как уменьшить количество файлов?
Больше 40 тысяч файлов с несколькими постами и с небольшим количеством установленных модулей. Файлы продолжают увеличиваться даже без активности сайта.

On the server is constantly increasing the number of files with which it can be connected and how to reduce the number of files?
More than 40 thousands of files with a few posts and a small amount of the installed modules. Files continue to grow even without the active site.

**Comment by luke-** [comment]
How many of these files are in /protected/runtime folder?

**Comment by andrewua85** [comment]
Было:
be:

![Screenshot_167](https://user-images.githubusercontent.com/36643871/82500952-19e40a00-9afd-11ea-95b6-47a28ad09f9d.png)
После установил раннюю версию и около 8 модулей, стало 73 inodes, сделал 4 публикации и стало 80 inodes, сегодня решил обновить до последней версии и стало 100 inodes , в связи с этим сайт не запустился и ошибки на сайте.
больше 65к файлов + 8 модулей ?? Вам не кажется что слишком много занимает inodes ?

After installing an early version and about 8 modules, became 73 inodes, made 4 publications and became 80 inodes, today decided to upgrade to the latest version and became 100 inodes, 

![Screenshot_166](https://user-images.githubusercontent.com/36643871/82501291-b1495d00-9afd-11ea-8f86-1bca02f57fd0.png)

because of this the site did not launch and errors on the site.
More than 65k files + 8 modules? Don 't you think it takes inodes too much?
