### ISSUE TITLE
Update - Error after upgrade completion

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4136]
Только что обновился с ранней версии и по завершению ошибка
Just updated from an earlier version and on completion error

![Screenshot_165](https://user-images.githubusercontent.com/36643871/82495936-93c3c580-9af4-11ea-99ee-8fa4ab40381a.png)
![Screenshot_164](https://user-images.githubusercontent.com/36643871/82495941-96beb600-9af4-11ea-892a-9e75a47d37bb.png)
![Screenshot_160](https://user-images.githubusercontent.com/36643871/82495947-97574c80-9af4-11ea-84cd-ec007fa8dfbd.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
apparently no more space is available on your server.
