### ISSUE TITLE
Dashboard post input on mobile cuts editor menu

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4139]
### What steps will reproduce the problem?

- Enable `Show user profile post form on dashboard` in `Administration -> Settings -> General`
- Access dashboard on mobile
- Focus the post input form

### What is the expected result?

Richtext menu fully visible and usable.

### What do you get instead?

The richtext menu is cut:

![grafik](https://user-images.githubusercontent.com/9800854/82552991-8134a500-9b63-11ea-958c-ef1df592a8e0.png)

**Comment by andrewua85** [comment]
> ### What steps will reproduce the problem?
> * Enable `Show introduction tour for new users` in `Administration -> Settings -> General`
> * Access dashboard on mobile
> * Focus the post input form
> 
> ### What is the expected result?
> Richtext menu fully visible and usable.
> 
> ### What do you get instead?
> The richtext menu is cut:
> 
> ![grafik](https://user-images.githubusercontent.com/9800854/82552991-8134a500-9b63-11ea-958c-ef1df592a8e0.png)

У меня тоже самое
I have the same

**Comment by buddh4** [comment]
We should just omit the overlay style of the focus menu on mobile by setting a `margin-top:0`

**Comment by andrewua85** [comment]
> We should just omit the overlay style of the focus menu on mobile by setting a `margin-top:0`

Это должны исправить разработчики а не делать в ручную постоянно или пусть сделают отдельный подключаемый глобальный стиль из админки.
This should be fixed by developers rather than done in manual constantly or let them make a separate plug-in global style from the admin.

**Comment by buddh4** [comment]
I did not mention/suggest any manual fix. My comment was rather a note to myself. Will be fixed in the next minor release...

**Comment by MasterMindNET** [comment]
Is it still relevant?

Because I have got this option enabled, but on "Dashboard" I do not have an input field.
So, what have I done wrong?

![image](https://user-images.githubusercontent.com/22347676/90317815-a7849980-df34-11ea-84ee-121eaaae4a2d.png)

**Comment by luke-** [comment]
@MasterMindNET You can enable this Post form in the settings (Adminsitration -> Settings)

**Comment by luke-** [comment]
@MasterMindNET Thanks it's merged. Please create a new issue for this question. Ideally with some screenshots.
