### ISSUE TITLE
Database Exception – yii\db\Exception

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4143]
![изображение](https://user-images.githubusercontent.com/36643871/82563521-e8f8e900-9b7f-11ea-9993-7db70a89a95b.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.2
| PHP version      | 7.1
| Operating system | 

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by buddh4** [comment]
https://docs.humhub.org/docs/about/support#how-to-get-support
