### ISSUE TITLE
Warning Search =(

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4144]
![изображение](https://user-images.githubusercontent.com/36643871/82566697-fa90bf80-9b84-11ea-8b46-f40d4cdcfddb.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by buddh4** [comment]
Seems to be a restriction on your hosting environment, please ask your hoster regarding this error.

**Comment by andrewua85** [comment]
ошибка была из за другой кодировки БД

Error was due to a different database encoding
