### ISSUE TITLE
How can I connect with https?

### ISSUE THREAD

**Issue by KazunariShimizu** [humhub/humhub#4145]
Hello.

I want to display images on https.
What should i do?

![toraden](https://user-images.githubusercontent.com/44958539/82599670-a965e780-9be7-11ea-8d5d-01b37fdfb186.jpg)

FireFox 76.0.1(64-bit)

**Comment by luke-** [comment]
Make sure your base url is set to https:// (Administration -> Settings)

**Comment by kevin-m87** [comment]
I get same issue
