### ISSUE TITLE
Language keys do not work

### ISSUE THREAD

**Issue by Vatarus** [humhub/humhub#415]
You close the ticket #411 , but the problem has not been solved.

You do not understand me.
In Views file recoverPassword_success.php code does not work.

In views_auth_recoverPassword_success.php file there are lines:
![screenshot 3](https://cloud.githubusercontent.com/assets/3394915/5154836/dcc2859a-72ba-11e4-842e-b0ec4e984d35.png)

but code in recoverPassword_success.php file does not work
i.e.
Yii::t('UserModule.views_auth_recoverPassword_success', '<strong>Password</strong> recovery!')
etc.  does not work.
![screenshot 4](https://cloud.githubusercontent.com/assets/3394915/5154850/a32a6158-72bb-11e4-9504-0f3612f5e371.png)

![screenshot 2](https://cloud.githubusercontent.com/assets/3394915/5154841/085eb570-72bb-11e4-97b4-52a980bf09f0.png)

A similar problem is here:

![screenshot 5](https://cloud.githubusercontent.com/assets/3394915/5154887/e662bf82-72bc-11e4-80f2-6f520d328d1d.png)

Code: Yii::t('UserModule.forms_AccountRecoverPasswordForm', 'Password Recovery'); 
 does not work.

**Comment by luke-** [comment]
@Vatarus sorry for the delay - it's fixed for recover password now.

**Comment by luke-** [comment]
@Vamoss https://github.com/humhub/humhub/blob/master/protected/modules_core/like/messages/pt_br/widgets_views_likeLink.php#L6 - Works for me
