### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by NENJAK** [humhub/humhub#4150]
Hi all,

It might be error for the creator of the chat Module. 
It is not possible to type more than ONE LETTER in chat whem I am using Iphone (8).

Thanks.
Nenad

![7DF297FF-2FDA-4417-8845-F22CE5445B14](https://user-images.githubusercontent.com/25792378/82739941-62d9cf80-9d44-11ea-8608-8309d22fb5df.png)

### What steps will reproduce the problem?
Using chat on Iphone
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Can you please contact the module creator for this issue:
https://www.humhub.com/en/marketplace/freichat/
