### ISSUE TITLE
"Save & Test" Gives No Result

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#4153]
At `/admin/setting/mailing-server` I've configured SMTP and seems to be mostly working but I need to troubleshoot a couple things.

When I click the "Save & Test" button all I get is a banner that says "Saved".

So where's the test result?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1

**Comment by buddh4** [comment]
The test mail is sent to the email address of the logged in user.

**Comment by miqrogroove** [comment]
Well, I'm not receiving any mail.  In the meantime, it would help to know whether or not the message was sent, so there really should be a banner saying whether or not the SMTP request was successful.  Is that possible?

**Comment by miqrogroove** [comment]
The 2nd symptom that I've identified is with the password field at `/admin/setting/mailing-server`

When I click the the eye icon on the right side of the field, the password dots change to the phrase `---invisible---` which is neither the correct password, nor is it something I would ever set here.

So I don't have a specific bug yet, but something unexpected has happened for sure.

**Comment by miqrogroove** [comment]
The 3rd problem is that it is impossible for an Administrator to change their own email address at `/user/account/change-email` if the email system isn't working.  It was something I thought to try but it looks like it would require database manipulation.

**Comment by miqrogroove** [comment]
If I switch from SMTP to PHP, it says "Could not send test email."  This is better feedback than "Saved".  So maybe these banners just need some tweaks.

**Comment by miqrogroove** [comment]
I stubbed in a test at `/var/www/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/SmtpTransport.php` and found the constructor is being called without my settings when I save them.  It's using localhost port 25, which is not valid in my environment.  😥

**Comment by miqrogroove** [comment]
After some hours of hacking on the swiftmail transport files, I discovered the destination mailbox hosted by Dreamhost has a new anti-spam system that is blocking ALL Humhub emails 😭

It is possible to disable the filter and add blacklist/whitelist options, but it's hard to find and just silently blackholes all of the messages.  What a frustrating mess.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/pull/4172

**Comment by buddh4** [comment]
@miqrogroove can you list the filters which are violated? If yes, perhaps another issue.

**Comment by miqrogroove** [comment]
When I was searching for solutions on my end, it looked like Vade was a proprietary filter system.  My only options are enable, disable, and filter by address.
