### ISSUE TITLE
Mobile shows post to stream

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#4155]
### What steps will reproduce the problem?
Using mobile device go to any post you've made and you'll see above the back to stream button there's a post entry option.
### What is the expected result?
No post entry option
### What do you get instead?
![screenshot31052020_200421](https://user-images.githubusercontent.com/35392110/83366216-98ea0580-a37b-11ea-8570-a699687e1922.jpg)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5
| PHP version      | community version
| Operating system | community version

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by buddh4** [comment]
Don't fully understand the issue. You mean the "Back to Stream" is needless because we have a "Stream" menu entry right above?

**Comment by ArchBlood** [comment]
This is not needed because you're not posting to any stream.
![Screenshot_1](https://user-images.githubusercontent.com/35392110/85848957-f3019f00-b75e-11ea-873d-bdf5b7d22284.png)

**Comment by buddh4** [comment]
Hmm, you are right its rather confusing to see the post input field in this case.

**Comment by luke-** [comment]
@buddh4 Yes, in the mobile version we can really remove the button. 
Also in the case of hiding the post input should be good.

Somehow we should show the user that he only sees a single post.

**Comment by buddh4** [comment]
Perhaps, we can render the button under the button beneath the stream entry.

**Comment by buddh4** [comment]
I'll close this for now, the back to stream button was improved. The difference between the "Back to stream" and "Stream" is that the menu item reloads the whole page, while the "Back to stream" button only loads the stream. Regarding hiding the stream input I've opened another issue: https://github.com/humhub/humhub/issues/4927
