### ISSUE TITLE
Message submission rate for this client has exceeded the configured limit

### ISSUE THREAD

**Issue by caumons** [humhub/humhub#4160]
We're facing errors when sending the email summaries regarding comments, likes, etc. because Humhub is exceeding the configured limit. Is there any way to configure the email sending throttling?

The first error shown is: `activityCould not send activity mail to: <Name Surname1 Surname2> (Expected response code 250 but got code "421", with message "421 4.4.2 Message submission rate for this client has exceeded the configured limit")`

Then, we encounter the following error: `activityCould not send activity mail to: <Name Surname1 Surname2> (fwrite(): send of 32 bytes failed with errno=104 Connection reset by peer)`

Since this second error, all the email sendings fail with the following error: `activityCould not send activity mail to: <Name Surname1 Surname2> (fwrite(): send of 64 bytes failed with errno=32 Broken pipe)`

We're using Humhub 1.2.4 on production, but we've also installed version 1.5.1 in another environment and we haven't found any option to set the email sending limits.

**Comment by luke-** [comment]
Seems this is related to your configured mail server in Humhub.
