### ISSUE TITLE
Number of "n more" likes is invalid

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#4161]
Community edition 1.5.2

The screenshot says it all
![image](https://user-images.githubusercontent.com/57734154/84264145-f96a0700-ab20-11ea-9f58-375d073927f3.png)

e.g. 6 likes, there is no "n more"
plural is french is invalid: should be `autre aime` for 1 et `autres aiment` for more than 1
other ways to write it: `autre(s) aime(nt)` or `autre·s aime·nt`

**Comment by buddh4** [comment]
Just for your info, you can contribute or discuss such translations in the [translation community](https://translate.humhub.org/user/auth/login)

**Comment by michael79bxl** [comment]
@buddh4 Thanks. Translation updated on the community site 👍
