### ISSUE TITLE
Display bug in activity protected module

### ISSUE THREAD

**Issue by michael79bxl** [humhub/humhub#4162]
The module should not entity encode `&` sign to avoid showing `&gt;` instead of `>` on screen etc.
It would also be nice to remove smileys not supported by this module `:[a-z0-9_]+:`
The module should also show "commented with an image or with a file" when the comment is empty and only contains a file or an image.
This would avoid having `commented ""` in the recent activity list.

```
            <div class="media-body text-break">

                <!-- Show content -->
                <?= preg_replace('/:[a-z0-9_]+:/', '', str_replace('&amp;', '&', $content)) ?>
                <br>

                <!-- show time -->
                <?= TimeAgo::widget(['timestamp' => $record->content->created_at]) ?>
            </div>
```

**Comment by luke-** [comment]
This is unfortunately a general encoding problem in several places atm. 
https://github.com/humhub/humhub/issues/3662
