### ISSUE TITLE
Possible Typo: "User filer"

### ISSUE THREAD

**Issue by thomas-mc-work** [humhub/humhub#4166]
### Where

In the LDAP repo settings page I've found `User Filer`, right after `Login Filter`.

### What is the expected result?

I guess this should be `User Filter`, as everything else wouldn't make sense.

Just asking, before starting to invest time into the PR.

**Comment by luke-** [comment]
Yes, that is indeed a bug.

A PR would be great. In this case, all message files must be modified using Search&Replace. (Fix the original English text).
