### ISSUE TITLE
Update page URL on filter change

### ISSUE THREAD

**Issue by verement** [humhub/humhub#4169]
### Is your feature request related to a problem? Please describe.

It would be nice to be able to share a link to a HumHub space that includes the currently applied filter(s).

### Describe the solution you'd like

Could it be possible to update the page URL upon changes to the current stream filter? This would allow the URL to be copied and shared to apply the same filter when a recipient follows the link.

### Describe alternatives you've considered

I found that by using the search feature, it is possible to click on a topic tag in the results to be taken to the stream, filtered by that topic, and that the page URL reflects this. I would like the same page URL to be visible when changing filters directly in the stream.

**Comment by errotu** [comment]
I'd appreciate this feature, too!
Regarding the alternative you mention: The topic tag in the search stream does not (if I'm not mistaken) redirect to a page URL which reflects the tag, it does only reflect the search request (keyword and space id) made beforehand.

**Comment by verement** [comment]
> Regarding the alternative you mention: The topic tag in the search stream does not (if I'm not mistaken) redirect to a page URL which reflects the tag, it does only reflect the search request (keyword and space id) made beforehand.

I didn’t look too deeply at it, but I found that after clicking on a topic label in the search results, the resulting URL in the address bar indeed produces a filter effect on the stream limited to that topic without any residual search keywords. I’d like the same URL to appear when clicking on topic labels within a space in the same way to reflect the current filter.

**Comment by errotu** [comment]
You're right, my mistake!

**Comment by yurabakhtin** [comment]
@luke- I have started this in PR https://github.com/humhub/humhub/pull/5094 where at this moment I implemented only to set filters from current request like `?filters[entry_userinvolved]=1&filters[entry_files]=1&sort=sort_update&visibility=visibility_private`.

**Comment by luke-** [comment]
Thanks looks good. Do you think it would make sense to make the filter names/values a bit nicer from the wording?

**Comment by yurabakhtin** [comment]
@luke- 

> Do you think it would make sense to make the filter names/values a bit nicer from the wording?

Yes, it would be better, because no reason to keep prefix same as group name, i.e. the filter id/name `entry_files` may be renamed into `files`, then `sort_update` => `update`, `visibility_private` => `private`. They are defined here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/stream/widgets/WallStreamFilterNavigation.php#L80-L93. I didn't investigated the code deeply but at this moment I don't see a reason to keep the prefixes there. It may be done after when I will done this task completely so we will see what params appear in browser address bar to consider how they may be renamed.

**Comment by luke-** [comment]
@yurabakhtin Ok, We should mention a note about the changes in the Developer Migration Guide, but otherwise I don't see any problems here right now either.

**Comment by yurabakhtin** [comment]
@luke- In new today's commits I have implemented the updating URL in address bar by change only **checkbox** filters. For other filter types I will do later.

**Comment by luke-** [comment]
@yurabakhtin Look good, thanks for the update!

**Comment by yurabakhtin** [comment]
@luke- I have finished this task. I tested only on Space and Profile wall streams, if you know where the filters should work same way let me know.
I didn't renamed filter names yet as we discussed above, maybe after review and testing current implementation you will tell me how they should be renamed.
