### ISSUE TITLE
Disable browser notifications popup when notifications are disabled

### ISSUE THREAD

**Issue by TheHolyRoger** [humhub/humhub#4180]
We have "Allow desktop notifications by default." disabled/turned OFF, but the browser notification popup always ops up regardless, how can we disable that?

**Comment by buddh4** [comment]
While we're at it, we might as well only ask for desktop notificaiton permission once a user is logged-in, or at least make this configurable. There currently are no notifications for guest users.

**Comment by buddh4** [comment]
Related to https://github.com/humhub-contrib/fcm-push/issues/6

**Comment by luke-** [comment]
Should be handled by `fcm-push` module
