### ISSUE TITLE
Periodic PHP Fatal errors (strange memory allocation)

### ISSUE THREAD

**Issue by xaro1** [humhub/humhub#419]
Regularly, I have some PHP fatal errors (strange memory allocation size) like this : 

<pre>PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 1164202188 bytes) in /xyz/humhub-master-20141122/protected/modules_core/space/models/Space.php on line 156
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 18446744071717836844 bytes) in /xyz/humhub-master-20141122/protected/modules_core/space/models/Space.php on line 153
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 18446744071751339656 bytes) in /xyz/humhub-master-20141122/protected/modules_core/space/models/Space.php on line 156
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 1155875564 bytes) in /xyz/humhub-master-20141122/protected/modules_core/space/models/Space.php on line 156
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 18446744071751339656 bytes) in /xyz/humhub-master-20141122/protected/modules_core/space/models/Space.php on line 156
...</pre>

This is always followed by an httpd segfault 11.

Some extra info from HumHub application.log : 

<pre>
[error] [php] Cannot use a scalar value as an array (/xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveRecord.php:1861)
Stack trace:
#0 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveFinder.php(804): CJoinElement->populateRecord()
#1 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveFinder.php(437): CJoinElement->runQuery()
#2 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveFinder.php(68): CJoinElement->find()
#3 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveRecord.php(1356): CActiveFinder->query()
#4 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveRecord.php(1536): SpaceMembership->query()
#5 /xyz/humhub-master-20141122/protected/modules_core/space/models/SpaceMembership.php(175): SpaceMembership->findAllByAttributes()
#6 /xyz/humhub-master-20141122/protected/modules_core/user/widgets/UserSpacesWidget.php(19): GetUserSpaces()
#7 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(167): UserSpacesWidget->run()
#8 /xyz/humhub-master-20141122/protected/widgets/StackWidget.php(94): ProfileController->widget()
#9 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(173): ProfileSidebarWidget->run()
#10 /xyz/humhub-master-20141122/protected/modules_core/user/views/profile/_layout.php(26): ProfileController->widget()
#11 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(126): require()
#12 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(95): ProfileController->renderInternal()
#13 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(869): ProfileController->renderFile()
#14 /xyz/humhub-master-20141122/protected/components/Controller.php(198): ProfileController->renderPartial()
#15 /xyz/humhub-master-20141122/protected/views/layouts/main.php(211): ProfileController->renderPartial()
#16 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(126): require()
#17 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(95): ProfileController->renderInternal()
#18 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(784): ProfileController->renderFile()
#19 /xyz/humhub-master-20141122/protected/modules_core/user/controllers/ProfileController.php(62): ProfileController->render()
#20 /xyz/humhub-master-20141122/protected/vendors/yii/web/actions/CInlineAction.php(49): ProfileController->actionIndex()
#21 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams()
#22 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CFilterChain.php(133): ProfileController->runAction()
#23 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run()
#24 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter()
#25 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CInlineFilter.php(58): ProfileController->filterAccessControl()
#26 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#27 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(291): CFilterChain->run()
#28 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(265): ProfileController->runActionWithFilters()
#29 /xyz/humhub-master-20141122/protected/vendors/yii/web/CWebApplication.php(282): ProfileController->run()
#30 /xyz/humhub-master-20141122/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController()
#31 /xyz/humhub-master-20141122/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest()
#32 /xyz/humhub-master-20141122/index.php(39): WebApplication->run()

[error] [php] Cannot use a scalar value as an array (/xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveRecord.php:1861)
Stack trace:
#0 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveFinder.php(804): CJoinElement->populateRecord()
#1 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveFinder.php(437): CJoinElement->runQuery()
#2 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveFinder.php(68): CJoinElement->find()
#3 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveRecord.php(1356): CActiveFinder->query()
#4 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveRecord.php(1536): SpaceMembership->query()
#5 /xyz/humhub-master-20141122/protected/modules_core/space/models/SpaceMembership.php(175): SpaceMembership->findAllByAttributes()
#6 /xyz/humhub-master-20141122/protected/modules_core/user/widgets/UserSpacesWidget.php(19): GetUserSpaces()
#7 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(167): UserSpacesWidget->run()
#8 /xyz/humhub-master-20141122/protected/widgets/StackWidget.php(94): ProfileController->widget()
#9 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(173): ProfileSidebarWidget->run()
#10 /xyz/humhub-master-20141122/protected/modules_core/user/views/profile/_layout.php(26): ProfileController->widget()
#11 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(126): require()
#12 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(95): ProfileController->renderInternal()
#13 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(869): ProfileController->renderFile()
#14 /xyz/humhub-master-20141122/protected/components/Controller.php(198): ProfileController->renderPartial()
#15 /xyz/humhub-master-20141122/protected/views/layouts/main.php(211): ProfileController->renderPartial()
#16 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(126): require()
#17 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(95): ProfileController->renderInternal()
#18 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(784): ProfileController->renderFile()
#19 /xyz/humhub-master-20141122/protected/modules_core/user/controllers/ProfileController.php(62): ProfileController->render()
#20 /xyz/humhub-master-20141122/protected/vendors/yii/web/actions/CInlineAction.php(49): ProfileController->actionIndex()
#21 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams()
#22 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CFilterChain.php(133): ProfileController->runAction()
#23 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run()
#24 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter()
#25 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CInlineFilter.php(58): ProfileController->filterAccessControl()
#26 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#27 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(291): CFilterChain->run()
#28 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(265): ProfileController->runActionWithFilters()
#29 /xyz/humhub-master-20141122/protected/vendors/yii/web/CWebApplication.php(282): ProfileController->run()
#30 /xyz/humhub-master-20141122/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController()
#31 /xyz/humhub-master-20141122/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest()
#32 /xyz/humhub-master-20141122/index.php(39): WebApplication->run()

[error] [php] Illegal string offset 'onbeforedelete' (/xyz/humhub-master-20141122/protected/vendors/yii/base/CComponent.php:474)
Stack trace:
#0 /xyz/humhub-master-20141122/protected/components/HActiveRecord.php(53): HInterceptor->intercept()
#1 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveRecord.php(1854): SpaceMembership->init()
#2 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveFinder.php(848): SpaceMembership->populateRecord()
#3 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveFinder.php(804): CJoinElement->populateRecord()
#4 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveFinder.php(437): CJoinElement->runQuery()
#5 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveFinder.php(68): CJoinElement->find()
#6 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveRecord.php(1356): CActiveFinder->query()
#7 /xyz/humhub-master-20141122/protected/vendors/yii/db/ar/CActiveRecord.php(1536): SpaceMembership->query()
#8 /xyz/humhub-master-20141122/protected/modules_core/space/models/SpaceMembership.php(175): SpaceMembership->findAllByAttributes()
#9 /xyz/humhub-master-20141122/protected/modules_core/user/widgets/UserSpacesWidget.php(19): GetUserSpaces()
#10 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(167): UserSpacesWidget->run()
#11 /xyz/humhub-master-20141122/protected/widgets/StackWidget.php(94): ProfileController->widget()
#12 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(173): ProfileSidebarWidget->run()
#13 /xyz/humhub-master-20141122/protected/modules_core/user/views/profile/_layout.php(26): ProfileController->widget()
#14 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(126): require()
#15 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(95): ProfileController->renderInternal()
#16 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(869): ProfileController->renderFile()
#17 /xyz/humhub-master-20141122/protected/components/Controller.php(198): ProfileController->renderPartial()
#18 /xyz/humhub-master-20141122/protected/views/layouts/main.php(211): ProfileController->renderPartial()
#19 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(126): require()
#20 /xyz/humhub-master-20141122/protected/vendors/yii/web/CBaseController.php(95): ProfileController->renderInternal()
#21 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(784): ProfileController->renderFile()
#22 /xyz/humhub-master-20141122/protected/modules_core/user/controllers/ProfileController.php(70): ProfileController->render()
#23 /xyz/humhub-master-20141122/protected/vendors/yii/web/actions/CInlineAction.php(49): ProfileController->actionAbout()
#24 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams()
#25 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CFilterChain.php(133): ProfileController->runAction()
#26 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run()
#27 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter()
#28 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CInlineFilter.php(58): ProfileController->filterAccessControl()
#29 /xyz/humhub-master-20141122/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#30 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(291): CFilterChain->run()
#31 /xyz/humhub-master-20141122/protected/vendors/yii/web/CController.php(265): ProfileController->runActionWithFilters()
#32 /xyz/humhub-master-20141122/protected/vendors/yii/web/CWebApplication.php(282): ProfileController->run()
#33 /xyz/humhub-master-20141122/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController()
#34 /xyz/humhub-master-20141122/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest()
#35 /xyz/humhub-master-20141122/index.php(39): WebApplication->run()
</pre>

Versions : 
PHP 5.4.23
httpd 2.4.6
HumHub Master from 22/11/2014

**Comment by xaro1** [comment]
HumHub + DB migrated to another system (from Fedora 18 to Fedora 21) and all seems to be working normally...

**Comment by michaelwemoto** [comment]
I'm getting the same errors -
[Mon Sep 07 13:59:33.298373 2015] [core:notice] [pid 2773] AH00052: child pid 2777 exit signal Segmentation fault (11)
[Mon Sep 07 14:32:31.599210 2015] [core:notice] [pid 2773] AH00052: child pid 2785 exit signal Segmentation fault (11)
[Mon Sep 07 14:32:34.611410 2015] [core:notice] [pid 2773] AH00052: child pid 2786 exit signal Segmentation fault (11)
[Mon Sep 07 14:32:45.628318 2015] [core:notice] [pid 2773] AH00052: child pid 2775 exit signal Segmentation fault (11)
[Mon Sep 07 14:32:45.628426 2015] [core:notice] [pid 2773] AH00052: child pid 2778 exit signal Segmentation fault (11)
[Mon Sep 07 14:32:45.628557 2015] [core:notice] [pid 2773] AH00052: child pid 2782 exit signal Segmentation fault (11)
[Mon Sep 07 14:32:45.628569 2015] [core:notice] [pid 2773] AH00052: child pid 2783 exit signal Segmentation fault (11)
[Mon Sep 07 14:32:45.628582 2015] [core:notice] [pid 2773] AH00052: child pid 2821 exit signal Segmentation fault (11)
[Mon Sep 07 14:32:45.628592 2015] [core:notice] [pid 2773] AH00052: child pid 2822 exit signal Segmentation fault (11)
[Mon Sep 07 14:32:45.628602 2015] [core:notice] [pid 2773] AH00052: child pid 2823 exit signal Segmentation fault (11)

This is a fresh centos7.1 install, I struggled and got everything working with selinux enabled and once I completed the setup process I am unable to login. any suggestions?

**Comment by myusufe** [comment]
I have the same error also.

Have anyone fixed this issue?
