### ISSUE TITLE
HumHumb 1.3.177 to 1.5.2 update loses topic order in spaces

### ISSUE THREAD

**Issue by alexszilagyi** [humhub/humhub#4196]
### What steps will reproduce the problem?
I have upgraded from 1.3.17 to 1.5.2 (each version of a time)
### What is the expected result?
On spaces I have lost the order of the topic, for all spaces

### What do you get instead?
Insted of ordered topics: from zero to max number I've got all zero as values.
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.2
| PHP version      |  7.2.31
| Operating system | Centos 7.8

**Comment by buddh4** [comment]
The topic sort_order was introduced in HumHub 1.4. In 1.3 you could not manually sort topics, perhaps we are missing a second order by name.
