### ISSUE TITLE
Delete pending registrations automatically

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#4225]
Entries of pending registrations/invitations should be deleted automatically after a period of time or at least the admin should be able to 'select all' and delete them. The list gets quite messy after a while otherwise.

**Comment by MasterHans** [comment]
@buddh4 Did you mean this list?
![invite-list](https://user-images.githubusercontent.com/17376109/96353711-51b8a300-10d7-11eb-82ed-109e1552ab0f.png)

**Comment by luke-** [comment]
@MasterHans It's about this entries: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/admin/controllers/PendingRegistrationsController.php#L44

**Comment by siwa-tkapplmueller** [comment]
Wouldn't it make a lot more sense for admins to be able to disable / configure this feature in the admin settings rather than just automatically deleting all invites after a fixed period of time without any possibility to disable that or change the amount of days before deleting?
