### ISSUE TITLE
Auto enable "Hide file info (name, size) for images on wall" option

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4230]
Currently the "Hide file info (name, size) for images on wall" seems to be disabled by default. This option prevents attached post images from being listed in the attached file info list of a wallentry and can be changed in `Administration -> Settigns -> Advanced -> Files`.

Without this setting enabled:

![grafik](https://user-images.githubusercontent.com/9800854/87452377-75b0a800-c601-11ea-92be-f4cb60e9cbbe.png)

With setting enabled:

![grafik](https://user-images.githubusercontent.com/9800854/87452543-9d077500-c601-11ea-9ea9-5407ebc695a0.png)

Furthermore we should move it to the `Administration -> Appearance`.

**Comment by luke-** [comment]
+1

**Comment by luke-** [comment]
Fixed by: https://github.com/humhub/humhub/pull/4353

**Comment by buddh4** [comment]
One issue left: Currently only images are hidden but no mp3, mp4, should I open another issue?

**Comment by luke-** [comment]
@buddh4 Yes please, and maybe we should rename it to "hideMediaFileInfo"
