### ISSUE TITLE
Cronjob error with APCu

### ISSUE THREAD

**Issue by der-phillip** [humhub/humhub#4239]
If t turn APC(u) to File, the cronjobs works fine.

###################

user:/html/humhub/protected > ./yii
Exception 'yii\base\InvalidConfigException' with message 'ApcCache requires PHP apcu extension to be loaded.'

in /html/humhub/protected/vendor/yiisoft/yii2/caching/ApcCache.php:47

Stack trace:
#0 /html/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\caching\ApcCache->init()
#1 [internal function]: yii\base\BaseObject->__construct(Array)
#2 /html/humhub/protected/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#3 /html/humhub/protected/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('yii\\caching\\Apc...', Array, Array)
#4 /html/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('yii\\caching\\Apc...', Array, Array)
#5 /html/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#6 /html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('cache', true)
#7 /html/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('cache')
#8 /html/humhub/protected/humhub/libs/BaseSettingsManager.php(170): yii\di\ServiceLocator->__get('cache')
#9 /html/humhub/protected/humhub/libs/BaseSettingsManager.php(51): humhub\libs\BaseSettingsManager->loadValues()
#10 /html/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\libs\BaseSettingsManager->init()
#11 [internal function]: yii\base\BaseObject->__construct(Array)
#12 /html/humhub/protected/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#13 /html/humhub/protected/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('humhub\\componen...', Array, Array)
#14 /html/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\componen...', Array, Array)
#15 /html/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#16 /html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('settings', true)
#17 /html/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('settings')
#18 /html/humhub/protected/humhub/components/console/Application.php(44): yii\di\ServiceLocator->__get('settings')
#19 /html/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\console\Application->init()
#20 /html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#21 /html/humhub/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#22 /html/humhub/protected/yii(28): yii\console\Application->__construct(Array)
#23 [main]

###################

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.2
| PHP version      |  7.4.1

**Comment by luke-** [comment]
Make sure that the APCu extension is also enabled in the `php.ini` file used by the cli.
