### ISSUE TITLE
MySQL - table `comment` : Add an index for the fields `object_model` and `object_id`

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4251]
### Is your feature request related to a problem? Please describe.

In a custom module, if you need to do a left join on the `content` table (ActiveRecord model `Content`):
```
        $content->query->leftJoin(
            'comment',
            'comment.object_id = content.object_id
        );
```

The network activity stream is very slow to load.

### Describe the solution you'd like

Add an index for the fields `object_model` and `object_id` solves the problem:
```
ALTER TABLE `comment` ADD INDEX `index_object_model` (`object_model`,`object_id`)
```

Thanks.

**Comment by buddh4** [comment]
Think indexing object id should be sufficient. Indexing the model is probably ptoblematic due to index size limitations. Also there are currently only two types of models used in this table, at least in most cases. .

**Comment by buddh4** [comment]
Also we should analyze why this affects the activity stream, there should be no comment fetching on in the activity stream.

**Comment by funkycram** [comment]
Sure, but this is for a custom module developpment, adding a filter for `\humhub\modules\stream\models\filters\StreamQueryFilter`.

And yes
```
ALTER TABLE `comment` ADD INDEX `index_object` (`object_id`)
```
is enough

**Comment by luke-** [comment]
https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/comment/migrations/m200715_184207_commentIndex.php#L15

I've added this with 1.6

Do you see any problems here?

**Comment by buddh4** [comment]
@luke- Do you think the object_model index makes sense, there are only content and comment models used? Regarding the index length it should not be a problem since the object_model is limited to 100.

**Comment by luke-** [comment]
@buddh4 As I understand it, it is an index of object_model AND object_id. I hope the index refers to the combination, otherwise of course object_id is sufficient.

**Comment by buddh4** [comment]
Yes, it is a combined index, just not sure if this is necessary when only having two distinct values in one of the indexed columns.

**Comment by luke-** [comment]
Changed here: https://github.com/humhub/humhub/pull/4277
