### ISSUE TITLE
Notification dropdown issue on mobile

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4257]
![Screenshot_20200721_232652_com.android.chrome.jpg](https://user-images.githubusercontent.com/9800854/88109248-77064580-cbaa-11ea-815b-65a0e1fcd0f8.jpg)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6
| PHP version      | 
| Operating system |

**Comment by MasterMindNET** [comment]
What is wrong with it?

Are you talking about the text which is going off the boundaries?

Thank you!

**Comment by luke-** [comment]
The green box should be positioned to the right of the red box.
![image](https://user-images.githubusercontent.com/4736168/88520118-70852d00-cff3-11ea-85d5-7b4041352f36.png)

**Comment by MasterMindNET** [comment]
I get it.

Could you please te me knwo how I can see the notifications?

I have got the next setup:
![image](https://user-images.githubusercontent.com/22347676/88933307-e4d7fe80-d287-11ea-9f39-30bfd7e3f68c.png)

Thank you!

**Comment by luke-** [comment]
Make sure that the background jobs are running, maybe that's why no notifications are triggered.

**Comment by buddh4** [comment]
You can also configure [Instant or Sync Queue](https://docs.humhub.org/docs/admin/asynchronous-tasks#sync-and-instant-queue) in your test environment.

**Comment by MasterMindNET** [comment]
I believe this issues can be closed, please, check this out:
https://github.com/humhub/humhub/pull/4314

Thank you!

**Comment by luke-** [comment]
@MasterMindNET ok thanks!
