### ISSUE TITLE
New ContentVisibilitySelect is missing a CreatePublicContent permission check

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4263]
The ContentVisibilitySelect form widget introduced with 1.6 does not check for CreatePublicContent permission on the container.

**Comment by buddh4** [comment]
We should also implement this visibility check in a helper function, for custom module development and furthermore add such a validation to the base content model (Perhaps just force private visibility instead of blocking save).

**Comment by luke-** [comment]
https://github.com/humhub/humhub/pull/4270
