### ISSUE TITLE
Random quotes snippet

### ISSUE THREAD

**Issue by xdCL** [humhub/humhub#4266]
### Is your feature request related to a problem? Please describe.

I think snippets on dashboard are great, but, will it be possible to do a snippet (custom pages), show a phrase, image, quote, randomly?

### Describe the solution you'd like

Perform this system in the dashboard snippets.

### Describe alternatives you've considered

Maybe integration of some code to load from a list every time, randomly, in the snippet.

Thank you for your attention!

**Comment by ArchBlood** [comment]
I believe you're looking for something like what this module does.

https://github.com/bumrufus/humhub-modules-quotes
