### ISSUE TITLE
Guess timezone for new accounts

### ISSUE THREAD

**Issue by samsheridan** [humhub/humhub#4272]
Right now, when users join their profile uses the default timezone set by an administrator. The place to change it is not obvious to most users. It is confusing when they see a calendar event and it's showing a weird timezone.

I propose that HumHub tries to use the time from a user's browser and perhaps location information (or whatever the best practice is) to set the timezone when a user registers, or maybe even every time a user logs in.

Alternatively, the timezone setting should be able to be shown at registration so the user can set it right away.

**Comment by buddh4** [comment]
Perhaps we should ask for the timezone while registration.
