### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'profile.email_virtual' in 'where clause'

### ISSUE THREAD

**Issue by cayolblake** [humhub/humhub#4274]
### What steps will reproduce the problem?
1. Running latest pull from "develop" branch.

2. Clicking on any user tag.

```
Database Exception – yii\db\Exception

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'profile.email_virtual' in 'where clause'
The SQL being executed was: SELECT COUNT(*) FROM `user` LEFT JOIN `profile` ON `user`.`id` = `profile`.`user_id` WHERE (`user`.`status`=1) AND ((`user`.`username` LIKE '%Yoga%') OR (`user`.`email` LIKE '%Yoga%') OR (`user`.`tags` LIKE '%Yoga%') OR (`profile`.`firstname` LIKE '%Yoga%') OR (`profile`.`lastname` LIKE '%Yoga%') OR (`profile`.`title` LIKE '%Yoga%') OR (`profile`.`gender` LIKE '%Yoga%') OR (`profile`.`street` LIKE '%Yoga%') OR (`profile`.`zip` LIKE '%Yoga%') OR (`profile`.`city` LIKE '%Yoga%') OR (`profile`.`country` LIKE '%Yoga%') OR (`profile`.`state` LIKE '%Yoga%') OR (`profile`.`birthday` LIKE '%Yoga%') OR (`profile`.`about` LIKE '%Yoga%') OR (`profile`.`phone_private` LIKE '%Yoga%') OR (`profile`.`phone_work` LIKE '%Yoga%') OR (`profile`.`mobile` LIKE '%Yoga%') OR (`profile`.`email_virtual` LIKE '%Yoga%') OR (`profile`.`fax` LIKE '%Yoga%') OR (`profile`.`im_skype` LIKE '%Yoga%') OR (`profile`.`im_xmpp` LIKE '%Yoga%') OR (`profile`.`url` LIKE '%Yoga%') OR (`profile`.`url_facebook` LIKE '%Yoga%') OR (`profile`.`url_linkedin` LIKE '%Yoga%') OR (`profile`.`url_xing` LIKE '%Yoga%') OR (`profile`.`url_youtube` LIKE '%Yoga%') OR (`profile`.`url_vimeo` LIKE '%Yoga%') OR (`profile`.`url_flickr` LIKE '%Yoga%') OR (`profile`.`url_myspace` LIKE '%Yoga%') OR (`profile`.`url_twitter` LIKE '%Yoga%'))
Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'profile.email_virtual' in 'where clause'
)
↵
Caused by: PDOException

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'profile.email_virtual' in 'where clause'

in ~/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 1293

``` 

### Additional info
| HumHub version   | 3f22f75c2c803d744e1c25136dc0b8f5cd27dbfb
| PHP version      | 7.4

**Comment by buddh4** [comment]
Is there a full stack trace available?

**Comment by buddh4** [comment]
We need to make sure those flags are set to 0 for vitual fields, and ideally not editable when creating the field:

```
MariaDB [humhub_dev]> select field_type_class, required, show_at_registration, editable, visible from profile_field where id = 31;
+------------------------------------------------+----------+----------------------+----------+---------+
| field_type_class                               | required | show_at_registration | editable | visible |
+------------------------------------------------+----------+----------------------+----------+---------+
| humhub\modules\user\models\fieldtype\UserEmail |        1 |                    1 |        1 |       1 |
+------------------------------------------------+----------+----------------------+----------+---------+
```

**Comment by cayolblake** [comment]
Thanks for the quick fix.

I pulled the latest and the problem still persists. I assume I should run a certain SQL query to get this fixed on my current database?

**Comment by buddh4** [comment]
Can you post the full error stack from `Administration -> Information -> Logging`? I can't recreate the issue with https://github.com/humhub/humhub/pull/4275

**Comment by cayolblake** [comment]
Here's the latest logged one.

`PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'profile.email_virtual' in 'where clause' in ~/humhub/protected/vendor/yiisoft/yii2/db/Command.php:1293 Stack trace: #0 ~/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute() #1 ~/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute() #2 ~/humhub/protected/vendor/yiisoft/yii2/db/Command.php(427): yii\db\Command->queryInternal() #3 ~/humhub/protected/vendor/yiisoft/yii2/db/Query.php(494): yii\db\Command->queryScalar() #4 ~/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(352): yii\db\Query->queryScalar() #5 ~/humhub/protected/vendor/yiisoft/yii2/db/Query.php(366): yii\db\ActiveQuery->queryScalar() #6 ~/humhub/protected/humhub/modules/directory/controllers/DirectoryController.php(98): yii\db\Query->count() #7 [internal function]: humhub\modules\directory\controllers\DirectoryController->actionMembers() #8 ~/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #9 ~/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams() #10 ~/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction() #11 ~/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction() #12 ~/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest() #13 ~/humhub/index.php(25): yii\base\Application->run() #14 {main} Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'profile.email_virtual' in 'where clause' The SQL being executed was: SELECT COUNT(*) FROM `user` LEFT JOIN `profile` ON `user`.`id` = `profile`.`user_id` WHERE (`user`.`status`=1) AND ((`user`.`username` LIKE '%Microsoft%') OR (`user`.`email` LIKE '%Microsoft%') OR (`user`.`tags` LIKE '%Microsoft%') OR (`profile`.`firstname` LIKE '%Microsoft%') OR (`profile`.`lastname` LIKE '%Microsoft%') OR (`profile`.`title` LIKE '%Microsoft%') OR (`profile`.`gender` LIKE '%Microsoft%') OR (`profile`.`street` LIKE '%Microsoft%') OR (`profile`.`zip` LIKE '%Microsoft%') OR (`profile`.`city` LIKE '%Microsoft%') OR (`profile`.`country` LIKE '%Microsoft%') OR (`profile`.`state` LIKE '%Microsoft%') OR (`profile`.`birthday` LIKE '%Microsoft%') OR (`profile`.`about` LIKE '%Microsoft%') OR (`profile`.`phone_private` LIKE '%Microsoft%') OR (`profile`.`phone_work` LIKE '%Microsoft%') OR (`profile`.`mobile` LIKE '%Microsoft%') OR (`profile`.`email_virtual` LIKE '%Microsoft%') OR (`profile`.`fax` LIKE '%Microsoft%') OR (`profile`.`im_skype` LIKE '%Microsoft%') OR (`profile`.`im_xmpp` LIKE '%Microsoft%') OR (`profile`.`url` LIKE '%Microsoft%') OR (`profile`.`url_facebook` LIKE '%Microsoft%') OR (`profile`.`url_linkedin` LIKE '%Microsoft%') OR (`profile`.`url_xing` LIKE '%Microsoft%') OR (`profile`.`url_youtube` LIKE '%Microsoft%') OR (`profile`.`url_vimeo` LIKE '%Microsoft%') OR (`profile`.`url_flickr` LIKE '%Microsoft%') OR (`profile`.`url_myspace` LIKE '%Microsoft%') OR (`profile`.`url_twitter` LIKE '%Microsoft%')) AND ((`user`.`username` LIKE '%Office%') OR (`user`.`email` LIKE '%Office%') OR (`user`.`tags` LIKE '%Office%') OR (`profile`.`firstname` LIKE '%Office%') OR (`profile`.`lastname` LIKE '%Office%') OR (`profile`.`title` LIKE '%Office%') OR (`profile`.`gender` LIKE '%Office%') OR (`profile`.`street` LIKE '%Office%') OR (`profile`.`zip` LIKE '%Office%') OR (`profile`.`city` LIKE '%Office%') OR (`profile`.`country` LIKE '%Office%') OR (`profile`.`state` LIKE '%Office%') OR (`profile`.`birthday` LIKE '%Office%') OR (`profile`.`about` LIKE '%Office%') OR (`profile`.`phone_private` LIKE '%Office%') OR (`profile`.`phone_work` LIKE '%Office%') OR (`profile`.`mobile` LIKE '%Office%') OR (`profile`.`email_virtual` LIKE '%Office%') OR (`profile`.`fax` LIKE '%Office%') OR (`profile`.`im_skype` LIKE '%Office%') OR (`profile`.`im_xmpp` LIKE '%Office%') OR (`profile`.`url` LIKE '%Office%') OR (`profile`.`url_facebook` LIKE '%Office%') OR (`profile`.`url_linkedin` LIKE '%Office%') OR (`profile`.`url_xing` LIKE '%Office%') OR (`profile`.`url_youtube` LIKE '%Office%') OR (`profile`.`url_vimeo` LIKE '%Office%') OR (`profile`.`url_flickr` LIKE '%Office%') OR (`profile`.`url_myspace` LIKE '%Office%') OR (`profile`.`url_twitter` LIKE '%Office%')) in ~/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:677 Stack trace: #0 ~/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException() #1 ~/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute() #2 ~/humhub/protected/vendor/yiisoft/yii2/db/Command.php(427): yii\db\Command->queryInternal() #3 ~/humhub/protected/vendor/yiisoft/yii2/db/Query.php(494): yii\db\Command->queryScalar() #4 ~/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(352): yii\db\Query->queryScalar() #5 ~/humhub/protected/vendor/yiisoft/yii2/db/Query.php(366): yii\db\ActiveQuery->queryScalar() #6 ~/humhub/protected/humhub/modules/directory/controllers/DirectoryController.php(98): yii\db\Query->count() #7 [internal function]: humhub\modules\directory\controllers\DirectoryController->actionMembers() #8 ~/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #9 ~/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams() #10 ~/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction() #11 ~/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction() #12 ~/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest() #13 ~/humhub/index.php(25): yii\base\Application->run() #14 {main} Additional Information: Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'profile.email_virtual' in 'where clause' )
`

**Comment by cayolblake** [comment]
Never mind, I forgot to checkout "fix/4274". 

Seems to be fixed now.
