### ISSUE TITLE
Yii2 doesn't work with latest MySQL server version (8.0.21)

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4287]
In https://docs.humhub.org/docs/admin/requirements it is written MySQL 5.7+

But the latest MySQL version 8.0.21 is not compatible with the current Yii2 framework : https://github.com/yii2tech/ar-variation/issues/25

This MySQL makes Humhub crash:
![image](https://user-images.githubusercontent.com/23310825/88897544-bb997d00-d24b-11ea-9a12-5b991ee15de0.png)

**Comment by buddh4** [comment]
https://github.com/yiisoft/yii2/issues/18171

**Comment by davidtessier** [comment]
Yeah 1.6 broke my HumHub for the same reason.

**Comment by luke-** [comment]
@davidtessier is this occur with HumHub 1.6?

**Comment by davidtessier** [comment]
I believe so. 

Last night I upgraded from 1.5.2 to 1.5.3 and then immediately to 1.6. I suppose I don’t know if it’s 1.6 or 1.5.3 that broke my instance. I get the following error. 

`
ERROR  Thu, 30 Jul 2020 16:24:49 -0400  yii\base\ErrorException:8
yii\base\ErrorException: Undefined index: constraint_name in /var/www/humhub/protected/vendor/yiisoft/yii2/db/mysql/Schema.php:394 Stack trace: #0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/mysql/Schema.php(394): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/humhub...', 394, Array) #1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/mysql/Schema.php(126): yii\db\mysql\Schema->findConstraints(Object(yii\db\TableSchema)) #2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php(757): yii\db\mysql\Schema->loadTableSchema('content_tag') #3 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php(193): yii\db\Schema->getTableMetadata('content_tag', 'schema', false) #4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(435): yii\db\Schema->getTableSchema('content_tag') #5 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(469): yii\db\ActiveRecord::getTableSchema() #6 /var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(500): yii\db\ActiveRecord->attributes() #7 /var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(315): yii\db\BaseActiveRecord->hasAttribute('module_id') #8 /var/www/humhub/protected/humhub/modules/content/models/ContentTag.php(136): yii\db\BaseActiveRecord->__set('module_id', 'topic') #9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\content\models\ContentTag->init() #10 /var/www/humhub/protected/humhub/modules/content/models/ContentTag.php(112): yii\base\BaseObject->__construct(Array) #11 /var/www/humhub/protected/humhub/modules/content/models/ContentTag.php(395): humhub\modules\content\models\ContentTag->__construct() #12 /var/www/humhub/protected/humhub/modules/content/models/ContentTag.php(351): humhub\modules\content\models\ContentTag::moduleQuery(Object(yii\db\ActiveQuery)) #13 /var/www/humhub/protected/humhub/modules/content/models/ContentTag.php(339): humhub\modules\content\models\ContentTag::addQueryCondition(Object(yii\db\ActiveQuery)) #14 /var/www/humhub/protected/humhub/modules/content/models/ContentTag.php(615): humhub\modules\content\models\ContentTag::find() #15 [internal function]: humhub\modules\content\models\ContentTag::findByContainer(Object(humhub\modules\user\models\User), true) #16 /var/www/humhub/protected/humhub/modules/content/widgets/ContentTagPicker.php(52): call_user_func(Array, Object(humhub\modules\user\models\User), true) #17 /var/www/humhub/protected/humhub/modules/content/widgets/ContentTagPicker.php(46): humhub\modules\content\widgets\ContentTagPicker->findDefaults() #18 /var/www/humhub/protected/humhub/modules/topic/widgets/TopicPicker.php(55): humhub\modules\content\widgets\ContentTagPicker->init() #19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\topic\widgets\TopicPicker->init() #20 [internal function]: yii\base\BaseObject->__construct(Array) #21 /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array) #22 /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('humhub\\modules\\...', Array, Array) #23 /var/www/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\modules\\...', Array, Array) #24 /var/www/humhub/protected/humhub/components/Widget.php(60): yii\BaseYii::createObject(Array) #25 /var/www/humhub/protected/humhub/modules/content/widgets/views/wallCreateContentForm.php(59): humhub\components\Widget::widget(Array) #26 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...') #27 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/humhub...', Array) #28 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/humhub...', Array, Object(humhub\modules\post\widgets\Form)) #29 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\post\widgets\Form)) #30 /var/www/humhub/protected/humhub/modules/content/widgets/WallCreateContentForm.php(100): yii\base\Widget->render('@humhub/modules...', Array) #31 /var/www/humhub/protected/humhub/modules/post/widgets/Form.php(45): humhub\modules\content\widgets\WallCreateContentForm->run() #32 /var/www/humhub/protected/humhub/components/Widget.php(63): humhub\modules\post\widgets\Form->run() #33 /var/www/humhub/protected/humhub/modules/dashboard/widgets/DashboardContent.php(26): humhub\components\Widget::widget(Array) #34 /var/www/humhub/protected/humhub/components/Widget.php(63): humhub\modules\dashboard\widgets\DashboardContent->run() #35 /var/www/humhub/protected/humhub/modules/dashboard/views/dashboard/index.php(20): humhub\components\Widget::widget(Array) #36 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...') #37 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/humhub...', Array) #38 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/humhub...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #39 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(409): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #40 /var/www/humhub/protected/humhub/modules/dashboard/controllers/DashboardController.php(69): yii\base\Controller->render('index', Array) #41 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #42 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #43 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #44 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #45 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array) #46 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #47 /var/www/humhub/index.php(25): yii\base\Application->run() #48 {main}
`

**Comment by davidtessier** [comment]
I will say I migrated to Ubuntu server 20.04 a week or so ago and HumHub was working with it well (considering we have a small, family user base)  on version 1.5.2.

**Comment by funkycram** [comment]
No, not related to Humhub 1.6
The problem occurs with all versions : 1.3, 1.5 and 1.6
It is only related to the latest MySQL version with Yii2.

**Comment by buddh4** [comment]
- Fix in craftCMS: https://github.com/darkdef/yii2/commit/933fb25dfe72a3b61f0e22dbe2a4f094714f5379
- Fix in yii core: https://github.com/yiisoft/yii2/pull/18176/files

Until the next yii release we could provide a custom `db/mysql/Schema.php` replacement.

**Comment by luke-** [comment]
@buddh4 Should we wait for the Yii2 release and update with 1.6.1 or add a hotfix like Craft CMS? We could also backport the hotfix to 1.5 or 1.4.

**Comment by funkycram** [comment]
I have tried the fix https://github.com/yiisoft/yii2/pull/18176/files in Humhub 1.3 and 1.5: works perfectly !

**Comment by davidtessier** [comment]
You are all voodoo wizards! Thank you for a quick fix. I had to do the update the manual way as opposed to the web UI method, but it was easy and my instance is up again. Thank you!!!

**Comment by funkycram** [comment]
Yes, each time a critical bug appear, you solve it strait away, many thanks !
