### ISSUE TITLE
Richtext: Automatic URL recognition and create link tag 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4290]
### Is your feature request related to a problem? Please describe.

Create a text with a valid URL like https://www.google.com

### Describe the solution you'd like

See a clickable link 

### Describe alternatives you've considered

Leave it as it is or create a Markdown Link Element

@buddh4 Is there any reasons for not automatically create link tags?

**Comment by buddh4** [comment]
You mean when typing an url manually instead of copy paste?

**Comment by luke-** [comment]
Yes, it's a migration from HumHub 1.1 and there all URLs are no longer clickable

**Comment by buddh4** [comment]
There was a parser active replacing such links with markdown links for such legacy content, the problem was this also replaced links e.g. in code blocks and therefore was replaced. We could add auto link creation as markdown-it plugin directly in the richtext.

**Comment by Carl2213** [comment]
Perhaps an exception can be made for code blocks and quotes? Or, if it gets auto linkified within the richtext, the user can manually remove the link if it's not desired.

**Comment by luke-** [comment]
Ok, since the problem only affects very old HumHub installations and mostly posts I think we can ignore the problem.
Maybe I can find an individual solution for my case here.

Thanks!

**Comment by ArchBlood** [comment]
Should check if the output is sending URLs as `<span>http://example.com</span>` or `http://<span></span>example.com` that's pretty much how you can do it on GitHub. :thinking:
https://gist.github.com/alexpeattie/4729247

**Comment by buddh4** [comment]
I've opened an feature request https://github.com/humhub/humhub/issues/4307
