### ISSUE TITLE
LinkPreview and comment threads attached to wrong posts

### ISSUE THREAD

**Issue by verement** [humhub/humhub#4292]
### What steps will reproduce the problem?

Not clear, but since upgrading to 1.6.0, the problem exists when multiple posts are displayed in a stream, and some of them have attached link previews and comments. The problem does not seem to occur when individual posts are shown (e.g. by clicking on activity links or opening permalinks).

### What is the expected result?

The link preview and comments should be attached to the post they were created for.

### What do you get instead?

Sometimes the link preview and comment thread shown as attached to a post actually belong to another post  (which is otherwise unseen in the stream).

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.0
| PHP version      | 7.3.19
| Operating system | Debian

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by verement** [comment]
Here is an example of what I’m seeing:

```html
<div class="wall-entry" data-content-container-id="4" data-stream-entry="1" data-stream-pinned="0" data-action-component="stream.StreamEntry" data-content-key="2548" style="opacity: 1;">
    <div class="panel panel-default wall_humhubmodulespostmodelsPost_347”>  <!-- note id -->
        <div class="panel-body">
            <div class="media”>
                <!-- ... -->
                <div class="content" id="wall_content_humhubmodulespostmodelsPost_347”>  <!-- note id -->
                    <div class="stream-entry-addons clearfix”>
                        <!-- ... -->
                        <div class="well well-small comment-container" style="" id="comment_humhubmodulespostmodelsPost_343”>  <!-- note id -->
                            <!-- ... -->
                        </div>
                        <!-- ... -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

Notice the differing post ids between the content (wall_content_humhubmodulespostmodelsPost_**347**) and comments (comment_humhubmodulespostmodelsPost_**343**). All of the comments shown are for Post 343 and not for Post 347 which the comments are displayed under.

Any hints on where I could start looking for the cause?

**Comment by luke-** [comment]
Can you reproduce the problem with our hosting? Does it only occur in combination with the Link Preview module?

**Comment by buddh4** [comment]
Could you try to recreate this (perhaps in a test space of yours) and describe step for step when this occures. I could not recreate this. Are you using a custom theme?

**Comment by verement** [comment]
FYI I believe I have traced this problem to an errant OEmbed provider. The provider was returning HTML containing a self-closing `<iframe …/>` tag which turns out to be invalid. After the OEmbed HTML was corrected to return `<iframe …></iframe>` the problem went away.

**Comment by luke-** [comment]
Thanks for the info!
