### ISSUE TITLE
Error: Call to a member function can() on null 

### ISSUE THREAD

**Issue by LogRol** [humhub/humhub#4294]
Hi,

I have recently installed HumHub after the update on my hosting and I got the following error when accessing my main (admin) profile: Error: Call to a member function can() on null. This affects only the streamline of my profile: https://prnt.sc/tsdh6h

Apart from this I also have a symfony proc_open error: https://prnt.sc/tsdhgg

Thanks in advance,

Kind Regards,
LogRol

**Comment by ArchBlood** [comment]
`proc_open` error is either you don't have the PHP extension installed or it's disabled on your server, best to contact your server provider about this one, as for the other error, what version of PHP are you using, what version of HumHub are you using? More information is needed.

**Comment by LogRol** [comment]
Hi,

How can I install this extension? However since I have installed it via Softaculus I think its installed. 

I'm using the newest 1.6.0 HumHub and my server is running with PHP 7.2.32

**Comment by LogRol** [comment]
proc_open error solved by my server provider, the other error is still happening
