### ISSUE TITLE
Ajax search with filters

### ISSUE THREAD

**Issue by CarlSinclair** [humhub/humhub#4298]
### Is your feature request related to a problem? Please describe.
Related to #3403, #1839 and #1358
Search is slow, unsorted, requires reloading, and lacks even stream filters.
### Describe the solution you'd like
1. Ajax support. I don't think autocomplete would be useful for large networks, but results should appear as you type, like with @
2. Results sorted from most recent to oldest
3. Search filters:
-Stream filters
-Show posts from friends
-Show posts from joined spaces
-By date
-By profile fields (location, workplace, tags, etc). This would make the tags feature a lot more useful.
-By post type (module wall entries)

**Comment by funkycram** [comment]
+1 (mainly the sort by date)
And also the ADD and OR syntax
Thanks !

**Comment by Carl2213** [comment]
I think AND and OR are a bit too advanced for a social network, but that would definitely be cool.

The current implementation just isn't useful at all in most scenarios. If you need to search more than one word, it'll show all instances of EITHER word, not both. And of course the results aren't sorted at all and are completely random so it's a nightmare to find a post I know I've seen before in the community even.

**Comment by spoorun** [comment]
People are often used to using quote marks for a phrase, or could have a box to search a phrase

**Comment by funkycram** [comment]
I think this is one of the most important features missing in Humhub.

1) Zend Lucene is so slow, that on platforms with many contents, it your search has many keywords, it can take more than one minute to display the results on a dedicated server with 4 CPU !

2) Sorting by date

3) Adding filters, in the same way as in the spaces:
![image](https://user-images.githubusercontent.com/23310825/140511682-0badb54d-ec93-41eb-bdaa-de7bfc415f7c.png)

**Comment by marc-farre** [comment]
Update:
Now searches uses `AND` operator and results are sorted by date.
And the search engine is much faster, no timeout anymore.
