### ISSUE TITLE
Feature: Choosing JPEG compression quality

### ISSUE THREAD

**Issue by xaro1** [humhub/humhub#430]
Actually, JPEG compression quality is a static value fixed to 100. With a value of 95, the perceptible quality is unchanged but the file size is 3 to 4x smaller.

It would be great to have an option to choose the JPEG compression quality in administrative panel, whether 0-100% slider, input box or defined list like this : 
- low 25%
- mid 50%
- standard (default 75%)
- high 95% (BEST compromise size vs. quality)
- ultra 100%

This feature should also convert again all files previously processed.

**Comment by xaro1** [comment]
4 years later, same problem but much more problematic due to higher pictures resolutions.

I upload 1.8MB JPEG picture, resulting a 5.6MB size after processed by HH. It's a nonsense.

It would be great to fix a value from 70 to 75% (but NOT 100) or add a configuration option.

**Comment by petrk94** [comment]
I would like to fix this, with my PHP skills not a problem, but the whole thing is build in Yii and I have no idea how to get in it and the documentation is not clear enough how to make own customizations like this.
But it should not be a problem to make a php html slider write the value to database and Yii could read this instead of using a fixed value :/ sorry that I cant help in it.

**Comment by xaro1** [comment]
I think image conversion stuff is here : /protected/humhub//modules/file/libs/ImageConverter.php

**Comment by luke-** [comment]
> I upload 1.8MB JPEG picture, resulting a 5.6MB size after processed by HH. It's a nonsense.

@xaro1 can you please provide steps to reproduce?

Fyi, we're planning to switch to another libary like yii2-imagine in future...

**Comment by xaro1** [comment]
1. take a picture, get the filesize then upload file
2. click to view uploaded picture
3. download (save as) the picture and see the new filesize

The problem is the quality of JPEG compression fixed to 100. Changing lib will not change the way of JPEG compression with similar values.

**Comment by xaro1** [comment]
PLEASE PLEASE PLEASE, anyone can change JPEG compression to 70 instead of 100 ?

Our HH instance is unusable sometimes due to high bandwidth consumption.

**Comment by xaro1** [comment]
```
--- /root/ImageConverter.php	2018-12-18 10:16:52.626482113 +0100
+++ ImageConverter.php	2018-12-18 10:11:25.724507566 +0100
@@ -43,7 +43,7 @@
 
             if ($gdImage !== null) {
                 $gdImage = self::fixOrientation($gdImage, $sourceFile);
-                imagejpeg($gdImage, $targetFile, 100);
+                imagejpeg($gdImage, $targetFile, 60);
                 imagedestroy($gdImage);
             }
         }

```
