### ISSUE TITLE
Cron/run not working

### ISSUE THREAD

**Issue by laurall11** [humhub/humhub#4309]
Hello,
for a while, I've been getting the following warnings on the front page oy my HumHub installation:

The cron job for the background jobs (queue) does not seem to work properly.
The cron job for the regular tasks (cron) does not seem to work properly.

Now, I'm working with Windows as an OS and hosting HumHub with an Apache server (xampp).
I was able to fix the first problem by configuring the task in the task scheduler, but when trying to run:

`C:\xampp\htdocs\humhub\protected\yii cron/run` in `C:\xampp\php>`, I get the following error and stacktrace:

Running reminder process... done.
Optimizing search index...Exception "ZendSearch\Lucene\Exception\RuntimeException" with message "fopen(C:\xampp\htdocs\humhub\protected\runtime/searchdb/segments.gen): failed to open stream: Permission denied"

in C:\xampp\htdocs\humhub\protected\vendor\nqxcode\zendsearch\library\ZendSearch\Lucene\Index.php:154

Stack trace:
C:\xampp\htdocs\humhub\protected\vendor\nqxcode\zendsearch\library\ZendSearch\Lucene\Index.php(382): ZendSearch\Lucene\Index::getActualGeneration(Object(ZendSearch\Lucene\Storage\Directory\Filesystem))
C:\xampp\htdocs\humhub\protected\vendor\nqxcode\zendsearch\library\ZendSearch\Lucene\Lucene.php(56): ZendSearch\Lucene\Index->__construct('C:\\xampp\\htdocs...', true)
C:\xampp\htdocs\humhub\protected\humhub\modules\search\engine\ZendLuceneSearch.php(352): ZendSearch\Lucene\Lucene::create('C:\\xampp\\htdocs...')
C:\xampp\htdocs\humhub\protected\humhub\modules\search\engine\ZendLuceneSearch.php(332): humhub\modules\search\engine\ZendLuceneSearch->getIndex()
C:\xampp\htdocs\humhub\protected\humhub\modules\search\Events.php(35): humhub\modules\search\engine\ZendLuceneSearch->optimize()
[internal function]: humhub\modules\search\Events::onHourlyCron(Object(yii\base\Event))
C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\base\Event.php(312): call_user_func(Array, Object(yii\base\Event))
C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\base\Component.php(636): yii\base\Event::trigger('humhub\\commands...', 'hourly', Object(yii\base\Event))
C:\xampp\htdocs\humhub\protected\humhub\commands\CronController.php(102): yii\base\Component->trigger('hourly')
C:\xampp\htdocs\humhub\protected\humhub\commands\CronController.php(54): humhub\commands\CronController->runHourly()
[internal function]: humhub\commands\CronController->actionRun()
C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\console\Controller.php(164): yii\base\Controller->runAction('run', Array)
C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\base\Module.php(528): yii\console\Controller->runAction('run', Array)
C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('cron/run', Array)
C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('cron/run', Array)
C:\xampp\htdocs\humhub\protected\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
C:\xampp\htdocs\humhub\protected\yii(29): yii\base\Application->run()
{main}

Thank you very much in advance for anyone who has an idea of how to fix this.

### What steps will reproduce the problem?

-Opening the commandline and trying to run the cronjobs manually

### What is the expected result?

-That the cronjobs were executed properly and the warning thus would go away.

### What do you get instead?

See stacktrace above

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.2 Enterprise Edition
| PHP version      | 7.2.28
| Operating system | Windows

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
It seems that the user under which the CronJob is running cannot access all files in the HumHub directory.
