### ISSUE TITLE
Feature: hashtags

### ISSUE THREAD

**Issue by acki** [humhub/humhub#431]
Hi there

Is it planned to integrate a hashtag function?

Cheers

**Comment by acki** [comment]
Any news? It sucks that you can't just hashtag some keywords

**Comment by sandipp** [comment]
+1

**Comment by samet** [comment]
+1

**Comment by AlDemion** [comment]
+1

**Comment by enginhu** [comment]
+1

**Comment by CKGrafico** [comment]
+1

**Comment by kkayacan** [comment]
+1

**Comment by CKGrafico** [comment]
Suggestion:
With js: search '#' (more or less) in the posts and highlight the word.
Backend: when user click on a hastahg only filter on current space with this word.

not the best form but it's something functional

**Comment by JulienMcJay** [comment]
I would really appreciate the feature in the next release.

**Comment by aerth** [comment]
+1 sounds like a module to me

**Comment by WASasquatch** [comment]
+1

Yeah I though hashtags and post searching was going to be part of 0.11.0-1.
Oh well, next time.

**Comment by JeXawoW** [comment]
+1

**Comment by ToonSoft** [comment]
+1 I hope the hashtags can be part of next release.

**Comment by binitprads** [comment]
+1

**Comment by jakeyjdavis** [comment]
+1

**Comment by paoloimpelluso** [comment]
+1

**Comment by IceSweets** [comment]
+1

**Comment by brainscript** [comment]
+1

**Comment by Censtudios** [comment]
This feature would be really awesome. You could then click the tags to find other related posts.

**Comment by feldrim** [comment]
+1

**Comment by lucasrcsantana** [comment]
+1

**Comment by aerth** [comment]
+9000, who is doing it?

**Comment by vladanPro** [comment]
+1 Is it going to be soon or i better start on my own? tnx

**Comment by Censtudios** [comment]
Probably should start on your own lol =/ Luke said over a year ago he wanted to do this but I guess he focused on other things first. I think hashtags are like a key feature in social networks though.

**Comment by feldrim** [comment]
https://github.com/humhub/humhub/issues/1347

**Comment by tatianaJacques** [comment]
+1 !

**Comment by primantok** [comment]
Hello @luke-

It seems that HumHub use at.js library (https://github.com/ichord/At.js) to handle @mention and :smileys

Is it posible to use Linky library (https://github.com/AnSavvides/jquery.linky) to handle linkify and #hashtag function for v1.2?

> Linky is a jQuery plugin for linkifying URLs, mentions (for Twitter, Instagram or GitHub) and hashtags (for Twitter); that is, taking plain text references of URLs, mentions and hashtags and turning them to the appropriate links. Existing linkified URLs are kept untouched.

Thanks

**Comment by gseilheimer** [comment]
Further Idea: Is there an option to get the information of additional fields from the registration field automatically as an hashtag in the profile?
=> https://github.com/humhub/humhub/issues/1347

**Comment by githubjeka** [comment]
HumHub has bug around hash https://github.com/toopay/bootstrap-markdown/issues/280

**Comment by funkycram** [comment]
Any news ? Thanks !

**Comment by buddh4** [comment]
@funkycram perhaps we could implement a hashtag module as example how to write extensions/plugins for the new wysiwyg editor in 1.3. I've added this to my internal 1.3 editor idea list.

**Comment by dsun29** [comment]
Any update?

**Comment by buddh4** [comment]
Sorry did not have the time yet ;/

**Comment by samuk** [comment]
Any news?
