### ISSUE TITLE
Add "Can Like" Permission 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4310]
### Is your feature request related to a problem? Please describe.

Similar to the "Create comment" permission it would be good to provide a "Can Like" permission as well.

**Comment by MasterMindNET** [comment]
> ### Is your feature request related to a problem? Please describe.
> Similar to the "Create comment" permission it would be good to provide a "Can Like" permission as well.

You mean to add a new class the `protected\humhub\modules\comment\permissions` folder.
By default, who should be able to like the comments?

**Comment by MasterMindNET** [comment]
> ### Is your feature request related to a problem? Please describe.
> Similar to the "Create comment" permission it would be good to provide a "Can Like" permission as well.

You mean to add a new class the `protected\humhub\modules\comment\permissions` folder.
By default, who should be able to like the comments?

Or I should copy the `protected\humhub\modules\comment` whole folder and rework it for the "Can Like"?
