### ISSUE TITLE
User space reactions/activities statistics

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#4312]
### Is your feature request related to a problem? Please describe.
A SPACE OWNER on our humhub says "I want to know how much activities/reactions on my space. If that could be displayed on each space, I will be able to appeal "The space which I have sounds fun!".

### Describe the solution you'd like
The sidemenu of space display the statistics about space activities like a snippet of space members.
Proffesional edition, directory menu displays more information about "Is the space hot recently?"

### Describe alternatives you've considered
The novice member who is uncertain whether to participate could consider the data.
The SNS members are interested in a new space on directory.

**Comment by Carl2213** [comment]
Like user activity? Posts, comments and likes?

**Comment by tomofu74** [comment]
@Carl2213  Thank you for your interesting.
Yes, as you see, there are several possible indicators, but I cannot choose what is best. I can't come up with an idea as to what screen (like some snippet?) should be displayed in what format, too.
I want people who have good ideas to participate in the discussion more and more.
Thank you.

**Comment by Carl2213** [comment]
Yeah, FB has a similar feature in groups.

The "Most active users" module already serves this purpose though, doesn't it? Although on a global scale. It can probably be modified to work on a space scale.

**Comment by Carl2213** [comment]
Or are you talking about "Most active spaces" to determine which spaces have had the most activity recently?

**Comment by tomofu74** [comment]
Mmm... How about like these line graph.
![humhubscreenshot](https://user-images.githubusercontent.com/19162094/89899466-523b4600-dc1d-11ea-8604-72ae0932da43.png)

**Comment by paulooliveira** [comment]
If you have direct access to the DB you can make these queries:

Total Likes = `SELECT count(*) FROM like;`
Total Comments = `SELECT count(*) FROM comment;`
Total Posts = `SELECT count(*) FROM content WHERE content.object_model = 'humhub\\modules\\post\\models\\Post';`


Extracted from: https://github.com/humhub-contrib/mostactiveusers/blob/master/models/ActiveUser.php

**Comment by tomofu74** [comment]
Thank you paulooliveria. I am involved in the operation of a humhub  enterprise edition site. It has a "directory" function, and users can search spaces by any words. But space Not all spaces are active. Users ask me to present some active spaces.
![screenshot](https://user-images.githubusercontent.com/19162094/103324438-f0c02a80-4a8a-11eb-8786-61a287a7cf00.png)

**Comment by ArchBlood** [comment]
@luke- can be closed due to the Analytics module.
