### ISSUE TITLE
How do I resolve Integrity consraint violation?

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#4313]
### What steps will reproduce the problem?
The full error stacks from `Administration --> Information --> Logging` is bellow. And errors from your browser console is not displayed.

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'humhub\modules\activity\jobs\SendMailSummary1' for key 'PRIMARY' in /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Command.php:1293 Stack trace: #0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute() #1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute() #2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->execute() #3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert() #4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal() #5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert() #6 /var/www/html/humhub/protected/humhub/modules/queue/helpers/QueueHelper.php(63): yii\db\BaseActiveRecord->save() #7 /var/www/html/humhub/protected/humhub/modules/queue/Events.php(76): humhub\modules\queue\helpers\QueueHelper::markAsQueued() #8 [internal function]: humhub\modules\queue\Events::onQueueAfterPush() #9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func() #10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger() #11 /var/www/html/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(197): yii\base\Component->trigger() #12 /var/www/html/humhub/protected/humhub/modules/activity/Events.php(41): yii\queue\Queue->push() #13 [internal function]: humhub\modules\activity\Events::onCronHourlyRun() #14 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func() #15 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger() #16 /var/www/html/humhub/protected/humhub/commands/CronController.php(102): yii\base\Component->trigger() #17 /var/www/html/humhub/protected/humhub/commands/CronController.php(54): humhub\commands\CronController->runHourly() #18 [internal function]: humhub\commands\CronController->actionRun() #19 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #20 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams() #21 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction() #22 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction() #23 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #24 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction() #25 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest() #26 /var/www/html/humhub/protected/yii(29): yii\base\Application->run() #27 {main} Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'humhub\modules\activity\jobs\SendMailSummary1' for key 'PRIMARY' The SQL being executed was: INSERT INTO `queue_exclusive` (`id`, `job_message_id`) VALUES ('humhub\\modules\\activity\\jobs\\SendMailSummary1', '813') in /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:677 Stack trace: #0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException() #1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute() #2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->execute() #3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert() #4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal() #5 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert() #6 /var/www/html/humhub/protected/humhub/modules/queue/helpers/QueueHelper.php(63): yii\db\BaseActiveRecord->save() #7 /var/www/html/humhub/protected/humhub/modules/queue/Events.php(76): humhub\modules\queue\helpers\QueueHelper::markAsQueued() #8 [internal function]: humhub\modules\queue\Events::onQueueAfterPush() #9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func() #10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger() #11 /var/www/html/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(197): yii\base\Component->trigger() #12 /var/www/html/humhub/protected/humhub/modules/activity/Events.php(41): yii\queue\Queue->push() #13 [internal function]: humhub\modules\activity\Events::onCronHourlyRun() #14 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func() #15 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger() #16 /var/www/html/humhub/protected/humhub/commands/CronController.php(102): yii\base\Component->trigger() #17 /var/www/html/humhub/protected/humhub/commands/CronController.php(54): humhub\commands\CronController->runHourly() #18 [internal function]: humhub\commands\CronController->actionRun() #19 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #20 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams() #21 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction() #22 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction() #23 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #24 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction() #25 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest() #26 /var/www/html/humhub/protected/yii(29): yii\base\Application->run() #27 {main} Additional Information: Array ( [0] => 23000 [1] => 1062 [2] => Duplicate entry 'humhub\modules\activity\jobs\SendMailSummary1' for key 'PRIMARY' )

### What is the expected result?
humhub cron try to sending hourly mail for users.

### What do you get instead?
It seems to humhub could not send any mail.

### Additional info
Administrator run the command on server : " php yii integrity/run" and All integrity checks done twice.
 But it continue report the violation.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.2
| PHP version      |  7.4
| Operating system | Ubuntu20.4

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by tomofu74** [comment]
integrity check result:

*** Performing database integrity checks

Validating: Calendar Module (5 reminder entries)
Validating: Calendar Module (6 reminder sent entries)
Validating: CFile Module (19 entries)
Validating: CFile Module (19 entries)
Validating: Polls Module - Answers (3 entries)
Validating: Polls Module - Answers User (2 entries)
Validating: ReportContent Module (3 entries)
Validating: Activity Module (21423 entries)
Validating: Comment Module (563 entries)
Validating: Content Objects (41071 entries)
Validating: File Module (208 entries)
Validating: Like (551 entries)
Validating: Notification Module (157291 entries)
Validating: Post  Module - Posts (19437 entries)
Validating: Space Module - Spaces (48 entries)
Validating: Space Module - Memberships (640 entries)
Validating: User Module - ContentContainer (79 entries)
Validating: User Module - Users (79 entries)
Validating: User Module - Password (79 entries)
Validating: User Module - Profile (79 entries)
Validating: User Module - Mentioning (74 entries)
Validating: User Module - Follow (6487 entries)
Validating: User Module - Content container (128 entries)

*** All integrity checks done

**Comment by tomofu74** [comment]
I left it for about 12 hours and healed before I knew it....

**Comment by luke-** [comment]
Usually this method should handle duplicate exclusive jobs:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/queue/helpers/QueueHelper.php#L27

**Comment by vpadhariya** [comment]
@luke- I have latest Humhub installed 1.8.1

I have also ran the integrity check command it run fine

I am still getting this issue, can you please release patch in next update?

```PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'humhub\modules\activity\jobs\SendMailSummary1' for key 'PRIMARY' in /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/Command.php:1299 Stack trace: #0 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/Command.php(1299): PDOStatement->execute() #1 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('INSERT INTO `qu...') #2 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute() #3 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('queue_exclusive', Array) #4 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL) #5 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL) #6 /home/customer/www/intranetteam.yuneco.be/public_html/protected/humhub/modules/queue/helpers/QueueHelper.php(63): yii\db\BaseActiveRecord->save() #7 /home/customer/www/intranetteam.yuneco.be/public_html/protected/humhub/modules/queue/Events.php(76): humhub\modules\queue\helpers\QueueHelper::markAsQueued('3857', Object(humhub\modules\activity\jobs\SendMailSummary)) #8 [internal function]: humhub\modules\queue\Events::onQueueAfterPush(Object(yii\queue\PushEvent)) #9 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\queue\PushEvent)) #10 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('yii\\queue\\Queue', 'afterPush', Object(yii\queue\PushEvent)) #11 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2-queue/src/Queue.php(197): yii\base\Component->trigger('afterPush', Object(yii\queue\PushEvent)) #12 /home/customer/www/intranetteam.yuneco.be/public_html/protected/humhub/modules/activity/Events.php(41): yii\queue\Queue->push(Object(humhub\modules\activity\jobs\SendMailSummary)) #13 [internal function]: humhub\modules\activity\Events::onCronHourlyRun(Object(yii\base\Event)) #14 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event)) #15 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('humhub\\commands...', 'hourly', Object(yii\base\Event)) #16 /home/customer/www/intranetteam.yuneco.be/public_html/protected/humhub/commands/CronController.php(102): yii\base\Component->trigger('hourly') #17 /home/customer/www/intranetteam.yuneco.be/public_html/protected/humhub/commands/CronController.php(70): humhub\commands\CronController->runHourly(true) #18 [internal function]: humhub\commands\CronController->actionHourly() #19 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #20 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #21 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('hourly', Array) #22 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('hourly', Array) #23 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('cron/hourly', Array) #24 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('cron/hourly', Array) #25 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #26 /home/customer/www/intranetteam.yuneco.be/public_html/protected/yii(29): yii\base\Application->run() #27 {main} Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'humhub\modules\activity\jobs\SendMailSummary1' for key 'PRIMARY' The SQL being executed was: INSERT INTO `queue_exclusive` (`id`, `job_message_id`) VALUES ('humhub\\modules\\activity\\jobs\\SendMailSummary1', '3857') in /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/Schema.php:678 Stack trace: #0 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `qu...') #1 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('INSERT INTO `qu...') #2 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute() #3 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('queue_exclusive', Array) #4 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL) #5 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL) #6 /home/customer/www/intranetteam.yuneco.be/public_html/protected/humhub/modules/queue/helpers/QueueHelper.php(63): yii\db\BaseActiveRecord->save() #7 /home/customer/www/intranetteam.yuneco.be/public_html/protected/humhub/modules/queue/Events.php(76): humhub\modules\queue\helpers\QueueHelper::markAsQueued('3857', Object(humhub\modules\activity\jobs\SendMailSummary)) #8 [internal function]: humhub\modules\queue\Events::onQueueAfterPush(Object(yii\queue\PushEvent)) #9 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\queue\PushEvent)) #10 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('yii\\queue\\Queue', 'afterPush', Object(yii\queue\PushEvent)) #11 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2-queue/src/Queue.php(197): yii\base\Component->trigger('afterPush', Object(yii\queue\PushEvent)) #12 /home/customer/www/intranetteam.yuneco.be/public_html/protected/humhub/modules/activity/Events.php(41): yii\queue\Queue->push(Object(humhub\modules\activity\jobs\SendMailSummary)) #13 [internal function]: humhub\modules\activity\Events::onCronHourlyRun(Object(yii\base\Event)) #14 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event)) #15 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('humhub\\commands...', 'hourly', Object(yii\base\Event)) #16 /home/customer/www/intranetteam.yuneco.be/public_html/protected/humhub/commands/CronController.php(102): yii\base\Component->trigger('hourly') #17 /home/customer/www/intranetteam.yuneco.be/public_html/protected/humhub/commands/CronController.php(70): humhub\commands\CronController->runHourly(true) #18 [internal function]: humhub\commands\CronController->actionHourly() #19 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #20 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #21 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('hourly', Array) #22 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('hourly', Array) #23 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('cron/hourly', Array) #24 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('cron/hourly', Array) #25 /home/customer/www/intranetteam.yuneco.be/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #26 /home/customer/www/intranetteam.yuneco.be/public_html/protected/yii(29): yii\base\Application->run() #27 {main} Additional Information: Array ( [0] => 23000 [1] => 1062 [2] => Duplicate entry 'humhub\modules\activity\jobs\SendMailSummary1' for key 'PRIMARY' )
Duplicate of #```

**Comment by luke-** [comment]
@vpadhariya Are you using any special queuing driver? Can you please send a screenshot of the page Information -> Preqreusites and Information -> Background Jobs.

**Comment by vpadhariya** [comment]
@luke- 

1. it is MySQL queue driver (default)
2. Background jobs are set as per the Humhub documentation : https://docs.humhub.org/docs/admin/installation#cronjobs
3. Site is hosted on siteground.com
4. Attached is the full screenshot of the error.
![screenshot-intranetteam yuneco be-2021 03 16-12_26_53](https://user-images.githubusercontent.com/570747/111268218-02a97680-8653-11eb-8a49-3981fa364acf.png)
5. Another screenshot of the cron job setup
![screenshot-tools siteground com-2021 03 16-12_28_04](https://user-images.githubusercontent.com/570747/111268327-2371cc00-8653-11eb-91ef-96cff7636987.png)

**Comment by luke-** [comment]
@vpadhariya Can you please remove the cronjobs cron/hourly & cron/daily and try it again?

**Comment by vpadhariya** [comment]
@luke- tried that, waiting for results, will let you know what happens.
