### ISSUE TITLE
string cannot be translated: views_activities_EntryResponse

### ISSUE THREAD

**Issue by xdCL** [humhub/humhub#4320]
### What steps will reproduce the problem?

This php file cannot be translated :(

When i edit this file and send it back throws a "ParseError: syntax error"

I can just leave the file blank, like for example the en_UK translation, and it doesn't cause a problem, but i need to translate into spanish!

```
return array (

  '%displayName% attends to %contentTitle%.' => '',

  '%displayName% maybe attends to %contentTitle%.' => '',

  '%displayName% not attends to %contentTitle%.' => '',

);
```

### What is the expected result?

Fill inner '' with some words translated.

Yeah, i keep the utf-8 format.

### What do you get instead?

```
ParseError: syntax error,
unexpected 'return' (T_RETURN) in /MY-HH-INSTALLATION/modules/calendar/messages/es/views_activities_EntryResponse.php:1 Stack trace: #0 /MY-HH-INSTALLATION/humhub/components/i18n/PhpMessageSource.php(51): yii\i18n\PhpMessageSource->loadMessagesFromFile('/MY/HH-INSTALLATION...') #1 /MY-HH-INSTALLATION/humhub/components/i18n/ModuleMessageSource.php(67): humhub\components\i18n\PhpMessageSource->loadMessages('views_activitie...', 'es') #2 /MY-HH-INSTALLATION/vendor/yiisoft/yii2/i18n/MessageSource.php(107): humhub\components\i18n\ModuleMessageSource->loadMessages('views_activitie...', 'es') #3 /MY-HH-INSTALLATION/vendor/yiisoft/yii2/i18n/MessageSource.php(87): yii\i18n\MessageSource->translateMessage('views_activitie...', '%displayName% i...', 'es') #4 /MY-HH-INSTALLATION/humhub/components/i18n/ModuleMessageSource.php(59): yii\i18n\MessageSource->translate('views_activitie...', '%displayName% i...', 'es') #5 /MY-HH-INSTALLATION/vendor/yiisoft/yii2/i18n/I18N.php(90): humhub\components\i18n\ModuleMessageSource->translate('views_activitie...', '%displayName% i...', 'es') #6 /MY-HH-INSTALLATION/humhub/components/i18n/I18N.php(148): yii\i18n\I18N->translate('CalendarModule....', '%displayName% i...', Array, 'es') #7 /MY-HH-INSTALLATION/vendor/yiisoft/yii2/BaseYii.php(538): humhub\components\i18n\I18N->translate('CalendarModule....', '%displayName% i...', Array, 'es') #8 /MY-HH-INSTALLATION/modules/calendar/activities/views/response_attend.php(14): yii\BaseYii::t('CalendarModule....', '%displayName% i...', Array) #9 /MY-HH-INSTALLATION/vendor/yiisoft/yii2/base/View.php(348): require('/MY/HH-INSTALLATION...') #10 /MY-HH-INSTALLATION/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/MY/HH-INSTALLATION...', Array) #11
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.2
| PHP version      | 7.0
| Operating system | centOS

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

I never did a issue in github before so, thanks you everyone on humhub community!

**Comment by luke-** [comment]
Maybe the space between the return and the round brackets? 

In general it is not recommended to modify translation files directly. 
https://docs.humhub.org/docs/about/contribution#be-part-of-the-translation-community

**Comment by buddh4** [comment]
Also have a look at https://docs.humhub.org/docs/admin/translations
