### ISSUE TITLE
Firefox 80 complains about Cookie ‘_identity’

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub#4352]
Firfox 80 gives console.log Cookie ‘_identity’ attribute ‘SameSite’  ‘None’ is insecure in get-new-message-count-json and poll. Will be rejected in the future.

**Comment by luke-** [comment]
Which HumHub/PHP Version? 

The cookie should be marked as LAX:
https://github.com/humhub/humhub/blob/master/protected/humhub/config/web.php#L39

**Comment by aronbos** [comment]
Humhub version 1.6.2 
PHP 7.2  -> that will be the problem. PHP 7.4 is required.
