### ISSUE TITLE
How to create a new Members Directory list with specific sort and fields ?

### ISSUE THREAD

**Issue by devFNO** [humhub/humhub#4367]
### Is your feature request related to a problem? Please describe.
There is different list (members list, spaces lists publication list ...)
I want to add a new one with specific fields from profile.
### Describe the solution you'd like
I would like a list of members order by a zipcode with the result of two checkbox info field from table profiles
How to do that ?

### Describe alternatives you've considered
no idea

**Comment by ArchBlood** [comment]
Soon the Directory core module will be reworked see #4157
