### ISSUE TITLE
Simplify badges/labels by removing text

### ISSUE THREAD

**Issue by Carl2213** [humhub/humhub#4373]
### Is your feature request related to a problem? Please describe.
A lot of modules, like Tasks, can inject a lot of labels into stream entries. This can quickly become crowded on small viewports, even causing a line break between the author and the "Created by" label.
![image](https://user-images.githubusercontent.com/69092633/93095101-13b00580-f679-11ea-8d2a-e7664ca04ad7.png)

### Describe the solution you'd like
Some badges, like Public, are universally recognizable with just the icon. They don't need any text. The text can be removed for a cleaner look. For additional information, tooltips can be used.

Suggestions:
![image](https://user-images.githubusercontent.com/69092633/93095355-5e318200-f679-11ea-8716-b838d5d797de.png)
![image](https://user-images.githubusercontent.com/69092633/93095486-87eaa900-f679-11ea-84aa-d52a8152a690.png)
![image](https://user-images.githubusercontent.com/69092633/93095554-9e910000-f679-11ea-98df-69153eec0b10.png)

The same can also be done for other badges, but I started with Public as an example because it's the easiest to remove the text from without causing confusion.
![image](https://user-images.githubusercontent.com/69092633/93095794-f16ab780-f679-11ea-846a-62fdf363b65b.png)

### Describe alternatives you've considered
I've already accomplished this for Task posts by modifying view files, but doing it manually requires figuring out how each module injects the badge and also figuring out how regular (non-module) stream entries inject the badge, which I've been unsuccessful with. It's often easier to modify the icon than the text, which can be set by the controller. 
![image](https://user-images.githubusercontent.com/69092633/93097285-c3867280-f67b-11ea-9c74-25b101e59221.png)

**Comment by luke-** [comment]
Thanks for the issue, but we are currently reworking the stream entries and will greatly reduce and in some cases completely remove badges & co. 

I think this week there will be a PR for this.

**Comment by Carl2213** [comment]
That's not the discourse-style appearance, right? I'm not a fan of Discourse's UI.
