### ISSUE TITLE
activate PrettyUrl 404 not found

### ISSUE THREAD

**Issue by byndstd** [humhub/humhub#4377]
I activate pretty URL and I get 
```
404 not found 
The requested URL was not found on this server.
```
on url  : **http://127.0.0.1/web/dashboard**
without PrettyURL my web work 
**http://127.0.0.1/web/index.php?r=dashboard%2Fdashboard**

### What steps will reproduce the problem?
File : protected/config/common.php
```
return [
    'components' => [
        'urlManager' => [
            'class' => 'yii\web\UrlManager',
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ]
];
```

```
cd /var/www/html/web
cp .htaccess.dist .htaccess
```

### What is the expected result?
existing page 

### What do you get instead?
```
404 not found 
The requested URL was not found on this server.
```
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.0-dev
| PHP version      |  7.4
| Operating system | linux Debian

**Comment by ArchBlood** [comment]
Your common.php file should look like this

```php
<?php

return [

    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ]
];
```
In addition you should also have changed the `.htaccess.dist` file to `.htaccess`

If you're using a sub-directory then uncomment out this section and replace `/humhub` with `/web`

https://github.com/humhub/humhub/blob/c1765aaff6d257dc999279a610f07c772465e689/.htaccess.dist#L7-L8

**Comment by byndstd** [comment]
I did uncomment 
#RewriteBase /humhub  
to 
RewriteBase /web

and reload the apache but still getting the same error
my file protected/config/common.php
```
return [

    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ]
];
```

**Comment by byndstd** [comment]
> Your common.php file should look like this
> 
> ```
> <?php
> 
> return [
> 
>     'components' => [
>         'urlManager' => [
>             'showScriptName' => false,
>             'enablePrettyUrl' => true,
>         ],
>     ]
> ];
> ```
> 
> In addition you should also have changed the `.htaccess.dist` file to `.htaccess`
> 
> If you're using a sub-directory then uncomment out this section and replace `/humhub` with `/web`
> 
> https://github.com/humhub/humhub/blob/c1765aaff6d257dc999279a610f07c772465e689/.htaccess.dist#L7-L8
> 
> In some cases you'll also have to restart Apache as well

I did uncomment
#RewriteBase /humhub
to
RewriteBase /web

and reload the apache but still getting the same error
my file protected/config/common.php

```
return [

    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ]
];
```
