### ISSUE TITLE
Web installed modules breaking yii console

### ISSUE THREAD

**Issue by hunwalk** [humhub/humhub#4383]
### What steps will reproduce the problem?

1. Install the latest humhub (by unzipping and stuff, not with composer)
2. Install for e.g. the calendar module 
3  Now try to run `php yii` inside the protected folder

### What is the expected result?

	Normal Yii console output.

### What do you get instead?
<img width="1245" alt="kép" src="https://user-images.githubusercontent.com/32835435/93301686-1df90d80-f7f9-11ea-9d46-9bf596b0c83a.png">

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.63?
| PHP version      | 7.4
| Operating system | Linux (shared hosting environment with shell, but if i have to guess it's debian)

**Comment by ArchBlood** [comment]
Can't reproduce on my end of things, maybe something to do with sub-directories that cause this issue? :thinking:

**Comment by hunwalk** [comment]
Huh, okay, I will try to reinstall it at the end of the day

**Comment by hunwalk** [comment]
For some reason, it's searching for the modules in /protected/humhub/modules but the user installed modules are at /protected/modules

![kép](https://user-images.githubusercontent.com/32835435/93312143-248e8180-f807-11ea-8878-2ed1b844adad.png)

Same thing happened with 1.62

**Comment by hunwalk** [comment]
Okay, fixed it for myself.

If you can't reproduce this issue, at least i leave this here:

1. I cloned the repo, checked out at the latest tag to a new branch.
2. `composer install --ignore-platform-reqs`
3. Edit composer.json

Add 
```json
"autoload": {
  "psr-4": { "humhub\\modules\\": ["protected/modules"] }
},
```

![kép](https://user-images.githubusercontent.com/32835435/93314074-98ca2480-f809-11ea-8e19-eea6f007f086.png)

4. `composer dump-autoload`
