### ISSUE TITLE
Checkbox field type - Required option not working 

### ISSUE THREAD

**Issue by verement** [humhub/humhub#4389]
### Is your feature request related to a problem? Please describe.

If I create a new profile field with fieldtype _checkbox_, marking it _required_ does not seem to have any effect.

### Describe the solution you'd like

Since there are only two states for a checkbox, I would expect marking one _required_ to mean it is required to be checked. This would be an ideal way to require agreement with explicit terms during registration.

### Describe alternatives you've considered

This would be in addition to other legal module options.

**Comment by yurabakhtin** [comment]
@luke- Ok, I have tried to implement in the PR https://github.com/humhub/humhub/pull/4805 what is required in the described problem above.
But I am not sure where it may need to deny to post a form without checked/enabled checkbox, probably it will be useful only for some checkbox like `[√] I agree terms and policies on this site.` on a registration form.
If yes, then ok, but please note such modifications will not allow to save a form with unchecked fields if they were created before this modifications, so some users will be confused, so admins will should make such checkboxes to not required. If you think this is ok then the PR can be merged.

<img width="853" alt="require_checkbox" src="https://user-images.githubusercontent.com/6995524/106253744-f2ffdb00-6228-11eb-9a32-84dd1057c52c.png">

**Comment by luke-** [comment]
@yurabakhtin Thank you for pointing this out. I think if you mark a checkbox as Required, this behaviour should be expected.
