### ISSUE TITLE
Pinned Post Option

### ISSUE THREAD

**Issue by StephaneBouvet** [humhub/humhub#4393]
What about pinned permission for a group ? It would be (I think) an interesting option !

In my case I would like to let user pin a post only if they are in some group.

**Comment by luke-** [comment]
Do you really mean Group based permissions? e.g. an user in Group A can Pin Posts in all Spaces?

For content the permissions are usually assigned to Space roles.

**Comment by LaRepDuClic** [comment]
OK. Thanks for the answer !
