### ISSUE TITLE
Logo image doesn't refresh after updated as well . Browser cache ?

### ISSUE THREAD

**Issue by devFNO** [humhub/humhub#4394]
### What steps will reproduce the problem?
go to admin https://domain.com/index.php?r=admin%2Fsetting%2Fdesign
upload an logo

### What is the expected result?
logo changed on website and in admin panel

### What do you get instead?
logo NOT changed event on admin panel 

url of the image is  https://domain.com/uploads/logo_image/logo.png?cacheId=0
I can see the right image when I go to
https://domain.com/uploads/logo_image/logo.png?cacheId=1

Maybe it is a webbrowser cache issue for all my users, and they dont know they hhave to update their webbrowser cache.
Could you increase the number Id of variable cacheId when we upload a new logo/image ?

Thanks for all

### Additional info
I erase the server cache with https://domain.com/index.php?r=admin%2Fsetting%2Fcaching
but still not display the right image

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4
| PHP version      |  7.2
| Operating system | linux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Can you please try this with a newer HumHub version?
We refactored this logo handling part a lot in later releases.

**Comment by luke-** [comment]
This is one related commit: https://github.com/humhub/humhub/commit/945fa2b62d6460af3cea9d0a40c46ea084f851d2#diff-8509c3b6588f585d6473d7d99619c8b2
