### ISSUE TITLE
Submitting only picture in comment results in debug error.

### ISSUE THREAD

**Issue by Beheadedstraw** [humhub/humhub#4396]
# What steps will reproduce the problem?
Without typing anything in comment, upload a picture and hit send. Put anything in comment with picture, operates normal. I believe this uses the same validation as normal posting where the main message can't be left blank (which should probably also change when someone only wants to post a picture with no text).

### What is the expected result?
Picture posted in comment with no text needed.

### What do you get instead?
Debug Error popup on debug instance.

### Additional info
`<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Trying to get property of non-object&#039; \n\nin /var/www/socialrealms/html/protected/humhub/modules/comment/widgets/views/comment.php:68\n\nStack trace:\n#0 /var/www/socialrealms/html/protected/humhub/modules/comment/widgets/views/comment.php(68): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Trying to get p...&#039;, &#039;/var/www/social...&#039;, 68, Array)\n#1 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/base/Vie...",
`
| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.5 AND current dev branch.
| PHP version      |       7.4 
| Operating system |   Ubuntu 16 server

**Comment by ArchBlood** [comment]
If you upload an image or file from the Richtext editor you should be able to post without adding text

**Comment by Beheadedstraw** [comment]
> If you upload an image or file from the Richtext editor you should be able to post without adding text

That's... very abstract, it would be far more user friendly to have the upload files button (which every new user is going to use) do this instead since it basically already does it anyways albeit with the pitfalls mentioned above =\.

**Comment by ArchBlood** [comment]
I completely agree with you on that, it's just a workaround to use the Richtext editor for now

**Comment by MasterHans** [comment]
Hi guys,
Please help me.
I can't reproduce the issue. I tried and everything works...
I tried to insert the picture from the buffer by Shift+Insert keys and submit it.
I tried to insert the picture from the editor's panel and submit as well. It works pictures successfully submitted.
There is no text of course beside the picture.

Try it both on my local environment and humhub.com.

Please follow this link record video for you:
https://youtu.be/HUKpZzVYF78

Thank you
See you 
Alex

**Comment by buddh4** [comment]
@MasterHans I think they are talking about attaching an image (upload button beside send) instead of embedding an image in the richtext.

**Comment by MasterHans** [comment]
Thank you **buddh4**! I found it.  Observing the issue.

**Comment by MasterHans** [comment]
Hi everyone,
I hope you doing well

The gist of issue hiding in validation rules for model Comment. The rules were strict and demand that the "message" field "required "  to be not empty.

I have changed the rules added the condition 'where'. 
If the comment did not contain any attached files, it must be not empty.

            [['message'], 'required', 'when' => function ($comment) {
                return !$comment->fileManager->find()->exists();
            }],

Thank you,
Alex

**Comment by Beheadedstraw** [comment]
> Hi everyone,
> I hope you doing well
> 
> The gist of issue hiding in validation rules for model Comment. The rules were strict and demand that the "message" field "required " to be not empty.
> 
> I have changed the rules added the condition 'where'.
> If the comment did not contain any attached files, it must be not empty.
> 
> ```
>         [['message'], 'required', 'when' => function ($comment) {
>             return !$comment->fileManager->find()->exists();
>         }],
> ```
> 
> Thank you,
> Alex

Seems we're still seeing the original error above, with the current code patched we still receive:

```
yii\base\ErrorException: Trying to get property of non-object in /var/www/socialrealms/html/protected/humhub/modules/comment/widgets/views/comment.php:68 Stack trace: #0 /var/www/socialrealms/html/protected/humhub/modules/comment/widgets/views/comment.php(68): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/social...', 68, Array) #1 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/social...') #2 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/social...', Array) #3 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/social...', Array, Object(humhub\modules\comment\widgets\Comment)) #4 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('comment', Array, Object(humhub\modules\comment\widgets\Comment)) #5 /var/www/socialrealms/html/protected/humhub/modules/comment/widgets/Comment.php(58): yii\base\Widget->render('comment', Array) #6 /var/www/socialrealms/html/protected/humhub/components/Widget.php(63): humhub\modules\comment\widgets\Comment->run() #7 /var/www/socialrealms/html/protected/humhub/modules/comment/controllers/CommentController.php(148): humhub\components\Widget::widget(Array) #8 [internal function]: humhub\modules\comment\controllers\CommentController->humhub\modules\comment\controllers\{closure}(Object(yii\db\Connection)) #9 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/db/Connection.php(796): call_user_func(Object(Closure), Object(yii\db\Connection)) #10 /var/www/socialrealms/html/protected/humhub/modules/comment/controllers/CommentController.php(149): yii\db\Connection->transaction(Object(Closure)) #11 [internal function]: humhub\modules\comment\controllers\CommentController->actionPost() #12 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #13 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #14 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('post', Array) #15 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('comment/comment...', Array) #16 /var/www/socialrealms/html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #17 /var/www/socialrealms/html/index.php(25): yii\base\Application->run() #18 {main}
```

This is doing the same thing attaching an image through the file upload in a comment without putting text in the actual comment. We're running on the latest dev build but I see this same problem in stable release as well.

**Comment by ArchBlood** [comment]
Could `$user->contentcontainer_id` be replaced with `$user->contentContainer->id` in this case or does this go against the container?

**Comment by MasterHans** [comment]
Hi guys,
Thank you for your replay

> Seems we're still seeing the original error above, with the current code patched we still receive:
How did you patch this correction code? Did you manually put it inside <your domain>/humhub/protected/humhub/modules/comment/models/Comment.php 
or maybe you simply took code from the "master" branch of humhub repository?

I am sorry, but at the moment this correction **did not deliver** to the **master** branch and to the production Humhub.com as well. Please wait for us put it there. It will not take long.


> Could `$user->contentcontainer_id` be replaced with `$user->contentContainer->id` in this case or does this go against the container id rules @buddh4?
PHP language is strict to a using case of variables, properties, and methods.  **$user->contentcontainer_id** - is correct expression.

Why this issue appeared in the view /var/www/socialrealms/html/protected/humhub/modules/comment/widgets/views/comment.php at 68 string.
Please look into this code:
<?= UserImage::widget(['user' => $user, 'width' => 40, 'htmlOptions' => ['class' => 'pull-left', 'data-contentcontainer-id' => $user->contentcontainer_id]]); ?>

We are extracting the property from the **User** model **$user->contentcontainer_id**. But **$user** (the **User** model object instance) is empty. You can't take property from the void (from an empty object).

Why **$user** empty? That's happened because the system did not create an instance of **Comment** model in the CommentController actionPost method string 140:

            $comment = new Comment(['message' => $message]);
            $comment->setPolyMorphicRelation($this->target);
            $comment->save();
            $comment->fileManager->attach($files);

And setPolyMorphicRelation did not work and the related model User did not fill up. It is empty.

Why Comment model instance did not create? Because of rule of validation on "message" coloumn.

See you
Alex
