### ISSUE TITLE
Deep links/Permalinks to comments

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4399]
### Is your feature request related to a problem? Please describe.

For content with many comments, the notifications / activities regarding comments always lead to the content instead of the relevant comment.

### Describe the solution you'd like

- Create a deep link to the comment
- Mark comment with border.

**Comment by buddh4** [comment]
Perhaps slightly related https://github.com/humhub/humhub/issues/3442 or how do you want to display the comment in such cases?

**Comment by luke-** [comment]
e.g. we could use a border color

**Comment by buddh4** [comment]
No, I rather mean when currently opening a permalink only a few comments are visible. Or do you want to add a dedicated view for just the comment in question similar to redit or twitter?

**Comment by ArchBlood** [comment]
Could do like Facebook and use permalinks to display all content of a post while only showing the bare minimum of comments on the dashboard, I see this being one way of doing this, the other would be doing like how GitHub does things through their notifications on new content added to make it more visible, just a thought :thinking:

**Comment by luke-** [comment]
@buddh4 No, an own view is probably too much. It would be sufficient if the requested comment would be loaded and marked somehow.

**Comment by Carl2213** [comment]
I don't think Facebook shows all content when a notification is clicked. If I'm not mistaken, they show comments in increments of 10. And they load the 10 comments that include the comment from your notification, but with a "load more comments" button above and below.

This would be an ideal implementation. Loading all comments could be excessive and confusing, and would still require scrolling to the comment in question and highlighting it.

**Comment by buddh4** [comment]
I would not load all comments, but I would load many more comments in the detail view of a content (see https://github.com/humhub/humhub/issues/3442) but even when loading many comments we need a load more behavior on top as well as bottom when highlighting a comment outside of the default comment selection.

**Comment by Carl2213** [comment]
Or maybe all comments can be hidden except for the highlighted comment? That would provide great focus on the most important content. And if the user wants to see more, they can always load more (above or below).

For replies (subcomments), The single comment might be all that is interesting to the user, either to reply to it or because the notification refers to a reply to that comment.

**Comment by Carl2213** [comment]
Yeah, like Facebook's viral public posts with thousands of comments. The default behavior of only showing the last 10 comments (or 10 "most popular" comments) makes sense in general. But if someone mentioned you in that post, you usually don't care about any other comments. You only want to see your friend's comment and maybe reply to it.

**Comment by acheype** [comment]
I still have some users lost after clicking some notifications. It would be awesome to fix this bug.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5168:

<img width="1363" alt="mark_comment" src="https://user-images.githubusercontent.com/6995524/125790349-37dd7167-49e5-437f-b530-c2addbcc8fd1.png">

**Comment by orangiene** [comment]
Hi all,

@yurabakhtin I like your idea with the highlighted background, also the colour.
I made two proposals for the bg colour - what's your favourite
![HumHub-Enterprise-deeplinks-01](https://user-images.githubusercontent.com/62644500/134912088-fb0a0d4a-3e4b-483a-a333-6a43d645655e.jpg)
![HumHub-Enterprise-deeplinks-02](https://user-images.githubusercontent.com/62644500/134912104-f3f03ea8-8a2b-4382-b746-f13bbd419f48.jpg)
?

**Comment by orangiene** [comment]
@yurabakhtin what's your favorite? ;-) Semir prefers the blue one. 
blue is CI compliant, yellow stands out - so both have their benefits.

**Comment by yurabakhtin** [comment]
@orangiene In my first version I used the like yellow color specially as negative color of the main theme color because I thought we should mark/highlight the opened comment, i.e. I think such thing should be contrasted, so user will find the opened comment by eyes more faster right after page loading. It is why for such thing I prefer to use a contrast color like yellow.

But if no purpose to make the opened comment more notable/marked/highlighted then we can use the blue color, however I am not UI/UX expert and I may be wrong here.

**Comment by orangiene** [comment]
@yurabakhtin : just for our understanding: which color variable did you use? 

There is no wrong or right in this case. Your explanation makes sense, so let's continue with your yellow version, we like it :)

**Comment by luke-** [comment]
Should I merge it? Or is something todo e.g. border, color, etc.? :-)

**Comment by yurabakhtin** [comment]
@orangiene 

> just for our understanding: which color variable did you use?

I didn't use color/less variable there, I just created new style class `.comment-current` with `background: #fff3cd;` - https://github.com/humhub/humhub/pull/5168/files#diff-4f3e259f1e936c71ed899333b38b8aea754c45c05ae878e71f7fcc8ca2dc042dR35. If you know some variable please tell me and I will change that.

**Comment by luke-** [comment]
Hmm, this color should not be hardcoded:

We should take one of the definable color values for this:
![image](https://user-images.githubusercontent.com/4736168/135049597-97524b9c-194c-442b-879f-8ac571b03717.png)
Maybe we could lighten or darken...

@yurabakhtin @orangiene Please use one of these... :-)

**Comment by orangiene** [comment]
what do you think about this one?
I took the success colour with 35% transparency:
![HumHub-Community-deeplinks-02](https://user-images.githubusercontent.com/62644500/135053025-01027f67-49af-4957-b002-794aa0d1f615.jpg)

**Comment by orangiene** [comment]
Hi @yurabakhtin ,

could you please change the colour value for "warning" in #FFC107. 
And then please use the colour "warning" in 25% for deeplionks.

Thank you :)
![HumHub-Community-deeplinks-03](https://user-images.githubusercontent.com/62644500/135058591-3f7c86cf-be50-452e-9f54-b92b6a4adedb.jpg)

**Comment by yurabakhtin** [comment]
@orangiene Hi Angela, it seems you want to use color `#FFC107` as base and apply 25% opacity, so it looks like this:

<img width="929" alt="custom_color" src="https://user-images.githubusercontent.com/6995524/135073441-aaa21a25-a7da-4b10-9dc5-8e72ffc1c494.png">

But as I understand we should use the "less" variable `@warning` with default value `#f8b763` and it looks a bit difference than your screenshot:

<img width="936" alt="warning-color" src="https://user-images.githubusercontent.com/6995524/135073719-93a42739-65e0-4efe-9350-859f975a7007.png">

I committed the version with 25% of the `@warning` - https://github.com/humhub/humhub/pull/5168/commits/aae8e89ee753c39087772a46aab83c7ff1b7b459.

**Comment by luke-** [comment]
@yurabakhtin With HumHub 1.10 we change the default value of the less variable @warning to #FFC107.

**Comment by luke-** [comment]
@yurabakhtin Can you please also add a "Permalink" Option here?
![image](https://user-images.githubusercontent.com/4736168/135088701-3da2351b-51af-4e8c-98a0-05f4d9db7280.png)

An url e.g. `/comment/perma/24242` would be nice.

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please also add a "Permalink" Option here?

Commit https://github.com/humhub/humhub/pull/5168/commits/fec4ce7beb1f04b67002ab501037f8e3c5ff260f.

**Comment by luke-** [comment]
@yurabakhtin - The permalink is currently only shown when you can edit the comment. Can you please display it for everyone?

- Also, it would be good if a dialog like this would pop up then:
![image](https://user-images.githubusercontent.com/4736168/135225526-4b5edf66-19d2-4493-9f6c-194eddf9c0e1.png)

- It might be good to implement the dropdown menu (permalink, edit, delete) as a real `Menu widget`. Then, for example, a `ReportContent` module could also inject there.

**Comment by yurabakhtin** [comment]
@luke- 

> - The permalink is currently only shown when you can edit the comment. Can you please display it for everyone?
> - Also, it would be good if a dialog like this would pop up then: ...

Commit https://github.com/humhub/humhub/pull/5168/commits/6244fabc1774f766aa3752a5408fc28709260969:

<img width="610" alt="comment_permalink" src="https://user-images.githubusercontent.com/6995524/135283032-396fa302-d892-4cc7-8019-458b99873f79.png">

**Comment by yurabakhtin** [comment]
@luke- Ok, I remove a container name from comment permalinks:
https://github.com/humhub/humhub/pull/5168/commits/60ce9c23144712d44868cefe593bb8cf75de96e7
<img width="605" alt="short_comment_url" src="https://user-images.githubusercontent.com/6995524/135300013-756c3bd6-7d2b-4100-8e01-7ec53df46399.png">

---

> - It might be good to implement the dropdown menu (permalink, edit, delete) as a real Menu widget. Then, for example, a ReportContent module could also inject there.

It is in process yet...

**Comment by yurabakhtin** [comment]
@luke- 

> - It might be good to implement the dropdown menu (permalink, edit, delete) as a real Menu widget. Then, for example, a ReportContent module could also inject there.

Commit https://github.com/humhub/humhub/pull/5168/commits/23b7ec037fa17648f6dfacd97cbac249fdb54a37.

**Comment by luke-** [comment]
@yurabakhtin I have changed it a bit, that `MenuLinks` are used. that saves some code.
See here: https://github.com/humhub/humhub/pull/5168/commits/efac7217e0fbe5c6021ded5cd703454a71fc75b3

Somehow the PermaLink popup can only be opened once, then it doesn't work anymore. can you please investigate this some more?

**Comment by yurabakhtin** [comment]
@luke- 

> Somehow the PermaLink popup can only be opened once, then it doesn't work anymore. can you please investigate this some more?

Fixed in commit https://github.com/humhub/humhub/pull/5168/commits/615dd012c6580c0c563733270c9f9da47634ed56. I detected the permalink js code doesn't open the window twice if the link has some url in the `href` attribute instead of `#`.

**Comment by luke-** [comment]
@yurabakhtin Awesome thank you!
