### ISSUE TITLE
RecoverPassword.php view file show a white link on a white background

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4400]
### What steps will reproduce the problem?

In the login page, try to get a new password.
You get this mail:

![image](https://user-images.githubusercontent.com/23310825/94139423-e37f1880-fe69-11ea-92a1-55d1f4ae475c.png)

The link color to reset password is white on a white background, so not visible

### What is the expected result?

This link should not be white

### Additional info

The problem is in here : https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/views/mails/RecoverPassword.php#L119
The default color is #FFF 
On a background color #FFF : https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/views/mails/RecoverPassword.php#L64

Theme is enterprise

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.2
| PHP version      | 7.3

**Comment by ArchBlood** [comment]
This is only for the `text-color-contrast`, what email client are you using? Could be that your email client is stripping HTML elements that `Yii::$app->view->theme->variable` throws out and just shows `#fff`?

**Comment by funkycram** [comment]
`text-color-contrast` less variable is server side. Browser sees the `color` attribute generated by php with `Yii::$app->view->theme->variable('text-color-contrast', '#fff')`.
This screenshot is on Gmail client.

**Comment by ArchBlood** [comment]
Not able to reproduce on my end of things while using v1.6.3 & Gmail, so what I'm thinking is instead of getting the normal email you're getting a plaintext email instead, which is stripped of HTML & PHP tags :thinking:

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/views/mails/plaintext/RecoverPassword.php

**Comment by funkycram** [comment]
No, it is the HTML layout : https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/views/mails/RecoverPassword.php
I have analyze it with the browser's developing tools

**Comment by funkycram** [comment]
Precision : theme is enterprise

**Comment by ArchBlood** [comment]
Just tested this on the enterprise theme as well, all elements are intact for me and no white backgrounds for the button, just in case I also went into the code for both `/mails/RecoverPassword.php` & `/mails/plaintext/RecoverPassword.php` and searched for `$linkPasswordReset` and made sure that `Html::decode($linkPasswordReset)` was used which originally isn't being used, shouldn't really need it for `/mails/RecoverPassword.php` that I can think of :sweat_smile:

**Comment by funkycram** [comment]
Thanks a lot @ArchBlood for your diagnostic.
Ended, the problem is on the background of the button : https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/views/mails/RecoverPassword.php#L116

In the theme, the `variables.less` had this:
```
@primary: @myColor;
```

And Humhub can not get the value of `@myColor`.

So the fix was to put directly the HTML color code:
```
@primary: #333;
```

So I close this issue and create an other one for this problem.

**Comment by funkycram** [comment]
See https://github.com/humhub/humhub/issues/4401
