### ISSUE TITLE
Variables in the theme variables.less file cannot have an other variable as value

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4401]
### What steps will reproduce the problem?

In your custom theme, in the `variables.less` write this:
```
@myColor: #CCC;
@primary: @myColor;
```

### What is the expected result?

```
$this->theme->variable('primary');
```
Should display `#CCC`

### What do you get instead?

Not `#CCC`

### Additional info

Problem diagnosed in https://github.com/humhub/humhub/issues/4400

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6

**Comment by luke-** [comment]
I think we can implement such a simple lookup but it must be clear that we cannot handle more complicated cases like calculations.

**Comment by funkycram** [comment]
Yes of curse, but for colors it would be already a good start as usually we have a color panel (graphical charter) set in variables and we use theses variables to set the others colors.

I suggest also to write theses restrictions in https://github.com/humhub/humhub/blob/master/themes/HumHub/less/variables.less as we think we can write any Less code.

**Comment by buddh4** [comment]
In the future we should work with css variables where possible.

**Comment by funkycram** [comment]
Great, thanks @luke-
