### ISSUE TITLE
Rework TimeAgo widget

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4407]
- Instead of using `Yii::$app->params['formatter']['timeAgoStatic']` and ` Yii::$app->params['formatter']['timeAgoHideTimeAfter']` use widget options
- Render tooltip by default with full date
- Disable `timeAgoHideTimeAfter` by default
- Use ui addition instead of inline script block
- Use html 5 time element

**Comment by luke-** [comment]
Related: https://github.com/humhub/humhub/issues/4137 

?
