### ISSUE TITLE
Audio player on mobile overflows stream content

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4408]
On mobile the jp audio player overflows the content area:

![grafik](https://user-images.githubusercontent.com/9800854/94467035-ac3e9d80-01c2-11eb-9d1e-f0fe25f7ad17.png)

Steps to reproduce:

- Attach mp3 file to stream entry
- Check the new post on a mobile device (or by devtools)

Perhaps we should check if there are better or newer alternatives available for the current audio player in use.

**Comment by Carl2213** [comment]
I've fixed this using CSS a long time ago, without losing any functionality.

Viewport >480px:

![image](https://user-images.githubusercontent.com/69092633/94478711-054e0780-01aa-11eb-882f-9338bab10ef2.png)

<480px

![image](https://user-images.githubusercontent.com/69092633/94478752-1434ba00-01aa-11eb-91cd-a2f28da397f0.png)

`@media (max-width:480px) {
.jp-current-time {
margin-left: 0!important;
}
.jp-audio {
width: 280px !important;
margin-left:0!important;
}
.jp-audio .jp-controls {
padding: 2px 12px 0!important;
}
.jp-audio .jp-progress {
left: 3px!important;
top: 45px!important;
width: 200px!important;
}
.jp-audio .jp-volume-controls {
position: absolute!important;
top: 15px!important;
left: 170px!important;
}
.jp-audio .jp-time-holder {
left:3px!important;
top:60px!important;
width:200px!important;
}
.jp-audio .jp-toggles {
left: 210px!important;
top: 45px!important;
width:199px!important;
}
.jp-playlist ul {
padding: 0 0 0 0!important;
}
}
div.jp-type-playlist div.jp-playlist a.jp-playlist-current, div.jp-type-playlist div.jp-playlist a:hover {
color: #33a82f!important;
}
.jp-play-bar {
background: url(../img/jplayer.green.mini.jpg) 0 -218px repeat-x!important;
}
.jp-volume-bar {
background: url(../img/jplayer.green.mini.jpg) 0 -250px repeat-x!important;
}
.jp-volume-bar-value {
background: url(../img/jplayer.green.mini.jpg) 0 -220px repeat-x!important;
}
.jp-seek-bar {
background: url(../img/jplayer.green.mini.jpg) 0 -202px repeat-x!important;
}
.jp-previous {
background: url(../img/jplayer.green.mini.jpg) 0 -112px no-repeat!important;
}
.jp-play {
background: url(../img/jplayer.green.mini.jpg) no-repeat!important;
}
.jp-state-playing .jp-play {
background: url(../img/jplayer.green.mini.jpg) 0 -42px no-repeat!important;
}
.jp-next {
background: url(../img/jplayer.green.mini.jpg) 0 -141px no-repeat!important;
}
.jp-state-muted .jp-mute {
background: url(../img/jplayer.green.mini.jpg) -60px -170px no-repeat!important;
}
.jp-mute:focus {
background: url(../img/jplayer.green.mini.jpg) -19px -170px no-repeat!important;
}
.jp-repeat:focus {
background: url(../img/jplayer.green.mini.jpg) -30px -290px no-repeat!important;
}
.jp-shuffle:focus {
background: url(../img/jplayer.green.mini.jpg) -30px -270px no-repeat!important;
}
.jp-state-shuffled .jp-shuffle:focus {
background: url(../img/jplayer.green.mini.jpg) -90px -270px no-repeat!important;
}
.jp-volume-max:focus {
background: url(../img/jplayer.green.mini.jpg) -19px -186px no-repeat!important;
}
.jp-details, .jp-playlist {
border-top: 1px solid #33a82f;
}
.jp-audio, .jp-audio-stream, .jp-video {
border: 1px solid #33a82f;
}`

**Comment by Carl2213** [comment]
There was a margin/width attribute as well. I'm not sure if that's included in the codeblock.

**Comment by buddh4** [comment]
Thanks I'll test the css in the new layouts.

**Comment by buddh4** [comment]
Will be part of https://github.com/humhub/humhub/pull/4397
