### ISSUE TITLE
Conflict between imagick and gmagick

### ISSUE THREAD

**Issue by LaRepDuClic** [humhub/humhub#4409]
Good morning.

In my environment I loaded GraphicsMagick and when I started my Humhub instance (V1.6.3), I got the following error :
`PHP Core Warning – yii\base\ErrorException
Cannot load module 'imagick' because conflicting module 'gmagick' is already loaded`

When I replace GraphicsMagick by ImageMagick, I got the following error :
`PHP Startup: Unable to load dynamic library 'gmagick.so' (tried: /usr/lib64/php-7.3/extensions/gmagick.so (/usr/lib64/php-7.3/extensions/gmagick.so: cannot open shared object file: No such file or directory), /usr/lib64/php-7.3/extensions/gmagick.so.so (/usr/lib64/php-7.3/extensions/gmagick.so.so: cannot open shared object file: No such file or directory))`

**Comment by luke-** [comment]
You need either ImageMagick or GMagick.
https://docs.humhub.org/docs/admin/requirements#extensions
