### ISSUE TITLE
Remove DbExpression

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4428]
### Is your feature request related to a problem? Please describe.

Replace `new \yii\db\Expression('NOW()');` calls with `date('Y-m-d G:i:s');` to not rely on database time (-zone) config.

Also affects modules.

**Comment by ArchBlood** [comment]
Just out of curiosity could `time()` also be added optionally or as a fallback?

**Comment by luke-** [comment]
@ArchBlood time() only returns the unix timestamp and we need a DB format here. Maybe some DBs supports just a timestamp here.

**Comment by yurabakhtin** [comment]
@luke- PR - https://github.com/humhub/humhub/pull/4443

> Also affects modules.

Does it mean we should do same updating in ALL modules like this https://github.com/humhub/humhub-modules-custom-pages/blob/master/migrations/m160907_175706_default_templates.php#L135 ?

**Comment by luke-** [comment]
@yurabakhtin yes, I don't know how widely this is used, but if there are found locations we should change this in our modules.

**Comment by yurabakhtin** [comment]
@luke- I detected that I did a fix only for `new \yii\db\Expression('NOW()');` but there are many `use yii\db\Expression;` + `new Expression('NOW()')` which must be replaced as well.

**Comment by luke-** [comment]
Great thanks!

**Comment by yurabakhtin** [comment]
@luke- I replaced this in repositories of all modules, see above.

**Comment by luke-** [comment]
Awesome, have you also looked here?
https://github.com/humhub-contrib

**Comment by yurabakhtin** [comment]
@luke- I find in 2 repos https://github.com/search?q=org%3Ahumhub-contrib+%22Expression%28%27NOW%28%29%27%29%22&type=code, please check them and let me know if they should be updated as well.

**Comment by luke-** [comment]
Yes please!

**Comment by ArchBlood** [comment]
Looking over it all in total there's a lot of places this is still used in general :thinking:
https://github.com/search?q=org%3Ahumhub+%22Expression%28%27NOW%28%29%27%29%22&type=code

**Comment by yurabakhtin** [comment]
@luke- 

> Yes please!

Ok, I did changes in repo https://github.com/humhub-contrib/fcm-push, but cannot push changes because no perms, please give me them, and I will do this.

- https://github.com/humhub-contrib/dropbox - here I don't see a reason to do any changes because I see message "**This repository has been archived by the owner. It is now read-only.**".

**Comment by yurabakhtin** [comment]
@ArchBlood I think the search results are related to `master` branches, but we did changes only in `develop` branches and in branches like `fix/4428`, please wait when they will be merged from PRs what you can find above.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub-contrib/fcm-push/pull/1/files, this is the last repo where we used `Expression('NOW()')`, after merging this PR you can close this issue.
