### ISSUE TITLE
Some *.less files resided in static/less has tab symbol 2 space size

### ISSUE THREAD

**Issue by MasterHans** [humhub/humhub#4432]
According to less coding convention:

Use only spaces for indentation:

Tab size: **4 spaces**
Indent size: 4 spaces
Continuation indent: 4 spaces

These *.less files have a tab **2 space size**:

- activities.less
- badge.less
- base.less
- button.less
- comment.less
- datepicker.less
- dropdown.less
- file.less
- icon.less
- installer.less
- list-group.less
- loader.less
- login.less
- mentioning.less
- mixins.less
- modal.less
- module.less
- pagination.less
- popover.less
- progress.less
- sidebar.less
- stream.less
- tags.less
- tooltip.less
- tour.less
- well.less

**Comment by luke-** [comment]
@buddh4 Can @MasterHans start with the change?

**Comment by buddh4** [comment]
Yes, dev branch should be clear.
