### ISSUE TITLE
Ampersand is displayed as `&amp;` in profile widget "Member of these spaces"

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#4434]
- HH 1.6.3
- On profile
- Widget "Member of these Spaces"
- Displayed when hovering over the icon

![asdf1](https://user-images.githubusercontent.com/38326726/95076663-7fced800-0712-11eb-8de2-6098f96fce86.PNG)

**Comment by yurabakhtin** [comment]
Fixed. PR - https://github.com/humhub/humhub/pull/4439.
I remove the quoting `Html::encode()` there completely for `$space->name` because it worked as double quoting.
I tested with space name `Search & Find "123` and saw in page source ` title="Search &amp; Find &quot;123"` as expected.
