### ISSUE TITLE
Stream could not be initialized! error when adding a new calendar event or wiki page in develop branch

### ISSUE THREAD

**Issue by fae7em** [humhub/humhub#4440]
### What steps will reproduce the problem?
In the `develop` branch, if we add a new event or wiki page or maybe other things, we get this error: 
`Stream could not be initialized!`

and in the stack trace: 
`
Error: Call to a member function isControlsMenuDisabled() on null in /var/www/app/protected/humhub/modules/content/widgets/WallEntryControls.php:71 Stack trace: #0 
/var/www/app/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\WallEntryControls->run() #1
 /var/www/app/protected/humhub/modules/content/widgets/views/wallEntry.php(31): humhub\components\Widget::widget(Array) #2
 /var/www/app/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/app/pr...') #3 
/var/www/app/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/app/pr...', Array) #4 
/var/www/app/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/app/pr...', Array, Object(humhub\modules\calendar\widgets\WallEntry)) #5 
/var/www/app/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\calendar\widgets\WallEntry)) #6 
/var/www/app/protected/humhub/components/Widget.php(63): yii\base\Widget->render('@humhub/modules...', Array) #7 
[internal function]: humhub\components\Widget::widget(Array) #8 
/var/www/app/protected/humhub/modules/content/components/ContentActiveRecord.php(334): call_user_func('humhub\\modules\\...', Array) #9 
/var/www/app/protected/humhub/modules/stream/actions/LegacyStreamTrait.php(151): humhub\modules\content\components\ContentActiveRecord->getWallOut(Array) #10 
/var/www/app/protected/humhub/modules/stream/actions/LegacyStreamTrait.php(121): humhub\modules\stream\actions\Stream::renderLegacyWallEntry(Object(humhub\modules\calendar\models\CalendarEntry), Array, false) #11 
/var/www/app/protected/humhub/modules/stream/actions/LegacyStreamTrait.php(63): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\calendar\models\CalendarEntry), Array) #12 
/var/www/app/protected/humhub/modules/stream/actions/Stream.php(359): humhub\modules\stream\actions\Stream::getContentResultEntry(Object(humhub\modules\content\models\Content)) #13
/var/www/app/protected/humhub/modules/stream/actions/Stream.php(325): humhub\modules\stream\actions\Stream->getStreamEntryResult(Object(humhub\modules\content\models\Content),  Object(humhub\modules\content\widgets\stream\StreamEntryOptions)) #14 
[internal function]: humhub\modules\stream\actions\Stream->run() #15 
/var/www/app/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #16 
/var/www/app/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\Action->runWithParams(Array) #17 
/var/www/app/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('stream', Array) #18 
/var/www/app/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('space/space/str...', Array) #19 
/var/www/app/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #20
`
<img width="1674" alt="Screenshot 2020-10-06 at 22 55 08" src="https://user-images.githubusercontent.com/66942918/95259129-0379e900-0827-11eb-9b08-451669c7b348.png">

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.3
| Branch | develop

**Comment by luke-** [comment]
This probably has something to do with new wall entry layouts, but it should actually remain compatible. 

@buddh4 any idea?

**Comment by buddh4** [comment]
Yes, added this check pretty late and it breaks compatibility with old entry types.
