### ISSUE TITLE
Hide all preview files if "Hide file info" setting is active

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4448]
Currently when the "Hide file info for images on wall" is enabled, images are not listed in the file attachment list and only rendered within the preview. Since there are also previews available for other files types as mp3 and mp4, those files should also be excluded.

**Comment by buddh4** [comment]
Related issue: https://github.com/humhub/humhub/issues/4230

**Comment by fae7em** [comment]
@buddh4, So maybe we should change the name and description of this setting, in the admin panel view and also in codes because its variable name is clearly about images, and its behavior supposed to be different.

**Comment by luke-** [comment]
Maybe something like "Hide media files"...

**Comment by ArchBlood** [comment]
> Maybe something like "Hide media files"...

This would be kind of confusing as it would suggest you're hiding files themselves, something like "Hide uploaded media extensions" sounds slightly better but could still be confused as you're hiding the files :thinking:

**Comment by buddh4** [comment]
What about

"Include media files in stream attachment file list"

**Comment by ArchBlood** [comment]
> What about
> 
> "Include media files in stream attachment file list"

This could work, although we're talking about excluding here specifically right? Either way this would work much better

**Comment by buddh4** [comment]
Yes, "Exclude media files in stream attachment list" would reflect the current setting behavior.
