### ISSUE TITLE
Needed to add comment to the variable $canCreatePosts and $isMember in humhub/modules/space/views/home.php

### ISSUE THREAD

**Issue by MasterHans** [humhub/humhub#4454]
### Describe the solution you'd like
IDE did not recognize the variables and underlines it with red.
humhub/modules/space/views/home.php

Suggesting to use 
/**@var boolean $canCreatePosts**/

**Comment by luke-** [comment]
Yes, unfortunately this has been ignored in the past. If you notice any missing type hint comments, please feel free to add them.

Example of newer views:
https://github.com/humhub/humhub/blob/feature/spaceAboutPage/protected/humhub/modules/space/views/space/about.php#L8-L12
