### ISSUE TITLE
UserFollow Activity Visibility 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4459]
### Is your feature request related to a problem? Please describe.

The UserFollow activity is never visible if the users are not friends. If the friendship system is disabled, these activities are never visible.

On my tests: If the users are friends, an error is triggered when clicking on a UserFollow activity.

### Describe the solution you'd like

The Userfollow activity (content) should be always public.
This follower list of each user is publicly accessible anyway.

**Comment by yurabakhtin** [comment]
@luke- 

> The Userfollow activity (content) should be always public.

PR https://github.com/humhub/humhub/pull/5153

> On my tests: If the users are friends, an error is triggered when clicking on a UserFollow activity.

Could you please show me what error did you get? Or test how it works with new changes.

**Comment by luke-** [comment]
@yurabakhtin Thanks. Works also for me now... Maybe fixed in the meantime.
