### ISSUE TITLE
LDAP PHP 8 incompatibility (multiPageSearch)

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4465]
## PHPCS output:

FILE: /humhub/modules/ldap/components/ZendLdap.php

FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES

 87 | WARNING | Function ldap_control_paged_result() is deprecated since PHP 7.4; Use ldap_search() instead
 98 | WARNING | Function ldap_control_paged_result_response() is deprecated since PHP 7.4; Use ldap_search() instead

### From PHP8 breaking changes:

**LDAP**:

. The deprecated function ldap_sort has been removed.
. The deprecated function ldap_control_paged_result has been removed.
. The deprecated function ldap_control_paged_result_response has been removed.
. The interface of ldap_set_rebind_proc has changed; the $callback parameter
does not accept empty string anymore; null value shall be used instead.

**Comment by luke-** [comment]
Upstream: https://github.com/laminas/laminas-ldap/pull/9

**Comment by luke-** [comment]
See also: https://github.com/laminas/laminas-ldap/issues/11
