### ISSUE TITLE
Comments and likes don't work in the site.

### ISSUE THREAD

**Issue by fioresarro** [humhub/humhub#449]
The problem is really hot. The comments and the likes are very important for interaction. I have tested them with macosx an I used Mozilla and Safari!!! I made a test also in a windows virtual system with mozilla and they don't work.

**Comment by fioresarro** [comment]
I have updated today and the problem is always there. I explain better by this video: http://projectware.eu/test/humhub.swf.

**Comment by andystrobel** [comment]
I have really no idea. Like you can see on http://translate.humhub.org/ other users (and me) are able to comment and like posts (I just tested it with Firefox and Safari). But I ask my questions again. Do you get any error in your browser console when you clicking the like link?

**Comment by fioresarro** [comment]
I also think it's strange. But my video talks clear about.
Also a my friend has the same error.
Browser console gets no error.
I don't know how I can explain still the problem.

I have also changed the computer and the browsers.

Is it an italian problem?

Ask your users about for statistics.

I don't have other ideas at the moment.

**Comment by andystrobel** [comment]
That's it!!!
When I switch to the italian language I have the same behavior. It's because of apostrophes in some translations. Ok, now I know what to do and can fix it ;-)

**Comment by fioresarro** [comment]
Ahahahahhah!!! Eureka!!!
I'm very happy now!!!
My suggest appeared a joke.
Incredible!!!

**Comment by andystrobel** [comment]
Haha... really funny, but so it is sometimes :smiley:
