### ISSUE TITLE
Empty "Add Modules" modal on space creation

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4494]
See commens at https://community.humhub.com/s/installation-and-setup/?contentId=227254

Not sure how to reproduce but I assume if there are no modules availalbe which can be installed on space level or if the only module which is installable on space level is already installed as default module. The "Add Modules" step of the space creation process is empty.

**Comment by subversve** [comment]
Some added info...

Modules added: Calendar, Custom Pages, Gallery, RESTful API, Social Share, Tasks

I set Calendar, Custom Pages, Gallery, & Tasks to be 'Always Active' (under the Set As Default settings). After doing that, I am presented with a blank popup to add modules when I add a new space.

[
<img width="816" alt="Screen Shot 2020-10-13 at 9 42 48 AM" src="https://user-images.githubusercontent.com/1066676/95907967-33f2e300-0d51-11eb-82ac-74d56c55ab09.png">
](url)

**Comment by ArchBlood** [comment]
> Some added info...
> 
> Modules added: Calendar, Custom Pages, Gallery, RESTful API, Social Share, Tasks
> 
> I set Calendar, Custom Pages, Gallery, & Tasks to be 'Always Active' (under the Set As Default settings). After doing that, I am presented with a blank popup to add modules when I add a new space.
> 
> [ <img alt="Screen Shot 2020-10-13 at 9 42 48 AM" width="816" src="https://user-images.githubusercontent.com/1066676/95907967-33f2e300-0d51-11eb-82ac-74d56c55ab09.png"> ](url)

Can confirm this
