### ISSUE TITLE
Lock conversations by disabling comments

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4495]
Admins/Moderators should be able to lock a conversation and disable commenting on such content.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5181:

<img width="667" alt="disabled_comments" src="https://user-images.githubusercontent.com/6995524/126462078-71bf96f0-6731-418b-a73a-8c0b335f4a11.png">

**Comment by luke-** [comment]
@Semir1212 Any ideas for the naming/labeling?
Maybe the lock symbol/word is better?

**Comment by funkycram** [comment]
Great feature! As the lock symbol is already used privacy, maybe the `check` and `times` (cross) icons?

**Comment by ArchBlood** [comment]
> Great feature! As the lock symbol is already used for privacy, maybe the `check` and `times` (cross) icons?

I'd prefer if `user-secret` were used for privacy instead so that the `lock` & `unlock-alt` could be used here

**Comment by luke-** [comment]
@yurabakhtin Can we use following wording please:
``` 
Lock comments
Unlock comments
Comments are locked
```

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub/pull/5181/commits/527ed03c0c71d3cb780380ee18c1650679073cdd

**Comment by luke-** [comment]
@yurabakhtin Can you please rename the method accordingly?

**Comment by yurabakhtin** [comment]
@luke- Ok, commit https://github.com/humhub/humhub/pull/5181/commits/9000ffb77c5d1c0aeb63cda663753911fd97640d.

**Comment by luke-** [comment]
@yurabakhtin Thanks! Two more points:

- Whether someone can lock comments should depend on the ManageContent Permission.
- Can you please also rename the database field to "locked_comments". (No extra migration is needed here)

(I am still unsure about the icon.)

**Comment by yurabakhtin** [comment]
@luke- 

- https://github.com/humhub/humhub/pull/5181/commits/61420cde4fbe5aac3f7ee4e2285b5672a13fd2ec - "Fix permission for locking comments"
- https://github.com/humhub/humhub/pull/5181/commits/73155564f1aa920985f8d3be61cab738c1954352 - "Rename database field to "locked_comments""

**Comment by luke-** [comment]
@yurabakhtin Thanks, PR is merged!
