### ISSUE TITLE
1.7 Notifications dropdown text too penetrant

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4497]
When comparing the Notification dropdown with the mail dropdown the notification dropdown text looks a bit too penetrant due to the text color changes. We should align the style with activity or mail dropdown.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7

**Comment by luke-** [comment]
Here some examples:
![image](https://user-images.githubusercontent.com/4736168/95963597-2cdadc00-0e08-11eb-90dc-e63290d970c2.png)
![image](https://user-images.githubusercontent.com/4736168/95963709-4ed45e80-0e08-11eb-810f-02722ef9c6db.png)

I would prefer the lighter style of the Mail Module. What do you think?
