### ISSUE TITLE
Cronjob via HTTP

### ISSUE THREAD

**Issue by Freekkel** [humhub/humhub#453]
Hi,

I use humhub on a webhoster and I I'm not allowed to make cronjobs via ssh I can only call a .php file. So how do i make it this way? I think the cronjob is really necessary. 
Best regards 

Sven

**Comment by benpowell** [comment]
Did this feature get created? I am on hosted on a shared host, without access via SSH. No cron jobs. I could use an external web cron service, but this batch file can't be run externally, even if I allow hosts via the .htaccess file.
