### ISSUE TITLE
Remove Stream post left padding on mobile

### ISSUE THREAD

**Issue by st5000** [humhub/humhub#4531]
Big left padding totally useless make horrible experience on mobile devices since HH1.7-beta.1.

![image](https://user-images.githubusercontent.com/57590912/96336468-5aca5580-1080-11eb-9dc3-0411b27fb6cd.png)

![image](https://user-images.githubusercontent.com/57590912/96336568-18eddf00-1081-11eb-8689-09de21e99234.png)

**Comment by buddh4** [comment]
We could think about removing the padding on mobile. Generally I think the padding makes a stream way more structured on bigger screens. Also in the future the space could be used for other features as for example stack-overflow like votings / bookmark icons / colored marking of posts. Such a padding is also used on other platforms as reddit or twitch, so its not that uncommon. Furthermore, the padding can be easily removed in your theme.

I aggree that on mobile its perhaps a bit too much wasted space.

**Comment by st5000** [comment]
Some people don't reject any theme changes that have REAL advantages. Which added value have this padding on **daily HumHub usage** ? For me, nothing. Totally useless. Even on big and wide screen.

Please don't try to always copy others (like post visibility now same as Twitter...) ;-)

**Comment by ArchBlood** [comment]
The sides open the possibility to add sidebars to either side of the screen just a possible solution in the future :thinking:

**Comment by buddh4** [comment]
In case you aim for a constructive discussion, try to be a bit less offensive towards others who implement software you probably use for free. I did not design the changes and features as the visiblitiy Icon were planned way before I've even had a Twitter account. If you dislike the changes you are free to give contructive feedback, I've even agreed with some of your points and offered a solution through theming.

**Comment by st5000** [comment]
Sorry for my limited capabilities in English...

**Comment by buddh4** [comment]
Lets wait for some further feedback, we could also think about a poll in the community. I can (and should) write a theme migration guide, how to remove the padding if not wanted. With "People tend to reject theme changes" I did not specificly refer to you, I also tend to do so from time to time. As I said I personally like the padding because the stream looks more structured for me, especially when mixing differen content types (which are not yet implemented). But I do not insist on this change. I think initially the idea was beeing able to mark specific posts with a color and we even had design concepts for this.

**Comment by st5000** [comment]
@buddh4 I removed left padding for comparison. For me, it's really better like this. Indentation of comments is OK.

![image](https://user-images.githubusercontent.com/57590912/96351996-19599a80-10c0-11eb-93e6-215fa46188b1.png)

Suggestion: colors, votes, etc. may be put outside left the post container. In the unused left sidebar.

**Comment by luke-** [comment]
We would remove the padding for the mobile view and leave it as it is in the desktop view..

With this code a theme developer can also easily implement this for the desktop views in own themes.
Maybe we can additionally add  a small tutorial in the community wiki for this.

**Comment by buddh4** [comment]
Setting [this](https://github.com/humhub/humhub/blob/develop/static/less/stream.less#L53) variable to 0 should be enough i think.

**Comment by buddh4** [comment]
I was wrong, but https://github.com/humhub/humhub/pull/4562 introduces a new variable `@wallEntryContentLeftPadding` for this purpose.

**Comment by luke-** [comment]
Awesome!
