### ISSUE TITLE
In the new "about" page in a space, the date of "Member since:" is wrong

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4542]
in https://community.humhub.com/s/announcements/space/space/about
The "Member since:" date is wrong:
![image](https://user-images.githubusercontent.com/23310825/96505108-f4972b80-1255-11eb-8595-061771cc998d.png)

But the bug doesn't seems to be in the code, as in my own Humhub v1.7.0-beta.1 the date is correct

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.0-beta.1

**Comment by ArchBlood** [comment]
Not seeing this on my end in the community site or my personal test site, maybe it's something to do with legacy members that joined at a specific time and date? :thinking:

![Screenshot_20201019-160834_Chrome.jpg](https://user-images.githubusercontent.com/35392110/96506386-85094800-1225-11eb-854f-3cbb8e2b26c0.jpg)

**Comment by funkycram** [comment]
Fine. Should I close this issue ?

**Comment by ArchBlood** [comment]
Not at all, I genuinely believe there is some kind of issue going on, just effects some members rather than all members which we don't know if in the long run if this issue will happen to others when they become legacy members :thinking:

**Comment by fae7em** [comment]
It seems it happens because of field `created_at` is empty for some old users. 
We can ignore displaying the `member since` item for users with empty `created_at`.

**Comment by luke-** [comment]
@fae7em Okay, in that case we'll just leave it out!

**Comment by ArchBlood** [comment]
As much as I don't like the idea, wouldn't it be better to create a migration for such a thing?

**Comment by fae7em** [comment]
We don't have the date of membership of users with empty created_at, so what can we do in migration?

**Comment by buddh4** [comment]
Just an idea, maybe get the oldest available `crated_at` date from this table, and use it for all memberships where created_at is null?

**Comment by ArchBlood** [comment]
> Just an idea, maybe one of the following:
> 
> - Get the oldest available `crated_at` date from this table, and use it for all memberships where created_at is null 
> - ~Use the space creation date~
> - Use the user creation date

This would be much preferred to simply ignoring the field as it would probably cause confusion between members thinking it was a platform issue

**Comment by fae7em** [comment]
I think the oldest available `created_at` is better than the others.

**Comment by luke-** [comment]
Ok also an option, can we solve this with a migration?

**Comment by buddh4** [comment]
But we should be aware all of the solutions could introduce inconsistent data e.g. created_at before space creation or created_at before user creation etc. But I think its not a big issue?

**Comment by ArchBlood** [comment]
> Ok also an option, can we solve this with a migration?

If the entry is `null` then you should be able to inject into the `created_at` table couldn't you?

**Comment by ArchBlood** [comment]
> But we should be aware all of the solutions could introduce inconsistent data e.g. created_at before space creation or created_at before user creation etc. But I think its not a big issue?

Then the logical solution would be creating a `created_before` table which would be piggybacking so to speak? :thinking:

**Comment by fae7em** [comment]
I think the decision about putting some estimated dates in users' database is up to the owner of the projects, not us.
As much as users may be confused about not having a `Member Since` field, they may be confused about whether this date is wrong.

**Comment by buddh4** [comment]
@fae7em you are right, but we maybe should note this in phpdocs, since this is rather a legacy problem and maybe can lead to rare issues only in rather old installations.
