### ISSUE TITLE
Enh idea: add in the space "about" page the list of the last members with the membership date

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4543]
Future enhancement idea:

Add in the new space "about" page (see https://github.com/humhub/humhub/issues/4370) the list of the last members sorted by space membership date and showing the date of membership ("members since").

Because today only admins can see this membership date in /manage/member, but if moderator want to say "hello" to new the members of this week for example, he cannot know who they are.

**Comment by luke-** [comment]
@fae7em We could add a order flag to the members sidebar widget and use the current sort on the Space Stream page (as before) and a sort by `new members` on the About page.

What do you think?

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/widgets/Members.php#L62

**Comment by fae7em** [comment]
Can we just give read access in `Manage members` to Moderators?

**Comment by luke-** [comment]
@fae7em Do you mean access to the member administration?

**Comment by fae7em** [comment]
Yes, Space member administration contains a list of members with their join date and last visit, but without access to change their roles.

**Comment by luke-** [comment]
Ok, that would also be a good option but probably a bit too complicated.
The widget would also work for everyone (not only moderators) and would only need to be slightly customized.

Maybe we can enhance the member list popup in future and display more infos like "membership since".

**Comment by luke-** [comment]
Thanks! Merged in 1.8-dev
