### ISSUE TITLE
Handle invalid timezone validation in registration process

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4549]
Since HumHub 1.7 we try to determine the user timezone from the browser in the registration process. Currently this may fail if the given timezone is not included in `DateTimeZone::listIdentifiers()`. There is no way of changing this value manually so users would be stuck on this validation error. We should set the app timezone as fallback, in case the validation fails, and prevent locking down user registrations.

- PR: https://github.com/humhub/humhub/pull/4350
- Issue in the community: https://community.humhub.com/content/perma?id=227832

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7

**Comment by yurabakhtin** [comment]
@luke- @buddh4 Please note I did to set `$this->$attribute = null;` on validate the time zone attribute but on save `User` it is updated to default time zone by code here https://github.com/humhub/humhub/blob/fix/4549-handle-invalid-timezone-on-registration/protected/humhub/modules/user/models/User.php#L496-L498:

```
if ($this->time_zone == '') {
    $this->time_zone = Yii::$app->settings->get('timeZone');
}
```

I.e. after registration such users without correct time zone will use the time zone from site general settings "Administration" > "Settings" > "General" > "Server Timezone".

**Comment by luke-** [comment]
@yurabakhtin Nice solution!
