### ISSUE TITLE
Daily/Weekly Mail Summary Resend

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4553]
### What steps will reproduce the problem?

In rare cases the Mail Summary Sending Active Job (queue) aborts and starts again (one hour?) later. 
Users who have already been processed by then will receive a MailSummary again when there is new content.

Since we store the time of the last send anyway, we should take this into account.
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/activity/components/MailSummary.php#L102

### What is the expected result?

Job retry should only process not processed users

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/4736

**Comment by yurabakhtin** [comment]
@luke- I forgot to tell you that during working on this I detected another issue(probably it is related only to my local mail service `MailHog` which I used to catch emails): if a user email has a dot then it is not sent, e.g. sample user `sara1989` with email address `sara.schuster@example.com` cannot receive any email. Only if I change the email address to `saraschuster@example.com` then it works.

**Comment by luke-** [comment]
@yurabakhtin 
We have a little "hack" here that prevents emails from being sent to the demo accounts: 
https://github.com/humhub/humhub/blob/master/protected/humhub/components/mail/Mailer.php#L33

Because of the PR, I think we have to add some tolerance intervals here, because the Daily/Weekly/Hourly job is usually only triggered once and runs for different lengths of time. 

```php
            $intervalTimes = [
                self::INTERVAL_WEEKLY => 432000, // 5days
                self::INTERVAL_DAILY  => 57600, // 16hours
                self::INTERVAL_HOURLY => 2700, // 45min
            ];
```

Perhaps the problem could be solved by such intervals? Unfortunately, this is not the prettiest solution.

**Comment by yurabakhtin** [comment]
@luke- Ok, thank you for the info about the little "hack".

Yes, I understand a job is triggered once, but we created the fix for abort case.
If we will use 5 days instead of 7 days for `INTERVAL_WEEKLY` then it may be resent often than 1 week, so user may be confused if he received the email on Monday and then on Saturday of the same week instead of expected Monday of the next week. Of course the aborted job can be not executed each day during week, but if you think the solution is enough I can do this, please confirm.

**Comment by luke-** [comment]
@yurabakhtin  I'll pass the PR on to the user with the probematic installation. I think we'll see pretty quickly whether the approach works well.  I will get back to you!
