### ISSUE TITLE
Deprecate CompatModuleManager

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4558]
- Mark method here as deprecated:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/behaviors/CompatModuleManager.php

- Remove usages in core & modules

**Comment by yurabakhtin** [comment]
@luke- Do I understand you correctly we should modify in all places like this:

- `$space->getAvailableModules()` => `$space->getModuleManager()->getAvailable()`
- `$user->disableModule($module)` => `$user->getModuleManager()->disable($module)`
- etc.

?

**Comment by luke-** [comment]
Yes.

Maybe `$space->moduleManager->getAvailable()`would be better instead of `getModuleManager()`?

**Comment by yurabakhtin** [comment]
@luke- Yes, you are right the `$space->getModuleManager()` is called from magic method `__get()`, ok I will use the `$space->moduleManager->...` instead.

**Comment by yurabakhtin** [comment]
@luke- Core PR https://github.com/humhub/humhub/pull/5274,
module PRs:

- https://github.com/humhub/calendar/pull/253
- https://github.com/humhub/cfiles/pull/136
- https://github.com/humhub/custom-pages/pull/195
- https://github.com/humhub-contrib/external_calendar/pull/29
- https://github.com/humhub-contrib/gallery/pull/87
- https://github.com/humhub/meeting/pull/13
- https://github.com/humhub/news/pull/34
- https://github.com/humhub/polls/pull/90
- https://github.com/humhub/tasks/pull/164
- https://github.com/humhub/wiki/pull/200

**Comment by luke-** [comment]
@yurabakhtin Awesome, thanks for the overview!
