### ISSUE TITLE
LDAP connection to OS X Server

### ISSUE THREAD

**Issue by Manuwickrama** [humhub/humhub#456]
I'm trying to connect to OS X server having Open Directory through LDAP. SSL is enabled. I'm getting this error:

Status: Error! (Message: 0x51 (Can't contact LDAP server): ldaps://10.10.10.27:389)

Is it because I'm using self signed certificates? If so I will have to set:

"TLS_REQCERT never" in LDAP configuration

How do I do this in HumHub?
Thanks.

**Comment by Liz-Gtz** [comment]
Hi!
I'm new and I wanted to auth user using ldap but I'm getting this error:

Status: ¡Error! (Mensaje: 0x34 (Server is unavailable; 00000000: LdapErr: DSID-0C090F7B, comment: Error initializing SSL/TLS, data 0, v2580): 192.168.1.6:389)

Please help me
Thanks
