### ISSUE TITLE
Custom Pages for Guests only

### ISSUE THREAD

**Issue by vip3r78** [humhub/humhub#4563]
Unregistered visitors should be directed to a custom page, registered visitors to the dashboard.

At Custom pages you can choose between "Admin only", "Members only" and "Members & Guests". Here a fourth option "Guests only" would be useful, especially for a landing page.

As described here I have tried some things without success:
https://community.humhub.com/s/general-discussion/?contentId=226319

**Comment by luke-** [comment]
You can create a feature request in the custom pages module repository:
https://github.com/humhub/humhub-modules-custom-pages
