### ISSUE TITLE
Minor differences between clickable and non clickable space/user counter

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4574]
Minor difference between clickable and non clickable space/user counter:

![grafik](https://user-images.githubusercontent.com/9800854/97162812-014cdf80-1780-11eb-8dcd-01af38e9a3c8.png)

**Comment by ArchBlood** [comment]
Maybe grayout the non-clickable counters while highlight the clickable counters? Would make this show the differences between the two without doing much work
