### ISSUE TITLE
Image alignment in Richtext

### ISSUE THREAD

**Issue by J0000** [humhub/humhub#4587]
By using Humhub with Desktop you'll see a lot of text. A little bit of illustrating would be great, but when you try to use an image as design-element you have not much choices how to use it.

It would be nice if there's the possibility to set alignment for pictures in richtext-editing. I know that's perhaps a problem with the responsive layout, but i'm sure there's a solution with the layout framework.

**Comment by buddh4** [comment]
I've thought about this feature. Unfortunately such an alignment is not supported by markdown, but there are some workarounds available. I've added this to https://github.com/humhub/humhub/issues/4215

**Comment by buddh4** [comment]
Will be available in HumHub 1.8

**Comment by J0000** [comment]
Thanks a lot
