### ISSUE TITLE
Possibility for users  to add themselves a group.

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4588]
I need to develop the possibility for users to add themselves a group.
The idea is that in the admin configuration of each group we can choose if this group is allowed for users to add it to themselves without needing to ask an administrator to do so.
And in the groups directory, for the groups allowed, a button appears to become a member of this group.

I will publish the code in open source and for free to the Humhub community.
@luke- @buddh4  Should I develop this feature in the user module and create a pull request, or should I develop a separated module ?

**Comment by luke-** [comment]
Imo something like this would probably make more sense as a module. 
Sounds like a very special usecase and such a button could only be placed on the "Groups" page in the directory. 

For your requirement, wouldn't it also be imageable via a Space?

**Comment by funkycram** [comment]
Thanks for your answer. Fine, I will develop it as a module.
Yes, the buttons would be on the "Groups" page in the directory.
No, not via Space, as it is `humhub\modules\user\models\Group` model, so no relation with the spaces.
