### ISSUE TITLE
UserUrlRule throws error on incomplete url

### ISSUE THREAD

**Issue by radiolip** [humhub/humhub#459]
Why the show code of page, if write link http://site.com/u/user/home without "home" (http://site.com/u/user) how to hide the code of page?

![capture](https://cloud.githubusercontent.com/assets/9461399/5315582/33657bf0-7c34-11e4-9eb6-61c73043806b.PNG)

**Comment by luke-** [comment]
Fixed here https://github.com/humhub/humhub/commit/c6aa3cb5be37ae63c71643567006d1b57d849178
