### ISSUE TITLE
RegistrationController.php doesn't return translated text

### ISSUE THREAD

**Issue by staruch** [humhub/humhub#4591]
One of the controllers is missing Yii text call, therefore it doesnt return translated message. I changed the code, so it is now reading from language file UserModule.base. Here is the code snippet, commented part is original code:

```
 public function beforeAction($action)
    {
        if (!Yii::$app->user->isGuest) {
            /* throw new HttpException(401, "You are already logged in. Please logout first!"); */
           throw new HttpException(401, Yii::t('UserModule.base', 'You are already logged in. Please logout first!'));
        }

        return parent::beforeAction($action);
    }
```

### What steps will reproduce the problem?
When user clicks on the registration link in the email containing invitation token, but is already logged in.
example.domain/index.php?r=user%2Fregistration&token=TOKENHERE 

### What is the expected result?
Information about "You are already logged in.." in users language

### What do you get instead?
Untranslated english text

### Additional info
Some fancier text wrapping with call to action like "log off" or "proceed" will be nice to have on that place. 

HumHub version: 1.6.4
PHP version: php7.4-fpm
Operating system: Ubuntu 20.04.1 LTS

**Comment by luke-** [comment]
@MasterHans Can you please take look? it's not required to rebuild/extract the message files. (This happens automatically by our translation site)
