### ISSUE TITLE
How do you add emoji's to humhub

### ISSUE THREAD

**Issue by Yushe** [humhub/humhub#460]
I really want my custom emotes on humhub but I don't know which file to edit so I can add them.

**Comment by timvango** [comment]
+1

**Comment by paulocmb-duplicate** [comment]
folder "\protected\libs\HHTml.php"

**Comment by jahd2602** [comment]
What about /protected/widgets/views/heditor? it also has a emojis' list in line 19 similar to HHTml.php one, but in JS.

```javascript
var emojis = ["Ambivalent", "Angry", "Confused", "Cool", "Frown", "Gasp", "Grin", "Heart", "Hearteyes", "Laughing", "Slant", "Smile", "Wink", "Yuck"];
```

**Comment by WASasquatch** [comment]
@jahd2602 yes, that needs to be updated as well. That is so the JS editor recognizes the correct title for each smiley. You will also have to add the new smiley image.

**Comment by baoc75** [comment]
Then how to translate the emoji text? I try to change  "$emojis = array('Ambivalent', 'Angry', 'Confused', 'Cool', 'Frown', 'Gasp', 'Grin', 'Heart', 'Hearteyes', 'Laughing', 'Naughty', 'Slant', 'Feliz', 'Wink', 'Yuck');" but no luck.

**Comment by 001101** [comment]
Can someone please tell me how to post the smilies in normal editor?!

Why isn't there no simple smilie popup list where you can select the emojis?
Normal users don't learn the names of the smilies and with the internationalization in mind it is not a good way of UX.

**Comment by buddha87** [comment]
if you pres ':' within the post or comment textbox there should be a smile selection

**Comment by 001101** [comment]
Post or comment of course, but not in private messages or other pages, why is  that so?
