### ISSUE TITLE
Picture upload list is shown in posts

### ISSUE THREAD

**Issue by smashm** [humhub/humhub#4605]
### What steps will reproduce the problem?
Upload some pictures with the »Attach Files«-button at a post.

### What is the expected result?
In older versions only the pictures were shown.

![Bildschirmfoto 2020-11-05 um 08 48 18](https://user-images.githubusercontent.com/60502320/98214092-58a03c00-1f46-11eb-9218-e4868a09ec59.png)

### What do you get instead?
In 1.7.0 there is additionally shown the list with the picture names/links. 

![Bildschirmfoto 2020-11-05 um 08 47 56](https://user-images.githubusercontent.com/60502320/98214127-6950b200-1f46-11eb-9c07-1a8d556ee836.png)

(By the way, smaller images are now enlarged to grid size.)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.0
| PHP version      | 7.4.12

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by fae7em** [comment]
It's an enhancement for display attachment files in the 1.7.0 version. 
If you have activated the `hideImageFileInfo` in the previous version, and you run all migrations, it supposed to be activated as well. Could you please send the values of `excludeMediaFilesPreview` and/or `hideImageFileInfo` in your `setting` table in the database?
Also, you can exclude\include media files from the stream attachment list through the administration panel in Settings -> Advanced -> Files.

**Comment by buddh4** [comment]
@smashm did you update by git or by updater module?

**Comment by ArchBlood** [comment]
Had the same issue just went into the settings again and saved which fixed it

**Comment by smashm** [comment]
Thanks for your advices. First of all, I misunderstood the new phrasing »Exclude media files from stream attachment list« instead of »Hide file info (name, size) for images on wall«. I searched for the old possibility (as I remembered), while I thought, that the new point is an easy way to exclude stream entries for media files (which is so far handled with 'streamExcludes' in common.php) – »attachment« seems to be a very small word which could be read over. ;) 

But: I first noticed the change in my inhouse test environment (with php 7.3) and then was able to reproduce it on another instance (with php 7.4) at the hosting provider, also mainly for testing purposes. Too bad that exactly in this installation the file infos were not hidden, like in the productive environment (which still runs 1.6.4) and my main test scenario, so that I have gained the impression, that 1.7.0 is the reason. To make matters worse, test changes had no effect there, despite emptying caches etc. (In contrast to changes to the hosted test instance.)

So, it seems, that the updater maybe(!) has ignored the old setting, I'm not able to verify that.

Mainly it was a classical PEBCAK. Sorry for that. 

At least, to give answers to your questions:
– the values in the settings 0 or 1 do now, what they should.
– all updates are made with the updater module

**Comment by buddh4** [comment]
Thanks for the info, there is a migration transfering the old setting. Also the active setting should be the new default.

**Comment by fae7em** [comment]
@buddh4 I update 2 different instances with and without the old setting using the updater, data transfer worked well.
But, It didn't work. As I checked, It seems the problem is because of the `humhub.files.js` assets file which is not refreshed and uses the old js codes.

**Comment by buddh4** [comment]
@fae7em If you manually update the module e.g. via git you have to clear the cach, otherwiese the old assets file are used. The updater module should do this automatically.

**Comment by fae7em** [comment]
I used the updater module to update the project and as I checked this file didn't refresh. 
Does the updater module handle to set `forceCopy` or you do it manually?

**Comment by buddh4** [comment]
I think the core updater should flush the cache, did it work for you after manually flushing the cache?

**Comment by fae7em** [comment]
I changed the `flushCaches` function in the updater module's `InstallController` to the below codes and it worked:

````
protected function flushCaches()
    {
        Yii::$app->moduleManager->flushCache();
        Yii::$app->assetManager->clear();  //added to clear assets directory
        Yii::$app->cache->flush();
    }
````
