### ISSUE TITLE
Image editor issue in 1.7

### ISSUE THREAD

**Issue by samsheridan** [humhub/humhub#4614]
### What steps will reproduce the problem?
Log into the HumHub Community. Go to your profile or a space you can change the picture of. Click the edit button on your profile image. Drag cropping handles.

### What is the expected result?
A new cropped portion of the image.

### What do you get instead?
A skewed, resized portion of the image. Saving the image results in a different view altogether.

### Additional info
Seems to affect banner images as well. I also noticed that certain images I upload appear distorted on my site, even though they worked fine on previous versions and I have not enabled compression.

**Comment by buddh4** [comment]
[This](https://github.com/humhub/humhub/pull/4402/files#diff-d196835517c79db43789ddb725ae44ff3ffb124221316d04c661c053d9216be5R59) seems to be the issue, when reverting to none it works for me, can you approve this?

**Comment by buddh4** [comment]
Related to: https://github.com/humhub/humhub/issues/4111

**Comment by samsheridan** [comment]
Reverting to `none` worked for me. Thank you!

**Comment by shubham-singh-dev** [comment]
**Anyone have the solution ?**
