### ISSUE TITLE
Image Croping Issue

### ISSUE THREAD

**Issue by shubham-singh-dev** [humhub/humhub#4616]
**Hello,**

Can someone help me with this problem. I set it to production not this is happening.
Please help.
Issue is while modifing the image crop does not work properly. I have attached an image.

![Capture](https://user-images.githubusercontent.com/69746961/98431112-c7ad9a00-20d8-11eb-9169-e19e956887d3.JPG)
![Capture1](https://user-images.githubusercontent.com/69746961/98431114-c8dec700-20d8-11eb-8d8e-10e9a32c64bb.JPG)

**Comment by ArchBlood** [comment]
Related to #4614

**Comment by shubham-singh-dev** [comment]
Fix is here  4614

**Comment by shubham-singh-dev** [comment]
Fix is here #4614

**Comment by shubham-singh-dev** [comment]
Fix is #4615

**Comment by shubham-singh-dev** [comment]
Fix is #4615
Thank You @buddh4
