### ISSUE TITLE
(Marketplace & Onlyoffice) SSL certificate problem 

### ISSUE THREAD

**Issue by shubham-singh-dev** [humhub/humhub#4617]
**- Could not parse HumHub API response! Curl error: #60 - SSL certificate problem: unable to get local issuer certificate.**
**- Could not get document server response! Error in cURL request: SSL certificate problem: unable to get local issuer certificate.**

I got this error it was working fine on previous version.

**Comment by luke-** [comment]
Seems related to https://github.com/humhub/humhub/pull/4471
But I'm not sure, why this happens.

@yurabakhtin Any idea?

**Comment by ArchBlood** [comment]
Could it be a cURL version issue?

**Comment by luke-** [comment]
I guess something on the server configuration. 

@shubham-singh-dev Can you give us some more details about the operating system here?

**Comment by shubham-singh-dev** [comment]
I am using it on IIS Server With Reverse Nginx Proxy Manager.

**Comment by luke-** [comment]
Can you check this settigns: https://martinsblog.dk/windows-iis-with-php-curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/

**Comment by shubham-singh-dev** [comment]
One more thing My Nginx proxy manage is hosted on linux server, and humhub is hosted on iss server.

**Comment by shubham-singh-dev** [comment]
> Can you check this settigns: https://martinsblog.dk/windows-iis-with-php-curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/

Thanks this solved my issue.
