### ISSUE TITLE
Allow for custom language packs to override installed language messages

### ISSUE THREAD

**Issue by tcinelli** [humhub/humhub#463]
I'd be nice for admins to be able to create their own local version of messages/"language code".  For example, in my local install, I would like to update the "en" messages currently provided by the code base, but not necessarily want them included in the base code.

Included in this feature would also allow the tour text to be reworded according to local preferences.

I have installed the humhub-modules-translation module and played with this to do something similar, but this module makes changes to core code.

Perhaps we can add a "language pack" option to themes, or just keep as separate "language pack" module type add on?

**Comment by funkycram** [comment]
Doesn't seems to work.
Is the change made to `protected/components/HTheme.php` ([see commit](https://github.com/humhub/humhub/commit/1718e23605bb1e0bbb2148ba2687e9fd4586bb1e)) lost as this file doesn't exist any more?

**Comment by Felli** [comment]
This doesn't work within Yii2 environments from what I've looked at.

**Comment by buddh4** [comment]
@funkycram check http://docs.humhub.org/admin-translations.html#overwrite-translation-messages

**Comment by funkycram** [comment]
Thanks very much, that's perfect, sorry for not having seen it before posting !!

**Comment by buddh4** [comment]
No problem, in the future consider asking the [community](http://community.humhub.com/). Github should only be used for bugs and actual developement issues.
