### ISSUE TITLE
User approval - default text is not transferred

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#4630]
HH 1.7.0

'Default content of approval emails' (Administration --> Users --> Settings) is not transferred to approval form which is displayed when an admin approves a user. Although the form is empty, the email is sent out with content. 

Besides that the loginURL is displayed incorrectly in the email.

![image_2020_11_12T15_42_22_574Z](https://user-images.githubusercontent.com/38326726/98963108-95040700-2507-11eb-9cc7-ac724d3117be.png)

**Comment by fae7em** [comment]
Have you changed the default message in the setting form or it's generated by code? Because it suppose to be `{loginLink}` instead of `{loginURL}`.

https://github.com/humhub/humhub/blob/a618cc186ba0e3f5ccb0700c9db8a646089c464f/protected/humhub/modules/admin/models/forms/ApproveUserForm.php#L230-L240

**Comment by buddh4** [comment]
It seems I changed it in https://github.com/humhub/humhub/commit/bc621489ffe2505a10a3bd80fb436fd26ced1ede#diff-50786b2517fe78c0e6d6e2da1e1a20acb43afe83066ab033fd535e02eaa235a7 can we just replace both cases?

**Comment by buddh4** [comment]
So loginUrl = only url and loginLink is the rendered link.

**Comment by paviro** [comment]
I am also having this issue. Good tipp that it was changed to {loginLink}. To form is also empty for me on the sending screen.

**Comment by luke-** [comment]
A fix will be available with 1.7.1

https://github.com/humhub/humhub/pull/4631

**Comment by Cpt-KeksMonster** [comment]
Hello, is it possible this issue has returned in v1.11.1? I am experiencing the exact issue.

### What steps will reproduce the problem?
**Deny** a user in Administration > "User Approval".

### What is the expected result?
User gets an e-mail informing him, that he was not allowed to access this humhub instance.

### What do you get instead?
An e-mail is send to the denied user telling him that he was approved.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.1
| PHP version      | 8.1

![grafik](https://user-images.githubusercontent.com/38458892/166639713-39f322f1-13e0-4ed7-8fa7-bd3afe604792.png)

**Comment by luke-** [comment]
Can you please create a new issue for it?
