### ISSUE TITLE
mentioned non-member users get notification in private content

### ISSUE THREAD

**Issue by fae7em** [humhub/humhub#4632]
### What steps will reproduce the problem?
In private content of public space, if we mention a non-member user in a post or comment, that user doesn't receive any notification of it.
But after that, the user will receive notification for every comment on that post (which the user is mentioned in it or in its comments)

### What is the expected result?
If the non-member user is mentioned in a private space, he/she should receive notification about it, if the scenario is to ignore notification for non-members, then the user should not receive other notifications of that posts.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7
| PHP version      | 7.4

**Comment by buddh4** [comment]
I think there is an issue related to this. Currently users only get mentioned if the user can access the content. I think we should  discuss this further prior to change this behavior. In which case it makes sense that a users is informed about a mentioning in a content he can not access?

**Comment by buddh4** [comment]
Related: 

- https://github.com/humhub/humhub/issues/3767 I did not find the other discussion
- https://github.com/humhub/humhub/issues/3701 (in which the wished behavior was marked as bug)
- https://github.com/humhub/humhub/issues/2791

**Comment by fae7em** [comment]
Actually, it's not about the decision of informing a non-member mentioned user or not, it's about that it doesn't have the same behavior in the current scenario.
I just tried some cases and in each case, there is a different behavior: 

Imagine there is a public space and we have users: `x`, `y`,`z`, `w` (which user `w` is not a space member)
In each case, user `x` create a private post in the public space.

-x create a post, x mention w in its comment (no one gets notification), x reply that comment (**w get notification of new comment now while w is not a member, and w didn't get notif for mentioning in parent comment**)
-x create a post, x mention w in its comment (no one gets notification), y reply that comment (x get notification)
-x create a post, y mention w in its comment (x get notification), x reply that comment (**w get a notification while it's not a member, y didn't get notification although is the owner of the parent comment**)
-x create a post, y mention w in its comment (x get notification), y reply that comment (x get a notification)
-x create a post, y mention w in its comment (x get notification), z reply that comment (**just x get a notification, not also y that is the owner of the parent comment**)
-x create a post, y mention w in its comment (x get notification), x create **a new** comment (**w get a notification while it's a totally new comment, not reply to that comment, and also w is not a member**)

**Comment by buddh4** [comment]
Could you write test cases to cover those issues in a PR and then we can discuss the right behavior. https://github.com/humhub/humhub/issues/3767 is related to the content subscription problem. If you need help with the tests, just let me know.

Another case would be if the visibility of a content is changed, we should unsubscribe users who are not allowed to see the content.

**Comment by fae7em** [comment]
> Could you write test cases to cover those issues in a PR and then we can discuss the right behavior. #3767 is related to the content subscription problem. If you need help with the tests, just let me know.
> 
> Another case would be if the visibility of a content is changed, we should unsubscribe users who are not allowed to see the content.

I write some tests in PR to cover cases I described and also cases the visibility of content is changed.

> In the Issue I did not find someone suggested that we should not be able to mention users which are not allowed to see the content. I'am not sure if this is the right behavior since you may want to mention someone in an admin only space.

In this issue and #3767, the problem is about the content subscription. I think it's a correct behavior to mention non-members in private content and add them to the content subscriber in  the`user_follow` table  (for cases that content visibility is changed). But it should be managed in the content following notifications to check if some users don't have access to content, it prevents sending notif to them.

**Comment by buddh4** [comment]
Ok, so the content follower list can contain users which are not allowed to see the content. We should add this to the php doc of the getter function or maybe add a flag to automatically filter out followers which are not allowed to see a content.

**Comment by fae7em** [comment]
Also, if the user membership state changes (mentioned member cancel his space membership, or mentioned non-member become a member)

**Comment by luke-** [comment]
Maybe related. https://github.com/humhub/cfiles/issues/147
