### ISSUE TITLE
Most Links Broken After 1.7.0 Upgrade

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#4633]
After upgrading from 1.6 to 1.7, most of the internal links are randomly broken unless I click on them multiple times or refresh the page.

There is a similar issue posted at https://community.humhub.com/content/perma?id=229413

I am able to reproduce the symptoms on both desktop and mobile versions of Chrome.  For example, in a space gallery, I can hover but not click the thumbnails on desktop.  On mobile, I can tap and see the controls, but can't open the full photo viewer without refreshing the page.

Thumbnails on profile streams tend to be broken on mobile more often than not.

On desktop, links to profiles and spaces are often broken, whereas they seem to work most or all of the time on mobile.

**Comment by buddh4** [comment]
Can you make sure that:

 - All your modules are up to date
 - You've cleared the cache

Also check the backend logs and the developer console of your browser.

**Comment by miqrogroove** [comment]
The only installed module is Gallery and it is updated.  I haven't tested any other config so it might be specific to its presence or absence of other modules.

Haven't had time to drop the browser cache yet.  Shouldn't be necessary but I will try it this weekend or next week.

HumHub log is empty.  Debug is disabled in index.php.  I will check PHP log next.

**Comment by buddh4** [comment]
Hmm, I think the community issue is also related to the gallery. Can you try to deactivate the gallery snippet for a moment and check if the problem is gone?

**Comment by buddh4** [comment]
Plus can you confirm that the installed gallery version is 1.2.0

**Comment by buddh4** [comment]
I think this was caused by https://github.com/humhub-contrib/gallery/issues/72 there is a new gallery module version available which should fix the issue.

**Comment by miqrogroove** [comment]
Yes this bug is fixes by Gallery module 1.2.1.  Thanks for the quick patch!
