### ISSUE TITLE
Profile settings do not accept birthdate in russian format

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4638]
Profile settings do not accept birthdate when using russian locale:

![image](https://user-images.githubusercontent.com/9800854/99104581-75d9a800-25e1-11eb-849e-abd4b96e45c2.png)

**Comment by ArchBlood** [comment]
Not able to reproduce on my end of things but I am seeing this
![Screenshot_1](https://user-images.githubusercontent.com/35392110/99105032-d0f2a700-25af-11eb-8063-78a890b6af57.png)

**Comment by ArchBlood** [comment]
Alright only way I can reproduce this is if I'm using another language (i.e. English) then try entering Russian format in the field :thinking:

**Comment by buddh4** [comment]
Hmm sometimes it works for mee to but for example `4 Ноя 1987 г.` and changing the month seems to be broken.

**Comment by buddh4** [comment]
And while we are at it we should fix the datepicker z-index issue as well ;)

**Comment by ArchBlood** [comment]
Would seem that the only way this doesn't work for me is if I manually enter the date or have it translated from English to Russian then switch back to English otherwise it doesn't get reproduced on my end :thinking:

**Comment by buddh4** [comment]
Maybe an issue related with PHP + INTL version:

![grafik](https://user-images.githubusercontent.com/9800854/99113779-16cf5f80-25f0-11eb-886f-4fee1d189b50.png)

**Comment by ArchBlood** [comment]
Not sure as I'm using a different PHP version and lower version of INTL
![Screenshot_1](https://user-images.githubusercontent.com/35392110/99115795-fb009500-25c0-11eb-8bcf-d8af19040820.png)

**Comment by buddh4** [comment]
Can you copy paste the date value of your screenshot above. I could recreate this also with PHP 7.3.

**Comment by ArchBlood** [comment]
### English Manually
![Screenshot_1](https://user-images.githubusercontent.com/35392110/99116691-76af1180-25c2-11eb-9d49-36a178d1c27a.png)

### Russian Manually
![Screenshot_2](https://user-images.githubusercontent.com/35392110/99116776-98a89400-25c2-11eb-8a37-2d097a2fc3b4.png)

### Russian on change from English to Russian
![Screenshot_3](https://user-images.githubusercontent.com/35392110/99116824-aeb65480-25c2-11eb-934d-6a6dd4db848f.png)

**Comment by ArchBlood** [comment]
Copy & paste work the same as if I did it manually

**Comment by buddh4** [comment]
Yes, there is a difference in the text of the month. One is probably the short form and your working example uses the full month I assume.

**Comment by ArchBlood** [comment]
No, from what I'm told `Нояб` is short form whereas `Ноя` is not, `Ноябрь` is full month

**Comment by buddh4** [comment]
@ArchBlood can you confirm that if you change the date in the date picker the month format is `Нояб.` and not `Ноя`?

The short names are defined in https://github.com/jquery/jquery-ui/blob/master/ui/i18n/datepicker-ru.js 

I've tested manually changing `Ноя` to `нояб.` in the russian datepicker file and it worked. But I'am not sure if this is related to the ICU version or not. 

Here some additional test output:

![grafik](https://user-images.githubusercontent.com/9800854/100377466-9bb77180-3011-11eb-986e-ced632aa2058.png)

In a first bugfix version, we could change the format to short in case of russian local (or for all languages)? But this won't fix the issue since medium format date picker validation and translation would be broken in other places.

**Comment by buddh4** [comment]
Probably related to 

- https://github.com/yiisoft/yii2/issues/9312
- https://github.com/yiisoft/yii2-jui/issues/70

**Comment by ArchBlood** [comment]
> Нояб

Yes, after changing to `Нояб` everything looks to be working with manual input for me as well

**Comment by buddh4** [comment]
@ArchBlood I mean after clicking on a day in the datepicker, does it show `Нояб` or `Ноя`?

**Comment by ArchBlood** [comment]
I'm still seeing `Ноя` in the dropdown menu so the click option still defaults to `Ноя` not `Нояб` :thinking:

**Comment by buddh4** [comment]
And submitting `Ноя` works for you?

**Comment by ArchBlood** [comment]
`Ноя` does not work on my end whereas `Нояб` does :frowning_face:
