### ISSUE TITLE
Like gives error -> what to do?

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub#4651]
### What steps will reproduce the problem?
I don't really know.  It is an foreseen error:
        if ($modelClass == "" || $pk == "") {
            throw new HttpException(500, 'Model & ID parameter required!');
        }

### What is the expected result?
No error
### What do you get instead?
An error in the log
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version    1.7
| PHP version  7.4    | 
| Operating system Ubuntu Server 20.04 

yii\web\HttpException: Model & ID parameter required! in mypath/humhub/protected/humhub/modules/content/components/ContentAddonController.php:86 Stack trace:
#0 mypath/humhub/protected/humhub/modules/like/controllers/LikeController.php(40): humhub\modules\content\components\ContentAddonController->beforeAction()
#1 mypath/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): humhub\modules\like\controllers\LikeController->beforeAction()
#2 mypath/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction()
#3 mypath/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#4 mypath/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest()
#5 mypath/humhub/index.php(27): yii\base\Application->run()
#6 {main}

**Comment by luke-** [comment]
- Custom modules & themes?
- Are there any errors in the browser console?
- Can you check the ajax request in the browser?

**Comment by aronbos** [comment]
Yes, I use custom modules and my own theme. The theme only changes one view: layout/main.php. My own modules do not use the LikeController.

I do no know the cause of the error, other than the log and therefore I can not check the ajax request. 

So the question is from which view and controller action this like is called? Or is it just a search engine following links?

**Comment by luke-** [comment]
The LikeLinkWidget and LikeController is involved here.
But I think there is a Javascript error which causes problems here.
