### ISSUE TITLE
Module::update() is not called after module update with the marketplace

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#4653]
### What steps will reproduce the problem?

In the `Module.php` file, create this class: `class Module extends \humhub\components\Module`
In this class, create this function:

    /**
     * @inheritdoc
     */
    public function update()
    {
        parent::update();
        
        // Code to execute here after marketplace update
    }

### What is the expected result?

After module update with the Marketplace, `// Code to execute here after marketplace update` should have been executed.

### What do you get instead?

Code is note exectuded.
Perhaps this code should be in `beforeUpdate()` ?
Or do we need to create an event to have a code executed after a module update ? The `EVENT_AFTER_UPDATE` of the marketplace module ?

### Additional info

No error in the log.
Thanks for your help !

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7

**Comment by luke-** [comment]
Probably related to: https://github.com/humhub/humhub/issues/3872

**Comment by marc-farre** [comment]
Issue moved to https://github.com/humhub/humhub/issues/6744
