### ISSUE TITLE
Problem with cronjob cron

### ISSUE THREAD

**Issue by emilio-millepiani** [humhub/humhub#4655]
### What steps will reproduce the problem?
Every hour Cronjob cron with this command:

/usr/local/bin/php73 /volume1/web/humhub/protected/yii cron/run >/dev/null 2>&1

Normally run. Today there is a problem: 
Cronjob cron interrupt.
Cronjob queue, in other instance, is good.

### Additional info
Full error stacks

yii\base\UnknownPropertyException
yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\notification\models\Notification::content in /volume1/web/humhub/protected/vendor/yiisoft/yii2/base/Component.php:154 Stack trace: #0 /volume1/web/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('content') #1 /volume1/web/humhub/protected/modules/mentionedUsers/Events.php(20): yii\db\BaseActiveRecord->__get('content') #2 [internal function]: humhub\modules\mentionedUsers\Events::onContentDelete(Object(yii\base\ModelEvent)) #3 /volume1/web/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\ModelEvent)) #4 /volume1/web/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\componen...', 'beforeDelete', Object(yii\base\ModelEvent)) #5 /volume1/web/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1027): yii\base\Component->trigger('beforeDelete', Object(yii\base\ModelEvent)) #6 /volume1/web/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): yii\db\BaseActiveRecord->beforeDelete() #7 /volume1/web/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\db\ActiveRecord->deleteInternal() #8 /volume1/web/humhub/protected/humhub/modules/notification/Events.php(148): yii\db\ActiveRecord->delete() #9 [internal function]: humhub\modules\notification\Events::onCronDailyRun(Object(yii\base\Event)) #10 /volume1/web/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event)) #11 /volume1/web/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\commands...', 'daily', Object(yii\base\Event)) #12 /volume1/web/humhub/protected/humhub/commands/CronController.php(130): yii\base\Component->trigger('daily') #13 /volume1/web/humhub/protected/humhub/commands/CronController.php(55): humhub\commands\CronController->runDaily() #14 [internal function]: humhub\commands\CronController->actionRun() #15 /volume1/web/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #16 /volume1/web/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #17 /volume1/web/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('run', Array) #18 /volume1/web/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array) #19 /volume1/web/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('cron/run', Array) #20 /volume1/web/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('cron/run', Array) #21 /volume1/web/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #22 /volume1/web/humhub/protected/yii(29): yii\base\Application->run() #23 {main} 

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7
| PHP version      | 7.3
| Operating system | Synology DSM 6.2.3-25426 Update 2 

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
Just going to note that Synology DSM is a fork of Debian for the developers and for future reference, it uses Upstart instead of SysVinit or Systemd :thinking:

See here about Upstart and Cron Job running: https://stackoverflow.com/questions/31129348/can-upstarts-service-start-be-used-inside-a-cron-job

**Comment by buddh4** [comment]
This seems like a custom module of yours `humhub/protected/modules/mentionedUsers/Events.php` ?
