### ISSUE TITLE
Switch to OnlyOffice Connector not working

### ISSUE THREAD

**Issue by gino909** [humhub/humhub#4657]
Hi 
I have updated Humhub 1.3.10 to the latest Version 1.7. 
In 1.3.10 I have worked perfectly with the "OnlyOffice Integration" plugin, but this is no more maintained as it seems.
So i decided to move from the legacy "OnlyOffice Integration" to the new module "ONLYOFFICE Connector".

I have removed the old plugin, installed the new one. When I activate the new module 2 strange things happens:

1) the already existing documents in the spaces disappear, no document is visible anymore. when i deactivate the Plugin the documents are again visible.
2) when I want create a new document and open it in onlyoffice I get the error message: Unable to find humhub\\modules\\onlyoffice\\filehandler\\ViewFileHandler...

I switched then back to the previous "OnlyOffice Integration" module, by copying the module from 1.3.10 backup, but is does not work anymore. when opening a document in onlyoffice get the error message: The document could not be saved. Please check connection settings or contact your Administrator.

### What steps will reproduce the problem

Upgrade from 1.3.10 to 1.4 to 1.5 to 1.6 to 1.7
Deinstall legacy OnlyOffice Integration
Install Onlyoffice connector

| HumHub version   | 1.7
| PHP version    7.2  b

Error with "OnlyOffice Integration"

Error: Call to a member function getServerApiUrl() on null in /var/www/humhub/humhub-1.7.0/protected/modules/onlydocuments/assets/Assets.php:29 Stack trace: #0 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\onlydocuments\assets\Assets->init() #1 /var/www/humhub/humhub-1.7.0/protected/humhub/components/Module.php(179): yii\base\BaseObject->__construct() #2 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/marketplace/controllers/UpdateController.php(83): humhub\components\Module->publishAssets(true) #3 [internal function]: humhub\modules\marketplace\controllers\UpdateController->actionInstall() #4 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #5 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #6 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('install', Array) #7 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('marketplace/upd...', Array) #8 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #9 /var/www/humhub/humhub-1.7.0/index.php(25): yii\base\Application->run() #10 {main}

Error with "Onlyoffice connector"

yii\base\UnknownClassException: Unable to find 'humhub\modules\onlyoffice\filehandler\ViewFileHandler' in file: /var/www/humhub/humhub-1.7.0/protected/modules/onlyoffice/filehandler/ViewFileHandler.php. Namespace missing? in /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/BaseYii.php:296 Stack trace: #0 [internal function]: yii\BaseYii::autoload('humhub\\modules\\...') #1 /var/www/humhub/humhub-1.7.0/protected/modules/onlyoffice/Events.php(46): spl_autoload_call('humhub\\modules\\...') #2 [internal function]: humhub\modules\onlyoffice\Events::onFileHandlerCollection(Object(yii\base\Event)) #3 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event)) #4 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\modules\\...', 'init', Object(yii\base\Event)) #5 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/handler/FileHandlerCollection.php(58): yii\base\Component->trigger('init') #6 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\file\handler\FileHandlerCollection->init() #7 [internal function]: yii\base\BaseObject->__construct(Array) #8 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs(Array) #9 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('humhub\\modules\\...', Array, Array) #10 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\modules\\...', Array, Array) #11 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/handler/FileHandlerCollection.php(96): yii\BaseYii::createObject(Array) #12 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/libs/FileHelper.php(73): humhub\modules\file\handler\FileHandlerCollection::getByType(Array, Object(humhub\modules\file\models\File)) #13 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/libs/FileHelper.php(130): humhub\modules\file\libs\FileHelper::createLink(Object(humhub\modules\file\models\File)) #14 /var/www/humhub/humhub-1.7.0/protected/modules/onlyoffice/controllers/CreateController.php(49): humhub\modules\file\libs\FileHelper::getFileInfos(Object(humhub\modules\file\models\File)) #15 [internal function]: humhub\modules\onlyoffice\controllers\CreateController->actionDocument() #16 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #17 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #18 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('document', Array) #19 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('onlyoffice/crea...', Array) #20 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #21 /var/www/humhub/humhub-1.7.0/index.php(25): yii\base\Application->run() #22 {main}

Error: Class 'humhub\modules\onlyoffice\filehandler\ViewFileHandler' not found in /var/www/humhub/humhub-1.7.0/protected/modules/onlyoffice/Events.php:46 Stack trace: #0 [internal function]: humhub\modules\onlyoffice\Events::onFileHandlerCollection(Object(yii\base\Event)) #1 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event)) #2 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\modules\\...', 'init', Object(yii\base\Event)) #3 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/handler/FileHandlerCollection.php(58): yii\base\Component->trigger('init') #4 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\file\handler\FileHandlerCollection->init() #5 [internal function]: yii\base\BaseObject->__construct(Array) #6 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/di/Container.php(406): ReflectionClass->newInstanceArgs(Array) #7 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('humhub\\modules\\...', Array, Array) #8 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\modules\\...', Array, Array) #9 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/handler/FileHandlerCollection.php(96): yii\BaseYii::createObject(Array) #10 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/libs/FileHelper.php(73): humhub\modules\file\handler\FileHandlerCollection::getByType(Array, Object(humhub\modules\file\models\File)) #11 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/libs/FileHelper.php(130): humhub\modules\file\libs\FileHelper::createLink(Object(humhub\modules\file\models\File)) #12 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/widgets/FilePreview.php(119): humhub\modules\file\libs\FileHelper::getFileInfos(Object(humhub\modules\file\models\File)) #13 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/widgets/FilePreview.php(86): humhub\modules\file\widgets\FilePreview->getFileData() #14 /var/www/humhub/humhub-1.7.0/protected/humhub/components/Widget.php(63): humhub\modules\file\widgets\FilePreview->run() #15 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/widgets/views/showFiles.php(91): humhub\components\Widget::widget(Array) #16 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...') #17 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/humhub...', Array) #18 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/humhub...', Array, Object(humhub\modules\file\widgets\ShowFiles)) #19 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('showFiles', Array, Object(humhub\modules\file\widgets\ShowFiles)) #20 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/file/widgets/ShowFiles.php(56): yii\base\Widget->render('showFiles', Array) #21 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\modules\file\widgets\ShowFiles->run() #22 /var/www/humhub/humhub-1.7.0/protected/humhub/widgets/BaseStack.php(90): yii\base\Widget::widget(Array) #23 /var/www/humhub/humhub-1.7.0/protected/humhub/components/Widget.php(63): humhub\widgets\BaseStack->run() #24 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/content/widgets/stream/views/wallStreamEntryFooter.php(16): humhub\components\Widget::widget(Array) #25 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...') #26 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/humhub...', Array) #27 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/humhub...', Array, Object(humhub\modules\post\widgets\WallEntry)) #28 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('@content/widget...', Array, Object(humhub\modules\post\widgets\WallEntry)) #29 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(255): yii\base\Widget->render('@content/widget...', Array) #30 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(188): humhub\modules\content\widgets\stream\WallStreamEntryWidget->renderFooter() #31 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(128): humhub\modules\content\widgets\stream\WallStreamEntryWidget->renderBody() #32 /var/www/humhub/humhub-1.7.0/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\stream\StreamEntryWidget->run() #33 [internal function]: humhub\components\Widget::widget(Array) #34 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(88): call_user_func('humhub\\modules\\...', Array) #35 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/stream/actions/StreamEntryResponse.php(80): humhub\modules\content\widgets\stream\StreamEntryWidget::renderStreamEntry(Object(humhub\modules\post\models\Post), Object(humhub\modules\content\widgets\stream\StreamEntryOptions), Array) #36 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/stream/actions/Stream.php(392): humhub\modules\stream\actions\StreamEntryResponse::getAsArray(Object(humhub\modules\content\models\Content), Object(humhub\modules\content\widgets\stream\StreamEntryOptions)) #37 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/stream/actions/Stream.php(347): humhub\modules\stream\actions\Stream->getStreamEntryResult(Object(humhub\modules\content\models\Content), Object(humhub\modules\content\widgets\stream\StreamEntryOptions)) #38 /var/www/humhub/humhub-1.7.0/protected/humhub/modules/stream/actions/Stream.php(326): humhub\modules\stream\actions\Stream->addResponseEntries(Array, Object(humhub\modules\stream\actions\StreamResponse)) #39 [internal function]: humhub\modules\stream\actions\Stream->run() #40 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #41 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\Action->runWithParams(Array) #42 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('stream', Array) #43 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('space/space/str...', Array) #44 /var/www/humhub/humhub-1.7.0/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #45 /var/www/humhub/humhub-1.7.0/index.php(25): yii\base\Application->run() #46 {main}

**Comment by ArchBlood** [comment]
I believe for a quicker fix you should jump over to the OnlyOffice repo
https://github.com/ONLYOFFICE/onlyoffice-humhub

**Comment by luke-** [comment]
Can you please create an issue here:  https://github.com/ONLYOFFICE/onlyoffice-humhub

Please try to reinstall the latest onlyoffice module and also flush the cache.
