### ISSUE TITLE
Banner Image Crop function produces wrong cutout

### ISSUE THREAD

**Issue by keinerweiss** [humhub/humhub#4658]
### What steps will reproduce the problem?

* Open a "custom_page"
* Upload a banner picture
* Edit the banner picture for a crop
* Select an area
* Save
* See the crop does not match at all what was selected

### What is the expected result?

The crop should match the selection.

### What do you get instead?

The crop looks like the exact size from the minimized preview is used and then cut in this dimensions from the original.
This results in a crazy "zoomed in" cutout. Also the preview of the crop is heavily miscalculated.

I found the problem, but am hesitant to provide a merge request, since it just hacks a hack.

https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/views/container-image/cropModal.php

```
            <style>
                /* Dirty Workaround against bootstrap and jcrop */
                #profile-image-crop-modal img {
                    max-width: 100%;
                }
            </style>
```
The max-width does not only affect the preview image but also the original image which is then used to size-up to the actual cutout dimensions.

Limiting it to the preview does solve the problem:

```
#profile-image-crop-modal #cropmodal > .jcrop-holder > img {
  max-width: 100%;
}
```
However, as I said, it's a hack for a hack, as you see. If it's suitable, feel free to use it.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7
| PHP version      | 7.1
| Operating system | Linux, Debian

**Comment by buddh4** [comment]
This was already fixed by https://github.com/humhub/humhub/issues/4616
