### ISSUE TITLE
Uploaded (attached) video displays as a blank area with a "play" button in the Space and Dashboard stream

### ISSUE THREAD

**Issue by joshkitt** [humhub/humhub#4664]
### What steps will reproduce the problem?
Upload a video as part of a new post.

### What is the expected [result?]
I would expect to see the video preview (still shot of video) with a "play" button.

### What do you get instead?
I see a blank area where the video should be, with a "play" button (see attached screenshot).

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7
| PHP version      | 7.4
| Operating system | Ubuntu backend server, iPhone client with Safari browser.
![IMG_8077](https://user-images.githubusercontent.com/913476/100394865-e201d600-2ffb-11eb-8b1d-7b4991b16952.jpg)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by smashm** [comment]
Which camera settings do you use? I suspect strongly, that the HEIV format is used for the preview for films with H.265 codec. (Unfortunately I can't try this because I don't have an iPhone.)
In this article you can see a screenshot the settings, maybe »moste compatible« is a try worth, if it is actually set to »high efficiency«.
https://www.apowersoft.com/heif-vs-jpeg.html

**Comment by joshkitt** [comment]
I had an Android user test a video upload also. It shows the same blank video on some browsers, but shows a video preview on other browsers.

When I test it with an iPhone, I'm using the default settings, so it is possible it is using HEIF format.

**Comment by buddh4** [comment]
Currently, we just render a very basic html5 video element without touching the original video. We probably need to integrate a converter for proper support.

**Comment by joshkitt** [comment]
How can I find out exactly what format these videos are so we can troubleshoot more? When you say we probably need to integrate a converter, is that assuming it is an unsupported format of video? Thanks.

**Comment by buddh4** [comment]
You could deactivate `Administration -> Settings -> Advanced -> Files -> Exclude media files from stream attachment list`. Then you should be able to download the file within the stream.

**Comment by joshkitt** [comment]
Here are the results from some basic testing after enabling download within the stream to download the files:

1. .mov file -> ISO Media, Apple QuickTime movie, Apple QuickTime (.MOV/QT) -> Works on desktop Chrome browser, does not show preview in mobile iPhone browser -> video taken on an iPhone
2. .mp4 file -> ISO Media, MP4 v2 [ISO 14496-14] -> Works on desktop Chrome browser, does not show preview in mobile iPhone browser -> video taken on Android phone

**Comment by buddh4** [comment]
Here some ideas we can try:

- Set a `poster` attribute (we'd need to extract a thumbnail from the video) https://stackoverflow.com/questions/20075875/how-to-set-the-thumbnail-image-on-html5-video
- Set initial start time https://web.dev/video-and-source-tags/#specify-start-and-end-times

**Comment by joshkitt** [comment]
Is this the same for everyone, or is it a bug for me? Is there documentation on video formats and which browsers they work with (and show a preview frame)?

**Comment by buddh4** [comment]
The video support is just not very well at the moment but I've not yet seen videos without preview but only tested with mp4 on windows or android. [Here](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs) you have detailed information about video codecs for the web.

**Comment by joshkitt** [comment]
I'd like to see what I can do to keep this request moving. I've read a little about video codecs from your link, but I'm not sure where to go from there. Is there a way to see what the priority would be for this?

**Comment by ArchBlood** [comment]
Just wanted to say that I was able to get previews by adding `preload="metadata"` with `#t=0.1`

https://github.com/humhub/humhub/blob/fcb8e0c924f33a37d0e953919f6edaea2684bdf1/protected/humhub/modules/file/widgets/views/showFiles.php#L51-L77

### Modified code
```php
                <?php foreach ($videos as $video): ?>
                    <?php if (FileHelper::getExtension($video->file_name) === 'webm'): ?>
                        <div class="<?= $fullWidthColumnClass ?>">
                            <a data-ui-gallery="<?= 'gallery-' . $object->getUniqueId() ?>" href="<?= $video->getUrl(); ?>#.webm#t=0.1" preload="metadata" title="<?= Html::encode($video->file_name) ?>">
                                <video src="<?= $video->getUrl() ?>" type="video/webm" controls preload="metadata" height="130"></video>
                            </a>
                        </div>
                    <?php elseif (FileHelper::getExtension($video->file_name) === 'mp4'): ?>
                        <div class="<?= $fullWidthColumnClass ?>">
                            <a data-ui-gallery="<?= 'gallery-' . $object->getUniqueId() ?>" href="<?= $video->getUrl(); ?>#.mp4#t=0.1" preload="metadata" title="<?= Html::encode($video->file_name) ?>">
                                <video src="<?= $video->getUrl() ?>" type="video/mp4" controls preload="metadata" height="130"></video>
                            </a>
                        </div>
                    <?php elseif (FileHelper::getExtension($video->file_name) === 'ogv'): ?>
                        <div class="<?= $fullWidthColumnClass ?>">
                            <a data-ui-gallery="<?= 'gallery-' . $object->getUniqueId() ?>" href="<?= $video->getUrl(); ?>#.ogv#t=0.1" preload="metadata" title="<?= Html::encode($video->file_name) ?>">
                                <video src="<?= $video->getUrl() ?>" type="video/ogg" controls preload="metadata" height="130"></video>
                            </a>
                        </div>
                    <?php elseif (FileHelper::getExtension($video->file_name) === 'mov'): ?>
                        <div class="<?= $fullWidthColumnClass ?>">
                            <a data-ui-gallery="<?= 'gallery-' . $object->getUniqueId() ?>" href="<?= $video->getUrl(); ?>#.mov#t=0.1" preload="metadata" title="<?= Html::encode($video->file_name) ?>">
                                <video src="<?= $video->getUrl() ?>" type="video/quicktime" controls preload="metadata" height="130"></video>
                            </a>
                        </div>
                    <?php endif; ?>
                <?php endforeach ?>
```

Although I do not own an iPhone so I can not test this on all mobile devices

**Comment by joshkitt** [comment]
I can spin up a dev instance and manually test it

**Comment by joshkitt** [comment]
@ArchBlood Is your code (above) for videos that show up in the Dasboard or Space Stream?

**Comment by ArchBlood** [comment]
Should be both :thinking: if they both use the same logic with the core file module

**Comment by joshkitt** [comment]
It looks like Safari (on Mac) does the same thing, meaning it does not showing the video preview in the stream. This is after making the code change you posted. So maybe it's a more general Safari issue.
![Screen Shot 2020-12-11 at 4 05 00 PM](https://user-images.githubusercontent.com/913476/101962965-bc172c80-3bca-11eb-9005-74832282a6ab.png)

**Comment by joshkitt** [comment]
It looks like Safari on Mac has the same problem where the video does not show a preview in the stream (see screenshot). This is after applying the code posted here.
![Screen Shot 2020-12-11 at 4 22 19 PM](https://user-images.githubusercontent.com/913476/101963881-19ac7880-3bcd-11eb-833e-9217991d272d.png)

**Comment by ArchBlood** [comment]
Then maybe this will help?
https://stackoverflow.com/questions/41255841/how-to-get-html5-video-thumbnail-without-using-poster-on-safari-or-ios

**Comment by joshkitt** [comment]
After reading through the StackOverflow page, and reviewing your code above, I see one difference. If I add the "#t=0.1" to the "src" attribute of the "`<video>`" tag, it then works on Safari Mac and iOS:

`<video src="<?= $video->getUrl() ?>#t=0.1" type="video/quicktime" controls preload="metadata" height="130"></video>`

So, I think that will fix the problem for me. In your code above, you added "#t=0.1" to the "href" attribute of the "`<a>`" tag that wraps around the "`<video>`" tag. What is the purpose of the "`<a>`" tag around the "`<video>`" tag in this case?

**Comment by buddh4** [comment]
Related to https://github.com/humhub/humhub/issues/4411 when replacing jplayer we maybe can use e.g. mediaelements also as video player.

**Comment by luke-** [comment]
Fixed here: https://github.com/humhub/humhub/pull/5184
