### ISSUE TITLE
request: add a editing function custom word to the invitation email

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#4672]
### Is your feature request related to a problem? Please describe.
We want to invite an external user to our humhub space. Of cause, we can send invite mail by space member. But they would like to add a few words to them for the management of the space.

### Describe the solution you'd like
Wouldn't it be possible to add a message edit box to the email invitation form?

**Comment by luke-** [comment]
Maybe an invitation via link could be also a solution for your problem.
So you can simply create a link in HumHub and send it personally.

https://github.com/humhub/humhub/issues/226

**Comment by tomofu74** [comment]
Thank you. I see.
