### ISSUE TITLE
Video Galllery support

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#4674]
I'm trying to make gallery works with videos. But I recieve this error:

`yii\base\ErrorException: Trying to get property 'file_name' of non-object in /home/brfriends/public_html/protected/modules/gallery/widgets/views/galleryListEntry.php:39 Stack trace: #0 /home/brfriends/public_html/protected/modules/gallery/widgets/views/galleryListEntry.php(39): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/home/brfriends/...', 39, Array) #1 /home/brfriends/public_html/protected/vendor/yiisoft/yii2/base/View.php(348):`

The code where the error happen:
`<?php if(FileHelper::getExtension($fileUrl->file_name) == 'mp4'): ?>`

> PHP Version: 7.2
> HumHub Version: 1.7.1

**Comment by luke-** [comment]
Please provide steps to reproduce.
