### ISSUE TITLE
Maxlength in username

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#4675]
I want to control the maxlength in the username field, but I was change it and nothing happen.
   
```
$form['elements']['username'] = [

            'type' => 'text',

            'maxlength' => '10',

 ];

```

Maxlength doesnt works. What I do?
Obs.: is this possible control the empty space and capital letter too?

**Comment by ArchBlood** [comment]
You do this through [configuration](https://docs.humhub.org/docs/admin/advanced-configuration/#module-configurations)
See here for the exact parameter needed used; https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/Module.php#L66
