### ISSUE TITLE
request: user picker select with tags

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#4676]
### Is your feature request related to a problem? Please describe.
When a member invite others to his space, it is easier to pick them with their tags.

### Describe the solution you'd like
User picker shown with user tags. Or user would be picked with their tags.

### Describe alternatives you've considered
It would be necessary to inform the acquired members in advance that a unified tag will be attached to their account.

**Comment by luke-** [comment]
Do you mean tags specified at: Account settings -> Settings -> Tags?

**Comment by tomofu74** [comment]
Yes, I do.

**Comment by luke-** [comment]
So it would be enough for you if tags were included in the search? Or do you want to change something in the appearance?

**Comment by tomofu74** [comment]
Sorry, I mistake the tags for topics. (Account Settings -> Settings -> Topics)

It is advisable that the search were included in the search. If it could be possible ... 4 more ideas.

- Color the topic box according to the topic. It will need the editing form... 

- Color the frame of the user's picture according to the topic.  

- When User select member with User Picker, system recommend the user who have related topics. 
For example: the User Picker work on Space Invitation, system recommends the user who have any topics that are same as space topics.

- The system cron extracts characteristic words from the user's profile and posts, and automatically tags the extracted words for topics. ( Automatic tagging. not only for User but also Space )

**Comment by buddh4** [comment]
The topic concept is currently only used to mark/categorize content and not users. The underlying concept is named "ContentTags" and should not be used outside of the context of content. I think we should rather to enhance user tags and design them similar to topics.

**Comment by tomofu74** [comment]
There was a proper use of tags and topics. I'm sorry I don't understand. I want to use the system more comfortably with them.
We need more information. Thank you.
