### ISSUE TITLE
Whats wrong?

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#4677]
`Could not execute queued job! Message: The command "'/usr/bin/php' '/home/brfriendss/public_html/protected/yii' 'queue/exec' '1196' '300' '1' '21770' '--color='" failed. Exit Code: 255(Unknown error) Working directory: /home/brfriendss Output: ================ Error Output: ================ PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in /home/brfriendss/public_html/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Search/QueryParser.php:262 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main} Trace:#0 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(126): yii\queue\cli\Command->handleMessage('1196', 'O:41:"humhub\\mo...', '300', 1) #1 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}('1196', 'O:41:"humhub\\mo...', '300', 1) #2 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func(Object(Closure), '1196', 'O:41:"humhub\\mo...', '300', 1) #3 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(84): yii\queue\cli\Queue->handleMessage('1196', 'O:41:"humhub\\mo...', '300', 1) #4 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure)) #5 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure)) #6 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure)) #7 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false) #8 [internal function]: yii\queue\db\Command->actionRun() #9 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #10 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #11 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('run', Array) #12 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array) #13 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array) #14 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array) #15 /home/brfriendss/public_html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #16 /home/brfriendss/public_html/protected/yii(29): yii\base\Application->run() #17 {main}`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1
| PHP version      | 7.2 
| Operating system | Cpanel

**Comment by ArchBlood** [comment]
Use `which php` to find the right path to PHP

**Comment by luke-** [comment]
seems to be the PHP Version
