### ISSUE TITLE
Markdown library doesn't removes the title attribute in the URL of the link

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4684]
### What steps will reproduce the problem?

```
echo \humhub\widgets\MarkdownView::widget([
    'markdown' => 'Text [link name](https://www.humhub.com/ "my title")',
]);
```

Note : title value can be set with the rich text editor using the link button.

### What is the expected result?

```
Text <a href="https://www.humhub.com/" title="my title" target="_blank">link name</a>
```

### What do you get instead?

```
Text <a href="https://www.humhub.com/%20" target="_blank" rel="noreferrer noopener">link name</a>
```

So the URL is `https://www.humhub.com/ &quot;my title&quot;` instead of `https://www.humhub.com/`

### Additional info 1

This title should be removed by https://github.com/humhub/humhub/blob/master/protected/humhub/libs/Markdown.php#L94 `parseLinkOrImage` function.
But the `$pattern` doesn't found the title.

### Additional info 2

If I use:
```
echo \humhub\modules\content\widgets\richtext\RichText::widget(['text' => 'Text [link name](https://humhub.com/ "my title")', 'minimal' => true]);
```
Then the URL is correct, the title attribute has been removed completly.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1

**Comment by buddh4** [comment]
Did you try `RichText::output($markdown)`? Is there a reason you only want to parse plain markdown? The `MarkdownView` widget seems rather deprecated, but nonetheless it should work properly.

**Comment by funkycram** [comment]
Yes, I need it for emails. Humhub sends emails without formatting (see https://github.com/humhub/humhub/issues/3478) but I need formatting for some modules.
If `MarkdownView` will be deprecated, `\humhub\widgets\MarkdownView` should not. And this code has the same problem:
```
echo \humhub\widgets\MarkdownView::widget([
    'markdown' => 'Text [link name](https://www.humhub.com/ "my title")',
]);
```

**Comment by funkycram** [comment]
Other bug related:
```
echo \humhub\widgets\MarkdownView::widget([
    'markdown' => '[link name](https://www.humhub.com/ "my title")',
]);
```
Renders `<a href="https://www.humhub.com/%20" target="_blank" rel="noreferrer noopener">link name</a>`

And if no slash at the end of the URL
```
echo \humhub\widgets\MarkdownView::widget([
    'markdown' => '[link name](https://www.humhub.com "my title")',
]);
```
Renders `<a target="_blank" rel="noreferrer noopener">link name</a>`

**Comment by buddh4** [comment]
@funkycram as I said I'am currently reworking the richtext in order to convert to different formats as plain markdown (without richtext features) and simple html for HumHub 1.8. Currently the MarkdownView is not able to translate special richtext features as file links or mentionings or oembeds so this will create invalid links for your emails.

**Comment by funkycram** [comment]
Perfect !
However, I have find a widget that work correctly with title attributes:
```
echo (new \humhub\modules\content\widgets\richtext\PreviewMarkdown)->parse('Text [link name](https://www.humhub.com/ "my title")');
```

It is quite a mess with all theses different widgets to render Markdown, glad to here you're working on making this better for HH1.8, thanks !

**Comment by funkycram** [comment]
If it can help you for the Markdown to HTML converter for HH1.8, I share my code that now works quite well (basic, not in a class, just to understand how it works):
```
use humhub\libs\EmojiMap;

$markdownCode = 'Text [link name](https://www.humhub.com/ "my title") '."\n".' <text to keep> :smiley:';
// From https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php#L193
$markdownCode = preg_replace('/\\\\(\n|\r){1,2}/',  ' ', $markdownCode);
// Replace < and > with temporary sentences (as Markdown hasn't HTML tags)
$markdownCode = str_replace(['<', '>'], ['LOWER_CHAR', 'UPPER_CHAR'], $markdownCode);
$markdownCode = (new \humhub\modules\content\widgets\richtext\PreviewMarkdown)->parse($markdownCode);
// Replace temporary sentences with < and > in HTML format
$markdownCode = str_replace(['LOWER_CHAR', 'UPPER_CHAR'], ['&lt;', '&gt;'],$markdownCode);
// Add <br>
$markdownCode = nl2br($markdownCode);
// Convert emojis
$markdownCode = toUTF8Emoji($markdownCode);
echo $markdownCode;

// From https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php#L199
function toUTF8Emoji($text)
{
    // Note the ; was used in the legacy editor
    return preg_replace_callback('/[:|;](([A-Za-z0-9])+)[:|;]/', function($match)  {
        $result =  $match[0];

        if(isset($match[1])) {
            $result = array_key_exists(strtolower($match[1]), EmojiMap::MAP) ?  EmojiMap::MAP[strtolower($match[1])] : $result;
        }

        return $result;
    }, $text);
}
```

**Comment by buddh4** [comment]
@funkycram thanks for the feedback and code, yes all the different markdown widgets are a mess, I think we can heavily improve this in 1.8 and deprecate the old widgets.

**Comment by buddh4** [comment]
I'll close this for now `MarkdownView` will probably be deprecated in 1.8
