### ISSUE TITLE
Markdown rendering with RichText widget

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4685]
### What steps will reproduce the problem?

```
echo \humhub\modules\content\widgets\richtext\RichText::widget(['text' => 'Text [link](https://humhub.com/)', 'minimal' => true]);
echo \humhub\modules\content\widgets\richtext\RichText::widget(['text' => 'Texte [link](https://humhub.com/)', 'minimal' => true]);
```

Renders:
```
Text link<p>Texte</p>
<p>Texte <a href="https://humhub.com/" target="_blank">link</a></p>
```

### Additional info

If I create a new post in a space containing `Texte [link](https://humhub.com/)`
![image](https://user-images.githubusercontent.com/23310825/100980401-782a8480-3545-11eb-8b76-4fae68ba64ba.png)

When I save the post, it doesn't display on the wall stream.

Could be related to https://github.com/humhub/humhub/issues/4684

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1

**Comment by funkycram** [comment]
Edit: it seems that the problem occurs for any text starting with `Texte`.

**Comment by buddh4** [comment]
I got other results:

`RichText::widget(['text' => 'Text [link](https://humhub.com/)', 'minimal' => true])`: Text link
`RichText::widget(['text' => 'Texte [link](https://humhub.com/)', 'minimal' => true])`: Texte link

The `minimal` output currently just returns a plain text version of the richtext.

**Comment by funkycram** [comment]
Try:
```
echo \humhub\modules\content\widgets\richtext\RichText::widget(['text' => 'Texte [link](https://humhub.com/)', 'minimal' => true]);
exit;
```
And then open your source code of the page on your browser.

And try also to create a post containing `Texte [link](https://humhub.com/)` as shown on the screenshot

**Comment by buddh4** [comment]
![grafik](https://user-images.githubusercontent.com/9800854/100996289-2a1f7c00-3559-11eb-8a87-e14c6e9d95f3.png)

Can you debug into the richtext call and check which richtext implementation is used?

**Comment by funkycram** [comment]
Very sorry, it is caused by a mistake of myself (because of tests with https://github.com/humhub/humhub/issues/4684)...
