### ISSUE TITLE
segments_18k' is not readable.'

### ISSUE THREAD

**Issue by farias06** [humhub/humhub#4687]
### What steps will reproduce the problem?

Cron not work since last update :

root@my:~# /usr/bin/php /var/www/humhub/protected/yii cron/run 
Optimizing search index...Exception 'ZendSearch\Lucene\Exception\InvalidArgumentException' with message 'File '/media/usbdisk-1/humhub/protected/runtime/searchdb/segments_18k' is not readable.'

in /media/usbdisk-1/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Storage/File/Filesystem.php:46

Stack trace:
#0 /media/usbdisk-1/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Storage/Directory/Filesystem.php(354): ZendSearch\Lucene\Storage\File\Filesystem->__construct('/media/usbdisk-...')
#1 /media/usbdisk-1/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index.php(279): ZendSearch\Lucene\Storage\Directory\Filesystem->getFileObject('segments_18k')
#2 /media/usbdisk-1/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index.php(434): ZendSearch\Lucene\Index->_readSegmentsFile()
#3 /media/usbdisk-1/humhub/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Lucene.php(68): ZendSearch\Lucene\Index->__construct('/media/usbdisk-...', false)
#4 /media/usbdisk-1/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php(350): ZendSearch\Lucene\Lucene::open('/media/usbdisk-...')
#5 /media/usbdisk-1/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php(332): humhub\modules\search\engine\ZendLuceneSearch->getIndex()
#6 /media/usbdisk-1/humhub/protected/humhub/modules/search/Events.php(34): humhub\modules\search\engine\ZendLuceneSearch->optimize()
#7 [internal function]: humhub\modules\search\Events::onHourlyCron(Object(yii\base\Event))
#8 /media/usbdisk-1/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event))
#9 /media/usbdisk-1/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\commands...', 'hourly', Object(yii\base\Event))
#10 /media/usbdisk-1/humhub/protected/humhub/commands/CronController.php(102): yii\base\Component->trigger('hourly')
#11 /media/usbdisk-1/humhub/protected/humhub/commands/CronController.php(54): humhub\commands\CronController->runHourly()
#12 [internal function]: humhub\commands\CronController->actionRun()
#13 /media/usbdisk-1/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /media/usbdisk-1/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#15 /media/usbdisk-1/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('run', Array)
#16 /media/usbdisk-1/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array)
#17 /media/usbdisk-1/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('cron/run', Array)
#18 /media/usbdisk-1/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('cron/run', Array)
#19 /media/usbdisk-1/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#20 /media/usbdisk-1/humhub/protected/yii(29): yii\base\Application->run()
#21 {main}

root@my:~# ls -l /media/usbdisk-1/humhub/protected/runtime/searchdb/*
-rw-rw-rw- 1 www-data www-data  0 déc.   3 10:51 /media/usbdisk-1/humhub/protected/runtime/searchdb/optimization.lock.file
-rw-rw-rw- 1 www-data www-data  0 déc.   3 20:17 /media/usbdisk-1/humhub/protected/runtime/searchdb/read.lock.file
-rw-rw-rw- 1 www-data www-data  0 déc.   3 10:51 /media/usbdisk-1/humhub/protected/runtime/searchdb/read-lock-processing.lock.file
-rw-rw-rw- 1 root     root      0 déc.   3 10:51 /media/usbdisk-1/humhub/protected/runtime/searchdb/segments_18m
-rw-rw-rw- 1 www-data www-data 20 déc.   3 10:51 /media/usbdisk-1/humhub/protected/runtime/searchdb/segments.gen
-rw-rw-rw- 1 root     root      0 déc.   3 10:51 /media/usbdisk-1/humhub/protected/runtime/searchdb/_wj.cfs
-rw-rw-rw- 1 www-data www-data  0 déc.   3 10:51 /media/usbdisk-1/humhub/protected/runtime/searchdb/write.lock.file

root@my:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

root@my:~# php --version
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

### What is the expected result?

No Crash 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1
| PHP version      | 7.3.19-1~deb10u1 
| Operating system | Debian GNU/Linux 10 (buster)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Can you try to rebuild the search index: https://docs.humhub.org/docs/admin/search#index-rebuilding

**Comment by farias06** [comment]
Perfect, issue fix.
root@my:~# /usr/bin/php /var/www/humhub/protected/yii search/rebuild
Rebuild search index: ..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................OK!

root@my:~# /usr/bin/php /var/www/humhub/protected/yii queue/run
root@my:~# /usr/bin/php /var/www/humhub/protected/yii cron/run 

I have a stupid question, the best it's to rebuild every month ?

Thanks.

**Comment by luke-** [comment]
Normally it should not be necessary, but it is also no problem to execute the command regularly.

**Comment by ArchBlood** [comment]
Just to put this out there, @GreenMeteor members found this module on GitHub relating to the search rebuild, probably something to look into as well if you have or expect to have a large community, also probably needs updated as well

https://github.com/Themroc/humhub_index-hourly
