### ISSUE TITLE
module_backups Errors After Manual Upgrade

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#4690]
### What steps will reproduce the problem?

I follow the instructions for Upgrading Manually at https://docs.humhub.org/docs/admin/updating/

### What is the expected result?

Everything goes well.

### What do you get instead?

Between versions, I get a log full of cron errors about trying to delete subdirectories in protected/runtime/module_backups.

### Additional info

I looked a little deeper after updating from 1.7.0 to 1.7.1 and found that subdirectories of module_backups and files inside module_downloads are created as root:root by the migration script, even though I unpack everything as root:www-data.  This means the www-data account will not have the expected permissions.

At the same time, it looks as though everything under protected/modules/gallery is still owned by root:www-data even after the migration.

I suggest either looking for a way to make file ownership more consistent, or consider changing the manual upgrade instructions to run module/update-all as the web server rather than admin.

**Comment by buddh4** [comment]
@luke- can you have a look?

**Comment by luke-** [comment]
@miqrogroove Did you ran the step "Fix permissions" described here https://docs.humhub.org/docs/admin/updating/#upgrade-manually ?

If you follow this step and the cron user is also www-data, there should not be any problems with the permissions.

**Comment by miqrogroove** [comment]
Maybe I'm just doing that step in the wrong order, before the migration rather than after.  I will check it tonight.

**Comment by miqrogroove** [comment]
I will set permissions both before and after running the migration script in the future.
