### ISSUE TITLE
attached image previews are cropped to one shape, missing parts of the image after upgrade from 1.6.3 to 1.7.1

### ISSUE THREAD

**Issue by zogith** [humhub/humhub#4691]
### What steps will reproduce the problem?

After upgrading from 1.6.3 to 1.7.1 uploaded images with a narrow aspect ratio display with the top and bottom cropped. I'm quite sure this was not the case on 1.6.3 and other users of the site have mentioned the embedded images in posts missing parts, for example a picture of a car missing the wheels when it didn't before.
If this is configurable to get the previous behavior info on how to re-enable would be great.

This occurs with the new image rescaling module enabled or disabled according to https://docs.humhub.org/docs/admin/uploads

### What is the expected result?

The embedded thumbnail/preview image for attached images to show the whole image, as it did before, for example with this test image I would see all the text in the preview when uploaded to humhub:

![Screenshot_2020-12-05_12-17-45](https://user-images.githubusercontent.com/7069599/101269595-9fdb5000-37c4-11eb-8325-1e2bd86bb3a9.png)

### What do you get instead?

![Screenshot_2020-12-06_13-12-26](https://user-images.githubusercontent.com/7069599/101269602-b97c9780-37c4-11eb-84ae-81aa13b0a55c.png)

see example on https://community.humhub.com/ at https://community.humhub.com/content/perma?id=231015

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1
| PHP version       |  7.3.23-4+
| Operating system | Debian Linux
Also occurs on https://community.humhub.com/ so easy to view

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
No errors
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
See here for the parameters that you're looking for;
https://github.com/humhub/humhub/blob/fcb8e0c924f33a37d0e953919f6edaea2684bdf1/protected/humhub/modules/file/Module.php#L80-L90

**Comment by ArchBlood** [comment]
In addition to the report @luke- I noticed that in `https://website.com/admin/setting/file` the options to do this in the admin panel was removed?

**Comment by buddh4** [comment]
The previews of attached images in 1.7 use a `object-fit: cover` style in order to allow a image grid with equal image sizes. You can either align the style in your theme or embed images within the richtext for rendering images in other formats.

**Comment by zogith** [comment]
thanks @buddh4  I was able to get the previous behaviour back by changing

  “object-fit:cover” to “object-fit:contain” in the file themes/HumHub/css/theme.css

**Comment by buddh4** [comment]
@zogith You should rather use a [custom theme](https://docs.humhub.org/docs/theme/overview) for such changes, otherwise the change will be overwritten with the next update.
