### ISSUE TITLE
Hide button to add new space

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub#4692]
### What steps will reproduce the problem?

Set permissions for a group:
- Manage Space: Allow
- Create private space: Deny
- Create public space: Deny

Go to admin menu to manage spaces `/admin/space` by a user of the group,
Click to green button "+ Add new space"

### What is the expected result?

I think the green button must be hidden.

### What do you get instead?

An unexpected error with a message: "You are not allowed to create spaces!"

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.0

<img width="996" alt="create_space_issue" src="https://user-images.githubusercontent.com/6995524/101323016-0f127c00-3879-11eb-9d8d-c62ea28ff2f7.png">

**Comment by luke-** [comment]
Yes, we should hide this button.
@yurabakhtin Can you please create a PR for it?

**Comment by yurabakhtin** [comment]
@luke- done https://github.com/humhub/humhub/pull/4694/commits/d923afd05c24da0bbf8104b424ca6c8d28c2b544
