### ISSUE TITLE
Marketplace: Possibility to prohibit modules via the configuration

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4706]
### Is your feature request related to a problem? Please describe.

In some cases it is useful to hide some modules. e.g. The Updater Module on managed environments. 

### Describe the solution you'd like

Add new attribute in marketplace module.

### Describe alternatives you've considered

-

**Comment by buddh4** [comment]
Maybe an option to lock an already installed module would be nice e.g. if you have a forked module version and you don't want marketplace updates. Not sure if this is covered by this feature request.

**Comment by luke-** [comment]
@buddh4 

This is already possible. Marketplace features like (Update/Uninstall) are only possible for modules that are located in this path:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/marketplace/Module.php#L42

All other module autoloader paths are locked for the marketplace.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/pull/4761
