### ISSUE TITLE
Search function gives error

### ISSUE THREAD

**Issue by GertuZz** [humhub/humhub#4707]
On version 1.7.1 clicking on the search function gives the following error:

TypeError
Return value of ZendSearch\Lucene\AbstractFSM::addState() must be an instance of ZendSearch\Lucene\void, none returned

**Comment by luke-** [comment]
Can you please try to rebuild the search index?

https://docs.humhub.org/docs/admin/search#index-rebuilding

**Comment by GertuZz** [comment]
Rebuilding the search index unfortunately gives the same error in CLI.

**Comment by luke-** [comment]
Can you try to the delete the folder: protected/runtime/searchdb - and try it again?
Can you please post the CLI result?

**Comment by GertuZz** [comment]
The folder searchdb is not present. After rebuilding the search index (php yii search/rebuild) the folder is there, but the process gives me the following error:

**Rebuild search index: Exception 'TypeError' with message 'Return value of ZendSe                                                                                                                                                             arch\Lucene\AbstractFSM::addState() must be an instance of ZendSearch\Lucene\voi                                                                                                                                                             d, none returned'**

**in /var/www/html3/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene                                                                                                                                                             /AbstractFSM.php:159**

Stack trace:
#0 /var/www/html3/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene                                                                                                                                                             /AbstractFSM.php(141): ZendSearch\Lucene\AbstractFSM->addState(0)
#1 /var/www/html3/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene                                                                                                                                                             /AbstractFSM.php(126): ZendSearch\Lucene\AbstractFSM->addStates(Array)
#2 /var/www/html3/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene                                                                                                                                                             /Search/QueryParser.php(167): ZendSearch\Lucene\AbstractFSM->__construct(Array,                                                                                                                                                              Array)
#3 /var/www/html3/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene                                                                                                                                                             /Search/QueryParser.php(250): ZendSearch\Lucene\Search\QueryParser->__construct(                                                                                                                                                             )
#4 /var/www/html3/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene                                                                                                                                                             /Search/QueryParser.php(264): ZendSearch\Lucene\Search\QueryParser::_getInstance                                                                                                                                                             ()
#5 /var/www/html3/protected/humhub/modules/search/engine/ZendLuceneSearch.php(34                                                                                                                                                             3): ZendSearch\Lucene\Search\QueryParser::setDefaultEncoding('utf-8')
#6 /var/www/html3/protected/humhub/modules/search/engine/ZendLuceneSearch.php(73                                                                                                                                                             ): humhub\modules\search\engine\ZendLuceneSearch->getIndex()
#7 /var/www/html3/protected/humhub/modules/space/Events.php(35): humhub\modules\                                                                                                                                                             search\engine\ZendLuceneSearch->add(Object(humhub\modules\space\models\Space))
#8 [internal function]: humhub\modules\space\Events::onSearchRebuild(Object(yii\                                                                                                                                                             base\Event))
#9 /var/www/html3/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_f                                                                                                                                                             unc(Array, Object(yii\base\Event))
#10 /var/www/html3/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\ba                                                                                                                                                             se\Event::trigger('humhub\\modules\\...', 'onRebuild', Object(yii\base\Event))
#11 /var/www/html3/protected/humhub/modules/search/engine/Search.php(97): yii\ba                                                                                                                                                             se\Component->trigger('onRebuild')
#12 /var/www/html3/protected/humhub/modules/search/commands/SearchController.php                                                                                                                                                             (39): humhub\modules\search\engine\Search->rebuild()
#13 [internal function]: humhub\modules\search\commands\SearchController->action                                                                                                                                                             Rebuild()
#14 /var/www/html3/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call                                                                                                                                                             _user_func_array(Array, Array)
#15 /var/www/html3/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\b                                                                                                                                                             ase\InlineAction->runWithParams(Array)
#16 /var/www/html3/protected/vendor/yiisoft/yii2/console/Controller.php(179): yi                                                                                                                                                             i\base\Controller->runAction('rebuild', Array)
#17 /var/www/html3/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\conso                                                                                                                                                             le\Controller->runAction('rebuild', Array)
#18 /var/www/html3/protected/vendor/yiisoft/yii2/console/Application.php(180): y                                                                                                                                                             ii\base\Module->runAction('search/rebuild', Array)
#19 /var/www/html3/protected/vendor/yiisoft/yii2/console/Application.php(147): y                                                                                                                                                             ii\console\Application->runAction('search/rebuild', Array)
#20 /var/www/html3/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\                                                                                                                                                             console\Application->handleRequest(Object(yii\console\Request))
#21 /var/www/html3/protected/yii(29): yii\base\Application->run()
#22 {main}

**Comment by luke-** [comment]
Please check your PHP Version. https://docs.humhub.org/docs/admin/requirements

**Comment by GertuZz** [comment]
That did the trick! Thank you!
