### ISSUE TITLE
Youtube oembed not working

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4714]
Not sure if this is related with the recent youtube outage or if this is a permanent change on youtube side, but oembed requests to `http` instead of  `https` are blocked by:

![grafik](https://user-images.githubusercontent.com/9800854/102242001-e3873580-3ef9-11eb-9b1e-6c6516e3a022.png)

Changing to https fixes the issue:

![grafik](https://user-images.githubusercontent.com/9800854/102241944-d36f5600-3ef9-11eb-8d8d-24b4f963e127.png)

**Comment by luke-** [comment]
We should make sure that all OEmbed endpoints use HTTPS anyway. 

A bug fix should correct the existing URL values.

**Comment by yurabakhtin** [comment]
@luke- @buddh4 please check PR https://github.com/humhub/humhub/pull/4721:
- in the first commit I fixed the sample endpoints to use HTTPS,
- in the second commit I create a migration to update ONLY sample endpoints to HTTPS if they still use HTTP.

**Comment by yurabakhtin** [comment]
@luke- PR for `master` branch - https://github.com/humhub/humhub/pull/4723

**Comment by yurabakhtin** [comment]
@luke- Why did you reopen this issue?

**Comment by luke-** [comment]
@yurabakhtin Yes, but it seems to affect only our SaaS hosting, due to a  a prebuild database.
