### ISSUE TITLE
Content::canArchive() broken on global content

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4715]
Calling `$content->canArchive()` on a global content fails, duo to:

```
public function canArchive()
{
   return $this->getContainer()->permissionManager->can(new ManageContent());
}
```

This for example happens when generating archive links for global custom page wall entries.

**Comment by luke-** [comment]
It should not be possible to archive global content at the moment, right?

**Comment by buddh4** [comment]
Its not since the check fails, but I do not see an issue with archived global content in general. [Here](https://community.humhub.com/content/perma?id=232000) is the related issue from the community.

**Comment by luke-** [comment]
Ok, then we would have to link the permission to archive global content with the edit permission?
@buddh4 Can you take care of this, please?

**Comment by buddh4** [comment]
Yes, we could use a global permission in combination with canEdit()? The user group needs to be allowed to archive content + the user needs to be able to edit the content.
