### ISSUE TITLE
Comment widget renders gap between comments

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4716]
This seems only to happen outside of the stream, e.g. in the task module. In the stream the comment-container of nested comments is hidden by `display:none`.

![grafik](https://user-images.githubusercontent.com/9800854/102395274-31279f00-3fdb-11eb-99b7-3901045c679d.png)

**Comment by yurabakhtin** [comment]
@buddh4 PR https://github.com/humhub/humhub-modules-tasks/pull/136

**Comment by luke-** [comment]
I could not reproduce the problem with other modules (Calendar, Wiki, Files). 

@yurabakhtin The fix works fine for me!
