### ISSUE TITLE
Misalignment in banner menu and content

### ISSUE THREAD

**Issue by olantrust** [humhub/humhub#4717]
### What steps will reproduce the problem?

Open either a space or user profile and view the alignment of different sections

### What is the expected result?

The header, banner, any vertical menus, and content will align on all sides.

### What do you get instead?

The header, banner and content do not align correctly on the right hand side. 

As can be seen in the attached screenshots.

This includes the menu if the window is small and the vertical menu is transformed to a horizontal menu. But it also includes the header and content.

It occurs in personal profile and users spaces (but not dashboard).

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | Version: 1.7.1
| PHP version      | 
| Operating system | Server Ubuntu 20.04

**Comment by buddh4** [comment]
Do you use a custom theme?

**Comment by olantrust** [comment]
> Do you use a custom theme?

Using standard Humhub theme.
Uploading screenshots now.

**Comment by olantrust** [comment]
https://drive.google.com/file/d/157ShCfYatwUSuR4IIKNENBExgrikwrzL/view?usp=sharing

https://drive.google.com/file/d/1a4m4dM1W_6jNGuKvm4FDdI-whUMvpKu3/view?usp=sharing

**Comment by buddh4** [comment]
Ok, seems only to happen for a certain media query.
