### ISSUE TITLE
Spaced or profile banner smaller if edited then if uploaded without edit

### ISSUE THREAD

**Issue by olantrust** [humhub/humhub#4718]
### What steps will reproduce the problem?

Upload a photo as a banner to a space or user profile, note the height
Edit the area of the photo selected (using the fixed proportion selector within Humhub), save, note the height

### What is the expected result?

That the banner size (and ratio) stays the same.

### What do you get instead?

The banner when uploading a new photo is always taller then after editing the photo, no matter what changes were made to the edit.

### Additional info

Not a major problem, but does result in inconsistent appearance - on both small and large devices.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1
| PHP version      |  
| Operating system |

**Comment by buddh4** [comment]
You mean when cropping an image, the result does not match the crop selection?

**Comment by luke-** [comment]
Uploaded files will be converted to 192px height, cropped parts to 180px height.

**Comment by yurabakhtin** [comment]
@luke- sorry, but I don't find any issue there:
<img width="1659" alt="test_image_upload_crop" src="https://user-images.githubusercontent.com/6995524/102611332-c17ef480-413f-11eb-953a-7331193f9c9c.png">

**Comment by luke-** [comment]
Steps to reproduce:

1. Upload a photo image as banner.

![image](https://user-images.githubusercontent.com/4736168/102643185-2dbd2080-415f-11eb-9b62-3aa9d7b08ded.png)

2. The image will be automatically resized to a max. height of 192px. (see screenshot)

3. Edit the uploaded image, and select a part of the image

![image](https://user-images.githubusercontent.com/4736168/102643395-7ecd1480-415f-11eb-82ed-9a105ba53a9e.png)

And save:

![image](https://user-images.githubusercontent.com/4736168/102643360-72e15280-415f-11eb-9665-f74c36d6af2f.png)

The part of the image will be converted to a max. height of 180px.

I am not sure if this behaviour is a problem at all. It is just strange that different sizes are used here.

**Comment by olantrust** [comment]
> Steps to reproduce:
> 
>     1. Upload a photo image as banner.

>     1. The image will be automatically resized to a max. height of 192px. (see screenshot)
> 
>     2. Edit the uploaded image, and select a part of the image
> 
> And save:
> The part of the image will be converted to a max. height of 180px.

Exactly. The profile pic's are fine, simple squares. The banners have two different sizes.

> I am not sure if this behaviour is a problem at all. It is just strange that different sizes are used here.

Indeed it's not a huge problem, but I would suggest it is still a problem; I and others noticed it immediately, and visually it's at least disconcerting when the banner size changes, feels less professional or smooth.

If it can be fixed, it seems advisable.

**Comment by yurabakhtin** [comment]
@luke- Thank you for the details, I made to use same sizes in all places from the values https://github.com/humhub/humhub/blob/fix/4718-spaced-or-profile-banner-sizes-after-edit/protected/humhub/libs/ProfileImage.php#L52-L60 and https://github.com/humhub/humhub/blob/fix/4718-spaced-or-profile-banner-sizes-after-edit/protected/humhub/libs/ProfileBannerImage.php#L32-L40.
PR https://github.com/humhub/humhub/pull/4733.

**Comment by luke-** [comment]
Thanks, look fine. Will be merged in 1.8
