### ISSUE TITLE
Unknown property: humhub\modules\user\models\Group::notify_users

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub#4720]
### What steps will reproduce the problem?

Fresh install https://github.com/humhub/humhub/tree/develop on new empty DB.

### What is the expected result?

Success install.

### What do you get instead?

`Getting unknown property: humhub\modules\user\models\Group::notify_users`

<img width="1677" alt="intall_bug_notify_users" src="https://user-images.githubusercontent.com/6995524/102453389-2e659200-404d-11eb-897b-e08622c5cac7.png">

### Additional info

I guess a Group is created during install but it has no the column `notify_users` yet because it will be added recently in separate migration in this PR https://github.com/humhub/humhub/pull/4643/files#diff-ef33c0fdf0e30eb6eb1ebbf7cfc5f88141b8639639cb49dad6b180b33d12ddb9R15

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8

**Comment by yurabakhtin** [comment]
After refreshing the page I could go to next step to set up data like admin login/pass and etc., but on a step to install sample data I caught another error(see screenshot below), however after refreshing the page I could finish the installation successfully and site looks works well.

<img width="1518" alt="bug_create_sample_data" src="https://user-images.githubusercontent.com/6995524/102454739-8a311a80-404f-11eb-98cc-ecf3ac5e077e.png">

**Comment by luke-** [comment]
@yurabakhtin  You may run the migrations `yii migrate/up --includeModuleMigrations=1`  if you switch from master -> devleop branch.
