### ISSUE TITLE
Youtube OEmbed not rendering

### ISSUE THREAD

**Issue by kenthejr** [humhub/humhub#4737]
### What steps will reproduce the problem?
Paste a YouTube link into a Post.

### What is the expected result?
Expected the YouTube video to render.

### What do you get instead?
No video render, only the link.

### Additional info
Two points that have me curious:

- Vimeo links still render, so I don't think it has to do with my client or the OEmbed function itself.
- An old YouTube video that I pasted 6 months ago still is showing as rendered, it's just the new links that aren't rendering. 

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1
| PHP version      | 7.3.19-1~deb10u1
| Operating system | Debian

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
Go into the oEmbed providers from the admin panel then update it so that the provider link is `https` not `http`

**Comment by kenthejr** [comment]
Oh my. That was too easy.
