### ISSUE TITLE
Tracker issues

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4739]
Tracker issues it works incorrectly!

Не корректно работает CMS и не корректно работает Модуль после установки и активации 
CMS does not correctly work and the module does not correctly work after installation and activation

![изображение](https://user-images.githubusercontent.com/36643871/103152334-ab9caf80-478f-11eb-80e7-6b14c5c17844.png)

![изображение](https://user-images.githubusercontent.com/36643871/103152409-544b0f00-4790-11eb-8477-38567b76999a.png)

![изображение](https://user-images.githubusercontent.com/36643871/103152422-76dd2800-4790-11eb-9839-b7491db1acdb.png)

И не сохраняются Tracker
And do not persist Tracker

![изображение](https://user-images.githubusercontent.com/36643871/103152449-c6bbef00-4790-11eb-9726-c0308723ad84.png)

Не сохраняются !
Do not persist!

И в сообществе нет
And there is no community

**Comment by luke-** [comment]
Please create an issue here: 
https://github.com/githubjeka/tracker-issues
