### ISSUE TITLE
Bug on saving a group without Default Space

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub#4740]
### What steps will reproduce the problem?

- Open any group edit form by admin
- Remove all Default Space(s)
- Save
- Error: `Invalid argument supplied for foreach()` on Line 55 of the file `/protected/humhub/modules/user/models/forms/EditGroupForm.php` because there is `$this->defaultSpaceGuid` is empty string instead of expecting array.

### What is the expected result?

Group should be either allowed to store without Default Space or the field should be required.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8

**Comment by luke-** [comment]
@yurabakhtin Can you please fix this?

**Comment by yurabakhtin** [comment]
@luke- Done in PR https://github.com/humhub/humhub/pull/4741.

**Comment by luke-** [comment]
Thanks!
