### ISSUE TITLE
Banner image orientation not being processed

### ISSUE THREAD

**Issue by samsheridan** [humhub/humhub#4744]
### What steps will reproduce the problem?
Upload a space banner image with EXIF orientation data.

### What is the expected result?
A banner image with proper orientation.

### What do you get instead?
An upside down banner image.

### Additional info
`protected/humhub/libs/ProfileBannerImage.php` does not call `ImageHelper::fixJpegOrientation` like `protected/humhub/libs/ProfileImage.php` does. A quick change to that code seems to have resolved it with no side effects.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1
| PHP version      | 7.4
| Operating system | Fedora 32

**Comment by luke-** [comment]
Thanks for the commit, looks fine!
 Would you also like to create a PR for it or should I do that?
