### ISSUE TITLE
Get "You're not registered" when trying to login using social oauth (LinkedIn & Google) after trying to login with a previously created user by admin

### ISSUE THREAD

**Issue by superseby2** [humhub/humhub#4748]
I know, it has to be me as I could not find any related issue regarding my problem. 

I am trying to login with a user I created previously using the admin section, with LinkedIN or Google but the account on Humhub is not found while I am sure the email address is the same. 

To setup oauth I followed : https://docs.humhub.org/docs/admin/authentication

### What steps will reproduce the problem?

- The admin user creates a new user
- The new user has an email / fistname / lastname and is enabled

- The code needed in config/common.php is there for both Google and LinkedIN auth

### What is the expected result?

- The user which logs in using one of the 2 Oauth is loggedin
- 

### What do you get instead?

When registration for anonymous user is NOT ON :

I have this Flash message : 

        You're not registered.

When registration for anonymous user is ON : 

I have this Flash message : 
   User with the same email already exists but isn\'t linked to you. Login using your email first to link it.

### Additional info

- Registered user's email is realy the same as the one for the 2 social accounts.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1
| PHP version      |  7.3
| Operating system | LINUX

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by superseby2** [comment]
Ok just found out that you need to "connect your account"   here : 

> user/account/connected-accounts

I hope there is a way to do this API side ?

And thx for humhub ! Very impressive product!

**Comment by superseby2** [comment]
Found the info in DB  in the user_auth  table. 

Anyone knows if dealing with the database directly is the only way to be able to "automatically" connect an account to its auth ? 
if not, I ll have to understand how to add that entry. 

Thx again!

**Comment by superseby2** [comment]
Digging a little, I understand that a successfull oauth is when a user is found and that user  has the corresponding oauth_id. I believe, what  i am looking for is a way to make the condition : oauth is successfull when the user found has the corresponding email address. ..

**Comment by ArchBlood** [comment]
In most cases OAuths are used as a connection of service, of course there are ways of account creation as well, just to note, from my understanding the OAuths are going to be migrated into their own modules over time so that the common.php file doesn't need modified

#### Google OAuth
https://github.com/humhub-contrib/auth-google

**Comment by luke-** [comment]
@superseby2  Good point, I think there is nothing against logging the user in automatically instead of displaying the message. I have opened a new issue for this. Would it solve your problem completely?

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/4750

**Comment by superseby2** [comment]
Thx @ArchBlood for your help and the info regarding the upcoming modules.

Thx @luke. Yes! That would solve my issue and actually possibly another use-case : when someone reveives an invitation but decide to use an social auth to login(I know some tweaking is to be done on the reg.form). Considering the current condition (the need to "link" your profile) this registration would fail ultimately. 

So x2 yes if changes brought by  #4750  could  be done indeed!

To be able to link your account to a social account with a different email address is great and bring flexibility, with the automatic link based on email it would make it even better. Ithink. 

Thx again !

**Comment by ArchBlood** [comment]
@luke- I believe this can be close unless @superseby2 sees any reason it should still be opened?
