### ISSUE TITLE
Hide separator between LikeLink and CommentLink

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub#4751]
Implement like described here https://github.com/humhub/humhub/pull/4747#issuecomment-752521919:

In many places we have a code like this:

```php
<?= CommentLink::widget(['object' => $comment]); ?>
&middot;
<?= LikeLink::widget(['object' => $comment]); ?>
```

we should implement similar this in order to don't show a separator `&middot;` when one of both are hidden because of no permission:

```php
<?= \humhub\widgets\BaseStack::widget([
    'widgets' => [
        [
            CommentLink::class, ['object' => $comment], ['sortOrder' => 100],
            LikeLink::class, ['object' => $comment], ['sortOrder' => 200]
        ]
    ]
]);
```

> But instead of using the BaseStack class directly, it would be good to create a new one like CommentEntryControls.

Do this as PR for `develop` branch.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4772

You wrote here https://github.com/humhub/humhub/pull/4747#issuecomment-752406182:

> But instead of using the `BaseStack` class directly, it would be good to create a new one like `CommentEntryControls`.

I did this, but please note I could use new `CommentEntryControls` only in a single place of core code, but others similar places where we should use it are located in external modules: `cfiles`, `gallery`, `linklist`, `wiki` and probably some others, so if we will update the modules then they will works only for humhub ver 1.8 where the new class `CommentEntryControls`, is it ok?
Should I create PRs for the changes in the external modules?

**Comment by luke-** [comment]
@yurabakhtin  Thanks for the PR! 

Can you send me an example of a module where this would be necessary? Actually, shouldn't they all use the Comment widget?

**Comment by yurabakhtin** [comment]
@luke- As you can see I did this replacement https://github.com/humhub/humhub/pull/4772/files#diff-2455bbf1c20e63b6c757a089044d36d3d774ea6cefe3a2a04ad1b985818824dfL92-L95.

I think similar modifications should be done in external modules:

- `cfiles`: https://github.com/humhub/humhub-modules-cfiles/blob/master/widgets/views/fileSystemItem.php#L80-L82
- `gallery`: https://github.com/humhub-contrib/gallery/blob/master/views/custom-gallery/gallery_view.php#L83-L85
- `gallery`: https://github.com/humhub-contrib/gallery/blob/master/widgets/views/galleryListEntry.php#L57
- `linklist`: https://github.com/humhub-contrib/linklist/blob/master/views/linklist/index.php#L84-L86
- `wiki`: https://github.com/humhub/humhub-modules-wiki/blob/master/views/page/view.php#L38

**Comment by luke-** [comment]
@yurabakhtin Ah ok, I would create a new widget (basically same as CommentEntryControls) for these cases, maybe somehow "humhub/modules/content/widget/ContentControls". 

What do you think about that?

**Comment by yurabakhtin** [comment]
@luke- As you can see new created class `CommentEntryControls` has only default separator - https://github.com/humhub/humhub/pull/4772/files#diff-6ec7ab6693e86ee62ab4dd4f69c09f8f7aba3172494701e96ea0d50605f42e3cR20, but really we can override this value from file by passing param `CommentEntryControls::widget(['seperator' => ' - '])`, so currently I don't see a reason to keep even the `CommentEntryControls` but it seems you prefer this only to have more clear class name instead of `BaseStack` and if you need same for all other contents then yes we can create similar with name `ContentControls`.

**Comment by luke-** [comment]
@yurabakhtin  The main reason for a separate class(es) for me is the possibility that modules can then add their own entries via events.

If a developer wants to add another option (e.g. Dislike), he can decide where via events:

- WallEntryControls (Add Inside the Stream/Wall)
- ContentControls (Add also outside the Stream/Wall)
- CommentEntryControls (Add also for comments)

However, similar to the WallEntryControls, we should probably also introduce an attribute `object` for the new classes, so that there is then access to the respective object/comment.

**Comment by yurabakhtin** [comment]
@luke- Ok, I got the reason.

> However, similar to the WallEntryControls, we should probably also introduce an attribute `object` for the new classes, so that there is then access to the respective object/comment.

It seems you mean `WallEntryAddons` instead of `WallEntryControls` because it is extended from `BaseStack`.

**Comment by luke-** [comment]
@yurabakhtin That's right, `WallEntryControls` is wrong. The class `WallEntryLinks` should be the right one.
(It's the first WallEntryAddon - unfortunately it's all a bit nested.)

Injectd here: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/Events.php#L97
(Maybe we should also include the `seperator` & `template` directly in the class.)

- WallEntryLinks (Add Inside the Stream/Wall)
- **ContentObjectLinks** (Add also outside the Stream/Wall)
- **CommentEntryLinks** (Add also for comments)

Then we should also name the new classes according to the "Links" scheme, what do you think of the variants?

**Comment by yurabakhtin** [comment]
@luke- 

> Injectd here: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/Events.php#L97
(Maybe we should also include the `seperator` & `template` directly in the class.)

I have moved then into the class `WallEntryLinks` here https://github.com/humhub/humhub/pull/4772/commits/9944475ccb8f1b5a35ec5fe5527aef8ab062915a

---

> However, similar to the WallEntryControls, we should probably also introduce an attribute object for the new classes, so that there is then access to the respective object/comment.
> - **CommentEntryLinks** (Add also for comments)

Commit https://github.com/humhub/humhub/pull/4772/commits/68c5ad62902b08dfc7f3c76310e8ce632bfecc1f:

- renamed `CommentEntryControls` to `CommentEntryLinks`
- created `CommentEntryLinks->object`
- call shorter code form template: `<?= CommentEntryLinks::widget(['object' => $comment]); ?>` because default widgets are initialized inside the class.

---

> - **ContentObjectLinks** (Add also outside the Stream/Wall)

Commit https://github.com/humhub/humhub/pull/4772/commits/cbb5cd07e00c91a0d2911701ec74ccfd60eef6e0:

- new class `ContentObjectLinks`

but I didn't use this in external modules yet.

For example, the code:

```php
<?= LikeLink::widget(['object' => $row->getModel()]); ?>
|
<?= CommentLink::widget(['object' => $row->getModel(), 'mode' => CommentLink::MODE_POPUP]); ?>
```

can be replaced with:

```php
<?= ContentObjectLinks::widget([
    'object' => $row->getModel(),
    'widgetParams' => [CommentLink::class => ['mode' => CommentLink::MODE_POPUP]],
]); ?>
```

If the implementation of the class `ContentObjectLinks` is correct and enough please confirm to do changes in all external modules where it is required, thanks.

**Comment by luke-** [comment]
Nice solution and I have already merged it.

 It would be good if you could prepare the module PRs!

**Comment by yurabakhtin** [comment]
@luke- 

> It would be good if you could prepare the module PRs!

I could find the use of `LikeLink::widget` and `CommentLink::widget` only in 4 external modules as you can see above.

**Comment by luke-** [comment]
@yurabakhtin Thank you! Everything is fine!

**Comment by buddh4** [comment]
Just a small note, we should become a bit more consistent with the naming of the `object` property. We use different naming for similar fields throughout the application e.g.:

- `model`
- `record`
- `object`
- ...

I kind of prefer the name `model` in such cases.
