### ISSUE TITLE
Download yields outdated file due to browser caching

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#4752]
I reported this against the onlyoffice plugin and was redirected: https://github.com/ONLYOFFICE/onlyoffice-humhub/issues/28

If a file is modified in place (i.e. the download URL does not change), you will not get the updated file on subsequent downloads due to browser caching.

### What steps will reproduce the problem?
See https://github.com/ONLYOFFICE/onlyoffice-humhub/issues/28

### Additional information
Humhub serves the file download with this header: `Cache-Control: public, max-age=3600`

### Workaround / Fix?
```diff
--- a/DownloadAction.php_bkup
+++ b/DownloadAction.php
@@ -73,7 +73,8 @@ class DownloadAction extends Action
             return true;
         }
 
-        $httpCache = new HttpCache();
+       $httpCache = new HttpCache();
+       $httpCache->cacheControlHeader = 'max-age=0, must-revalidate'; // can't rely on cache when in place editing of files can occur
         $httpCache->lastModified = function() {
             return Yii::$app->formatter->asTimestamp($this->file->updated_at);
         };

```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1
| PHP version      |  7.2.24
| Operating system | CentOS 8

**Comment by ArchBlood** [comment]
Not sure but something to look into when it comes to this issue

> ### Requiring revalidation
> `no-cache` and `max-age=0, must-revalidate` indicates same meaning.
Clients can cache a resource but must revalidate each time before using it. This means HTTP request occurs each time though, it can skip downloading HTTP body if the content is valid.

**Comment by dreua** [comment]
> Clients can cache a resource but must revalidate each time before using it.

That is exactly the behavior I'd like to see, therefore I chose this value, what exactly are you not sure about?

The only other approach I can think of would be changing the download URL each time the file changes, e.g. by appending the last changed timestamp as a parameter. (This would not be parsed on the serving side, since it only needs to indicate to the browser and possible proxy caches that this is a different file.)

(Third option: Declare file contents immutable and toss the ball back to onlyoffice plugin and possibly others.)

**Comment by dreua** [comment]
History of download caching:
- introduced in https://github.com/humhub/humhub/commit/8d02f902b056196c185a604e4e2ece6d21acf0eb
- removed in https://github.com/humhub/humhub/commit/823894656cba797c9db9a9a1ffbde1c0a6894c33#diff-1e3410e828d6d32c5a3657a8e00761416822a5394041a98af8ef80aee04c9b7e by @luke-
- re-added using HttpCache in https://github.com/humhub/humhub/commit/6dfd5c8658ffd23ac45243a01a390e27100dcffc by @luke-

**Comment by luke-** [comment]
Thank you for the detailed analysis of the problem!

To solve the problem, it would probably be best to add a part of the content SHA checksum to the file URL, for example.

This way, we could still use strong browser caching for unchanged files such as images, and the URL changes for changed documents.

It would probably be best to include the SHA checksum directly in the file table and append (part of) it here:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/models/File.php#L108

**Comment by dreua** [comment]
> Thank you for the detailed analysis of the problem!

That's the least I can do, thanks go back to everyone involved in providing Humhub as FOSS! :heart:

**Comment by yurabakhtin** [comment]
@luke- 

> It would probably be best to include the SHA checksum directly in the file table and append (part of) it here:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/models/File.php#L108

As I understand we should add a new column like `hash` into the table `file` and store there values like `88b184adea10bf987b15257a5d6c5cb94eba69d3` of result `sha1_file($filePath)` and then append part of the hash to a file URL like `file-url?hash=88b184ad`
I think to fille the new column `hash` on creating/updating file, but don't fill it on migrations for all already created files, instead we can fill it on first request when `hash` is `NULL`.

**Comment by luke-** [comment]
@yurabakhtin Ok, I like the approach.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4769
