### ISSUE TITLE
Shorten high member numbers

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4754]
### Describe the solution you'd like

It would be nice if for large spaces with many members, instead of the exact number of members in the header, there was only a rough value, as in the case of the screenshot, e.g. 13K.

![image](https://user-images.githubusercontent.com/4736168/103531401-898ae780-4e89-11eb-8365-019152161530.png)

However, this behaviour must also be translatable. There may also be a solution here from the Yii Formatter.

### Describe alternatives you've considered

-

There may be other places where such a display could make sense.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4771:
<img width="430" alt="test_high_numbers" src="https://user-images.githubusercontent.com/6995524/104293116-b1ec9480-54ce-11eb-973d-c0f42bf05213.png">
