### ISSUE TITLE
ERROR in yii\base\...

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4765]
![изображение](https://user-images.githubusercontent.com/36643871/103963539-3b643580-5162-11eb-90bd-8814e7db1df6.png)

![изображение](https://user-images.githubusercontent.com/36643871/103963570-474ff780-5162-11eb-9039-54f91b869d59.png)

![изображение](https://user-images.githubusercontent.com/36643871/103963592-559e1380-5162-11eb-8ca8-a744f8bfa307.png)

....

**Comment by andrewua85** [comment]
"for bug reports and feature requests" Just on the screenshot of the mistakes in Humhub

**Comment by andrewua85** [comment]
![изображение](https://user-images.githubusercontent.com/36643871/104024126-4dc68980-51cb-11eb-940a-3d7105093c14.png)
this is ERROR
this is ERROR
this is ERROR
That's what it is ERROR

**Comment by ArchBlood** [comment]
Just to clear this up, it's not an issue with HumHub else everyone would have it, this is more than likely something to do with your server and how it's setup, that is why it was marked the way it was, my suggestion would be go down the list of HumHub's [requirements](https://docs.humhub.org/docs/admin/requirements/) to be ran

> Note: In the future PHP 7.2 will be a requirement

**Comment by buddh4** [comment]
Seems to be an issue with your cron configurstion.

**Comment by andrewua85** [comment]
> Seems to be an issue with your cron configurstion.

Thanks It was a problem cron  ;)
