### ISSUE TITLE
Message mail and notification error

### ISSUE THREAD

**Issue by erenakkuss** [humhub/humhub#4766]
Hi 
My hosting is shared hosting that is why I cant acces console. I add verified account tick so hiw can I add it in stream and in message. I cant get any notification and when I send mail error message is :

{
    "url": "/index.php?r=mail%2Fmail%2Fcreate",
    "status": 500,
    "response": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Getting unknown property: humhub\\modules\\content\\models\\ContentContainerSetting::title&#039; \n\nin /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\\base\\Component-&gt;__get(&#039;title&#039;)\n#1 /home/interga2/antaresmedya.site/protected/vendor/yiisof...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Getting unknown property: humhub\\modules\\content\\models\\ContentContainerSetting::title&#039; \n\nin /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\\base\\Component-&gt;__get(&#039;title&#039;)\n#1 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/validators/Validator.php(258): yii\\db\\BaseActiveRecord-&gt;__get(&#039;title&#039;)\n#2 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Model.php(367): yii\\validators\\Validator-&gt;validateAttributes(Object(humhub\\modules\\content\\models\\ContentContainerSetting), Array)\n#3 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(560): yii\\base\\Model-&gt;validate(Array)\n#4 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\\db\\ActiveRecord-&gt;insert(true, NULL)\n#5 /home/interga2/antaresmedya.site/protected/humhub/libs/BaseSettingsManager.php(80): yii\\db\\BaseActiveRecord-&gt;save()\n#6 /home/interga2/antaresmedya.site/protected/modules/mail/models/Config.php(142): humhub\\libs\\BaseSettingsManager-&gt;set(&#039;conversationCou...&#039;, 1610304117)\n#7 /home/interga2/antaresmedya.site/protected/modules/mail/models/Config.php(159): humhub\\modules\\mail\\models\\Config-&gt;getConversationCount(Object(humhub\\modules\\user\\models\\User))\n#8 /home/interga2/antaresmedya.site/protected/modules/mail/models/forms/CreateMessage.php(126): humhub\\modules\\mail\\models\\Config-&gt;incrementConversationCount(Object(humhub\\modules\\user\\models\\User))\n#9 /home/interga2/antaresmedya.site/protected/modules/mail/controllers/MailController.php(318): humhub\\modules\\mail\\models\\forms\\CreateMessage-&gt;save()\n#10 [internal function]: humhub\\modules\\mail\\controllers\\MailController-&gt;actionCreate(NULL)\n#11 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#12 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#13 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller-&gt;runAction(&#039;create&#039;, Array)\n#14 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction(&#039;mail/mail/creat...&#039;, Array)\n#15 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#16 /home/interga2/antaresmedya.site/index.php(25): yii\\base\\Application-&gt;run()\n#17 {main}</pre>",
        "status": 500,
        "statusText": "error"
    },
    "dataType": "html",
    "html": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Getting unknown property: humhub\\modules\\content\\models\\ContentContainerSetting::title&#039; \n\nin /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\\base\\Component-&gt;__get(&#039;title&#039;)\n#1 /home/interga2/antaresmedya.site/protected/vendor/yiisof...",
    "error": {},
    "errorThrown": "",
    "validationError": false
}

**Comment by luke-** [comment]
Seems related to "verified account tick".

**Comment by erenakkuss** [comment]
I made it from profile header.  I removed it still Any account cant get any notification. And it sending message but Getting this error.

{
"url": "/index.php?r=mail%2Fmail%2Fcreate",
"status": 500,
"response": "

Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Getting unknown property: humhub\modules\content\models\ContentContainerSetting::title' \n\nin /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('title')\n#1 /home/interga2/antaresmedya.site/protected/vendor/yiisof...",

"textStatus": "error",

"xhr": {

"readyState": 4,

"responseText": "
Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Getting unknown property: humhub\modules\content\models\ContentContainerSetting::title' \n\nin /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('title')\n#1 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/validators/Validator.php(258): yii\db\BaseActiveRecord->__get('title')\n#2 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(humhub\modules\content\models\ContentContainerSetting), Array)\n#3 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(560): yii\base\Model->validate(Array)\n#4 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)\n#5 /home/interga2/antaresmedya.site/protected/humhub/libs/BaseSettingsManager.php(80): yii\db\BaseActiveRecord->save()\n#6 /home/interga2/antaresmedya.site/protected/modules/mail/models/Config.php(142): humhub\libs\BaseSettingsManager->set('conversationCou...', 1610304117)\n#7 /home/interga2/antaresmedya.site/protected/modules/mail/models/Config.php(159): humhub\modules\mail\models\Config->getConversationCount(Object(humhub\modules\user\models\User))\n#8 /home/interga2/antaresmedya.site/protected/modules/mail/models/forms/CreateMessage.php(126): humhub\modules\mail\models\Config->incrementConversationCount(Object(humhub\modules\user\models\User))\n#9 /home/interga2/antaresmedya.site/protected/modules/mail/controllers/MailController.php(318): humhub\modules\mail\models\forms\CreateMessage->save()\n#10 [internal function]: humhub\modules\mail\controllers\MailController->actionCreate(NULL)\n#11 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#12 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)\n#13 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('create', Array)\n#14 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('mail/mail/creat...', Array)\n#15 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))\n#16 /home/interga2/antaresmedya.site/index.php(25): yii\base\Application->run()\n#17 {main}
",

"status": 500,

"statusText": "error"

},

"dataType": "html",

"html": "
Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Getting unknown property: humhub\modules\content\models\ContentContainerSetting::title' \n\nin /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /home/interga2/antaresmedya.site/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('title')\n#1 /home/interga2/antaresmedya.site/protected/vendor/yiisof...",

"error": {},

"errorThrown": "",

"validationError": false

}

**Comment by buddh4** [comment]
You seem to have a validator for `ContentContainerSetting::title` which does not actually exists in the db andseems to be a custom change of yours?
