### ISSUE TITLE
Notification not coming

### ISSUE THREAD

**Issue by erenakkuss** [humhub/humhub#4767]
Any accounts notification not receiving and when send mail to someone, its sending but giving an error

![Screenshot_20210110-222825_Chrome](https://user-images.githubusercontent.com/77244757/104133270-903ac280-5393-11eb-9680-19cc9dff1dff.jpg)

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/4766#issuecomment-757529790

**Comment by erenakkuss** [comment]
@luke-  I fix it but still ??

**Comment by luke-** [comment]
The problem seems to be related to individual customizations. 

You can post in the community exact steps to reproduce the problem from a fresh installation, maybe we can help you there.
