### ISSUE TITLE
Still getting IP in emails instead of base url

### ISSUE THREAD

**Issue by agit8or** [humhub/humhub#4774]
No proxy in front of it, I've searched and tried all of the suggestion with no luck.

**Comment by ArchBlood** [comment]
Not sure why this would be happening, if Base Url is set in the admin settings section it should pull the domain not ip

**Comment by agit8or** [comment]
Yet it is. When I first installed it, I had to use it's IP to access as the DNS hadn't been setup yet, however the base url was set once this was done and ssl setup.

**Comment by ArchBlood** [comment]
Only thing I can think of is that the IP isn't pointing to the domain name correctly :thinking:

**Comment by luke-** [comment]
Does this affect all e-mails? Daily Summaries and Password Recovery?
