### ISSUE TITLE
Emoji Search broken on mobile

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#4775]
### What steps will reproduce the problem?
On mobile click the emoji icon in the richtext bar and try entering `thinking`

### What is the expected result?
Entering `thinking` should show the results after searching through all emojis i.e :thinking:

### What do you get instead?
Typing `thinking` does not cycle through the emojis to display the searched for emoji

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7
| PHP version      | 7.3
| Operating system | CloudLinux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
@buddh4 Can you please take a look?

**Comment by buddh4** [comment]
Also the usability on mobile is not good. Maybe a static position would be better on mobile.

**Comment by luke-** [comment]
@buddh4 Thanks for the fix. Can you please release the ProseMirror module directly, I would release Beta.2 soon.

**Comment by buddh4** [comment]
kk wanted to work on some richtext related issues today, do you want to release today, or is tomorrow ok?

**Comment by luke-** [comment]
@buddh4 It planned for today. I would do it in about 2-3 hours. Otherwise, the changes will be included in the next release. I'm not sure yet if there will be a third beta version.

**Comment by buddh4** [comment]
k, I'll let you know once I've released.

**Comment by buddh4** [comment]
@luke- can you update the prosmirror dependency to 1.1.1 and do a composer update?

**Comment by luke-** [comment]
Yes, thanks!

**Comment by buddh4** [comment]
@luke- can you again update to 1.1.2? Sorry there was a small issue with the emoji chooser on mobile or did you already relase?

**Comment by luke-** [comment]
@buddh4 no prob - done
