### ISSUE TITLE
Include License in repository

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#4779]
### Is your feature request related to a problem? Please describe.
Users and developers should have a fast and reliable way to find the license of this project. Currently the license is only available via link to [humhub.com](https://www.humhub.com/en/licences). This is not ideal because the site may be down, links my be broken or the content may be changed without notice.

### Describe the solution you'd like
Add a `LICENSE` file to the repository containing the full license text. You may opt to move the AGPL to a second file, for example `LICENSE.AGPL-3.0-or-later` and use the main file to explain the dual licensing option referring to that second file for the AGPL part.

Whether you include the commercial license in full text or just link to the Website is up to you, but I think the AGPL and basic information on the dual licensing should be included with the source code.

Additional benefit is that the LICENSE is linked in the Github sidebar making it easier to find.

**Comment by ArchBlood** [comment]
I don't really think it's necessarily a bad thing to not have a LICENSE file in the repo, as a developer of a project you can simple do an alternative `@license` to reference a license or multiple license that are shown on a website in this case

https://github.com/humhub/humhub/blob/5c20ca98ebf4a85ecca78dd3c7f92d4a9d49c9c3/protected/humhub/controllers/ErrorController.php#L3-L7

**Comment by dreua** [comment]
I agree that it's not *necessarily a bad thing* but I still think it's *better* to have that stuff baked into the repository because it maximizes reliability and transparency at no additional cost.

I hope that the HumHub GmbH & Co. KG has a bright and long future and I don't have any reason to believe otherwise, but hey, let's meet at a local bar and I'll tell you how things can change in unexpected and radical ways... Companies get bought, websites get discontinued or changed and in that case the HumHub code can not be reused because it lacks a license.

I as an open source developer am reluctant to invest time in a project that could loose it's open source license at any time.

**Comment by dreua** [comment]
Any updates?

**Comment by dreua** [comment]
Done via https://github.com/humhub/humhub/commit/f28d4b58de0df1cea175c7b1c28468ce448b89be, thanks!
