### ISSUE TITLE
Always enable Space Membership Web Notifications

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4787]
Make sure this checkbox is always activated (like Message).
![image](https://user-images.githubusercontent.com/4736168/105379064-c2a6b400-5c0c-11eb-877c-6631885f594e.png)

When unchecked it's not longer possible to invite the user to private spaces.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4789

**Comment by punkyard** [comment]
could a warning be added here?
