### ISSUE TITLE
Editor Scrolling Broken in Android Chrome

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#4788]
When scrolling a large block of text in the dashboard post editor, the entire page scrolls and/or the Chrome pull-to-refresh gets triggered and destroys all input.  I first noticed this in HumHub 1.7.1 and have not tested other versions.

Excuse me if it's a duplicate issue, but I couldn't find the last one I submitted and there was no reply.

**Comment by luke-** [comment]
I've moved the issue here: https://github.com/humhub/humhub-prosemirror/issues/25
