### ISSUE TITLE
Email Sent from console & email summaries stopped working

### ISSUE THREAD

**Issue by superseby2** [humhub/humhub#4797]
Hello, 

Starting a couple of days ago I noticed exception in logs like the one at the end of this post.
Running the test  from the console would trigger the same issue 

php yii test/email <my email>

Looking closer at the logs, I realized the HELO command using [127.0.0.1].  

When looking at /var/www/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php

I just cannot figure out, how, when running from the console the domain name is set ? Not being a PHP expert I must have missed something? 

### What steps will reproduce the problem?

php yii test/email <my email>

### What is the expected result?
Email being sent

### What do you get instead?

Exception as show below

### Additional info

- Running the test from the webconsole works perfectly. 
- As mentionned in the title, it "used to work", and that is what bugs me ...
- I had to hard-code our domain name in _AbstractSmtpTransport.php_ to make all this work. Of course this is not viable solution.
- The php is running within a Docker container. I tried to change the hostname with no improvement

Any pointers on how you guys are setting the domain name before sending emails would help me to understand what I have done to break this thing. :smiley: 

Thx !

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1
| PHP version      |  7.3
| Operating system | Linux

Swift_TransportException: Expected response code 250 but got code "", with message "" in /var/www/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383 Stack trace: #0 /var/www/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('', Array) #1 /var/www/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('HELO [127.0.0.1...', Array, Array) #2 /var/www/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(296): Swift_Transport_EsmtpTransport->executeCommand('HELO [127.0.0.1...', Array) #3 /var/www/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(322): Swift_Transport_AbstractSmtpTransport->_doHeloCommand() #4 /var/www/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand() #5 /var/www/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start() #6 /var/www/humhub/protected/vendor/yiisoft/yii2-swiftmailer/Mailer.php(146): Swift_Mailer->send(Object(Swift_Message)) #7 /var/www/humhub/protected/humhub/components/mail/Mailer.php(117): yii\swiftmailer\Mailer->sendMessage(Object(humhub\components\mail\Message)) #8 /var/www/humhub/protected/vendor/yiisoft/yii2/mail/BaseMailer.php(263): humhub\components\mail\Mailer->sendMessage(Object(humhub\components\mail\Message)) #9 /var/www/humhub/protected/vendor/yiisoft/yii2/mail/BaseMessage.php(49): yii\mail\BaseMailer->send(Object(humhub\components\mail\Message)) #10 /var/www/humhub/protected/humhub/modules/notification/targets/MailTarget.php(82): yii\mail\BaseMessage->send() #11 /var/www/humhub/protected/humhub/modules/notification/targets/BaseTarget.php(161): humhub\modules\notification\targets\MailTarget->handle(Object(humhub\modules\calendar\notifications\ForceAdd), Object(humhub\modules\user\models\User)) #12 /var/www/humhub/protected/humhub/modules/notification/components/NotificationManager.php(85): humhub\modules\notification\targets\BaseTarget->send(Object(humhub\modules\calendar\notifications\ForceAdd), Object(humhub\modules\user\models\User)) #13 /var/www/humhub/protected/humhub/modules/notification/jobs/SendBulkNotification.php(38): humhub\modules\notification\components\NotificationManager->sendBulk(Object(humhub\modules\calendar\notifications\ForceAdd), Object(humhub\modules\user\components\ActiveQueryUser)) #14 /var/www/humhub/protected/humhub/modules/queue/ActiveJob.php(33): humhub\modules\notification\jobs\SendBulkNotification->run() #15 /var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(246): humhub\modules\queue\ActiveJob->execute(Object(humhub\modules\queue\driver\MySQL)) #16 /var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('1819', 'O:53:"humhub\\mo...', '300', '1') #17 /var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('1819', 'O:53:"humhub\\mo...', '300', '1', '13328') #18 [internal function]: yii\queue\cli\Command->actionExec('1819', '300', '1', '13328') #19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #20 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #21 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('exec', Array) #22 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('exec', Array) #23 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array) #24 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/exec', Array) #25 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #26 /var/www/humhub/protected/yii(29): yii\base\Application->run() #27 {main}

**Comment by superseby2** [comment]
I realized we can export an ENV variable like export SERVER_NAME and it seems to be picked up by PHP code. 
Is it how everything should be done?

**Comment by luke-** [comment]
Unfortunately, I can't quite reproduce your problem.

If you don't have any individual config file settings, HumHub should use the admin settings.

Here you can retrieve the values: 

```
php protected/yii settings/list base
```

**Comment by superseby2** [comment]
Thanks @luke, 

Strangely enough, all settings seem to be picked up allright except for the domain name :thinking: 
My workaround (passing the ENV value is doing the trick though) . 

Since you cannot reproduce the pb your end, I guess we could close this issue. Up to you. 

Thx!

**Comment by luke-** [comment]
Thanks for the response. If you have more details, feel free to add them here. Until then I would close the issue, it doesn't seem to be a common problem.
