### ISSUE TITLE
Error: PHP Core Warning: Module 'imagick' already loaded // Service Unavailable

### ISSUE THREAD

**Issue by Abatjour3407** [humhub/humhub#4801]
I just installed a fresh installation of HumHub (latest version) using Softaculous on cPanel, I logged in and was going through the tutorials when I got an error message (unfortunately I can't remember what it was now*), I thought maybe there wasn't enough memory so I increased the memory on the php.ini wizard (on cPanel) and now I get this error: [https://ibb.co/gJsRm32]

After fruitless searches on Google for the solution I contacted my host support (usually very good) but they couldn't help and said they aren't familiar with HumHub and should contact someone here. If there's something they can do they would be happy to but I would have to instruct them it seems. 

Extra info: When the support agent checked out the site it looked fine still, then they logged into my account and got the same error - seems the login screen is uneffected. I also tried uninstalling the software and reinstalling it - same problem...

Any ideas what the problem is?

*PS: I tried clearing my browser data (cache, etc) and tried shift+refresh and it gives a new error message. This is the same error message I got right in the beginning:
**Service Unavailable**
**The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.**

**Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.**

**Comment by luke-** [comment]
It seems like it's a problem with your hosting PHP settings.

The error message says that an extension was loaded twice.

Due to this error message, HumHub can not work correctly.
