### ISSUE TITLE
head.php not rendering code

### ISSUE THREAD

**Issue by Schillers** [humhub/humhub#4802]
#### Using Google AdSense.
The first step to use Google AdSense is to get the HumHub site verified by placing a string similar to "<script data-ad-client="ca-pub-xxxxxxxxxxxxxxxx" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>" into the \<head> of the site.

I have installed the HumHub Google AdSense module and signed up for an AdSense account.  The information input into the AdSense module requires a "slot" input which is not made available in the first instance by Google AdSense, I have since retrieved this value but would still like to place the code into the \<head> of the site. To circumvent this, I have attempted to use Custom HTML and place the String into the \<head> of the site by using the "protected/humhub/views/layouts/head.php" as outlined in [Issue #2663](https://github.com/humhub/humhub/issues/2663). After placing this string and waiting for all CRON and SQL jobs to run, clearing the cache and trying on multiple devices the string still does not exist in the \<head> of the site.

### What is the expected result?
After placing the string in the "protected/humhub/views/layouts/head.php" file, I would expect to see "<script data-ad-client="ca-pub-xxxxxxxxxxxxxxxx" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>" placed in the \<head> of the website as per Google AdSense Guidelines.

### What do you get instead?
The code was not present in the <head> of the site.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.2
| PHP version      | 7.3.23
| Operating system | Linux

**Comment by luke-** [comment]
Please use this repo: https://github.com/GreenMeteor/humhub-adsense-module

**Comment by buddh4** [comment]
@luke- nontheless the `head.php` should add code to the head, if not we should remove it or document how to manipulate the head section of a theme.

**Comment by Schillers** [comment]
> @luke- nontheless the `head.php` should add code to the head, if not we should remove it or document how to manipulate the head section of a theme (or maybe even without a theme).

@buddh4 thank you for your comment. I have rectified the issue as a result but I would like to contribute by suggesting an edit to the documentation such that the theme files will overwrite the primary file.

Many thanks!

**Comment by ArchBlood** [comment]
> @luke- nontheless the `head.php` should add code to the head, if not we should remove it or document how to manipulate the head section of a theme (or maybe even without a theme).

Just to note here for the future;
This seems to be the correct solution when dealing with adding to `<head></head>` section, see [yii2 docs](https://www.yiiframework.com/doc/guide/2.0/en/output-client-scripts)
```php
$this->registerJsFile('LINK_HERE', ['DATA_ENTRY' => 'DATA', 'async' => 'async', 'position' => View::POS_HEAD]);
```
The only issue that I see is that entering an external/internal link also applies a version number? Well in this case it doesn't seem to do any harm but does need to be investigated on how to remove such things in the future :thinking:

**Comment by luke-** [comment]
If a theme provides the view file `views/layouts/head.php`, it should still be added to the head section.

@ArchBlood Yes, this is the approach preferred by Yii2 and us for modules and core head entries.
