### ISSUE TITLE
1.8 - Uneven spacing between comment/linke link in stream

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4809]
![grafik](https://user-images.githubusercontent.com/9800854/106323403-ad1e3380-6277-11eb-9901-ea18c0be2d33.png)

**Comment by yurabakhtin** [comment]
@luke- @buddh4 Fixed in PR https://github.com/humhub/humhub/pull/4816.
The separators were copied from old code in the PR https://github.com/humhub/humhub/pull/4772/files#diff-b0aae92581056000f258ba9452e5b3a57049bb8fefb383dfdfd1312086c45419R30
