### ISSUE TITLE
Add db/table collation prerequisite check

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4818]
See https://github.com/humhub/humhub/issues/677

**Comment by luke-** [comment]
However, these checks must be skipped during installation (without an existing DB connection).

New Checks:
- Database Version Requirement: https://docs.humhub.org/docs/admin/requirements#database
- Table checks (possibly merged): All tables should use the same engine and the same collation (utf8mb4).
- Optionally desired InnoDB Table Engine is used

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4827:

<img width="751" alt="tests_install" src="https://user-images.githubusercontent.com/6995524/106758066-23d57b00-6642-11eb-962e-d9e89cdf4739.png">

<img width="1144" alt="tests_admin" src="https://user-images.githubusercontent.com/6995524/106758085-2932c580-6642-11eb-9973-e849448e5a41.png">

<img width="850" alt="tests_wrong_ver_collaction_engine" src="https://user-images.githubusercontent.com/6995524/106758099-2cc64c80-6642-11eb-9e53-e1d6579b0a12.png">
