### ISSUE TITLE
1.8 - Markdown Table Columns not visible

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4820]
### What steps will reproduce the problem?

- Create a 3 column / 3 rows Table in the Richtext Editor
- Columns not visible 

![image](https://user-images.githubusercontent.com/4736168/106644140-fe396a80-658a-11eb-91ae-bf4979b976e3.png)

### What is the expected result?

See columns at least in edit mode 

### What do you get instead?

No columns

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8

**Comment by buddh4** [comment]
Ok, we should add the columns in the editor.
