### ISSUE TITLE
Wrong Translation pt_BR

### ISSUE THREAD

**Issue by fsainovich** [humhub/humhub#4824]
![image](https://user-images.githubusercontent.com/27427085/106736687-899b1600-65f4-11eb-869d-af2cc2e07629.png)

Please, correct changes in code like below

Edit file: /protected/humhub/modules/admin/messages/pt-BR/information.php

Change: 

'<strong>CronJob</strong> Status' => 'Status <strong>CronJob strong&gt;</strong>',
'<strong>Queue</strong> Status' => 'Status da <strong>fila strong&gt;</strong>',

To:

'<strong>CronJob</strong> Status' => 'Status <strong>CronJob</strong>',
'<strong>Queue</strong> Status' => 'Status da <strong>fila</strong>',

**Comment by luke-** [comment]
Thanks is fixed@translation
