### ISSUE TITLE
imagecreatefromjpeg bug

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#483]
Not loaded Feed on the http://site.com/directory/directory/userPosts, 

firefox issue:

imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Premature end of JPEG file

add in index.php

ini_set(‘gd.jpeg_ignore_warning’, 1);

but not solved.

log:

{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
{*\generator Riched20 6.4.9879}\viewkind4\uc1 
\pard\sa200\sl276\slmult1\f0\fs22\lang9 imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Premature end of JPEG file (/home/admin/web/site.com/public_html/protected/modules_core/file/libs/ImageConverter.php:280) Stack trace: #0 /home/admin/web/site.com/public_html/protected/modules_core/file/libs/ImageConverter.php(82): ResizeGD() #1 /home/admin/web/site.com/public_html/protected/modules_core/file/models/File.php(274): Resize() #2 /home/admin/web/site.com/public_html/protected/modules_core/file/widgets/views/showFiles.php(22): File->getPreviewImageUrl() #3 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(130): require() #4 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(95): ShowFilesWidget->renderInternal() #5 /home/admin/web/site.com/public_html/protected/vendors/yii/web/widgets/CWidget.php(244): ShowFilesWidget->renderFile() #6 /home/admin/web/site.com/public_html/protected/modules_core/file/widgets/ShowFilesWidget.php(23): ShowFilesWidget->render() #7 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(173): ShowFilesWidget->run() #8 /home/admin/web/site.com/public_html/protected/modules_core/comment/widgets/views/showComment.php(79): ShowCommentWidget->widget() #9 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(130): require() #10 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(95): ShowCommentWidget->renderInternal() #11 /home/admin/web/site.com/public_html/protected/vendors/yii/web/widgets/CWidget.php(244): ShowCommentWidget->renderFile() #12 /home/admin/web/site.com/public_html/protected/modules_core/comment/widgets/ShowCommentWidget.php(39): ShowCommentWidget->render() #13 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(173): ShowCommentWidget->run() #14 /home/admin/web/site.com/public_html/protected/modules_core/comment/widgets/views/comments.php(34): CommentsWidget->widget() #15 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(130): require() #16 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(95): CommentsWidget->renderInternal() #17 /home/admin/web/site.com/public_html/protected/vendors/yii/web/widgets/CWidget.php(244): CommentsWidget->renderFile() #18 /home/admin/web/site.com/public_html/protected/modules_core/comment/widgets/CommentsWidget.php(49): CommentsWidget->render() #19 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(167): CommentsWidget->run() #20 /home/admin/web/site.com/public_html/protected/widgets/StackWidget.php(94): WallController->widget() #21 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(173): WallEntryAddonWidget->run() #22 /home/admin/web/site.com/public_html/protected/modules_core/wall/views/wallLayout.php(72): PostWidget->widget() #23 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(126): require() #24 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(95): PostWidget->renderInternal() #25 /home/admin/web/site.com/public_html/protected/vendors/yii/web/widgets/CContentDecorator.php(76): PostWidget->renderFile() #26 /home/admin/web/site.com/public_html/protected/vendors/yii/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate() #27 /home/admin/web/site.com/public_html/protected/vendors/yii/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput() #28 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(206): CContentDecorator->run() #29 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(300): PostWidget->endWidget() #30 /home/admin/web/site.com/public_html/protected/modules_core/post/widgets/views/post.php(23): PostWidget->endContent() #31 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(130): require() #32 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(95): PostWidget->renderInternal() #33 /home/admin/web/site.com/public_html/protected/vendors/yii/web/widgets/CWidget.php(244): PostWidget->renderFile() #34 /home/admin/web/site.com/public_html/protected/modules_core/post/widgets/PostWidget.php(38): PostWidget->render() #35 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CBaseController.php(167): PostWidget->run() #36 /home/admin/web/site.com/public_html/protected/modules_core/post/models/Post.php(113): WallController->widget() #37 /home/admin/web/site.com/public_html/protected/modules_core/wall/StreamAction.php(256): Post->getWallOut() #38 /home/admin/web/site.com/public_html/protected/vendors/yii/web/actions/CAction.php(76): StreamAction->run() #39 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CController.php(308): StreamAction->runWithParams() #40 /home/admin/web/site.com/public_html/protected/vendors/yii/web/filters/CFilterChain.php(133): WallController->runAction() #41 /home/admin/web/site.com/public_html/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #42 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #43 /home/admin/web/site.com/public_html/protected/vendors/yii/web/filters/CInlineFilter.php(58): WallController->filterAccessControl() #44 /home/admin/web/site.com/public_html/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #45 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #46 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CController.php(265): WallController->runActionWithFilters() #47 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CWebApplication.php(282): WallController->run() #48 /home/admin/web/site.com/public_html/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #49 /home/admin/web/site.com/public_html/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #50 /home/admin/web/site.com/public_html/index.php(39): WebApplication->run() REQUEST_URI=/wall/wall/stream/type/Community/guid//limit/4/from/58236/filters//sort/c?CSRF_TOKEN=fbbd878d8f4e26ba6d48b3f23d3489ff70bd5690&_=1418330404931 \par
}

**Comment by WASasquatch** [comment]
This could be the issue I was trying to figure out. We are a art website where images can range from 1mb to 10+mb 

However, HumHub uses ImageMagick (if installed) so we are we not then resorting to a conversion call from ImageMagick in the case of GD failure?
