### ISSUE TITLE
1.8: Username validation breaks language change

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4831]
### What steps will reproduce the problem?

- Create a username with whitespace.
- Update to 1.8 with stricter username valdiation: https://github.com/humhub/humhub/commit/2bdc435486bd2b855fe170a29de6b2c8f675647e
- Try to change language: Account settings -> Settings -> language

### What is the expected result?

Changed language

### What do you get instead?

Stay in old language.

### Additional info

Ideally, the regexp username should apply only to new users or when the username is changed.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/4834
