### ISSUE TITLE
Ability to add a header + subject to  a Post

### ISSUE THREAD

**Issue by superseby2** [humhub/humhub#4839]
### Is your feature request related to a problem? Please describe.
Nope

### Describe the solution you'd like

I discovered circle.so which basically is exactly what Humhub can do (Spaces, Posts, comments etc ..) But they are organizing things a little different. 
Another difference, is the way you Post something. They call it topics, and you can add a Subject + a cover Image. 

While I thought a subject was a bit too much, in some case it does make sense : when you are doing a write up for instance and you want to clearly indicate the motivation behind it. 

Also, the cover image makes the writeup stands out.

It would be nice to have in the parameters the aility to add a subject and a cover image : I imagine 2 fields being added. One allowing to copy/paste or upload an image / the other one bieing a simple text field with no formatting.

### Describe alternatives you've considered

I realized I can do it already by copying / pasting an image at the top of my post but it would be much easier to have  a field that will allow to upload and a process which will take care of resizing etc .. 

![image](https://user-images.githubusercontent.com/32198925/106995636-98fa9a80-677f-11eb-831b-37f0bffa6bfe.png)

**Comment by luke-** [comment]
We are currently working on a News module, which is very much in this direction. 
Unfortunately I can't give more details about it yet.

**Comment by superseby2** [comment]
Nice to hear and thanks for sharing the "news" :) 
Could you give us maybe an ETA and if it would be part of the community edition?


Thanx again.

**Comment by luke-** [comment]
Maybe in 1-2 months. It is currently intended for the Professional Edition. 

Apart from that, there was also the discussion that Posts could optionally have a title. However, no images would be planned here.

**Comment by superseby2** [comment]
Ok thx!
