### ISSUE TITLE
Include space tags in the space’s “About” page

### ISSUE THREAD

**Issue by verement** [humhub/humhub#4848]
### Is your feature request related to a problem? Please describe.

The tags set in a user’s account settings appear on that user’s profile page. Incongruously, the tags set in a space’s settings do not appear anywhere within the space.

### Describe the solution you'd like

It would be great to have the space’s tags appear in the “About” page for the space.

### Describe alternatives you've considered

Both user tags and space tags do helpfully appear in the directory.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/4ddc1339908eaefe49073b485cec84e32428146a
