### ISSUE TITLE
Parse multiple space and user tags in the same way

### ISSUE THREAD

**Issue by verement** [humhub/humhub#4849]
### Is your feature request related to a problem? Please describe.

The handling of multiple tags in space and user tags is inconsistent. Multiple user tags must be separated with commas, and tags may contain internal spaces. Multiple space tags may be separated by spaces or commas, and individual tags may not themselves contain spaces.

### Describe the solution you'd like

I would like all tags to be parsed in the same way. Ideally this would be comma-separated, so that tags may contain spaces. It would also be helpful to document this for the user within the interface.

### Describe alternatives you've considered

While I found it possible to use non-breaking spaces within space tags to work around the space-splitting, this would be highly non-obvious to most users.

**Comment by luke-** [comment]
Should be solved by this issue: https://github.com/humhub/humhub/issues/4862
