### ISSUE TITLE
OAuth onSuccessLogin() errors

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#4850]
### What steps will reproduce the problem?
Setup an OAuth client, any will do

### What is the expected result?
You should be automatically logged in

### What do you get instead?
Throws `Calling unknown method {OAUTH_CLIENT}::onSuccessLogin()`

### Additional info
You can confirm the issue through the [community site](https://community.humhub.com/dashboard) as well
| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.x & 1.8
| PHP version      | 7.3.26
| Operating system | CloudLinux

**Comment by ArchBlood** [comment]
Fixed by #4854

**Comment by luke-** [comment]
Merged: https://github.com/humhub/humhub/commit/6af25dd0eea406b470b42f29500ae2c6d17040ea
