### ISSUE TITLE
Allow admins to add and change User profile photos

### ISSUE THREAD

**Issue by spoorun** [humhub/humhub#4851]
Currently admins cannot change a User's profile image when in Settings > User administration

It is possible by using the impersonation facility, but this is not obvious, nor quick.

When adding lots of users for a company for example, the admin may wish to populate pics etc as they are created to enhance the aesthetics and usability of their spaces.

**Comment by ArchBlood** [comment]
This is configurable via /protected/config/common.php file see https://docs.humhub.org/docs/admin/advanced-configuration/#module-configurations

https://github.com/humhub/humhub/blob/0874a48727b08acd8ce6e16a78a4f615a80de5fb/protected/humhub/modules/user/Module.php#L55-L60

**Comment by spoorun** [comment]
> This is configurable via /protected/config/common.php file see https://docs.humhub.org/docs/admin/advanced-configuration/#module-configurations

Thanks @ArchBlood  appreciated.

It would be useful to expose that in the admin settings, I would say a lot of people would find it useful.

**Comment by luke-** [comment]
We plan to better describe these module options in the documentation.
