### ISSUE TITLE
Allow admins to fill all User fields at time of user creation

### ISSUE THREAD

**Issue by spoorun** [humhub/humhub#4852]
Many users of our voluntary organisations do not complete the required fields when they log in, nor add photos or essential contact details.

Admins should have the option of adding the User's details (in particular phone, mobile, photo, birthday, address/town/country, and title) when the User is being created.

Going in afterwards to edit is time-consuming if there's a lot of Users to add.

Title in particular is important.

**Comment by ArchBlood** [comment]
Admins can already do this

### Admin > Users > Users Tab > Edit User
![Screenshot_1](https://user-images.githubusercontent.com/35392110/107107651-752b6900-6800-11eb-9bac-8121248e9566.png)

### Select Tab and edit
![Screenshot_2](https://user-images.githubusercontent.com/35392110/107107545-aa838700-67ff-11eb-9829-1b3eeb3dcca8.png)

> Note: These screenshots are from `v1.8-beta.1`

**Comment by ArchBlood** [comment]
You can also make fields required as well

### Admin > Users > Profiles
![Screenshot_3](https://user-images.githubusercontent.com/35392110/107107800-7610ca80-6801-11eb-8260-15501792ff8a.png)
