### ISSUE TITLE
Space moderator cannot invite pending members

### ISSUE THREAD

**Issue by raffitz** [humhub/humhub#4856]
### What steps will reproduce the problem?

User sends a request to join a Space.
Moderator tries to invite that user to join a Space.

### What is the expected result?

User becomes a member of the Space.

### What do you get instead?

The invite cannot go through because there is a pending application from that user.
If the Moderator asks the User to cancel their application, and then invites them, the User becomes a member of the Space.

### Additional info

This happened on the HumHub Translations instance.

**Comment by luke-** [comment]
@yurabakhtin Can you please check this out. In this case, the membership request should be approved with this.  Target Branch: Develop

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4865
