### ISSUE TITLE
Problem with sub reply in Android

### ISSUE THREAD

**Issue by sarz4fun** [humhub/humhub#4858]
When i click on a sub reply from android webapp, mention can bot be deleted but auto-types last 2 chat of mention when i tap backspace.

### What steps will reproduce the problem?

Tap reply on sub replay and tap backspace a lot.

![Screenshot_20210207-090403__01](https://user-images.githubusercontent.com/39486520/107140807-e49a7900-6924-11eb-85f3-7459b1b2746f.jpg)

### What is the expected result?
Delete mention
### What do you get instead?
GMGMGMGMGM
### Additional info
Today on community.humhub.org.

**Comment by luke-** [comment]
Hmm, I can't reproduce this. When I tap on a reply to a comment, the mentioning is automatically inserted, but I can also remove it again without any problems. (If I remove using backspace, all the Mentioning is removed at once).

Using Chrome one Android.

**Comment by ArchBlood** [comment]
I've also been able to reproduce this, it's a rare occurrence in Android 10+ devices

**Comment by luke-** [comment]
Any tip how to reproduce on Android 11?

**Comment by ArchBlood** [comment]
The only thing I can think of is going through a notification link then clicking on a reply of a reply and let the auto mention pop up and try deleting the mention or adding to the reply with text then try deleting the text, I've also noticed that when doing this your text indicator always shows before the mention position

**Comment by ArchBlood** [comment]
I must note that the reply button to a comment doesn't do this, just the reply button to a reply does

**Comment by sarz4fun** [comment]
> I've also been able to reproduce this, it's a rare occurrence in Android 10+ devices

I am using android 9 (oneplus3), Chrome for Android, from link in drawer.

**Comment by ArchBlood** [comment]
@luke- seems that this p/r is when it all started #4571, tested 1.7.x as well seems to not being affected, would seem that the implementation of the mentioning function is the core cause of the issue :thinking:

**Comment by luke-** [comment]
@ArchBlood Hmm, thanks for the hint. 

Steps to reproduce the problem:
- Try to reply to a comment of a comment via "Reply" link.
- Then automatically a Mentioning appears like e.g. @Example in the comment input
- When you try to delete it with backspace, this weird behavior happens?

Can you confirm this?

**Comment by ArchBlood** [comment]
> @ArchBlood Hmm, thanks for the hint.
> 
> Steps to reproduce the problem:
> 
> * Try to reply to a comment of a comment via "Reply" link.
> * Then automatically a Mentioning appears like e.g. @example in the comment input
> * When you try to delete it with backspace, this weird behavior happens?
> 
> Can you confirm this?

I can confirm, an alternative method to fix this, remove mentioning and use blockquotes of the message that you're replying to

**Comment by buddh4** [comment]
Seems to be a problem with chrome:

- https://github.com/ProseMirror/prosemirror/issues/565
- https://bugs.chromium.org/p/chromium/issues/detail?id=612446

**Comment by ArchBlood** [comment]
So the action needed done is to `contenteditable="inherit"` or find places where this is needed to be set to `true` or `false`?
