### ISSUE TITLE
Embedding of Player for AVI/M4V not working

### ISSUE THREAD

**Issue by blackPantherOS** [humhub/humhub#4859]
### What steps will reproduce the problem?
drop avi file to comment 

### What is the expected result?
simple uploaded file,attached to post as hidden file, cannot embedding, 

### What do you get instead?
ogv file working and embedding fine

| ---------------- | ---
| HumHub version   | 1.7.2
| PHP version      |  7.2
| Operating system | blackPanther OS

> Note: Also provide the full error stacks
empty

**Comment by ArchBlood** [comment]
See #4411
