### ISSUE TITLE
Problem! Files get lost

### ISSUE THREAD

**Issue by JK742020** [humhub/humhub#4860]
Uploaded a PDF within custom page. Two days later it was gone. Link was still there but after clicking the link the PDF wasn't shown. Instead: “Uuups. File not available.” (Freely translated from German)

Pictures within a article. Same thing.

Uploaded audio mp3. Same thing.

### What steps will reproduce the problem?

No idea. It happens quite randomly. Some files are affected others aren't.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.3
| PHP version      | 
| Operating system | Mac Catalina

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

There are no errors to be found in the Log!

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by FreshCSGOSkins** [comment]
Some additional information on this issue. Running PHP 7.3 (now testing with 7.4) on Hetzner webhosting with APCu and OPcache. Uploading files and including them in posts works quite normal. When files go missing the whole post itself stays completely in tact (the URL to the file itself seems to be broken only). It only affects individual files when more are present in a post. They usually go missing after more than 1 day - thats why my best guess right now is that they are being removed by humhubs cron job.

I would appreciate any ideas how to take a deeper look into this. PHP / Humhub Logs show no related issues. Is there a way to save a detailed log of the cronjobs or is there a good way to track changes of the public filesystem?
I would provide any additional information thats needed.

Thanks in advance

**Comment by ArchBlood** [comment]
Not sure about v1.6.3, but if a file doesn't get attached to a record then HumHub will remove the file, how exactly are you uploading, through upload function or editor upload function? :thinking:

Overall I strongly recommend updating to the latest stable version
https://docs.humhub.org/docs/admin/updating/

**Comment by luke-** [comment]
You can check if an uploaded file is automatically deleted if the field `object_model` in the database table `files` is empty.
Normally the field should be empty during post creation and then set when submitting the post.

Can you please check under what circumstances this happens and give us steps to reproduce it?
It would also be interesting to see if the Browser Console displays Javascript errors.

Otherwise an update to the latest HumHub installation would also be advisable.

**Comment by FreshCSGOSkins** [comment]
Thanks for the helpful tip @luke- . It really seems some of the uploaded files are missing the object_model reference so it only makes sense that they are removed during cron. We are now going to look into some test cases to determine how to reproduce the issue.

**Comment by buddh4** [comment]
In case you can reproduce the issue with the custom pages module please share information about how to reproduce (which type of page, template etc) here https://github.com/humhub/humhub-modules-custom-pages
