### ISSUE TITLE
Uniform Tag Picker

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4862]
Currently the tag fields for Spaces/User are simple comma separated text fields.

![image](https://user-images.githubusercontent.com/4736168/107200347-e3864c00-69f7-11eb-9950-4dbcaeb88b46.png)
![image](https://user-images.githubusercontent.com/4736168/107200392-ef720e00-69f7-11eb-8203-a6f8da91d0a5.png)

Here, analogous to the Topic Picker, there should be a field with better UI.
![image](https://user-images.githubusercontent.com/4736168/107200576-2cd69b80-69f8-11eb-88bb-0bd09b561516.png)

If possible, the existing tags (text DB field) should be saved and migrated via the existing ContentTags logic.

**Comment by yurabakhtin** [comment]
@luke- 

> If possible, the existing tags (text DB field) should be saved and migrated via the existing ContentTags logic.

Do you mean to create a new migration in order to move all tags from the tables `space` and `user` into the table `content_tag`?

<img width="970" alt="topics" src="https://user-images.githubusercontent.com/6995524/107372552-98069780-6af6-11eb-888c-7259fc8f5813.png">
<img width="1075" alt="user_tags" src="https://user-images.githubusercontent.com/6995524/107372567-9b018800-6af6-11eb-915b-dfd88038205c.png">
<img width="858" alt="space_tags" src="https://user-images.githubusercontent.com/6995524/107372572-9b9a1e80-6af6-11eb-9251-69965c32f432.png">

**Comment by luke-** [comment]
Yes, the existing tags should be migrated. (In the last step)

I'm not sure if we can map these existing space / user tags (contentcontainer) via the `content_tag` table.
Maybe we need to create a new `contentcontainer_tag` table or enhance the `content_tag` for this usecase.

**Comment by luke-** [comment]
@buddh4 do you have any advice for this?

**Comment by yurabakhtin** [comment]
@luke- As first step I have implemented the tag picker for Space without DB modifications, i.e. the tags still are stored in the same single column `Space:tags`. Next step I will implement the same for User container.

PR https://github.com/humhub/humhub/pull/4867:

<img width="960" alt="space_tags" src="https://user-images.githubusercontent.com/6995524/107519159-f8620b80-6bc0-11eb-9382-d1af212dea15.png">

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub/pull/4867/commits/faa3aee9c7769ab6e5e9f62b01535d1c624e3011:

<img width="856" alt="user_tags" src="https://user-images.githubusercontent.com/6995524/107525774-3adb1680-6bc8-11eb-9c80-df2deb1350b1.png">

Please let me know if I should start to implement next step as moving all tags from columns `space:tags` and `user:tags` into new table like `contentcontainer_tag`.

**Comment by luke-** [comment]
@yurabakhtin Looks good for me. Do you see any possibility to also use `content_tag` for this usecase as well or do we really need a new `contentcontainer_tag` table(s)?

**Comment by buddh4** [comment]
Content tags are meant to be assigned to content and not containers, so I we should use another table for this. Also none of the content tag features are used here.

**Comment by luke-** [comment]
@buddh4 Thanks for the clarification.

**Comment by yurabakhtin** [comment]
@luke- I have implemented the moving user and space columns `tags` into the new tables `contentcontainer_tag` and `contentcontainer_tag_relation` - commit https://github.com/humhub/humhub/pull/4867/commits/2830de3a5e5924d8614db6dcf97c35845cb8b6e3.

But please note the columns were used as searchable fields, so probably we should implement to use new tables like I wrote in TODO here https://github.com/humhub/humhub/pull/4867/commits/2830de3a5e5924d8614db6dcf97c35845cb8b6e3#diff-2575cda244a6a074e97e4c57c0249ed08b61d219f392dd082f33af33435d8f79R121-R123 and https://github.com/humhub/humhub/pull/4867/commits/2830de3a5e5924d8614db6dcf97c35845cb8b6e3#diff-c56f756041215843f1483ed466d4718eaa67a7a05d83ac6f3100a85c37d34bceR69-R73. Let me know if I should do this too.

**Comment by yurabakhtin** [comment]
@luke- I have fixed the fixtures data, so tests have no errors, and I think the PR can be merged.

**Comment by luke-** [comment]
@yurabakhtin Looks good for me. Can you please add some tests. Also some tests with the legacy `tags` attribute would also be good.

Btw. The feature is planned for HumHub 1.9,  can you please change the @since notes here.
I would wait with the merge until 1.8 is stable, but then we should also adapt the 1.9 migration guide, because of the "tags" attribute change.

**Comment by yurabakhtin** [comment]
@luke- 

> Btw. The feature is planned for HumHub 1.9, can you please change the @SInCE notes here.

Commit https://github.com/humhub/humhub/pull/4867/commits/06d1d0086f63b1185e57076f8a1c0e3910a6d9bf

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please add some tests. Also some tests with the legacy tags attribute would also be good.

Commit https://github.com/humhub/humhub/pull/4867/commits/8d640f039bd1075c1ea80c0de19e96abb12385ad
