### ISSUE TITLE
Reset of existing email summaries / notifications settings

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4868]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/4736168/107624701-8db1de00-6c5b-11eb-9b93-17037e067819.png)

**Comment by yurabakhtin** [comment]
@luke- I have stared this in PR https://github.com/humhub/humhub/pull/4873, but I think it is not completed yet, because it seems not all notification settings are reset. I will do this later because no time now.

**Comment by luke-** [comment]
@yurabakhtin Looks good so far! Have a nice weekend! :-)

**Comment by yurabakhtin** [comment]
@luke- I have completed the PR, but I think one setting should be reset as well, currently it is not reset even per current User, please see on the screenshot:

<img width="1148" alt="user_settings" src="https://user-images.githubusercontent.com/6995524/107914342-42f1d800-6f73-11eb-8dd0-7177df44cdbb.png">

On my opinion the checkbox setting should be reset on click the grey button "Reset to defaults" and on click new red button "Reset for all users", do you agree?

<img width="1147" alt="general_settings" src="https://user-images.githubusercontent.com/6995524/107914440-7d5b7500-6f73-11eb-98e2-ad7c5e3f9eea.png">

**Comment by luke-** [comment]
@yurabakhtin Yes, I agree, the "Desktop Noticiations" should be also reset.

**Comment by yurabakhtin** [comment]
@luke- 

> Yes, I agree, the "Desktop Noticiations" should be also reset.

Commit https://github.com/humhub/humhub/pull/4873/commits/cea8a91a65b57d6bc93f7ef8496fe06a16c97cac.

**Comment by yurabakhtin** [comment]
@luke- I think this the PR is completed and can be merged.
