### ISSUE TITLE
Default Timezone for Guests

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4871]
### Is your feature request related to a problem? Please describe.

It is possible to define a time zone for a registered user and it is possible to define the time zone of the database server. 

Currently, however, there is no possibility to set the default time zone for guests or newly registered users. 
e.g. the problem affects our hosting clients ( we use  CET time zone and users outside this zone).

**Comment by ArchBlood** [comment]
Maybe something similar to this can be done?

Reverse engineer the code itself to show for guests instead of non-guest and save locally on browser

https://stackoverflow.com/questions/39306867/show-hours-in-users-timezone-in-view

**Comment by buddh4** [comment]
Don't we try to determine the timezone in the installer from the browser? Maybe we could use the same approach here.

**Comment by yurabakhtin** [comment]
@luke- I find here `/admin/setting/basic` the general setting "Server Timezone" that is used on `/user/account/edit-settings` for user setting "TimeZone" if it is not filled yet - https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/controllers/AccountController.php#L119

Maybe we can use the general setting "Server Timezone" for guests or newly registered users?

**Comment by luke-** [comment]
@yurabakhtin The existing timezone setting was necessary because we created entries in the database with "new Expression("NOW")" and partly a different timezone was configured in the database. After we have turned off this behavior (and using time() everywhere), we can remove this setting in the future, but I would wait for a few more versions.

The Guest Timezone is necessary if someone has e.g. a hosting with us in Germany, but the users come mainly e.g. from Japan. Then the DB timezone must still be "Europe/Berlin", but guests need an additional timezone here. 

We should introduce a new setting field "defaultTimeZone", and use this everywhere instead of "timeZone". 
In a later version we can then remove "timeZone". (A new field is probably just to ease the transition.)

**Comment by yurabakhtin** [comment]
@luke- I have started this in PR https://github.com/humhub/humhub/pull/4983:

<img width="857" alt="default_timezone" src="https://user-images.githubusercontent.com/6995524/112989097-37e2b800-916d-11eb-834c-73b3fcf1a922.png">

---

The setting "Server Timezone" is filled on install here https://github.com/humhub/humhub/pull/4983/files#diff-3be885119f7c206d26a3b3b58c296f8a938da2cf7339fcaf91bfb404847bf146R531 so I did same for new created setting "Default Timezone", but I think we should create a migration in order to copy a value from old "Server Timezone" to new "Default Timezone", do you agree this?

---

Also I find the old setting "Server Timezone" in the modules "Calendar" and "External Calendar", as I understand we should replace this with new "Default Timezone", right?

**Comment by luke-** [comment]
@yurabakhtin Yes, a migration would be fine. Regarding the modules: Yes, would be great. We should also add a deprecated notice about the "timeZone" in the code and documenation: https://github.com/humhub/documentation/blob/develop/docs/develop/modules-migrate.md#migrate-from-18-to-19

**Comment by yurabakhtin** [comment]
@luke- 

> Yes, a migration would be fine

Commit https://github.com/humhub/humhub/pull/4983/commits/d325a66ad5d5bab107571bc5a1898ecf340224f2

**Comment by yurabakhtin** [comment]
@luke- 

> Regarding the modules: Yes, would be great.

PRs https://github.com/humhub/humhub-modules-calendar/pull/236, https://github.com/humhub-contrib/external_calendar/pull/25.

**Comment by luke-** [comment]
@yurabakhtin Yes, just add a bullet point to version 1.9. We will go through the texts again before the release and correct them if necessary.

**Comment by yurabakhtin** [comment]
@luke- Ok, https://github.com/humhub/documentation/blob/develop/docs/develop/modules-migrate.md#migrate-from-18-to-19, commit https://github.com/humhub/documentation/commit/16e4a0bf1b4015d08c80217648fab81be10b2ebd.

**Comment by luke-** [comment]
@yurabakhtin :+1:
