### ISSUE TITLE
Option to rename "Spaces"

### ISSUE THREAD

**Issue by Abatjour3407** [humhub/humhub#4872]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Ability to rename Spaces to e.g. "Clubs", "Communities", "Departments", etc.

### Describe alternatives you've considered
I did a grep search of all the files including the word "spaces"... Lol x_x

**Comment by ArchBlood** [comment]
Space is kind of a special case word when it comes to HumHub so it's not really allowed to be changed not even in translation overwriting

**Comment by ArchBlood** [comment]
See #4455, I personally would like to generalize the term in some places and not all
