### ISSUE TITLE
Mobile Text Indicator Position

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#4876]
### What steps will reproduce the problem?

Here are the steps that I've found to reproduce this issue;

- Place a link or random text
- Go to beginning position of the post and start to type out a message
- Press space and it will move the position of the text indicator

### What is the expected result?
A space should just make a space not move the position of the indicator

### What do you get instead?
The indicator is moved forward by 5 characters

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.x & 1.8
| PHP version      | 7.3
| Operating system | CloudLinux

**Comment by ArchBlood** [comment]
Could be related to #4858

**Comment by luke-** [comment]
Unfortunately, I can't reproduce it either.

@buddh4 Can you please take a look?

**Comment by buddh4** [comment]
Could recreate https://github.com/humhub/humhub/issues/4858 but not this issue.

**Comment by buddh4** [comment]
@ArchBlood which device and browser are you using to reproduce this?

**Comment by ArchBlood** [comment]
> @ArchBlood which device and browser are you using to reproduce this?

I'm using PWA by latest version of Chrome mobile browser

**Comment by ArchBlood** [comment]
Here's some screenshots of the issue in action

![Screenshot_20210217-092345.png](https://user-images.githubusercontent.com/35392110/108217770-fa1c5980-7101-11eb-8d0d-ca0e589e67a8.png)
![Screenshot_20210217-092407.png](https://user-images.githubusercontent.com/35392110/108217788-fdafe080-7101-11eb-9c2d-6130b86ee6eb.png)

**Comment by ArchBlood** [comment]
The reason I say this could be related to #4858 is because this only happens with rich text features, like linking and mentioning :thinking:

**Comment by buddh4** [comment]
@ArchBlood which keyboard are you using `Settings -> System -> Language & input`

**Comment by ArchBlood** [comment]
> @ArchBlood which keyboard are you using `Settings -> System -> Language & input`

Gboard is the default keyboard input, not changed it since I got it

**Comment by buddh4** [comment]
Ok, could reproduce it but only with Gboard not with SwiftKey.

**Comment by buddh4** [comment]
This seems to be a general issue with prosemirror in combination with Gboard, so I let this on hold for now.

**Comment by ArchBlood** [comment]
No longer seeing this issue as of now it can be closed unless it's still visible by reply fields.
