### ISSUE TITLE
Conflicts on multiple onBeforeControllerAction redirects

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4890]
See discussion and ideas here: https://github.com/humhub-contrib/legal/issues/16

**Comment by luke-** [comment]
Some modules or actions are intercepts requests:

e.g.

- Maintenance mode
- Must change password
- Two factor auth
 -Legal module
- Live poll
- Rest


@buddh4 's Idea:

All core controller/actions could be directly defined within the module e.g. by an similar array as you mentioned.
Some use-cases above maybe could be solved by some kind of controller interface, so the modules can kind of negotiate and somehow manage the priority:

Very rough concept:

MyController extends Controller implements RequestInterceptionController
In modules:

if($event->action->controller instanceof RequestInterceptionController && $this->priority < $event->action->controller->getPriority()) {
    return;
}
Similar with the rest controller, there should be a marker interface for this, or the rest controllers could also implement the interface above.

**Comment by yurabakhtin** [comment]
@luke- As I understand you prefer the approach with controller interface, but please note we have one case for whole module, I mean the `rest` module here `https://github.com/humhub-contrib/legal/blob/master/Events.php#L97`, i.e. all controllers of the module should be excluded. I think it is not good idea to use the interface for each controller of the module, because we should edit many files of each controller and don't forget this for all future controllers.

It is why I suggested to use some new module config with list of actions, where we can use `*` for all actions. Of course my suggested var name was not clear, so probably we can use your `$doNotInterceptActionIds` or `$noInterceptActions`.

So I think each module should define what its actions cannot be intercepted by other modules, for example:

- Module `user`:

```php
public $doNotInterceptActionIds = [
    ['account', 'delete'],
    'auth', // means ALL actions of the controller 'auth'
];
```

- Module `mail`:

```php
public $doNotInterceptActionIds = [
    ['mail', '*'] // means All actions of the controller 'mail'
];
```

- Module `poll`:

```php
public $doNotInterceptActionIds = [
    'poll'
];
```

- Module `rest`:

```php
public $doNotInterceptActionIds = [
    '*' // means All actions of ALL controllers of the module
];
```

- Module `twofa`:

```php
public $doNotInterceptActionIds = [
    'check'
];
```

Do you agree this single config array per Module or you still need a config array per Controller?

**Comment by luke-** [comment]
@yurabakhtin Thanks for the overview.
Wouldn't it  possible e.g to. `BaseController` of the Rest module to set it centrally for all Rest controllers. e.g. `$doNotInterceptActionIds = ['*'];`?

https://github.com/humhub/humhub-modules-rest/blob/c3dfa5309f65c3872e86f8ff4d8fdd9ffd2d5077/components/BaseController.php#L29

If we're abble to find a "one place" solution for the Rest module, I would prefer the controller solution.
Otherwise we can implement it in the module.

**Comment by yurabakhtin** [comment]
@luke- Yes, you are right the `BaseController` is used for all rest controllers except of `AdminController` but we should not use the filter there because this controller is not used for api endpoints.

So we can implement the controller solution. Should I start this?

**Comment by luke-** [comment]
@yurabakhtin Ok. Yes please start!

**Comment by yurabakhtin** [comment]
@luke- Please check how I implemented this in PRs above, if all ok I should to investigate how we can use new `Controller->isNotInterceptedAction()` in:

- Maintenance mode (probably here https://github.com/humhub/humhub/blob/enh/4890-do-not-intercept-action-ids/protected/humhub/components/access/ControllerAccess.php#L542)
- Must change password (probably here https://github.com/humhub/humhub/blob/enh/4890-do-not-intercept-action-ids/protected/humhub/modules/user/components/User.php#L237)
- Two factor auth (https://github.com/humhub/humhub-modules-twofa/blob/master/Events.php#L57)

**Comment by luke-** [comment]
@yurabakhtin Sounds good, I've already merged the other PRs if possible.

**Comment by yurabakhtin** [comment]
@luke- The changes in PR https://github.com/humhub/humhub-modules-polls/pull/84 was done by mistake, correct place is in core module `live` - https://github.com/humhub/humhub/pull/4966/commits/974e1606193c1fd297d37f4d537f88ca488ec9d2.

**Comment by luke-** [comment]
@yurabakhtin Ok. Should we leave the mail  module exception?

**Comment by yurabakhtin** [comment]
@luke- I am trying to find why it was added here https://github.com/humhub-contrib/legal/commit/fc182943#diff-666c020a6d1e6a59ba261ba9316aaa19e27dbd851bcc4fdcaecaa278ddc96c10R96

**Comment by luke-** [comment]
@yurabakhtin I think it is enough to add the following action:  https://github.com/humhub/humhub-modules-mail/blob/master/controllers/MailController.php#L405

**Comment by yurabakhtin** [comment]
@luke- Ok, fixed in commit https://github.com/humhub/humhub-modules-mail/pull/220/commits/f0a0a7fca9bada14200e5383dd42bf2ea0003905
