### ISSUE TITLE
No streamExcludes option when loading single stream entry 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4898]
### Problem

If a single content should be loaded (e.g. permalink) the config file option StreamExcludes should not be applied.

- Add Files to Stream Excludes
```
    'modules' => [
        'stream' => [
            'streamExcludes' => [
                'humhub\modules\cfiles\models\File',

            ]
        ]
    ],
```
- Use File Module and click `Shot Post` in Context Menu
![image](https://user-images.githubusercontent.com/4736168/108508395-09df9d80-72bc-11eb-87f6-a78ab7b29f31.png)

- Shown URL is not working

### Describe alternatives you've considered

To handle this special case in all modules is not ideal. Could also be good for the upcoming content Detail View...

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/4962

**Comment by luke-** [comment]
@yurabakhtin Thanks!
