### ISSUE TITLE
1.8: Positions of Comment / Like interchanged under posts

### ISSUE THREAD

**Issue by smashm** [humhub/humhub#4907]
On the first answer level the positions of the _comment_ and _like_ links are interchanged. 
Until 1.7.x _comment_ was on the first position from the left. 
The next answer levels have maintained this order.

![Bildschirmfoto 2021-02-22 um 16 25 54](https://user-images.githubusercontent.com/60502320/108729323-b030da80-752a-11eb-8338-675ee78f9a0a.png)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4909
