### ISSUE TITLE
1.8: Maintenance mode - activating can be misleading; users are still logged in

### ISSUE THREAD

**Issue by smashm** [humhub/humhub#4910]
See my two comments in the community at the beta-news: 
https://community.humhub.com/content/perma?id=236860

- Maintenance Message: missing linebreak between the standard text and the individual supplement

- Misleading activation process

- Different views for user in the mode

**Comment by yurabakhtin** [comment]
@luke- 

> - Maintenance Message: missing linebreak between the standard text and the individual supplement

Commit https://github.com/humhub/humhub/pull/4911/commits/138ac98ef8634a0c57347a3defef827f80b330d0

> - Misleading activation process
> - Different views for user in the mode

I have read the comments there but cannot understand what to do for these 2 points, could you tell me more details? Thanks.

**Comment by smashm** [comment]
@yurabakhtin 
Hi, maybe this hint put you in the right direction, but I'm not a coder.

> * Different views for user in the mode

When opening an humhub instance by examplewebserver.adress/humhub/ user in closed communities (e.g. humhub community) are forwarded to the login site examplewebserver.adress/humhub/index.php?r=user%2Fauth%2Flogin

In open communities where unregistered guest can see some content, they are forwarded to /humhub/index.php?r=dashboard%2Fdashboard

As described in the community, users who try to login in open communities, are forwarded/redirected after the (of course failure) attempt to the closed view, when the maintenance mode is active.

From my point of view (layman) it should be enough to change the redirect from `index.php?r=user%2Fauth%2Flogin` to `index.php?r=dashboard%2Fdashboard`, because the dashboardlink is forwarded anyway to the auth-login, when the guestview is not enabled.

**Comment by luke-** [comment]
@smashm Thanks for the issues. Two of your problems have already been fixed by @yurabakhtin, I have also created separate issues: 
https://github.com/humhub/humhub/issues/4912
https://github.com/humhub/humhub/issues/4913
