### ISSUE TITLE
1.8: Maintenance Mode - Guest Access

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4912]
### What steps will reproduce the problem?

- Enable Guest Access
![image](https://user-images.githubusercontent.com/4736168/108844626-a667af80-75dc-11eb-9f72-90d34903528b.png)
- Enable Maintenance Mode
- Open Dashboard e.g. 
 

### What is the expected result?

- Show Admin Login

### What do you get instead?

See Dashboard

### Additional info

Guest Mode show be disabled during Maintance Mode

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4914
