### ISSUE TITLE
Warning dialog before before leaving page with edited content

### ISSUE THREAD

**Issue by rcheetah** [humhub/humhub#4915]
### Is your feature request related to a problem? Please describe.
Yes! At the moment when you type content into any form (comments, wall entrys, wiki pages …) it is completely lost as soon as anything leads you from the page. This can be an unintended click onto any link, or losing focus of the input field and hitting the backspace button to remove the last characters etc. All of this results in any unpublished content being irreversibly lost. So many times I lost paragraphs full of text, or even entire discussion protocols (backspace problem on wiki pages). I issued this as a feature request, but if you consider UX it’s more of a bug report.

### Describe the solution you'd like
There are many solutions possible. But I think the simplest is the same, that any other similar website uses. Add a warning dialog on the page unload event (“You have unsaved content! Do you really wan’t to leave this page?”). When this is defined in the HumHub base for any form, then it will also work on any modules like the wiki, tasks, and so on. 

### Describe alternatives you've considered
There are other ways, like duplicating content into a cookie and deleting the cookie on successful save. So if the content would not be saved, it could be reentered into the form. This would work for page reloads, could be a little tricky for navigation to another page and then back. I think the warning dialog would be the best way.

**Comment by luke-** [comment]
@rcheetah We are working on this issue for HumHub 1.9.

For the Wiki module this will be available earlier.

Related: https://github.com/humhub/humhub/pull/4776
Related: https://github.com/humhub/tasks/issues/25

**Comment by rcheetah** [comment]
Great, I look forward to it :D
