### ISSUE TITLE
Download my data ability for User

### ISSUE THREAD

**Issue by spoorun** [humhub/humhub#4916]
In many jurisdictions, online services are required to provide the ability to give Users and for held connected with them (with exceptions). 

For example in UK a "Subject Access Request" under Freedom of Information, GDPR in Europe, and similar elsewhere.

Currently, there is no simple way for a user to make such a request, and even less of a means for an admin to provide that information easily.

The ideal way of confirming with this is to provide by default a "Download my data" button on User settings (which could be turned off in Admin settings). Other online platforms have similar functions.

(This would also assist in the event someone wishes to leave a community, close an account, or move jobs, but wishes to retain information held on them as they often have a right to.)

**Comment by luke-** [comment]
https://github.com/humhub-contrib/legal/issues/20

I have moved this RFE to the Legal Tool module. This functionality is planned for this module.

**Comment by lisandi** [comment]
The Legal Module still don't offer the ability for a user to download all HIS/Her content "Download my Data" - As this is a serious GDPR issue I like to ask when this feature finally would get implemented.

Additional the legal module should be able to be named "Impressum" as especially in Germany it has to be called "Impressum" and has to be reached with only one click. A link on the new Spaces Directory is completely missing but according to GDPR the link to the "Impressum" has to be present on any page.

**Comment by ArchBlood** [comment]
> Additional the legal module should be able to be named "Impressum" as especially in Germany it has to be called "Impressum" and has to be reached with only one click. A link on the new Spaces Directory is completely missing but according to GDPR the link to the "Impressum" has to be present on any page.

Currently you can change the name to whatever is preferred see the screenshot attached;

![Screenshot_1](https://user-images.githubusercontent.com/35392110/189549137-9ba0a54a-4682-4959-b116-e68458558a61.png)

If the title doesn't change with language then I suggest that a p/r or more information be given on this, I also agree that there are some footers missing on some important pages that should be addressed.
