### ISSUE TITLE
Option to hide User group status in directory

### ISSUE THREAD

**Issue by SocioHub-FID** [humhub/humhub#4917]
Hi HumHub-Team & Community :)

### Is your feature request related to a problem? Please describe.

In our HumHub-setup we added an additional user group (btw - great feature that this is possible :thumbsup:). Just now we noticed that the user group for all users is generally shown publicly in the member directory (e.g. here https://community.humhub.com/directory/members). Our data privacy officer explained that is now a clean way regarding the implementation of GDPR.

### Describe the solution you'd like

Our idea would be to add an option in the admin menu to hide the user group in the member directory.

### Describe alternatives you've considered

---

We are currently using HumHub version 1.3.20.

---

Thanks to the HumHub-Team & community for the great work & product :)

**Comment by ArchBlood** [comment]
You can hide user groups in the admin area already
![Screenshot_3](https://user-images.githubusercontent.com/35392110/109003048-f3976000-7674-11eb-81fc-823f540d8454.png)
In addition you can also hide the Directory from guests as well by way of the /protected/config/common.php file
https://docs.humhub.org/docs/admin/advanced-configuration/#module-configurations

**Comment by ArchBlood** [comment]
You can also remove `/directory/members` from view by theme overwrite `/protected/humhub/modules/directory/views/directory/members.php` becomes `/themes/YOUR_THEME/views/directory/directory/members.php` just remove what code you don't want viewed

**Comment by SocioHub-FID** [comment]
Thanks @ArchBlood for the quick response. Sorry I guess my description was not too precise. What I meant was this view:

![image](https://user-images.githubusercontent.com/58687517/109004066-88678100-76a8-11eb-9160-8b5f12b73934.png)

The option you described (https://github.com/humhub/humhub/issues/4917#issuecomment-785054718) has now influence on this.

**Comment by ArchBlood** [comment]
> Thanks @ArchBlood for the quick response. Sorry I guess my description was not too precise. What I meant was this view:
> 
> ![image](https://user-images.githubusercontent.com/58687517/109004066-88678100-76a8-11eb-9160-8b5f12b73934.png)
> 
> The option you described ([#4917 (comment)](https://github.com/humhub/humhub/issues/4917#issuecomment-785054718)) has now influence on this.

Easy fix, removed this line in your theme overwrite 
https://github.com/humhub/humhub/blob/90ec96678822041c5ee479947faa23ffc0440c95/protected/humhub/modules/directory/views/directory/members.php#L64

**Comment by luke-** [comment]
I would only display group names here that are also displayed in the directory.

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look? We should only display groups besides the user which are also marked as "Show in directory". -> Target Branch would be develop (1.9)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/4920

**Comment by luke-** [comment]
@yurabakhtin  Thanks!
