### ISSUE TITLE
Richtext gets focus when collapsing comments

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4918]
In case of clicking the "Comment" link of a stream entry the comment section closes in case its already opened/visible. Both, opening and closing the comment section will trigger a focus event of the comment input. When closing the comment section, the richtext should not be focused, otherwise the mobile keyboard will be activate for a short moment.

Also we should think about if this behavior maybe should be blocked on mobile (or at all?). On mobile you scroll from top to bottom and expect to focus the comment input to write a comment when clicking on the comment link no matter if the comment section is opened or closed.

Clicking on "Comment" shoud always focus the comment input at least on mobile. Is the closing of the comment section even be used that often or really useful?

- Should we remove the collapse feature of the comment section?
- Should we only remove it on mobile?
- At least fix the focus behavior.

**Comment by luke-** [comment]
I have just discussed this with @Semir1212 and we couldn't really find a good solution for this either. 
The feature to collapse comments is useful for comments & subcomments.

Probably it would be good rather try to fix the misbehavior until we have a good idea/concept here.

BTW: On the dashboard in our community there is a long post right now (with many comments).
Here, the comment link  is also behaving very strangely. When you click it, the comments collapse and the browser scrolls down automatically.

**Comment by buddh4** [comment]
I think at least on mobile its more annoying if you click on comment or reply and not being able to comment, but close the comment section instead. This is very misleading. In order to comment on mobile, you have to scroll down manually and since the mobile view is streched its just a bad usability.

I'd suggest either hide the comments and replys on mobile by default or maybe add another link (maybe on the right side) for collapsing a comment section. Its not obious that clicking on `Comment` or `Reply` closes a section anyways.

**Comment by buddh4** [comment]
I'll fix the focus issue, but we should find a solution regarding the overall misbehavior.

**Comment by buddh4** [comment]
I've opened a discussion at https://github.com/humhub/humhub/issues/4925

**Comment by luke-** [comment]
Sounds good, so for us it would be the preferred solution to initially hide the comments by default on mobile. By clicking on comment (show and focus).
