### ISSUE TITLE
naming a Customprofilfield = status causes ambiguous sql query

### ISSUE THREAD

**Issue by Andre0383** [humhub/humhub#4921]
### What steps will reproduce the problem?

* create a new category
* create a new field:
**  internalname status
** name status
** type selectlist with status1 => mystatus1, status2 => mystatus2
* select a status in personal profil
* save

### What is the expected result?

* having the possibility to select a status in profil

### What do you get instead?

* worked fine for a couple of time
* errormessage after half an hour or so
![screenshot](https://user-images.githubusercontent.com/79633947/109134539-6d534a80-7756-11eb-9e55-ea357d841eca.jpeg)
* realy sorry that i cant provide you with a full errormessage other than this mobil screenshot, i was away from keyboard when the error occurs

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.2
| PHP version      | 7.4.15
| Operating system | dont know, its a sharing hosting enviroment

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'status' in where clause is ambiguous in /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Command.php:1293 Stack trace: #0 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute() #1 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute('SELECT COUNT(*)...') #2 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Command.php(427): yii\db\Command->queryInternal('fetchColumn', 0) #3 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Query.php(494): yii\db\Command->queryScalar() #4 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(352): yii\db\Query->queryScalar('COUNT(*)', Object(yii\db\Connection)) #5 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Query.php(366): yii\db\ActiveQuery->queryScalar('COUNT(*)', Object(yii\db\Connection)) #6 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/ActiveDataProvider.php(169): yii\db\Query->count('*', NULL) #7 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(169): yii\data\ActiveDataProvider->prepareTotalCount() #8 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/ActiveDataProvider.php(106): yii\data\BaseDataProvider->getTotalCount() #9 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(101): yii\data\ActiveDataProvider->prepareModels() #10 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(114): yii\data\BaseDataProvider->prepare() #11 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(155): yii\data\BaseDataProvider->getModels() #12 /homepages/32/d13462383/htdocs/intern/protected/humhub/modules/admin/widgets/DashboardApproval.php(20): yii\data\BaseDataProvider->getCount() #13 /homepages/32/d13462383/htdocs/intern/protected/humhub/components/Widget.php(63): humhub\modules\admin\widgets\DashboardApproval->run() #14 /homepages/32/d13462383/htdocs/intern/protected/humhub/widgets/BaseStack.php(90): humhub\components\Widget::widget('[<span class="s...') #15 /homepages/32/d13462383/htdocs/intern/protected/humhub/components/Widget.php(63): humhub\widgets\BaseStack->run() #16 /homepages/32/d13462383/htdocs/intern/protected/humhub/modules/dashboard/views/dashboard/index.php(28): humhub\components\Widget::widget('[<span class="s...') #17 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/View.php(348): require('/homepages/32/d...') #18 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/homepages/32/d...', '[<span class="s...') #19 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/homepages/32/d...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #20 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/Controller.php(409): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #21 /homepages/32/d13462383/htdocs/intern/protected/humhub/modules/dashboard/controllers/DashboardController.php(81): yii\base\Controller->render('index', Array) #22 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #23 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #24 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #25 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #26 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array) #27 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #28 /homepages/32/d13462383/htdocs/intern/index.php(25): yii\base\Application->run() #29 {main} Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'status' in where clause is ambiguous The SQL being executed was: SELECT COUNT(*) FROM `user` LEFT JOIN `profile` ON `user`.`id` = `profile`.`user_id` WHERE `status`=2 in /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Schema.php:677 Stack trace: #0 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...') #1 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute('SELECT COUNT(*)...') #2 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Command.php(427): yii\db\Command->queryInternal('fetchColumn', 0) #3 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Query.php(494): yii\db\Command->queryScalar() #4 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(352): yii\db\Query->queryScalar('COUNT(*)', Object(yii\db\Connection)) #5 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/db/Query.php(366): yii\db\ActiveQuery->queryScalar('COUNT(*)', Object(yii\db\Connection)) #6 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/ActiveDataProvider.php(169): yii\db\Query->count('*', NULL) #7 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(169): yii\data\ActiveDataProvider->prepareTotalCount() #8 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/ActiveDataProvider.php(106): yii\data\BaseDataProvider->getTotalCount() #9 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(101): yii\data\ActiveDataProvider->prepareModels() #10 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(114): yii\data\BaseDataProvider->prepare() #11 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(155): yii\data\BaseDataProvider->getModels() #12 /homepages/32/d13462383/htdocs/intern/protected/humhub/modules/admin/widgets/DashboardApproval.php(20): yii\data\BaseDataProvider->getCount() #13 /homepages/32/d13462383/htdocs/intern/protected/humhub/components/Widget.php(63): humhub\modules\admin\widgets\DashboardApproval->run() #14 /homepages/32/d13462383/htdocs/intern/protected/humhub/widgets/BaseStack.php(90): humhub\components\Widget::widget('[<span class="s...') #15 /homepages/32/d13462383/htdocs/intern/protected/humhub/components/Widget.php(63): humhub\widgets\BaseStack->run() #16 /homepages/32/d13462383/htdocs/intern/protected/humhub/modules/dashboard/views/dashboard/index.php(28): humhub\components\Widget::widget('[<span class="s...') #17 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/View.php(348): require('/homepages/32/d...') #18 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/homepages/32/d...', '[<span class="s...') #19 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/homepages/32/d...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #20 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/Controller.php(409): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #21 /homepages/32/d13462383/htdocs/intern/protected/humhub/modules/dashboard/controllers/DashboardController.php(81): yii\base\Controller->render('index', Array) #22 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #23 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #24 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #25 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #26 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array) #27 /homepages/32/d13462383/htdocs/intern/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #28 /homepages/32/d13462383/htdocs/intern/index.php(25): yii\base\Application->run() #29 {main} Additional Information: Array ( [0] => 23000 [1] => 1052 [2] => Column 'status' in where clause is ambiguous )

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
@yurabakhtin We should disallow all possible name conflicts (user table, profile table, space table, membership table, ...) on the internal name. Better a few field names more than too few.

Can you implement a check here?

**Comment by buddh4** [comment]
Can't we just add the table prefix in the query?

**Comment by luke-** [comment]
Maybe we can do both here.

But there are probably a lot database queries that join User+Profile.

**Comment by buddh4** [comment]
Its probably to late for this but couldn't we prefix the profile columns like `custom_status` by default.

**Comment by luke-** [comment]
Maybe something for the planned big profile rewrite 2035 :-)

@yura Thanks!

**Comment by yurabakhtin** [comment]
@buddh4 Yes, a prefix would be better than without prefix, but really I don't like the dynamic structure on the table `profile`, it would be better to keep there only 3 columns `user_id`, `profile_field_id` and `value`, but probably I don't know why it was created by that way.
