### ISSUE TITLE
Some Whitespaces breaks file upload / validation

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4923]
### What steps will reproduce the problem?

[test.zip](https://github.com/humhub/humhub/files/6042345/test.zip)

- Unpack zip
- Try to upload the file
- Receive error 
![image](https://user-images.githubusercontent.com/4736168/109141732-5c0e3c00-775e-11eb-86e6-765b360e0808.png)

### What is the expected result?

Upload filed

The error is caused by a non regular white space (first whitespace in test file name).

Probably it would be good if in such cases we could simply replace the invalid characters with "_".
In the current case, of course, a normal space would be ideal.

**Comment by ArchBlood** [comment]
Possible solutions that I could see working for such a case

```php
$filename = preg_replace('/\s+/', '_', $filename);
```
or
Not really a fan of this method :thinking:
```php
$filename = trim(str_replace(' ', '_', $_FILES['userfile']['name']));
```

**Comment by buddh4** [comment]
We should probably alsow escape all charachters we do not allow: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/Module.php#L27

**Comment by yurabakhtin** [comment]
@luke- @buddh4 I have debugged the file name and detected that the first char(between words "TestFile" and "The") which like space is really a not one space char but this is two chars `\xC2` + `\xA0`.
The `\xC2` was not denied but the `\xA0` was denied, I have created a PR https://github.com/humhub/humhub/pull/4928. If you think the char should be allowed then you can merge, or just rename the file to correct space char that has code `\x20`.

**Comment by buddh4** [comment]
@yurabakhtin as luke noted, we probably should just replace (any) invalid characters with an underscore or something else.

**Comment by luke-** [comment]
@yurabakhtin Hmm, I'm not sure if we should allow such a "special" chars. I would really prefer the solution of simply replacing invalid characters with an underscore. The filter is relatively permissive anyway, so it should rarely be the case.

**Comment by yurabakhtin** [comment]
@luke- @buddh4 Ok, I have reverted the pattern and implemented the replacement all not allowed chars with underscore '_' - https://github.com/humhub/humhub/pull/4928/commits/49122f96088eab5fc9621c8425dd785d822f436b.

**Comment by yurabakhtin** [comment]
I fixed tests for the changes in the file name validator - https://github.com/humhub/humhub/pull/4928/commits/6d6a1e3c5d3228064412e62b85a91d2981a85247
