### ISSUE TITLE
Don't show additional links when multiple photos are uploaded

### ISSUE THREAD

**Issue by spoorun** [humhub/humhub#4929]
_Currently_
User uploads multiple images
Below the images an additional separate line is shown for each image showing the filename and size
When User hovers over an image they can view the filename, but not the size

This lengthens the stream, sometimes doubling the size of the post, and reduces the aesthetic value and decreases usability
Filenames and sizes can be important, but there's a trade off and being able to obtain them on 'hover over' strikes a balance

_Preferable_
User uploads multiple images
No extra lines are shown below image
When User hovers over an image they can view the filename, **and the size**

![image](https://user-images.githubusercontent.com/627140/109292221-f08da280-7821-11eb-9ea3-8391d9662229.png)

**Comment by spoorun** [comment]
Or allow the User posting to determine whether to show the additional links or not, so they are only shown when required.

**Comment by luke-** [comment]
Do you know this option?
![image](https://user-images.githubusercontent.com/4736168/109301695-951adf00-7838-11eb-84de-14812cb32436.png)

**Comment by spoorun** [comment]
Thanks @luke- :smiley:
