### ISSUE TITLE
Parent navigations not highlighted for sub section "Profile Permissions" (and LDAP)

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4931]
![grafik](https://user-images.githubusercontent.com/9800854/109432520-e16a4880-7a0b-11eb-8199-7f1869c63082.png)

![grafik](https://user-images.githubusercontent.com/9800854/109432531-ef1fce00-7a0b-11eb-8244-8d669759a181.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4933.
