### ISSUE TITLE
Images in email

### ISSUE THREAD

**Issue by superseby2** [humhub/humhub#4935]
### Is your feature request related to a problem? Please describe.

When receiving notification by email, the content is now nicely output from Markedown (good job!!) 
for everything except images. Trying both images resulting from a copy/paste or form an attachment in a Post. 

### Describe the solution you'd like

It would be nice to have images rendered as well.

**Comment by buddh4** [comment]
We'd probably need to attach such images to the mail since in many installations images are not accessible without a login.

**Comment by superseby2** [comment]
:thinking: ... how user's profile images are handled for those installations where a login is required? In our setup, you need to have an account but you can see profile's user image in emails (summaries or post notification). 
Can't we have the same approche for post images? It makes content public indeed, but you will still need to figure out the path (could be UUID-like) + we could make those images expirable?

Having images as attachment only, to me, would be bleh ;)

**Comment by luke-** [comment]
Images as attachments can of course also be embedded in the e-mail content as an image.
Otherwise it would also be a solution to allow optional file access via a direct even without login.

**Comment by superseby2** [comment]
If I could vote :) I would vote for solution number 2. Because embedding one or more images could lead to super big emails and we might run into problems at some point.
Making images available via a link seems to me a better way to do this.

My 2 cents.

**Comment by luke-** [comment]
@yurabakhtin We should implement the new parser RichTextToEmailHtmlConverter in notifications that already use RichText in emails (e.g. New Comment or New Content) to be able to display images here as well.

**Comment by yurabakhtin** [comment]
@luke- To implement the new parser we should merge the PR https://github.com/humhub/humhub/pull/5038#issuecomment-825529282.

**Comment by luke-** [comment]
@yurabakhtin is merged and also available in the `develop` branch.

**Comment by yurabakhtin** [comment]
I think to apply css rule `max-width: 100%` for all images in email messages, because currently it looks not good:

<img width="2119" alt="big_image" src="https://user-images.githubusercontent.com/6995524/115871595-6cceeb80-a449-11eb-9a6c-ee6485ea9236.png">

**Comment by luke-** [comment]
@yurabakhtin Yes, can you please add this?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5041, yes I have fixed image style:

<img width="628" alt="email_image_preview" src="https://user-images.githubusercontent.com/6995524/115889327-8299dc00-a45c-11eb-80e4-1ffb4d67b325.png">

**Comment by superseby2** [comment]
Thanks for this guys. It looks awesome!
