### ISSUE TITLE
Installer Sample Emoji Broken

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4936]
### What steps will reproduce the problem?

- Fresh install HumHub

### What is the expected result?

See Emoji on sample post

### What do you get instead?

![image](https://user-images.githubusercontent.com/4736168/109686890-fe755780-7b82-11eb-834e-62584049ab9c.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8

**Comment by buddh4** [comment]
The sample uses legacy emoji style. The legacy richtext parser is deactivated in new installations since 1.8

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4937=
<img width="761" alt="fixed_emoji" src="https://user-images.githubusercontent.com/6995524/109755665-73827480-7bf7-11eb-84e9-e75f185ff312.png">

**Comment by luke-** [comment]
Thanks!
