### ISSUE TITLE
Add css variables to theme

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4938]
Currently the only way of accessing theme variables is by calling `Yii::$app->view->theme->variable('info')`. Modules are more or less forced to set inline styles in order to keep themable.
Using css variables for our theme colors etc. would heavily ease the theming of modules and theming in general. Related issues:

- https://github.com/humhub/humhub-modules-mail/issues/218
- https://github.com/humhub/humhub/issues/3982
- https://github.com/humhub/humhub/issues/4539
- https://github.com/humhub/humhub-modules-mail/issues/32

**Comment by spoorun** [comment]
@luke- just to be clear, is this now resolved?

**Comment by luke-** [comment]
Yes see here: https://github.com/humhub/humhub/pull/6081
