### ISSUE TITLE
Typo in /user/account/edit/ Menu | de |"Benachrichtungen"

### ISSUE THREAD

**Issue by klauswagner** [humhub/humhub#4940]
### What steps will reproduce the problem?
German Language: Typo in /user/account/edit/ -Menu: "Benachrichtungen" instead of "Benachrichtigungen"

Found in `/protected/humhub/modules/user/messages/de/account.php`
`'Notifications' => 'Benachrichtungen',`

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.0 and all lower versions

**Comment by luke-** [comment]
Thanks will be fixed with 1.8.1
https://github.com/humhub/humhub/pull/4941/files
