### ISSUE TITLE
Database Migration to Humhub 1.8.0 went wrong

### ISSUE THREAD

**Issue by smitti** [humhub/humhub#4946]
### What steps will reproduce the problem?
Update via browser started
### What do you get instead?
        Yii Migration Tool (based on Yii v2.0.40)

Total 5 new migrations to be applied:
	m201130_073907_default_permissions
	m201130_073908_disable_legacy_richtextparser
	m201228_064513_default_group
	m210111_105355_hash
	m210203_122333_profilePermissions

*** applying m201130_073907_default_permissions
    > create table contentcontainer_default_permission ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'contentcontainer_default_permission' already exists
The SQL being executed was: CREATE TABLE `contentcontainer_default_permission` (
	`permission_id` varchar(150) NOT NULL,
	`contentcontainer_class` char(60) NOT NULL,
	`group_id` varchar(50) NOT NULL,
	`module_id` varchar(50) NOT NULL,
	`class` varchar(255),
	`state` tinyint(1)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.0
| PHP version      | 7.4
| Operating system | Linux

**Comment by buddh4** [comment]
Please check the logs again, the error suggests that the migration was running a second time, the error of the first run would be interesting.

**Comment by smitti** [comment]
Latest errors:

FEHLER  Thu, 04 Mar 2021 18:13:38 +0100 yii\base\UnknownMethodExceptionyii\base\UnknownMethodException: Calling unknown method: humhub\modules\user\components\User::mustChangePassword() in /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Component.php:301 Stack trace: #0 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/humhub/modules/live/controllers/PollController.php(56): yii\base\Component->__call('mustChangePassw...', Array) #1 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(179): humhub\modules\live\controllers\PollController->beforeAction(Object(yii\base\InlineAction)) #2 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('', Array) #3 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('live/poll', Array) #4 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request)) #5 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/index.php(25): yii\base\Application->run() #6 {main}
FEHLER  Mon, 01 Mar 2021 14:05:01 +0100 queueCould not execute queued job! Message: Job must be a JobInterface instance instead of false. Trace:#0 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2-queue/src/Queue.php(230): yii\queue\Queue->unserializeMessage('O:53:"humhub\\mo...') #1 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('60953', 'O:53:"humhub\\mo...', '300', '1') #2 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('60953', 'O:53:"humhub\\mo...', '300', '1', '22016') #3 [internal function]: yii\queue\cli\Command->actionExec('60953', '300', '1', '22016') #4 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #5 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #6 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('exec', Array) #7 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('exec', Array) #8 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array) #9 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/exec', Array) #10 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request)) #11 /is/htdocs/wp11141389_5VUUJ7N9W6/b-u-p-daheim.de/protected/yii(29): yii\base\Application->run() #12 {main}

**Comment by buddh4** [comment]
This also is not the error of the update, but nontheless a strange error, seems like some files did not update. The actual update error message most likely includes a snippet of a failed SQL query and was triggered right after the update failed.

**Comment by smitti** [comment]
Sorry, that´s my oldest error. Any ideas, what to do?

**Comment by ArchBlood** [comment]
From my standpoint, I've only seen this happening for users that use MySQL database driver, no problem for MariaDB as of yet :thinking:

**Comment by buddh4** [comment]
You could manually drop the table `contentcontainer_default_permission` and re-run the migration.

I assume the problematic line is:

```
  $this->addPrimaryKey('contentcontainer_default_permission_pk', 'contentcontainer_default_permission', ['permission_id', 'group_id', 'module_id', 'contentcontainer_class']);
```

We had a similar issue in the beta phase, I thought it was fixed, any idea @yurabakhtin ?

**Comment by smitti** [comment]
My Humhub-Installation is running at a shared Virtual Server. How can I run the imigration?

**Comment by smitti** [comment]
How can I re-run the migration?

**Comment by jwleon** [comment]
I have the same problem. Seems that the key is too long when using utf8mb4 collation. Unfortunately, this stopped all migrations from happening, nut just the one for the "content" module. @smitti  when you are on shared hosting, you could create a PHP script (in a .htaccess / .htpasswd protected folder) to execute yii commands. Here it is:

`<?php

$execMigration = '/usr/bin/php73 ' . getenv('DOCUMENT_ROOT') . 'protected/yii migrate/up --includeModuleMigrations=1 --interactive=0';

exec($execMigration , $output, $code);
echo "Code: " . $code . "<br>";
echo "Output: " . "<br>";
echo "<pre>"; print_r($output);
`

**Comment by ArchBlood** [comment]
> I have the same problem. Seems that the key is too long when using utf8mb4 collation. Unfortunately, this stopped all migrations from happening, not just the one for the "content" module. @smitti when you are on shared hosting, you could create a PHP script (in a .htaccess / .htpasswd protected folder) to execute yii commands. Here it is:
> 
> ```
> <?php
> 
> $execMigration = '/usr/bin/php73 ' . getenv('DOCUMENT_ROOT') . 'protected/yii migrate/up --includeModuleMigrations=1 --interactive=0';
> 
> exec($execMigration , $output, $code);
> echo 'Code: ' . $code . '<br>';
> echo 'Output: ' . '<br>';
> echo '<pre>'; print_r($output);
> ```
> 
> Note that as long as the core problem is not fixed, the migration will probably fail again. If you just rerun the migration, it will fail telling you that the table `contentcontainer_default_permission` already exists (from the first failed attempt)...
> 
> For those needing a quick fix for this because of broken upgrade:
> 
> Go into `protected/humhub/modules/content/migrations/m201130_073907_default_permissions.php` and change the following line. Make sure the table `contentcontainer_default_permission` from any failed migration attempt is dropped and then rerun the migration.
> 
> Old: `'permission_id' => $this->string(160)->notNull(),`
> New: `'permission_id' => $this->string(90)->notNull(),`
> 
> The summed up key length of 90 + 60 + 50 + 50 is 250, times 4 (utf8mb4), 1000, which probably is your MySQL driver limitation. Keep in mind that this solution is not really a solution but a dirty quick-hack and needs a real fix when the developers know a better way to handle the problem. Nonetheless, it will not make your system blow up immediately and will, as far as I can tell, not cause any harm until then.

You are correct on this, it comes down to the data pool of the MySQL used, this is why MariaDB isn't heavily affected and all migrations normally run smoothly
I'd think if you increased `max_connections` it would probably help slightly

**Comment by yurabakhtin** [comment]
@buddh4 

> We had a similar issue in the beta phase, I thought it was fixed, any idea @yurabakhtin ?

I fixed that in commit https://github.com/humhub/humhub/commit/2cfe20a9, there was an error about long key because the column `contentcontainer_class` had a size 255 chars, so I changed that to correct 60 because we have same length for the column `class` in the table `contentcontainer`.

When I worked on the bug I have investigated and understood the limit depends in single column length and not on sum of the columns of the index key. I.e. for `utf8mb4` we can use each column with length <= 191, because 767/4 = 191,75, I already explained this here https://github.com/humhub/humhub/issues/4806#issuecomment-769887587

**Comment by luke-** [comment]
@jwleon Are you sure it's the keylength? I have often seen this problem in relation to different TableEngines. So a foreign key between an InnoDB and MyISAM table.

**Comment by jwleon** [comment]
It's definitely the error I got - and it was fixed when I reduced the field length as described from 160 to 90 so that the summed up length of the key stays at or below 1000 (which was the limit the error message stated).

It may depend on the MySQL Version / Engine; I installed 1.8.0 some days ago on a local testing server and there was no problem with this table...

**Comment by luke-** [comment]
See also here: https://community.humhub.com/s/general-discussion/?contentId=237527

@yurabakhtin Can you take a look? 
maybe we should also wrap the ForeignKey Index in a TryCatch and only log an error if there is a problem here.

**Comment by yurabakhtin** [comment]
@luke- In all reported error messages above I see only the error "Table 'contentcontainer_default_permission' **already exists**".
I guess the migration `m201130_073907_default_permissions` was failed on first call because there was wrong length `255` for one column `contentcontainer_class`, i.e. only table was created but key could not created. it is strange why the migration was not rollbacked automatically if at least one command is failed.
Then the migration is called second time so the users have the error of **already existing** table `contentcontainer_default_permission`.
For me it is also stange why `yii\db\Migration->createTable()` tries to create a table if it already exists, I think we should extend the class `yii\db\Migration` in order to check the table before creating/deleting and etc. i.e. we should either remove the old table before create new one or we can skip the creating of new table with same name, but I prefer to remove because old table may contains wrong columns which should be updated, or we should update only the single column `contentcontainer_class` to correct length if the table `contentcontainer_default_permission` already exists.

**Comment by ArchBlood** [comment]
> I guess the migration `m201130_073907_default_permissions` was failed on first call because there was wrong length `255` for one column `contentcontainer_class`, i.e. only table was created but key could not created. it is strange why the migration was not rollbacked automatically if at least one command is failed.

This pretty much just brings me back to this link about this exact thing;
https://stackoverflow.com/questions/4539242/mysql-varchar-byte-length-255-issue

But on the note of this exact migration that's being done I still refer to the yii2 docs as stated below
> Note that some DB queries in some DBMS cannot be put into a transaction. For some examples, please refer to [implicit commit](http://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html). If this is the case, you should still implement up() and down(), instead.
--------
> For me it is also stange why `yii\db\Migration->createTable()` tries to create a table if it already exists, I think we should extend the class `yii\db\Migration` in order to check the table before creating/deleting and etc. i.e. we should either remove the old table before create new one or we can skip the creating of new table with same name, but I prefer to remove because old table may contains wrong columns which should be updated, or we should update only the single column `contentcontainer_class` to correct length if the table `contentcontainer_default_permission` already exists.

I agree that the yii2 Migration class should be extended by the core to favor of how HumHub wants to update over being forced to update in favor of yii2, the only question is how does HumHub want to update? :thinking:

**Comment by luke-** [comment]
@yurabakhtin Thanks, worked well in my tests! I hope this solves the problems.

**Comment by smitti** [comment]
After all I get this messages  @information/requirements:

 MySQL - Table collations - utf8mb4_unicode_ci, latin1_german2_ci (Hint: Recommended collation is utf8mb4 for the tables: contentcontainer_permission)
 MySQL - Table engines - MyISAM (Hint: Recommended engine is InnoDB for the tables: activity, calendar_entry, calendar_entry_participant, calendar_reminder, calendar_reminder_sent, cfiles_file, cfiles_folder, comment, content, content_tag, content_tag_relation, contentcontainer, contentcontainer_default_permission, contentcontainer_module, contentcontainer_permission, contentcontainer_setting, custom_pages_container_page, custom_pages_container_snippet, custom_pages_page, custom_pages_snippet, custom_pages_template, custom_pages_template_container, custom_pages_template_container_content, custom_pages_template_container_content_definition, custom_pages_template_container_content_item, custom_pages_template_container_content_template, custom_pages_template_element, custom_pages_template_file_content, custom_pages_template_file_download_content, custom_pages_template_hh_richtext_content, custom_pages_template_image_content, custom_pages_template_image_content_definition, custom_pages_template_owner_content, custom_pages_template_richtext_content, custom_pages_template_text_content, file, gallery_gallery, gallery_media, group, group_permission, group_space, group_user, like, live, log, logging, message, message_entry, message_tag, migration, module_enabled, notification, poll, poll_answer, poll_answer_user, post, profile, profile_field, profile_field_category, queue, queue_exclusive, report_content, setting, space, space_membership, task, task_item, task_list_setting, task_reminder, task_user, url_oembed, user, user_auth, user_follow, user_friendship, user_http_session, user_invite, user_mentioning, user_message, user_message_tag, user_password, wiki_page, wiki_page_revision)
