### ISSUE TITLE
Link creation does not copy URL from selected text

### ISSUE THREAD

**Issue by spoorun** [humhub/humhub#4949]
Current:
User types a URL into a post or comment
User selects URL text
User clicks 'link' icon in rich text panel
Dialogue displays to create link
User has to re-enter URL

Expected:
The selected URL is copied automatically into the URL box
User can simply press enter to create the link (if they don't want alternative text option, just to show the link and make it click-able)

**Comment by ArchBlood** [comment]
I believe this only happens on mobile?

**Comment by spoorun** [comment]
> I believe this only happens on mobile?

I'm getting this behaviour in desktop and mobile, including Chrome and Firefox (on Linux and Android).

**Comment by spoorun** [comment]
Moved to humhub-prosemirror repository:
https://github.com/humhub/humhub-prosemirror/issues/51
