### ISSUE TITLE
User Admin Command Line: Add possibility to delete user 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4951]
Currently, deleting users from the command line is not implemented.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4964.

Please note I used the same form `UserDeleteForm` that is used on `/admin/user/delete?id=123`, but there are two options:

- [ ] Delete all contributions of this user
- [ ] Delete spaces which are owned by this user

Should we implement these options for the new command `user/delete` as well?

**Comment by luke-** [comment]
@yurabakhtin 

Background: There are two different ways to delete users. **Soft Delete** (without general content) and **Hard Delete** with all content. I would suggest the following behavior:

```
php yii user/delete example # Soft Delete
php yii user/delete example --full # Hard Delete, error if Space Owner
php yii user/delete example --full --force # Hard Delete including owned Spaces
```

**Comment by yurabakhtin** [comment]
@luke- Ok, done in commit https://github.com/humhub/humhub/pull/4964/commits/13caaf737f37753f1b342cb2bc1f3e5284c6b1ff

**Comment by luke-** [comment]
@yurabakhtin Thanks, can you please rebase it to the "develop" branch.

**Comment by yurabakhtin** [comment]
@luke- The PR has been rebased.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
