### ISSUE TITLE
Stream could not be initialized!

### ISSUE THREAD

**Issue by Baratuxu** [humhub/humhub#4954]
I updated from Humhub 1.7.8 to Humhub 1.8.0 using the updater plugin and started getting the "Stream could not be initialized!" error in several spaces (the majority).

HumHub version: 1.8
PHP version: 7.3.26
Operating system: Linux

**Stream could not be initialized! -
An unexpected server error occurred. If this keeps happening, please contact a site administrator.**

{
    "url": "/index.php?r=space%2Fspace%2Fstream&cguid=d2743854-7a4c-4075-b992-325e972c30c9",
    "status": 500,
    "response": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Setting unknown property: humhub\\modules\\file\\models\\File::hash_sha1&#039; \n\nin /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Component.php:210\n\nStack trace:\n#0 /home/intranet/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\\base\\Component-&gt;__set(&#039;hash_sha1&#039;, &#039;060a91e63a1ef57...&#039;)\n#1 /home/intranet/public_html/protected/humhub/module...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Setting unknown property: humhub\\modules\\file\\models\\File::hash_sha1&#039; \n\nin /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Component.php:210\n\nStack trace:\n#0 /home/intranet/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\\base\\Component-&gt;__set(&#039;hash_sha1&#039;, &#039;060a91e63a1ef57...&#039;)\n#1 /home/intranet/public_html/protected/humhub/modules/file/models/File.php(165): yii\\db\\BaseActiveRecord-&gt;__set(&#039;hash_sha1&#039;, &#039;060a91e63a1ef57...&#039;)\n#2 /home/intranet/public_html/protected/humhub/modules/file/models/File.php(147): humhub\\modules\\file\\models\\File-&gt;saveHash()\n#3 /home/intranet/public_html/protected/humhub/modules/file/models/File.php(133): humhub\\modules\\file\\models\\File-&gt;getHash(8)\n#4 /home/intranet/public_html/protected/humhub/modules/file/libs/FileHelper.php(128): humhub\\modules\\file\\models\\File-&gt;getUrl()\n#5 /home/intranet/public_html/protected/humhub/modules/file/widgets/FilePreview.php(119): humhub\\modules\\file\\libs\\FileHelper::getFileInfos(Object(humhub\\modules\\file\\models\\File))\n#6 /home/intranet/public_html/protected/humhub/modules/file/widgets/FilePreview.php(86): humhub\\modules\\file\\widgets\\FilePreview-&gt;getFileData()\n#7 /home/intranet/public_html/protected/humhub/components/Widget.php(63): humhub\\modules\\file\\widgets\\FilePreview-&gt;run()\n#8 /home/intranet/public_html/protected/humhub/modules/file/widgets/views/showFiles.php(95): humhub\\components\\Widget::widget(Array)\n#9 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require(&#039;/home/intranet/...&#039;)\n#10 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\\base\\View-&gt;renderPhpFile(&#039;/home/intranet/...&#039;, Array)\n#11 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\\base\\View-&gt;renderFile(&#039;/home/intranet/...&#039;, Array, Object(humhub\\modules\\file\\widgets\\ShowFiles))\n#12 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\\base\\View-&gt;render(&#039;showFiles&#039;, Array, Object(humhub\\modules\\file\\widgets\\ShowFiles))\n#13 /home/intranet/public_html/protected/humhub/modules/file/widgets/ShowFiles.php(56): yii\\base\\Widget-&gt;render(&#039;showFiles&#039;, Array)\n#14 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(141): humhub\\modules\\file\\widgets\\ShowFiles-&gt;run()\n#15 /home/intranet/public_html/protected/humhub/widgets/BaseStack.php(88): yii\\base\\Widget::widget(Array)\n#16 /home/intranet/public_html/protected/humhub/components/Widget.php(63): humhub\\widgets\\BaseStack-&gt;run()\n#17 /home/intranet/public_html/protected/humhub/modules/content/widgets/stream/views/wallStreamEntryFooter.php(16): humhub\\components\\Widget::widget(Array)\n#18 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require(&#039;/home/intranet/...&#039;)\n#19 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\\base\\View-&gt;renderPhpFile(&#039;/home/intranet/...&#039;, Array)\n#20 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\\base\\View-&gt;renderFile(&#039;/home/intranet/...&#039;, Array, Object(humhub\\modules\\post\\widgets\\WallEntry))\n#21 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\\base\\View-&gt;render(&#039;@content/widget...&#039;, Array, Object(humhub\\modules\\post\\widgets\\WallEntry))\n#22 /home/intranet/public_html/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(255): yii\\base\\Widget-&gt;render(&#039;@content/widget...&#039;, Array)\n#23 /home/intranet/public_html/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(188): humhub\\modules\\content\\widgets\\stream\\WallStreamEntryWidget-&gt;renderFooter()\n#24 /home/intranet/public_html/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(131): humhub\\modules\\content\\widgets\\stream\\WallStreamEntryWidget-&gt;renderBody()\n#25 /home/intranet/public_html/protected/humhub/components/Widget.php(63): humhub\\modules\\content\\widgets\\stream\\StreamEntryWidget-&gt;run()\n#26 [internal function]: humhub\\components\\Widget::widget(Array)\n#27 /home/intranet/public_html/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(91): call_user_func(&#039;humhub\\\\modules\\\\...&#039;, Array)\n#28 /home/intranet/public_html/protected/humhub/modules/stream/actions/StreamEntryResponse.php(80): humhub\\modules\\content\\widgets\\stream\\StreamEntryWidget::renderStreamEntry(Object(humhub\\modules\\post\\models\\Post), Object(humhub\\modules\\content\\widgets\\stream\\StreamEntryOptions), Array)\n#29 /home/intranet/public_html/protected/humhub/modules/stream/actions/Stream.php(412): humhub\\modules\\stream\\actions\\StreamEntryResponse::getAsArray(Object(humhub\\modules\\content\\models\\Content), Object(humhub\\modules\\content\\widgets\\stream\\StreamEntryOptions))\n#30 /home/intranet/public_html/protected/humhub/modules/stream/actions/Stream.php(367): humhub\\modules\\stream\\actions\\Stream-&gt;getStreamEntryResult(Object(humhub\\modules\\content\\models\\Content), Object(humhub\\modules\\content\\widgets\\stream\\StreamEntryOptions))\n#31 /home/intranet/public_html/protected/humhub/modules/stream/actions/Stream.php(346): humhub\\modules\\stream\\actions\\Stream-&gt;addResponseEntries(Array, Object(humhub\\modules\\stream\\actions\\StreamResponse))\n#32 [internal function]: humhub\\modules\\stream\\actions\\Stream-&gt;run()\n#33 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)\n#34 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\Action-&gt;runWithParams(Array)\n#35 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\base\\Controller-&gt;runAction(&#039;stream&#039;, Array)\n#36 /home/intranet/public_html/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\base\\Module-&gt;runAction(&#039;space/space/str...&#039;, Array)\n#37 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#38 /home/intranet/public_html/index.php(25): yii\\base\\Application-&gt;run()\n#39 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "html",
    "html": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Setting unknown property: humhub\\modules\\file\\models\\File::hash_sha1&#039; \n\nin /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Component.php:210\n\nStack trace:\n#0 /home/intranet/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\\base\\Component-&gt;__set(&#039;hash_sha1&#039;, &#039;060a91e63a1ef57...&#039;)\n#1 /home/intranet/public_html/protected/humhub/module...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

**Also Log entries have following errors:**

yii\base\UnknownPropertyException: Setting unknown property: humhub\modules\file\models\File::hash_sha1 in /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Component.php:210 Stack trace: #0 /home/intranet/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set('hash_sha1', '060a91e63a1ef57...') #1 /home/intranet/public_html/protected/humhub/modules/file/models/File.php(165): yii\db\BaseActiveRecord->__set('hash_sha1', '060a91e63a1ef57...') #2 /home/intranet/public_html/protected/humhub/modules/file/models/File.php(147): humhub\modules\file\models\File->saveHash() #3 /home/intranet/public_html/protected/humhub/modules/file/models/File.php(133): humhub\modules\file\models\File->getHash(8) #4 /home/intranet/public_html/protected/humhub/modules/file/libs/FileHelper.php(128): humhub\modules\file\models\File->getUrl() #5 /home/intranet/public_html/protected/humhub/modules/file/widgets/FilePreview.php(119): humhub\modules\file\libs\FileHelper::getFileInfos(Object(humhub\modules\file\models\File)) #6 /home/intranet/public_html/protected/humhub/modules/file/widgets/FilePreview.php(86): humhub\modules\file\widgets\FilePreview->getFileData() #7 /home/intranet/public_html/protected/humhub/components/Widget.php(63): humhub\modules\file\widgets\FilePreview->run() #8 /home/intranet/public_html/protected/humhub/modules/file/widgets/views/showFiles.php(95): humhub\components\Widget::widget(Array) #9 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/intranet/...') #10 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/intranet/...', Array) #11 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/intranet/...', Array, Object(humhub\modules\file\widgets\ShowFiles)) #12 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\base\View->render('showFiles', Array, Object(humhub\modules\file\widgets\ShowFiles)) #13 /home/intranet/public_html/protected/humhub/modules/file/widgets/ShowFiles.php(56): yii\base\Widget->render('showFiles', Array) #14 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(141): humhub\modules\file\widgets\ShowFiles->run() #15 /home/intranet/public_html/protected/humhub/widgets/BaseStack.php(88): yii\base\Widget::widget(Array) #16 /home/intranet/public_html/protected/humhub/components/Widget.php(63): humhub\widgets\BaseStack->run() #17 /home/intranet/public_html/protected/humhub/modules/content/widgets/stream/views/wallStreamEntryFooter.php(16): humhub\components\Widget::widget(Array) #18 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/intranet/...') #19 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/intranet/...', Array) #20 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/intranet/...', Array, Object(humhub\modules\post\widgets\WallEntry)) #21 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\base\View->render('@content/widget...', Array, Object(humhub\modules\post\widgets\WallEntry)) #22 /home/intranet/public_html/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(255): yii\base\Widget->render('@content/widget...', Array) #23 /home/intranet/public_html/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(188): humhub\modules\content\widgets\stream\WallStreamEntryWidget->renderFooter() #24 /home/intranet/public_html/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(131): humhub\modules\content\widgets\stream\WallStreamEntryWidget->renderBody() #25 /home/intranet/public_html/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\stream\StreamEntryWidget->run() #26 [internal function]: humhub\components\Widget::widget(Array) #27 /home/intranet/public_html/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(91): call_user_func('humhub\\modules\\...', Array) #28 /home/intranet/public_html/protected/humhub/modules/stream/actions/StreamEntryResponse.php(80): humhub\modules\content\widgets\stream\StreamEntryWidget::renderStreamEntry(Object(humhub\modules\post\models\Post), Object(humhub\modules\content\widgets\stream\StreamEntryOptions), Array) #29 /home/intranet/public_html/protected/humhub/modules/stream/actions/Stream.php(412): humhub\modules\stream\actions\StreamEntryResponse::getAsArray(Object(humhub\modules\content\models\Content), Object(humhub\modules\content\widgets\stream\StreamEntryOptions)) #30 /home/intranet/public_html/protected/humhub/modules/stream/actions/Stream.php(367): humhub\modules\stream\actions\Stream->getStreamEntryResult(Object(humhub\modules\content\models\Content), Object(humhub\modules\content\widgets\stream\StreamEntryOptions)) #31 /home/intranet/public_html/protected/humhub/modules/stream/actions/Stream.php(346): humhub\modules\stream\actions\Stream->addResponseEntries(Array, Object(humhub\modules\stream\actions\StreamResponse)) #32 [internal function]: humhub\modules\stream\actions\Stream->run() #33 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #34 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\Action->runWithParams(Array) #35 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('stream', Array) #36 /home/intranet/public_html/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('space/space/str...', Array) #37 /home/intranet/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request)) #38 /home/intranet/public_html/index.php(25): yii\base\Application->run() #39 {main}

Need help!

**Comment by luke-** [comment]
Can you please post a screenshot of the output: Adminsitration -> Information -> Database?

**Comment by Baratuxu** [comment]
Thx Luke for your interest! Here it is:
![Humhub](https://user-images.githubusercontent.com/80325100/110791713-71a95880-826a-11eb-849b-86073e7d72e9.png)

Reinforcing the obvious; I'm more lost than a blind man in a gunfight. I have no idea what to do; but I understand there was a problem with the migration!
Many thanxs!

**Comment by luke-** [comment]
See here: https://github.com/humhub/humhub/issues/4946
