### ISSUE TITLE
Some emoji are not detected by RichTextEmojiExtension

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4955]
Make this conversion:
```
echo \humhub\modules\content\widgets\richtext\RichText::convert($wikiPageContent, ':upside_down_face:  :+1:');
```

You should have 2 emojis displayed.
But only `upside_down_face` is converted to emoji. `+1` is not: 
![image](https://user-images.githubusercontent.com/23310825/110490978-1c960700-80f1-11eb-80c6-6723513a98f6.png)

This is because `+1` is not dected as a match here: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/widgets/richtext/extensions/emoji/RichTextEmojiExtension.php#L39

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8

**Comment by luke-** [comment]
@yurabakhtin Awesome thanks!
