### ISSUE TITLE
Add possibility to register purchased modules via CLI

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4958]
Add `register`  e.g. https://docs.humhub.org/docs/admin/console#module

**Comment by yurabakhtin** [comment]
@luke- As I understood the new command should do same what the form `/marketplace/purchase` does by click on the button "Register". I have done this in commit https://github.com/humhub/humhub/pull/4963.

**Comment by luke-** [comment]
@yurabakhtin Yes, thanks!
