### ISSUE TITLE
Horizontal scrollbar for images

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#4959]
Upload a wide picture in a post, wikipage or other Richtext:
![image](https://user-images.githubusercontent.com/23310825/110939122-332ca000-8335-11eb-94dc-9ab5d4512e07.png)

The image has `width="100%"` wich is correct, but also `margin: 0 5px;` which creates an horizontal scrollbar:
https://github.com/humhub/humhub/blob/master/static/less/markdown.less#L168
```
[data-ui-richtext] img:not(.center-block) {
    max-width: 100%;
    margin: 0 5px;
}
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4961

**Comment by luke-** [comment]
@yurabakhtin Does it still look good now without margin or Is there no difference? Can you please post a screenshot?
Maybe you should use a padding instead of a margin?

**Comment by yurabakhtin** [comment]
@luke- It looks like without margin, if we need the space then yes we should use a padding, should I use padding?

<img width="680" alt="tests" src="https://user-images.githubusercontent.com/6995524/110960811-31c49d00-8360-11eb-8831-b7a0561b3bce.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks for the screenshots. The variant without margin is really the best. I'll merge the PR.
