### ISSUE TITLE
Files broken when filename contains russian characters

### ISSUE THREAD

**Issue by dimontajik** [humhub/humhub#497]
When you load music from the Russian name appears bug removed the name of the music and then the music is not played

![2](https://cloud.githubusercontent.com/assets/10101408/5424496/9129a1e2-831b-11e4-9aee-d40943392abb.jpg)
![3](https://cloud.githubusercontent.com/assets/10101408/5424497/91453056-831b-11e4-93fc-521c0772273f.jpg)

**Comment by Vatarus** [comment]
__Вывод русских имен в прикрепленных файлах.__
Вносим изменения в File.php (protected/modules_core/file/models) 
public function sanitizeFilename()
{ 
setlocale(LC_CTYPE, 'ru_RU.UTF-8'); 
$this->file_name = trim($this->file_name); 
$this->file_name = preg_replace("/[^a-zA-ZА-Яа-я0-9_()\-s\. ]/u", "", $this->file_name);
![russian](https://cloud.githubusercontent.com/assets/3394915/7308240/aa5eafd8-ea4d-11e4-9f63-886437738596.png)

**Comment by WASasquatch** [comment]
Good work, Vatarus. :D
