### ISSUE TITLE
When removing someone from a group. No matter what has been specified, user gets a notification

### ISSUE THREAD

**Issue by superseby2** [humhub/humhub#4972]
### What steps will reproduce the problem?

- Go to /admin/group/manage-group-users?id=2
- Make sure **Enable Notifications** is not checked for this group
- Remove user

### What is the expected result?
- User has 0 notifications

### What do you get instead?
- User got a notification about his/her removal from group
- 
### Additional info

- Adding a user into a group respects the notification settings : when added and "no notification" is specified,user does not receive any notification. which is expected.
- When checking "Enable Notifications" both adding or removing lead correctly to a notification being sent.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.0
| PHP version      | 7
| Operating system | Linux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4977

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by superseby2** [comment]
Anyone told you recently that you guys rocks? 
Thx for fixing this so fast!
