### ISSUE TITLE
Would you consider using  EasyMDE as Mardown Editor

### ISSUE THREAD

**Issue by superseby2** [humhub/humhub#4974]
### Is your feature request related to a problem? Please describe.

3 "problems" (more of annoyances but still) 

- when  trying to format my text I am annoyed with the way lists is done.  Especially creating 
sublist is not easy at all and require some patience
- hitting "TAB" fails miserably 
- emojis : having to select from the menu is not intuitive. Doing like here on github editor is much easier 
- :thinking: I prefer to have it display in text but selected quicky by typing the word. 

### Describe the solution you'd like

- Have been using EasyMDE  for projects and it works very well. It would be awesome if it could be used 
and that would solve my problem 1 & 2 ;)

https://github.com/Ionaru/easy-markdown-editor/

- For emojis : it would require some work  I guess but maybe a workaround would be to be able to focus on the widget input text?

**Comment by dreua** [comment]
Could someone fix "Markdown" in the heading? This is hard to read when going through search results.

**Comment by luke-** [comment]
Some points, such as the TAB, have now been improved

Otherwise, it would be better to have a separate issue for each feature/change request.
