### ISSUE TITLE
Scrollbars on post when large picture in content

### ISSUE THREAD

**Issue by Reuns** [humhub/humhub#4980]
### What steps will reproduce the problem?
Create a new content and transfer a picture (or add an external image).
The image should have a larger width than the template (no matter the height is)

### What do you get instead?
An horizontal scrollbar appear at the bottom of the post.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.1
| PHP version      |  7.4

![scrollbar](https://user-images.githubusercontent.com/19529531/112443021-be9e2c00-8d4c-11eb-9e91-69cc4095a473.png)

**Comment by ArchBlood** [comment]
Should be fixed in #4961
