### ISSUE TITLE
Activity Mail Broken due QueryParams

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4985]
### What steps will reproduce the problem?

Could not send activity mail to: XXX (Calling unknown method: yii\console\Request::getQueryParam()#0 /srv/humhub/protected/humhub/modules/stream/actions/Stream.php(192): yii\base\Component->__call('getQueryParam', Array) #1 /srv/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\stream\actions\Stream->init() #2 /srv/humhub/protected/vendor/yiisoft/yii2/base/Action.php(62): yii\base\BaseObject->__construct(Array) #3 /srv/humhub/protected/humhub/modules/activity/components/MailSummary.php(147): yii\base\Action->__construct('stream', Object(yii\queue\db\Command), Array) #4 /srv/humhub/protected/humhub/modules/activity/components/MailSummary.php(79): humhub\modules\activity\components\MailSummary->getActivities() #5 /srv/humhub/protected/humhub/modules/activity/components/MailSummaryProcessor.php(67): humhub\modules\activity\components\MailSummary->send() #6 /srv/humhub/protected/humhub/modules/activity/jobs/SendMailSummary.php(59): humhub\modules\activity\components\MailSummaryProcessor::process(1) #7 /srv/humhub/protected/humhub/modules/queue/ActiveJob.php(33): humhub\modules\activity\jobs\SendMailSummary->run() #8 /srv/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(246): humhub\modules\queue\ActiveJob->execute(Object(humhub\modules\queue\driver\MySQL)) #9 /srv/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('137446', 'O:44:"humhub\\mo...', '3600', '1') #10 /srv/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('137446', 'O:44:"humhub\\mo...', '3600', '1', '14616') #11 [internal function]: yii\queue\cli\Command->actionExec('137446', '3600', '1', '14616') #12 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #13 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #14 /srv/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('exec', Array) #15 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('exec', Array) #16 /srv/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('queue/exec', Array) #17 /srv/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('queue/exec', Array) #18 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #19 /srv/www/htdocs/community/yii.php(38): yii\base\Application->run() #20 {main})

Related Commit: https://github.com/humhub/humhub/commit/3e7d39cffe4b8f00e822b117df34e256c3385085#diff-5c61435181cd93284ced192dc250e7ff5d285ec5c5f9e5495e68e6444b9c4fae

We need to check for Console Action before accessing query params

**Comment by yurabakhtin** [comment]
@luke- Thank you for the link where it was broken.
Fixed in PR https://github.com/humhub/humhub/pull/4986.
Also the same bug was reported in the issue https://github.com/humhub/tasks/issues/102.
