### ISSUE TITLE
Unable to archive posts/space on Form Validation errors 

### ISSUE THREAD

**Issue by rafasants** [humhub/humhub#4988]
Hello!

I am having some problems, but just when we need to Archive an post/space.
When I go to the Page/Space configs and click on the "Archive" button, the page show me "Post Archived", but, if I refresh the space page
I realize that the page/space wasn't archived.

I don't know if it's a bug or it's because of the Traefik reverse proxy (SSL redirect) is impacting in something. Because I didn't find any error log on the server (Apache and PHP).

Thing that I did:

-> Flush the cache
-> Fix the permissions of crontab jobs and of all files located in /var/www/html/*

Additional info:

HumHub version : 1.8.1
PHP version : 7.4.15
Operating system : CentOS Linux 8
![humhub_1](https://user-images.githubusercontent.com/56829721/113324341-6091bb80-92ed-11eb-86ff-b53ba9d54a93.png)
![humhub_2](https://user-images.githubusercontent.com/56829721/113324354-62f41580-92ed-11eb-9d12-ab3f8d3455bc.png)

**Comment by luke-** [comment]
Can you please post a screenshot of the space after clicking archive?

**Comment by rafasants** [comment]
@luke- Sure. Are here.
When I click in "Archive", show me that the space was Archived:
![humhub_1](https://user-images.githubusercontent.com/56829721/113325217-84093600-92ee-11eb-9b48-353446f06347.png)

But when I refresh the Page, the space still un-archive.:
![humhub_2](https://user-images.githubusercontent.com/56829721/113325343-ad29c680-92ee-11eb-94f0-a0ef156848da.png)

**Comment by luke-** [comment]
Hmm, can not reproduce this with 1.8.1

**Comment by rafasants** [comment]
@luke- So, isn't a bug ?

**Comment by luke-** [comment]
I don't think. You can try to reproduce this on our cloud hosting: https://www.humhub.com/en/professional-edition/demo

**Comment by Reuns** [comment]
Hello there.
I'm using 1.9.1 and I have the exact same issue.
But I can't reproduce it on a test hosting. :/

Did you have any other informations about this problem ?

**Comment by rafasants** [comment]
> Hello there.
> I'm using 1.9.1 and I have the exact same issue.
> But I can't reproduce it on a test hosting. :/
> 
> Did you have any other informations about this problem ?

Yes I Did Reuns, but I forgot to Close this "Issue". Anyway, in my case, the problem was that the Description Field of the space has a limit until 100 characters, and I don't know how, but this same field had more than 100 characters (Probably some update changed this). And I deleted the extra characters, and after this, it was possible to archive the space. :)

**Comment by Reuns** [comment]
It works great, Thank you very much !
I think it's a good thing for the team to know that.
@luke- you may find this interesting...

**Comment by Reuns** [comment]
Wow ... more to know about this : it's not only the space with too much characters that is locked for archive ... but all spaces are locked for this option.
When I change description, the others space I tried to archive were suddenly archived (without any other action from me).
From this point it could be a real pain in the heck to find out which space is in cause, mostly when you don't even know about this bug.

This issue should remain open and tagged as bug for the team to resolve this issue. 
@luke- ?

**Comment by funkycram** [comment]
I also had the same problem with old spaces created before the limitation to 100 characters of the descriptions.

@luke- Perhaps we should replace `$this->save();` with `$this->save(true);` here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/models/Space.php#L424 ?

**Comment by luke-** [comment]
Yes we can do that, however it would be good to add a comment why the valdation was disabled.

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/6151
