### ISSUE TITLE
MySQL - Table engines

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4990]
MySQL - Table engines - MyISAM, InnoDB - Varying table engines are not supported. (Hint: Recommended engine is InnoDB for the tables: activity, comment, content, content_tag, content_tag_relation, contentcontainer, contentcontainer_module, contentcontainer_permission, contentcontainer_setting, custom_tag, file, group, group_permission, group_user, legal_page, like, live, log, logging, message, message_entry, message_tag, migration, module_enabled, notification, post, profile, profile_field, profile_field_category, queue, queue_exclusive, setting, space, space_membership, url_oembed, user, user_auth, user_follow, user_friendship, user_http_session, user_invite, user_mentioning, user_message, user_message_tag, user_password)

![image](https://user-images.githubusercontent.com/36643871/113460776-87054300-9422-11eb-87be-87d58b7af5ab.png)

**Comment by luke-** [comment]
Please see our bug report template with required information.

**Comment by andrewua85** [comment]
After Updates HUMHUB error!
Click to link
![image](https://user-images.githubusercontent.com/36643871/113493407-ab772300-94e7-11eb-80ef-13298d3d36c9.png)

and after this
![image](https://user-images.githubusercontent.com/36643871/113493438-f5600900-94e7-11eb-885a-98fd03a44ec4.png)

**Comment by andrewua85** [comment]
![Uploading image.png…]()

**Comment by luke-** [comment]
You need to fix this error: MySQL - Table engines - MyISAM, InnoDB - Varying table engines are not supported.
And then run the database migrations again: e.g. at Adminstration -> Information -> Database

**Comment by dreua** [comment]
> You need to fix this error: MySQL - Table engines - MyISAM, InnoDB - Varying table engines are not supported.

How does one do that?

**Comment by ArchBlood** [comment]
@luke- with resent reports to the community site maybe it would be a good idea to pin this issue? As it seems to continue to be asked about even in v1.9

https://community.humhub.com/s/general-discussion/?contentId=243890

**Comment by luke-** [comment]
@ArchBlood Ok, I'll pin this issue for some time.

**Comment by atk87a** [comment]
I got the same problem here. what is the way to get this fixed?

`MySQL - Table engines - MyISAM, InnoDB - Varying table engines are not supported. (Hint: Recommended engine is InnoDB for the tables: activity, calendar_entry, calendar_entry_participant, calendar_reminder, calendar_reminder_sent, cfiles_file, cfiles_folder, comment, content, content_bookmark, content_tag, content_tag_relation, contentcontainer, contentcontainer_default_permission, contentcontainer_module, contentcontainer_permission, contentcontainer_setting, custom_pages_container_page, custom_pages_container_snippet, custom_pages_page, custom_pages_snippet, custom_pages_template, custom_pages_template_container, custom_pages_template_container_content, custom_pages_template_container_content_definition, custom_pages_template_container_content_item, custom_pages_template_container_content_template, custom_pages_template_element, custom_pages_template_file_content, custom_pages_template_file_download_content, custom_pages_template_hh_richtext_content, custom_pages_template_image_content, custom_pages_template_image_content_definition, custom_pages_template_owner_content, custom_pages_template_richtext_content, custom_pages_template_text_content, file, gallery_gallery, gallery_media, group, group_permission, group_space, group_user, legal_page, like, linklist_category, linklist_link, linkpreview, live, log, logging, meeting, meeting_item, meeting_item_moderator, meeting_participant, meeting_task, message, message_entry, message_tag, migration, module_enabled, notification, onlyoffice_share, poll, poll_answer, poll_answer_user, post, profile, profile_field, profile_field_category, queue, queue_exclusive, setting, space, space_membership, task, task_item, task_list_setting, task_reminder, task_user, url_oembed, user, user_auth, user_follow, user_friendship, user_http_session, user_invite, user_mentioning, user_message, user_message_tag, user_password, wiki_page, wiki_page_revision)`

**Comment by luke-** [comment]
@atk87a Maybe this helps: https://stackoverflow.com/questions/3856435/how-to-convert-all-tables-from-myisam-into-innodb

**Comment by ArchBlood** [comment]
For those that have phpMyAdmin installed there is an easier method under `Your Database > Operations > Collation` then you can easily use `ALTER TABLE table_name ENGINE=InnoDB;`, where `table_name` refers to the table name that you're wanting to change, to convert to the required and recommended engine, of course, if you have a newer version of phpMyAdmin you could also manually go through each of the listed needed to be changed then use the Operations button and change the engine there for each individual table.

But again it is easier to just do the SQL option and copy & paste it multiple times then replace the `table_name` with the wanted table to be changed then run the command.

How this helps somewhat on the issue with changing tables and engines of those tables.
