### ISSUE TITLE
Marketplace Module Path automatically add to Autoloader Paths 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4992]
### Is your feature request related to a problem? Please describe.

The path defined here
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/marketplace/Module.php#L42
Should be automatically used by
https://github.com/humhub/humhub/blob/master/protected/humhub/components/bootstrap/ModuleAutoLoader.php

(if not already set)

Target Branch: Develop

**Comment by yurabakhtin** [comment]
@luke- I have investigated the files, but not enough clear what to do, please read what I found:

- Here https://github.com/humhub/humhub/blob/master/protected/humhub/components/bootstrap/ModuleAutoLoader.php#L48 we initalize modules from the paths `Yii::$app->params['moduleAutoloadPaths']` which are from config https://github.com/humhub/humhub/blob/master/protected/humhub/config/common.php#L170 with value `'moduleAutoloadPaths' => ['@app/modules', '@humhub/modules'],`.
- I.e. there we already find modules from the path `@app/modules` same as in `humhub\modules\marketplace\Module::modulesPath = '@app/modules'`.

Do you mean to modify the line https://github.com/humhub/humhub/blob/master/protected/humhub/components/bootstrap/ModuleAutoLoader.php#L48 to load modules in additional from the `marketplace\Module::modulesPath`, like this: ?

```php
$modulePaths = Yii::$app->params['moduleAutoloadPaths'];
$modulePaths[] = (new humhub\modules\marketplace\Module())->modulesPath;
$modules = static::findModules($modulePaths);
```

**Comment by luke-** [comment]
@yurabakhtin Yes, the initial problem is that if you change the module folder `modulePath`in the MarketplaceModule, you need to add it again in the ModuleAutoloader `moduleAutoloadPaths`.

But I had not considered that we do not have access to the Marketplace module attributes `modulesPath` at this point, since the Module is also not initialised yet.

If we don't find a nice solution here, I would leave the behaviour as it is at the moment.
Perhaps we should at least add to the `modulePath` variable doc that the `moduleAutoloaderPath` path must also be modified.

**Comment by yurabakhtin** [comment]
@luke- Yes, we cannot access to the `marketplace` module there. And I find we set `marketplace\Module->modulesPath` from the config if the config is defined https://github.com/humhub/humhub/blob/master/protected/humhub/modules/marketplace/Module.php#L88-L90:

```php
if (!empty(Yii::$app->params['moduleMarketplacePath'])) {
    $this->modulesPath = Yii::$app->params['moduleMarketplacePath'];
}
```

so it will be strange if we will do a reverse action like `Yii::$app->params['moduleMarketplacePath'] = marketplace\Module->modulesPath`.

But if we need we can try to replace the public var `marketplace\Module->modulesPath` to static so access like `marketplace\Module::MODULES_PATH` will works in the file `ModuleAutoLoader.php` I think.

> Perhaps we should at least add to the `modulePath` variable doc that the `moduleAutoloaderPath` path must also be modified.

Let me know to do this if you don't agree the solution with static var.

**Comment by luke-** [comment]
@yurabakhtin Thank you for the investigation and suggestions.

I think we will leave it as it is with an additional hint that the individual path has to be defined in two locations.
https://github.com/humhub/humhub/commit/42ff9f8df4dd5f75d5df3057b5651b4a1a667643
