### ISSUE TITLE
"An unexpected error occurred. If this keeps happening, please contact a site administrator" showed when I uploaded a large file (1.6G) through a 4G network.

### ISSUE THREAD

**Issue by jimlinntu** [humhub/humhub#4993]
### What steps will reproduce the problem?

I uploaded a file with about 1.6G size through a 4G network.
And it showed `An unexpected error occurred. If this keeps happening, please contact a site administrator`

### What is the expected result?
I expect that even though a 4G network's upload speed was slow, it should not produce this error message.

### What do you get instead?
it showed `An unexpected error occurred. If this keeps happening, please contact a site administrator`.

<img width="1425" alt="Screen Shot 2021-04-05 at 4 33 52 PM copy" src="https://user-images.githubusercontent.com/31609554/113560105-0d916e80-9635-11eb-92db-98f58ab2b69d.png">

<img width="1425" alt="Screen Shot 2021-04-05 at 5 13 24 PM copy" src="https://user-images.githubusercontent.com/31609554/113560123-12eeb900-9635-11eb-82b7-44f5b036ab76.png">

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.2|
| PHP version      |  7.3.21|
| Operating system |Ubuntu 18.04|

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by jimlinntu** [comment]
I guess this error message was triggered by things in https://github.com/humhub/humhub/tree/master/protected/humhub/modules/file

But because I am not familiar of `yii`'s framework, can someone point out what happens here?

**Comment by luke-** [comment]
Can you please provide the  error message? e.g. /protected/runtime/logs or a error message from the webserver?

**Comment by jimlinntu** [comment]
> Can you please provide the error message? e.g. /protected/runtime/logs or a error message from the webserver?

@luke- May I ask how can I enable storing logs?
