### ISSUE TITLE
Simple search improvement

### ISSUE THREAD

**Issue by spoorun** [humhub/humhub#5001]
Currently search has only one advanced setting: filter by space

This is very commonly used and is currently hidden and unintuitive.

Improvements:

- [ ] Replace the wording with 'Filter by' rather than 'Search only in certain...', it's less wordy and more consistent
- [ ] Show search filter automatically rather than hidden behind 'Advanced settings' which is not obvious and overkill for a single option
- [ ] Add filter by 'Profiles' option

In future it could look like

"Search for user, spaces, and content                Search

Filter by: 
Space [                            ]
Profile [                            ]
Type  [ ] Image [ ] Document [ ] Post [ ]  Message [ ] etc..."

**Comment by tomofu74** [comment]
I want to add sorting by datetime ascendant/descendant, if it is able to.

**Comment by klauswagner** [comment]
related: https://github.com/humhub/humhub/issues/4298
