### ISSUE TITLE
Dashboard doesn't reload by clicking the logo or dashboard button

### ISSUE THREAD

**Issue by DezzyTee** [humhub/humhub#5003]
### What steps will reproduce the problem?
Clicking on "Dashboard" or the logo of the site.

### What is the expected result?
Redirect to the main dashboard (<domain>/index.php?r=dashboard%2Fdashboard)

### What do you get instead?
Infinite site loading until refreshing the page.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version | 1.8.1
| PHP version | 7.3
| Operating system | Debian 10

Log and Errors are empty.

**Comment by ArchBlood** [comment]
HumHub uses pre-loaded assets so that full-page reloads aren't needed, this is what pjax does, you're probably using a module or an external script that needs to be updated  to work with pjax loading

**Comment by DezzyTee** [comment]
> HumHub uses pre-loaded assets so that full-page reloads aren't needed, this is what pjax does, you're probably using a module or an external script that needs to be updated to work with pjax loading

Thank you! All of my modules were up to date but the code box module was responsible for the bug. Now it works like a charm.
You've just made my day. I've spent way to long trying to figure out what was going on.
