### ISSUE TITLE
error when initializing fresh database with new install of 1.8.1 and when adding users as admin

### ISSUE THREAD

**Issue by stockh0lm** [humhub/humhub#5007]
When installing humhub 1.8.1 on a fresh webspace with a fresh database i get this error, seconds after entering the database details:

Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: humhub\modules\user\models\Group::is_default_group

        in /home/sites/site100023887/web/unser/protected/vendor/yiisoft/yii2/base/Component.php at line 210

    201202203204205206207208209210211212213214215216217218219

                    $behavior->$name = $value;                 return;             }         }           if (method_exists($this, 'get' . $name)) {             throw new InvalidCallException('Setting read-only property: ' . get_class($this) . '::' . $name);         }           throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);     }       /**      * Checks if a property is set, i.e. defined and not null.      *      * This method will check in the following order and act accordingly:      *      *  - a property defined by a setter: return whether the property is set      *  - a property of a behavior: return whether the property is set 

        in /home/sites/site100023887/web/unser/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 324 – yii\base\Component::__set()
        in /home/sites/site100023887/web/unser/protected/humhub/modules/installer/libs/InitialData.php at line 439 – yii\db\BaseActiveRecord::__set()

    433434435436437438439440441442443

            }           $group = new Group();         $group->name = "Users";         $group->description = "Example Group by Installer";         $group->show_at_directory = false;         $group->is_default_group = 1;         $group->save();     }   } 

        in /home/sites/site100023887/web/unser/protected/humhub/modules/installer/controllers/ConfigController.php at line 96 – humhub\modules\installer\libs\InitialData::bootstrap()

    90919293949596979899100101102

        {           if (Yii::$app->settings->get('name') == "") {             Yii::$app->settings->set('name', "HumHub");         }           \humhub\modules\installer\libs\InitialData::bootstrap();           return $this->redirect(Yii::$app->getModule('installer')->getNextConfigStepUrl());     }       /**      * Basic Settings Form 

        humhub\modules\installer\controllers\ConfigController::actionIndex()
        in /home/sites/site100023887/web/unser/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array()
        in /home/sites/site100023887/web/unser/protected/vendor/yiisoft/yii2/base/Controller.php at line 181 – yii\base\InlineAction::runWithParams()
        in /home/sites/site100023887/web/unser/protected/vendor/yiisoft/yii2/base/Module.php at line 534 – yii\base\Controller::runAction()
        in /home/sites/site100023887/web/unser/protected/vendor/yiisoft/yii2/web/Application.php at line 104 – yii\base\Module::runAction()
        in /home/sites/site100023887/web/unser/protected/vendor/yiisoft/yii2/base/Application.php at line 392 – yii\web\Application::handleRequest()
        in /home/sites/site100023887/web/unser/index.php at line 27 – yii\base\Application::run()

    21222324252627

        require(__DIR__ . '/protected/humhub/config/web.php'),     (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],     require(__DIR__ . '/protected/config/common.php'),     require(__DIR__ . '/protected/config/web.php') );   (new humhub\components\Application($config))->run(); 

$_GET = [     'r' => 'installer/config/index', ];  $_COOKIE = [     'wordpress_test_cookie' => 'WP Cookie check',     'wordpress_logged_in_c74e586cf06c4529ca64409a1adbe761' => 'andreas|1618567995|vi3LubGvPIEO9ll7vjLc7dt8yElsqEsGGW88oYBDJi2k|70199e2f26adfce14ed9ca33e4aa05f569f282e1afdda6ca2db91ba1bfc5a14c',     'wp-settings-time-1' => '1618157729',     '_csrf' => '339ef0720ce50b1214d96bb97faedfc5908bc6b373b16e8329a481802a1453e6fa:2:{i:0;s:5:"_csrf";i:1;s:32:"2_v_-Kgn8T1wKe3ETe76UxdK5O4vjXjzo";}', ];

aaee422c-bdfe-49a7-9311-82adc1ea3a34.png

2021-04-13, 10:12:53

Apache

Yii Framework/2.0.40

Also when i add a new user  as the admin i get a related error:

Invalid Argument – yii\base\InvalidArgumentException
Key "is_default_group" is not a column name and can not be used as a filter

        in /home/sites/site100023887/web/mitglieder/protected/vendor/yiisoft/yii2/db/ActiveRecord.php at line 238

    229230231232233234235236237238239240241242243244245246247

         */     protected static function filterCondition(array $condition, array $aliases = [])     {         $result = [];         $db = static::getDb();         $columnNames = static::filterValidColumnNames($db, $aliases);           foreach ($condition as $key => $value) {             if (is_string($key) && !in_array($db->quoteSql($key), $columnNames, true)) {                 throw new InvalidArgumentException('Key "' . $key . '" is not a column name and can not be used as a filter');             }             $result[$key] = is_array($value) ? array_values($value) : $value;         }           return $result;     }       /**      * Valid column names are table column names or column names prefixed with table name or table alias 

        in /home/sites/site100023887/web/mitglieder/protected/vendor/yiisoft/yii2/db/ActiveRecord.php at line 191 – yii\db\ActiveRecord::filterCondition()
        in /home/sites/site100023887/web/mitglieder/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 112 – yii\db\ActiveRecord::findByCondition()
        in /home/sites/site100023887/web/mitglieder/protected/humhub/modules/user/Module.php at line 209 – yii\db\BaseActiveRecord::findOne()

    203204205206207208209210211212213214215

        /**      * Get default group      * @return Group      */     public function getDefaultGroup()     {         return Group::findOne(['is_default_group' => 1, 'is_admin_group' => 0]);     }       /**      * Get default group id      * @return integer|null      */ 

        in /home/sites/site100023887/web/mitglieder/protected/humhub/modules/user/models/Group.php at line 448 – humhub\modules\user\Module::getDefaultGroup()

    442443444445446447448449450451452453454

                    ->where(['show_at_registration' => 1, 'is_admin_group' => 0])                 ->orderBy('name ASC')                 ->all();         }           $groups = [];         if ($defaultGroup = Yii::$app->getModule('user')->getDefaultGroup()) {             $groups[] = $defaultGroup;         }           return $groups;     }   

        in /home/sites/site100023887/web/mitglieder/protected/humhub/modules/user/models/forms/Registration.php at line 367 – humhub\modules\user\models\Group::getRegistrationGroups()

    361362363364365366367368369370371372373

        {         if ($this->_groupUser === null) {             $this->_groupUser = new GroupUser();             $this->_groupUser->scenario = GroupUser::SCENARIO_REGISTRATION;               // assign default value for group_id             $registrationGroups = Group::getRegistrationGroups();             if (count($registrationGroups) == 1) {                 $this->_groupUser->group_id = $registrationGroups[0]->id;             }         }           return $this->_groupUser; 

        in /home/sites/site100023887/web/mitglieder/protected/humhub/modules/user/models/forms/Registration.php at line 212 – humhub\modules\user\models\forms\Registration::getGroupUser()

    206207208209210211212213214215216217218

         */     protected function setModels()     {         // Set Models         $this->models['User'] = $this->getUser();         $this->models['Profile'] = $this->getProfile();         $this->models['GroupUser'] = $this->getGroupUser();         if ($this->enablePasswordForm) {             $this->models['Password'] = $this->getPassword();             if (!isset($this->models['Password']->mustChangePassword)) {                 // Enable the checkbox by default on new user form:                 $this->models['Password']->mustChangePassword = true;             } 

        in /home/sites/site100023887/web/mitglieder/protected/humhub/modules/user/models/forms/Registration.php at line 248 – humhub\modules\user\models\forms\Registration::setModels()

    242243244245246247248249250251252253254

        /**      * @inheritdoc      */     public function submitted($buttonName = "")     {         // Ensure Models         $this->setModels();           return parent::submitted($buttonName);     }       /**      * Registers users 

        in /home/sites/site100023887/web/mitglieder/protected/humhub/modules/admin/controllers/UserController.php at line 248 – humhub\modules\user\models\forms\Registration::submitted()

    242243244245246247248249250251252253254

        public function actionAdd()     {         $registration = new Registration();         $registration->enableEmailField = true;         $registration->enableUserApproval = false;         $registration->enableMustChangePassword = true;         if ($registration->submitted('save') && $registration->validate() && $registration->register()) {             return $this->redirect(['edit', 'id' => $registration->getUser()->id]);         }           return $this->render('add', ['hForm' => $registration]);     }   

        humhub\modules\admin\controllers\UserController::actionAdd()
        in /home/sites/site100023887/web/mitglieder/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array()
        in /home/sites/site100023887/web/mitglieder/protected/vendor/yiisoft/yii2/base/Controller.php at line 181 – yii\base\InlineAction::runWithParams()
        in /home/sites/site100023887/web/mitglieder/protected/vendor/yiisoft/yii2/base/Module.php at line 534 – yii\base\Controller::runAction()
        in /home/sites/site100023887/web/mitglieder/protected/vendor/yiisoft/yii2/web/Application.php at line 104 – yii\base\Module::runAction()
        in /home/sites/site100023887/web/mitglieder/protected/vendor/yiisoft/yii2/base/Application.php at line 392 – yii\web\Application::handleRequest()
        in /home/sites/site100023887/web/mitglieder/index.php at line 25 – yii\base\Application::run()

    19202122232425

        require(__DIR__ . '/protected/humhub/config/web.php'),     (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],     require(__DIR__ . '/protected/config/common.php'),     require(__DIR__ . '/protected/config/web.php') );   (new humhub\components\Application($config))->run(); 

$_GET = [     'r' => 'admin/user/add', ];  $_COOKIE = [     '_csrf' => 'e3f501808bdb6096b8d219c04c19ff9ce22d7dbe6b7c06aa5ac51f3095a40cb4a:2:{i:0;s:5:"_csrf";i:1;s:32:"cLMd1BjBdu60o2LmqjyaxwcWhmn_SF6M";}',     'PHPSESSID' => 'pt9tqbh3ocmksb04264si3r8le',     '_identity' => '611299257777472e47c1bd4e32c0c0d5a8623745dc90af4213d3970dd72efcaca:2:{i:0;s:9:"_identity";i:1;s:50:"[1,"de78639b-1eb8-4f4f-bd13-a3aa18bae96f",2592000]";}', ];  $_SESSION = [     '__flash' => [],     '__returnUrl' => 'http://s100023887.ngcobalt331.manitu.net/mitglieder/index.php?r=dashboard%2Fdashboard',     '__id' => 1,     '__expire' => 1618309621,     'currentAuthClientId' => 'local',     'user.canSeeAdminSection' => true,     'live.poll.lastQueryTime' => 1618308190, ];

7720bc76-2d98-4790-873b-a949b8f09db1.png

2021-04-13, 12:03:41

Apache

Yii Framework/2.0.40

### What steps will reproduce the problem?

Just a fresh installing might help.

### What is the expected result?

that the error does not occure and also that it is possible to add users.

### What do you get instead?

error message

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.1
| PHP version      | 7.4
| Operating system | linux 5.4.8, gentoo

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
Please check #4990, this seems related

**Comment by luke-** [comment]
@stockh0lm Does this error occur on a fresh installation? Were there any errors during the installation process?

Can you please attach a screenshot of the page: Administration -> Infromation -> Database?
