### ISSUE TITLE
No Video Thumbnail on iOS

### ISSUE THREAD

**Issue by DezzyTee** [humhub/humhub#5009]
### What steps will reproduce the problem?
Browse HumHub with iOS and find a posted video.

### What is the expected result?
HumHub shows a video thumbnail before playing it.

### What do you get instead?
Blank screen until you play the video.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.1
| PHP version      | 7.3
| Operating system | Debian 10

The reason for the issue lies with iOS Safari but there is an easy workaround that should be implemented in Humhub.
All uploaded videos should be loaded at 0.1s. There is an easy html5 fix for this but I do not know how to implement it into the code that it affects every video on the site.

The code:
`<video preload="metadata" controls>
    <source src="video.mp4#t=0.1" type="video/mp4">
</video>`

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look here?

**Comment by yurabakhtin** [comment]
@luke- Yes, I confirm the issue exists even on MacOS Safari browser:

Safari:
<img width="664" alt="safari_before" src="https://user-images.githubusercontent.com/6995524/126502105-6d32dc0d-78d5-4405-adaf-2e65ffb8707b.png">

Chrome, Firefox:
<img width="665" alt="chrome_before" src="https://user-images.githubusercontent.com/6995524/126502318-3c813c08-4944-4470-a9e3-b09fc0ee9d4a.png">

I have fixed this in PR https://github.com/humhub/humhub/pull/5184 with the suggested solution but I used `#t=0.001` as it advised here https://muffinman.io/blog/hack-for-ios-safari-to-display-html-video-thumbnail/:

Safari after fix:
<img width="668" alt="safari_after" src="https://user-images.githubusercontent.com/6995524/126502223-a75d5339-436b-4750-99d1-df4b780bdb13.png">

**Comment by luke-** [comment]
@yurabakhtin Thank you!
