### ISSUE TITLE
online?

### ISSUE THREAD

**Issue by dimontajik** [humhub/humhub#501]
suggest that the system has built-in when the user on the site online

![web](https://cloud.githubusercontent.com/assets/10101408/5426908/31fe0562-83a4-11e4-8025-36a6318e0eb5.jpg)

**Comment by dimontajik** [comment]
I think this is a very important feature

**Comment by Felli** [comment]
I believe this module [here](https://github.com/001101/humhub-module-onlineusers) does more than enough at the moment?
