### ISSUE TITLE
Uploads fail/do not show up if $_SERVER['SERVER_SOFTWARE'] is not provided

### ISSUE THREAD

**Issue by psg-webdev** [humhub/humhub#5013]
### What steps will reproduce the problem?
Having a system running nginx & php with a small amount of env vars ($_SERVER), with 'SERVER_SOFTWARE' empty or not set.

### What is the expected result?
Posts showing previews of uploads/images, files are available.

### What do you get instead?
Posts with placeholders/no images instead of uploads/images, files not available.

### Additional info
https://www.php.net/manual/en/reserved.variables.server.php

| Q                | A
| ---------------- | ---
| nginx | 1.18.0 
| HumHub version   | 1.8.1
| PHP version      |  7.4
| Operating system | Ubuntu 20.04.2 LTS

The reason for the issue is that php may provide informations in env vars but it is not a must (see link in additional info).

Our workaround:
in web/protected/humhub/components/Response.php:24
replace:
    `if (strpos($_SERVER['SERVER_SOFTWARE'], 'nginx') === 0) {`
with:
    `if (!isset($_SERVER['SERVER_SOFTWARE']) || strpos($_SERVER['SERVER_SOFTWARE'], 'nginx') === 0) {`

Error message:
yii\base\ErrorException: Undefined index: SERVER_SOFTWARE in /protected/humhub/components/Response.php:24

**Comment by luke-** [comment]
This should only occur with "XSendFile" enabled or?
![image](https://user-images.githubusercontent.com/4736168/115008862-f01d9980-9eab-11eb-900e-5558d4c0e577.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5021

> This should only occur with "XSendFile" enabled or?

Yes.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
