### ISSUE TITLE
Add a group permission to be able to allow impersonate to non sys admin group

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5016]
It would be great to have a group permission setting to enable a non system admin group to use impersonate feature.
This is useful for network moderator or someone making the support, but that should not have system administration access.
I can code it and make a pull request if you want.

**Comment by luke-** [comment]
Would it make sense to link this permission to the Manage User permission?

However, we would then have to make sure that the user cannot become a SystemAdmin user account.

**Comment by funkycram** [comment]
I think this could be right, yes. Tell me if you want me to do an PR for that or if we wait for other suggestions.

**Comment by luke-** [comment]
Yes, would be great if you make a PR for it, that is based on the ManageUser Permission.

**Comment by funkycram** [comment]
https://github.com/humhub/humhub/pull/5032

**Comment by luke-** [comment]
@funkycram Thanks, is merged!
