### ISSUE TITLE
File remain after delete space

### ISSUE THREAD

**Issue by sparrowyang** [humhub/humhub#5017]
HI~
### What steps will reproduce the problem?
I had deleted a space in my hub
### What is the expected result?
I  expect this file will be removed. and free my space.
### What do you get instead?
 I see the files which belong this space still remain in my server. There are too big (6GB).
### Additional info
- I have tried all yii function (such as cron,files,cache and so on) ,but it seem dons't work well.
- I run humhub in my phone with termux.

thanks 

| Q                | A
| ---------------- | ---
| HumHub version   |  1.8.1
| PHP version      | 8.0.2
| Operating system | Android OS, aarch

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
错误  Sun, 18 Apr 2021 09:29:31 +0000 yii\base\ErrorException:8192yii\base\ErrorException: Required parameter $params follows optional parameter $attribute in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/models/Folder.php:599 Stack trace: #0 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): yii\base\ErrorHandler->handleError(8192, 'Required parame...', '/data/data/com....', 599) #1 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include() #2 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/Module.php(78): yii\BaseYii::autoload('humhub\\modules\\...') #3 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/humhub/components/ModuleManager.php(388): humhub\modules\cfiles\Module->disable() #4 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/humhub/modules/marketplace/commands/MarketplaceController.php(114): humhub\components\ModuleManager->removeModule('cfiles') #5 [internal function]: humhub\modules\marketplace\commands\MarketplaceController->actionRemove('cfiles') #6 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #7 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #8 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('remove', Array) #9 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('remove', Array) #10 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('module/remove', Array) #11 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('module/remove', Array) #12 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #13 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/yii(29): yii\base\Application->run() #14 {main}
错误  Sun, 18 Apr 2021 09:29:25 +0000 yii\console\Exceptionyii\console\Exception: 函数缺少参数：moduleId in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php:243 Stack trace: #0 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(51): yii\console\Controller->bindActionParams(Object(yii\base\InlineAction), Array) #1 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #2 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('remove', Array) #3 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('remove', Array) #4 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('module/remove', Array) #5 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('module/remove', Array) #6 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #7 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/yii(29): yii\base\Application->run() #8 {main}
错误  Sun, 18 Apr 2021 09:29:02 +0000 yii\base\ErrorException:8192yii\base\ErrorException: Required parameter $params follows optional parameter $attribute in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/models/Folder.php:599 Stack trace: #0 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): yii\base\ErrorHandler->handleError(8192, 'Required parame...', '/data/data/com....', 599) #1 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include() #2 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/Module.php(78): yii\BaseYii::autoload('humhub\\modules\\...') #3 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/humhub/components/ModuleManager.php(388): humhub\modules\cfiles\Module->disable() #4 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/humhub/modules/admin/controllers/ModuleController.php(195): humhub\components\ModuleManager->removeModule('cfiles') #5 [internal function]: humhub\modules\admin\controllers\ModuleController->actionRemove() #6 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #7 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #8 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('remove', Array) #9 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('admin/module/re...', Array) #10 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/index.php(25): yii\base\Application->run() #12 {main}
错误  Sun, 18 Apr 2021 09:27:55 +0000 yii\base\ErrorException:8192yii\base\ErrorException: Required parameter $params follows optional parameter $attribute in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/models/FileSystemItem.php:160 Stack trace: #0 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): yii\base\ErrorHandler->handleError(8192, 'Required parame...', '/data/data/com....', 160) #1 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include() #2 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/models/File.php(31): yii\BaseYii::autoload('humhub\\modules\\...') #3 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include('/data/data/com....') #4 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/Events.php(95): yii\BaseYii::autoload('humhub\\modules\\...') #5 [internal function]: humhub\modules\cfiles\Events::onAfterFileAction(Object(yii\base\ActionEvent)) #6 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\ActionEvent)) #7 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('humhub\\modules\\...', 'afterAction', Object(yii\base\ActionEvent)) #8 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(329): yii\base\Component->trigger('afterAction', Object(yii\base\ActionEvent)) #9 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(183): yii\base\Controller->afterAction(Object(humhub\modules\file\actions\DownloadAction), NULL) #10 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('download', Array) #11 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('file/file/downl...', Array) #12 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/index.php(25): yii\base\Application->run() #14 {main}
错误  Sun, 18 Apr 2021 09:27:35 +0000 yii\base\ErrorException:8192yii\base\ErrorException: Required parameter $params follows optional parameter $attribute in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/models/FileSystemItem.php:160 Stack trace: #0 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): yii\base\ErrorHandler->handleError(8192, 'Required parame...', '/data/data/com....', 160) #1 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include() #2 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/models/File.php(31): yii\BaseYii::autoload('humhub\\modules\\...') #3 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include('/data/data/com....') #4 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/Events.php(95): yii\BaseYii::autoload('humhub\\modules\\...') #5 [internal function]: humhub\modules\cfiles\Events::onAfterFileAction(Object(yii\base\ActionEvent)) #6 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\ActionEvent)) #7 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('humhub\\modules\\...', 'afterAction', Object(yii\base\ActionEvent)) #8 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(329): yii\base\Component->trigger('afterAction', Object(yii\base\ActionEvent)) #9 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(183): yii\base\Controller->afterAction(Object(humhub\modules\file\actions\DownloadAction), NULL) #10 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('download', Array) #11 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('file/file/downl...', Array) #12 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/index.php(25): yii\base\Application->run() #14 {main}
错误  Sun, 18 Apr 2021 09:27:35 +0000 yii\base\ErrorException:8192yii\base\ErrorException: Required parameter $params follows optional parameter $attribute in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/models/FileSystemItem.php:160 Stack trace: #0 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): yii\base\ErrorHandler->handleError(8192, 'Required parame...', '/data/data/com....', 160) #1 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include() #2 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/models/File.php(31): yii\BaseYii::autoload('humhub\\modules\\...') #3 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include('/data/data/com....') #4 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/modules/cfiles/Events.php(95): yii\BaseYii::autoload('humhub\\modules\\...') #5 [internal function]: humhub\modules\cfiles\Events::onAfterFileAction(Object(yii\base\ActionEvent)) #6 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\ActionEvent)) #7 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('humhub\\modules\\...', 'afterAction', Object(yii\base\ActionEvent)) #8 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(329): yii\base\Component->trigger('afterAction', Object(yii\base\ActionEvent)) #9 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(183): yii\base\Controller->afterAction(Object(humhub\modules\file\actions\DownloadAction), NULL) #10 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('download', Array) #11 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('file/file/downl...', Array) #12 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/index.php(25): yii\base\Application->run() #14 {main}
错误  Sun, 18 Apr 2021 09:25:33 +0000 yii\console\Exceptionyii\console\Exception: You should specify cache components names in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/controllers/CacheController.php:78 Stack trace: #0 [internal function]: yii\console\controllers\CacheController->actionFlush() #1 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #2 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #3 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('flush', Array) #4 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('flush', Array) #5 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('cache/flush', Array) #6 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('cache/flush', Array) #7 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #8 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/yii(29): yii\base\Application->run() #9 {main}
错误  Sun, 18 Apr 2021 09:24:47 +0000 yii\console\Exceptionyii\console\Exception: 函数缺少参数：configFile, bundleFile in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php:243 Stack trace: #0 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(51): yii\console\Controller->bindActionParams(Object(yii\base\InlineAction), Array) #1 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #2 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('compress', Array) #3 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('compress', Array) #4 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('asset/compress', Array) #5 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('asset/compress', Array) #6 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #7 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/yii(29): yii\base\Application->run() #8 {main}
错误  Sun, 18 Apr 2021 09:24:42 +0000 yii\console\Exceptionyii\console\Exception: 函数缺少参数：configFile, bundleFile in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php:243 Stack trace: #0 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(51): yii\console\Controller->bindActionParams(Object(yii\base\InlineAction), Array) #1 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #2 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('', Array) #3 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('', Array) #4 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('asset', Array) #5 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('asset', Array) #6 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #7 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/yii(29): yii\base\Application->run() #8 {main}
错误  Sat, 17 Apr 2021 15:10:26 +0000 yii\console\Exceptionyii\console\Exception: You should specify cache components names in /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/controllers/CacheController.php:78 Stack trace: #0 [internal function]: yii\console\controllers\CacheController->actionFlush() #1 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #2 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #3 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('flush', Array) #4 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('flush', Array) #5 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('cache/flush', Array) #6 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('cache/flush', Array) #7 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #8 /data/data/com.termux/files/usr/share/apache2/default-site/htdocs/humhub/protected/yii(29): yii\base\Application->run() #9 {main}

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
I cant open community, too slow

**Comment by luke-** [comment]
@sparrowyang The space is deleted but the files remain in the Uploads folder?

Does this only affect very large files? Can you recreate this on another environment or is it only on your Android?

**Comment by sparrowyang** [comment]
@luke-  I have tested again on my Android , and I think I find the reason:
when I upload a large file, usually more than 1 GB ,but it was failed . it show "An unexpected error has been found. If the error persists, please contact the site administrator". whereas , the file was uploaded complete when I check my upload folder. So, When I delete this space ,the file remained.

----
php.ini:
```
allow_url_include = On

upload_max_filesize = 5000M

post_max_size = 3000M

display_errors = Off

```

**Comment by luke-** [comment]
So the missing cleanup only happens for files which threw an error during the upload?
Are the files  in the Files module or are they embedded in a post?

**Comment by sparrowyang** [comment]
No, it doesn't see any files in my browser view

**Comment by luke-** [comment]
Hmm, In the database table "file" an entry is created for each uploaded file. If object_model and object_id is not set, the file will be deleted automatically after 48 hours.

For your error regarding the error with manually deleted files, I created a PR.
