### ISSUE TITLE
wall bug

### ISSUE THREAD

**Issue by dimontajik** [humhub/humhub#502]
when I write a message on the wall, after you take appears in English, the system itself is in Russian I

![3](https://cloud.githubusercontent.com/assets/10101408/5426955/0d0ee82c-83a7-11e4-8304-157ca2cda94c.jpg)

**Comment by luke-** [comment]
Already fixed? I cannot reproduce it yet.

Please reopen when still a problem.

**Comment by Vatarus** [comment]
Yes, fixed!
