### ISSUE TITLE
Disable text wrapping in stream richtext 

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#5024]
![image](https://user-images.githubusercontent.com/38326726/115231948-789f7280-a116-11eb-8137-72fd5a17e258.png)

Might look better if we do not automatically wrap up the text within the stream entries. Currently, there should be a global setting for this.

**Comment by luke-** [comment]
@yurabakhtin Would be great if we can turn off the wrapping behavior for richtext only. 

For people who want to have this, we could then provide a CSS option to enable it again?

**Comment by yurabakhtin** [comment]
@luke- I have removed the work wrapping in PR https://github.com/humhub/humhub/pull/5035

> For people who want to have this, we could then provide a CSS option to enable it again?

Where do you want to add the setting, maybe on the page `/admin/setting/design` "Administration"->"Settings"->"Appearance"? We could add there a checkbox like `[ ] Wrap words in steam content` and if it is enabled we will append some new class to a wall entry.

**Comment by luke-** [comment]
@yurabakhtin Thanks, for people who care, they can manually add the stylesheet back.
