### ISSUE TITLE
add text auto formated

### ISSUE THREAD

**Issue by radiolip** [humhub/humhub#503]
When copy text from other sites and paste to humhub, it is not formated still gaps, spaces, etc.

![capture1](https://cloud.githubusercontent.com/assets/9461399/5427702/c43c1af0-835d-11e4-92d6-3e3bfbbc9bf8.PNG)

![capture](https://cloud.githubusercontent.com/assets/9461399/5427703/c44038d8-835d-11e4-98d8-5c90920f1779.PNG)

**Comment by luke-** [comment]
We only support text in posts
