### ISSUE TITLE
RichTextToShortTextConverter should render image as [image]

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5037]
Like `[table]`  and `[code block]` the https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/widgets/richtext/converter/RichTextToShortTextConverter.php#L77  should also render images as `[Image]`.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5040

**Comment by yurabakhtin** [comment]
@luke- Please review how I fixed tests in commit https://github.com/humhub/humhub/pull/5040/commits/0537b12db401bd2d1e9a203f65c2d5b7b6dfbb2c, there is a result of the function `RichText::convert($markdown, RichText::FORMAT_SHORTTEXT, $options);`, do you think the results are correct and what you expected to see for this task?

**Comment by luke-** [comment]
@yurabakhtin Looks good. For RichText::FORMAT_SHORTTEXT this should be ok.

**Comment by yurabakhtin** [comment]
@luke- Then the PR can be merged.
