### ISSUE TITLE
IPV6 server can't reach the Marketplace...

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#5047]
### Is your feature request related to a problem? Please describe.
I install a humhub ver.1.8.1 on debian10 32bit server with IPV6.
After setup I log in, but it can't show the Maraketplace.
And Admin -> Information -> log shows:
![erorrs](https://user-images.githubusercontent.com/19162094/116192164-6e115880-a768-11eb-97e2-9fc4f23bd4c9.png)

### Describe the solution you'd like
I don't know how to solve this.

### Describe alternatives you've considered
...?? curl error?  What's going on?

**Comment by luke-** [comment]
@tomofu74 Unfortunately, our Marketplace or API is currently IPv4 only. But I have opened an internal issue here. I hope that we can support it in the next months.

**Comment by tomofu74** [comment]
We commend your efforts for operation of the server to be stable.
BUT I'm very sorry, It may be my mistake. The firewall was closing the dhcp client port, so the server wasn't aware of dns and couldn't look up the way to the humhub server. I solved this problem, and after installing php-json and php-mbstring with apt, it leads to Marketplace.

Thank you, anyway.
