### ISSUE TITLE
Required profile field should not be required in administration

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5049]
### Is your feature request related to a problem? Please describe.

1. Check a profile field as required.
2. Edit a user's account: `/admin/user/edit?id=xxx`
3. You want to change only his groups for example.
4. As the user has not yet filled this new required field, you cannot change is groups unless you fill it for him

The problem is that you often don't know what value to fill for an other user's profile...
And some users never update their account, so you can have this problem many months after making the field required.

### Describe the solution you'd like

Required fields should be required only for the user concerned, not for administrator.

**Comment by luke-** [comment]
I agree with that. There should already be a separate scenario for admin edits in the model class.

**Comment by luke-** [comment]
We should also disable the requirement on the user cli commands.

**Comment by funkycram** [comment]
Maybe in https://github.com/humhub/humhub/blob/98efeb4eb455b85104634b250c62387dfb32f4cf/protected/humhub/modules/user/models/fieldtype/BaseType.php#L302 replace the `if ($this->profileField->required)` with:
```
if ($this->profileField->required && !Yii::$app->user->can(ManageUsers::class) && !Yii::$app->request->isConsoleRequest) {
```

**Comment by luke-** [comment]
Probably it is enough to comment out this line: https://github.com/humhub/humhub/blob/98efeb4eb455b85104634b250c62387dfb32f4cf/protected/humhub/modules/user/models/Profile.php#L117

**Comment by funkycram** [comment]
Commenting this line works for changing group (for example), but all profile fields are disabled (an admin cannot change the values of users' profile fields).

**Comment by luke-** [comment]
https://github.com/humhub/humhub/blob/98efeb4eb455b85104634b250c62387dfb32f4cf/protected/humhub/modules/user/models/fieldtype/BaseType.php#L299

Maybe something like:

```
$rules[] = [$this->profileField->internal_name, 'required', 'except' => Profile::SCENARIO_EDIT_ADMIN];
```

**Comment by funkycram** [comment]
Yes, this solution is fine (tested), thanks!
And for CLI, should we add `&& !Yii::$app->request->isConsoleRequest` in the `if`condition ?

**Comment by luke-** [comment]
Great. The console should also use the scenario, so no additional conditions should be needed here.

**Comment by funkycram** [comment]
@luke- Checkbox field type needed also to have this scenario: https://github.com/humhub/humhub/pull/5180

**Comment by luke-** [comment]
@funkycram thanks, is merged!
