### ISSUE TITLE
Preserve linebreaks in Logging

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#5061]
### Is your feature request related to a problem? Please describe.

The messages displayed on the Logging tab are missing line feeds which makes them very hard to read and understand, take this example from #2026:
> exception 'Exception' with message 'Make sure all files are writable!' in /var/www/humhub-1.1.0/protected/modules/updater/modules/packageinstaller/controllers/InstallController.php:54 Stack trace: #0 [internal function]: humhub\modules\updater\modules\packageinstaller\controllers\InstallController->actionValidate() #1 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #2 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #3 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('validate', Array) #4 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('package-install...', Array) #5 /var/www/humhub-1.1.0/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /var/www/humhub-1.1.0/index.php(25): yii\base\Application->run() #7 {main}

### Describe the solution you'd like
Here is a log that I manually formatted by adding line breaks:

```
Exception: Make sure all files are writable! 
(/var/www/[redacted]/html/protected/humhub/modules/file/actions/DownloadAction.php) in 
/var/www/[redacted]/html/protected/modules/updater/modules/packageinstaller/controllers/InstallController.php:58

Stack trace:
#0 [internal function]: humhub\modules\updater\modules\packageinstaller\controllers\InstallController->actionValidate()
#1 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('validate', Array)
#4 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('package-install...', Array) 
#5 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request)) 
#6 /var/www/[redacted]/html/index.php(25): yii\base\Application->run() 
#7 {main}
```
To save everyone from the hassle of manually formatting the log messages or reading unformatted log messages, I propose to format them already in the Logging view.

I'm quite sure that they were previously formatted similar to what I did but the line breaks are lost at some point. Maybe a simple `s/\n/<br>` or some `<pre>...</pre>` at the right place would be sufficient.

**Comment by dreua** [comment]
Thank you, looks great in the beta :heart: :+1:

**Comment by luke-** [comment]
@dreua Thanks for the feedback!
