### ISSUE TITLE
User Admin: Show User ID

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5062]
### Is your feature request related to a problem? Please describe.

We need a possibility to show the user id in the user admin.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/4736168/116886200-0e63f300-ac29-11eb-89f7-be5f059b26cb.png)

**Comment by ArchBlood** [comment]
`Yii::$app->user->guid` would normally be used for this case? :thinking:

**Comment by luke-** [comment]
In some cases the admin needs an ID of the user. Possibly, we could also display the GUID here in addition. But two fields would probably be a bit much here

**Comment by ArchBlood** [comment]
> In some cases the admin needs an ID of the user. Possibly, we could also display the GUID here in addition. But two fields would probably be a bit much here

Maybe an alternative would be allowing the admin a field type option to display this as well as the GUID for those that have the Manage Users permissions? Would probably have to configure it so that it would display in a selected area though, thoughts on how this could be accomplished?

**Comment by yurabakhtin** [comment]
@luke- I have added only `ID` field. PR https://github.com/humhub/humhub/pull/5085.

**Comment by luke-** [comment]
@yurabakhtin ok thanks!
