### ISSUE TITLE
Cron error when `pcntl` PHP module is not enabled  

### ISSUE THREAD

**Issue by addictif80** [humhub/humhub#5065]
### What steps will reproduce the problem?
CronJob
### What is the expected result?
Cron task successfully finished
### What do you get instead?
```
Error: Call to undefined function yii\queue\cli\pcntl_signal() in /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2-queue/src/cli/SignalLoop.php:74 Stack trace: #0 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\queue\cli\SignalLoop->init() #1 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2-queue/src/cli/SignalLoop.php(61): yii\base\BaseObject->__construct() #2 [internal function]: yii\queue\cli\SignalLoop->__construct() #3 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/di/Container.php(412): ReflectionClass->newInstanceArgs() #4 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build() #5 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get() #6 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(104): yii\BaseYii::createObject() #7 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker() #8 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run() #9 [internal function]: yii\queue\db\Command->actionRun() #10 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #11 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams() #12 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction() #13 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction() #14 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction() #15 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction() #16 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest() #17 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/yii(29): yii\base\Application->run() #18 {main}
```

This error log is added every one minute (my cron schedule)
### Additional info
**There are my cron file** 
```
* * * * * /usr/bin/php /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/yii queue/run >/dev/null 2>&1
* * * * * /usr/bin/php /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/yii cron/run >/dev/null 2>&1
```
**I don't know if this info log is linked to the CRON error, but if it can help for fix this issue (appear every minutes) :** 
```
$_GET = [] $_SERVER = [ 'HOME' => '/home/a.berlamont' 'LOGNAME' => 'a.berlamont' 'PATH' => '/usr/bin:/bin' 'LANG' => 'fr_FR.UTF-8' 'SHELL' => '/bin/sh' 'PWD' => '/home/a.berlamont' 'PHP_SELF' => '/home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/yii' 'SCRIPT_NAME' => '/home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/yii' 'SCRIPT_FILENAME' => '/home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/yii' 'PATH_TRANSLATED' => '/home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/yii' 'DOCUMENT_ROOT' => '' 'REQUEST_TIME_FLOAT' => 1620710161.2555 'REQUEST_TIME' => 1620710161 'argv' => [ 0 => '/home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/yii' 1 => 'queue/run' ] 'argc' => 2 ]
```

**HumHub is installed with Softaculous**

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.2
| PHP version      | 7.4-FPM
| Operating system | Debian 10 with VestaCP

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
@addictif80 Can you please try the `isolate=0` option? 
https://docs.humhub.org/docs/admin/cron-jobs#cronjob-configuration

**Comment by addictif80** [comment]
@luke- Thanks for your reply
If i add the isolate=0 option, it return this error to log

`yii\console\Exception: Option inconnue : --isolate. Options available: --color, --interactive, --help, --silentExitOnException in /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/console/Controller.php:175 Stack trace: #0 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction() #1 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction() #2 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction() #3 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest() #4 /home/a.berlamont/web/social.gsr-rp.fr/public_html/protected/yii(29): yii\base\Application->run() #5 {main}`

**Comment by luke-** [comment]
@addictif80 The `-isolate` option must be added to the `queue/run` command.

**Comment by addictif80** [comment]
@luke- 
it's already added
`/usr/bin/php /home/USER/web/social.gsr-rp.fr/public_html/protected/yii queue/run --isolate=0 >/dev/null 2>&1`

**Comment by luke-** [comment]
@addictif80 Your hosting provider blocks a required PHP function. Maybe you can ask your hoster to unblock it or you could change the hoster.

**Comment by addictif80** [comment]
Hello, im m'y own provider, i have a VPS with VestaCP Web hosting control panel.
Where can i enable this option ?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please add a check for this to the requirement checker?

PR https://github.com/humhub/humhub/pull/5071

<img width="856" alt="pcntl" src="https://user-images.githubusercontent.com/6995524/117984900-e9663300-b340-11eb-856e-9b5d07911606.png">

**Comment by addictif80** [comment]
Hello, i think i've found the problem : 
In my php.in config file, i've this line
`disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,pcntl_unshare,`

When i comment that with ";" at line start, the HumHub log stay empty.
The problem : what can i test if the cronjob work proprely ?
In the "Backgroun tasks" > "Latest execution (hours)" show "13 minutes ago", but my cron tasks are set to every minutes.

(Realy sorry for my english, i'm a french user of HumHub)

**Comment by addictif80** [comment]
Ok, i've solved this issue.
There is the php.ini config file "disabled functions".
For solve this problem, just comment the followed line with ";" in the php.ini config file :
`disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,pcntl_unshare,`
