### ISSUE TITLE
 Cron Jobs not working

### ISSUE THREAD

**Issue by Bechaker** [humhub/humhub#5074]
Hello
This error started to appear and I can't find any evidence that tells me why

"The cron job running jobs in the background (queue) doesn't seem to be working properly."

![Error1](https://user-images.githubusercontent.com/43526466/118208337-92418a80-b434-11eb-913d-e9057f396635.jpg)
![error2](https://user-images.githubusercontent.com/43526466/118208338-92da2100-b434-11eb-8f17-3e2b72aefcec.jpg)

Thank you !!

_Originally posted by @Bechaker in https://github.com/humhub/humhub/issues/3293#issuecomment-840935077_

**Comment by GrizzBees** [comment]
I have exactly the same issue. What does your background jobs say? Do you have a lot of jobs in 'waiting'? Are you running on a shared server environment?

**Comment by luke-** [comment]
What happens if you run the cron or queue command manually from the console?

**Comment by GrizzBees** [comment]
I don't have access to a console on shared server cpanel. I have checked with the hosting co and the job is running but it doesn't process any jobs in the queue and have the same message as @Bechaker. i have tried --isolate=0 but the job stops running. nothing in the logs.

**Comment by Bechaker** [comment]
Hello @GrizzBees @luke- 

In the log view, there is no message about what the problem is, nothing appears when I look at the console (I am in a virtual environment testing the solution), but the behavior is strange, it smells like a bug

I am using the latest version, could it be that it has a fault?

Thank you

Bechaker

**Comment by ArchBlood** [comment]
> Hello @GrizzBees @luke-
> 
> In the log view, there is no message about what the problem is, nothing appears when I look at the console (I am in a virtual environment testing the solution), but the behavior is strange, it smells like a bug
> 
> I am using the latest version, could it be that it has a fault?
> 
> Thank you
> 
> Bechaker

Is it a Linux or Windows 10 based VPS? Overall it's not a bug, it's more than likely a configuration issue on the server itself, here are a few common reasons a failure of corn jobs/crontabs will occur;

https://blog.cronitor.io/4-common-reasons-cron-jobs-fail-ce067948432b

**Comment by Bechaker** [comment]
Hello @GrizzBees 

The problem I have is that every so often (a matter of minutes) I get queued, and only cleaning the queue disappears the error or executing the previous script manually, I have an error, do I have to program the cronies?

Example:
#Execution of cron manually
/ usr / bin / php / var / www / humhub / protected / yii cron / run

Thank you

**Comment by luke-** [comment]
Can you please provide a screenshot of your cronjob configuration?

**Comment by GrizzBees** [comment]
here is my cron setup
![Screenshot 2021-05-20 112407](https://user-images.githubusercontent.com/84171657/118904833-f8ab3900-b95d-11eb-948a-7bc66d334cd9.jpg)

**Comment by GrizzBees** [comment]
I still get The cron job for the background jobs (queue) does not seem to work properly.

**Comment by ArchBlood** [comment]
@GrizzBees, here's some information that should be known `0` is set so every `0` minutes your Cron will execute the command every hour, every day, every month, and every weekday, of course, there is also the possibility that the cron won't execute at all, `* * * * *` will run the cron everything minute which is more commonly used, the other issue I'm seeing in your cron command is that you've added `* * * * *` at the end of the command, which isn't needed and will also throw an error, getting on with the issues, you're adding multiple commands within a single command, you need to create 2 separate commands, one for `cron/run` & one for `queue/run`

For most shared hosting you can only run a single cron every `5` minutes just in case, you should ask your server provider if there are any limits set on how many cron tasks that can be ran per X amount of minutes

**Comment by GrizzBees** [comment]
Boom that worked - thanks @ArchBlood

**Comment by Bechaker** [comment]
@ArchBlood thank you!! RESOLVED

**Comment by alexito2** [comment]
@Bechaker @GrizzBees 

can help me?🥺
