### ISSUE TITLE
Comments appear in summaries emails even if the option is not set in settings

### ISSUE THREAD

**Issue by superseby2** [humhub/humhub#5079]
### What steps will reproduce the problem?
Uncheck 
"Comments - Whenever a new comment was written."

### What is the expected result?
Not reading anything related to comments in mail summary.

### What do you get instead?
Still reading 'new comment' info in mail summary
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.0
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by superseby2** [comment]
Sorry for the noise. I was not looking in the right place!

**Comment by superseby2** [comment]
Sorry for x2 the noise .. This issue is very real I meant to close another issue and I mixed things up)

**Comment by yurabakhtin** [comment]
@superseby2 Please review my tests, for me it looks work as expected:

Test with **enabled** option:
<img width="1153" alt="enabled_option" src="https://user-images.githubusercontent.com/6995524/119666956-85626500-be3e-11eb-9950-4948c1500abe.png">

Test with **disabled** option:
<img width="861" alt="disabled_option" src="https://user-images.githubusercontent.com/6995524/119666993-8dbaa000-be3e-11eb-87f3-074b6965d525.png">

**Comment by superseby2** [comment]
You are right. Things are working as they should. I mixed up emails coming from different accounts (one with the Comment setting on and one off). 
So sorry for the waste of time .. .I'll make sure to triple check next time. 

Thx again.
