### ISSUE TITLE
Stream sorting based on created_at or updated_at rather than content-id

### ISSUE THREAD

**Issue by jwleon** [humhub/humhub#5086]
This is not really a bug, since HumHub actually does not provide opportunities to change the date and time of content at the moment. So currently you can assume that a higher content-id correlates with a newer content entry and everything works just fine: Depending on the sorting mode, HumHub actually uses either `content.stream_sorting_date` (Mode Stream::SORT_UPDATED_AT) or `content.id` (Mode Stream::SORT_CREATED_AT).

I don't know the actual benefits of using "stream_sorting_date" over "updated_at" in the mode Mode Stream::SORT_UPDATED_AT, **but especially for the mode Stream::SORT_CREATED_AT I think it would be much better to use content.created_at as the sorting field.** The main benefit would be: Content created_at could be changed (manually in the db or by a module or in future HumHub versions by the user?!) to somewhere in the past without potentially messing up stream order.

I stumbled across this issue while writing a small bot that creates HumHub posts from mails on an IMAP server, where the posts have time and date from the original email. Unfortunately, even though created_at was set correctly, they appeared at the beginning of the stream even though the created_at date was way in the past.

My suggestion is to modify the file `/protected/humhub/modules/stream/models/StreamQuery.php` as follows:

```
if ($this->sort == Stream::SORT_UPDATED_AT) {


    $this->_query->orderBy('content.stream_sort_date DESC'); // --- OLD LINE ---
    $this->_query->orderBy('content.updated_at DESC'); // --- NEW LINE ---


    if (!empty($this->from)) {
        $this->_query->andWhere(
            ['or',
                "content.stream_sort_date < (SELECT stream_sort_date FROM content wd WHERE wd.id=:from)",
                ['and',
                    "content.stream_sort_date = (SELECT stream_sort_date FROM content wd WHERE wd.id=:from)",
                    "content.id > :from"
                ],
            ], [':from' => $this->from]);
    } elseif (!empty($this->to)) {
        $this->_query->andWhere(
            ['or',
                "content.stream_sort_date > (SELECT stream_sort_date FROM content wd WHERE wd.id=:to)",
                ['and',
                    "content.stream_sort_date = (SELECT stream_sort_date FROM content wd WHERE wd.id=:to)",
                    "content.id < :to"
                ],
            ], [':to' => $this->to]);
    }
} else {


    $this->_query->orderBy('content.id DESC'); // --- OLD LINE ---
    $this->_query->orderBy('content.created_at DESC'); // --- NEW LINE ---


    if (!empty($this->from)) {
        $this->_query->andWhere("content.id < :from", [':from' => $this->from]);
    } elseif (!empty($this->to)) {
        $this->_query->andWhere("content.id > :to", [':to' => $this->to]);
    }
}
```

I am not 100% firm with database queries and potentially side-effects, especially for "from" and "to" of search queries, so I am not feeling confident making a pull-request for it - in case you want to change it at all.

**Comment by luke-** [comment]
@jwleon  Thanks for the input. For example, `stream_sorting_date` is updated when a content gets a new comment and the content itself does not change.

If I understand you correctly, it would be sufficient for your use case if sorting (by newest) is always done by the `created_at` column? In theory, there is nothing against this, but we should definitely do some performance tests before making such a change.

**Comment by jwleon** [comment]
Ok, now I understand the necessity of having the `stream_sorting_date` field - thanks for the explanation!

That is exactly what I meant - and sure, I understand that those things need testing. But wouldn't `stream_sorting_date`, which is an available sorting field via `Stream::SORT_UPDATED_AT`, have the same performance implications?

**Comment by jwleon** [comment]
Hey! Is this still an issue that will potentially be worked on? Since opening this issue, I am using HumHub with the change mentioned above (`id` > `created_at`) and it works flawlessly, but I would much prefer if this would be default behaviour (since, logically, it should be) and I do not need to integrate the change after each upgrade of HumHub...

Unfortunately, I have no idea how to perform performance tests and I am not into HumHub logic enough to see possible side effects, I can just contribute that I did not experience any in the year since I have been using the modified code... What I see, though, is that the stream filters should use `created_at` as well (maybe). In the UI, one selectes a date - I do not understand how the comparison with `id` works at all...

This feature might seem irrelevant, but it opens up the possibility for plugins and API to insert posts that backdate. I can imagine many cases where this is desireable!
