### ISSUE TITLE
Space description length

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub#5088]
### What steps will reproduce the problem?

Change space description with text more than 100 chars.

### What is the expected result?

At least the input should be restricted by attribute `maxlength=100` before I press "Save".
Either we should not limit the filed from server side at all because DB column `space.description` allows this.

### What do you get instead?

I see error after submit the space form, I think users should not waste a time to calculate chars in the input.

### Additional info

<img width="964" alt="space_desc_limit" src="https://user-images.githubusercontent.com/6995524/120168985-26b73580-c208-11eb-92f8-7d6a52049d87.png">

**Comment by luke-** [comment]
@yurabakhtin This restriction of 100 characters is relatively new. I like the idea of the maximum character length in the input field. Would great if you can add this.

However, I would leave the database field and the ValidationRule as they are for now, as there may be problems with backwards compatibility.

**Comment by yurabakhtin** [comment]
@luke- 

> I like the idea of the maximum character length in the input field. Would great if you can add this.

Ok, fixed in PR https://github.com/humhub/humhub/pull/5092.

**Comment by luke-** [comment]
Thanks!
