### ISSUE TITLE
Summarize "Latest Activity" 

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#5090]
### Is your feature request related to a problem? Please describe.
If you have a lot of active users, posting all of their activities individually in the "Latest News" stream would be cumbersome and unreadable.

### Describe the solution you'd like
How about summarizing and displaying similar activities of users in the past?

### Describe alternatives you've considered
As the activity to let users know what's happening, not who do what.

**Comment by luke-** [comment]
Yes, this would really helps!

See here: https://github.com/humhub/humhub/issues/3430
