### ISSUE TITLE
When posting a Twitter link, in the email received (notifications or summary), the link is mixed up with the following line 

### ISSUE THREAD

**Issue by superseby2** [humhub/humhub#5095]
### What steps will reproduce the problem?

- copy / paste a Twitter link
- The twitter block gets expanded (Oembed)  and your cursor is appearing below it
- Type some content (without entering a new line)

### What is the expected result?

- The link is properly displayed in notification and summaries email

### What do you get instead?

- The link has the following line appended.
-

### Additional info
![edit](https://user-images.githubusercontent.com/32198925/120682275-91809f00-c49c-11eb-97cd-f395bf25fa04.png)
![edit2](https://user-images.githubusercontent.com/32198925/120682748-19ff3f80-c49d-11eb-869f-6b98c2b9e37a.png)

![emai](https://user-images.githubusercontent.com/32198925/120682301-99d8da00-c49c-11eb-9bab-f77b532d23f7.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by superseby2** [comment]
Any update on this ?

Thx !

**Comment by ArchBlood** [comment]
Seems that the email purified the HTML encoding

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5227 - I have added a space around URLs in email.

**Comment by luke-** [comment]
@yurabakhtin Thanks, can you please add some unit tests for this. 

Especially with the RichTextParsers we should always add some unit tests, because there are always many output possibilities/combinations.

**Comment by yurabakhtin** [comment]
@luke- New tests for `RichTextToEmailHtmlConverter` in commit https://github.com/humhub/humhub/pull/5227/commits/71a405923fda9faabccbd46f3ebe1ba4a04d8212.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
