### ISSUE TITLE
HumHub is using UTC server time

### ISSUE THREAD

**Issue by centretarn** [humhub/humhub#5098]
Hi,

I'm facing an issue on my HumHub configuration. HumHub is using UTC and not server timezone for posts, comments ...

I set the correct timezone in the HumHub parameters (Europe/Paris). There, the "reported database time" is shown as UTC time. However, NOW(), CURRENT_TIMESTAMP() or DateTime() with mysql or PHP, return the right UTC+2 server time.

How can I fix it ?

Thanks

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.2
| PHP version      | 8.0.5
| Operating system | Debian 10 / Apache / mariaDB

**Comment by luke-** [comment]
What shows the "Settings - Time zone" at Admiistration -> Information -> Prerequisites?

**Comment by centretarn** [comment]
Here are the prerequisites
![humhub-conf](https://user-images.githubusercontent.com/68742352/120779598-8030a480-c527-11eb-93dc-126823ca87be.jpg)

After further investigation, I noticed that the creation date is OK in the database. The values in the "_created_at_" table are OK (UTC +2). The problem seems to be attached to the date calculation in the _data-original-title_ option. Thus, the text with _timeago_ class is OK, but the hint that is shown on hover is not OK at all with the _datetime_ option.

![humhub-conf2](https://user-images.githubusercontent.com/68742352/120780957-e2d67000-c528-11eb-8332-b44ab0de9cab.jpg)

**Comment by centretarn** [comment]
OK, I fixed it.

All the users had a wrong default timezone in their account parameters : UTC-11:00 Pacific/Midway. That is not even my server timezone. It led to a weird miscaculation of two hours in the tooltip.

I don't know how and why this timezone was set as default and don't understand much more how and why it led to such a silly error in time calculation.
