### ISSUE TITLE
idea to hide the public statistics show

### ISSUE THREAD

**Issue by radiolip** [humhub/humhub#510]
I think this is good idea to hide public statistics like on facebook, vk.com, only show to admins statistics site, online & registered users. Shows public statistics It is not professionally for large projects....

Imagine a situation: Facebook shows how online and registered users in the directory/members.

Lol...

**Comment by acinelli** [comment]
This can be achieved using a custom theme, overriding "views/directory/widgets/memberStats.php".  I simply encapsulated the user-stats panel in a if (Yii::app()->user->isAdmin()) block.

**Comment by luke-** [comment]
Yes you can create a custom theme.

In future the directory module will be optional. So you can also create an own directory which fits your needs.
