### ISSUE TITLE
[1.9] Space Member Count

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5102]
### Is your feature request related to a problem? Please describe.

Use short number counts. See Space Headers

![image](https://user-images.githubusercontent.com/4736168/120892384-51d9c480-c60e-11eb-9713-d94e67642ec8.png)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5105

**Comment by luke-** [comment]
Thanks!
