### ISSUE TITLE
After creating a new captcha the old code is still valid

### ISSUE THREAD

**Issue by steinm** [humhub/humhub#5107]
### What steps will reproduce the problem?
1. Open the login page
2. Enter a valid email address
3. Press tab to forward into the field for the captcha code
4. Enter a false code but memorize the right code and hit tab again
Now the field for the catcha code gets a red border because of the wrong code.
5. Click on the captcha image to create a new code
6. Enter that code into the field and hit tab (this time enter the code shown on the image)
7. The field will again get a red border, even if the code was propperly entered
8. Enter the code from the old captcha you memorized in step 4 and hit tab again
9. Now the field border turns green

### What is the expected result?
A new captcha should correspond with the checked code

### What do you get instead?
An error, even if the captcha code is entered propperly.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.1-1.8.2
| PHP version      |  7.x
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@steinm @luke- Fixed in PR https://github.com/humhub/humhub/pull/5112.

**Comment by luke-** [comment]
@yurabakhtin Awesome thanks!
