### ISSUE TITLE
Advanced profile fields search in directory (mysql)

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#5108]
### Why?
If the social network has a lot of users, its interesting a advanced profile field search in the directory. For exemple:
**Search by state**
/directory/members?_pjax=%23layout-content&_=1623162576327&page=1&keyword=friendship&state=1
When I selecte the preferencial **state** in the advanced search it will show only users from this state. For exemple, in the profile field in mysql, 1 is "New Jersey", and when i search for this, only jerseyans members appears.

**Comment by luke-** [comment]
Will be available with HumHub 1.9

**Comment by marlonbjj** [comment]
thanks :)
