### ISSUE TITLE
Stream will not open if Italian language is selected

### ISSUE THREAD

**Issue by samuk** [humhub/humhub#5110]
### What steps will reproduce the problem?
Install humhub on a Cloudron instance: https://git.atrilahiji.dev/Alt-Ron/cloudron-humhub-app

Or use the hosted version https://xyz.humhub.com/s/somespace

Set your user language to Italian. Browse to any stream.

### What is the expected result?
A stream is visible

### What do you get instead?
An error message saying An unexpected server error occurred. If it repeats, contact your administrator. (in Italian)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.2
| PHP version      | 
| Operating system | Debian

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
If the issue is with the Cloudron repo then this should be reported to them shouldn't it, as for the issue, in general, I'm not seeing any issues with the Italian translations in 1.8.2, could you post your error logs from Administrations > Information > Logging for more information? Also, could you include your PHP version

**Comment by samuk** [comment]
@ArchBlood As I mentioned this issue also happens on spaces hosted by Humhub eg [](https://xyz.humhub.com/s/somespace
)
I'll check what PHP I'm running, but I expect Humhub staff know what version they have on their SAAS?

Here's the log from yesterday

Could not execute queued job! Message: unserialize(): Error at offset 4046 of 4229 bytes Trace:#0 /app/data/public/protected/vendor/yiisoft/yii2-queue/src/Queue.php(230): yii\queue\Queue->unserializeMessage() #1 /app/data/public/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage() #2 /app/data/public/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage() #3 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}() #4 /app/data/public/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func() #5 /app/data/public/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker() #6 /app/data/public/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run() #7 [internal function]: yii\queue\db\Command->actionRun() #8 /app/data/public/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #9 /app/data/public/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams() #10 /app/data/public/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction() #11 /app/data/public/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction() #12 /app/data/public/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction() #13 /app/data/public/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction() #14 /app/data/public/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest() #15 /app/data/public/protected/yii(29): yii\base\Application->run() #16 {main}

**Comment by luke-** [comment]
@samuk Can you please provide exact steps to reproduce the problem on our demo/SaaS hosting? Feel free to create a free new instance for it.

**Comment by samuk** [comment]
1) Create an instance

2) Using English user create some content in a stream

3) Create an Italian user

4) Attempt to view the stream using the Italian user

You could use this instance to verify https://transitionhubs.humhub.com/s/hubs-heart-circle/

Here's a screenshot
https://huhm.lahijiapps.dev/index.php?r=file%2Ffile%2Fdownload&guid=6cf6f3df-8ccb-4270-b3e9-9e394d8f9c54&hash_sha1=8c7100e1

**Comment by luke-** [comment]
Thank you for the test installation. I have created a `hunmhub` test user here for a moment, feel free to delete this user.
The problem seems related to the the "External Calendar" Module. 

You can use the filters for the affected space and then filter by content type. All other content types work. 

Can you then please create an issue here with more information:
https://github.com/humhub-contrib/external_calendar/issues
