### ISSUE TITLE
Humhub 1.8.2 search not working

### ISSUE THREAD

**Issue by r4nc0r** [humhub/humhub#5117]
Hi, we are a business User of Humhub, and recently we updatet to Humhub v1.8.2 and also updated all Modules accordingly.
Now our search doesnt work, if we search for something with a lot of Hits.

### What steps will reproduce the problem?
Search for something that would result in many hits

### What is the expected result?
Get a working search

### What do you get instead?
Internal Server error and the below error Message from the Admin interface
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.2
| PHP version      | 7
| Operating system | debian+docker

```text
ZendSearch\Lucene\Exception\OutOfBoundsException: Terms per query limit is reached. in /var/www/localhost/htdocs/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Search/Query/Wildcard.php:188 
Stack trace: #0 /var/www/localhost/htdocs/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Search/Query/Boolean.php(134): ZendSearch\Lucene\Search\Query\Wildcard->rewrite() 
#1 /var/www/localhost/htdocs/protected/vendor/matthewbdaly/zendsearch/src/ZendSearch/Lucene/Index.php(691): ZendSearch\Lucene\Search\Query\Boolean->rewrite() 
#2 /var/www/localhost/htdocs/protected/humhub/modules/search/engine/ZendLuceneSearch.php(178): ZendSearch\Lucene\Index->find() 
#3 /var/www/localhost/htdocs/protected/humhub/modules/search/controllers/SearchController.php(91): humhub\modules\search\engine\ZendLuceneSearch->find() 
#4 [internal function]: humhub\modules\search\controllers\SearchController->actionIndex() 
#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() 
#6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams() 
#7 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction() 
#8 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction() 
#9 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest() 
#10 /var/www/localhost/htdocs/index.php(25): yii\base\Application->run() #11 {main}
```

**Comment by smashm** [comment]
Can reproduce this error. You can avoid it by increasing this limitation.
![Bildschirmfoto 2021-06-10 um 13 31 18](https://user-images.githubusercontent.com/60502320/121517974-3dbc0b80-c9f0-11eb-9d69-ef53a7eb029b.png)

Example, I set the value to little 48 as my search term (_he_ or _he*_) gives 144 results, whole word _heizdecken_ only 9.
![Bildschirmfoto 2021-06-10 um 13 27 59](https://user-images.githubusercontent.com/60502320/121518373-b02ceb80-c9f0-11eb-83d7-c630b6a8e985.png)

![Bildschirmfoto 2021-06-10 um 13 25 07](https://user-images.githubusercontent.com/60502320/121518410-bae78080-c9f0-11eb-82a7-ef8a4bf4c806.png)

Using _he_ causes an error: 
![Bildschirmfoto 2021-06-10 um 13 27 05](https://user-images.githubusercontent.com/60502320/121518748-203b7180-c9f1-11eb-8c74-6c1d12b2139a.png)

Logging:
![Bildschirmfoto 2021-06-10 um 13 24 17](https://user-images.githubusercontent.com/60502320/121518791-2df0f700-c9f1-11eb-8299-861add913c26.png)


Hope this helps.

**Comment by smashm** [comment]
Or alternatively increase the minimum number of letters in this file:
![Bildschirmfoto 2021-06-10 um 13 52 28](https://user-images.githubusercontent.com/60502320/121521092-f2a3f780-c9f3-11eb-98e5-84b179cfc37a.png)

I don't know, if or how these values can be set in config.php.

**Comment by r4nc0r** [comment]
Thanks for the quick reply, i set searchItemLimit to 0(no limit) and it didnt work. Then I set it to 40000 and it didnt work either :(
I even rebuild the search index in between, deleted the redis cache and my browser cache.

And your second option didnt help because the error occurs on longer strings like "meeting". And a min query Token lenght of 2 or 4 would be ok but 7 is a bit long :)
