### ISSUE TITLE
Incorrect HTML syntax in user profile

### ISSUE THREAD

**Issue by insoln** [humhub/humhub#5124]
### What steps will reproduce the problem?
Fill "About" field for user and view the user's profile About page. Example: https://translate.humhub.org/u/insoln/user/profile/about

### What is the expected result?
Correct label-value output, `.form-control-static` element wrapping RichText output

### What do you get instead?
Depending on browser, there may be extra space before field value or some other visual glitches. Most browsers will forcefully close `p.form-control-static` when see following `div`. As per https://www.w3.org/TR/html401/struct/text.html#h-9.3.1, a div inside a p is syntactically invalid in HTML

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.3
| PHP version      | 7.4.3
| Operating system | Windows 10 21H1, Chrome 91.0.4472.101

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by insoln** [comment]
A nice and neat PR https://github.com/humhub/humhub/pull/5122 for whatever reason doesn't pass tests.

**Comment by luke-** [comment]
I have restarted the tests. Sometimes there are timeouts here.
