### ISSUE TITLE
Web Share Target API

### ISSUE THREAD

**Issue by vpadhariya** [humhub/humhub#5125]
### Is your feature request related to a problem? Please describe.
I am developing a feature in humhub through which I can share Message, Files to Humhub Setup. (Like we share File or Message from Mobile device to different social media platforms etc.)

### Describe the solution you'd like

1. From Mobile, I am able to install Humhub as App (PWA based app)
2. Ability for a user to Share Message, Image, Audio, Video using [Web Share Target API](https://w3c.github.io/web-share-target/)
3. The post will be shared on user's profile or on Space (he can choose the space)
4. [This is the Example](https://github.com/w3c/web-share-target/blob/main/docs/explainer.md) what I am trying to achieve.

### Describe alternatives you've considered

1. as per [Web Share Target API](https://w3c.github.io/web-share-target/) also update manifest.json
2. I also try to wrote my own capture method (In Controller thorugh module)
3. I received the Data successfully (using POST method - Wrote them in logs)
4. Striving to save as "post" (with single Message or with Files uploaded)
5. Want to give experience like Facebook Share from mobile.

Any help around will be much appriciated.

**Comment by vpadhariya** [comment]
I have also created a [community post here](https://community.humhub.com/s/general-discussion/?contentId=241407)

**Comment by luke-** [comment]
Good be integrated similar than: https://www.humhub.com/en/marketplace/socialshare/

**Comment by vpadhariya** [comment]
Hey @luke- thanks for quick response. 

I had developed this module https://www.humhub.com/en/marketplace/socialshare/

This module is for sharing out side from Humhub, means to share a Humhub Post out side social media.

Now what I am looking for is "Share to Humhub" thorugh "[Web Share Target](https://w3c.github.io/web-share-target/)" API.

Like this [example ](https://github.com/w3c/web-share-target/blob/main/docs/explainer.md)

**Comment by luke-** [comment]
Ahso I got it. 

In that case, you probably need to edit the PWA manifest.

Here is the controller for it:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/web/pwa/controllers/ManifestController.php#L38

Here is a sample code to extend the manifest via a module.
https://github.com/humhub-contrib/fcm-push/blob/master/Events.php#L24-L30

It may also be possible to implement this directly in the core.

**Comment by vpadhariya** [comment]
thanks @luke- 

Is there a way I can share Images from my mobile gallery?

Like I select an image from my mobile gallary -> Share to Humhub Mobile App -> My profile post and it should shown like this.

![screenshot-localhost-2021 06 15-19_46_07](https://user-images.githubusercontent.com/570747/122068881-61c58580-ce12-11eb-9c6d-4bd4f717d483.png)

Is there a way do this?

**Comment by vpadhariya** [comment]
@luke- a quick update on this,

finally I have managed to get this done. thanks for your help.

Will publish the Module in future for this. (a lot of test cases + cross testing is going on this)

Thanks.

**Comment by luke-** [comment]
That sounds great. We are very excited about it!

**Comment by vpadhariya** [comment]
@luke- 

Need some inputs from you.

How can I publish my own modules to [Humhub Marketplace](https://www.humhub.com/en/marketplace)?

If you have any guidence it will be a great help.

Thanks.

**Comment by luke-** [comment]
@vpadhariya please get in touch via hello@humhub.com

**Comment by vpadhariya** [comment]
@luke- 

The module is coming soon in Humhub market place.

I will publish it from Parntner site, will inform you when done.

Thanks.

**Comment by luke-** [comment]
@vpadhariya Thank you. We'll get in touch with you.

**Comment by vpadhariya** [comment]
@luke- 

FYI, 

I just published the Web Share Target in the partner store.

https://github.com/olantrust/humhub-websharetarget

**Comment by vpadhariya** [comment]
@luke- I am interesting in publishing this module, can you help me publish this module in Humhub, thanks
