### ISSUE TITLE
Humhub 1.9-beta.1 - the new Spaces directory crashes with PHP 8.0

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5137]
### What steps will reproduce the problem?

Activate PHP 8.0 version
Go to `/spaces`

### What do you get instead?

![hhdev localhost_spaces](https://user-images.githubusercontent.com/23310825/122670993-e7f01c00-d1c4-11eb-8702-9eef1e5e5b66.png)

TypeError: floor(): Argument #1 ($num) must be of type int|float, string given in /var/www/hhdev/protected/humhub/components/i18n/Formatter.php:94
Stack trace:
#0 /var/www/hhdev/protected/humhub/components/i18n/Formatter.php(94): floor()
#1 /var/www/hhdev/protected/humhub/modules/space/widgets/views/spaceDirectoryIcons.php(16): humhub\components\i18n\Formatter->asShortInteger()
#2 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#3 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#4 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#5 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\base\View->render()
#6 /var/www/hhdev/protected/humhub/modules/space/widgets/SpaceDirectoryIcons.php(33): yii\base\Widget->render()
#7 /var/www/hhdev/protected/humhub/components/Widget.php(63): humhub\modules\space\widgets\SpaceDirectoryIcons->run()
#8 /var/www/hhdev/protected/humhub/modules/space/widgets/views/spaceDirectoryCard.php(30): humhub\components\Widget::widget()
#9 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#10 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#11 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#12 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\base\View->render()
#13 /var/www/hhdev/protected/humhub/modules/space/widgets/SpaceDirectoryCard.php(38): yii\base\Widget->render()
#14 /var/www/hhdev/protected/humhub/components/Widget.php(63): humhub\modules\space\widgets\SpaceDirectoryCard->run()
#15 /var/www/hhdev/protected/humhub/modules/space/views/spaces/index.php(46): humhub\components\Widget::widget()
#16 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#17 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#18 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#19 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Controller.php(410): yii\base\View->render()
#20 /var/www/hhdev/protected/humhub/modules/space/controllers/SpacesController.php(69): yii\base\Controller->render()
#21 [internal function]: humhub\modules\space\controllers\SpacesController->actionIndex()
#22 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#23 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#24 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#25 /var/www/hhdev/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#26 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#27 /var/www/hhdev/index.php(25): yii\base\Application->run()
#28 {main}

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9-beta.1
| PHP version      | 8.0
| Operating system | Ubuntu 20.04

**Comment by ArchBlood** [comment]
I'm currently using the latest beta as well as PHP 8.0.7, not seen any problems as of yet, could you provide PHP extension as well as HumHub modules that you have enabled?

**Comment by funkycram** [comment]
PHP extension are exactly the same as the one I have with PHP 7.3 (for which the new spaces directory works).
In Informations -> Prerequisites everything is similar when I change PHP version, except of curse the PHP version (tested as well with 8.1.7).
The log does not mention any module, so it doesn't seems to be related to module incompatibility (No need to give you the list since most of them are not in the marketplace).
If nobody can reproduce, I will try to understand better what's happening.

**Comment by funkycram** [comment]
The explanation must be somewhere here: https://www.php.net/manual/fr/migration80.incompatible.php
Maybe because of:
```
The default error_reporting level is now E_ALL. Previously it excluded E_NOTICE and E_DEPRECATED.
display_startup_errors is now enabled by default.
```
But anyway, there is a type problem with the floor function's argument.

**Comment by luke-** [comment]
@yurabakhtin Can you please also take a look into this issue?

**Comment by yurabakhtin** [comment]
@luke- @funkycram I could not reproduce this bug with php config:

```
display_errors               = on
display_startup_errors       = on
error_reporting              = E_ALL
```

My PHP can display similar error only when call like `floor('1a')` or `floor(1,2)`, but if I call `floor('12')` or `floor('1.2')` it works well without errors.

In order to avoid such errors I decided to do a small fix in PR https://github.com/humhub/humhub/pull/5139.

**Comment by funkycram** [comment]
Thanks @yurabakhtin . This PR #5139 fixes the problem.
