### ISSUE TITLE
Profiles fields administration limited to 20 fields

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5143]
### What steps will reproduce the problem?

Create more than 20 profile fields in the same category.
The fields having the highest sort order AND after the 20 fields are not visible in `/admin/user-profile`

### Solution

Remove `'layout' => '{items}',` in https://github.com/humhub/humhub/blob/09b1dd060f55cdaab75d958ac2cba8102423f06c/protected/humhub/modules/admin/views/user-profile/_fieldGrid.php#L27

Removing this layout makes pagination appear. So we can access to page 2.

I do not know what `{items}` layout is for?

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8 and 1.9-beta-1

**Comment by luke-** [comment]
@funkycram I would prefer to remove the limit/pagination at all? What do you think?

**Comment by funkycram** [comment]
> @funkycram I would prefer to remove the limit/pagination at all? What do you think?

Yes, I agree, this is a better solution.

**Comment by yurabakhtin** [comment]
@luke- @funkycram Fixed in PR https://github.com/humhub/humhub/pull/5266.

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by funkycram** [comment]
Thanks @yurabakhtin !
