### ISSUE TITLE
Show sort order in profile fields settings

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5144]
In `/admin/user-profile`, add a column with `sort_order` to make it more easy to set a sort number to fields.
In can make a PR if you want.

**Comment by luke-** [comment]
@funkycram yes, that would be great!

**Comment by funkycram** [comment]
https://github.com/humhub/humhub/pull/5147

**Comment by luke-** [comment]
@funkycram Thanks! Can you check the CLA Bot problem?

**Comment by funkycram** [comment]
Done
