### ISSUE TITLE
If joining a space with the "Join" button, space's page does not refresh

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5149]
### What steps will reproduce the problem?

Go to a space of which you are not a member. E.g https://community.humhub.com/s/contribution-core-development/
Click on the "Join" button

### What is the expected result?

Space page refresh so that I can see :
- private contents
- the space's menu (e.g to cancel my membership)

### What do you get instead?

Only the "Join" button disappear.
But I need to refresh the page to see private contents or the space's menu.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9-beta-1

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- I confirm this behaviour, we changed the button to AJAX mode when worked on new layout for "People"/"Spaces" directories. Ok, I have reverted only the button "Join" and only on the space header to link/URL mode so currently page is refreshed on click. But I kept the AJAX mode for Spaces directory page.

PR https://github.com/humhub/humhub/pull/5150.

**Comment by funkycram** [comment]
Thanks @yurabakhtin for your quick fix!
