### ISSUE TITLE
HumHub produces open_basedir error in PHP 7.4.21 and 8.0.8

### ISSUE THREAD

**Issue by yanus** [humhub/humhub#5155]
### What steps will reproduce the problem?
Upgrade PHP to the latest version (7.4.21 or 8.0.8) on an existing installation of HumHub or install HumHub on a server with the latest version of PHP with the open_basedir value set in php.ini.

### What is the expected result?
HumHub should work normally.

### What do you get instead?
PHP error message: file_exists(): open_basedir restriction in effect
(see full stacktrace from a clean installation below)

### Additional info
Probably related to this https://bugs.php.net/bug.php?id=76359 which was fixed in the mentioned versions.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.2
| PHP version      | 7.4.21 / 8.0.8
| Operating system | Ubuntu 20.04.1 with Apache

### Stacktrace ###
`yii\base\ErrorException: file_exists(): open_basedir restriction in effect. File(/humhub/assets/f5196fba/jquery.js) is not within the allowed path(s): (/var/www/:/tmp/) in /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php:344
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php(344): file_exists()
#2 /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php(298): humhub\modules\ui\view\components\View->addCacheBustQuery()
#3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/AssetBundle.php(159): humhub\modules\ui\view\components\View->registerJsFile()
#4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/View.php(267): yii\web\AssetBundle->registerAssetFiles()
#5 /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php(211): yii\web\View->registerAssetFiles()
#6 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/View.php(265): humhub\modules\ui\view\components\View->registerAssetFiles()
#7 /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php(211): yii\web\View->registerAssetFiles()
#8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/View.php(265): humhub\modules\ui\view\components\View->registerAssetFiles()
#9 /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php(211): yii\web\View->registerAssetFiles()
#10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/View.php(265): humhub\modules\ui\view\components\View->registerAssetFiles()
#11 /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php(211): yii\web\View->registerAssetFiles()
#12 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/View.php(163): humhub\modules\ui\view\components\View->registerAssetFiles()
#13 /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php(436): yii\web\View->endBody()
#14 /var/www/html/humhub/protected/humhub/modules/installer/views/layouts/main.php(48): humhub\modules\ui\view\components\View->endBody()
#15 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/html/h...')
#16 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#17 /var/www/html/humhub/protected/humhub/components/Controller.php(136): yii\base\View->renderFile()
#18 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(411): humhub\components\Controller->renderContent()
#19 /var/www/html/humhub/protected/humhub/modules/installer/controllers/IndexController.php(35): yii\base\Controller->render()
#20 [internal function]: humhub\modules\installer\controllers\IndexController->actionIndex()
#21 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#22 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#23 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#24 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#25 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#26 /var/www/html/humhub/index.php(25): yii\base\Application->run()
#27 {main}`

**Comment by yo-hansolo** [comment]
Exactly the same problem for me.

<html>
<body>


Q | A
-- | --
HumHub version | 1.8.2
PHP version | 7.4.21
Operating system | Ubuntu 18.04.1 LTS with Apache 2.4.48


</body>
</html>

After updating yesterday, Humhub stopped working at all and throw base_dir error everywhere.
I've added in my base_dir the /assets/xxxxxx/ for jquery.js to test, but after that more base_dir error and it's impossible to log in.

More info : my server is on ISPConfig 3.2.4 with classic mail services
there is about 25 others php/html/mysql sites on this server. All of them work well (Wordpress for most of them).

CheerS/.

**Comment by paviro** [comment]
We sadly have the same problem. Our Webhoster updated PHP and now HumHub is down and no longer usable. Any workaround for this? Even on 7.3.29 this problem persists.

**Comment by ArchBlood** [comment]
Try looking at this to see if any of this fixes your issues 

https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

**Comment by paviro** [comment]
Setting basedir to none seems to have helped for now.

**Comment by yo-hansolo** [comment]
> Try looking at this to see if any of this fixes your issues
> 
> https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

My ISPconfig server installation seems refuses the use of the open base_dir snippet to none for security reasons. Even for a php.ini dedicated to a particular vhost... to sad. I will try to force by the command line interface... but lately, we're on sunday ^_^!

What i don't understand is me open base_dir is fixed to '/var/www/clientXX/webXX/web'
In web there are all reps and files for Humhub, like assets, protected, etc.

What's the point for HHub to not found a file in his own install ??
I red somewhere sometime a problem with '../' and './' to catch files. Maybe Humhub try to go down or up in reps instead of start straight to basedir ?

CheerS/.

**Comment by ArchBlood** [comment]
> > Try looking at this to see if any of this fixes your issues
> > https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths
> 
> My ISPconfig server installation seems refuses the use of the open base_dir snippet to none for security reasons. Even for a php.ini dedicated to a particular vhost... to sad. I will try to force by the command line interface... but lately, we're on sunday ^_^!
> 
> What i don't understand is me open base_dir is fixed to '/var/www/clientXX/webXX/web'
> In web there are all reps and files for Humhub, like assets, protected, etc.
> 
> What's the point for HHub to not found a file in his own install ??
> I red somewhere sometime a problem with '../' and './' to catch files. Maybe Humhub try to go down or up in reps instead of start straight to basedir ?
> 
> CheerS/.

Not sure exactly, I do know in Laravel you could set `setTemporaryFolder()` in the application as a work around, not sure how Yii handles this method myself but it's worth looking into, but doing some digging around in the Yii issues I found this one https://github.com/yiisoft/yii2/issues/7497 looking at this @luke- could a check be done for `open_basedir` or is this already implemented through Yii itself?

**Comment by yurabakhtin** [comment]
From the error message `yii\base\ErrorException: file_exists(): open_basedir restriction in effect. File(/humhub/assets/f5196fba/jquery.js) is not within the allowed path(s): (/var/www/:/tmp/) in /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php:344`
 I see the `open_basedir = /var/www/:/tmp/` for the server.

If I tried in my `php.ini` the config `open_basedir = /var/www/:/tmp/` I get the expected error `Warning: Unknown: open_basedir restriction in effect. File(/Users/my_user_name/www/humhub/humhub/index.php) is not within the allowed path(s): (/var/www/:/tmp/) in Unknown on line 0`.
But if I set `open_basedir = /Users/my_user_name/www/humhub/humhub/` it works well, I can install and use HumHub without any errors, so I cannot catch a problem with '../' and './'.

**Comment by yo-hansolo** [comment]
> From the error message `yii\base\ErrorException: file_exists(): open_basedir restriction in effect. File(/humhub/assets/f5196fba/jquery.js) is not within the allowed path(s): (/var/www/:/tmp/) in /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php:344`
> I see the `open_basedir = /var/www/:/tmp/` for the server.
> 
> If I tried in my `php.ini` the config `open_basedir = /var/www/:/tmp/` I get the expected error `Warning: Unknown: open_basedir restriction in effect. File(/Users/my_user_name/www/humhub/humhub/index.php) is not within the allowed path(s): (/var/www/:/tmp/) in Unknown on line 0`.
> But if I set `open_basedir = /Users/my_user_name/www/humhub/humhub/` it works well, I can install and use HumHub without any errors, so I cannot catch a problem with '../' and './'.

Hi there !
ok let's say i've `open basedir = /var/www/clients/client1/web/web:/var/www/clients/client1/web/private:/var/www/clients/client1/web/tmp:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin`

my humhub is install directly in `/var/www/clients/client1/web/web`. So jquery.js assets is in `/var/www/clients/client1/web/web/assets/abcdefgh/jquery.js`

with this Humhub show me in debug mode `file_exists(): open_basedir restriction in effect. File(/assets/3baa0e36/jquery.js) is not within the allowed path(s):`

what kind of changes do i need to make to my open basedir to avoid error ? add /humhub/humhub/ to my openbase dir ??
CheerS/.

**Comment by yo-hansolo** [comment]
Like i said before, when i try to add the directory of jquery.js. Humhub main page shows again, but impossible to log in.
new open basedir error for the static loader.js

```
{
    "url": "/index.php?r=user%2Fauth%2Flogin",
    "status": 500,
    "response": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;file_exists(): open_basedir restriction in effect. File(/static/js/humhub/legacy/jquery.loader.js) is not within the allowed path(s): (/var/www/clients/client1/web54/web:/var/www/clients/client1/web54/private:/var/www/clients/client1/web54/tmp:/var/www/inspirees.quellebonneidee.fr/web:/srv/www/inspirees.quellebonneidee.fr/web:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urand...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;file_exists(): open_basedir restriction in effect. File(/static/js/humhub/legacy/jquery.loader.js) is not within the allowed path(s): (/var/www/clients/client1/web54/web:/var/www/clients/client1/web54/private:/var/www/clients/client1/web54/tmp:/var/www/inspirees.quellebonneidee.fr/web:/srv/www/inspirees.quellebonneidee.fr/web:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urandom:/var/www/clients/client1/web54/web/assets/3baa0e36)&#039; \n\nin /var/www/clients/client1/web54/web/protected/humhub/modules/ui/view/components/View.php:344\n\nStack trace:\n#0 [internal function]: yii\\base\\ErrorHandler-&gt;handleError()\n#1 /var/www/clients/client1/web54/web/protected/humhub/modules/ui/view/components/View.php(344): file_exists()\n#2 /var/www/clients/client1/web54/web/protected/humhub/modules/ui/view/components/View.php(298): humhub\\modules\\ui\\view\\components\\View-&gt;addCacheBustQuery()\n#3 /var/www/clients/client1/web54/web/protected/vendor/yiisoft/yii2/web/AssetBundle.php(159): humhub\\modules\\ui\\view\\components\\View-&gt;registerJsFile()\n#4 /var/www/clients/client1/web54/web/protected/vendor/yiisoft/yii2/web/View.php(267): yii\\web\\AssetBundle-&gt;registerAssetFiles()\n#5 /var/www/clients/client1/web54/web/protected/humhub/modules/ui/view/components/View.php(211): yii\\web\\View-&gt;registerAssetFiles()\n#6 /var/www/clients/client1/web54/web/protected/vendor/yiisoft/yii2/web/View.php(265): humhub\\modules\\ui\\view\\components\\View-&gt;registerAssetFiles()\n#7 /var/www/clients/client1/web54/web/protected/humhub/modules/ui/view/components/View.php(211): yii\\web\\View-&gt;registerAssetFiles()\n#8 /var/www/clients/client1/web54/web/protected/vendor/yiisoft/yii2/web/View.php(163): humhub\\modules\\ui\\view\\components\\View-&gt;registerAssetFiles()\n#9 /var/www/clients/client1/web54/web/protected/humhub/modules/ui/view/components/View.php(423): yii\\web\\View-&gt;endBody()\n#10 /var/www/clients/client1/web54/web/protected/humhub/modules/ui/view/components/View.php(181): humhub\\modules\\ui\\view\\components\\View-&gt;endBody()\n#11 /var/www/clients/client1/web54/web/protected/vendor/yiisoft/yii2/web/Controller.php(53): humhub\\modules\\ui\\view\\components\\View-&gt;renderAjax()\n#12 /var/www/clients/client1/web54/web/protected/humhub/modules/user/controllers/AuthController.php(118): yii\\web\\Controller-&gt;renderAjax()\n#13 [internal function]: humhub\\modules\\user\\controllers\\AuthController-&gt;actionLogin()\n#14 /var/www/clients/client1/web54/web/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()\n#15 /var/www/clients/client1/web54/web/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction-&gt;runWithParams()\n#16 /var/www/clients/client1/web54/web/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\base\\Controller-&gt;runAction()\n#17 /var/www/clients/client1/web54/web/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\base\\Module-&gt;runAction()\n#18 /var/www/clients/client1/web54/web/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Application-&gt;handleRequest()\n#19 /var/www/clients/client1/web54/web/index.php(25): yii\\base\\Application-&gt;run()\n#20 {main}</pre>",
        "status": 500,
        "statusText": "error"
    },
    "dataType": "html",
    "html": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;file_exists(): open_basedir restriction in effect. File(/static/js/humhub/legacy/jquery.loader.js) is not within the allowed path(s): (/var/www/clients/client1/web54/web:/var/www/clients/client1/web54/private:/var/www/clients/client1/web54/tmp:/var/www/inspirees.quellebonneidee.fr/web:/srv/www/inspirees.quellebonneidee.fr/web:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urand...",
    "error": {},
    "errorThrown": "",
    "validationError": false
}
```

**Comment by yanus** [comment]
> From the error message `yii\base\ErrorException: file_exists(): open_basedir restriction in effect. File(/humhub/assets/f5196fba/jquery.js) is not within the allowed path(s): (/var/www/:/tmp/) in /var/www/html/humhub/protected/humhub/modules/ui/view/components/View.php:344`
> I see the `open_basedir = /var/www/:/tmp/` for the server.
> 
> If I tried in my `php.ini` the config `open_basedir = /var/www/:/tmp/` I get the expected error `Warning: Unknown: open_basedir restriction in effect. File(/Users/my_user_name/www/humhub/humhub/index.php) is not within the allowed path(s): (/var/www/:/tmp/) in Unknown on line 0`.
> But if I set `open_basedir = /Users/my_user_name/www/humhub/humhub/` it works well, I can install and use HumHub without any errors, so I cannot catch a problem with '../' and './'.

Hi Yuriy, thanks for looking into this. The error you are getting makes total sense, since the open_basedir is set to the wrong directory. It should be set to wherever the web server's public files are located (`/var/www/` in my test installation, `/Users/my_user_name/www/` in your case, `/var/www/vhosts/domain.org/` on my Plesk powered production system).
In the described situation, however, HumHub seems to be looking for files relative to the system root (e.g. `/assets/...`) instead of inside its installation path, which obviously it shouldn't do.

**Comment by yurabakhtin** [comment]
@luke- As I got the problem exists only in the function https://github.com/humhub/humhub/blob/master/protected/humhub/modules/ui/view/components/View.php#L338:

```php
    protected function addCacheBustQuery($url)
    {
        if (strpos($url, '?') === false) {
            $file = str_replace('@web', '@webroot', $url);
            $file = Yii::getAlias($file);

            if (file_exists($file)) {
                $url .= '?v=' . filemtime($file);
            } else {
                $url .= '?v=' . urlencode(Yii::$app->version);
            }
        }

        return $url;
    }
```

because here `$url` is passed with value `/assets/f4c986b0/jquery.js` instead of expecting `@web/assets/f4c986b0/jquery.js`.
However on my local server if I have php config `open_basedir = /Users/my_user_name/www/humhub/humhub/` I cannot get the error even on call `file_exists('/assets/f4c986b0/jquery.js')`, it just returns `false`, but I can get the error if I call `file_exists('/var/some_test_file_name')`. I guess the function generates the error if a folder `/assets/` exists on server root, and yes we should find a solution indeed.

I can suggest 2 solutions:

1) before line `$file = Yii::getAlias($file);` add the following code:

```php
if (substr($file, 0, 1) === '/') {
    $file = '@webroot' . $file;
}
```

i.e. if the passed param `$url` is started with `/` we consider this file path is relative to root of the site, so the result of the `Yii::getAlias($file)` will be as `/Users/yurabakh/www/humhub/humhub/assets/f4c986b0/jquery.js` and then `file_exists($file)` will not generate the error `open_basedir restriction ...`.
But this solution creates a side effect:

- currently all urls look like this `http://humhub.yb/assets/f4c986b0/jquery.js?v=1.8.3` (here we have app version)
- but after the url will be like `http://humhub.yb/assets/f4c986b0/jquery.js?v=1626078430` (file time)

Do you agree this change in file urls?

2) We should change the condition `if (file_exists($file)) {` to:

```php
if (strpos($file, Yii::getAlias('@webroot')) === 0 && file_exists($file)) {
```

in such case the `file_exists()` will be called only for files under the site root folder, and the url param `v` keep app version as now.

---

I think 1st solution is more right because url is started with `/` looks wrong, but I am not sure how it may be slower to get time of each file because it is access to disk, so if we need more performance it is better to use app version by applying 2nd solution.

Please let me know what solution your prefer because I see the code was created by you https://github.com/humhub/humhub/commit/974a57543a8403385eda96f1e6f4cb6c38129b14#diff-02e1de6533dd0013fe89ed98aaae3da036eb8cfa3a9ecba0d61dbb240c89dd77R96-R110 and probably you remember what better result this function should returns.

**Comment by yo-hansolo** [comment]
Tested the two way. Works well ;)
Didn't see any difference in tems of performance betwenn the two. Our server is a RAID array of SSD by the way.

I prefer the second solution to be clearer than the first one when you read the code.
It's only subjective
CheerS/.

**Comment by ArchBlood** [comment]
As for the external URL issue, I personally use the following and removed the possibility for this file to be updated by the updater module
```php
    /**
     * Adds cache bust query string to given URL if no query is present
     *
     * @param string $url
     * @return string the URL with cache bust paramter
     */
    protected function addCacheBustQuery($url)
    {
        if (strpos($url, '?') === false) {
            $file = str_replace('@web', '@webroot', $url);
            $file = Yii::getAlias($file);

            if (file_exists($file)) {
                $url .= '?v=' . filemtime($file);
            } else if (file_exists($file)) {
                $url;
            }
        }

        return $url;
    }
```
File time tags are only applied to `$file` if they're internal asset files which then show the file time, forcing external URLs to also be cached is also somewhat of a performance drainer so it's not really needed, and to be honest, could be removed completely by just removing it completely as I have done here.

**Comment by luke-** [comment]
@yurabakhtin @ArchBlood What do you think of the following solution?

```php
    protected function addCacheBustQuery($url)
    {
        if (strpos($url, '?') === false) {
            $file = str_replace('@web', '@webroot', $url);
            $file = Yii::getAlias($file);

            // The @ suppresses openBaseDir Fatal Errors
            if (@file_exists($file)) {
                $url .= '?v=' . filemtime($file);
            } else {
                $url .= '?v=' . urlencode(Yii::$app->version);
            }
        }

        return $url;
    }
``` 

I would not recommend to always put a @webroot in front of it, because @uploads, @webroot-static or in the future also an assets CDN could be possible.

Do you agree with the @ error surpress solution?

**Comment by yurabakhtin** [comment]
@luke- I thought about the error suppress by `@` too, but as I know it is not recommended solution because we can skip important error, so it would be better to avoid using `@` in code at all, but if you think we can use this here we can try it.

As I know CDN url is started with double slash like `//site.com/page/file.js`, and we can apply my 1st solution only for url started with single slash `/`, but if we don't like 1st solution then we can use 2nd solution where the checking `file_exists()` is applied only for files located inside in the site root, and in such case we will escape the error of `open_basedir` restriction.

**Comment by ArchBlood** [comment]
> @yurabakhtin @ArchBlood What do you think of the following solution?
> 
> ```php
>     protected function addCacheBustQuery($url)
>     {
>         if (strpos($url, '?') === false) {
>             $file = str_replace('@web', '@webroot', $url);
>             $file = Yii::getAlias($file);
> 
>             // The @ suppresses openBaseDir Fatal Errors
>             if (@file_exists($file)) {
>                 $url .= '?v=' . filemtime($file);
>             } else {
>                 $url .= '?v=' . urlencode(Yii::$app->version);
>             }
>         }
> 
>         return $url;
>     }
> ``` 
> 
> I would not recommend to always put a @webroot in front of it, because @uploads, @webroot-static or in the future also an assets CDN could be possible.
> 
> Do you agree with the @ error surpress solution?

I like the approach, although if the version tag is still applied then sites like Google will ignore it and adsense will not check correctly

**Comment by ArchBlood** [comment]
> Do you agree with the @ error suppress solution?

I'd also like to take the time to post about this as well, as I'm not sure that `@` would be the right solution with PHP 8.0.x
```txt
Warning
Prior to PHP 8.0.0, the value of the severity passed to the custom error handler was always 0 if the diagnostic was suppressed.
This is no longer the case as of PHP 8.0.0.
```
Of course, this Is only the case for PHP 8, the solution provided by @yurabakhtin (i.e. solution 2) by far is a better one in this case
But of course, also doesn't do much for my case with version tags being placed in external links, but that's a completely different topic which I will abstain from mentioning more of here.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/pull/5163
