### ISSUE TITLE
Updater/Modules don't show updates even if they are available / SSL certificate has expired

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#5165]
### What steps will reproduce the problem?
Check for updates with the updater plugin / check the Modules Marketplace

### What is the expected result?
Either available updates OR an error message should be shown.

### What do you get instead?
Updater: "There is no new HumHub update available!" (Wrong claim in my instance!)
Modules: "Available updates  0"
Modules/Browse Online: "No modules found!" (There should be some.)

### Additional info
Log shows errors: `"Could not parse HumHub API response! Curl error: #60 - SSL certificate problem: certificate has expired"`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.2 and 1.9.0-beta.1
| PHP version      | 7.2.24
| Operating system | CentOS 8

**Comment by luke-** [comment]
Thanks. Is updated.

**Comment by dreua** [comment]
Thanks for the fast response! However, for me this issue has two sides:
1) Certificate issue (fixed)
2) UX issue: Displaying "no updates" in cases where there actually was an error retrieving update information. (Still open.) This happendes also in cases where the server has no outgoing internet connection or DNS resolving issues.

**Comment by luke-** [comment]
@dreua Yes, you are right about that. I have opened an issue for this. We are planning some improvements in the Marketplace with v1.10 anyway.
