### ISSUE TITLE
Enable more than 50 groups to a user

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5169]
### Is your feature request related to a problem? Please describe.

When you edit a user (in the admin), you cannot set more than 50 groups

### Describe the solution you'd like

Allow up to 250 groups

If you agree, I can make a PR for that.

**Comment by luke-** [comment]
Oh, that's a lot of groups of course, but you need that you are welcome to do a PR on this here. I don't see any reason for the limitation otherwise.

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/5171

**Comment by luke-** [comment]
@funkycram Thanks!
