### ISSUE TITLE
Humhub 1.9-beta - Dashboard module should not use old Directory module widgets

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5172]
https://github.com/humhub/humhub/blob/63e726c9ff0b50675856376b9d8340a6f3e5a18c/protected/humhub/modules/dashboard/views/dashboard/index_guest.php#L6 uses old Directory module widgets

They still work, but as the module is now disabled in Humhub 1.9, the button to see all members show an unauthorized page: /directory/members

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9-beta2

**Comment by luke-** [comment]
@yurabakhtin Probably it would be best to use a copy of the widget in the 'user` Module?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5177

**Comment by funkycram** [comment]
@yurabakhtin the translations have not been transferred from directory module to user and space module.
E.g '<strong>New</strong> people'
So text is displayed in English now.
Thanks.

**Comment by yurabakhtin** [comment]
@luke- Here https://github.com/humhub/humhub/pull/5177/files#diff-599b113cff643b85934237d3a18cbcfb9544bbc7f6cbdf5db511f64ed6af2246R17I changed the message category, but how we can quickly for move the translations from old module to new? Do you know some tool or should it be done manually?

**Comment by luke-** [comment]
@funkycram @yurabakhtin I commited the updated  translations here:
https://github.com/humhub/humhub/commit/60792edc2b2b89f6eab8492415b36a4a3002412a
