### ISSUE TITLE
Bug when closing the action confirmation dialog directly

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#5173]
When the action confirmation dialog is closed directly, the button's display content will be in processing.

![2021-07-17_16h24_51](https://user-images.githubusercontent.com/38252517/126030149-22ce037d-9c50-41e7-a921-7c26ed84d4e6.gif)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.0-beta.2

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5176

**Comment by luke-** [comment]
@yurabakhtin Thanks!
