### ISSUE TITLE
Humhub 1.9-beta - Tour module crashes

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5174]
### What steps will reproduce the problem?

Enable Tour module (in /admin/setting/basic)
Create a new account on Humhub 1.9-beta2

As `tags` property has been removed from [User model](https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/user/models/User.php), the form field in https://github.com/humhub/humhub/blob/63e726c9ff0b50675856376b9d8340a6f3e5a18c/protected/humhub/modules/tour/views/tour/welcome.php#L90 crashes

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9-beta2

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5175

**Comment by funkycram** [comment]
Great, thanks @yurabakhtin !

**Comment by luke-** [comment]
@yurabakhtin Thanks, is merged into develop!
