### ISSUE TITLE
PHP Warning – yii\base\ErrorException

### ISSUE THREAD

**Issue by sasch901** [humhub/humhub#5183]
### What steps will reproduce the problem?
we have done nothing, this bug is from now to another day. 

### What is the expected result?
try to login

### What do you get instead?
https://app.hallo.network/

### Additional info
to fix this, i try to delete the "assets" folder. Doesn't fix anything.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | tried with 7.4.21 and 8.0
| Operating system | Webhosting Linux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
not possible to launch the admin console

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by josaur** [comment]
Same Problem here. It seems that Netcup (the hoster of the instance described in the issue) has changed something at the Systems. Right now I`m in contact with the support tho figure out what they changed for the webhosting.

**Comment by ArchBlood** [comment]
What version of HumHub are you using, and check your /protected/runtime/log/app.log file for error

**Comment by luke-** [comment]
This bug should be fixed in 1.8.3+ https://github.com/humhub/humhub/blob/master/CHANGELOG.md#183-july-14-2021

**Comment by sasch901** [comment]
> What version of HumHub are you using, and check your /protected/runtime/log/app.log file for error

thank you for the fast help. How can i check my Version. The Problem is, its not possible to login. I tried also searching in some files to check the version number

`2021-07-21 15:58:19 [2001:16b8:a08a:f100:cab2:9bff:fefc:258d][-][f0025b4dc7d58b3e736fe29386cadacd][error][yii\base\ErrorException:2] yii\base\ErrorException: file_exists(): open_basedir restriction in effect. File(/assets/3cd54a93/jquery.js) is not within the allowed path(s): (/var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/:/tmp/:/var/lib/php/sessions:/var/www/vhosts/hosting106713.a2f1e.netcup.net/tmp) in /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/modules/ui/view/components/View.php:344
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'file_exists(): ...', '/var/www/vhosts...', 344, Array)
#1 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/modules/ui/view/components/View.php(344): file_exists('/assets/3cd54a9...')
#2 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/modules/ui/view/components/View.php(298): humhub\modules\ui\view\components\View->addCacheBustQuery('/assets/3cd54a9...')
#3 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/web/AssetBundle.php(159): humhub\modules\ui\view\components\View->registerJsFile('/assets/3cd54a9...', Array)
#4 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/web/View.php(267): yii\web\AssetBundle->registerAssetFiles(Object(humhub\modules\ui\view\components\View))
#5 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/modules/ui/view/components/View.php(211): yii\web\View->registerAssetFiles('yii\\web\\JqueryA...')
#6 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/web/View.php(265): humhub\modules\ui\view\components\View->registerAssetFiles('yii\\web\\JqueryA...')
#7 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/modules/ui/view/components/View.php(211): yii\web\View->registerAssetFiles('humhub\\assets\\A...')
#8 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/web/View.php(265): humhub\modules\ui\view\components\View->registerAssetFiles('humhub\\assets\\A...')
#9 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/modules/ui/view/components/View.php(211): yii\web\View->registerAssetFiles('humhub\\assets\\C...')
#10 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/web/View.php(265): humhub\modules\ui\view\components\View->registerAssetFiles('humhub\\assets\\C...')
#11 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/modules/ui/view/components/View.php(211): yii\web\View->registerAssetFiles('/themes/HumHub/...')
#12 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/web/View.php(163): humhub\modules\ui\view\components\View->registerAssetFiles('/themes/HumHub/...')
#13 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/modules/ui/view/components/View.php(436): yii\web\View->endBody()
#14 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/modules/user/views/layouts/main.php(28): humhub\modules\ui\view\components\View->endBody()
#15 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/vhosts...')
#16 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/vhosts...', Array)
#17 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/components/Controller.php(136): yii\base\View->renderFile('/var/www/vhosts...', Array, Object(humhub\modules\user\controllers\AuthController))
#18 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/base/Controller.php(411): humhub\components\Controller->renderContent('\n<div class="co...')
#19 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/humhub/modules/user/controllers/AuthController.php(121): yii\base\Controller->render('login', Array)
#20 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin()
#21 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#23 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('login', Array)
#24 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('user/auth/login', Array)
#25 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#26 /var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/index.php(25): yii\base\Application->run()
#27 {main}
2021-07-21 15:58:19 [2001:16b8:a08a:f100:cab2:9bff:fefc:258d][-][f0025b4dc7d58b3e736fe29386cadacd][info][application] $_GET = [
    'r' => 'user/auth/login'
]

$_SERVER = [
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'PP_CUSTOM_PHP_INI' => '/var/www/vhosts/system/app.hallo.network/etc/php.ini'
    'PP_CUSTOM_PHP_CGI_INDEX' => 'php74-fastcgi-nc'
    'SCRIPT_NAME' => '/index.php'
    'REQUEST_URI' => '/index.php?r=user%2Fauth%2Flogin'
    'QUERY_STRING' => 'r=user%2Fauth%2Flogin'
    'REQUEST_METHOD' => 'GET'
    'SERVER_PROTOCOL' => 'HTTP/1.0'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'REMOTE_PORT' => '41458'
    'SCRIPT_FILENAME' => '/var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network/index.php'
    'SERVER_ADMIN' => '[no address given]'
    'CONTEXT_DOCUMENT_ROOT' => '/var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network'
    'CONTEXT_PREFIX' => ''
    'REQUEST_SCHEME' => 'https'
    'DOCUMENT_ROOT' => '/var/www/vhosts/hosting106713.a2f1e.netcup.net/app.hallo.network'
    'REMOTE_ADDR' => '2001:16b8:a08a:f100:cab2:9bff:fefc:258d'
    'SERVER_PORT' => '443'
    'SERVER_ADDR' => '2a03:4000:30:19ea::10:6713'
    'SERVER_NAME' => 'app.hallo.network'
    'SERVER_SOFTWARE' => 'Apache'
    'SERVER_SIGNATURE' => '<address>Apache Server at app.hallo.network Port 443</address>
'
    'HTTP_COOKIE' => 'PHPSESSID=f0025b4dc7d58b3e736fe29386cadacd'
    'HTTP_ACCEPT_LANGUAGE' => 'de,en-US;q=0.9,en;q=0.8'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_REFERER' => 'https://github.com/humhub/humhub/issues/5183'
    'HTTP_SEC_CH_UA_MOBILE' => '?0'
    'HTTP_SEC_CH_UA' => '\"Chromium\";v=\"91\", \" Not;A Brand\";v=\"99\"'
    'HTTP_SEC_FETCH_DEST' => 'document'
    'HTTP_SEC_FETCH_USER' => '?1'
    'HTTP_SEC_FETCH_MODE' => 'navigate'
    'HTTP_SEC_FETCH_SITE' => 'cross-site'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36'
    'HTTP_DNT' => '1'
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
    'HTTP_CONNECTION' => 'close'
    'HTTP_X_ACCEL_INTERNAL' => '/internal-nginx-static-location'
    'HTTP_X_REAL_IP' => '2001:16b8:a08a:f100:cab2:9bff:fefc:258d'
    'HTTP_HOST' => 'app.hallo.network'
    'HTTPS' => 'on'
    'PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY' => '0'
    'PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY' => '0'
    'FCGI_ROLE' => 'RESPONDER'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1626875899.1628
    'REQUEST_TIME' => 1626875899
]
`

**Comment by luke-** [comment]
@sasch901 You can find you version in the file: /protcetd/humhub/config/common.php

**Comment by sasch901** [comment]
@luke-  'version' => '1.8.1'

**Comment by ArchBlood** [comment]
If it's related to the `open_basedir` issue then this has already been fixed in newer versions of the platform, I'd suggest manually updating then running the migrations.

**Comment by luke-** [comment]
@sasch901 ok the bug is closed with HumHub 1.8.3
