### ISSUE TITLE
Display the month and day of birthday in a language-specific format.

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#5187]
When the "Hide year in profile" option is checked in the profile settings, the birthday will always be displayed in the format `'dd. MMMM'`.

**example**
_Birthday is July 22, 2000 (21 years old), and the language setting for users browsing is Japanese._
![2021-07-22_22h47_18](https://user-images.githubusercontent.com/38252517/126661773-4a72d14e-d15f-4834-8f03-44b49f81f0c6.png)

The display format differs depending on whether "Hide year in profile" is off or on. The display format when it is on is very unnatural in Japanese.

https://github.com/humhub/humhub/blob/b7ddfd57e28a4a65c517d349329f624eefec73fe/protected/humhub/modules/user/models/fieldtype/Birthday.php#L202-L207

Is it possible to define `'dd. MMMM'` in the translation file and use Y::t() or something similar to achieve a language-appropriate indication of the month and day?

**Comment by luke-** [comment]
@yurabakhtin Any idea how we can handle this case?

**Comment by ArchBlood** [comment]
> @yurabakhtin Any idea how we can handle this case?

When dealing with this I believe going by yii2 standards would be best in this case
https://www.yiiframework.com/wiki/183/using-international-dates

**Comment by ArchBlood** [comment]
> @ArchBlood I don't think there is a predefined localized date format without year information. But maybe? 

What about something like this? A little bit of a hack but should do, only thing is, we'd have to make sure that it checks current location in this case :thinking:
https://stackoverflow.com/questions/10087390/php-converting-date-without-a-year/10087407#:~:text=2%20Answers&text=You%20can't%20get%20the,any%20old%20year%20in%20there.

**Comment by luke-** [comment]
@ArchBlood I think it's about something else. We need a localized day/month string.  For example, in Germany we use "dd.mm" and in the USA probably "mm-dd".

**Comment by ArchBlood** [comment]
> @ArchBlood I think it's about something else. We need a localized day/month string. For example, in Germany we use "dd.mm" and in the USA probably "mm-dd".

Yes, that is correct, in most parts of the USA `mm, dd, yyyy` is used but as suggested in that post just use something like the following?

```php
if ($timeZone1) {
Yii::$app->formatter->locale = 'en-US';
echo Yii::$app->formatter->asDate(strtotime('2014-01-01')); // output: January 1
} if ($timeZone2) {
Yii::$app->formatter->locale = 'de-DE';
echo Yii::$app->formatter->asDate(strtotime('2014-01-01')); // output: 1. Januar
} if ($timeZone3) {
Yii::$app->formatter->locale = 'ru-RU';
echo Yii::$app->formatter->asDate(strtotime('2014-01-01')); // output: 1 января г.
}
```

Not sure if `strtotime()` would work here though without testing 🤔

> https://www.yiiframework.com/doc/guide/2.0/en/output-formatting#localizing-data-format

**Comment by luke-** [comment]
@ArchBlood  For me, the year is always displayed. See my outputs:

```php
Yii::$app->formatter->locale = 'en-US';
echo Yii::$app->formatter->asDate(strtotime('2014-01-03')); // output: Jan 2, 2014

Yii::$app->formatter->locale = 'de-DE';
echo Yii::$app->formatter->asDate(strtotime('2014-01-03')); // output: 02.01.2014

Yii::$app->formatter->locale = 'ru-RU';
echo Yii::$app->formatter->asDate(strtotime('2014-01-03')); // output: 2 янв. 2014 г.

```

**Comment by ArchBlood** [comment]
> @ArchBlood For me, the year is always displayed. See my outputs:
> 
> ```
> Yii::$app->formatter->locale = 'en-US';
> echo Yii::$app->formatter->asDate(strtotime('2014-01-03')); // output: Jan 2, 2014
> 
> Yii::$app->formatter->locale = 'de-DE';
> echo Yii::$app->formatter->asDate(strtotime('2014-01-03')); // output: 02.01.2014
> 
> Yii::$app->formatter->locale = 'ru-RU';
> echo Yii::$app->formatter->asDate(strtotime('2014-01-03')); // output: 2 янв. 2014 г.
> ```

Maybe it's because `'jS F', ` isn't being used here? So in turn using this should return the month and day?
```php
Yii::$app->formatter->locale = 'en-US';
echo Yii::$app->formatter->asDate(strtotime('jS F', '2014-01-03')); // output: Jan 2

Yii::$app->formatter->locale = 'de-DE';
echo Yii::$app->formatter->asDate(strtotime('jS F', '2014-01-03')); // output: 02.01

Yii::$app->formatter->locale = 'ru-RU';
echo Yii::$app->formatter->asDate(strtotime('jS F', '2014-01-03')); // output: 2 янв. г.
```

**Comment by yurabakhtin** [comment]
@luke- Yes we can display the date in correct format for all locales only if we will specify them manually in some config file per each locale, but I tried to implement this by code in PR https://github.com/humhub/humhub/pull/5205, yes it cannot be ideal for all languages, so please review how it looks:

![birthday](https://user-images.githubusercontent.com/6995524/127303431-06a8ffbb-f394-4f95-a93a-0b13e38e8956.jpg)

**Comment by luke-** [comment]
@yurabakhtin Thanks, looks like a good solution.

@ArchBlood @sakurafarm Is the Japanese format ok?

**Comment by ArchBlood** [comment]
> @yurabakhtin Thanks, looks like a good solution.
> 
> @ArchBlood @sakurafarm Is the Japanese format ok? 

Looks okay to me

**Comment by luke-** [comment]
Thanks. Lets try this solution!

**Comment by sakurafarm** [comment]
@luke- I have confirmed that there is no problem with the display format in Japanese. Thank you very much for the fix.
