### ISSUE TITLE
Minimum character limit for tags

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#5189]
HumHub 1.9.0-beta.1 and later introduces a new tag picker for spaces and profiles, but it is not backward compatible with the minimum number of characters entered.

HumHub 1.8 and earlier allows one character tags, while HumHub 1.9.0-beta.1 and later requires at least three characters.

My native language is Japanese, but for example, if I translate the English word 'DEVELOP' into Japanese (kanji), it is two characters.

I hope that the minimum number of characters in a tag will be changed to two, or that it will be configurable in common.php.

| Q                | A
| ---------------- | ---
| HumHub version   | HumHub 1.9.0-beta.1 or later
| PHP version      | 
| Operating system |

**Comment by luke-** [comment]
From my side, we can reduce the limit.

@yurabakhtin Is there anything on your end that speaks against this? Maybe the tag search?

**Comment by yurabakhtin** [comment]
@luke- I don't find any against, the search works even with 1 char.
We can reduce the limit here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/modules/manage/views/default/index.php#L33 by adding widget param `['minInput' => 2]`.

---

But I think the search by tag is broken on client/JS side:

![search_by_tag_bug](https://user-images.githubusercontent.com/6995524/127312989-2b64f727-8434-4130-8685-4ad64017c599.jpg)

Should I create a separate issue for this bug?

**Comment by luke-** [comment]
@yurabakhtin Ok great. Then let's reduce the limit to 2. Tags with only one character I would not support for now.
Can you also fix the error with the search? An extra issue does not necessarily have to be.

Thank you!

**Comment by yurabakhtin** [comment]
@luke- 

> Then let's reduce the limit to 2.

PR https://github.com/humhub/humhub/pull/5207

> Can you also fix the error with the search? An extra issue does not necessarily have to be.

Ok, I have fixed this in the same PR in commit https://github.com/humhub/humhub/pull/5207/commits/6b484138a2a6740132405584af2947698d215252:

![search_by_tags](https://user-images.githubusercontent.com/6995524/127331908-fc679803-1879-4e04-8657-6e64cfe65ff0.jpg)

As I got the code we should keep the tags in the html element in order to highlight the searched keyword, otherwise if the keyword is not found the line is not displayed, so I added the new line `Tags: ...` under space description.
I guess the searching by tags was implemented in recent version but tags were not added to be displayed in the space chooser list.

**Comment by luke-** [comment]
@yurabakhtin Unfortunately, I have already merged the PR/Branch. 
But can we somehow show the tags here only if there is also a hit? 

Always show the tags in the chooser is unfortunately not so nice

**Comment by yurabakhtin** [comment]
@luke- Ok, PR https://github.com/humhub/humhub/pull/5212 - I have done to display space tags only if the requested keyword is found there, otherwise the tags are hidden on the space chooser.

![space_chooser_tags](https://user-images.githubusercontent.com/6995524/127491368-f74ab57f-6a63-4297-8230-3f2c8f37fe59.jpg)

**Comment by luke-** [comment]
@yurabakhtin Awesome thanks!

**Comment by sakurafarm** [comment]
@luke @yurabakhtin 
It seems that my initial explanation was inadequate.
I've applied this fix and confirmed that the tags on the profile page and space settings still need to be at least 3 characters to be registered.

![2021-08-02_14h50_35](https://user-images.githubusercontent.com/38252517/127811131-16a9e9e1-d896-4284-adcf-f2b08c28a380.png)
![2021-08-02_14h53_09](https://user-images.githubusercontent.com/38252517/127811134-d524bdc3-9c65-4a80-943f-179b96686e97.png)

Is the minimum character limit for profile and space tags due to the following definition?

https://github.com/humhub/humhub/blob/56033c592c48e11c8553aeca8a99f047701fbed1/protected/humhub/modules/ui/form/widgets/BasePicker.php#L76-L82

Would it be possible to change this definition to 2 or some other way to add a two-character tag?

**Comment by yurabakhtin** [comment]
@sakurafarm We changed this to 2 chars only for space in the first PR here https://github.com/humhub/humhub/pull/5207/files#diff-848966e98b4adcb8cabe5fd615ec83c30b2ae7a47593140b7d9f05b6b863e02fR33:

![space_tags](https://user-images.githubusercontent.com/6995524/127814903-394655c3-5af1-4183-9c49-d3aea14578c8.jpeg)

@luke- Should we apply the same for user tags?

![user_tags](https://user-images.githubusercontent.com/6995524/127815005-21dff22d-0493-4299-8e3f-39baf231a8f4.jpeg)

**Comment by sakurafarm** [comment]
> @sakurafarm We changed this to 2 chars only for space in the first PR here https://github.com/humhub/humhub/pull/5207/files#diff-848966e98b4adcb8cabe5fd615ec83c30b2ae7a47593140b7d9f05b6b863e02fR33:
> 
> ![space_tags](https://user-images.githubusercontent.com/6995524/127814903-394655c3-5af1-4183-9c49-d3aea14578c8.jpeg)
> 
> @luke- Should we apply the same for user tags?
> 
> ![user_tags](https://user-images.githubusercontent.com/6995524/127815005-21dff22d-0493-4299-8e3f-39baf231a8f4.jpeg)

I think that the minimum character limit for profile tags should be the same as for spaces.

I don't understand why there is a distinction between the minimum number of characters in tags for profile and space.

There are several languages that use kanji, not just Japanese, and there are many words that are two characters long when expressed in kanji.

In Humhub v1.8, profile and space tags can be registered with a single character. A Humhub instance that is already up and running may already have profile and space tags with less than three characters.

If these instances are upgraded to Humhub v1.9, won't the users be in trouble? Because they are not backward compatible!

I think this is a serious specification change regarding tag registration requirements. However, I don't think this point was mentioned in the Humhub v1.9 release notes.

If there is such an unpublicized spec change, Humhub instance administrators will have a hard time explaining and responding to registered users.

**Comment by luke-** [comment]
@yurabakhtin Can you please also reduce the limit for user profiles?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5228.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
