### ISSUE TITLE
Upgrade to 1.9 - Migration failed because of existing table cfiles_file

### ISSUE THREAD

**Issue by superseby2** [humhub/humhub#5190]
### What steps will reproduce the problem?

- Switch to 1.9 codebase
- run php yii migrate/up --includeModuleMigrations=1

### What is the expected result?
- the migration to go smoothly

### What do you get instead?

- *** applying m150720_174011_initial
    > create table cfiles_file ...Exception 'yii\db\Exception' with message 'SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cfiles_file' already exists
The SQL being executed was: CREATE TABLE `cfiles_file` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`parent_folder_id` int(11) NULL
) '

### Additional info

- Original codebase is 1.8.0
- deleting cfiles_file will and re-run the migration will throw the same error but for cfiles_folder
- deleting both tables and re-run the migration lead to a migration success
(but obviously it is not really an opton in production env.)
Yii Migration Tool (based on Yii v2.0.40)

- More logs : 

Total 14 new migrations to be applied:
	m150720_174011_initial
	m160810_174011_add_description
	m160817_180831_add_type
	m160824_120822_add_has_wall_entry
	m170210_154141_folderNoStream
	m170211_110702_show_in_stream
	m170830_122433_set_root_partent_null
	m170830_122439_foreignkeys
	m201030_071320_add_download_counter
	m201217_081828_fix_oembed_setting
	m210211_051243_container_tag
	m210310_103412_fix_hash
	m210331_115144_default_timezone
	m210506_060737_profile_field_directory_filter

Apply the above migrations? (yes|no) [no]:yes
*** applying m150720_174011_initial
    > create table cfiles_file ...Exception 'yii\db\Exception' with message 'SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cfiles_file' already exists
The SQL being executed was: CREATE TABLE `cfiles_file` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`parent_folder_id` int(11) NULL
) '

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.0 -> 1.9.0
| PHP version      |  7.3
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Hmm, I don't think it's a 1.9 related problem. 

What happens if you do a "migrate/up --includeModuleMigrations=1" on the original 1.8.0 installation? Are there any available migrations displayed then?

**Comment by superseby2** [comment]
To do that, I guess I should setup the database in its previous state ? 

Changing only the code base and running the command gives : 

Yii Migration Tool (based on Yii v2.0.40)

No new migrations found. Your system is up-to-date.

**Comment by luke-** [comment]
Yes, the database state is the interesting part.

**Comment by superseby2** [comment]
Well .. I could not get back to the previous state on my dev environnement. 
I went to use the prod backups and had fewer migrations proposed : 

Total 5 new migrations to be applied:
	m201217_081828_fix_oembed_setting
	m210211_051243_container_tag
	m210310_103412_fix_hash
	m210331_115144_default_timezone
	m210506_060737_profile_field_directory_filter

and all went smoothly !

So, definitively something rigged in my previous setup. 

Thx for your help.
