### ISSUE TITLE
The Notification permission may only be requested in a secure context

### ISSUE THREAD

**Issue by romanown** [humhub/humhub#5191]
I  coped the example-basi module as mymodule. i coped base humhub theme as mytheme. i copyed views folder The notification modue of humhub to views folder mytheme. i added into the file layouts/web.php string  
`<?= Button::primary(Yii::t('NotificationModule.base', 'Say Hello!'))->action("mymodule.hello")->loader(false); ?>`
but after is in console browser writed
`The Notification permission may only be requested in a secure context.`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
This is probably just a warning that the PWA is probably not working correctly, since it is a development environment without HTTPS.

**Comment by romanown** [comment]
i fix it

**Comment by arseniigorkin** [comment]
Hi! How did you fix it?

**Comment by romanown** [comment]
sorry. I've been doing this project for a short time and it's been a long time and I don't remember what I did. I don't even remember what I wrote about it here.
