### ISSUE TITLE
Is there a way to log Deleted posts? 

### ISSUE THREAD

**Issue by sholtomcneilage** [humhub/humhub#5192]
Hey team, 

Hope you're well. 

We're having some issues with people making comments which go against our community guidelines and deleting them after. 

I've checked the logs and these events don't seem to be captured. 

Is there any way to store the deleted comments event as well as the content as users are doing this? 

Thanks!

**Comment by luke-** [comment]
Currently there is no such logging option.

However, it is planned to integrate logging for such cases:
https://github.com/humhub/humhub/issues/3988
