### ISSUE TITLE
Confirm leave page for Posts & Comments

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5194]
### Is your feature request related to a problem? Please describe.

Like on other forms and e.g. the wiki pages, it would be good to get a warning when you want to leave the page and there is an unsaved post/comment.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5214, please note the form feature `acknowledge` didn't work for several forms on a same page, so I had to modify the JS code to make it works.

**Comment by luke-** [comment]
@yurabakhtin Ok, looks fine. Can you please check the tests? Seems there is an error.

**Comment by yurabakhtin** [comment]
@luke- Yes, the bug was in my new code of the PR, I have fixed that in next commit https://github.com/humhub/humhub/pull/5214/commits/0638397861e2ccc2f5a1c27524aacae873f5693f, but it is strange why the codeception tests were not run for the commit but the PR has green "All checks have passed".

**Comment by luke-** [comment]
@yurabakhtin Thanks.  It worked! In the meantime there were changes in the "develop" branch and the conflicts (changelog) had to be resolved first.
