### ISSUE TITLE
Export users (in the administration) crashes

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5195]
### What steps will reproduce the problem?

Go to Administration -> Users -> Export (CSV or XLSX) (direct link: `/admin/user/export?format=csv`)

### What is the expected result?

A file

### What do you get instead?

```
TypeError
htmlspecialchars(): Argument #1 ($string) must be of type string, array given
```

See full log below.

The bug is in the file `/humhub/protected/vendor/yiisoft/yii2/helpers/BaseHtml.php`:
```
    public static function encode($content, $doubleEncode = true)
    {
        return htmlspecialchars($content, ENT_QUOTES | ENT_SUBSTITUTE, Yii::$app ? Yii::$app->charset : 'UTF-8', $doubleEncode);
    }
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.0
| PHP version      | 8.0

TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given in /var/www/communaute.seve.org/humhub/protected/vendor/yiisoft/yii2/helpers/BaseHtml.php:111
Stack trace:
#0 /var/www/communaute.seve.org/humhub/protected/vendor/yiisoft/yii2/helpers/BaseHtml.php(111): htmlspecialchars()
#1 /var/www/communaute.seve.org/humhub/protected/vendor/yiisoft/yii2/i18n/Formatter.php(497): yii\helpers\BaseHtml::encode()
#2 [internal function]: yii\i18n\Formatter->asText()
#3 /var/www/communaute.seve.org/humhub/protected/vendor/yiisoft/yii2/i18n/Formatter.php(460): call_user_func_array()
#4 /var/www/communaute.seve.org/humhub/protected/humhub/components/export/DataColumn.php(126): yii\i18n\Formatter->format()
#5 /var/www/communaute.seve.org/humhub/protected/humhub/components/export/SpreadsheetExport.php(331): humhub\components\export\DataColumn->renderDataCellContent()
#6 /var/www/communaute.seve.org/humhub/protected/humhub/components/export/SpreadsheetExport.php(262): humhub\components\export\SpreadsheetExport->composeBodyRow()
#7 /var/www/communaute.seve.org/humhub/protected/humhub/modules/admin/controllers/UserController.php(401): humhub\components\export\SpreadsheetExport->export()
#8 [internal function]: humhub\modules\admin\controllers\UserController->actionExport()
#9 /var/www/communaute.seve.org/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/communaute.seve.org/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#11 /var/www/communaute.seve.org/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#12 /var/www/communaute.seve.org/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#13 /var/www/communaute.seve.org/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#14 /var/www/communaute.seve.org/humhub/index.php(38): yii\base\Application->run()
#15 {main}

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5198.
I think this bug appeared after we moved user tags in separate table, so `User->tags` became an array instead of string in previous version.

**Comment by luke-** [comment]
@yurabakhtin thank you!

**Comment by funkycram** [comment]
Thanks @yurabakhtin !
I confirm this patch solves the problem.
