### ISSUE TITLE
Auto creating following for friends 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5200]
### What steps will reproduce the problem?

Since 1.9 you can un-/follow friends.

### What is the expected result?

Still following all friends after update.

### What do you get instead?

No following of friends after upgrade to 1.9

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5201.

**Comment by luke-** [comment]
@yurabakhtin Thanks for the fast PR!

**Comment by miqrogroove** [comment]
Tested and working now.  Thank you!!
