### ISSUE TITLE
Bug Update 1.9

### ISSUE THREAD

**Issue by Bust3r666** [humhub/humhub#5213]
After the update 1.9 when i click on people button on the main menu the software give me this error:
"
Wed, 28 Jul 2021 19:32:39 +0200  yii\base\InvalidArgumentException
yii\base\InvalidArgumentException: Key "directory_filter" is not a column name and can not be used as a filter in /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php:238
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(191): yii\db\ActiveRecord::filterCondition(Array, Array)
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(121): yii\db\ActiveRecord::findByCondition(Array)
#2 /var/www/humhub/protected/humhub/modules/user/widgets/PeopleFilters.php(85): yii\db\BaseActiveRecord::findAll(Array)
#3 /var/www/humhub/protected/humhub/modules/ui/widgets/DirectoryFilters.php(35): humhub\modules\user\widgets\PeopleFilters->initDefaultFilters()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\ui\widgets\DirectoryFilters->init()
#5 [internal function]: yii\base\BaseObject->__construct(Array)
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php(412): ReflectionClass->newInstanceArgs(Array)
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\modules\\...', Array, Array)
#9 /var/www/humhub/protected/humhub/components/Widget.php(60): yii\BaseYii::createObject(Array)
#10 /var/www/humhub/protected/humhub/modules/user/views/people/index.php(33): humhub\components\Widget::widget()
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...')
#12 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/humhub...', Array)
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/humhub...', Array, Object(humhub\modules\user\controllers\PeopleController))
#14 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(410): yii\base\View->render('index', Array, Object(humhub\modules\user\controllers\PeopleController))
#15 /var/www/humhub/protected/humhub/modules/user/controllers/PeopleController.php(69): yii\base\Controller->render('index', Array)
#16 [internal function]: humhub\modules\user\controllers\PeopleController->actionIndex()
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('', Array)
#20 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('user/people', Array)
#21 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#22 /var/www/humhub/index.php(25): yii\base\Application->run()
#23 {main} 
"

and YII migration tool give me this error:

"
     Yii Migration Tool (based on Yii v2.0.40)

Total 3 new migrations to be applied:
	m210211_051243_container_tag
	m210331_115144_default_timezone
	m210506_060737_profile_field_directory_filter

*** applying m210211_051243_container_tag
    > create table contentcontainer_tag ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'contentcontainer_tag' already exists
The SQL being executed was: CREATE TABLE `contentcontainer_tag` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` varchar(100) NOT NULL,
	`contentcontainer_class` char(60) NOT NULL
) (/var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `c...')
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('CREATE TABLE `c...')
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /var/www/humhub/protected/humhub/modules/content/migrations/m210211_051243_container_tag.php(23): yii\db\Migration->createTable('contentcontaine...', Array)
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(114): m210211_051243_container_tag->safeUp()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): yii\db\Migration->up()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m210211_051243_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('up', Array)
#11 /var/www/humhub/protected/humhub/commands/MigrateController.php(198): yii\console\Controller->runAction('up')
#12 /var/www/humhub/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll()
#13 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase()
#14 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('database', Array)
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('admin/informati...', Array)
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#19 /var/www/humhub/index.php(25): yii\base\Application->run()
#20 {main}
*** failed to apply m210211_051243_container_tag (time: 0.001s)

0 from 3 migrations were applied.

Migration failed. The rest of the migrations are canceled.
"

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look here?

**Comment by luke-** [comment]
Duplicate: https://github.com/humhub/humhub/issues/5204
