### ISSUE TITLE
Profile tags links to old directory

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5215]
### What steps will reproduce the problem?
![image](https://user-images.githubusercontent.com/4736168/127664177-dd961399-9e35-4e3b-88d9-fc243e361cc3.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- I also found other similar places and fixed them all in PR https://github.com/humhub/humhub/pull/5222.

Also I find the old links in modules `enterprise-theme` and `custom-pages`, I will fix there too.

**Comment by luke-** [comment]
@yurabakhtin Yes thanks! For the custom pages issue I've created a new issue:
https://github.com/humhub/custom-pages/issues/192
