### ISSUE TITLE
missing:  1. Content review mechanism 2. Reporting of content and comments

### ISSUE THREAD

**Issue by lwq057** [humhub/humhub#5220]
Suppose this is an advertisement content or malicious content.

Once I register and log in, I can publish any content that violates the rules without restraint.

I can also register many accounts to frequently post illegal comments in other people's content.

The system is missing:

1. Content review mechanism
2. Reporting of content and comments
3. The creation of space needs to be reviewed

humhub is doing very well, hope humhub can pay attention to this issue.

**Comment by luke-** [comment]
Please create individual issues for missing functionalities.

There is a Report Content Module which probably covers something.
