### ISSUE TITLE
User Approvals - Use Richtext

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5229]
### Is your feature request related to a problem? Please describe.

We should use our Richtext Editor also for the e-mail approval/decline mails. The Richtext2HTMLEmail parser can then be used in the e-mail.

![image](https://user-images.githubusercontent.com/4736168/128163401-de2f0cc7-9c31-45cf-a05f-0e4e86cbec86.png)

It would be nice if we could disable some features like FileUpload/OEmbed in the Richtext editor. (Possibly a separate issue in the Prosemirror repo?).

The Template must be also Rrichtext.
![image](https://user-images.githubusercontent.com/4736168/128163566-d810638b-568d-4fe7-b545-19c6cc0fdd7c.png)

**Comment by ArchBlood** [comment]
Isn't that why $exclude is implemented?

**Comment by ArchBlood** [comment]
> @ArchBlood May be. i don't know des $exclude, but that sounds like it would be just that!
Seen in this file it should be possible to do this very thing
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/widgets/richtext/AbstractRichTextEditor.php

**Comment by ArchBlood** [comment]
Changing the following
```php
<?= $form->field($model, 'registrationApprovalMailContent')->textarea(['class' => 'form-control', 'rows' => 8, 'style' => 'resize: vertical']); ?>
```
to this should do what you're wanting done, not sure if `{displayName}`, `{loginLink}` or `{AdminName}` will be usable done this way though 🤔

```php
<?= $form->field($model, 'registrationApprovalMailContent')->widget(RichTextField::class, ['exclude' => ['oembed', 'upload']]); ?>
```

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5234.

**Comment by luke-** [comment]
@yurabakhtin Please see my review

**Comment by yurabakhtin** [comment]
@luke- I answered there.
