### ISSUE TITLE
Typo in Offline Page Text

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#5238]
When viewing `offline.pwa.html` the text currently reads, "refresh this page once your are online again", with the word "you" misspelled.

This typo is still present as of v1.9.0

https://github.com/humhub/humhub/blob/64d439c03dc4d4cf090e5a7ea158a59135729b7b/protected/humhub/modules/web/pwa/views/offline/index.php#L45

https://github.com/humhub/humhub/blob/64d439c03dc4d4cf090e5a7ea158a59135729b7b/protected/humhub/modules/web/messages/am/pwa.php#L21

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5240.
