### ISSUE TITLE
Error Database Migration 

### ISSUE THREAD

**Issue by Bust3r666** [humhub/humhub#5245]
Hi,
After previously migration errors i have delete:

contentcontainer_tag table
contentcontainer_tag_relation table
AND
the column tags_cached of the contentcontainer table.

But now give me this error.

Yii` Migration Tool (based on Yii v2.0.40)

Total 3 new migrations to be applied:
m210211_051243_container_tag
m210331_115144_default_timezone
m210506_060737_profile_field_directory_filter

*** applying m210211_051243_container_tag
> create table contentcontainer_tag ... done (time: 0.008s)
> create unique index unique-contentcontainer-tag on contentcontainer_tag (contentcontainer_class,name) ... done (time: 0.007s)
> create table contentcontainer_tag_relation ... done (time: 0.007s)
> add primary key pk-contentcontainer-tag-rel on contentcontainer_tag_relation (contentcontainer_id,tag_id) ... done (time: 0.007s)
> add foreign key fk-contentcontainer-tag-rel-contentcontainer-id: contentcontainer_tag_relation (contentcontainer_id) references contentcontainer (id) ... done (time: 0.020s)
> add foreign key fk-contentcontainer-tag-rel-tag-id: contentcontainer_tag_relation (tag_id) references contentcontainer_tag (id) ... done (time: 0.026s)
> add column tags_cached string NULL DEFAULT NULL to table contentcontainer ... done (time: 0.006s)
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'where clause'
The SQL being executed was: SELECT * FROM space WHERE (tags != '') AND (tags IS NOT NULL) (/var/www/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'SELECT * FROM ...') #1 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1165): yii\db\Command->internalExecute('SELECT * FROM ...')
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Command.php(407): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Query.php(248): yii\db\Command->queryAll()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#5 /var/www/humhub/protected/humhub/modules/content/migrations/m210211_051243_container_tag.php(67): yii\db\ActiveQuery->all()
#6 /var/www/humhub/protected/humhub/modules/content/migrations/m210211_051243_container_tag.php(37): m210211_051243_container_tag->moveContainerTags('humhub\modules\...')
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/db/Migration.php(114): m210211_051243_container_tag->safeUp()
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(744): yii\db\Migration->up()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m210211_051243_...')
#10 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('up', Array)
#14 /var/www/humhub/protected/humhub/commands/MigrateController.php(198): yii\console\Controller->runAction('up')
#15 /var/www/humhub/protected/humhub/modules/admin/controllers/InformationController.php(95): humhub\commands\MigrateController::webMigrateAll()
#16 [internal function]: humhub\modules\admin\controllers\InformationController->actionDatabase()
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('database', Array)
#20 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('admin/informati...', Array)
#21 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#22 /var/www/humhub/index.php(25): yii\base\Application->run()
#23 {main}
*** failed to apply m210211_051243_container_tag (time: 0.081s)

0 from 3 migrations were applied.

Migration failed. The rest of the migrations are canceled.

**Comment by ArchBlood** [comment]
What database driver are you using, MariaDB, MySQL, or other?
Are all your collation tables and collations `utf8mb4_unicode_ci`?
Are you using the InnoDB or MyISAM table engine?

Overall you're only giving limited information
See #4946 as well as #5204 for more information about this issue

**Comment by luke-** [comment]
Please use
https://github.com/humhub/humhub/issues/5245#issuecomment-899607550
