### ISSUE TITLE
Space Join Activity

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#5254]
### Is your feature request related to a problem? Please describe.
Currently, when you join a Space it shows individual spaces that the person has joined in mass separate activities, this then floods the Latest Activities widget as well as emails sent to users, this shouldn't be the norm (see the [community site](https://community.humhub.com/dashboard) for example)

### Describe the solution you'd like
When someone joins multiple spaces at once the activities should show all in one activity message as well as reflect the same in email summaries

### Describe alternatives you've considered
I thought about the limiting of activities allowed shown but such a workaround shouldn't be needed, so in the end, merging multiple activities is the only option that I could define as a sure-fire way of fixing it, I'm also open to other suggestions if more were given.

**Comment by luke-** [comment]
@ArchBlood Thanks, This is already planned here: https://github.com/humhub/humhub/issues/3430
