### ISSUE TITLE
Delete Old Unread Notifications

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5257]
### Is your feature request related to a problem? Please describe.

- Unread notifications are never deleted
- The time for deletion cannot be changed via the configuration file (module class).

See:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/notification/Events.php#L146

### Describe the solution you'd like

- Delete unread notifications by default after 3 months
- Delete read notifications after 2 months
- Add these times to the module class, then they can be configured if necessary.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5260.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
