### ISSUE TITLE
Who invited new user?

### ISSUE THREAD

**Issue by RoundAboutWEB** [humhub/humhub#5258]
Transfer the "Invited by" column to the "Pending approvals" display as well. \
This would facilitate the administrative work.

**Comment by vsemradu** [comment]
I didn't quite understand the task. Please give a detailed explanation.

**Comment by RoundAboutWEB** [comment]
I miss in the list of new user approvals to be approved the information who invited this user:

![grafik](https://user-images.githubusercontent.com/26809494/150332076-b7e57767-7256-442a-9e0b-add0b771145c.png)

**Comment by vsemradu** [comment]
![screenshot_3](https://user-images.githubusercontent.com/10543601/150774783-f26e398f-8348-42b3-8fcb-a425d03b6742.png)

**Comment by RoundAboutWEB** [comment]
Exactly this column at the point I mean.
Why is it not displayed for me?
What do I have to do so that it is displayed?

**Comment by luke-** [comment]
@RoundAboutWEB There is a Pull request here: https://github.com/humhub/humhub/pull/5511
