### ISSUE TITLE
Allow members of groups other than sys admin to view all content

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5263]
### Is your feature request related to a problem? Please describe.

If the Content module properties `adminCanViewAllContent` or `adminCanEditAllContent` are changed in the `protected/config/common.php` file, the modified values applies only to sys admin.

In some cases, we need to let others groups members than sys admin to be able to view or edit users contents (e.g. moderators).

### Describe the solution you'd like

In the groups permissions (`/admin/group/manage-permissions?id=x`), add the possibility to change theses values instead of having them in the `Module.php` file.
I can create a PR for that if you think it is a good proposal.

**Comment by funkycram** [comment]
Perhaps an easier solution would be to enable view content (if activated in config/common.php) to all users that can manage user?
In that case, the [canViewAllContent() method](https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/user/models/User.php#L700) could be:

```
    public function canViewAllContent()
    {
        return Yii::$app->getModule('content')->adminCanViewAllContent && ($this->isSystemAdmin() || (new PermissionManager(['subject' => $this]))->can(ManageUsers::class);
    }
```

If you think it's a good idea, I can do a PR.

**Comment by funkycram** [comment]
@luke- would you agree for such a PR?

**Comment by luke-** [comment]
@funkycram Yes, but I would like to keep the option `adminCanViewAllContent` only via the configuration file. Admins should not be able to simply switch this. 

When on `true` we could connect the permission with `ManageSpaces` and with limit to `Space` content?
or/and `ManageUsers` and profile content?

**Comment by funkycram** [comment]
@luke- yes, that's much better (MangeUsers for profile content and ManageSpaces for space's content).
PR: https://github.com/humhub/humhub/pull/6093
