### ISSUE TITLE
Logging shows not entries

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5265]
### What steps will reproduce the problem?

If called initially the logging section sometimes doesn't show any entries.

![image](https://user-images.githubusercontent.com/4736168/131353369-b4730d69-aff0-4007-87da-71de3c5693af.png)

At "select category" there are logigng categories. If select "Select category" again, I receive following output

![image](https://user-images.githubusercontent.com/4736168/131353530-2707b270-aecb-48a8-93a1-c3f8c5494df4.png)
 
We should ensure, that if called initially, the page should always show all log entries

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | develop
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- When I open the page from any other page I get URL `http://humhub.local/admin/logging` and in all cases even on many times page reloading I always see the filter Level = "Error":
<img width="1515" alt="logging_initial_page" src="https://user-images.githubusercontent.com/6995524/131383122-c6dcaf01-137f-480c-9943-98b133cd905e.png">

I can get the page without filters if I manually remove the filter, but in such case the URL is changed as you can see:
<img width="1515" alt="logging_with_params" src="https://user-images.githubusercontent.com/6995524/131383248-176928c4-2213-4741-8845-79c247400297.png">

Could you please tell me some more details how to reproduce this if you know?

**Comment by luke-** [comment]
@yurabakhtin fyi, I've send you the link to a example site. Seems it's caused because there are no "Error" entries.

**Comment by yurabakhtin** [comment]
@luke- I fixed in PR https://github.com/humhub/humhub/pull/5267, now it looks like this when no "Error" logs:

<img width="1156" alt="fixed_log_error" src="https://user-images.githubusercontent.com/6995524/131394203-cc861f49-f0b9-4106-b1bd-64f76fe11bb4.png">

If you think we should not use the default filter level "Error" let me know.

**Comment by luke-** [comment]
@yurabakhtin Thanks, that should be ok!
