### ISSUE TITLE
Information/Logging shows "0 entries" even if there are Info and Warning level entries

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#5270]
### What steps will reproduce the problem?
1. You will need a HumHub instance which has no error messages but Info or Warning messages in its Logs.
2. Go to Administration/Information/Logging

### What is the expected result?
Info / Warning messages should be shown since the "Select level" field is empty, i.e. I assume that there is no filtering in place.

### What do you get instead?
"Total 0 entries found."

### Additional info
Workaround: Select a level and remove it again. I assume the "Selected Level" defaults to "Error" but it is not shown as such, which is quite confusing.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.1
| PHP version      |  7.3.20
| Operating system | CentOS 8 Stream

**Comment by luke-** [comment]
Should be fixed here: https://github.com/humhub/humhub/issues/5265
