### ISSUE TITLE
Tif file creates warning each time the space is accessed

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#5271]
### What steps will reproduce the problem?
1. Attach a tif / tiff file to a post.
1. Navigate to  the space / user containing this post.
2. Check Information -> Logging (Be aware of #5270 )

### What is the expected result?
Either convert/show the tif correctly or ignore it, but don't spam the log on each space access.

### What do you get instead?
```
INFO:
$_GET = [
'r' => 'space/space/stream'
'cguid' => '88c676b8-4585-498a-a6cd-514a1aaab9e9'
'StreamQuery' => [
'sort' => 'c'
'from' => '0'
'limit' => '8'
]
]

$_SERVER = [
'USER' => 'apache'
'HOME' => '/usr/share/httpd'
'SCRIPT_NAME' => '/index.php'
'REQUEST_URI' => '/index.php?r=space%2Fspace%2Fstream&cguid=88c676b8-4585-498a-a6cd-514a1aaab9e9&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=8'
'QUERY_STRING' => 'r=space%2Fspace%2Fstream&cguid=88c676b8-4585-498a-a6cd-514a1aaab9e9&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=8'
'REQUEST_METHOD' => 'GET'
'SERVER_PROTOCOL' => 'HTTP/1.1'
'GATEWAY_INTERFACE' => 'CGI/1.1'
'REMOTE_PORT' => '44452'
'SCRIPT_FILENAME' => '/var/www/testing.humhub-{redacted}.de/html/index.php'
'SERVER_ADMIN' => 'it@{redacted}.de'
'CONTEXT_DOCUMENT_ROOT' => '/var/www/testing.humhub-{redacted}.de/html'
'CONTEXT_PREFIX' => ''
'REQUEST_SCHEME' => 'https'
'DOCUMENT_ROOT' => '/var/www/testing.humhub-{redacted}.de/html'
'REMOTE_ADDR' => '{redacted}'
'SERVER_PORT' => '443'
'SERVER_ADDR' => '{redacted}'
'SERVER_NAME' => 'testing.humhub-{redacted}.de'
'SERVER_SOFTWARE' => 'Apache/2.4.37 (centos) OpenSSL/1.1.1k'
'SERVER_SIGNATURE' => ''
'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'
'HTTP_COOKIE' => '{redacted}'
'HTTP_CONNECTION' => 'keep-alive'
'HTTP_REFERER' => 'https://testing.humhub-{redacted}.de/index.php?r=space%2Fspace&cguid=88c676b8-4585-498a-a6cd-514a1aaab9e9'
'HTTP_SEC_FETCH_SITE' => 'same-origin'
'HTTP_SEC_FETCH_MODE' => 'cors'
'HTTP_SEC_FETCH_DEST' => 'empty'
'HTTP_DNT' => '1'
'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
'HTTP_X_CSRF_TOKEN' => '{redacted}=='
'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5'
'HTTP_ACCEPT' => '*/*'
'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0'
'HTTP_HOST' => 'testing.humhub-{redacted}.de'
'proxy-nokeepalive' => '1'
'SSL_TLS_SNI' => 'testing.humhub-{redacted}.de'
'HTTPS' => 'on'
'UNIQUE_ID' => '{redacted}@{redacted}'
'FCGI_ROLE' => 'RESPONDER'
'PHP_SELF' => '/index.php'
'REQUEST_TIME_FLOAT' => 1630743608.7044
'REQUEST_TIME' => 1630743608
] 

WARNING: 
Could not convert file with id 20. Error: Unable to open image /var/www/testing.humhub-{redacted}.de/html/uploads/file/a/f/afb860c0-27dd-436f-9a5b-2f7eab481370/file 
```

### Additional info
Not installed: PHP - ImageMagick Extension (Hint: Optional)
Not installed: PHP - GraphicsMagick Extension (Hint: Optional) 

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.1
| PHP version      |  7.3.20
| Operating system | CentOS 8 Stream

**Comment by ArchBlood** [comment]
At least one of the image libraries should be installed and enabled in such cases :thinking:

**Comment by dreua** [comment]
@ArchBlood Is this a guess, knowledge or official statement?
I don't have those installed because I couldn't find packages for CentOS 8 and I didn't compile/install them myself yet, because everything else seems to work just fine. I'm not that deep into this topic, but it [looks like GD should be able to process TIFFs](https://libgd.github.io/manuals/2.3.0/files/gd_tiff-c.html) as well.

**Comment by ArchBlood** [comment]
> @ArchBlood Is this a guess, knowledge or official statement?
> I don't have those installed because I couldn't find packages for CentOS 8 and I didn't compile/install them myself yet, because everything else seems to work just fine. I'm not that deep into this topic, but it [looks like GD should be able to process TIFFs](https://libgd.github.io/manuals/2.3.0/files/gd_tiff-c.html) as well.

Small and easy tutorial on installing it for CentOS 8
https://idroot.us/install-imagemagick-centos-8/

Looking at the PHP manual;
https://www.php.net/manual/en/intro.image.php

> You can use the image functions in PHP to get the size of JPEG, GIF, PNG, SWF, **_TIFF_**, and JPEG2000 images.

In addition, if you want to see which formats are supported by your GD library you could of course use the following by creating a file then navigating to `yourdomain.com/example.php`

```php
<?php
var_dump(gd_info());
?>
```

Of course, I would still install another library over relying solely on the GD library as it even states the following;
> There is only most basic support for the TIFF format available for now; for instance, multiple pages are not yet supported.

**Comment by ArchBlood** [comment]
As for the general term `TIFF`, just because it claims to support it, doesn't mean that it's fully supported both versions of the extension, as `TIF` is mostly used in older file systems while newer ones fully support `TIFF` and sometimes have `TIF` disabled or not supported 🤔

**Comment by dreua** [comment]
Thanks for the input, ArchBlood, for some reason this issue just disappeared therefore I'm closing this.

Just reopened a similar issue for svg: https://github.com/humhub/humhub/issues/6595
