### ISSUE TITLE
No access to directory/spaces as admin

### ISSUE THREAD

**Issue by atk87a** [humhub/humhub#5275]
I mentioned that i cant access directory/spaces as a user or admin.
humhub says no access.
There is no entry in the protocol.
I use the latest version, but it also was an issue before the update.

Maybe a database problem?

Is there a way to fix this?

**Comment by ArchBlood** [comment]
Not sure why you're not able to access as an admin in previous versions but it is now permission-based as of 1.9.x

![Screenshot_1](https://user-images.githubusercontent.com/35392110/132252495-73621bea-8db4-4b3e-ac15-c7a4c2e21192.png)

If you're using a custom theme that uses the old, now deprecated Directory core module, then you will have to update your theme to comply with the new changes, the same can be said for core widgets used

**Comment by luke-** [comment]
@atk87a The `/directory` module is not longer available with Humhub 1.9+

**Comment by atk87a** [comment]
ah, ok. this explains the problem with the missing directory/ path.
thank you all!
