### ISSUE TITLE
Allow to set the number of contents from which "Show {i} more." appears in the stream

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5280]
### Is your feature request related to a problem? Please describe.

For instance, create 3 events in the calendar.
Only 2 will appear on the wall stream.
To see the third one, you need to click the link "Show 1 more."

Many people are not used to that and do not see the third content because nowadays, the stream runs down the page by itself.

### Describe the solution you'd like

In https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/stream/Module.php, add this public property
```
    /**
     * @var int number of contents from which "Show more" appears in the stream
     */
    public $streamSuppressLimit = 2;
```

In https://github.com/humhub/humhub/blob/0dae9fc4718d40d7648c4491fce5a1522d508357/protected/humhub/modules/stream/models/StreamSuppressQuery.php#L88 replace `$this->limit < 3` with `$this->limit <= $streamModule->streamSuppressLimit` and add before this line:
```
        /* @var $streamModule \humhub\modules\stream\Module */
        $streamModule = Yii::$app->getModule('stream');
```

### PR

If you agree with this idea, I can send a PR.

**Comment by luke-** [comment]
@funkycram Sounds good. I first assumed that it is already configurable :-)

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/5288
