### ISSUE TITLE
On account creation, registration form has HTML tag set with English language

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5282]
### What steps will reproduce the problem?

Create an account.
On registration form, with have `<html lang="en">` even if the form language is in an other language (du to `allowedLanguages` param).

Problem: Google Chrome thinks the page is in English, and tries to translate the form from English to the browser's language. This transforms the text badly as the language was already correct.

### What is the expected result?

https://github.com/humhub/humhub/blob/0dae9fc4718d40d7648c4491fce5a1522d508357/protected/humhub/modules/user/views/layouts/main.php#L14
should be `<html lang="<?= Yii::$app->language ?>">`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.1

**Comment by funkycram** [comment]
See https://github.com/humhub/humhub/pull/5283

**Comment by luke-** [comment]
@funkycram Great, thanks!
