### ISSUE TITLE
stream entry based deactivation of comment function 

### ISSUE THREAD

**Issue by optitsolutions** [humhub/humhub#5284]
We have general posts in a Space for the information of all members. These posts should not be commented on. 

It would be handy if there was a "disable comments" option when creating entries.

Are there alternatives to achieve this goal? I have not identified any.

**Comment by luke-** [comment]
Currently it is only possible to disable the comment function on Space level.

With HumHub 1.10 it will be possible to disable comments for certain content.
See: https://github.com/humhub/humhub/issues/4495
