### ISSUE TITLE
Main layout width

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub#5285]
### What steps will reproduce the problem?

<img width="1153" alt="main_layout_width" src="https://user-images.githubusercontent.com/6995524/132850238-9f786640-947c-4551-88a1-e96bc2190647.png">

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9

**Comment by luke-** [comment]
@yurabakhtin Thank you for the report.

The problem seems to affect all Space or Profile pages that do not use a sidebar/snippet column.

Can you check if you can find a solution here?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5292:

<img width="1164" alt="fixed_main_layout" src="https://user-images.githubusercontent.com/6995524/133552216-79f04bb5-556a-47dd-9912-4b5a85a0570a.png">

Please note I removed the text color `#123456` from here https://github.com/humhub/humhub/pull/5292/files#diff-253504ccb914db6269dd51736a32292747cc1bccb65f52102f08112bc24d3a0bL99 because it looks like forgotten debug code otherwise strange why this color was only on the width >768px and <991px.

**Comment by luke-** [comment]
@yurabakhtin Looks good, thank you! Also for the little cleanup!
