### ISSUE TITLE
Can't login; wrong password with valid password, Admin saved password not working either

### ISSUE THREAD

**Issue by cybrpimp** [humhub/humhub#5289]
# Can't login; wrong password

![image](https://user-images.githubusercontent.com/61793417/133504482-0deaf8b7-6f05-4a8b-8130-3e2d0f9d2e2c.png)

We have a user we created in a new demo instance of Humhum and added some users.  One of the users we saved the password but can not log in.

So lets assume we screwed the pooch and got passwords mixed up.

![image](https://user-images.githubusercontent.com/61793417/133504556-dabd4e9c-dfa8-4c40-90dd-34513c91a852.png)

We even tried a Administrator password set feature; and no matter what combination of user\password we use, we get can't log in, the wrong password at the login screen.

Next, I'll try deleting the user and resetup, but maybe in the meantime, maybe someone has a solution?

| Q                | A
| ---------------- | ---
| HumHub version   | Version: 1.9.1
| PHP version      | 7?
| Operating system | cPanel/Not sure Posix flavor

**Comment by ArchBlood** [comment]
Is this a fresh install or updated from an older version?

Currently I'm seeing no issues with the login function, is the password field being shown in the database as filled out? :thinking:

**Comment by gustrix** [comment]
I am experiencing the same issue.
Fresh install from cpanel. I was auto-logged in as admin. I created a new account. The password didn't work.
I tried changing it from the admin account. I also tried resetting it from the login page. Nothing works.

HumHub  Community Edition
Version: 1.9.1

**Comment by cybrpimp** [comment]
> Is this a fresh install or updated from an older version?
> 
> Currently I'm seeing no issues with the login function, is the password field being shown in the database as filled out? 🤔

Yes, brand new installed from cPanel and no matter what, user & password does not work.
