### ISSUE TITLE
Cant delete user as Administrator

### ISSUE THREAD

**Issue by cybrpimp** [humhub/humhub#5291]
We do not seem to be able to delete a user in the Adminstration.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
Have you setup your `queue/run` Cron Job?

**Comment by cybrpimp** [comment]
Yes, in theory the CronJob is setup.

![image](https://user-images.githubusercontent.com/61793417/135556067-a7cde099-9cac-44b0-af2d-d8dedb203140.png)

**Comment by cybrpimp** [comment]
After creating a support ticket with my ISP it turns out the cPanel Softalicious installation had the wrong path to PHP in the cronjob.

The path has been fixed and we are running cronjobs now.
