### ISSUE TITLE
Possibility to automatically go to default space on login?

### ISSUE THREAD

**Issue by hobbesjaap** [humhub/humhub#5295]
### Is your feature request related to a problem? Please describe.

Not so much a problem, but people who aren't very tech-savvy tend to get quite confused. Since I'm starting out with a very small community, I'm only using one space. So I would like all people to be directed to that space after login. So not to their dashboard.

### Describe the solution you'd like

As soon as you login, to be automatically redirected to a Space (one that everyone is automatically signed up to anyway, the Welcome Space).

### Describe alternatives you've considered

Using the Space URL somewhere. But it's a bit clunky doing it that way.

**Comment by luke-** [comment]
Please check the documentation or Community wiki. You can overwrite the default homepageUrl.
