### ISSUE TITLE
Format notification emails in HTML 

### ISSUE THREAD

**Issue by BSP-ALIPTIC** [humhub/humhub#5297]
I think providing a system for formatting emails in HTML, for example for notifications, would be relevant: a lot of HumHub users seem to be waiting for this feature.

Is this possible?

**Comment by luke-** [comment]
Can you give a specific example here? Actually, there is already basic support here. However, this is not yet implemented in all places.

**Comment by BSP-ALIPTIC** [comment]
Here is the published message 
![image](https://user-images.githubusercontent.com/38069229/134029586-716db51d-5bfa-46bb-b438-c7663e874c72.png)

Here is the rendering by email 
![image](https://user-images.githubusercontent.com/38069229/134029699-4e19a78a-f614-48cf-8a0c-31b388b9ee87.png)

Humhub version 1.9.1 

Maybe I missed something to configure?

**Comment by luke-** [comment]
Your example email is not a Notification E-Mail it is a Mail Summary. These are two different concepts in HumHub (Notifications and Activities).

Formatting of the mail summaries (your case) is currently not implemented. Currently, it is intentionally without markup to ensure overview and readability.

**Comment by BSP-ALIPTIC** [comment]
Ok, thank you for your response (and your responsiveness). Sorry for the confusion.
In the event that I want to set up a markdown / HTML conversion, do you have any ideas?
Thanks again !

**Comment by luke-** [comment]
Here is an Extra Markdown to HtmlEmail Converter. https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/widgets/richtext/converter/RichTextToEmailHtmlConverter.php

Unfortunately, I can't provide you more details yet.

**Comment by BSP-ALIPTIC** [comment]
Thank you for that answer. This is already a starting point ;-)
This ticket can be closed.
Good day.

**Comment by luke-** [comment]
Ok,fFeel free to post results here then, maybe we can adopt some of it.

Related issue: https://github.com/humhub/humhub/issues/3970
