### ISSUE TITLE
Info page - Show overview of followers

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#5298]
![image](https://user-images.githubusercontent.com/38326726/134028318-3a10fd35-b3b8-4008-8226-80dea2a3f4e5.png)

Adding an overview of all space followers to the info page (similar to the overview of all space members) would be useful, especially when using the Enterprise Theme. Currently there is no possibility to see who is following a space when using the Enterprise Theme.

**Comment by yurabakhtin** [comment]
@Semir1212 @luke- PR https://github.com/humhub/humhub/pull/5439:

<img width="1146" alt="space_followers" src="https://user-images.githubusercontent.com/6995524/143018122-fabded8e-15a5-4b34-a734-2cc5fe161cd6.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks
