### ISSUE TITLE
Editor layout

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#5299]
**Editor and input area layout - Location of "send" buttons + other minor details**
Small problems buts it’s annoying (some of our community members complained),
See attached PDF file for details.
[Demo améliorations.pdf](https://github.com/humhub/humhub/files/7197393/Demo.ameliorations.pdf)

Solved by way of additionnal css and js in our custom theme.
See attached demo theme in ZIP file.
[HumHub_demo_210918.zip](https://github.com/humhub/humhub/files/7197394/HumHub_demo_210918.zip)
_Sorry, some comment lines remain in french_

I am only a "hoobbyist selfmade part time coder" so the modifications are surely not an example of the best academic way, but they have now been running for a few months and IT WORKS! 
Hope the same results to be achieved in one of the next  native HH code.

**Comment by orangiene** [comment]
Hello @Gilbertdelyon , @luke- ,

we have looked at the issue and should definitely pick up some points here. Thank you very much for your input.
We have created internal tasks on HumHub page for each of the issues and are working on them.
