### ISSUE TITLE
In a button, data-action-cancel-text doesn't wok

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5304]
### What steps will reproduce the problem?

Create a button with `confirm` method:
```
<?= Button::info()
    ->icon('info')
    ->link('#')
    ->confirm('title text', 'body text', 'confirm button text', 'cancel button text') ?>
```

Click on the button: the loader will start, but the confirm modal box will not appear.

Now, if you do the same button, but removing `, 'cancel button text'`, the confirm modal box will appear.

This bug has been introduced in a new Humhub version, as it was working before (cannot remember when, but for sure on Humhub 1.2.4).

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.1

**Comment by luke-** [comment]
@s-tyshchenko Thanks!
@funkycram Can you please take a look at the PR and check if it fixes the bug?

**Comment by funkycram** [comment]
Thanks @s-tyshchenko, it works fine!
