### ISSUE TITLE
Calling unknown method: yii\data\ActiveDataProvider::active()

### ISSUE THREAD

**Issue by tosintech-web** [humhub/humhub#5317]
### What steps will reproduce the problem?

Just after version up from ver.1.8.2 ~> ver.1.9.1.

Access:  Space -> manage -> members

### What is the expected result?

We want to manage members info.

### What do you get instead?

Error report. (bellow)

### Additional info

/var/www/localhost/htdocs/protected/humhub/modules/space/modules/manage/controllers/MemberController.php
line:50
```
$dataProvider = $searchModel->search(Yii::$app->request->queryParams)->active();
```
Unknown Method – yii\base\UnknownMethodException
Calling unknown method: yii\data\ActiveDataProvider::active()

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.1
| PHP version      | 7.4.3
| Operating system | unbuntu20.04

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
It seems that in your installation the line was overwritten. Here the original without error:
https://github.com/humhub/humhub/blob/v1.9.1/protected/humhub/modules/space/modules/manage/controllers/MemberController.php#L50

**Comment by tosintech-web** [comment]
Thank you for your reply.
We try to rewrite that.
