### ISSUE TITLE
Check People/Spaces automatic reload/scrolling

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5318]
On the community, the automatic reloading of users does not seem to work correctly...

https://community.humhub.com/people

Related: https://github.com/humhub/humhub/issues/5188

**Comment by yurabakhtin** [comment]
@luke- Yes strange bug, I could reproduce it locally on `develop` too, however I remember it worked before well, probably package `protected/vendor/npm-asset/intersection-observer` was updated last time so I had to apply this fix - https://github.com/humhub/humhub/pull/5321.

**Comment by luke-** [comment]
@yurabakhtin Ok, strange - but thanks for the fast fix!
