### ISSUE TITLE
Adding Ability to "Friend" Users

### ISSUE THREAD

**Issue by tcinelli** [humhub/humhub#532]
I'm looking to add User "Friend" functionality to HumHub for a current project and was hoping to get some input on the best way to go about doing so.  I looked at modules, but I'm not sure I'm able to override default User behavior.  The functionality I want to add is:

- Allow disable this new Friend functionality, which would restore the original functionality of "Follow" (which is why I thought a module might be best)
- User to request "Friend" status from other User (can accept, decline, block)
- Restrict ability to "Follow" ony if Users are first "Friends"
- Becoming "Friends" with another User automatically creates "Follows" between the Users
- Once Users are "Friends", each User will have the ability to "Unfollow" their Friend User, which will keep Friend status but not display the Unfollowed User's posts on dashboard, status notifications, etc.
- Update all "Follower" stats, widgets, etc to include Friends instead (for example on User Profile, only display "Friends" and not "Following" or "Followers"

The addition of Friend would not affect the Follow functionality except that if Friend was enabled, a User would first need to be a Friend before you could Follow him or her.

I didn't want to stray from the HumHub master branch to implement this.  If this feature is popular enough, maybe we can add to core, allow an admin config to either enable "Friend" mode or keep current "Follow" functionality.

Also, I was thinking if a current admin wanted to now use "Friend" mode, on initial "module" activation, any Follows in the DB would generate Friend requests, perhaps send out an email saying to continue Following user, you must first become Friends.

Let me know your thoughts, thanks.

**Comment by kkayacan** [comment]
+1

**Comment by acinelli** [comment]
Continuing work on this, would need Issue #548 to be merged into master at some point since it is the basis of this Friend feature (adding privacy settings "who can friend me", "only friends can see my posts", etc)

**Comment by dimontajik** [comment]
Very good

**Comment by jahd2602** [comment]
I've got an idea: What about "I follow you" and "You follow me" equals "Friends" and can write in each other's wall?

**Comment by WASasquatch** [comment]
Following usually indicates a platonic interest rather then friendship.

On Sun, May 31, 2015 at 5:19 PM, Jairo Honorio <notifications@github.com>
wrote:

> I've got an idea: What about "I follow you" and "You follow me" equals
> "Friends" and can write in each other's wall?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/532#issuecomment-107262024>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*

**Comment by buddha87** [comment]
Good news, the friendship system will be introduced in version 1.1. The friendship system has to be enabled by an admin, but will be part of the humhub core.
