### ISSUE TITLE
No 'dirty' bit set when editing many items

### ISSUE THREAD

**Issue by michaelh99** [humhub/humhub#5322]
my apologies if this is a dupe but I searched and didn't find.  I thought I'd commented on the same kind of issue or even maybe reported it before but again, didn't find it.

Latest release HH, start writing a comment to an existing post and if you click to switch away you lose your comment.

HH should set a dirty bit that asks the user if they want to abandon their edit.

I've seen this happen in other areas (new posts I'm sure) and will update with a more complete list.

**Comment by luke-** [comment]
It's already implemented in the upcoming 1.10 version.

You can already test this in our community. https://community.humhub.com

**Comment by michaelh99** [comment]
Sigh.  Again, my apologies.  Not sure why I couldn't find it.  Would you be kind enough to post a link to the feature/bug?

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/5194
