### ISSUE TITLE
Provide a site member the means to export his data 

### ISSUE THREAD

**Issue by dranii** [humhub/humhub#5326]
### Is your feature request related to a problem? Please describe.

This is a problem in the sense that we cannot provide a site member the means to export his data once he decides to delete his account or wishes to use another system of networks.  This Github itself as well as Wordpress, Drupal and various social network scripts including much smaller php-based social net scripts offer some means to export out at least the text data **per user by the user himself** (for example, a rss feed for all the public posts at the bare minimum).

Example :
![exp](https://user-images.githubusercontent.com/9887635/135752559-b9c3970d-d8b4-4418-8d46-a2b634291e08.png)

### Describe the solution you'd like

Some means for the member or the end-user to export out at least their text data. Or if its not possible, some means or script or at least a knowlegde-base code-snippet how the site admin can generate a text only file from the Humhub database of an user's content that she or he can download.

### Describe alternatives you've considered

As above.

**Comment by ArchBlood** [comment]
See https://github.com/humhub-contrib/legal/issues/20

**Comment by dranii** [comment]
@ArchBlood  Many Thanks for pointing me to the right direction. I see one of the related issues already closed but could not make out what solution or work-around was there. I have now seen humhub-contrib/legal#20 - Thanks. While this is in progress - if any member here can point to any work-around like Site Super Admin doing this via database manually for any one user OR how to generatie a RSS feed per user (public posts) - any plugins ... ? Thanks again.

**Comment by luke-** [comment]
@dranii In the meantime, such information has to be exported manually from the database.
