### ISSUE TITLE
Your contact form is broken

### ISSUE THREAD

**Issue by michaelh99** [humhub/humhub#5337]
I know this isn't a Humhub software problem but the only other way I saw to contact you was using the form that's broken.
The country list never populates and I can't send.  This is showing in the dev console...

Uncaught TypeError: jQuery(...).select2 is not a function
    <anonymous> https://www.humhub.com/en/news line 129 > injectedScript:3
    jQuery 14
    Modal https://www.humhub.com/assets/8ec77900/js/bootstrap.js:957
    Plugin https://www.humhub.com/assets/8ec77900/js/bootstrap.js:1240
    jQuery 2
    Plugin https://www.humhub.com/assets/8ec77900/js/bootstrap.js:1235
    <anonymous> https://www.humhub.com/assets/8ec77900/js/bootstrap.js:1281
    jQuery 2

Your main website devs need to get the word.

What I'm trying to ask is...

I'm curious about the pro edition but I would like more information on the "Spaces Types (categories)" feature, specifically how it differs from the free edition.

Also, is it possible to have sub-spaces and/or share specific data between private spaces?

**Comment by ArchBlood** [comment]
Space Types is just like the name suggests, it gives you the option to not only use the current Spaces but create another tree of "Spaces" under a different name, they all work the same as a normal space, however.

There are no sub-spaces and no sharing of private data from one private space to another, personally, it would defeat the purpose of being private otherwise.

**Comment by ArchBlood** [comment]
> I think that makes sense. So it actually _is_ a tree but a really stunted one :-) in that there are only two levels and potentially a ton of leaves.
> 
> So could I have:
> 
> Space A - private |___ Space B - private |___ Space C - private |___ Space D - private
> 
> where people in B-D have access to A but not to the other spaces on the same level unless they are explicitly given access as for any other space or would B-D have access to everything because they have access to A?
> 
> btw, none of this is documented anywhere that I can find.

You are partly right Space Types is more of a category system where you can create "Spaces" with different names and that's it, everything else is fully Space core

#### Space "Category" A
- Space Name A
- Space Name B
- Space Name C
#### Space "Category" B
- Space A
- Space B
- Space C

And so on, so as mentioned Spaces do not interact with one another in any way, even Spaces that have a different name **_do not_** interact with one another.

I would like to note that no matter what, they're all a **type of Space** and no added functionalities were added like this.

**Comment by michaelh99** [comment]
Thank you.  Seems like it's  a small enough feature that it should be part of the free version.  In my case, it's literally the only reason I'm thinking of upgrading to the pro version.  None of the other features are helpful to our org. Grouping would be helpful but a hierarchy would be more useful.
