### ISSUE TITLE
Apostrophe in a user's first or last name creates bugs

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5348]
### What steps will reproduce the problem?

Change the first name of a user to `David d'Auterive Roberts`:
![image](https://user-images.githubusercontent.com/23310825/136972803-2254b1cc-deec-4f35-83ec-ec3d05dbbeba.png)

Write a message to him (mail module) and tag him in the description:
![image](https://user-images.githubusercontent.com/23310825/136972481-2965b5e6-d562-4206-ab05-2c2320fdfc1e.png)

2 problems:
- The destination user is displayed `David d&#039;Auterive Roberts`
- When tagging, as soon as you start typing the `'` char, you have no result (I think because `’` is automatically changed to `’` while typing)

Now receive an email from him (he replies to your private message): the mail subject is `New message from David d&#039;Auterive Roberts`

### Idea

Perhaps it would be an idea to automatically replace `’` with `’` in first and last name?

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.1

**Comment by luke-** [comment]
@funkycram @Soundwave2142 I have opened three separate issues for this. This is better for tracking & discussion. Thanks!
