### ISSUE TITLE
Privacy Policy and Terms & Conditions acceptance

### ISSUE THREAD

**Issue by mrluisiko99** [humhub/humhub#535]
It is required by many people. Acceptance of cookies is also required to comply with European law. You could add the option to add all this in the Administration in the next update.

Thanks and congratulations for the best software :+1:

**Comment by mrluisiko99** [comment]
No, spanish politicians go for the weakest, because they can not with the most powerful companies. This article of the Cookies Law - http://www.elconfidencial.com/tecnologia/2014-01-24/primera-multa-a-dos-webs-espanolas-por-violar-las-normas-sobre-cookies_80190/ - says: "Una sanción ejemplar... para dos empresas 'insignificantes'" - "An exemplary sanction ... for two 'insignificant' companies"

I have not asked anything from the Spanish law, I only asked that you can activate a warning to adapt to the European law, it could be useful for some people.

**Comment by Felli** [comment]
Not much but you can use [Privacybox](https://github.com/GreenVolume/humhub-modules-privacybox) a hack-ish way of turning the Termsbox into a Privacy Policy module.
