### ISSUE TITLE
Remove `NewMember` widget from Core

### ISSUE THREAD

**Issue by smartens** [humhub/humhub#5352]
### Is your feature request related to a problem? Please describe.

Due to privacy policy, I don't want to show member information to guests on the home page. I can't find any option in the settings to disable this widget. 

### Describe the solution you'd like

I want unregistered users to see only public posts on the home page and the "New Spaces" widget. I would like to have an option in the settings that allows me to disable the "New Members" widget.

### Describe alternatives you've considered

Here https://github.com/humhub/humhub/issues/2057#issuecomment-257550830 is described how to hide the widget through a custom theme. But this is only a hack, because the resource is loaded from the server anyway.

**Comment by luke-** [comment]
Yes, then there is no solution for the module yet.

Of course, it would be best to implement this directly in the module.

**Comment by ArchBlood** [comment]
I personally think that the module itself should be removed and achieved as it's already a part of the core as is, and a configurable flag should be in place to toggle off for those that wish for this not to be displayed, an easy workaround is removing it through theme view overwriting, and adding `if (\Yii::$app->user->isGuest){}` to remove the widget display for guests completely for the module itself, but again, this does not fix any issue when having both the module and the core widget in display at the same time other than the core only shows for the guest whereas the module shows for both so in turn theme view overwriting is needed in this case.

**Comment by luke-** [comment]
Since the "NewMembers" widget is really only used in the guest dashboard, and actually used to be part of the directory, I would remove it completely from the core and rather add some options to the module.

**Comment by ArchBlood** [comment]
@luke- then the same should be done to the Space widget as well shouldn't it? I'm pretty sure that I seen someone create one for this as well and published it on GitHub
