### ISSUE TITLE
Remove deprecated `Directory` module

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5358]

**Comment by luke-** [comment]
@yurabakhtin Thanks for the hint. Are you still create a PR for the Enterprise version? 
Removing the directory is not planned until 1.11 anyway.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/enterprise-theme/pull/17

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by n3wborn** [comment]
Hi

Sorry to reopen this issue but it's the first time I work on humhub and I'm currently working on an old codebase where directory Module was still used. I'm not sure to understand what this was supposed to do at the time it was still available and if this has been replaced by Space Module or not. 

Seeing [this merged PR](https://github.com/humhub/humhub/pull/5177/files#diff-635efd8d462e825a358e2b006c31b9f1a9f2db4c42c689c6f4901eca41011a48) I'd say yes but on the other hand I also see a [Directory section in current Core Modules Config Documentation](https://docs.humhub.org/docs/admin/config-options/#directory). 

If someone could bring light on this I'd be really grateful. Thanks

**Comment by luke-** [comment]
@n3wborn In previous versions there was a main menu item "Directory" which displayed a list of all users and spaces on subpages.

In new versions this menu item does not exist anymore, but there are own spaces and members menu items which are created by the respective user/space modules.
