### ISSUE TITLE
Tags appear blank

### ISSUE THREAD

**Issue by ShrewMaster** [humhub/humhub#5379]
Hello, developers!

Since v1.9.1, our tags appear blank, as you can see from image 1 below. If I click on the tags, or use the search filter with tags, they become visible on the panel (see image 2, top left). This means their properties are conserved. Nonetheless, they remain invisible to users. Any idea what might have caused this issue, and how to fix it?

**Image 1**
![Captura de Ecrã (363)](https://user-images.githubusercontent.com/27917943/138330208-8179e21d-6fb7-462b-83b6-17bfcae7718c.png)

**Image 2**
![Captura de Ecrã (364)_LI](https://user-images.githubusercontent.com/27917943/138330281-d35680d6-0bf7-4dcd-81ca-ef2196936ed9.jpg)

**Comment by ArchBlood** [comment]
Are you using a custom theme, if you are then you will need to update your theme
