### ISSUE TITLE
Incorrect Mail summary & notification with PHP 8

### ISSUE THREAD

**Issue by Reuns** [humhub/humhub#5388]
### What steps will reproduce the problem?
Hi !

I’m trying to update PHP from 7.4.24 to 8.0.11

Everything seems to work great, but the emails are getting weird.
They’re pretty much unreadable.

Thanks for your help.
### What do you get instead?
![image](https://user-images.githubusercontent.com/19529531/138612864-50c6ae61-739c-4c36-a655-67cb63f103fa.png)
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.2
| PHP version | 7.4.24 -> 8.0.11     | 
| Operating system | Linux version 3.10.0-962.3.2.lve1.5.31.el7.x86_64  (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) |

**Comment by Reuns** [comment]
Hello,

what kind of information can I give you to help you out ?
@luke-

**Comment by Reuns** [comment]
The problem occur (at least) on gmail.
I've checked the DB settings : **Utf8mb4_unicode_ci** character set and **InnoDB** Ok !

**Comment by Reuns** [comment]
this is the option available on the server :
![image](https://user-images.githubusercontent.com/19529531/140079109-40875c0f-ae0f-49b0-a2f9-6a2cd3b36ffd.png)
![image](https://user-images.githubusercontent.com/19529531/140079317-fd33cfb6-7deb-4b30-84e2-6f9c8fa388d8.png)

**Comment by ArchBlood** [comment]
See #5244 @luke- this can be closed
