### ISSUE TITLE
installation error: 1.8.latest > 1.9.2

### ISSUE THREAD

**Issue by hj-beckers** [humhub/humhub#5398]
### What steps will reproduce the problem?
installation from 1.8.latest to 1.9.2 Please see the full thread in the community forum (https://community.humhub.com/s/installation-and-setup/?contentId=247458).
### What is the expected result?
a working 1.9.2 installation
### What do you get instead?
The errors as stated in the community forum
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.5?
| PHP version      |  7.4.6
| Operating system | opensuse 15.2

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by hj-beckers** [comment]
No help, no tipps, no answers?

**Comment by yurabakhtin** [comment]
@hj-beckers @luke- Sorry, it was indeed my bug, because here https://github.com/humhub/humhub/commit/ea0757ab747526bf5d8b44d2efa944fc18313133#diff-165768d5264abf499f64dfebc8457418231c40e499429732ec7080f5695eab96R112 I used a static name on my local database.
I have fixed this in PR https://github.com/humhub/humhub/pull/5416.

**Comment by luke-** [comment]
@yurabakhtin Thanks.

@hj-beckers Will be fixed with 1.9.3. Until you can manually replace following files:
https://github.com/humhub/humhub/pull/5416/files

**Comment by hj-beckers** [comment]
I patched the files and executed according to https://docs.humhub.org/docs/admin/updating the steps Flush caches, Database migration and Update installed modules with success. But restarting humhub yields the following error:

Not instantiable – yii\di\NotInstantiableException
Failed to instantiate component or class "humhub\modules\questionanswer\models\Comment".
↵
Caused by: ReflectionException
Class humhub\modules\questionanswer\models\Comment does not exist

in /srv/www/htdocs/humhub/protected/vendor/yiisoft/yii2/di/Container.php at line 508

Background: During the update from 1.8.2 -> 1.8.5 I got an error which IIRC mentioned the above modul. This was solved by restoring 1.8.2 instance and DB, removing some not used modules and restarting the 1.8.5 update, which succeded.

**Comment by hj-beckers** [comment]
Do I have to open a new issue regarding the new problem or do you reopen issue #5398?

Thanks for your help.
Hermann-Josef Beckers

**Comment by hj-beckers** [comment]
According to the table "module_enabled" the modules cfiles, legal, linklist, polls, tasks, updater and wiki are enabled. A directory "questionanswer" can only be found in the protected/runtime/module_backups directory in the humhub backup directories I made before trying the update(s). It has a time stamp in unix seconds of the time when I removed the modules before the 1.8.5 update. In the active humhub a directory "questionanswer" can not be found.

**Comment by luke-** [comment]
I would either try installing the "QuestionAnswer" module again, apparently the uninstall did not work correctly. Maybe you can contact the developer?

Otherwise you can run the IntegrityChecker from HumHub to clean the database from invalid entries.
https://docs.humhub.org/docs/admin/troubleshooting#data-integrity

**Comment by hj-beckers** [comment]
Thanks.

Using the IntegrityChecker helped:

…
Deleting activity id 910 without existing target! (humhub\modules\user\models\Follow) (yes|no) [no]:yes
Validating: File Module (46 entries)
Validating: Content Objects (2511 entries)
Deleting content id 1032 of type humhub\modules\questionanswer\models\Comment without valid content object! (yes|no) [no]:yes
Deleting content id 1033 of type humhub\modules\questionanswer\models\Comment without valid content object! (yes|no) [no]:yes
Validating: Space Module - Spaces (27 entries)
…

Yours
Hermann-Josef Beckers
