### ISSUE TITLE
Humhub 1.10 beta 1 : the gender field returns null value and make crash the administration

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5408]
### What steps will reproduce the problem?

The gender profile field is visible, editable and shown in the search results.
Create an admin user and do not select any gender in the profile.
Go to Administration -> Users

### What do you get?

![image](https://user-images.githubusercontent.com/23310825/139664406-e8c58311-185e-47af-a271-bbc582725004.png)

TypeError: humhub\modules\user\models\ProfileField::getUserValue(): Return value must be of type string, null returned in /var/www/humhub-jdn/protected/humhub/modules/user/models/ProfileField.php:313
Stack trace:
#0 /var/www/humhub-jdn/protected/humhub/modules/user/models/Profile.php(341): humhub\modules\user\models\ProfileField->getUserValue()
#1 /var/www/humhub-jdn/protected/humhub/modules/user/models/User.php(737): humhub\modules\user\models\Profile->getProfileFields()
#2 /var/www/humhub-jdn/themes/enterprise-jdn/views/ui/menu/widgets/views/left-navigation.php(15): humhub\modules\user\models\User->getSearchAttributes()
#3 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#4 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#5 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#6 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\base\View->render()
#7 /var/www/humhub-jdn/protected/humhub/modules/ui/menu/widgets/Menu.php(91): yii\base\Widget->render()
#8 /var/www/humhub-jdn/protected/humhub/components/Widget.php(63): humhub\modules\ui\menu\widgets\Menu->run()
#9 /var/www/humhub-jdn/protected/humhub/modules/admin/views/layouts/main.php(10): humhub\components\Widget::widget()
#10 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#11 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#12 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/widgets/ContentDecorator.php(79): yii\base\View->renderFile()
#13 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/Widget.php(110): yii\widgets\ContentDecorator->run()
#14 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/View.php(526): yii\base\Widget::end()
#15 /var/www/humhub-jdn/protected/humhub/modules/admin/views/layouts/user.php(10): yii\base\View->endContent()
#16 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#17 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#18 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#19 /var/www/humhub-jdn/protected/humhub/components/Controller.php(125): yii\base\View->render()
#20 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/Controller.php(411): humhub\components\Controller->renderContent()
#21 /var/www/humhub-jdn/protected/humhub/modules/admin/controllers/UserController.php(90): yii\base\Controller->render()
#22 [internal function]: humhub\modules\admin\controllers\UserController->actionList()
#23 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#24 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#25 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#26 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#27 /var/www/humhub-jdn/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#28 /var/www/humhub-jdn/index.php(25): yii\base\Application->run()
#29 {main}

### Additional info

If I remove `: string` at the end of the line of the `getUserValue` the problem is solved.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10 beta 1

**Comment by funkycram** [comment]
Sorry, I haven't seen https://github.com/humhub/humhub/pull/5401

**Comment by luke-** [comment]
@funkycram If the fix doesn't work for you, please reopen!

**Comment by funkycram** [comment]
I was able to try it and it works.
