### ISSUE TITLE
Full translate RU

### ISSUE THREAD

**Issue by Stalker-X** [humhub/humhub#541]
Hello!
I was full translated humhub to RU at my local server.
How can I send translate to community and if I update humhub to new version will I lost it?

**Comment by KarelWintersky** [comment]
@daglex 
> милости просим в русскоязычную ветку http://translate.humhub.org.
не вижу ветки.
А ошибки в переводе вижу. Ошибки, опечатки, типично-программерские высказывания с обилием запятых.
