### ISSUE TITLE
Humhub 1.10 beta 1: Profile About Field causes »An internal server error occurred.«

### ISSUE THREAD

**Issue by smashm** [humhub/humhub#5414]
### What steps will reproduce the problem?

Try to open the about site on a member profile.
You get this error:
![Bildschirmfoto 2021-11-02 um 11 13 20](https://user-images.githubusercontent.com/60502320/139828990-fe90df2e-f527-4673-9aff-02634da29cf2.png)

The error is reducible and also concerns the HumHub Community. (Screenshot is from Luke's profile.)

| HumHub version   | 1.10 beta 1

**Comment by luke-** [comment]
Shoulkd be fixed in beta.2
