### ISSUE TITLE
Custom defaultRoute

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#5415]
Also refer:
-  to this old thread: [redirect to a custom page #1915](https://github.com/humhub/humhub/issues/1915#issue-170083604)
-  to this page [https://www.yiiframework.com/doc/guide/2.0/en/runtime-routing#default-route](https://www.yiiframework.com/doc/guide/2.0/en/runtime-routing#default-route)

In `config/web.php` if I add:

 `'defaultRoute' => 'space/spaces',` **it works !** redirection to spaces page OK
 `'defaultRoute' => 'user/people',` **it works !** redirection to users page OK

but if I add:

 `'defaultRoute' => 'space/space/caeab114-e494-4039-a249-c28b4121cd61',` it does **NOT** work ?
 `'defaultRoute' => 'custom_pages/1',` it does **NOT** work ?

Please, where is the trick ?

**Comment by luke-** [comment]
Did you tried a real url?

**Comment by Gilbertdelyon** [comment]
Hello Luke,
What do you mean by real URL?

The Custom page "id=2" exists, it is a 100% public page
![image](https://user-images.githubusercontent.com/91057837/139862967-d7612800-53b2-42f5-9941-830d02aec930.png)


In my `web.php`:
![image](https://user-images.githubusercontent.com/91057837/139861918-f2baa5de-7683-4daf-a14c-75ca47b924f3.png)

in navigator:
![image](https://user-images.githubusercontent.com/91057837/139862413-53618571-cb5d-454c-9297-80594459cda7.png)

If by  "real URL" you mean the URL as displayed in navigator, please notice that I get the same result with:
'defaultRoute' => 'custom_pages/view/2',
'defaultRoute' => 'custom_pages%2Fview&id=2',
'defaultRoute' => 'index.php?r=custom_pages%2Fview&id=2',
'defaultRoute' => 'http://humhub192/index.php?r=custom_pages%2Fview&id=2',

So I worry if I have to specify the defaultRoute on a another way, or if it is not possible to specify a particular custm page or particular space as defaultRoute.

**Comment by luke-** [comment]
I've added an example for a custom page home page here:
https://community.humhub.com/s/installation-and-setup/wiki/page/view?title=Change+Homepage

**Comment by Gilbertdelyon** [comment]
Thank you Luke, but this is what  I get

**Comment by Gilbertdelyon** [comment]
Thank you Luke, It works !

**Comment by Lx** [comment]
> I've added an example for a custom page home page here: https://community.humhub.com/s/installation-and-setup/wiki/page/view?title=Change+Homepage

That URL now generates an internal server error.  The updated URL is:

https://community.humhub.com/s/installation-and-setup/wiki/35/Change+Homepage

and for posterity, the current content of that page is:

---

You can change the homepage in the configuration file: `protected/config/web.php`

**Example:**

```
<?php

return [
   'homeUrl' => '/s/some-space/',
];
```

**Example (Custom Page):**\
\`\`\`

```
<?php

return [
   'homeUrl' => ['/custom_pages/view/view', 'id' => 2],
];
```

Or you can use the [Homepage module](https://marketplace.humhub.com/module/homepage/description) to create landing pages for guests, registered users, or members of specific groups.

The [Menu Manager module](https://marketplace.humhub.com/module/menu-manager/description) allows adding a “Home” item on the top menu.
