### ISSUE TITLE
Profile field search not appears

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#5422]
### What steps will reproduce the problem?
When i come to the people page, profile fields search doesnt appears to me. Only: search, sort, status and resert filter.

### What is the expected result?
Profile fields search.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.2
| PHP version      |  7.3
| Operating system | 

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by smashm** [comment]
What do you mean with »profile fields search«? 

If you have the search field, it also searches the profile fields.

![Bildschirmfoto 2021-11-09 um 13 12 07](https://user-images.githubusercontent.com/60502320/140954987-c8d45d4a-caa9-4361-b670-8b07a9510bcf.png)
