### ISSUE TITLE
Topics added to a post does not appear correctly

### ISSUE THREAD

**Issue by minettesunet** [humhub/humhub#5425]
![2021-11-11_12-53-51](https://user-images.githubusercontent.com/94115743/141294532-331e21f0-83fe-4b6b-abb2-8622e68134f6.png)
When adding a topic to a post, the only thing that is visible is a white button. It seems like the text for the topic is missing. A bug?

**Comment by ArchBlood** [comment]
It is probably due to a custom theme that hasn't been recompiled as I've not seen any issues with the current stable nor the beta themes when it comes to the Topics core function.

**Comment by minettesunet** [comment]
> It is probably due to a custom theme that hasn't been recompiled as I've not seen any issues with the current stable nor the beta themes when it comes to the Topics core function.

Yes that solved the problem, thanks!
