### ISSUE TITLE
Deep Links to Single Comment

### ISSUE THREAD

**Issue by OxyFuse** [humhub/humhub#5427]
### What steps will reproduce the problem?
Click on a `comment` activity from the Latest Activity widget, such as https://community.humhub.com/s/general-discussion/?contentId=248085&commentId=39640

Or you can also open it through the comment permalink. Make sure that the comment you try to open is from the collpased comments.

### What is the expected result?
It should expand the collapsed comments and highlight the target single comment.

### What do you get instead?
It just open the permalink and the single comment is still hidden in the collpased comments.

### Additional info
It will only happened if the post has many comments and the single comment was collapsed/hidden.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10 Beta 1
| PHP version      |  8.0

**Comment by luke-** [comment]
Also to be considered: Nested discussions where the permalink goes to a subcomment.

**Comment by yurabakhtin** [comment]
@luke- Yes, I can reproduce the issue on the post https://community.humhub.com/s/general-discussion/?contentId=248085&commentId=39640, but locally on `develop` branch (1.10.0-beta.2 (November 12, 2021)) it works well:

<img width="858" alt="deep_comment_link" src="https://user-images.githubusercontent.com/6995524/142807720-1486a7aa-23ee-4cf4-99ab-0bca780bc940.png">

Maybe there is old version?

**Comment by luke-** [comment]
Just updaated to the latest version @Community
Can you please try again?

**Comment by yurabakhtin** [comment]
@luke- It still does work there, ok I will review the code again in order to understand how to reproduce this bug.

**Comment by yurabakhtin** [comment]
@luke- The problem was in enabled caching. I fixed this in PR https://github.com/humhub/humhub/pull/5438.

**Comment by luke-** [comment]
@yurabakhtin Perfect, thanks for the fix. The bugfix was important for the stable 1.10 release!
