### ISSUE TITLE
commentsPreviewMax for Permalink

### ISSUE THREAD

**Issue by OxyFuse** [humhub/humhub#5429]
### Is your feature request related to a problem? Please describe.
No.

### Describe the solution you'd like
The `commentsPreviewMax` option are the same for both in Stream Posts and when viewing the permalink of a post. It would be nice if there is a different option, let's say  `commentsPermalinkPreviewMax`, that determines the maximum initial comments to show in post permalink.

For example, when viewing the Stream Posts, there will be only 2 (_default_) comments to show. And when I open the permalink of a post, it will initially show 30 comments or whatever is set in `commentsPermalinkPreviewMax`.

**Comment by luke-** [comment]
@OxyFuse Something like that is already planned here. 

Please reopen this issue if it does not apply.
https://github.com/humhub/humhub/issues/3442
