### ISSUE TITLE
mobile theme for phones and tablets

### ISSUE THREAD

**Issue by dimontajik** [humhub/humhub#543]
propose to make mobile theme for phones and tablets, the cat has finished pattern should be optimized for mobile devices
![a1ade90b02b7e153e34aa71d9837c607](https://cloud.githubusercontent.com/assets/10101408/5526485/2cd61c84-8a1e-11e4-9185-b93ca73abd84.png)

**Comment by luke-** [comment]
You could create module for that.

E.g. you can catch the beforeRender / onInit of Controller and switch the theme
