### ISSUE TITLE
Cannot upload a document

### ISSUE THREAD

**Issue by libanAKG** [humhub/humhub#5440]
### What steps will reproduce the problem?
Trying to upload a document.

### What is the expected result?

Successful upload of a document. 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.2
| PHP version      |  7.3.27-1~deb10u1
| Operating system | Ubuntu

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

ERROR  Tue, 23 Nov 2021 19:48:43 			 yii\base\UnknownPropertyException

yii\base\UnknownPropertyException: Setting unknown property: tracker\models\Document::access_for_all in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php:210
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set('access_for_all', '0')
#1 /var/www/humhub/protected/modules/tracker_issue/controllers/services/DocumentCreator.php(97): yii\db\BaseActiveRecord->__set('access_for_all', '0')
#2 /var/www/humhub/protected/modules/tracker_issue/controllers/DocumentController.php(99): tracker\controllers\services\DocumentCreator->create()
#3 [internal function]: tracker\controllers\DocumentController->actionCreate()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('create', Array)
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('tracker-issues/...', Array)
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#9 /var/www/humhub/index.php(25): yii\base\Application->run()
#10 {main}

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Please open a issue here: https://github.com/githubjeka/tracker-issues

**Comment by ArchBlood** [comment]
> Please open a issue here: https://github.com/githubjeka/tracker-issues

Already made apparently https://github.com/githubjeka/tracker-issues/issues/48

**Comment by ChilliPipper** [comment]
> > Please open a issue here: https://github.com/githubjeka/tracker-issues
> 
> Already made apparently [githubjeka/tracker-issues#48](https://github.com/githubjeka/tracker-issues/issues/48)

Yes, i opened it ! Same error, couldn't find a solution by my own yet, and apparently there's nothing on the web
