### ISSUE TITLE
Comments aren't displayed anymore

### ISSUE THREAD

**Issue by Reuns** [humhub/humhub#5447]
### What steps will reproduce the problem?
Update from 1.9.3 to 1.10.0
Comment a post.
Reload the page.
Comment count is good, but comments aren't displayed.

### What is the expected result?
The comments should be displayed

### What do you get instead?
No comments available

### Additional info
I can see comments made before the upgrade.
But the new comments doesn't work properly.

- There are no errors since the upgrade to 1.10.0
- Upgrade done with HumHub updater
- All modules are up-to-date
- Search / rebuild : done
- Integrity check : done

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.0
| PHP version      | 7.4 AND 8.0

**Comment by smashm** [comment]
I can't reproduce that with PHP 7.4 (8 not tested). 
Two hints: 
• I have made a habit of clearing the PHP cache after updates, because the display has spun more often. (Browser cache clearing could also be helpful) -> admin menu/settings/advanced/caching
• Do you use an own theme? -> Better rebuild it

**Comment by Reuns** [comment]
I knew I was forgetting something : clearing the cache !
Thanks for the reminder, but it still doesn't work...

I'm using default theme. No tweak.

**Comment by luke-** [comment]
Can you please try to flush your browser cache?

**Comment by TorWaG77** [comment]
We have the same problem. After clearing the php-Cache the comments are visible, but new comments are hidden again until I clear the cache again. I see the same problem in the Community-Forum (i.e. https://community.humhub.com/content/perma?id=249052 cannot see my own comment)

**Comment by luke-** [comment]
Fixed here: https://github.com/humhub/humhub/pull/5448
