### ISSUE TITLE
Not yet approved user is reported in Activities as joining a space

### ISSUE THREAD

**Issue by acinelli** [humhub/humhub#545]
Setting:  
New Users are automatically placed in "Users" group, and also in "Welcome Space", with "Require group admin approval after registration" enabled in Admin -> Authentication.

Before the group admin approves the new user registration, this pre-approved user shows up in the "Latest Activities" as joining the "Welcome Space" at the time of initial registration request (though not approved yet).

Nothing should show up in "Latest Activities" while a user is still waiting for approval.

**Comment by luke-** [comment]
Fixed in upcoming 0.11
