### ISSUE TITLE
Fail2ban configuration help

### ISSUE THREAD

**Issue by gfontaniere** [humhub/humhub#5454]
### How to configure Fail2Ban ?

Please, could you help me to configure fail2ban for Humhub ?

- jail.d/defaults-debian.conf
- filter.d/humhub.conf

Thank you.

**Comment by ArchBlood** [comment]
You should either speak to the developers of fail2ban or use the community site for help such as this.

**Comment by gfontaniere** [comment]
> ### How to configure Fail2Ban ?
> Please, could you help me to configure fail2ban for Humhub ?
> 
> * jail.d/defaults-debian.conf
> * filter.d/humhub.conf
> 
> Thank you.

OK. Thank you very much.
