### ISSUE TITLE
Comment notification should contain to the comment link and not the content link

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5457]
### Is your feature request related to a problem? Please describe.

On new comment notification, if you click on "Show online", you are redirected to the content.

### Describe the solution you'd like

On Humhub 1.10, with the new comments permalinks, it would be possible for the "Show online" button to redirect you directly on the comment.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5464.

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by funkycram** [comment]
Great! Thanks @yurabakhtin
