### ISSUE TITLE
htaccess Broken by v1.10

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#5466]
After upgrading from v1.9.2 to v1.10.2, the installation is no longer accessible through the web server.

According to the new .htaccess.dist

```
    # uncomment if using the AssetManager::linkAssets option
    #Options +FollowSymLinks
```

Unfortunately, Apache's mod_rewrite will not honor any RewriteRule directive unless the FollowSymLinks option is enabled.  This has nothing to do with HumHub options.

The workaround would seem to be explicitly enabling FollowSymLinks at the site level to avoid this .htaccess.dist failing to do so.

**Comment by luke-** [comment]
Thanks for the info.

I would then simply remove the two lines. And if someone wants to use the "LinkAssets" option (very rare case), he has to decide himself how to configure the webserver?

**Comment by miqrogroove** [comment]
It's the other way around.  The `Options +FollowSymLinks` needs to be un-commented, else the server has to be configured for this at a higher level.  With that option missing, mod_rewrite fails and the site is not accessible.

**Comment by luke-** [comment]
Did I understand it correctly that `Options +FollowSymLinks" should be always uncommented,because "mod_rewrite" requires it?

**Comment by miqrogroove** [comment]
Quoted from

https://httpd.apache.org/docs/current/mod/mod_rewrite.html

> The rewrite engine may be used in .htaccess files and in <Directory> sections, with some additional complexity.
> To enable the rewrite engine in this context, you need to set "RewriteEngine On" and "Options FollowSymLinks" must be enabled. If your administrator has disabled override of FollowSymLinks for a user's directory, then you cannot use the rewrite engine. This restriction is required for security reasons.

**Comment by luke-** [comment]
@miqrogroove Oh ok, thanks for the hint!
Fixed here: https://github.com/humhub/humhub/commit/e63d6b5e4cbd7ab5cfb40a6f047017ffa4c12164
