### ISSUE TITLE
CR: Using the @ symbol with no Latin logins

### ISSUE THREAD

**Issue by daglex** [humhub/humhub#547]
I would like to be able to use the @ symbol positions with Cyrillic logins, not only in Latin. This can be done for the next release? 

For example to send a private message in the general post by the symbol @Cyrillic_Login

**Comment by daglex** [comment]
My question is clear?

**Comment by daglex** [comment]
Please answer this very important if my question is not clear, I will formulate it differently.

**Comment by luke-** [comment]
Sorry, I don't get it.

**Comment by daglex** [comment]
What information do you need? Can I help?

**Comment by luke-** [comment]
Can you please give an example?

**Comment by daglex** [comment]
For example, porobujte add the @ symbol and add the nickname or name of space in Russian, it does not find the user and space, because it works only with Latin characters.

**Comment by daglex** [comment]
We want this to be possible, and with Cyrillic logins.

**Comment by daglex** [comment]
You need to edit the file \protected\widgets\views\heditor.php
regexp = new RegExp(flag + '([A-Za-zА-яа-я0-9_\\s\+\-\]*)$', 'gi');

**Comment by luke-** [comment]
Fixed
