### ISSUE TITLE
Pending approval page: add grouped actions and custom columns

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5471]
Original discussion: https://community.humhub.com/content/perma?id=249489
Since Andreas offers to pay me to make this improvement, I can offer a PR.

### Is your feature request related to a problem? Please describe.

1. For manual approvals of new users via the "Approval Pending" page, there are many clicks to be made.
2. It takes time to see the profile fields of each user to approve

### Describe the solution you'd like

In the ["Approval Pending" page](https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/admin/views/approval/index.php), add:
- A column with checkbox
- An action dropdown field to approve or decline the users checked
- A “Screen options” button enabling to add some profile fields values as additional columns

I was inspired by Wordpress administration (see the "Bulk actions" dropdown):

![image](https://user-images.githubusercontent.com/23310825/145670770-4d46c457-da1d-41ba-bece-04e788bdfb3e.png)

![image](https://user-images.githubusercontent.com/23310825/145670785-05b745b6-0494-49fc-8b9d-0f70469a1db8.png)

### Describe alternatives you've considered

If the "Screen options" is not relevant, forget it and it is possible to add columns erasing the [index.php](https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/admin/views/approval/index.php) file with a custom theme.

**Comment by funkycram** [comment]
@luke- When the approval (or decline) form is shown, as the mail subject and message is in the language of the user, on the form when approving multiple users at the same time, I should theoretically show 2 fields by users (subject + message ; e.g. 20 fields for 10 users to approve).
This is impractical if the admin wants to customize the message.

Should I show only 2 fields (subject + message) in the langage of the default language platform (or admin language if not set)?

**Comment by luke-** [comment]
@funkycram  Good question. What do you think about only being able to define an individual Approval/Decline message when enabling users individually?  Then in Bulk Mode, you could simply send the default message for all users in the respective language.

What do you think about that?

**Comment by funkycram** [comment]
As the messages texts can be customized in `protected/config/messages`, I think it is indeed the best option. Thanks.

**Comment by funkycram** [comment]
@luke- What do you think about this proposal?

![image](https://user-images.githubusercontent.com/23310825/146184452-e871e90d-45c1-490f-a156-736a5452b32b.png)

![image](https://user-images.githubusercontent.com/23310825/146184819-45b38c4e-03fb-4ad6-b9d7-38aac8fa3bbc.png)

![image](https://user-images.githubusercontent.com/23310825/146184523-41c9f6ac-0f88-401c-ae29-5cf2822f7767.png)

![image](https://user-images.githubusercontent.com/23310825/146184620-fed7b281-5de3-40a5-a3f7-a40999e98f80.png)

![image](https://user-images.githubusercontent.com/23310825/146185002-652a7f9e-7867-4d87-bdd9-672827484fcc.png)

**Comment by smashm** [comment]
Looks very well. In the screenshot it is a bit unclear, but isn't it useful to limit the selection of the screenoptions to the (for registration) _required_ fields only?

**Comment by funkycram** [comment]
Yes, you're right @smashm . I would say the "Show at registration" (and not only required).

**Comment by luke-** [comment]
@funkycram Yeah, looks nice. 

Maybe we could combine the buttons here
![image](https://user-images.githubusercontent.com/4736168/146531361-6b302131-6b09-4066-bdfa-5692ee1d9cae.png)
Into one dropdown, like here:
![image](https://user-images.githubusercontent.com/4736168/146531514-0e8a76e3-a510-4e00-a6bb-9e958b0161b6.png)
to save Space for user Information?

@orangiene Maybe you can also take a look?

**Comment by funkycram** [comment]
In a way it indeed save space, in an other, you need 2 clics to approve an individual user.
Maybe should I combine the buttons only when some profile fields are selected in the screen options?

**Comment by orangiene** [comment]
![pending-approvals](https://user-images.githubusercontent.com/62644500/146960030-6bb16fd3-6f9d-4c5e-8b9a-904aa7902c3f.jpg)
![pending-approvals-2](https://user-images.githubusercontent.com/62644500/146960039-2fd6d691-3fa7-46c6-bd69-ed18a7306b4a.jpg)

Hi all, what do you think about this?

**Comment by funkycram** [comment]
Great ideas @orangiene, thanks! I will integrate them.

**Comment by funkycram** [comment]
@luke- see #5488

**Comment by luke-** [comment]
@funkycram Great thanks!

**Comment by luke-** [comment]
@funkycram Thank you, it is merged. I have made a few minor changes. 

The translations are now also maintainable on our translation site.

**Comment by funkycram** [comment]
Thanks a lot @luke- for your commit https://github.com/humhub/humhub/commit/f6659136e028e17b9d4e5506176ab1513e510389
Translations have been done.
