### ISSUE TITLE
Prevent Specific Usernames

### ISSUE THREAD

**Issue by r007ops** [humhub/humhub#5475]
I've done some searching and don't seem to beable to find this anywhere.

I would like to prevent certain usernames from being used on my site withoutbhaving to register them all myself.
E.g. I want to stop admin, administrator, hhadmin, hhadministrator, root, etc,

Are there ny plans for such a feature and if not, ca I please recinnnd it

TYVM akk!

**Comment by luke-** [comment]
It would probably be easiest to first add an array variable `$forbiddenUsernames` here, in which individually forbidden user names can be set via the configuration file.

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/Module.php#L140

**Comment by vsemradu** [comment]
Branch: enh/5475

**Comment by luke-** [comment]
@vsemradu Thanks, please see my review

**Comment by luke-** [comment]
@Semir1212 Currently "You cannot use this username.'" is the error message
