### ISSUE TITLE
A non member of a private space do not have the "unauthorized" message in some pages

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5479]
### What steps will reproduce the problem?

With an account that is not member of a private space, directly go to the URL:
http://humhub.tdl/s/private-space/space/manage

And, if the calendar module is activated, go to:
http://humhub.tdl/s/private-space/calendar/container-config

### What is the expected result?

You should have the message "You are not allowed to do this action"

### What do you get instead?

The page crashes.

It happens for all controllers that extends `ContentContainerController` and having a rule access. E.g.:
```
    public function getAccessRules()
    {
        return [
          ['permission' => [ManageSpaces::class]]
        ];
    }
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.2
| PHP version      | 7.4 and 8.0
| Operating system | Ubuntu

#### Error for http://humhub.tdl/s/private-space/space/manage

Error: Call to a member function getUserGroup() on null in /var/www/hhdev/protected/humhub/modules/content/components/UserGroupAccessValidator.php:55
Stack trace:
#0 /var/www/hhdev/protected/humhub/components/access/ActionAccessValidator.php(47): humhub\modules\content\components\UserGroupAccessValidator->validate()
#1 /var/www/hhdev/protected/humhub/components/access/ControllerAccess.php(373): humhub\components\access\ActionAccessValidator->run()
#2 /var/www/hhdev/protected/humhub/components/behaviors/AccessControl.php(149): humhub\components\access\ControllerAccess->run()
#3 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/ActionFilter.php(77): humhub\components\behaviors\AccessControl->beforeAction()
#4 [internal function]: yii\base\ActionFilter->beforeFilter()
#5 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Component.php(628): call_user_func()
#6 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Controller.php(300): yii\base\Component->trigger()
#7 /var/www/hhdev/protected/vendor/yiisoft/yii2/web/Controller.php(207): yii\base\Controller->beforeAction()
#8 /var/www/hhdev/protected/humhub/components/Controller.php(191): yii\web\Controller->beforeAction()
#9 /var/www/hhdev/protected/humhub/modules/content/components/ContentContainerController.php(101): humhub\components\Controller->beforeAction()
#10 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Controller.php(179): humhub\modules\content\components\ContentContainerController->beforeAction()
#11 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#12 /var/www/hhdev/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#13 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#14 /var/www/hhdev/index.php(25): yii\base\Application->run()
#15 {main}

#### Error for http://humhub.tdl/s/private-space/calendar/container-config

Error: Call to a member function can() on null in /var/www/hhdev/protected/humhub/modules/content/components/ContentContainerPermissionAccess.php:30
Stack trace:
#0 /var/www/hhdev/protected/humhub/components/access/PermissionAccessValidator.php(27): humhub\modules\content\components\ContentContainerPermissionAccess->verifyPermission()
#1 /var/www/hhdev/protected/humhub/components/access/ActionAccessValidator.php(47): humhub\components\access\PermissionAccessValidator->validate()
#2 /var/www/hhdev/protected/humhub/components/access/ControllerAccess.php(373): humhub\components\access\ActionAccessValidator->run()
#3 /var/www/hhdev/protected/humhub/components/behaviors/AccessControl.php(149): humhub\components\access\ControllerAccess->run()
#4 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/ActionFilter.php(77): humhub\components\behaviors\AccessControl->beforeAction()
#5 [internal function]: yii\base\ActionFilter->beforeFilter()
#6 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Component.php(628): call_user_func()
#7 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Controller.php(300): yii\base\Component->trigger()
#8 /var/www/hhdev/protected/vendor/yiisoft/yii2/web/Controller.php(207): yii\base\Controller->beforeAction()
#9 /var/www/hhdev/protected/humhub/components/Controller.php(191): yii\web\Controller->beforeAction()
#10 /var/www/hhdev/protected/humhub/modules/content/components/ContentContainerController.php(101): humhub\components\Controller->beforeAction()
#11 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Controller.php(179): humhub\modules\content\components\ContentContainerController->beforeAction()
#12 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#13 /var/www/hhdev/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#14 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#15 /var/www/hhdev/index.php(25): yii\base\Application->run()
#16 {main}

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5483.

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by funkycram** [comment]
Great, thanks !
