### ISSUE TITLE
Add Admin, User Privacy Settings - Profile Display of Follow, Space Info

### ISSUE THREAD

**Issue by tcinelli** [humhub/humhub#548]
I'm working on adding the ability to hide / display Follower, Following, and Space info on a User's profile (including associated widgets).  Admin can set default Privacy settings to show, hide this info on a user's profile, also allowing a user to override this default setting.

The default settings represent the current look and feel of humhub, displaying all info by default.

**Comment by acinelli** [comment]
:+1:
