### ISSUE TITLE
Enable using grid view pagination in modal box

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5482]
### Is your feature request related to a problem? Please describe.

If you have a grid view in a modal box, when clicking on an other page (in the pagination bar), the page will reload but not in the modal box.
![image](https://user-images.githubusercontent.com/23310825/147381373-154d51d0-24e0-4649-ad2a-950ca4a3ea0e.png)

### Describe the solution you'd like

You should stay in the modal box.

An easy solution would be to add this to https://github.com/humhub/humhub/blob/develop/protected/humhub/widgets/GridView.php (I can do a PR for that):
```
    /**
     * Should be true in a modal box
     * @var bool 
     */
    public $ajaxLinkPager = false;

    /**
     * @inerhitdoc 
     */
    public function renderPager()
    {
        if ($this->ajaxLinkPager) {
            return  AjaxLinkPager::widget(['pagination' => $this->dataProvider->getPagination()]);
        }
        return parent::renderPager();
    }
```

## Alternative

Create this class:
```
use humhub\widgets\AjaxLinkPager;
use humhub\widgets\GridView;

class GridViewModal extends GridView
{
    /**
     * @inerhitdoc 
     */
    public function renderPager()
    {
        return AjaxLinkPager::widget(['pagination' => $this->dataProvider->getPagination()]);
    }
}
```

**Comment by luke-** [comment]
@funkycram Did you tried, following:

```
   <?= GridView::widget([
              'pager' => ['class' => AjaxLinkPager::class]
              'dataProvider' => ...
   ]); ?>
```

If this work, we could add a `modalMode` which automatically add this Pager.
