### ISSUE TITLE
Dashboard for modle "jitsi meet"

### ISSUE THREAD

**Issue by RoundAboutWEB** [humhub/humhub#5487]
The module "jitsi meet" is missing several important functions, so you need additional platforms like "https://jitsi-admin.de/room/dashboard", which makes the module superfluous again.

Cool would therefore be a management of appointments for users, as well as permanent appointments and the invitation of external (no HumHub users).

**Comment by luke-** [comment]
@RoundAboutWEB Please open the issue in the Module Repo: https://github.com/humhub-contrib/jitsi-meet
