### ISSUE TITLE
`People` and `Spaces` not visible for guests

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5492]
### Is your feature request related to a problem? Please describe.

When guest access is enabled, the 'Spaces' and 'Members' pages are never visible.

### Describe the solution you'd like

It would be good to have a setting whether these pages are visible.

By default `Spaces` should be visible and `Members` not.

### Describe alternatives you've considered

-

**Comment by ArchBlood** [comment]
I might have some time later today to test some things out when it comes to this issue, as @GreenMeteor has been getting a lot of requests for this change. :thinking:

**Comment by donni106** [comment]
Is this about the pages `/directory/spaces` and `/directory/members`?

**Comment by luke-** [comment]
Yes
