### ISSUE TITLE
Adjust style of the new Post form

### ISSUE THREAD

**Issue by orangiene** [humhub/humhub#5493]
![image](https://user-images.githubusercontent.com/62644500/149176440-28b1f59c-32dd-4644-9b5b-89792fd45116.png)

**Comment by orangiene** [comment]
![image](https://user-images.githubusercontent.com/62644500/149176615-0884b957-0855-45c5-9021-fcead34ad5c8.png)

![image](https://user-images.githubusercontent.com/62644500/149176662-2a5ff038-ebed-4888-9bc3-20d51287c9db.png)

![image](https://user-images.githubusercontent.com/62644500/149176695-ad59ee6d-9e13-4c39-bb5e-659b6e40aed3.png)

**Comment by luke-** [comment]
@orangiene Can you add a screenshot of the initial state. Without the buttons?

**Comment by orangiene** [comment]
![New post menu #177-initial](https://user-images.githubusercontent.com/62644500/149180468-b49ddfba-ce36-4a41-9bce-ee2eb202956b.jpg)
