### ISSUE TITLE
OEmbed for Facebook, Twitter..

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#5494]
As is currently the case with e.g. YouTube, oEmbed links should also be available for other common networks by default (e.g. Facebook, Twitter, Instagram). 

![image](https://user-images.githubusercontent.com/38326726/149188194-33c41528-0d44-4eca-be08-f08cc092ca07.png)

**Comment by luke-** [comment]
We should also add migrations for existing installations...
