### ISSUE TITLE
Search Doesn't Show Private Posts Except in Spaces

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#5495]
I was trying to use the search feature on my site today and couldn't find my own post no matter what keywords I used.  As I fiddled around with it more, I realized every result from the search feature is marked public.

Edit: Private visibility posts from Space Streams will show up.  For some reason this bug is only affecting User Streams.  This might be a friendship bug.

**Comment by luke-** [comment]
Can you please provide steps to reproduce? I can find Private Space content.

**Comment by miqrogroove** [comment]
Ah, I can confirm that.  I didn't realize this was behaving differently for Spaces and Users.  Top post edited.

To reproduce, try putting a private post on your own profile, as well as a post on a friend's profile stream (friending enabled). 
 Neither post will ever shows up in search results.  Stream display and filters are not affected, just search results.

**Comment by miqrogroove** [comment]
Any luck with this?

**Comment by miqrogroove** [comment]
Steps...

![screen1](https://user-images.githubusercontent.com/1371835/153088559-f6541c61-be4e-405c-8c9c-a6445cb2398e.jpg)
![screen2](https://user-images.githubusercontent.com/1371835/153088560-74122206-9a34-42a6-8311-b43244466636.jpg)

**Comment by miqrogroove** [comment]
Same bug confirmed in v1.11.1.  This bug is top of my wishlist because my site is old enough that I need to search for things sometimes.

**Comment by miqrogroove** [comment]
This bug was fixed in a recent release.  Tested and working on v1.16.1.
