### ISSUE TITLE
Add an option to disable the login form

### ISSUE THREAD

**Issue by azmeuk** [humhub/humhub#5497]
Hi. I use [yii2-authclient](https://github.com/yiisoft/yii2-authclient) to authenticate my users, and this is the only authentication method I want to use.
I find it confusing that users see two different authentication methods on the login page (the regular login/password form, and the "connect with OpenID Connect" button yii2-authclient adds). So I would love a configuration option that could allow me to disable this form:

https://github.com/humhub/humhub/blob/6a8d8e3fbfe272e81381694743324cefc2830a84/protected/humhub/modules/user/views/auth/login.php#L47

If it is OK with you, I volunteer to provide a patch. What do you think?

**Comment by luke-** [comment]
In our SAML SSO we have an option that the user is redirected directly to the SAML provider without seeing the login page.

Would this also be an option for you? Or do you like to show the login page anyway?

**Comment by azmeuk** [comment]
That would totally be an option. To properly skip the login screen was what I was looking for in the first place :)

**Comment by luke-** [comment]
@azmeuk You can try to add following block to your `\protected\¢onfig\web.php`:

```php
    //...
    'container' => [
        'definitions' => [
            \humhub\modules\user\controllers\AuthController::class => [
                'on beforeAction' => function ($e) {
                    if ($e->action->id === 'login' && Yii::$app->request->isGet && empty(Yii::$app->request->get('noRedirect'))) {
                        $e->isValid = false;
                        Yii::$app->response->redirect(['/user/auth/external', 'authclient' => 'ADDYOURAUTHCLIENTIDHERE']);
                    }
                }
            ]
        ]
     //...
```

**Comment by azmeuk** [comment]
This works thank you! <3
I think this feature should be either documented, or made a simple configuration.

**Comment by luke-** [comment]
Great!

I've added it here: https://community.humhub.com/s/installation-and-setup/wiki/page/view?title=Configuration+Examples
