### ISSUE TITLE
Add option to filter by date

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#5499]
From...to date - Any ideas @orangiene A simple solution would be sufficient for now. 

![image](https://user-images.githubusercontent.com/38326726/149982348-a77ec0a2-4b2a-44be-bc3a-a8719d062a78.png)

**Comment by orangiene** [comment]
Hey @luke- 
I would choose the date picker by bootstrap.

![datepicker-fiter](https://user-images.githubusercontent.com/62644500/155175795-96daa37b-db47-4c2d-82f3-e95052c52af7.jpg)


https://www.figma.com/file/tshvUVBzxy7uW8eZs6n6IG?node-id=0:1#156065130

**Comment by luke-** [comment]
@orangiene ok, we can try that. I'm not sure if a new column won't be a bit small. Here is the default design:

![image](https://user-images.githubusercontent.com/4736168/155284546-a0001045-e2ae-4dde-b27c-79b1fa1e2027.png)

**Comment by orangiene** [comment]
@luke- yes, I know, but let's try. Maybe we can make the formfields a little bit smaller.
If it doesn't work, I will make a new proposal.

**Comment by luke-** [comment]
Ok
