### ISSUE TITLE
Module install > browse online > click install

### ISSUE THREAD

**Issue by mrtn** [humhub/humhub#550]
Fatal error: Class 'ZipArchive' not found in /protected/modules_core/admin/libs/OnlineModuleManager.php on line 87

**Comment by xaro1** [comment]
You must install PHP ZipArchive library. Package php-pecl-zip. After install, don't forget to restart your webserver service.

**Comment by luke-** [comment]
We should add this to requirements...

**Comment by mrtn** [comment]
@luke- I think it is a good idea. 

I am on shared hosting and it is not installed standard. I will ask to install it and try again.

**Comment by maddox22** [comment]
i am also trying to install modules .. but i here erorr is protected/modules_core/admin/libs/OnlineModuleManager.php on line 87
