### ISSUE TITLE
Profile Fields with `tel://` Prefix

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5503]
### Is your feature request related to a problem? Please describe.

For phone number profile fields, it would be good to link them with "tel://".

Maybe it makes sense to include anchor type(?) field in the profile field definition where you can specify e.g. tel://, sip://,xmpp://, http://. 

For default phone field we should of course enable it by default.

**Comment by vsemradu** [comment]
https://github.com/humhub/humhub/pull/5520
