### ISSUE TITLE
Cannot use comment form widget in my module.

### ISSUE THREAD

**Issue by rifaideen** [humhub/humhub#551]
Comment form does not work properly inside my module. I am showing comment form widget in my module and it shows the comment form and files also uploadable but the problem is it does not submit the comment when i press enter key.

**Comment by WASasquatch** [comment]
I believe the JS files are not properly linking, which is why you get a normal line-break on enter.

**Comment by rifaideen** [comment]
My Problem is I can use all the controls that are normally loaded in wall. i.e new album created activity shown on wall working perfectly. but at the same I have provided the option to view the entire album in lightbox loaded via ajax request. in that modal I am using the show comments widget and entering the comments will not get submitted this may happening due to the same id generated by comment widget. so introduce unique id with some random values.

**Comment by WASasquatch** [comment]
Or it could be happening because the JS is not designed to select elements newly added to the DOM and does not listen for those changes. Comment form is used no where in AJAX so it's likely this functionality is not in the jQuery.

**Comment by rifaideen** [comment]
yes @WASasquatch I have planned on extending the comment widget to work on this.
