### ISSUE TITLE
Link preview text has incorrect encoding

### ISSUE THREAD

**Issue by waldyrious** [humhub/humhub#5514]
### What steps will reproduce the problem?

Post a link whose title or text contains non-ASCII characters ([example](https://www.noticiasdeaveiro.pt/porque-me-candidato-pelo-livre-a-assembleia-da-republica/)).

### What is the expected result?

The rich preview of the link should include the proper characters like à, ú, í, etc.

### What do you get instead?

The non-ASCII characters are misinterpreted as Ã, Ãº, Ã£, Ã¢, etc. According to [this StackOverflow thread](https://stackoverflow.com/questions/5127744/how-to-convert-these-strange-characters-%C3%83-%C3%83-%C3%83%C2%AC-%C3%83%C2%B9-%C3%83#5127758), it may be due to UTF-8 text being interpreted as ISO-8859-1. 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by aaukt** [comment]
https://github.com/humhub/linkpreview-issues/issues/16

**Comment by waldyrious** [comment]
Thanks, @aaukt — I will close this issue in favor of that one.
