### ISSUE TITLE
"Follows" Notifications are Awkward

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#5517]
Ever since Follow became entwined with Friendship, we get awkward emails every time a friend request is sent or accepted.  And it says nothing about friendship.  The notification is literally "X now follows Y" as well as "Y now follows X".  These are not meaningful in the way they might be intended.

**Comment by luke-** [comment]
There should be no such notification at all.

**Comment by yurabakhtin** [comment]
@luke-

> There should be no such notification at all.

Do you mean we should not send a notification "Follows" even if user click on the button "Follow"?
Currently in PR https://github.com/humhub/humhub/pull/5526 I fixed to don't send the notification "Follows" when user request a friendship, in such case only single notification is sent with subject "User1 sent you a friend request.".
But if user click directly on the button "Follow" then one notification is sent with subject "User is now following you.".

**Comment by luke-** [comment]
Ok, the notifications seem to be correct, but it seems that a Following activity is also triggered with a friendship. This should not be created. @miqrogroove Can you confirm?

**Comment by yurabakhtin** [comment]
@luke- 

> but it seems that a Following activity is also triggered with a friendship. This should not be created.

It is not created. When friendship is triggered the Follow notification and Follow activity are not triggered because on call `Friendship:add()` we call `$friend->follow($user, $withNotifications = false);` without notifications here https://github.com/humhub/humhub/blob/fix/5517-follows-notifications-on-friendship/protected/humhub/modules/friendship/models/Friendship.php#L246, then here https://github.com/humhub/humhub/blob/fix/5517-follows-notifications-on-friendship/protected/humhub/modules/friendship/models/Friendship.php#L246 I added to call Follow notification and Follow activity only when `$withNotifications == true`.

**Comment by luke-** [comment]
@yurabakhtin Currently I can reproduce following behavior:
Click on `+ Friends` on People page for User X. The User X receives following Notifcations:
![image](https://user-images.githubusercontent.com/4736168/152139834-6bed3e34-bf74-437e-8321-9c090b69fc4e.png)

**Comment by miqrogroove** [comment]
> Ok, the notifications seem to be correct, but it seems that a Following activity is also triggered with a friendship. This should not be created. @miqrogroove Can you confirm?

There might be more than one problem here.  In addition to the Notifications that you reproduced for a new friend request sent to "you", there are the messages appearing to everyone(?) else in E-Mail Summaries.  These are the "X now follows Y" and "Y now follows X" messages I originally reported.

But I think this is wrong for multiple reasons.  When I look in the account settings, it never mentions Following activity for E-Mail Summaries.

![screen](https://user-images.githubusercontent.com/1371835/152155865-a563033c-a434-44a7-a4a4-720cd4dc310d.png)

I suggest proceeding very thoughtfully here.  Even if the Notifications are cleared up, it looks like users have no control over the appearance of Following activity in E-Mail Summaries.  I would say the same thing about Friendship activity, however I've not seen any Friendship activity in my E-Mail Summaries.  So, one solution is to stop including Following in E-Mail Summaries, to be consistent with account settings as well as expected behavior.

**Comment by yurabakhtin** [comment]
@luke- 

> Currently I can reproduce following behavior:
Click on + Friends on People page for User X. The User X receives following Notifcations:

Did you test on the new branch https://github.com/humhub/humhub/tree/fix/5517-follows-notifications-on-friendship?
For me it works without Follow notifications:

<img width="1156" alt="test_friendship_without_follow_notification" src="https://user-images.githubusercontent.com/6995524/152158067-3275208e-b38c-49d3-b791-c31e623c596b.png">

**Comment by miqrogroove** [comment]
I'm no expert on the HumHub code, but while surfing this raised a question for me...

https://github.com/humhub/humhub/blob/26d7e2667a9317057abe335a056ac8e8f4d675fb/protected/humhub/modules/activity/components/MailSummary.php#L155

If the MailSummary system is based on "suppressed" rather than "allowed" activities, and the MailSummaryForm does not list all available activities, then users can never control new types of activities unless every new type of activity is specified as both an activity as well as a new account setting?  Was this intentional?  Should this be reversed to only show activities selected by the user?

**Comment by luke-** [comment]
@yurabakhtin Thanks for the PR. There was indeed a problem here.

@miqrogroove If there is a problem in the email summary, can you please create a new issue including screenshots. Then we try to reproduce it.
