### ISSUE TITLE
Number of activities reported in the mail summary is limited to 20

### ISSUE THREAD

**Issue by Douand** [humhub/humhub#5518]
**### What steps will reproduce the problem?**
The mail summary is limited to only the last 20 most recent activities. A suggested solution in the Community Hub was to add the following block to protected/config/common.php:

    'container' => [
        'definitions' => [
            \humhub\modules\activity\components\MailSummary::class => [
                'maxActivityCount' => 500
            ]
        ]
    ],
However, this does not increase the reported activities.

**### What is the expected result?**
The ability to increase the number of reported activities in mail summaries, either through adding to common.php, or  perhaps from within the application.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.3
| PHP version      |  7.4
| Operating system |

**Comment by vsemradu** [comment]
please clarify the following: 
Is this task related to this module https://www.humhub.com/marketplace/mail ? 
I don't quite understand on which page the limit of 20 records is displayed?

**Comment by Douand** [comment]
This relates to the e-mail summaries of activity sent hourly, daily, weekly (or never), as set in the user account settings.

![image](https://user-images.githubusercontent.com/74459399/151518563-55ee2ed2-4b99-43a2-b3a1-54633f78a3f6.png)
