### ISSUE TITLE
php Warning by clicking Register! can anyone help me?

### ISSUE THREAD

**Issue by DrHouse96** [humhub/humhub#552]
All is working perfectly but if i want to Register to community I become these PHP WARNING:
![error_message](https://cloud.githubusercontent.com/assets/10351877/5581767/8974a25c-905f-11e4-8e16-a59b6e6c3e3f.PNG)

"require(/home/crowdpub/public_html/protected/extensions/yii-mail/vendors/swiftMailer/dependency_maps/../mime_types.php): failed to open stream: No such file or directory (/home/crowdpub/public_html/protected/extensions/yii-mail/vendors/swiftMailer/dependency_maps/mime_deps.php:3) Stack trace: #0 /home/crowdpub/public_html/protected/extensions/yii-mail/YiiMail.php(240): require() #1 /home/crowdpub/public_html/protected/extensions/yii-mail/YiiMail.php(106): YiiMail->registerScripts() #2 /home/crowdpub/public_html/protected/vendors/yii/base/CModule.php(387): YiiMail->init() #3 /home/crowdpub/public_html/protected/vendors/yii/base/CModule.php(103): WebApplication->getComponent() #4 /home/crowdpub/public_html/protected/extensions/yii-mail/YiiMailMessage.php(112): WebApplication->__get() #5 /home/crowdpub/public_html/protected/modules_core/user/models/UserInvite.php(145): HMailMessage->__construct() #6 /home/crowdpub/public_html/protected/modules_core/user/controllers/AuthController.php(115): UserInvite->sendInviteMail() #7 /home/crowdpub/public_html/protected/vendors/yii/web/actions/CInlineAction.php(49): AuthController->actionLogin() #8 /home/crowdpub/public_html/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #9 /home/crowdpub/public_html/protected/vendors/yii/web/CController.php(286): AuthController->runAction() #10 /home/crowdpub/public_html/protected/vendors/yii/web/CController.php(265): AuthController->runActionWithFilters() #11 /home/crowdpub/public_html/protected/vendors/yii/web/CWebApplication.php(282): AuthController->run() #12 /home/crowdpub/public_html/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #13 /home/crowdpub/public_html/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #14 /home/crowdpub/public_html/index.php(39): WebApplication->run() REQUEST_URI=/index.php?r=user/auth/login in /home/crowdpub/public_html/protected/extensions/yii-mail/vendors/swiftMailer/dependency_maps/mime_deps.php (3) in /home/crowdpub/public_html/protected/extensions/yii-mail/vendors/swiftMailer/dependency_maps/mime_deps.php (3) in /home/crowdpub/public_html/protected/extensions/yii-mail/vendors/swiftMailer/swift_init.php (23) in /home/crowdpub/public_html/protected/extensions/yii-mail/YiiMail.php (240) in /home/crowdpub/public_html/protected/extensions/yii-mail/YiiMail.php (106) "

**Comment by DrHouse96** [comment]
any Idea? :/

**Comment by scrobbleme** [comment]
@DrHouse96 
Have you checked that the file exists and the permissions are correct? Also, maybe the upload (for this file) failed and you have to re-upload it.
