### ISSUE TITLE
Only 500 Users replicated through LDAP?

### ISSUE THREAD

**Issue by MarcusBauch** [humhub/humhub#5525]
Dear Humhub team, our community now has **over** 500 members (connected via LDAP). We found out that only 500 users are imported to Humhub. What could be the reason for this?

HumHub version: 1.10.3
PHP version: 7.4.27
OS: Debian 10

Regards

**Comment by luke-** [comment]
What is the default pagination size of your LDAP server?

**Comment by MarcusBauch** [comment]
It's an openLDAP server. There is nothing changed. Documentation said: default=500, but a LDAPSEARCH give me (all) 512 entrys

**Comment by luke-** [comment]
Try to adjust the LDAP Page Size to 500 in your configuration
https://docs.humhub.org/docs/admin/config-options#ldap

**Comment by MarcusBauch** [comment]
The problem was solved by increasing the pagination in the OpenLDAP configuration
