### ISSUE TITLE
Tooltip: Improving readability

### ISSUE THREAD

**Issue by orangiene** [humhub/humhub#5529]
### Is your feature request related to a problem? Please describe.
The font size in the tooltip is too small and not easy to read.
Accessibility is also not guaranteed due to the self-selectable colour (primary colour).

### Describe the solution you'd like
I propose that we make the tooltip uniform.
Background colour white, font colour #555555, frame colour (as usual) #C5C5C5.
The tooltip may have the usual shadow. 
Font: Open Sans regular, font size 12px.
Spacing up, down, left and right 12px.

![Tooltip-02](https://user-images.githubusercontent.com/62644500/152328256-5396a316-737e-4625-a201-478f4b6ed191.jpg)

The minimum solution, however, would be to at least adjust the font size and style.
Font size 12 px
Font style regular

![Tooltip-01](https://user-images.githubusercontent.com/62644500/152328247-57ae313c-496f-404a-b814-cdd5d4cbffad.jpg)

**Comment by luke-** [comment]
@orangiene In your example I would prefer the lighter version.

But usually tooltips with less text & single line are used. Here I would be concerned that the tooltip would not stand out as much. 

![image](https://user-images.githubusercontent.com/4736168/152332684-fee8cb7e-2533-4794-a23f-3d85a3f992a0.png)

**Comment by orangiene** [comment]
is it possible to use different versions here or can we only use one?

**Comment by luke-** [comment]
That would be possible. But then I would prefer to open a modal in cases with a lot of text.

**Comment by Semir1212** [comment]
@luke- Users should also be able to easily hover over the message without it disappearing (for accessibility reasons).

**Comment by orangiene** [comment]
@luke- is it still possible to at least adjust the font size and style as indicated above? 
Then in the worst case it would not be so bad if a tooltip appeared anyway.

**Comment by luke-** [comment]
@orangiene Yes, we can change the style. But then that applies everywhere.

**Comment by orangiene** [comment]
If you think that the worst case scenario with a lot of text rarely happens, then we can leave it as it is for now.

**Comment by orangiene** [comment]
@luke-  yes please increase the text size to 12px , thank you!
