### ISSUE TITLE
Comment/Post: FileHandler Buttons not always available

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5530]
When `Edit` a post or `Create/Edit` a comment - the FileHandlers are not available.

**Create a Post**
![image](https://user-images.githubusercontent.com/4736168/152353310-af14b995-f11e-4f1a-a3f2-0fcc3a8433e8.png)

**Edit a Post***
![image](https://user-images.githubusercontent.com/4736168/152357072-42c570a1-a510-44cf-a252-a7777595cdb8.png)

Related to: https://github.com/humhub/humhub/issues/4634

**Comment by yurabakhtin** [comment]
@luke- I will implement this after https://github.com/humhub/humhub/issues/4634#issuecomment-1040026196 or right in the same PR.

**Comment by yurabakhtin** [comment]
@luke- It was implemented here - https://github.com/humhub/humhub/issues/4634#issuecomment-1041223710:

<img width="660" alt="attach_post_edit_form" src="https://user-images.githubusercontent.com/6995524/154231665-39fbd6b6-c2fe-461f-92dc-07a4d93df103.png">

**Comment by luke-** [comment]
@yurabakhtin Awesome thanks!
