### ISSUE TITLE
Content/Comment Deleted Notification

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5536]
When an admin/moderator deletes someone else's content or comment, a modal should pop up. Here it should be possible to give a reason or delete the content without notification.

The creator of the content will receive a notification. e.g. "Your comment was deleted by NAME. (Reason: text content)".

**Comment by Semir1212** [comment]
Headline: Delete Comment/Post?
Message --> Reason
Send a notification to the author. --> Send notification to author
Delete -->  Confirm


Your post/comment '............' has been deleted by ABC for 'Reason'

@s-tyshchenko
