### ISSUE TITLE
Space: Starting Page gets lost when changing URL

### ISSUE THREAD

**Issue by lisandi** [humhub/humhub#5537]
### What steps will reproduce the problem?

1. Enter a starting page for Members
2. Define a Starting Page for Guests shouldn't be Stream (Default to see the problem!)
3. Save
4. now go again and change the path segment to something else
5. Save

### What is the expected result?
The already defined Starting Pages should not be changed when the Path segment gets changed.

### What do you get instead?
as you can see both - Members and Guests - will have their Starting Pages reset to default. The correct previous entries are lost.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.3 - newestupdates via GITmaster?
| PHP version      |  8.0
| Operating system | Ubuntu 20.04 LTS

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
![Screen Shot 2022-02-04 at 11 52 22](https://user-images.githubusercontent.com/1982011/152674501-d9addcfe-9920-408a-8ee3-83fd4b25cc0e.png)

https://community.humhub.com/file/file/download?guid=757ee244-e600-41cd-bd6d-c9f7cc5c0ff

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
@gevorgmansuryan Can you please try to reproduce?
