### ISSUE TITLE
Access Error in Gallery Widget

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#5543]
### What steps will reproduce the problem?

Click the Settings option in the Gallery Widget menu.

### What is the expected result?

See some settings, I guess???

### What do you get instead?

```
Oooops... It looks like you may have taken the wrong turn.
You are not permitted to access this section.
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.3
| Gallery version   | 1.2.2
| PHP version      | 7.4.27
| Operating system | Ubuntu 20.04.3

![step1](https://user-images.githubusercontent.com/1371835/153077358-b7358fce-d4c3-4c24-9c7f-e6ec6b2f2bae.jpg)
![step2](https://user-images.githubusercontent.com/1371835/153077360-829a4795-b29f-412e-9912-de6820a10afe.jpg)
![step3](https://user-images.githubusercontent.com/1371835/153077362-18042db5-d197-4b3c-b72b-1f4be469faff.jpg)
.

**Comment by ArchBlood** [comment]
Love that bug reports are coming in but this should be opened on the gallery module repo no?

**Comment by luke-** [comment]
-> https://github.com/humhub-contrib/gallery
