### ISSUE TITLE
Showing post at top of stream if new comment is submitted

### ISSUE THREAD

**Issue by Tagussan** [humhub/humhub#555]
Like facebook, it would be useful if Humhub shows the post which new comment is submitted, at the top of stream. I want to see heated discussion at the top of the stream.

**Comment by andystrobel** [comment]
It's already possible with the sort menu:

![bildschirmfoto 2015-01-02 um 16 28 16](https://cloud.githubusercontent.com/assets/6032728/5597094/b1a44194-929c-11e4-87d7-e8f973ef5114.png)

But I'm with you. It would be nice to have it as a default option at the admin section (which also works for the dashboard then)

**Comment by xaro1** [comment]
+1

**Comment by ufukk** [comment]
This doesn't seem to work for us. Feeds with the most recent comments don't go to the top. Also, I don't know if it's related but [Post.lastUpdatedAt] field value doesn't change after a new comment.
