### ISSUE TITLE
No formatted output for date fields in "About me" profile area

### ISSUE THREAD

**Issue by KarlKeu00** [humhub/humhub#5556]
### What steps will reproduce the problem?
- Add a new profile field.
- Enter a date.
- Go to the "About me" page.
- The date will not be formatted nicely.

### What is the expected result?
A nicely formatted date (like the birthday)

### Additional info
I will upload the fix in a moment :)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
@KarlKeu00 Thank you!
