### ISSUE TITLE
Css Bug: Statistic display broken on high values

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#556]
![capture](https://cloud.githubusercontent.com/assets/9461399/5599925/9c39c05e-92d8-11e4-83c6-7dd57bf12285.PNG)

**Comment by radiolip** [comment]
how to fix or hide the statistics?

**Comment by andystrobel** [comment]
Build your own theme and change the css properties.

**Comment by radiolip** [comment]
need to fix the bug...

**Comment by luke-** [comment]
@radiolip Please use more explanatory issue titles!
