### ISSUE TITLE
Cron-jobs with Cron-job.org

### ISSUE THREAD

**Issue by mgutsch42** [humhub/humhub#5574]
<!--
HumHub version   | 1.10.3

My webserver does not accept cron commands. The support mentioned, that they do not support Cron jobs or Crontab on their servers regrettably. So I thought to use cron-job.org instead. But I don´t know, how to set the alternative go live. As I am not so technical familiar, I would be very thankful, if you know a solution, as I am probably not the only one, who loves the idea of humhub, but who is not an expert .

I won´t to avoid the warning message 

Warning incomplete setup!
The cron job for the background jobs (queue) does not seem to work properly.
The cron job for the regular tasks (cron) does not seem to work properly.

So the jobs and the queue has to be executed. But I don´t know how with the alternative.

Always thankful for your help.

Kind regards,

Martin

**Comment by luke-** [comment]
Did you tried this? 
https://www.humhub.com/de/marketplace/cron-daemon/
