### ISSUE TITLE
Add Content Topics to Search

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5575]
### Is your feature request related to a problem? Please describe.

Assigned topics to a content are not added to the search index

### Describe the solution you'd like

Make topics also searchable

**Comment by yurabakhtin** [comment]
@luke- I tried to do this: for the class `\humhub\modules\post\models\Post` add a new attribute for the method `getSearchAttributes()`:

- `'tags' => implode(' ', $this->content->getTags()->select('name')->column()),`

but it doesn't work, could you please help me to understand why?

Also it seems you want to apply new searching by topics for all classes implemented from `Searchable` and extended from `ContentActiveRecord`, I see at least 11 such classes. Does it mean we should do this for all these classes?

**Comment by luke-** [comment]
@yurabakhtin For me your line is working.
![image](https://user-images.githubusercontent.com/4736168/156417167-91af0cc4-47f1-4971-bb08-cc5bed6452ef.png)

The content is added asychnron via the queue in the search index. Maybe it takes some time or the queue processing is not running correctly on your dev machine?

Of course, it would be good if this works automatically for all content and does not have to be added to each one individually.

**Comment by yurabakhtin** [comment]
@luke- Thank you for the info "The content is added asychnron via the queue in the search index.", it helped me.

> Of course, it would be good if this works automatically for all content and does not have to be added to each one individually.

I have implemented this.
PR https://github.com/humhub/humhub/pull/5600.
