### ISSUE TITLE
Searching in "Content" still searches author names

### ISSUE THREAD

**Issue by dantefromhell** [humhub/humhub#5579]
When using the search function, but choosing to search "Content" only, the author name of a post is still searched.

As there is an "Users" search option, it raises the expectation that "Content" search is limited to message content, not including message author.

### What steps will reproduce the problem?
E.g. when searching for the term "DAV" (as in CalDAV, CardDAV) in the HumHub community (https://community.humhub.com/) and choosing "Content", messages that have been created by users whose name includes "David" are shown.

### What is the expected result?
When selecting "Content" search, the search term is applied to the message content only.
When selecting "Users" search, the search term is applied to users only.
When selecting "All" search, messages where username and/or content matches are shown.

### What do you get instead?
see above.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.3
| PHP version      | unknown (hosted by HumHub)
| Operating system | unknown (hosted by HumHub)

**Comment by lisandi** [comment]
Actually, both would be good to have, depending on the kind of forum you need to search for people, and here also mentions of people in the content too.

**Comment by dantefromhell** [comment]
Agreed @lisandi 

Would it make sense to have checkboxes instead of clickable text links instead?
Like a 'Content' and 'Users', possibly an 'Authors' checkbox which inform the search engine from which context to return results from?

IMO that would allow for any possible search combination while not exploding in complexity.
