### ISSUE TITLE
Why isn't PostgreSQL supported?

### ISSUE THREAD

**Issue by miloskroulik** [humhub/humhub#559]
I wonder, why PostgreSQL DB isn't supported. I don't have much experience with MySQL, so it's requirement is a big disadvantage for me.

**Comment by luke-** [comment]
We try to support multiple database engines in future. 
Atm we haven't enough resources/time & PostgreSQL experiences to support it.

**Comment by miloskroulik** [comment]
Thanks, I will check again in future.

2015-01-08 20:31 GMT+01:00 luke- <notifications@github.com>:

**Comment by WASasquatch** [comment]
I am working on a port of HumHub DB for postgreSQL for a friend and his limited server. If I manage to get it working I will request a push.

**Comment by richhl** [comment]
hi, why is needed an specific support for postgresql? yii framework is supposed to deal with postgresql. As long as one uses wrapped DAO and don't write SQL with specific extensions Humhub would work as is. am I missing any point? thx

**Comment by luke-** [comment]
At least we need to test it. :-)

There are some complexer sql statements - I'm not sure everything is fully compatible.
Maybe there are some minor changes required.

**Comment by richhl** [comment]
ok, thx. Schema creation is driven by any library able to generate for several rdbms as doctrine annotations or one needs to create it manually?

**Comment by luke-** [comment]
Schema creation *should* also be fully db independent.

e.g.
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/friendship/migrations/m160216_160119_initial.php
