### ISSUE TITLE
Introduce variables in ContentContainerActiveRecord model to call ProfileImage and ProfileBannerImage

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5599]
### Is your feature request related to a problem? Please describe.

It is not possible to change the profile and banner image with a module.

### Describe the solution you'd like

Similar to the [Widget](https://github.com/humhub/humhub/blob/develop/protected/humhub/components/Widget.php) class, add `const EVENT_CREATE = 'create';` in [ProfileImage](https://github.com/humhub/humhub/blob/develop/protected/humhub/libs/ProfileImage.php) and [ProfileBannerImage](https://github.com/humhub/humhub/blob/develop/protected/humhub/libs/ProfileBannerImage.php)

If you agree, I can send a PR. Thanks.

**Comment by luke-** [comment]
Can you please briefly describe what exactly you want to do with the module (e.g. stop uploading profile images) and how the new Event should work.

**Comment by funkycram** [comment]
I would like to be able to change the URL of the profile image with a module (1).
I had in mind to have the same possibility we have with the `EVENT_CREATE` for widgets, which enables a module to replace the class using `$event->config['class']` in `Events.php`
Thanks!

(1) I'm developing a module enabling groups to have spaces members in addition to users members.
The objective being, among other things, to be able to restrict access to spaces based on group membership and also to be able to be a member of a group automatically if you become a member of a space of this same group.
This module will also allow to assign an image to a group and to classify the spaces thanks to the groups.
When we have a lot of spaces, in order to unify them graphically, I would like to be able to automatically, if the space has no profile picture, display that of the group of which it is a member.

**Comment by luke-** [comment]
@funkycram 

Yes, that's right. You can use the `EVENT_CREATE` to replace the class of a widget with another one.
I.e. you could replace the Space (`humhub\modules\space\widgets\Image`) or User (`humhub\modules\space\widgets\Image`)  Image with it.  For example, we use it in the Enterprise theme to replace the Space Chooser.

Sounds like an interesting module, there are definitely many use cases for it!

**Comment by funkycram** [comment]
@luke- yes, that's fine, thanks!
See https://github.com/humhub/humhub/pull/5611, I can change it if you want.

**Comment by luke-** [comment]
Merged, thank you!

**Comment by funkycram** [comment]
Thanks!
