### ISSUE TITLE
Duplicated field "Hostname" on install

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub#5608]
### What steps will reproduce the problem?
Start new installation and go to the page "Database Configuration"

### What is the expected result?
Single field "Hostname"

### What do you get instead?
![install-field-duplicated](https://user-images.githubusercontent.com/6995524/160087458-d73e1148-5526-4211-8be0-6352b9459ec0.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.0-beta.2

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5609.

It seems the duplicated field was added there by mistake during merging - https://github.com/humhub/humhub/commit/cdd71eb#diff-7484fd47557382ae8c22ae8afa6950d211e249e4e19dc2cafd8bb82768df4bacR21-R22

**Comment by luke-** [comment]
@yurabakhtin Thanks!
