### ISSUE TITLE
RichText post process event doesn't pass data

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5612]
### What steps will reproduce the problem?

Create an event triggering `AbstractRichText::EVENT_POST_PROCESS`.
E.g.:
```
use humhub\modules\content\widgets\richtext\AbstractRichText;
....
        [
            'class' => AbstractRichText::class,
            'event' => AbstractRichText::EVENT_POST_PROCESS,
            'callback' => [Events::class, 'onAbstractRichTextPostProcess']
        ],
```

In Events.php, add:
```
public static function onAbstractRichTextPostProcess($event)
    {
        Yii::error(print_r($event->data, true));
    }
```

### What is the expected result?

In the log, get the data sent by [this event](https://github.com/humhub/humhub/blob/ff5ff85ec986d1e39027eb8f5055bd48ac57cd3b/protected/humhub/modules/content/widgets/richtext/AbstractRichText.php#L243):
`['text' => $text, 'record' => $record, 'attribute' => $attribute]`

### What do you get instead?

An empty entry in the log.

### Additional info

This is because `data` attribute  is always overridden by the values from event handler."
See https://github.com/yiisoft/yii2/issues/15227

We should use the `result` attribute instead.

I suggest this code (I can do a PR if you agree):
```
        $evt = new Event(['result' => ['text' => $text, 'record' => $record, 'attribute' => $attribute]]);
        Event::trigger(static::class, static::EVENT_POST_PROCESS, $evt);
        $result = $evt->result;
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look here?

**Comment by yurabakhtin** [comment]
@funkycram Thank you the found issue. Fixed in PR https://github.com/humhub/humhub/pull/5615.

**Comment by funkycram** [comment]
Thanks @yurabakhtin ! Just tested, it works fine.
