### ISSUE TITLE
oEmbed confirmation leaves blank form

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#5616]
### What steps will reproduce the problem?
Take any of the oEmbed options (i.e YouTube) and paste the link into a post form or comment/reply form then click the checkbox and confirm it, once you have done this the YouTube link is removed and you're left with a blank form again, you can then try multiple times afterward with the same results happening.

### What is the expected result?
After the confirmation of the provider, the link should render the video/post as intended as it did before.

### What do you get instead?
The provider link is removed and you're left with a blank form.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11-beta.2
| PHP version      | 7.4
| Operating system | CloudLinux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
You can also reproduce it on the community site as well as cloud and self-hosted installations.

**Comment by luke-** [comment]
I'm not sure if we even need that for the editor.

**Comment by ArchBlood** [comment]
> I'm not sure if we even need that for the editor.

I myself like the option to have it, but only if it actually worked 😅

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5620

> I'm not sure if we even need that for the editor.

I have done to don't show the yellow confirmation in the edit forms:

![oembed-in-form](https://user-images.githubusercontent.com/6995524/160848364-a622421d-de7d-40bc-8883-864ed73934ee.png)
