### ISSUE TITLE
Enhance soft-delete for GDPR compliance

### ISSUE THREAD

**Issue by samuk** [humhub/humhub#5619]
### Is your feature request related to a problem? Please describe.

When a user soft-deletes themselves their name is not deleted from the database. This is not GDPR compliant

### Describe the solution you'd like

Content by a given user remains, but their name is removed from it. All personal data (email address etc) is deleted from the database.

### Describe alternatives you've considered

Some further discussion here: https://community.humhub.com/s/general-discussion/post/post/view?id=14316

**Comment by luke-** [comment]
See `softDeleteKeepProfileFields` here https://docs.humhub.org/docs/admin/config-options#user
