### ISSUE TITLE
Chrome Lighthouse is complaining jQuery UI@1.12.1 has  3 security issues

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub#5625]
Humhub version 1.10.3 community edition

Chrome Lighthouse (F12, tab Lighthouse) says that the used version of JQuery UI 1.12.1 is too old and has 3  [Cross-site Scripting (XSS)] issues. See https://snyk.io/vuln/npm:jquery-ui?lh=1.12.1&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit

Is JQuery UI still needed and if so, can it be upgraded to version 1.13.1?

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look?

**Comment by yurabakhtin** [comment]
@luke- I find the JQuery UI is registered by `yii\jui\JuiAsset` from `@bower/jquery-ui/jquery-ui.js`.
The file `protected/vendor/bower-asset/jquery-ui/package.json` has `"version": "1.12.1"`
https://github.com/yiisoft/yii2-jui/blob/master/src/JuiAsset.php#L21
https://github.com/components/jqueryui/blob/master/package.json#L4
It seems we should wait when it will be updated there.

**Comment by aronbos** [comment]
Perhaps we have to wait very long. The last update to the blob package was 6 years ago. 
Why don´t we use an other repository?

**Comment by luke-** [comment]
Maybe we should rather create an issue in Yii2-JUI.
Do we use JUI & Jquery-UI at all? I think the bugs will rather not affect us.

@yurabakhtin : Can you check why we need Jquery UI?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you check why we need Jquery UI?

I find it is used at least for date picker, for example, for user birthday field and in external modules like Calendar.

Also `sortable` is used in external modules like Tasks. And it seems the `sortable` was used for user profile fields in past but I see the related code was not cleared completely: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/admin/controllers/UserProfileController.php#L175-L179 - I don't find where the action is used, and the `this->reorderContent()` doesn't exist, the file https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/views/reorderContent.php is not used anymore (I find there the using of UI `sortable`).

**Comment by aronbos** [comment]
So adding the Jquery UI part needed for the data picker to the Humhub javascript library would free us from including Jquery UI? That would be a great win in minimizing the unused javascript.

**Comment by luke-** [comment]
@yurabakhtin Can we somehow force an upgrade here?

**Comment by yurabakhtin** [comment]
@luke- Ok, I have updated jQuery UI version to 1.13.2 in PR https://github.com/humhub/humhub/pull/6140.
I check datepicker and sortable feature work well, but probably we may find some wanrings about deprecated features in other places later.
