### ISSUE TITLE
Cron Job not working

### ISSUE THREAD

**Issue by BaconTriple** [humhub/humhub#5626]
### What steps will reproduce the problem?
This is constant as the error has been happening for 14 days.

### What is the expected result?
That the cron job runs without errors.

### What do you get instead?
Every minute I get the following:

`"ERROR  Wed, 06 Apr 2022 22:04:02 +0100 yii\base\Exceptionyii\base\ErrorException: mkdir(): Permission denied in /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:640 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'mkdir(): Permis...', '/var/www/html/p...', 640, Array) #1 /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(640): mkdir('upload', 484) #2 /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(637): yii\helpers\BaseFileHelper::createDirectory('upload', 484, true) #3 /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(637): yii\helpers\BaseFileHelper::createDirectory('upload/files', 484, true) #4 /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(637): yii\helpers\BaseFileHelper::createDirectory('upload/files/a', 484, true) #5 /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(637): yii\helpers\BaseFileHelper::createDirectory('upload/files/a/...', 484, true) #6 /var/www/html/protected/humhub/modules/file/components/StorageManager.php(150): yii\helpers\BaseFileHelper::createDirectory('upload/files/a/...', 484, true) #7 /var/www/html/protected/humhub/modules/file/components/StorageManager.php(102): humhub\modules\file\components\StorageManager->getPath() #8 /var/www/html/protected/humhub/modules/file/models/File.php(107): humhub\modules\file\components\StorageManager->delete() #9 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): humhub\modules\file\models\File->beforeDelete() #10 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\db\ActiveRecord->deleteInternal() #11 /var/www/html/protected/humhub/modules/file/Events.php(51): yii\db\ActiveRecord->delete() #12 [internal function]: humhub\modules\file\Events::onCronDailyRun(Object(yii\base\Event)) #13 /var/www/html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event)) #14 /var/www/html/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('humhub\\commands...', 'daily', Object(yii\base\Event)) #15 /var/www/html/protected/humhub/commands/CronController.php(130): yii\base\Component->trigger('daily') #16 /var/www/html/protected/humhub/commands/CronController.php(55): humhub\commands\CronController->runDaily() #17 [internal function]: humhub\commands\CronController->actionRun() #18 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #19 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #20 /var/www/html/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('run', Array) #21 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('run', Array) #22 /var/www/html/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('cron/run', Array) #23 /var/www/html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('cron/run', Array) #24 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #25 /var/www/html/protected/yii(29): yii\base\Application->run() #26 {main} Next yii\base\Exception: Failed to create directory "upload": mkdir(): Permission denied in /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:645 Stack trace: #0 /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(637): yii\helpers\BaseFileHelper::createDirectory('upload', 484, true) #1 /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(637): yii\helpers\BaseFileHelper::createDirectory('upload/files', 484, true) #2 /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(637): yii\helpers\BaseFileHelper::createDirectory('upload/files/a', 484, true) #3 /var/www/html/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(637): yii\helpers\BaseFileHelper::createDirectory('upload/files/a/...', 484, true) #4 /var/www/html/protected/humhub/modules/file/components/StorageManager.php(150): yii\helpers\BaseFileHelper::createDirectory('upload/files/a/...', 484, true) #5 /var/www/html/protected/humhub/modules/file/components/StorageManager.php(102): humhub\modules\file\components\StorageManager->getPath() #6 /var/www/html/protected/humhub/modules/file/models/File.php(107): humhub\modules\file\components\StorageManager->delete() #7 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): humhub\modules\file\models\File->beforeDelete() #8 /var/www/html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\db\ActiveRecord->deleteInternal() #9 /var/www/html/protected/humhub/modules/file/Events.php(51): yii\db\ActiveRecord->delete() #10 [internal function]: humhub\modules\file\Events::onCronDailyRun(Object(yii\base\Event)) #11 /var/www/html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event)) #12 /var/www/html/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('humhub\\commands...', 'daily', Object(yii\base\Event)) #13 /var/www/html/protected/humhub/commands/CronController.php(130): yii\base\Component->trigger('daily') #14 /var/www/html/protected/humhub/commands/CronController.php(55): humhub\commands\CronController->runDaily() #15 [internal function]: humhub\commands\CronController->actionRun() #16 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #17 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array) #18 /var/www/html/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('run', Array) #19 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('run', Array) #20 /var/www/html/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('cron/run', Array) #21 /var/www/html/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('cron/run', Array) #22 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request)) #23 /var/www/html/protected/yii(29): yii\base\Application->run() #24 {main}"`

I have checked the permissions on all folders and even as a temporary measure gave full access across the board but the issue persists. I have no idea what folder its looking at as it just says '...' after part of the directory string.

Really appreciate someone telling me whats going on.

Josh

**Comment by ArchBlood** [comment]
Your service probably limits to run a cron every 5 minutes or more, this is topical for shared hosting and even some dedicated servers.

**Comment by BaconTriple** [comment]
> Your service probably limits to run a cron every 5 minutes or more, this is topical for shared hosting and even some dedicated servers.

Hey, appreciate your reply, this is not the case, it has been working for the past year up until 2 weeks ago and as I am the only person working on it I know that nothing changed apart from me uninstalling a module. I feel like I could solve the problem if the error logs would just show the entire location that its complaining about.

**Comment by luke-** [comment]
@BaconTriple Can you manually create a directory with the cron user in the location? Maybe there are other system restrictions (max. folders).

**Comment by BaconTriple** [comment]
@luke- I am unsure how to make a directory using the cron user?

I can make other directories there in general using www-data or root. Without knowing what it is trying to make its a bit difficult to know what the issue is other than its something to do with humhub

**Comment by luke-** [comment]
Are your CronJobs and web application running under the same user "www-data"?

**Comment by BaconTriple** [comment]
@luke- yeah they are using www-data, this is what i've got set up and its been working for over a year:
![image](https://user-images.githubusercontent.com/97461220/163262210-57d12959-2cc2-439c-a1e6-b9a9e191fc3d.png)

**Comment by BaconTriple** [comment]
I didn't close this?

**Comment by ArchBlood** [comment]
> I didn't close this?
> 
> The jobs are still broken and I have not changed anything from my side. I don't see how I can troubleshoot if the logs don't show me a full path.

Are you using a shared hosting plan, dedicated plan or VPS solution?

**Comment by BaconTriple** [comment]
@ArchBlood as in where is my instance hosted? Its on a private physical server in my house running Linux

**Comment by ArchBlood** [comment]
> @ArchBlood as in where is my instance hosted? Its on a private physical server in my house running Linux

Try using the absolute path to the directory

**Comment by BaconTriple** [comment]
@ArchBlood ok that makes sense, how do I change Humhubs configuration to use the absolute path, I don't know where it needs changing
