### ISSUE TITLE
Editing tags in user-profile

### ISSUE THREAD

**Issue by MarcusBauch** [humhub/humhub#5627]
Recently, editing your own user tags no longer works correct. As soon as a new tag is added, the other tags are jumbled or deleted.

### What steps will reproduce the problem?
Profile -> Edit -> edit Tags

### What is the expected result?
As many tags in the tag-field as possible without replacements or deletions 

| HumHub version   | 1.10.3 - Community Edition
| PHP version | 7.4.27
| Operating system | Debian Buster 10.11
| Tested with HumHub App, Vivaldi 5.1.2567.73, Chrome 100.0.4896.60, Brave 1.37.109 (all PC, Linux/Windows), Firefox 99.0

**Comment by yurabakhtin** [comment]
@MarcusBauch Could you show what problem you have? Because I cannot reproduce this, for me it works, so I can add/delete tags and save results:

![tags](https://user-images.githubusercontent.com/6995524/162383463-2550cf32-bebb-4e64-b86e-ef0a33fc3f30.png)

**Comment by ArchBlood** [comment]
I've also not been able to reproduce this issue, could it be a custom theme or module that is being used that stops you from editing tags?
