### ISSUE TITLE
Time Zones are Backward

### ISSUE THREAD

**Issue by YaroKasear** [humhub/humhub#5632]
I am trying to configure time zones in the configuration and I noticed that the offset from UTC is backward. I am in America/Chicago, which is supposed to be -5:00 from UTC... but it ADDS 5 instead. Whereas if I go to, say, Maldives, a location at +5, it SUBTRACTS five from UTC. 

This is keeping me from setting the correct time zone using this software. 

### What steps will reproduce the problem?

1. Set up Humhub in Docker.
2. Go to Administration -> Settings -> General -> Server Timezone
3. Set it to anything +- a nonzero amount from UTC and apply it. 
4. Go to Administration -> Settings -> General -> Default Timezone
5. Set it to anything +- a nonzero amount from UTC and apply it. 

### What is the expected result?

That the reported database time would actually follow the correct time for the timezone. If I select a time zone 5 hours behind UTC, I expect it would be UTC-5.

### What do you get instead?

I get a time that's UTC+5. This results in me getting a reported database time that in no way reflects reality. At the time I file this, it's 1.47 PM in America/Chicago. My database, due to this issue, is reporting 11.47 PM. If I instead set the server time to UTC and my default time to something like Maldives, then I get a database time that's correct. Even though Maldives is AHEAD of UTC, the software applies a time BEHIND UTC instead. 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.3
| PHP version     | 7.4.27 
| Operating system | Arch Linux (Docker)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@YaroKasear Could you show screenshots where you have the issue?
Please check my screenshots and let me know where I didn't understand the reproducing steps correctly:

![test_time](https://user-images.githubusercontent.com/6995524/163139498-46c1d050-09b4-4e39-8abb-46614e883abe.png)

**Comment by Dayflare** [comment]
you should also check your personal user timezone in the user settings. 
User -> Settings -> Settings -> Timezone

**Comment by YaroKasear** [comment]
![step1](https://user-images.githubusercontent.com/11284661/164029954-af638c12-7bb2-4b9b-a903-e44fe6ec4708.png)
I have everything set to America/Chicago. The only way I was able to get the server to do the correct time for America/Chicago was to start my container with literally everything pointing to that time zone in environment variables.

![step2](https://user-images.githubusercontent.com/11284661/164030262-c5c55567-3757-4abc-9c6f-63ebc0092943.png)
I set it to a time zone one hour BEHIND Chicago (Yes, I know it still says Chicago, this is another oddity this software is showing: Not reflecting my settings changes unless I restart the container entirely.)

Notice, though, that the time is now wrong on the database. Why would changing the default TZ make the database change its time? Yes, I know if it's 9 AM in Mountain time it'd be 10 AM in Central, but at no point did I say the TIME was different, just the default time zone, so this time should not be changing. 

This made it worse when I tried to have database time in UTC and TZ in Chicago. The time was wrong (No matter what I did.) and then trying to change to Chicago made the database time off by a whole ten hours. 

This is made worse by the fact I can't get multifactor authentication working at all, probably because despite my best efforts the software has no idea what time it is. I can't even be sure that just because it's reporting the time correctly for America/Chicago that internally it actually thinks it's that time in America/Chicago.

**Comment by yurabakhtin** [comment]
@YaroKasear Thank you for the additional details, but sorry, I still cannot understand where the problem is, it would be good if you will write step by step what you do, what you get and what you expect, like this example:

1. My server/container has currently time "2022-04-22 10:23 AM", timezone is "UTC+02:00 - Europe/Berlin"
2. Go to "Administration -> Settings -> General" and set "Default Timezone" and "Server Timezone" to "UTC-05:00 - America/Chicago"
3. Go to google to be sure the time by request string "now time america chicago" is "2022-04-22 03:23 AM"
4. Create a post
5. Go to database tables `content` and `post` and see the fields `created_at` has a value "XXXX-XX-XX XX:XX:XX", but I expect to see there value as "YYYY-YY-YY YY:YY:YY".

So it would be good if you will tell us what date/time and timezone you have on each step above and what result you get on the step 5 and what you expect there. This will helps us to find and solve the issue much faster.
Thank you!
