### ISSUE TITLE
404 response for sw.js

### ISSUE THREAD

**Issue by paulkre** [humhub/humhub#5636]
### What steps will reproduce the problem?

Install HumHub on a server and navigate to the front page in a browser.

### What is the expected result?

No erros in the browser console.

### What do you get instead?

HumHub is requesting a service worker file at `/sw.js` which does not seem to exist. Even with URL rewrites enabled it causes a 404 error. I tried enabling the service worker functionality by modifying `@protected/config/common.php`:

```php
return [
  // ...
  'modules' => [
    'web' => [
      'enableServiceWorker' => true,
    ],
  ],
];
```

Is this the correct way to configure service workers?

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.3
| PHP version      | 8.0.16
| Operating system | Ubuntu 20.04.2 LTS

**Comment by paulkre** [comment]
It seems like the default value for `enableServiceWorker` is actually `true`. Even though the [documention](https://docs.humhub.org/docs/admin/config-options#web) states it's `false`. So I'm assuming, in order to fix the 404 error I could either disable service workers by setting `enableServiceWorker` to `false` or I could provide my own `sw.js` file at the root of the HumHub directory, right? It might be a good idea to clarify this behaviour in the docs. At the very least the default value for `enableServiceWorker` should be updated.

**Comment by luke-** [comment]
I fixed the error in the documentation. By default, the variable is set to true.

If URL rewriting is enabled, the file "/sw.js" should be always available. 
Are you sure that URL rewriting is configured correctly?

**Comment by paulkre** [comment]
Thank you. So if HumHub is running correctly, it should generate the `/sw.js` file automatically when it is requested? I'm using NGINX to serve the site with the following configuration to get URL rewriting to work:

```nginx
server
{
    # ...
    location / {
      try_files $uri $uri/ /index.php?$args;
    }
    # ...
}
```

This works well for all paths like `/dashboard` and it even generates the `/manifest.json` file correctly. But it returns 404 for the `/sw.js` route. Is there anything I need to add to my server configuration?

**Comment by paulkre** [comment]
I found the problem. There was a statement in the configuration of NGINX which prevented all paths ending with `.js` to be transferred to PHP. As soon as I removed that statement, the service worker script was generated successfully.

**Comment by paulkre** [comment]
If I go to `/offline.pwa.html` now, it says: "Unable to connect to ...". Is this the intended behaviour?

**Comment by luke-** [comment]
> If I go to `/offline.pwa.html` now, it says: "Unable to connect to ...". Is this the intended behaviour?

Yes
