### ISSUE TITLE
Add option to "Underline" text

### ISSUE THREAD

**Issue by dantefromhell** [humhub/humhub#5640]
Is it possible to extend the list of text formatting options by the underline ?
As you can find e.g. in Word Documents. HTML5 supports this style with the <u> tag.

### Describe the solution you'd like
The button row above the text-editor field include an icon (and keyboard shortcut) to format text as underlined.

### Describe alternatives you've considered
HTML tags within text, but the HTML is not rendered by the browser, see 
https://community.humhub.com/content/perma?id=254297

**Comment by luke-** [comment]
We do not use HTML but Markdown as markup language. 
https://softwareengineering.stackexchange.com/questions/207727/why-there-is-no-markdown-for-underline

Unfortunately we are somewhat limited here, but do not plan to switch to HTML or other Markup languages.

**Comment by ArchBlood** [comment]
> We do not use HTML but Markdown as markup language. https://softwareengineering.stackexchange.com/questions/207727/why-there-is-no-markdown-for-underline
> 
> Unfortunately we are somewhat limited here, but do not plan to switch to HTML or other Markup languages.

Sadly I can agree here, and it looks like the few attempts at adding underline functionality have been archived;
https://github.com/ueberdosis/html-to-prosemirror
https://github.com/ueberdosis/prosemirror-to-html

Only other thing that I've found is a gist example;
https://gist.github.com/canegru/e398d09270a065f6dbb711570139aace
