### ISSUE TITLE
Page Redirection does not work as expected - 301

### ISSUE THREAD

**Issue by BaconTriple** [humhub/humhub#5653]
### What steps will reproduce the problem?
Its unclear as it seems to affect random pages, I initially thought it was just custom pages but this is not true. I have two pages set up identically but one redirects to its trailing slash counterpart and one does not.
### What is the expected result?
All pages should redirect to a trailing slash
### What do you get instead?
random pages do and random pages don't.
### Additional info
https://ichor-studios.co.uk/p/comics automatically redirects to https://ichor-studios.co.uk/p/comics/
However despite testing with duplicates of this page I cannot get anything else to redirect such as
https://ichor-studios.co.uk/p/comics-comedy to https://ichor-studios.co.uk/p/comics-comedy/

The same can be said for all space pages so it would seem only a few finite number redirect and nothing I change in .htaccess has any effect which leads me to believe there is something else within HumHub that doesn't appear to be documented anywhere.

I would appreciate some clarification and a point in the right direction as my SEO is suffering.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Can you recreate the redirect behavior on our demo hosting as well?
Normally, for custom pages, the URL should be correct without a trailing slash. 
Would be good if there were steps to reproduce.

**Comment by BaconTriple** [comment]
@luke- Are you asking me to set up a new demo to test with or?

I haven't amended any system files so am unsure why it uses a trailing slash on some but not others. Surely there is a way of forcing it to always using a trailing slash on every page except dashboard (as no alternate page exists at /dashboard/)

**Comment by luke-** [comment]
Yes, it would be good if we can somehow reproduce the behavior.

**Comment by BaconTriple** [comment]
I don't really have the resources to create a test instance of this. Could you clarify what part of Humhub controls redirection as something clearly overrides the .htaccess file within the apache2 folder

**Comment by BaconTriple** [comment]
![image](https://user-images.githubusercontent.com/97461220/164948251-d1a6107c-8863-45a5-a343-b2a96274f0f4.png)

Useful discovery here, I have used window.location.href to define var 'url' which is showing a trailing slash but the url bar does not so humhub is removing this for some reason.

**Comment by BaconTriple** [comment]
Is it an issue with this .htaccess file?

# check if RewriteModule is available
<IfModule mod_rewrite.c>

    Options +FollowSymLinks
    RewriteEngine on

    # uncomment to force https requests
    RewriteCond %{HTTPS} !=on
    RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/[0-9a-zA-Z_-]+$ [NC]
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

    # prevent httpd from serving dotfiles (.htaccess, .svn, .git, etc.) - except let's encrypt challenge
    RedirectMatch 403 ^/?\.(?!well-known/acme-challenge/[\w-]{43}$)

    # ensure permalink when url rewriting was enabled (index.php?r=content/perma&id=6 => /content/perma/?id=6
    RewriteCond %{QUERY_STRING} ^r=content(/|%2)perma&id=([0-9]*)$
    RewriteRule ^index\.php$ %{REQUEST_URI}/content/perma/?id=%2 [R=302,L]

    RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]

    # Sets the HTTP_AUTHORIZATION header removed by apache
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule .? - [L]

    RewriteCond %{HTTP_HOST} ^ichor-studios.com [NC,OR]
    RewriteCond %{HTTP_HOST} ^www.ichor-studios.com [NC]
    RewriteRule ^(.*)$ https://ichor-studios.co.uk/$1 [L,R=301,NC]
    
    RewriteCond %{HTTP_HOST} !^ichor-studios.co.uk$
    RewriteRule ^(.*)$ https://ichor-studios.co.uk/$1 [R=301,L]

    RewriteRule .? %{ENV:BASE}/index.php [L]
</IfModule>

# Config files from vendor should not be readable via browser
<FilesMatch "^(\.|composer\.(json|lock|phar)$)">
    <IfModule authz_core_module>
        Require all denied
    </IfModule>
    <IfModule !authz_core_module>
        Order deny,allow
        Deny from all
    </IfModule>
</FilesMatch>

**Comment by BaconTriple** [comment]
I've amended .htaccess within the www directory (which isn't visible so I didn't know it was there, it was only when trying to create the file did it open and show me contents)

Added the following:

    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule .? - [L]
    RewriteCond %{REQUEST_URI} ^/p/(.*)$
    RewriteRule ^(.*[^/])$ /$1/ [R=301,L]
    RewriteCond %{REQUEST_URI} ^/g/(.*)$
    RewriteRule ^(.*[^/])$ /$1/ [R=301,L]
