### ISSUE TITLE
Possibility to archive and lock comments on global contents (not in a space)

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5655]
### Is your feature request related to a problem? Please describe.

If you have a stream of global contents (not in a space), you cannot archive them or lock comments.

### Describe the solution you'd like

In [this `canArchive()` method](https://github.com/humhub/humhub/blob/10c8ee6702b1ab1196db6cb7366b3ed18e003493/protected/humhub/modules/content/models/Content.php#L430) and [this `canLockComments()` method](https://github.com/humhub/humhub/blob/10c8ee6702b1ab1196db6cb7366b3ed18e003493/protected/humhub/modules/content/models/Content.php#L787), replace:
```
        if (!$this->getContainer()) {
            return false;
        }
```

With:
```
        if (!$this->getContainer()) {
            return $this->canEdit();
        }
```

Tested successfully (archiving and locking comments works).
What doesn't work is `canPin()`. Needs investigation.

### Describe alternatives you've considered

Replace `$this->canEdit();` with another permission?

**Comment by funkycram** [comment]
I can do a PR if this solution is OK for you.

**Comment by luke-** [comment]
Sounds good!

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/5670

**Comment by luke-** [comment]
@funkycram Thanks!
