### ISSUE TITLE
Url '/directory/members' generates a yii\base\InvalidConfigException

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub#5658]
Since upgrading to version 1.11.0
PHP 7.4
Search engines call /directory/members and generate the log entry:
yii\base\InvalidConfigException: Object configuration must be an array containing a "class" or "__class" element. in humhub/protected/vendor/yiisoft/yii2/BaseYii.php:368
Stack trace:
#0 humhub/protected/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject()
#1 humhub/protected/vendor/yiisoft/yii2/base/Module.php(592): yii\base\Module->getModule()
#2 humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Module->createController()
#3 humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#4 humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#5 humhub/index.php(27): yii\base\Application->run()
#6 {main} 
It looks like a configuration error, but I didn't change the configuration after upgrading to 1.11.0.

**Comment by luke-** [comment]
Since 1.10 the Directory module is no longer available.

**Comment by luke-** [comment]
Do you have any leftovers in your configuration? In the Modules->Directory block?

**Comment by aronbos** [comment]
Yes,
        'directory' => [
               'guestAccess' => false,
        ],
I will remove it. Thank you!
