### ISSUE TITLE
Live chat thing? Help?

### ISSUE THREAD

**Issue by anonnymouse** [humhub/humhub#566]
Okay so I have managed to get HumHub installed and such and have installed the custom pages add on, I was wondering how I would be able to integrate a live chat box into the site.

for example I found this : http://candy-chat.github.io/candy/#showcase

But I do not know how I would get that to appear on the site, I understand I could extract it to my webserver and have it all sitting up there but it wouldntbe on the humhub site if that makes sense?

Could anybody help because I just dont know

**Comment by Linusscout** [comment]
Hello .. over the plugin "Mail" you can open a Group Channel ;)

**Comment by anonnymouse** [comment]
Thanks Linusscout, I tried but that only really enabled sending messages to more than one person, I mean like a live chat-With the candy chat thing you get admin controls and such, I want to be able to integrate this as like a public place on the site where anybody logged in can come and discuss without using mail and meet new people, but its just getting it to work that isnt happening haha

**Comment by Lokke** [comment]
candychat needs a xmpp server running on your machine

**Comment by Lokke** [comment]
if u would run a xmpp service like on facebook - try this one ;)
https://github.com/sualko/jsxc

**Comment by WASasquatch** [comment]
You simply need to install the "Custom Pages" module, and link your chat via the iframe type of custom page. You can then install any sort of chat system and link it.

**Comment by anonnymouse** [comment]
Yeah but how would I do so? I am really very new to this

**Comment by WASasquatch** [comment]
This is for HumHub support issues. Issues with installation of [other chats](http://candy-chat.github.io/candy/#showcase) should be taken up with their issue/support pages. 

Under Administration -> Modules -> (Browse Modules Online) Custom Pages -> Click "**Install**" 
Under Administration -> Modules -> Custom Pages -> Click "**Enable**"
Under Administration -> Custom Pages -> Add a new custom page -> Select iFrame for "**Type**" and enter the **URL** of the chat you have installed. 

If your chat requires special PHP implementation you will have to create a module. Read through the documentation and check out the [example module](http://github/humhub/humhub-modules-example-module)

You can also try my [Custom Pages Extended](http://github.com/WASasquatch/humhub-modules-custom-pages-extended) which allows you to add **PHP** based pages, passing user information which can be used for chats as nicknames, etc.
