### ISSUE TITLE
Custom Modules marked as Official

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5660]
See: https://community.humhub.com/s/module-development/post/post/view?id=14387

v1.11

**Comment by yurabakhtin** [comment]
@luke- We have there the code:

```php
if ($onlineModule->isProOnly) {
    $this->_status = 'professional';
} else if ($onlineModule->isFeatured) {
    $this->_status = 'featured';
} else if (!$onlineModule->isThirdParty) {
    $this->_status = 'official';
} else if ($onlineModule->isPartner) {
    $this->_status = 'partner';
} else if ($onlineModule->isDeprecated) {
    $this->_status = 'deprecated';
} else {
    $this->_status = 'none';
}
// TODO: Implement new status detection
```

I.e. if the module has no `isThirdParty` then it is detected as "Official". Probably we should have the option as `true` when it is not defined, what do you think?

**Comment by yurabakhtin** [comment]
@luke- I mean a fix like this https://github.com/humhub/humhub/pull/5664.

**Comment by luke-** [comment]
@yurabakhtin Thanks, the PR should solve the problem. Maybe we should improve the API response in the future a bit.
