### ISSUE TITLE
LDAP username

### ISSUE THREAD

**Issue by vpean** [humhub/humhub#567]
![csc](https://cloud.githubusercontent.com/assets/10041444/5660781/1de86e5e-975f-11e4-8e02-1289ae055fae.png)
Hi !
One of my LDAP members has a 3 letters long username and can not login.
This user is the only one who does not sync with your platform, but he does with our other webapps.
Actually, I can see an empty field user in the directory page, but nothing in the user list from admin area.
I did try to create his account manually, but then the registration module informed me that the minimum length for username is 4 letters.
Is there a way to disable this limitation, at least for LDAP directory members?

Thanks
VP

**Comment by l4red0** [comment]
Same problem here.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/56fba49eca91f37de3d67c9d9ad1823ed370d23e
