### ISSUE TITLE
Could not find underlying content or content addon record! in like/user-list.

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub#5676]
Humhub 1.11.0, PHP 7.4

I am getting this log entry, which occurs since a long time and it is therefore not related to the latest version.

Calling /like/like/user-list:

yii\web\HttpException: Could not find underlying content or content addon record! in /humhub/protected/humhub/modules/content/components/ContentAddonController.php:93
Stack trace:
#0 /humhub/protected/humhub/modules/like/controllers/LikeController.php(40): humhub\modules\content\components\ContentAddonController->beforeAction()
#1 /humhub/protected/vendor/yiisoft/yii2/base/Controller.php(179): humhub\modules\like\controllers\LikeController->beforeAction()
#2 /humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#3 /humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#4 /humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#5 /humhub/index.php(27): yii\base\Application->run()
#6 {main} 

Is this a configuration error on my side? Or is it a search engine just clicking? Or is it a problem in my database? Or is it a bug?

**Comment by luke-** [comment]
How do you call the user list?

**Comment by aronbos** [comment]
$_SERVER = [
    'REDIRECT_SCRIPT_URL' => '/like/like/user-list'
   ...
  'HTTP_FROM' => 'tech@babbar.tech'
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (compatible; Barkrowler/0.9; +https://babbar.tech/crawler)'
  ...

So it is a search engine that somewhere picks up this url and generates a [yii\web\HttpException:500] yii\web\HttpException:

Calling the url user-list directly will generate a Model & ID parameter required! screen.  (It has yet to be translated!) That is correct.

Sorry. I can not answer the question  how the crawler calls the user-list.

**Comment by luke-** [comment]
Seems that the crawler tries to open an Url of deleted content.
@yurabakhtin Can we drop a 404 in such cases?

**Comment by yurabakhtin** [comment]
@luke- I just changed base to `master`.

**Comment by luke-** [comment]
@yurabakhtin Can you please check, seems something is broken in the PR.
