### ISSUE TITLE
Denied users get e-mail informing them about their successful approval

### ISSUE THREAD

**Issue by Cpt-KeksMonster** [humhub/humhub#5679]
A similar issue was solved before but I am experiencing the exact same issue with 1.11.1 (closed issue: #4630)

### What steps will reproduce the problem?
**Deny** a user in Administration > "User Approval".

### What is the expected result?
User gets an e-mail informing him, that he was not allowed to access this humhub instance.

### What do you get instead?
An e-mail is send to the denied user telling him that he was approved.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.1
| PHP version      | 8.1

![grafik](https://user-images.githubusercontent.com/38458892/166639713-39f322f1-13e0-4ed7-8fa7-bd3afe604792.png)

**Comment by yurabakhtin** [comment]
@luke- I confirm the bug was on press button "Decline all selected", because there was wrong message used for email.
Fixed in PR https://github.com/humhub/humhub/pull/5683.

@Cpt-KeksMonster Thank you for the report!

**Comment by luke-** [comment]
@yurabakhtin Thanks for the quick fix!
