### ISSUE TITLE
People: Add Group Description

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5681]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/4736168/166695756-7431e57f-4f66-40ea-8446-e415ed4867b8.png)

**Comment by luke-** [comment]
@Semir1212 Would it be sufficient to simply not store a description in case you don't want it? Otherwise the description will not be used.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6188:

![group-desc](https://user-images.githubusercontent.com/6995524/227203042-bd779939-8498-4f67-b401-88f2533aa76c.png)
