### ISSUE TITLE
Possibility to change default images (banner, user, space and module)

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5684]
### Is your feature request related to a problem? Please describe.

It is not possible to change `static/img/default_xxx.jpg` images as they are overwritten on each Humhub update.
Moreover, in some Docker installations, this folder is not writable.

### Describe the solution you'd like

Create the `static/img/default` folder and move these 4 images inside.

Then, create the `@web-static-img-default` alias to this folder.
E.g.,in https://github.com/humhub/humhub/blob/d41aabbfb5e8f76cb38b2145ef1c5d36b1a7a46e/protected/humhub/libs/ProfileImage.php#L108:
`$path = '@web-static/img/' . $this->defaultImage;` would be replaced by `$path = '@web-static-img-default/' . $this->defaultImage;`.

This way, it will be possible in the configuration file to change the `@web-static-img-default` alias value to a custom folder on the server where we can upload custom images.

### Describe alternatives you've considered

In Settings -> Appearance, the same way we can change the logo, we could change these 4 default images.

**Comment by luke-** [comment]
This should already be possible via theme, unfortunately has not been documented.

Here is the new page about it: https://docs.humhub.org/docs/theme/default-images

**Comment by funkycram** [comment]
Great, that's fine, thanks for the doc!
