### ISSUE TITLE
LDAP not found users from subdirectory

### ISSUE THREAD

**Issue by dap1995** [humhub/humhub#569]
I used google translate:
Set up my ldap, but he only finds users specify the exact location.
![tree](https://cloud.githubusercontent.com/assets/8496735/5673998/ce92c42c-978a-11e4-88c3-623162dcb87f.png)

If I specify a previous directory to where users are no longer works.

The only way to get users find the setting is as follows:
OU=Usuarios,OU=TI,OU=Equipes,OU=Intersys,DC=domain,DC=local

contrary case: "Status: OK! (0 Users)"

Is there any other way to set up, is it any permission, is a problem?

I have other systems which was not me that set up using the same server and you can get all users. But perhaps the setting to another.

grateful

**Comment by adilmehmoodbutt** [comment]
How can i  migrate Gitlab accounts from standard accounts to ldap users along with work history.

**Comment by chrismorehead** [comment]
Hi mate,

I had the same problem but I have manage to fix it. 

On line 216 of the document: humhub\protected\modules_core\admin\controllers\SettingController.php
You need to change:
Zend_Ldap::SEARCH_SCOPE_ONE
to
Zend_Ldap::SEARCH_SCOPE_SUB

This will then allow you to find all the users in the subdirectories within LDAP from the BaseDN.

I hope this helps... Good luck

**Comment by nunthu** [comment]
Thanks @chrismorehead  - Your suggestion helped me to solve issue of not being able to fetch all users in multiple OU.

**Comment by chrismorehead** [comment]
Glad I could help :)

**Comment by dap1995** [comment]
Thanks, you are amazing!

**Comment by almirdiasfilho** [comment]
Hello, friends I tried in every way, I changed the file indicated above:

On line 216 of the document: humhub\protected\modules_core\admin\controllers\SettingController.php
You need to change:
Zend_Ldap::SEARCH_SCOPE_ONE
to
Zend_Ldap::SEARCH_SCOPE_SUB


Still returns (Status: OK (0 users)!)

Podem me ajudar?
Estou usando servidor Active Directory.

Thanks!

**Comment by chrismorehead** [comment]
almirdiasfilho, all I can suggest is check your Base DN settings.
