### ISSUE TITLE
Bug: Galery - no permission to upload jpg file to my own galery

### ISSUE THREAD

**Issue by Meeques** [humhub/humhub#5692]
### What steps will reproduce the problem?
create a galery on your own profile (as administrator) and try to upload a .jpg file

### What is the expected result?
the .jpg file gets uploaded

### What do you get instead?
an error message:

![BugGalerieBerechtigung](https://user-images.githubusercontent.com/92315677/167827299-2f38788c-abaf-4ebd-92b2-1fea18649bbf.jpg)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.1
| PHP version      |  7.4.3
| Operating system | 

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

![BugGalerieBerechtigungKonsole](https://user-images.githubusercontent.com/92315677/167828590-3f5b500f-31b9-415e-9e76-cd7b9b37a63d.jpg)

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
@Meeques  Thanks for the report. Please use the following GitHub repo as issue tracker.
https://github.com/humhub-contrib/gallery/issues

 Does it work with other file extensions?
 Can you reproduce the behavior in our demo hosting?

**Comment by Meeques** [comment]
It does work on the demo version. So I guess it's a problem at our instance, with our konfiguration. I'll hand it to our administrator. Thank you!
