### ISSUE TITLE
Allow users to invite by link

### ISSUE THREAD

**Issue by samuk** [humhub/humhub#5699]
### Is your feature request related to a problem? Please describe.

People are unlikely to click on an anonymous/impersonal email.

### Describe the solution you'd like

When sending invites the subject and body of the email can be edited by the person doing the invitation

### Describe alternatives you've considered

None

**Comment by samuk** [comment]
@luke- Would you accept a pull for this? If so would you have particular needs around how it was implemented?

**Comment by luke-** [comment]
@samuk I would be a bit concerned that the emails could then be abused as spam if normal users can freely define the recipient and content.

Can you maybe make some mockups how you imagine it from the interface.

Otherwise I am open for a PR.

**Comment by funkycram** [comment]
Maybe this new field could be displayed only to space admin and moderators?

**Comment by samuk** [comment]
@funkycram it's the personal "Hi Julie this is a really great space, We're discussing XYZ on it and thought of you" that I think will create trust/click-throughs in the recipients.

I take Lukes's point on spam though. It might be a good use for a [badge/reputation system](https://meta.discourse.org/badges) like Discourse has, although I guess that would be a lot of work.

A moderator defined message would be better than the current message IMHO.

**Comment by funkycram** [comment]
If the field is displayed only to space admin and moderators, we don't need badge reputation.
I suggest having a pre-filled field such as this:
![image](https://user-images.githubusercontent.com/23310825/169854049-862f42c7-dd19-48ee-9cfa-f196b26f5f7f.png)

**Comment by samuk** [comment]
Yes looks good to me.

Having it only visible to mods/admin is less-good than having it exposed to users, but let's go ahead and do this if Luke's happy with it.

A user reputation system would be powerful in its own right, but let's discuss this elsewhere.

**Comment by luke-** [comment]
What do you guys think about an invite link that you can just share personally?

Somehow I'm not a big fan of the solution with the placeholders + only for mods/admins.

**Comment by samuk** [comment]
Sorry for slow reply.

I think an invite link would be a good thing to have.

I wonder if it could be presented with a mailto option? Something like;

----------

Share this link with your friends: https://somehumhubinstance.com/space/invitecode

Or send via email <a href="mailto:yourfriend@gmail.com&subject=Really%fun%social%networkl
&body=I'm%really%liking%this%new%social%space%come%join%mehttps://somehumhubinstance.com/space/invitecode</a>

Help to <a href="https://support.google.com/a/users/answer/9308783?hl=en>send mail from your Gmail</a>

**Comment by funkycram** [comment]
@luke- 
What do you think about this?

![image](https://user-images.githubusercontent.com/23310825/215120627-60bf7777-21ac-45c6-b714-6221df753c30.png)

![image](https://user-images.githubusercontent.com/23310825/215120301-f893034f-1127-4415-b55f-f720bdb9e041.png)

The token of this link nether expires, which allow to send the link to multiple recipients.
So this token is created only once (on space creation) and stored as a new column in the `space` table.
The name of the column could be `link_invite_token`.

**Comment by luke-** [comment]
I like the idea of an invitation link.

A few thoughts:

- Save the token as a space setting (`$space->settings->get('inviteToken');` instead of a new database field.
- It would be good if there were a button/link to regenerate the link.
- It would also be great if there was an invite link for non-space invites as well.

**Comment by funkycram** [comment]
Thanks. I totally agree.

- Should the "Regenerate token" button be displayed only to space administrators?
- Should I add an "Invite link" button here?

![image](https://user-images.githubusercontent.com/23310825/215144977-0b6e9e3b-786a-485b-9acd-2ce7913eb74e.png)

**Comment by luke-** [comment]
- Yes, the regenerate option should only available for Space admins

- A new "tab" would be cool here:
![image](https://user-images.githubusercontent.com/4736168/215149590-7bd14377-9c78-495e-b684-8cb3c7a11f9b.png)

- Option here: 
![image](https://user-images.githubusercontent.com/4736168/215149866-88097a47-fd0d-48ff-ac22-082b3d32c922.png)

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/6082

![image](https://user-images.githubusercontent.com/23310825/215764270-7ddb274c-300c-44af-a5b9-831cd84cd666.png)

![image](https://user-images.githubusercontent.com/23310825/215764151-6c55b8b1-f874-4c9c-bf2a-0a3ca7270a8f.png)

![image](https://user-images.githubusercontent.com/23310825/215764376-1b73784f-e29f-469d-bce2-3f34d3b9710f.png)

@samuk could you rename this issue to "Allow users to invite by link"? Thanks!

**Comment by luke-** [comment]
@funkycram Thanks for the cool feature. I have changed the "Create new" link a bit.
@Semir1212 Can you please review the wording from the screenshots?

![image](https://user-images.githubusercontent.com/4736168/216591854-a5b2e926-1c15-4f55-8e4c-ced51aff4617.png)

![image](https://user-images.githubusercontent.com/4736168/216591424-83e627e8-34d6-4f55-bcd0-51f564f89225.png)

**Comment by Semir1212** [comment]
@funkycram @luke- 

You can invite external users who are currently not registered via link. All you need to do is share this secure link with them. 

Send link via email -- > Send me the link

Create new --> Create new link

Confirm Action --> Create new link

The previous link... --> Please note that any links you have previously created will become invalid as soon as you create a new one. Would you like to proceed?

**Comment by funkycram** [comment]
Thanks Semir for you proposals.

About "Send me the link" I think we should use "Send the link via email" as the purpose of the button is to generate a pre-fill email in your default email client, and then you just have to enter the addresses in the "to" field:

![image](https://user-images.githubusercontent.com/23310825/216988151-aad821f2-7363-4573-a8ae-fba2273d0275.png)

![image](https://user-images.githubusercontent.com/23310825/216988288-6921167f-223d-4345-ae55-4acd59441ac0.png)

The text in the email is from https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/views/mails/plaintext/UserInvite.php and https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/views/mails/plaintext/UserInviteSpace.php

**Comment by Semir1212** [comment]
@funkycram Let's go with your text then. I thought it would work in a different way.

**Comment by luke-** [comment]
@funkycram @Semir1212 Thank you! The translations can now be changed on Translate platform.

**Comment by luke-** [comment]
@funkycram One more problem we've noticed a bit late, how should the email verification process work when registering with a link?  Presumably we still have to add a verification mask before?

**Comment by funkycram** [comment]
@luke- see https://github.com/humhub/humhub/pull/6082/files -> protected/humhub/modules/user/controllers/RegistrationController.php
And mainly this part:
![image](https://user-images.githubusercontent.com/23310825/217275110-bef2001e-9c88-41de-a85a-a85be1b09f2c.png)

**Comment by luke-** [comment]
@funkycram Hmm, the email address is not prompted or verified or have I missed something here? E.g. on our tests the users are created without an e-mail address:
![image](https://user-images.githubusercontent.com/4736168/217278384-a8127311-2d2b-4c7d-bacb-86a7d03cb61c.png)

**Comment by luke-** [comment]
@funkycram Please see my review comment.

**Comment by funkycram** [comment]
@samuk it's done, thanks to @luke- that added some small fixes and tests!
You can close this issue.

**Comment by samuk** [comment]
Thanks @luke- great to see this feature..

**Comment by funkycram** [comment]
@luke- bug fix: https://github.com/humhub/humhub/pull/6125

**Comment by luke-** [comment]
@funkycram Thanks!
