### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by max2020** [humhub/humhub#570]
Hello,

I have a problem when i post a status with an image, this image is in landsacape view instead of in portrait.

Could you help me ?

Thanks.

**Comment by aquibcn** [comment]
Thank you!

2015-03-30 6:03 GMT+02:00 Lucas Bartholemy <notifications@github.com>:

> Closed #570 <https://github.com/humhub/humhub/issues/570>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/570#event-268130976>.
>



-- 
Saludos

Maurici Torra
aquibcn@gmail.com

**Comment by aquibcn** [comment]
Thank you!
