### ISSUE TITLE
Confirm modal doesn't work for button

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub#5706]
On delete a Space `/s/space-url-name/space/manage/default/delete` the red button "Delete" doesn't show a confirmation box, so the form is submitted right after press on it.

There is a php code:

```php
Button::danger(Yii::t('SpaceModule.manage', 'Delete'))->confirm()->submit()
```

it is rendered as:

```html
<button type="submit" id="h264440w5" class="btn btn-danger" data-action-confirm="" data-ui-loader="">Delete</button>
```

---

I think the issue is here https://github.com/humhub/humhub/blob/master/static/js/humhub/humhub.action.js#L368:

```js
$(document).on('click', '[href][data-action-confirm]', function(evt) {
```

because the confirm modal works only for link with defined attribute `href`.

I think the `href` restriction should be removed and below code should be adapted for buttons as well, because currently the code looks like developed only for links, otherwise it is strange why the `->confirm()` is used at least in the detected place.
It should looks like this:

![confirm_button](https://user-images.githubusercontent.com/6995524/168797383-8ad43d03-bbfc-443c-8103-5182d5bf633f.png)

@luke- Do you agree to make it works? Maybe do you remember a version when the button worked like my screenshot above?

**Comment by yurabakhtin** [comment]
PS: I detected the bug working on the issue https://github.com/humhub/hostinginfo/issues/1

**Comment by luke-** [comment]
@yurabakhtin Sounds good, agree with it! Can you then please also include the confirm at the user part?

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5719, also added the confirmation on user deleting.
