### ISSUE TITLE
Where are the tab menu items stored?

### ISSUE THREAD

**Issue by manulitopetito** [humhub/humhub#571]
Hi! 
I wanted to change some menu-items. Where are they stored?
I looked into the database, and the files topNavigation.php etc, but couldn't find the items. 

thank a lot!

**Comment by andystrobel** [comment]
Please take a look at: https://github.com/humhub/humhub/blob/master/protected/docs/guide/developer/menus.md

**Comment by elbotho** [comment]
Link not working any more
