### ISSUE TITLE
Mail not send on Forget Password

### ISSUE THREAD

**Issue by v16vishal** [humhub/humhub#572]
I'm using regular "php sendmail" for sending mail on forget password. It redirects to success page but no mail received by users.

**Comment by andystrobel** [comment]
It sounds like a configuration issue. Please provide some information about your OS, PHP version etc. and check your logging files...

**Comment by v16vishal** [comment]
![aviation connect2](https://cloud.githubusercontent.com/assets/10474700/5691707/36c9c1d8-98fa-11e4-9cce-90b3e4746bd3.png)

**Comment by bastrian** [comment]
Unable to reproduce it. Tryed it with 3 different SMTP Server (Own SMTP, Google and Yahoo)

**Comment by hederzapatero** [comment]
I have a similar problem, I configured the smtp, and with smtp configured it gives error , I don't receive the email to register a new user on the network my configuration are:
Apache Version	2.2.29
PHP Version	5.4.37
MySQL Version	5.5.40-cll
And my SMTP are SSL/TLS
