### ISSUE TITLE
User Picker allows custom Input

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5724]
In the latest version, somehow it has come that now arbitrary values are accepted in the user picker.

![image](https://user-images.githubusercontent.com/4736168/170697965-021e3bb5-0696-4a62-ac97-9607e2385911.png)
![image](https://user-images.githubusercontent.com/4736168/170697972-eabde7ab-c2f0-4671-ac6e-def408981a9e.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5725, the bug was created here https://github.com/humhub/humhub/pull/5548/files#diff-55845c98784682c2415ffd1071e11c82a159791b010c9b6d206c871386278d58R374.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
