### ISSUE TITLE
Incorrect time indication

### ISSUE THREAD

**Issue by Linusscout** [humhub/humhub#573]
The Time on Mail Messages or Comments and Posts is wrong ... I have a deviation of 6 hours. How can i change the Time or Timezone ?!

**Comment by mrluisiko99** [comment]
There is a tutorial: https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/timezones.md

**Comment by WASasquatch** [comment]
User set timezones would probably be the best option as part of profile settings. This should not need to be manually set. 

My Apache, and PHP timezones are my timezones, HumHub is using Los Angelas, but still has a deviation of 6 -12 hours.

**Comment by sithik** [comment]
this issue is still happening

**Comment by funkycram** [comment]
Same for me, I have tried all the indications (timezone on the server, timezone in the php configuration, timezone in the humhub settings) and still have the problem...
Thanks

**Comment by Felli** [comment]
Did you also set your own profile timezone?

**Comment by funkycram** [comment]
Yes. UTC+1 is configured in :
- /user/account/edit-settings (my profile)
- /admin/setting/basic (general settings)
- the server (Ubuntu 16.04) : `dpkg-reconfigure tzdata`
- `/etc/php/7.1/apache2/php.ini` (apache reloaded of course)

Posts and comments display ` about an hour ago ` when it is just posted.
Thanks.

**Comment by buddh4** [comment]
@funkycram make sure your database timezone is correct.

**Comment by funkycram** [comment]
That's right ! My MySQL timezone is set to get the timezone of the SYSTEM, but it take the value when the MySQL server starts. So I had to restart MySQL after setting the system timezone :

1- `dpkg-reconfigure tzdata`
2- `service mysql reload`

Thanks for your help !

**Comment by Tie-fighter** [comment]
Is there a solution for webspace hosted solutions where one cannot restart the MySQL server?

I hope you don't mind my asking, but what is the purpose of the profile timezone?

**Comment by theankush** [comment]
Any update on how to get it corrected on a shared host?

**Comment by luke-** [comment]
@Kaor It should be sufficient to correct the server timezone under (Adminsitrator -> Settings).

**Comment by Kaor** [comment]
arg no, post dates are incorrect.
I change server timezone and user profile timezone but i have incorrect dates.
I really don't understand why

**Comment by olantrust** [comment]
Same problem here. Set all users and server timezone equally: each user post shows up as an hour earlier than it was sent (only to other users, the sending user sees the correct time.)

NB This also seems to mess up desktop, web, and mobile notifications as a consequence - they are slow to appear and sporadic, and no mobiles notifications

**Comment by diego22100** [comment]
Hi, i had the same problem, i searched an issue and finally found it :

I am in France, when i am adding a post, i saw the post date with -6 hours.

So i have configured my timezone in my server (UTC+2 Europe/Paris) and for humhub i have choosen (UTC-4 - America/Detroit) and now it works for me; post dates are correct !

To find UTC that you must choose, you must do it : 

- put the UTC of your official timezone (for me **UTC+2** Paris) in your server 
- AND YOU HAVE TO SUSTRACT the time that you see on post date (for me it was **-6 hours**),
- so **UTC+2**  -   **UTC -6**
- so you must choose an UTC with -4 in Humhub choices

Hope that you have understand, i thin it will help you !

**Comment by olantrust** [comment]
@luke- this still seems to be an issue.
Could you reopen please?

We're using the shared SAAS server, with all users set to London time (UCT+1 at present), and posts on the MOBILE app show as an hour or two hours earlier, but on the webapp show at the correct moment!

This also stops mobile notifications working (since the posts are deemed to have arrived hours ago!)

**Comment by buddh4** [comment]
@olantrust you mean you are hosting in the humhub cloud?

**Comment by olantrust** [comment]
> @olantrust you mean you are hosting in the humhub cloud?

Yes sorry, we're hosted in the Humhub cloud... You think it's more a bug with the server set-up there, than the software?

**Comment by buddh4** [comment]
Did you change the timezone in the humhub backend?

**Comment by olantrust** [comment]
> Did you change the timezone in the humhub backend?

It didn't work without any changes.
(Set it to London time when setting-up account, and tried to change it in settings, and individually for users, the time difference shifted, but still incorrect.

**Comment by buddh4** [comment]
I will have a look tomorrow, usually the timezone should be aligned with the server timezone, not sure why this can be changed on the hosting instances. Since the calculation is done in the frontend either the browser is using a wrong timezone or the date format used is wrong.

**Comment by buddh4** [comment]
@olantrust Can you please open a support ticket to hello@humhub.com they will guide you to the right setting. Just as additional information:

- New posts are saved in in the timezone used by the database, therefore the configured timezone in the backend needs to match the database timezone and system timezone.

- The time indication in posts and notifications are calculated in the frontend. Therefore I assume that there is a problem with either your desktop or mobile browser determining the right timezone.

**Comment by dinkoduric** [comment]
Installed everything and after two days I noticed that on all posts date and time are incorrect!!
Server time is local.
In settings  Default Timezone & Server are also local.
No matter what I set, even if I tried to use [diego22100](https://github.com/diego22100) advice, nothing.
Time is shown as -2 hrs
THIS IS SERIOUS ISSUE!!!
