### ISSUE TITLE
HTML editor for systemadministrators

### ISSUE THREAD

**Issue by Meeques** [humhub/humhub#5731]
### Is your feature request related to a problem? Please describe.
My Problem is, that I linked a word in a table on a wiki page to a website. On the wiki view, it's all fine, but in the stream, the link gets disconnected from the word. Then there is only half fo the link displayed and therefore it leads to the false website (the parent page).
See screenshot:
![Fehler_linkinTabelle](https://user-images.githubusercontent.com/92315677/171141555-293150f8-16eb-42d8-bb44-e6bfc98480b8.jpg)

### Describe the solution you'd like
I'd like an editor for html code of a post. This could be only available for systemadmins as to prevent foulplay.

### Describe alternatives you've considered
Editing the html code seems to be the easiest option.

**Comment by luke-** [comment]
See: https://github.com/humhub/humhub/issues/5729

**Comment by Meeques** [comment]
But the problem with the table still persists.. Then it's not a feature request but a bug report.
