### ISSUE TITLE
OEmbed Migration Failure

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5735]
2022-06-01 16:07:35 [182.52.83.98][1][ohfe5crqpajef722m7dvt34fnv][error][yii\base\ErrorException:2] yii\base\ErrorException: preg_match(): Unknown modifier '/' in /srv/humhub/protected/humhub/migrations/m220121_193617_oembed_setting_update.php:60
Stack trace:

**Comment by yurabakhtin** [comment]
@luke- Strange bug, I could not reproduce it, and I reviewed all regexps from here https://github.com/humhub/humhub/blob/master/protected/humhub/migrations/m220121_193617_oembed_setting_update.php#L18, they all look correctly, in all cases the delimeter `/` is escaped with `\/`.

**Comment by luke-** [comment]
I've added some debugging:

```
Match: /soundcloud\.com/

Match: /vimeo\.com/

Match: /slideshare\.net/

Match: /embed\.podcasts\.apple\.com/us/podcast//

PHP Warning 'yii\base\ErrorException' with message 'preg_match(): Unknown modifier '/''

in /srv/humhub/protected/humhub/migrations/m220121_193617_oembed_setting_update.php:62
```

**Comment by luke-** [comment]
Seems the related installation has some custom oembed providers.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5748

**Comment by luke-** [comment]
@yurabakhtin Thanks!
