### ISSUE TITLE
Cannot approve user

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5736]
### What steps will reproduce the problem?

- Try to approve user
- Success message appears
- User is not approved

### What is the expected result?

- Show error or approve user

- Check if Save is "true":
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/admin/models/forms/ApproveUserForm.php#L161

- Following error 
```
(
[language] => Array
(
[0] => Language is valid..
)
)
```
When language is set to `language: en-US`

**Comment by yurabakhtin** [comment]
@luke- Done in PR https://github.com/humhub/humhub/pull/5737.

**Comment by luke-** [comment]
@yurabakhtin Did you find the problem with the language?

**Comment by yurabakhtin** [comment]
@luke- 

> Did you found the problem with the language?

No, I could not reproduce the error.
On my side mew user is created with `en-US` in the column `language` of the DB table `user`, and I can approve it without error.

I think the error is related to the rule `['language', 'in', 'range' => array_keys(Yii::$app->i18n->getAllowedLanguages())],`, so when I change the rule for testing to `['language', 'in', 'range' => ['de']],` then yes I can reproduce the described steps.
If I test the same with new fix then I see the error and no email sending with approving report:
![test_lang_user](https://user-images.githubusercontent.com/6995524/172298883-f5b934a9-d828-4251-95e1-07164439f728.png)

So I think the PR fixes the issue, but it strange why the language `en-US` is missed on their side.

**Comment by luke-** [comment]
Could this be related to the "TranslationManager" where the Admin can restrict languages?

**Comment by yurabakhtin** [comment]
@luke- 

> Could this be related to the "TranslationManager" where the Admin can restrict languages?

I didn't find it, tested this case with steps:

- Register new user, so it was created with value `en-US` in column `user:language`
- Activate module "Translation Manager"
- Go to "Administration -> Translations -> Languages" and select only "Deutsch" and "Français"
- See the message with text:

```
Default language has been changed from "English (US)" to "Deutsch"!
Language of 3 users has been changed to default "Deutsch" because they used the disabled languages!
```

- Check the values in the column `user:language` were updated to `de` for all users
- Go to approve the new registered user: it is run without error, so the user is approved and email message is received.

**Comment by luke-** [comment]
@yurabakhtin Thanks for testing. Then we will monitor the behavior further.
