### ISSUE TITLE
Cannot use clean url for modules that are dedicated for user module.

### ISSUE THREAD

**Issue by rifaideen** [humhub/humhub#574]
@andystrobel  and @luke-  I have developed album module. it little similar to fb photo management. so this module can be enabled or disabled by each individual user and everything works fine when using get format in the UrlManager configuration. If I use clean url i.e path format of UrlManager. humhub generates the following url __localhost/rifaitechlabs/index.php/u/admin/album/view/id/11__ so when I click this link I cant reach the album page with this url causes this error The system is unable to find the requested action "id". I am use\ing the proper way to generate the url's. If I enter the url like this __localhost/rifaitechlabs/index.php/u/admin/album/view?id=11__ so tell me how to enable this. here is my [repo](http://github.com/rifaideen/humhub-modules-album/)

**Comment by luke-** [comment]
Sorry, I didn't get it. Could you meanwhile solve this problem?
