### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by uab22** [humhub/humhub#5755]
If translation is not appropriate as a topic here, please move or delete.

'Most active users' has in Norwegian been mistranslated to say the equivalent of 'Most numerous active users' (which is obviously nonsense). Instead of 'Flest aktive brukere' it should say 'Mest aktive brukere'. Thanks

**Comment by ArchBlood** [comment]
You should use the translation site where this should be able to be fixed, there should also be a module repo as well for this module.

https://translate.humhub.org/

**Comment by uab22** [comment]
Thanks
