### ISSUE TITLE
Approval button doesn't save group

### ISSUE THREAD

**Issue by antho2305** [humhub/humhub#5756]
### What steps will reproduce the problem?
When an user is waiting for approval, if I click in the green approval button it does not save group in user profil, while if I use the pencil toggle it works.

### What is the expected result?
Using the green approval button should save the group.
### What do you get instead?
The group is not save
### Additional info
Note that is was perfectly working before the update.

Here are somes screenshots.

**If I use the pencil toggle and set account user manually it works and in any case I see the group using this toggle.**
![workflow1](https://user-images.githubusercontent.com/40645459/173227414-e74a67b4-fd4e-493a-8261-9919046299aa.jpg)

**But if I use the green approval button to validate user, it doesn't save the group**

![workflow2](https://user-images.githubusercontent.com/40645459/173227440-8cec9b18-fac0-4daf-be7b-9129921946e2.jpg)

I tried to select the "pencil toggle" see that the group was present then click return and use the green approval button doesn't work too.

In parameters, defaut group is set as defaut and visible (or not same issue). I tried everything. No errors in the log system. 
Moreover, if I use the pencil toggle to validate users they don't receive the mail...

| Q                | A
| ---------------- | ---
| HumHub version   | 1.1.2?
| PHP version  8    | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- I have tested and reviewed the code and find the default group is assigned only at registration time.
I don't  find that default group was assigned at approving time in previous versions.

I could not find how a default group can be unassigned from user after registration, because the group field is required.

We can implement an additional assigning of the default group at approving time if user has no group by some reason, do you agree this?

**Comment by luke-** [comment]
@yurabakhtin Ok. Please commit it to my open PR. The additional assign check will be added to the private method here?
https://github.com/humhub/humhub/pull/5757/files#diff-d3a4745ae7c92bb2ed3212a38c146f5f29268cf40a693d007f752f679a1f52abR617

**Comment by yurabakhtin** [comment]
@luke- Yes, I think there is a good place in the private method. Done in commit https://github.com/humhub/humhub/pull/5757/commits/50d1d4803f0e1070cf2776deec84d4ca64c9462b.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
@antho2305 Should be fixed with 1.12+
