### ISSUE TITLE
Not being able to modify the widget view in themes

### ISSUE THREAD

**Issue by JSharma4BTS** [humhub/humhub#5758]
I am trying to change the look of the way a notification appears in an email, and the core file that is in charge of this is called mailbutton.php (C:\wamp64\www\connect\protected\humhub\widgets\mails\views\mailButton.php), however, I am unable to find a location in themes where the changes I make in the view file are displayed. The changes work when modifying the core file but not when I try to edit it in themes.  After trying several different locations, I asked the HumHub community where I should put mailbutton.php in themes and they said C:\wamp64\www\connect\themes\bst1\views\widgets\mails\mailButton.php.  However, that is a location I already tried and it did not work.  So it seems like there is an internal error within HumHub where the widget view in humhub\protected\widgets\mails\views cannot be modified from the theme.  

| HumHub version: 1.11.1
| PHP version: PHP 7.4.26 (cli) (built: Nov 16 2021 18:15:31) ( ZTS Visual C++ 2017 x64 )
| Operating system: Windows 10 Enterprise, 64-bit operating system, x64-based processor
![Picture of Path](https://user-images.githubusercontent.com/107417293/173380795-8cb5b8da-4d1a-44cd-a5dc-c309cd516d56.PNG)

Thank you.

**Comment by luke-** [comment]
Did you tried following path: `/themes/bst1/views/humhub/widgets/mails/views/mailButton.php`

See examples here: [/themes/HumHub2/views/humhub/widgets/mails/views](https://docs.humhub.org/docs/theme/views#examples)
