### ISSUE TITLE
Searching users

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#576]
I have a user with the same name used in her user title. So it shows her name twice. This user is also ironically not searchable with the User / Space search. Everyone else is though.

Example image with user picked up by my Random User Module: http://i.imgur.com/OyMvY2j.png

**Comment by luke-** [comment]
Maybe this is a problem with your Random User Module?

e.g. the user is not confirmed yet or disabled

**Comment by WASasquatch** [comment]
Random User module is seperate from seaech and uses its own DB call. Not sure how static PHP can interfere with JavaScript.

**Comment by luke-** [comment]
No, i mean maybe the Random User module DB call fetches a user which is e.g. disabled.

You can also try to rebuild the search with   "yiic search_rebuild"

**Comment by WASasquatch** [comment]
Well that's unrelated but thanks for pointing that out. How would I go about checking if a user is validated?
