### ISSUE TITLE
Notifcations, Posts & Database Importing

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#577]
I was unable to update HumHub via the update feature, and had to unfortunately install a new version. 

I had to dump all content besides users. Now when activity is posted, the notifications will not load any notifications. When I imported the all data, the dashboard would not load as well, so I dropped ALL content besides the users. And now the notifications will not load new posts/comments/anything.

No code has been changed, so this must be a issue with imported users?

We need to have a database management tool to upload a database and all missing rows/fields be automatically entered into the upload with default values to prevent database failure from rows/fields not in the previous database. 

Currently if anyone has issues updating their HumHub they will NOT be able to recover their information. This has cost me my data twice now. 

I was able to fix this, by again, dumping all the content of the system. This time I manually added the users via the ACP, and manually updated their pass hashes. -__-

We achieved this on IP.Board by saving a skeleton of the database and comparing any import, and editing if necessary before actually applying the import. Requires extensive knowledge of file manipulation and Regex. I was not involved in this development so I am not sure where to begin.

**Comment by luke-** [comment]
Sorry, I don't fully get it.

To ensure your database structure is up to date you can use

yiic update
or
yiic migrate

**Comment by WASasquatch** [comment]
Both these do not handle the data and make sure it should actually add the data to prevent database failure. Again, I can't use `yiic update` because your system won't override half the views so I am forced to hardcode more then 80% of customization due to poor theme management.
