### ISSUE TITLE
Can't unpin a post 

### ISSUE THREAD

**Issue by Meeques** [humhub/humhub#5778]
### What steps will reproduce the problem?
Pin a post, try to unpin after several days/weeks

### What is the expected result?
Get the option "unpin"/"lösen" to unpin a post

### What do you get instead?
no option to unpin, see screenshot

### Additional info
![Bug_anpinnen](https://user-images.githubusercontent.com/92315677/176202760-62043a61-c39d-4ecb-809a-113d4ca64fa9.jpg)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.1
| PHP version      |  7.4.3
| Operating system |

**Comment by Semir1212** [comment]
@Meeques Please check whether you have the permission to "Manage Content" in that specific Space.

**Comment by Meeques** [comment]
@Semir1212 I did as an administrator but not as the owner. Giving myself permission as the owner did the trick, thanks!
