### ISSUE TITLE
User picker - option to remove single users missing

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#5780]
HH 1.11 / 1.12 beta

![image](https://user-images.githubusercontent.com/38326726/176453356-bc770034-7873-4a74-80fe-e9f815deee3f.png)

**Comment by luke-** [comment]
I am also a bit unsure, but sounds good. Can you please make the PR only in the Develop Branch?

**Comment by yurabakhtin** [comment]
@luke- Ok, I have reverted the changes in templates of picker - https://github.com/humhub/humhub/pull/5781, because I really cannot understand why we should disable this feature "remove item" when picker doesn't allow to add new items.
