### ISSUE TITLE
Custom route definitions for well-known paths

### ISSUE THREAD

**Issue by KarlKeu00** [humhub/humhub#5785]
### Is your feature request related to a problem? Please describe.
Currently, all .well-known requests are blocked (with the exception of the acme-challenge). For developers, it would be great if you could still define your own .well-known actions/pages/etc. (if the file does not really exist).
Some examples would be auto-configurations for CardDAV, CalDAV or OpenID. New pages, such as security.txt could also be added through modules.
Basically, it would be much easier to write modules that make the settings for the .well-known actions/pages/etc. available to the administrators as a GUI.

### Describe the solution you'd like
Two changes in the .htaccess file:
[New line 16](https://github.com/humhub/humhub/blob/fe5c3b5719cddb4d775cdb9debf3bec88f45e333/.htaccess.dist#L16): ```RedirectMatch 403 ^/?\.(?!well-known/.+$)```
[New line 36](https://github.com/humhub/humhub/blob/fe5c3b5719cddb4d775cdb9debf3bec88f45e333/.htaccess.dist#L36): ```<FilesMatch "^(\.(?!well-known)|composer\.(json|lock|phar)$)">```

The changes have the effect that .well-known URLs are also forwarded to the UrlManager if no file exists under this path. This means that it is now also possible to add new .well-known files quickly.

### Describe alternatives you've considered
Alternatively, each module would have to add its own RewriteRules ([example](https://github.com/KeudellCoding/HumHub-Modules-HumDAV/blob/37b734dc431bb127c64b6814a79d44117f8f7cda/controllers/AdminController.php)). Unfortunately, this is very error-prone if the user has edited his .htaccess file or does not use it at all.

**Comment by dantefromhell** [comment]
@luke- messages comment says `1.12`, the tag says `1.13`. I'm curious which is accurate? ;-)

**Comment by luke-** [comment]
@dantefromhell Ups, `v1.13`
