### ISSUE TITLE
User Title Truncate

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#579]
I have added a pull for a style change to add truncate class to style.css for user titles (and other strings to long for small areas like widgets and menus). 

Here is an example of the Random User Module truncaterandom class

http://i.imgur.com/wgtPkhA.png

**Comment by andystrobel** [comment]
Thanks @WASasquatch. Please make css changes always to the *.less files and compile it. Otherwise your changes will be lost during the next update.

**Comment by WASasquatch** [comment]
How do I compile it? You must remember this is web software and most will be using it from their browser and SFTP programs, not other 3rd party utilities. These features should be in the base admin system.
