### ISSUE TITLE
UK locale non functional

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#580]
Editing the local for UK, and the selecting English (UK) does not show any of the translations.

**Comment by luke-** [comment]
Please note the english uk locale is "en_gb".
"uk" is Ukrainian.

There are no generated language files for english (uk) at the moment.

**Comment by WASasquatch** [comment]
Thanks for that clarification. Should probably hide the English (UK) option. I made the "en_uk" folder in hopes it would take to that option because I noticed none generated.

**Comment by luke-** [comment]
I also create them next time.

The UK Locale is also used for date formats etc.

**Comment by WASasquatch** [comment]
+1

**Comment by cebe** [comment]
why is there an en_uk folder in the translations now? it should be en_gb. en_uk is not really valid or useful.

- http://intl.rmcreative.ru/tables?locale=en_gb
- http://intl.rmcreative.ru/tables?locale=en_uk

selecting the locale in the settings will use `en_gb` so there should be a folder for that. https://github.com/humhub/humhub/blob/1f28edb50650ddf1c300d5237197edf0f1abf115/protected/humhub/config/common.php#L107
