### ISSUE TITLE
Issue with Default routes

### ISSUE THREAD

**Issue by BaconTriple** [humhub/humhub#5801]
### What steps will reproduce the problem?
If you open '/protected/humhub/modules/space/models/space.php' and amend 'public $defaultRoute = '/space/space';' to 'public $defaultRoute = '/';' 
### What is the expected result?
That the space urls end with the space name not /space/space
### What do you get instead?
"Oooops... It looks like you may have taken the wrong turn."
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.2
| PHP version      |  7.3
| Operating system | Debian

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

Before migrating my website to a new host for reliability I had the following line set within the '/protected/humhub/modules/space/models/space.php' file:
public $defaultRoute = '/';

It worked as expected, it removed the '/space/space' from the url and instead presented as 'www.website.com/spacename'.

If I change the default route value to public $defaultRoute = '/'; then I get 'page not found' errors and no explanation as to why.

Please can someone let me know what I can do here?

As Luke was unsure of what I meant I will try to be as clear as possible:

- My website is www.ichor-studios.co.uk
- An example space I have set up is called Gangster Mice
- Before the migration of the site the URL to access this space was www.ichor-studios.co.uk/g/gangster-mice
- After the migration of the site the URL to access this space is now www.ichor-studios.co.uk/g/gangster-mice/space/space

The default route for spaces is set the exact same as it was before but humhub does not see it as a valid URL and instead gives a "Oooops... It looks like you may have taken the wrong turn." error.

To be clear this worked before moving the site as amending space.php's default route removed the additional /space/space from the URL.

A similar thing is occurring with the user profiles where they show as "https://ichor-studios.co.uk/u/Josh/user/profile/home" instead of "https://ichor-studios.co.uk/u/Josh" despite me changing the default route which worked on the previous install of humhub.

If you need further clarification please let me know.

**Comment by BaconTriple** [comment]
Guys is there any movement on this as it is broken and I need to know how to fix it. This is a bug

**Comment by ralfblask** [comment]
You don't have to change modules!

**Comment by ralfblask** [comment]
Make HumHub updates to get back clear code. We are at version 1.12.

**Comment by BaconTriple** [comment]
@ralfblask when it is set to the default options it presents the same issue, and that is that I cannot amend the default routes

**Comment by luke-** [comment]
@BaconTriple It is not intended that changes will be made in the default routes.

**Comment by BaconTriple** [comment]
@luke- as it stands the default routes are incredibly messy, having so many subdirectories is both not pleasing on the eye but more importantly it's detrimental to effective SEO.
