### ISSUE TITLE
Error 500 on database migration

### ISSUE THREAD

**Issue by antho2305** [humhub/humhub#5807]
### What steps will reproduce the problem?
Update to the humhub beta 1.12
### What is the expected result?
Error script fail at database migration and give an error 500 with no error message
### What do you get instead?
Humhub reload with error 500
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12 beta
| PHP version      | 8.0
| Operating system | windows 11

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Did you checked Administration --> Information --> Logging ?

**Comment by antho2305** [comment]
> Did you checked Administration --> Information --> Logging ?

@luke- I can't access anything I get an error 500 blank page so I can't access humhub anymore

**Comment by luke-** [comment]
The file /protected/runtime/logs/app.log  contains also error messages.

**Comment by shenrenguo** [comment]
type error: symfony\component\mailer\transport\dsn::__construct(): argument #5 ($port) must be of type ?int, string given, called in /var/www/xhub/protected/vendor/yiisoft/yii2-symfonymailer/src/mailer.php 

solution: change the $port defalut value to 25 from ''

**Comment by luke-** [comment]
@shenrenguo thanks for the info. I've patched this.

**Comment by antho2305** [comment]
Hi @luke- sorry for being late but couldn't update via the updater anymore. So I retried the update here is the error and got the same issue

[27-Jul-2022 17:18:52 Europe/Paris] PHP Fatal error:  Uncaught ValueError: class_alias(): Argument #1 ($class) must be a user-defined class name, internal class name given in /home/sc1infoconne/site/espoirdelame.org/social/protected/vendor/laminas/laminas-servicemanager/src/autoload.php:14
Stack trace:
#0 /home/sc1infoconne/site/espoirdelame.org/social/protected/vendor/laminas/laminas-servicemanager/src/autoload.php(14): class_alias()
#1 /home/sc1infoconne/site/espoirdelame.org/social/protected/vendor/composer/autoload_real.php(66): require('/home/sc1infoco...')
#2 /home/sc1infoconne/site/espoirdelame.org/social/protected/vendor/composer/autoload_real.php(56): composerRequireb241116ca0fd4e83656d43c99589b201()
#3 /home/sc1infoconne/site/espoirdelame.org/social/protected/vendor/autoload.php(7): ComposerAutoloaderInitb241116ca0fd4e83656d43c99589b201::getLoader()
#4 /home/sc1infoconne/site/espoirdelame.org/social/index.php(13): require('/home/sc1infoco...')
#5 {main}
  thrown in /home/sc1infoconne/site/espoirdelame.org/social/protected/vendor/laminas/laminas-servicemanager/src/autoload.php on line 14
