### ISSUE TITLE
Add a menu to remove all members of a space

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5808]
### Is your feature request related to a problem? Please describe.

If you archive a space, the members remain and still can access the space if they have the URL.
This is correct.
But in some cases, we need to remove all members of the space to only keep the contents as an archive.
If you have several thousand members, this is not possible manually.

### Describe the solution you'd like

In the "Manage members" page, add a button to remove all members of a space.
Clicking on this button will remove all members, including applicants and invitations, but excluding moderators and administrators.

If you agree, I can send a PR for this.

![image](https://user-images.githubusercontent.com/23310825/179707742-1d80d765-68c0-46e0-b6b9-4cabe7552223.png)

![image](https://user-images.githubusercontent.com/23310825/179713181-61790434-af0d-4f80-b4aa-21c2e99c9be5.png)

**Comment by luke-** [comment]
In principle, I like the idea, but the button is too prominent for this edge case.

Maybe we can introduce a dropdown menu (grey button) and list this as an option there. Later other modules or feature can also integrate in this menu.

What do you think?

**Comment by ArchBlood** [comment]
> In principle, I like the idea, but the button is too prominent for this edge case.
> 
> Maybe we can introduce a dropdown menu (grey button) and list this as an option there. Later other modules or feature can also integrate in this menu.
> 
> What do you think?

What if you do as what has been done in the admin section and use a checkbox grid for re moving users and add a select all option? Would have the best of both ideas.

**Comment by luke-** [comment]
@ArchBlood I don't know if that would work for thousands of users. It only works page by page.

**Comment by ArchBlood** [comment]
> @ArchBlood I don't know if that would work for thousands of users. It only works page by page.

You have a point there. :thinking:

**Comment by funkycram** [comment]
Yes, the dropdown menu is a good idea.
I tested with 7000 members on a cloud installed Humhub, it took 5 minutes to delete all members.
Do you think we should do it to do it with a queued job?

**Comment by luke-** [comment]
Yes, please use a queued job for this.

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/5842

![image](https://user-images.githubusercontent.com/23310825/184496308-947608f0-6b5b-4f04-8bc0-8548a6ef497b.png)

![image](https://user-images.githubusercontent.com/23310825/184496321-8cf50dab-5f52-4d62-b43d-683821c92365.png)

![image](https://user-images.githubusercontent.com/23310825/184496328-0bd85ace-4344-4daa-b1fe-594f07e746dc.png)

**Comment by luke-** [comment]
@funkycram Great, thanks that looks very good!

@Semir1212 Can you please review the messages?

**Comment by Semir1212** [comment]
@funkycram 

Text: All members excluding moderators and administrators **of this Space** will be removed. All pending invitations and membership requests will be terminated. Would you like to proceed?

Success message: Removal of members queued

**Comment by funkycram** [comment]
Thanks @Semir1212 . Done: https://github.com/humhub/humhub/pull/5842/commits/ec3ba1940729bd0e0d730729e6cdc2eb38fac5be

**Comment by luke-** [comment]
@funkycram Thanks! Merged!
