### ISSUE TITLE
Improve checkbox style on load page

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub#5809]
### What steps will reproduce the problem?

Load any page with checkbox settings.

### What is the expected result?

It would be good to see correct style for checkboxes right after page load, and not only after init some js code:

![checkbox_styles](https://user-images.githubusercontent.com/6995524/179774307-5f0b3ac8-4727-4692-a71d-e905f6d113f3.png)

### What do you get instead?

See first screen where checkbox styles are not same, I see this first 1-2 seconds after all other page styles were already loaded.
I guess some JS code modify the checkboxes so their style is changed.
I believe it is possible to apply styles together with other main theme styles, at least we can add simple `padding-left: ...px` in order to avoid the jumping labels of the checkbox.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11

**Comment by yurabakhtin** [comment]
@luke- Done in PR https://github.com/humhub/humhub/pull/5815.

I have done to apply the styles for all fields of `ActiveForm` at render time on server side, so there is no "jumping" after page loaded. However, I didn't remove the JS code that added the styles, because some checkboxes can be rendered from not `ActiveForm` like on this page:

![checkbox_not_active_form](https://user-images.githubusercontent.com/6995524/181000005-9d487230-47f7-476e-82f7-e284197251cd.png)

Should I fix this place too?

**Comment by luke-** [comment]
@yurabakhtin Yes, would be cool if you could solve it there too. If not a big deal.  Otherwise please have a look at my PR comment.

**Comment by yurabakhtin** [comment]
@luke- https://github.com/humhub/humhub/pull/5815#discussion_r930887202 - answer for your PR's comments.

> Yes, would be cool if you could solve it there too. If not a big deal.

Commit https://github.com/humhub/humhub/pull/5815/commits/b4a031c86b12f38221b1c1ceb0127a34b26d83eb:

For these checkboxes the yii class is used, I could not handle it from PHP side as I did before for `ActiveField`, so I did this from CSS side.
Really when I suggested to improve this I thought to fix this only from CSS side, and I had a plan to clear the JS code completely, but I didn't remove the JS code because the HTML structure what is generated by the JS code is used from external modules.

---

Before this PR it works like this:

- on PHP side the HTML code is rendered like this: `<label><input type="checkbox"> Some label</label>` (sometimes it can be rendered without `<label>`)
- then JS code modify the code to: `<label><input type="checkbox" class="regular-checkbox"> Some label <div class="regular-checkbox-box"></div></label>`
- so the real `input.regular-checkbox` is hidden, but the `div.regular-checkbox-box` is used as styled checkbox for check action

I.e. the JS code https://github.com/humhub/humhub/blob/master/static/js/humhub/humhub.ui.form.elements.js#L5-L141 is used only to add style classes `.regular-xxxxxx` and append some new html elements, but really they all are not needed, because all these styles can be implemented right with `input[type=checkbox]` as you can see in the second commit of the PR.

However I couldn't remove the JS code and all styles like `.regular-xxxxxx` because I find they are used by external modules in JS and CSS code, e.g. modules `wiki`, `calendar`, `meeting`, `tasks`, `spd-otf`, `external_calendar` use it.

---

In my first commit I decided to render all style classes `.regular-xxxxxx` right on the PHP side, so when page is loaded we already see correct styles and no need to wait when JS code does it.

But I didn't remove the JS code because it may be used for some checkbox/radio elements which are no rendered by `ActiveField`, and even after my second commit where we already see the correct style we cannot remove the JS code because it may be used by some external modules in JS or/and CSS code.
