### ISSUE TITLE
Force Password - Remove Existing Password if not exists

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5811]
If a user was created e.g. via REST Api and is forced to initally change the password. The dialog asks for existing password.
![image](https://user-images.githubusercontent.com/4736168/179808035-b6b10361-d041-45bc-aafb-ef6ad1903300.png)

Only ask for this is a password entry exists.

**Comment by yurabakhtin** [comment]
@luke- Could you tell me how you can create a user via REST API without password?
If I try this request https://www.humhub.com/en/marketplace/rest/docs/html/user.html#tag/User/paths/~1user/post without provided filed `password: newPassword` I get a message "New password cannot be blank.".
I.e. I can create a user only with password.
Also if you see the form to force a password then you are already logged in, but how do you log in without password?

**Comment by luke-** [comment]
@yurabakhtin e.g. when a user logs in and registers via OAuth2 (e.g. via GitHub) he has no password. But it can also happen with users created via module.

**Comment by yurabakhtin** [comment]
@luke- Ok, thanks for the additional info, I have tested it with module `auth-github`.
PR https://github.com/humhub/humhub/pull/5916.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
