### ISSUE TITLE
PHP 8.1 Deprecated Warning 'mktime(): Passing null to parameter #1 ($hour) of type int is deprecated'

### ISSUE THREAD

**Issue by liloumuloup** [humhub/humhub#5813]
### What steps will reproduce the problem?
I have errors caused by deprecated error related to `mktime` when lauching the cron or browsing the website on a brand new installation of Humhub.

* Install a brand new Humhub on a managed dedicated server from Infomaniak with PHP 8.1
* Test the cron execution : `/opt/php8.1/bin/php /home/humhub/protected/yii cron/run`
* Or browse on the "about" section of a profile
* Or some other pages but couldn't find exactly where

### What is the expected result?
Execution without the error

### What do you get instead?
When executing the cron manually : 
```
/opt/php8.1/bin/php /home/humhub/protected/yii cron/run Deleting old unassigned files... done. Deleting old notifications... PHP Deprecated Warning 'yii\base\ErrorException' with message 'mktime(): Passing null to parameter #1 ($hour) of type int is deprecated'

in /home/humhub/protected/humhub/modules/notification/Events.php:167

Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'mktime(): Passi...', '/home/clients/e...', 167) #1 /home/humhub/protected/humhub/modules/notification/Events.php(167): mktime(NULL, NULL, NULL, 5) #2 /home/humhub/protected/humhub/modules/notification/Events.php(148): humhub\modules\notification\Events::deleteNotifications(true, 2) #3 [internal function]: humhub\modules\notification\Events::onCronDailyRun(Object(yii\base\Event)) #4 /home/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event)) #5 /home/humhub/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('humhub\commands...', 'daily', Object(yii\base\Event)) #6 /home/humhub/protected/humhub/commands/CronController.php(130): yii\base\Component->trigger('daily') #7 /home/humhub/protected/humhub/commands/CronController.php(55): humhub\commands\CronController->runDaily() #8 [internal function]: humhub\commands\CronController->actionRun() #9 /home/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #10 /home/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array) #11 /home/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('run', Array) #12 /home/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('run', Array) #13 /home/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('cron/run', Array) #14 /home/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('cron/run', Array) #15 /home/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request)) #16 /home/humhub/protected/yii(29): yii\base\Application->run() #17 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.4
| PHP version      |  8.1.7
| Operating system | Debian GNU/Linux 8.11 (jessie)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

I also created a message on the community with some info, if needed : https://community.humhub.com/content/perma?id=257582

**Comment by liloumuloup** [comment]
I don't have these errors with PHP 8.0

**Comment by ArchBlood** [comment]
From PHP site;

> Calling mktime() without arguments is deprecated. time() can be used to get the current timestamp.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5816.

**Comment by liloumuloup** [comment]
Wow. Such a fast patch. Thank you very much.
I'm not familiar with your release cycle. May i have an estimation for the date when we will have a new release available ?
Kind regards.

**Comment by luke-** [comment]
@yurabakhtin Have you checked if there are similar or other PHP 8.1 problems?

**Comment by yurabakhtin** [comment]
@luke- I don't find other places where `mktime()` is used with `null` value in first param. (doc: https://www.php.net/manual/en/function.mktime.php#refsect1-function.mktime-changelog - since 8.0.0	first param `hour` is no longer optional)

---

I found another error on php 8.1:

![twig_error](https://user-images.githubusercontent.com/6995524/181198798-124bc9fb-6c5c-43bb-b673-4ed88c82228b.png)

PHP Fatal Error – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
During inheritance of Countable: Uncaught yii\base\ErrorException: Return type of Twig\Node\Node::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ...\humhub\protected\vendor\twig\twig\src\Node\Node.php:213

Fix is in the commit https://github.com/humhub/humhub/pull/5816/commits/e98b5bc1c2f034b27e98945f7a2a339ffbb3d56d.
