### ISSUE TITLE
ParseError after update to 1.12

### ISSUE THREAD

**Issue by molle100** [humhub/humhub#5819]
Every minute I get this error-code (ParseError)

ParseError: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2-symfonymailer/src/Mailer.php:30
Stack trace:
#0 [internal function]: yii\BaseYii::autoload('yii\\symfonymail...')
#1 /hp/cq/aa/ox/www/hh/protected/humhub/components/mail/Mailer.php(21): spl_autoload_call('yii\\symfonymail...')
#2 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/BaseYii.php(293): include('/hp/cq/aa/ox/ww...')
#3 [internal function]: yii\BaseYii::autoload('humhub\\componen...')
#4 [internal function]: spl_autoload_call('humhub\\componen...')
#5 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct('humhub\\componen...')
#6 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies('humhub\\componen...')
#7 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('humhub\\componen...', Array, Array)
#8 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\componen...', Array, Array)
#9 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#10 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/base/Module.php(766): yii\di\ServiceLocator->get('mailer', true)
#11 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('mailer')
#12 /hp/cq/aa/ox/www/hh/protected/humhub/modules/ui/view/bootstrap/ThemeLoader.php(46): yii\di\ServiceLocator->__get('mailer')
#13 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/base/Application.php(325): humhub\modules\ui\view\bootstrap\ThemeLoader->bootstrap(Object(humhub\components\console\Application))
#14 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/base/Application.php(271): yii\base\Application->bootstrap()
#15 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#16 /hp/cq/aa/ox/www/hh/protected/humhub/components/console/Application.php(90): yii\console\Application->init()
#17 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\console\Application->init()
#18 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#19 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#20 /hp/cq/aa/ox/www/hh/protected/humhub/components/console/Application.php(52): yii\console\Application->__construct(Array)
#21 /hp/cq/aa/ox/www/hh/protected/yii(28): humhub\components\console\Application->__construct(Array)
#22 {main}

Next ParseError: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2-symfonymailer/src/Mailer.php:30
Stack trace:
#0 /hp/cq/aa/ox/www/hh/protected/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/hp/cq/aa/ox/ww...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('yii\\symfonymail...')
#2 /hp/cq/aa/ox/www/hh/protected/humhub/components/mail/Mailer.php(21): spl_autoload_call('yii\\symfonymail...')
#3 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/BaseYii.php(293): include('/hp/cq/aa/ox/ww...')
#4 [internal function]: yii\BaseYii::autoload('humhub\\componen...')
#5 [internal function]: spl_autoload_call('humhub\\componen...')
#6 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct('humhub\\componen...')
#7 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies('humhub\\componen...')
#8 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('humhub\\componen...', Array, Array)
#9 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\componen...', Array, Array)
#10 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#11 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/base/Module.php(766): yii\di\ServiceLocator->get('mailer', true)
#12 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('mailer')
#13 /hp/cq/aa/ox/www/hh/protected/humhub/modules/ui/view/bootstrap/ThemeLoader.php(46): yii\di\ServiceLocator->__get('mailer')
#14 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/base/Application.php(325): humhub\modules\ui\view\bootstrap\ThemeLoader->bootstrap(Object(humhub\components\console\Application))
#15 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/base/Application.php(271): yii\base\Application->bootstrap()
#16 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#17 /hp/cq/aa/ox/www/hh/protected/humhub/components/console/Application.php(90): yii\console\Application->init()
#18 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\console\Application->init()
#19 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#20 /hp/cq/aa/ox/www/hh/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#21 /hp/cq/aa/ox/www/hh/protected/humhub/components/console/Application.php(52): yii\console\Application->__construct(Array)
#22 /hp/cq/aa/ox/www/hh/protected/yii(28): humhub\components\console\Application->__construct(Array)
#23 {main}

**Comment by luke-** [comment]
Sounds like a PHP version that is too old. Maybe also only with the Console PHP.

**Comment by molle100** [comment]
I've installed PHP Version 8.0.20.

**Comment by luke-** [comment]
Please make sure also the CronJobs are execute with PHP 8. The error indicates that the cronjobs/queue is excuted with a PHP 7.3 or earlier.

**Comment by molle100** [comment]
Thing is....where do I find the information? Where can I change the version?

**Comment by luke-** [comment]
Whats your current cronjob configuration?

**Comment by M4ggifixx** [comment]
I got the same Error with this Configuration: 
PHP - Version - 7.4.30
Console PHP - 7.2.34

Cronjob Config:
<?php

 exec("/usr/bin/php /www/htdocs/path/to/humhub/protected/yii cron/run >/dev/null 2>&1", $out, $result);

 echo "Returncode: " .$result ."<br>";
 echo "Ausgabe des Scripts: " ."<br>";
 echo "<pre>"; print_r($out);

 ?>

This is a shared hosting enviroment and this Configuration worked fine on HumHub Version 1.11.4 without --isolate=0.

Any Solutions?
Thanks

**Comment by ArchBlood** [comment]
> I got the same Error with this Configuration: 
> PHP - Version - 7.4.30
> Console PHP - 7.2.34
> 
> Cronjob Config:
> 
> ```
> <?php
> 
>  exec("/usr/bin/php /www/htdocs/path/to/humhub/protected/yii cron/run >/dev/null 2>&1", $out, $result);
> 
>  echo "Returncode: " .$result ."<br>";
>  echo "Ausgabe des Scripts: " ."<br>";
>  echo "<pre>"; print_r($out);
> 
>  ?>
> ```
> 
> This is a shared hosting enviroment and this Configuration worked fine on HumHub Version 1.11.4 without --isolate=0.
> 
> Any Solutions?
> Thanks

I'm not sure why it would work in v1.11.4 as it doesn't support PHP version 7.2, could have started around the time that you updated to v1.11.x and is just showing up more now

https://docs.humhub.org/docs/admin/requirements/#php-environment

**Comment by M4ggifixx** [comment]
> > I got the same Error with this Configuration:
> > PHP - Version - 7.4.30
> > Console PHP - 7.2.34
> > Cronjob Config:
> > ```
> > <?php
> > 
> >  exec("/usr/bin/php /www/htdocs/path/to/humhub/protected/yii cron/run >/dev/null 2>&1", $out, $result);
> > 
> >  echo "Returncode: " .$result ."<br>";
> >  echo "Ausgabe des Scripts: " ."<br>";
> >  echo "<pre>"; print_r($out);
> > 
> >  ?>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is a shared hosting enviroment and this Configuration worked fine on HumHub Version 1.11.4 without --isolate=0.
> > Any Solutions?
> > Thanks
> 
> I'm not sure why it would work in v1.11.4 as it doesn't support PHP version 7.2, could have started around the time that you updated to v1.11.x and is just showing up more now
> 
> https://docs.humhub.org/docs/admin/requirements/#php-environment

I just updated the Domain php to 8.1 and still got the same Error.  Deleted all Cronjobs, reconfigured them, still not working.

**Comment by molle100** [comment]
The error started exactly after the update from 1.11.4 to 1.12. Right away. I phoned my webhoster today and they explained to me that I have to execute the cron in an special PHP-Folder. I tried with opt/php80/var/www...
Parallel to that I installed the "Daemon Cron"-modul via Humhub. Now I use cron-job.org for executing the urls.
For now: Everything works fine again. The only thing: I don't know, if my cronjob with the webhost is configured in the right way. Anyway: The error-console is empty now.

**Comment by molle100** [comment]
The URLS are created by the "Cron Daemon"- modul and start with https. I just copied them to a cronjob within cron-job.org. It's quite easy to create a job there...

**Comment by optitsolutions** [comment]
here also.
PHP 7.4.x, 2 different Humhub installations - same error.
It has nothing to do with PHP 8 or PHP 7.3.

It is an version 1.12 related issue.

**Comment by M4ggifixx** [comment]
> here also. PHP 7.4.x, 2 different Humhub installations - same error. It has nothing to do with PHP 8 or PHP 7.3.
> 
> It is an version 1.12 related issue.

I came to the same conclusion.
Updated PHP CLI from 7.0.x to 8.0.20
HumHub PHP 8.1.7

I can't even Rebuild the Search Index without an Error. 
`InvalidArgumentException: Unsupported sendmail command flags "/dev/null"; must be one of "-bs" or "-t" but can include additional flags. in /path/to/humhub/protected/vendor/symfony/mailer/Transport/SendmailTransport.php:58`

**Comment by ralfblask** [comment]
If you have a look at Mailer.php Line 30, there is a questionmark before the variable `SymfonyMailer`. This is new since php 7.4 and defines, that the following variable can be `null`.

    23  class Mailer extends BaseMailer
    24  {
    25      /**
    26       * @var string message default class name.
    27       */
    28      public $messageClass = Message::class;
    29  
    30      private ?SymfonyMailer $symfonyMailer = null;
    31      private ?SMimeEncrypter $encryptor = null;

Your php and php_cli has to be >= 7.4

**Comment by M4ggifixx** [comment]
Hello, my daily Cronjob is working now.

I changed following Script Code:
` exec("/usr/bin/php /www/htdocs/path/to/humhub/protected/yii cron/run >/dev/null 2>&1", $out, $result);
`
to 
` exec("/usr/bin/php80 /www/htdocs/path/to/humhub/protected/yii cron/run >/dev/null 2>&1", $out, $result);
`
