### ISSUE TITLE
Reverse proxy Selftest

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5820]
Sometimes SSL or Hostname gets lost in some setups during Reverse Proxy Configurations.

It would be great to check somehow the configured BaseUrl / Browser URL / with the currently detected URL.

See: https://github.com/humhub-contrib/legal/issues/54#issuecomment-1200781799

**Comment by yurabakhtin** [comment]
@luke- Do you mean to display an error when saving of the setting "Base URL" is not equal to current URL?

![base-url](https://user-images.githubusercontent.com/6995524/192488575-50b605c9-ff81-4e71-a377-a1f9b25f6c9d.png)

**Comment by luke-** [comment]
A test here would be great:
![image](https://user-images.githubusercontent.com/4736168/193856815-8708f961-6f03-4245-8b20-03a465783273.png)


Cool would be a solution to somehow retrieve the current 'document.location` via javascript and compare it with the BaseURL (your screenshot).

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5886:

![check_base_url](https://user-images.githubusercontent.com/6995524/194032446-7d315a34-a6a0-49a6-b9d1-47e57613cc71.png)

> Cool would be a solution to somehow retrieve the current 'document.location` via javascript and compare it with the BaseURL (your screenshot).

I have done this with checking on server side from global array `$_SERVER`.
