### ISSUE TITLE
 content not full width in mobile view

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/humhub#5822]
![Bildschirmfoto 2022-08-01 um 11 05 49](https://user-images.githubusercontent.com/105652258/182114984-c02b0a04-700a-4c3c-bb10-e5864fd6b754.png)

The content should be centered and full width.  

![Bildschirmfoto 2022-08-01 um 11 10 58](https://user-images.githubusercontent.com/105652258/182115604-016d6a6f-7131-4ebd-b2ee-0b7100c8f25e.png)

The Code says "padding-left = 0" but no "padding-right = 0".
In order to set it to full width, add "padding-right = 0" to the code?

![Bildschirmfoto 2022-08-01 um 11 10 46](https://user-images.githubusercontent.com/105652258/182115637-3977ca16-a03f-4d0a-8150-09b662fd43ec.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5824.

**Comment by luke-** [comment]
@yurabakhtin Thanks, can you please take a look into the tests? (Also when not related to this PR)

**Comment by yurabakhtin** [comment]
@luke- It is a strange bug, because it can be fixed only by increase a waiting time to 30 seconds - https://github.com/humhub/humhub/pull/5824/commits/370222df4da3bb991ca4207c129e7da47a373b19.
