### ISSUE TITLE
 Unsupported sendmail command flags "/dev/null"; 

### ISSUE THREAD

**Issue by optitsolutions** [humhub/humhub#5826]
### What steps will reproduce the problem?
Rebuild the database index via frontend, admin area
### What is the expected result?
building new database index
### What do you get instead?
an error: 
I can't even Rebuild the Search Index without an Error.
InvalidArgumentException: Unsupported sendmail command flags "/dev/null"; must be one of "-bs" or "-t" but can include additional flags. in /path/to/humhub/protected/vendor/symfony/mailer/Transport/SendmailTransport.php:58
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12
| PHP version      | 7.4
| Operating system |

**Comment by M4ggifixx** [comment]
> ### What steps will reproduce the problem?
> Rebuild the database index via frontend, admin area
> 
> ### What is the expected result?
> building new database index
> 
> ### What do you get instead?
> an error: I can't even Rebuild the Search Index without an Error. InvalidArgumentException: Unsupported sendmail command flags "/dev/null"; must be one of "-bs" or "-t" but can include additional flags. in /path/to/humhub/protected/vendor/symfony/mailer/Transport/SendmailTransport.php:58
> 
> ### Additional info
> Q	A
> HumHub version	1.12
> PHP version	7.4
> Operating system

Same Error with PHP 8.1.

**Comment by luke-** [comment]
Can you please open the file "protected/config/dynamic.php" and post me the "mail" section here? 

Also, you can try, to  resave the mail settings at `Administration -> Settings -> E-Mail`.

**Comment by M4ggifixx** [comment]
`'mailer' => 
    array (
      'transport' => 
      array (
        'dsn' => 'native://default',`

**Comment by luke-** [comment]
Can you determine your `php.ini` `sendmail_path` value? e.g.
![image](https://user-images.githubusercontent.com/4736168/182680405-8bf03214-8018-418b-8a84-2234b0473692.png)

Another option could be to manually change the `dynamic.php` value to:

`'mailer' => array ( 'transport' => array ( 'dsn' => 'sendmail://default', ), ),`

**Comment by M4ggifixx** [comment]
I manually changed the dynamic.php and finally after 5 Days of bugfixing I'am done. 
Thanks a lot!

**Comment by luke-** [comment]
What did you changed?

**Comment by M4ggifixx** [comment]
> 'mailer' => array ( 'transport' => array ( 'dsn' => 'sendmail://default', ), ),

native to sendmail.

**Comment by smashm** [comment]
I have other error logging, but similar problems with queued things. Tested with PHP 7.4, 8 and 8.1.

Sending the testmail is only working with »Custom DSN -> sendmail://default« or »PHP (Use settings of the php.ini file)«, but not per »SMTP/SMTPS«. 

![Bildschirmfoto 2022-08-04 um 10 48 33](https://user-images.githubusercontent.com/60502320/182805300-4bafcecd-6583-47d7-8115-46ffaee5dd66.png)

The sendmail path differs from luke's one with **s**bin: 

![Bildschirmfoto 2022-08-04 um 09 59 00](https://user-images.githubusercontent.com/60502320/182806882-b6514484-e39d-4320-9cce-9a622ae3a1dc.png)

A fast desktop search shows, that the old swiftmailer lib includes this path, wether nothing similar can be found in the symfony folder:
![Bildschirmfoto 2022-08-04 um 10 23 15](https://user-images.githubusercontent.com/60502320/182807416-48559e60-aad2-4f8a-af60-137c9fdf8a2c.png) 

Regardless of the fact that the testmail can be sent, there are some logged errors. The first one is reducible by rebuilding the search index, the second/third one seems to be the result of the hourly tasks: 
![Bildschirmfoto 2022-08-04 um 08 33 59](https://user-images.githubusercontent.com/60502320/182807756-5353a465-5fec-469f-99d4-884a6ca4eb21.png)

**Comment by luke-** [comment]
@smashm I suppose that the sendmail command is not configured correctly in the PHP CLI Ini. Can you please post the output of `php -i | grep "sendmail"`

**Comment by smashm** [comment]
@luke 

:~$ php -i | grep "sendmail"
sendmail_from => no value => no value
sendmail_path => /usr/sbin/sendmail -t -i => /usr/sbin/sendmail -t -i
Path to sendmail => /usr/sbin/sendmail -t -i

**Comment by luke-** [comment]
@smashm Ah ok, you never did have the SendMail "/dev/null" problem though, did you?  

@M4ggifixx @optitsolutions Can you please post the output of `php -i | grep "sendmail"`?

**Comment by smashm** [comment]
@luke Not that I know of, nothing to find with /dev/null variations in the logs. 

Please remember, that there are still no problems with the 1.10.4 instance, which is running in the same environment without any errors. I think the probability that Hetzner has misconfigured the shared server is rather small.

**Comment by optitsolutions** [comment]
@luke  @smashm Yes, no problems with 10.x and 11.x instance on same environment. shared server from Hostnet.

**Comment by luke-** [comment]
@optitsolutions It looks like you have "/dev/null" as SendMail command in the PHP.ini of the Console PHP version. 

You can check with your hoster or use "sendmail://default" or another SMTP configuration.
