### ISSUE TITLE
CSS bug

### ISSUE THREAD

**Issue by SirbitoX** [humhub/humhub#583]
There is a bug on all textareas related to spaces or stream of user profiles in firefox! when you type a very long string, it wouldn't fit to the box!

**Comment by WASasquatch** [comment]
That is just text limits... You cannot post super long messages, or the JS begins cropping it.

**Comment by SirbitoX** [comment]
I didn't mean this limitation! When you type a long string greater than textbox's width without any spaces in firefox, it will write out of the textbox instead of going to new line. 
P.S. In chrome every thing is OK
firefox sample: 
![firefox](https://cloud.githubusercontent.com/assets/4799349/5708788/5a23fbd4-9aa9-11e4-9a09-766ebd11b552.PNG)
chrome sample:
![chrome](https://cloud.githubusercontent.com/assets/4799349/5708795/68703cc0-9aa9-11e4-960f-31657fab6cf0.PNG)

**Comment by WASasquatch** [comment]
Ahh, white-space.

**Comment by SirbitoX** [comment]
white-space didn't fix any thing but word-wrap did!
`word-wrap: break-word;`
Thanks.

**Comment by WASasquatch** [comment]
Haha woops that's what I meant for the first one haha.
