### ISSUE TITLE
Stack trace opening files.

### ISSUE THREAD

**Issue by dantefromhell** [humhub/humhub#5832]
I have the following stack trace in my humhub error logs

```
2022-07-30 13:58:11
[172.18.0.1][16][qaoefsdakg32evtc48bvgt372a][error][yii\base\ErrorException:8]
yii\base\ErrorException: Trying to get property 'displayName' of
non-object in
/var/www/localhost/htdocs/protected/humhub/modules/file/views/view/index.php:37
Stack trace:
#0
/var/www/localhost/htdocs/protected/humhub/modules/file/views/view/index.php(37):
yii\base\ErrorHandler->handleError()
#1
/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/View.php(347):
require('/var/www/localh...')
#2
/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/View.php(257):
yii\base\View->renderPhpFile()
#3
/var/www/localhost/htdocs/protected/humhub/modules/ui/view/components/View.php(220):
yii\base\View->renderFile()
#4
/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Controller.php(53):
humhub\modules\ui\view\components\View->renderAjax()
#5
/var/www/localhost/htdocs/protected/humhub/modules/file/controllers/ViewController.php(62):
yii\web\Controller->renderAjax()
#6 [internal function]:
humhub\modules\file\controllers\ViewController->actionIndex()
#7
/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array()
#8
/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(178):
yii\base\InlineAction->runWithParams()
#9
/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(552):
yii\base\Controller->runAction()
#10
/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(103):
yii\base\Module->runAction()
#11
/var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(384):
yii\web\Application->handleRequest()
#12 /var/www/localhost/htdocs/index.php(25):
yii\base\Application->run()
#13 {main}
```

The request URI is `/file/view?guid=c2f82755-3d76-4cb3-b61f-8de72fe42512`

The user reported the problem occured when clicking on a file, but the error was also transient and has since disappeared.

### What steps will reproduce the problem?
Unclear how to <s>reproduce</s> trigger the empty `updated_by` field. The error starts appearing at some point affecting a specific file <s>and show flaky behaviour. Most of the times users report they are unable to open the file, and in some rare cases one user can open the file while the error persists for others.</s> (turns out user was confused). All successive attempts to open this file fail with the stack trace. See details on possibly why below.

### What is the expected result?
File can be openen, no errors in logfile

### What do you get instead?
The overlay for file details opens, shows a loading animation and closes afterwards.
An error message saying "an unknown error has occured" appears on the bottom of the screen.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.2
| PHP version      | 7.4.29
| Operating system | docker

[EDIT] Updated with some corrections regarding reproducability.

**Comment by dantefromhell** [comment]
The document in question is a DOCX document, created via the OnlyOffice Humhub integration.

**Comment by dantefromhell** [comment]
Update after some more digging.

The error looks reproducible for all files that do not have a value set for `updated_by` in the `file` table.

> SELECT * FROM file WHERE updated_by IS NULL;

Looking at the code
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/views/view/index.php#L36
it seems the logic is not taking into account that the `updated_by` field can be `NULL`

```
> DESCRIBE file;
+----------------+------------------+------+-----+---------+----------------+
| Field          | Type             | Null | Key | Default | Extra          |
+----------------+------------------+------+-----+---------+----------------+
| id             | int(11)          | NO   | PRI | NULL    | auto_increment |
| guid           | varchar(45)      | YES  |     | NULL    |                |
| object_model   | varchar(100)     | YES  | MUL |         |                |
| object_id      | varchar(100)     | YES  |     |         |                |
| content_id     | int(11) unsigned | YES  |     | NULL    |                |
| file_name      | varchar(255)     | YES  |     | NULL    |                |
| title          | varchar(255)     | YES  |     | NULL    |                |
| mime_type      | varchar(150)     | YES  |     | NULL    |                |
| size           | varchar(45)      | YES  |     | NULL    |                |
| created_at     | datetime         | YES  |     | NULL    |                |
| created_by     | int(11)          | YES  | MUL | NULL    |                |
| updated_at     | datetime         | YES  |     | NULL    |                |
| updated_by     | int(11)          | YES  |     | NULL    |                |
| show_in_stream | tinyint(1)       | YES  |     | 1       |                |
| hash_sha1      | varchar(40)      | YES  |     | NULL    |                |
| onlyoffice_key | char(20)         | YES  |     | NULL    |                |
+----------------+------------------+------+-----+---------+----------------+
16 rows in set (0.002 sec)
```

Why only 2 files in this installation have a value of `NULL` for `updated_by` and other files dont I couldnt figure out though.

**Comment by ArchBlood** [comment]
@dantefromhell probably something to contact the maintainers of the module?

https://github.com/ONLYOFFICE/onlyoffice-humhub/issues

**Comment by luke-** [comment]
@dantefromhell I guess the problem was if the last_update user is no longer available. Can you please try my PR Change?

**Comment by dantefromhell** [comment]
@luke- 
From first tests #5833 looks good.

@ArchBlood 
There might be something about the onlyoffice module not updating the field under all circumstances, but as described not checking that an optional DB column has a value before accessing it is an issue too.

**Comment by dantefromhell** [comment]
@luke- 
Can you please elaborate on what you mean by
> the problem was if the last_update user is no longer available.

not available as in user deleted?

**Comment by luke-** [comment]
@dantefromhell Yes. e.g. Deleted, Soft Delete, maybe from Disabled/Blocked. There can be several reasons that a user model is not loaded.

**Comment by luke-** [comment]
Has the file been edited with anything? 

Onlyoffice handles this ok: https://github.com/ONLYOFFICE/onlyoffice-humhub/blob/master/controllers/BackendController.php#L164

**Comment by ArchBlood** [comment]
> Has the file been edited with anything? 
> 
> Onlyoffice handles this ok: https://github.com/ONLYOFFICE/onlyoffice-humhub/blob/master/controllers/BackendController.php#L164

That's something that I've been noticing of late, `empty()` or `!empty()` hasn't really been working since 1.10 for any module that uses this function in PHP, new Discord module can attest to that, even the Adsense module now affected by this issue, as it's used to hide the widget if not configured but still appears regardless. :thinking:

**Comment by luke-** [comment]
@ArchBlood That sounds really strange. `empty` a standard PHP function. I don't think the behavior has changed here...

**Comment by ArchBlood** [comment]
> @ArchBlood That sounds really strange. `empty` a standard PHP function. I don't think the behavior has changed here... 

The function is currently used here in the Adsense module, which is supposed to display a message to configure the module if `getClient()` hasn't been configured, this has been like this since the release of 1.10, with no fixes possible, I believe this is due to some kind of change within the core JavaScript that deals with containers.

I have also tested on fresh installs with the same problem occurring. The only thing that I have not tried yet is using `var_dump()` for this to identify the main issue. :thinking:

https://github.com/GreenMeteor/adsense/blob/master/widgets/views/adframe.php#L25

**Comment by luke-** [comment]
Hmm `empty()` should return a bool. So this line makes more sense:

` <?php if (!empty($module->getClient())): ?>`

**Comment by ArchBlood** [comment]
> Hmm `empty()` should return a bool. So this line makes more sense:
> 
> ` <?php if (!empty($module->getClient())): ?>`

Using this returns `NULL` if configurations are set and force the widget to display the admin message regardless.

To workaround this I was forced to use the following instead as for some reason `$module->getFunctionNameHere` wouldn't work as I wanted even though both function are linked up with `$client` & `$slot`;
`<?php if (empty($client && $slot)): ?>`
