### ISSUE TITLE
Fix DateFilter Test

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5834]
---
Please note the test https://github.com/humhub/humhub/runs/7720728730?check_suite_focus=true#step:18:1386 is broken again, I already increased the test time from 10 seconds to 30 seconds and some time it worked, but now I see the 30 seconds is not enough again, that's strange.

_Originally posted by @yurabakhtin in https://github.com/humhub/humhub/issues/5828#issuecomment-1207793593_

**Comment by yurabakhtin** [comment]
@luke- It seems I have found a solution, but I am not sure, because locally it works, probably we should re-run tests for the latest commit from the PR https://github.com/humhub/humhub/pull/5836 and it they will be executed without errors then you can merge it.

**Comment by luke-** [comment]
@yurabakhtin Cool, it seems to work.
