### ISSUE TITLE
iOS problem : Safari: Invalid regular expression: invalid group specifier name 

### ISSUE THREAD

**Issue by tosintech-web** [humhub/humhub#5840]
### What steps will reproduce the problem?
always load stream (dashboard).

### What is the expected result?
PC and Android have no problem but iOS (iPhone) safari shows an error on console.
![スクリーンショット 2022-08-12 3 58 59](https://user-images.githubusercontent.com/75475434/184219623-32b47cf7-a6d8-4cb6-8143-9f379d596475.png)

### What do you get instead?
I can see stream and it may not cause any problem.... I can't recognize... 

It may be related this article on stackoverflow, I think...

https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.0
| PHP version      |  7.4.x
| Operating system | iPhone 15.3, iPhone 15.6 Safari

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Is it likely that the problem is related to the ReadLater module? Can you please try it without the module?

**Comment by tosintech-web** [comment]
Sorry to late response.
I try with 1.12.1 & composer update today. Then, these Syntax Errors disappeared.
When I deactivated the ReadLater Module, the Syntax Errors does not be appeared.
And I activate the ReadLater Module again, the Syntax Errors does not be appeared, too.
The errors are resolved by updates. It is related to some modules installed with composer.

Thanks anyway. I close this issue.
