### ISSUE TITLE
Logging: No default level filters

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5850]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/4736168/186366687-25725141-a46c-43c4-97c0-ae2c37d8424e.png)

**Comment by yurabakhtin** [comment]
@luke- Do you mean to use the filter as empty by default, i.e. all levels will be displayed on page loading by default?

**Comment by luke-** [comment]
Yes

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5852
