### ISSUE TITLE
Internal links should not open in a new tab

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5853]
### What steps will reproduce the problem?

Create a new post and insert an internal link (e.g. a permalink of another content of the same Humhub).

### What is the expected result?

The link opens in the same page.

### What do you get instead?

The link opens in a new tab.

### Additional info

I already seen discussions about this problem, but I could not found where...

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.0

**Comment by ArchBlood** [comment]
See https://github.com/humhub/humhub-prosemirror/issues/61

**Comment by funkycram** [comment]
Thanks @ArchBlood ! So I close this issue, but we could leave it as closed in this humhub repository in case of future researches about this problem.
