### ISSUE TITLE
User approval after registration is not possible if the user's browser language is not available in Humhub

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5854]
### What steps will reproduce the problem?

Limit available languages (https://docs.humhub.org/docs/admin/translations#limit-available-languages) with the `allowedLanguages` param or with the Translation manager module (in /translation-manager/admin/languages).

In the users settings, tick "Require group admin approval after registration".

Create an account with a Browser having the `HTTP_ACCEPT_LANGUAGE` set to a language that is **not** in the available languages.

### What is the expected result?

When the admin approves the account, a email is sent to the user and the account is enabled.

### What do you get instead?

This message is displayed: "Could not approve the user!".

### Additional info

If you add the language of this browser in the available languages, then you can approve the user.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.1

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5865: I have done to don't check the lang column on approve action.

**Comment by luke-** [comment]
@yurabakhtin I think we need to fix this issue in several places: 

- When a user registers it should not be possible to select a deactivated language via the `HTTP_ACCEPT_LANGUAGE`.
- If a user has selected an unavailable language in the settings. Reset to the default language of the application. (Adminsitration -> Settings)

**Comment by yurabakhtin** [comment]
@luke- Ok, I have done this in the commit https://github.com/humhub/humhub/pull/5865/commits/daf376cc4c08d8f7d84aa1941e65b71243810d05.

**Comment by funkycram** [comment]
Thanks @yurabakhtin !
