### ISSUE TITLE
Email Stopped Working After 1.12.0 Upgrade

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#5856]
I was curious why nobody was visiting my HumHub site lately and attempted the e-mail Save & Test button from the Settings page.  The result was "Could not send test email."  Since the only recent server change was the upgrade to v1.12.0 it seems like it might be a HumHub issue.  The changelog says "New and improved email systems" which makes me even more suspicious.

When I click the eyeball icon in the password field on the same page, it fails to reveal the password.  Instead it displays `---invisible---` which makes that feature appear to be broken as well.  The eyeball icon works only when typing a new password, which is unintuitive.

Resetting the password also did not work.

**Comment by miqrogroove** [comment]
I couldn't find any information in the PHP log, but then I remembered there's an internal log under Administration > Information > Logging

Since the 1.12.0 upgrade I'm getting this persistently:

```
yii\symfonymailer\Mailer::sendMessage
Connection could not be established with host "ssl://<my host>:587": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by luke-** [comment]
We just had a similar case.
https://serverfault.com/questions/1099904/mail-server-sending-to-postfix-refusing-tls-connection-with-certificate-expired

It may be that with the new implementation invalid SSL certificates are now handled more strictly.

**Comment by miqrogroove** [comment]
Workaround Found:

By clearing the "Use SMTPS" checkbox on the Settings > Advanced > E-Mail tab, the v1.12 email subsystem becomes compatible with the same server that was in use with v1.11. 

It appears the HumHub configuration itself is not backward compatible.

**Comment by luke-** [comment]
@funkycram SMTPS is usually on Port `465` can you please test it with this port?

**Comment by funkycram** [comment]
@luke- thanks, indeed, Port `465` works with SMTPS.

So `e.g. 25 (for SMTP) or 587 (for SMTPS)` should be replaced with `e.g. 25 or 587 (for SMTP), or 465 (for SMTPS)`
![image](https://user-images.githubusercontent.com/23310825/188846325-751272e0-9b73-4a34-a5a2-89d6f70255c1.png)

And when migrating from Humhub 1.11 to 1.12, if the port was 587 on 1.11, SMTPS should be unticked on 1.12

**Comment by svigerske** [comment]
With Humhub 1.12.2, the text for the port number still suggests 587 for SMTPS, while it should be 465.

**Comment by luke-** [comment]
@svigerske Thanks, will be fixed in v1.13

**Comment by dreua** [comment]
Same here, the Protocol was apparently updated to smtps but port stayed 587, which doesn't and shouldn't work. Fixed by some head scratching and manually changing the port to 465.

**Comment by Duftorgel** [comment]
I have a similar issue with 1.15.0. I can't get email to work at all: "Could not send test email."
In the log file it says:

Connection could not be established with host "ssl://192.168.2.24:25": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A00010B:SSL routines::wrong version number

This is the same if i use SMTPS and port 465 and 587 and the checkbox for accepting selfsigned certificates.

**Comment by marc-farre** [comment]
> I have a similar issue with 1.15.0. I can't get email to work at all: "Could not send test email." In the log file it says:
> 
> Connection could not be established with host "ssl://192.168.2.24:25": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:0A00010B:SSL routines::wrong version number
> 
> This is the same if i use SMTPS and port 465 and 587 and the checkbox for accepting selfsigned certificates.

Duplicate of https://github.com/humhub/humhub/issues/6717
