### ISSUE TITLE
Dashboard shows internal error after update

### ISSUE THREAD

**Issue by blu-IT** [humhub/humhub#5858]
### What steps will reproduce the problem?

I updated my HumHub instance from v. 1.8.4 to the last recent version v. 1.12.1
I also updated the modules, everything went fine. But my dashboard stream now says "internal error". 
The rest of the system works. 

### What is the expected result?

A working dashboard stream.

### What do you get instead?

Dashboard shows "internal error".

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.1
| PHP version      |  7.4
| Operating system | Linux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

The logfile says:

```
yii\base\InvalidConfigException: Unable to locate message source for category 'DirectoryModule.views_directory_spaces'. in /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/i18n/I18N.php:201
Stack trace:
#0 /kunden/548428_64711/forum-test/protected/humhub/components/i18n/I18N.php(172): yii\i18n\I18N->getMessageSource()
#1 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/i18n/I18N.php(89): humhub\components\i18n\I18N->getMessageSource()
#2 /kunden/548428_64711/forum-test/protected/humhub/components/i18n/I18N.php(148): yii\i18n\I18N->translate()
#3 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/BaseYii.php(538): humhub\components\i18n\I18N->translate()
#4 /kunden/548428_64711/forum-test/protected/modules/recentspaces/widgets/views/_linkSpaces.php(33): yii\BaseYii::t()
#5 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/View.php(347): require('/kunden/548428_...')
#6 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#7 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#8 /kunden/548428_64711/forum-test/protected/modules/recentspaces/widgets/views/sidebar.php(26): yii\base\View->render()
#9 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/View.php(347): require('/kunden/548428_...')
#10 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#11 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#12 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Widget.php(242): yii\base\View->render()
#13 /kunden/548428_64711/forum-test/protected/modules/recentspaces/widgets/Sidebar.php(24): yii\base\Widget->render()
#14 /kunden/548428_64711/forum-test/protected/humhub/components/Widget.php(63): humhub\modules\recent_spaces\widgets\Sidebar->run()
#15 /kunden/548428_64711/forum-test/protected/humhub/widgets/BaseStack.php(88): humhub\components\Widget::widget()
#16 /kunden/548428_64711/forum-test/protected/humhub/components/Widget.php(63): humhub\widgets\BaseStack->run()
#17 /kunden/548428_64711/forum-test/protected/humhub/modules/dashboard/views/dashboard/index.php(28): humhub\components\Widget::widget()
#18 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/View.php(347): require('/kunden/548428_...')
#19 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#20 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#21 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#22 /kunden/548428_64711/forum-test/protected/humhub/modules/dashboard/controllers/DashboardController.php(81): yii\base\Controller->render()
#23 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex()
#24 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#25 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#26 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#27 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#28 /kunden/548428_64711/forum-test/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#29 /kunden/548428_64711/forum-test/index.php(25): yii\base\Application->run()
#30 {main} 
```

Any idea?

Thanks!

**Comment by blu-IT** [comment]
I found this issue here 

https://github.com/humhub/humhub/issues/1817

and a similar behavior in the field "Hompage URL". I change the values, but doesn't help.

**Comment by ArchBlood** [comment]
Could you provide what language your HumHub instance is in?

**Comment by blu-IT** [comment]
It is in german.

**Comment by ArchBlood** [comment]
> It is in german.

In your /protected/config/common.php file are there any entries related to the now deprecated core Directory module?

**Comment by blu-IT** [comment]
I don't think so. There is only this enty related to cron:

```
<?php

return [
'params' => [
    'dailyCronExecutionTime' => '18:00',
	],
];
```

**Comment by blu-IT** [comment]
Found thsi here in the documentation:

https://docs.humhub.org/docs/admin/updating-migration2

`The deprecated "Directory" module has now been removed. It must now also no longer be used in the custom configuration files.`

Where else could be files / entries related to the Directory module?

**Comment by ArchBlood** [comment]
Alright, here's a few questions

1. Did you upgrade your instance straight to 1.12 or update to update?
2. Did you use the updated module or manual update?

From looking at the issue you're having could you be using translation overwrites?

https://docs.humhub.org/docs/admin/translations/#overwrite-translation-messages

**Comment by blu-IT** [comment]
Hi,

thanks for your support!

> Alright, here's a few questions
> 
>     1. Did you upgrade your instance straight to 1.12 or update to update?

I did the upgrade update to update...
> 
>     2. Did you use the updated module or manual update?

...via the update module.

> From looking at the issue you're having could you be using translation overwrites?

What do you mean? If I have done own translation in that installation? I'am nor sure, but I don't think so. 

> https://docs.humhub.org/docs/admin/translations/#overwrite-translation-messages

So what else can I do?

**Comment by ArchBlood** [comment]
What modules are installed?

**Comment by luke-** [comment]
Seems you have a custom module called `recentspaces` which causes the problems. Can you please try to uninstall it?

**Comment by blu-IT** [comment]
> Seems you have a custom module called `recentspaces` which causes the problems. Can you please try to uninstall it?

YES! I had that module (v. 0.4) installed. After deactivating that module, the dashboard works again!

@luke- @ArchBlood Thanks a lot to both of you for your help!!!

**Comment by ArchBlood** [comment]
> > Seems you have a custom module called `recentspaces` which causes the problems. Can you please try to uninstall it?
> 
> YES! I had that module (v. 0.4) installed. After deactivating that module, the dashboard works again!
> 
> @luke- @ArchBlood Thanks a lot to both of you for your help!!!

https://github.com/Basster/humhub-modules-recent-spaces/issues/5

**Comment by ArchBlood** [comment]
@blu-IT if the p/r that I pushed doesn't merge you can download my version which should work with newer versions of HumHub

https://github.com/ArchBlood/humhub-modules-recent-spaces/tree/patch-1
