### ISSUE TITLE
No email notification when a user likes or leaves a comment.

### ISSUE THREAD

**Issue by boutch** [humhub/humhub#587]
Hello,

I am not receiving any email notification when a user likes or leave a comment on my post. I've changed the notification settings in the administration panel and my account to "Always" and Daily but it did not help.I am using SMTP but with mail it does not work neither. Emails for forgotten password' works OK.

Humhub 0.10 (latest to my knowledge)
PHP 5 / Apache 2
Debian server.

I am not sure if that hels but I can see the error below when I run
/protected/yiic emailing daily.

Kind regards,

Jean-Luc

--

Processing : (myemailaddress@domain.com): exception 'Zend_Search_Lucene_Exception' in /var/www/fondaciouk-conn
ect/protected/vendors/Zend/Search/Lucene/Storage/File/Filesystem.php:67
Stack trace:
#0 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Storage/Directory/Filesystem.php
(184): Zend_Search_Lucene_Storage_File_Filesystem->__construct('/var/www/fondac...', 'w+b')
#1 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Index/SegmentInfo.php(1622): Zen
d_Search_Lucene_Storage_Directory_Filesystem->createFile('_h_1.del')
#2 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Index/Writer.php(405): Zend_Sear
ch_Lucene_Index_SegmentInfo->writeChanges()
#3 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Index/Writer.php(764): Zend_Sear
ch_Lucene_Index_Writer->_updateSegments()
#4 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene.php(1436): Zend_Search_Lucene_In
dex_Writer->commit()
#5 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Proxy.php(508): Zend_Search_Luce
ne->commit()
#6 /var/www/fondaciouk-connect/protected/libs/HSearch.php(143): Zend_Search_Lucene_Proxy->commit()
#7 /var/www/fondaciouk-connect/protected/modules_core/user/models/User.php(339): HSearch->deleteMode
l(Object(User))
#8 /var/www/fondaciouk-connect/protected/vendors/yii/db/ar/CActiveRecord.php(1126): User->afterSave(
)
#9 /var/www/fondaciouk-connect/protected/vendors/yii/db/ar/CActiveRecord.php(806): CActiveRecord->up
date(NULL)
#10 /var/www/fondaciouk-connect/protected/commands/shell/EMailing/EMailing.php(202): CActiveRecord->
save()
#11 /var/www/fondaciouk-connect/protected/commands/shell/EMailing/EMailing.php(59): EMailing->getAct
ivityContent(Object(User))
#12 /var/www/fondaciouk-connect/protected/vendors/yii/console/CConsoleCommandRunner.php(71): EMailin
g->run(Array)
#13 /var/www/fondaciouk-connect/protected/vendors/yii/console/CConsoleApplication.php(92): CConsoleC
ommandRunner->run(Array)
#14 /var/www/fondaciouk-connect/protected/vendors/yii/base/CApplication.php(180): CConsoleApplicatio
n->processRequest()
#15 /var/www/fondaciouk-connect/protected/yiic.php(26): CApplication->run()
#16 /var/www/fondaciouk-connect/protected/yiic(5): require_once('/var/www/fondac...')
#17 {main}PHP Fatal error:  Uncaught exception 'Zend_Search_Lucene_Exception' with message 'fopen(/v
ar/www/fondaciouk-connect/protected/runtime/searchdb//_h_2.del): failed to open stream: Permission d
enied' in /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Storage/File/Filesystem.p
hp:67
Stack trace:
#0 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Storage/Directory/Filesystem.php
(184): Zend_Search_Lucene_Storage_File_Filesystem->__construct('/var/www/fondac...', 'w+b')
#1 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Index/SegmentInfo.php(1622): Zen
d_Search_Lucene_Storage_Directory_Filesystem->createFile('_h_2.del')
#2 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Index/Writer.php(405): Zend_Sear
ch_Lucene_Index_SegmentInfo->writeChanges()
#3 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Index/Writer.php(764): Zend_Sear
ch_Lucene_Index_Writer->_updateSegments()
#4 /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene.php(1436): Zend_Se in /var/www/f
ondaciouk-connect/protected/vendors/Zend/Search/Lucene/Storage/File/Filesystem.php on line 67
admin@cloudhosting:/etc/apache2/sites-available$

**Comment by boutch** [comment]
Looking closely at the log, I found the issue. It was permission error.
I have applied a chown www-data:www-data -R to my /var/www directory.

{main}PHP Fatal error: Uncaught exception 'Zend_Search_Lucene_Exception' with message 'fopen(/v
ar/www/fondaciouk-connect/protected/runtime/searchdb//_h_2.del): failed to open stream: Permission d
enied' in /var/www/fondaciouk-connect/protected/vendors/Zend/Search/Lucene/Storage/File/Filesystem.p
hp:67

**Comment by elinarobin** [comment]
https://chathelp.org/epson-printer-support/
