### ISSUE TITLE
URL's not displaying correctly

### ISSUE THREAD

**Issue by BaconTriple** [humhub/humhub#5870]
### What steps will reproduce the problem?
Accessing a space

### What is the expected result?
That the URL is corrected

### What do you get instead?
The wrong URL

### Additional info
I have two installs of HumHub. On one my spaces and user profiles have the correct URL formatting but on the other they don't.
![image](https://user-images.githubusercontent.com/97461220/190947957-7bb4305f-e93a-48fa-b26d-d8908215ae7d.png)
As you can see from the image there is an additional 'space/space' at the end of all of my space URL's.
![image](https://user-images.githubusercontent.com/97461220/190948041-26a40c5a-34f4-4850-b57b-ae5f437deb28.png)
As you can see from the image there is an additional 'user/profile' at the end of all of my user profile URL's.

However on my other install this is not the case as below:
![image](https://user-images.githubusercontent.com/97461220/190948108-acef9679-7dcc-4ee3-bacb-b10441a97d32.png)
The same can be said about spaces:
![image](https://user-images.githubusercontent.com/97461220/190948234-75821c18-f5a7-495d-ae6a-bf01c33754f1.png)

Please can someone tell me what needs changing so that the URLs are displayed correctly. I have attempted to go into the UrlRule.php file of each module and amend the default routes but this has no effect.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.2
| PHP version      |  8.1
| Operating system | Debian

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Try to update to the lastest version.
It is not intended that the routes can be changed per installation.

**Comment by BaconTriple** [comment]
I have tried to update but the issue is the same. Even if I don't change the default routes the problem is still that one installation (without any changes being made) is showing the correct URL without "space/space" and one installation (again without any changes being made) is showing the incorrect URL

**Comment by ArchBlood** [comment]
I believe those are only displayed when you click the stream menu from the space or profile which is apparently intended and comes with all installations of HumHub, not SEO friendly of course, but where it's implemented you can't really do much here without core editing.

**Comment by ArchBlood** [comment]
As seen in the following lines;

### User Profile
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/widgets/ProfileMenu.php#L54

### Space
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/widgets/Menu.php#L61

**Comment by ArchBlood** [comment]
@luke- maybe instead of using `createUrl` here call for the space URL and remove the `createUrl` or mark it with `/` or `#`?

**Comment by BaconTriple** [comment]
@ArchBlood thanks for replying. Unfortunately this happens with any links to profiles or spaces and if I try to use the correct URL manually (u/josh) it just redirects to the dashboard.

**Comment by BaconTriple** [comment]
@ArchBlood sorry I didn't get notified that you had replied.

My common.php in its entirety:

```
<?php

return [

    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ]
];
```
