### ISSUE TITLE
Marketplace - Removing licence key by the partner removes the "Add licence key" in the modules admin

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5874]
### What steps will reproduce the problem?

1. Create a licence key on https://partner.humhub.com/
2. On the Humhub instance -> Administration -> Modules: add the licence key
3. Remove the licence key on https://partner.humhub.com/
4. Create again a licence key on https://partner.humhub.com/ for the same module

### What is the expected result?

On the Humhub instance, it should be possible to add again the licence key:
![image](https://user-images.githubusercontent.com/23310825/191270499-3a52358c-959b-44a0-a031-84cf45a9c1d8.png)

### What do you get instead?

The "Add licence key" is removed from the menu:
![image](https://user-images.githubusercontent.com/23310825/191270100-f8a41511-82a1-49ea-934f-56d26d3462dc.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.4 (or before?) to 1.12.1

**Comment by ArchBlood** [comment]
Does it fix the issue on hard refresh or clearing cache?

**Comment by funkycram** [comment]
> Does it fix the issue on hard refresh or clearing cache?

No, it doesn't.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5883.
