### ISSUE TITLE
Asian language characters not rendering in Wiki module

### ISSUE THREAD

**Issue by cfrejya** [humhub/humhub#5881]
### Additional info Is this caused by the database fields for the Wiki have the wrong encoding?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.1CE
| PHP version      | 8.1
| Operating system | Win10

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
This is a database issue your collations aren't set to `utf8mb4_unicode_ci` by default, fix this and the languages are displayed correctly.

**Comment by cfrejya** [comment]
Thank you, @ArchBlood . I had a suspicion that it was! Do you know where in the database schema the table for wiki entries is? Does it create multiple instances, for example if the wiki module is activated in two spaces, is that two separate tables needing update?
