### ISSUE TITLE
Invitation mail is in the default site language instead of user language

### ISSUE THREAD

**Issue by atdqm** [humhub/humhub#5885]
### Is your feature request related to a problem? Please describe.
In a multi-language site :
The site language is in french : /admin/setting/basic , Default language list is on « Français »
The account language of the connected user is for instance Spanish (ES) : /admin/setting/basic
The user sends an invitation to another user with the invitation button on the people page /people
The invitation is sent in the default language of the site (French in this test case)

### Describe the solution you'd like
The invitation mail should be in the language of the user who send the invitation (this example in spanish)

### Describe alternatives you've considered
There is a ticket saying that the mail arrives in the invitee language #4673 I think it’s false...

When the user click on the link in the invitation mail, what is the language of the page ? The one of the browser ? It’s not good #5854 : it should be the language of the invitation ?

**Comment by funkycram** [comment]
There is setting allowing to send invite emails in the sender user's language:
https://docs.humhub.org/docs/admin/config-options/#user
`sendInviteMailsInGlobalLanguage`

@atdqm I think you can close this issue.

**Comment by atdqm** [comment]
Thanks
