### ISSUE TITLE
Mobile Post Images

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#589]
Images on mobile tend to often break the constraints of the body. They also like to up-scale image too small. 

Browsers: Firefox/Chrome Mobile

http://s29.postimg.org/l2xuxthlj/Screenshot_2015_01_07_23_59_08.png
http://s29.postimg.org/jmmcfoeon/Screenshot_2015_01_11_10_13_51.png

**Comment by andystrobel** [comment]
Is it possible that this depends on your theme changes? because normally all uploaded images to posts will be resized to maximum width of 200px.
