### ISSUE TITLE
Stream Shouldn't Say "No Matches" When Truly Empty

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#5892]
### What steps will reproduce the problem?

Visit a user profile for someone who has never posted anything.

### What is the expected result?

Ideally, a message saying the user "hasn't posted yet".

### What do you get instead?

"No matches with your selected filters!"

### Additional info

HumHub 1.12.1

**Comment by luke-** [comment]
Duplicate: https://github.com/humhub/humhub/pull/5877 ?

**Comment by miqrogroove** [comment]
Probably, yes.
