### ISSUE TITLE
0 byte .jpg

### ISSUE THREAD

**Issue by hagalaz** [humhub/humhub#591]
Hi! IMPORTANT! Uploading 0 byte size .jpg crashes all, need to repair!! >> getimagesize(): Read error!

**Comment by WASasquatch** [comment]
getimagesize() should always be in a conditional with errors hidden 

```php
if (list($width, $height) = @getimagesize($ref)) {
   // Do something
}
```

To prevent the system from failing on compressed/fragmented/bad images.

**Comment by hagalaz** [comment]
ok, https://github.com/humhub/humhub/pull/592
