### ISSUE TITLE
php_imagick fails to load.

### ISSUE THREAD

**Issue by dionisanchez** [humhub/humhub#5910]
### What steps will reproduce the problem?

Install HumHub in a Plesk domain enabling imagick extension.

### What is the expected result?

Get it up and running :)

### What do you get instead?

An error when browing through HumHub:

### Full error message appearing in frontend:

{
    "url": "/index.php?r=dashboard%2Fdashboard%2Factivity-stream",
    "status": 500,
    "response": {
        "name": "PHP Core Warning",
        "message": "Unknown: Unable to load dynamic library 'php_imagick.dll' (tried: /opt/plesk/php/8.0/lib/php/modules/php_imagick.dll (/opt/plesk/php/8.0/lib/php/modules/php_imagick.dll: cannot open shared object file: No such file or directory), /opt/plesk/php/8.0/lib/php/modules/php_imagick.dll.so (/opt/plesk/php/8.0/lib/php/modules/php_imagick.dll.so: cannot open shared object file: No such file or directory))",
        "code": 32,
        "type": "yii\\base\\ErrorException",
        "file": "Unknown",
        "line": 0,
        "stack-trace": [
            "#0 [internal function]: yii\\base\\ErrorHandler->handleFatalError()",
            "#1 {main}"
        ]
    },
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"name\":\"PHP Core Warning\",\"message\":\"Unknown: Unable to load dynamic library 'php_imagick.dll' (tried: /opt/plesk/php/8.0/lib/php/modules/php_imagick.dll (/opt/plesk/php/8.0/lib/php/modules/php_imagick.dll: cannot open shared object file: No such file or directory), /opt/plesk/php/8.0/lib/php/modules/php_imagick.dll.so (/opt/plesk/php/8.0/lib/php/modules/php_imagick.dll.so: cannot open shared object file: No such file or directory))\",\"code\":32,\"type\":\"yii\\\\base\\\\ErrorException\",\"file\":\"Unknown\",\"line\":0,\"stack-trace\":[\"#0 [internal function]: yii\\\\base\\\\ErrorHandler->handleFatalError()\",\"#1 {main}\"]}",
        "responseJSON": {
            "name": "PHP Core Warning",
            "message": "Unknown: Unable to load dynamic library 'php_imagick.dll' (tried: /opt/plesk/php/8.0/lib/php/modules/php_imagick.dll (/opt/plesk/php/8.0/lib/php/modules/php_imagick.dll: cannot open shared object file: No such file or directory), /opt/plesk/php/8.0/lib/php/modules/php_imagick.dll.so (/opt/plesk/php/8.0/lib/php/modules/php_imagick.dll.so: cannot open shared object file: No such file or directory))",
            "code": 32,
            "type": "yii\\base\\ErrorException",
            "file": "Unknown",
            "line": 0,
            "stack-trace": [
                "#0 [internal function]: yii\\base\\ErrorHandler->handleFatalError()",
                "#1 {main}"
            ]
        },
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "json",
    "name": "PHP Core Warning",
    "message": "Unknown: Unable to load dynamic library 'php_imagick.dll' (tried: /opt/plesk/php/8.0/lib/php/modules/php_imagick.dll (/opt/plesk/php/8.0/lib/php/modules/php_imagick.dll: cannot open shared object file: No such file or directory), /opt/plesk/php/8.0/lib/php/modules/php_imagick.dll.so (/opt/plesk/php/8.0/lib/php/modules/php_imagick.dll.so: cannot open shared object file: No such file or directory))",
    "code": 32,
    "type": "yii\\base\\ErrorException",
    "file": "Unknown",
    "line": 0,
    "stack-trace": [
        "#0 [internal function]: yii\\base\\ErrorHandler->handleFatalError()",
        "#1 {main}"
    ],
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.4
| PHP version      |  8.0
| Operating system | Ubuntu

### My comments

As you can see is trying to find /opt/plesk/php/8.0/lib/php/modules/php_imagick.dll.so but plesk has /opt/plesk/php/8.0/lib/php/modules/php_imagick.so instead.

**Comment by luke-** [comment]
The problem is not related to HumHub rather because of your Plesk PHP configuration.Did you manually modified something in the php.ini?

**Comment by dionisanchez** [comment]
> The problem is not related to HumHub rather because of your Plesk PHP configuration.Did you manually modified something in the php.ini?

No, im not. Just enable extensions on the GUI.

I dont know if it is related to HumHub directly but, as I said is trying to find **_php_imagick.dll.so_** but in linux this extension is named **_php_imagick.so_** .

**Comment by dionisanchez** [comment]
Still open, can't fix it, please give me some help!

**Comment by ArchBlood** [comment]
Sounds similar to the following issue on Plesk

https://support.plesk.com/hc/en-us/articles/6077118452370-PHP-scripts-fails-with-the-following-error-Unable-to-load-dynamic-library-sodium-so-cannot-open-shared-object-file-No-such-file-or-directory
