### ISSUE TITLE
Possibility to configure the "Follow" activity in the e-mail summaries

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5913]
### Is your feature request related to a problem? Please describe.

We would like to remove the `{user1} now follows {user2}.` activity in the e-mail summaries.

### Describe the solution you'd like

In "Aministration" -> "Settings" -> "E-Mail Summaries" (/activity/admin/defaults), add a checkbox for "User following - Whenever a user follows another one."

The value of this setting should then be added in the second parameter of `$this->getUser()->follow(Yii::$app->user->getIdentity());` (see https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/controllers/ProfileController.php#L106).

### Describe alternatives you've considered

An additional property in the `humhub\modules\user\Module` class.

**Comment by luke-** [comment]
How do we handle Space followings? One checkbox for User & Space Followings should be enough or?

**Comment by funkycram** [comment]
We don't have any notifications or activity when a user is following a space because of `$this->object_model == User::class` here: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/Follow.php#L99
If we add the possibility to have notifications and activity to spaces, we need to adapt the views, e.g. https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/activities/views/userFollow.php

So I suggest to mention only "User Followings" in the checkbox.

**Comment by luke-** [comment]
@funkycram Ok, then start with "User Followings"!

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/5925

**Comment by luke-** [comment]
@funkycram Cool thanks!
@Semir1212 Can you please check the activity description text:

**User following**
Whenever a user follows another one.

**Comment by Semir1212** [comment]
@luke- 

Following (User)
Whenever a user follows another user.

Following (Space)
Whenever...

**Comment by luke-** [comment]
@Semir1212 Thanks!
