### ISSUE TITLE
Changing Mail Trasport Type SMTP/SMTPS -> No Delivery (Debug mode, save as file)  occurs system crash.

### ISSUE THREAD

**Issue by tosintech-web** [humhub/humhub#5918]
### What steps will reproduce the problem?
Administration menu -> Settings and Configuration -> Advanced Settings -> E-mail

Mail Transport Type 
 SMTP/SMTPS   => (change) => No Delivery (Debug Mode, Save as file -> Save & Test

Next, Shows error 

### What is the expected result?
Go Debug Mode mail settings and system run normally...

### What do you get instead?
Invalid Configuration Exception
![スクリーンショット 2022-11-10 150830](https://user-images.githubusercontent.com/75475434/201013812-04d324af-6553-41da-a039-11ddbb999ca2.png)

### Additional info
config/dynamic.php overwritten automatically
 components['mailer']['transport'] => array(),
 components['mailer']['useFileTransport'] => true,

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.1
| PHP version      |  8.1.11
| Operating system | ubuntu20.04

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Please remove `components['mailer']['transport'] => array(),`. It's not longer required since v1.12

**Comment by tosintech-web** [comment]
Why is not removed automatically when we change the setting? Why does it write null array?

**Comment by luke-** [comment]
Hmm, components-mailer-transport should be automatically removed from dynamic config.

**Comment by tosintech-web** [comment]
Thanks, anyway.  I'll try to remove by myself when debugging time.
