### ISSUE TITLE
Humhub 1.13 - WallCreateContentMenu should not use the WallStreamModuleEntryWidget -> $editMode

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5929]
### What steps will reproduce the problem?

On Humhub 1.13 develop branch, in a `WallEntry` widget class extending `WallStreamModuleEntryWidget`, if the `$editMode` attribute is set to `WallStreamModuleEntryWidget::EDIT_MODE_MODAL` instead of the inline mode, the `WallCreateContentMenu` widget tries to display the `WallCreateForm` widget in a modal box (but fails).

As the `$editMode` is for editing the content, `WallCreateContentMenu` should not use this value. It should always load the `WallCreateForm` in inline mode.

### What is the expected result?

![image](https://user-images.githubusercontent.com/23310825/202298784-b170117e-717f-470b-af74-06c73c945bca.png)

### What do you get instead?

![image](https://user-images.githubusercontent.com/23310825/202298915-11ad3bf2-32de-4e12-ac5e-f30135056af2.png)

### Additional info

Related to https://github.com/humhub/humhub/pull/5827

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13 develop

**Comment by yurabakhtin** [comment]
@funkycram Hello, what module has the issue?

For example, the module `calendar` uses `public $editMode = self::EDIT_MODE_MODAL;` here https://github.com/humhub/calendar/blob/master/widgets/WallEntry.php#L39 and it works without fail.
Could you show what error you have when the modal is loaded, probably the error on the request from the property `public $createRoute` like we have in the module `calendar` - `public $createRoute = '/calendar/entry/add-from-wall';`.

**Comment by funkycram** [comment]
Thanks @yurabakhtin for having an eye on this!

The Wiki module works differently: to create a new wiki page from the wall stream, it's a simple redirection to a page of the Wiki module.

The bug is with the [Survey module](https://www.humhub.com/en/marketplace/survey) that I'm upgrading for Humhub 1.13, so you cannot test easily with this module.

But you can reproduce the bug easily with the Poll module.
In the [WallEntry class](https://github.com/humhub/polls/blob/master/widgets/WallEntry.php), add `public $editMode = self::EDIT_MODE_MODAL;` and you'll see the bug by clicking on the "Question" tab (as you can see on the screenshots above). It's not a PHP bug, there are no log I can send you.

Thanks!

**Comment by funkycram** [comment]
Thanks @yurabakhtin for having an eye on this!

The Calendar module works differently: to create a new event from the wall stream, it opens a modal box. And for the Wiki module, it's a simple redirection to a page of the Wiki module.

The problem is with the [Survey module](https://www.humhub.com/en/marketplace/survey) that I'm upgrading for Humhub 1.13.

This module works the same way as the Poll module: the `WallCreateForm` widget is integrated into the wall page by JS, bellow the `WallCreateContentMenu` widget (no modal box or redirection).
I think that in this case `$editMode` should not be used. Or maybe we should introduce a `$createMode` attribute, the same way the `$createRoute` has bee added.

To reproduce the problem, In the [WallEntry class of the Poll module](https://github.com/humhub/polls/blob/master/widgets/WallEntry.php), add public $editMode = self::EDIT_MODE_MODAL; and you'll see the bug by clicking on the "Question" tab (as you can see on the screenshots above). It's not a PHP bug, there are no log I can send you.

Thanks!

**Comment by funkycram** [comment]
Thanks @yurabakhtin for these detail explanations and screenshots!

Yes, I can develop a modal box, but if possible I would prefer to stay with current way the Survey module works:
- Creation: inline
- Edition: modal

Ideally, the same way we have `$createRoute` and `$editRoute` in the `WallStreamModuleEntryWidget` class, it would be great if we had `$createMode` AND `$editMode`. This way, we could have separate behaviors for creation and edition mode, and I think it would be easier to understand. With the current 1.13 version, it's not obvious that `$editRoute` is also used for creation.

If it's not possible to separate the creation from the edition mode by adding a `$createMode` attribute to  `WallStreamModuleEntryWidget` class, then yes, I will create a modal box for creation the survey.

Thanks!

**Comment by yurabakhtin** [comment]
@funkycram Yes, it seems you are right, if we have `$createRoute` and `$editRoute` + `$editMode` then we should add new `$createMode`.

@luke- What do you think, should extend core for adding new `$createMode`?

@funkycram While we don't implement the `$createMode` you can extend your class `WallEntry` by adding a code like this:

```php
public function init()
{
    parent::init();

    if (!$this->model->isNewRecord) {
        $this->editMode = self::EDIT_MODE_MODAL;
    }
}
```

**Comment by luke-** [comment]
@yurabakhtin Probably a separate `createMode` would be good. Would be nice if it takes the value of `editMode` by default.

**Comment by yurabakhtin** [comment]
@luke- Ok, I have added new `createMode` with default value from `editMode` in the PR https://github.com/humhub/humhub/pull/5935.

**Comment by funkycram** [comment]
That's perfect, thanks @yurabakhtin !
