### ISSUE TITLE
dailySummaryHour ?

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#5941]
it is easy to set the **weeklySummaryDay** in config files,
but, is there **dailySummaryHour ?** I cannot find any.
So,
Is there a way to set the daily summary hour? and the weekly summary hour?
How is the summary hour calculated in the present HH versions?
In our site daily and weekly summaries are sent at around 18:00. Is it the default time?

Thanks in advance

**Comment by ArchBlood** [comment]
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/activity/Module.php#L28-L31

**Comment by Gilbertdelyon** [comment]
Yes, this is what I already found.
But I guess that summary time isn't  a "rabbit out of a hat".
In our site the daily summary is at 18:55 every day (while cron/run once per hour at HH:52). 
I had like to know where this time is comming from and if there is a way to alter the native time.

**Comment by Gilbertdelyon** [comment]
yes! I found the answer
Summary is triggered by the daily cron
