### ISSUE TITLE
help warning

### ISSUE THREAD

**Issue by spunkdeveloper** [humhub/humhub#5942]
I detected a new bug The latest version of humhub is Version: 1.12.2 . when the administrator creates a user, the system crashes into an error and this is indicated as a server error, even if the user account seems to have been created, the created user cannot login to our humhub site, please fix it. a situation that can cause serious problems in the future.  help warning !!

In addition, the system of sending invitations to the e-mails of the people who will become members from the admin panel does not work.

please help us with a humhub update..

**Comment by luke-** [comment]
Please use our bug reporting template.
