### ISSUE TITLE
Follow Notifications

### ISSUE THREAD

**Issue by thedude83** [humhub/humhub#595]
It would be great that if when a user followed you, you got a notification.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/3a803a6363a825da6a6018f83806e56dee9e35ce

**Comment by Kanasagra-Jaydip** [comment]
Thanks @luke- 

This is the perfect code.
But when i click on notification then i got an error
"Could not determine redirect url for this kind of source object!"

have you any idea for that?
Please tell me how to fix it.
Thansk,

**Comment by marjanapesic** [comment]
Yes,

The issue already exists and is resolved https://github.com/humhub/humhub/issues/657
