### ISSUE TITLE
FireBase push notifications in 1.12.2 ?

### ISSUE THREAD

**Issue by karimbernardet83** [humhub/humhub#5955]
Hi

We are using humhub community edition version 1.12.2. 
I have setup the fcm-push plugin with a Firebase google access (Legacy API Cloud Messaging). I already did it before.
I use the PWA version of humhub on my phone but I do not receive any notification on the phone and I do not see any errors in the log files (humhub, apache).
 Is it supposed working in 1.12.2 ?

Thanks 

Karim

**Comment by luke-** [comment]
Please create a issue here: https://github.com/humhub-contrib/fcm-push
