### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by yoshida-git-ai** [humhub/humhub#5959]
Is there a repository for that?

"Community Edition" was built successfully, but only for HumHum community connections
https://github.com/evolved37/github_android_humhub

Is it a better way to set the destination URL to your own server and build it?

**Comment by luke-** [comment]
At the moment there are no official mobile apps. We only provide PWA.

**Comment by spoorun** [comment]
It would be nice if there was a way for users to automate production of apps for their users/members
:
- Android app distributed as an .apk
- iPhone app
- Windows app
- Linux app (distributed as .flatpak)
Perhaps via an instruction page
