### ISSUE TITLE
Single Sign On into HumHub

### ISSUE THREAD

**Issue by greenplanet95014** [humhub/humhub#596]
What's the best way to implement single sign on into HumHub?

**Comment by slobberbone** [comment]
I'm interested by the answer too !

**Comment by ymalmaguer** [comment]
me to

**Comment by himanshumehru** [comment]
me 3 4 5

**Comment by luke-** [comment]
Wait for 1.1

https://github.com/humhub/humhub/blob/v1.1-dev/protected/humhub/docs/guide/admin-adv-auth.md
