### ISSUE TITLE
Spaces - Banner changing area of viewing (cropping for space)

### ISSUE THREAD

**Issue by jayavman** [humhub/humhub#5960]
### What steps will reproduce the problem?

When Changing spaces banner size area in large image (move to the image to select another part of the image) for the top banner area in spaces

### What is the expected result?

No errors

### What do you get instead?

yii\base\ErrorException: Implicit conversion from float-string "144.54545454545456" to int loses precision in /home/world/public_html/hub/protected/vendor/imagine/imagine/src/Imagick/Image.php:164
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'Implicit conver...', '/home/world/p...', 164)
#1 /home/world/public_html/hub/protected/vendor/imagine/imagine/src/Imagick/Image.php(164): Imagick->cropImage(1200, 203, '0', '144.54545454545...')
#2 /home/world/public_html/hub/protected/humhub/libs/ProfileImage.php(160): Imagine\Imagick\Image->crop(Object(Imagine\Image\Point), Object(Imagine\Image\Box))
#3 /home/world/public_html/hub/protected/humhub/modules/content/controllers/ContainerImageController.php(121): humhub\libs\ProfileImage->cropOriginal('0', '144.54545454545...', '203.17460317460...', '1200')
#4 /home/world/public_html/hub/protected/humhub/modules/content/controllers/ContainerImageController.php(63): humhub\modules\content\controllers\ContainerImageController->handleCrop('banner')
#5 [internal function]: humhub\modules\content\controllers\ContainerImageController->actionCropBanner()
#6 /home/world/public_html/hub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /home/world/public_html/hub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#8 /home/world/public_html/hub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('crop-banner', Array)
#9 /home/world/public_html/hub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('space/manage/im...', Array)
#10 /home/world/public_html/hub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 /home/world/public_html/hub/index.php(25): yii\base\Application->run()
#12 {main} 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.0-beta.2
| PHP version      |  8.1.12
| Operating system | Centos

**Comment by yurabakhtin** [comment]
@luke- Yes, I confirm, I could reproduce the issue and fixed in PR https://github.com/humhub/humhub/pull/5964.
