### ISSUE TITLE
admin can't create a user if Notifications are enabled in default group

### ISSUE THREAD

**Issue by punkyard** [humhub/humhub#5967]
### What steps will reproduce the problem?
1. in Administration menu > users > groups > settings of the default group v Enable Notifications
2. try to create a new user with admin account or try to edit page the user account

### What is the expected result?
when saving the new user credentials, see the 'edit user' page in Administration > user

### What do you get instead?
error message:

> Oooops... It looks like you may have taken the wrong turn.
> An internal server error occurred.

### Additional info
| HumHub version   | 1.12.2
| PHP version           |  8.1
| Operating system | ubuntu 2204

LOGS
> INFO  Sun, 04 Dec 2022 01:51:43 +0100  application
$_GET = []

$_SERVER = [
'TEMP' => '/home/tmp'
'TMPDIR' => '/home/tmp'
'TMP' => '/home/tmp'
'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
'USER' => 'myself'
'HOME' => '/home'
'SCRIPT_NAME' => '/reseau-1-12-2/index.php'
'REQUEST_URI' => '/reseau-1-12-2/people'
'QUERY_STRING' => ''
'REQUEST_METHOD' => 'GET'
'SERVER_PROTOCOL' => 'HTTP/1.0'
'GATEWAY_INTERFACE' => 'CGI/1.1'
'REDIRECT_URL' => '/reseau-1-12-2/people'
'REMOTE_PORT' => '53548'
'SCRIPT_FILENAME' => '/home/index.php'
'SERVER_ADMIN' => 'info@mon.rez0.net'
'CONTEXT_DOCUMENT_ROOT' => '/home'
'CONTEXT_PREFIX' => ''
'REQUEST_SCHEME' => 'https'
'DOCUMENT_ROOT' => '/home'
'REMOTE_ADDR' => '93.5.120.234'
'SERVER_PORT' => '443'
'SERVER_ADDR' => '173.212.238.44'
'SERVER_NAME' => 'mon.rez0.net'
'SERVER_SOFTWARE' => 'Apache/2.4.54 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/3.0.2'
'SERVER_SIGNATURE' => ''
'HTTP_COOKIE' => '_identity=e5c1a66f1fc43d3d651d734126967151e6beebd185c2a28c432e66af0b44338ca%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%2296988c29-3bd7-4fbf-b270-332ec883a11f%22%2C2592000%5D%22%3B%7D; PHPSESSID=vtld255juq5mtk0dkt0v2cv25v; _csrf=b1fd82af28c7c16bbae4be299ca615f4d08700a8caa295058110660213359c31a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22QscQNL5y7t_tVvSuQ1fJEZw96OCp9_YT%22%3B%7D; language=bb6ce3163c1f588e67bf425ac15e954b7b2dba33b884af94990c7579c2f94236a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A5%3A%22en-US%22%3B%7D; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true'
'HTTP_CF_CONNECTING_IP' => '93.5.120.234'
'HTTP_REFERER' => 'https://mon.rez0.net/reseau-1-12-2/spaces'
'HTTP_ACCEPT_LANGUAGE' => 'fr-fr'
'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15'
'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
'HTTP_CF_VISITOR' => '{\"scheme\":\"https\"}'
'HTTP_X_FORWARDED_PROTO' => 'https'
'HTTP_CF_RAY' => '77408e22dce222ab-CDG'
'HTTP_ACCEPT_ENCODING' => 'gzip'
'HTTP_CDN_LOOP' => 'cloudflare'
'HTTP_CF_IPCOUNTRY' => 'FR'
'HTTP_CONNECTION' => 'close'
'HTTP_X_FORWARDED_FOR' => '93.5.120.234, 93.5.120.234'
'HTTP_HOST' => 'mon.rez0.net'
'proxy-nokeepalive' => '1'
'HTTPS' => 'on'
'BASE' => '/reseau-1-12-2'
'REDIRECT_STATUS' => '200'
'REDIRECT_HTTPS' => 'on'
'REDIRECT_BASE' => '/reseau-1-12-2'
'FCGI_ROLE' => 'RESPONDER'
'PHP_SELF' => '/reseau-1-12-2/index.php'
'REQUEST_TIME_FLOAT' => 1670115103.1862
'REQUEST_TIME' => 1670115103
]

ERROR  Sun, 04 Dec 2022 01:51:43 +0100  yii\base\ErrorException:2
yii\base\ErrorException: Attempt to read property "tags_cached" on null in /home/protected/humhub/modules/content/components/ContentContainerActiveRecord.php:397
Stack trace:
#0 /home/protected/humhub/modules/content/components/ContentContainerActiveRecord.php(397): yii\base\ErrorHandler->handleError()
#1 /home/protected/humhub/modules/user/widgets/PeopleTagList.php(45): humhub\modules\content\components\ContentContainerActiveRecord->getTags()
#2 /home/protected/humhub/components/Widget.php(63): humhub\modules\user\widgets\PeopleTagList->run()
#3 /home/protected/humhub/modules/user/widgets/views/peopleCard.php(47): humhub\components\Widget::widget()
#4 /home/protected/vendor/yiisoft/yii2/base/View.php(347): require('...')
#5 /home/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#6 /home/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#7 /home/protected/vendor/yiisoft/yii2/base/Widget.php(242): yii\base\View->render()
#8 /home/protected/humhub/modules/user/widgets/PeopleCard.php(39): yii\base\Widget->render()
#9 /home/protected/humhub/components/Widget.php(63): humhub\modules\user\widgets\PeopleCard->run()
#10 /home/protected/humhub/modules/user/views/people/index.php(46): humhub\components\Widget::widget()
#11 /home/protected/vendor/yiisoft/yii2/base/View.php(347): require('...')
#12 /home/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#13 /home/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#14 /home/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#15 /home/protected/humhub/modules/user/controllers/PeopleController.php(70): yii\base\Controller->render()
#16 [internal function]: humhub\modules\user\controllers\PeopleController->actionIndex()
#17 /home/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#18 /home/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#19 /home/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#20 /home/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#21 /home/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#22 /home/index.php(25): yii\base\Application->run()
#23 {main}

> and errors from your browser console if possible: SAFARI
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

  | locationReplace | @ | jquery.pjax.modified.js?v=1668208366:460
-- | -- | -- | --
  | options.error | @ | jquery.pjax.modified.js?v=1668208366:294
  | options.error | @ | humhub.client.pjax.js?v=1668208366:68
  | fire | @ | jquery.js?v=1669071363:3500
  | fireWith | @ | jquery.js?v=1669071363:3630
  | done | @ | jquery.js?v=1669071363:9798
  | (anonymous) | @ | jquery.js?v=1669071363:10057
  | load (async) |   |  
  | send | @ | jquery.js?v=1669071363:10076
  | ajax | @ | jquery.js?v=1669071363:9690
  | pjax | @ | jquery.pjax.modified.js?v=1668208366:421
  | handleClick | @ | jquery.pjax.modified.js?v=1668208366:140
  | (anonymous) | @ | jquery.pjax.modified.js?v=1668208366:74
  | dispatch | @ | jquery.js?v=1669071363:5430
  | elemData.handle | @ | jquery.js?v=1669071363:5234

audioblocktrue
VM319:130 canvasfont = true
edit?id=18:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
VM401:5 Settings loaded...
intercept.js:1 Filter Running...
edit?id=18:1 Failed to load resource: the server responded with a status of 500 ()
jquery.js?v=1669071363:10109

**hoping to make the work evolve even more !**

**Comment by punkyard** [comment]
now, my modules come off, as if they were never installed ^^

**Comment by luke-** [comment]
Can you reproduce this on our demo hosting?

**Comment by punkyard** [comment]
yes

![Capture d’écran 2022-12-04 à 19 27 55](https://user-images.githubusercontent.com/59349105/205508698-f6b3a418-1aa4-4576-b56f-3bedb6e4dfcd.png)

**Comment by punkyard** [comment]
good news, it's fixed then?!
am i winning anything? ^^
