### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by samuk** [humhub/humhub#5974]
### Describe the solution you'd like

https://github.com/humhub/humhub#readme could include text similar to

Humhub is an open-source social network platform written in PHP. It allows users to create and manage their own social network websites, similar to popular platforms such as Facebook and LinkedIn.

To use Humhub, you will need to download the source code from the above GitHub repository and install it on a web server that supports PHP. Once installed, you can access the platform by visiting the URL of your server in a web browser.

Here are some key features of Humhub:

- Customizable user profiles: Users can create and customize their own profiles, including profile pictures, cover photos, and personal information.

- Content management: Humhub allows users to create and share a variety of different content, including text posts, images, videos, and files.

- Social features: Humhub includes social features such as the ability to follow and interact with other users, create and join groups, and share content with specific users or groups.

- Modularity: Humhub is built on a modular architecture, which allows users to easily extend and customize the platform by installing and enabling additional modules.

- Responsive design: Humhub is designed to be responsive, meaning that it looks and works great on a variety of different devices, including smartphones and tablets.

- Overall, Humhub is a powerful and flexible social network platform that can be used to create a wide range of different types of social network websites.

**Comment by HubiHonold** [comment]
See Update README.md #6009
