### ISSUE TITLE
Search: Missing Context Menu Options in Content Search Results

### ISSUE THREAD

**Issue by noman-maken** [humhub/humhub#5975]
When the admin search for any content from the search feature, he has no option to edit or delete content.

![image](https://user-images.githubusercontent.com/60031819/206744514-d7ad9d0a-6427-40b2-b3d9-159bb8d29aea.png)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/7067: I have activated all options except of "Pin to top".
