### ISSUE TITLE
server error in community humhub

### ISSUE THREAD

**Issue by radiolip** [humhub/humhub#598]
PHP Error [8]

getimagesize(): Read error!

![capture](https://cloud.githubusercontent.com/assets/9461399/5728592/16d6066c-9b74-11e4-9dd4-0a8c7c880dcb.PNG)

**Comment by WASasquatch** [comment]
This issue has been looked into in a previous issue. They do not do a conditional, nor hide errors on the event of failing. There should be a conditional statement to prevent handling of a dead image, and hidden errors to prevent breaking HumHub (throwing it's own error in console or w/e)

**Comment by radiolip** [comment]
This is because gd image converter with large image...

**Comment by radiolip** [comment]
FcgidMaxRequestLen, Default 131072 http://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#fcgidmaxrequestlen

Cenos: /etc/httpd/conf.d/fcgid.conf 
Deb/untu: /etc/apache2/mods-available/fcgid.conf 

FcgidMaxRequestLen 1073741824 - 1GB.

**Comment by WASasquatch** [comment]
I doubt that very seriously... I can convert images up to 10mb...
