### ISSUE TITLE
Tracker issue

### ISSUE THREAD

**Issue by wehowski** [humhub/humhub#5986]
Sorry if this is not the correct repo, as I did not find the one for the tracker issue module?
I just would like to report that I disabled this module after the last humhub updates, as it throw error if I open someones profile module.

2022-12-22 09:06:18 [5.161.65.182][-][croif3e58979jgi30tollqms34][error][yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: humhub\modules\user\models\User::isModuleEnabled() in /.../protected/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /.../protected/modules/tracker_issue/Events.php(79): yii\base\Component->__call()
#1 [internal function]: tracker\Events::onStreamViewerCreate()
#2 /.../protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#3 /.../protected/humhub/components/Widget.php(54): yii\base\Event::trigger()
#4 /.../protected/humhub/modules/user/views/profile/home.php(20): humhub\components\Widget::widget()
#5 /.../protected/vendor/yiisoft/yii2/base/View.php(347): require('...')
#6 /.../protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#7 /.../protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#8 /.../protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#9 /.../protected/humhub/modules/user/controllers/ProfileController.php(86): yii\base\Controller->render()
#10 /.../protected/humhub/modules/user/controllers/ProfileController.php(75): humhub\modules\user\controllers\ProfileController->actionHome()
#11 [internal function]: humhub\modules\user\controllers\ProfileController->actionIndex()
#12 /.../protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#13 /.../protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#14 /.../protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#15 /.../protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#16 /.../protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#17 /.../index.php(25): yii\base\Application->run()
#18 {main}
2022-12-22 09:06:18 [5.161.65.182][-][croif3e58979jgi30tollqms34][info][application] $_GET = [
    'cguid' => '...'
]

**Comment by luke-** [comment]
Here you can find the correct repo: https://github.com/githubjeka/tracker-issues

Seems it's not compatible with the latest HumHub version:
https://docs.humhub.org/docs/develop/modules-migrate#version-113
