### ISSUE TITLE
User Permissions - type string

### ISSUE THREAD

**Issue by jayavman** [humhub/humhub#5996]
Error Log :

yii\base\ErrorException: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/fredons/public_html/hub/protected/humhub/modules/user/components/User.php:275
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'strpos(): Passi...', '/home/fredons/p...', 275)
#1 /home/fredons/public_html/hub/protected/humhub/modules/user/components/User.php(275): strpos(NULL, 'Microsoft Offic...')
#2 /home/fredons/public_html/hub/protected/humhub/components/behaviors/AccessControl.php(224): humhub\modules\user\components\User->loginRequired()
#3 /home/fredons/public_html/hub/protected/humhub/components/behaviors/AccessControl.php(154): humhub\components\behaviors\AccessControl->loginRequired()
#4 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/ActionFilter.php(77): humhub\components\behaviors\AccessControl->beforeAction(Object(yii\base\InlineAction))
#5 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#6 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#7 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Controller.php(297): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#8 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/Controller.php(222): yii\base\Controller->beforeAction(Object(yii\base\InlineAction))
#9 /home/fredons/public_html/hub/protected/humhub/components/Controller.php(208): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#10 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Controller.php(176): humhub\components\Controller->beforeAction(Object(yii\base\InlineAction))
#11 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#12 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#13 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#14 /home/fredons/public_html/hub/index.php(25): yii\base\Application->run()
#15 {main} 

| HumHub version   | 1.13.0
| PHP version      |  8.1.13

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5999.
