### ISSUE TITLE
PHP Fatal error with ldap login

### ISSUE THREAD

**Issue by arnikodelkia** [humhub/humhub#600]
Connected to ldap and users are found and imported into the environment, but no ldap login is possible.

This appears in the errpt.log httpd file 

[error] [client xxxxxxxx PHP Fatal error:  Call to a member function getAttribute() on a non-object in /web/social/protected/libs/HLdap.php on line 149, referer: http://xxxxxxxxxxx/social/index.php?r=user/auth/login

Versions:

php54-php-5.4.16-22.el6.x86_64
httpd-2.2.15-39.el6.x86_64
mysql-server-5.1.73-3.el6_5.x86_64

**Comment by luke-** [comment]
Did you specified a username attribute in ldap configuration?

**Comment by arnikodelkia** [comment]
Hi Luke

Yes, "uid"

**Comment by acidjames** [comment]
Hi guys,

i'm having exactly the same problem with the latest stable version 0.20.1. Using php5.5.9-1ubuntu4.14.

When the user logins, i have the same error : 

```PHP Fatal Error – yii\base\ErrorException
Call to a member function getAttribute() on a non-object

    1. in /home/vhostssl/humhub/web/protected/humhub/modules/user/libs/Ldap.php
```


The user appears in the "Users" section of the admin panel... weird.

LDAP panel states i have 70 users found...

Anyone have an idea ?

**Comment by acidjames** [comment]
Hi, 

i have also tried from Docker image https://github.com/cboulanger/humhub-docker

Same error, impossible to login with LDAP even though the user is found and added

**Comment by acidjames** [comment]
This problem is solved by correctly configuring openldap in my case: 
/etc/openldap/slapd.conf

access to *
        by peername=yourwebserveripaddress auth
        by * read

Enjoy

**Comment by acidjames** [comment]
@luke- you can close this issue
