### ISSUE TITLE
Disolving Spaces Post and Delay Space Post

### ISSUE THREAD

**Issue by jayavman** [humhub/humhub#6003]
Feature Request :

1. 
**Set Date/Time to Post Spaces Message and  delete Spaces Post at Set Date/time.** 

to avoid clog up of Spaces Post messages that are UN-relatable the day after the post is made. Administrations will be still able to see the post on the spaces page they manage but it is grayed out (to a lighter colour) to show this post has been deleted. All other users on the spaces page will not see the post anymore after date is out of region.

2.
**Schedule Spaces Post**

Post Spaces can set a time to post (and no end date if wanted), This is designed for people who want to post to a space when they aren't at the computer (great for overnight posts)

**Comment by luke-** [comment]
Please create one issue per feature request and check for duplicates.
https://github.com/humhub/humhub/issues/5624
