### ISSUE TITLE
Different number of users

### ISSUE THREAD

**Issue by rickerde** [humhub/humhub#6007]
Hi all,

Firstly, please open the page "Spaces" which gives you an overview over all spaces. Let's say a certain space shows 93 members. As a second step, please open this specific space and look at its header. It now says "91 members". The difference comes from two former members who are deactivated users.

As an admin and as a normal user, I would expect to see the count of 91 members everywhere. Deactivated users should not be counted in the total user count.

HumHub version: 1.13.0

**Comment by yurabakhtin** [comment]
Hello @rickerde, thank you for the report!

@luke- Fixed in the PR https://github.com/humhub/humhub/pull/6011.
