### ISSUE TITLE
Facebook Sign-in Not Working

### ISSUE THREAD

**Issue by OxyFuse** [humhub/humhub#6013]
### What steps will reproduce the problem?
Follow the Facebook instructions at https://docs.humhub.org/docs/admin/authentication or use the [Facebook Sign-in](https://www.humhub.com/en/marketplace/auth-facebook/) module

### What is the expected result?
User should be able to login using Facebook.

### What do you get instead?
After clicking the `Continue as Name` button in the `AppName is requesting access to:` screen, it goes back to the login screen. Nothing happens when the Facebook button in the `Please Sign-in` area is clicked, it just reloads the login screen.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.0?
| PHP version      | 8.09

**Comment by ArchBlood** [comment]
This affects all OAuth modules, just tested to confirm it, @luke-

**Comment by ArchBlood** [comment]
Requirements added

 - [x]  https://github.com/humhub-contrib/auth-facebook/pull/3
- [x] https://github.com/humhub-contrib/auth-google/pull/6
- [x] https://github.com/humhub-contrib/auth-twitter/pull/3

**Comment by luke-** [comment]
@ArchBlood Great thanks!
