### ISSUE TITLE
Topic Link Error

### ISSUE THREAD

**Issue by OxyFuse** [humhub/humhub#6014]
### What steps will reproduce the problem?
Write a post in Space or Profile and add a `Topic`. Go back to Dashboard and click on the `Topic(s)` you've posted.

### What is the expected result?
It will show the content with the specified Topic.

### What do you get instead?
Error occured and can't show the post(s):
`An unexpected error occurred. If this keeps happening, please contact a site administrator.`

> TypeError: Cannot read properties of undefined (reading 'timeout')
> TypeError: Cannot read properties of undefined (reading 'timeout')
>     at Object.redirect (/static/js/humhub/humhub.client.pjax.js?v=1671610402:23:95)
>     at Object.addTopic (/assets/7d3090cb/js/humhub.topic.js?v=1671667455:21:25)
>     at _executeAction (/static/js/humhub/humhub.action.js?v=1671610402:587:35)
>     at ActionBinding.handle (/static/js/humhub/humhub.action.js?v=1671610402:560:17)
>     at HTMLAnchorElement. (/static/js/humhub/humhub.action.js?v=1671610402:809:27)
>     at HTMLDocument.dispatch /assets/af390ac6/jquery.js?v=1671667454:5430:27)
>     at elemData.handle (/assets/af390ac6/jquery.js?v=1671667454:5234:28)

### Additional info

- Clicking the Topic in the Search Results will also bring the same error.
- Clicking the Topic within the Space or Profile works just fine.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.0
| PHP version      | 8.09

**Comment by luke-** [comment]
Related: https://github.com/humhub/humhub/issues/5861
