### ISSUE TITLE
Poll Menu Not Showing

### ISSUE THREAD

**Issue by OxyFuse** [humhub/humhub#6015]
### What steps will reproduce the problem?
Activate the Polls module in Space or Profile.

### What is the expected result?
Polls menu item should appear in Space/Profile Menu

### What do you get instead?
No Poll menu.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.0
| PHP version      | 8.09
| Polls version | 1.2.1

**Comment by luke-** [comment]
@OxyFuse Please always open issues in the correct repo e.g. humhub/polls.

The menu entry and polls page no longer exists.


Polls can created here: 
![image](https://user-images.githubusercontent.com/4736168/211097486-b728596e-882f-46f4-8198-d753c7ed8fe6.png)
