### ISSUE TITLE
PHP- Mail dont work

### ISSUE THREAD

**Issue by LevyFukawa** [humhub/humhub#6019]
Hello, I did a completely fresh Ubuntu 20.04 installation and a completely fresh Humhub installation.
When i configurated the email tab and try to send it failed.
Then i installed postfix and then it said that they send an email but it didnt.
Is this a bug or how can i fix it?

| HumHub version   | 1.13.0
| PHP version 7.4     | 
| Operating system Ubuntu 20.04 and Apache2 |

**Comment by luke-** [comment]
Probably your postfix is not completely configured and therefore the emails are not delivered. The easiest way would be to use an existing email server via SMTP.
