### ISSUE TITLE
Guest Mode: Click on Members results in Error

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6026]
### What steps will reproduce the problem?

- Enable Guest Mode

- Click as not logged in user at Spaces on the member count

![image](https://user-images.githubusercontent.com/4736168/211290835-2ca686d8-ba12-4428-8cc5-291aad88a73e.png)

- Error
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6037 - I completely hid the icons with members counter if user has no access to the action. Also we can display the mermbers counter without link action, do you prefer this?

**Comment by luke-** [comment]
@yurabakhtin Yes good point, it would be better to display the number of members without link action. Can you please change this?

**Comment by yurabakhtin** [comment]
@luke- Done in the commit https://github.com/humhub/humhub/pull/6037/commits/1a39ab4b339659dc75d0f66e1242552c5c998ed1
