### ISSUE TITLE
UserPicker should search in all searchable profile fields.

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6030]
### What steps will reproduce the problem?

- Mark Profilefield `street` as searchable
- Add `Teststreet` to some user profile
- Try to invite a user to a Space and search for `Teststreet`
- No user is found.

In mentioning it's possible to find users with all searchable profile fields. 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6040.

**Comment by yurabakhtin** [comment]
@luke- Fixed in commit https://github.com/humhub/humhub/pull/6040/commits/e619bce1b4351924b9fa1907a017f07fefbbc422.
