### ISSUE TITLE
On users list grid, show Auth mode badge only for sys admins

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6031]
### Is your feature request related to a problem? Please describe.

If an SSO is configured, in the space members list (or other user lists using [`DisplayNameColumn` class](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/grid/DisplayNameColumn.php), a "badge" label is displayed to show the name of the SSO with which the user created his account.
Example with Keycloak:
![image](https://user-images.githubusercontent.com/23310825/211551728-ea56a98b-24a2-4519-b9ac-d85f4433fda3.png)

Space admins don't understand this badge as they don't even know what Keycloak is. And it's useless for them. It could be useful for sys admins only.

### Describe the solution you'd like

Show this badge only to sys admins by replacing `if ($user->auth_mode !== 'local')` with `if ($user->auth_mode !== 'local' && Yii::$app->user->isAdmin())` in https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/grid/DisplayNameColumn.php#L46

I can send a PR if you want.

### Describe alternatives you've considered

Delete this badge.

**Comment by luke-** [comment]
@funkycram Ok sounds good, so we only display it for sys admins!

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/6032 Thanks

**Comment by luke-** [comment]
@funkycram Thanks!
