### ISSUE TITLE
Timezones & Deletable Profile Fields

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#604]
**A)** We should have the ability for user assigned timezones as shown in [Yii Documentation](http://www.yiiframework.com/wiki/197/local-time-zones-and-locales/#hh5)

I am attempting to add this via the custom fields, if I figure it out I'll share the relative code and you can make it a default and required field (but has a default value) field. 

**B)** All profile fields should be deletable besides requires ones like firstname, lastname, user title. However, I should be able to delete whether a user stores 3 different numbers, or just Work and Mobile. Or, whether a user should put their address on my website. Or whether I want users posting links to MySpace, Google+, or Facebook. Depending on the community, it could be harmful. In my case, I just don't want people putting their addresses online, and I'm not sure what Xing is but I'm sure none of my users use it.

**Comment by programguy** [comment]
B) You can make those fields invisible and read-only using the User Profiles section in the administration area. (Maybe you already knew about this.) It is a little harder than it should be though.

**Comment by WASasquatch** [comment]
Yes, however they are still there, taking up MySQL queries and space. And space in my ACP. I don't need them, ever, and since they are not relied upon in the system, should be completely removable.

**Comment by programguy** [comment]
+1

**Comment by Lokke** [comment]
+1

**Comment by programguy** [comment]
I just research the profile fields thing a little bit. This commit: https://github.com/humhub/humhub/commit/273b0ef59366726f5d641f8a5c1e94950b3d7e44
is where all default profile fields became non-removable. They are marked as system, and therefore, cannot be deleted. So all we need to do is unmark the ones that should be removable.

**Comment by WASasquatch** [comment]
Yeah I saw that too. But again, this is something that shouldn't be there in the main system to begin with. 

Also, I noticed descriptions aren't displayed for your profile fields creating a huge UX gap.

**Comment by luke-** [comment]
You can only mark system/default profile fields as not visible.

Reasons:
  - Future modules like SMS/XMPP Gateway or themes may rely on them.
  - These fields are translated by the community

**Comment by WASasquatch** [comment]
Those are sort of mundane reasons... what if I do not want to install the SMS or XMPP gateway modules, as they are inherently modules, and optional, thus the field should be able to be deleted. Again, it brings up security concerns on a commercial installation ran by up 100 admins, and possible disputes.

**Comment by rwatts3** [comment]
I agree, 
locking down fields as apart of the base core sort of goes against the modular approach.
Modular should give us the ability to remove these fields if we do not need them. 
I can see having things that are modularly dependant such as the Profiles section altogether as a necessary schema item, but not the arbitrary fields contained within them. At least add the option to the main profiles page to bulk hide, edit, or make fields required rather than having to enter each section and rinse, wash, repeat the process. There are quite a bit of fields that are in need of disable and this process alone has taken me quite some time to disable or hide them all.
