### ISSUE TITLE
Admin lock/unlock comments

### ISSUE THREAD

**Issue by tpnsolutions** [humhub/humhub#6043]
It seems only an "owner" of a space can "lock/unlock" comments. While "impersonating" an owner allows an "admin" to conduct these tasks, it seems logical to allow an "admin" to conduct these tasks by default.

What is the logic to only allowing a space "owner" the ability to conduct tasks like this?

To clarify, I believe both an "owner" and "admin" should have this ability.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6047.

**Comment by luke-** [comment]
@yurabakhtin The author of a content should not be able to do this. Only Space members with the "ManageContent" permission or "global" administrators.

**Comment by yurabakhtin** [comment]
@luke- Ok, I changed this in commit https://github.com/humhub/humhub/pull/6047/commits/ee18bf462bc45e3e203921aa7a25c0199cc1af91.
