### ISSUE TITLE
Dynamic Hostname for Media

### ISSUE THREAD

**Issue by tpnsolutions** [humhub/humhub#6044]
In the interest of utilizing parallel downloading capability of browser, I'm wondering if it'd be possible to map media such as JavaScript, css, images and videos through a set of subdomains.

Ex.

1.static.domain.com
2.static.domain.com
3.static.domain.com

The idea would be to map these subdomains as aliases at the web server level, then map them in humhub, whereby humhub would reference the subdomain when rendering the pages.

The way the domains are mapped on rendering could be in a random model and would allow these static assets to be downloaded in parallel to the browser where the browser supports it.

**Comment by ArchBlood** [comment]
My only question would be the overall use case for such a thing?

If it's to be used as a CDN then you would have to map not only the core but also modules, and I shouldn't have to remind anyone of the downsides of using CDN. :thinking:

**Comment by tpnsolutions** [comment]
Actually my bad, my basis for this request was from dated information meant for HTTP/1.1 standards. It appears HTTP/2 addresses the parallel request model already.
