### ISSUE TITLE
Notify Members in a post - Cannot select users

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#6045]
PHP8.1
HH1.13.0 fresh install - native theme
 **Steps to reproduce:**
 - Add a new post
- Open the "Notify members" functionnality
- Try to enter the first letters of the members you want to notify
- And you will get this **"waiting wheel" during hours.**
![image](https://user-images.githubusercontent.com/91057837/212528981-f2fcba10-ef91-4a03-8049-f322118a890c.png)

We get this behaviour on 3 of our HH1.13.0 sites.
**Is it a bug or a wrong setting/install of our sites?**

Error in console as soon as I enter the first letters:
![image](https://user-images.githubusercontent.com/91057837/212532294-eb400d43-11e0-4eea-a4c6-8f46a6eefde2.png)

**Additional QUESTION**: What will happen if we succeed in adding these "Notified Members"? Will they be notified in addition to the normal notifications? Or in place of the normal notifications? Will they receive a mail even if they did not ask for ? Can we add members that do not belong to the space where the post is written?
Thanks in advance for advice.

**Edit:** please notice that in the same site you can select a "@member" without issue: 
![image](https://user-images.githubusercontent.com/91057837/212565957-986ca19d-1b98-41f8-b2f1-41377daa87ef.png)

**Comment by luke-** [comment]
@Gilbertdelyon Can you reproduce this behavior on our demo hosting?

**Comment by Gilbertdelyon** [comment]
@luke- 
Yes it works. 
So, I need a bit more time for investigation in the logs of our sites
May be tomorow
I'll keep you informed

**Comment by Gilbertdelyon** [comment]
**NEW TEST.**
PHP 8.1.0
Reinstall a brand new fresh naked HH 1.13.0 (fully native install, no custom theme, no additional module, no additional space, only native demo users) . SSL let's Encrypt
**And again the same issue:**
Screen crop after some minutes
![image](https://user-images.githubusercontent.com/91057837/212771427-f1d933a7-0297-4121-8a51-a47ddd7fa0c2.png)

HH site logs empty
![image](https://user-images.githubusercontent.com/91057837/212771654-3f7aa75e-1ffa-42e1-acbe-5d86af77977a.png)

Server Error logs (cPanel): Empty (the last error is 3 days old)

The only hints are 2 errors in console:
![image](https://user-images.githubusercontent.com/91057837/212772503-5dcca1d5-9dbc-4946-9a22-6cf8e566f915.png)
They are triggered as soon as I type the third letter of the famous Sara Shuster.

Adding members to be notified  is not at all a key functionnality for our site, but I would be please to understand what happens, because if something is wrong in our installation it could affect another function.

**Comment by luke-** [comment]
@Gilbertdelyon I just noticed, the bug is known and will be fixed with version 1.13.1. I expect we will release this version in the next few days

https://github.com/humhub/humhub/blob/master/CHANGELOG.md
Fix #5985: Space user search in picker

**Comment by Gilbertdelyon** [comment]
@luke- Thank you for this prompt answer. 
I am now more confident in our installation !

**Comment by ArchBlood** [comment]
I believe it subscribes them to content updates related to the post(s).

**Comment by Gilbertdelyon** [comment]
As far as I can see in HH demo site/
- You can add ONLY members of the space 
- You can add these members only before sending the post. (You cannot add in comment)
