### ISSUE TITLE
Admin can create a password for a user that isn't valid for login

### ISSUE THREAD

**Issue by michaelh99** [humhub/humhub#6050]
When changing a password for a user, the admin can use a password that isn't valid such as "beagles"

The system will accept that password but when the user tries to use it, the user is unable to log in.

| HumHub version   | 1.13.0

**Comment by michaelh99** [comment]
@luke- No, no errors in the admin interface when changing the users password. 

This is just a plain web user.

**Comment by luke-** [comment]
Can you reproduce this on our demo hosting?
