### ISSUE TITLE
When you are the creator of a space you will NOT receive the "NEW UPDATE AVAILABE" message

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#6051]
Brand new **HH 1.13.0** installation. Only native modules. and native theme
it works!

A user is adding a post in a space (let's say the native WELCOME space)
If another user is visiting the site at same time:
-  he will receive a "NEW UPDATE AVAILABE" message 
-  and the new post will be added in the "latest activities"
 like this:
![image](https://user-images.githubusercontent.com/91057837/213668659-66e9c074-d393-455e-9008-a940d25a7a12.png)
OK, it works!

**Now lets's create new spaces:**
**User A** creates a new spaceX and invites other users.
**User A** adds a post to this spaceX.
Other users are visting the site. They receive the "NEW UPDATE AVAILABE" message
OK, it works!

**And now the issue:**
One of the other  users (let's say **user B**)  adds a post in the spaceX 
User A   **DOESN'T** receive the "NEW UPDATE AVAILABE" message.

**Now lets do the opposite:**
User B creates a new spaceY and adds a post to it
User A will receive the "NEW UPDATE AVAILABE" message

User A adds a post to it
User B will **NOT** receive the  "NEW UPDATE AVAILABE" message

Conclusion is in the title of this issue.
Is it the normal way? It it a bug? or did I miss some setting?.

**Comment by ArchBlood** [comment]
@luke- it's probably because space owner/admin isn't subscribed to new content automatically when creating a space.

**Comment by yurabakhtin** [comment]
@Gilbertdelyon Thank you for the report this bug!

@luke- Fixed in PR https://github.com/humhub/humhub/pull/6053.
Problem was because a cache was not be refreshed for a space creator as it is normally done on trigger event `Membership::EVENT_MEMBER_ADDED`.

**Comment by Gilbertdelyon** [comment]
@yurabakhtin My pleasure,
It took me a while to trap this one!
