### ISSUE TITLE
Switch to page 2 of notifications loses filter selection

### ISSUE THREAD

**Issue by atdqm** [humhub/humhub#6054]
### What steps will reproduce the problem?
I click on the "Show all notifications" link /notification/overview
I click on some of the filters to remove them but I leave enough so that there is pagination at the bottom of the page
I click on page 2 /notification/overview/index?reload=1&page=2

### What is the expected result?
The page show the page 2 and the filters on the right

### What do you get instead?
The interface of the page seems broken, the filters on the right are gone and the content does not take into account the filters anymore
![image](https://user-images.githubusercontent.com/112695767/214002397-2c124aa2-644a-468a-b133-e5c9e96b4f95.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.0
| PHP version      |  	7.4.33
| Operating system | HumHub Cloud Hosting

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6059.
