### ISSUE TITLE
the checkboxes of the filters on the all notifications page does not change their status

### ISSUE THREAD

**Issue by atdqm** [humhub/humhub#6055]
### What steps will reproduce the problem?

I go to the all notification page /notification/overview
I click on the checkbox of any filter (not on the text, but inside the checkbox)
![image](https://user-images.githubusercontent.com/112695767/214002995-7d7f330e-97c0-434d-9701-e4c946621f11.png)

### What is the expected result?
The checkbox status changes

### What do you get instead?
the checkbox status doesn't change

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.0
| PHP version      | 7.4.33
| Operating system | HumHub Cloud Hosting
| Firefox | 105.0

**Comment by yurabakhtin** [comment]
@atdqm Thank you fo the report!
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6056.
