### ISSUE TITLE
User Profile - About Page going to Internal Error

### ISSUE THREAD

**Issue by jayavman** [humhub/humhub#6057]
User Profile Page
<img width="275" alt="Screenshot 2023-01-24 at 9 45 25 am" src="https://user-images.githubusercontent.com/114973646/214170659-3011c3eb-fd80-4fee-919c-ac50a27f4e38.png">
Click On About
<img width="563" alt="Screenshot 2023-01-24 at 9 45 33 am" src="https://user-images.githubusercontent.com/114973646/214170678-16eccfad-1214-4699-9e56-024a02ab29ed.png">

Page should be on the about page but with no content if someone hasn't added info about them.

| HumHub version | 1.13.0
| PHP version | 8.1.13

**Comment by jayavman** [comment]
Ahh It maybe based around the Birthday issue I reported on a separate occurrence.

 yii\base\ErrorException: DateTime::createFromFormat(): Passing null to parameter #2 ($datetime) of type string is deprecated in /home/fredons/public_html/hub/protected/humhub/modules/user/models/fieldtype/Birthday.php:180
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'DateTime::creat...', '/home/fredons/p...', 180)
#1 /home/fredons/public_html/hub/protected/humhub/modules/user/models/fieldtype/Birthday.php(180): DateTime::createFromFormat('Y-m-d', NULL, Object(DateTimeZone))
#2 /home/fredons/public_html/hub/protected/humhub/modules/user/models/ProfileField.php(314): humhub\modules\user\models\fieldtype\Birthday->getUserValue(Object(humhub\modules\user\models\User), true)
#3 /home/fredons/public_html/hub/protected/humhub/modules/user/models/Profile.php(339): humhub\modules\user\models\ProfileField->getUserValue(Object(humhub\modules\user\models\User))
#4 /home/fredons/public_html/hub/protected/humhub/modules/user/models/Profile.php(308): humhub\modules\user\models\Profile->getProfileFields(Object(humhub\modules\user\models\ProfileFieldCategory))
#5 /home/fredons/public_html/hub/protected/humhub/modules/user/views/profile/about.php(12): humhub\modules\user\models\Profile->getProfileFieldCategories()
#6 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/View.php(347): require('/home/fredons/p...')
#7 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/fredons/p...', Array)
#8 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/fredons/p...', Array, Object(humhub\modules\user\controllers\ProfileController))
#9 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('about', Array, Object(humhub\modules\user\controllers\ProfileController))
#10 /home/fredons/public_html/hub/protected/humhub/modules/user/controllers/ProfileController.php(96): yii\base\Controller->render('about', Array)
#11 [internal function]: humhub\modules\user\controllers\ProfileController->actionAbout()
#12 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('about', Array)
#15 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/profile/ab...', Array)
#16 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#17 /home/fredons/public_html/hub/index.php(25): yii\base\Application->run()
#18 {main}

**Comment by luke-** [comment]
Will be fixed here: https://github.com/humhub/humhub/issues/5997

The 1.13.1 will be released probably tomorrow.
