### ISSUE TITLE
Spaces/Files - Internal Error

### ISSUE THREAD

**Issue by jayavman** [humhub/humhub#6058]
Go to Spaces, Go to Files comes up with Internal Error (Not birthday issue)

yii\base\ErrorException:8192
yii\base\ErrorException: strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/helpers/BaseHtml.php:345
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'strcasecmp(): P...', '/home/fredons/p...', 345)
#1 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/helpers/BaseHtml.php(345): strcasecmp(NULL, 'get')
#2 /home/fredons/public_html/hub/protected/modules/cfiles/views/browse/index.php(29): yii\helpers\BaseHtml::beginForm(NULL, NULL, Array)
#3 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/View.php(347): require('/home/fredons/p...')
#4 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/fredons/p...', Array)
#5 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/fredons/p...', Array, Object(humhub\modules\cfiles\controllers\BrowseController))
#6 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('index', Array, Object(humhub\modules\cfiles\controllers\BrowseController))
#7 /home/fredons/public_html/hub/protected/modules/cfiles/controllers/BrowseController.php(36): yii\base\Controller->render('index', Array)
#8 [internal function]: humhub\modules\cfiles\controllers\BrowseController->actionIndex()
#9 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#12 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('cfiles/browse', Array)
#13 /home/fredons/public_html/hub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#14 /home/fredons/public_html/hub/index.php(25): yii\base\Application->run()
#15 {main} 

| HumHub version | 1.13.0
| PHP version | 8.1.13

**Comment by luke-** [comment]
Should be fixed with Filesmodule v0.15.0

**Comment by luke-** [comment]
https://github.com/humhub/cfiles/issues/165
