### ISSUE TITLE
Cannot create an account from space invite with SSO if new users cannot register

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6075]
Same problem as https://github.com/humhub/humhub/issues/3593 (which is resolved), but when "New users can register" is unticked.

### What steps will reproduce the problem?

1. Add an SSO to Humhub.
2. In the settings, untick "New users can register"
3. In a space, invite a new user
4. The user click on the button in the mail
5. He click on the SSO button to create his account

### What is the expected result?

When he comes back from the SSO login, the Humhub form allows him to fill in his profile fields (username and password fields are hidden).

### What do you get instead?

An error dialog displays "You're not registered." under the SSO button and he needs to register the conventional way (username and password fields are displayed).

![image](https://user-images.githubusercontent.com/23310825/215109685-2e3bd6bf-09b0-475a-bd74-72316664cd1e.png)

### Additional info

The problem is in this if condition: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/controllers/AuthController.php#L170-L174
```php
if (!$authClient instanceof ApprovalBypass && !Yii::$app->getModule('user')->settings->get('auth.anonymousRegistration')) {
...
}
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.1

**Comment by funkycram** [comment]
@luke- fixed in commit https://github.com/humhub/humhub/commit/79f9d31329bc7e5a5239e473c71fe20dc3218a77
See discussion here: https://github.com/humhub/humhub/issues/6164#issuecomment-1507210055

**Comment by luke-** [comment]
@funkycram Thanks. Lets close this issue and proceed with #6164
