### ISSUE TITLE
Registration failed: No token (query) or authclient (session) found!

### ISSUE THREAD

**Issue by gituser317** [humhub/humhub#6084]
Good day,

we are getting the error message **Registration failed** if a new user logins for the first time via LDAP.
In the logs we see the folling error: Registration failed: No token (query) or authclient (session) found!.

Environment:
- Ubuntu 22.04.
- Humhub 1.13.0

**Comment by luke-** [comment]
Maybe related to this: https://github.com/humhub-contrib/legal/blob/master/docs/CHANGELOG.md#133-january-24-2023

Are you using this module?

**Comment by gituser317** [comment]
No, the modules we are using are:

- Custom Pages 1.8.6
- Polls 1.2.1
- Scroll Up 1.0.6
- Show selected content 1.6.0

**Comment by luke-** [comment]
Strange. Are you using a reverse proxy and is the base url (under Administration -> Settings) set correctly?

**Comment by gituser317** [comment]
I have checked the base url and its set correctly. We do not use a reverse proxy.

Our Apache webserver config looks like below:
```
<VirtualHost *:80>
        ServerName subdomain.domain.com

        RewriteEngine On
        RewriteRule ^/?(.*) https://%{SERVER_NAME}:443/$1 [R,L]

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>


<VirtualHost *:443>
        ServerName subdomain.domain.com
        DocumentRoot /var/www/humhub

        <Directory /var/www/humhub>
                Options -Indexes
        </Directory>

        ProxyRequests off
        SSLEngine On
        SSLProtocol -all +TLSv1.2
        SSLCertificateFile /etc/apache2/ssl/cert.crt
        SSLCertificateKeyFile /etc/apache2/ssl/key.key
        RequestHeader set X-Forwarded-Proto "https"
        Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
</VirtualHost>
```

**Comment by gituser317** [comment]
Any ideas on this or anything i can provide you? It's quite urgent cause no new user can use our humhub.
Can it be related to a space in username? Our sAMAccountName is 'Firstname Lastname'.

**Comment by luke-** [comment]
@gituser317 It would be interesting if you could check the redirects/requests in the network tabs of the Browser Console to see if the domain is being changed. Somehow a session value is lost during the registration.

**Comment by gituser317** [comment]
So i have performed a login workflow with a testuser and got the `Registration failed` message. In the network tab i have checked the requests of type `document / Redirect` and `fetch / Redirect`:

![image](https://user-images.githubusercontent.com/32760949/218697227-6d43f848-c54a-44e1-a0cd-4e45f353c687.png)

I i make a mouse over i can see the correct and same domain on the colums name and initiator.

**Comment by luke-** [comment]
The apache2 error is interesting.

Can you try to add following method to the class `protected/humhub/modules/ldap/authclient/LdapAuth.php`.

```php
    public function __serialize(): array
    {
        $this->_ldap = null;
    }
```

**Comment by gituser317** [comment]
If i add this to the class `protected/humhub/modules/ldap/authclient/LdapAuth.php` i get this:

`PHP Fatal error:  Uncaught TypeError: humhub\\modules\\ldap\\authclient\\LdapAuth::__serialize(): Return value must be of type array, none returned in /var/www/humhub/protected/humhub/modules/ldap/authclient/LdapAuth.php:586\nStack trace:\n#0 [internal function]: humhub\\modules\\ldap\\authclient\\LdapAuth->__serialize()\n#1 /var/www/humhub/protected/vendor/yiisoft/yii2/web/DbSession.php(166): session_write_close()\n#2 [internal function]: yii\\web\\DbSession->close()\n#3 {main}\n  thrown in /var/www/humhub/protected/humhub/modules/ldap/authclient/LdapAuth.php on line 586, referer: https:/sub.domain.com/index.php?r=dashboard%2Fdashboard`

**Comment by luke-** [comment]
Please use instead

```

    public function __sleep()
    {
        $this->_ldap = null;
    }
```

**Comment by luke-** [comment]
@gituser317 Should be fixed now. Can you please test the PR?
