### ISSUE TITLE
[Problem] Get Errors and not be done any cron jobs : symfony process of vendor?

### ISSUE THREAD

**Issue by tosintech-web** [humhub/humhub#6086]
### What steps will reproduce the problem?
I could updated PHP version from 7.4.3 to 8.1.15. Then I run Composer Update.

### What is the expected result?
I expected no problem, no error.

### What do you get instead?
Our HumHub stopped sending daily reports. And it does not be done any cron jobs.
The following message is now left in the error log every minute.
```
ParseError: syntax error, unexpected token ")" in /var/www/localhost/htdocs/protected/vendor/symfony/process/Process.php:311
Stack trace:
#0 /var/www/localhost/htdocs/protected/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#1 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(185): Composer\Autoload\ClassLoader->loadClass()
#2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(126): yii\queue\cli\Command->handleMessage()
#3 [internal function]: yii\queue\cli\Command->yii\queue\cli\{closure}()
#4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144): call_user_func()
#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83): yii\queue\cli\Queue->handleMessage()
#6 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}()
#7 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func()
#8 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker()
#9 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run()
#10 [internal function]: yii\queue\db\Command->actionRun()
#11 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#12 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#13 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#14 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#15 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#16 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#17 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#18 /var/www/localhost/htdocs/protected/yii(29): yii\base\Application->run()
#19 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.3
| PHP version      |  8.1.15
| Operating system | docker (php: 8.1-fpm-alpine3.16)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by tosintech-web** [comment]
According to the compose.lock file, the version of symfony/process is v6.2.5.

**Comment by luke-** [comment]
@tosintech-web Is it possible that the queue runners are running with an older version of PHP? Can you try an update to the current HumHub version including dependencies?

**Comment by ArchBlood** [comment]
> @tosintech-web Is it possible that the queue runners are running with an older version of PHP? Can you try an update to the current HumHub version including dependencies?
> 
> 

That would be dependent on the version of the docker image wouldn't it?

**Comment by tosintech-web** [comment]
Thak you for reply, Archblood.
I was running HumHub with PHP 7.4 before. Queue runner was crond which was started by supervisord. 

Then I wrote docker compose file which runs  PHP8.1, I change dependencies versions.

umm... docker images version? I' ll check it after.

Thank you.

**Comment by tosintech-web** [comment]
Hi, Archblood.

That error had been occcured in php:8.1-fpm-alpine3.16.
I tried docker with other image version, php:8.1-fpm-alpine3.15. Then, that error was not occured.
But, it seems to be not running queue with 3.15 image.  I will continue my investigation.

Thank you.

**Comment by tosintech-web** [comment]
Finaly, I gave up crond and starting to use Cron Daemon module and gettting that now works as expected.

<What we found> 

- php:8.1-fpm-alpine3.16 occurs error at synfony process module.

- php:8.1-fpm-alpine3.15 can't run crond ( It doesn't work similar way as  php:7.4-fpm-alpine3.15 with supervisord. )
