### ISSUE TITLE
parse_str(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by TheFox** [humhub/humhub#6103]
### What steps will reproduce the problem?

1. Browse to /admin/setting/oembed
2. Klick on "Add new provider".
3. Error

### What is the expected result?

To add a new provider.

### What do you get instead?

```
PHP Deprecated Warning – [yii\base\ErrorException](https://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
parse_str(): Passing null to parameter #1 ($string) of type string is deprecated

1. in /var/www/html/protected/humhub/modules/admin/views/setting/oembed_edit.php
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.2
| PHP version      | 8.1.15
| Operating system | Debian 11

### Additional Question

Why does the Versions page https://docs.humhub.org/docs/admin/requirements says HumHub is PHP 8 ready when it's clearly not ready for PHP 8?

**Comment by yurabakhtin** [comment]
@TheFox Thank you for the report!
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6106.
