### ISSUE TITLE
Troubles with email in 1.13.1

### ISSUE THREAD

**Issue by liloumuloup** [humhub/humhub#6121]
### What steps will reproduce the problem?
The users of the instance i'm taking care of told me that they didn't receive the email notification anymore.
It was a 1.12.1.
I tried to upgrade to 1.13.1, and now a have this error in my journal (this is the full error) : 
```
 Could not set mailer transport: Transport configuration array must contain either "dsn", or "scheme" and "host" keys.
```

I don't know if it was linked to these or not but it doesn't seems to be the same error : 
https://github.com/humhub/humhub/issues/5912
https://github.com/humhub/humhub/issues/5893

I'm using the SMTP written in php.ini. I have access to it but i can't change the parameters as it's not a dedicated server.

Can you help ?

Kind regards.

### What is the expected result?
No error in journal and email notification

### What do you get instead?
Error in journal and no email notification

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.1
| PHP version      | 8.0
| Operating system | Debian GNU/Linux 8.11

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
What are your e-mail settings in Administration -> Settings -> E-Mail?

**Comment by liloumuloup** [comment]
Here are for the summaries : 
![image](https://user-images.githubusercontent.com/4968531/220320283-cbecd3c8-99dd-444e-aff0-aaeddbea68b8.png)

Here is for the advanced panel : 
![image](https://user-images.githubusercontent.com/4968531/220321207-a530a37a-f069-43ed-bfbb-1acaafb36c8e.png)

**Comment by luke-** [comment]
Hmm, strange. there is also no test e-mail sent when the e-mail server setting is saved?
Can you try a sender name without accents?

**Comment by liloumuloup** [comment]
I tried to update the sender name without accent and got this error when saving : 
```
Error: Call to undefined function Symfony\Component\Mailer\Transport\Smtp\Stream\proc_open() in /var/www/humhub/protected/vendor/symfony/mailer/Transport/Smtp/Stream/ProcessStream.php:41
Stack trace:
#0 /var/www/humhub/protected/vendor/symfony/mailer/Transport/SendmailTransport.php(114): Symfony\Component\Mailer\Transport\Smtp\Stream\ProcessStream->initialize()
#1 /var/www/humhub/protected/vendor/symfony/mailer/Transport/AbstractTransport.php(72): Symfony\Component\Mailer\Transport\SendmailTransport->doSend(Object(Symfony\Component\Mailer\SentMessage))
#2 /var/www/humhub/protected/vendor/symfony/mailer/Transport/SendmailTransport.php(77): Symfony\Component\Mailer\Transport\AbstractTransport->send(Object(Symfony\Component\Mailer\SentMessage), Object(Symfony\Component\Mailer\DelayedEnvelope))
#3 /var/www/humhub/protected/vendor/symfony/mailer/Mailer.php(45): Symfony\Component\Mailer\Transport\SendmailTransport->send(Object(Symfony\Component\Mime\Email), NULL)
#4 /var/www/humhub/protected/vendor/yiisoft/yii2-symfonymailer/src/Mailer.php(210): Symfony\Component\Mailer\Mailer->send(Object(Symfony\Component\Mime\Email))
#5 /var/www/humhub/protected/humhub/components/mail/Mailer.php(120): yii\symfonymailer\Mailer->sendMessage(Object(Symfony\Component\Mime\Email))
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/mail/BaseMailer.php(263): humhub\components\mail\Mailer->sendMessage(Object(humhub\components\mail\Message))
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/mail/BaseMessage.php(49): yii\mail\BaseMailer->send(Object(humhub\components\mail\Message))
#8 /var/www/humhub/protected/humhub/modules/admin/controllers/SettingController.php(205): yii\mail\BaseMessage->send()
#9 [internal function]: humhub\modules\admin\controllers\SettingController->actionMailingServerTest()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('mailing-server-...', Array)
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/setting/m...', Array)
#14 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#15 /var/www/humhub/index.php(25): yii\base\Application->run()
#16 {main}
```

**Comment by luke-** [comment]
Seem your PHP installation has `proc_open` disabled, which is required for the mail transport. You can may try to use another mail option.

**Comment by liloumuloup** [comment]
After looking at the `php_ini`, i can confirm `proc_open` has been disabled : 
```
php_admin_value[disable_functions]=set_time_limit,passthru,exec,system,popen,shell_exec,proc_open,pcntl_exec

```

Fortunatly, i had enough rights to re-enable it and it seems to work now. Thank you for you help !
