### ISSUE TITLE
We would like to see the certification mark implemented.

### ISSUE THREAD

**Issue by aris-mirai** [humhub/humhub#6124]
to<! --
Thank you for suggesting an idea to make HumHub better.

Please fill in as much of the template below as you can.
--> 
Please fill in as much of the template below as you can. I am using HumHub to run a social networking site, and there are many impersonators, especially recently, and many of them are dangerous. So I would like to be able to put an authentication mark on my users. Also, I would like to see additional variations added to the authentication mark (colors, etc.) For example, on Twitter, you can use
Blue is the certification mark for individuals, gold is the certification mark for companies, and gray is the certification mark for governments. I propose that HumHub also implement such an easily recognizable certification mark.

### Please fill in as much of the template below as you can.
Yes, please describe. I believe that spoofing and spam will be eliminated by implementing an official mark.
### Describe the solution you'd like
Describe the solution you'd like
### Describe alternatives you've considered
HumHub has a module that implements the certification mark, but it is currently not working. So, I'd like you to implement it.

**Comment by ArchBlood** [comment]
Duplicate #920

**Comment by aris-mirai** [comment]
I found this code and tried it out.
URL https://github.com/humhub/humhub/issues/920#issuecomment-377828769
I tried to put it in ProfileHeader.php but I got an error and could not do it. And I also put it in containerProfileHeader.php, no error, but it didn't change.
I do not know where to place it. If you could tell me where to place it and give me a sample, that would be great.
Thank you in advance.
