### ISSUE TITLE
Add default settings for space creation

### ISSUE THREAD

**Issue by atdqm** [humhub/humhub#6130]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
In the space administration page (/admin/space/settings) we can choose somme default settings for the creation of spaces by members.

I'd like to add some other choices  :

- checkboxes for hidding some blocks
- dropdown lists to choose the default start pages (see #6129 for the texts of the last one)

![image](https://user-images.githubusercontent.com/112695767/221565163-a9f42e82-762c-44e1-a3fb-cce22d88e696.png)

**Comment by luke-** [comment]
I would like to see this feature and would be great when you create a PR for it.
The "homepage" could be a bit difficult, since it differs from space to space. (Different modules / custom pages)

Please consider some time for automated tests. If you have any questions about this, feel free to write me.

**Comment by funkycram** [comment]
Thanks.
About the "home page", I though we could give the choice only between Stream and About.

After adding the properties to the `SpaceSettingsForm` and view, I was thinking about replacing the `loadBySettings()` method, in https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/space/models/AdvancedSettings.php#L104
with something like this (I haven"t test maybe it's needs adjustments):
```php

    public function loadBySettings()
    {
        /** @var Module $module */
        $module = Yii::$app->getModule('space');

        $settings = $this->space->getSettings();

        $this->url = $this->space->url;
        $this->indexUrl = $settings->get('indexUrl', $module->settings->get('defaultIndexUrl'));
        $this->indexGuestUrl = $settings->get('indexGuestUrl', $module->settings->get('defaultIndexGuestUrl'));

        $this->hideMembers = $settings->get('hideMembers', (bool)$module->settings->get('defaultHideMembers'));
        $this->hideAbout = $settings->get('hideAbout', (bool)$module->settings->get('defaultHideAbout'));
        $this->hideActivities = $settings->get('hideActivities', (bool)$module->settings->get('defaultHideActivities'));
        $this->hideFollowers = $settings->get('hideFollowers', (bool)$module->settings->get('defaultHideFollowers'));
    }
```

I'm not quite sure about which automated tests we would need, as for the moment I haven't seen any test about the existing `SpaceSettingsForm` properties (`defaultVisibility`, etc.).
Thanks!

**Comment by ArchBlood** [comment]
> Thanks. About the "home page", I though we could give the choice only between Stream and About.
> 
> After adding the properties to the `SpaceSettingsForm` and view, I was thinking about replacing the `loadBySettings()` method, in https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/space/models/AdvancedSettings.php#L104 with something like this (I haven"t test maybe it's needs adjustments):
> 
> ```
>     public function loadBySettings()
>     {
>         /** @var Module $module */
>         $module = Yii::$app->getModule('space');
> 
>         $settings = $this->space->getSettings();
> 
>         $this->url = $this->space->url;
>         $this->indexUrl = $settings->get('indexUrl', $module->settings->get('defaultIndexUrl'));
>         $this->indexGuestUrl = $settings->get('indexGuestUrl', $module->settings->get('defaultIndexGuestUrl'));
> 
>         $this->hideMembers = $settings->get('hideMembers', (bool)$module->settings->get('defaultHideMembers'));
>         $this->hideAbout = $settings->get('hideAbout', (bool)$module->settings->get('defaultHideAbout'));
>         $this->hideActivities = $settings->get('hideActivities', (bool)$module->settings->get('defaultHideActivities'));
>         $this->hideFollowers = $settings->get('hideFollowers', (bool)$module->settings->get('defaultHideFollowers'));
>     }
> ```
> 
> I'm not quite sure about which automated tests we would need, as for the moment I haven't seen any test about the existing `SpaceSettingsForm` properties (`defaultVisibility`, etc.). Thanks!

I like the idea behind this, but there is a lot of changes between the variables used, namely the `default` being added, dropping this would be fine and easier to manage without much change to the codebase while also making the code cleaner and not stretched out.

![Screenshot_1](https://user-images.githubusercontent.com/35392110/224519088-e87d6665-0394-45be-b7a2-a60999e32478.png)

I also believe that it can be extended to shorten `$module->settings` as well.

So something like this;

```php
    public function loadBySettings()
    {
        /** @var Module $module */
        $module = Yii::$app->getModule('space')->settings;

        $settings = $this->space->getSettings();

        $this->url = $this->space->url;
        $this->indexUrl = $settings->get('indexUrl', $module->get('indexUrl'));
        $this->indexGuestUrl = $settings->get('indexGuestUrl', $module->get('indexGuestUrl'));

        $this->hideMembers = $settings->get('hideMembers', (bool)$module->get('hideMembers'));
        $this->hideAbout = $settings->get('hideAbout', (bool)$module->get('hideAbout'));
        $this->hideActivities = $settings->get('hideActivities', (bool)$module->get('hideActivities'));
        $this->hideFollowers = $settings->get('hideFollowers', (bool)$module->get('hideFollowers'));
    }
```

**Comment by funkycram** [comment]
Thanks @ArchBlood for the suggestions. The `default` must be added to stay in the logic of https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/admin/models/forms/SpaceSettingsForm.php#L15

Yes, `$module->settings` can be replaced with `$settings` but this code was just to explain the idea.

@luke- About the "home page": If the choice is only between "Stream" and "About", I think we should also hide the field with javascript when "Hide "About" page" is ticked.

**Comment by luke-** [comment]
@funkycram Ok, would be good, if we use these two options for the "Homepage" setting.

Regarding the configuration, please see following Wiki page:
https://community.humhub.com/s/module-development/wiki/Module+Configuration

Maybe you can adjust the Model and code to this boilerplate?

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/6219
