### ISSUE TITLE
Sync existing LDAP-user after renaming (German Umlauts)

### ISSUE THREAD

**Issue by MarcusBauch** [humhub/humhub#6134]
Hej!

Having "trouble" to sync existing LDAP-user (openLDAP) after renaming. Eg. german Umlauts. oe to ö in givenname ...
Cronjobs up and running.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version | 1.13.1 or older (community)
| PHP version |  7.4.33
| Operating system | Debian Bullseye

`Administration --> Information --> Logging` -> no errors

**Comment by luke-** [comment]
Can you describe "Trouble" in more detail? :-)

This should usually no problem. But it is important that you have an ID attribute specified in the LDAP settings.
Maybe you can try to rebuild the mapping: https://docs.humhub.org/docs/admin/ldap#user-mapping-humhub-to-ldap

**Comment by MarcusBauch** [comment]
Hej Luke.

Thanks for responing.

As I wrote, it all works wonderfully. Likewise the LDAP mapping.

But if I rename a user, because e.g. data of the name were transmitted incorrectly (Böttcher instead of Boettcher), the change which was successfully completed in the LDAP, is apparently not perceived by HH.

**Comment by MarcusBauch** [comment]
Hej.

If this command bring up all LDAP-Attributes, the it works.
![humhub-1](https://user-images.githubusercontent.com/46030934/222123425-34fdc000-caad-41a1-8f41-8149c9033445.PNG)

...there are much more. This is filtered, because of privacy.

**Comment by luke-** [comment]
On the bottom of the ldap settings page, there is a checkbox "Auto sync" if it is not checked, there is only a sync on login.

**Comment by luke-** [comment]
Hmm thats strange..

**Comment by MarcusBauch** [comment]
...it is.
When the User is deleted (HH) and recreated it works... imo this is a Bug

**Comment by luke-** [comment]
Hmm, I tried the exact steps:

- changed the "givenName" of one user from "Max" to "Mäx".
- The change was synchronized correctly.

**Comment by MarcusBauch** [comment]
...i deleted the user, and after the reimport, without! other changes, it worded too. But, THIS is not a solution. How can i test what happen? Is there a hidden Debog-LOG?

![humhub-4](https://user-images.githubusercontent.com/46030934/222494373-e39ab0eb-03d6-4a48-a598-5563c0613945.png)

**Comment by luke-** [comment]
The fact that it is a community edition should not be a problem.

Are only umlaut changes not applied to the affected user or also other changes?

**Comment by MarcusBauch** [comment]
...don't know. I am going to test it...

**Comment by MarcusBauch** [comment]
...another test with Umlauts...

Created a Demo-User in LDAP with my name...import is sucuessfull. 
![humhub-5 1](https://user-images.githubusercontent.com/46030934/222575510-a5598711-caee-4586-92bc-c27a6561e01c.PNG)

...changed username in LDAP to "Marcüs"...
![humhub-5 3](https://user-images.githubusercontent.com/46030934/222575788-5dbc2558-ea31-40a7-a9aa-705e082b5b04.png)

...waiting until cronjob is running...
![humhub-5 2](https://user-images.githubusercontent.com/46030934/222575853-19a0df39-1163-45c0-89e5-6ea5075ca4ea.png)

...check server console again...
![humhub-5 4](https://user-images.githubusercontent.com/46030934/222576297-cc1cc684-5ae1-4f65-9579-fb186cf2308f.png)

Same result.

Now i change a normal ABC-character in my name and see what happens

**Comment by MarcusBauch** [comment]
...does not work
![humhub-6](https://user-images.githubusercontent.com/46030934/222590546-e6b58ee1-0879-41e8-95bc-9f618ed363d6.png)

![humhub-6 1](https://user-images.githubusercontent.com/46030934/222590774-f1aa2265-2cb6-47e7-9860-dbcdd11c7384.png)

**Comment by MarcusBauch** [comment]
...take a look into mysql...

This is the user creation time
![humhub-7](https://user-images.githubusercontent.com/46030934/222593320-fad8ff7a-97a4-4702-b20d-86e585d41afc.png)

**Comment by MarcusBauch** [comment]
Ooookay, It seens this is no LDAP <-> Import problem...i will try to figure it out, later

**Comment by MarcusBauch** [comment]
I dug through all the settings again.

In the menu "User administration/Profiles/About me" I found a newly created user attribute with a "mandatory field", which was set by the owner of the portal. This "mandatory field" prevents the update of the user properties which should be synchronized from LDAP. After I "filled in" the mandatory field, the LDAP matching went smoothly.

In my opinion this is wrong!

The users do not register themselves, but are "handpicked", so they can also fill in this mandatory field, which does not come from LDAP, only after creating their account. If they do not do this, the matching is prevented. At the latest when a user logs in for the first time, he should be asked to fill in this field. If the user logs in much later, it should not be that all changes, also those of other users, are discarded.

At this point HH should distinguish what comes from its own database, and what is read from external.

Because, such a mandatory field can also be activated much later in the settings, so then "per se" all updates from the LDAP are prevented.

**Comment by luke-** [comment]
Currently, there should be an entry in the log if an LDAP user cannot be saved due to missing information.

But  I agree with you, the validation should not be that strict in case of LDAP users. Feel free to open a feature request issue for this.
