### ISSUE TITLE
Unable to verify data submission 

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#6136]
### What steps will reproduce the problem?
It seems to be selective when reproducing the error but when on any stream (dashboard, space or profile stream) click to load more comments/replies

### What is the expected result?
Loading of comments/replies

### What do you get instead?
Error status bar pops up reading "Unable to verify data submission"

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | Community site
| PHP version      | Community site 
| Operating system | Community site 

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
@ArchBlood Can you provide a link  to an example? I can't reproduce it...

**Comment by ArchBlood** [comment]
> @ArchBlood Can you provide a link  to an example? I can't reproduce it... 

Happens on the community site via mobile.

https://community.humhub.com/dashboard

**Comment by luke-** [comment]
Hmm, cannot reproduce. Which browser / os?

**Comment by ArchBlood** [comment]
> Hmm, cannot reproduce. Which browser / os?

Android 12 Chrome browser

**Comment by ArchBlood** [comment]
The error popped up on dashboard for the following post once I was unsubscribed to notifications;
https://community.humhub.com/content/perma?id=265125

**Comment by ArchBlood** [comment]
I'm still encountering this issue and seems to only happen on slow load time of the dashboard or posts.

**Comment by luke-** [comment]
Any change to reproduce this or does this occur randomly?

**Comment by ArchBlood** [comment]
> Any change to reproduce this or does this occur randomly?

This is a random occurrence for larger communities that have to load posts on dashboard stream as well as space streams, I've only encountered this on the community site so far via pwa.

At the time that this happens is when the load button pops up and takes longer than expected which throws the error, it also throws the error if you push the load more button when this occurs. A quick refresh by pulling the screen down sometimes fixes the issue.

**Comment by ArchBlood** [comment]
From looking into this more I'm turning up the following possibilities `invalid csrf token, user generated csrf token, expired csrf token`

**Comment by luke-** [comment]
We have not been able to observe the problem yet.

The cause of the error is related to cookies and CSRF Protection. When cookies are lost for some reason, the error occurs. Really strange...

**Comment by ArchBlood** [comment]
> We have not been able to observe the problem yet.
> 
> The cause of the error is related to cookies and CSRF Protection. When cookies are lost for some reason, the error occurs. Really strange...

I'm wondering if the issue could be caused by switching between mobile data and WiFi connections?

**Comment by luke-** [comment]
Hmm, maybe but I don't think the cookies/session is bound to a specifc ip adress
