### ISSUE TITLE
Error when saving empty values in admin settings

### ISSUE THREAD

**Issue by noratchi** [humhub/humhub#6142]
It occurs in two fields.
- `Administration menu`->`Settings`->`Appearance`->**`Default pagination size`**
- `Administration menu`->`Settings`->`Advanced`->`Files`->**`Maximum upload file size`**

### What steps will reproduce the problem?
Humhub is running in debug mode.
___
In case **`Default pagination size`**
1. Empty the value and save (Can be saved normally)
2. Click the :mag: (search icon) on the top menu
3. Error occurs `TypeError Unsupported operand types: int * string`
___
In case **`Maximum upload file size`**
1. Empty the value and save
2. Error occurs `TypeError Unsupported operand types: string * int` 
  
| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.1
| PHP version      | 8.1
| Operating system |

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6143.
