### ISSUE TITLE
Invitation by link: when registering within an SSO, the email should only be requested on the service provider

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6164]
### Is your feature request related to a problem? Please describe.

1. Get an "invitation by link".
2. Open this link: a form asks you for your email
3. After sending your email, you receive a link in your mailbox
4. You can now click on the button register with the SSO (Facebook, Google, etc.)
5. If you don't have an account on the Service Provider (SP), you need to create one and enter again your email
6. Usually, the SP check your mailbox by sending a verification email

Problem:
- You need to type twice your email (on Humhub and the SP)
- You need to validate twice the address by receiving an email in your mailbox (Humhub & SP)

### Describe the solution you'd like

1. Get an "invitation by link".
2. **skip**
3. **skip**
4. **same**
5. **same**
6. **same**

### Technical proposal

To achieve this, we need to add the "invite by link" **token** and **space ID** to the return URL params sent to the SP.
Then, in `AuthController::onAuthSuccess()` we can detect this token and space ID to allow the user to create the account even if `Yii::$app->getModule('user')->settings->get('auth.anonymousRegistration')` is false.

But to be able to send more params in the return URL to the SP, we need to overwrite the `parametersToKeepInReturnUrl` attribute in all classes extending Oauth2 or OpenIdConnect. This means updating all the Humhub Auth modules (Google, Facebook, Keycloak, etc.) with something like:
```php

     /**
     * @inerhitdoc 
     */
     public $parametersToKeepInReturnUrl = [
        'authclient',
        'inviteToken',
        'inviteSpaceId',
    ];
```

@luke- if you approve this idea, I can send a PR.

**Comment by samuk** [comment]
@luke- did you have any thoughts on this?

**Comment by luke-** [comment]
@samuk Not yet
@funkycram Feel free to create a draft PR here.

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/6194
I need to do more use case testing.
But I first wanted to check with you if this proposal is correct for you.

With this PR, we don't need to overwrite the `$parametersToKeepInReturnUrl` property in all auth clients as suggested on my first technical proposal, as I can do it in the `AuthAction` class.

You'll see 2 `property_exists` in my PR. I'm not sure we need this. I've added it because the client is an instance of `StandaloneAuthClient` which doesn't have this property. But all clients extending BaseOauth have this property.

Perhaps I should replace the `property_exists` with `$client instanceOf BaseOauth`?
I don't know about LDAP, I've never used it. Should I do some tests with it too or it's useless?

Thanks!

PS: I took the opportunity of this work to fix a small problem: after login with SSO, the button to login was still shown on the registration form. It's now removed by adding `$showAuthClients = false;` (see https://github.com/humhub/humhub/pull/6194/files)

**Comment by luke-** [comment]
@funkycram Thanks for the PR. i would also take a closer look here after the v14 stable release.

**Comment by funkycram** [comment]
@luke- I've just committed this: https://github.com/humhub/humhub/pull/6194/commits/79f9d31329bc7e5a5239e473c71fe20dc3218a77

It fixes another problem:
If "New users can register" is disabled:
![image](https://user-images.githubusercontent.com/23310825/231815285-6b2551d3-62da-4fad-8e88-2a5305d38279.png)
And we invite someone by email
And he tries creating his account using and SSO
He gets the message: "You're not registered.":
![image](https://user-images.githubusercontent.com/23310825/231815992-fd4c1cb8-f4c3-465e-9afc-caae1a2b84d6.png)

**Comment by funkycram** [comment]
I forgot this last problem was already mentioned here: https://github.com/humhub/humhub/issues/6075
