### ISSUE TITLE
Content polymorphic relation : get class from getObjectModel() instead of the depreciated className()

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6169]
### What steps will reproduce the problem?

Create this parent class:
```php
class MyParentModel extends ContentActiveRecord {
    /**
     * @inheritdoc
     */
    public $autoFollow = true;
}
```
Create a sub-class:
```php
class MySubModel extends MyParentModel
{
    /**
     * @inheritdoc
     */
    public static function getObjectModel()
    {
        return MyParentModel::class;
    }
}
```

Create a new content using the sub model:
```php
(new MySubModel())->save();
```

### What is the expected result?

In the `user_follow`, the `object_model` is `MyParentModel`.

### What do you get instead?

The `object_model` is `MySubModel`.

### Additional info

this causes integrity failures in the DB.

I think we should, in https://github.com/humhub/humhub/blob/develop/protected/humhub/components/behaviors/PolymorphicRelation.php#L91, replace `$this->owner->setAttribute($this->classAttribute, $object->className());` with:
```php
                $className = is_callable([$object, 'getObjectModel']) ?
                    $object::getObjectModel() :
                    get_class($object);
                $this->owner->setAttribute($this->classAttribute, $className);
```

I'm not sure `is_callable` is useful as I think we always should have the `getObjectModel`, but I'm not sure, and I didn't test much.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14-beta-1
| PHP version      | 8.1

**Comment by luke-** [comment]
Hmm, I would say the "SubModel" is correct.
e.g. we have a similar case here:

https://github.com/humhub/cfiles/blob/master/models/FileSystemItem.php (Parent)
https://github.com/humhub/cfiles/blob/master/models/Folder.php (Sub)
https://github.com/humhub/cfiles/blob/master/models/File.php (Sub)

**Comment by funkycram** [comment]
If the case of humhub\modules\cfiles\models\File model, we have the sub-model in the `user_follow` table, which is what I don't want:
![image](https://user-images.githubusercontent.com/23310825/225230606-3e814f1b-09fc-4ce1-b6af-712e86ea82bc.png)

What I need, when I add this to the sub-class:
```php
    public static function getObjectModel()
    {
        return MyParentModel::class;
    }
```
is to have the parent in the `user_follow` table.

Currently, I need to add this in addition of the `getObjectModel()`:
```php
    public static function className()
    {
        return static::getObjectModel();
    }
```

This is because Humhub still uses the deprecated `className()` e.g. here: https://github.com/humhub/humhub/blob/develop/protected/humhub/components/behaviors/PolymorphicRelation.php#L91

If you want, I can send you more details with screenshots, but in another hand this issue is not very important, it was just to ask if it was possible to replace the deprecated `className()` with the `getObjectModel()` in Humhub core.
Thanks!

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look into this? I would like to avoid new additional methods if possible.

**Comment by funkycram** [comment]
In summary, we have 2 methods to force the class name:
- The deprecated `className` since Yii 2.0.14 but still used by Humhub
- The `getObjectModel` used by `ContentActiveRecord`
Thanks!

**Comment by luke-** [comment]
@funkycram Thanks for the brief overview. We should really refactor usages of the deprecated `className()` method.

**Comment by funkycram** [comment]
When available, if you can replace `className` with `getObjectModel` rather than `::class` if would allow forcing child models to have the parent's class name. Thanks!

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6185:

- for some cases I could replace `::className()` to `::class`
- for some cases I replaced `$object->className()` to `get_class($object)`
- You wrote to avoid new methods, but if we need to allow to handle a class name from child Active Records I decided to implement new method `humhub\components\ActiveRecord->class()` => `static::class` and for `ContentActiveRecord` it returns `static::getObjectModel()`.

**Comment by yurabakhtin** [comment]
@luke- If the solution is ok I can do the same updates for external modules.

**Comment by luke-** [comment]
@yurabakhtin Thanks for the PR. I don't like the approach to replace the deprecated `className()` method with a new `class()` method.

Wouldn't it be sufficient:

- Switch to `::class` or `get_class($obj)` instead of `className()`.
- Where it fits from the context, use `getObjectModel()` and solve the problem with polymorphic relations

@funkycram Would this solve this issue? 

Or did I missed something here?

**Comment by funkycram** [comment]
Yes. I would say: each time `getObjectModel()` is available, use it. And if not, use `::class` or `get_class($obj)`
Thanks @yurabakhtin for this work!

**Comment by yurabakhtin** [comment]
@luke- Ok, I have removed the `ActiveRecord->class()` in the commit https://github.com/humhub/humhub/pull/6185/commits/893b9db17bd19d969a4fec8ccf29b59d124ce37d, but I don't like current solution because there are many duplicates like this:

```php
$class = get_class($obj);
if ($obj instanceof ContentActiveRecord) {
    $class = $class::getObjectModel();
}
```

Why cannot we keep some new method in order to avoid such duplicates?
What if we will create a static helpter method in order to avoid such duplicates, for example, this method may be created for `humhub\components\ActiveRecord`:

```php
    public static function getObjectModel($object = null): string
    {
        if ($object === null || $object instanceof ContentActiveRecord) {
            return static::class;
        }

        return get_class($object);
    }
```

then we can remove the same named method from the `ContentActiveRecord` because it is currently:

```php
    public static function getObjectModel()
    {
        return static::class;
    }
```

so new method can be used by code `humhub\components\ActiveRecord::getObjectModel($obj)` instead of the duplicated code.

**Comment by luke-** [comment]
@yurabakhtin I would like to keep the model classes as lightweight as possible.

What do you think about adding the helper method here: 
`humhub\components\behaviors\PolymorphicRelation::getObjectModel()`

It's mainly used in the context of polymorphic relations anyway or?

**Comment by yurabakhtin** [comment]
@luke- Yes, I agree. Then the method will be like this:

```php
    public static function getObjectModel(yii\base\Model $object): string
    {
        return $object instanceof ContentActiveRecord
            ? $object::getObjectModel()
            : get_class($object);
    }
```

Can I implement this?

**Comment by luke-** [comment]
@yurabakhtin Yes please

**Comment by yurabakhtin** [comment]
@luke- Done in commit https://github.com/humhub/humhub/pull/6185/commits/1849477d92d1e13df201d841bb861fa47e073745.

**Comment by funkycram** [comment]
Thanks @yurabakhtin !

Just an idea to ignore if it makes no sens: as we are refactoring this on all Humhub, perhaps we could add the `ContentAddonActiveRecord::getObjectModel()` method

And then in `PolymorphicRelation::getObjectModel()` replace `return $object instanceof ContentActiveRecord` with `return $object instanceof ContentActiveRecord || $object instanceof ContentAddonActiveRecord`?

This way, `ContentAddonActiveRecord` would work the same way as `ContentActiveRecord`.

**Comment by yurabakhtin** [comment]
@luke- Do you agree to add new method `ContentAddonActiveRecord::getObjectModel()` and the related code?

**Comment by luke-** [comment]
@yurabakhtin Yes, please

**Comment by yurabakhtin** [comment]
@luke- @funkycram The `ContentAddonActiveRecord::getObjectModel()` has been done in the commit https://github.com/humhub/humhub/pull/6185/commits/e5918d6e05ddcabc1a86b5feaa829ec2a5a82665.

**Comment by luke-** [comment]
Thanks, will be merged in `v1.15`.

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/6358
Fixes get activities on content or content addon deletion when a different class name is defined in getObjectModel().

**Comment by luke-** [comment]
@funkycram I would now merge this PR #6185 here and then we could use the method? https://github.com/humhub/humhub/pull/6185/files#diff-63b6b65bbd93ed9d3bb6f24c5ede589d08cf030f8887b055599815653bb4697bR100 there as well?

**Comment by funkycram** [comment]
Thanks! Yes, I forgot we have this new method now.
PR updated with commit https://github.com/humhub/humhub/pull/6358/commits/d466741979ecbab4fcd6f88d86da75eb8aa9403b

**Comment by luke-** [comment]
@funkycram Thanks! I've merged it!
