### ISSUE TITLE
Users allowed to manage settings can access to module configurations

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6174]
### Is your feature request related to a problem? Please describe.

Currently (Humhub 1.13), if you want to change a setting in a module configuration page, you need to be allowed to manage modules.
Which means you are allowed to uninstall all modules and definitively delete all related data (e.g. all private messages of the mail module).

### Describe the solution you'd like

**A new permission** allowing some group members to access the module configuration pages.

### Describe alternatives you've considered

Allowing users to access the module configuration pages if they are allowed to **manage settings** (or manage modules).
This alternative is simple, but the users will then be allowed to access to system settings, such as email settings, etc.
But why not, this is reversible (not like module deactivation), and we could easily remove some setting pages with a custom module.

**Comment by funkycram** [comment]
@luke- now Humhub 1.15 has the (great!) new module administration, would you accept a PR for this idea?
If yes, on witch Humhub version?

**Comment by luke-** [comment]
@funkycram Do you mean to create a third permission "Manage Module Settings"?
![image](https://github.com/humhub/humhub/assets/4736168/7a46062a-717c-491d-b6cc-1b73bd928c33)

What would you think about:
- Manage Modules (install, deactivate, ..., configure modules)
- Manage Settings (general settings and module settings)

Not sure that we really need a third permission here.

**Comment by funkycram** [comment]
@luke- yes, that's a better idea.
So would you accept a PR where users "allowed to manage settings" are allowed to view:
- The Modules admin page (/admin/module/list) without the cog dropdown button list?
- The modules configuration pages?

E.g.:

![image](https://github.com/humhub/humhub/assets/23310825/6f1bd14b-0fdd-4c3e-8d05-d8a214206c1c)

![image](https://github.com/humhub/humhub/assets/23310825/635832cc-420f-4354-a9d3-4ee5893160f6)

Do you think that a user "allowed to manage modules" but not "allowed to manage settings" should be able to view the modules configuration page? I think that the answer is no.

If you agree, in this case, what do you think about replacing in https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/admin/components/Controller.php#L74:
`ManageModules::class` with `ManageSettings::class`?

I will check all controllers extending `humhub/modules/admin/components/Controller` and overwrite `getAccessRules()` if the permission is wrong with this new value (such as the `marketplace` module).

**Comment by luke-** [comment]
> @luke- yes, that's a better idea. So would you accept a PR where users "allowed to manage settings" are allowed to view:
> 
> * The Modules admin page (/admin/module/list) without the cog dropdown button list?
> * The modules configuration pages?

:+1: 

> Do you think that a user "allowed to manage modules" but not "allowed to manage settings" should be able to view the modules configuration page? I think that the answer is no.
> 
> If you agree, in this case, what do you think about replacing in https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/admin/components/Controller.php#L74: `ManageModules::class` with `ManageSettings::class`?

Ok for me. 


> I will check all controllers extending `humhub/modules/admin/components/Controller` and overwrite `getAccessRules()` if the permission is wrong with this new value (such as the `marketplace` module).

:+1:

**Comment by luke-** [comment]
@funkycram Thanks for the summary.

> > @luke- yes, that's a better idea. So would you accept a PR where users "allowed to manage settings" are allowed to view:
> > 
> > * The Modules admin page (/admin/module/list) without the cog dropdown button list?


> > * The modules configuration pages?
> 
> +1
> 
> > Do you think that a user "allowed to manage modules" but not "allowed to manage settings" should be able to view the modules configuration page? I think that the answer is no.
> > If you agree, in this case, what do you think about replacing in https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/admin/components/Controller.php#L74: `ManageModules::class` with `ManageSettings::class`?
> 
> Ok for me.
> 
> > I will check all controllers extending `humhub/modules/admin/components/Controller` and overwrite `getAccessRules()` if the permission is wrong with this new value (such as the `marketplace` module).
> 
> +1

**Comment by funkycram** [comment]
@luke- Done in PR https://github.com/humhub/humhub/pull/6449

If you accept it, I'll update the migration doc: https://docs.humhub.org/docs/develop/modules-migrate#version-115 

User allowed to manage modules but not settings:
![image](https://github.com/humhub/humhub/assets/23310825/9fd5449c-56d0-4f52-a715-d8eaf29cccd3)

User allowed to manage settings but not modules:
![image](https://github.com/humhub/humhub/assets/23310825/107507e0-6dc2-4e80-bd5f-9f2332ebe11d)

User allowed to manage both (as you can see I removed the "Configure" item in the menu as it was a duplicate of the button near by):
![image](https://github.com/humhub/humhub/assets/23310825/e0d1af82-cf30-448f-9396-78ff347b5e09)

**Comment by luke-** [comment]
@funkycram Ok thanks, looks good for me.

@Semir1212 Can you please take a look into the new warnings?

**Comment by funkycram** [comment]
I've informed about this the change in MIGRATE-DEV.md :
https://github.com/humhub/humhub/pull/6449/commits/97ec8c1cbb01b78d6333ad051e14917baae47856

But not on https://github.com/humhub/documentation/blob/master/docs/develop/modules-migrate.md#version-115 as if I understand well it will be done from the MIGRATE-DEV.md file once Humhub 1.15 is released.

**Comment by luke-** [comment]
> I've informed about this the change in MIGRATE-DEV.md : [97ec8c1](https://github.com/humhub/humhub/commit/97ec8c1cbb01b78d6333ad051e14917baae47856)
> 
> But not on https://github.com/humhub/documentation/blob/master/docs/develop/modules-migrate.md#version-115 as if I understand well it will be done from the MIGRATE-DEV.md file once Humhub 1.15 is released.

Yes, we'll switch to MIGRATE-DEV.md in future.

**Comment by Semir1212** [comment]
@luke- "You do not have the permission to manage modules. Please contact the administrator for further information."

**Comment by funkycram** [comment]
Thanks @Semir1212 !
@luke- Indeed, I've forgotten to update the permissions tests. Done in commit https://github.com/humhub/humhub/pull/6449/commits/398c3aca58e557c10b59d2b1e16211f9c34156a6
Now tests are OK.

**Comment by luke-** [comment]
@funkycram Thanks, I'll merge
