### ISSUE TITLE
Space Picker allows custom Input

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/humhub#6187]
### What steps will reproduce the problem?

No need to allow to add a custom space in the space pciker:

![space_selector](https://user-images.githubusercontent.com/6995524/226840203-8e4246b2-6c1c-4e28-bda9-45a3c772cd8e.png)

### What is the expected result?

It should be fixed as we did for User Picker here https://github.com/humhub/humhub/issues/5724

### What do you get instead?

see screenshot above.

### Additional info

Investigate all pickers extened from `humhub\modules\ui\form\widgets\BasePicker` and consider where this option should be enabled/disabled, probably by default it should be disabled if in most cases we don't need a custom value.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13

**Comment by yurabakhtin** [comment]
@luke- Could you please tell where to fix this issue, v1.13 or v1.14?

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6198.

> Investigate all pickers extened from `humhub\modules\ui\form\widgets\BasePicker` and consider where this option should be enabled/disabled, probably by default it should be disabled if in most cases we don't need a custom value.

I don't find other places where we should restrict a custom value in pickers.

**Comment by luke-** [comment]
@yurabakhtin I think this was introduced when we allowed searching by arbitrary values on the "People" page.  Or Space / User Tags maybe?

**Comment by yurabakhtin** [comment]
@luke- The enabling of custom inputs for all pickers was done here https://github.com/humhub/humhub/pull/5548/files#diff-55845c98784682c2415ffd1071e11c82a159791b010c9b6d206c871386278d58R374.

**Comment by luke-** [comment]
@yurabakhtin Ok thanks. So we close this with your merged PR right?

**Comment by yurabakhtin** [comment]
@luke- Yes, we can close this.
