### ISSUE TITLE
Timeout on php yii queue/run executed by command line

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6209]
### What steps will reproduce the problem?

I cannot reproduce. It's the first time it happens.
The error occurred on cron run.
Command executed: `php yii queue/run`

### What is the expected result?

No bug

### What do you get instead?

A timeout error.
As it was executed by command line, there should be no timeout.
But when analyzing the error log bellow it seems to be a timeout check in the code: `Symfony\Component\Process\Process->checkTimeout()`.

```
2023-03-28 17:38:02 [-][-][-][error][queue] Could not execute queued
job! Message: The process "'/usr/bin/php7.4'
'/var/www/humhub/protected/yii'
'queue/exec' '39646' '300' '1' '20305' '--color='" exceeded the
timeout of 300 seconds. Trace:#0
/var/www/humhub/protected/vendor/symfony/process/Process.php(430):
Symfony\Component\Process\Process->checkTimeout()
#1
/var/www/humhub/protected/vendor/symfony/process/Process.php(254):
Symfony\Component\Process\Process->wait()
#2
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(193):
Symfony\Component\Process\Process->run()
#3
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(126):
yii\queue\cli\Command->handleMessage()
#4 [internal function]:
yii\queue\cli\Command->yii\queue\cli\{closure}()
#5
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(144):
call_user_func()
#6
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(83):
yii\queue\cli\Queue->handleMessage()
#7 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}()
#8
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117):
call_user_func()
#9
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93):
yii\queue\cli\Queue->runWorker()
#10
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56):
yii\queue\db\Queue->run()
#11 [internal function]: yii\queue\db\Command->actionRun()
#12
/var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array()
#13
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178):
yii\base\InlineAction->runWithParams()
#14
/var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180):
yii\base\Controller->runAction()
#15
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552):
yii\console\Controller->runAction()
#16
/var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180):
yii\base\Module->runAction()
#17
/var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147):
yii\console\Application->runAction()
#18
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384):
yii\console\Application->handleRequest()
#19
/var/www/humhub/protected/yii(29):
yii\base\Application->run()
#20 {main}
in
/var/www/humhub/protected/humhub/modules/queue/Events.php:48
2023-03-28 17:33:01 [-][-][-][info][application] $_GET = []
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.1
| PHP version      | 7.4
| Operating system | Ubuntu 20.04

**Comment by luke-** [comment]
I think we have a default timeout here. Maybe we should increase it a bit and also make it configurable for larger installations. 

This should be documented here: https://community.humhub.com/s/installation-and-setup/wiki/Performance+and+scaling#queue-processing

**Comment by funkycram** [comment]
Thanks @gevorgmansuryan !

**Comment by funkycram** [comment]
@luke- I have a timeout on `PurgeDeletedContents` on an Humhub instance.

Shouldn't we use this new `LongRunningActiveJob` for more jobs such as:
- `PurgeDeletedContents`
- `DatabaseCleanup`
- `ModuleCleanupsJob`
- `SendBulkNotification`
- `AddUsersToSpaceJob`
- `ChangeContentVisibilityJob`
- `RemoveAllMembersFromSpaceJob`
- `DeleteUser`

**Comment by luke-** [comment]
@funkycram Yes, good point! Do you want to create a PR here? Otherwise I'll take care of it.

**Comment by funkycram** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6361

I've added the required `canRetry()` method for the `RetryableJobInterface` in the `LongRunningActiveJob` abstract class [here](https://github.com/humhub/humhub/pull/6361/files#diff-d0e57c8afe71af84d2a98a675f27f0ec11e01a51453f331283f3a6628d49ac76R24) and removed it in `RebuildIndex` and `SendMailSummary` as they extend `LongRunningActiveJob`.

**Comment by luke-** [comment]
@funkycram Thanks you!
