### ISSUE TITLE
How to change the background of the login page?

### ISSUE THREAD

**Issue by redforgeinnovatives** [humhub/humhub#622]
I need to change the background of the login page. It is an image in the JPEG format. I do not want to create a whole theme for it. Is there any way this task could be accomplished?

**Comment by gamebenchjake** [comment]
Copy the HumHub Theme, and then edit HumHub/css/theme.less :42 (body {}) to set your background. Recompile the .less file to .css afterwards

**Comment by redforgeinnovatives** [comment]
From where should I copy the Humhub theme? Actually, I tried changing the background in HumHub/css/theme.css. It changed the login page's background as well as that of the application. Can't I change only the background for the login page?

**Comment by WASasquatch** [comment]
The background of the login page is located in /protected/modules_core/user/views/auth/_layout.php

**Comment by lArcade** [comment]
Go to:  /protected/modules_core/user/views/auth/_layout.php

And now replace the code for this:


<div class="outside login-screen">
    <?php echo $content; ?>
    <div class="text text-center animated fadeIn">
        Powered by: <a href="http://www.humhub.org" target="_blank">HumHub</a>
    </div>
</div>

<style type="text/css">
    div {
        background-image: url(URL IMAGE) !important;
    }
</style>

**Comment by WASasquatch** [comment]
@lArcade it is not advised to edit the base templates as it will interfere and possibly cause updates to fail with HumHub. 

You are to make a new theme.

**Comment by nguyen-matthias** [comment]
Hello guys, how i can change the login background ? I use Humhub 1.0.0 Beta4. I've already google for this problem...
