### ISSUE TITLE
Attached files in private messages can be downloaded by public

### ISSUE THREAD

**Issue by DaKeks** [humhub/humhub#6226]
### Description
Attached files in private messages can be downloaded by public if URL (especially GUID) is known.

### What steps will reproduce the problem?
- Send a file via private message by using file upload in the chat window
- Copy URL of the file (right click -> copy link)
- Open new private tab in browser
- Open copied link
- File download will start

### What is the expected result?
- Access forbidden and sign in prompt is displayed

### What do you get instead?
- Access to file

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.2
| PHP version      | 8.1.17
| Operating system | Web Hosting @ netcup

**Comment by luke-** [comment]
Thanks for the report. It's related to the Mail module and there is an existing issue here: https://github.com/humhub/mail/issues/320
