### ISSUE TITLE
Administrators allowed to manage users cannot invite by email or by link if disabled in the settings

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6228]
### What steps will reproduce the problem?

Disable invitations:
![image](https://user-images.githubusercontent.com/23310825/231763558-5ecae1a3-389b-4d0c-ac7d-19c3ab07afdb.png)

As an admin allowed to manage users, invite new people:
![image](https://user-images.githubusercontent.com/23310825/231763925-65a9156b-f38c-453b-84ce-8635be77eda3.png)

#### Invite by email

![image](https://user-images.githubusercontent.com/23310825/231764200-b841d8c1-e3a1-4297-be53-5a95e9c88705.png)

#### Invite by link

![image](https://user-images.githubusercontent.com/23310825/231764646-3e3d54de-4653-47b9-a60e-46c362b9faa1.png)

#### Invite by email

The email is send.

#### Invite by link

The invite link works.

#### Invite by email

After sending the mail, we have:
![image](https://user-images.githubusercontent.com/23310825/231764353-223ce410-53be-4501-a453-4a00e0d66b56.png)

#### Invite by link

When opening the link:
![image](https://user-images.githubusercontent.com/23310825/231764797-22b33246-1c99-49a4-a68b-13faee66ca53.png)

This is of course because of the settings disabling invitations by email and link, but if the "Invite new people" is displayed, it should work for admins allowed to manage users.

### Additional info

Another option would be to not display the button "Invite new people" in the User Administration: `/admin/user/add`:
![image](https://user-images.githubusercontent.com/23310825/231767652-3e26ab26-ba9b-4db4-914f-8d3b74c34ea2.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13 and 1.14

**Comment by ArchBlood** [comment]
Personally if they're disabled I prefer the option of hiding the invite button till they're enabled.

**Comment by funkycram** [comment]
I think this make sense, yes. But in another hand, users allowed to manage users are also allowed to change this setting, so it could make send to allow them (and only them) to send invite even if disabled.

**Comment by luke-** [comment]
I would prefer if admins can always invite via email/link.

But at least we should hide the button as long as that doesn't work.

**Comment by willas00** [comment]
I still have this issue

You are not allowed to run this action.
{
    "url": "/user/invite",
    "status": 403,
    "response": {
        "error": true,
        "message": "Invite denied!"
    },
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"error\":true,\"message\":\"Invite denied!\"}",
        "responseJSON": {
            "error": true,
            "message": "Invite denied!"
        },
        "status": 403,
        "statusText": "error"
    },
    "dataType": "json",
    "error": true,
    "message": "Invite denied!",
    "errorThrown": "",
    "validationError": false
}

Version: 1.14.0

**Comment by funkycram** [comment]
@willas00 the fix will be available in Humhub 1.14.1 which is not yet released.

**Comment by joryanick** [comment]
Hello, my site previously had the issue in this thread. It was upgraded to 1.14.1 and it no longer shows the invite option to administrators. The two administration/user invite options have always been disabled. I tried turning the options on, testing the email invite feature (which works fine), and then turning the options off but no luck, the invite button does not show up for admins. Thank you for your hard work.

**Comment by funkycram** [comment]
Can you check you have:
![image](https://github.com/humhub/humhub/assets/23310825/4b9ec44f-bc9e-4a2a-9c2a-10b1ad1d3230)

For the group your admins are members of:
![image](https://github.com/humhub/humhub/assets/23310825/1ec3f602-d208-49f9-b630-b9ea3a68346e)

**Comment by joryanick** [comment]
Hi Marc, the settings are off, as only Administrators are allowed to send invites in this set up:


The administrative group settings:

**Comment by joryanick** [comment]
Hi Marc, the settings are off, as only Administrators are allowed to send invites in this HumHub installation:
![A02AB09D-6CC1-4949-B945-E8B46EDE45AE](https://github.com/humhub/humhub/assets/68076442/9c365541-683e-4b3f-a315-9a59b87c6578)

The administrative group settings:
![2DAD755D-0CB7-47AF-8EEC-B78E1EF6DE28](https://github.com/humhub/humhub/assets/68076442/20dd984e-edd5-46d7-8ddb-94fa8f03770c)
![0EF22F6D-3828-40F1-8715-B3D8271B9557](https://github.com/humhub/humhub/assets/68076442/272a8f2b-2498-443f-bb52-881e8a3ba498)

**Comment by funkycram** [comment]
> I would prefer if admins can always invite via email/link.

@luke- : @joryanick is right, if "[...] can invite external users by email" and "[...] by link" are disabled, admins cannot invite by email/link (tested on develop branch)

**Comment by joryanick** [comment]
Confirming this issue is also present in 1.14.2 on the same install.

**Comment by WizWareTech** [comment]
If admins can turn on the option to send an invite by email, then they should be able to see the invite by email button without having to turn on the option first.

This is what we need (and how it used to work before this was changed:

1. ONLY admins are able to invite user to humhub by email link
2. Space admins still be able to invite users that already exist on the system, but NOT invite by external email.

What settings do we set to allow the above two requirements? At the very least, can we have a configuration setting to always show invite button for administrators?

**Comment by WizWareTech** [comment]
I think this issue could be resolved easily by moving these two options
![image](https://github.com/humhub/humhub/assets/13114/2cb43eca-f89a-4f37-9335-ee4c0d82476c)
to individual group permissions, so administrators could control which user groups are allowed to send invites by email, rather than it being a global option for all users that happen to be able to manage users. The problem is that I want site administrators to be able to send email invite, but NOT space administrators or standard users.

**Comment by hochleitner** [comment]
Sorry to add something to this already closed issue, but is this really closed/completed? I'm on HumHub 1.15.3, and I still can't invite people as an administrator when the option (Members can invite external users by email) is disabled.
When it's enabled and I go to Administatration -> Users -> Overview -> Add new User then I see the "Invite new Users" Button.
When it's disabled, the button is not there, and I have to turn the feature on. That doesn't seem right.

**Comment by ArchBlood** [comment]
> Sorry to add something to this already closed issue, but is this really closed/completed? I'm on HumHub 1.15.3, and I still can't invite people as an administrator when the option (Members can invite external users by email) is disabled. When it's enabled and I go to Administatration -> Users -> Overview -> Add new User then I see the "Invite new Users" Button. When it's disabled, the button is not there, and I have to turn the feature on. That doesn't seem right.

I've tested this against the master branch and can confirm this to be true, but I haven't tested for the develop branch.

**Comment by luke-** [comment]
Can you please create a new issue for this. with steps to reproduce

**Comment by hochleitner** [comment]
> Can you please create a new issue for this. with steps to reproduce

Thanks, I've opened up https://github.com/humhub/humhub/issues/6893.
