### ISSUE TITLE
read-only doc tag for writable property `\BaseApplication::$controller`

### ISSUE THREAD

**Issue by martin-rueegg** [humhub/humhub#6230]
The `\BaseApplication::$controller` is marked read-only ...

https://github.com/humhub/humhub/blob/b0d4b50c913a05abcbd2de754b7a264204cf576f/protected/humhub/Yii.php#L21

... while the overriden property `\yii\base\Application::$controller` is actually writable:

https://github.com/yiisoft/yii2/blob/1a07bb14d929b206fb8e22df32021f68a1eb4b7d/framework/base/Application.php#L118

Is there a reason for this?

Of course, one usually would not mess with that property. PhpStorm marks code which is writing to that property [as an error](https://youtrack.jetbrains.com/issue/WI-72275/Possibility-to-disable-read-only-inspection-for-writable-class-property-solely-marked-with-read-only). Since that cannot be disabled, it's a bit annoying.

**Comment by luke-** [comment]
@martin-rueegg I don't think there is any reason for this. Looks more like a bug.

**Comment by martin-rueegg** [comment]
The same issue might apply to `\humhub\modules\space\controllers\SpaceController::$contentContainer`:

https://github.com/humhub/humhub/blob/b0d4b50c913a05abcbd2de754b7a264204cf576f/protected/humhub/modules/space/controllers/SpaceController.php#L30

vs

https://github.com/humhub/humhub/blob/b0d4b50c913a05abcbd2de754b7a264204cf576f/protected/humhub/modules/content/components/ContentContainerController.php#L54

**Comment by luke-** [comment]
Yes, on "real" properties there should never be a `-read`.

**Comment by martin-rueegg** [comment]
Fixed in #6375
