### ISSUE TITLE
Logging: Show log entries from migrations with category `migration`

### ISSUE THREAD

**Issue by martin-rueegg** [humhub/humhub#6236]
Currently, all log entries are shown as 'application' (unless issued by Yii-internal code).

It would be great to introduce at least a "migration" category.

Happy to create a PR for this, if appreciated.

**Comment by luke-** [comment]
@martin-rueegg  Yes, would be cool to have a single category for Migrations.

**Comment by martin-rueegg** [comment]
> @martin-rueegg Yes, would be cool to have a single category for Migrations.

See  #6238
