### ISSUE TITLE
Submit button hidden when editing a comment having a long "code" line

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6242]
### What steps will reproduce the problem?

Go to this comment: https://community.humhub.com/comment/perma?id=44781
Edit it.

### What is the expected result?

You can save the modifications

### What do you get instead?

![image](https://user-images.githubusercontent.com/23310825/232746941-942250b5-6b45-4101-a0fa-6c07ec8fb1f6.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | Community platform

**Comment by luke-** [comment]
@funkycram Thanks for the report. As workaround you can use STRG+S to save.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/issues/6242:

![scroll_long_code](https://user-images.githubusercontent.com/6995524/235216035-b81346e7-4708-4999-bb5e-c366bda89362.png)
