### ISSUE TITLE
Registration failed

### ISSUE THREAD

**Issue by lArcade** [humhub/humhub#626]
Hi, I have a problem
When I want to register I do not get the email. 

What can I do? 

-------------------------------------------------------------------- 
Hola, tengo un problema. 
Cuando quiero registrarme en mi sitio no me llega el email e igual pasa con el demo que cree. 
Que puedo hacer?

**Comment by gamebenchjake** [comment]
https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/installation.md

See the Email Configuration settings

**Comment by programguy** [comment]
Hey I'm having this problem too. It only sends the email sometimes. I am using SMTP. I haven't had time to trace down the problem, so that's all I have at the moment.

**Comment by WASasquatch** [comment]
Have you checked your spam inboxes? Sending from your localhost, or a subdomain will usually be flagged as spam.

**Comment by programguy** [comment]
@WASasquatch I am using free hosting from x10hosting.com. My email address is news@mysubdomain.x10host.com. Personally, I can't duplicate the problem with receiving the email. I have gotten it on Gmail and Yahoo. I have other people trying to sign up for my site, and it only works for some of them. I had one of them check spam, but that's all I really know.

**Comment by WASasquatch** [comment]
All emails sent from my system are sent to spam box because they are lacking proper TLD credentials. I'm not sure how they got by your spam protection. But I'd note on the registration page to check your spam inbox. If you are also using their free SMPT, it's highly probable it is overloaded.

**Comment by programguy** [comment]
There was a spot for me to set an SPF record. I don't know if it is helping, but I think it is. You're probably right that it is overloaded. I've noticed that I haven't gotten some other emails I was supposed to get.

**Comment by lArcade** [comment]
I tried everything but nothing works.
I configured the server settings but... not working

---------------------------------------------

Lo intenté todo pero sigue sin funcionar.
Probé el SMPT pero no sirvió para nada no me llega ni a gmail ni outlook

**Comment by WASasquatch** [comment]
What are you using for a SMPT server then? You need something. Gmail is free. You just need to allow unsecure apps to use the gmail account or HumHub will be blocked.

**Comment by lArcade** [comment]
I do not know what happened.
Suddenly I receive emails.
It solved only  xD
------------------------------------

Bueno no se lo que pasó ya que me acaban de llegar los emails de registro de hace tiempo y ahora llegan rápidos.
Se solucionó solo xD

**Comment by FirePhenix** [comment]
Hi, i have this problem also . i set gmail stmp server on the backend . but it's always have error like this :

Connection could not be established with host smtp.gmail.com [Connection timed out #110] 

please help me ,thanks .
