### ISSUE TITLE
BaseSettingsManager::deleteAll() does use prefix as wildcard

### ISSUE THREAD

**Issue by martin-rueegg** [humhub/humhub#6266]
The comment to the function reads: 

``` php
/**
 * @param string|null $prefix if set only delete settings with given name prefix (e.g. theme.)
 **/
```

As such, the parameter $prefix is understood to be a prefix only. One would expect an SQL along the lines 
``` SQL
WHERE name LIKE 'prefix%'
```
(or given the dot mentioned in the comment, even `'prefix.%`). However, the code does not use it as a prefix:

https://github.com/humhub/humhub/blob/43e866772ca200d904e6c5afd7ff40cf777959a9/protected/humhub/libs/BaseSettingsManager.php#L251

The 3rd parameter to the like condition is missing, and not `%` manually added! Hence the SQL created will be 
``` SQL
WHERE name LIKE '%prefix%
```

The docs [read](https://www.yiiframework.com/doc/api/2.0/yii-db-queryinterface#where()-detail):

>    **like:** operand 1 should be a column or DB expression, and operand 2 be a string or an array representing the values that the column or DB expression should be like. For example, ['like', 'name', 'tester'] will generate name LIKE '%tester%'. (...)
>  **Sometimes, you may want to add the percentage characters to the matching value by yourself, you may supply a third operand false to do so. For example, ['like', 'name', '%tester', false] will generate name LIKE '%tester'.**

How shall we deal with this discrepancy?

1. Change the comment and the name of the parameter to reflect the actual behavior
2. Change the behavior to reflect the description in the comment, but potetially break someone's code who relied on this bug
3. Create an option to provide your own `%`, in which case the value is used as-is, otherwise make it `prefix%`

(It showed up while creating tests for #6190)

**Comment by martin-rueegg** [comment]
@luke-

**Comment by luke-** [comment]
@martin-rueegg I would prefer option 2.)  I would check if there are modules that use the wrong behavior.

What do you think?

**Comment by martin-rueegg** [comment]
@luke-, I like the idea that I could delete all with a certain suffix. This would be option 3, with an argument like `$prefix = "%_temp` without to have to create another function.

It is comatible with option 2 and easy to imlement:

```php

if (false === stros("%", $prefix)) {
  $prefix .= "%";
}
```

The only issue that comes up is that in either case it would not be possible to match the `%` itself. I'm not sure if there is an SQL -standard for escaping the `%` in the LIKE clause. Would have to check. Otherwise we would have to make sure we ignore quoted `%` ...

The other question is, if you want to add the `.` (dot) by default as well, so that the `$prefix` would only match if there is a dot following. E.g.: `$prefix = 'test'` would match `test.a` and `test.b`, but not `test` or `testing`. Or do we leave that up to the user to add the dot (it could always be circumvented by using `$prefix = "test%"` if we opt for option 3.

**Comment by luke-** [comment]
@martin-rueegg Ok sounds good to me. Let's implement it as you suggested:

- If no `%` present in the argument, change to `arg%`
- If argument contains at least `%` pass it 1:1 to the like condition. (No special handling for `%`)
- The `dot` must be included in the argument, there is no special handling

Did I miss something or misunderstand?  

I think the method is almost never actively used by a module. So a Migration Guide note should be suffient.

**Comment by martin-rueegg** [comment]
> @martin-rueegg Ok sounds good to me. Let's implement it as you suggested:
> 
>     * If no `%` present in the argument, change to `arg%`
>     * If argument contains at least `%` pass it 1:1 to the like condition. (No special handling for `%`)
>     * The `dot` must be included in the argument, there is no special handling

Awesome.

> Did I miss something or misunderstand?

Nope.

> I think the method is almost never actively used by a module. So a Migration Guide note should be suffient.

Talking about the migration guide. I was wondering, we should have a document like `CHANGELOG-DEV.md` (e.g. `MIGRATE-DEV.md`) to be able to add these changes. And then they can be published from there?

**Comment by luke-** [comment]
> > I think the method is almost never actively used by a module. So a Migration Guide note should be suffient.
> 
> Talking about the migration guide. I was wondering, we should have a document like `CHANGELOG-DEV.md` (e.g. `MIGRATE-DEV.md`) to be able to add these changes. And then they can be published from there?

I like the idea. So instead of adding it directly to https://docs.humhub.org/docs/develop/modules-migrate , lets collect them in `MIGRATE-DEV.md`. This way we can combine the documentation with the related PRs.
