### ISSUE TITLE
Editable Mention Text

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#627]
Currently, you cannot delete even the backspace after a mention text without it breaking. Is there a way to better implementation this so it is not only editable (delete last name and only mention through first name), but the ability to trail it with a comma, or period for proper grammar. 

I haven't tracked down the mention files to really look at the code, so if anyone knows their locations already point them out and I can take a look.

**Comment by luke-** [comment]
Code should be here: https://github.com/humhub/humhub/blob/master/protected/widgets/views/heditor.php

Can you please provide steps to reproduce the problem?

**Comment by WASasquatch** [comment]
If you mention anyone, and add a comma for propper grammer, the mentioned person will come through as "@THE_GUID_HERE" instead, and will not work. If you delete any text from the mention name (for example to mention only their first name) the same thing happens. 

I'll take a look at the code when I get my dedicated server up. My Localhost has died on both computers and not sure if I'm being targeted by HumHub members that have my IP/Domain.
