### ISSUE TITLE
Search UserWall & Wall Widget Refactoring

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#6284]
### Is your feature request related to a problem? Please describe.
Currently you're not able to extend `humhub\modules\user\widgets\UserWall` or `humhub\modules\space\widgets\Wall` with `EVENT_CREATE` because both are extending `\yii\base\Widget` instead of `humhub\components\Widget` which is required currently in one of our current issues (https://github.com/GreenMeteor/verified/issues/22#issuecomment-1531804576).

### Describe the solution you'd like
We'd like to change the extended class in both `UserWall` & `Wall` so that we can implement a `EVENT_CREATE` to show the verified icon for Users and Spaces.

### Describe alternatives you've considered
No other possible alternatives are currently possible without theme view overwrite method.

**Comment by luke-** [comment]
Yes, feel free to create a PR that these Widgets extends from `humhub\components\Widget`

**Comment by ArchBlood** [comment]
> Yes, feel free to create a PR that these Widgets extends from `humhub\components\Widget`
> 

Would you rather it be under the develop branch?

**Comment by luke-** [comment]
develop please
