### ISSUE TITLE
Websocket for notifications

### ISSUE THREAD

**Issue by gamebenchjake** [humhub/humhub#629]
Should look at integrating Yii-Nfy extension for live notifications of messages/alerts

**Comment by WASasquatch** [comment]
Yii-Nfy uses AJAX pulls just like current implementation. Intervals is all that would need to be changed to make it more "live"

**Comment by luke-** [comment]
We plan to enhance / rewrite the notification system in future.

Maybe there will be an additional node js websocket service in future for (chat, push notifications)

**Comment by CKGrafico** [comment]
@luke This present is the future :) when push notifications? our users don't like to receive emails to know what's happening
