### ISSUE TITLE
Deleted content not purged on cron daily?

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6293]
### What steps will reproduce the problem?

Create a content (tested with a wiki page).
Delete it.
In the `content` table, the state becomes `100` which is the `Content::STATE_DELETED` status.
Run daily cron: `php yii cron/daily` and queue: `php yii queue/run`

### What is the expected result?

The content is removed from the database

### What do you get instead?

The content is still present.

### Additional info

Shouldn't `$content->delete();` be replaced with `$content->hardDelete();` here?
https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/jobs/PurgeDeletedContents.php#L23

@luke- If yes, I can send a PR on master if you want.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.0

**Comment by funkycram** [comment]
I think if this bug really exists, it would be nice if the fix was part of the upcoming Humhub 1.14.1 release. Thanks!

**Comment by yurabakhtin** [comment]
@funkycram @luke- Fixed in PR https://github.com/humhub/humhub/pull/6308.

**Comment by funkycram** [comment]
Thanks @yurabakhtin !
