### ISSUE TITLE
Add the possibility to display if users are online

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6295]
### Is your feature request related to a problem? Please describe.

See discussion here: https://github.com/humhub/mail/issues/325

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/23310825/236410138-975af721-f26d-4942-bf3c-0d8683459c9a.png)

**Comment by funkycram** [comment]
@luke- Commit https://github.com/humhub/humhub/commit/bae5b214cc7bb8f3d28fb008d853a3102fdd2c34

I need one more think to make the PR:

To update online status, the code(1) added to the `PollController` works well, but when browsing the platform for the first time, we need to wait for 20 seconds to the controller to be triggered.
I would like to update status also on first load or full refresh, somewhere like the controller that displays the `main` view.

Have you got an idea where I could add the code(1) to update the user status on full page load?
Thanks!

(1):
```php
(new IsOnlineService(Yii::$app->user->id))->updateStatus();
```

**Comment by luke-** [comment]
@funkycram Maybe here in the `else` condition: https://github.com/humhub/humhub/blob/master/protected/humhub/components/Controller.php#L223

We should also add a comment, that it's only intended for full page loads.

**Comment by funkycram** [comment]
Thanks!
Would you like to show the online status on the People directory?
![image](https://user-images.githubusercontent.com/23310825/236610092-dc46cc63-e847-4e54-b4a3-3625d06a9f0b.png)

**Comment by luke-** [comment]
Yes, would be great.
But we need to find a possibility to disable this feature globally. And ideally per user level.

**Comment by funkycram** [comment]
I can add this:
![image](https://user-images.githubusercontent.com/23310825/236610966-26a51b0f-a075-42bf-ae28-51183d772cac.png)
![image](https://user-images.githubusercontent.com/23310825/236611032-b900fcb8-b41f-4dab-896f-1769d199345c.png)

But if you need auto testing, I might be short in time.

**Comment by luke-** [comment]
@Semir1212 Can you please take a look here for the wording. I wouldn't use the term "Profile Image" because we could probably use this in other situations later. e.g. to also disable "User A is typing..." hints.

@funkycram Ok,  we can contribute tests. It would be good if most of the logic is implemented in the service class. Thanks!

**Comment by funkycram** [comment]
Thanks for your testing contribution!
PR https://github.com/humhub/humhub/pull/6297
I've added some reviews.

**Comment by Semir1212** [comment]
@funkycram @luke- Shouldn't the online status be displayed by default? So that the option would be "Hide online status".

**Comment by funkycram** [comment]
@Semir1212 This is also my question in one of the pending reviews: https://github.com/humhub/humhub/pull/6297
But I haven't though about the idea to change it to  "Hide online status". I'll add this idea in the review. Thanks!

**Comment by Semir1212** [comment]
@funkycram @luke- Depending on which way we go I would suggest the following: 

- Show online status of users // Show my online status
- Hide online status of users // Hide my online status

**Comment by funkycram** [comment]
Thanks @Semir1212 .
@luke- I think Semir suggestion to show online status by default is better.
If you agree, I'll change the code for:
Hide online status of users // Hide my online status

**Comment by luke-** [comment]
@funkycram Yes, good point!

**Comment by funkycram** [comment]
Done and added to PR.

What do you think about these screenshots?
![image](https://github.com/humhub/humhub/assets/23310825/eff0d0ca-4373-438e-89e4-9662dee1598f)
![image](https://github.com/humhub/humhub/assets/23310825/d7d034b9-054c-40f7-9660-a9a8e95fea08)

**Comment by Eladnarlea** [comment]
there are two things that have come to my attention: 

1. please move the `online indicator circle` more into the picture frame. 
 e.g:
![Screenshot 2023-05-10 at 4 15 25 PM](https://github.com/humhub/humhub/assets/105652258/dc306f8c-ef23-4a56-ace3-bfcb589411c6)

2. please make the stroke a bit thicker. at least the same thickness as the profile picture's stroke itself. Also in this example the dot could be a bit bigger. 
![Screenshot 2023-05-10 at 4 20 05 PM](https://github.com/humhub/humhub/assets/105652258/5eeb5acc-1f0e-47f9-9cb2-9c58b3109256)

**Comment by funkycram** [comment]
@Eladnarlea thanks for your advise.

@luke- done on commit https://github.com/humhub/humhub/commit/638283322a5b80a5964a9f137d2c1c16e66337c2

Screenshot with this new commit:
![image](https://github.com/humhub/humhub/assets/23310825/e5d1d4f3-f192-4feb-b63c-7f5d754bb79e)

**Comment by luke-** [comment]
@funkycram Thanks, is this ready to merge or is something still open? From my side everything looks good.

**Comment by luke-** [comment]
@funkycram Ok, thanks. `media.less` is ok for now. Maybe we will create a new `user.less` in the future.
I will merge it then and we can test it on develop.
@Eladnarlea  is now on vacation for a few weeks and will surely take a closer look afterwards. :-)

Thanks for this great contribution!
