### ISSUE TITLE
New User Password is not working

### ISSUE THREAD

**Issue by TheFox** [humhub/humhub#6300]
### What steps will reproduce the problem?

When I want to create a new Passwort for a new User using protected/humhub/modules/user/models/Password.php I am getting an error.

```php
$userPasswordModel = new Password();
$userPasswordModel->scenario = 'registration';
$userPasswordModel->mustChangePassword = false;
$userPasswordModel->setPassword($data['password']);
$userPasswordModel->user_id = $userModel->id;
$userPasswordModel->save();
```

### What is the expected result?

Create a new User and create a Password for that user.

### What do you get instead?

Error in Password.php in Line 190:

```php
$this->user->auth_key = Yii::$app->security->generateRandomString(32);
```

Error:
```
Indirect modification of overloaded property humhub\modules\user\models\Password::$user has no effect
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14
| PHP version      |  8.1
| Operating system | Debian 11

**Comment by gevorgmansuryan** [comment]
it should be:

$userPasswordModel = new Password();
$userPasswordModel->scenario = 'registration';
$userPasswordModel->mustChangePassword = false;
**$userPasswordModel->user_id = $userModel->id;
$userPasswordModel->setPassword($data['password']);**
$userPasswordModel->save();

user_id should be set before calling setPassword

**Comment by luke-** [comment]
@gevorgmansuryan To avoid such problems, we could perhaps adjust the "setPassword" so that if no `User` is set yet, the `auth_key` is not reset either.  Could you please prepare a `develop` PR for this?
