### ISSUE TITLE
Wording when creating draft

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#6304]
![image](https://user-images.githubusercontent.com/38326726/236846157-f01aa683-6990-4816-93ba-16d69e3fdf6e.png)

When creating a post as draft the button should change to something like "Save as draft".

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6318:

![draft](https://github.com/humhub/humhub/assets/6995524/6a69bbaa-f2e5-4aa8-8806-7ae252647f4a)
![scheduled](https://github.com/humhub/humhub/assets/6995524/ea2f99f3-0bb3-461a-97e9-babb120b6842)

**Comment by Semir1212** [comment]
@yurabakhtin 

Button: Save scheduled post 
Label: Scheduled for..

**Comment by yurabakhtin** [comment]
@luke- 

> Button: Save scheduled post

Should I find a solution to get the "post" from `ContentActiveRecord->getContentName()`? Because e.g. Poll record has a value `Poll` there.
