### ISSUE TITLE
Gmail Users (Alias Email Address) cannot be added to HumHub

### ISSUE THREAD

**Issue by TheFox** [humhub/humhub#6305]
It's not possible to add a user with "username" using a Gmail Alias Email address. For example, I have an email address example@gmail.com and an alias for example+alias@gmail.com. I cannot use example+alias@gmail.com as an username when I want to create a new user. I guess this is because `+` is invalid in the username field, right?

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14
| PHP version      | 8.1
| Operating system | Debian 11

**Comment by ArchBlood** [comment]
I believe that if the username uses the first and last name fields then a `+` is used, that's probably the issue.

**Comment by luke-** [comment]
You can specify allowed username characters here: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/Module.php#L78

**Comment by TheFox** [comment]
@luke- But that will be overwritten when upgrading to a newer HumHub version, right?

**Comment by luke-** [comment]
You can overwrite this using the configuration: https://docs.humhub.org/docs/admin/advanced-configuration#module-configurations

**Comment by TheFox** [comment]
Ok, I see. Thank you. No further questions.
