### ISSUE TITLE
Multipart e-mail messages: text/plain & text/html

### ISSUE THREAD

**Issue by dakur** [humhub/humhub#631]
Hi, some users of our HumHub installation are having problem with viewing messages from HumHub, because their webmail does not really support HTML messages, which HumHub is sending.
I've heard about multipart content-type, which allows to have text/html part as well as text/plain in the message. I did not find any information about this in HumHub, so would it be possible to add it there?

**Comment by dakur** [comment]
@luke- I think solution of this should be priority, because users using mobile mailclients not parsing HTML or older webmails receive non-sense e-mails, which they can't understand - something like "name of the site, name of the site, click here". - but it's as plain text as I wrote it here.
Unfortunatelly, I don't have enough understooding of OOP/MVC programming to do it.

**Comment by WASasquatch** [comment]
Definitely a bug. HTML is NOT a standard mail format. It's substandard.

**Comment by luke-** [comment]
Can you give some examples which webmail/mobile clients are affected to this problem?

**Comment by WASasquatch** [comment]
Many cpanel/whm configured email where the employer/host has specifically
disabled HTML, and other work email accounts and software (to ensure work
environments are not compromised via a neglectful employee)

It should inherently be a option, to send in plain text or HTML. In the
event of plain text id avoid a daily summary for viewing purposes

http://www.georgedillon.com/web/html_email_is_evil.shtml

**Comment by dakur** [comment]
Another example: one faculty on our university uses SquirrelMail as a webmail and people there have this problem when receiving updates from HumHub.
Plus - I've almost forgotten - the described problem is not just about notifications, but also with the activation link e-mail after registering - people do not see activation link there.

**Comment by dakur** [comment]
Is this going to move soon, please? It should not be that difficult for those who understand the framework, and it's quite fundamental...

**Comment by dakur** [comment]
Guys, what about this? :-\

**Comment by luke-** [comment]
@dakur Thanks!
https://github.com/humhub/humhub/commit/533c629ed9bdd8dd76c200a2076230d685a1c93b

**Comment by dakur** [comment]
@luke- : It is needed to merge also changes in mail module: https://github.com/humhub/humhub-modules-mail/pull/77
