### ISSUE TITLE
Modules administration - Refresh the page after adding a licence key

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6334]
### What steps will reproduce the problem?

1. Add a licence key:
![image](https://github.com/humhub/humhub/assets/23310825/f85afa62-0a0f-474a-ac0d-8e6245a73bef)

2. Close the modal box

### What is the expected result?

The "Install" button:
![image](https://github.com/humhub/humhub/assets/23310825/e1f3a434-9c20-49c7-b8e6-7f5db5d398b3)

### What do you get instead?

Still the "Buy" button:
![image](https://github.com/humhub/humhub/assets/23310825/9a3f3864-7c98-4bfd-8b43-3413b9bd7e73)

### Additional info

Alternatively, after adding the licence, the module could install automatically. But the page still needs to refresh after closing the modal box.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.1

**Comment by luke-** [comment]
@yurabakhtin Maybe we can improve this in combination with the module admin enh.

**Comment by yurabakhtin** [comment]
@luke- Ok, it seems you tell about the task "Marketplace / Modules Redesign", I will do this there.

**Comment by yurabakhtin** [comment]
@luke- Done in commit https://github.com/humhub/humhub/pull/6348/commits/e28f89975dffdf23aad3824f233c85c540be658d:

![add_licence_key](https://github.com/humhub/humhub/assets/6995524/7f27c306-d460-4466-8751-c6cb17a1bdef)

**Comment by funkycram** [comment]
Great! Thanks @yurabakhtin
