### ISSUE TITLE
Pending approvals: possibility to send a message

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6335]
### Is your feature request related to a problem? Please describe.

When a new user creates an account and an admin must approve or refuse it, sometimes the admin needs to ask him complementary information.

### Describe the solution you'd like

Add the possibility to send him a message:

![image](https://github.com/humhub/humhub/assets/23310825/2d0f84f3-49ac-4945-81eb-efc01850240c)

And in `/admin/authentication` add a rich text field to have a message model (similar to the approval and refuse message template).

### Describe alternatives you've considered

Instead of adding a 4th button, replace with a drop down list.

**Comment by luke-** [comment]
Wouldn't it be sufficient if the admin clicks on the email address?

**Comment by ArchBlood** [comment]
> Wouldn't it be sufficient if the admin clicks on the email address?

I'm not sure about this, as an admin wouldn't know that this action would be possible without prior knowledge of HumHub, maybe if a `tooltip` were also implemented suggesting that the action is available then this would be possible. :thinking:

**Comment by luke-** [comment]
Hmm, the "Send message" feature would have the same problems as an e-mail:

- Other admins can't see that a message has been sent
- The reply to the message would be sent by email anyway

**Comment by funkycram** [comment]
The advantage of this idea is to have a ready-made email template to ask them for additional information.

It also allows you to use the system email rather than a personal email. But of curse, yes, you need to receive replied emails. This is a limitation, but can work.

We could imagine, in the future, saving the information that an email has been sent in order to show it next to the button (label or other), which would be practical if we manage a lot of registrations or if there are several admins.

But I agree this feature idea is not perfect, so if you think it adds more complexity than advantages, lets forget it!

**Comment by luke-** [comment]
@funkycram Hmm, I'm really unsure about it. 

What happens after, when the Admin have sent a message to the user? The user himself has no possibility to update his registration details.

**Comment by funkycram** [comment]
The idea is that the user will answer the questions by replying to the email.
The admin should receive the reply email (but on some mail configuration he might not receive it...).
If he's satisfied by his answer, he approves the account. If not, he declines it.
But I admin it's not a perfect solution, so let's forget it if it's not a good idea.

**Comment by luke-** [comment]
@funkycram Ok I got it. This feature should be small from the code base, so if you like, feel free to create a PR for it. Thanks :-)

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/6365

![image](https://github.com/humhub/humhub/assets/23310825/ff0647ab-be56-4d24-9c6a-c1ccfd35fe5e)

![image](https://github.com/humhub/humhub/assets/23310825/63798486-c6b2-4710-adad-eabd1427f18b)

![image](https://github.com/humhub/humhub/assets/23310825/9299ca28-ce10-4771-ad71-b9e930f776ef)

**Comment by ArchBlood** [comment]
> @luke- #6365
> 
> ![image](https://user-images.githubusercontent.com/23310825/242227580-ff0647ab-be56-4d24-9c6a-c1ccfd35fe5e.png)
> 
> ![image](https://user-images.githubusercontent.com/23310825/242227752-63798486-c6b2-4710-adad-eabd1427f18b.png)
> 
> ![image](https://user-images.githubusercontent.com/23310825/242228863-9299ca28-ce10-4771-ad71-b9e930f776ef.png)
> 
> ![image](https://user-images.githubusercontent.com/23310825/242240423-27a7cd57-fbce-43f3-aae1-b954853474a0.png)

Could you provide a mobile view of the buttons with the default theme?

**Comment by funkycram** [comment]
@ArchBlood I only added a button, so the view is the same as before on mobile. It mainly depends on the number of profile fields you add to the table.
Example with 500px width (under the result is bad):
![image](https://github.com/humhub/humhub/assets/23310825/8cca0ec4-81e2-459b-b25c-502e1c643c87)

**Comment by funkycram** [comment]
@luke- 4 tests fails.
- `ApproveUserFormTest.php:testSendMessageIsSentInUserLanguage` ([here](https://github.com/humhub/humhub/actions/runs/5131892043/jobs/9232510911#step:18:1440)): we first need german translation for it to work
- The 3 others: I don't understand why they don't work. I've created them on the same model as the approve and decline ones. Perhaps we don't need so many tests only for sending an email?

**Comment by luke-** [comment]
@funkycram Thanks for the PR.

@yurabakhtin Can you maybe help?

**Comment by yurabakhtin** [comment]
> Can you maybe help?

I think the error is here https://github.com/humhub/humhub/pull/6365#pullrequestreview-1453447382

**Comment by luke-** [comment]
@funkycram Thank you for your patience.

**Comment by marc-farre** [comment]
@luke- would you accept an additional commit to https://github.com/humhub/humhub/pull/6365 allowing to send a bulk message to several pending approval users at the same time, adding a button at the bottom, before "Approval all selected"?

![image](https://github.com/humhub/humhub/assets/23310825/671d3e7d-6705-4e70-9cb5-7c7cf8655fca)

Thanks!

**Comment by luke-** [comment]
@marc-farre Yes! :-)

**Comment by marc-farre** [comment]
@luke- Done in commit https://github.com/humhub/humhub/pull/6365/commits/6d998f111c9b8cf46afb42f565cba9eca28dffa7
