### ISSUE TITLE
Accessibility issue

### ISSUE THREAD

**Issue by ASponch** [humhub/humhub#6339]
Dear Humhub community,

First, scuse me for my poor english. ;)

I got a speak with a blindness user. This one explain to me that the platform was unusable for him.

The first point is that the post button in response of a comment isn't accessible. I am searching to reproduce but I don't see where is the trouble. Anyway, I think he is right.
The second point, most interresting thinks is that the headings don't respect the hierarchy. On a post, the Title is right H1 but h2 and h3 was lost in profit of h4 that is referring to update on the post (maybe).

Also, an "hidden gallery" isn't visible to valid user but is screen readable for screen reader (on certain post). It's an information that is inusefull blindness user.

I hope this message will help according to the A.D.A. (Americans with Disabilities Act) and I remain at your disposal.

best regards,
Asponch

**Comment by ASponch** [comment]
Also, on the welcome space, when using the "Web developper toolbar" browser plugin to see the document outline ("information" panel). It is not possible to see the whole page (due to the page load ; I don't thik that this is a problem but this is an open question) :)

Have a nice day,
ASponch

**Comment by luke-** [comment]
Thank you for your feedback.

We are continuously improving the software in terms of accessibility.

Topics such as the comment section and the hidden gallery are currently on our schedule.

If there are specific issues, please create a separate issue for each misbehavior.

Thank you!
