### ISSUE TITLE
Modules HumHub

### ISSUE THREAD

**Issue by suustenvoorde** [humhub/humhub#634]
Hi people,

I have just downloaded Humhub, it's really cool! I just got one problem.. 
When I open the modules, I see this error:
"Could not fetch module list online! (Error in cURL request: Could not resolve host: www.humhub.org)"

Please, can anyone help me?

Thanks a lot!

Suus

**Comment by WASasquatch** [comment]
It's because your localhost has no internet to be able to fetch the modules online to download and install them.

**Comment by suustenvoorde** [comment]
Do I have to change something in the script or something else to fix it? Or is it impossible because my localhost has no internet to fetch the modules? 

Thanks you very much!

**Comment by WASasquatch** [comment]
I don't think there is a fix currently, there was proposed enhancement to make the connection optional. I can't find the request however. Hopefully development team can help you.

**Comment by suustenvoorde** [comment]
I will try to ask this question to the development team. Thanks a lot!
