### ISSUE TITLE
Confirm deletion should mention post type

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/humhub#6350]
### Is your feature request related to a problem? Please describe.

Contents of different modules are added as stream content like posts (events, wiki pages, links). The delete option does not make clear that the content itself will be deleted, not just the stream entry.
See https://community.humhub.com/content/perma?id=267932

### Describe the solution you'd like

The modal window "Confirm post deletion" should use the post type (wiki page, event, link etc.) instead of always "post".

### Describe alternatives you've considered

Let the modules decide about the deletion process. But I think the post type is good.

**Comment by luke-** [comment]
Thank you for the report.

@Semir1212 Don't we already have an internal wording issue on this?

**Comment by luke-** [comment]
Related: https://github.com/humhub/wording/issues/107

Will be fixed in v1.15
