### ISSUE TITLE
Create new module "space" guide invalid

### ISSUE THREAD

**Issue by Kakiho** [humhub/humhub#636]
> https://github.com/humhub/humhub/blob/master/protected/docs/guide/developer/space.md

```    
'SpaceModuleBehavior' => array(
    'class' => 'application.modules_core.space.SpaceModuleBehavior',
),
```
This is NOT WORK
Please, change to:
```
'SpaceModuleBehavior' => array(
    'class' => 'application.modules_core.space.behaviors.SpaceModuleBehavior',
),
```
This is WORK (from "Polls" module).

**Comment by ziegenberg** [comment]
please close, was fixed in a4816fb42c479a2549da97ca62a4957c4495c1dc
