### ISSUE TITLE
Add an event in the NotificationManager to allow removing some notifications categories in the settings

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6363]
### Is your feature request related to a problem? Please describe.

Some modules needs to remove notification categories in the account settings:
- E.g. 1: the upcoming Reaction module needs to hide the Like category.
- E.g. 2: on a custom Humhub instance, we want to hide some categories in the settings because we don't want to allow users to change them, or to reduce complexity (leave only the most important categories)

### Describe the solution you'd like

Add an event in the NotificationManager that can be triggered by a module.

**Comment by funkycram** [comment]
@luke- what do you think about this PR? https://github.com/humhub/humhub/pull/6364

Usage example:
```php
            foreach ($event->result as $key => $moduleNotification) {
                if ($moduleNotification instanceof NewLike) {
                    unset($event->result[$key]);
                }
            }
```

Thanks!

**Comment by luke-** [comment]
@funkycram Looks good. Thank you!
