### ISSUE TITLE
Editing wall entries does not transform their markdown format into HTML until refresh

### ISSUE THREAD

**Issue by LiveLaughLearn** [humhub/humhub#6366]
### What steps will reproduce the problem?
Install a fresh 1.14.2 release and turn on recommended modules during setup.
Create a wall entry that contains some basic formatting. Edit the entry and hit save. Entry will be displayed in untransformed markdown format until page is refreshed

### What is the expected result?
After saving entry should directly transform into html and look the same as during the editing

### What do you get instead?
Until refreshing wall entry shows markdown format

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.2 release from https://github.com/humhub/humhub/releases/tag/v1.14.2
| PHP version      |  8.0 and 8.1 tested
| Operating system | MacOS 12.4 with Chrome 112.0

No error logging in Humhub Logs and Dev console. No backend chaching in place.

**Comment by ArchBlood** [comment]
Is this a git based installation or from HumHub download site?

**Comment by LiveLaughLearn** [comment]
More or less git based - as stated in the Q/A I took the release from the v1.14.2 tag 1w ago. Links can be found in the additional info section.
Not to mention I ran composer install and build all assets

**Comment by luke-** [comment]
Should be fixed with upcoming 1.14.3
https://github.com/humhub/humhub/blob/master/CHANGELOG.md#1143-unreleased
