### ISSUE TITLE
A-Z Sorting in Settings/Modules

### ISSUE THREAD

**Issue by lisandi** [humhub/humhub#6376]
###A-Z listing in Modules
### Chaos right now - no sorting - usability gen zero
Right now it is a complete chaos and takes lots of time to find and to configure or adjust a module because the modules are not simply srted A-Z

### A-Z sorting - usability state of the art
Simply Present all Modules in an alphabetical order and admins can fast find the correct module and do the necessary configurations. It makes also support  so much easier because you can people tell that the module appears after or before one they probably have already found. This is especially necessary when you work and have support countries like Thailand a.o. where there is already a huge language problem and english proficiency is more or less near zero

**Comment by luke-** [comment]
We're working already on an optimized view: https://github.com/humhub/humhub/pull/6348
