### ISSUE TITLE
In command line, a content cannot be archived

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6383]
### What steps will reproduce the problem?

In a console controller, create this code:

```php
$content = Content::findOne(1);
var_dump($content->canArchive());
$content->archive();
return;
```

### What is the expected result?

`true` and the content is archived.

### What do you get instead?

`false` and the content is not archived.

### Additional info

`->archive()` doesn't archive the content because it first checks if `->canArchive()`.

`->canEdit()` and `->canPin()` also return `false`.

I think we should add an exception when `Yii::$app->request->isConsoleRequest` is `true` in `humhub\modules\user\components/PermissionManager::can()` but I'm not sure:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/components/PermissionManager.php#L67

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.2

**Comment by yurabakhtin** [comment]
@funkycram I think for actions which require a logged in user you should have some special user or it may be Admin, so you should run the code like this before:

```php
$consoleUser = User::findOne(['username' => 'console_user']);
if ($consoleUser instanceof IdentityInterface) {
    Yii::$app->user->switchIdentity($consoleUser);
} else {
    return;
}
```

**Comment by funkycram** [comment]
Thanks @yurabakhtin . Yes, that would be an option. 
But I think that a console controller should have rights to create (except if `created_by` is required), delete, archive, edit and pin content.
However, if you think that switching to and admin account is the correct way to manipulate content with command line, I'll close this issue.

**Comment by luke-** [comment]
@yurabakhtin Yes, I like the idea. We should probably do it in this way in general.

**Comment by yurabakhtin** [comment]
@luke- Do you mean you prefer this way? :

```php
if ($content->canArchive() && $content->archive()) {
    // run some code
}
```

So we should remove the `$content->canArchive()` from the method `$content->archive()`?

**Comment by yurabakhtin** [comment]
@luke- Done in PR https://github.com/humhub/humhub/pull/6437.

**Comment by funkycram** [comment]
Thanks @yurabakhtin ! That's fine and has now the same behavior than `pin()` which didn't checks if `canPin()`.
