### ISSUE TITLE
Error when a user registers

### ISSUE THREAD

**Issue by mrluisiko99** [humhub/humhub#639]
![captura](https://cloud.githubusercontent.com/assets/9170655/5895769/067caece-a529-11e4-9c80-d2a455451cfc.PNG)
Please help!

Error in logging:
Trying to get property of non-object (/public_html/protected/modules_core/space/behaviors/SpaceModelMembershipBehavior.php:339) Stack trace: #0 /public_html/protected/vendors/yii/db/ar/CActiveRecord.php(227): Space->__call() #1 public_html/protected/modules_core/user/models/User.php(385): Space->__call() #2 /public_html/protected/modules_core/user/models/User.php(385): Space->addMember() #3 /public_html/protected/modules_core/user/models/User.php(347): User->setUpApproved() #4 /public_html/protected/vendors/yii/db/ar/CActiveRecord.php(1097): User->afterSave() #5 public_html/protected/vendors/yii/db/ar/CActiveRecord.php(806): User->insert() #6 public_html/protected/modules_core/user/controllers/AuthController.php(317): User->save() #7 public_html/protected/vendors/yii/web/actions/CInlineAction.php(49): AuthController->actionCreateAccount() #8 /public_html/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #9 /public_html/protected/vendors/yii/web/CController.php(286): AuthController->runAction() #10 /public_html/protected/vendors/yii/web/CController.php(265): AuthController->runActionWithFilters() #11 /public_html/protected/vendors/yii/web/CWebApplication.php(282): AuthController->run() #12 /public_html/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #13 /public_html/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #14 /public_html/index.php(39): WebApplication->run() REQUEST_URI=/user/auth/createAccount/token/54c5d9349d11f142482139 in /public_html/protected/modules_core/space/behaviors/SpaceModelMembershipBehavior.php (339) in /public_html/protected/modules_core/user/models/User.php (385) in /public_html/protected/modules_core/user/models/User.php (385) in /public_html/protected/modules_core/user/models/User.php (347) in /public_html/protected/modules_core/user/controllers/AuthController.php (317)

**Comment by mrluisiko99** [comment]
I have resolved. It was a problem with a space. I have removed the space and it works now but... What was the problem?

**Comment by hezthuo** [comment]
Hi, Mrluiski, Having same problem :( Where was the space?

**Comment by mrluisiko99** [comment]
It was the Welcome space

**Comment by hezthuo** [comment]
Thank you so much for the swift response. I will try that :)

**Comment by cdoebler** [comment]
Hi guys,

did anybody else get into this kind of trouble? I removed the Welcome Space but the error is still there when a new user registers, right after he typed in his registration data (username, firstname, lastname, etc.).

Cheers,

Chris

**Comment by hezthuo** [comment]
-cdoebler I found that enabling a default space and "Require group admin approval after registration" at the same time caused this error for me. When I disabled one or both of them it was ok.

Regards,

Hez

**Comment by cdoebler** [comment]
Hi Hez,

thanks for helping! Unfortunately, this didn't work for me. To make the registration work again, I had to patch temporarily:
```
--- protected/modules_core/space/behaviors/SpaceModelMembershipBehavior.php
+++ protected/modules_core/space/behaviors/SpaceModelMembershipBehavior.php
@@ -336,7 +336,7 @@ class SpaceModelMembershipBehavior extends CActiveRecordBehavior
             $membership->admin_role = 0;
             $membership->share_role = 0;

-            $userInvite = UserInvite::model()->findByAttributes(array('email' => $user->email));
+            $userInvite = UserInvite::model()->findByAttributes(array('email' => Yii::app()->user->email));
             if ($userInvite !== null && $userInvite->source == UserInvite::SOURCE_INVITE) {
                 SpaceInviteAcceptedNotification::fire($userInvite->user_originator_id, $user, $this->getOwner());
             }
```

Cheers,

Chris
