### ISSUE TITLE
Possibility to replace module licence key with another one

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6401]
### Is your feature request related to a problem? Please describe.

On the modules administration, add a licence key for a module.

Later, you want to replace this licence key with another one, without removing it on the Partner site (in case of use on the other Humhub instances).

If you try adding the new licence key on Humhub, the old licence key is staying.

### Describe the solution you'd like

![image](https://github.com/humhub/humhub/assets/23310825/817053dd-347a-459d-beb2-c175315d0889)

Clicking on “Register” replaces the old key with the new one.

### Describe alternatives you've considered

A possibility to remove the key on Humhub (and not on the Partner site).

Thanks!

**Comment by yurabakhtin** [comment]
@luke- 

> Clicking on “Register” replaces the old key with the new one.

I have implemented this way in PR https://github.com/humhub/web/pull/26.

**Comment by funkycram** [comment]
Thanks @yurabakhtin for your quick fix!
That's fine!
PS: I have no access to https://github.com/humhub/web

**Comment by luke-** [comment]
@funkycram Is deployed, can you please test?

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by funkycram** [comment]
> @funkycram Is deployed, can you please test?

It works perfectly, thanks!
