### ISSUE TITLE
Translation for custom profile field is served from wrong file

### ISSUE THREAD

**Issue by codiflow** [humhub/humhub#6403]
### What steps will reproduce the problem?
- Create a new profile field and assign the ModuleID.MessageFile `UserModule.custom`
- Enter `Field name X` into the field name and `Description X` into the description fields
- Save
- Add the respective translations to the two files (this is for German):

`/protected/config/messages/de/UserModule.profile.php`

```php
<?php
return array (
    'Field name X' => 'Field name (Profile)',
    'Description X' => 'Description X (Profile)',
);
```

`/protected/config/messages/de/UserModule.custom.php`
```php
<?php
return array (
    'Field name X' => 'Field name (Custom)',
    'Description X' => 'Description X (Custom)',
);
```

### What is the expected result?
If I change the ModuleID.MessageFile to `UserModule.profile` the translations for field name and description are served from the respective ModuleID.MessageFile file.

### What do you get instead?
The field name does but the description **does not**. It is always served from `/protected/config/messages/de/UserModule.profile.php`

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.2
| PHP version      | 8.1
| Operating system | Debian

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by gevorgmansuryan** [comment]
Can not reproduce.

![Image](https://github.com/humhub/humhub/assets/11891855/555d31b6-fa07-49bf-9d94-d7cd954bb3d5)

![Image](https://github.com/humhub/humhub/assets/11891855/f5b78933-0d85-4861-89a4-b9cb83d056c3)

can you please try `php yii cache/flush-all` ?

**Comment by ArchBlood** [comment]
I'm not able to reproduce this either, as once a custom translation id is placed my translations reflect the file created in the correct order.

**Comment by codiflow** [comment]
Interesting. One difference between your screenshots and my paths are the file names – may this be the cause?

I'm putting stuff to `UserModule.custom.php` and `UserModule.profile.php`, you put it into `custom.php` and `profile.php`.

What did you assign to the field `ModuleID.MessageFile`? I used `UserModule.custom` and `UserModule.profile` there.

**Comment by codiflow** [comment]
`php yii cache/flush-all` did not change anything.

Here an additional screenshot with my config:
![image](https://github.com/humhub/humhub/assets/43847817/631721a4-28d1-4a1b-8315-f25e45c5f341)

Content of `/htdocs/protected/config/messages/de/UserModule.profile.php`:
```
<?php
return array (
'Add a link to your Telegram group here (if any)' => 'Falls du eine Telegram-Gruppe betreibst, kannst du hier den Link dazu angeben (Profile)',
);
```

Content of `/htdocs/protected/config/messages/de/UserModule.custom.php`:
```
<?php
return array (
'Add a link to your Telegram group here (if any)' => 'Falls du eine Telegram-Gruppe betreibst, kannst du hier den Link dazu angeben (Custom)',
);
```

It still only displays the translation from `UserModule.profile.php`:
![image](https://github.com/humhub/humhub/assets/43847817/e15d4ab3-91d7-4064-91da-f8f7decc4f4e)

**Comment by gevorgmansuryan** [comment]
@codiflow thanks for additional info. Now i'm able to reproduce. It's already fixed

**Comment by luke-** [comment]
@gevorgmansuryan Thanks!
