### ISSUE TITLE
Question: How to change the distance between the panels?

### ISSUE THREAD

**Issue by Vatarus** [humhub/humhub#641]
Greetings! 
How to change the distance between the panels? 
Thanks in advance.
![padding](https://cloud.githubusercontent.com/assets/3394915/5896675/c14e6c4e-a57c-11e4-8d60-71c020fd3366.png)

**Comment by andystrobel** [comment]
By changing the CSS!?!

**Comment by andystrobel** [comment]
The easyiest way would be to change the CSS. HumHub is built with Bootstrap. So please have a look at http://getbootstrap.com/
