### ISSUE TITLE
Spaces directory shows the "Member" button on spaces of which I'm not a member

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6415]
### What steps will reproduce the problem?

Create a new account on https://community.humhub.com/
Go to https://community.humhub.com/spaces

### What is the expected result?

Have a "Join" button on space cards I'm not a member of and that I can join.

### What do you get instead?

![image](https://github.com/humhub/humhub/assets/23310825/827f550b-452b-4351-8b82-255e6a918c52)

**Comment by luke-** [comment]
@yurabakhtin Thanks!

@gevorgmansuryan FYI
