### ISSUE TITLE
An internal server error occurred. After Humhub Moving from host to host 

### ISSUE THREAD

**Issue by imadn** [humhub/humhub#6426]
### What steps will reproduce the problem?
I am trying to move a humhub app from an old to new host by using official docker compose from docker hub
When running docker-compse up, every thing is ok and I can access to host:8080, Humhub app is up no problem from Humhub, we can connect to our new db
The goal is to move mariadb and connect Humhub to that mariadb, so, I recovered a mariadb backup.sql from the old host using the command sudo docker exec db_container sh -c 'exec mariadb-dump --all-databases -uroot -p"sql root password"' > all-databases.sql
And then, restore from backup (.sql) to the new host by docker exec -i environment_db_1 sh -c 'exec mariadb -uroot -p"root"' < databases.sql
When connecting to mariadb_container on new host by docker exec -it ... /bin/bash and then we run mysql -u root -p ... we can run sql queries without issue 
The issue starts when we try to connect humhub to the imported database, after filling all fields db_host, port, db_user, db_password, db_name. after clic on next we have "An internal server error occurred."

### What is the expected result?
we move Humhub app without issue.

### What do you get instead?
not able to load and read an imported mariadb

### Additional info
from docker compose logs, we have:
humhub_1  | - -  11/Jul/2023:22:26:48 +0000 "GET /index.php" 200
humhub_1  | - -  11/Jul/2023:22:26:57 +0000 "POST /index.php" 302
humhub_1  | - -  11/Jul/2023:22:26:58 +0000 "GET /index.php" 302
humhub_1  | - -  11/Jul/2023:22:26:58 +0000 "GET /index.php" 500
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "NOTICE: PHP message: An Error occurred while handling another error:"
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "ReflectionException: Class redis does not exist in /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Container.php:507"
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "Stack trace:"
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "#0 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct()"
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "#1 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()"
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "#2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()"
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "#3 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Instance.php(175): yii\di\Container->get()"
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "#4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Instance.php(144): yii\di\Instance->get()"
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2-redis/src/Cache.php(175): yii\di\Instance::ensure()"
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "#6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\redis\Cache->init()"
humhub_1  | [11-Jul-2023 22:26:58] WARNING: [pool www] child 49 said into stderr: "#7 [internal function]: yii\base\BaseObjec..."
humhub_1  | 2023/07/11 22:26:58 [error] 45#45: *7 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
humhub_1  | ReflectionException: Class redis does not exist in /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Container.php:507
humhub_1  | Stack trace:
humhub_1  | #0 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct()
humhub_1  | #1 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
humhub_1  | #2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
humhub_1  | #3 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Instance.php(175): yii\di\Container->get()
humhub_1  | #4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/di/Instance.php(144): yii\di\Instance->get()
humhub_1  | #5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2-redis/src/Cache.php(175): yii\di\Instance::ensure()

| Q                | A
| ---------------- | ---
| HumHub version   | stable
| PHP version      | 7.4.33
| Operating system | "Ubuntu 18.04.6 LTS"

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
From looking at the error you have enabled redis but don't have a redis configured correctly.

My other question would be what type of server was the old one hosted on.

**Comment by imadn** [comment]
Hello,
Thanks for your investigation
You'r right, by adding and config redis ... we have no issue
