### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by spifd** [humhub/humhub#643]
Hi, is there any open REST API to post status, comments, ...  ?

**Comment by luke-** [comment]
Unfortunately not.

But this functionality could be added as module/extension.

**Comment by studentdeng** [comment]
Do we have any plan to build this REST API ?
It would be useful to support other client

**Comment by haimich** [comment]
I would love to have a REST API, because we're planning to migrate our current website including all of the user profiles to the superb Humhub which would mean manual effort without an API.

**Comment by mboo2005** [comment]
Is there any plan to build this REST API?
We need a REST API in our iOS App.

**Comment by MVprobr** [comment]
+1

**Comment by okobsamoht** [comment]
Hello somebody made it!
see here https://github.com/petersmithca/humhub-api

**Comment by shiddhant** [comment]
Please tell me. how can i use this petersmitca  humhub-api ...give sample demo please
