### ISSUE TITLE
Filter: Collapsible State in URL

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6439]
Currently, active filters are included in the URL. e.g.

https://example.com/dashboard?filters[entry_archived]=1&filters[entry_files]=1

It would also be good to include the state of the filter box (collapsed or expanded) in the URL.

**Comment by sunshinebard** [comment]
with that I could achieve that there is one navigation for the public posts:
![image](https://github.com/humhub/humhub/assets/77971502/3e2c0445-67db-4cd8-afa3-ec98860a3983)

should be just displayed like this
![image](https://github.com/humhub/humhub/assets/77971502/04e8924f-532b-455c-ac78-a8c0ae4f3c3b)

**Comment by yurabakhtin** [comment]
@luke- 

> It would also be good to include the state of the filter box (collapsed or expanded) in the URL.

PR https://github.com/humhub/humhub/pull/6445

> with that I could achieve that there is one navigation for public posts ("öffentlich").

Should we implement new tags in the header like we have for "Content Type" and "Topic"?

**Comment by luke-** [comment]
> @luke-
> 
> > It would also be good to include the state of the filter box (collapsed or expanded) in the URL.
> 
> PR #6445

Thanks!

> 
> > with that I could achieve that there is one navigation for public posts ("öffentlich").
> 
> Should we implement new tags/labels in the header like we have for "Content Type" and "Topic"?

Not for now, we first need a UI concept for that.
