### ISSUE TITLE
JPEG data: premature end of data

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#644]
In user profile post

"NetworkError: 500 Internal Server Error - http://site.com/wall/wall/stream/type/Community/guid//limit/4/from/78447/filters//sort/c?CSRF_TOKEN=7a496a7db96b9475364ec74a990dff8f55e3155a&_=2472273116235"

PHP Error
<p>imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Corrupt JPEG data: premature end of data segment
</p>

**Comment by radiolip** [comment]
solved by deleting the user who uploaded the corrupted image, but it is not good solution for future...
