### ISSUE TITLE
Filter: Topics not included when Filter is loaded by URL

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6441]
e.g. create a Filter with topics e.g.

![image](https://github.com/humhub/humhub/assets/4736168/43151e91-832d-4d7a-9341-db47d58bd735)
The Topic is added correctly. 

Open generated URL e.g. https://example/s/humhub-feedback/?topics[]=12

![image](https://github.com/humhub/humhub/assets/4736168/cc0f5694-b038-4be4-bd35-63690e852d68)

**Comment by sunshinebard** [comment]
would be also nice, if the other options are somehow shown too. eg "public" - just by a symbol.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6446.
