### ISSUE TITLE
http://translate.humhub.org status?

### ISSUE THREAD

**Issue by JirosMunro** [humhub/humhub#645]
I would like to see if I could help with a Slovak translation and was looking for some resources to help me get started as I am new to both HumHub and the Yii framework. I found this issue https://github.com/humhub/humhub/issues/163 which suggested registering at http://translate.humhub.org but there has been a message up for the last couple of days that it is "Temporarily down for updating & merging"

Is it due to come back up soon? Or is there somewhere else  you could suggest?

Thanks 

Jamie

**Comment by luke-** [comment]
translate.humhub.org will be back in few hours.

**Comment by JirosMunro** [comment]
Great. Thanks Luke. 

Jamie

**Comment by luke-** [comment]
Done, I've also added the Slovak language files.
