### ISSUE TITLE
Redirect to the latest-visited page after login or registration

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6458]
### Is your feature request related to a problem? Please describe.

1. Logout
2. Click on a notification link or go directly on a specific URL of Humhub (a private page)
3. Login or create an account to view the private page
4. You are redirected to the homepage

### Describe the solution you'd like

Be redirected to the latest-visited page

**Comment by funkycram** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6459

**Comment by luke-** [comment]
@funkycram Hmm, cannot reproduce this. I've tried (with `develop`).

1.) Logout
2.) Enter `http://humhub.localhost/spaces` in Browser
3.) Redirected to `https://luke.humhub.com/user/auth/login`
4.) After login I'm redirected to:  `http://humhub.localhost/spaces`

**Comment by funkycram** [comment]
Thanks @luke- for your tests.
You're right if "Allow visitors limited access to content without an account" is unticked.
But if ticked, then the login is done with the modal box, in ajax mode.
In this case, we have the problem.

So I've moved my fix to the ajax condition as it's unnecessary in full page login:
https://github.com/humhub/humhub/pull/6459/commits/501fff1fda3b7684e235292e9cfe566cc5f55671

**Comment by luke-** [comment]
@funkycram Would this also fixes the bug? https://github.com/humhub/humhub/pull/6459/files/501fff1fda3b7684e235292e9cfe566cc5f55671..913bff3b61a2e2871c681142c61273f46adb667e

**Comment by funkycram** [comment]
Thanks @luke- ! I would never have found this place to save the redirect URL!
Tested in all conditions (classic login, SSO, account registration), your solution always works perfectly!

**Comment by luke-** [comment]
@funkycram I also first looked in other places like `loginRequired()`. :-) But thanks for testing!
