### ISSUE TITLE
Bug? `ContentContainerControllerAccess::isAdmin` contains inaccessible code

### ISSUE THREAD

**Issue by martin-rueegg** [humhub/humhub#6464]
https://github.com/humhub/humhub/blob/7a2495325911fa6746c253c9556cd932092970ec/protected/humhub/modules/content/components/ContentContainerControllerAccess.php#L176-L177

This condition is never true, as the previous check is exactly the same.

Is this a hidden bug and the test should be different or can the second conditional block just be removed?

@buddh4?

**Comment by luke-** [comment]
@martin-rueegg Seems to be a bug.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6541.
