### ISSUE TITLE
Module Administration - Marketplace Links broken

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6468]
### What steps will reproduce the problem?

Install Beta, go to Administration Modules

![image](https://github.com/humhub/humhub/assets/4736168/4c15cd4a-0b89-45d0-aa06-7e22d42b4d7b)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15  Beta1
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6470.

**Comment by luke-** [comment]
@yurabakhtin Thanks, please do not forget to update the changelog. I've added this change...

**Comment by yurabakhtin** [comment]
@luke- Ok, I thought no need to add a separate point for such small fix.

**Comment by luke-** [comment]
@yurabakhtin Did you also fixed the link here?
![image](https://github.com/humhub/humhub/assets/4736168/09c8cada-35c6-4bbb-8926-8c44eb475216)

**Comment by yurabakhtin** [comment]
@luke- Yes, because the 3 links is the same widget `humhub\modules\marketplace\widgets\MarketplaceLink` where I fixed URL.

![install_updates-link](https://github.com/humhub/humhub/assets/6995524/abdee208-aa94-4507-901b-b2ea4924d654)

**Comment by luke-** [comment]
@yurabakhtin thanks!
