### ISSUE TITLE
Unable to change LDAP server

### ISSUE THREAD

**Issue by JoaoSilva-JS** [humhub/humhub#6479]
Good afternoon, I'm trying to change the LDAP server, but when I click on save the saved message appears, but the server goes back to how it was before and it is not possible to place the new one.

![1](https://github.com/humhub/humhub/assets/78453835/a2e38e0a-b119-4d3c-a79b-c2fbb35c1f1e)
![2](https://github.com/humhub/humhub/assets/78453835/2ce9fc0e-57b6-4e05-9605-474e0d490e6a)
![3](https://github.com/humhub/humhub/assets/78453835/b7671496-62f3-4851-8778-ed69b03bf96f)

**Comment by luke-** [comment]
Can you please provide more details? Version number & log entries.

Maybe there is a problem with the cache or there are other errors in the LDAP configuration page.

**Comment by JoaoSilva-JS** [comment]
Version: 1.14.2

In the log there is no error, it seems that he is considering the action as a success.

Here is the last error log that occurred

yii\base\ErrorException: mkdir(): Permission denied in /var/www/humhub/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:645
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(645): mkdir()
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(642): yii\helpers\BaseFileHelper::createDirectory()
#3 /var/www/humhub/protected/humhub/modules/file/components/StorageManager.php(163): yii\helpers\BaseFileHelper::createDirectory()
#4 /var/www/humhub/protected/humhub/modules/file/components/StorageManager.php(117): humhub\modules\file\components\StorageManager->getPath()
#5 /var/www/humhub/protected/humhub/modules/file/models/File.php(140): humhub\modules\file\components\StorageManager->delete()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(754): humhub\modules\file\models\File->beforeDelete()
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(724): yii\db\ActiveRecord->deleteInternal()
#8 /var/www/humhub/protected/humhub/modules/file/Events.php(51): yii\db\ActiveRecord->delete()
#9 [internal function]: humhub\modules\file\Events::onCronDailyRun()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#12 /var/www/humhub/protected/humhub/commands/CronController.php(130): yii\base\Component->trigger()
#13 /var/www/humhub/protected/humhub/commands/CronController.php(55): humhub\commands\CronController->runDaily()
#14 [internal function]: humhub\commands\CronController->actionRun()
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#19 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#20 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#21 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#22 /var/www/humhub/protected/yii(29): yii\base\Application->run()
#23 {main}

Next yii\base\Exception: Failed to create directory "/var/www/humhub/uploads/file/6/4": mkdir(): Permission denied in /var/www/humhub/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:650
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(642): yii\helpers\BaseFileHelper::createDirectory()
#1 /var/www/humhub/protected/humhub/modules/file/components/StorageManager.php(163): yii\helpers\BaseFileHelper::createDirectory()
#2 /var/www/humhub/protected/humhub/modules/file/components/StorageManager.php(117): humhub\modules\file\components\StorageManager->getPath()
#3 /var/www/humhub/protected/humhub/modules/file/models/File.php(140): humhub\modules\file\components\StorageManager->delete()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(754): humhub\modules\file\models\File->beforeDelete()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(724): yii\db\ActiveRecord->deleteInternal()
#6 /var/www/humhub/protected/humhub/modules/file/Events.php(51): yii\db\ActiveRecord->delete()
#7 [internal function]: humhub\modules\file\Events::onCronDailyRun()
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#10 /var/www/humhub/protected/humhub/commands/CronController.php(130): yii\base\Component->trigger()
#11 /var/www/humhub/protected/humhub/commands/CronController.php(55): humhub\commands\CronController->runDaily()
#12 [internal function]: humhub\commands\CronController->actionRun()
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#14 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#20 /var/www/humhub/protected/yii(29): yii\base\Application->run()
#21 {main}

**Comment by JoaoSilva-JS** [comment]
2023-08-04 08:28:07 [177.136.40.230][-][-][warning][yii\caching\FileCache::setValue] Unable to write cache file '/var/www/humhub/protected/runtime/cache/b0/humhubb0af4f05c6c608f3a445d4dbc083d653.bin': file_put_contents(/var/www/humhub/protected/runtime/cache/b0/humhubb0af4f05c6c608f3a445d4dbc083d653.bin): failed to open stream: Permission denied
2023-08-04 08:28:07 [177.136.40.230][-][-][warning][yii\caching\FileCache::setValue] Unable to write cache file '/var/www/humhub/protected/runtime/cache/60/humhub603dc001ed7eec95b0c26ace56b4e8ea.bin': file_put_contents(/var/www/humhub/protected/runtime/cache/60/humhub603dc001ed7eec95b0c26ace56b4e8ea.bin): failed to open stream: Permission denied
2023-08-04 08:28:07 [177.136.40.230][-][-][info][application] $_GET = []
