### ISSUE TITLE
Reasons why feed may stop loading?

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#648]
I am curious, I haven't made any JS changes that would cause this (literally all there is, is added HTML and stuff to the view), but my feeds only load one, or two sets of posts before failing. Any reasons why this may happen? 

On my personal profile, the feed doesn't seem to load even a second set of posts. On the dashboard it loads 3 and fails.

**Comment by radiolip** [comment]
https://github.com/humhub/humhub/issues/644  

https://github.com/humhub/humhub/issues/483

**Comment by WASasquatch** [comment]
This same error happens on a fresh install of HumHub using the same DB as well. So it's not the source code. Any ideas still? This is a huge crutch and may have to abandon HumHub development.

**Comment by gamebenchjake** [comment]
I've just testing on my installation with no issues - loaded through 5 sets of posts just fine.

**Comment by WASasquatch** [comment]
This seems to be a DB error. Or something relative. The DB has given me nothing but problems because NO WHERE does HumHub actually check if it's connections are true, or if the data it seeks exists, so instead it just errors out. For example, try importing parts of a DB to a new build (like your members)

**Comment by gamebenchjake** [comment]
Interesting - could you be missing some related rows in a module DB? I've noticed that HumHub likes to shit the bed so to speak when it's missing a row.

**Comment by WASasquatch** [comment]
That's what I assumed, but there is nothing in the log file. It seems to simply be JS breaking for some unknown reason because of data it's pulling.

**Comment by gamebenchjake** [comment]
Care to post your updated feed file? I'd like to take a look and see if I can't help debug it.

**Comment by WASasquatch** [comment]
The problem exists on both a unaltered HumHub, so its the DB not the feed.

**Comment by gamebenchjake** [comment]
It's possible that it's an encoding issue - aye - try changing your collation?

**Comment by dasmoscas** [comment]
Guys, I have the same problem and just now I figured out how to trigger it.
I thought that the streams appeared only for the super administrator, because of its administrator premissions, but the problem was that the administrator uses the English language, while normal users use pt_br.
Only changing the user language to English in the DB or in the user settings the stream went back to work.
BUT I need to use pt_br :(
Any help on this?

**Comment by Censtudios** [comment]
This issue still persists. My members asked me to activate SSL so I did using Cloudflare, but now using the https:// URL for profiles it won't show the stream at all, it's basically just blank where the stream should be. If I visit the same pages with just http then it shows fine.

**Comment by luke-** [comment]
@dasmoscas Please provide at least :
- Error Messages (Webserver, HumHub, Browser/Javascript)
- Used Version(s)

**Comment by Censtudios** [comment]
- For me there are no error messages at all, it just doesn't load, like it's non-existent.
- Caused when I visit the site as HTTPS. Some things like the profile feed and the "total users" and "online right now" on the directory page don't show up at all.
- Version 0.20.1
- All browsers

**Comment by dasmoscas** [comment]
I have the answer!!!
some translation files might not have been saved as UTF-8 (or UTF-8 BOM
whatever)
My problem was the translation files of the library module.
Seriously, I found out by chance after trying to debug all mothrfuckin'
things. Found out while on the phone discussing other stuff.
Review permissions and the codification of all translation files, or else
the damn timeline won't load.
Hope it helps!!!
success!

On Wed, Nov 25, 2015 at 8:12 AM, Censtudios <notifications@github.com>
wrote:

>
>    - For me there are no error messages at all, it just doesn't load,
>    like it's non-existent.
>    - Caused when I visit the site as HTTPS. Some things like the profile
>    feed and the "total users" and "online right now" on the directory page
>    don't show up at all.
>    - Version 0.20.1
>    - All browsers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/648#issuecomment-159560888>.
>



-- 
[]s
Víctor Davi
