### ISSUE TITLE
Cannot save the "Set as default module" form on Humhub 1.15.0-beta.1

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6492]
### What steps will reproduce the problem?

Go to the page /admin/module/list and click on the "Set as default" module submenu:

![image](https://github.com/humhub/humhub/assets/23310825/43a5d0b6-4b56-4e19-a70d-e00348fbc062)

Then click on the "Save" button.

### What is the expected result?

The form is saved.

### What do you get instead?

![image](https://github.com/humhub/humhub/assets/23310825/4d5d7a43-bbad-41bc-8505-20ce1a57e3fc)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0-beta.1

**Comment by funkycram** [comment]
Thanks @yurabakhtin . Tested, it works well with this fix.
Yes, I also though a "Saved" flash message after submit would be nice.

**Comment by yurabakhtin** [comment]
> Yes, I also though a "Saved" flash message after submit would be nice.

@funkycram @luke- Done in commit https://github.com/humhub/humhub/pull/6494/commits/bdb212146d77fc9734d8e30b0634218cd06f80f3.
