### ISSUE TITLE
/vendor/maennchen/zipstream-php/src/ZipStream.php have a Error?

### ISSUE THREAD

**Issue by tosintech-web** [humhub/humhub#6495]
### What steps will reproduce the problem?
Administration Menu -> user -> export

### What is the expected result?
export a user information list with Excel file format

### What do you get instead?

```
ParseError: syntax error, unexpected identifier "Closure", expecting variable in /var/www/localhost/htdocs/protected/vendor/maennchen/zipstream-php/src/ZipStream.php:111
Stack trace:
#0 /var/www/localhost/htdocs/protected/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('...')
#1 /var/www/localhost/htdocs/protected/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/ZipStream3.php(15): Composer\Autoload\ClassLoader->loadClass('...')
#2 /var/www/localhost/htdocs/protected/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/ZipStream0.php(15): PhpOffice\PhpSpreadsheet\Writer\ZipStream3::newZipStream(Resource id #55)
#3 /var/www/localhost/htdocs/protected/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(548): PhpOffice\PhpSpreadsheet\Writer\ZipStream0::newZipStream(Resource id #55)
#4 /var/www/localhost/htdocs/protected/humhub/components/export/ExportResult.php(124): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save('...')
#5 /var/www/localhost/htdocs/protected/humhub/components/export/ExportResult.php(138): humhub\components\export\ExportResult->saveAs('...')
#6 /var/www/localhost/htdocs/protected/humhub/modules/admin/controllers/UserController.php(400): humhub\components\export\ExportResult->send()
#7 [internal function]: humhub\modules\admin\controllers\UserController->actionExport('...')
#8 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('...', Array)
#11 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('...', Array)
#12 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#13 /var/www/localhost/htdocs/index.php(25): yii\base\Application->run()
#14 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.3
| PHP version      |  8.1.13
| Operating system | Ubuntu 20.04

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
I had no issues creating an xlsx file and downloading it. I tested with both the stable and beta version with PHP 8.1.14 no errors have happened. :thinking:

**Comment by tosintech-web** [comment]
Is it related about this?

https://github.com/PHPOffice/PhpSpreadsheet/issues/3616

**Comment by tosintech-web** [comment]
I customize composer.json adding these lines to require block, then run conmposer update.

```
    "maennchen/zipstream-php": "^2.4",
    "yiisoft/yii2-composer": "~2.0.10",
```

Then, the excel file download is going as normaly. And downloaded file works as well as before.

**Comment by yurabakhtin** [comment]
@tosintech-web 

> My composer.lock file says:
> 
> ```
>         "name": "maennchen/zipstream-php",
>         "version": "3.1.0",
> ```

Do you know how you get the version `3.1.0`?
I tested this on HumHub version `1.14.3` with `composer install` and `composer update` but in all cases I get the version `2.2.6` for `maennchen/zipstream-php` as it is here https://github.com/humhub/humhub/blob/v1.14.3/composer.lock#L3004.

@luke- 

> I customize composer.json adding these lines to require block, then run conmposer update.

I am not sure we should add the `"maennchen/zipstream-php": "^2.4",` in `composer.json` because I cannot reproduce to have the version `maennchen/zipstream-php: 3.1.0` in the `composer.lock`.

**Comment by ArchBlood** [comment]
> @tosintech-web 
> 
> > My composer.lock file says:
> > 
> > ```
> >         "name": "maennchen/zipstream-php",
> >         "version": "3.1.0",
> > ```
> 
> Do you know how you get the version `3.1.0`?
> I tested this on HumHub version `1.14.3` with `composer install` and `composer update` but in all cases I get the version `2.2.6` for `maennchen/zipstream-php` as it is here https://github.com/humhub/humhub/blob/v1.14.3/composer.lock#L3004.
> 
> @luke- 
> 
> > I customize composer.json adding these lines to require block, then run conmposer update.
> 
> I am not sure we should add the `"maennchen/zipstream-php": "^2.4",` in `composer.json` because I cannot reproduce to have the version `maennchen/zipstream-php: 3.1.0` in the `composer.lock`.

I agree we shouldn't need to modify anything as it's a dependency of a dependency so not much can be done on our end.

https://github.com/PHPOffice/PhpSpreadsheet/blob/master/composer.json#L79

**Comment by luke-** [comment]
@yurabakhtin Not sure we should change anything here as @ArchBlood stated.

**Comment by yurabakhtin** [comment]
@luke- Ok, then this issue should be closed.
