### ISSUE TITLE
yii\base\UnknownPropertyException

### ISSUE THREAD

**Issue by moln4rvilmos** [humhub/humhub#6504]
### What steps will reproduce the problem?
INFÓ  Sun, 13 Aug 2023 20:55:17 +0200 application
$_GET = []

$_SERVER = [
'USER' => 'vh-41074'
'HOME' => '/var/www/customers/vh-41074'
'SCRIPT_NAME' => '/index.php'
'REQUEST_URI' => '/fcm-push/token/update'
'QUERY_STRING' => ''
'REQUEST_METHOD' => 'POST'
'SERVER_PROTOCOL' => 'HTTP/1.1'
'GATEWAY_INTERFACE' => 'CGI/1.1'
'REDIRECT_URL' => '/fcm-push/token/update'
'REMOTE_PORT' => '50536'
'SCRIPT_FILENAME' => '/var/www/customers/vh-41074/web/home/V/social/index.php'
'SERVER_ADMIN' => '[no address given]'
'CONTEXT_DOCUMENT_ROOT' => '/var/www/customers/vh-41074/web/home/V/social/'
'CONTEXT_PREFIX' => ''
'REQUEST_SCHEME' => 'http'
'DOCUMENT_ROOT' => '/var/www/customers/vh-41074/web/home/V/social/'
'REMOTE_ADDR' => '94.44.100.73'
'SERVER_PORT' => '80'
'SERVER_ADDR' => '172.20.100.106'
'SERVER_NAME' => 'social.vilix.hu'
'SERVER_SOFTWARE' => 'Apache'
'SERVER_SIGNATURE' => '<address>Apache Server at social.vilix.hu Port 80</address>
'
'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
'HTTP_COOKIE' => 'cookieconsent_status=dismiss; language=35a70f165f16ca1c4df87d7c97b69b87c8b4658cc26adaa5aa99af364bba6ba6a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22hu%22%3B%7D; _identity=04feae6b4dce70cc14ef59d1030c3d77817781d7ec0331c8566dab97e36eabc1a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A46%3A%22%5B1%2C%22_p9RhWs24JOMLebL0v9s7MrezJwLlZ3x%22%2C2592000%5D%22%3B%7D; PHPSESSID=sbc7l4d1vvc68hjj9o3e1eetg7; _csrf=27f042bf5b84db9120b025f9a880fa045c0419280ac459e32f5fcd1e5fa91ffda%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22q4Yxhq8E4QOZZaOt1Ze1SURA4JV0oceM%22%3B%7D'
'HTTP_ACCEPT_LANGUAGE' => 'hu-HU,hu;q=0.9'
'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
'HTTP_REFERER' => 'https://social.vilix.hu/dashboard'
'HTTP_SEC_FETCH_DEST' => 'empty'
'HTTP_SEC_FETCH_MODE' => 'cors'
'HTTP_SEC_FETCH_SITE' => 'same-origin'
'HTTP_ORIGIN' => 'https://social.vilix.hu'
'HTTP_SEC_CH_UA_PLATFORM' => '\"Linux\"'
'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
'HTTP_ACCEPT' => '*/*'
'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8'
'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
'HTTP_SEC_CH_UA_MOBILE' => '?0'
'HTTP_X_CSRF_TOKEN' => 'kTDU-LUq4OFQeZB1d9usYuBB3KzwdUbvZgiAh8bdGBrgBI2A3VvYpGQo3y8tuuMW0Ru5naMgFK5SQta3qb59Vw=='
'HTTP_DNT' => '1'
'HTTP_SEC_CH_UA' => '\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"'
'CONTENT_LENGTH' => '160'
'HTTP_X_FORWARDED_PROTO' => 'https'
'HTTP_X_FORWARDED_PORT' => '443'
'HTTP_X_REAL_IP' => '94.44.100.73'
'HTTP_HOST' => 'social.vilix.hu'
'proxy-nokeepalive' => '1'
'HTTP_AUTHORIZATION' => '***'
'HTTPS' => 'on'
'UNIQUE_ID' => 'ZNknFYAFYtdKynm8UYTfzAAAAgc'
'REDIRECT_STATUS' => '200'
'REDIRECT_HTTP_AUTHORIZATION' => ''
'REDIRECT_HTTPS' => 'on'
'REDIRECT_UNIQUE_ID' => 'ZNknFYAFYtdKynm8UYTfzAAAAgc'
'FCGI_ROLE' => 'RESPONDER'
'PHP_SELF' => '/index.php'
'REQUEST_TIME_FLOAT' => 1691952917.2108
'REQUEST_TIME' => 1691952917
]

### What do you get instead?
 Sun, 13 Aug 2023 20:55:17 +0200 yii\base\UnknownPropertyException
yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\fcmPush\models\FcmUser::sender_id in /var/www/customers/vh-41074/web/home/V/social/protected/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/customers/vh-41074/web/home/V/social/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get()
#1 /var/www/customers/vh-41074/web/home/V/social/protected/modules/fcm-push/services/TokenService.php(30): yii\db\BaseActiveRecord->__get()
#2 /var/www/customers/vh-41074/web/home/V/social/protected/modules/fcm-push/controllers/TokenController.php(41): humhub\modules\fcmPush\services\TokenService->storeTokenForUser()
#3 [internal function]: humhub\modules\fcmPush\controllers\TokenController->actionUpdate()
#4 /var/www/customers/vh-41074/web/home/V/social/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /var/www/customers/vh-41074/web/home/V/social/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#6 /var/www/customers/vh-41074/web/home/V/social/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#7 /var/www/customers/vh-41074/web/home/V/social/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#8 /var/www/customers/vh-41074/web/home/V/social/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#9 /var/www/customers/vh-41074/web/home/V/social/index.php(25): yii\base\Application->run()
#10 {main}
### Additional info

]
| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.3 and after 1.15.0 béta-1
| PHP version      | 8.2
| Operating system | inux s6 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 (nethely.hu)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
The error is stating that the sender id being used isn't being recognized by the token, or either the sender id is wrong or the token needs refreshed.

**Comment by moln4rvilmos** [comment]
> A hiba azt jelzi, hogy a használt feladóazonosítót a token nem ismeri fel, vagy a feladó azonosítója rossz, vagy a tokent frissíteni kell.

Thanks! And where can I do this? In the settings of the installed Humhub, do I need to change some file or in the webhosting service?

**Comment by ArchBlood** [comment]
> > A hiba azt jelzi, hogy a használt feladóazonosítót a token nem ismeri fel, vagy a feladó azonosítója rossz, vagy a tokent frissíteni kell.
> 
> Thanks! And where can I do this? In the settings of the installed Humhub, do I need to change some file or in the webhosting service?

If you're using the newest version of the Push Notification module there's two options, use the `push.humhub.com` service or the Google firebase service, if you're using firebase then you'd have to change this from their settings, if HumHub's service is used then that would be something to email HumHub about directly.

**Comment by moln4rvilmos** [comment]
THANKS! What is Installation ID?

**Comment by ArchBlood** [comment]
@luke- I believe this can be closed.
