### ISSUE TITLE
Suggestion - notification of new message in title

### ISSUE THREAD

**Issue by mrluisiko99** [humhub/humhub#651]
If you have a new message (mail) the title doesn't show as show the notifications. [ (1) SiteTitle]

**Comment by WASasquatch** [comment]
Facebook doesn't do this either... because it's not a notification, it's a message.

**Comment by mrluisiko99** [comment]
I have not named any time Facebook... it is a suggestion, but if you don't want to add ok.

**Comment by WASasquatch** [comment]
You labeled it as a bug as if that is what it's suppose to do.....

**Comment by mrluisiko99** [comment]
I just wanted to help, I didn't come with bad intentions... but if you think so... bye.

**Comment by luke-** [comment]
Unfortunately this is not possible atm.

But we plan to enhance the mail module a lot in future - i think there will be some sort notifications
