### ISSUE TITLE
Scheduled Post Dates

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#6520]
### What steps will reproduce the problem?
Set a scheduled post date
Once the post is published it should show the publication dates (`updated_at` and `created_at`) for when the post is available.

### What is the expected result?
It should show when the publication was published not when the post was created.

### What do you get instead?
![Screenshot_20230817-105031.png](https://github.com/humhub/humhub/assets/35392110/d1f48f88-c2fa-49f8-a012-ae3e4bbf1dbe)

![Screenshot_20230817-105022.png](https://github.com/humhub/humhub/assets/35392110/03165a54-87eb-4f63-b374-14ebe070f1e1)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | Community site
| PHP version      | Community site
| Operating system | Community site

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
@yurabakhtin Can we change the date/time on publish?

**Comment by luke-** [comment]
@yurabakhtin Thanks, let's discuss further in #6337
