### ISSUE TITLE
Allow other users to write posts an my profile wall

### ISSUE THREAD

**Issue by andystrobel** [humhub/humhub#653]
User can activate / deactive it at his account settings

**Comment by WASasquatch** [comment]
+1

**Comment by programguy** [comment]
+1
Perhaps it could be enabled for only followers/following?

**Comment by xaro1** [comment]
+1

**Comment by WASasquatch** [comment]
In light of the followers/following, it may actually not be a good idea to implement this until the Friends system is in place. As all you'd need to do is follow someone, and blow up their feed.

**Comment by programguy** [comment]
I agree with @WASasquatch.

**Comment by timvango** [comment]
+1

**Comment by Stranikevg** [comment]
+1

**Comment by nomadkira** [comment]
+1
