### ISSUE TITLE
ONLYOFFICE can't view or edit files now (with beta)

### ISSUE THREAD

**Issue by WizWareTech** [humhub/humhub#6535]
### What steps will reproduce the problem?
Try to view or edit any ONLYOFFICE doc.
### What is the expected result?
The doc opens for viewing or editing.
### What do you get instead?
**Files other than docx open these two messages (and no file content shows):**
Yellow triangle:
The document could not be saved. Please check connection settings or contact your administrator.
When you click the 'OK' button, you will be prompted to download the document.

Red circle with white line:
An error has occurred while opening the file.
The file content corresponds to text documents (e.g. docx), but the file has the inconsisten extension .xlsx.

**docs Files open, but the file content is not the actual file content, and is instead part of the humhub login screen:**
Please sign in
Please login with your username/email and password.
1  Remember me

Sign in
Forgot your password?

Choose language:   
·	English (US)
·	English (UK)
·	Deutsch
·	Français
·	Nederlands
·	Polski
·	Português
·	Português do Brasil
·	Español
·	Català
·	Italiano
·	ไทย
·	Türkçe
·	Русский
·	Українська
·	Ελληνικά
·	日本語
·	Magyar
·	Norsk bokmål
·	Nynorsk
·	中文(简体)
·	中文(台灣)
·	Aragonés
·	Tiếng Việt
·	Svenska
·	Čeština
·	Dansk
·	Ўзбек
·	فارسی
·	Български
·	Slovenčina
·	Română
·	العربية/عربي‎‎
·	한국어
·	Bahasa Indonesia
·	Lietuvių kalba
·	Kreyòl ayisyen
·	Latvijas
·	Slovenščina
·	Hrvatski
·	አማርኛ
·	Suomalainen
·	עברית
·	Shqip
·	Cymraeg
·	Kiswahili
·	Сербисцх

Powered by HumHub
CancelConfirm
Hidden Gallery
‹›×

### Additional info
Version 1.13.1 does NOT exhibit this issue, both running ONLYOFFICE module 3.0.0 and using same ONLYOFFICE server.
I've tried with older ONLYOFFICE install and the latest. This seems to be only associated with the Humhub Beta 1.15-0-beta.1.

**Here is the web console while loading:**
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. browse
INS: content-ads.js loaded:  https://hub.WEBSITE.org/s/kss/cfiles/browse content-scripts.js:1:108429
TSS: content-tss.js loaded:  https://hub.WEBSITE.org/s/kss/cfiles/browse content-scripts.js:1:118223
INS: content-blocked-items.js loaded:  https://hub.WEBSITE.org/s/kss/cfiles/browse content-scripts.js:1:138261
GET TAB ID RESPONSE:  
Object { tabId: 45 }
content-scripts.js:1:119759
TSS: excluded result:  
Object { excluded: false }
content-scripts.js:1:128944
TSS: hosted page injected browse:4:21
InstallTrigger is deprecated and will be removed in the future. browse:111:16
TSS: caught notification permission request browse:87:25
TSS: Checking if repeated 2 times for interval 5000 against data:  
Object { lastTime: 1693369307450, lastCount: 1 }
browse:43:51
The Notification permission may only be requested from inside a short running user-generated event handler. browse
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://onlyoffice.WEBSITE.com/web-apps/apps/api/documents/api.js?v=1.15.0-beta.1 humhub-app.js:1:80248
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ humhub-app.js:1:78636
Feature Policy: Skipping unsupported feature name “autoplay”. api.js:1023:15
Feature Policy: Skipping unsupported feature name “clipboard-write”. api.js:1023:15
Feature Policy: Skipping unsupported feature name “autoplay”. api.js:519:51
Feature Policy: Skipping unsupported feature name “clipboard-write”. api.js:519:51
Partitioned cookie or storage access was provided to “https://onlyoffice.WEBSITE.com/7.4.1-36/web-apps/apps/documenteditor/main/index.html?_dc=7.4.1-36&lang=en-US&customer=ONLYOFFICE&frameEditorId=iframeContainer&mode=view&parentOrigin=https://hub.WEBSITE.org” because it is loaded in the third-party context and dynamic state partitioning is enabled.

INS: content-ads.js loaded:  https://onlyoffice.WEBSITE.com/7.4.1-36/web-apps/apps/documenteditor/main/index.html?_dc=7.4.1-36&lang=en-US&customer=ONLYOFFICE&frameEditorId=iframeContainer&mode=view&parentOrigin=https://hub.WEBSITE.org content-scripts.js:1:108429
TSS: content-tss.js loaded:  https://onlyoffice.WEBSITE.com/7.4.1-36/web-apps/apps/documenteditor/main/index.html?_dc=7.4.1-36&lang=en-US&customer=ONLYOFFICE&frameEditorId=iframeContainer&mode=view&parentOrigin=https://hub.WEBSITE.org content-scripts.js:1:118223
INS: content-blocked-items.js loaded:  https://onlyoffice.WEBSITE.com/7.4.1-36/web-apps/apps/documenteditor/main/index.html?_dc=7.4.1-36&lang=en-US&customer=ONLYOFFICE&frameEditorId=iframeContainer&mode=view&parentOrigin=https://hub.WEBSITE.org content-scripts.js:1:138261
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. index.html
GET TAB ID RESPONSE:  
Object { tabId: 45 }
content-scripts.js:1:119759
TSS: excluded result:  
Object { excluded: false }
content-scripts.js:1:128944
TSS: hosted page injected index.html:4:21
InstallTrigger is deprecated and will be removed in the future. index.html:111:16
Obsolete: The 'chat' parameter of the 'customization' section is deprecated. Please use 'chat' parameter in the permissions instead.

When trying to view docx, no errors in log. When trying to edit docx, this error:

Error  Tue, 29 Aug 2023 22:42:35 -0600  Error
Error: Cannot pass parameter 3 by reference in /var/www/humhub/protected/modules/onlyoffice/Module.php:409
Stack trace:
#0 /var/www/humhub/protected/modules/onlyoffice/controllers/BackendController.php(53): humhub\modules\onlyoffice\Module->readHash()
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(176): humhub\modules\onlyoffice\controllers\BackendController->beforeAction()
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#5 /var/www/humhub/index.php(25): yii\base\Application->run()
#6 {main}

Previous related issue: https://github.com/humhub/humhub/issues/6497

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0-beta.1
| PHP version      |  7.4.33
| Operating system | Linux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
Should be reporting to OnlyOffice as it seems to be on their end

https://github.com/ONLYOFFICE/onlyoffice-humhub

Also from 1.15+ PHP version 7.4 or older will not be supported, use 8.0+

**Comment by WizWareTech** [comment]
Is this true even though the ONLYOFFICE module 3.0.0 works without any issue on 1.13, but this issue only exists on 1.15 beta?

**Comment by lonesomewalker** [comment]
I suggest to rethink about the usage from onlyoffice.
We currently had to tell one of our customers that he can't use it, since main development is done in Russia, also problematic in case of true open source...

**Comment by luke-** [comment]
Please create a issue here: https://github.com/ONLYOFFICE/onlyoffice-humhub

**Comment by lonesomewalker** [comment]
Nah, this is NOT an OO-issue, this is a humhub issue...

**Comment by ArchBlood** [comment]
> Nah, this is NOT an OO-issue, this is a humhub issue... 

No, I can definitely say this is due to the OO module and not HumHub, the issue is the JWT decode process when `readHash` is called.

https://github.com/ONLYOFFICE/onlyoffice-humhub/blob/master/controllers/BackendController.php#L53-L56
