### ISSUE TITLE
Registration not possible with SSO and email invites if "New users can register" is disabled (Humhub 1.15.0-beta.1)

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6544]
### What steps will reproduce the problem?

Add a module to login with an SSO (Keycloak, Google, etc).

In Admin -> Users -> Settings, untick "New users can register" and tick "Members can invite external users by email".

Invite a non registered user by email.

When the user opens the invitation, instead of creating his account with username/password, he clicks on the SSO button and login to the SSO.

### What is the expected result?

Returning on Humhub registration form.

### What do you get instead?

An error message: "You're not registered.".

### Additional info

Invite by link works throw an SSO.

I'm preparing a PR to fix this bug.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0-beta.1

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6545

This PR gets the email returned by the SSO after login to find the related invite token.

**Comment by luke-** [comment]
@yurabakhtin Can you please review?

**Comment by yurabakhtin** [comment]
@luke- I have tested it, yes the PR fixes the issue, but probably it should be merged into the `master` branch because it is a bug.

**Comment by luke-** [comment]
@yurabakhtin Thanks. Yes, you're right, but `develop` is also fine for this bug.
