### ISSUE TITLE
Humhub 1.14.3 - Module widget crash when clicking on the "Not installed" tab

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6557]
### What steps will reproduce the problem?

Go to "Administration" -> "Modules" -> "Not installed" tab.

### What is the expected result?

View the not installed modules

### What do you get instead?

See https://community.humhub.com/content/perma?id=271074 (personally I cannot reproduce the bug)

### Additional info

@yurabakhtin  I think the problem is here: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/admin/widgets/Modules.php#L45

Maybe we should replace `public $groups;` with `public $groups = [];`?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.3

**Comment by yurabakhtin** [comment]
@luke- @marc-farre Fixed in PR https://github.com/humhub/humhub/pull/6560.
I could reproduce the error with disabled module "Marketplace".
