### ISSUE TITLE
Space logos got lost on update

### ISSUE THREAD

**Issue by brecke** [humhub/humhub#656]
Hi there guys,

I just updated fom 0.10.0rc1 to 0.10.0 on my own server according to instructions and the space logos got lost, all of them. Is there an easy way to get them back? 

Hopefully this will be fixed in the future to avoid the situation altogether.

**Comment by luke-** [comment]
Maybe you missed this point. 

Restore from backup:
- /path/to/humhub/uploads/profile_image

https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/updating.md

**Comment by brecke** [comment]
Yes I did, I'm sorry :-( Thanks.
