### ISSUE TITLE
Date grouping in Messenger (minor bug)

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#6589]
### What steps will reproduce the problem?
create a new conversation
Send the first message
Edit the message 
Send the  message

### What is the expected result?
The message should be displayed in the existing "TODAY" group

### What do you get instead?
Instead A new "TODAY" group is added and the edited message is displayed in this added group.
 
![image](https://github.com/humhub/humhub/assets/91057837/9aca99a0-81b2-4f4a-bbd6-8afa32a6453f)

### Additional info
You need to refresh the page to get only one single "TODAY" group

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/mail/pull/354.
