### ISSUE TITLE
Support more caching engines

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#659]
add the enabling memcached from admin panel. Without memcached, the site work slow. In my site im use memchached, otherwise site use more ram of apache2, and mysql cpu... I recommend to use the memcached for all... This saves to you 40-50 percent of server resources... The APC, File cache, or db cache = bullshit... Use only memcached!

**Comment by mrluisiko99** [comment]
+1

**Comment by sandipp** [comment]
Redis beats Memcached

**Comment by bastrian** [comment]
Not every Shared Hoster supports memcache, so it should remain a Option.

**Comment by radiolip** [comment]
Not every Shared Hoster supports APC and dbcache, but the humhub have the option in admin panel, why no add support for cmemcache!?

**Comment by Stranikevg** [comment]
+1

**Comment by simdol** [comment]
I am surprised that there are still no updates to this -- I am interested on the redis cache support as others have mentioned above. APC or file cache seems too slow and I am in need of speeding up the site as much as possible and decrease the server load.

Please consider adding redis cache as caching mechanism.

**Comment by luke-** [comment]
@simdol You can already add redis cache via configuration file. We support all Yii2 Caching Engines...

http://www.yiiframework.com/doc-2.0/guide-caching-data.html#supported-cache-storage

**Comment by simdol** [comment]
@luke- Thank you for letting me know. The documentation was not clear enough for me to know that the framework itself supported that feature. Perhaps, in the future, it might be good idea to document this into official humhub documentation?

**Comment by hexblot** [comment]
After losing a whole afternoon because of the lack of proper documentation, here's what to do to (finally!) get Redis working with HumHub:

1. Edit your `protected/config/common.php` file
2. In the `return` array, add a `components` key with `redis`, `cache` subkeys like so:

>     return [
>        'components' => [
>           'redis' => [
>                'class' => 'yii\redis\Connection',
>                'hostname' => 'localhost',
>                'port'    => 6379,
>                'database' => 0,
>           ],
>           'cache' => [
>               'class' => 'yii\redis\Cache',
>           ],
>          // Add other components here
>      ],
> ];

If you already have a `components` key, just add the `redis` and `cache` key along with the other stuff.

**Fair warning:** Even though you've just enabled redis and it is working (as shown by using `MONITOR` in `redis-cli`), the UI will display "No Caching" -- apparently, that's normal.

Hope this prevents further hair pulling from other users!

**Comment by simdol** [comment]
@hexblot Thank you very much for your input. I needed this as I had trouble comprehending the Yii framework documentation.

**Comment by zzplab** [comment]
+1 Adding Xcache option

**Comment by xr09** [comment]
@hexblot Same here, but I've managed to save sessions also on redis.

In protected/confif/web.php

      'components' => [
        'session' => [
            'class' => 'yii\redis\Session',
            'redis' => [
                'hostname' => 'localhost',
                'port' => 6379,
                'database' => 0,
            ],
        ],

        'cache' => [
            'class' => 'yii\redis\Cache',
            'redis' => [
                'hostname' => 'localhost',
                'port' => 6379,
                'database' => 1,
            ],
        ],
     ]

By not using a single redis component you can have separate db for cache and sessions.

Show db contents:

    redis-cli -n 0 keys "*" 
    redis-cli -n 1 keys "*"


You must also comment the sessionTable property in "protected/humhub/config/web.php"

    'session' => [
            'class' => 'humhub\modules\user\components\Session',
            // 'sessionTable' => 'user_http_session',
        ],

**Comment by acs-ferreira** [comment]
I can't manage Sessions to work with Redis...

@xr09 my `web.php` file is empty, but when i try to configure `components` to use redis sessions, in latest `master`:

```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: yii\redis\Session::sessionTable
```

**Comment by ShalokShalom** [comment]
TiDB might be also helpful: https://github.com/pingcap/tidb

**Comment by BeZazz** [comment]
> After losing a whole afternoon because of the lack of proper documentation, here's what to do to (finally!) get Redis working with HumHub:
> 
>     1. From your humhub root directory, run `composer require yiisoft/yii2-redis`
> 
>     2. Edit your `protected/config/common.php` file
> 
>     3. In the `return` array, add a `components` key with `redis`, `cache` subkeys like so:
> 
> 
> > ```
> > return [
> >    'components' => [
> >       'redis' => [
> >            'class' => 'yii\redis\Connection',
> >            'hostname' => 'localhost',
> >            'port'    => 6379,
> >            'database' => 0,
> >       ],
> >       'cache' => [
> >           'class' => 'yii\redis\Cache',
> >       ],
> >      // Add other components here
> >  ],
> > ```
> > ];
> 
> If you already have a `components` key, just add the `redis` and `cache` key along with the other stuff.
> 
> **Fair warning:** Even though you've just enabled redis and it is working (as shown by using `MONITOR` in `redis-cli`), the UI will display "No Caching" -- apparently, that's normal.
> 
> Hope this prevents further hair pulling from other users!

Thank  you so much :)
Shame the documents do not contain the full explanation.

**Comment by volomike** [comment]
> 1. From your humhub root directory, run `composer require yiisoft/yii2-redis`

That just installs the extension. What installs the Redis service daemon so that it's listening on TCP port 6379?

**Comment by ArchBlood** [comment]
> > 1. From your humhub root directory, run `composer require yiisoft/yii2-redis`
> 
> That just installs the extension. What installs the Redis service daemon so that it's listening on TCP port 6379?

https://docs.humhub.org/docs/admin/performance/#application-caching
