### ISSUE TITLE
SVG file creates warning each time the space is accessed

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#6595]
### What steps will reproduce the problem?
1. Attach a svg file to a post.
1. Navigate to  the space / user containing this post.
2. Check Information -> Logging

### What is the expected result?
Either convert/show the svg correctly or ignore it, but don't spam the log on each space access.

### What do you get instead?
```
Could not convert file with id 12225. Error: Unable to open image /var/www/[redacted]/html/uploads/file/6/2/62929677-c833-4061-bc19-abd3e816211c/file
```

### Additional info

Sample file: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/cartman.svg
SVG support was initially introduced in https://github.com/humhub/humhub/issues/1714 but I guess this just enabled uploading not handling it in any meaningful way.

| Q                | A
| ---------------- | ---
| HumHub version   |  1.14.4
| PHP version      | 8.0.20
| Operating system |  CentOS 8 Stream

Edit: Fixed PHP version, that was previously from my local machine.

**Comment by ArchBlood** [comment]
I don't believe the uploader for posts can convert svg files currently.

**Comment by yurabakhtin** [comment]
@luke- @dreua I could not reproduce the error on conveting `svg` file, I see it is converted to `png` on my test local server, I have these PHP extenssions:

![php-test](https://github.com/humhub/humhub/assets/6995524/cb6d8bf9-2c21-46cc-8e68-9f82aac4398b)

But I have detected the mime type is defined from extenssion, so in my case the file is really `png` after converting, but the image is tried to be displayed as `svg` with mimetype `image/svg_xml`, and the image is not viewable as expected:

![before_fix](https://github.com/humhub/humhub/assets/6995524/7945dd2d-2359-4c17-b185-b3257a9c84ca)

I have fixed to get a mimetype from a file, now it works like this after PR https://github.com/humhub/humhub/pull/6599:

![after_fix](https://github.com/humhub/humhub/assets/6995524/e1f525b7-f588-499f-b920-dce169635ab5)
