### ISSUE TITLE
Uploaded files with non standard ASCII characters are renamed & cannot be deleted.

### ISSUE THREAD

**Issue by santiagoti** [humhub/humhub#660]
## Installation Environment
HumHub Online Demo

## Description
1. When a file with Chinese characters or Spanish accents (I suppose that it will also happen with any non ASCII character) is attached to a comment or post, the non ASCII characters are trimmed from the file name:
![humhub](https://cloud.githubusercontent.com/assets/7720638/5957571/27a7d2de-a7f6-11e4-844d-3bfd2ca04f62.png)

2. Additionally, posts and comments with these uploaded files cannot be deleted.

## How to Reproduce
1. Attach a file with non ASCII characters to a comment or post (For example, a file with a Chinese or Spanish accent)
2. The names used in my test are: [Spanish ú.pak] & [中文.pak]

## Notes
Thank you for your hard work and for creating such a great platform.

**Comment by mrluisiko99** [comment]
+1

**Comment by Vatarus** [comment]
+1
