### ISSUE TITLE
Add Standard Basque language (code: eu)

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6607]
@luke- is it possible to add Standard Basque language (code: eu) to Humhub?

See https://en.wikipedia.org/wiki/Standard_Basque

If yes, then a native Basque person will do the translations directly on https://translate.humhub.org/

Thanks!

**Comment by luke-** [comment]
Yes, I'll create a PR soon.
https://en.wikipedia.org/wiki/Basque_language
