### ISSUE TITLE
Same space is displayed 2 times in "My spaces" menu

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#6613]
**HH 1.15 last beta version**
The main space of our site  is public, all site members are members of this space.
It is displayed 2 times in the "my spaces" dropdown menu .
The 2 items are routing to the same space
![image](https://github.com/humhub/humhub/assets/91057837/554da28a-7c70-4091-b10b-0e5a8a9ef308)
Is it a bug or a wrong setting?

**Edit:** This behaviour depends on the users. Only 1 time for some users, 2 times for some others

**Comment by Gilbertdelyon** [comment]
please also notice that in "**My Profile** " page i am member of 4 spaces (this is wrong),
but when I click on the "**4 spaces**" item, only 3 are displayed (this is right)
![image](https://github.com/humhub/humhub/assets/91057837/bea97b36-3065-4cc2-8098-44090861a6fb)

**Comment by felixhahnweilheim** [comment]
Do you have any custom modules that could cause this?
I don't know this issue but maybe running an integrity check could help: https://docs.humhub.org/docs/admin/troubleshooting#data-integrity

**Comment by Gilbertdelyon** [comment]
This is the result of integity check. 
It looks good, but the issue is still there
![image](https://github.com/humhub/humhub/assets/91057837/60cb87c6-e3d4-4b21-83f4-fb6c6e95ce2a)

**Comment by Bruno-du-Vexin** [comment]
To complete: when someone registers, this is done twice.
![image](https://github.com/humhub/humhub/assets/144030866/72937739-2223-4134-8270-62a104997b5b)

**Comment by ArchBlood** [comment]
Do you have a custom module installed or customized core space module?

**Comment by Bruno-du-Vexin** [comment]
No.

**Comment by Bruno-du-Vexin** [comment]
I just updated to version: 1.15.0-beta.1

**Comment by Gilbertdelyon** [comment]
@Bruno-du-Vexin 

Did you try flushing the cache (how to: [here](https://docs.humhub.org/docs/admin/console/) - you have to open the terminal in your server)

Today [this issue](https://github.com/humhub/humhub/issues/6613#issuecomment-1764088852) has diasappeared,
but [this one](https://github.com/humhub/humhub/issues/6613#issue-1943523586) is remaining

**Comment by Bruno-du-Vexin** [comment]
_Did you try flushing the cache (how to: [here](https://docs.humhub.org/docs/admin/console/) - you have to open the terminal in your server)_ : I did it

**Comment by Gilbertdelyon** [comment]
This issue was probably the result of some undue upgrade/downgrade/upgrade... between the last stable version and the new beta version. 
After deleting some duplicates in the `space_membership` table theere are no more duplicate spaces in the "My Spaces" menu item.
So far so good
Sorry for the distrurbance

**Comment by felixhahnweilheim** [comment]
'space_id,user_id' should be Primary Key in  space_membership table. So duplicate entries actually should not be possible.

**Comment by Bruno-du-Vexin** [comment]
and yet it happened
![image](https://github.com/humhub/humhub/assets/144030866/c6051daa-fa48-4e11-aa1b-34d39a45847c)

**Comment by felixhahnweilheim** [comment]
Did you really check the primary key?

(I had such an issue once with WordPress (after manual migration) and it was a nightmare. So it should be corrected as soon as possible.)

**Comment by Bruno-du-Vexin** [comment]
How do I check the primary key please?

**Comment by felixhahnweilheim** [comment]
Actually I overlooked an update.It should be like this:

![Screenshot_20231019_113628_Chrome.jpg](https://github.com/humhub/humhub/assets/84990763/b0556c1a-d7a3-4de0-ae0e-8dae037a9c70)


in PHPMyAdmin open the table and then the Structure tab.

**Comment by Bruno-du-Vexin** [comment]
_in PHPMyAdmin open the table and then the Structure tab._

**Comment by Bruno-du-Vexin** [comment]
in PHPMyAdmin open the table and then the Structure tab.
Yan I did this...and after ?
