### ISSUE TITLE
Spaces sort order "Alphabetical" == "Sort Order"

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#6623]
**context:**
HH1.15 beta 2
 New feature: spaces "Sort Order",
 
**Issue:**
 In **admin/setting/appearence** you can select "Dropdown space order" = "Alphabetical" or "Last visit"
 If you select "Alphabetical" spaces are **not alphabetically ordered**, but "Sort Oder" ordered

This the setting page
![image](https://github.com/humhub/humhub/assets/91057837/db2d83a8-e77d-4d19-820e-c225d75d4d48)
 And this is the result
 
![image](https://github.com/humhub/humhub/assets/91057837/de921048-172d-4dcd-97c7-d794e56328e9)

not a major issue, but it's confusing

**Comment by luke-** [comment]
Maybe we should add a hint e.g. "A manual sort is always applied first."?
@marc-farre What do you think?

**Comment by marc-farre** [comment]
@luke- yes, good idea.
PR https://github.com/humhub/humhub/pull/6624
![image](https://github.com/humhub/humhub/assets/23310825/d6f72298-5634-4ce9-90a3-af79a2a09ebb)

**Comment by Gilbertdelyon** [comment]
Good idea. Thank you.
My 2 cents:
In my mind "manual sort" doesn't refer to something concrete.
I would prefer:
Space "Sort Order" is always applied first when space sort order has been configured in space settings
This was olnly my 2 cents. I let you decide !

**Comment by Gilbertdelyon** [comment]
Or another idea, may be less confusing
- Replace "Alphabetical" by "Sort Order"
- And hint:
**Spaces without  (or with same) "Sort Order" setting will be alpabetically ordered.**

**Comment by luke-** [comment]
@Semir1212 Can you please take a look into the wording here?

**Comment by Semir1212** [comment]
@luke @marc-farre @Gilbertdelyon How about this:

Dropdown Sort Order --> 'My Spaces' Sorting
Alphabetical --> Custom Sort Order
Hint: Custom sort order will be used (Space settings). If no custom values are defined, alphabetical sorting will be applied.

**Comment by marc-farre** [comment]
Thanks @Semir1212 .
Preview: 
![image](https://github.com/humhub/humhub/assets/23310825/a55ea2e8-ab5e-4997-af0d-5c6b13971339)

I think it's not totally right, because the hint is about the 2 options, but in reality the custom sort order doesn't apply in case of "Last visit" option selected.

So what do you think about this alternative?
![image](https://github.com/humhub/humhub/assets/23310825/ab07da61-662c-47a8-a1c9-70a46e60e809)
![image](https://github.com/humhub/humhub/assets/23310825/b5b1569f-a0a7-4fff-b3d7-0cf562df2ef7)

**Comment by Gilbertdelyon** [comment]
@marc-farre 
In my mind that's perfect!

**Comment by Semir1212** [comment]
Looks good @marc-farre

**Comment by marc-farre** [comment]
@luke- Done in commit https://github.com/humhub/humhub/pull/6624/commits/a1e01bed6ad5f79d3501f7ff95b826dcf17ca066

**Comment by luke-** [comment]
@marc-farre Thank you for the improvement. The new translations are also available on the translation site.

**Comment by marc-farre** [comment]
@luke- French translations done.
