### ISSUE TITLE
Date is invalid

### ISSUE THREAD

**Issue by Draky50110** [humhub/humhub#6649]
Hello.

Just installed HumHub 1.15 and set some settings and then when going to dashboard, HH asks me, as first user, to fill profile info.

When I try to enter the birthdate, it tells me "The format of birthday is invalid".

I can access admin with direct URL (r?admin) and I can edit the profile directly, even add a birthdate but when going back to dashboard, it asks to fill in and validating gives the error message.

I was older issues closed but here it is again...

Any idea ?

**Comment by luke-** [comment]
@Draky50110 Can you please provide a screenshot and the used locale?

**Comment by Draky50110** [comment]
Locale is French but switched to English (US) and the problem is still here.

![humhub-french](https://github.com/humhub/humhub/assets/1558487/1efccc0f-4f40-4fb5-991e-3eb3a58a42bc)
![humhub-english](https://github.com/humhub/humhub/assets/1558487/1c054cb4-0b83-46ab-bbb9-f1dfb6dbad6c)

**Comment by yurabakhtin** [comment]
@Draky50110 Thank you for the report.
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6651.

**Comment by Draky50110** [comment]
This problem ix fixed but got another so will open a new issue.
