### ISSUE TITLE
Add assets GZIP compression with Apache

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6650]
### Is your feature request related to a problem? Please describe.

Without compression, a Humhub page loads for about 4,5 Mb of files.
With Apache compression, it's reduced to 2,5 Mb.

E.g. the `humhub-bundle.js` is 1,5 Mb. When sent with Apache GZIP compression, it's only 455 Kb.

### Describe the solution you'd like

Add this to the `.htaccess` file:
```
# GZIP compression for text files: HTML, CSS, JS, Text, XML, fonts
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE application/javascript
  AddOutputFilterByType DEFLATE application/rss+xml
  AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
  AddOutputFilterByType DEFLATE application/x-font
  AddOutputFilterByType DEFLATE application/x-font-opentype
  AddOutputFilterByType DEFLATE application/x-font-otf
  AddOutputFilterByType DEFLATE application/x-font-truetype
  AddOutputFilterByType DEFLATE application/x-font-ttf
  AddOutputFilterByType DEFLATE application/x-javascript
  AddOutputFilterByType DEFLATE application/xhtml+xml
  AddOutputFilterByType DEFLATE application/xml
  AddOutputFilterByType DEFLATE font/opentype
  AddOutputFilterByType DEFLATE font/otf
  AddOutputFilterByType DEFLATE font/ttf
  AddOutputFilterByType DEFLATE image/svg+xml
  AddOutputFilterByType DEFLATE image/x-icon
  AddOutputFilterByType DEFLATE text/css
  AddOutputFilterByType DEFLATE text/html
  AddOutputFilterByType DEFLATE text/javascript
  AddOutputFilterByType DEFLATE text/plain
  AddOutputFilterByType DEFLATE text/xml
</IfModule>
```

**Comment by marc-farre** [comment]
@luke- if you think it's a good idea, I can send a PR.
But I'm not an Apache expert.
This solution works well for me, but I don't know if it's the best practice nowadays.

**Comment by ArchBlood** [comment]
You should attach gzip to event handlers on Response, instead of doing this in the `.htaccess`.

**Comment by marc-farre** [comment]
> You should attach gzip to event handlers on Response, instead of doing this in the `.htaccess`.

@ArchBlood Thanks. I've founded this about your recommendation: https://stackoverflow.com/a/36705085

However, I've had a look to other Humhub instances I manage and files are already compressed!
The difference is the server, but I didn't add any extra code on the instances where compression works.

@luke- Do you know what to do to have gzip compression on assets?
- Do you want me to add something about it on https://docs.humhub.org/ (I didn't find anything)?
- Maybe we could add a check in Administration -> Information -> Prerequisistes?

**Comment by luke-** [comment]
@marc-farre It would probably be best, at least for the time being, to include notes and sample configurations in our wiki: https://community.humhub.com/s/installation-and-setup/wiki/Performance+and+scaling

With our cloud hosting, for example, compression is handled by the front-end proxy (NGINX).

Apart from that, we should perhaps include compression in the ".htaccess" or NGINX example configuration.

**Comment by ArchBlood** [comment]
> > You should attach gzip to event handlers on Response, instead of doing this in the `.htaccess`.
> 
> @ArchBlood Thanks. I've founded this about your recommendation: https://stackoverflow.com/a/36705085
> 
> However, I've had a look to other Humhub instances I manage and files are already compressed! The difference is the server, but I didn't add any extra code on the instances where compression works.
> 
> @luke- Do you know what to do to have gzip compression on assets?
> 
> * Do you want me to add something about it on https://docs.humhub.org/ (I didn't find anything)?
> * Maybe we could add a check in Administration -> Information -> Prerequisites?

Personally the event handler is the best option here with a check to make sure that `gzencode, gzcompress, gzfile, ob_gzhandler, Phar::compress` are all installed, and requires less work.
- https://www.yiiframework.com/wiki/39/enabling-gzip

### GZip Extensions Check
```php
        // Checks GZip Extensions
        $title = 'PHP - ' . Yii::t('AdminModule.information', '{phpExtension} Extension', ['phpExtension' => 'GZip']);
        if (class_exists('gzencode' && 'gzcompress' && 'gzfile' && 'ob_gzhandler' && 'Phar::compress')) {
            $checks[] = [
                'title' => $title,
                'state' => 'OK'
            ];
        } else {
            $checks[] = [
                'title' => $title,
                'state' => 'ERROR',
                'hint' => Yii::t('AdminModule.information', 'Install {phpExtension} Extension', ['phpExtension' => 'PHP GZip'])
            ];
        }
```
If any of the gzip extensions aren't installed then GZip would be counterproductive if this were implemented anyway.

**Comment by luke-** [comment]
@ArchBlood Thanks for the example. All files from the `/static/` or `/assets` directory are not delivered by PHP or the HumHub application, but instead directly from the web server. Therefore, the webserver should also take over the transfer including compression.

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6654

@ArchBlood 
> check to make sure that `gzencode, gzcompress, gzfile, ob_gzhandler, Phar::compress` are all installed

This is done in `.htaccess` with `<IfModule mod_deflate.c>`

**Comment by luke-** [comment]
@marc-farre Thanks!
