### ISSUE TITLE
Can"t close welcome page after filling profile

### ISSUE THREAD

**Issue by Draky50110** [humhub/humhub#6652]
Hello.

Following the fix of #6649 , I tried to fill the profile page, I choose "save and lose" button but the profile page does not close, without giving error message.

It just refresh "close and reopen" immediately.

**Comment by ArchBlood** [comment]
Also happens with the modal for license keys, create a key from the partner site for a free module then enter and register the key, after this the "X" stops working till refreshed.

**Comment by yurabakhtin** [comment]
> Hello.
> 
> Following the fix of #6649 , I tried to fill the profile page, I choose "save and lose" button but the profile page does not close, without giving error message.
> 
> It just refresh "close and reopen" immediately.

@Draky50110 Thanks again!

@luke- I could reproduce the issue only when for example some profile field is required but it is not displayed on the welcome profile form page, so I have fixed to update only the fields what are visible on the welcome page.
PR https://github.com/humhub/humhub/pull/6655.
I have also detected the field Tags were not updated and fixed this in the same PR as well.

**Comment by yurabakhtin** [comment]
> Also happens with the modal for license keys, create a key from the partner site for a free module then enter and register the key, after this the "X" stops working till refreshed.

@ArchBlood It seems this issue is not related. Do you tell about Administration - Modules? Can you show a screenshot or url where to test this? Thanks.

**Comment by Draky50110** [comment]
I confirm the fix is working.
Thanks.
