### ISSUE TITLE
Remove "Space" word from the title of space's widgets

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6664]
### Is your feature request related to a problem? Please describe.

When we are in a space, we know that everything here is related to the current space.
So we don't need to mention that widgets refers to a space.

### Describe the solution you'd like

Replace:
![image](https://github.com/humhub/humhub/assets/23310825/8c8fdd26-7686-433e-82ae-b0d72460fdcd)

With:
![image](https://github.com/humhub/humhub/assets/23310825/7033cfdc-ce89-4e08-b67e-5a351280ee2c)

**Comment by marc-farre** [comment]
@luke- if you agree with it, I'll send a PR for the `Members`, `SpaceFollowers` and `SpaceTags` widgets.

**Comment by ArchBlood** [comment]
Seems related to #4455

**Comment by luke-** [comment]
@marc-farre I'm not sure about this. Currently we always use this style "**Some** Title", with the bold first word.

@Eladnarlea Let's discuss this

**Comment by Eladnarlea** [comment]
@luke- since we're already in the process of rethinking the typography rules, especially the semi-bold letters, I'd say this can wait until the upcoming general changes. What do you think?

**Comment by marc-farre** [comment]
+1 to remove HTML tags in translations.
If we choose not to have 2 font weights in the same text, the `<strong>` tag should be completely removed as we can have `.panel-header {font-weight: bold;}` in the theme.

**Comment by luke-** [comment]
We should definitely find a new style of typography here in the future. 
But until then, I would prefer to keep it that way. So I would close...
