### ISSUE TITLE
JQuery 3.7+ - Dropdown menus not working after a global modal box AND a confirmation modal box have been opened

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6666]
### What steps will reproduce the problem?

The bug occurs when the confirm modal box is opened after (or before) a global modal box.

Example:

1. Go on a space having an image.
2. ![image](https://github.com/humhub/humhub/assets/23310825/3c76bb8c-4571-4d44-b854-fc8e6d3eee04)
3. ![image](https://github.com/humhub/humhub/assets/23310825/9af6dd77-4d99-4651-bc71-086ecc613712)
4. ![image](https://github.com/humhub/humhub/assets/23310825/fa80d1c8-81c0-4fb3-80e9-e00ee4e49768)
5. ![image](https://github.com/humhub/humhub/assets/23310825/74e1d5d3-8bda-4e1e-afdd-b932c71eb40b)
6. ![image](https://github.com/humhub/humhub/assets/23310825/bb4852d0-2d04-4a14-a84f-bad48a1dce80)

### What is the expected result?

On step 6, when clicking, you should have the dropdown menu.

### What do you get instead?

The menu doesn't open.

### Additional info

Console error:
![image](https://github.com/humhub/humhub/assets/23310825/aa55e66b-ea98-40c2-b1a8-b882fbed0b06)

Tested with a fresh Humhub install without module, the bug is still present, so it must be in the core code.

Could explain this bug: https://community.humhub.com/content/perma?id=272861
If not, we should create and issue on Only Office module repository.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0

**Comment by yurabakhtin** [comment]
@luke- I have compared HumHub versions `1.14` and `1.15` and find a difference in jQuery versions:

- `1.14` - jQuery v3.6.4
- `1.15` - jQuery v3.7.1

So I have decided to do a temp solution is to limit jQuery to version < `3.7.0` - PR https://github.com/humhub/humhub/pull/6672.
I still need to investigate why we have the error on jQuery `3.7.1`, probably something was deprecated.

**Comment by marc-farre** [comment]
@yurabakhtin Thanks!

Yes, the bug comes from the jQuery version.
Tests:
- 3.6.4: works
- 3.7.0: bug

So it's somewhere here: https://github.com/jquery/jquery/compare/3.6.4...3.7.0

Shouldn't we keep this issue open while the bug is not totally identified?
Because if later we forget and switch back to v3.7 we might have the bug again.

**Comment by yurabakhtin** [comment]
@marc-farre 

> Shouldn't we keep this issue open while the bug is not totally identified?
Because if later we forget and switch back to v3.7 we might have the bug again.

Yes, I agree.

@luke- I cannot fix an error in tests https://github.com/humhub/humhub/pull/6672#issuecomment-1825292874 yet.

**Comment by luke-** [comment]
Please reopen if still present.

**Comment by marc-farre** [comment]
@luke- This issue has been solved by @yurabakhtin by downgrading jQuery from version 3.7.0 to 3.6.3.
The problem is that it will come back if we upgrade jQuery library again.
The latest available version is 3.7.1
I tried updating to this v3.7.1 (we previously tested v3.7.0) and the bug still occurs.
So I think we should keep this issue open.

**Comment by luke-** [comment]
@marc-farre I have assigned the issue to you. It might make sense to look at it in the course of the BS5 migration. It may be obsolete by then.

**Comment by marc-farre** [comment]
@luke- @yurabakhtin On `bs5` branch, upgrading to the latest jQuery version (3.7.1) works well.
So I'll set this jQuery version in the `composer.json` of the `bs5` branch, which make it available when we merge it to develop.
