### ISSUE TITLE
Option to disable "show x more" button if needed

### ISSUE THREAD

**Issue by liloumuloup** [humhub/humhub#6670]
### Is your feature request related to a problem? Please describe.
Since the last update, some of the users of my Humhub instance have found that there is a new functionnality that collapses events and polls and shows a button "show x more" : 
![image](https://github.com/humhub/humhub/assets/4968531/4633edd1-2276-465a-8f47-edf9929d52d4)
This is a problem for my users because a lot of them don't see it and then missed some information related to this.

### Describe the solution you'd like
As i couldn't find a way to disable this, maybe add and option in "appearance" to disable this ?

### Describe alternatives you've considered
At this moment, i warned them but it's not really efficient, as some of them still miss the button.

**Comment by felixhahnweilheim** [comment]
You can set this for specific content types via file configuration: 'streamSuppressQueryIgnore'
see https://docs.humhub.org/docs/admin/config-options#stream

You can also set 'streamSuppressLimit' to a higher number (for all content types). (Not sure why it is not mentioned in the docs.)
For all available options see
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/stream/Module.php

**Comment by liloumuloup** [comment]
Hi ! Thank you for your answer. 

That was not very clear on how to it so i added this in the file `protected/config/web.php` based on this doc https://docs.humhub.org/docs/admin/advanced-configuration : 
```php
return [
    'modules' => [
        'stream' => [
            'streamSuppressLimit' => 150
        ]
    ]
];
```

Am i right ?

N.B. : the links of Humhum doc at the top of this file lead to a 404 error.
