### ISSUE TITLE
On the space invitation by link page, the language chooser doesn't save the selected language

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6679]
### What steps will reproduce the problem?

1. In a space, get an "Invite by link" URL
2. Open the page to register
3. Change language in the language chooser at the bottom of the page

### What is the expected result?

The page reloads with the selected language.

### What do you get instead?

The page reloads with the previous language.

### Additional info

This is because the language is forced from the owner's space language: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/services/LinkRegistrationService.php#L68C71-L68C71

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0

**Comment by marc-farre** [comment]
@luke- I can send a PR, but I have 2 options:

1/ Remove this line: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/services/LinkRegistrationService.php#L68C71-L68C71

2/ Replace it with:
```php
if (Yii::$app->request->post('ChooseLanguage') === null) {
                Yii::$app->setLanguage($this->space->ownerUser->language);
            }
```

I think we should choose option 1, because this behavior is difficult to understand and may cause problems if an admin creates spaces for different countries.
And option 2 is not a very pretty solution...

**Comment by luke-** [comment]
@marc-farre The current situation here is really not optimal. I think solution 1.) is also the best. Either the default language of the system or new users can choose.

**Comment by marc-farre** [comment]
@luke- PR on Master branch: https://github.com/humhub/humhub/pull/6680
