### ISSUE TITLE
Make the container header clickable to return to the container's home

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6686]
### Is your feature request related to a problem? Please describe.

When we want to go back to the Homepage, we instinctively click on the logo.
In a container (Space or User), clicking on it displays it in full screen.

But we could make the rest of the banner clickable.

### Describe the solution you'd like

When clicking here we go back to the container's homepage:
![image](https://github.com/humhub/humhub/assets/23310825/c5f2c86b-f502-4c81-ad29-44d9de107283)

This should be possible only for non admins, because admins needs to click on it on touch screen to change the banner's logo.
For admins, we could add the link to the container's homepage only the container's name and description text.

### Describe alternatives you've considered

For both admins and non admin, only the text is clickable.

**Comment by marc-farre** [comment]
@luke- if you agree, I can make a PR

**Comment by luke-** [comment]
@marc-farre Perhaps it is better to make only the text clickable, as this could cause problems on mobile devices, for example?

@Eladnarlea What do you think?

**Comment by ArchBlood** [comment]
I believe we should also think of refactoring the whole containerProfileHeader, currently as seen in the Verified module, you can't easily interact within this without view manipulation, and if you have multiple modules or themes doing this then only one will actually take effect.
I'd also like to mention how stressful it is that if you try interacting with the title, such as clicking, the profile banner is interacted with, this isn't optimal.

**Comment by marc-farre** [comment]
@Eladnarlea do you agree if these text become clickable (link to the space home)?
![image](https://github.com/humhub/humhub/assets/23310825/eb51ec46-6967-4e72-803c-137d2f28d207)
Thanks!

**Comment by Eladnarlea** [comment]
@marc-farre we can do that, yes. But only the header, in this case `General Discussion` -right?

**Comment by marc-farre** [comment]
@Eladnarlea Thanks. So the space description (second rectangle on my screenshot) is not clickable.

@luke- PR https://github.com/humhub/humhub/pull/6732
