### ISSUE TITLE
No link on "X now follows Y" on Last Activities

### ISSUE THREAD

**Issue by Lazuis** [humhub/humhub#670]

**Comment by yurabakhtin** [comment]
@luke- Not enough clear task.
Should we display a point for `{user1} now follows {user2}.` on the panel "**Latest** activities" like we already display `{displayName} joined the space {spaceName}` or `{displayName} created a new post.` there?
Or the point is already displayed but it has no some expected link/`<a>`?

**Comment by luke-** [comment]
Yes, it's about the panel  "Latest activities". 

Here is the related Activity class:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/activities/UserFollow.php#L34-L37

Since the activity also implements a method "GetUrl", we can probably close the issue.
Can you trigger such activity and test if you can click on it?

**Comment by yurabakhtin** [comment]
@luke- I triggered such activity(by follow to different users) and I find records are created in db table `activity` with `class`:`humhub\modules\user\activities\UserFollow` and `object_model`:`humhub\modules\user\models\Follow`, but I don't see any activity for such actions in the panel "**Latest** activities".
Is it a bug? Should I try to make it visible in the panel?

**Comment by luke-** [comment]
@yurabakhtin  You do not see any activities of your own. Maybe this is the problem here?

**Comment by yurabakhtin** [comment]
@luke- I tested with 3 different users, it looks like bug and the follow activity is not displayed in the panel at all, it would be good if you will test this too and tell me how it must works correctly, thanks.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/4459

It's working if I manually change the visibility in the database.

I've opend a new ticket here.
