### ISSUE TITLE
Custom theme: reload `@baseTheme` after flushing cache

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6700]
### What steps will reproduce the problem?

1. Create a child custom theme.
2. In Settings -> Appearance, select this theme (must be done before next step to have the problem)
3. in `variables.less`, set the `@baseTheme`, e.g. `@baseTheme: "main-custom-theme";`
4. Flush the cache

### What is the expected result?

The view files of the `main-custom-theme` overwrite the core ones.

### What do you get instead?

The view files of the `main-custom-theme` don't overwrite the core ones.

### Additional info

To solve this problem, you need to change the theme to any other one and change it again to the child custom theme.
Then, overwriting of  `main-custom-theme` views works.

I think that when flushing cache we should also check the @baseTheme, because it's not obvious that we need to change theme to load the new `@baseTheme` in the system.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0

**Comment by yurabakhtin** [comment]
@marc-farre @luke- Fixed in PR https://github.com/humhub/humhub/pull/6701.

**Comment by marc-farre** [comment]
@yurabakhtin thanks for your quick fix!
