### ISSUE TITLE
Regression: Link in summary emails not working with installation directory

### ISSUE THREAD

**Issue by juliuspopp** [humhub/humhub#6702]
### What steps will reproduce the problem?
1. Install Humhub 1.14.3 to a directory, e.g. example.com/cloud
2. Upgrade Humhub to 1.15.0
3. -> In the daily summary email, the links are not working, they link to example.com/s/... or example.com/comment/... instead of example.com/cloud/s/... and example.com/cloud/comment/... respectively

### What is the expected result?
working links that include the installation directory in the URL (as was the case in 1.14.3)

### What do you get instead?
A broken link

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0
| PHP version      | ?
| Operating system | linux x86_64 

#### Tried workaround:
change path to example.com, save
change it back to example.com/cloud, save
did not work

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
Was this uncommented out?
https://github.com/humhub/humhub/blob/master/.htaccess.dist#L7-L8

**Comment by juliuspopp** [comment]
additional information:
I got it working, added redirects via cpanel
also had the code of Humhub's .htaccess copied to the root folder's htaccess file, after removing this the workaround started working
