### ISSUE TITLE
HumHub Pjax customization taints Yii2 Pjax widget

### ISSUE THREAD

**Issue by martin-rueegg** [humhub/humhub#6703]
Yii's `\yii\widgets\Pjax` is not working, since humhub's implementation/overwriting `$.pjax` overwrites the `container` setting.

For more information refer to the discussion on the community forum:
https://community.humhub.com/s/contribution-core-development/?contentId=273226

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14+
| PHP version      | 7.4+
| Operating system |

**Comment by ArchBlood** [comment]
I believe this could help out a little bit when it comes to information about the Pjax class;

https://github.com/humhub/humhub/pull/6277

**Comment by martin-rueegg** [comment]
- https://github.com/humhub/documentation/pull/92

**Comment by martin-rueegg** [comment]
As far as I can tell and I have tested, this is already fixed in 1.15 with
- https://github.com/humhub/humhub/pull/6277
