### ISSUE TITLE
REST Api PUT user/id bug

### ISSUE THREAD

**Issue by denser** [humhub/humhub#6709]
### What steps will reproduce the problem?
i.e. running /user/883 PUT request with body
```
{
    "account": {
        "visibility": 0,
        "status": 1
    }
}
```

Want to change visibility and/or status(enable or disable user) and nothing changes. System response wit code 200 and show user data.

### What is the expected result?
status or visibility attribute changes

### What do you get instead?
status or visibility attribute stay as was

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0
| PHP version     | 8.1.2
| Operating system |ubuntu

**Comment by ArchBlood** [comment]
You should be getting something like this for disabled accounts;
```json
{
  "account": {
    "username": "john.doe",
    "email": "john.doe@example.com",
    "status": 0,
    "tagsField": [
      "Administration",
      "Support",
      "HumHub"
    ],
    "language": "DE",
    "authclient": "local",
    "authclient_id": "0123456789"
  },
  "profile": {
    "firstname": "John",
    "lastname": "Doe",
    "title": "Test user",
    "gender": "male",
    "street": "New Street 5",
    "zip": 80331,
    "city": "Munich",
    "country": "DE (ISO 3166 code)",
    "state": "string",
    "birthday_hide_year": 0,
    "birthday": "1990-01-01",
    "about": "string",
    "phone_private": "string",
    "phone_work": "string",
    "mobile": "string",
    "fax": "string",
    "im_skype": "string",
    "im_xmpp": "string",
    "url": "string",
    "url_facebook": "string",
    "url_linkedin": "string",
    "url_xing": "string",
    "url_youtube": "string",
    "url_vimeo": "string",
    "url_flickr": "string",
    "url_myspace": "string",
    "url_twitter": "string"
  },
  "password": {
    "newPassword": "SuperSecretPassword",
    "mustChangePassword": true
  }
}
```
Also you should report this to the module repo instead of the core platform;
https://github.com/humhub/rest/issues

**Comment by denser** [comment]
Ok. I will cry to module team :)

**Comment by marc-farre** [comment]
Issue transferred to https://github.com/humhub/rest/issues/146
