### ISSUE TITLE
People: Filter by `Online` Status

### ISSUE THREAD

**Issue by 5Chyandour** [humhub/humhub#6712]
Added Functionality Request:  The possibility to show which users are online on the 'people' page and their avatar in posts. With the option to turn the function on and off.
As discussed here: https://community.humhub.com/s/module-development/?contentId=273414&commentId=47120

![Users-on-Line](https://github.com/humhub/humhub/assets/153312570/e4e978a8-0bfa-4765-ac9b-420c6e276e50)
![people-page](https://github.com/humhub/humhub/assets/153312570/511ca46d-5145-4f06-b01e-d54afb634466)

**Comment by marc-farre** [comment]
> Its a bit difficult to implement, as we are working with the cache in terms of online status. @marc-farre Do you see a easy possibility here?

Indeed... It would require refactoring:
- Saving all online user IDs and creation minute in a single cache key (see array example bellow)
- On cron run (every minute), we remove all users added more than 1 minute ago

Array example: if we have 2 online users, one has ID 531 and was added to the array at the minute 42, and the other is 673, minute 43
```php
[
  [531, 42],
  [673, 43]
]
```

Maybe there is a better idea, I don't really like adding this extra cron job every minute...

**Comment by ArchBlood** [comment]
> > Its a bit difficult to implement, as we are working with the cache in terms of online status. @marc-farre Do you see a easy possibility here?
> 
> Indeed... It would require refactoring:
> - Saving all online user IDs and creation minute in a single cache key (see array example bellow)
> - On cron run (every minute), we remove all users added more than 1 minute ago
> 
> Array example: if we have 2 online users, one has ID 531 and was added to the array at the minute 42, and the other is 673, minute 43
> ```php
> [
>   [531, 42],
>   [673, 43]
> ]
> ```
> 
> Maybe there is a better idea, I don't really like adding this extra cron job every minute...

I'm not a fan of making everything run through Cron, this wouldn't be optimal for all, I'd prefer using websocket over this, also would prefer this over polling in general. :thinking:

**Comment by marc-farre** [comment]
@5Chyandour maybe you could close this issue as the https://github.com/001101/humhub-module-onlineusers module seams to work well, as you mentioned it on https://community.humhub.com/s/module-development/?contentId=273414
