### ISSUE TITLE
Error when showing profile details

### ISSUE THREAD

**Issue by yahahey** [humhub/humhub#6715]
### What steps will reproduce the problem?
When clicking on the profile details
<img width="1484" alt="Capture d’écran 2023-12-09 à 22 24 46" src="https://github.com/humhub/humhub/assets/153396309/5e38c296-35d1-425f-8a62-e2a0f9b36fe9">

### What is the expected result?
Profile details

### What do you get instead?
The following error <img width="1765" alt="Capture d’écran 2023-12-09 à 22 24 33" src="https://github.com/humhub/humhub/assets/153396309/2413f16b-f229-4923-bce5-aab1d6e91f24">

### Additional info
It happens only when the birthday is empty

| Q                | A
| ---------------- | ---
| HumHub version   | v1.13.1
| PHP version      |  8.1
| Operating system | Chrome

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
Is fixed in 1.13.2, see last Changelog entry here: https://github.com/humhub/humhub/blob/master/CHANGELOG.md#1132-march-27-2023
