### ISSUE TITLE
Change email settings from DB?

### ISSUE THREAD

**Issue by Xulescu** [humhub/humhub#672]
Hi. Due to some reasons, I can not access the Administration panel. And the email function does not work, so users can not make new accounts because Email is not configured (Administration -> Mailing -> Server Settings) .
Can I configure it manually from PhpMyAdmin database?
I searched around, and I found "systememailaddress" under "settings" table. But after I modify this value with my own Gmail adress, it comes up with an error: CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away. The SQL statement executed was: SELECT `id` FROM `user_http_session` WHERE id=:id. Bound with :id='2979caf5fdb8d43a2278f7ec2c2a632a'

What I have to do? Thank you!

**Comment by luke-** [comment]
You cannot access the whole administration menu?

**Comment by Xulescu** [comment]
Yes. I can not change it from program interface. How to change email from database? Thank you
