### ISSUE TITLE
Allow theme without second topbar menu 

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6725]
### Is your feature request related to a problem? Please describe.

1. Create a theme without `#topbar-second` element, e.g. the [Clean Theme](https://marketplace.humhub.com/module/clean-theme/description).
2. In the console, you'll have `Uncaught TypeError: Cannot read properties of undefined (reading 'offsetHeight')`

The problem is because of `$topBarSecond[0].offsetHeight` here: https://github.com/humhub/humhub/blob/master/static/js/humhub/humhub.ui.topNavigation.js#L52C42-L52C71

### Describe the solution you'd like

Test if `#topbar-second` exists before reading it with JS.

**Comment by marc-farre** [comment]
@luke- would you accept a PR where I add tests in `humhub.ui.topNavigation.js` and `humhub.ui.view.js`?
Or should I add an empty `<div id="topbar-second"></div>` in the theme?

**Comment by luke-** [comment]
@marc-farre Yes, would be fine for me. So feel free to create a PR which tests if the second toolbar exists.

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6728

I've changed the way of calculating the topbar menus height: https://github.com/humhub/humhub/pull/6728/files#diff-b154946f00749e44d107396a9627ecd5987a0bab499487d466968f514df4bdc3R163-R168

Before: Position of the second menu from the top + height of the second menu
After: sum of the heights of all top menus (based on `.topmenu` class)

**Comment by luke-** [comment]
@marc-farre Looks fine for me. Thanks!
