### ISSUE TITLE
Trim URL in settings when saving

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6734]
### What steps will reproduce the problem?

See https://community.humhub.com/comment/perma?id=47173

1. In  Administration -> Settings -> Base URL, add a space char at the end of the URL
2. Click on a link in an email notification or summary

### What is the expected result?

The link works

### What do you get instead?

It doesn't work because a `%20` is added to the link, because of the char space

### Additional info

I suggest to trim the URL when saving them in settings.
Maybe with a validator?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15

**Comment by jdepi** [comment]
Hello Marc, 
I am not sure, if my issue has the same cause. I've been using a domain name with a sub-directory like 
https://my-domain/dirname The email summary contains a link without the dirname. Notifictions via email still contain the correct base url.
Jens

**Comment by luke-** [comment]
@jdepi This issue will be fixed with HumHub 1.15.1 which will be released today

**Comment by marc-farre** [comment]
However, the space char issue is still present, even on the develop branch.
Sub-directories is a different issue.

**Comment by yurabakhtin** [comment]
@marc-farre Fixed in PR https://github.com/humhub/humhub/pull/6737.

**Comment by marc-farre** [comment]
Thanks @yurabakhtin 
Another way (would simplify the code, and I think more robust) would be to add an `url` validator (which also checks if there are no spaces), replacing:
https://github.com/humhub/humhub/blob/2fe1c264db21551bbd488a88e1d43722635ed132/protected/humhub/modules/admin/models/forms/BasicSettingsForm.php#L60-L64
with:
```php
[['baseUrl'], 'url'],
```

**Comment by ArchBlood** [comment]
> Thanks @yurabakhtin Another way (would simplify the code, and I think more robust) would be to add an `url` validator (which also checks if there are no spaces), replacing:
> 
> https://github.com/humhub/humhub/blob/2fe1c264db21551bbd488a88e1d43722635ed132/protected/humhub/modules/admin/models/forms/BasicSettingsForm.php#L60-L64
> 
> 
> with:
> ```
> [['baseUrl'], 'url'],
> ```

Personally something like how the space model rules are done could be done here, otherwise just using `url` can be used;

https://github.com/humhub/humhub/blob/bc1cfbfb0e660ac7cb68929e18358ec704b07e70/protected/humhub/modules/space/models/Space.php#L129

**Comment by yurabakhtin** [comment]
@marc-farre @ArchBlood The `url` validator doesn't allow to use localhost urls like `http://localhost`, maybe new option like `allowLocalDomains` will be implemented in future - https://github.com/yiisoft/validator/issues/4.
So I had to modify the default pattern https://www.yiiframework.com/doc/api/2.0/yii-validators-urlvalidator#$pattern-detail in order to allow localhost urls.
Also the url validator allows url with with space in the end like `http://site.com/ `, it is why I have added the `trim` validator.

Commit https://github.com/humhub/humhub/pull/6737/commits/8f0bb1ce1a24ae3d7625cec334f067b95c745d4d.

**Comment by marc-farre** [comment]
@yurabakhtin Very nice, thanks! When no pattern, the `url` doesn't allow space at the end (tested).
