### ISSUE TITLE
Add per-user import/export functionality 

### ISSUE THREAD

**Issue by elima** [humhub/humhub#674]
To differentiate Humhub from centralized data silos (FB, G+, etc), an import/export functionality is essential.

Data for which a user is authoritative, should be retrievable in a machine readable format (RSS, RDF, SQL dump, etc), to provide a migration oportunity to the user, should he/she decides to take his/her data somewhere else.

Building a social network graph and adding content is a very time-consuming task. An import/export feature would avoid/mitigate wasting that time.

**Comment by timvango** [comment]
+1

**Comment by WASasquatch** [comment]
Does G+ provide dumps? I've tried FB dump, and it never has worked and provides dead links. Though this feature would be amazing. 

+1

**Comment by devcline** [comment]
+1

**Comment by edmundhighcock** [comment]
This has definitely been the reaction from my users as well: if I invest a lot into this site, how can I take it with me if I choose to leave? +1

**Comment by Ace2213** [comment]
+1

**Comment by funkycram** [comment]
Related to https://github.com/humhub-contrib/legal/issues/20 ?

**Comment by samuk** [comment]
@luke- which pull request provides this functionality please?

**Comment by funkycram** [comment]
@samuk it's closed because the subject is moved to https://github.com/humhub-contrib/legal/issues/20
