### ISSUE TITLE
Attempt to read property "guid" on null during example content import

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [humhub/humhub#6740]
### What steps will reproduce the problem?
Attempt to install example content during installation while using Galera as a SQL database. 

### What is the expected result?
The installation should install example content. 

### What do you get instead?
The installation page returns an error when you check to install example content. You can refresh the error page and the installation will move to the next step. The example content is not installed. 

Here is the backtrace. 
```
yii\base\ErrorException: Attempt to read property "guid" on null in /apps/humhub/protected/humhub/modules/installer/controllers/ConfigController.php:259
Stack trace:
#0 /apps/humhub/protected/humhub/modules/installer/controllers/ConfigController.php(259): yii\base\ErrorHandler->handleError(2, 'Attempt to read...', '/apps/humhub/pr...', 259)
#1 [internal function]: humhub\modules\installer\controllers\ConfigController->actionSampleData()
#2 /apps/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /apps/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#4 /apps/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('sample-data', Array)
#5 /apps/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('installer/confi...', Array)
#6 /apps/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#7 /apps/humhub/index.php(25): yii\base\Application->run()
#8 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0 and 1.15.1. 
| PHP version      |  PHP 8.2 and 8.3 tested
| Operating system | FreeBSD
| Database | MariaDB 10.6.16 with Galera 26.4.16.

Please let me know what else you need, or any other way I can help.

**Comment by ArchBlood** [comment]
@jSML4ThWwBID69YC is this still an issue? If not then I believe it can be closed.

**Comment by jSML4ThWwBID69YC** [comment]
Yes. Closing.
