### ISSUE TITLE
Bug? Default container permissions - `permission_id` vs `class`

### ISSUE THREAD

**Issue by martin-rueegg** [humhub/humhub#6747]
I in [`ContentContainerPermissionManage::getDefaultStoredState()`](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/ContentContainerPermissionManager.php#L97C22-L97C43) default permission states are saved to cache in an array structure.

\
What seems odd to me is that upon saving, the permission's `permission_id` is used (`[$defaultPermission->permission_id]`):
https://github.com/humhub/humhub/blob/ad48254d9c4a005af7a12cdfadd8459e20887ef9/protected/humhub/modules/content/components/ContentContainerPermissionManager.php#L121

\
This seems correct, as it also corresponds to the [table's primary key](https://github.com/humhub/humhub/blob/ad48254d9c4a005af7a12cdfadd8459e20887ef9/protected/humhub/modules/content/migrations/m201130_073907_default_permissions.php#L39):
https://github.com/humhub/humhub/blob/ad48254d9c4a005af7a12cdfadd8459e20887ef9/protected/humhub/modules/content/migrations/m201130_073907_default_permissions.php#L39

\
However, upon retrieval, the permission's _class_ is used (`[get_class($permission)]`):
https://github.com/humhub/humhub/blob/ad48254d9c4a005af7a12cdfadd8459e20887ef9/protected/humhub/modules/content/components/ContentContainerPermissionManager.php#L127

\
In many cases, the class is used as the `permission_id`. However, that's not mandatory and many permissions do _not_ follow this pattern and use a "meaningful" identifier instead. E.g. `humhub\modules\admin\permissions\ManageGroups`;
https://github.com/humhub/humhub/blob/ad48254d9c4a005af7a12cdfadd8459e20887ef9/protected/humhub/modules/admin/permissions/ManageGroups.php#L18-L23

\
Did I miss something or should lines 126-128 read

```php
        if (isset($cachedDefaultPermissions[$groupId][$permission->moduleId][$permission->permission_id])) {
            return (int) $cachedDefaultPermissions[$groupId][$permission->moduleId][$permission->permission_id];
        }
```

| Q                | A
| ---------------- | ---
| HumHub version   | `master`
| PHP version      | 
| Operating system |

**Comment by yurabakhtin** [comment]
@martin-rueegg I confirm if `BasePermission` has defined `protected $id` then we have the bug, so we have to use `BasePermission->getId()` which returns `$this->id` if defined otherwise `static::class`.

@luke- Fixed in PR https://github.com/humhub/humhub/pull/6764.

**Comment by martin-rueegg** [comment]
Thanks, @yurabakhtin
