### ISSUE TITLE
Allow modules to add widgets at the left or right sidebar of a space

### ISSUE THREAD

**Issue by carlosgcampos** [humhub/humhub#675]
There's currently a single SpaceSidebarWidget where modules can add widgets. In the case of spaces, there are 3 builtin widgets (info, latest activities and members), so widgets added by modules are usually below the 3 builtin ones and you need to scroll to see them. However, at the left of a space there's usually plenty of available space. It would be great if module widgets were added there, to make sure they are always visible without scrolling, like for example the upcoming events widget of the calendar module. Modules might decide where to put their widgets depending on how important they are for example, or it could even be configurable by the user.

**Comment by WASasquatch** [comment]
As for priority, HumHub uses a 100, 200, 300 sorting system. So use 0, 1, 2, 3 to get above those widgets. ;)

**Comment by carlosgcampos** [comment]
Yes, I know, but then other widget will have that problem, my point is that we can use the empty space on the left. Since that depends on the modules installed and the space configuration, I think the best solution would be to make it configurable.

**Comment by WASasquatch** [comment]
Will have what problem? You just again, order them differently. Do you mean the option to change the physical location of a widget? 

Modules are custom apps for HumHub, you can render to the left hand side by editing the `_layout.php` and change the locaiton of a widget. 

https://github.com/humhub/humhub/blob/master/protected/modules_core/space/views/space/_layout.php

**Comment by luke-** [comment]
Hmm, maybe you can create a two column right sidebar via a theme.

**Comment by WASasquatch** [comment]
Custom pages extended adds to space columns. You'll just need to update to
latest version of humhub. The code is old.
