### ISSUE TITLE
Allow changing visibility of global content

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6757]
### Is your feature request related to a problem? Please describe.

In a stream of global content (not in a content container), we can do some actions on them, but not changing the visibility to public:
![image](https://github.com/humhub/humhub/assets/23310825/5d3e8da9-f16a-4e94-b35b-072347f29b58)

### Describe the solution you'd like

![image](https://github.com/humhub/humhub/assets/23310825/30219f8b-7ea3-43e1-8a72-e44b30cac21a)

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6758

I've checked `Content::canView()` (https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/models/Content.php#L970) with global content when private or public, it's fine, it already works well.

**Comment by luke-** [comment]
@marc-farre Hmmm, actually global content should always be public. 

Where is private global content used? How is the permission checked? (Also in terms of streams and search).

**Comment by marc-farre** [comment]
> Where is private global content used?

It will be for global surveys when this PR is merged.

> How is the permission checked?

@luke- For global content, `Content::canView()` returns this:
- Private:
  - User: true (1)
  - Guest: false (2)
- Public:
  - User: true (1)
  - Guest
    - if guest access is enabled: true (2)
    - if not: false (2)

(1) https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/models/Content.php#L979-L981

(2) https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/models/Content.php#L989-L991 and then https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/models/Content.php#L1027-L1029

> in terms of streams

You're right, I forgot about this. Thanks!
I'll add a commit later today.

> in terms of search

This PR only impact guests. And guests cannot search. So it should be OK.

**Comment by luke-** [comment]
Ok, I like this distinction for global content

However, we should:

- We should add some documentation about this. E.g. also add support for this here: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/ui/form/widgets/ContentVisibilitySelect.php

- Unit Tests

- If Guest Access is not active, how do we behave. Do not display the button?
- What happens when Guest Access is switched

**Comment by marc-farre** [comment]
Yes, I forgot these implications, thanks!

1a/ Doc:

It's about https://docs.humhub.org/docs/develop/content#content-visibility
Done in PR https://github.com/humhub/documentation/pull/95

1b/ `ContentVisibilitySelect`: Done

2/ I don't see any possibility to create a global content with Humhub core (only with additional modules). Have you got an idea of test I could do?

3 & 4/ I think we should have the same behavior than in private spaces (no Guest Access means Humhub is full private, like a private space).

So it means that if Guest Access is not active:
- the button shouldn't be displayed if the content is private: https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/widgets/VisibilityLink.php#L41-L46
- when Guest Access is enabled again, content keep the previous visibility state (when switching a private space to public, the content visibility is not modified)

Done on `VisibilityLink` widget

5/ Stream:

I've added:
- `humhub\modules\stream\actions\GlobalStream`
- `humhub\modules\stream\models\GlobalStreamQuery`
- `humhub\modules\stream\models\filters\GlobalStreamFilter`

I've added them to `M̀IGRATE-DEV.MD`

It's already OK for https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/components/ActiveQueryContent.php#L114

New commit: https://github.com/humhub/humhub/pull/6758/commits/5fd326e0349aa3192ef06d84a62d84c0f1990fc4

**Comment by luke-** [comment]
@marc-farre Thanks looks good. Here are a few more points. The point for custom pages is not necessary yet. 

Unit tests would be very important to ensure that this currently rarely used visibility always works correctly. For Tests you could maybe use a Dummy Content model like this: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/tests/codeception/unit/TestContent.php

- [ ] We should rename `GlobalStream` & other classes to `GlobalContentStream`. Its clearer.
- [ ] We should also add a hint to `ContentVisibilitySelect` e.g. https://github.com/humhub/humhub/blob/master/protected/humhub/modules/ui/form/widgets/ContentVisibilitySelect.php#L78 to `(Also visible to people who are not logged in.)`
- [ ] Add Unit Tests for `GlobalContentStream` 
- [ ] Add Unit Tests for `Content::canView()` 
- [ ] Custom Pages: Implement Feature here: https://github.com/humhub/custom-pages/issues/317

Let me know when I can help.

**Comment by marc-farre** [comment]
@luke- new PR based on HumHub 1.16: https://github.com/humhub/humhub/pull/6930

Sorry for having been so long.
Thanks to [your "Test" tutorial](https://community.humhub.com/s/module-development/wiki/Test+Cheatsheet) I've managed to configure it correctly on my computer, so from now I'll be able to create tests much more easily!
