### ISSUE TITLE
Disabled modules can cause errors

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#6763]
### What steps will reproduce the problem?
1. Have some older/custom modules on your test instance which causes errors after HumHub update. (I don't have the time right now to figure out which module exactly it was and where it was from, sorry. Let me know if you need this in order to reproduce/fix this, I'll try to find the time to dig deeper.)
2. Notice in Information -> Prerequisites that there are some "custom" modules (Nice! :+1: )
     `HumHub - Custom Modules (Tags, Announcements, Bookmark, Subscriptions) (Hint: Must be updated manually. Check compatibility with newer HumHub versions before updating.)`
3. Consider that they might be the culprit, therefore *disable* them.
4. Issue persists
5. *Head scratching intensifies*
6. Decide to uninstall those disabled modules just to be sure
7. Errors are unexpectedly gone

### What is the expected result?
I expect disabled modules to not be able to cause errors in the stream, what's the point in disabling them if they still can cause trouble?

### What do you get instead?
Disabled modules still caused errors.

### Additional info

Stacktrace of the error, may depend on the custom module:
```
yii\base\UnknownPropertyException: Setting unknown property: humhub\modules\content\widgets\richtext\ProsemirrorRichText::markdown in /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('markdown', true)
#1 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(humhub\modules\content\widgets\richtext\ProsemirrorRichText), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#5 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\modules\\...', Array, Array)
#6 /var/www/[redacted]/html/protected/humhub/components/Widget.php(60): yii\BaseYii::createObject(Array)
#7 [internal function]: humhub\components\Widget::widget(Array)
#8 /var/www/[redacted]/html/protected/humhub/modules/content/widgets/richtext/RichText.php(57): call_user_func('humhub\\modules\\...', Array)
#9 /var/www/[redacted]/html/protected/modules/humhub-modules-announcements/widgets/views/entry.php(19): humhub\modules\content\widgets\richtext\RichText::widget(Array)
#10 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/View.php(347): require('/var/www/testin...')
#11 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/testin...', Array)
#12 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/testin...', Array, Object(humhub\modules\announcements\widgets\WallEntry))
#13 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Widget.php(249): yii\base\View->render('entry', Array, Object(humhub\modules\announcements\widgets\WallEntry))
#14 /var/www/[redacted]/html/protected/modules/humhub-modules-announcements/widgets/WallEntry.php(20): yii\base\Widget->render('entry', Array)
#15 /var/www/[redacted]/html/protected/humhub/modules/content/widgets/WallEntry.php(304): humhub\modules\announcements\widgets\WallEntry->run()
#16 /var/www/[redacted]/html/protected/humhub/modules/content/widgets/WallEntry.php(265): humhub\modules\content\widgets\WallEntry->getWallEntryViewParams()
#17 /var/www/[redacted]/html/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\WallEntry->getLayoutViewParams()
#18 [internal function]: humhub\components\Widget::widget(Array)
#19 /var/www/[redacted]/html/protected/humhub/modules/content/components/ContentActiveRecord.php(392): call_user_func('humhub\\modules\\...', Array)
#20 /var/www/[redacted]/html/protected/humhub/modules/stream/actions/LegacyStreamTrait.php(170): humhub\modules\content\components\ContentActiveRecord->getWallOut(Array)
#21 /var/www/[redacted]/html/protected/humhub/modules/stream/actions/LegacyStreamTrait.php(140): humhub\modules\stream\actions\Stream::renderLegacyWallEntry(Object(humhub\modules\announcements\models\Announcement), Array, false)
#22 /var/www/[redacted]/html/protected/humhub/modules/stream/actions/LegacyStreamTrait.php(81): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\announcements\models\Announcement), Array)
#23 /var/www/[redacted]/html/protected/humhub/modules/stream/actions/Stream.php(411): humhub\modules\stream\actions\Stream::getContentResultEntry(Object(humhub\modules\content\models\Content))
#24 /var/www/[redacted]/html/protected/humhub/modules/stream/actions/Stream.php(369): humhub\modules\stream\actions\Stream->getStreamEntryResult(Object(humhub\modules\content\models\Content), Object(humhub\modules\content\widgets\stream\WallStreamEntryOptions))
#25 /var/www/[redacted]/html/protected/humhub/modules/stream/actions/Stream.php(348): humhub\modules\stream\actions\Stream->addResponseEntries(Array, Object(humhub\modules\stream\actions\StreamResponse))
#26 [internal function]: humhub\modules\stream\actions\Stream->run()
#27 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#28 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#29 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('stream', Array)
#30 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array)
#31 /var/www/[redacted]/html/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#32 /var/www/[redacted]/html/index.php(25): yii\base\Application->run()
#33 {main} 
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.1
| PHP version      |  8.0.20
| Operating system | CentOS Stream 8

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
It seems to be a problem with the announcement module.

```
#14 /var/www/[redacted]/html/protected/modules/humhub-modules-announcements/widgets/WallEntry.php(20): yii\base\Widget->render('entry', Array)
```

At first look, it looks as if the module did not delete all data when it was disabled.
Please create an issue there.

**Comment by marc-farre** [comment]
This module is not maintained since a long time: [humhub-modules-announcements](https://github.com/staxDB/humhub-modules-announcements) 

You could try to repair your database with https://docs.humhub.org/docs/admin/console/#integrity

**Comment by dreua** [comment]
> This module is not maintained since a long time: [humhub-modules-announcements](https://github.com/staxDB/humhub-modules-announcements)

I was aware of that, it is on a test instance like I said

> You could try to repair your database with https://docs.humhub.org/docs/admin/console/#integrity

While uninstalling fixed any visible errors, the integrity check found some more issues in the DB, thanks!


I probably had a too optimistic expectation of what disabling of a module actually means. From my experience with different software and operating systems I expected it to be disabled by HumHub so that any errors in the module would cease to have effect on the platform. From what I read between @luke- 's lines it sounds like proper disabling is the module's job and it can still cause issues when the disabling mechanism is not properly implemented on the module side or broken due to incompatibilities.

No point in creating an issue with a unmaintained module but thanks for the clarification!
