### ISSUE TITLE
When `enableMailSummaries` is false in the configuration file, prevent accessing the "E-Mail Summaries" page in the account settings

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6774]
### What steps will reproduce the problem?

Disable E-Mail Summaries: https://docs.humhub.org/docs/admin/config-options/#activity -> `'enableMailSummaries' => false`

Go to https://my-humhub.com/activity/user

### What is the expected result?

404 not found

### What do you get instead?

The page is displayed

### Additional info

Original discussion: https://community.humhub.com/content/perma?id=273925

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.2

**Comment by marc-farre** [comment]
@luke- if the solution is only to throw a 404 error in the controller, I can send a PR for it.

**Comment by luke-** [comment]
@marc-farre Yes, in this case we should hide the navigation item in the user & admin area and a 404 is sufficient for the controller.

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6775
Menu was already OK

**Comment by luke-** [comment]
@marc-farre Thanks!
