### ISSUE TITLE
Provide support for Piwigo image galleries

### ISSUE THREAD

**Issue by bigfoot90** [humhub/humhub#678]
Piwigo is an open source php application for managing photos and albumns.
Piwigo provide web services for integrating in other applications like wordpress, joomla for example.

http://piwigo.org/doc/doku.php?id=dev:webapi:start
http://piwigo.org/demo/tools/ws.htm

**Comment by Ace2213** [comment]
The only benefit to this that I see over the current gallery module is the "visits" info and ratings ]]:

![image](https://user-images.githubusercontent.com/12226710/70045769-6a919600-15a3-11ea-9d75-18bb656f8bfa.png)
