### ISSUE TITLE
cant' register new account

### ISSUE THREAD

**Issue by jhilal08** [humhub/humhub#6784]
i keep getting this error when i register

Call to undefined function Symfony\Component\Mailer\Transport\escapeshellarg()

what should i do? this error appears on the actual website when you try to sign up.

here's the website:  http://islamicmedia.rf.gd/

**Comment by ArchBlood** [comment]
The function `escapeshellarg()` is disabled by the hosting provider and must be enabled.

**Comment by jhilal08** [comment]
> The function `escapeshellarg()` is disabled by the hosting provider and must be enabled.

Ok thank you but how do I do that?

**Comment by ArchBlood** [comment]
> > The function `escapeshellarg()` is disabled by the hosting provider and must be enabled.
> 
> Ok thank you but how do I do that?

If you have access to your php.ini then that's where you can enable it, otherwise you must request it from your hosting provider.
