### ISSUE TITLE
Internal server error when accessing site appearance settings, and when trying to use the Wiki module

### ISSUE THREAD

**Issue by Voldemorte420** [humhub/humhub#6787]
Internal server error when accessing site appearance settings, and when trying to use the Wiki module

### What steps will reproduce the problem?
I am unsure.

### What is the expected result?
Being able to access site appearance settings using the UI

### What do you get instead?
Internal server error occurred

### Additional info
This is the full error I receive::

 yii\base\ErrorException: scandir(/home/webriglt/MYSITE/themes): Failed to open directory: No such file or directory in /home/webriglt/MYSITE/protected/humhub/modules/ui/view/helpers/ThemeHelper.php:78
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /home/webriglt/MYSITE/protected/humhub/modules/ui/view/helpers/ThemeHelper.php(78): scandir()
#2 /home/webriglt/MYSITE/protected/humhub/modules/ui/view/helpers/ThemeHelper.php(40): humhub\modules\ui\view\helpers\ThemeHelper::getThemesByPath()
#3 /home/webriglt/MYSITE/protected/humhub/modules/admin/models/forms/DesignSettingsForm.php(133): humhub\modules\ui\view\helpers\ThemeHelper::getThemes()
#4 /home/webriglt/MYSITE/protected/humhub/modules/admin/views/setting/design.php(40): humhub\modules\admin\models\forms\DesignSettingsForm->getThemes()
#5 /home/webriglt/MYSITE/protected/vendor/yiisoft/yii2/base/View.php(347): require('/home/webriglt/...')
#6 /home/webriglt/MYSITE/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#7 /home/webriglt/MYSITE/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#8 /home/webriglt/MYSITE/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#9 /home/webriglt/MYSITE/protected/humhub/modules/admin/controllers/SettingController.php(232): yii\base\Controller->render()
#10 [internal function]: humhub\modules\admin\controllers\SettingController->actionDesign()
#11 /home/webriglt/MYSITE/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#12 /home/webriglt/MYSITE/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#13 /home/webriglt/MYSITE/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#14 /home/webriglt/MYSITE/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#15 /home/webriglt/MYSITE/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#16 /home/webriglt/MYSITE/index.php(24): yii\base\Application->run()
#17 {main} 

Domain name changed with "MYSITE" for privacy. My website is managed using cPanel and hosted with an external provider. Please help point me in the right direction

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.2
| PHP version      | 
| Operating system | Windows

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by marc-farre** [comment]
Can you try with the Humhub community theme?
![image](https://github.com/humhub/humhub/assets/23310825/e22491ca-8d5c-4de5-b357-5cce2ed5d54e)

**Comment by Voldemorte420** [comment]
> Can you try with the Humhub community theme? ![image](https://private-user-images.githubusercontent.com/23310825/295256384-e22491ca-8d5c-4de5-b357-5cce2ed5d54e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTUyMTEsIm5iZiI6MTcwNDgxNDkxMSwicGF0aCI6Ii8yMzMxMDgyNS8yOTUyNTYzODQtZTIyNDkxY2EtOGQ1Yy00ZGU1LWIzNTctNWNjZTJlZDVkNTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE1NDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMjczZmVjNWNhNTVhYWRlODY2Y2U5MGNjZjZmOGJlNjQxMWI2YTQyZGEyYzg3NGQ0Zjg4MTdjMzkyMmUxMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0wuGsNlf6ZRRswSi_r9mog03eKERqLu6A-fcvFmbBHg)

Hello @marc-farre I have just deleted the clean theme and dark theme modules, yet I am still unable to access the appearance settings using the admin interface. It appears that the Themes folder in my main directory simply doesn't exist. As for my website prerequisites, all of them are reported as working well besides LDAP support.
