### ISSUE TITLE
Marketplace search internal error

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#6790]
HH 1.16

yii\base\UnknownMethodException: Calling unknown method: humhub\modules\marketplace\models\Module::getName() in /srv/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /srv/humhub/protected/humhub/components/ModuleManager.php(423): yii\base\Component->__call()
#1 /srv/humhub/protected/humhub/components/ModuleManager.php(392): humhub\components\ModuleManager->filterModulesByKeyword()
#2 /srv/humhub/protected/humhub/modules/marketplace/widgets/ModuleGroups.php(73): humhub\components\ModuleManager->filterModules()
#3 /srv/humhub/protected/humhub/modules/marketplace/widgets/ModuleGroups.php(33): humhub\modules\marketplace\widgets\ModuleGroups->initDefaultGroups()
#4 /srv/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\marketplace\widgets\ModuleGroups->init()
#5 [internal function]: yii\base\BaseObject->__construct()
#6 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(411): ReflectionClass->newInstanceArgs()
#7 /srv/humhub/protected/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#8 /srv/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#9 /srv/humhub/protected/humhub/components/Widget.php(60): yii\BaseYii::createObject()
#10 /srv/humhub/protected/humhub/modules/marketplace/views/browse/index.php(35): humhub\components\Widget::widget()
#11 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require('/srv/humhub/pro...')
#12 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#13 /srv/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#14 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#15 /srv/humhub/protected/humhub/modules/marketplace/controllers/BrowseController.php(51): yii\base\Controller->render()
#16 [internal function]: humhub\modules\marketplace\controllers\BrowseController->actionIndex()
#17 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#18 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#19 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#20 /srv/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#21 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#22 /srv/www/htdocs/doku2/index.php(24): yii\base\Application->run()
#23 {main}

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6792.
The unknown methods were added here https://github.com/humhub/humhub/commit/48ba9def229ed92c8a64c4db048301000c1e9a46#diff-46a3b644fa0848e9b9ff89b55e78b267182b69d39cea2f61870c54d37d0a78a5R413-R421.

**Comment by luke-** [comment]
@yurabakhtin Thanks for the fix and investigation!
