### ISSUE TITLE
User Admin Search 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6795]
When searching for a keyword and select `Deactivated` users, also `Active` users will be displayed.

e.g.

![image](https://github.com/humhub/humhub/assets/4736168/d9f577df-e20c-4da2-8d6e-4439e361f258)

**Comment by Semir1212** [comment]
@luke- @yurabakhtin Deactivated users also seem to receive notifications/email summaries. Might be connected to this. I have created an issue for the Messenger.
