### ISSUE TITLE
The link about attached files in the rich text editor doesn't open in a new tab

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6796]
### Is your feature request related to a problem? Please describe.

Create a post and attach a file in the rich text editor (1) and the same file to the post (2):
![image](https://github.com/humhub/humhub/assets/23310825/fabe7c4d-3d31-4afe-b483-5e285c55422c)

Click on:
- the first link (in the rich text): it opens in the same tab
- the second one (attached to the post): it opens in a new tab

### Describe the solution you'd like

In both cases, the link opens in a new tab, to avoid leaving Humhub.

Original discussion: https://community.humhub.com/comment/perma?id=47527

**Comment by luke-** [comment]
Good point, we should always ensure that links to files and external URLs are opened in a new window/tab.

@yurabakhtin can you please take a look into this?

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub-prosemirror/pull/135.

**Comment by luke-** [comment]
@marc-farre Can you please test?

**Comment by marc-farre** [comment]
@luke- @yurabakhtin Yes, it works perfectly!
