### ISSUE TITLE
PHP version check in pre-requisites

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6797]
### What steps will reproduce the problem?

Install Humhub 1.15 on a server with PHP 7.4.
Check pre-requisistes.

### What is the expected result?

A warning about the PHP version.

### What do you get instead?

![image](https://github.com/humhub/humhub/assets/23310825/e1f7e73c-0daf-4a0b-bfb9-4827a16a7662)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.3
| PHP version      | 7.4

**Comment by luke-** [comment]
@marc-farre 7.4 should actually still be allowed. As of 1.16, 8.0+ is a prerequisite. Or am I mixing something up here?

**Comment by marc-farre** [comment]
@luke- The way I understood it, PHP 7.4 is not allowed for Humhub 1.15:
![image](https://github.com/humhub/humhub/assets/23310825/8a94773f-575f-427c-8cf0-06f01ba72b68)

So now some of my modules that require 1.15 uses PHP 8 functionalities.

**Comment by luke-** [comment]
@marc-farre Unfortunately, this is an incorrect in our documentation. 

https://github.com/humhub/humhub/blob/master/protected/humhub/config/common.php#L29

From v1.16+ min Version will become 8.0

**Comment by marc-farre** [comment]
I see. It was done on this commit: https://github.com/humhub/documentation/commit/a545cbf0c64b2a2d26d8b41676064527ea62fa98

Well, on https://community.humhub.com/ I told some people the minimal Humhub version is now 8.0 and I think @ArchBlood too.
And some modules of mine are not compatible with PHP 7.4 because I thought the minimal PHP version was 8.

So should we update the doc and modules or should Humhub 1.15.3 fix this minimal version to PHP 8.0?

**Comment by ArchBlood** [comment]
It's already too late for some of Green Meteor's modules to downgrade PHP versions.

**Comment by ArchBlood** [comment]
This is why I suggested in the Module Development space we add version control for PHP versions in the `module.json` as well;

https://community.humhub.com/content/perma?id=274120

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/documentation/pull/96

I'll try to downgrade the PHP version for my modules (but not simple because some of them depends on external libraries that I need to downgrade and then change my code to make it work again with the old version of it). FYI, the known incompatible one is the Web Feed module, but I have to check for the others.

Next time, I'll have a look to the code you mentioned!
