### ISSUE TITLE
Follow all or no users

### ISSUE THREAD

**Issue by sebastianSchmidt86** [humhub/humhub#6813]
### What steps will reproduce the problem?
Let's assume I don't follow any users yet. Open /people. Click the "Follow" button on the first people card.

### What is the expected result?
I only follow this specific user.

### What do you get instead?
I follow all users. (Only in the frontend, in the database everything is fine)

### Additional info
It looks like it's a caching issue. If I don't follow the very first user, then I don't follow any user.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.2
| PHP version      | 
| Operating system |

**Comment by yurabakhtin** [comment]
@luke- It was fixed in the PR https://github.com/humhub/humhub/pull/6814, so we can close it.
