### ISSUE TITLE
[Develop] Web Migrations broken

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6819]
The migrations are displayed but there is no possibility to execute them.

![image](https://github.com/humhub/humhub/assets/4736168/064a8f8a-79f2-45d3-9ee5-53dd462ddc76)

**Comment by yurabakhtin** [comment]
@luke- It seems you fixed this bug here https://github.com/humhub/humhub/pull/6820.

**Comment by luke-** [comment]
@yurabakhtin Oh yes, can you please approve?

**Comment by yurabakhtin** [comment]
@luke- Done.
