### ISSUE TITLE
Stream could not be initialized!

### ISSUE THREAD

**Issue by vslonska** [humhub/humhub#6825]
Hello,

All of a sudden, I have the message "Stream could not be initialized!" and everything is broken. No updates of modules nor Humhub. I don't understand what caused that.
I did `php yii integrity/run` in protected folder, without any result.
![Screenshot 2024-01-30 at 21-47-58 cPanel - Terminal](https://github.com/humhub/humhub/assets/24274243/d2524596-0d44-4f71-b30e-15049207ac45)

Does anyone have an idea of what I can do ?

Thank you !

**Comment by ArchBlood** [comment]
Check your log file in `/protected/runtime`

**Comment by vslonska** [comment]
Hello,
Thank you for your answer. I don't have any error in this file other than the ones that appear when I disable a module (`Next yii\db\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rqbt1528_humh255.custom_pages_page' doesn't exist` for example).
I really don't understand...
Thank you very much,

**Comment by vslonska** [comment]
But I do see that in console :+1: 
![Uploading Captura desde 2024-01-31 09-37-54.png…]()

**Comment by vslonska** [comment]
But I do see that in console : 

![Captura desde 2024-01-31 09-37-54](https://github.com/humhub/humhub/assets/24274243/aecab30c-0190-4884-b7c6-4a456229ec28)

**Comment by vslonska** [comment]
And that in HumHub when I click on the arrow next the error : 
    ```
................... lot of things
"172704": "\"",
    "172705": ":",
    "172706": "[",
    "172707": "]",
    "172708": "}",
    "url": "/index.php?r=dashboard%2Fdashboard%2Fstream",
    "status": 200,
    "response": "                                                                                                                                                                                                                                                                                                                         
........................................................ lot of things
        "status": 200,
        "statusText": "parsererror"
    },
    "dataType": "json",
    "error": {},
    "errorThrown": {},
    "validationError": false
}
```

**Comment by marc-farre** [comment]
> Hello, No, I already tried that and it doesn't change anything...

Don't hesitate to post on https://community.humhub.com/dashboard and we'll try to help you if possible.
