### ISSUE TITLE
Add the new requirements.php file in modules having specific requirements

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6832]
### Is your feature request related to a problem? Please describe.

Some modules need specific PHP version, extensions or depends on other modules.

E.g, the External Calendar should not be installed if the Calendar module is not enabled.

### Describe the solution you'd like

Add the new requirements.php file in modules having specific requirements.

See https://github.com/humhub/humhub/issues/6744

**Comment by luke-** [comment]
Perhaps we should create an issue directly in the respective module repostories.

But I don't expect many cases here.
