### ISSUE TITLE
Administrator should be able to restrict the Profile modules from being activated by the user on his profile

### ISSUE THREAD

**Issue by jac69** [humhub/humhub#6833]
It is unfortunately not possible to prevent users from activating and using modules on their profile. 

Administrator should be able to restrict the Profile modules from being activated by the user on his profile

On the Administration - Modules area - options - Set as default, we can see 3 option:
- Deactivated
- Activated
- Always activated.

We need the "Always Deactivated" option for user profiles.

**Comment by marc-farre** [comment]
It's done: https://github.com/humhub/humhub/issues/6486
It's part of HumHub 1.16 which is not yet released.
