### ISSUE TITLE
The getObjectModel() method should work for all ActiveRecord classes

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6839]
### What steps will reproduce the problem?

```php
class A extends ActiveRecord
{}

class B extends class A
{
    public static function getObjectModel(): string
    {
        return A::class;
    }
}
```

Attach a file to B

```
$a = new A();
count ($a->fileManager->findAll());
```

### What is the expected result?

1 (the file is attached to A).

### What do you get instead?

0 (the file is attached to B).

### Additional info

This is because `PolymorphicRelation::getObjectModel()` only works for `ContentActiveRecord` or `ContentAddonActiveRecord`:
https://github.com/humhub/humhub/blob/master/protected/humhub/components/behaviors/PolymorphicRelation.php#L119

@luke- would you accept a PR where:

```php
    public static function getObjectModel(): string
    {
        return static::class;
    }
```

is moved from `ContentActiveRecord` and `ContentAddonActiveRecord` to `ActiveRecord`?

And in `PolymorphicRelation::getObjectModel()` I'll replace:

```php
return $object instanceof ContentActiveRecord || $object instanceof ContentAddonActiveRecord
```

with:

```php
return $object instanceof ActiveRecord
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.2

**Comment by marc-farre** [comment]
> It's not really a common approach for extending multiple classes no?

Use case:

```php
class Product extends ActiveRecord {...}
class ProductForm extends Product {...}
```

I use ProductForm to attach images.

**Comment by luke-** [comment]
> But in another hand, I think we should have the possibility to extend any `ActiveRecord` classes without breaking the polymorphic relation because, at least for the `file` table, any `ActiveRecord` can attach files in it.
> 
> So I think that restricting `getObjectModel()` to only `ContentActiveRecord` or `ContentAddonActiveRecord` adds even more complexity than having this method working for all `ActiveRecord`.

@marc-farre I agree with that.  Since the File module is based on polymorphic relations, we must have this option at the ActiveRecord level.


> ### PolymorphicRelationTargetInterface
> Yes, the `PolymorphicRelationTargetInterface` would be much better I think.
> 
> Another approach, more complicated in the code, but that could avoid `getObjectModel()` or `PolymorphicRelationTargetInterface` (so maybe more reliable for new developers) would be, in `PolymorphicRelation::getObjectModel()`, to find the closer parent class declaring the `tableName()` method (because this is the class that should be used for polymorphic relations).
> 

Interesting idea. To summarize: Always use the class in hierarchy which directly implements the `tableName()` method? But I'm not sure this is possible, because `method_exists` should always return true, because there is a very early `tableName()` implementation of the Yii ActiveRecord implemenation.

Hmm, actually, we can also keep the name `getObjectModel()`. The PHPDoc is quite good and we could easily add an interface at any time. So from my point of view, I would be fine to simply move it to AR...

**Comment by marc-farre** [comment]
@luke- yes, you're right (as usual 😉!). But it's possible to detect in which class the `tableName()` method has been declared this way (tested successfully this time!):

```php
        function tableNameIsDeclared($className)
        {
            $reflector = new \ReflectionClass($className);
            $method = $reflector->getMethod('tableName');
            return $method->class === $className;
        }


        function getCloserParentClassWithTableName($object)
        {
            $class = get_class($object);
            if (tableNameIsDeclared($class)) {
                return $class;
            }
            while ($class = get_parent_class($class)) {
                if (tableNameIsDeclared($class)) {
                    return $class;
                }
            }
            return null;
        }

        $object = new ProductForm();
        echo getCloserParentClassWithTableName($object); // returns humhub\modules\myModule\models\Product
```

So should we implement this and remove `getObjectModel()` everywhere, or should move `getObjectModel()` to the AR level?

**Comment by luke-** [comment]
Hmm, I would prefer to move "getObjectModel()" to AR.

The other solution is also interesting. The only question is whether the class with "tableName()" is really always the right one. And if not, how could it be overwritten?

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6854
