### ISSUE TITLE
Photo Gallery on profile

### ISSUE THREAD

**Issue by avasima** [humhub/humhub#684]
enhancement : 
1:Please Construction Photo Gallery on user Profile
2: Add Private Message Button on User Profile
3: User Can Send Private and Public Post 
4: User Can Block other users 
:+1: :+1: :+1: :+1: :+1:

**Comment by WASasquatch** [comment]
Please use constructive issue titles encompassing the goal of your topic. 

1) https://github.com/rifaideen/humhub-modules-album
2) This cannot be done at this time. Messaging application is a optional module and not part of HumHub core. You can do it manually if you want.
3) By private, what do you mean? A hidden post that no one can see? Aside from that the public-side of HumHub is in development. You can notice some of it's functionality already integrated into HumHub currently.
4) https://github.com/humhub/humhub/issues/564
