### ISSUE TITLE
Humhub 1.15.2 uses dev version of yii2 ?

### ISSUE THREAD

**Issue by ukaeufe** [humhub/humhub#6845]
### What steps will reproduce the problem?

check yii2 version in. installed humhub folders and in admin panel

### What is the expected result?

e.g. 2.0.49

### What do you get instead?

v2.0.50-dev

### Additional info

I found that by looking for the root cause of an issue where setting YII_DEBUG=false leads to internal server error in a netcup/plesk environment => I may create another issue for that problem.

Where do you actually specify your dependencies and versions?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.2
| PHP version      | 8.2
| Operating system | Linux ae93c 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
| Env | Netcup webhosting using plesk

**Comment by luke-** [comment]
This is intentional, as it contains some fixes that we need.
