### ISSUE TITLE
In the "Module Administration" page, remove "Show in Marketplace" for modules not in the `@app/modules` directory

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6849]
### What steps will reproduce the problem?

Add a custom module to your HumHub instance.
Go to "Administration" ->  "Module Administration".

![image](https://github.com/humhub/humhub/assets/23310825/8ff87c48-20bb-4aaf-819b-ed75ea96228e)

### What is the expected result?

View the module

### What do you get instead?

![image](https://github.com/humhub/humhub/assets/23310825/28003216-e07c-4780-a50e-cca3a72b994c)

### Additional info

We should remove "Show in Marketplace" for custom modules that are not in the marketplace.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15

**Comment by luke-** [comment]
The reason behind this is that the 'Administration -> Modules' page should also work without a Marketplace API request, and should not be delayed by it.

Normally the folder `protected/modules` is for Marketplace Modules. Custom modules are preferably in other module folders.

We may be able to display the "Show in Marketplace" message only for modules from this folder.

**Comment by marc-farre** [comment]
So maybe we could create a `protected/custom-modules` directory in the source and add it to the `moduleAutoloadPaths` param, to avoid having to do it manually?
This way, sys-admins would see this directory and understand it's the place to add the custom modules.

**Comment by luke-** [comment]
Hmm, yes could be a solution. Maybe it would already be suffient to improve the docs here.

**Comment by marc-farre** [comment]
@luke-
- Doc: https://github.com/humhub/documentation/pull/102
- HumHub: https://github.com/humhub/humhub/pull/6855
