### ISSUE TITLE
Some Unicode emoji in profile fields don't seem to work

### ISSUE THREAD

**Issue by absynth42** [humhub/humhub#6853]
### What steps will reproduce the problem?
Use an emoji like 🤖 in the "first name", "last name" or custom profile fields will yield a "????". 

### What is the expected result?
The emoji ✅ shows up correctly, I would expect 🤖 to show up, too. 

### What do you get instead?
The profile field shows "????".

### Additional info
| Q                | A
| ---------------- | ---
| HumHub version   | Hosted on humhub.com
| PHP version      | 
| Operating system |

**Comment by marc-farre** [comment]
@luke- I've managed to reproduce this issue this way:

1. Open https://community.humhub.com/mail/mail with Android 10
2. Write a message and include a thumb up emoji from Android keyboard (not from HumHub after typing `: `)
3. After sending the message, `????` is displayed instead of the emoji

![image](https://github.com/humhub/humhub/assets/23310825/f8a23e5a-91bd-48b9-8fc5-e6471595f77e)

**Comment by ArchBlood** [comment]
> @luke- I've managed to reproduce this issue this way:
> 
> 1. Open https://community.humhub.com/mail/mail with Android 10
> 2. Write a message and include a thumb up emoji from Android keyboard (not from HumHub after typing `: `)
> 3. After sending the message, `????` is displayed instead of the emoji
> 
> ![image](https://github.com/humhub/humhub/assets/23310825/f8a23e5a-91bd-48b9-8fc5-e6471595f77e)
> 

I'm not able to reproduce on Android 12, the only issue that I see is the positioning of the emoji selector when you close the keyboard, not sure if it's due to Gboard or not.

**Comment by marc-farre** [comment]
Example on the Community network: https://community.humhub.com/comment/perma?id=48549

![image](https://github.com/humhub/humhub/assets/23310825/9bc9d7b4-ed46-4921-909c-2725ccd5b0e0)

**Comment by yurabakhtin** [comment]
I have tested on local server with `master-v1.15.5`:

![user-emoji](https://github.com/humhub/humhub/assets/6995524/b0d0ae57-b584-410a-b171-17ff0d72fec6)
![post-emoji](https://github.com/humhub/humhub/assets/6995524/8bbb08e6-3221-402e-b04e-5f9a1f0b05cf)
![mail-emoji](https://github.com/humhub/humhub/assets/6995524/d20306f2-9df2-411a-a49c-188ca8a30a46)

@luke- Could you please check what "Collation" the problem columns have on humhub.com server, I think they all should have `utf8mb4_unicode_ci` like this:

![user-table](https://github.com/humhub/humhub/assets/6995524/a74994ee-e20a-42bf-af28-6821708dfcf9)
![message-table](https://github.com/humhub/humhub/assets/6995524/1692f99f-4f2f-41bf-bbb3-a52f8fdc2d01)

**Comment by luke-** [comment]
@yurabakhtin Here the Community Database:

![image](https://github.com/humhub/humhub/assets/4736168/275de56a-38ed-4c35-b8d5-69ecc9dfebdd)

![image](https://github.com/humhub/humhub/assets/4736168/bfcac8e1-eaf3-41e5-a1ae-29d34ce36813)

**Comment by yurabakhtin** [comment]
@luke- Yes the tables look correctly.

As I understand the problem only on insert emoji from Android keyboard, maybe later I will find a way to open my local server on Android phone.

@marc-farre humhub emojis is not real unicode emoji please compare how it works on my local server:

![img-vs-emoji](https://github.com/humhub/humhub/assets/6995524/776ae157-0b39-4ece-ae5d-dc827e7ca0b6)

but it is strange why it cannot be stored on the community site correctly even on Windows Chrome:

![test-community](https://github.com/humhub/humhub/assets/6995524/d7a3b892-bca2-4e09-8301-cd947e54109b)

![test-user](https://github.com/humhub/humhub/assets/6995524/2a98e9cd-516f-41d8-b953-c626d23fcbef)

**Comment by yurabakhtin** [comment]
@luke- I guess it may be related to some issue of DB version but DB settings of the site look correctly:

- PHP - Version - 8.2.7
- Database driver - MariaDB
- MariaDB - Version - 10.11.6-MariaDB-0+deb12u1-log
- MariaDB - Database collation - utf8mb4_unicode_ci
- MariaDB - Table collations - utf8mb4_unicode_ci
- MariaDB - Table engines - InnoDB

As known emoji are supported correctly since MySQL v5.5.3 and MariaDB v10.2.3.

Maybe we should try a solution from [here](https://stackoverflow.com/a/65141582), because now I see in the config file `dynamic.php` we have:

```php
'dsn' => 'mysql:host=localhost;port=3306;dbname=humhub',
```

what if to add here `;charset=utf8mb4;collation=utf8mb4_unicode_ci` or add new param like:

```php
'charset' => 'utf8mb4',
```

**Comment by yurabakhtin** [comment]
I have also tested on my local server with `MariaDB v10.6`:

![db-info](https://github.com/humhub/humhub/assets/6995524/6c41458b-8816-4eaa-8d1f-9393e3042a0e)

![post-icons](https://github.com/humhub/humhub/assets/6995524/60ff6e48-56fb-4f8b-8d66-4b7dfad33da6)

![user-icons](https://github.com/humhub/humhub/assets/6995524/8ed24cc2-4466-419e-8569-1e64a6fdb53c)

**Comment by luke-** [comment]
@yurabakhtin Oh, we had defined a fixed charset in our hosting configs: 
https://github.com/humhub/saas-node/blob/952caae24a102b4f28f8b0be4bfc87d0b5b3e27f/classes/Instance.php#L355

I've changed this now to `utf8mb4` which should solves the issue.

**Comment by marc-farre** [comment]
Maybe we should add a check in pre-requisites?

**Comment by yurabakhtin** [comment]
> @yurabakhtin Oh, we had defined a fixed charset in our hosting configs: https://github.com/humhub/saas-node/blob/952caae24a102b4f28f8b0be4bfc87d0b5b3e27f/classes/Instance.php#L355
> 
> I've changed this now to `utf8mb4` which should solves the issue.

@luke- Yes, now it works, thanks.

![user-emoji](https://github.com/humhub/humhub/assets/6995524/e0e550a0-f0a4-4101-8b07-61dd4375019d)
![message-emoji](https://github.com/humhub/humhub/assets/6995524/50eca8f6-586e-47e2-852d-09c6fe00b48a)

**Comment by luke-** [comment]
Thanks for testing.

The change is now deployed on most instances.
