### ISSUE TITLE
Emojis broken after upgrade from 1.15.1 to .3

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#6868]
### What steps will reproduce the problem?
Post a message on HumHub 1.15.1 announcing maintenance work, starting with a worker emoji to give it some color:

"👷 some text"

### What is the expected result?
The post should look the same after upgrade to 1.15.3 (Using the online updater module. Didn't stop at 1.15.2 to check, unfortunately.)

### What do you get instead?
Post says now ":construction_worker_man: some text"

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.1 / .3
| PHP version      | 8.0.20
| Operating system | CentOS Stream release 8 x86_64

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

No errors in log.

It is now possible to create a new post with the emoji working, but the old one just looks broken.

**Comment by marc-farre** [comment]
@dreua see issue https://github.com/humhub/humhub/issues/6851

**Comment by dreua** [comment]
Argh thanks, I did search for emoji, but that but wasn't found by this search term. Just realized that it might make sense to look through the "Type: Bug" and open/closed issues next time. Maybe pinning or a "known bugs" section would help if mistakes like this happen frequently.
