### ISSUE TITLE
Notifications of removed post stay visible in Notifications list(s)

### ISSUE THREAD

**Issue by martincodeinc** [humhub/humhub#6869]
### What steps will reproduce the problem?
Delete a post
### What is the expected result?
Notifications for this posts should be removed
### What do you get instead?
Notifications of deleted post remain visible for everyone
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.3
| PHP version      |  8.2
| Operating system | Debian

**Comment by felixhahnweilheim** [comment]
I have the issue now with community.humhub.com

The second notification seems to be of a deleted post: 
![Screenshot_20240321_143440_Chrome](https://github.com/humhub/humhub/assets/84990763/ce7d61f3-833c-405c-a664-663bd0aaa407)

Reloading the page did not help.

**Comment by yurabakhtin** [comment]
@luke- Fixed in the PR https://github.com/humhub/humhub/pull/6983.
