### ISSUE TITLE
Cache is not deleted after deleting a value in the settings

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6871]
### What steps will reproduce the problem?

Common to the 3 following controllers:
```php
$moduleUserSettings = Yii::$app->getModule('my-module')->settings->user(Yii::$app->user->identity);
```

Controller 1:
```php
$moduleUserSettings->set('test-value', true);
```

Controller 2:
```php
$moduleUserSettings->delete('test-value');
```

Controller 1:
```php
$val = $moduleUserSettings->get('test-value');
var_dump($val);
```

### What is the expected result?

`null`

### What do you get instead?

`1`

### Additional info

Related to https://github.com/humhub/humhub/issues/6189 ?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.3

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6872

I've only added https://github.com/humhub/humhub/pull/6872/files#diff-cc3085d54fa643468beac823005c268bbb78e9cdf279cf096db4d0be3cff3ef1R197

**Comment by martincodeinc** [comment]
If you return after the delete, it will never hit   $this->invalidateCache();

**Comment by luke-** [comment]
@martincodeinc Yes, that's right. But `delete()` should have its own `invalidateCache()` anyway, if it is called directly.
