### ISSUE TITLE
Better UX for the maintenance mode administration form

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#6879]
When you put the site in maintenance mode you go to admin > setting > maintenance  and there you can only select or unselect maintenance mode.

It would be nice to also have a text input area  where you could enter a contextual message with probable duration of maintenance.

It's made this way in my other favorite CMS and it's very convenient.

**Comment by marc-farre** [comment]
It's already the case. Once "Enable maintenance mode" is checked, the message field becomes editable:

![image](https://github.com/humhub/humhub/assets/23310825/006dc220-0c3b-4957-bdf8-b75a4e01d84f)

**Comment by ArchBlood** [comment]
> It's already the case. Once "Enable maintenance mode" is checked, the message field becomes editable:
> 
> ![image](https://github.com/humhub/humhub/assets/23310825/006dc220-0c3b-4957-bdf8-b75a4e01d84f)
> 

Exactly so, although I'm not sure a lot of people understand that the checkbox field must be checked to use the text field, maybe we should add a hint for the checkbox after all.

**Comment by Gilbertdelyon** [comment]
Ah, I see :
I didn't see it because popup appears before and once the popup is displayed you think that a click on "Activate" will put directly the site in maintenance mode.
So, I would suggest this way:
- text input field is fillable in any case
- popup will appear after you click the save button of the form, if the maintenance mode checkbox was modified.

**Comment by Gilbertdelyon** [comment]
An other issue with the way it works is that once you click "Activate" in the popup you may think that the site is now in maintenance mode while it is not as long as you haven't saved the complete form.
I now realised that I made this mistake several times. Fortunately the sites I manage are not very busy.

**Comment by marc-farre** [comment]
> once you click "Activate" in the popup you may think that the site is now in maintenance mode

I agree, I've had admins report this issue to me.

@luke- Suggestions summary:
- Rename "Enable maintenance mode" to "Maintenance mode is enabled"
- Remove the modal box and add the warning text in the form, or show this warning as a modal confirmation on form submit
- Nether disable the "custom info text" field

![image](https://github.com/humhub/humhub/assets/23310825/6d0690e6-a3ee-4706-b16e-9c4ec633d91c)

![image](https://github.com/humhub/humhub/assets/23310825/93de6a67-d067-45c4-aaf4-71e4243e4cc6)

**Comment by Semir1212** [comment]
@marc-farre I'm not sure if I've understood your idea correctly, but I would do it this way: 

- Remove modal
- Leave checkbox text as is
- Add placeholder text into the input field "Add individual info text..."
- Warning below the input field "Maintenance mode restricts access to the platform and immediately logs out all users except Admins."

What do you think about that?

**Comment by ArchBlood** [comment]
> @marc-farre I'm not sure if I've understood your idea correctly, but I would do it this way:
> 
> * Remove modal
> * Leave checkbox text as is
> * Add placeholder text into the input field "Add individual info text..."
> * Warning below the input field "Maintenance mode restricts access to the platform and immediately logs out all users except Admins."
> 
> What do you think about that?

I can agree with this, of course with the confirmation notice before enabling maintenance mode, the issue here would be the save state and how @Gilbertdelyon describes how currently you must click the checkbox then the save button, I agree with the current method used, but I'm not opposed to making the checkbox and an auto save, the only issue would be also implementing the confirmation. modal

**Comment by Gilbertdelyon** [comment]
My 2 cents!
I would suggest:
Warning below the **checkbox** field:
 "Maintenance mode will restricts access to the platform and immediately logs out all users except Admins."
 
Let the hint below the text input field: 
"Add custom info text for maintenance mode. Displayed on the login page."

**Comment by Gilbertdelyon** [comment]
An other usefull thing I would suggest:
When the site is in Maintenance Mode (MM) if you visit it as admin there is no sign that MM is active. So you may forget to unset the MM.
Would it be a pain to add a warning somewhere  in the top bar or sidebar?

**Comment by ArchBlood** [comment]
> An other usefull thing I would suggest: When the site is in Maintenance Mode (MM) if you visit it as admin there is no sign that MM is active. So you may forget to unset the MM. Would it be a pain to add a warning somewhere in the top bar or sidebar?

As an admin you should see this in the sidebar;
![Screenshot_1](https://github.com/humhub/humhub/assets/35392110/77c07254-4d9f-4571-8948-7be94f72f3be)

**Comment by Gilbertdelyon** [comment]
Oups, You are right. Sorry.

**Comment by marc-farre** [comment]
@Semir1212 thanks for this summary:

> * Remove modal
> * Leave checkbox text as is
> * Add placeholder text into the input field "Add individual info text..."
> * Warning below the input field "Maintenance mode restricts access to the platform and immediately logs out all users except Admins."

That's fine.
Maybe we could also rename the checkbox "Enable maintenance mode" to "Maintenance mode is enabled".

Also, it's important not to disable the input field when the checkbox is unchecked:
![image](https://github.com/humhub/humhub/assets/23310825/56290713-2ddb-47eb-ac91-2f67745ee1d7)

And as @Gilbertdelyon suggests, the warning message should be under the checkbox and not the input field:
![image](https://github.com/humhub/humhub/assets/23310825/2f2f7f1d-adf8-45c0-b23a-795e8825f970)

The maintenance mode warning on the sidebar could be a separated issue I think.

**Comment by Gilbertdelyon** [comment]
> The maintenance mode warning on the sidebar could be a separated issue I think.

In fact I made mistake. The maintenance mode in the sidebar is already existing. Sorry

**Comment by Semir1212** [comment]
@marc-farre I would leave the checkbox text for now as the style somewhat aligns with other checkboxes. We are also currently working on a few improvements regarding the wording.

Rest is fine with me.

**Comment by marc-farre** [comment]
> @marc-farre I would leave the checkbox text for now as the style somewhat aligns with other checkboxes. We are also currently working on a few improvements regarding the wording.
> 
> Rest is fine with me.

Fine. Thanks!

PS: About "the warning message should be under the checkbox", I was thinking about an attribute hint of the checkbox, so no custom style.

**Comment by Gilbertdelyon** [comment]
Another "small" issue with maintenance mode.
As soon as maintenance mode is active I get this error in console: 
![image](https://github.com/humhub/humhub/assets/91057837/91d72652-143b-495b-86df-b66b6805f26c)

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6910

@Semir1212 

![image](https://github.com/humhub/humhub/assets/23310825/0bff9597-a1d1-4581-915d-db9ed8808c12)

![image](https://github.com/humhub/humhub/assets/23310825/b3ecede0-10fa-4b05-9fa1-c70f485f47c7)
