### ISSUE TITLE
Adding authClientCollection to config file disables standard username/password login 

### ISSUE THREAD

**Issue by martincodeinc** [humhub/humhub#6882]
### What steps will reproduce the problem?
Add the following to common.php to enable Facebook auth:
'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [

                'facebook' => [
                    'class' => 'yii\authclient\clients\Facebook',
                    'clientId' => 'xxxxxx',
                    'clientSecret' => 'xxxxxxx',
                ],
                
            ],
         ],

### What is the expected result?
Auth with Facebook working AND the standard username/password login

### What do you get instead?
Standard username/password login not working anymore

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.3
| PHP version      |  8.3
| Operating system | Debian 11

No debug info in admin/information/logging
Do i need to add the basic form auth to the authClientCollection? And do you have an example for me?

**Comment by luke-** [comment]
Did you tried this? https://github.com/humhub-contrib/auth-facebook

**Comment by martincodeinc** [comment]
I installed that module too, I started with that, but the module is not working at all, without the above settings in the config.  

if you only install the Facebook auth module without the config addition, you always get the following error in the humhub log:

Registration failed: No token (query) or authclient (session) found!

**Comment by martincodeinc** [comment]
The yii Facebook connector is trying to find an authClient session variable, which is missing when using the Facebook auth module

**Comment by ArchBlood** [comment]
I'm not having any issues on my end for the Facebook OAuth module.

**Comment by martincodeinc** [comment]
That’s all very nice, but I have setup 8 different Humhub installations the last 5 years, and I’ve never seen the module working. It’s working on one installation, that’s what I’m saying above, but then the standard login stops working. I see more closed issues with the same problem that are closed without an answer. 

I hope this problem can be solved in a more constructive way than “i don’t have any issues”.

I want to repeat my question:
Since the authCliemtCollection is working (for the Facebook part), Is the solution maybe to add the default auth to the authClientCollection ? I only don’t know which name and class to use.

**Comment by ArchBlood** [comment]
> That’s all very nice, but I have setup 8 different Humhub installations the last 5 years, and I’ve never seen the module working. It’s working on one installation, that’s what I’m saying above, but then the standard login stops working. I see more closed issues with the same problem that are closed without an answer.
> 
> I hope this problem can be solved in a more constructive way than “i don’t have any issues”.
> 
> I want to repeat my question: Since the authCliemtCollection is working (for the Facebook part), Is the solution maybe to add the default auth to the authClientCollection ? I only don’t know which name and class to use.

Does this happen with just this module or all Social Login modules? As I'm seeing no issues as long as the requirements are met;

### Requirements
- PHP 7.4+
- `allow_url_fopen` **MUST** be enabled.

**Comment by martincodeinc** [comment]
I have no other social modules enabled. Allow_furl_open is enabled.

**Comment by martincodeinc** [comment]
Facebook auth module:
Error in humhub log: 
Registration failed: No token (query) or authclient (session) found!

The yii Facebook connector is trying to find an authClient session variable, which is missing when using the Facebook auth module

**Comment by luke-** [comment]
Unfortunately not, can you please open a new issue there. Thank you!
