### ISSUE TITLE
Allow adding an anchor tag to a permalink

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6898]
### Is your feature request related to a problem? Please describe.

In, e.g, wiki page texts, title HTML elements have IDs.
This allows to create a direct link to the title in the text:
`https://my-humhub.com/s/space-name/wiki/page-title#title-in-the-text`

But if the title of the wiki page changes, the link doesn't work anymore.
That's why it's better to share a permalink.
So we would need to be able to share:
`https://my-humhub.com/content/perma?id=67354#title-in-the-text`

### Describe the solution you'd like

When the permalink redirects to the page, e.g. `https://my-humhub.com/s/space-name/wiki/page-title`, it should add the anchor to the redirection to have `https://my-humhub.com/s/space-name/wiki/page-title#title-in-the-text`

And `https://go.humhub.com?url=...` should also be able to deal with `#` anchors in the URL.

**Comment by marc-farre** [comment]
@luke- If you agree with the idea, I can work on it.

**Comment by luke-** [comment]
@marc-farre What do you think about the option of creating wiki page URLs in the format `/s/some-space/wiki/2422/Some+Test+Page+Title`. We could always use the ID for the link. This could possibly also be a preparation for the request to allow several wiki pages with the same title.

Or did I missed something here?

**Comment by marc-farre** [comment]
Yes, good Idea. Thanks!
So I close this issue and will work on https://github.com/humhub/wiki/issues/256

**Comment by luke-** [comment]
@marc-farre Ok, but I don't know exactly when we will be able to implement this feature. There is also still one unclear points.
