### ISSUE TITLE
Change the year to 2015 and width to 100px

### ISSUE THREAD

**Issue by jeanette2091** [humhub/humhub#690]
It would be nice if you could change this:

/protected/modules_core/admin/views/about/index.php
© 2010 - 2014 The HumHub Project ----> © 2010 - 2014 The HumHub Project or maybe you can use <?php echo date("Y") ?> instead. 
Like this: (© 2010 - <?php echo date("Y") ?> The HumHub Project)

/protected/modules_core/admin/views/space/index.php
'htmlOptions' => array('width' => '90px'), ----> 'htmlOptions' => array('width' => '100px'),

/protected/modules_core/admin/views/user/index.php
'htmlOptions' => array('width' => '90px'), ----> 'htmlOptions' => array('width' => '100px'),

Thank you! :)

**Comment by ziegenberg** [comment]
Why do you need 100px wide columns? There's enough space for the three buttons (each 25px wide).

**Comment by jeanette2091** [comment]
No not on my website.

**Comment by ziegenberg** [comment]
Could you provide us with a screenshot?
