### ISSUE TITLE
Yiic execution of cronjob via ssh outputs error

### ISSUE THREAD

**Issue by butterflyx** [humhub/humhub#691]
After upgrading to HumHub v.0.10.1

Due to the message in the admin panel, that the cronjob was never executed, I tried to find the prob via SSH.

The execution of the cron command terminates with an error message:
(uiserver):protected > yiic cron hourly
X-Powered-By: PHP/4.4.9
Content-type: text/html

<br />
<b>Parse error</b>:  syntax error, unexpected T_STRING, expecting T_OLD_FUNCTION or T_FUNCTION or T_VAR or '}' in <b>/homepages/htdocs/humhub/protected/vendors/yii/YiiBase.php</b> on line <b>62</b><br />

**Comment by luke-** [comment]
Not sure this is related to 0.10.1

Seems you are using a very old PHP version on console
X-Powered-By: PHP/4.4.9  (We require at least 5.4)

**Comment by butterflyx** [comment]
Thank you for giving a hint in the right direction. Not an issue of humhub but 1&1, one of the biggest hosters in Germany. 
If using a 1&1 shared hosting environment for humhub, one can specifiy the PHP-Version to use on CLI by using the command php+version e.g. php5.5-cli

My initial example:
`(uiserver):protected > php5.5-cli yiic cron hourly`
works perfect.
