### ISSUE TITLE
User - Profile - Country Field without value

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6919]
- Create a "Country" profile field type
- Select a Country
- Go to About Page, the Country is empty

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6937, I think it was done [here](https://github.com/humhub/humhub/pull/6809) by mistake because I don't think we should store in DB full country name like "Germany" instead of previous way where we stored only a country code `DE`.

**Comment by luke-** [comment]
@yurabakhtin We should only store the country code in the database and display the localized country name (if possible).
Is that not the case? If so, we should reconsider.

One problem, when storing the code, could be the search for a country name.

**Comment by yurabakhtin** [comment]
@luke-

> We should only store the country code in the database and display the localized country name (if possible).
> Is that not the case? If so, we should reconsider.

Yes, after my current fix we store in DB only a country code, and it worked this way before the changes from the PR https://github.com/humhub/humhub/pull/6809.
I think it was a mistake to use a key in the array as country full name:
`$items[Iso3166Codes::country($code)] = Iso3166Codes::country($code);`

> One problem, when storing the code, could be the search for a country name.

Yes, it is a problem, because there is a simple SQL query like `profile.country LIKE 'keyword'`, i.e. if we store only `DE` then we cannot find a user by keyword `Germany`.

**Comment by luke-** [comment]
@yurabakhtin  Ok perfect. I just wanted to make sure that we really only save the country code. Then that's fine.

Would be cool if you could try this wordaround, then we would have solved the search issue.

**Comment by yurabakhtin** [comment]
> Would be cool if you could try this wordaround, then we would have solved the search issue.

@luke- Done in the commit https://github.com/humhub/humhub/pull/6937/commits/11c2f3f16d98b7a55f88fca032fcf5fffc6f85c4.

**Comment by marc-farre** [comment]
@yurabakhtin Thanks for the fix.
Is there a migration planned to convert full country names to ISO 3166 codes in the DB (for profiles created or updated during the bug)?

**Comment by yurabakhtin** [comment]
> Is there a migration planned to convert full country names to ISO 3166 codes in the DB (for profiles created or updated during the bug)?

@marc-farre Good question! I see a full country name was stored in DB from `Iso3166Codes::country($code, $translate = true)`, i.e. a country name was stored as translated, so I am afraid it may be stored as "France" and "Frankreich" and "Francia" and etc. I don't think it will be a good idea to run a search process for a country code between 250 countries and 47 languages.

**Comment by marc-farre** [comment]
@yurabakhtin Maybe we could do a migration for the default language only? If not, as I have to do it for some instances I manage, I'll share the code here.

**Comment by marc-farre** [comment]
@yurabakhtin Thanks very much! Tested, it works fine.

**Comment by yurabakhtin** [comment]
@marc-farre Have you already started a PR for the migration code or should I do this?

**Comment by marc-farre** [comment]
@luke- @yurabakhtin https://github.com/humhub/humhub/pull/6956
