### ISSUE TITLE
Private Spaces selected to Receive 'New Content' Notifications in the administration settings shouldn't appear in the notification settings of users who are not members of the space

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6931]
### What steps will reproduce the problem?

Select a private Space in the notifications' administration settings:
![image](https://github.com/humhub/humhub/assets/23310825/a298fd5d-d3ce-465b-b381-6ea31d990a4f)

Open the notification settings of a user who is not members of the "Private" space

### What is the expected result?

![image](https://github.com/humhub/humhub/assets/23310825/fdc15e34-1f37-44b3-b1c8-75a0e44abdee)

### What do you get instead?

![image](https://github.com/humhub/humhub/assets/23310825/0ba332c6-3627-4a0c-b941-9c7c4668472f)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16-beta.1

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6935.
