### ISSUE TITLE
When a public space is selected in "Receive 'New Content' Notifications", notifications about private content are sent to users who are not members of the space

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6932]
### What steps will reproduce the problem?

User 1 is a member of "Public" space.
User 2 is not a member of this space.

1. User 2 navigates to the account Notification Settings and adds the "Public" space to "Receive 'New Content' Notifications for the following spaces":

![image](https://github.com/humhub/humhub/assets/23310825/89cc19af-c37e-4007-877e-36b3d05a8219)

2. User 1 creates a new private post

### What is the expected result?

User 2 isn't notified about the new private post

### What do you get instead?

User 2 receives a notification. When clicking on it, this page displays:

_Oooops... It looks like you may have taken the wrong turn._

### Additional info

Related to https://github.com/humhub/humhub/issues/3767 ?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16-beta-1

**Comment by marc-farre** [comment]
@yurabakhtin I've done some more tests:

1/ If "Default content visibility" is private, it's fine (no notification sent to non-member)

2/ If "Default content visibility" is public:
1. Create a post
2. Change it to private
3. `php yii queue/run -v`

Then the bug occurs.

So in fact, it's more or less a bug, because in fact if you change a content to private after publishing it, even solving this issue, the notification can be sent if the cron job is processed before changing it to private.

@luke- Should we:
- close this issue (I think we can)?
- or check if the content is still "readable" before sending the notification?

**Comment by yurabakhtin** [comment]
@luke- 

> - or check if the content is still "readable" before sending the notification?

If we need it we could add the code for the `humhub\modules\content\notifications\ContentCreated`:

```php
public function beforeMailSend(MessageInterface $message)
{
    return parent::beforeMailSend($message) && $this->source->content->canView($this->record->user->id);
}
```

**Comment by luke-** [comment]
@yurabakhtin @marc-farre So, if it's just this method, I would include such a readable test.
Or is there something against it?

**Comment by yurabakhtin** [comment]
@luke- The method [BaseNotification::beforeMailSend](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/notification/components/BaseNotification.php#L583-L593) is called only before send email ny [MailTarget](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/notification/targets/MailTarget.php#L78-L80):

```php
if ($notification->beforeMailSend($mail)) {
    $mail->send();
}
```

I.e. if we will add the code to the `humhub\modules\content\notifications\ContentCreated` then it will restricts a sending of the email about new Private Content if user cannot view it.

**Comment by luke-** [comment]
Hmm, if this only affect mail but other e.g. web notifications remain, I wouldn't do this solution as it only works partially.

I would rather close the issue. A better error message for content that is not found or cannot be displayed is also planned.

One solution could possibly be to completely delete all notifications for users who no longer have view permission when the visibility is changed.

But not sure this is really needed.

**Comment by marc-farre** [comment]
> A better error message for content that is not found or cannot be displayed is also planned.
> delete all notifications for users who no longer have view permission when the visibility is changed.

I agree.
