### ISSUE TITLE
Space mentioning with other symbol 

### ISSUE THREAD

**Issue by Lazuis** [humhub/humhub#694]
If you write @ -user- you mention to a user. It will be interesting if there will be an option to mention spaces with other symbol.

**Comment by hugochinchilla** [comment]
I would find this very useful, +1

**Comment by JeXawoW** [comment]
+1

**Comment by WASasquatch** [comment]
Well, it should just be with the same symbol like everything site. "@" meants "at".

**Comment by luke-** [comment]
It's possible to also mention a space using the "@" symbol
