### ISSUE TITLE
Track downloads and views 

### ISSUE THREAD

**Issue by sir1ke** [humhub/humhub#6943]
### Is your feature request related to a problem? Please describe.
I want to know how often a file has been accesed from the stream to get an idea of the popularity of the file

### Describe the solution you'd like
Track access/downloads from news stream aswell (for pictures/audios/videos that get viewed i'd wish for a separate counter)

### Describe alternatives you've considered
Uploading files only through files module (some files need more context than the regular stream entry)

**Comment by Gilbertdelyon** [comment]
@sir1ke 
That's right, I have developped a custom module that registers files downloads. it's presently working on 2 small sites, but not published. Not  professional coding but it works!
it registers only downloads of files managed by "cfiles" module
You can select the mime type of the files you want to register (all, none, one of, none of, not images,...)
The data( file name, user name, date, link to parent folder) of each download are registered in a file. Should be ported to a db table for a large buzy site.
You can display a table of the downloads in admin pages and download it in csv format.
**Interface is in in french. No time for translation these days,**
If you are interested, please let me know
