### ISSUE TITLE
Display modules Manuals and Readme from admin > modules page

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#6948]
### Is your feature request related to a problem? Please describe.
Unless I didn't find how to, it is not possible to display the Readme.md , Manual.md , Changelog.md directly from the **admin > Modules** page.
This would be very helpfull and I dont think it would be a heavy work to implement such a functionality because the data is already available in the files.

### Describe the solution you'd like
New items in the module dropdown menu (Readme, Manual, Changelog,

**Comment by ArchBlood** [comment]
I believe the reason why they weren't added is because of API call overload.

**Comment by Gilbertdelyon** [comment]
> >  because of API call overload.

Are you sure
If some items are added to the module dropdown menu the user will call only one file at a time. The files are already in the module. I have in mind a simple controller + a bit of styling could do this.
![image](https://github.com/humhub/humhub/assets/91057837/a9bf5c8b-a37a-45ef-9172-e38707d952df)

**Comment by ArchBlood** [comment]
> > > because of API call overload.
> 
> Are you sure? If some items are added to the module dropdown menu the user will call only one file at a time. The files are already in the module. I have in mind a simple controller + a bit of styling could do this. ![image](https://private-user-images.githubusercontent.com/91057837/322131942-f7ed6ca0-bf09-47e0-b0dd-98d6a665dfc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTc4NjgsIm5iZiI6MTcxMjk1NzU2OCwicGF0aCI6Ii85MTA1NzgzNy8zMjIxMzE5NDItZjdlZDZjYTAtYmYwOS00N2UwLWIwZGQtOThkNmE2NjVkZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIxMzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYzE2NDE3M2U4YTVjMmM3N2RlMmFiNmNhMmU1MTY1M2VmMDMzNjM1OGUyNDA4MmQ5MjAxNmMzNTJiOWE1ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.45xxF3WS5cNBOcsjmDdufunC-nllrgMTLKSm5cCy68k)

I believe a little discussion was made in #6848 if you'd like to continue there?

**Comment by marc-farre** [comment]
@Gilbertdelyon Yes, @ArchBlood is right, the discussion is here: https://github.com/humhub/humhub/issues/6848
Maybe this issue can be closed.
