### ISSUE TITLE
Icon::get() injection leads to HTML Output

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#6952]
### What steps will reproduce the problem?
Currently I'm facing some issues when trying to inject the `Icon::get()` method for icons through the Verified module, we use the Icon class for the icons within our widget class `VerifiedIcon` this works with the method of extending an existing widget class through `EVENT_CREATE` but this also requires us to also extend the existing view as well, I've currently gotten an example of our module to implement this through `EVENT_BEFORE_RUN` but the issue is that the `Icon::get()` function won't allow the use case we need.

### What is the expected result?
The `Icon::get()` method should allow to be rendered correctly.

### What do you get instead?
HTML output is displayed `<i class="fa fa-check-circle tt" title="Verified" aria-hidden="true" role="img" style="color: #458e56;"></i><span class="sr-only">Verified</span>`

### Additional info
I've tried everything from encoding to decoding even tried multiple hack-ish methods without any ability to use the `Icon:get()` method in a way so that we don't need to rely on core view manipulation through `EVENT_CREATE`.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.0-beta.2
| PHP version      | 8.1.18
| Operating system | CloudLinux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
For better understanding of what I mean here's the screenshot of how it's rendered;

As you'll see it's injected correctly but the output is returned as HTML due to `Icon::get()`
![Screenshot_1](https://github.com/humhub/humhub/assets/35392110/07405a93-edd2-4985-8f41-090e6ca2b26f)

**Comment by ArchBlood** [comment]
A simple solution would be removing `Html::encode()` from the view file, I don't really see any need for it anymore but if the HumHub staff still think it's needed we'll have to find another possible solution which requires looking into the `Icon::get()` method.
https://github.com/humhub/humhub/blob/619191f8715c575aa4b5e612ad92acc99af40cf9/protected/humhub/modules/content/widgets/views/containerProfileHeader.php#L55

**Comment by yurabakhtin** [comment]
@ArchBlood I think the `Html::encode()` is used there in order to avoid js script like this:

![alert](https://github.com/humhub/humhub/assets/6995524/a97b2f78-468b-4075-9ff9-a7a47fd2532f)

**Comment by felixhahnweilheim** [comment]
Yes, but it could be moved from the view file into the widget class (`init()` function) where `$title` is defined.

**Comment by yurabakhtin** [comment]
@felixhahnweilheim Yes, you are right, I have done this in the PR https://github.com/humhub/humhub/pull/6955.
@ArchBlood After the PR you can append an icon to a title in the event `EVENT_BEFORE_RUN`.
@luke- Please merge it.

**Comment by ArchBlood** [comment]
> @felixhahnweilheim Yes, you are right, I have done this in the PR #6955. @ArchBlood After the PR you can append an icon to a title in the event `EVENT_BEFORE_RUN`. @luke- Please merge it.

Works very well for the needed use case.

**Comment by luke-** [comment]
PR is mreged.
