### ISSUE TITLE
Non-editable profile fields are not displayed

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#6960]
HH 1.15.4.

- Create new profile field
- Mark it as not-editable

--> Profile field is not shown in users profiles; Not shown as "People" filter regardless of settings.

Woraround: Temporarily mark it as editable and save the profile data.

**Comment by luke-** [comment]
@Semir1212 I'm not sure if this is a bug.

- As an admin, I can edit the "Not editable" field for the users via the user administration.

- As soon as there is a value, the field is also displayed. Other fields such as "Youtube URL" also remain hidden until the user/admin enters a value.

- The directory filter is not displayed as long as there are no values for filtering. As soon as at least one user has filled a value in the profile field, it is also displayed.

**Comment by Semir1212** [comment]
@luke-  You have misunderstood me. The field is not displayed regardless of whether there is a value or not. 

It only becomes visible once you mark the profile field as "editable", edit the users profile and save it again.
