### ISSUE TITLE
Directory Filter - Remove Followers from Status if Following is disabled in Module

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6962]
![image](https://github.com/humhub/humhub/assets/4736168/68b16c70-f048-4927-8118-6d6bc448e631)

**Comment by ArchBlood** [comment]
@yurabakhtin does this also fix the current issue when it comes to User Groups as well?
![Screenshot_1](https://github.com/humhub/humhub/assets/35392110/c467a0c9-4fd8-41c9-aebe-44648b43e5ea)

**Comment by yurabakhtin** [comment]
@ArchBlood Thank you for the report!
@luke- Fixed in the PR https://github.com/humhub/humhub/pull/7004, sorry, it was my error, I forgot to add the filter `show_at_directory = 1` for case when people is filtered.
