### ISSUE TITLE
Report Feature

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#697]
Using the "Drop Down" menu for posts there should be a feature to report a post. This should show up in the administration center under a "Reports" page. 

The "Report Post" link should bring up a light box which contains a category for the report. Whether it's offensive material, miscategorized, prohibited content, custom input, etc. 

Under a users profile there should also be a "Report User" link somewhere. These reports should also be sent to the "Reports" page. 

The "Report User" link should also bring up a light box which contains a category for the report. Whether it's offensive material, prohibited content, custom input, etc. 

Additionally Administrators could get a notification regarding Report Activity. In light of high volume HumHub installations, this notification should be updated with a current count, and not spam the admins notifications each time a report is made. 

Admin-related notifications should have a sticky priority over normal notifications, but only contain one notification per category (reports, user approvals, etc) and update with a count of entries needing review.

**Comment by timvango** [comment]
+1

**Comment by luke-** [comment]
Can you please resubmit the request here: https://github.com/humhub/humhub-modules-reportcontent

**Comment by WASasquatch** [comment]
No problem.
