### ISSUE TITLE
Upload dropdown on mobile

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/humhub#6973]
The File Upload dropdown overlaps the screen.

## 1. issue
- open community.humhub.com on a phone
- create a post
- click the upload dropdown (below the text field)

-> The dropdown overlaps the screen on the right side
![Screenshot_20240429_163002_Chrome.jpg](https://github.com/humhub/humhub/assets/84990763/d881304a-0793-4205-ba06-9c10f7b7d401)

## 2. issue
same place but click the upload dropdown from the ProseMirror editor menubar
-> the dropdown overlaps on the left (and is not readable)

![Screenshot_20240429_163416_Chrome.jpg](https://github.com/humhub/humhub/assets/84990763/b6ed9e6d-bba8-46c2-bb55-2e671971a0f0)

### Additional info
tested with Samsung Galaxy A51

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by felixhahnweilheim** [comment]
1. issue already happens in HumHub 1.15
It is because the German "Abschicken" is longer than "Submit".

2. issue is new in HumHub 1.16 and also happens with English language.

**Comment by yurabakhtin** [comment]
@luke- @felixhahnweilheim PR https://github.com/humhub/humhub/pull/6982:

![dropdown-attachment](https://github.com/humhub/humhub/assets/6995524/0c15b049-db87-426f-b9d9-7e9c59959ac0)

![dropdown-richtext](https://github.com/humhub/humhub/assets/6995524/cc25e05d-9d50-4ed0-991c-16207f8416a4)
