### ISSUE TITLE
Enabling a module from the marketplace throw "The requested resource could not be found." on HumHub 1.16

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6978]
### What steps will reproduce the problem?

1. Install HumHub 1.16.0-beta.2
1. Go to the marketplace page: `/marketplace/browse`
2. Click "Install" on any module
3. Click "Enable now" in the modal box

### What is the expected result?

The module is enabled and no error is thrown.

### What do you get instead?

The module is enabled but this error is thrown:

The requested resource could not be found.

```json
{
    "url": "/marketplace/browse/enable",
    "status": 404,
    "response": {
        "error": true,
        "message": "Could not find the requested module!"
    },
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"error\":true,\"message\":\"Could not find the requested module!\"}",
        "responseJSON": {
            "error": true,
            "message": "Could not find the requested module!"
        },
        "status": 404,
        "statusText": "Not Found"
    },
    "dataType": "json",
    "error": true,
    "message": "Could not find the requested module!",
    "errorThrown": "Not Found",
    "validationError": false
}
````

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.0-beta.2

**Comment by marc-farre** [comment]
@yurabakhtin Additional, but certainly linked issue: the initial module migration is not done.
I need to do it manually: `php yii migrate/up --includeModuleMigrations=1`

**Comment by yurabakhtin** [comment]
@marc-farre @luke- Fixed in the PR https://github.com/humhub/humhub/issues/6978.
It didn't work for modules without migration or if a module has a redeclared method `enable()` with returned `null` or `void`.

**Comment by marc-farre** [comment]
@yurabakhtin thanks for your quick fix!
@luke- PR tested, works perfectly.
