### ISSUE TITLE
Add translation for LatAm Spanish

### ISSUE THREAD

**Issue by dvn0** [humhub/humhub#6987]
### Is your feature request related to a problem? Please describe.

Currently Spanish translation is only for European/Castilian/Peninsular Spanish. It would be nice to have an option for Latin American Spanish, similar to how there is "English (UK)" and "English (US)", though this would be more broad. There is already an offer to help with translation to this dialect of Spanish - See: https://translate.humhub.org/content/perma?id=86299

### Describe the solution you'd like

A new language target in this repo
A new translation space for "ES LatAm" on translate.humhub.org

**Comment by luke-** [comment]
What would be the ISO 639-1 code for the language? `es-mx`?

**Comment by ArchBlood** [comment]
> What would be the ISO 639-1 code for the language? `es-mx`?

I believe it to be `es-419`? As `es_MX` would be Mexico.

**Comment by dvn0** [comment]
[From wikipedia](https://en.wikipedia.org/wiki/Language_code)

> es-419 – Spanish appropriate for the Latin America and Caribbean region, using the [UN M.49 region code](https://en.wikipedia.org/wiki/UN_M.49)

**Comment by dvn0** [comment]
Anything ever happen with this?

**Comment by luke-** [comment]
Just added the language to the `develop` branch. 

Seems there are problems with the `es-419` language code. The language cannot be selected in the account settings or translation tool.

**Comment by ArchBlood** [comment]
> Just added the language to the `develop` branch.
> 
> Seems there are problems with the `es-419` language code. The language cannot be selected in the account settings or translation tool.

Seems to me the reason behind this is that Yii can't have numbers at the end of the language code (i.e. `-123`) because they're not read.

**Comment by luke-** [comment]
Fyi, we will also adjust the translation community a bit to improve the translatation derived languages.
