### ISSUE TITLE
User::getSearchAttributes() removed in HumHub 1.16

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7008]
`User::getSearchAttributes()` has been removed from HumHub 1.16, but it's not documented and it wasn't a deprecated method:

https://github.com/humhub/humhub/commit/cc832c5e753c1913c8a36080e2e634263e0a2a4f#diff-d3a4745ae7c92bb2ed3212a38c146f5f29268cf40a693d007f752f679a1f52abL787

I think it should be put back as a deprecated method, otherwise `Yii::$app->user->identity->getSearchAttributes()` doesn't work anymore, and some modules are not updated with this removal.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16

**Comment by ArchBlood** [comment]
If I remember correctly I had a similar issue (i.e. #6941) in turn I just removed `getSearchAttributes()` from my model completely. Ideally this should still be possible to be used in a model just requires more coding than it should.

**Comment by luke-** [comment]
The method was used by the old search and I expected it to be used internally only.

Can you give an example of an intended use of the method?

Nevertheless, we should add this to the “MIGRATE-DEV.md”. I would prefer to keep the method removed.  (Depending of UseCases)

**Comment by marc-farre** [comment]
@luke- I see. I was using it in my modules, but they are now all updated.
I've done a quick check to most popular modules, they don't use it.
So it's fine!

 “MIGRATE-DEV.md” update: PR https://github.com/humhub/humhub/pull/7009
