### ISSUE TITLE
How to do cronjob via http

### ISSUE THREAD

**Issue by Betacarotin** [humhub/humhub#701]
I run humhub on a managed Server where I can not access the cron tab. So i run the yiic.php file with my cronjobmanager. 
Bit in Humhub it says in the cronjob menu: 
Letzte Ausführung (stündlich): Niemals 
Letze Ausführung (täglich): Niemals

When I start the yiic.php manually it says:
Yii command runner (based on Yii v1.1.15) Usage: [parameters...] The following commands are available: - cache - cron - emailing - integritychecker - message - migrate - module - search_optimize - search_rebuild - shell - space - update - webapp To see individual command help, use the following: help

I guess it waits for some "command"? 
For what is that cronjob and how can it running? 

Sorry, I know my questions must sound some kind of stupid to you-but I can not do better actually, I am at the ultranoob status and try to get out, so please give me a hint.

**Comment by luke-** [comment]
Currently cronjobs only possible via command line

We try to support cronjobs via http in future
 https://github.com/humhub/humhub/issues/98

**Comment by Betacarotin** [comment]
What is this cronjob doing? Or can it be a problem if it is not working?

**Comment by benpowell** [comment]
Just another vote up for this feature. My hoster does not support cron or SSH without paying an extra 14 EUR a month for a virtual server.
