### ISSUE TITLE
Rich text tables: Vertical align top instead of middle

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7010]
Discussion: https://community.humhub.com/s/feature-requests/post/post/view?id=16591

### Is your feature request related to a problem? Please describe.

![image](https://github.com/humhub/humhub/assets/23310825/572b48f1-0803-49b9-bec3-08874b43d6c2)

### Describe the solution you'd like

![image](https://github.com/humhub/humhub/assets/23310825/7cc8a113-f3e4-48b6-bb44-521f8d8ebba5)

**Comment by marc-farre** [comment]
@luke- If you think it's a good idea, I can create a PR for it.

**Comment by luke-** [comment]
@marc-farre Yes, sounds good for me.

**Comment by luke-** [comment]
@marc-farre Thanks!
