### ISSUE TITLE
Space creation notification to users allowed to manage spaces

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7037]
### Is your feature request related to a problem? Please describe.

When a space is created by a user not allowed to manage spaces, we want to check if it's relevant, well configured and no spam.

### Describe the solution you'd like

Users allowed to manage spaces are notified when a new space is created.

### Describe alternatives you've considered

Spaces are created as a hidden state, then a user who is allowed to manage spaces must validate them.

_Keywords: `space create creation new notify notification admin manager`_

**Comment by marc-farre** [comment]
@luke- would you accept a PR with a new notification to users allowed to manage space each time a new space is created?

**Comment by luke-** [comment]
Notifying Space Managers when a non-Space Manager/Admin creates a Space sounds useful to me. 

@humhub/team Thoughts on this?

**Comment by yurabakhtin** [comment]
I confirm such notifications can be useful.

**Comment by gevorgmansuryan** [comment]
yeah, would be nice!

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/7057

Email notification:
![image](https://github.com/humhub/humhub/assets/23310825/919df53e-cc17-441b-be16-21e4f7523d87)

Web notification:
![image](https://github.com/humhub/humhub/assets/23310825/19f05a1a-12ec-41eb-bcc3-3498a9bc6577)

Notification settings (visible only for space managers):
![image](https://github.com/humhub/humhub/assets/23310825/02775a84-a73b-4073-806c-d9bbcadc12c7)

**Comment by luke-** [comment]
@marc-farre Thanks, looks good!

@Semir1212 Text ok?

**Comment by Semir1212** [comment]
@marc-farre Please remove the "a" in the sentence.

**Comment by marc-farre** [comment]
> remove the "a" in the sentence

@Semir1212 thanks! Done in commit https://github.com/humhub/humhub/pull/7057/commits/6b162e09eab02b949309992ace230e9f0ae717d8
