### ISSUE TITLE
Reduce space and user banner image size in space and people directories

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7039]
### Is your feature request related to a problem? Please describe.

When browsing the space directory (e.g. https://community.humhub.com/spaces) or the people directory (e.g. https://community.humhub.com/people), banner images of space/user cards are 1134px width and 192px height

### Describe the solution you'd like

Create an additional version of the banner image with 400 x 130 px and 60% JPEG compression.

**Comment by marc-farre** [comment]
@luke- if you agree with the idea, I've started a PR to show how we could solve this issue: https://github.com/humhub/humhub/pull/7040/files

Result with it:
![image](https://github.com/humhub/humhub/assets/23310825/8ff22ab1-40fc-47f5-8612-9c5cd8d48d85)

This PR is missing a migration to create the "thumb" version of all existing banners.
I'll do it as soon as you approve the idea.

**Comment by samuk** [comment]
Thanks Marc. One of the motivations for this might be to reduce the page load impacts from both a UX and [climate point ](https://ecograder.com/report/Uu3d6UG9AEp6IYpp59kxer2B)to view

**Comment by ArchBlood** [comment]
> Could WebP be a better alternative to JPEG, considering that even Google recommends it for faster page loads?

I agree with switching to WebP over JPEG/JPG, advantages would be that WebP can provide what PNG, JPEG/JPG & GIF provides with lossy and lossless compression, this means smaller file size without loss of image quality.

**Comment by luke-** [comment]
I'll close this, as the PR will be merged in v17.

@marc-farre Thanks!
