### ISSUE TITLE
Problem with initial page of instalation. 

### ISSUE THREAD

**Issue by munenedenis** [humhub/humhub#705]
First page of installation opens as incomplete html file, I can not click next to proceed with installtion  This is what i see. 
![ongoza](https://cloud.githubusercontent.com/assets/1670665/6105696/fef7ba02-b06a-11e4-986b-85dcde141b3c.png)

**Comment by luke-** [comment]
Check your PHP Version. We require at least 5.4

**Comment by munenedenis** [comment]
I am using PHP version 5.4.24 and still getting the problem

**Comment by aneesh84** [comment]
Me too! i am also using php 5.4.24 and getting the same error. What could be the issue?

**Comment by aneesh84** [comment]
Anyone please help!

**Comment by jdezio** [comment]
same here....
