### ISSUE TITLE
Help needed: HumHub is getting very slow

### ISSUE THREAD

**Issue by Betacarotin** [humhub/humhub#707]
Since user increased from 5 to 14 humhub is nearly not useable anymore, it is so slow that some pages load about 20 seconds. I think it´s something I´ve done wrong but I can´t find the mistake. 
Could this be because of the not working cron jobs? (I can not access Cron tab in my Server package)

**Comment by bastrian** [comment]
Well, it could be Chronjobs, Database Issue or something with the Apache Server itself. It is hard to say without Logs or anything. It would be helpful if you give us more information.

**Comment by filipemiguel** [comment]
Also check this.
Slows down when I'm not connected to the internet.
When I'm connected to the internet works well.
I have not even started to change the code.

I like very much the Humhub.
Best Regards,
Filipe

**Comment by WASasquatch** [comment]
@filipemiguel It's probably slow because of requests to HumHub and other verification on links waiting to timeout if the server has no access to the web.

**Comment by filipemiguel** [comment]
Meanwhile I noticed that an email is sent for each chat´s message. Being offline the humhub is waiting to timeout if the server has no access to the web. So everything is ok.
Best Regards,
Filipe
