### ISSUE TITLE
Text in lists is smaller than in paragraphs

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7074]
### Is your feature request related to a problem? Please describe.

In messenger (and certainly other places):

![image](https://github.com/humhub/humhub/assets/23310825/4073c6ae-5cb1-4af7-aa11-54a04ad7850c)

On the stream, size is fine (13 px).

### Describe the solution you'd like

Remove `font-size: 12px;` here:
https://github.com/humhub/humhub/blob/d0a7a3915ab87c393ff335563159c35a3de4cddc/static/less/media.less#L10-L10

Or is there a reason to have 12 px for media lists?

**Comment by Eladnarlea** [comment]
@marc-farre we can certainly remove the 12px for media lists and correct it to 13px. @luke- is that okay with you?

**Comment by luke-** [comment]
@Eladnarlea @marc-farre Fine for me!

**Comment by marc-farre** [comment]
@Eladnarlea @luke- Thanks. PR https://github.com/humhub/humhub/pull/7077
