### ISSUE TITLE
System show Testmode after Update to Version 1.16.0

### ISSUE THREAD

**Issue by MarcusBauch** [humhub/humhub#7080]
After updating to 1.16.0, HH suddenly displays the message with the test version. The system has been running for three years and the settings in config.php have remained unchanged since then.

Debian Buster, PHP 8.3.8

**Comment by ArchBlood** [comment]
Make sure that your `index.php` looks like the following to disable debug & dev modes.

```php
<?php

/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) 2017 HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */

// comment out the following two lines when deployed to production
use humhub\helpers\DatabaseHelper;

//defined('YII_DEBUG') or define('YII_DEBUG', true);
//defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/protected/vendor/autoload.php');
require(__DIR__ . '/protected/vendor/yiisoft/yii2/Yii.php');


$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/protected/humhub/config/common.php'),
    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);

try {
    (new humhub\components\Application($config))->run();
} catch (\Throwable $ex) {
    if (null === DatabaseHelper::handleConnectionErrors($ex)) {
        throw $ex;
    }
}
```

**Comment by yurabakhtin** [comment]
I guess it occured because the file `index.php` was updated [here](https://github.com/humhub/humhub/pull/6512/files#diff-7413d6453f901e939bbd840c8f0d1c7b20c2ca0e7f71741e4e07c6cf036f16c0) and on update it was overwritten.
Maybe we should comment the lines by default.

**Comment by MarcusBauch** [comment]
Hej!

Yes, index.php was overwritten ^^ ...i stupidly only looked in the configuration directory. Thanks a lot. Works now.

**Comment by yurabakhtin** [comment]
@luke- I have tested the upgrade from 1.15.6 to 1.16.0 and I confirm the file `index.php` is overwritten because it was updated to new version. The file `update.json` contains:

```
        "index.php": {
            "changeType": "M",
            "newFileMD5": "348fcb23e5aceb94c64ff344b19fa617",
            "oldFileMD5": "5fdf271fb1728d4816e801f4a1884271"
        },
```

Do you think we should somehow to restore previous values of `YII_DEBUG` and `YII_ENV` in the file `index.php` after the file was updated?

**Comment by luke-** [comment]
@yurabakhtin Thanks, I've created an issue for it.

**Comment by diskbuster** [comment]
i have still an issue when switching to prod mode.
my theme looks very gliched in prod mode.
when get back by uncommenting the YII_DEBUG and YII_ENV values to dev, the page looks fine again.

a cache clear in prod mode doesn't  help.

what can it be?
