### ISSUE TITLE
See space content without beeing a member of the space

### ISSUE THREAD

**Issue by gallandp** [humhub/humhub#709]
Hey guys,

Is there any option to see the space content without beeing a member of the space? Using the follow function isn't an option because when I use it, I'll see all the posts from the spaces I'm following directly on my dashboard.

It would be great if I have the chance to browse spaces without getting their content on my dashboard.

Thanks a lot!
Philipp

**Comment by luke-** [comment]
Possible since 0.11

**Comment by gallandp** [comment]
Hi Luke,

how can I do that? I can't find a way to browse the spaces without beeing a member.

Regards
Philipp
