### ISSUE TITLE
Content Search rebuild on HumHub 1.16.0 crashes in command line

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7090]
### What steps will reproduce the problem?

Post: https://community.humhub.com/s/general-discussion/post/post/view?id=16710

```sh
php yii content-search/rebuild
```

### What is the expected result?

Search rebuild

### What do you get instead?

```
Exception 'TypeError' with message 'humhub\modules\content\models\Conte nt::getModel(): Return value must be of type humhub\modules\content\components\ContentActiveRecord, n ull returned'

in /protected/humhub/modules/content/models/Content.php:218

Stack trace:

#0 /protected/humhub/modules/content/search/driver/MysqlDriver.php(58): humhub\module s\content\models\Content->getModel()

#1 /protected/humhub/modules/content/services/ContentSearchService.php(34): humhub\mo dules\content\search\driver\MysqlDriver->update(Object(humhub\modules\content\models\Content))

#2 /protected/humhub/modules/content/commands/SearchController.php(43): humhub\module s\content\services\ContentSearchService->update(false) #3 [internal function]: humhub\modules\content\commands\SearchController->actionRebuild()

#4 /protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Arr ay, Array)

#5 /protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->ru nWithParams(Array)

#6 /protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->r unAction('rebuild', Array)

#7 /protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAc tion('rebuild', Array)

#8 /protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runA ction('content-search/...', Array)

#9 /protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Applicati on->runAction('content-search/...', Array)

#10 /protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application ->handleRequest(Object(yii\console\Request))

#11 /protected/yii(31): yii\base\Application->run()

#12 {main}
```

### Additional info

The issue is here:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/search/driver/MysqlDriver.php#L58
`$content->getModel()` returns `null` for a content.

Shouldn't we perform a database integrity check before indexing the search engine?
Or bypass `null` models and display a warning?

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.0

**Comment by yurabakhtin** [comment]
@marc-farre 

> Shouldn't we perform a database integrity check before indexing the search engine?

Yes, the command `yii integrity/run` will solve the issue.

@luke- I have decided to do the fixes to avoid such errors for case when some `Content` record has a wrong object:

- https://github.com/humhub/humhub/pull/7093
- https://github.com/humhub/solr/pull/14

**Comment by luke-** [comment]
@yurabakhtin I don't know if I would merge the PRs if it is just work around code for corrupt DBs. 

I would rather fix the cause. Otherwise it will be difficult for the later maintenance/refactoring team to understand why such conditions are present.

Maybe we could add some auto integrity check?

**Comment by yurabakhtin** [comment]
@luke- 

> Maybe we could add some auto integrity check?

Do you mean we should run the content integrity check before run content search rebuilding?
It could be run on the method `ContentSearchService->update(false)` before call the code `$this->getSearchDriver()->update($this->content);`.

**Comment by luke-** [comment]
@yurabakhtin 

No, for Search I would assume that the database is correct.

But we could, for example, implement something like this here in the future: https://github.com/humhub/humhub-internal/issues/301

---

I wouldn't merge the PRs now. In the future, we can implement auto integrity.

**Comment by yurabakhtin** [comment]
> But we could, for example, implement something like this here in the future: [humhub/humhub-internal#301](https://github.com/humhub/humhub-internal/issues/301)

@luke- Yes, we could implement a new cron job for the integrity check, for example, for the admin module as we already have similar jobs [there](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/admin/Events.php#L54-L59).
