### ISSUE TITLE
Inconsistencies with baseUrl setting

### ISSUE THREAD

**Issue by dantefromhell** [humhub/humhub#7097]
Looking at the Prerequisites tab (<HUMHUB_URL>/admin/information/prerequisites) [1] it gives me a warning about the "Base Url" being `http://<HUMHUB_URL>`.

My `common.php` though uses `https://<HUMHUB_URL>`, my admin setting (<HUMHUB_URL>/admin/setting/basic) as well as `yii settings/list-modules base` display the scheme as `https://`.

It looks like this is not solely an issue on the "Prerequisites" page, looking at the source code for each of the pages mentioned above the HTML page source contain the following references to `http://<HUMHUB_URL>`:

1. `<meta property="og:url" content="http://<HUMHUB_URL>/<CURRENT_PAGE>`
  with `<CURRENT_PAGE>` the URL of the currently loaded page, e.g. `/admin/information/prerequisites`
2. `<meta name="og:image" content="http://<HUMHUB_URL>//assets/logo/600x600.png?v=1705015498">`
3. `<meta property="twitter:url" content="http://<HUMHUB_URL>//admin/information/prerequisites">`
4. `<meta name="twitter:image" content="http://<HUMHUB_URL>//assets/logo/600x600.png?v=1705015498">`
5. `<link href="http://<HUMHUB_URL>/<CURRENT_PAGE>" rel="canonical">`
  with `<CURRENT_PAGE>` the URL of the currently loaded page, e.g. `/admin/information/prerequisites`

For the pages mentioned above, all other absolute URL paths correctly start with `https://<HUMHUB_URL>`, . I have not checked exhaustively other pages within my HumHub install.

### What is the expected result?
All absolute URLs in the page source start with `https://<HUMHUB_URL>`.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.5
| PHP version      | 8.1.28
| Operating system | Linux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by marc-farre** [comment]
@dantefromhell I don't think there is any issue with HumHub about this.
The problem you have is that you're browsing your HumHub with http instead of https.
You should force https by editing the `.htaccess` file. See `# uncomment to force https requests` in it.

**Comment by dantefromhell** [comment]
@marc-farre 
Being on HTTP is technically impossible, this instance is served HTTPS-only.

Given how the parameters are set (as described above), my understanding is that I have forced HTTPS and all URLs that Humhub generates should be schemed with "https://"

**Comment by ArchBlood** [comment]
> @marc-farre Being on HTTP is technically impossible, this instance is served HTTPS-only.
> 
> Given how the parameters are set (as described above), my understanding is that I have forced HTTPS and all URLs that Humhub generates should be schemed with "https://"

Are you using a reverse proxy to handle HTTPS? If possible are you able to provide any configurations that you have done with redacted personal information?

**Comment by marc-farre** [comment]
@dantefromhell When you see `<meta property="og:url" content="http://<HUMHUB_URL>/<CURRENT_PAGE>` in the source code, it means that the URL in the browser is HTTP. Can you check?

**Comment by dantefromhell** [comment]
@marc-farre It is not. The connection from the browser to the reverse proxy is always HTTPS, the connection from the reverse proxy to HumHub is always HTTP. The setup makes any other communication impossible as the reverse proxy does not support incoming HTTP and the Humhub instance does not support incoming HTTPS.

I should also mention that `Settings -> General -> Base URL` is explicitly set to `https://humhub.domain.com`.
This makes part of my confusion about this issue, as my expectation is that by setting the scheme explicitly in the configuration no other scheme is used to generate URLs for this HumHub instance.

**Comment by marc-farre** [comment]
@dantefromhell I think this PR should solve the issue in HumHub 1.16.3: https://github.com/humhub/humhub/pull/7307/files
If not, you can reopen it.
