### ISSUE TITLE
Replace LESS variables with CSS variables

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7099]
### Is your feature request related to a problem? Please describe.

Each time we update HumHub to a new version, we need to recompile the CSS of child themes (including Enterprise Theme, Clean Theme and Theme Builder).
This is often forgotten, which causes display issues.
And it can be complex to do when we have child-child themes, because all parent themes must be updated.

Now that we [added CSS variables to theme](https://github.com/humhub/humhub/issues/4938), we could replace LESS variables with CSS variables.

This would allow changing the values without having to recompile the CSS.

### Describe the solution you'd like

- Replace all LESS variables with CSS variable in LESS files
- Move the `:root` CSS variables from the `themes/HumHub/css/theme.css` file to a new `themes/HumHub/css/static/css/variables.css`
- This new `variables.css` file will be generated by adding a new line to [the Gruntfile.js file](https://github.com/humhub/humhub/blob/master/Gruntfile.js#L86), and by moving the `:root` CSS variables from [the `variables.less` file](https://github.com/humhub/humhub/blob/master/static/less/variables.less#L101-L146) to a new `static/less/css-variables.less` file
- We register this new `variables.css` file via `humhub\modules\ui\view\components\Theme` by replacing the `register()` method with:

```php
    /**
     * Registers theme css and resources to the view
     *
     * @param bool $includeParents also register parent themes
     */
    public function register($includeParents = true)
    {
        if (Yii::$app->request->isAjax) {
            return;
        }

        if ($includeParents) {
            foreach (array_reverse($this->getParents()) as $parent) {
                /** @var Theme $parent */
                $parent->registerVariables();
            }
        }
        $this->registerVariables();

        if ($includeParents) {
            foreach (array_reverse($this->getParents()) as $parent) {
                /** @var Theme $parent */
                $parent->registerTheme();
            }
        }
        $this->registerTheme();
    }

    public function registerVariables()
    {
        if (file_exists($this->getBasePath() . '/css/variables.css')) {
            $mtime = filemtime($this->getBasePath() . '/css/variables.css');
            Yii::$app->view->registerCssFile($this->getBaseUrl() . '/css/variables.css?v=' . $mtime, ['depends' => CoreBundleAsset::class]);
        }
    }

    public function registerTheme()
    {
        if (file_exists($this->getBasePath() . '/css/theme.css')) {
            $mtime = filemtime($this->getBasePath() . '/css/theme.css');
            Yii::$app->view->registerCssFile($this->getBaseUrl() . '/css/theme.css?v=' . $mtime, ['depends' => CoreBundleAsset::class]);
        }
    }
```

Then, we can just add a `variables.css` file in our child theme to overwrite the core values:
- No need to compile LESS
- No need to recompile the CSS on each HumHub or parent theme update
- The Theme Builder can use this new file to change colors
- It allows adding configuration to the Theme modules (such as the Clean Theme) without having to recompile the hole CSS each time: when saving the module configuration, the `theme/moduleTheme/css/variables.css` file is generated by PHP.

Related to https://github.com/humhub/humhub/issues/4539 and https://github.com/humhub/humhub/issues/4938

**Comment by marc-farre** [comment]
@luke- if you agree with this idea, I can create a PR (on the develop branch for 1.17?)

**Comment by luke-** [comment]
@marc-farre Can we perhaps start with a PR that replaces LESS variables with CSS variables?

Then we can see how we can optimise this further?

**Comment by marc-farre** [comment]
@luke- fine.

About darkened and lightened color values such as `color: darken(@primary, 5%)`, I've explored solutions with `color-mix` and `hsl` CSS functions, but none of them can be used:
- `color-mix` gives a color different from `darken` or `lighten` (because it adds a translucent white or black layer on the original color)
- `hsl` works fine, but, it's not supported by Safari…

So the only solution I have is to create more CSS variables:
```css
:root {
  --primary: @primary;
  --primary-dark: @primary-dark;
  --primary-dark-5: darken(@primary, 5%);
  --primary-dark-10: darken(@primary, 10);
  --primary-dark-15: darken(@primary, 15);
  --primary-dark-20: darken(@primary, 20);
  --primary-dark-25: darken(@primary, 25);
  --primary-dark-30: darken(@primary, 30);
  --primary-dark-35: darken(@primary, 35);
  --primary-dark-40: darken(@primary, 40);
  --primary-dark-45: darken(@primary, 45);
  --primary-dark-50: darken(@primary, 50);
}
```

Do you agree with this approach?

**Comment by luke-** [comment]
@marc-farre Hmm, somehow looks a bit hacky...

In the course of the upcoming BS5 migration and also with the plan to cleanup/revision of the variables, I wouldn't add a bunch of new vars in the meantime...

Could be interesting (BS5): 
- https://getbootstrap.com/docs/5.3/customize/color/#notes-on-sass
-  https://codepen.io/emdeoh/pen/zYOQOPB

**Comment by felixhahnweilheim** [comment]
Just want to mention my flex theme, maybe parts of the work can be helpful: https://github.com/felixhahnweilheim/humhub-flex-theme/

The DevController (console command) goes through all LESS files and replaces LESS variables with CSS variables.

Darken, Lighten and Fade are also replaced. Those colors are then calculated by ColorHelper.

Of course I also thought abot the CSS brightness filter but it didn't work. It affects a whole element (font color and background color).

**Comment by marc-farre** [comment]
@luke- Thanks for your suggestion. The problem is that a lot of the darken and lighten colors are not div backgrounds. And it also generates many CSS classes, so it won't create a more compact CSS file than having all the required CSS variables.

What do you think about the idea of generating the CSS variables with a LESS loop, e.g.:
```less
  .generate-dark-shades(@i) when (@i =< 50) {
    --primary-dark-@{i}: darken(@primary, @i*1%);
    .generate-dark-shades(@i + 5);
  }
  .generate-dark-shades(5);
```

This will create the required color variables:
```css
  --primary-dark-5: darken(@primary, 5%);
  --primary-dark-10: darken(@primary, 10);
  --primary-dark-15: darken(@primary, 15);
  --primary-dark-20: darken(@primary, 20);
  --primary-dark-25: darken(@primary, 25);
  --primary-dark-30: darken(@primary, 30);
  --primary-dark-35: darken(@primary, 35);
  --primary-dark-40: darken(@primary, 40);
  --primary-dark-45: darken(@primary, 45);
  --primary-dark-50: darken(@primary, 50);
```

I should be able to optimize the loop to deal with other colors without having to write a new loop for each one.

@felixhahnweilheim Thanks. It's great for a module CSS compiler. However, for the theme, I would like to avoid PHP and complexity.

With this approach, we will have a `theme.css` file containing all CSS variables, allowing to easily change the variable values without having to recompile the CSS. This will allow creating themes much more easily, and will prevent display issues when updating HumHub or the parent theme.

**Comment by felixhahnweilheim** [comment]
Yes, PHP is only used for creating the base CSS file (during development, not in production).

(Actually my original idea with the flexible theme was to get away from LESS completely. Because it seems kind of outdated, most other platforms prefer SASS or pure CSS over LESS.)

I didn't know about LESS loops, that sounds good.

That would mean that custom themes still need to run a little LESS for the variables, right?
But they would have a lot less issues with HumHub updates which I would appreciate.

**Comment by marc-farre** [comment]
@felixhahnweilheim yes, LESS should be replaced with SAAS in the future, but if we already use pure CSS variables, it will make it even easier for custom themes to migrate to SASS later. We might even be able to avoid completely LESS and SASS in the future in custom themes with small CSS changes.

When switching to SASS, we can still create a loop to generate the CSS variables for darken and lighten variations:
```sass
  @for $i from 1 through 10 {
    $percentage: $i * 5;
    --primary-dark-#{$percentage}: #{darken($primary, $percentage)};
  }
```

**Comment by luke-** [comment]
Generally, I would like to follow the BS5 framework scheme (variable naming/color concept/theming) as closely as possible.

This will likely mean that we will have to change/remove/add some existing variables anyway.

I am therefore concerned that if we add many additional new variables now, we will only have more work to do later during the BS5 migration.  

It is not a concern of whether the variables are created by loop or otherwise, but rather that they are then also used and may have to be adjusted again.

I'm therefore not sure whether it makes sense to introduce new CSS variables now, which we will very soon change (or removed) again.

**Comment by marc-farre** [comment]
@luke- I agree.

BS5 has color variations in pure CSS variables: https://getbootstrap.com/docs/5.3/customize/css-variables/#default
E.g.: `--bs-success-text-emphasis`
Or: `--bs-gray-400`

BS5 recommends to uses the `mix()` function instead of `darken()` and `lighten()`: https://getbootstrap.com/docs/5.3/customize/color/#notes-on-sass

The new pure CSS `color-mix()` function is equivalent to the SASS `mix()` function.
It's supported in all modern browsers and the global usage is 90%: https://caniuse.com/?search=color-mix

We can find a relative equivalence to the LESS `darken()` or `lighten()` functions.

E.g.:
```less
@primary: #435f6f;
:root {
  --primary: @primary;
}
#div1 {
    background-color: darken(@primary, 10%);
}
#div2 {
    background-color: color-mix(in srgb, var(--primary) 70%, black);
}
```
![image](https://github.com/humhub/humhub/assets/23310825/a9e065e0-3a43-4a85-a86b-135144e3900e)

@luke- Do you think we can already use the pure CSS `color-mix()` function, knowing that the global usage will be even better than 90% when HumHub 1.17 will be released? https://caniuse.com/?search=color-mix

If not, I don't see any alternative of creating the required CSS variables, even when switching to SASS.
But we don't need to create all variations (only the required ones), and we can use the Bootstrap syntax, without the `bg-` which will be added when migrating to BS5.
I estimate to more or less 25 variables.

E.g.:
```less
:root {
  --primary-525: darken(@primary, 5%);
  --primary-425: lighten(@primary, 5%);
  --default-510: darken(@default, 2%);
  ...
}
```

**Comment by marc-farre** [comment]
OK to postpone. I think I'll make some tests with the Clean Theme, and then if it works fine, we can use this code for HumHub core.

> Can we implement a fallback here?

I have no idea for fallbacks... But it shouldn't have a very big impact (e.g., when hovering a button, the background won't darken), and it should concern less and less browsers in the future.

However, we could create a few temporary variables containing the darkened and lightened colors generated by LESS.
And later, when browser support with `color-mix()` is sufficient, we can remove them.

> do we want to remove SASS/LESS color vars?
> don't BS components always rely on the LESS/SASS variables?
> modules could access color values via this component:

I need to learn more about BS5 to answer what's the best practice.
But it could be done in a second time.
E.g.:
- 1.17: LESS color variables are depreciated
- 1.18: they are removed

> Wouldn't it better to wait for BS5 Migration

For plain colors, no, but for darkened or lightened colors, you're right, I think we should review them, and hopefully a lot of them will be removed or replaced with a native BS5 support

> ThemeBuilder

I think it's a good opportunity to refactor it to use native CSS variables, using the idea described in my first comment.
But this could be done in a second time (by first only marking LESS colors as deprecated).

**Comment by luke-** [comment]
> OK to postpone. I think I'll make some tests with the Clean Theme, and then if it works fine, we can use this code for HumHub core.
> 

Ok thanks. Then let's do some tests before.

We should also check whether there is a problem if BS5 uses SASS variables internally and we only want to switch to CSS variables. Not that there are conflicts here.

---

It's ok if we have a roadmap here with e.g. (v17) Mark as Deprecated and then (v18) remove/refactor it completely.
We just have to make sure that we take the more time-consuming step in v18 so that the core does not still use deprecated code. 

But before, we need to ensure it works to switch to Pure CSS Vars only.

**Comment by marc-farre** [comment]
@luke- @felixhahnweilheim I've released Clean Theme version 2 (beta): https://community.humhub.com/content/perma?id=279367

Thanks to @felixhahnweilheim [Flex Theme](https://github.com/felixhahnweilheim/humhub-flex-theme/), the module integrates a command to modify HumHub LESS files (from a copy) which replaces all LESS color variables with CSS variables.
For darken and lighten, additional CSS variables are created: https://github.com/cuzy-app/clean-theme/blob/master/resources/less/special-color-variables-in-humhub-modified.txt

Then, the Clean Theme module configuration generates the `resources/css/humhub.clean-theme.dynamic.css` file (not in GitHub) containing all CSS variables including color variations (darkened and lightened).
It's loaded via an asset: https://github.com/cuzy-app/clean-theme/blob/master/assets/CleanThemeAsset.php#L29

I've also added the [scssphp library](https://github.com/scssphp/scssphp) to compile SCSS to CSS from the custom CSS filed in the Configuration: https://github.com/cuzy-app/clean-theme/blob/master/composer.json#L7

More info: https://github.com/cuzy-app/clean-theme/blob/master/docs/DEVELOPER.md

I'ts currently tested on 4 HumHub instances in production and seems to work quite well.

**Comment by luke-** [comment]
Thanks, for sharing! Tricky solution. :-)

Does this also work with standard Bootstrap components that do not use CSS variables internally? 

For example 
```html
<div class=‘alert alert-success’ role=‘alert’>...</div>
```
or button classes like `btn-primary`.

**Comment by marc-farre** [comment]
@luke- yes, it does work, because we have this CSS code (e.g. for the button):

```css
.btn-primary {
    background: var(--primary);
    color: var(--text-color-contrast) !important;
}
```

If you want, I can create a branch (from HumHub core develop) which removes all LESS variables and use CSS variables only so you can test (no PR for a start, just for testing).

**Comment by luke-** [comment]
@marc-farre Hmm, so there are now definition overrides for `alert-primary`, `btn-primary`, `label-primary`, ...  ?

If we want to have a complete solution, that means we have to overwrite all bootstrap classes that contain a colour value, right?

**Comment by marc-farre** [comment]
@luke- no. The above code example (for `.btn-primary`) is in HumHub core (in the static folder).
Other themes (Enterprise, etc.) only overwrite the CSS variables. Example:

### HumHub core `root.less`

```less
:root {
  --primary: #435f6f;
  --text-color-contrast: #fff;
}
```

### HumHub core `button.less`

```less
.btn-primary {
    background: var(--primary);
    color: var(--text-color-contrast) !important;
}
```

### Custom theme `root.less`

```less
:root {
  --primary: #546e7e;
  --text-color-contrast: #eee;
}
```

### Custom theme `import.less`

```less
@import "@{HUMHUB}/root.less";
@import "@{CUSTOM_THEME}/root.less"; // Can be done at the end of the file too, because the overwrite is done into the navigator (the compiled CSS file will contain the HumHub CSS variable values AND the custom theme ones, but will take into account the last one
@import "@{HUMHUB}/humhub.less";
```

**Comment by marc-farre** [comment]
This issue is paused.
We will reopen it when switching to Bootstrap 5.

As a reminder for later, we should read https://getbootstrap.com/docs/5.3/customize/css-variables/#root-variables

> Bootstrap includes many CSS custom properties (variables) in its compiled CSS for real-time customization without the need to recompile Sass. These provide easy access to commonly used values like our theme colors, breakpoints, and primary font stacks when working in your browser’s inspector, a code sandbox, or general prototyping.
> 
> All our custom properties are prefixed with bs- to avoid conflicts with third party CSS.

**Comment by marc-farre** [comment]
@luke- I'm reopening this issue for BS5.

In summary, I could switch to CSS variables if you agree for adding variations CSS variables (darken and lighten colors), the way it is done here:
https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss
E.g. `$gray-100`.

This would allow changing colors dynamically (dark theme, theme builder and increasing contrast for visual impairs).

**Comment by luke-** [comment]
@marc-farre Would it be possible to defer this topic a little?

At a later stage of the BS5 migration, we should also revise the current color variables and change them if necessary. And before that, I don't want to introduce a lot of new variables.
