### ISSUE TITLE
Add an external link icon to the "Install Updates" button to avoid thinking it updates the modules directly

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7105]
### Is your feature request related to a problem? Please describe.

See https://community.humhub.com/content/perma?id=279078

In the Administration -> Modules page, when we see the "Install Updates" button, we think it's an action button, which will directly install the updates.

### Describe the solution you'd like

Rename the button so that we understand it's a link button for the Marketplace page.
E.g. "Go to the Marketplace"

### Describe alternatives you've considered

Replace the button with a text link called "Please update now".

**Comment by luke-** [comment]
@Semir1212 @mbumpalumpa Any idea?

**Comment by Semir1212** [comment]
"Updates available!"? @luke- @mbumpalumpa @marc-farre

**Comment by luke-** [comment]
Or rename both buttons and something like "Install more modules via the Marketplace"

**Comment by Semir1212** [comment]
That would be a bit to much for a button @luke- 

I would suggest that we go with "Visit Marketplace" in the top right corner and remove the button on the bottom.

**Comment by luke-** [comment]
Hmm, then I would rather stick with the current solution.

The fact that you can "install more modules" is important.

**Comment by Semir1212** [comment]
@mbumpalumpa @luke- Let's just leave it as is than.

**Comment by marc-farre** [comment]
@Semir1212 @luke- @mbumpalumpa maybe we could rename the "Install Updates" button only to something like "Manage updates" and add the `external-link` icon?

![image](https://github.com/humhub/humhub/assets/23310825/8774732a-9282-4d39-9d6a-34ea9573d718)

And leave the "Add more modules" button as it is.

**Comment by marc-farre** [comment]
> addition of external link icon on existing copy of the button

@luke- Done in commit https://github.com/humhub/humhub/pull/7114 on master branch

**Comment by dreua** [comment]
This is incorrect usage of design language imo. The external link icon usually signifies a link to another domain, I totally expected to be directed to something like https://marketplace.humhub.com/browse/index .
