### ISSUE TITLE
Cannot edit image in fullscreen editor

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#7109]
**HH 1.16 - Native theme** 

Steps to reproduce:
Add a post with an image. You can edit image size and location
![image](https://github.com/humhub/humhub/assets/91057837/4f648d4b-c598-4059-9a27-7daab4e6c342)

Change editor size to fullscreen - You cannot edit image
![image](https://github.com/humhub/humhub/assets/91057837/18c10507-cf0f-4aeb-bf76-538c228ab922)

Notice: It works in HH community site, but no success in our dev and production sites

**Comment by marc-farre** [comment]
Tested on HumHub 1.16.1 and I don't have the issue.
@Gilbertdelyon Could you check if you have any JavaScript errors in the browser console?

**Comment by yurabakhtin** [comment]
I think the bug was be fixed by PR https://github.com/humhub/humhub-prosemirror/pull/146.

**Comment by Gilbertdelyon** [comment]
Sorry for late answer. I only had limited acces to the web for some days.
You are right. **It works after updating to 1.16.1**. -:)
