### ISSUE TITLE
Latest activities' scroll-bar

### ISSUE THREAD

**Issue by jeanette2091** [humhub/humhub#711]
![skaermbillede 2015-02-10 kl 21 58 29](https://cloud.githubusercontent.com/assets/9905319/6136350/4dfa7e2c-b170-11e4-9214-defa187a2e7b.png)

I think something is wrong with the Latest activities' scroll-bar (You can see it on the image)

I don't know if it's because of my macbook or something else? But everything on HumHub Community is perfect.

**Comment by andystrobel** [comment]
I saw, you changed the design. Maybe because of that? Can you try it out with the normal HumHub-Theme or with a fresh installation with this existing database content?
