### ISSUE TITLE
No notifications since Update 1.16.x

### ISSUE THREAD

**Issue by optitsolutions** [humhub/humhub#7110]
### What steps will reproduce the problem?
Changes/Posts/Likes from another user in a space marked for notifications

### What is the expected result?
I get a notification at the top of the humhub site, or the notification number increases
### What do you get instead?
no notifications since the update from 1.15.x to 1.16.(1)
### Additional info
several users (maybe all) in our installations have this problem.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.1
| PHP version      | 8.0
| Operating system |

Maybe this Error:
yii\base\ErrorException: Attempt to read property "profile" on null in /usr/local/www/apache24/noexec/domain.de/protected/modules/mail/widgets/InboxMessagePreview.php:74
Stack trace:
#0 /usr/local/www/apache24/noexec/domain.de/protected/modules/mail/widgets/InboxMessagePreview.php(74): yii\base\ErrorHandler->handleError(2, 'Attempt to read...', '/usr/local/www/...', 74)
#1 /usr/local/www/apache24/noexec/domain.de/protected/modules/mail/widgets/InboxMessagePreview.php(97): humhub\modules\mail\widgets\InboxMessagePreview->getUsername()
#2 /usr/local/www/apache24/noexec/domain.de/protected/modules/mail/widgets/InboxMessagePreview.php(33): humhub\modules\mail\widgets\InboxMessagePreview->getMessageTitle()
#3 /usr/local/www/apache24/noexec/domain.de/protected/humhub/components/Widget.php(62): humhub\modules\mail\widgets\InboxMessagePreview->run()
#4 /usr/local/www/apache24/noexec/domain.de/protected/modules/mail/controllers/InboxController.php(52): humhub\components\Widget::widget(Array)
#5 [internal function]: humhub\modules\mail\controllers\InboxController->actionLoadMore()
#6 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#8 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('load-more', Array)
#9 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('mail/inbox/load...', Array)
#10 /usr/local/www/apache24/noexec/domain.de/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 /usr/local/www/apache24/noexec/domain.de/index.php(28): yii\base\Application->run()
#12 {main}

**Comment by optitsolutions** [comment]
wrong PHP version in the scripts obviously. sorry!

**Comment by marc-farre** [comment]
I've created https://github.com/humhub/humhub/issues/7111 which would prevent this issue.
