### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by Lazuis** [humhub/humhub#712]
Proposed by bastrian :+1:

**Comment by bastrian** [comment]
For the Information: The Clef Project can be found here: https://getclef.com/ and a full Documentation about it can be found here: http://docs.getclef.com/

**Comment by heinrich-ulbricht** [comment]
Are there any developments in this direction? Just asking to check if I missed it or it is yet to be done.

**Comment by bastrian** [comment]
> Are there any developments in this direction? Just asking to check if I missed it or it is yet to be done.

Not implemented yet it seems.

**Comment by smashm** [comment]
Maybe this could be an option to adopt it for humhub as it is yii2 based:

https://yii2-usuario.readthedocs.io/en/latest/helpful-guides/how-to-implement-two-factor-auth/
https://github.com/2amigos/2fa-library
https://github.com/2amigos/qrcode-library

**Comment by luke-** [comment]
WIll be available with HumHub 1.8+
https://www.humhub.com/en/marketplace/twofa/
