### ISSUE TITLE
Error during user registration because of regex issue

### ISSUE THREAD

**Issue by Mueller-Patrick** [humhub/humhub#7123]
### What steps will reproduce the problem?

Register as a new user and click on the link in the received email to complete the registration. Fill out the form and click submit

### What is the expected result?

Form is submitted and user is successfully created

### What do you get instead?

yii\base\ErrorException: preg_match(): No ending delimiter '.' found in /var/www/vhosts/domain/httpdocs/protected/vendor/yiisoft/yii2/validators/RegularExpressionValidator.php:57
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /var/www/vhosts/domain/httpdocs/protected/vendor/yiisoft/yii2/validators/RegularExpressionValidator.php(57): preg_match()
#2 /var/www/vhosts/domain/httpdocs/protected/vendor/yiisoft/yii2/validators/Validator.php(306): yii\validators\RegularExpressionValidator->validateValue()
#3 /var/www/vhosts/domain/httpdocs/protected/vendor/yiisoft/yii2/validators/Validator.php(260): yii\validators\Validator->validateAttribute()
#4 /var/www/vhosts/domain/httpdocs/protected/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes()
#5 /var/www/vhosts/domain/httpdocs/protected/humhub/compat/HForm.php(99): yii\base\Model->validate()
#6 /var/www/vhosts/domain/httpdocs/protected/humhub/modules/user/models/forms/Registration.php(240): humhub\compat\HForm->validate()
#7 /var/www/vhosts/domain/httpdocs/protected/humhub/modules/user/controllers/RegistrationController.php(100): humhub\modules\user\models\forms\Registration->validate()
#8 [internal function]: humhub\modules\user\controllers\RegistrationController->actionIndex()
#9 /var/www/vhosts/domain/httpdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/vhosts/domain/httpdocs/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#11 /var/www/vhosts/domain/httpdocs/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#12 /var/www/vhosts/domain/httpdocs/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#13 /var/www/vhosts/domain/httpdocs/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#14 /var/www/vhosts/domain/httpdocs/index.php(28): yii\base\Application->run()
#15 {main} 

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.1
| PHP version      | 8.2.21
| Operating system | Debian 12 bookworm

**Comment by ArchBlood** [comment]
Currently not seeing any issues with registrations, but on closer look you are having an issue with a form field that is required on the specific HumHub instance that uses an REGEX that's causing the issue.

**Comment by Mueller-Patrick** [comment]
Ahh that was it, thanks a lot for your help! :)
