### ISSUE TITLE
Gii module generation - requires $breadcrumbs declaration in Controller

### ISSUE THREAD

**Issue by baldwindc** [humhub/humhub#713]
When a new module is created using the Gii module generator, the error "Property "DefaultController.breadcrumbs" is not defined." is generated at line 4 of the modules index.php file. 

Solution is to define breadcrumbs in the Controller class. 

public $breadcrumbs = []

**Comment by baldwindc** [comment]
Wasn't sure if this should go in the Gii page or here, but since the code change required is in Humhub I put it here.

**Comment by luke-** [comment]
Hmm, not sure if we should add a unused breadcrumbs property to our controller to avoid this.

Maybe we should create own Gii Templates.


I create an issue there...https://github.com/humhub/humhub-modules-yiigii/issues/2
