### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#714]
https://www.youtube.com/watch?v=r7KlcAB6W2M&feature=youtu.be

**Comment by bastrian** [comment]
Sorry, but a Youtube Video ist NOT a bug report. Please describe the Bug and append necessary Informations like Apache Logs (Remove the IPs) and other relevant logs

**Comment by Vatarus** [comment]
same problem

**Comment by luke-** [comment]
We didn't handle bug reports with title "Bug" and Youtube Video.

Please reopen it with more informations, etc.
