### ISSUE TITLE
Searching twice for the same keyword fails

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7141]
### What steps will reproduce the problem?

1. Navigate to https://community.humhub.com/dashboard
2. Search for a keyword, e.g. `test`, and click on the first content:
![image](https://github.com/user-attachments/assets/98edc8fa-f131-4ca0-b74c-36d25b1736fe)
3. Search again for the same keyword

### What is the expected result?

The same results

### What do you get instead?

![image](https://github.com/user-attachments/assets/41597bd4-6807-4c09-a30f-fb7c4fd04c46)

### Additional info

No error in the log. It seems to be a JS bug.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.1

**Comment by marc-farre** [comment]
Description edited: the Link Preview was not causing the error.
It's a JS error, but there is no error in the log and no error in the console.

Strangely, I had an error in the log yesterday: `Language not available: ET` but I cannot reproduce...

**Comment by yurabakhtin** [comment]
@marc-farre @luke- Fixed https://github.com/humhub/humhub/pull/7145.
