### ISSUE TITLE
Search starting with special characters

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#7152]
### What steps will reproduce the problem?
Start a search with some of the following special characters.

Some of the following work whereas others do not, I have not tested all of them but a number of them do throw the error;

| Character | Name                | Character | Name                   |
|-----------|---------------------|-----------|------------------------|
| !         | Exclamation mark    | @         | At sign                |
| #         | Hash (Pound)        | $         | Dollar sign            |
| %         | Percent sign        | ^         | Caret                  |
| &         | Ampersand           | *         | Asterisk               |
| (         | Left parenthesis    | )         | Right parenthesis      |
| -         | Hyphen (Dash)       | _         | Underscore             |
| +         | Plus sign           | =         | Equals sign            |
| {         | Left curly brace    | }         | Right curly brace      |
| [         | Left square bracket | ]         | Right square bracket   |
| \|        | Vertical bar (Pipe) | \         | Backslash              |
| :         | Colon               | ;         | Semicolon              |
| "         | Double quote        | '         | Single quote (Apostrophe) |
| <         | Less than sign      | >         | Greater than sign      |
| ,         | Comma               | .         | Period (Dot)           |
| ?         | Question mark       | /         | Forward slash          |
| ~         | Tilde               | `         | Grave accent           |

### What is the expected result?
Either a graceful error handling or proper mapping is done

### What do you get instead?
![Screenshot_1](https://github.com/user-attachments/assets/84303e06-45ff-420b-afba-a7c92b8aaea4)

### Additional info
No error stacks are given.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.1, 1.17.0-dev
| PHP version      | 8.2.5
| Operating system | CloudLinux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@ArchBlood Thank you for the report.
@luke- Fixed https://github.com/humhub/humhub/pull/7189.
