### ISSUE TITLE
Translate a role by applying Yii::t to the role string

### ISSUE THREAD

**Issue by Mint-Lime** [humhub/humhub#7162]
The role names in Space on the "About" page, within the "About your membership" section, were not localized into other languages. The code uses _ucfirst($role)_ directly, which prevents the role names from being localized correctly. The line:
https://github.com/humhub/humhub/blob/64aa24290bef364b2e7712ec035e3cd5cde1d6b9/protected/humhub/modules/space/widgets/views/myMembership.php#L16

should be replaced with:

`<p><b><?= Yii::t('SpaceModule.base', 'Role') ?>: </b><?= Yii::t('SpaceModule.base', ucfirst($role)) ?></p>`

This change ensures that the role name is passed through the Yii::t function, allowing for proper translation according to the selected language (if the appropriate translation is provided).

**Comment by yurabakhtin** [comment]
@luke- https://github.com/humhub/humhub/pull/7190
