### ISSUE TITLE
Administration menu voices visible but unable to access them

### ISSUE THREAD

**Issue by ilMagnifico** [humhub/humhub#7164]
What's the point of showing Me options that once clicked I can't access?
<img width="561" alt="Screenshot 2024-08-09 alle 18 24 58" src="https://github.com/user-attachments/assets/c35e831e-f3ea-4e74-aceb-b01820cc4d07">

<img width="854" alt="Screenshot 2024-08-09 alle 18 25 04" src="https://github.com/user-attachments/assets/fea90068-7790-4c88-a1f0-3632fadb0633">

Sidebar menu should show Me just the pages I can access on.

**Comment by ilMagnifico** [comment]
User have only enabled: View analytics  Analytics

**Comment by marc-farre** [comment]
> User have only enabled: View analytics Analytics

Thanks. I think you must have other authorizations, because I tested with a user which is a member of the User group only, if I only allow "View analytics" permission in the User group, I cannot see other admin menu elements (such as "Custom pages", "Modules", etc).

**Comment by ilMagnifico** [comment]
I've something like 50 modules turned on. Maybe it's because some of those. I assure you I had just that permits allowed

**Comment by ilMagnifico** [comment]
Still reporting this
