### ISSUE TITLE
How to make a module?

### ISSUE THREAD

**Issue by devaniljr** [humhub/humhub#718]
Is there any tutorial or documentation explaining details about creation of modules?

**Comment by bastrian** [comment]
Yes, there are. Please visit https://github.com/humhub/humhub/blob/master/protected/docs/guide/developer/modules_general.md
or on you Humhub Installation /protected/docs/guide/developer/modules_general.md

Inside /protected/docs/guide/developer you will find more information about Humhub Developeing
