### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by upfornaughty** [humhub/humhub#720]
I have tried numerous times and cant install.  I get the following message...

Welcome to HumHub
Your Social Network Toolbox

This wizard will install and configure your own HumHub instance.

To continue, click Next.

Parse error: syntax error, unexpected T_FUNCTION in /homepages/33/d293097015/htdocs/UpForNaughty2015/protected/libs/HHtml.php on line 199

can you please advise?

**Comment by luke-** [comment]
We require at least PHP 5.4
