### ISSUE TITLE
Typo in German first steps translation Tour 3/4

### ISSUE THREAD

**Issue by LoSaMe** [humhub/humhub#7206]
There is a typo in the first tour on page 3/4: Benuzerkonto-Menü instead of Benutzerkonto-Menü.
Seen in 1.16.1 and 1.15.4

![grafik](https://github.com/user-attachments/assets/79269919-ceb5-45d5-b0c0-51b62d8ac9ec)

**Comment by luke-** [comment]
Thanks, fixed on the translation site.
