### ISSUE TITLE
Importer for user lists

### ISSUE THREAD

**Issue by andystrobel** [humhub/humhub#721]
To import existing users from other platforms as CSV or other formats. It could be placed under **Administration -> Users**

![mockup-import-users](https://cloud.githubusercontent.com/assets/6032728/6183699/a91ece4a-b358-11e4-9474-da2749ff3d77.jpg)

**Comment by scienceapps** [comment]
+1

**Comment by WASasquatch** [comment]
+1

**Comment by scienceapps** [comment]
+2 ?

**Comment by benmag** [comment]
I've already made this as a module: 
https://github.com/ConnectedCommunities/humhub-modules-bulk_import

If this is still sought after and a PR would be accepted, I can have a go at implementing it
