### ISSUE TITLE
On some pages, the user menu wraps the caret underneath in Safari

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7210]
Original post: https://community.humhub.com/content/perma?id=280706

On some pages (e.g. People and Spaces) the user menu wraps the caret underneath in Safari:

![image](https://github.com/user-attachments/assets/78971a9d-54a1-4712-aa0c-98f33fb7132d)

Tested on Safari 17.6 with HumHub versions 1.7.3 through 1.16.2.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.2

**Comment by marc-farre** [comment]
@luke- I don't have a Mac to test, so I couldn't reproduce myself.

**Comment by luke-** [comment]
@Eladnarlea Can you please test this?

**Comment by Eladnarlea** [comment]
So, I have tested:

| HumHub Version | Safari Version |
|-------------------|------|
| 1.16.2 | 17.6 |
| 1.16.3 | 17.6 |
| 1.17.0-dev | 17.6 |


All show the error described. 

### One behaviour that I noticed:
____________________________

When on **Dashboard** `->` click **to Spaces overview page** `->` error shows `->` click to **Admin Menu** `->` error sometimes (!) stays `->` reload **Admin menu** `->` no error anymore


When on **Admin menu** (no error showing yet) `->` click **to Spaces overview page** `->` no error showing yet (!) `->` reload **Spaces page** `->` error shows

____________________________

### Quick Fix with Dev tools:

When I comment out `display: inline-block` then the error seems to be fixed.

<img width="635" alt="Screenshot 2024-09-10 at 8 23 19 AM" src="https://github.com/user-attachments/assets/9d432920-dadf-4840-aa13-8d7cddfa6dc7">

**Comment by luke-** [comment]
@Eladnarlea Thanks for your investigation!

@yurabakhtin Can you take a look into it?

**Comment by yurabakhtin** [comment]
@luke- @Eladnarlea It looks like Mac Safari renders the style `display: inline-block` sometimes as `display: block`:

![block](https://github.com/user-attachments/assets/6996da64-711f-4f80-899a-ca31acc67711)

By default `<span>` has `display: inline`:
![inline](https://github.com/user-attachments/assets/49a4b04a-e9b1-4a37-9991-bcb075415fad)

`display: inline-block`:
![inline-block](https://github.com/user-attachments/assets/b4c0fab5-01ed-4a1f-a08f-a803c12f884e)

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- I can suggest the following solution:

```css
#account-dropdown-link .caret {
    float: right;
    margin: 13px 0 0 5px;
}
```

but I can't test it on Mac Safari and I am not sure we need it because as I understand the bug is not permanent and probably it will be fixed in next versions of Safari browser.

**Comment by luke-** [comment]
@Eladnarlea Can you test the suggested solution?

**Comment by Eladnarlea** [comment]
### HH Version 1.16.2

- [ ] Works

<img width="343" alt="Screenshot 2024-09-11 at 7 40 02 AM" src="https://github.com/user-attachments/assets/f77dae15-decd-4c72-a6d6-df980f5b66e8">

_____________________________

### HH Version 1.16.3

- [ ] Works

<img width="257" alt="Screenshot 2024-09-11 at 7 34 02 AM" src="https://github.com/user-attachments/assets/0e37b235-85c2-4258-bd1e-5ec3e3787b65">

_____________________________

### HH Version 1.17.0-dev

- [ ] Works

<img width="299" alt="Screenshot 2024-09-11 at 7 40 12 AM" src="https://github.com/user-attachments/assets/33b8980e-ec61-44be-87e7-566f1c409805">


_____________________________

**Comment by luke-** [comment]
@yurabakhtin Can you please mark it as temp. fix for Safari?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/7217.
