### ISSUE TITLE
Better file structure in upload folder

### ISSUE THREAD

**Issue by Toxu-ru** [humhub/humhub#722]
I am very confused with the methods of files downloading. By default they are loading to uploads/file - profile_image. It’s OK when there will be 100 persons on site. But if there will be at least 50 000 and everyone will add one picture per day. What will happen with the folder? With the access to this folder? 
I am really upset with the system of files storage. 
What do you think about it? If there is a possibility to make it the same way as it’s made in other social networks, forums etc.? 
I.e. year/month/day….To use the bigger degree of enclosure and it will influence the productive capacity. 
I mean if I can load not more than 1000 files (profile images) into one catalogue, then at one level of enclosing I can safely locate on disc 256 000 files, at two levels – 65 536 000, at three levels – 16 777 216 000 and etc. The length of the line md5 of the hash allows us to make 16 levels of enclosing in the catalogues. I think it is enough to provide the operation of the most capacious discs. Thus, based on the practice, usually it’s enough to have three levels for the projects of any complicity.

**Comment by Stranikevg** [comment]
if (file_exists($this->getPath($prefix))) {
			
			$lavel1=$this->guid[0].$this->guid[1].$this->guid[2];
			$lavel2=$this->guid[3].$this->guid[4].$this->guid[5];
            //$path .= '/uploads/' . $this->folder_images . '/';
            $path .= '/uploads/' . $this->folder_images . '/'.$lavel1.'/'.$lavel2.'/';

			//dir
			$uploaddir = ROOT_DIR.'/uploads/' . $this->folder_images . '/'.$lavel1;
			//dir
			if(!is_dir($uploaddir)){
				@mkdir($uploaddir, 0777 );
				@chmod($uploaddir, 0777 );
			}	
			//dir
			$uploaddir = ROOT_DIR.'/uploads/' . $this->folder_images . '/'.$lavel1.'/'.$lavel2;
			//dir
			if(!is_dir($uploaddir)){
				@mkdir($uploaddir, 0777 );
				@chmod($uploaddir, 0777 );
			}

**Comment by luke-** [comment]
We also need a migration script which restructures the uploads folder.

**Comment by Stranikevg** [comment]
+1

**Comment by Vatarus** [comment]
+1

**Comment by WASasquatch** [comment]
Better to use `file_exists()` to prevent handling errors on some systems and open_basedir errors.
