### ISSUE TITLE
Problem in module "Most active users"

### ISSUE THREAD

**Issue by drpacheco** [humhub/humhub#724]
A problem occurs when using the module " mostactiveusers," the .zip file is in trouble someone already managed to activate with success?

    PHP - Version - 5.3.10-1 ubuntu3.15;

Detals: 
The problem occurs when trying to install the module; 
Error below:
PHP warning

ZipArchive::extractTo(/var/www/humhub/protected/modules/mostactiveusers/views/mostActiveUsers/list.php): failed to open stream: No such file or directory

/var/www/humhub/protected/modules_core/admin/libs/OnlineModuleManager.php(90)

078             $response = $http->request();
079             file_put_contents($downloadTargetFileName, $response->getBody());
080         } catch (Exception $ex) {
081             throw new CHttpException('500', Yii::t('AdminModule.libs_OnlineModuleManager', 'Module download failed! (%error%)', array('%error%' => $ex->getMessage())));
082         }
083 
084         // Extract Package
085         if (file_exists($downloadTargetFileName)) {
086             // Unzip
087             $zip = new ZipArchive;
088             $res = $zip->open($downloadTargetFileName);
089             if ($res === TRUE) {
090                 $zip->extractTo($modulePath);
091                 $zip->close();
092             } else {
093                 throw new CHttpException('500', Yii::t('AdminModule.libs_OnlineModuleManager', 'Could not extract module!'));
094             }
095         } else {
096             throw new CHttpException('500', Yii::t('AdminModule.libs_OnlineModuleManager', 'Download of module failed!'));
097         }
098 
099         ModuleManager::flushCache();
100 
101         // Call Modules autostart
102         $autostartFilename = $modulePath . DIRECTORY_SEPARATOR . $moduleId . DIRECTORY_SEPARATOR . 'autostart.php';

Stack Trace
#0 	
–
 /var/www/humhub/protected/modules_core/admin/libs/OnlineModuleManager.php(90): ZipArchive->extractTo("/var/www/humhub/protected/modules")

85         if (file_exists($downloadTargetFileName)) {
86             // Unzip
87             $zip = new ZipArchive;
88             $res = $zip->open($downloadTargetFileName);
89             if ($res === TRUE) {
90                 $zip->extractTo($modulePath);
91                 $zip->close();
92             } else {
93                 throw new CHttpException('500', Yii::t('AdminModule.libs_OnlineModuleManager', 'Could not extract module!'));
94             }
95         } else {

#1 	
–
 /var/www/humhub/protected/modules_core/admin/controllers/ModuleController.php(134): OnlineModuleManager->install("mostactiveusers")

129 
130         $moduleId = Yii::app()->request->getQuery('moduleId');
131 
132         if (!Yii::app()->moduleManager->isInstalled($moduleId)) {
133             $onlineModules = new OnlineModuleManager();
134             $onlineModules->install($moduleId);
135         }
136 
137         // Redirect to Module Install?
138         $this->redirect(Yii::app()->createUrl('admin/module/list'));
139     }

#2 	
+
 /var/www/humhub/protected/vendors/yii/web/actions/CInlineAction.php(49): ModuleController->actionInstall()
#3 	
+
 /var/www/humhub/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams(array("r" => "admin/module/install", "moduleId" => "mostactiveusers"))
#4 	
+
 /var/www/humhub/protected/vendors/yii/web/filters/CFilterChain.php(133): CController->runAction(CInlineAction)
#5 	
+
 /var/www/humhub/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run()
#6 	
+
 /var/www/humhub/protected/vendors/yii/web/CController.php(1145): CFilter->filter(CFilterChain)
#7 	
+
 /var/www/humhub/protected/vendors/yii/web/filters/CInlineFilter.php(58): CController->filterAccessControl(CFilterChain)
#8 	
+
 /var/www/humhub/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter(CFilterChain)
#9 	
+
 /var/www/humhub/protected/vendors/yii/web/CController.php(291): CFilterChain->run()
#10 	
+
 /var/www/humhub/protected/vendors/yii/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array("accessControl"))
#11 	
+
 /var/www/humhub/protected/vendors/yii/web/CWebApplication.php(282): CController->run("install")
#12 	
+
 /var/www/humhub/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController("admin/module/install")
#13 	
+
 /var/www/humhub/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest()
#14 	
–
 /var/www/humhub/index.php(39): CApplication->run()

34 Yii::import('application.vendors.*');
35 EZendAutoloader::$prefixes = array('Zend', 'Custom');
36 Yii::import("ext.yiiext.components.zendAutoloader.EZendAutoloader", true);
37 Yii::registerAutoloader(array("EZendAutoloader", "loadClass"), true);
38 
39 $app->run();

    
When trying to access the modules repository to manually perform the installation found that the .zip file is damaged below is the error reported when trying to unzip the .zip and the module address within the repository:
Repository: https://www.humhub.org/modules/60/

Erro .zip: 
7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=pt_BR.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)

Processing archive: /home/user/Downloads/60.zip

Extracting  mostactiveusers/views/mostActiveUsers
can not open output file /home/user/Downloads/60/mostactiveusers/views/mostActiveUsers/list.php
Extracting  mostactiveusers/views/config/config.php
ERROR: Can not delete output file /home/user/Downloads/60/mostactiveusers/views/config
ERROR: Can not delete output file /home/user/Downloads/60/mostactiveusers/views
Extracting  mostactiveusers/widgets/views
can not open output file /home/sales/Downloads/60/mostactiveusers/widgets/views/mostActiveUsersPanel.php
ERROR: Can not delete output file /home/user/Downloads/60/mostactiveusers/widgets
Extracting  mostactiveusers/widgets/MostActiveUsersSidebarWidget.php
Extracting  mostactiveusers/autostart.php
Extracting  mostactiveusers/assets
can not open output file /home/user/Downloads/60/mostactiveusers/assets/module_image.png
Extracting  mostactiveusers/forms/MostActiveUsersConfigureForm.php
ERROR: Can not delete output file /home/user/Downloads/60/mostactiveusers/forms
Extracting  mostactiveusers/README.md
Extracting  mostactiveusers/module.json
Extracting  mostactiveusers/resources
can not open output file /home/sales/Downloads/60/mostactiveusers/resources/mostactiveusers.css
Extracting  mostactiveusers/MostActiveUsersModule.php
Extracting  /srv/www/www.humhub.org/htdocs/modules/60
Extracting  mostactiveusers/controllers
can not open output file /home/user/Downloads/60/mostactiveusers/controllers/MostActiveUsersController.php
can not open output file /home/user/Downloads/60/mostactiveusers/controllers/ConfigController.php
ERROR: Can not delete output file /home/user/Downloads/60/mostactiveusers

Sub items Errors: 11

**Comment by nomadkira** [comment]
I had the same problem, i uploaded the .php file from a older version and it worked again

**Comment by mrluisiko99** [comment]
I think this issue would have to be here https://github.com/humhub/humhub-modules-mostactiveusers/issues

**Comment by drpacheco** [comment]
thank you @mrluisiko99 , I just create a question there :+1: https://github.com/humhub/humhub-modules-mostactiveusers/issues/1

**Comment by luke-** [comment]
Is fixed, was an broken ZIP Archive
