### ISSUE TITLE
Depreciated apple meta name apple-mobile-web-app-capable

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub#7242]
Google Lighthouse complains about:
`<meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">`

Changing line 39 of sftp://www.alforto.nl/var/www/html/pro.3de5.nl/humhub/protected/humhub/modules/web/pwa/widgets
from:       `$view->registerMetaTag(['name' => 'apple-mobile-web-app-capable', 'content' => 'yes']);`
in:         `$view->registerMetaTag(['name' => 'mobile-web-app-capable', 'content' => 'yes']); `
solved the problem.

**Comment by luke-** [comment]
@aronbos Thanks, it's already fixed in the upcoming version. https://github.com/humhub/humhub/pull/7219/files
