### ISSUE TITLE
Remove header X-Xss-Protection and X-Content-Security-Policy

### ISSUE THREAD

**Issue by aronbos** [humhub/humhub#7249]
### X-XSS-Protection

Humhub sets the  "X-XSS-Protection" => "1; mode=block", in web.php. Please remove it.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection says:

Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

The HTTP X-XSS-Protection response header was a feature of Internet Explorer, Chrome and Safari that stopped pages from loading when they detected reflected cross-site scripting ([XSS](https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting)) attacks. These protections are largely unnecessary in modern browsers when sites implement a strong [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) that disables the use of inline JavaScript ('unsafe-inline').

Warning: Even though this feature can protect users of older web browsers that don't yet support [CSP](https://developer.mozilla.org/en-US/docs/Glossary/CSP), in some cases, XSS protection can create XSS vulnerabilities in otherwise safe websites. See the section below for more information.

### X-Frame-Options
Also, remove  "X-Frame-Options" => "sameorigin",
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options says:
Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

Warning: Instead of this header, use the frame-ancestors directive in a Content-Security-Policy header.

### X-Content-Security-Policy
Debugging code I saw that Humhub sets de CSP double. With and without X- .  Wouldn't  it be better to use only the standard without X-?
https://owasp.org/www-community/controls/Content_Security_Policy says:
Content-Security-Policy : Defined by W3C Specs as standard header, used by Chrome version 25 and later, Firefox version 23 and later, Opera version 19 and later.
X-Content-Security-Policy : Used by Firefox until version 23, and Internet Explorer version 10 (which partially implements Content Security Policy).

Be changing line 155 in /protected/humhub/modules/web/security/models/securitySettings.php from:
return [static::HEADER_CONTENT_SECRUITY_POLICY], static::HEADER_CONTENT_SECRUITY_POLICY_IE];
to
return [static::HEADER_CONTENT_SECRUITY_POLICY]; //  , static::HEADER_CONTENT_SECRUITY_POLICY_IE]; 
you disable the old IE setting and hence the double policy.

**Comment by luke-** [comment]
@aronbos Thanks for the overview. We'll check

**Comment by luke-** [comment]
Will be removed in the next version.
