### ISSUE TITLE
Delete Uploaded Files / File Managment

### ISSUE THREAD

**Issue by nomadkira** [humhub/humhub#725]
HI,

wondering, if i upload a file how will all of these files be deleted ? Once if i attach a file to a comment and i delete the comment the file will remain on the server. I guess, one day we will be in trouble with a lot of dead files. Or did i miss something ?

**Comment by mrluisiko99** [comment]
+1

**Comment by Stranikevg** [comment]
+1

**Comment by luke-** [comment]
All unused files will be deleted on daily cron run:

https://github.com/humhub/humhub/blob/master/protected/modules_core/file/FileModuleEvents.php#L52-L58
