### ISSUE TITLE
Show "Powered by HumHub" even if no entries in the Footer menu

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7252]
### Is your feature request related to a problem? Please describe.

If no entries are added to the footer menu (e.g. via the Legal Terms module), the "Powered by HumHub" is not displayed.

This is because of:
- https://github.com/humhub/humhub/blob/cb8e56c45051b6a7a179da07a3712fde0f9f5c81/protected/humhub/modules/ui/menu/widgets/Menu.php#L81-L81
- and https://github.com/humhub/humhub/blob/cb8e56c45051b6a7a179da07a3712fde0f9f5c81/protected/humhub/widgets/views/footerNavigation.php#L19-L19

### Describe the solution you'd like

Add the `PoweredBy::widget()` as a menu entry and remove it from the `protected/humhub/widgets/views/footerNavigation.php` view.

### Describe alternatives you've considered

In the `protected/humhub/widgets/FooterMenu.php` class, replace:
```php
    public function run()
    {
        // Make sure Footer on login for powered by
        if (empty($this->entries) && $this->location === static::LOCATION_LOGIN) {
            return $this->render($this->template, $this->getViewParams());
        }

        return parent::run();
    }
```

With:
```php
    /**
     * Make sure "Powered by" is displayed even if no entries in the menu
     * @inheritDoc
     */
    public function run()
    {
        $this->trigger(static::EVENT_RUN);
        return $this->render($this->template, $this->getViewParams());
    }
```

**Comment by marc-farre** [comment]
@luke- I can send a PR if you agree with this. Let me know which solution you prefer.

**Comment by luke-** [comment]
@Semir1212 Currently, we only display “Powered by HumHub” if there are more entries in the footer navigation. We decided that years ago. Do we want to keep it that way or always display it?

**Comment by luke-** [comment]
@marc-farre Ok, please create a PR.

**Comment by marc-farre** [comment]
@Semir1212 thanks

@luke- PR https://github.com/humhub/humhub/pull/7256

FYI, the `hidePoweredBy` param in the configuration file still works in this PR.
