### ISSUE TITLE
Profile "About" page: don't display the menu if only one entry

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7265]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/88776954-f602-47c4-bf2c-8daaeacc4a7c)

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/1d6b6af5-75bf-4a48-a040-f1973712cd16)

By surrounding https://github.com/humhub/humhub/blob/571e1d2f8d49c3d34bde217bdbd280f10e6f5259/protected/humhub/modules/user/views/profile/about.php#L19-L29 with a if

**Comment by marc-farre** [comment]
@luke- If you agree, I can send a PR

**Comment by luke-** [comment]
@marc-farre Yes, sounds good!

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/7268
