### ISSUE TITLE
Mass deletion of members

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#7275]
### Is your feature request related to a problem? Please describe.
To delete or desactivate members you will browse to "admin / users" page and you will  delete users **one by one**.
That's a pain if you need to delete a significant number or users.

### Describe the solution you'd like
In the users table.
- Add a checkbox to each line
- Add a button 'Desactivate selected users" and a button 'Delete selected users"

### Describe alternatives you've considered
There is already a Dedicated module [https://marketplace.humhub.com/module/user-cleanup/description](https://marketplace.humhub.com/module/user-cleanup/description)
But it does the work on a fully  automatic way, while I would prefer to trigger deletion manualLy

Also refer to  [https://community.humhub.com/content/perma?id=282083](https://community.humhub.com/content/perma?id=282083)

**Comment by ArchBlood** [comment]
Related to #4908
