### ISSUE TITLE
Cron jobs cannot "Create public content" (since 1.15.3)

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7276]
### What steps will reproduce the problem?

1. In the Space security, set:
    - Visibility: Public
    - Default content visibility: Private
3. Create a content with a cron job (from a ContentActiveRecord object).
4. Make the content public
5. Save

E.g.:

```php
$object = new MyCustomContent();
$object->content->visibility = 1;
$object->save();
```

### What is the expected result?

The content is public.

### What do you get instead?

The content is private.

### Additional info

This issue has been introduced in 1.15.3 here: 
https://github.com/humhub/humhub/commit/9c5a54ef3a#diff-b3de8a7bb84547e2de7081f31795f491fb051a7df7042d02d991041ee0235a51R220-R229

Because `$this->container->can(CreatePublicContent::class)` is not true for cron jobs.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.3 and later

**Comment by marc-farre** [comment]
@yurabakhtin @luke- PR https://github.com/humhub/humhub/pull/7277

Done on `master` branch (we mustn't forget to merge it to `develop` branch).

**Comment by luke-** [comment]
@yurabakhtin Can you please review and merge?

**Comment by marc-farre** [comment]
@yurabakhtin Do you know why tests are broken with this PR?
It doesn't seem to be related to the changes, or am I wrong?

**Comment by yurabakhtin** [comment]
> @yurabakhtin Do you know why tests are broken with this PR? It doesn't seem to be related to the changes, or am I wrong?

@marc-farre Yes, the test error is not related to your PR, I think. I could not find a reason of the error. The test code looks correctly.

**Comment by marc-farre** [comment]
@yurabakhtin if everything's fine, can you merge https://github.com/humhub/humhub/pull/7277 ?
Thanks.
