### ISSUE TITLE
Installation PHP Warning

### ISSUE THREAD

**Issue by SAYConnected** [humhub/humhub#728]
Config:
Debian wheezy
PHP 5.4.35-0+deb7u2 (cli) (built: Nov 19 2014 07:56:24)
Install Method:
cd /path/..
wget https://github.com/humhub/humhub/archive/master.zip
chown 
chmod :
 - /assets
- /protected/runtime
- /protected/modules
- /protected/config/local
- /uploads/*

Error /var/www/clients/client3/web84/web/protected/vendors/yii/YiiBase.php(414)

see the attachment
![screen shot 2015-02-15 at 4 53 38 pm 2](https://cloud.githubusercontent.com/assets/7984070/6202867/d708d520-b534-11e4-9422-82d94723a777.png)

**Comment by bastrian** [comment]
The error says that it does not have access due open_basedir to /usr/share/pear/ 
You can change the open_basedir settings in php.ini
http://php.net/manual/en/ini.core.php#ini.open-basedir

**Comment by luke-** [comment]
Not sure how to avoid this: https://github.com/humhub/humhub/issues/129
