### ISSUE TITLE
1.17-beta-1 - Prerequisites: false warning for "Mobile App - Push Service"

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7282]
### What steps will reproduce the problem?

1. Install and configure the "Mobile App - Push Service" module on HumHub 1.17-beta-1
2. Go to Prerequisites

### What is the expected result?

No warning

### What do you get instead?

HumHub - Mobile App - Push Service (Hint: "Push Notifications (Firebase)" module and setup of Firebase API Key required)

### Additional info

Discussion: https://community.humhub.com/content/perma?id=282143

| Q                | A
| ---------------- | ---
| HumHub version   | 1.17-beta-1

**Comment by yurabakhtin** [comment]
@luke- Fixed in the PR https://github.com/humhub/humhub/pull/7283.

@marc-farre Just for info, I see [here](https://github.com/humhub/humhub/pull/7166/files#diff-864ee5d29be553a1a5776cf6cea6e7190eea1b0c7a03ef5edd005e8d2b87fe58R950) you forgot to move the array `$modules` into the new method.

**Comment by marc-farre** [comment]
@yurabakhtin Thank you very much!
