### ISSUE TITLE
Define topics at top/network level

### ISSUE THREAD

**Issue by philippconzett** [humhub/humhub#7289]
### Is your feature request related to a problem? Please describe.
In our planned HumHub network, different spaces will be dealing with many of the same topics, e.g., "File format", "Metadata", "License" etc. In the current HumHub setup, topics are defined at space-level, thus "File format" needs to be defined as a topic in each space where this topic is relevant. Network members who are members of several spaces need to be able to search for topics across spaces. However, in the current setup, "identical" topics are listed multiple times, once for each space they are found in; see this screenshot, where "Filformat" (Norwegian for 'file format') is listed three times:

![image](https://github.com/user-attachments/assets/238ca2a4-1ea6-4dc3-9522-46294b242b42)

### Describe the solution you'd like
To make search across spaces more streamlined and coherent, we'd like HumHub to allow topics to be defined at top/network level and being inherited to spaces.

### Describe alternatives you've considered
A more cumbersome alternative could be to add the name of the space to "shared" topics, e.g., "Topic 1 - Space 1", "Topic 1 - Space 2", "Topic 1 - Space 3", etc. This would require users to select multiple topics when searching for basically the same topic/concept.

**Comment by ArchBlood** [comment]
I believe @gevorgmansuryan and @luke- have made many changes to Topics in this regard https://github.com/humhub/humhub/pull/7223.

**Comment by gevorgmansuryan** [comment]
@philippconzett Now it’s possible to create a global topic and use it in multiple spaces/profiles

**Comment by philippconzett** [comment]
@gevorgmansuryan Ah, great! Thanks for this information. We're currently testing HumHub on the demo instance, which is on version 1.16.2.
