### ISSUE TITLE
reduce size top button on mobile version

### ISSUE THREAD

**Issue by ilMagnifico** [humhub/humhub#7290]
reduce size top button on mobile version so that it doesn't get too near the "send" button on post/comment.
![Screenshot_20241101_114253](https://github.com/user-attachments/assets/4d0ee07c-3c48-4b99-8056-954f5bc97fbb)

**Comment by marc-farre** [comment]
@ilMagnifico I think this is the [Scroll Up module](https://marketplace.humhub.com/module/scrollup/description).
@ArchBlood I'm I right?

**Comment by ilMagnifico** [comment]
> @ilMagnifico I think this is the [Scroll Up module](https://marketplace.humhub.com/module/scrollup/description). @ArchBlood I'm I right?

I believe.

**Comment by ArchBlood** [comment]
Thanks for the mention, yes, this button is of the scroll up module, can you close this issue and open a new one over here?

https://github.com/GreenMeteor/premium-modules/issues
