### ISSUE TITLE
Logo preview cropped by rounded corners

### ISSUE THREAD

**Issue by dantefromhell** [humhub/humhub#7304]
### What steps will reproduce the problem?
- Upload a logo in the *Appearance* settings (https://loveinaction.community/admin/setting/design) that is wide and see the preview being cropped around the edges.
![image](https://github.com/user-attachments/assets/87c48fa8-41c3-4942-a51f-3d6cae0f5764)

### What is the expected result?
In my testing the issue seems to be the `class="img-rounded"` attribute.
Removing this yields a correct display of the image:

![image](https://github.com/user-attachments/assets/e7933abf-f200-4518-8ce1-7d53b16b95e2)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.2
| PHP version      | 8.2
| Operating system | Alpine

**Comment by marc-farre** [comment]
@dantefromhell This a bug of the Clean Theme. It has been fixed, but the new version with the fix is not yet released.

**Comment by dantefromhell** [comment]
@marc-farre 
Are you pointing to the `border-radius: 50%` setting coming from the Clean Theme?

I have tested this with the default theme on `1.16.2` and the border radius is applied too, but with much lower values: `border-radius: 3px;`

Hence my proposed PR to completly remove the rounded borders on the logo in order to not interfere with how a platforms logo gets displayed.

**Comment by marc-farre** [comment]
@dantefromhell Yes, your PR makes sense too.
@luke- do you think we should remove the `img-rounded` class?
https://github.com/humhub/humhub/pull/7305/files

**Comment by luke-** [comment]
@marc-farre Not sure. Can you please check that we really do not need the class?

**Comment by marc-farre** [comment]
@luke- It's not a problem to leave it. It has no visual impact (it had in a previous version of the Clean Theme, but it's fixed).

However, @dantefromhell says that it should be removed because this `img-rounded` class means that the image should be rounded, whereas here we don't want the corners to be rounded.

But I don't know the side effects of removing it.

**Comment by luke-** [comment]
@marc-farre @dantefromhell  Hmm, especially with full-surface logos, the edges are rounded.

![image](https://github.com/user-attachments/assets/1fca2b92-97bc-4faa-a01c-8e68b4cb660c)

I would maybe change this behavior with the larger BS5 change.
But not now, in the beta.3.

So I'll postpone the PR for v18.

Thanks!

**Comment by marc-farre** [comment]
@luke- Yes, I agree, it's better to wait for Bootstrap 5.
Just for your info, @dantefromhell was mentioning the /admin/setting/design page:
![image](https://github.com/user-attachments/assets/52f68d52-bb4c-4a77-bf55-e7d4ec03f6a4)
