### ISSUE TITLE
send email event

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#7314]
### Is your feature request related to a problem?
I intend to built a  module where I would need a mail counter.
As far as I see, sending a mail doesn't trigger any event 

### Describe the solution you'd like
Add an event,  someting like Mail::EVENT_SEND,  Mail::EVENT_BEFORE_ SEND,  Mail::EVENT_AFTER_ SEND would be perfect

### Describe alternatives you've considered
Also see [this post](https://community.humhub.com/content/perma?id=282522)

**Comment by luke-** [comment]
What do you think? 
```
        ['class' => \yii\mail\BaseMailer::class, 'event' => \yii\mail\BaseMailer::EVENT_BEFORE_SEND, 'callback' => ['humhub\modules\example\Events', 'onBeforeMailSend']],
```

**Comment by Gilbertdelyon** [comment]
This is exactly [what I found in the meantime.](https://community.humhub.com/comment/perma?id=50826)
it works!
Thank you @luke-
