### ISSUE TITLE
New user sign up on my Humhub community version doesn't work.

### ISSUE THREAD

**Issue by Dee1266** [humhub/humhub#7318]
### Additional info 

| Q                | A
| ---------------- | ---
| HumHub version   | 1.?
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
@Dee1266 can you please be more specific and provide more information on the issues you're facing?

**Comment by Dee1266** [comment]
I have successfully installed a copy of Humbub from Softaculous in C-panel.
I have been doing the customization as the Admin.
I tried to register as a new user from another computer using another email but couldn't register. The sign up interface needs just an email address and captcha input. I tried several times to input the captcha but each time, the registration won't go through. The interface refreshes and shows a new captcha, and on and on.
![WechatIMG7584](https://github.com/user-attachments/assets/2c5e3fe8-bbfe-4ace-8154-a511d3d273d0)
![WechatIMG7585](https://github.com/user-attachments/assets/30ed45f5-6d67-4921-bd00-0dbe0aba8205)
![WechatIMG7586](https://github.com/user-attachments/assets/af38d9ab-a873-4bd5-98dd-1082cadf8d79)

![WechatIMG7587](https://github.com/user-attachments/assets/57ba874f-be12-49d0-9c12-5f33a2dacd9d)

**Comment by marc-farre** [comment]
@Dee1266 Softaculous is sadly not well maintaining HumHub app. So it's not recommended to install it via this software packager.
Even if you make it work, you will have troubles to update HumHub core to new versions.
Please use the official package instead: https://docs.humhub.org/docs/admin/installation

**Comment by Dee1266** [comment]
Thank you for the response Marc.
Oh that's sad that we can't depend on the package from Softaculous. Their installation process is really smooth. I have checked out the installation link you provided. It's not an easy task. Not for someone with basic knowledge.
Anyone offering an installation service for pay?

**Comment by Dee1266** [comment]
I wish someone had like a YouTube tutorial on this.

**Comment by marc-farre** [comment]
The easier and most reliable solution is HumHub SaaS offer: https://saas.humhub.com/en/create
Other solutions (you need to have create an account, it's free): https://community.humhub.com/s/hosting/wiki/72/homepage
Help with installation is here: https://community.humhub.com/s/installation-and-setup/
