### ISSUE TITLE
Edit Post No Submit Button

### ISSUE THREAD

**Issue by AJAyers1** [humhub/humhub#733]
When I Hit "Edit Post" a text line box pops up but no submit button to confirm the changes.

**Comment by andystrobel** [comment]
It's working the same way like on facebook. Please use Shift+Enter for new lines and the Enter key for submit.

**Comment by AJAyers1** [comment]
Still not working for me.. When I hit Enter is just creates new lines.

**Comment by andystrobel** [comment]
Hm ok... which release of HumHub you are using (or the current master)?, Which OS and which browser?

**Comment by AJAyers1** [comment]
Current-Master        Hosted on CentOS 6.5 my PC is Windows 8.1    Trie don Chrome and IE

**Comment by andystrobel** [comment]
And it is only when you edit a comment? When you create a new one, it works!?!

**Comment by AJAyers1** [comment]
Correct, on some I cannot even get the edit screen to pop. Is there maybe a PHP module malfunctioning? Everything was green during install.

**Comment by andystrobel** [comment]
Can you please try it again with the current master?

**Comment by WASasquatch** [comment]
Possibly related to placeholder JS?
