### ISSUE TITLE
Cannot run gii showing error 

### ISSUE THREAD

**Issue by codinglover** [humhub/humhub#736]
Hi there i am new to humhub actually,
I just installed the gii module and enabled it set the password also the IP address i am access using localhost and xampp but it showing error : 
Error 403
You are not allowed to access this page.

i have tried in many ways as i found in the web adding the ip in _default.php page and on other pages as described. even disabled the ip filter still couldn't run it at all.

any help ?

**Comment by codinglover** [comment]
problem solved :) just needed to edit the the ipfilter from YiiGiiModule.php and update again

**Comment by luke-** [comment]
You can also edit the ipfilter in Administration -> Modules -> YiiGii -> Configure
