### ISSUE TITLE
Dashboard doesn't reload automatically and follow with follow back option

### ISSUE THREAD

**Issue by codinglover** [humhub/humhub#737]
Hi there,
I am new to humhub and liking it much but few things that i found if updated would be really nice. First the dashboard doesn't reload automatically. Any way to reload it automatically. Secondly, the follow system which is like Add as a friend should have to have follow back option i guess. Like facebook friend adding and no friend. Couldn't find the option to make posts private that only friends can see not everyone.

If smeone can help would be really nice.

Thanks
Regards

**Comment by luke-** [comment]
Please avoid to combine multiple issues into one.

Also duplicate:
https://github.com/humhub/humhub/issues/229
https://github.com/humhub/humhub/issues/532
