### ISSUE TITLE
General user invite to the platform (independent from spaces)

### ISSUE THREAD

**Issue by andystrobel** [humhub/humhub#738]
At the moment it's only possible to invite external people into a space.

**Comment by programguy** [comment]
+1
It would also be nice to allow admins to invite new users by email without letting other standard users do that.

**Comment by SimonBaeumer** [comment]
+1

**Comment by Darren66** [comment]
+1

**Comment by vladanPro** [comment]
+1 for sure :)

**Comment by buddha87** [comment]
Can now be done within the directory under "New people"
