### ISSUE TITLE
A few identical notices, why?

### ISSUE THREAD

**Issue by daglex** [humhub/humhub#745]
A very strange phenomenon, comes to the post a few identical notices that someone has left a comment on the site. Who else is watching such a problem? 

For example, this photo where several identical notifications http://awesomescreenshot.com/05f4913v13 

The same situation in the Activity Stream http://awesomescreenshot.com/0614915jec

Here's a look yet, comment left alone, but in the last action block this comment is displayed several times, 4 times.  http://awesomescreenshot.com/0a04ar9e32

On HumHub also have this problem http://awesomescreenshot.com/01d4ard782

Discussion of the problem here http://community.humhub.com/wall/perma/content/model/Post/id/1121

**Comment by Vatarus** [comment]
Same problem

**Comment by bastrian** [comment]
Some Debug Logs, including Apache Logs would turn useful. I will try to reproduce it. 
@Vatarus Could you please describe the Steps to reproduce the Error?

**Comment by daglex** [comment]
I personally do not understand the reason, I can not reproduce the error.

**Comment by luke-** [comment]
Any news about this issue? Does this still happen with 0.11.x?

**Comment by daglex** [comment]
I have the latest version, but the problem has not been resolved.

**Comment by luke-** [comment]
Please reopen if appears on 0.20.x+
