### ISSUE TITLE
Overwrite ProfileFieldType class

### ISSUE THREAD

**Issue by SirbitoX** [humhub/humhub#749]
I want to change rule of validating input date in ProfileFieldTypeDateTime.php file in model of user module (in modules of core); but I don't want to change the core. Is there any solution to override it or extend this class in my own theme (like other views)?
p.s. the path of the file: /modules_once/user/models/ProfileFieldTypeDateTime.php. and I want to change getFieldRules function.

**Comment by luke-** [comment]
Hm, I don't think this is possible yet.

If this is a general validation feature you could directly add this to the core ProfileFieldTypeDateTime.

Otherwise you can try to make the ProfileField system more dynamic - so it support custom profile fields.
