### ISSUE TITLE
include_once(Zend/Uri/Http.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by xandro-at** [humhub/humhub#753]
When I click on Moduls in the Admin Section, i get the following error:

```
include_once(Zend/Uri/Http.php): failed to open stream: No such file or directory
```

**Comment by luke-** [comment]
can you try to reinstall it? Maybe there are some missing files?

Please check this file exists in your installation:
https://github.com/humhub/humhub/blob/master/protected/vendors/Zend/Uri/Http.php

**Comment by xandro-at** [comment]
a reinstallation did not solve the problem, the file in protected/vendors/Zend/Uri/Http.php exists.

**Comment by WASasquatch** [comment]
Why is it handing the path as `Zend/Uri/Http.php` and not a full path? If youre in the base directory of your humhub installation when running the script wouldn't a url like `Zend/Uri/Http.php` throw a error because it's missing the `protected/` bit in front? 

Confused at the functionality here.

**Comment by xandro-at** [comment]
Here ist the solution!

1. I reinstalled humhub

2. There was a problem because my Zend-Framework installation was in /usr/share/php and not /usr/share/pear

3. My fault was, that i tried to install the Modules by putting them into the modules folder by FTP.

Now it's everything allright!

**Comment by WASasquatch** [comment]
Glad you got that problem resolved. Are you by chance on CentOS? I've had that same issue with Zend before.

**Comment by xandro-at** [comment]
I'm working on Ubuntu 12.04.5 LTS.

**Comment by WASasquatch** [comment]
Oh alright. I haven't had that issue on Debian based OS systems. Weird.
