### ISSUE TITLE
Cannot Decline Member

### ISSUE THREAD

**Issue by AJAyers1** [humhub/humhub#755]
PHP notice

Trying to get property of non-object

/home/admin/web/platinumserverteam.com/public_html/workgroup/protected/modules_core/user/models/ProfileFieldTypeText.php(178)

166             $errorMsg = $this->regexpErrorMessage;
167             if ($errorMsg == "") {
168                 $errorMsg = "Invalid!";
169             }
170             $rules[] = array($this->profileField->internal_name, 'match', 'pattern' => $this->regexp, 'message' => $errorMsg);
171         }
172 
173         return parent::getFieldRules($rules);
174     }
175 
176     public function getUserValue($user, $raw = true) {
177         $internalName = $this->profileField->internal_name;
178         $value = $user->profile->$internalName;
179 
180         if (!$raw && $this->validator == self::VALIDATOR_EMAIL) {
181             return HHtml::link($value, $value);
182         } elseif (!$raw && $this->validator == self::VALIDATOR_URL) {
183             return HHtml::link($value, $value, array('target'=> '_blank'));
184         }
185 
186         return $value;
187     }
188 
189 }
190 
Stack Trace
#0	
–  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/modules_core/user/models/ProfileField.php(331): ProfileFieldTypeText->getUserValue(null, true)
326      *
327      * @return type
328      */
329     public function getUserValue($user, $raw = true)
330     {
331         return $this->fieldType->getUserValue($user, $raw);
332     }
333 
334     /**
335      * Returns the translation category 
336      * Defaults to: models_Profile
#1	
–  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/modules_core/user/models/Profile.php(243): ProfileField->getUserValue(null)
238         $criteria->condition .= "visible = 1";
239         $criteria->order = "sort_order";
240 
241         foreach (ProfileField::model()->findAll($criteria) as $field) {
242 
243             if ($field->getUserValue($this->user) != "") {
244                 $fields[] = $field;
245             }
246         }
247 
248         return $fields;
#2	
–  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/modules_core/user/models/User.php(562): Profile->getProfileFields()
557         );
558 
559         $profile = $this->getProfile();
560 
561         if (!$profile->isNewRecord) {
562             foreach ($profile->getProfileFields() as $profileField) {
563                 $attributes['profile_' . $profileField->internal_name] = $profileField->getUserValue($this, true);
564             }
565         }
566 
567         return $attributes;
#3	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/libs/HSearch.php(131): User->getSearchAttributes()
#4	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/modules_core/user/models/User.php(423): HSearch->deleteModel(User)
#5	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/db/ar/CActiveRecord.php(1220): User->beforeDelete()
#6	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/modules_core/admin/controllers/ApprovalController.php(126): CActiveRecord->delete()
#7	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/actions/CInlineAction.php(49): ApprovalController->actionApproveUserDecline()
#8	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams(array("r" => "admin/approval/approveUserDecline", "id" => "12"))
#9	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/filters/CFilterChain.php(133): CController->runAction(CInlineAction)
#10	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run()
#11	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/CController.php(1145): CFilter->filter(CFilterChain)
#12	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/filters/CInlineFilter.php(58): CController->filterAccessControl(CFilterChain)
#13	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter(CFilterChain)
#14	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/CController.php(291): CFilterChain->run()
#15	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array("accessControl"))
#16	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/CWebApplication.php(282): CController->run("approveUserDecline")
#17	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController("admin/approval/approveUserDecline")
#18	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest()
#19	
+  /home/admin/web/platinumserverteam.com/public_html/workgroup/index.php(39): CApplication->run()

**Comment by luroc** [comment]
Same here. 
The User gets the decline message, but I get the same Error.
When i go to Administration Menu> Users> Edit(of the User I delined) and change 'Status' to 'Enabled', I can delete the Account.

**Comment by luke-** [comment]
Fixed in upcoming 0.11
