### ISSUE TITLE
/admin/setting don't allow default space with a ' inside 

### ISSUE THREAD

**Issue by kowoila** [humhub/humhub#758]
When  choosing default space in admin page, if the name of the space contain a ', it displays in popin but can't be clicked (using Chrome browser)

![screenshot 2015-02-25 a 15 43 25](https://cloud.githubusercontent.com/assets/4354719/6372528/2733a958-bd05-11e4-9e1d-ad948ee7fcad.png)

**Comment by andystrobel** [comment]
Which Chrome version you're using? For me it works fine at Version 41.0.x
