### ISSUE TITLE
feature : have link for current logged user page

### ISSUE THREAD

**Issue by kowoila** [humhub/humhub#759]
context : 
I wanted to add an item "My page" in top navigation menu
The goal of the page is just to have an easier access to the current logged in user's page

What i tried : 
I saw that pages can be refered as /u/userName/home
but i cannot add a link to this page because it's not dynamic

feature : 
Do you think it could be nice to have a link like /u/home
that redirects to current user home ? instead of a 404 ? maybe it can be added in routing ?

Thx :) And by the way, i'm just discovering it but this tool is just F***G Awesome !!! :)) Thx to the team !!

**Comment by luke-** [comment]
Already done :-)
