### ISSUE TITLE
running `yiic message config/i18n.php` does not generate the corresponding files for Installer Module

### ISSUE THREAD

**Issue by ziegenberg** [humhub/humhub#771]
When I try to generate the message files for the Installer Module it does not generate them although I followed the documentation in `/protected/docs/guide/developer/i18n.md` and created the Message Directory `/protected/modules_core/installer/messages/`.

**Comment by ziegenberg** [comment]
Once skimmed through the pile of output generated by `yii message` I found the following.
```
Skip not enabled module: InstallerModule
Skip not enabled module: InstallerModule
```
So I guess that's the culprit.

**Comment by ziegenberg** [comment]
Further findings:
 1. `InstallerModule` is not registered with the app after it is installed (see `/modules_core/installer/autostart.php` for details)
 2. altering `/modules_core/installer/autostart.php` to register it with the app just for the sake of creating the message files makes `yiic message config/i18n.php` crash, so it's not registered for a reason *sigh*
 3. running `yiic message config/i18n.php` in a virgin checkout from git before actual install crashes too as it expects local settings in `protected/config/local/_settings.php`
 4. creating a fake `protected/config/local/_settings.php` and then running `yiic message config/i18n.php` crashed too as it expects a database it can actually connect to.
 5. creating a less fake `protected/config/local/_settings.php` with working database settings and then running again chrashes the same way as in 2. *Yay* I got a loop.

Any ideas?

**Comment by luke-** [comment]
Hi Daniel,

I've enabled the installer in ConsoleApplications.

See autostart.php change: https://github.com/humhub/humhub/commit/a41c5236cd78a5a91db3ef45822d2b4224c3c88a

In develop branch we also added the possibility to switch language during installation.

**Comment by ziegenberg** [comment]
thx
