### ISSUE TITLE
Proper Wiki for HumHub

### ISSUE THREAD

**Issue by bastrian** [humhub/humhub#772]
I would reccomend to setup a proper Wiki for HumHub. Mayby in a subdomain under wiki.humhub.org

The Wiki could be useful to let anyone find quickly Informations about Installation, issues, progress and so on. In addition it could be useful for Devs because we could integrate a dedicated section for Devs. and move/copy all the Docs. to the Wiki.

**Comment by luke-** [comment]
We're launching a Wiki Module for HumHub with the 0.11. release. 
We plan to enable this on our Community and collect docs/issues/roadmap there.
