### ISSUE TITLE
HumHub Community Follow Bug

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#773]
On HumHub.org, I receive multiple notification daily on people who have followed me. Even after viewing the notification. After a 24/hr period it seems to reactivate as unseen. Either that or every one of these users are trolling me and unfollowing, and following me, daily. Lol

**Comment by luke-** [comment]
Hmm, never seen this.

Maybe really a troll? :-)

**Comment by WASasquatch** [comment]
Seems to be the browser battling HumHub's cache control.
