### ISSUE TITLE
Click on Directory Button

### ISSUE THREAD

**Issue by cahuet** [humhub/humhub#774]
Gives:

PHP notice

Trying to get property of non-object

/var/www/humhub/protected/modules_core/directory/widgets/views/groupStats.php(45)

33             <strong><?php echo Yii::t('DirectoryModule.widgets_views_groupStats', 'Average members'); ?></strong><br><br>
34 
35             <input id="group-average" class="knob" data-width="120" data-displayPrevious="true" data-readOnly="true"
36                    data-fgcolor="#7191a8"
37                    data-skin="tron"
38                    data-thickness=".2" value="<?php echo $statsAvgMembers; ?>"
39                    data-max="<?php echo $statsTotalUsers; ?>"
40                    style="font-size: 25px !important; margin-top: 44px !important;">
41         </div>
42         <hr>
43 
44         <div style="text-align: center;">
45             <strong><?php echo Yii::t('DirectoryModule.widgets_views_groupStats', 'Top Group'); ?>:</strong> <?php echo CHtml::encode($statsTopGroup->name); ?>
46         </div>
47     </div>
48 </div>
49 
50 <script>
51     $(function () {
52         $(".knob").knob();
53         $(".knob-container").css( "opacity", 1 );
54     });
55 </script>
Stack Trace
#0	
+  /var/www/humhub/protected/vendors/yii/web/CBaseController.php(130): require("/var/www/humhub/protected/modules_core/directory/widgets/views/g...")
#1	
+  /var/www/humhub/protected/vendors/yii/web/CBaseController.php(95): CBaseController->renderInternal("/var/www/humhub/protected/modules_core/directory/widgets/views/g...", array("statsTotalGroups" => "2", "statsAvgMembers" => 48, "statsTopGroup" => null, "statsTotalUsers" => "96"), false)
#2	
+  /var/www/humhub/protected/vendors/yii/web/widgets/CWidget.php(244): CBaseController->renderFile("/var/www/humhub/protected/modules_core/directory/widgets/views/g...", array("statsTotalGroups" => "2", "statsAvgMembers" => 48, "statsTopGroup" => null, "statsTotalUsers" => "96"), false)
#3	
–  /var/www/humhub/protected/modules_core/directory/widgets/GroupStatisticsWidget.php(28): CWidget->render("groupStats", array("statsTotalGroups" => "2", "statsAvgMembers" => 48, "statsTopGroup" => null, "statsTotalUsers" => "96"))
23         $this->render('groupStats', array(
24             'statsTotalGroups' => $groups,
25             'statsAvgMembers' => round($statsAvgMembers, 1),
26             'statsTopGroup' => $statsTopGroup,
27             'statsTotalUsers' => $users,
28         ));
29     }
30 
31 }
32 
33 ?>
#4	
+  /var/www/humhub/protected/vendors/yii/web/CBaseController.php(167): GroupStatisticsWidget->run()
#5	
–  /var/www/humhub/protected/widgets/StackWidget.php(94): CBaseController->widget("application.modules_core.directory.widgets.GroupStatisticsWidget", array(), true)
89 
90         $i = 0;
91         foreach ($this->getWidgets() as $widget) {
92             $i++;
93 
94             $out = $this->getController()->widget($widget[0], $widget[1], true);
95 
96             if ($out != "") {
97                 $content .= $out;
98                 if ($i != count($this->getWidgets()))
99                     $content .= $this->seperator;
#6	
+  /var/www/humhub/protected/vendors/yii/web/CBaseController.php(173): StackWidget->run()
#7	
–  /var/www/humhub/protected/modules_core/directory/views/directory/_layout.php(79): CBaseController->widget("application.modules_core.directory.widgets.DirectorySidebarWidge...", array("widgets" => array()))
74         <div class="col-md-3">
75             
76             <?php
77             $this->widget('application.modules_core.directory.widgets.DirectorySidebarWidget', array(
78                 'widgets' => array()
79             ));
80             ?>
81         </div>
82     </div>
83 
84 </div>
#8	
+  /var/www/humhub/protected/vendors/yii/web/CBaseController.php(126): require("/var/www/humhub/protected/modules_core/directory/views/directory...")
#9	
+  /var/www/humhub/protected/vendors/yii/web/CBaseController.php(95): CBaseController->renderInternal("/var/www/humhub/protected/modules_core/directory/views/directory...", array("content" => "<div class="panel panel-default groups"> <div class="panel-..."), true)
#10	
+  /var/www/humhub/protected/vendors/yii/web/CController.php(869): CBaseController->renderFile("/var/www/humhub/protected/modules_core/directory/views/directory...", array("content" => "<div class="panel panel-default groups"> <div class="panel-..."), true)
#11	
+  /var/www/humhub/protected/components/Controller.php(198): CController->renderPartial("_layout", array("content" => "<div class="panel panel-default groups"> <div class="panel-..."), false, false)
#12	
+  /var/www/humhub/protected/views/layouts/main.php(212): Controller->renderPartial("_layout", array("content" => "<div class="panel panel-default groups"> <div class="panel-..."))
#13	
+  /var/www/humhub/protected/vendors/yii/web/CBaseController.php(126): require("/var/www/humhub/protected/views/layouts/main.php")
#14	
+  /var/www/humhub/protected/vendors/yii/web/CBaseController.php(95): CBaseController->renderInternal("/var/www/humhub/protected/views//layouts/main.php", array("content" => "<div class="panel panel-default groups"> <div class="panel-..."), true)
#15	
+  /var/www/humhub/protected/vendors/yii/web/CController.php(784): CBaseController->renderFile("/var/www/humhub/protected/views//layouts/main.php", array("content" => "<div class="panel panel-default groups"> <div class="panel-..."), true)
#16	
+  /var/www/humhub/protected/modules_core/directory/controllers/DirectoryController.php(174): CController->render("groups", array("groups" => array(Group, Group)))
#17	
+  /var/www/humhub/protected/vendors/yii/web/actions/CInlineAction.php(49): DirectoryController->actionGroups()
#18	
+  /var/www/humhub/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams(array())
#19	
+  /var/www/humhub/protected/vendors/yii/web/filters/CFilterChain.php(133): CController->runAction(CInlineAction)
#20	
+  /var/www/humhub/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run()
#21	
+  /var/www/humhub/protected/vendors/yii/web/CController.php(1145): CFilter->filter(CFilterChain)
#22	
+  /var/www/humhub/protected/vendors/yii/web/filters/CInlineFilter.php(58): CController->filterAccessControl(CFilterChain)
#23	
+  /var/www/humhub/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter(CFilterChain)
#24	
+  /var/www/humhub/protected/vendors/yii/web/CController.php(291): CFilterChain->run()
#25	
+  /var/www/humhub/protected/vendors/yii/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array("accessControl"))
#26	
+  /var/www/humhub/protected/vendors/yii/web/CWebApplication.php(282): CController->run("groups")
#27	
+  /var/www/humhub/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController("directory/directory/groups")
#28	
+  /var/www/humhub/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest()
#29	
+  /var/www/humhub/index.php(39): CApplication->run()

**Comment by luke-** [comment]
Hmm, sounds like there are no Groups in your installation.
Can you check the group table?

You need at least one group.
