### ISSUE TITLE
Allow maintenance mode

### ISSUE THREAD

**Issue by mrluisiko99** [humhub/humhub#777]

**Comment by mrluisiko99** [comment]
Module in development: https://github.com/WASasquatch/humhub-modules-devmode

**Comment by WASasquatch** [comment]
It is functional now.

**Comment by mrluisiko99** [comment]
Oh... anyway, this issue can be closed ^^

**Comment by WASasquatch** [comment]
You can close your own issues. Edit a post or post a new one and hit "Close"

**Comment by mrluisiko99** [comment]
I didn't know it, thank you.
