### ISSUE TITLE
dificuldades para inscrição de usuários

### ISSUE THREAD

**Issue by socialinkherberth** [humhub/humhub#778]
Oi tudo bem, queria reportar a vocês sobre um bug, meus usuários estão me falando que não estão conseguindo criar uma conta no socialink (minha rede social), eles me falam que a o colocar o email para receber as instruções , eles vão na caixa de entrada e o email não chega. :( me ajudem!

site da minha rede social: socialink.humhub.com

**Comment by luke-** [comment]
English please

**Comment by socialinkherberth** [comment]
Hi all right, quería report one YOU About hum bug , My Users station Speaking me who are not getting CREATE A Account not socialink (My Social Network ), they me speak What Putting the e- mail Receive Pará as INSTRUCTIONS, THEY VAO in inbox OE Enough NOT email . :( Help me !

place of my social network : socialink.humhub.com
