### ISSUE TITLE
Suggestion - Show a notification bubble in "My spaces" when there is new activity

### ISSUE THREAD

**Issue by Lazuis** [humhub/humhub#783]

**Comment by WASasquatch** [comment]
+1

**Comment by andystrobel** [comment]
Is that not still implemented?

![myspaces](https://cloud.githubusercontent.com/assets/6032728/6798209/14176ae2-d20b-11e4-9b97-0267b33678a5.png)

**Comment by WASasquatch** [comment]
I noticed it finally. Maybe change css to danger?

**Comment by andystrobel** [comment]
I think, like now, you have more a difference between Notifications (red bubbles) and activities...

**Comment by WASasquatch** [comment]
True.

**Comment by mrluisiko99** [comment]
Sorry, I meant show a notificación bubble in "My spaces" button. Maybe I have not expressed properly
