### ISSUE TITLE
Upgrade humhub

### ISSUE THREAD

**Issue by yiqiang** [humhub/humhub#785]
Planning to use humhub, a look on the structure similar to Yii1. If it is, i will be quite excited as it will be very good to my project, except, currently yii2 is out, any plans to upgrade humhub to yii2? if not, how can i integrate my yii2 application with humhub

**Comment by SergeyWegner** [comment]
The project Humhab developed as a self-contained project. The project provides for the extension of functionality through plugins. Integration of Your code suggest to implement a plug-in.
