### ISSUE TITLE
unable to be installed on a socket connection

### ISSUE THREAD

**Issue by 314parley** [humhub/humhub#788]
I am unable to successfully install HumHub on a socket connection. I cannot seem to get it working even if I set the host to localhost. Any ideas?

**Comment by luke-** [comment]
What do you mean with install HumHub on a socket connection?

**Comment by 314parley** [comment]
Instead of using a standard connection (like localhost), our host requires us to use [socket connections](http://www.linuxforums.org/forum/servers/1451-what-mysql-sock-file-post8465.html?s=895a3ce5917ed6b86fc2c16b1a269394#post8465) to connect I tried hacking together localhost support, but the software doesn't appear to like that.

**Comment by luke-** [comment]
In installer you try can enter in hostname field: localhost;unix_socket:/path/to/mysqld.sock

Or you can manually change the DB connectionString in protected/config/local/_settings.php

from e.g.
'connectionString' => 'mysql:host=localhost;dbname=humhub',
to
'connectionString' => 'mysql:host=localhost;unix_socket:/path/to/socket/mysql.sock;dbname=humhub',

**Comment by 314parley** [comment]
Thank you luke! got it up and running.

**Comment by mylcon** [comment]
The response of Luke contains a mistake (a semicolon instead of an equal sign). The correct hostname string must be:

;unix_socket=/path/to/mysqld.sock

No need to specify a host before the semicolon, according to the PDO specs.
