### ISSUE TITLE
Comments don't work

### ISSUE THREAD

**Issue by XxidroxX** [humhub/humhub#789]
Hello, I installed this beautiful project but I noticed that when I try to comment on my post, the page is reloaded and the comment does not appear

**Comment by SergeyWegner** [comment]
Какой язык вы использовали при установки?

**Comment by XxidroxX** [comment]
italian

**Comment by luke-** [comment]
Can you try it with English language?

**Comment by SergeyWegner** [comment]
It is important that the database was created with the encoding UTF8
MariaDB [(none)]> CREATE DATABASE `my_db` CHARACTER SET utf8 COLLATE utf8_general_ci;

continue the installation manual for

Write if you helped

**Comment by XxidroxX** [comment]
i will try when i can :)

**Comment by senzaccento** [comment]
Hello,
I'm experiencing the same problem. I'm up to date with the git repo, i created the db with UTF-8 enconding.

My firbug console however say:
SyntaxError: missing ) after argument list (jquery.js:50)

when page loads, and:
Empty string passed to getElementById().

when i click and focus on comments' input box.

Do you have some ideas why it happens?

**Comment by luke-** [comment]
Is this problem related to a particular language?

**Comment by senzaccento** [comment]
I'm writing in italian as xxidroxx, but not using special chars.

**Comment by senzaccento** [comment]
ehi, you got it

switching the app to english language solved the issue.

so it's a problem related to italian tanslation.

**Comment by XxidroxX** [comment]
ok thanks
