### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by Rutzki** [humhub/humhub#790]
When i try to upload a file bigger than 5MB the send button disapear.

Cheers

**Comment by luke-** [comment]
While uploading the send button disappear and a loader is displayed.

can you please provide more infos? e.g. max upload size...

**Comment by Rutzki** [comment]
1. 
![1](https://cloud.githubusercontent.com/assets/11334822/6824591/d696401e-d2f3-11e4-9303-9cd5f3c0f7d2.PNG)

2. start the upload 
![2](https://cloud.githubusercontent.com/assets/11334822/6824590/d69507a8-d2f3-11e4-88db-52019fb69df2.PNG)

3. Upload finished, but the send button is still not displayed
![3](https://cloud.githubusercontent.com/assets/11334822/6824592/d69682b8-d2f3-11e4-850a-f552ca7c960e.PNG)

Max Upload Size is 20MB

**Comment by WASasquatch** [comment]
What is your servers Max timeout, post limit, and upload limit? humhub works off apache/nginx settings. So changing upload size on HumHub wont change server settings.

**Comment by Rutzki** [comment]
thx for the hint with the post timeout, i just forgot that one :)
