### ISSUE TITLE
Code Pseudo Commenting

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#792]
I am not sure if you are aware, but as of PHP 5.3+, and exclusively in PHP6 you are to use only `//` commenting for hidden/nullified/placeholder code, and not text based comments. All comments should be in `/* .. */` format as of PHP6 and good practice in PHP 5.3+ for the up coming PHP release. 

I believe there will be debuggers for viewing/running/counting pseudo code in PHP6 which would mean all HumHub's commenting will be part of that rendering and not placeholder/nullified/old/new code. 

**Example Markup**

``` php
<?php
/*************** 
/* My Fancy Application
/* Version 1.0
/***************/

/*************** 
/* Set greeting!
/***************/

/* Old deutsch greeting */
// $greeting = "Guten Tag!";

$greeting = "Hello World!";

/*************** 
/* Output Greeting
/***************/

echo $greeting;

```

**Comment by luke-** [comment]
Thanks for the hint, can you give me a link for this?

**Comment by WASasquatch** [comment]
I'll have to get back to you on that, it's on php.net somewhere I was reading through all the articles about getting ready for PHP6. My problem with just "pulling it up" is "//" or "/*" is not a valid search keyword, and "comment" brings up every page on the net with a comments section. Lol

**Comment by mrluisiko99** [comment]
It is related with #748 bug?
