### ISSUE TITLE
Read More hiding Video Controls

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#797]
The "Read More" feature is hiding a portion of the videos, namely it's controls. I don't remember this being a issue in previous versions. Happens when adding text. 

<img src="http://i.imgur.com/BdO0bvs.png" />

**Comment by WASasquatch** [comment]
https://github.com/humhub/humhub/commit/8ad17ab585d77ce062354f33d443ac99e363b79f

**Comment by xaro1** [comment]
Anyone have a solution for this issue ?

**Comment by luke-** [comment]
Added new bug here: https://github.com/humhub/humhub/issues/1496
