### ISSUE TITLE
Feature request - RSS actvity feed 

### ISSUE THREAD

**Issue by nunthu** [humhub/humhub#802]
Is there a way to get activity feed for use in something else - like an rss feed?

**Comment by WASasquatch** [comment]
You can make a module for that. Or a view

***Take a look at***: `protected/modules_core/activity/widgets/views/activityStream.php`

The file can be augmented to be a XML file, and then a simple module to output a raw feed using the view and info from the `protected/modules_core/acivity/` module. 

Try looking at the example module and give it a go.

**Comment by simon-roderus** [comment]
+1

**Comment by RamonGuilherme** [comment]
+1

**Comment by ychoucha** [comment]
+1

**Comment by RamonGuilherme** [comment]
+1

**Comment by buddh4** [comment]
will be in the marketplace soon.

**Comment by gerhardbeck** [comment]
Is there now a way to show an RSS Feed in Humhub?

**Comment by buddh4** [comment]
hmm, not sure what happened with this module

**Comment by Profi420** [comment]
Are there any good news?

**Comment by samuk** [comment]
I'd also like this

**Comment by samuk** [comment]
@buddh4 any news on this?

**Comment by ArchBlood** [comment]
> @buddh4 any news on this?

You're probably looking for the following module @samuk, of course, I would ask the developer if the module is currently usable in v1.9.x of HumHub 
https://github.com/StevenJoynt/HumHub-RSS-Reader

**Comment by gerhardbeck** [comment]
> > @buddh4 any news on this?
> 
> https://github.com/StevenJoynt/HumHub-RSS-Reader

Isn't this thread about Humhub offering an RSS-*Feed*?

**Comment by ArchBlood** [comment]
> > > @buddh4 any news on this?
> > 
> > https://github.com/StevenJoynt/HumHub-RSS-Reader
> 
> Isn't this thread about Humhub offering an RSS-*Feed* , too?
> 
> (thanks for the RSS Reader Module. I won't need it any more, find a different was to import my content)
> 
> 
From the module description it does exactly that
> A HumHub module which imports an RSS News Feed as Posts in the Stream of a Space.

**Comment by samuk** [comment]
The reader imports content into humhub. 

This thread is about exporting data from humhub into other places using RSS.

**Comment by jazzcrack** [comment]
> This thread is about exporting data from humhub into other places using RSS.

You are 100% right. Unfortunately, many seem to overlook this. :-/

**Comment by samuk** [comment]
As an aside to this we've recently paid to get a n8n.io Humhub node written. I reckon it should be possible to create an RSS feed from that. Should be landing in n8n in the next few days.

I'll mention it in the community when it's available.
![Screenshot (1)](https://user-images.githubusercontent.com/400875/145463391-fa89a42c-3da7-4055-b63f-7e1f77278eae.png)
