### ISSUE TITLE
Tooltip Hovers above Menus on Scroll

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#803]
When on mobile, if a Tooltip is activated, it will scroll off screen above the first and second bar instead of floating below them. Just a z-index issue but thought I'd point it out.

**Comment by andystrobel** [comment]
At which page you have this issue for example?

**Comment by WASasquatch** [comment]
All pages on mobile. If a tooltip is active and you scroll the page it will
be hovering over the main, and second navigation bars. Not important but
would definitely look more fluid with a z-index lower then the navigation
bars.

**Comment by andystrobel** [comment]
Hm... honestly, I don't see this as a bug... Or prevents this behavior something regarding the menu navigation?

**Comment by WASasquatch** [comment]
It prevents knowing what anything is for users on mobile. That's a serious
bug. Lol

On Fri, Feb 26, 2016 at 9:34 AM, Lucas Bartholemy <notifications@github.com>
wrote:

> Closed #803 <https://github.com/humhub/humhub/issues/803>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/803#event-566710933>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*
