### ISSUE TITLE
Youtube video size was truncated by "read more"

### ISSUE THREAD

**Issue by xaro1** [humhub/humhub#806]
All is in the title...

Browser: Firefox 29

Caused probably by this commit https://github.com/humhub/humhub/commit/7ca2cd927d784d54e7812f275d9135b3d033dde9

**Comment by WASasquatch** [comment]
Check too see if there is already a issue like yours before submitting a issue

https://github.com/humhub/humhub/issues/797

In elaboration, you must strip tags before counting characters.

**Comment by xaro1** [comment]
Ok Policemen, I will do...

**Comment by WASasquatch** [comment]
Doesn't call for being rude. Its a basic rule of GutHub and projects. Saves DB space and confusion. I'm using the search issues tab before posting now to check.

**Comment by xaro1** [comment]
I've used the search tab too (but not used same keywords as yours) before open this bug report. This ticket is now closed. So, don't worry, be happy ;-)

**Comment by WASasquatch** [comment]
Video alone brings up mine...
