### ISSUE TITLE
bug online

### ISSUE THREAD

**Issue by dimontajik** [humhub/humhub#807]
Hi, after installing a bug that when the user does not even online, it is still showing online how to fix?

![-1](https://cloud.githubusercontent.com/assets/10101408/6602512/45ab28a6-c846-11e4-8a84-1873f483bb5c.jpg)

**Comment by dimontajik** [comment]
this is some bug how to fix?

**Comment by dimontajik** [comment]
it appeared after the transition to another hosting

**Comment by dimontajik** [comment]
I can not file some sort of copied?

**Comment by luke-** [comment]
Online users are stored in Mysql tabe "user_http_session" try to delete all entries.

**Comment by dimontajik** [comment]
thank you friend
