### ISSUE TITLE
Big Advance

### ISSUE THREAD

**Issue by wutong** [humhub/humhub#809]
Hello, I installed [Humhub](https://github.com/humhub/humhub) and I feels really good.
I guess Humhub's vision is to be the most popular and useful open-source social network project.
The most popular is done but most useful is not, in my eyes.
Humhub should make some detail position for it.
I thought it's school. Humhub should be a school social network project.
Made for teacher and student and for some club, organizations.
It's should have learning system to let teacher check the report and ...
also can have online teaching system. There is so many ideas for that point.
The important thing is Humhub should change the point.
By the way it's just my opinion. wish you guy's better :smile:

**Comment by WASasquatch** [comment]
HumHub is a Framework. It's whatever type of social network YOU make it into through customization.
