### ISSUE TITLE
Curlopt !!

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#810]
curl_setopt() [<a href='function.curl-setopt'>function.curl-setopt</a>]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set (/home/xxx/public_html/protected/models/UrlOembed.php:182) Stack trace: #0 /home/xxx/public_html/protected/models/UrlOembed.php(106): loadUrl() #1 unknown(0): {closure}() #2 /home/xxx/public_html/protected/models/UrlOembed.php(107): preg_replace_callback() #3 /home/xxx/public_html/protected/modules_core/post/models/Post.php(73): preload() #4 /home/xxx/public_html/protected/vendors/yii/db/ar/CActiveRecord.php(1071): Post->beforeSave() #5 /home/xxx/public_html/protected/vendors/yii/db/ar/CActiveRecord.php(806): Post->insert() #6 /home/xxx/public_html/protected/modules_core/post/controllers/PostController.php(49): Post->save() #7 /home/xxx/public_html/protected/vendors/yii/web/actions/CInlineAction.php(49): PostController->actionPost() #8 /home/xxx/public_html/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #9 /home/xxx/public_html/protected/vendors/yii/web/filters/CFilterChain.php(133): PostController->runAction() #10 /home/xxx/public_html/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #11 /home/xxx/public_html/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #12 /home/xxx/public_html/protected/vendors/yii/web/filters/CInlineFilter.php(58): PostController->filterAccessControl() #13 /home/xxx/public_html/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #14 /home/xxx/public_html/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #15 /home/xxx/public_html/protected/vendors/yii/web/CController.php(265): PostController->runActionWithFilters() #16 /home/xxx/public_html/protected/vendors/yii/web/CWebApplication.php(282): PostController->run() #17 /home/xxx/public_html/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #18 /home/xxx/public_html/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #19 /home/xxx/public_html/index.php(39): WebApplication->run() REQUEST_URI=/post/post/post

**Comment by WASasquatch** [comment]
Well.. read the error, do you have safe_mode enabled, or open_basedir set?
