### ISSUE TITLE
Suggestion: Remove limit to default spaces

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#811]
Can we just not make the list ever expand? I see no real reason why the default spaces would be limited to a number. What if the site only runs of default spaces and no users have the option to create/join spaces other then the "Official" spaces that that a admin has created? We are then limited to X pages.

**Comment by 001101** [comment]
It's possible to add a 1 to row 'auto_add_new_members' at table 'space' and all new members will join spaces which you add the 1, works with my 25 default spaces.
