### ISSUE TITLE
Suggestion: Mail Center

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#815]
It's nice that HumHub has it's own notification system, but as a Social Network, Work Source, University Network, etc, we may need to email members about upcoming events, and or maintenance notifications, and there seems to be no ability to do this, and I do not think it should be a module, but part of the base system as it is a crucial feature among other stuff we have been going over.

**Comment by dakur** [comment]
There are two non-direct possibilities:
1. using module Breaking News - message will be displayed after next page access to all users (but it's global)
2. Notifications are made in a way, that user can see new post inside the notification e-mail. So if he/she receives update notification, then can see, what admin writes.
But it's more not so reliable hack than a function. I agree it could be useful.

**Comment by WASasquatch** [comment]
Yeah I just use the DB and my own template based on HumHub but definitely
needed for maintenance, emergencies, and events or contests.
