### ISSUE TITLE
Oembed doesn't work?

### ISSUE THREAD

**Issue by CKGrafico** [humhub/humhub#819]
I don't know what's the error but when we post something including an url of any oembed provider the server returns a 500 error.
![Error image](http://i.imgur.com/zNX2JsW.png)

**Comment by WASasquatch** [comment]
Use `http` version of the link instead maybe? Insecure connections often fail when the hosting website doesn't have SSL.

**Comment by CKGrafico** [comment]
We tried without https but just the same.

**Comment by luke-** [comment]
Can you provide the error message of 500?

**Comment by CKGrafico** [comment]
HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR): POST - https://helpdev.org/social/index.php?r=post/post/post

**Comment by luke-** [comment]
Can you please check the Apache/PHP Error Log / HumHub Error Log (protected/runtime/application.log) for more infos about this error?

**Comment by CKGrafico** [comment]
Yes:
```
Stack trace:
#0 /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php(106): loadUrl()
#1 unknown(0): {closure}()
#2 /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php(107): preg_replace_callback()
#3 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/post/models/Post.php(73): preload()
#4 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/db/ar/CActiveRecord.php(1071): Post->beforeSave()
#5 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/db/ar/CActiveRecord.php(806): Post->insert()
#6 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/post/controllers/PostController.php(49): Post->save()
#7 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/actions/CInlineAction.php(49): PostController->actionPost()
#8 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams()
#9 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CFilterChain.php(133): PostController->runAction()
#10 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run()
#11 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter()
#12 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CInlineFilter.php(58): PostController->filterAccessControl()
#13 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#14 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(291): CFilterChain->run()
#15 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(265): PostController->runActionWithFilters()
#16 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CWebApplication.php(282): PostController->run()
#17 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController()
#18 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest()
#19 /var/www/vhosts/helpdev.org/httpdocs/social/index.php(39): WebApplication->run()
REQUEST_URI=/social/index.php?r=post/post/post
in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (182)
in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (125)
in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (106)
in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (107)
in /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/post/models/Post.php (73)
```

**Comment by luke-** [comment]
Can you please post also the error message (not only the stacktrace) :-)

**Comment by CKGrafico** [comment]
curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set (/var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php:182) Stack trace: #0 /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php(83): loadUrl() #1 /var/www/vhosts/helpdev.org/httpdocs/social/protected/libs/HHtml.php(203): GetOEmbed() #2 unknown(0): {closure}() #3 /var/www/vhosts/helpdev.org/httpdocs/social/protected/libs/HHtml.php(211): preg_replace_callback() #4 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/comment/widgets/views/showComment.php(78): enrichText() #5 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(130): require() #6 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(95): ShowCommentWidget->renderInternal() #7 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/widgets/CWidget.php(244): ShowCommentWidget->renderFile() #8 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/comment/widgets/ShowCommentWidget.php(39): ShowCommentWidget->render() #9 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(173): ShowCommentWidget->run() #10 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/comment/widgets/views/comments.php(34): CommentsWidget->widget() #11 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(130): require() #12 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(95): CommentsWidget->renderInternal() #13 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/widgets/CWidget.php(244): CommentsWidget->renderFile() #14 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/comment/widgets/CommentsWidget.php(49): CommentsWidget->render() #15 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(167): CommentsWidget->run() #16 /var/www/vhosts/helpdev.org/httpdocs/social/protected/widgets/StackWidget.php(94): WallController->widget() #17 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(173): WallEntryAddonWidget->run() #18 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/wall/views/wallLayout.php(72): PostWidget->widget() #19 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(126): require() #20 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(95): PostWidget->renderInternal() #21 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/widgets/CContentDecorator.php(76): PostWidget->renderFile() #22 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate() #23 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput() #24 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(206): CContentDecorator->run() #25 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(300): PostWidget->endWidget() #26 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/post/widgets/views/post.php(23): PostWidget->endContent() #27 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(130): require() #28 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(95): PostWidget->renderInternal() #29 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/widgets/CWidget.php(244): PostWidget->renderFile() #30 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/post/widgets/PostWidget.php(38): PostWidget->render() #31 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CBaseController.php(167): PostWidget->run() #32 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/post/models/Post.php(113): WallController->widget() #33 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/wall/StreamAction.php(256): Post->getWallOut() #34 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/actions/CAction.php(76): StreamAction->run() #35 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(308): StreamAction->runWithParams() #36 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CFilterChain.php(133): WallController->runAction() #37 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #38 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #39 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CInlineFilter.php(58): WallController->filterAccessControl() #40 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #41 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #42 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(265): WallController->runActionWithFilters() #43 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CWebApplication.php(282): WallController->run() #44 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #45 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #46 /var/www/vhosts/helpdev.org/httpdocs/social/index.php(39): WebApplication->run() REQUEST_URI=/social/index.php?r=wall/wall/stream&type=Dashboard&guid=&limit=4&filters=&sort=c&CSRF_TOKEN=947dcee672bbb6fcabd5e3192f7600b29448e8bb&_=1427396807334 in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (182) in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (125) in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (83) in /var/www/vhosts/helpdev.org/httpdocs/social/protected/libs/HHtml.php (203) in /var/www/vhosts/helpdev.org/httpdocs/social/protected/libs/HHtml.php (211)

**Comment by CKGrafico** [comment]
and this other when you try to post something with oembed links
```
curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set (/var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php:182) Stack trace: #0 /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php(106): loadUrl() #1 unknown(0): {closure}() #2 /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php(107): preg_replace_callback() #3 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/post/models/Post.php(73): preload() #4 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/db/ar/CActiveRecord.php(1071): Post->beforeSave() #5 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/db/ar/CActiveRecord.php(806): Post->insert() #6 /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/post/controllers/PostController.php(49): Post->save() #7 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/actions/CInlineAction.php(49): PostController->actionPost() #8 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #9 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CFilterChain.php(133): PostController->runAction() #10 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #11 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #12 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CInlineFilter.php(58): PostController->filterAccessControl() #13 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #14 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #15 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CController.php(265): PostController->runActionWithFilters() #16 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CWebApplication.php(282): PostController->run() #17 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #18 /var/www/vhosts/helpdev.org/httpdocs/social/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #19 /var/www/vhosts/helpdev.org/httpdocs/social/index.php(39): WebApplication->run() REQUEST_URI=/social/index.php?r=post/post/post in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (182) in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (125) in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (106) in /var/www/vhosts/helpdev.org/httpdocs/social/protected/models/UrlOembed.php (107) in /var/www/vhosts/helpdev.org/httpdocs/social/protected/modules_core/post/models/Post.php (73)
```

**Comment by WASasquatch** [comment]
You have openbase_dir set.

**Comment by CKGrafico** [comment]
Oh... yes ```open_basedir	/var/www/vhosts/helpdev.org/:/tmp/``` (in php.info)

**Comment by alfa5** [comment]
The line:
curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);

in the file:
protected/models/UrlOembed.php

Is really necesary? 

is not always possible disable the open_basedir in a shared hosting

**Comment by WASasquatch** [comment]
Of course. Most video oembed URLs forward to mask raw video.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/3c4fba7c30332cc978e8fd0172e34d860e3abe0c
