### ISSUE TITLE
Forum module

### ISSUE THREAD

**Issue by Lysande** [humhub/humhub#821]
Hi. Saw a previous issue that mentioned this but didn't get a reply regarding forums. 

Are you planning on adding a module for a more message board/forum?

I am looking for a platform that combines a social platform with a more traditional forum/message board, so such a module would be great. Thanks!

**Comment by WASasquatch** [comment]
Probably not. HumHub is essentially a forum on steroids as is.

**Comment by Lysande** [comment]
I disagree, unless I'm missing something. HumHub, like facebook, seems like a terrific social platform with groups and messaging and whatnot, but this does not replace a forum when it comes to structured discussion. 

The closest approximation I've found is spaces with posts and comments, but this does not give the structure that a forum does. A forum, in my eyes, needs the ability to categorize subsections, to have paginated pages with posts and the ability to link and reference individual posts. Spaces-posts and comments are presented more in a flow than in a structured pagination.

This does not lend itself well to discussion, as Facebook has been detrimental to internet-based discussion ever since it made its appearance. That said, I'd obviously respect the decision to not make a forum module, but I cannot agree that Groups, posts and comments are, in essence, forums.

**Comment by WASasquatch** [comment]
Spaces are your "categories" posts are threads, comments replies. Its a forum for the new age and why forums aren't as popular in todays world. 

You can get the link of any post, references will likely be added. Searching posts is already in works. You can easily add BBCode. I have a modification on HumHub community. It is not safe for latest version/patches so should be used as reference to create your own modification.

I don't see HumHub team really making a forum module. If they did it'd likely be a one-category (the name of the page) sort of forum with pagination. 

This is a framework intended for you to develop your own social network and in turn modules to run on it. Someone may be interested in writing one but they are generally extensive and require loads of security testing, time and testing better spent on the development of HumHub and its future releases to a 1.x.x final so they cam enjoy a long and well deserved vacation for a year or so haha

**Comment by Lysande** [comment]
Still, I disagree. The layout and categorization of spaces is not comparable to that of a forum, at least not in my eyes. Also, are spaces nestable? If they are, that's a slight approximation, even though posts+comments aren't the same as posts in a forum. I am aware that humhub is a framework and that development takes time. That's why I asked if something was planned or in the works. If it is not, I'll develop it myself, but if it is I won't have to. I'd also argue that forum-based discussion is far from dead, given that stackexchange and reddit exists. But this is moving way out of the original question "A forum would be nice, do you have anything planned? Y/n"

----- Ursprungligt meddelande -----
Från: "Jordan Thompson" <notifications@github.com>
Skickat: ‎2015-‎03-‎18 01:45
Till: "humhub/humhub" <humhub@noreply.github.com>
Kopia: "Lysande" <johnsen.emil@gmail.com>
Ämne: Re: [humhub] Forum module (#821)

Spaces are your "categories" posts are threads, comments replies. Its a forum for the new age and why forums aren't as popular in todays world. 
You can get the link of any post, references will likely be added. Searching posts is already in works. You can easily add BBCode. I have a modification on HumHub community. It is not safe for latest version/patches so should be used as reference to create your own modification.
I don't see HumHub team really making a forum module. If they did it'd likely be a one-category (the name of the page) sort of forum with pagination. 
This is a framework intended for you to develop your own social network and in turn modules to run on it. Someone may be interested in writing one but they are generally extensive and require loads of security testing, time and testing better spent on the development of HumHub and its future releases to a 1.x.x final so they cam enjoy a long and well deserved vacation for a year or so haha

**Comment by WASasquatch** [comment]
Of course there are standards in forums.  They also for the main ones
(stackexchange) pay thousands in marketing campaigns and investment
opportunities, and have never budged from their indexing on Google, however
stack exchange is not a forum. In fact it works very linear and, like
HumHub sections/posts (spaces) are found under keywords (tags).In fact to
get to different "main" categories you have to use a website chooser much
like the space chooses. Posts are all in one section, divided by filters
for unanswered, bounties, protected, and again tags.

There may be one in the works, or someone else that will no doubt make one
at some point. I just think it will be a focus any time soon from HumHub.
You can use my Custom Pages Extended which has PHP support and  integrated
any message board. Working out a single login, not sure. Would have to
tinker with their APIs to use info collected via the $user var passed to
php pages.

**Comment by secondtruth** [comment]
I totally agree with @Lysande.

**Comment by AlDemion** [comment]
+1 It would be great to have forum module.

**Comment by anonnymouse** [comment]
A forum module would be amazing

**Comment by WebCrew** [comment]
I dont need a forum with HumHub cause HumHub is more as enough to handle discussions.by categories, but thats my opinion. If You mates want to have a forum with HumHub then check out https://codoforum.com/ You can make a single sign on easily with HumHub and Codoforum :) Good luck mates!

**Comment by devcline** [comment]
vote for a simple subject discussion forum! would be great!

**Comment by Michael-AMA** [comment]
I also agree that a message board/forum spaces module would be very useful.  I am currently looking at using HumHub at the company I work for.  The way I plan to set it up is with each department having their own space and employees from the different departments can decide if they want to follow a different space or not.

The hierarchy of a message board could help with keeping the different departments content better organized then the wiki, notes, streams or any other options I've looked into so far.  For example with the Support department I want to set up a hierarchy like so:

Support Forum
--General Threads
----Support News
------Awards & Promotions
------Scheduled Maintenance 
------Global Support Cases
--Newsletters
----Product Updates / Release Dates
----Support In the Media
--Job Openings
----Biz Apps
----Voice Services
----Hosted Exchange/Email Services
    
Using something like codoforum.com and SSO is not going to work as this site needs to be for internal use only and closed off to the external world.  I may look into what it would take to develop something but will have to outweigh the value to effort ratio.

**Comment by sense-design** [comment]
+1 for a forum module

**Comment by ZikWall** [comment]
You can integrate a [bizley/podium](https://github.com/bizley/yii2-podium) into your project, it will inherit the authorization of humhub or it can be a separate application

**Comment by ITwrx** [comment]
I see that Spaces Types(categories) is an Enterprise Edition feature. This may explain why Wiki and Spaces and/or it's Stream don't have the option for heirarchical structure/organization and permissions. The free/non enterprise tier seems to be flat/single level only(except comments). While proper funding for the project is preferable, it would be nice for non enterprise users if Humhub's freemium business model kept only truly "enterprisey" features in the Enterprise Edition instead of just "overly useful" features like categories. 
Thanks

**Comment by buddh4** [comment]
There will be a topic feature to categorize content in v1.3 I think this will be very useful for filtering data etc. The topic feature also can be integrated in modules like wiki, calendar, tasks, etc.. Since v1.2.2 there is even a new concept for creating own tagging mechanisms which is currently used for calendar types and will be the base of the topic concept.

Instead of a Forum like view, Modules like the Wiki should rather provide global views with a folder like structure and filters like topic and a full text search.

**Comment by devcline** [comment]
The main reason i wish to see a forum module or similar is that i want to separate a big Talks/Questions and a main content of the space News/Multimedia (the content to show) , for now i have ONE merged space and its mess of Questions/Discussions and a Content/News in the feed. The wiki for me is more for big articles and documentations. 

The talk space Its like a 'GROUP' space where ALL people post whatever they want with or without moderation and a 'CONTENT' space where only admins can posts things. How to separate those ? The only one solution for me is to create 1 same space for talks and another space for content So thats why the forums is good, for a HEAVY discussions (with images, votes, videos) that never will be gone to the bottom of the feed. Anyway the forum module is still ccan be disabled or enabled.

**Comment by warshell** [comment]
any good news on the evolution of the 2015 topic, some "simple" forum engine will be great !

**Comment by buddh4** [comment]
I think ideally post should have an optional title. Then we could just implement a forum like view of posts in combination with https://github.com/humhub/humhub/issues/3442

**Comment by ArchBlood** [comment]
If anyone is still subscribed to this issue, could I please get some general details on functionalities one is looking for when it comes to a discussions board/forum? Would help me a little better when it comes to this topic :thinking:

**Comment by ArchBlood** [comment]
@luke- I believe this can now be closed once the Humhub staff are able to discuss about the forums module that I have built.

**Comment by ArchBlood** [comment]
This can now be closed, I've completed the development of the module @luke-.
