### ISSUE TITLE
Posts going "bad" and breaking feed

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#825]
<img src="http://img.prntscr.com/img?url=http://i.imgur.com/BikEsPl.png" />

letting it run I eventually got this stack trace: http://herbsy.cf/exception.htm

Deleted old info. 

I can narrow down the bug to a post in a specific space. The issue is. There are no tools to go about removing specific posts and or purging posts from a specific section. So... the only option I have is to purge ALL posts from the system.

We definitely need a system for validating posts, and also purging space/profile posts! This will not do for even beta testing if all info has to be dropped.

**Comment by luke-** [comment]
Try run 'yiic integritychecker'

**Comment by luke-** [comment]
*Backup DB before :-)

**Comment by WASasquatch** [comment]
I found the problem. Somehow a comment had a mention field in it `@-GUID` where guid was the guid of a user. Somehow it got saved to DB and was causing the feed to break.

**Comment by luke-** [comment]
hmm, @-USERGUID should be ok, can you reproduce it?

**Comment by WASasquatch** [comment]
Yeah, feed is still broke from another comment he used mentioning in, but trying to find it in DB is the issue considering i'm limited to a small portion of the message before viewing the full field. So i am going through some 500 comments one by one...

**Comment by luke-** [comment]
Try yiic at /home/****/***/herbsy.cf/public_html/protected

**Comment by WASasquatch** [comment]
Thanks will give it a go
