### ISSUE TITLE
Notification status not updated right after like

### ISSUE THREAD

**Issue by jaragunde** [humhub/humhub#826]
Steps to reproduce:
1. Like some post from other user.
2. At this moment you will get automatically subscribed to the notifications on that post.
3. Try to turn off notifications right now: go to the top-right menu in the post.
4. It will say "Turn on notifications", like if they were not turned on.
5. Reload the page, and the menu entry will change to "Turn off notifications".

**Comment by githubjeka** [comment]
outdated

**Comment by jaragunde** [comment]
Thanks!
