### ISSUE TITLE
Abililty to Bulk Invite User-Base to new Spaces

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#829]
Because of the limit on the default spaces there is a lack of new space exposure (one of the reasons I created the Random Space widget), there should be a ability to invite all members, or a specific group to spaces via the administration panel.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/3f7fd4a71b115239651a797356ad349d7dbe1c83
or use
yiic space assignAllMembers spaceGuid
