### ISSUE TITLE
Unable Paste to Post Form in Mobile

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#830]
I am unable to paste to mobile post form under mobile with Chrome browser on my HTC Evo 4G. I am able to tap the button to paste just fine, but nothing is pasted, and the keyboard is disabled when tapping paste causing you to need to re-focus on the input to bring up the keyboard again.

**Comment by Basster** [comment]
Can confirm this behaviour. I'm also not able to paste Text to the post form with a mobile Chrome on Android 4.4.4 and 5.

**Comment by WASasquatch** [comment]
It seems the default input behavior on the form is disabled. it only brings
up option to paste, no select all/copy/cut options. Maybe being a editable
div? May need extra jQuery parameters ti behave like a normal textarea?

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/1057
