### ISSUE TITLE
Feature Request: Different max picture sizes

### ISSUE THREAD

**Issue by DemonWareXT** [humhub/humhub#832]
So I noticed a bit of an awkward problem.
I set the max width of photos to 600 because most people use bigger screens nowadays to browse.
When I noticed an issue, or feature?
Phones take 600 as max too, so suddenly pictures go over content

Width max 600:
![image](https://cloud.githubusercontent.com/assets/3695159/6764387/c8ef1646-cfad-11e4-9a97-3e2d39df5da4.png)

Width max 300:
![image](https://cloud.githubusercontent.com/assets/3695159/6764388/d5b4bc3c-cfad-11e4-9802-82b7ca8c8e23.png)

Is there a way around this that I am unaware of?
Otherwise I think this could be an awesome feature to implement
(oh and thumbnails of gifs don't work)

Cheers!

Linus

**Comment by WASasquatch** [comment]
Add css for mobile ;) This is why its at 300. Though a dynamic width would
seem to be the best answer like my opengraph reader uses.

```css
@media (max-width: 767px) {
  /* css class for images in mobile */

}
```

**Comment by DemonWareXT** [comment]
yes exactly, dynamic width would be best, but I could live with an option of two different sizes
but agreed @WASasquatch dynamic is best, at least up to a certain degree, I'd still like to set a max width, because of the thumbnail size

**Comment by WASasquatch** [comment]
Use that code to set the CSS back to 300px for mobile ;)

**Comment by DemonWareXT** [comment]
aright I will, do you know which file there is to edit?

**Comment by WASasquatch** [comment]
I'd add it to your `theme.css` Right click the image to get the unique css selector, then just remove the child delegations to get a generic selector for all post images.

**Comment by DemonWareXT** [comment]
hah that works like a charm!
thanks whole bunches @WASasquatch
