### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#833]
![1](https://cloud.githubusercontent.com/assets/7725575/6764905/37af9eee-cfd0-11e4-84f0-95fe8c927b31.PNG)

![2](https://cloud.githubusercontent.com/assets/7725575/6764924/a77d1de6-cfd0-11e4-9055-f0afb4e69b8f.PNG)

![3](https://cloud.githubusercontent.com/assets/7725575/6764929/b8b9fb88-cfd0-11e4-905d-7eafbd160287.PNG)

**Comment by mrluisiko99** [comment]
+1

**Comment by WASasquatch** [comment]
Facebook UX is copyrighted. You can't make pure likeness.

**Comment by WASasquatch** [comment]
Facebook UX is copyrighted. You can't make pure likeness. Definitely need a better, and dynamic image template but it shouldn't look like Facebook's. 

You can hide image names in the files section.

You can make images dynamic by making a copy of the file view `/protected/modules_core/file/widgets/views/showFile.php` and changing the thumbnail resolution to a absolute clear size. Mine is 800x1024. 

```php
                <a data-toggle="lightbox" data-gallery="<?php if (count($files) > 1) { echo "gallery-". $this->object->getUniqueId(); } ?>" href="<?php echo $file->getUrl(); ?>#.jpeg"  data-footer='<button type="button" class="btn btn-primary" data-dismiss="modal"><?php echo Yii::t('FileModule.widgets_views_showFiles', 'Close'); ?></button>'>
                    <img src='<?php echo $file->getPreviewImageUrl(800,1024); ?>'>
                </a>
```

And then add a CSS rule to govern mobile and desktop dimensions in your `theme.css`

```css
.post-files {
  text-align: center;
}
.post-files img {
  max-width: 100%;
}
@media (max-width: 767px) {
  .post-files img {
    max-width: 300px;
  }
}
```

With a result of

<img src="http://img.prntscr.com/img?url=http://i.imgur.com/7Kxl3d5.jpg" />

<img src="http://s22.postimg.org/vky7fl0dt/Screenshot_2015_03_21_21_04_30.png" />

**Comment by JeXawoW** [comment]
@WASasquatch  Thanks
