### ISSUE TITLE
How to change language files?

### ISSUE THREAD

**Issue by Betacarotin** [humhub/humhub#844]
is there a easy way to make proper translations for everything? Even the Custom Pages? 
I am not shure how to make that an cant find anything via search. 

If I choose swedish ist only half translated.

**Comment by dakur** [comment]
Sign up on this HumHub translation tool: http://translate.humhub.org/

**Comment by WASasquatch** [comment]
Custom Pages would require adding a output buffer to the main.php and use
preg_replace

**Comment by WASasquatch** [comment]
Custom Pages would require adding a output buffer to the protected/views/layout/main.php and use preg_replace

You can then replace any occuring text. Best too add unique bits of HTML from source to translate unique stuff but for generic something like

`preg_replace('/'.preg_quote ('<strong>space</strong>').'/i', '<strong>Page</strong>

Would work
