### ISSUE TITLE
user login less than 4 letters

### ISSUE THREAD

**Issue by mamasw** [humhub/humhub#845]
Hello.

I have just installed humhub. Is it possible to change user login length requirement to be less than 4 letters?  

Cheers.

**Comment by WASasquatch** [comment]
Yes its just a form check. I'm on my phone but check out
protected/modules_core/user/auth

**Comment by mamasw** [comment]
I have found something in /protected/modules_core/user/models/User.php. Can you please check is this a only one file where this value is checked?

**Comment by WASasquatch** [comment]
Yes, that is is. 

`        $rules[] = array('username', 'length', 'max' => 25, 'min' => 4);`
to
`        $rules[] = array('username', 'length', 'max' => 25, 'min' => 3);`

**Comment by mamasw** [comment]
thank you for helping me :) Its working.

**Comment by WASasquatch** [comment]
Glad I could help. Maybe this should be a setting under authentication settings of the admin center @luke- ?
