### ISSUE TITLE
Add Online Indicator 

### ISSUE THREAD

**Issue by dimontajik** [humhub/humhub#851]
Please add the online icon in the system, and to find and elsewhere has shown Online

**Comment by WASasquatch** [comment]
You could add this to your theme by checking profile guid against sessions I believe.

**Comment by dimontajik** [comment]
Give an example of code

**Comment by JeXawoW** [comment]
+1

**Comment by Stranikevg** [comment]
+1

**Comment by viva-chegevara** [comment]
+1
need show who online, please ˆ_ˆ

**Comment by WASasquatch** [comment]
https://github.com/WASasquatch/humhub-modules-custom-pages-extended/blob/master/docs/example-hstats.md

You can find example code there to add this to your theme yourself.

**Comment by 001101** [comment]
https://github.com/001101/humhub-module-onlineusers

**Comment by orangiene** [comment]
![community_online-icon-people](https://user-images.githubusercontent.com/62644500/148966699-ea21ac21-b611-4843-b237-7c181eb9e887.jpg)
![enterprise_online-icon-people](https://user-images.githubusercontent.com/62644500/148966711-c0ee46cc-4237-41ab-9101-630f9416ac91.jpg)
![community_online-icon-messages](https://user-images.githubusercontent.com/62644500/148966751-3c10a154-1ac5-47b4-9ab1-ffa7144b0241.jpg)
![community_online-icon-02](https://user-images.githubusercontent.com/62644500/148966766-95d634d7-0a0f-468e-8060-0864574a5d5c.jpg)

Hello,

here are a few suggestions on which pages I would show the status of users:
- People page
- Conversations
- Space overview (under Space Members)

For the People page, I think it would be good to have the online icon next to the picture, including the text "online" or "offline".

What do you think?

**Comment by luke-** [comment]
@orangiene Looks good, thanks!

What do you think about only showing a green dot in the online case and not extra flagging the offline case?

Directory/People: I would leave out the word "online/offline". 

Mail: Here we could maybe show the online status only at the top of the participant list and omit it in the Mail Conversation dialog.

**Comment by orangiene** [comment]
thank you.
I prefer the version with "online" and "offline" but I can also live with it if the text is not included and you don't like it. :-)

For Mail I agree with you. I updated the screen:

![community_online-icon-messages](https://user-images.githubusercontent.com/62644500/149127272-7002ee51-a08b-40c9-a6b1-724d11bb6002.jpg)

**Comment by luke-** [comment]
@orangiene What do you think about showing only the online status?

**Comment by orangiene** [comment]
@luke- that's fine for me. What do you think about a status like in webex "absent", "on vacation" or is this too complex?
of course, it should then also be possible to set your own status, possibly with your own text, an out of office note.

**Comment by luke-** [comment]
@orangiene Sounds not bad, but I would then open a separate issue for it and we would also have to consider in detail how it should work. (Set status, etc.).

**Comment by orangiene** [comment]
ok, I will do that. @luke-

**Comment by luke-** [comment]
@orangiene Yes, lets begin with the online icon only.

- Only a green dot without online at People like here: https://user-images.githubusercontent.com/62644500/148966699-ea21ac21-b611-4843-b237-7c181eb9e887.jpg
- Never show the offline status (no red marker)

Can you please adapt the screens? Then we can start with the implementation...

**Comment by orangiene** [comment]
here you go:

![community_online-icon-people](https://user-images.githubusercontent.com/62644500/149184147-75ee836e-f556-443c-b020-e1c3aa8daeab.jpg)

**Comment by 001101** [comment]
who is @orangiene ?

**Comment by Ansari619** [comment]
How to add this function i need it....for my humhub site i want to add online offline ....how to add please help me

**Comment by WASasquatch** [comment]
How is this basic modern indicator still not part of base software? 

There are several examples above on how to this.

**Comment by luke-** [comment]
Upcoming v.15 will have some indicator:
https://github.com/humhub/humhub/pull/6297
