### ISSUE TITLE
Suggestion: Show user profile for guest users

### ISSUE THREAD

**Issue by avasima** [humhub/humhub#854]
=
Show user profile for guest and user can change profile to Public and private
=
profile is public : Show user profile for guest and any user
( but only user can be send comment and follow and liked post)

profile is private : Show user profile for only Followers Users

**Comment by mrluisiko99** [comment]
I think it will be in 0.11 update :)

**Comment by luke-** [comment]
Yes, optional public space/profile access will be available in upcoming 0.11

**Comment by avasima** [comment]
thanks for update  0.11
but user can send   private and public post only =space=
profile user only send public post
So Suggestion : user can send private and public post in user profile 
kind regards
