### ISSUE TITLE
[suggestion/issue] E-mail Verification

### ISSUE THREAD

**Issue by bigzooooz** [humhub/humhub#858]
I'm trying to disable the Email verification feature and I can't see anything in the panel does that
even if I activated the user approval feature, the registerants still need to verify their email
is there anyway i can do that?
what I'm looking for is a decentralized social-networking website. Having users verifying their email addresses is quite the opposite.
so in few words, what I'm looking for is
1- Email Verificatin = Disabled
2- User Approval = Enabled
and having capacha in the registration page wouldn't hurt ..
can that happen? I mean like using a module or replacing a code
or do I need to wait for the next update that you might add these features?

**Comment by aerth** [comment]
Here is registration captcha: https://github.com/aerth/humhub/commit/9b4f36e98e96316d6a72482d66a581750a219bba

**Comment by bigzooooz** [comment]
thank you @aerth !!
but the problem here that I could actually bypass it
by just loggin the username + password and ignore the captcha and it logged me right away ~
can this get fixed?
-
the other thing is the registration problem. since I run Humhub on a tor hidden service, I cannot send emails through it and therefor email verification can be a problem.
even invitations wouldn't work! 
if you have a solution for this one too I would really appreciate that.

**Comment by bigzooooz** [comment]
Fixed the verification problem by using a remote SMTP server that using hidden service .. mail2tor.com
and it works great ..

**Comment by camgaertner** [comment]
Is there still no way around this other than using a remote SMTP server?

**Comment by luke-** [comment]
@camgaertner HumHub uses SwiftMailer - you can use all supported transports.
But you'll configure them manually in the configuration file.

**Comment by camgaertner** [comment]
@luke thanks!

**Comment by mitya12342** [comment]
@aerth Your link is 404  :-(
I am trying to setup humhub to run in autonomous environment without internet connection
Email verification is my main problem right now
Are there any ways to disable it? Like it is implemented in phpbb
