### ISSUE TITLE
Revert to Old Cover Image

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#859]
The new cover image is incredibly warped, way more then the old cover image for profiles. It also only allows a slight portion of the uploaded image to be displayed due to new size restrictions, which is not very practical. It should resize to the section cropped, and use `overflow` to hide anything else. 

Users are simply removing their cover images.

**Comment by jahd2602** [comment]
I can confirm this. Please add a setting to change the size of all the cover images (or the new added images) and also please make them clickable to open them in a dialog, just like the profile picture.
