### ISSUE TITLE
New Installation - ActivityStreamWidget.type is not defined

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#861]
I get a 500 Internal Server error during the install of the database. Apache logs didn't seem to catch anything. After reloading, I was prompted to pick the site name, and my account into. After registering my account all I get is 

`Property "Profile.url_xing" is not defined. `

http://herbsy.cf/CException.htm

**Comment by luke-** [comment]
Hmm, seems the CException is thrown because the install db wasn't correctly set up.

There must be some entry in Apache/PHP Logs

**Comment by WASasquatch** [comment]
Since I flushed before starting new install I just have errors regarding
active old install of 0.10.1. Ill have a look again. Somehow php sessions
aren't working right for phpmyadmin so I can't login and exploring is slow
on MySQL console. Seems PHP update broke some things.

**Comment by WASasquatch** [comment]
Was able to get it to install over the database, however after restoring files I get `Property "ActivityStreamWidget.type" is not defined. ` I'm assuming it's my theme, however the stack trace doesn't pin-point any theme files that I can see. I also ran the update tool which said, again, there were no updates even though there was mass changes...

```txt


                     HumHub Console Interface - Version 1

--------------------------------------------------------------------------------
Updater
--------------------------------------------------------------------------------


*** Begin Migrations ***

Flushing Caches....
Autodetecting Modules....

Yii Migration Tool v1.0 (based on Yii v1.1.15)

extended with EMigrateCommand by cebe <mail@cebe.cc>

Active database component (connectionString):
    mysql:host=localhost;dbname=jordan_herbsy


No new migration found. Your system is up-to-date.

--------------------------------------------------------------------------------

*** Checking Modules ***





--------------------------------------------------------------------------------
Finished succesfully without errors!
--------------------------------------------------------------------------------
```txt


Updated error at http://herbsy.cf/CException.htm

**Comment by WASasquatch** [comment]
Disabling the theme via MySQL to HumHub didn't help so not sure why its
erroring. From DB?

**Comment by luke-** [comment]
the current is also stored in protected/config/local/_settings.php

**Comment by WASasquatch** [comment]
Thanks that got it back on the original theme. 

I would very much appreciate an exact change log of theme elements like with previous updates to help us update our themes without comparing every one of the hundreds of files for 'posssible' changes when I could be looking for the changes.

**Comment by luke-** [comment]
Fyi, you can create a list of changed views via git. 

git diff v0.10.1 v0.11.0 --stat | grep "views/"

**Comment by WASasquatch** [comment]
I would post that themes are not compatible between versions. As they are not. CSS has completely evolved, as well as the views.
