### ISSUE TITLE
Help in ImageMagick

### ISSUE THREAD

**Issue by andreluis3205** [humhub/humhub#862]
Hello , somebody could help me use imagemagick , I want when the User send a picture it is converted to 800x600 resolution .
In the Administration panel files have the imagemagick and it requests a command , I need someone tell me this conversion command .

**Comment by Vatarus** [comment]
I need too.

**Comment by WASasquatch** [comment]
Images are handled via the file module. You can change thumbnail size in `protected/modules_core/file/widgets/views/showFile.php` for example. I believe you'll find what you are looking for in one of the file module files.

**Comment by andreluis3205** [comment]
hello Sasquatch, I looked it but do not have an experience in Yii I not found.
What I need is that when the User make the photo upload the system converts the image to 800x600 and it is saved in this resolution on the server, because what is happening is that when the User sends a very big picture it is saved in server with the original properties and when users click on the image, it loads the screen with the original resolution and depending on the image it is very large and out of the monitor patterns, so I need to make this change.

**Comment by WASasquatch** [comment]
You can use CSS to simply apply a max-width and max-height so it functions
correctly in all browsers.

**Comment by andreluis3205** [comment]
please, could you show me where I find the css and what place I can make this change?

**Comment by mrluisiko99** [comment]
I think it is best convert the image because it will have less weight but there should also be a limit on CSS so that the image would not exceed the size of the monitor.

**Comment by WASasquatch** [comment]
"Weight" Or size of the file is controlled via the File settings and max
upload size.

**Comment by andreluis3205** [comment]
I think better image conversion at the time of upload, if you have this option as I set or where to implement the code

**Comment by WASasquatch** [comment]
Converting images is very heavy on servers, and would not "lighten" the load in the least, but create a heavy load. Especially if you have a active user base. This is why Facebook users an entirely separate server for Image Manipulation, and another for Video Manipulation. 

In any case, please see Image Magick Documentation: http://www.imagemagick.org/script/command-line-options.php
