### ISSUE TITLE
Error!!!!!

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#864]
exif_read_data(php8ki6q4) [<a href='function.exif-read-data'>function.exif-read-data</a>]: File not supported (/home/xxx/public_html/protected/modules_core/file/libs/ImageConverter.php:299) Stack trace: #0 /home/xxx/public_html/protected/libs/ProfileImage.php(180): TransformToJpeg() #1 /home/xxx/public_html/protected/modules_core/space/controllers/AdminController.php(282): ProfileImage->setNew() #2 /home/xxx/public_html/protected/vendors/yii/web/actions/CInlineAction.php(49): AdminController->actionImageUpload() #3 /home/xxx/public_html/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #4 /home/xxx/public_html/protected/vendors/yii/web/filters/CFilterChain.php(133): AdminController->runAction() #5 /home/xxx/public_html/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #6 /home/xxx/public_html/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #7 /home/xxx/public_html/protected/vendors/yii/web/filters/CInlineFilter.php(58): AdminController->filterAccessControl() #8 /home/xxx/public_html/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #9 /home/xxx/public_html/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #10 /home/xxx/public_html/protected/vendors/yii/web/CController.php(265): AdminController->runActionWithFilters() #11 /home/xxx/public_html/protected/vendors/yii/web/CWebApplication.php(282): AdminController->run() #12 /home/xxx/public_html/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #13 /home/xxx/public_html/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #14 /home/xxx/public_html/index.php(39): WebApplication->run() REQUEST_URI=/s/e2f97f69-5aab-4a69-a7a8-ef41a9cd189a/space/admin/imageUpload

**Comment by luke-** [comment]
Fixed here: https://github.com/humhub/humhub/commit/036c32c4b771124c2bee6c3355d4529bc35535da

**Comment by WASasquatch** [comment]
@luke-  can you edit the issue title to point the error in question for future reference? 

Just my OCD but I often refer to issues a lot and "Error!!!!" won't help with searches.
