### ISSUE TITLE
[0.11.0] activityLayout.php

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#868]
```txt
<b>Fatal error</b>:  Call to a member function getProfileImage() on a non-object in <b>/home/jordan/web/herbsy.cf/public_shtml/development/protected/modules_core/activity/views/activityLayout.php</b> on line <b>28</b><br />
```

`                     src="<?php echo $activity->content->space->getProfileImage()->getUrl(); ?>">
`

Not sure what this is from. Something a user posted in a space.

**Comment by luke-** [comment]
Hmm, do you use the default theme?

**Comment by WASasquatch** [comment]
Yes, it's default, only been working on CSS so far. 

I tried changing to: 

```php
                     src="<?php echo (isset($activity->content->space->getProfileImage()->getUrl())) ? $activity->content->space->getProfileImage()->getUrl() : 
										(file_exists(Yii::app()->theme->baseUrl . 'img/default_user.jpg')) ? Yii::app()->theme->baseUrl . 'img/default_user.jpg' : Yii::app()->baseUrl . 'img/default_user.jpg'; ?>">
```

But I get:

`Fatal error: Can't use method return value in write context in /home/jordan/web/herbsy.cf/public_shtml/development/protected/modules_core/activity/views/activityLayout.php on line 28`

Instead.

On the last version (which is still active) a user registered and has no required First or Last name and shows up as "joined the space xxxx" with no name or image in the feed. I think it may be related?

**Comment by xaro1** [comment]
Same error here.

**Comment by WASasquatch** [comment]
This is really a vital error which needs focus ASAP. 

This prevents using the software. 

It is clearly because YIIC will not run to optmize the database, so what can we manually do to fix it @luke- ?

**Comment by WASasquatch** [comment]
More testing and optimizing the DB I was able to rid the last error, and now get a 500 Server Error http://herbsy.cf/PHPerror.htm

**Comment by WASasquatch** [comment]
Trying to delete user that somehow registered with no First or Last name:

`http://herbsy.cf/development/admin/user/delete/id/41/doit/2`

http://herbsy.cf/CDbException.htm

**Comment by luke-** [comment]
https://github.com/humhub/humhub/commit/7de8f3a5bed2036e6e9f4534dfc67699d0f2dc0f
