### ISSUE TITLE
0.10.0 users registering with no name

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#873]
![screenshot_2015-03-31-15-57-52](https://cloud.githubusercontent.com/assets/1151589/6931169/f76d9b6e-d7be-11e4-87e1-834c7ba97157.png)

Not sure how users are suddenly getting by required fields... I can't.

**Comment by Manuwickrama** [comment]
Are you authorizing users through LDAP? If so, they probably still have an email account. Humhub needs only an email address to create an account.

**Comment by WASasquatch** [comment]
No LDAP. A account is not useable without verifying it via email and
filling out required First and Last name. These two users are writing post
and following people. And could be why 0.11.0 is erroring out trying to
render the activity feed for these empty results from the imported DB when
correlating spaces to users.
