### ISSUE TITLE
Cannot get installer to work

### ISSUE THREAD

**Issue by DFabri1986** [humhub/humhub#874]
Hi I have been trying to get an installation of Humhub to work, I have attempted to install on two different servers. One server is a shared server with JustHost and the other is my VPS with GoDaddy and it is an account under WHM.

I have tried following the installation instructions but it does not work for me. I just get a standard Cpanel error page.

I have uploaded the files, and given the folders the appropriate permissions and still doesn't work. PHP version is correct.

What am I doing wrong?

Thanks in advance

**Comment by WASasquatch** [comment]
Did you run those permissions recursively?

**Comment by DFabri1986** [comment]
No I did just the folders it mentions

**Comment by WASasquatch** [comment]
It needs to be recursive. All subfolders and files.

**Comment by DFabri1986** [comment]
Just tried it then, No difference

**Comment by DFabri1986** [comment]
Permission should be 755 correct? or have I got the wrong ones

**Comment by WASasquatch** [comment]
755 is default for folders. You need writable permissions for user and
group. 0777

**Comment by DFabri1986** [comment]
Still no difference.

**Comment by WASasquatch** [comment]
Can you provide us with the apache error? From my experience HumHub is
meant for dedicated servers, or servers with root/ssh access.

**Comment by DFabri1986** [comment]
For some reason the JustHost server started to work. So there must be some misconfiguration on my VPS server.

Thanks heaps anyways
