### ISSUE TITLE
Fails on rendering dashboard activity stream on 0.11.0

### ISSUE THREAD

**Issue by Basster** [humhub/humhub#875]
After update to 0.11.0 the activity stream on the dashboard fails to load when trying to render the first space image thumbnail.

This it what renders before existing with a 500:
```
<li class="activity-entry">
    <a href="#" onClick="activityShowItem(807);
                return false;">        <div class="media">
            <!-- Show user image -->
            <img class="media-object img-rounded pull-left" data-src="holder.js/32x32" alt="32x32"
                 style="width: 32px; height: 32px;"
                 src="http://<my-intrahub-url>/uploads/profile_image/ad059faf-77be-47ab-9d6f-8d25b4d00168.jpg?cacheId=0">

            <!-- Show space image, if you are outside from a space -->
                            <img class="media-object img-rounded img-space pull-left" data-src="holder.js/20x20" alt="20x20"
                     style="width: 20px; height: 20px;"
                     src="
```

The activity stream inside the spaces (without space thumbnail) works as intended.

I already ran 
```
yiic update
yiic integritychecker
yiic search_rebuild
yiic search_optimize
```

**Comment by WASasquatch** [comment]
Been trying to to figure this out for days. Habe not been able to use
0.11.0 because of this and like last update.. may need to drop all content
as I have not heard from staff.

**Comment by xaro1** [comment]
I am also in the same situation as you.

**Comment by luke-** [comment]
This should fixes the problem.

https://github.com/humhub/humhub/commit/7de8f3a5bed2036e6e9f4534dfc67699d0f2dc0f

**Comment by luke-** [comment]
Please provide an error message e.g. https://github.com/humhub/humhub/issues/878

Otherwise it's difficult to help...

**Comment by xaro1** [comment]
It works for me. Thanks.
