### ISSUE TITLE
Deasactivates the inscription

### ISSUE THREAD

**Issue by ychoucha** [humhub/humhub#882]
Hello,

how desactivated the inscription please ? 

![connexion - humhub - mozilla firefox](https://cloud.githubusercontent.com/assets/301074/6950314/56294c88-d8ba-11e4-94ba-193230e288a6.jpg)

i want remove the inscription button please

**Comment by WASasquatch** [comment]
You can try to comment out the code, but registrations cannot be disabled at this time I don't think.

**Comment by ychoucha** [comment]
HumHub looks really cool :)

but it's still an alphe, neeeeeed many many more things to use it in production :)

**Comment by luke-** [comment]
Disable "Administration -> Authentication -> Anonymous users can register"

**Comment by ychoucha** [comment]
ok works

![connexion - humhub- mozilla firefox](https://cloud.githubusercontent.com/assets/301074/6971327/1a7976fa-d97c-11e4-988a-52f783667e41.jpg)


thanks :)
