### ISSUE TITLE
[Solved] [Information] Installation fails at admin account creation

### ISSUE THREAD

**Issue by brainsht** [humhub/humhub#886]
[LAST EDIT: Okay I solved this Issue. I missed to install two PHP-Modules php56-iconv and php56-exif. As they are not included in the standard PHP-Installation, it is maybe a good idea to include them in the self test.]

The Installation fails, as soon as the data for the admin account gets sent (blank page appears).
If I enter the URL of the site again, the setup says that it's done but I can't login.
The database table "user_password" stays empty, but the admin user is created in "user" table.

[3rd EDIT: Here is the output of the nginx error log]
``` 
[error] 40011#0: *64 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function iconv() in /usr/local/www/humhub/protected/vendors/Zend/Search/Lucene/Analysis/Analyzer/Common/Utf8Num.php on line 77" while reading response header from upstream, client: 10.0.0.1, server: social.xy.com, request: "POST /index.php?r=installer/config/admin HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.socket:", host: "10.0.0.4", referrer: "https://social.xy.com/index.php?r=installer/config/admin"
```
[EDIT: But HumHub itself is unusable. Is there a way, how I can create users or a admin user myself?]

[2nd EDIT: My Setup is: FreeBSD 10.1-RELEASE-p6, nginx/1.6.2 ]

**Comment by luke-** [comment]
Added EXIF requirement here: https://github.com/humhub/humhub/commit/c6e5b95e95d3929292082a811d9a05d585b9a69c

Are you sure Iconv is required?

**Comment by WASasquatch** [comment]
Both EXIF and IconV are default in PHP. EXIF needs to be enabled on Windows.

http://php.net/manual/en/iconv.installation.php

http://php.net/manual/en/exif.installation.php

**Comment by brainsht** [comment]
@WASasquatch In UNIX systems like FreeBSD no PHP Module comes as "standard" or "default". You install every single module you need manually, which imho is a good way to keep a system clean. Have a look at the PHP Ports: ``` https://www.freebsd.org/cgi/ports.cgi?query=php56&stype=all ``` It's good to know that it's different on Linux Systems, though.

@luke- As you can see in my first post, iconv is required as a PHP Module. Otherwise nginx wouldn't log it as an error.  ``` PHP message: PHP Fatal error:  Call to undefined function iconv() ```

Please don't consider Linux Systems being the only OS people will install HumHub on.

**Comment by WASasquatch** [comment]
FreeBSD is not a standard in Unix, nor Linux, nor Server Environments. It's very much a "Alternative" Linux Distro. It has limited support for a lot of common Unix and Linux software and needs it's own special love.
