### ISSUE TITLE
/themes/Theme/views/notification/notification/notificationLayout.php will not override

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#887]
This theme will not override on 0.11.0 or am I doing something wrong? I need to run `HHtml::simpleMarkdown($content, false);` from my `HHtml.php` on the output, but it's not running.

**Comment by WASasquatch** [comment]
@luke- Any ideas? This is pretty important for my simple markdown feature. Even if I replace the view with "hello world" I don't even get a messed up page.

**Comment by luke-** [comment]
The correct path for is /themes/Theme/views/notification/notificationLayout.php 

https://github.com/humhub/humhub/blob/master/protected/docs/guide/theming/index.md#structure-of-theme-folders

There is no controllerId
