### ISSUE TITLE
Information : If you can't upload any image file after update to v0.11.0-1.

### ISSUE THREAD

**Issue by krai500** [humhub/humhub#890]
Because this line.
https://github.com/humhub/humhub/blob/master/protected/modules_core/file/libs/ImageConverter.php#L299

This function " $exif = @exif_read_data($filename);" need php "php_exif" extenstion ".

First time when I have problem I don't know how to fix.
Recommend : It would be better if humhub include "php_exif" requirement in selftest admin page .

**Comment by WASasquatch** [comment]
EXIF is part of default PHP environments. Only Windows enable extra DLLs for EXIF support. Thank you for the information.

http://php.net/manual/en/exif.installation.php
