### ISSUE TITLE
RSS Integration

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#893]
Hello,

my HumHub it's cool, but need some frech news on it for my group and me :)

so can i créate a group that can automaticly create post with rss ?

like the RSS of my favortie french blog Korben --> http://korben.info/feed

Thanks

**Comment by mrluisiko99** [comment]
+1

**Comment by JeXawoW** [comment]
+1

**Comment by kkayacan** [comment]
+1

**Comment by WASasquatch** [comment]
The only issue is the way the system is setup. Currently a post needs to be represented by several factors, including a user account.

A module could be created to theoretically create a dummy account `RSSUser` and then post to a Space GUID as that user based on a RSS feed and the latest entries on the list.

**Comment by luke-** [comment]
I'll try to remove the required user account for content in one of the next releases. Maybe 0.12

**Comment by ychoucha** [comment]
Hello how do that ?

**Comment by Ace2213** [comment]
+1

**Comment by petrk94** [comment]
+1

**Comment by Profi420** [comment]
+1 (because it would be so great!)

**Comment by petrk94** [comment]
+1

**Comment by samuk** [comment]
+1

**Comment by samuk** [comment]
I just spotted this project: https://github.com/StevenJoynt/HumHub-RSS-Reader

**Comment by wforte88** [comment]
+1

**Comment by ernie-sys** [comment]
+1

**Comment by samuk** [comment]
This is working for me now: https://github.com/StevenJoynt/HumHub-RSS-Reader

**Comment by ArchBlood** [comment]
> This is working for me now: https://github.com/StevenJoynt/HumHub-RSS-Reader

Remember to also read the following from the README.md

> Important: This is a work in progress. Do not install it on a live web site!

**Comment by Vjnm** [comment]
I'm having these errors. Any help is welcome., Thank you.
Vin


Could not execute queued job! Message: Call to undefined function sij\humhub\modules\rss\jobs\simplexml_load_file() Trace:#0 /var/www/humhub/protected/humhub/modules/rss/jobs/GetFeedUpdates.php(408): sij\humhub\modules\rss\jobs\GetFeedUpdates->parseNewsFeed()
#1 /var/www/humhub/protected/humhub/modules/rss/jobs/GetFeedUpdates.php(449): sij\humhub\modules\rss\jobs\GetFeedUpdates->downloadNewsFeed()
#2 /var/www/humhub/protected/humhub/modules/queue/ActiveJob.php(33): sij\humhub\modules\rss\jobs\GetFeedUpdates->run()
#3 /var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(246): humhub\modules\queue\ActiveJob->execute()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute()
#6 [internal function]: yii\queue\cli\Command->actionExec()
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#12 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction()
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#14 /var/www/humhub/protected/yii(29): yii\base\Application->run()
#15 {main}

**Comment by Vjnm** [comment]
Errors solved. Installed php xml extension and replaced php8 with php 7.4

**Comment by funkycram** [comment]
You also have this paid module in the Marketplace: https://marketplace.humhub.com/module/web-feed
