### ISSUE TITLE
[Suggestion] Spaces/Profiles: Post Policy

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#894]
Setting for whether posts are public or private by default. 

This will be helpful for a space which is intended to be public and users posting private posts. Such as a Help & Answers space. Or for users which don't always want to pin a post public (this should be a cookie/db setting like Facebook for profiles)

**Comment by pagliaso** [comment]
Besides this, it would be great if a post could be edited after have been sent, and make it public or not, if you changed your mind after creating it.

Currently, when you edit it, you don't have the option to make it public or not, just when you are creating it.

**Comment by WASasquatch** [comment]
Yeah, I've made a issue on that.
