### ISSUE TITLE
cant upload photos also am getting warnings 

### ISSUE THREAD

**Issue by snitch567** [humhub/humhub#896]
please help me fix these thanks :)

![screen shot 2015-04-03 at 12 14 18](https://cloud.githubusercontent.com/assets/3769596/6981535/01484556-d9fb-11e4-9547-23b0be4e1f04.png)
![screen shot 2015-04-03 at 12 13 52](https://cloud.githubusercontent.com/assets/3769596/6981538/06149aee-d9fb-11e4-8649-a866aff4e9e5.png)

**Comment by WASasquatch** [comment]
Fix your required settings. Writable modules folder, etc.

**Comment by brainsht** [comment]
@snitch567 +1 I also can't upload any images but I don't get any warnings at all.

@WASasquatch All settings done correctly, but I still can't upload any images. APC is not needed for this, though. It's optional - [requirements](https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/requirements.md)

![modules](https://cloud.githubusercontent.com/assets/11761596/6994638/3f6b7160-db21-11e4-9f52-d20437478029.jpg)

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/890

We've added php exif to the requirements...

**Comment by snitch567** [comment]
am still getting the warnings how do i fix them ?

**Comment by brainsht** [comment]
@snitch567 Did you manage to solve your problem? If so, how?
