### ISSUE TITLE
Update: Mail Settings Lost

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#897]
My mail settings from my 0.10.1 version didn't seem to be read by 0.11.0-1 and defaulted back to PHP default. When I put back in the settings manually, I am no long able to login to Gmail SMPT. I've tried all combinations of SSL/TLS. Yess less secure apps is enabled, and Captcha Disabled for the Login Attempts. 

Also, is the swift client using `gethostbyname()` to prevent servers like mine with IPv6 domains from having issues connecting to IPv4 domains? IPv6 takes precedence over IPv4 because it's "newer" even though seldom used yet.

**Comment by WASasquatch** [comment]
You may not be able to reproduce because of no IPv6. For example. I have 5 IPv4 allocations, that are ***secondary*** and then I have 150 main IPv6 allocations. So when I try to connect to `smpt.gmail.com` it usually times out attempting to try and connect to IPv6 at `smpt.gmail.com` instead of IPv4 which can be forced by using `gethostbyname('smpt.gmail.com')` or w/e host. And again for the source IP with something like: 

```php

As for login information disappearing I do not know.

**Comment by WASasquatch** [comment]
Here is the error, @luke-  http://herbsy.cf/Swift_TransportException.htm

<img src="http://img.prntscr.com/img?url=http://i.imgur.com/xPmiAL9.png" />

**Comment by luke-** [comment]
![image](https://cloud.githubusercontent.com/assets/4736168/7252059/92d94f62-e831-11e4-9f29-4a515248fa69.png)

**Comment by WASasquatch** [comment]
Was this issue fixed? I still can't login into gmail off my server on
0.11.x anymore.

On Tue, Apr 21, 2015 at 5:20 AM, Lucas Bartholemy <notifications@github.com>
wrote:

> Closed #897 <https://github.com/humhub/humhub/issues/897>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/897#event-286149034>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*

**Comment by luke-** [comment]
There was/is no issue. Check your hostname -> should be smtp.gmail.com

I've tested TLS & SSL modes.

**Comment by WASasquatch** [comment]
........ curse my dyslexia.
