### ISSUE TITLE
yiic space assignAllMembers

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#898]
When you run this command, the users in question will not see those spaces in their "My Spaces" dropdown, the only way to get to it is by searching. They are a member. When found they can post and participate as normal but it still doesn't show up in their "My Spaces"

For example, make a few test accounts and run this script

```bash
#!/bin/bash

# Additional Primary Spaces
SPACE[0]='{GUID_1}'
SPACE[1]='{GUID_2}'

# Spaces Count
COUNT=${#SPACE[@]}

# Run YIIC Commands
for (( i=0;i<$COUNT;i++)); do
    echo `./yiic space assignAllMembers ${SPACE[${i}]}` # &> /dev/null <-- Uncomment to hide output for Cronjob
done 
```
And then sign in as one of those members.

**Comment by luke-** [comment]
Which cache type do you use? When using e.g. APC you need to flush it - we can't do this via command line...

**Comment by WASasquatch** [comment]
APC Flushing didn't work until I flushed multiple times. There probably should be a level of Cache Flushing in the YIIC console for a production server like most frameworks. I shouldn't be required to be around to manage the cache. I'd make a PHP to CMD script to do so.
