### ISSUE TITLE
Users upload animated .gif (turns into plain jpeg with link to download)

### ISSUE THREAD

**Issue by aerth** [humhub/humhub#899]
To reproduce:
Upload example.gif in stream. 
See smaller static .jpeg thumbnail with link to .gif
here is what the urls look like (not for clicking)
gif link url: http://example.com/file/file/download/guid/1718f198-4b6f-494c-b43c-bda40bd3727b
jpeg thumb url: http://example.com/file/file/download/guid/1718f198-4b6f-494c-b43c-bda40bd3727b/suffix/pi_200x200
when click jpeg thumb links to: http://example.com/file/file/download/guid/1718f198-4b6f-494c-b43c-bda40bd3727b#.jpeg

Would like to see: animated gif. Or link to a page with the animated gif, if the jpeg thumbnail is a must.
Thanks!

**Comment by WASasquatch** [comment]
This isn't a bug. HumHub converts images to JPEG format.

**Comment by aerth** [comment]
But when clicking the JPEG, it sends me the .gif to download, what about an image preview popup or page?

**Comment by aerth** [comment]
What files to edit, if one would want to proceed anyways.

**Comment by WASasquatch** [comment]
Probably `/protected/modules_core/file/widgets/views/showFiles.php` and change the lightbox to point to the raw file?

**Comment by aerth** [comment]
Thanks!
