### ISSUE TITLE
open_basedir .. Error

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#901]
is_readable() [<a href='function.is-readable'>function.is-readable</a>]: open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/home/xxx:/usr/lib/php:/usr/php4/lib/php:/usr/local/lib/php:/usr/local/php4/lib/php:/tmp) (/home/xxx/public_html/protected/vendors/Codeigniter/CI_Security.php:574) Stack trace: #0 /home/xxx/public_html/protected/vendors/Codeigniter/CI_Security.php(921): Security->xss_hash() #1 unknown(0): Security->_decode_entity() #2 /home/xxx/public_html/protected/vendors/Codeigniter/CI_Security.php(377): preg_replace_callback() #3 /home/xxx/public_html/protected/vendors/Codeigniter/CI_Security.php(345): Security->xss_clean() #4 /home/xxx/public_html/protected/extensions/CmsInput.php(106): Security->xss_clean() #5 /home/xxx/public_html/protected/extensions/CmsInput.php(167): CmsInput->xssClean() #6 /home/xxx/public_html/protected/modules_core/post/controllers/PostController.php(41): CmsInput->stripClean() #7 /home/xxx/public_html/protected/vendors/yii/web/actions/CInlineAction.php(49): PostController->actionPost() #8 /home/xxx/public_html/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #9 /home/xxx/public_html/protected/vendors/yii/web/filters/CFilterChain.php(133): PostController->runAction() #10 /home/xxx/public_html/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #11 /home/xxx/public_html/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #12 /home/xxx/public_html/protected/vendors/yii/web/filters/CInlineFilter.php(58): PostController->filterAccessControl() #13 /home/xxx/public_html/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #14 /home/xxx/public_html/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #15 /home/xxx/public_html/protected/vendors/yii/web/CController.php(265): PostController->runActionWithFilters() #16 /home/xxx/public_html/protected/vendors/yii/web/CWebApplication.php(282): PostController->run() #17 /home/xxx/public_html/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #18 /home/xxx/public_html/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #19 /home/xxx/public_html/index.php(39): WebApplication->run() REQUEST_URI=/post/post/post

**Comment by WASasquatch** [comment]
http://wiki.vps.net/controlpanels/ispmanager/how-to-disable-open_basedir-for-one-website/
