### ISSUE TITLE
Updating just not Possible through Bugged YIIC

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#906]
I still don't get it, and would like answers:

<img src='http://img.prntscr.com/img?url=http://i.imgur.com/7D9qvGz.png' />

<img src='http://img.prntscr.com/img?url=http://i.imgur.com/SZnD2Rp.png' />

I ***NEVER*** can update HumHub on my server. How am I suppose to update HumHub if YIIC will not update it, and manually updating, YIIC will not update... ???

**Comment by luke-** [comment]
There was no database update between 0.11.0 and 0.11.1 - so this output ist OK

**Comment by WASasquatch** [comment]
Oh so it's just a source update? Alright. Maybe YIIC should make comments about these things? like "New source available" to tell the user it's not possible through YIIC.
