### ISSUE TITLE
HMarkdown.php Error

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#908]
![12323](https://cloud.githubusercontent.com/assets/7725575/7001657/60b80b1e-dc46-11e4-87d7-199669469e31.PNG)

Parse error: syntax error, unexpected '[' in 
/home/xxx/public_html/protected/libs/HMarkdown.php on line 109

**Comment by luke-** [comment]
We require at least PHP 5.4+

http://php.net/eol.php
