### ISSUE TITLE
Guest Mode Widgets

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#910]
Is there a specific reason the New People and New Spaces module is for Guests only? I mean I get the popularity concept, but for exploration it's inherently for members only...

**Comment by luke-** [comment]
These widgets are the same as on directory -> members -> new people.

You can also add them by your theme with pasting this lines
https://github.com/humhub/humhub/blob/master/protected/modules_core/dashboard/views/dashboard/index_guest.php#L16-L17

here:

https://github.com/humhub/humhub/blob/master/protected/modules_core/dashboard/views/dashboard/index.php#L23
