### ISSUE TITLE
Set user group_id by ldap

### ISSUE THREAD

**Issue by freshp** [humhub/humhub#912]
I want to map ldap groups to humhub user groups.

There is an issue in the UserIdentity->authenticate method. In this method one if condition call the HLdap::getInstance()->authenticate method. In the method handleLdapUser is called and the usermodel will be updated. But after all, the UserIdentity->onSuccessfulAuthenticate method will be called. This method get the usermodel, which was instanced before all modification. Now all updates will be overwritten.

**Comment by sascha-seyfert** [comment]
+1

**Comment by ychoucha** [comment]
+1

**Comment by luke-** [comment]
@freshp Thanks for the fix, I've moved the code a little bit deeper - Hope this also fixes the problem with less overhead :-)

**Comment by freshp** [comment]
thank you. i will wait for the next version.
