### ISSUE TITLE
Output error !

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#915]
https://community.humhub.com/dashboard/dashboard/stream/limit/-limit-/filters/-filter-/sort/-sort-/from/-from-/mode/normal

https://community.humhub.com/directory/directory/stream/limit/-limit-/filters/-filter-/sort/-sort-/from/-from-/mode/normal

![2](https://cloud.githubusercontent.com/assets/7725575/7024350/e3842fe2-dd44-11e4-9852-a1e08896f5e6.PNG)

**Comment by WASasquatch** [comment]
That is what the output should look like on a direct view.
