### ISSUE TITLE
Verified Users or Spaces

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#920]
Example
![323](https://cloud.githubusercontent.com/assets/7725575/7045328/ff354610-de05-11e4-8fdc-1fa7a32613f2.PNG)

**Comment by binarynos** [comment]
Yep... that would be an interesting feature...I don't know if this can be achieved already like this:
admins can create a group like verified and then assign verified users that group then use code to check if user belongs to that group and if yes then show some text on screen...

**Comment by 001101** [comment]
verified from what, who and for what purpose??

**Comment by Felli** [comment]
@001101 They are talking about the verified tick like how most social networks are doing now. Basically it is used to verify that person is a genuine person, business, company, & etc.

**Comment by 001101** [comment]
@Felli Yes I know, i also talking about that ;)

**Comment by nikolaaa4** [comment]
Any updates about this? Been 2 years.

**Comment by Felli** [comment]
@nikolaaa4 it's been marked an module idea, doesn't mean it'll make it on the to-do list as of yet. :+1:

**Comment by darien12** [comment]
Please make this! Would be sick!

**Comment by darien12** [comment]
Hey guys I've fiddled around and made a sort of temporary fix for this.

I'd added the following code to profileheader.php

` 
            <div class="img-profile-data">


                 <?php if (($user->id == 1) || ($user->id == 4) || ($user->id == 7)): { ?>  
                 
                 <h1><?= Html::encode($user->displayName); ?> <img src="VERIFIED ICON URL" width="22px" height="auto" style="margin-left: -3px; padding-bottom:1px;"></h1> 
                 
                 <?php } ?> 
                 
                 
                 
                 <?php else: { ?>  
                 
                 <h1><?= Html::encode($user->displayName); ?> </h1> 
                 
                 <?php } endif; ?> 

                <h2><?= Html::encode($user->profile->title); ?></h2>
            </div>

            `

Replace the userID's with the IDs of the verified users, and the VERIFIED ICON URL with the URL of your checkmark.

**Comment by edergo** [comment]
@darien12 it's perfect. I'm edited it for my version. It worked. Thanks. :) 👍 
[My edit](http://sosyal.iceplus.cloud/index.php?r=user%2Fprofile%2Fhome&uguid=99f51024-b471-4769-8437-37b31dfeb80c)

**Comment by MarkMarkovkin** [comment]
@darien12 I'm not very good at this, and because of this, I get an error when trying to enter the profile page "Oh ... It looks like you did something wrong. An internal server error occurred.".
How to fix it?
The code I added to the end of the script profileheader.php

**Comment by MarkMarkovkin** [comment]
@darien12 how to do it for spaces?

**Comment by helimansik** [comment]
It doesn't work for me, there is an error in the profile ...

**Comment by Ender951** [comment]
I think this would be a cool idea, and not only for verified badges... there could be one like if a user's account was disabled... it would show that in the form of a customizable badge... like an 'x' or a skull... something like that.

**Comment by haydenwalker980** [comment]
> It doesn't work for me, there is an error in the profile ...

Have you removed the extra \` at the end? @helimansik

**Comment by ArchBlood** [comment]
First of all, `containerProfileHeader.php` is now used, so if you're wanting to do something like this then do not use `profileHeader.php`

**Comment by haydenwalker980** [comment]
Okay, that didn't give me an error. But now the formatting's all messed up.

**Comment by ArchBlood** [comment]
@luke- I believe this can be closed finally.

https://github.com/GreenMeteor/verified
