### ISSUE TITLE
Mail versiyon: 0.5.13 Problem!!

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#922]
blank message problem
http://www.xxxxx.com/mail/mail/show/id/1/ajax/1?_=1428497320114

![233](https://cloud.githubusercontent.com/assets/7725575/7045461/f20ce35c-de06-11e4-8da1-2f0b18e1d435.PNG)

**Comment by luke-** [comment]
Can you please create this issue in

https://github.com/humhub/humhub-modules-mail/
