### ISSUE TITLE
post problem!!

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#923]
![adsiz](https://cloud.githubusercontent.com/assets/7725575/7046312/6b9ca2a6-de0d-11e4-8eda-bd9dc9b47cfc.png)

**Comment by andystrobel** [comment]
Can you please write some more details, that we are able to help you with that? When this happens? After commit, after file uploading? Stop everything working or is this behavior just for some seconds? Do you get an error in your browser console? Which browser you're using? ...

**Comment by WASasquatch** [comment]
Have you updated your PHP distribution yet?

**Comment by JeXawoW** [comment]
issue cookie
