### ISSUE TITLE
ldap user config : Status : Erreur! (Message: 0x5b (Connect error; (unknown error code)): 10.10.10.10:389)

### ISSUE THREAD

**Issue by ychoucha** [humhub/humhub#926]
Hello,

well i mtrynig to import contact from my active directory on humHub, but we can do that i have the error :

Status : Erreur! (Message: 0x5b (Connect error; (unknown error code)): 10.10.10.10:389)

so on my active directory i have this architecture : 

monDomaine.fr
     |-----> Dossier01 (Organisation Unit)
                     |-----> SousDossier02 (Organisation Unit)
                     |-----> SousDossier03 (Organisation Unit)
                     |-----> SousDossier04 (Organisation Unit)

So all my user is on evry "sousDossierXX"

my user to config ldap is on SousDossier04

This is my config on HumHUb :  
Hostname : 10.10.10.10
Port : 389
Encryption : TLS(aka SSLV2)
Username : CN=ldapUser,Ou=Dossier01,DC=monDomaine,DC=fr
Password : ******
Base DN : Ou= Dossier01,DC=monDomaine,DC=fr
Login Filter : (sAMAccountName=%s)
User Filter : (&(objectClass=person)(memberOf=OU=Dossier01,DC=monDomaine,DC=fr))
username Attribute : sAMAccountName

and with this config i have the error : 

Status : Erreur! (Message: 0x5b (Connect error; (unknown error code)): 10.10.10.10:389)

someon can help me to debug this and find where is the problem .

thanks

**Comment by ychoucha** [comment]
I found this in the log : 

Cound not bind to LDAP Server. Error: 0x5b (Connect error; (unknown error code)): 10.10.10.10:389 in /var/www/humhub/protected/libs/HLdap.php (76) in /var/www/humhub/protected/libs/HLdap.php (49) in /var/www/humhub/protected/modules_core/admin/controllers/SettingController.php (240) in /var/www/humhub/index.php (39) 


and this about the error 0x5b : 0x5B	91	LDAP_CONNECT_ERROR	Indicates that the LDAP client has lost either its connection or cannot establish a connection to the LDAP server.
here --> http://ldapwiki.willeke.com/wiki/LDAP%20Client%20Error%20And%20Result%20Codes



so what is wrong please

**Comment by ychoucha** [comment]
The good works for me is : 
Encryption : None
![humhub - mozilla firefox_2](https://cloud.githubusercontent.com/assets/301074/7087396/5a19c110-df8b-11e4-8bb3-7967fb37e044.jpg)

**Comment by R3m1n0X** [comment]
Reopen. Seems to be a bug and not fixed yet.

I have the same issue on current latest.
