### ISSUE TITLE
LikeController error!

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#929]
PHP Fatal error:  Call to a member function delete() on a non-object in /home/xxxxx/public_html/protected/modules_core/like/controllers/LikeController.php on line 74

**Comment by ASPIRINpp** [comment]
"Double dislike" - if dislike was already sent. For example: two tabs in browser and dislike was sent from both of them... I`m added if statement :)

**Comment by WASasquatch** [comment]
`empty()` should only be used on strings. Since we are dealing with objects, and variables, you should use `is_object()` or test `isset()` on a attribute.
