### ISSUE TITLE
Zend_Search_Lucene_Exception error!!

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub#930]
http://www.xxxx.com/search/index?mode=quick&keyword=-searchKeyword

![23](https://cloud.githubusercontent.com/assets/7725575/7082741/45840294-df61-11e4-8ddf-0f2fb49e9082.PNG)

Fatal error: Call to a member function removeReference() on a non-object in /home/xxxxx/public_html/protected/vendors/Zend/Search/Lucene/Proxy.php on line 63

**Comment by luke-** [comment]
Hmm you can try to rebuild your search index by

yiic search_rebuild
