### ISSUE TITLE
Ldap Mapping ldap information with contact  how add new info ?

### ISSUE THREAD

**Issue by Spartacus2018** [humhub/humhub#932]
Hello,

now i have my ldap connected on the humHub, so when a user connect the ldap info are added on my humhub :+1: 
Civilite (by the way is not the good mapping)
name
surname

how map other things please like phone number mail... ?

i m looking on the humHub code, i think u do the mapping in the files HLdap.php ?

**Comment by luke-** [comment]
Administration -> Settings -> User Profiles

**Comment by luke-** [comment]
Group Assignment: Administration -> Settings -> Groups

**Comment by ychoucha** [comment]
thanks,


but we don't have an group import on this page ?

u can create group manualy but u can't impot it from ldap ?

![humhub_import_ldap_group](https://cloud.githubusercontent.com/assets/301074/7088085/8a7ee834-df91-11e4-99cf-a231d64ab987.jpg)

**Comment by ychoucha** [comment]
u close the topic, but i m still not understand how group works on humHub

**Comment by luke-** [comment]
Edit the group:

![image](https://cloud.githubusercontent.com/assets/4736168/7146520/68628d08-e2f4-11e4-81af-e756c2c430b1.png)

**Comment by ychoucha** [comment]
ok thanks :)
