### ISSUE TITLE
humHub Internet explorer issue ?

### ISSUE THREAD

**Issue by ychoucha** [humhub/humhub#933]
Hello, 

when i lunch humHub from internet explrer i have this :  

![humhub_ie11_probleme](https://cloud.githubusercontent.com/assets/301074/7088490/51fad740-df94-11e4-8ebd-f7d124c417cb.jpg)

what is wrong please ?

**Comment by ychoucha** [comment]
i think is because i have activated a module !

**Comment by ychoucha** [comment]
not working on ie11

i remove all module, but i have the same issue in IE : 

i have this message with internet explporer debuger :   

SCRIPT5007: La valeur de la propriété « installUploader » est null ou non définie, pas un objet Function
Fichier : index.php, ligne : 953, colonne : 9


i have this on ie : 


![humhub_pb_ie11](https://cloud.githubusercontent.com/assets/301074/7111212/1a49a1ca-e1bd-11e4-823b-51c2ade6a194.jpg)


what i have to do please.

because my user have ie9 by default.

**Comment by ychoucha** [comment]
well i think now is an rights folder issue ?
all my humhub image have this : 
![humhub_image](https://cloud.githubusercontent.com/assets/301074/7111380/71c926a8-e1bf-11e4-8f56-604247ee2815.jpg)


for the rights i have tried : 

sudo chown www-data:www-data -R humhub/
sudo chmod 655 -R humhub/
sudo chmod 755 -R humhub/

sudo chmod 777 -R humhub/

What is wrong please ?

**Comment by JeXawoW** [comment]
@ychoucha  ie11 -  problem?
![1111](https://cloud.githubusercontent.com/assets/7725575/7111469/ae9c6c12-e1c8-11e4-9a17-069d86366dcb.PNG)

**Comment by ychoucha** [comment]
ok so maybe is an roghts problem on the server, but i give 777 to all humhub directory, no way that's nots working.

and don't understand what is wrong.

**Comment by ychoucha** [comment]
i don't know what i can do !!

i m stuck with this

can i reinstall humhub, and import my data, i make many conf, like ldap mapping user ...
:/

**Comment by luke-** [comment]
Does this problem also exists on our demo or on a fresh install?

**Comment by ychoucha** [comment]
With a frech install that's works : 
![ie1frechinstall](https://cloud.githubusercontent.com/assets/301074/7131451/d14210f2-e27f-11e4-9cea-25b6320c5be7.jpg)
![ie11frechinstall2](https://cloud.githubusercontent.com/assets/301074/7131450/d13e1826-e27f-11e4-8de9-4774161a205c.jpg)


so i have something broken on my first install, i have to reconfigure all :/

**Comment by ychoucha** [comment]
do u have a way to import data without manually reconfigure ?
please

**Comment by WASasquatch** [comment]
You uploaded in ASCII instead of Binary/Automatic for images and other
files.

**Comment by ychoucha** [comment]
@WASasquatch ?

How that, to install my humHub 
git clone https://github.com/humhub/humhub.git

after that i had right to chown www-data: www-data -R humhub/

after that i musing webinterface to upload all image i have, so at when moment i m using ASCII upload ?

**Comment by WASasquatch** [comment]
The web interface no doubt is not properly handling images. That look, specifically, is from broken images and files not handled in binary. I troubleshoot this daily with my hosted clients at our data center. 

Also did you chown to the web user and not just as current user?

**Comment by ychoucha** [comment]
i found It !!
the problem come from ie, u have an option than make humhub not good !

![ie_pb_humhub_01](https://cloud.githubusercontent.com/assets/301074/7196952/f5c49758-e4da-11e4-8a60-5264dd953f6f.jpg)
![ie_pb_humhub_02](https://cloud.githubusercontent.com/assets/301074/7196953/f5ca10ac-e4da-11e4-986d-577d11bf6d97.jpg)
![ie_pb_humhub_2](https://cloud.githubusercontent.com/assets/301074/7196954/f5cbafc0-e4da-11e4-8197-9795320fb168.jpg)
![ie_pb_humhub_03](https://cloud.githubusercontent.com/assets/301074/7196955/f5ce6ca6-e4da-11e4-936a-040797ef4485.jpg)

**Comment by WASasquatch** [comment]
Oh well ya. Compatibility mode is legacy support for IE8 and under
