### ISSUE TITLE
Spaces Dropdown Menu @ Smartphones ~320px (already solved, css-snipped)

### ISSUE THREAD

**Issue by gkaplick** [humhub/humhub#937]
CSS
@media screen and (max-width: 768px) #space-menu-dropdown { max-height: inherit;} 

... fixes a problem with the spaces-dropdown on smartphones :)
Screenshot: https://community.humhub.com/wall/perma/content/model/Post/id/1769

**Comment by OataO** [comment]
where cana i modify this ?

**Comment by WASasquatch** [comment]
I mentioned this before, it was fixed in 0.10.x, but seems another layer was added to the DIV which is not controlled by the height.

**Comment by OataO** [comment]
Is there a fix now ?

**Comment by gkaplick** [comment]
it should be placed at last to overwrite the original css... if it doesnt work and you dont know how to place it, just use:
@media screen and (max-width: 768px) #space-menu-dropdown { max-height: inherit!important;}
