### ISSUE TITLE
sort content by ascending or descending

### ISSUE THREAD

**Issue by renoa** [humhub/humhub#938]
the current options available in the drop down menu for posts are: 
-sort by publish date
-sort by edit date
but the default is already the publish date and is only useful if i chose "edit date" and wanted to go back. theres no way to sort by oldest posts first. 
is there a way to reverse the sorting so that it goes back and forth between oldest>newest and newest>oldest ?
(could've sworn i've posted this a few hours ago! if it was removed please tell me)

**Comment by luke-** [comment]
No, this sort order was never available

**Comment by renoa** [comment]
oh, i see. i see it's labeled as enhancement, does that mean you're considering adding it? 
if so, it would be great to have it either as a drop down item like it is now for profiles, or a fixed option, especially in the space settings (i'm hoping some spaces can be created for a story with chapters or comic pages, which could benefit from sorting oldest first so new readers always open the space to the first page) 
thank you for your hard work!
