### ISSUE TITLE
@Tagging people

### ISSUE THREAD

**Issue by lunascape-ourworld** [humhub/humhub#941]
Sometimes when you try to tag people, they don't always show up. This user in particular is having issues, aswell as myself.
![Image of Bug](https://lh5.googleusercontent.com/-7vTIl8WyCYY/VSh0CLeQgdI/AAAAAAAAFN4/h8U1oxpHeBQ/s0/2015-04-10_21-08-28.png)

**Comment by WASasquatch** [comment]
Additionally, the jQuery operator should check to see if the GUID/Tag behind the tag is valid. In case you delete characters, or add a question mark, or a period, or comma after a tagged person without a space. This will break the mention and cause it to show the GUID. Something to ensure it is valid before inserting would be nice. Else revert to plain text of what they were writing.

**Comment by luke-** [comment]
Maybe this was related to non latin characters? Does this problem still appears?
