### ISSUE TITLE
Uppload Video

### ISSUE THREAD

**Issue by ychoucha** [humhub/humhub#945]
hello,
well i m using humhub from my android (using dolphin browser)

but no way to upload an video

well when i try to upload video i have this error on the log :   

 error  Sun, 12 Apr 2015 12:44:39 +0200  exception.CHttpException.400
exception 'CHttpException' with message 'Le jeton CSRF n'a pu être vérifié.' in /var/www/html_prod/humhub/protected/vendors/yii/web/CHttpRequest.php:1247 Stack trace: #0 /var/www/html_prod/humhub/protected/vendors/yii/base/CComponent.php(561): CHttpRequest->validateCsrfToken(Object(CEvent)) #1 /var/www/html_prod/humhub/protected/vendors/yii/base/CApplication.php(207): CComponent->raiseEvent('onBeginRequest', Object(CEvent)) #2 /var/www/html_prod/humhub/protected/vendors/yii/base/CApplication.php(178): CApplication->onBeginRequest(Object(CEvent)) #3 /var/www/html_prod/humhub/index.php(39): CApplication->run() #4 {main} REQUEST_URI=/humhub/index.php?r=file/file/upload&objectModel=&objectId= HTTP_REFERER=https://192.168.50.40/humhub/index.php?r=dashboard/dashboard --- 

so what do u think please ?

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/939

**Comment by ychoucha** [comment]
To upload a video and show local video.

First the video need to be converted with vlc : using youtube HD format.

on humhub need to add this code on the files : protected/file/widgets/views/showFiles.php
on line 47 after the mp3 files detection : 
    
                <?php if ($file->getExtension() == "mp4" ) : ?>
                    
                    <?php $this->widget('ext.videoJs.videoJs', array(
                        'id' => $file->id,
                        'file' => $file->getUrl(),
                    )); ?>
                <?php endif;?>

and add the folder attached here on protected/extensions/

**Comment by aboro72** [comment]
Ich habe keine ahnung warum aber der findet die dateien nicht

**Comment by WASasquatch** [comment]
There are video players that play numerous formats, as well as free PHP libraries for server side conversion.

**Comment by plmorpheus** [comment]
ychoucha any update of your manual and module? On 0.20.1 it doesn't work..
