### ISSUE TITLE
! HTML, BBCode destroys user pages !

### ISSUE THREAD

**Issue by lunascape-ourworld** [humhub/humhub#948]
One of my users posted a BB Code or HTML code of some sort and it broke her whole feed and dashboard. I went on her account and could not load up her old feed. This is a very big issue and I dont want it to happen again. Do you have any idea what is causing it?

**Comment by luke-** [comment]
Can you please provide us the code or database (info@humhub.com) for investigation?

**Comment by k4r7u** [comment]
I had the same issue. Posting html code from Bandcamp.com to share an album destroys the dashboard. 
![image](https://cloud.githubusercontent.com/assets/8782287/8252058/152c7312-1682-11e5-88f9-f70efe9e7fd7.png)
![image](https://cloud.githubusercontent.com/assets/8782287/8252084/6e4e5636-1682-11e5-9613-615da5e8a621.png)
Is there a way to remove this post from the DB?
