### ISSUE TITLE
Create global processing modal 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#949]
Instead:
https://github.com/humhub/humhub/blob/master/protected/modules_core/admin/views/module/listOnline.php#L86-L113
https://github.com/humhub/humhub/blob/master/protected/modules_core/admin/views/module/list.php#L65-L92

Maybe additionally with changeable message.

**Comment by luke-** [comment]
Is it possible to pass the loading message via the a-link element? e.g.  data-processing-message ?

**Comment by WASasquatch** [comment]
+1
