### ISSUE TITLE
Cronjobs Not Running

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#951]
I have had the same cronjobs installed since I first added them, however, emails no longer come about my site (could be related to my other DB issues) but wondering why.

**Comment by luke-** [comment]
Maybe this was related to this bug.
https://github.com/humhub/humhub/commit/1fc36bc445b38bb8e9078d12a155f9f2e42e55cc

**Comment by luke-** [comment]
Did you see a status in Administration -> CronJobs?

**Comment by heikostueber** [comment]
Please check your PHP version. You must have PHP >= 5.4 !

**Comment by WASasquatch** [comment]
Nothing to PHP version. Script had nothing to return do to said commit fix.

**Comment by heikostueber** [comment]
In my case it was the php version. I changed it from 5.3 to 5.4 and now it's working with the current version.

I hope you find a solution for your case.

**Comment by WASasquatch** [comment]
Believe I'm running 5.6.x

**Comment by heikostueber** [comment]
I have not tested a newer version than 5.4, because the most software I need is running stable on 5.3 or 5.4. Have you any other issues with your php version ? Some people downgraded the php version minimum to 5.5, because they have problems with it. The most issues they have with the array-key and the json_decode(). Can you post the debug of the crons?

**Comment by WASasquatch** [comment]
The cronjobs works fine now, see the above linked commit by Luke.

Also there shouldn't be issues with HumHub and 5.6.x. See migrations:

http://php.net/manual/en/migration55.incompatible.php
http://php.net/manual/en/migration56.incompatible.php

**Comment by heikostueber** [comment]
Thats good.Thank you for the links.

**Comment by leopaula** [comment]
I updated to new humhub version 0.11.2 and cronjob does not run yet. My php is 5.4.38!

https://community.humhub.com/wall/perma/content/model/Post/id/2204

**Comment by bartez** [comment]
@leopaula you can try in console:
```
php /usr/home/bearsave/domains/bearsave.usermd.net/public_html/protected/yiic cron hourly >/dev/null 2>&1
```
Working for my server with PHP 5.4.41

**Comment by leopaula** [comment]
![cronjob_email](https://cloud.githubusercontent.com/assets/13361238/8800598/bb52310a-2fe6-11e5-95c8-9efc31bee5bc.png)

**Comment by leopaula** [comment]
Cronjobs works perfetcly now!

I sent that informations above to the server staff. He replied me:

We adjust your cron job to run with the version of PHP 5.4. Please make new check. Just remember that you can not perform actions as the root user in shared environments.

I hope this help someone!

Thank you guys!
