### ISSUE TITLE
Members lost

### ISSUE THREAD

**Issue by BartReymenants** [humhub/humhub#953]
I'm importing (insert query) members manualy from another system
When I look at the Directory/members url they don't show, only when they are manualy "updated" front-end without changing anything they show. 

it's here somewhere: /protected/modules_core/directory/controllers/DirectoryController.php
=> public function actionMembers()

**Comment by WASasquatch** [comment]
Have you tried `yiic search_rebuild ` and `yiic search_optimize ` ?

**Comment by BartReymenants** [comment]
Thx.. this works
I should investigate houw yii is working, cause it's not the way to go.. yiic doesn't alter the database, but the harddisk files.. it looks to me, there should be query optimization iso search_rebuild..

**Comment by WASasquatch** [comment]
It depends on your cache settings, HumHub does alter the DB but some files are loaded from cache, which you need to flush. As for the DB, things need to be synced and when importing, they are not.
