### ISSUE TITLE
["Urgent" Suggestion] Development Mode

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#956]
There needs to be some sort of development ASAP in a coming patch/new release. 

Just a basic setting in the admin control panel, like a check box "Development Mode" if checked, only a admin can view HumHub, if not, throw a exception. I'd make the patch myself but very afraid to use github, I am still not sure how to make a alteration to HumHub and push multiple files. I just know how to use the web interface. :(

But I'd I've done it with a simple "Admin post color" feature which is just a true/false int value. So I can do it if necessary, and someone wants to teach me how to make a pull request successful with multiple files. :)

``` php
if (Yii::app()->devMode && !Yii:app()->user->isAdmin()) {
    /* Using a unassigned status code for reference when a user reports this error by mistake
     * As using 503 when it can be caused by numerous system errors is not appropriate as others suggest */
    throw new CHttpException(418, 'Under Maintenance!'); 
}
```

Sorta clause in the main view. 

---

_Reason_: If I put up a splash page, it can be bypassed by typing `/dashboard` or by visiting links from email.

**Comment by WASasquatch** [comment]
https://github.com/WASasquatch/humhub-modules-devmode

**Comment by elbotho** [comment]
Isn't this the same thing as #777 that can be done by [your own plugin](https://github.com/WASasquatch/humhub-modules-devmode) @WASasquatch ?
(thanks by the way!)

Maybe you can close this one :)
