### ISSUE TITLE
security problem

### ISSUE THREAD

**Issue by ychoucha** [humhub/humhub#963]
![humhub_upluoad_directory](https://cloud.githubusercontent.com/assets/301074/7208128/aed265f0-e53e-11e4-99fc-7b61a2683077.jpg)
Hello,

i have a little problem with my humhub install :

i can acces at all uploaded files with this path  : 

https://192.168.50.40/humhub/uploads/profile_image/

**Comment by WASasquatch** [comment]
Not a security problem. They're binary files, not executable. Add .htaccess or to block it. Or use a index.php with a forward

```php
<?php $loc = !empty($_SERVER['HTTP_REFERER']) ? $loc = 'http://yourwebsite.com/' : $_SERVER['HTTP_REFERER']; header('Location: '.$loc);
```

**Comment by JeXawoW** [comment]
blank index.html 
![23](https://cloud.githubusercontent.com/assets/7725575/7216241/d01a589a-e600-11e4-855f-c0dc523eac85.PNG)

**Comment by luke-** [comment]
I'll close this issue because it's related to
