### ISSUE TITLE
Humhub session

### ISSUE THREAD

**Issue by karterpaul** [humhub/humhub#968]
how to use humhub session to custom pages

**Comment by WASasquatch** [comment]
Custom Pages doesn't yet have this feature but you are welcome to try custom pages extended

 https://github.com/WASasquatch/humhub-modules-custom-pages-extended

**Comment by luke-** [comment]
What do you mean? some sort of single sign on?

**Comment by WASasquatch** [comment]
I believe he means active user session on custom pages.

**Comment by karterpaul** [comment]
Thank you all for your reply
