### ISSUE TITLE
To enter in humhub online user or not. 

### ISSUE THREAD

**Issue by Stranikevg** [humhub/humhub#972]
As in many social networks.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/851

**Comment by WASasquatch** [comment]
For those wondering how to do this until it's part of HumHub, my HStats
class may have some useful functions/code to use ;)

https://github.com/WASasquatch/humhub-modules-custom-pages-extended/blob/master/docs/example.md

On Tue, Apr 21, 2015 at 7:58 AM, Lucas Bartholemy <notifications@github.com>
wrote:

> #851 <https://github.com/humhub/humhub/issues/851>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/972#issuecomment-94830731>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*
