### ISSUE TITLE
File settings are ignored (Maximum upload file size).

### ISSUE THREAD

**Issue by Vatarus** [humhub/humhub#975]
**Maximum upload file size settings: maxsize=1mb**
![file_01](https://cloud.githubusercontent.com/assets/3394915/7290753/85a826da-e9bf-11e4-89c1-00a785eeb1c1.png)
**Uploaded file: size=4mb**
![file_02](https://cloud.githubusercontent.com/assets/3394915/7290770/cc67dc82-e9bf-11e4-8e1f-d4e92584b45e.png)
**Post:**
![file_03](https://cloud.githubusercontent.com/assets/3394915/7290776/ed80d388-e9bf-11e4-9012-43fce7f7096e.png)

**Humhub version: 0.11.1**

**Comment by Stranikevg** [comment]
+1

**Comment by wOOx92** [comment]
+1

**Comment by Felli** [comment]
This can be changed via editing the PHP upload_max_filesize (This can be found via CPanel>Software>Select PHP Version>Switch To PHP Extensions for those using CPanel.)

**Comment by wOOx92** [comment]
@Felli That doesn't solve the problem, like the title says, humhub is ignoring these settings.

**Comment by Felli** [comment]
@wOOx92 Like I said editing the PHP version is needed to increase the upload size. Humhub checks for the default file upload size and sets it to that.
![screenshot_1](https://cloud.githubusercontent.com/assets/2011633/13038178/14b3d428-d344-11e5-95df-a4cf2c2a01b5.png)

**Comment by wOOx92** [comment]
@Felli please read the issue description carefully. It's possible to upload a 4 MB file, while the PHP says maximum is 2 MB AND humhub setting is set to 1 MB.

is: 4 MB file can be uploaded, although it's maximum is set to 2 MB (1 MB in humhub) and the file appears as "0 Byte" file.
shall: 4 MB file can not be uploaded, because the maximum filesize is exceeded.

**Comment by kahsky** [comment]
I you can set it manually under /protected/config/dynamic.php

      'file' =>
      array (
        '**maxFileSize**' => '10048576',
        'maxPreviewImageWidth' => '200',
        'maxPreviewImageHeight' => '200',
        'hideImageFileInfo' => '0',
      ),

**Comment by simonfranzen** [comment]
I am also having the problems, but only for profiles and Avatars.

- PHP 7.0
- php.ini max file size incraesed
- under settings increased as well

**Comment by arifefa** [comment]
how if i dont have access in php.ini . how to solve it

**Comment by funkycram** [comment]
@luke- I think this issue is solved (tested also with profile picture as mentioned on https://github.com/humhub/humhub/issues/975#issuecomment-375282257)

**Comment by luke-** [comment]
@funkycram Thanks, I'll close it.
