### ISSUE TITLE
Not all CronJobs are running

### ISSUE THREAD

**Issue by 8l4ckSh33p** [humhub/humhub#978]
First, sorry for my bad english. German I can do better;)

I can not run with my provider shell scripts only one CGI-bridge via PHP. It will look like this:

File cron_daily.phpx
```php
<?php

 exec("/usr/bin/php /www/htdocs/w0124xxx/social2/protected/yiic cron daily >/dev/null 2>&1", $out, $result);
 echo "Returncode: " .$result ."<br>";
 echo "Ausgabe des Scripts: " ."<br>";
 echo "<pre>"; print_r($out);

 ?>
```

and

File cron_hourly.phpx
```php
<?php

 exec("/usr/bin/php /www/htdocs/w0124xxx/social2/protected/yiic cron hourly >/dev/null 2>&1", $out, $result);
 echo "Returncode: " .$result ."<br>";
 echo "Ausgabe des Scripts: " ."<br>";
 echo "<pre>"; print_r($out);

 ?>
```

Hourly we do not run but every day is wonderful. The Webcron is called when all two minutes. Why is that?

i use PHP 5.5.22 on all-inkl.com with HumHub 0.11.1

**Comment by 8l4ckSh33p** [comment]
It works! The Script has a Permissions-Fail ;)

**Comment by HimBerty** [comment]
Hi!

Ich habe bei All-Inkl das gleiche Problem. Wie hast Du denn den Rechte-Fehler behoben?

LG

**Comment by 8l4ckSh33p** [comment]
@HimBerty see this https://community.humhub.com/wall/perma/content/model/Post/id/1880 and this http://liebig-project.com/humhub-richtig-auf-all-inkl-com-installieren/
