### ISSUE TITLE
After checking Self-Test and Update: Fatal Error takes down HumHub

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#989]
After I checked Self-Test and Update to see if there were migrations, upon returning to the dashboard I was greeted with:

`Parse error: syntax error, unexpected '<' in /home/****/***/***/public_shtml/protected/runtime/cache_autostart.php on line 78`

Error takes down all of HumHub.

```php
?>	<?php

	Yii::app()->moduleManager->register(array(
		'id' => 'devmode',
		'class' => 'application.modules.devmode.DevModeModule',
		'import' => array(
			'application.modules.devmode.*',
		),
		// Events to Catch 
		'events' => array(
			array('class' => 'AdminMenuWidget', 'event' => 'onInit', 'callback' => array('DevModeEvents', 'onAdminMenuInit')),
			array('class' => 'DashboardSidebarWidget', 'event' => 'onInit', 'callback' => array('DevModeModule', 'onSidebarInit')),
			),
	));
	

<?php 
Yii::app()->moduleManager->register(array(
```

Seems I forgot to close the PHP tag, though I figured that would be ok for the method but didn't like the entire file, and not it's code was rendered. Seems like globally removing PHP tags and only having the one open and close in the file would be prudent. Some developers don't add closing tags to applications anymore. 

@luke- Where is this file rendering? I'd like to optimize it for this redundant raw handling.

**Comment by luke-** [comment]
Make sure the autostart.php of your module ''devmode'' closes with ?>

Just remove the file  protected/runtime/cache_autostart.php and try again

**Comment by luke-** [comment]
cache_autostart.php  - combines all module's autostart.php files for faster loading

**Comment by WASasquatch** [comment]
Well, what I mean is opening a closing the PHP tag token creates a bit of overhead... and eventually down the road if you have 20-30 modules (or even more! who knows), there is a second or two of delay caused by the tags opening and closing. You can open the files and omit the PHP tokens and render them without the tokens in a already established PHP mode.

Just seems like since you are using multiple files, it'd be appropriate to run as one file. 

```php
$str = '<?php echo \'Hello World!\'; ?>';

eval(stripTokens($str));

function stripTokens($str) {
   if(!empty($str)) {
      $exp = array(
         '/'.preg_quote('<?php').'/i', 
         '/'.preg_quote('<?').'/i', 
         '/'.preg_quote('<?=').'/i', 
         '/'.preg_quote('?>').'/i'
      );
      return preg_replace($exp, '', $str);
   }
}
```
