### ISSUE TITLE
Global Hook system - Cannot Finish DevMode Module

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#991]
We need a global hook system for modules, otherwise they cannot have appropriate control of the system, as according to my topic here regarding the Development Mode, which cannot be a module, and must be part of the system, and called globally through `WebApplication` or similar.

 http://www.yiiframework.com/forum/index.php/topic/63434-having-trouble-understanding-events/page__gopid__279683#entry279683

**Comment by luke-** [comment]
Can I close that?

**Comment by WASasquatch** [comment]
Oh yep.
