### ISSUE TITLE
CDbConnection is unable to find PDO class "PDO". Make sure PDO is installed correctly.

### ISSUE THREAD

**Issue by vishnu477** [humhub/humhub#995]
CDbConnection is unable to find PDO class "PDO". Make sure PDO is installed correctly.

**Comment by WASasquatch** [comment]
Install PDO?

**Comment by vishnu477** [comment]
how to install can u explain me i have a shared linux hosting

**Comment by WASasquatch** [comment]
You will have to ask your hosting provider.

On Wed, Apr 29, 2015 at 11:55 AM, vishnu477 <notifications@github.com>
wrote:

> how to install can u explain me i have a shared linux hosting
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/995#issuecomment-97539524>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*
