### ISSUE TITLE
photo album

### ISSUE THREAD

**Issue by Themaster07** [humhub/humhub#996]
could add a module to photo album ?

**Comment by WASasquatch** [comment]
https://github.com/rifaideen/humhub-modules-album

**Comment by Themaster07** [comment]
@WASasquatch thanks friend but get error (Parse error: syntax error, unexpected '[', expecting ')' in /home/facedoog/public_html/protected/modules/humhub-modules-album-master/autostart.php on line 3)

**Comment by WASasquatch** [comment]
You need PHP 5.4 for HumHub.
