### ISSUE TITLE
Front End Coding Patterns

### ISSUE THREAD

**Issue by sagevann** [humhub/humhub#997]
I am noticing several anti-patterns being overused in the frontend coding of the core modules of humhub and would like to start a discussion about this.

Here are the three main issues I see:
## 1. Excessive user of `$this->style->of->value->input->in->views`

This makes it hard to read and edit the html in the views without trying to parse a load of php syntax. It is an unnecessary burden that can be cleaned up quite simply by doing the following 

At the top of a view file, create a manifest like so:

``` php
<?php
    //values to replace in view
    $name = $user->displayName;
    $title = $user->profile->title;

   //ternary to choose the correct text for my button if logged in
   $buttonText = $isProfileOwner ? 'Your page rocks!' : 'This is an ok page';

?>

<h1><?= $name ?></h1>
<h2><?= $title ?></h1>
<button><?= $buttonText ?></button>
```

There are cons to this way of doing things, but it makes the views so much easier to work with on many levels. As an alternative, exposing a cleaner way to access all the data from the view scope would also be an option.
## 2. Repeating Yourself, Repeating Yourself

In some views there is direct duplication of code in the same view. This is challenging on many fronts, and should be eliminated at all costs. Here's an example from `/protected/modules_core/user/widgets/views/profileHeader.php`

The header image and the profile/user image are roughly the same markup and are typed in explicitly as  giant mess of HTML and PHP, twice. Each contains logic that asks if the user is logged in as themselves, and displays the buttons for uploading a picture. This required roughly 150sloc to render two image blocks. Much of it is almost entirely cut and paste.

I would recommend that we find code like this and create 'partials' that can be rendered as follows:

``` php
     <div class="image-upload-container profile-user-photo-container">
         <!-- Render a header image uploader -->
         <?php $this->render('partials/profileImageUploadTemplate', array('type' => 'header') ); ?>
          <!-- Render a profile image uploader -->
         <?php $this->render('partials/profileImageUploadTemplate', array('type' => 'profile') ); ?>
    </div>
```
## 3. Logic in views

As was explained in point 2 above there seems to be excessive logic within the view files. I'm not 100% opposed to some logic in a view, particularly if it's a simple if / else logic, but the extent to which this is littered in the views particularly around the `$isProfileOwner` construct poses problems.

If there are so many different places that require custom dom elements to be injected based on if a user `$isProfileOwner` I would recommend that we look at creating moving all the 'owner' view code into a sub folder and having a high level helper method to inject said custom dom elements. It could be another flavor of render partial maybe something like this:

``` php
<?php $this->renderIfOwner(  'partial/path/goes/here' ); ?>
```

What would that do?

``` php
function renderIfOwner( $path ){
  $path = $isProfileOwner ? '/owner/.$path : $path;
  $this->render($path); 
 // I realize this wouldn't work due to scoping, but as psuedocode it illustrates the intent
}
```

This is an oversimplification and likely has syntax / variable scope errors but I assume you can see the idea.

If anyone is interested / willing to support me in working together on this I believe it would be a great boon to this project and the community springing up around the humhub software.

**Comment by WASasquatch** [comment]
Definitely like a lot of points here, but I do have some gripe. 

1) As far as I am aware `<?=` echoing is considered voodoo in extensive applications and been debated on removal in every version since 5.3. 
2) While organizing logic is good, you have to keep in mind profiling and the extent the system takes to render a view. I've noticed HumHub speed slowing patch by patch, and already is a incredibly slow system by comparison of any social network platform currently out there.
3) 2 lines of code is hardly an excuse to make a function. 

I do have agree that there should be more level of organization within some extensive views, for example your idea about large HTML blocks and logic like in the `profileHeader.php` view.

**Comment by sagevann** [comment]
To point 3) *'2 lines of code is hardly and excuse to make a function'* this would be true if the pattern of  ```php 
if( !$isProfileOwner ){ 
. . . do stuff for owners . . .
} else {
. . . do stuff for everyone else . . .
}
``` 

were not so pervasive. My recommendation is not to abstract out the `$isOwnerProfile` bit, but to adopt a pattern that parks the additional lines of code BEYOND the if into a logical space in the module/view hierarchy.

So, as I envision it, there would be an addition folder somewhere in the directory such that a module/views directory would be structured like below. In the example below we assume that the profileHeader view and the userTags view require unique markup or logic in comparison to the same views for non-owners.

```
```
├── user/
│   ├── widgets/
│   │   ├── views/
│   │   │   ├── profileHeader.php
│   │   │   ├── userTags.php
│   │   │   ├── owner/
│   │   │   │   ├── profileHeader.php
│   │   │   │   ├── userTags.php
│   │   │   │   ├── . . . .
```

**Comment by WASasquatch** [comment]
It's a fair enough idea, but the point of dynamic content is if/else logic to condense files. This creates more files to redundantly edit for a smile layout edit or something. It makes sense when categorizes things, like this "owner" section, but at the time, it's not used for much but buttons and profile owner queries like editing links. These things I find very much should be compacted into single views for ease of editing. 

I already have major problems with a lot of veiws which could be condensed for profiling of the overall system, let alone not creating a pre-build theme system. For example: When I run HumHub for the first time, ***all*** views should be reproduced in the `themes/HumHub/views/` folders to ***force*** users to edit those views. That way, if HumHub encounters a error in a view, it can fall back on a unedited view in the system modules. This also removes any confusion of view hierarchy for new users.

**Comment by sagevann** [comment]
@WASasquatch the plethora of nested files is a 'con' that was adopted with the Yii framework. Unless someone is going to change the framework, that's simply how it's going to be. Adding one more repeatable pattern to the humhub system that removes code duplication in views seems like a price I'd be willing to pay to know that I didn't have so many `if/else` clauses littering my templates.

**Comment by WASasquatch** [comment]
Well templates are inherently based on if/else clauses. xD

**Comment by sagevann** [comment]
It's not that you're 'wrong', it's that you're propagating a design pattern that makes it harder to reason about, write, and maintain your code. View code should be as close as possible to your final markup ( unless you're using a synthetic templating language like haml ). Here's a direct quote from the Yii documentation about MVC best practices:

>**Widgets:** if a lot of logic is needed to present a partial view, the partial view can be turned into a widget whose class file is the best place to contain this logic. For widgets that generate a lot of HTML markup, it is best to use view files specific to the widget to contain the markup.

> [Yii Best Practices ](http://www.yiiframework.com/doc/guide/1.1/en/basics.best-practices)
>

**Comment by WASasquatch** [comment]
I see where you are coming from, but you are sort of omitting the first use

>-should mainly contain presentational code, such as HTML, and simple PHP code to traverse, format and render data;

Which indicates just what HumHub has been doing so far. Rendering data would include a clauses for differential HTML between something like a owner or not.

However, for extensive use it should be a new file like you are saying, I do agree.

**Comment by andystrobel** [comment]
Hey guys, this is a lively discussion here :wink: 

I don't like to comment each point, but after reading everything I have some general thoughts.

@sagevann:
Thank you so much for analyzing the code and your feedback, I know that our view logic / patterns need definitly some imrovements.

**To point 1:**
I really like this idea. I think it's not really necessary but yes, it will make the views so much easier to read and work on. It will be also a great benefit for the auto-complete function in some simple but great editors like Sublime etc.

**To point 2:**
I know this is an unpleasant issue (specially the profieHeader topic). I also like the idea and I think that the rendering of some more partial views, will not slow down the whole system so much. This "speed" issue, @WASasquatch is talking about, depends on something else (like the count of simultaneously loading files or some unperformant Ajax calls -> we currently working on this)

**To point 3:**
I totally agree with @sagevann. We've chose Yii as framework for some good reasons, so now we should follow the patterns coming with Yii and use the best practice methods, as well.

@WASasquatch: I really like the idea, that HumHub push all views to the the theme folder. That would be very helpful for new theme creations and will certainly reduce this kind of questions a lot. But sometimes it's enough to edit the css and duplicate only some views for your new theme. So now, when we update the views at the core files you just have to modify these files at your theme. But if all views are duplicated by default. A theme developer always have to modify his theme after we did an update or he is not able to see the new changes we made. So with this way we will maybe reduce the questions for theme creation, but we will also increase the questions when we update views. (Like: "I don't see this new feature, what I have to do?").

**Comment by WASasquatch** [comment]
That's true though we could have a `theme.json` to declare compatibilities just like mods. I use this in my themes because theme info and compatibility should be there just like modules as views are part of modules and contain logic.

**Comment by sagevann** [comment]
@andystrobel FWIW, I am prepping a branch locally that will abstract all the image upload html + js + php into a global widget. To use it, you'll go into your module and subclass the widget and add on the necessary bits. For example, paths to the actions for upload, crop, delete, custom css IDs or classes for multiple editable images on a page. 

Should be done by next week and I'll make a pull request.

**Comment by WASasquatch** [comment]
Sounds good, sagevann, I'd pop it in here: https://community.humhub.com/s/96d933cd-e5a9-4314-8f8f-564f2dd81cf6/home I guess that's the place to discuss pull requests before making a pull request... though I'm unsure why. A pull request is a Discussion Topic just for that very reason. Little redundant.

**Comment by sagevann** [comment]
An example of a refactor that I did so you can see how different it is when views just render things, in each example below start a watch, and see how long it takes to understand what the view does:

### Original ```space/widgets/views/membershipButton.php```

```php
<?php
if ($membership === null) {
    if ($space->canJoin()) {
        if ($space->join_policy == Space::JOIN_POLICY_APPLICATION) {
            echo HHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', 'Request membership'), $space->createUrl('//space/space/requestMembershipForm'), array('class' => 'btn btn-secondary', 'data-toggle' => 'modal', 'data-target' => '#globalModal'));
        } else {
            echo HHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', 'Become member'), $space->createUrl('//space/space/requestMembership'), array('class' => 'btn btn-secondary'));
        }
    }
} elseif ($membership->status == SpaceMembership::STATUS_INVITED) {
    echo HHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', 'Accept Invite'), $space->createUrl('//space/space/inviteAccept'), array('class' => 'btn btn-secondary'));
    echo HHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', 'Deny Invite'), $space->createUrl('//space/space/revokeMembership'), array('class' => 'btn btn-secondary'));
} elseif ($membership->status == SpaceMembership::STATUS_APPLICANT) {
    echo HHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', 'Cancel pending membership application'), $space->createUrl('//space/space/revokeMembership'), array('class' => 'btn btn-secondary'));
} else {
    if (!$space->isSpaceOwner()) {
        echo CHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', "Cancel membership"), $this->createUrl('//space/space/revokeMembership', array('sguid' => $space->guid)), array('class' => 'btn btn-danger'));
    }
}
```

### Refactored  ```space/widgets/views/membershipButton.php``` 

```php
<?php
//we either have one button or multiple buttons ( usually 2)
//we should simply iterate over our btns array and render
//links for each
foreach( $btns as $btn){
    echo HHtml::link( $btn["text"], $btn["url"], $btn["attrs"]);
}   
?>
```

So where'd all those if statements go? Where they belong, back in the widget. 

### So then my widget code just got more complicated?
#### Yes. It's supposed to be more complicated than your view. However, it's also more readable, logical, and consistent. There's no helpers trying to render anything to the dom. There's no duplicated code in the form of helpers writing, effectively, the exact same thing to the dom with only minor changes. It makes the view simply a template, into which you inject data. 

So, here's the new ```space/widgets/SpaceMembershipButtonWidget.php``` w/o the function header

```php

class SpaceMembershipButtonWidget extends HWidget
{

    public $space;

    public function run()
    {
        $membership = $this->space->getMembership();
        $space = $this->space;

        //set up the default button
        $btn = array( );
        $btnB = array( );

		if ($membership === null) {
		    if ($space->canJoin()) {
		        if ($space->join_policy == Space::JOIN_POLICY_APPLICATION) {
		            $btn["url"]		= $this->space->createUrl('//space/space/requestMembershipForm');
		            $btn["text"] 	= 'Apply to Join';
		            $btn["attrs"]   = array('class' => 'btn btn-secondary', 'data-toggle' => 'modal', 'data-target' => '#globalModal');
		            		
		            // echo HHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', 'Request membership'), $space->createUrl('//space/space/requestMembershipForm'), array('class' => 'btn btn-secondary', 'data-toggle' => 'modal', 'data-target' => '#globalModal'));
       
		        } else {
		        	//free to join
		            $btn["url"]   	= $this->space->createUrl('//space/space/requestMembership');
		            $btn["text"] 	= 'Join Space';
		            $btn["attrs"]   = array('class' => 'btn btn-secondary');
		            		
		           // echo HHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', 'Become member'), $space->createUrl('//space/space/requestMembership'), array('class' => 'btn btn-secondary'));
		        }
		    }
		} elseif ($membership->status == SpaceMembership::STATUS_INVITED) {
			
			// set up the accept invite button
			$btn["url"]   	= $this->space->createUrl('//space/space/inviteAccept');
	        $btn["text"] 	= 'Accept Invite';
	        $btn["attrs"]   =  array('class' => 'btn btn-primary');
	        //echo HHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', 'Accept Invite'), $space->createUrl('//space/space/inviteAccept'), array('class' => 'btn btn-secondary'));
		   
		    // set up the decline invit button
		    // set up the accept invite button
			$btnB["url"]   	= $this->space->createUrl('//space/space/revokeMembership');
	        $btnB["text"] 	= 'Decline Invite';
	        $btnB["attrs"]   =  array('class' => 'btn btn-secondary');
		    //echo HHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', 'Deny Invite'), $space->createUrl('//space/space/revokeMembership'), array('class' => 'btn btn-secondary'));
		} elseif ($membership->status == SpaceMembership::STATUS_APPLICANT) { 
		    // set up the cancel request button
			$btn["url"]   	= $this->space->createUrl('//space/space/revokeMembership');
	        $btn["text"] 	= 'Cancel my request to join this space';
	        $btn["attrs"]   =  array('class' => 'btn btn-secondary full-width');
	       
		    //echo HHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', 'Cancel pending membership application'), $space->createUrl('//space/space/revokeMembership'), array('class' => 'btn btn-secondary'));
		} else {
		    if (!$space->isSpaceOwner()) {
		   		// set up the accept invite button
				$btn["url"]   	= $this->space->createUrl('//space/space/revokeMembership', array('tguid' => $space->guid));
	        	$btn["text"] 	= 'Leave Space';
	        	$btn["attrs"]   = array('class' => 'btn btn-danger');
	       
		        //echo CHtml::link(Yii::t('SpaceModule.widgets_views_membershipButton', "Cancel membership"), $this->createUrl('//space/space/revokeMembership', array('tguid' => $space->guid)), array('class' => 'btn btn-danger'));
		    } else {
		    	//is the spaceowner don't render anything
		    	return;
		    }
		} 

		//we pass a single array to our view and iterate over it there
		//we must assure that we don't send empty arrays or it will throw 
		//an exception when it tries to access keys that are not available
		$btns = ( count($btnB) > 0 ) ? array( $btn, $btnB ) : array( $btn );

        $this->render('membershipButton', array( 'btns' => $btns ));
    }

}
```

There's still some 'knowledge of the data' embedded in the view because I'm hard coding the key names in the array, but replacing those gets us into meta-programming territory, which is usually a full stop for anyone who is not a guru in their language of choice.

**Comment by WASasquatch** [comment]
I usually hate long drawn out arrays, but I like this a lot. Props to the efforts @sagevann

**Comment by sagevann** [comment]
@WASasquatch I'm not sure I understand what you're saying.

**Comment by WASasquatch** [comment]
I don't long drawn own arrays personally but this makes sense. Is all I'm saying.

**Comment by tobciu** [comment]
@sagevann why you use some 'complicated' logic with `btn` and `btnB` and not something like `array_push`?

Example (not tested):
```php
class SpaceMembershipButtonWidget extends HWidget
{
    public $space;

    public function run()
    {
        $membership = $this->space->getMembership();
        $space = $this->space;

        //set up the default button
        $btns = array( );

        if ($membership === null) {
            if ($space->canJoin()) {
                if ($space->join_policy == Space::JOIN_POLICY_APPLICATION) {
                    array_push($btns, array(
                        'url' => $this->space->createUrl('//space/space/requestMembershipForm'),
                        'text' => 'Apply to Join',
                        'attrs' => array('class' => 'btn btn-secondary', 'data-toggle' => 'modal', 'data-target' => '#globalModal')
                    ));
                } else {
                    //free to join
                    array_push($btns, array(
                        'url' => $this->space->createUrl('//space/space/requestMembership'),
                        'text' => 'Join Space',
                        'attrs' => array('class' => 'btn btn-secondary')
                    ));
                }
            }
        } 
        if ($membership->status == SpaceMembership::STATUS_INVITED) {
            // set up the accept invite button
            array_push($btns, array(
                'url' => $this->space->createUrl('//space/space/inviteAccept'),
                'text' => 'Accept Invite',
                'attrs' => array('class' => 'btn btn-secondary')
            ));

            // set up the decline invit button
            array_push($btns, array(
                'url' => $this->space->createUrl('//space/space/revokeMembership'),
                'text' => 'Decline Invite',
                'attrs' => array('class' => 'btn btn-secondary')
            ));
        } 
        if ($membership->status == SpaceMembership::STATUS_APPLICANT) { 
            // set up the cancel request button
            array_push($btns, array(
                'url' => $this->space->createUrl('//space/space/revokeMembership'),
                'text' => 'Cancel my request to join this space',
                'attrs' => array('class' => 'btn btn-secondary full-width')
            ));
        } 
        if ($membership->status == SpaceMembership::STATUS_MEMBER && !$space->isSpaceOwner()) {
            // set up the accept invite button
            array_push($btns, array(
                'url' => $this->space->createUrl('//space/space/revokeMembership', array('tguid' => $space->guid)),
                'text' => 'Leave Space',
                'attrs' => array('class' => 'btn btn-danger')
            ));
        } 

        $this->render('membershipButton', array( 'btns' => $btns ));
    }
}
```

**Comment by sagevann** [comment]
@tobciu when ( and if I get time ) I make the formal pull request for this I will update to do that. It's what I had intended to do, but needless to say when you're writing code at 00:00 on a Sunday after a 60 hour week you don't always make the best choices.

Also, I'm from the ruby world, so many of the idioms are different and I'm still getting used to the php syntax

**Comment by tobciu** [comment]
@sagevann ok :-) when i'm at this situation, i 'always' make the best choices ;-D *irony off
and i know your problems, i'm from the java world ;-)

**Comment by vasusesh** [comment]
Hi guys, Can someone help me with my problem? I am trying to create a web application. I want to add some content to the dashboard. How can I do that? Like, which code should I edit in the humhub folders in order to post content on dashboard? Kindly help me! It is very important for me to figure this out ASAP. Thanks in advance. I'm a beginner- just trying to get help.

**Comment by WASasquatch** [comment]
Read Yii Documentation.
